Repository n8n-io/n8n, pull requests merged in 2022-12, with the labels that each got.

#4712 test: E2E NDV
  cypress/e2e/5-ndv.cy.ts
  cypress/fixtures/NDV-test-select-input.json
  cypress/pages/index.ts
  cypress/pages/ndv.ts
  cypress/pages/workflow.ts
  cypress/pages/workflows.ts
  packages/editor-ui/src/components/CanvasControls.vue
  packages/editor-ui/src/components/CopyInput.vue
  packages/editor-ui/src/components/InputPanel.vue
  packages/editor-ui/src/components/Node.vue
  packages/editor-ui/src/components/NodeDetailsView.vue
  packages/editor-ui/src/components/NodeExecuteButton.vue
  packages/editor-ui/src/components/OutputPanel.vue
  packages/editor-ui/src/components/RunData.vue
Labels: ui, n8n team

#4702 fix(editor): JSON view values can be mapped like keys
  packages/editor-ui/src/components/RunData.vue
  packages/editor-ui/src/components/RunDataJson.vue
Labels: ui, n8n team

#4778 test(editor): Intercept credentials save and test request and wait for them in e2e test
  cypress/pages/modals/credentials-modal.ts
Labels: n8n team

#4631 feat(editor): Overhaul expression editor modal
  cypress/e2e/9-expression-editor-modal.cy.ts
  cypress/pages/workflow.ts
  docker/images/n8n-custom/Dockerfile
  package.json
  packages/design-system/src/css/_tokens.scss
  packages/editor-ui/.eslintrc.js
  packages/editor-ui/package.json
  packages/editor-ui/src/components/ExpressionEdit.vue
  packages/editor-ui/src/components/ExpressionEditorModal/ExpressionModalInput.vue
  packages/editor-ui/src/components/ExpressionEditorModal/ExpressionModalOutput.vue
  packages/editor-ui/src/components/ExpressionEditorModal/braceHandler.ts
  packages/editor-ui/src/components/ExpressionEditorModal/colorDecorations.ts
  packages/editor-ui/src/components/ExpressionEditorModal/n8nLanguagePack/index.cjs
  packages/editor-ui/src/components/ExpressionEditorModal/n8nLanguagePack/index.d.cts
  packages/editor-ui/src/components/ExpressionEditorModal/n8nLanguagePack/index.d.ts
  packages/editor-ui/src/components/ExpressionEditorModal/n8nLanguagePack/index.js
  packages/editor-ui/src/components/ExpressionEditorModal/n8nLanguageSupport.ts
  packages/editor-ui/src/components/ExpressionEditorModal/resolvable.completions.ts
  packages/editor-ui/src/components/ExpressionEditorModal/theme.ts
  packages/editor-ui/src/components/ExpressionEditorModal/types.ts
  packages/editor-ui/src/components/ExpressionInput.vue
  packages/editor-ui/src/components/ParameterInput.vue
  packages/editor-ui/src/components/ParameterInputWrapper.vue
  packages/editor-ui/src/components/VariableSelector.vue
  packages/editor-ui/src/components/VariableSelectorItem.vue
  packages/editor-ui/src/constants.ts
  packages/editor-ui/src/mixins/workflowHelpers.ts
  packages/editor-ui/src/plugins/i18n/locales/en.json
  packages/editor-ui/tslint.json
  packages/workflow/src/Expression.ts
  packages/workflow/src/WorkflowDataProxy.ts
  patches/quill@2.0.0-dev.4.patch
  pnpm-lock.yaml
Labels: core, ui, n8n team

#4777 fix(core): OAuth2 scope saved to DB fix
  packages/cli/src/credentials/oauth2Credential.api.ts
Labels: n8n team, node/issue

#4785 fix(Pipedrive Node): Resolve properties not working
  packages/nodes-base/nodes/Pipedrive/GenericFunctions.ts
  packages/nodes-base/nodes/Pipedrive/Pipedrive.node.ts
Labels: n8n team, node/issue

#4791 feat(Facebook Graph API Node): Update to support api version 15
  packages/nodes-base/nodes/Facebook/FacebookGraphApi.node.ts
Labels: node/improvement, n8n team

#4790 feat(Postmark Trigger Node): Update credentials so they can be used in the HTTP Request Node
  packages/nodes-base/credentials/PostmarkApi.credentials.ts
  packages/nodes-base/nodes/Postmark/GenericFunctions.ts
Labels: node/improvement, community

#4699 feat(editor): LDAP settings front-end updates
  packages/design-system/src/components/N8nFormInputs/FormInputs.vue
  packages/editor-ui/src/plugins/i18n/locales/en.json
  packages/editor-ui/src/views/SettingsLdapView.vue
Labels: ui, n8n team

#4782 fix: Credential overwrites should take precedence over credential default values
  packages/cli/src/CredentialsHelper.ts
  packages/cli/src/CredentialsOverwrites.ts
Labels: core, n8n team

#4800 ci: Add run name and start url for e2e tests and docker nighly command (no-changelog)
  .github/workflows/docker-images-nightly.yml
  .github/workflows/e2e-tests.yml
Labels: n8n team

#4808 fix(core): Fix linter error
  packages/nodes-base/nodes/Aws/AwsSnsTrigger.node.ts
  packages/nodes-base/nodes/Google/Sheet/v2/helpers/GoogleSheet.ts
Labels: n8n team, node/linting

#4809 fix(Execute Workflow Node): Update Execute Workflow node info notice text
  packages/nodes-base/nodes/ExecuteWorkflow/ExecuteWorkflow.node.ts
Labels: node/improvement, n8n team

#4636 docs: Update README (no-changelog)
  README.md
Labels: n8n team

#4737 refactor(Code Node): Limit n8n item key check
  packages/nodes-base/nodes/Code/Sandbox.ts
  packages/nodes-base/nodes/Code/utils.ts
Labels: node/improvement, n8n team

#4812 ci: Update slack notification messages for e2e tests (no-changelog)
  .github/workflows/e2e-tests.yml
Labels: n8n team

#4815 fix: Refresh credentials when re-entering workflows page (no-changelog)
  packages/editor-ui/src/views/NodeView.vue
Labels: ui, n8n team, Upcoming Release

#4813 fix: Stop using prefixed core modules from nodejs (no-changelog)
  packages/core/src/DirectoryLoader.ts
Labels: core, n8n team

#4817 feat: Add prompt to overwrite changes when concurrent editing occurs
  packages/editor-ui/src/Interface.ts
  packages/editor-ui/src/mixins/restApi.ts
  packages/editor-ui/src/mixins/workflowHelpers.ts
  packages/editor-ui/src/plugins/i18n/locales/en.json
Labels: ui, n8n team, Upcoming Release

#4793 feat(editor): Usage and plan
  packages/editor-ui/package.json
  packages/editor-ui/src/components/SettingsSidebar.vue
  packages/editor-ui/src/constants.ts
  packages/editor-ui/src/mixins/userHelpers.ts
  packages/editor-ui/src/plugins/i18n/locales/en.json
  packages/editor-ui/src/plugins/icons.ts
  packages/editor-ui/src/router.ts
  packages/editor-ui/src/stores/settings.ts
  packages/editor-ui/src/views/SettingsUsageAndPlan.vue
  pnpm-lock.yaml
Labels: ui, n8n team

#4818 feat: Fix checkbox line height and make checkbox label clickable
  packages/design-system/src/components/N8nCheckbox/Checkbox.vue
  packages/design-system/src/components/N8nInputLabel/InputLabel.vue
Labels: ui, n8n team, Upcoming Release

#4799 test(editor): Add more workflow actions tests
  cypress/e2e/5-workflow-actions.cy.ts
  cypress/e2e/7-workflow-actions.cy.ts
  cypress/fixtures/Test_workflow-actions_paste-data.json
  cypress/pages/workflow.ts
  cypress/support/commands.ts
  cypress/support/index.ts
  packages/editor-ui/src/mixins/copyPaste.ts
  packages/editor-ui/src/views/NodeView.vue
Labels: ui, n8n team

#4816 fix(Gmail Trigger Node): Trigger node missing some emails
  packages/nodes-base/nodes/Google/Gmail/GenericFunctions.ts
  packages/nodes-base/nodes/Google/Gmail/GmailTrigger.node.ts
Labels: n8n team, node/issue

#4820 fix(core): OAuth2 scopes does not save
  packages/cli/src/credentials/oauth2Credential.api.ts
Labels: n8n team, node/issue

#4770 refactor: Reactivate workflow locking
  packages/cli/src/ResponseHelper.ts
  packages/cli/src/databases/entities/WorkflowEntity.ts
  packages/cli/src/databases/migrations/mysqldb/1669739707125-AddWorkflowVersionIdColumn.ts
  packages/cli/src/databases/migrations/mysqldb/index.ts
  packages/cli/src/databases/migrations/postgresdb/1669739707126-AddWorkflowVersionIdColumn.ts
  packages/cli/src/databases/migrations/postgresdb/index.ts
  packages/cli/src/databases/migrations/sqlite/1669739707124-AddWorkflowVersionIdColumn.ts
  packages/cli/src/databases/migrations/sqlite/index.ts
  packages/cli/src/workflows/workflows.controller.ee.ts
  packages/cli/src/workflows/workflows.controller.ts
  packages/cli/src/workflows/workflows.services.ts
  packages/cli/test/integration/workflows.controller.ee.test.ts
  packages/editor-ui/src/Interface.ts
  packages/editor-ui/src/components/ExecutionsView/ExecutionsView.vue
  packages/editor-ui/src/components/WorkflowCard.vue
  packages/editor-ui/src/components/WorkflowSettings.vue
  packages/editor-ui/src/mixins/workflowHelpers.ts
  packages/editor-ui/src/stores/workflows.ts
  packages/editor-ui/src/views/NodeView.vue
Labels: core, n8n team

#4825 fix(Local File Trigger Node): Fix issue that causes a crash if the ignore field is empty (#4824)
  packages/nodes-base/nodes/LocalFileTrigger/LocalFileTrigger.node.ts
Labels: node/improvement, community

#4578 feat(KoBoToolbox Node): Add support for Media file API
  packages/nodes-base/nodes/KoBoToolbox/FileDescription.ts
  packages/nodes-base/nodes/KoBoToolbox/FormDescription.ts
  packages/nodes-base/nodes/KoBoToolbox/GenericFunctions.ts
  packages/nodes-base/nodes/KoBoToolbox/HookDescription.ts
  packages/nodes-base/nodes/KoBoToolbox/KoBoToolbox.node.ts
  packages/nodes-base/nodes/KoBoToolbox/KoBoToolboxTrigger.node.ts
  packages/nodes-base/nodes/KoBoToolbox/SubmissionDescription.ts
Labels: node/improvement, community

#4759 feat: Add message for readonly nodes. Improve foreign credentials handling
  packages/design-system/src/components/N8nUserSelect/UserSelect.vue
  packages/editor-ui/src/components/NodeDetailsView.vue
  packages/editor-ui/src/components/NodeSettings.vue
  packages/editor-ui/src/plugins/i18n/locales/en.json
Labels: ui, n8n team, Upcoming Release

#4615 feat(editor): JSON schema view
  packages/editor-ui/public/static/schema-mapping-gif.gif
  packages/editor-ui/src/Interface.ts
  packages/editor-ui/src/__tests__/setup.ts
  packages/editor-ui/src/components/Draggable.vue
  packages/editor-ui/src/components/NDVDraggablePanels.vue
  packages/editor-ui/src/components/ParameterInput.vue
  packages/editor-ui/src/components/ParameterInputFull.vue
  packages/editor-ui/src/components/RunData.vue
  packages/editor-ui/src/components/RunDataJson.vue
  packages/editor-ui/src/components/RunDataSchema.test.ts
  packages/editor-ui/src/components/RunDataSchema.vue
  packages/editor-ui/src/components/RunDataSchemaItem.vue
  packages/editor-ui/src/components/RunDataTable.vue
  packages/editor-ui/src/components/__snapshots__/RunDataSchema.test.ts.snap
  packages/editor-ui/src/mixins/externalHooks.ts
  packages/editor-ui/src/plugins/i18n/locales/en.json
  packages/editor-ui/src/plugins/icons.ts
  packages/editor-ui/src/plugins/telemetry/index.ts
  packages/editor-ui/src/stores/ndv.ts
  packages/editor-ui/src/styles/css-animation-helpers.scss
  packages/editor-ui/src/utils/__tests__/typesUtils.test.ts
  packages/editor-ui/src/utils/typeGuards.ts
  packages/editor-ui/src/utils/typesUtils.ts
Labels: ui, n8n team

#4831 fix: Handle error when workflow does not exist or is inaccessible
  packages/editor-ui/src/views/NodeView.vue
Labels: ui, n8n team

#4200 feat(core): Workflow Execution Statistics
  packages/cli/package.json
  packages/cli/src/Db.ts
  packages/cli/src/Interfaces.ts
  packages/cli/src/InternalHooks.ts
  packages/cli/src/Server.ts
  packages/cli/src/WebhookHelpers.ts
  packages/cli/src/WorkflowExecuteAdditionalData.ts
  packages/cli/src/WorkflowRunnerProcess.ts
  packages/cli/src/api/workflowStats.api.ts
  packages/cli/src/databases/entities/WorkflowEntity.ts
  packages/cli/src/databases/entities/WorkflowStatistics.ts
  packages/cli/src/databases/entities/index.ts
  packages/cli/src/databases/migrations/mysqldb/1664196174002-WorkflowStatistics.ts
  packages/cli/src/databases/migrations/mysqldb/index.ts
  packages/cli/src/databases/migrations/postgresdb/1664196174001-WorkflowStatistics.ts
  packages/cli/src/databases/migrations/postgresdb/index.ts
  packages/cli/src/databases/migrations/sqlite/1664196174000-WorkflowStatistics.ts
  packages/cli/src/databases/migrations/sqlite/index.ts
  packages/cli/src/events/WorkflowStatistics.ts
  packages/cli/src/events/index.ts
  packages/cli/src/index.ts
  packages/cli/src/telemetry/index.ts
  packages/cli/test/unit/Events.test.ts
  packages/cli/test/unit/Telemetry.test.ts
  packages/core/src/EventEmitter.ts
  packages/core/src/NodeExecuteFunctions.ts
  packages/core/src/index.ts
  pnpm-lock.yaml
Labels: core, n8n team

#4828 refactor: Disable ESLint `indent` rule (no-changelog)
  packages/@n8n_io/eslint-config/base.js
  packages/@n8n_io/eslint-config/frontend.js
Labels: n8n team

#4834 feat(editor): Alert design system component
  packages/design-system/src/components/N8nAlert/Alert.stories.ts
  packages/design-system/src/components/N8nAlert/Alert.vue
  packages/design-system/src/components/N8nAlert/__tests__/Alert.spec.ts
  packages/design-system/src/components/N8nAlert/index.ts
  packages/design-system/src/plugins/n8nComponents.ts
Labels: ui, n8n team

#4837 ci: Use multiple jobs for publishing various docker images
  .github/workflows/docker-images.yml
Labels: n8n team

#4833 fix: Make `nodes.exclude` and `nodes.include` work with lazy-loaded nodes
  packages/cli/src/config/schema.ts
  packages/cli/src/config/types.d.ts
  packages/core/src/DirectoryLoader.ts
Labels: core, n8n team

#4840 fix(editor): Schema unit test stub fontawesome icon
  packages/editor-ui/src/components/RunDataSchema.test.ts
  packages/editor-ui/src/components/__snapshots__/RunDataSchema.test.ts.snap
Labels: ui, n8n team

#4829 fix(core): Make expression resolution improvements
  packages/workflow/src/Expression.ts
  packages/workflow/src/WorkflowDataProxy.ts
  packages/workflow/test/Workflow.test.ts
Labels: core, n8n team

#4846 refactor(editor): Apply styling feedback to inline expression editor
  packages/editor-ui/src/Interface.ts
  packages/editor-ui/src/components/ExpressionEditorModal/ExpressionModalInput.vue
  packages/editor-ui/src/components/ExpressionEditorModal/ExpressionModalOutput.vue
  packages/editor-ui/src/components/ExpressionEditorModal/theme.ts
  packages/editor-ui/src/components/ExpressionParameterInput.vue
  packages/editor-ui/src/components/InlineExpressionEditor/InlineExpressionEditorInput.vue
  packages/editor-ui/src/components/InlineExpressionEditor/inputTheme.ts
  packages/editor-ui/src/components/NDVDraggablePanels.vue
  packages/editor-ui/src/components/ParameterInput.vue
  packages/editor-ui/src/stores/ndv.ts
Labels: ui, n8n team

#4848 refactor: Remove unnecessary console message (no-changelog)
  packages/cli/src/events/WorkflowStatistics.ts
  packages/cli/test/unit/Events.test.ts
Labels: core, n8n team

#4843 ci: Publish docker images for all architectures under the same tag (no-changelog)
  .github/workflows/docker-images.yml
Labels: n8n team

#4811 feat: Show warning message when removing last sharee that has access to credentials (no-changelog)
  packages/editor-ui/src/Interface.ts
  packages/editor-ui/src/components/WorkflowShareModal.ee.vue
  packages/editor-ui/src/plugins/i18n/locales/en.json
Labels: ui, n8n team

#4835 fix: Upgrade sse-channel to mitigate CVE-2019-10744
  packages/cli/package.json
  packages/cli/src/Push.ts
  packages/cli/src/Server.ts
  packages/cli/src/WebhookServer.ts
  packages/cli/src/middlewares/cors.ts
  packages/cli/src/sse-channel.d.ts
  pnpm-lock.yaml
Labels: core, n8n team

#4779 test(editor): Fix default-owner and credentials saving e2e specs
  cypress/e2e/3-default-owner.cy.ts
  cypress/e2e/5-ndv.cy.ts
  cypress/e2e/7-workflow-actions.cy.ts
  cypress/e2e/8-http-request-node.cy.ts
  cypress/e2e/9-expression-editor-modal.cy.ts
  cypress/pages/modals/credentials-modal.ts
  cypress/pages/sidebar/main-sidebar.ts
  cypress/pages/workflow.ts
  cypress/support/commands.ts
  cypress/support/index.ts
  packages/cli/src/CredentialsHelper.ts
  packages/design-system/src/components/N8nMenuItem/MenuItem.vue
Labels: n8n team

#4804 feat: Use generic auth-identities for LDAP
  packages/cli/src/Db.ts
  packages/cli/src/Interfaces.ts
  packages/cli/src/InternalHooks.ts
  packages/cli/src/Ldap/LdapSync.ee.ts
  packages/cli/src/Ldap/constants.ts
  packages/cli/src/Ldap/helpers.ts
  packages/cli/src/Ldap/routes/ldap.controller.ee.ts
  packages/cli/src/Ldap/types.d.ts
  packages/cli/src/UserAuthentication/methods/email.ts
  packages/cli/src/UserAuthentication/methods/ldap.ts
  packages/cli/src/UserManagement/Interfaces.ts
  packages/cli/src/UserManagement/UserManagementHelper.ts
  packages/cli/src/UserManagement/auth/jwt.ts
  packages/cli/src/UserManagement/routes/passwordReset.ts
  packages/cli/src/UserManagement/routes/users.ts
  packages/cli/src/commands/ldap/reset.ts
  packages/cli/src/databases/entities/AuthIdentity.ts
  packages/cli/src/databases/entities/User.ts
  packages/cli/src/databases/entities/index.ts
  packages/cli/src/databases/migrations/mysqldb/1670333612644-CreateLdapEntities.ts
  packages/cli/src/databases/migrations/postgresdb/1670333612644-CreateLdapEntities.ts
  packages/cli/src/databases/migrations/postgresdb/index.ts
  packages/cli/src/databases/migrations/sqlite/1670333612644-CreateLdapEntities.ts
  packages/cli/test/integration/ldap/ldap.api.test.ts
  packages/cli/test/integration/shared/testDb.ts
  packages/design-system/src/components/N8nUserInfo/UserInfo.vue
  packages/design-system/src/components/N8nUserSelect/UserSelect.stories.ts
  packages/design-system/src/components/N8nUsersList/UsersList.stories.ts
  packages/design-system/src/components/N8nUsersList/UsersList.vue
  packages/editor-ui/src/Interface.ts
  packages/editor-ui/src/stores/users.ts
  packages/editor-ui/src/utils/userUtils.ts
  packages/editor-ui/src/views/SettingsLdapView.vue
  packages/editor-ui/src/views/SettingsPersonalView.vue
Labels: core, n8n team

#4856 fix: Issue listing executions with Postgres
  packages/cli/src/executions/executions.service.ts
Labels: core, n8n team

#4859 fix: Stop returning `UNKNOWN ERROR` in the response if an actual error message is available
  packages/cli/src/ResponseHelper.ts
Labels: core, n8n team

#4842 feat(editor): Update Usage and plan page
  packages/design-system/src/components/N8nAlert/Alert.vue
  packages/editor-ui/package.json
  packages/editor-ui/src/components/SettingsSidebar.vue
  packages/editor-ui/src/constants.ts
  packages/editor-ui/src/plugins/i18n/locales/en.json
  packages/editor-ui/src/plugins/icons.ts
  packages/editor-ui/src/router.ts
  packages/editor-ui/src/stores/usageAndPlan.test.ts
  packages/editor-ui/src/stores/usageAndPlan.ts
  packages/editor-ui/src/views/SettingsUsageAndPlan.vue
  pnpm-lock.yaml
Labels: ui, n8n team

#4869 fix: Increase workflow reactivation max timeout to 1 day
  packages/cli/src/constants.ts
Labels: core, n8n team

#4870 test(editor): Set e2e test retries
  cypress.config.js
Labels: n8n team

#4872 fix: Use license-sdk v1.6.1
  packages/cli/package.json
  pnpm-lock.yaml
Labels: core, n8n team

#4858 fix: Update duplicate action
  packages/editor-ui/src/plugins/i18n/locales/en.json
Labels: ui, n8n team

#4873 fix(Split In Batches Node): Fix issue with pairedItem
  packages/core/src/NodeExecuteFunctions.ts
  packages/nodes-base/nodes/SplitInBatches/SplitInBatches.node.ts
  packages/workflow/src/Interfaces.ts
  packages/workflow/src/WorkflowDataProxy.ts
Labels: node/improvement, core, n8n team

#4787 feat(editor): Add undo/redo support for canvas actions
  packages/editor-ui/src/App.vue
  packages/editor-ui/src/Interface.ts
  packages/editor-ui/src/components/Node.vue
  packages/editor-ui/src/components/NodeSettings.vue
  packages/editor-ui/src/constants.ts
  packages/editor-ui/src/mixins/history.ts
  packages/editor-ui/src/mixins/nodeBase.ts
  packages/editor-ui/src/mixins/nodeHelpers.ts
  packages/editor-ui/src/models/history.ts
  packages/editor-ui/src/stores/history.ts
  packages/editor-ui/src/stores/n8nRootStore.ts
  packages/editor-ui/src/utils/canvasUtils.ts
  packages/editor-ui/src/views/NodeView.vue
Labels: ui, n8n team

#4881 fix(editor): Fix for broken tab navigation
  packages/editor-ui/src/views/NodeView.vue
Labels: ui, n8n team

#4878 ci: Upgrade pnpm and turborepo (no-changelog)
  .github/workflows/test-workflows.yml
  package.json
  pnpm-lock.yaml
Labels: n8n team

#4882 fix(Move Binary Data Node): Stringify objects before encoding them in MoveBinaryData
  packages/core/src/NodeExecuteFunctions.ts
  packages/editor-ui/src/components/BinaryDataDisplay.vue
  packages/editor-ui/src/components/BinaryDataDisplayEmbed.vue
  packages/editor-ui/src/components/RunData.vue
  packages/nodes-base/nodes/MoveBinaryData/MoveBinaryData.node.ts
  packages/nodes-base/package.json
  packages/workflow/src/Interfaces.ts
  packages/workflow/src/index.ts
  packages/workflow/src/utils.ts
  pnpm-lock.yaml
Labels: node/improvement, core, ui, n8n team

#4885 ci: Add libc6-compat to nightly docker builds (no-changelog)
  docker/images/n8n-custom/Dockerfile
Labels: n8n team

#4887 fix(editor): Avoid adding manual trigger node when webhook node is added
  packages/editor-ui/src/stores/nodeCreator.ts
Labels: ui, n8n team

#4883 fix(core): Remove `nodeGetter` checks
  packages/workflow/src/WorkflowDataProxy.ts
Labels: core, n8n team

#4850 feat: Handle sharing features when user skips owner setup
  packages/editor-ui/src/components/CredentialEdit/CredentialEdit.vue
  packages/editor-ui/src/components/CredentialEdit/CredentialSharing.ee.vue
  packages/editor-ui/src/components/WorkflowShareModal.ee.vue
  packages/editor-ui/src/plugins/i18n/locales/en.json
  packages/editor-ui/src/stores/users.ts
Labels: ui, n8n team

#4864 feat: Update credential test error message for sharees
  packages/editor-ui/src/components/CredentialEdit/CredentialConfig.vue
  packages/editor-ui/src/plugins/i18n/locales/en.json
Labels: ui, n8n team

#4871 :zap: Update paywall state for LDAP feature
  packages/cli/src/config/schema.ts
  packages/editor-ui/src/constants.ts
  packages/editor-ui/src/plugins/i18n/locales/en.json
  packages/editor-ui/src/views/SettingsLdapView.vue
Labels: core, ui, n8n team

#4880 fix: Remove foreign credentials when copying nodes or duplicating workflow
  packages/editor-ui/src/Interface.ts
  packages/editor-ui/src/components/DuplicateWorkflowDialog.vue
  packages/editor-ui/src/mixins/workflowHelpers.ts
  packages/editor-ui/src/stores/workflows.ts
  packages/editor-ui/src/views/NodeView.vue
Labels: ui, n8n team

#4894 fix: Remove delete sharee prompt except when deleting last cred accessor (no-changelog)
  packages/editor-ui/src/components/WorkflowShareModal.ee.vue
  packages/editor-ui/src/plugins/i18n/locales/en.json
Labels: ui, n8n team

#4893 fix: Update translation for sharing toast (no-changelog)
  packages/editor-ui/src/plugins/i18n/locales/en.json
Labels: ui, n8n team

#4879 fix(editor): Fix credential sharing issues handler when no matching id or name
  packages/editor-ui/src/components/NodeCredentials.vue
  packages/editor-ui/src/mixins/nodeHelpers.ts
  packages/editor-ui/src/plugins/i18n/locales/en.json
Labels: ui, n8n team

#4892 feat: Add sharing permissions info for workflow sharees
  packages/editor-ui/src/components/CredentialEdit/CredentialSharing.ee.vue
  packages/editor-ui/src/components/WorkflowShareModal.ee.vue
  packages/editor-ui/src/plugins/i18n/locales/en.json
  packages/editor-ui/src/stores/workflows.ee.ts
  packages/editor-ui/src/stores/workflows.ts
Labels: ui, n8n team

#4865 fix: Ensure parent directory exists before copying over the icons to generated static directory
  packages/cli/src/LoadNodesAndCredentials.ts
Labels: core, n8n team

#4898 fix(editor): Fix for wrong keycode when shift is pressed
  packages/editor-ui/src/mixins/history.ts
Labels: ui, n8n team

#4895 feat: Update readonly node notice when using foreign credentials (no-changelog)
  packages/editor-ui/src/components/NodeSettings.vue
  packages/editor-ui/src/plugins/i18n/locales/en.json
Labels: ui, n8n team

#4367 docs: Add codex file to Venafi TLS Protect Cloud Trigger
  packages/nodes-base/nodes/Venafi/ProtectCloud/VenafiTlsProtectCloudTrigger.node.json
Labels: node/new, n8n team

#4902 fix(editor): Schema view render empty data
  packages/editor-ui/src/__tests__/setup.ts
  packages/editor-ui/src/components/RunDataSchema.test.ts
  packages/editor-ui/src/components/RunDataSchema.vue
  packages/editor-ui/src/components/RunDataSchemaItem.vue
  packages/editor-ui/src/components/RunDataTable.vue
  packages/editor-ui/src/components/__snapshots__/RunDataSchema.test.ts.snap
  packages/editor-ui/src/plugins/i18n/locales/en.json
Labels: ui, n8n team

#4899 feat(core): Allow for hiding usage page via environment
  packages/cli/src/Interfaces.ts
  packages/cli/src/Server.ts
  packages/cli/src/config/schema.ts
Labels: core, n8n team

#4910 fix: Update pnpm-lock to fix build
  pnpm-lock.yaml
Labels: n8n team

#4904 test(editor): Add e2e tests for undo/redo
  cypress/constants.ts
  cypress/e2e/10-undo-redo.cy.ts
  cypress/e2e/7-workflow-actions.cy.ts
  cypress/pages/workflow.ts
  cypress/support/commands.ts
  cypress/support/index.ts
  packages/editor-ui/src/components/Node.vue
  packages/editor-ui/src/components/NodeTitle.vue
Labels: ui, n8n team

#4927 feat: Update credential sharing messages (no-changelog)
  packages/editor-ui/src/components/CredentialEdit/CredentialSharing.ee.vue
  packages/editor-ui/src/plugins/i18n/locales/en.json
Labels: ui, n8n team

#4925 feat: Update last credential accessor removal message (no-changelog)
  packages/editor-ui/src/plugins/i18n/locales/en.json
Labels: ui, n8n team

#4916 fix: Update permission for showing workflow caller policy
  packages/editor-ui/src/Interface.ts
  packages/editor-ui/src/components/WorkflowSettings.vue
  packages/editor-ui/src/plugins/i18n/locales/en.json
  packages/editor-ui/src/stores/settings.ts
Labels: ui, n8n team

#4928 feat(editor): Update user management setup message when sharing is disabled
  packages/editor-ui/src/plugins/i18n/locales/en.json
  packages/editor-ui/src/views/SettingsUsersView.vue
Labels: ui, n8n team

#4917 feat: Update workflow overwriting message
  packages/editor-ui/src/mixins/workflowHelpers.ts
  packages/editor-ui/src/plugins/i18n/locales/en.json
Labels: ui, n8n team

#4930 ci: Block all external network calls in tests (no-changelog)
  package.json
  packages/cli/jest.config.js
  packages/cli/test/setup.ts
  packages/cli/test/unit/Telemetry.test.ts
  pnpm-lock.yaml
Labels: core, n8n team

#4906 feat: Add workflow sharing telemetry
  packages/editor-ui/src/Interface.ts
  packages/editor-ui/src/components/DuplicateWorkflowDialog.vue
  packages/editor-ui/src/components/MainHeader/WorkflowDetails.vue
  packages/editor-ui/src/components/NodeDetailsView.vue
  packages/editor-ui/src/components/WorkflowCard.vue
  packages/editor-ui/src/components/WorkflowShareModal.ee.vue
  packages/editor-ui/src/mixins/workflowHelpers.ts
Labels: ui, n8n team

#4933 fix(core): Fix for Google and Microsoft generic OAuth2 credentials
  packages/cli/src/credentials/oauth2Credential.api.ts
Labels: n8n team, node/issue

#4935 refactor: Phase out TSLint in `editor-ui` (no-changelog)
  .npmignore
  packages/@n8n_io/eslint-config/package.json
  packages/design-system/src/components/N8nNodeCreatorNode/NodeCreatorNode.stories.ts
  packages/editor-ui/.eslintrc.js
  packages/editor-ui/package.json
  packages/editor-ui/src/Interface.ts
  packages/editor-ui/src/components/BreakpointsObserver.vue
  packages/editor-ui/src/components/CredentialEdit/CredentialEdit.vue
  packages/editor-ui/src/components/ExpressionEdit.vue
  packages/editor-ui/src/components/ExpressionEditorModal/ExpressionEditorModalOutput.vue
  packages/editor-ui/src/components/InlineExpressionEditor/InlineExpressionEditorOutput.vue
  packages/editor-ui/src/components/Node.vue
  packages/editor-ui/src/components/Node/NodeCreator/NodeItem.vue
  packages/editor-ui/src/components/NodeSettings.vue
  packages/editor-ui/src/components/ParameterInput.vue
  packages/editor-ui/src/components/TagsDropdown.vue
  packages/editor-ui/src/components/TagsManager/TagsView/TagsTable.vue
  packages/editor-ui/src/components/WorkflowSettings.vue
  packages/editor-ui/src/mixins/debounce.ts
  packages/editor-ui/src/mixins/emitter.ts
  packages/editor-ui/src/mixins/genericHelpers.ts
  packages/editor-ui/src/mixins/restApi.ts
  packages/editor-ui/src/mixins/workflowHelpers.ts
  packages/editor-ui/src/plugins/icons.ts
  packages/editor-ui/src/shims.d.ts
  packages/editor-ui/src/stores/nodeTypes.ts
  packages/editor-ui/src/stores/workflows.ts
  packages/editor-ui/src/utils/sortUtils.ts
  packages/editor-ui/src/views/NodeView.vue
  packages/editor-ui/src/views/SettingsUsersView.vue
  packages/editor-ui/tslint.json
  pnpm-lock.yaml
Labels: ui, n8n team

#4868 feat: Hide credentials password values
  packages/cli/src/constants.ts
  packages/cli/src/credentials/credentials.controller.ee.ts
  packages/cli/src/credentials/credentials.controller.ts
  packages/cli/src/credentials/credentials.service.ts
  packages/editor-ui/src/components/ParameterInput.vue
Labels: core, ui, n8n team

#4936 test(editor): Add e2e tests for inline expression editor
  cypress/e2e/11-inline-expression-editor.cy.ts
  cypress/e2e/9-expression-editor-modal.cy.ts
  cypress/pages/workflow.ts
  packages/editor-ui/src/components/InlineExpressionEditor/InlineExpressionEditorInput.vue
  packages/editor-ui/src/components/InlineExpressionEditor/InlineExpressionEditorOutput.vue
Labels: ui, n8n team

#4932 feat(OpenAI Node): Add a node to work with OpenAI
  packages/nodes-base/credentials/OpenAiApi.credentials.ts
  packages/nodes-base/nodes/OpenAi/ImageDescription.ts
  packages/nodes-base/nodes/OpenAi/OpenAi.node.json
  packages/nodes-base/nodes/OpenAi/OpenAi.node.ts
  packages/nodes-base/nodes/OpenAi/TextDescription.ts
  packages/nodes-base/nodes/OpenAi/openAi.svg
  packages/nodes-base/package.json
  packages/workflow/src/Interfaces.ts
  packages/workflow/src/RoutingNode.ts
Labels: node/new, n8n team

#4941 feat(Send Email Node): Add replyTo support
  packages/nodes-base/nodes/EmailSend/EmailSend.node.ts
Labels: node/improvement, n8n team

#4912 fix parameter name in disqus node
  packages/nodes-base/nodes/Disqus/Disqus.node.ts
Labels: node/improvement, community

#4806 fix(core): digestAuthAxiosConfig resolve http header
  packages/core/src/NodeExecuteFunctions.ts
Labels: core, community

#4528 fix(editor): Fix typo in retry-button option "Retry with original workflow"
  packages/editor-ui/src/components/ExecutionsList.vue
Labels: ui, community

#4945 fix(editor): Allow mapping onto expression editor with selection range
  packages/editor-ui/src/components/InlineExpressionEditor/InlineExpressionEditorInput.vue
Labels: ui, n8n team

#4946 fix(editor): Fix an issue where some node actions wouldn't select default params correctly
  packages/editor-ui/src/stores/workflows.ts
Labels: ui, n8n team

#4943 feat: Overhaul dynamic translations for local and cloud
  packages/editor-ui/src/Interface.ts
  packages/editor-ui/src/components/CredentialEdit/CredentialEdit.vue
  packages/editor-ui/src/components/CredentialEdit/CredentialSharing.ee.vue
  packages/editor-ui/src/components/MainHeader/WorkflowDetails.vue
  packages/editor-ui/src/components/WorkflowShareModal.ee.vue
  packages/editor-ui/src/constants.ts
  packages/editor-ui/src/plugins/i18n/locales/en.json
  packages/editor-ui/src/stores/ui.ts
Labels: ui, n8n team

#4947 fix: Do not crash the server when Telemetry is blocked via DNS
  packages/cli/src/ErrorReporting.ts
  packages/cli/src/telemetry/index.ts
Labels: core, n8n team

#4949 ci: Fix build on master (no-changelog)
  packages/editor-ui/package.json
  packages/node-dev/package.json
  pnpm-lock.yaml
Labels: core, ui, n8n team

#4948 fix: Enable crash journal only in production mode (no-changelog)
  packages/cli/src/CrashJournal.ts
  packages/cli/src/ResponseHelper.ts
  packages/cli/src/commands/BaseCommand.ts
  packages/cli/src/config/index.ts
  packages/cli/src/constants.ts
  packages/cli/src/databases/utils/migrationHelpers.ts
  packages/cli/src/middlewares/cors.ts
Labels: core, n8n team

#4951 fix: Always retain original errors in the error chain on NodeOperationError
  packages/nodes-base/nodes/FileMaker/FileMaker.node.ts
  packages/nodes-base/nodes/Jira/JiraTrigger.node.ts
  packages/nodes-base/nodes/N8n/GenericFunctions.ts
  packages/nodes-base/nodes/NocoDB/NocoDB.node.ts
  packages/nodes-base/nodes/SendInBlue/GenericFunctions.ts
Labels: node/improvement, n8n team

#4958 feat(editor): Improve license activation error messages (no-changelog)
  packages/cli/package.json
  packages/cli/src/license/license.controller.ts
  pnpm-lock.yaml
Labels: core, n8n team

#4961 docs: Add correct URL for credentials doc to OpenAI node
  packages/nodes-base/nodes/OpenAi/OpenAi.node.json
Labels: node/improvement, n8n team

#4964 fix: BinaryDataManager should store metadata when saving from buffer as well
  packages/core/src/BinaryDataManager/index.ts
Labels: core, n8n team

#4966 fix(editor): Fix for wrong execution data displayed in executions preview
  packages/editor-ui/src/components/ExecutionsList.vue
  packages/editor-ui/src/stores/workflows.ts
Labels: ui, n8n team

#4962 fix: Pick up credential test functions from versioned nodes as well
  packages/core/bin/generate-known
Labels: core, n8n team

#4875 feat(editor): In-app experience
  packages/cli/package.json
  packages/cli/src/ActiveWorkflowRunner.ts
  packages/cli/src/Interfaces.ts
  packages/cli/src/InternalHooks.ts
  packages/cli/src/License.ts
  packages/cli/src/Server.ts
  packages/cli/src/WebhookHelpers.ts
  packages/cli/src/databases/entities/WorkflowEntity.ts
  packages/cli/src/databases/migrations/mysqldb/1669823906994-AddTriggerCountColumn.ts
  packages/cli/src/databases/migrations/mysqldb/index.ts
  packages/cli/src/databases/migrations/postgresdb/1669823906995-AddTriggerCountColumn.ts
  packages/cli/src/databases/migrations/postgresdb/index.ts
  packages/cli/src/databases/migrations/sqlite/1669823906993-AddTriggerCountColumn.ts
  packages/cli/src/databases/migrations/sqlite/index.ts
  packages/cli/src/events/WorkflowStatistics.ts
  packages/cli/src/license/License.service.ts
  packages/cli/src/license/license.controller.ts
  packages/cli/src/requests.d.ts
  packages/cli/src/telemetry/index.ts
  packages/cli/test/integration/license.api.test.ts
  packages/cli/test/integration/shared/types.d.ts
  packages/cli/test/integration/shared/utils.ts
  packages/cli/test/unit/Events.test.ts
  packages/cli/test/unit/Helpers.ts
  packages/cli/test/unit/License.test.ts
  packages/cli/test/unit/Telemetry.test.ts
  packages/editor-ui/package.json
  packages/editor-ui/src/Interface.ts
  packages/editor-ui/src/api/usage.ts
  packages/editor-ui/src/components/SettingsSidebar.vue
  packages/editor-ui/src/plugins/i18n/locales/en.json
  packages/editor-ui/src/router.ts
  packages/editor-ui/src/stores/usage.test.ts
  packages/editor-ui/src/stores/usage.ts
  packages/editor-ui/src/stores/users.ts
  packages/editor-ui/src/stores/workflows.ts
  packages/editor-ui/src/utils/userUtils.ts
  packages/editor-ui/src/views/SettingsUsageAndPlan.vue
  pnpm-lock.yaml
Labels: ui, n8n team

#4976 fix(editor): Correctly display trigger nodes without actions and with related regular node in the "On App Events" category
  packages/editor-ui/src/stores/nodeCreator.ts
Labels: ui, n8n team

#4971 refactor(core): Ensure getSharedWorkflowIds returns string[] instead of number[]
  packages/cli/src/PublicApi/v1/handlers/executions/executions.service.ts
  packages/cli/src/PublicApi/v1/handlers/workflows/workflows.service.ts
  packages/cli/src/Server.ts
  packages/cli/src/WorkflowHelpers.ts
  packages/cli/src/executions/executions.service.ee.ts
  packages/cli/src/executions/executions.service.ts
  packages/cli/src/workflows/workflows.services.ts
Labels: core, n8n team

#4970 fix: Hide trigger tooltip for nodes with static test output
  packages/editor-ui/src/components/Node.vue
  packages/nodes-base/nodes/ExecuteWorkflowTrigger/ExecuteWorkflowTrigger.node.ts
  packages/nodes-base/nodes/ManualTrigger/ManualTrigger.node.ts
Labels: node/improvement, ui, n8n team

#4968 fix: Redirect home to workflows always
  packages/editor-ui/src/router.ts
Labels: ui, n8n team

#4965 feat: Update mapping pill for table/json views
  packages/editor-ui/src/components/MappingPill.vue
  packages/editor-ui/src/components/RunDataJson.vue
  packages/editor-ui/src/components/RunDataSchema.vue
  packages/editor-ui/src/components/RunDataTable.vue
  packages/editor-ui/src/components/__snapshots__/RunDataSchema.test.ts.snap
  packages/editor-ui/src/plugins/i18n/locales/en.json
Labels: ui, n8n team

#4950 test(editor): Add canvas actions e2e tests
  cypress/constants.ts
  cypress/e2e/10-undo-redo.cy.ts
  cypress/e2e/12-canvas.cy.ts
  cypress/e2e/7-workflow-actions.cy.ts
  cypress/pages/workflow.ts
  packages/editor-ui/src/components/CanvasControls.vue
  packages/editor-ui/src/views/NodeView.vue
Labels: ui, n8n team

#4819 feat(editor): Add usage and plan pages
  cypress/e2e/3-default-owner.cy.ts
  cypress/pages/settings-usage.ts
  cypress/pages/sidebar/settings-sidebar.ts
  packages/cli/package.json
  packages/cli/src/ActiveWorkflowRunner.ts
  packages/cli/src/Interfaces.ts
  packages/cli/src/InternalHooks.ts
  packages/cli/src/License.ts
  packages/cli/src/Server.ts
  packages/cli/src/WebhookHelpers.ts
  packages/cli/src/databases/entities/WorkflowEntity.ts
  packages/cli/src/databases/migrations/mysqldb/1669823906994-AddTriggerCountColumn.ts
  packages/cli/src/databases/migrations/mysqldb/index.ts
  packages/cli/src/databases/migrations/postgresdb/1669823906995-AddTriggerCountColumn.ts
  packages/cli/src/databases/migrations/postgresdb/index.ts
  packages/cli/src/databases/migrations/sqlite/1669823906993-AddTriggerCountColumn.ts
  packages/cli/src/databases/migrations/sqlite/index.ts
  packages/cli/src/events/WorkflowStatistics.ts
  packages/cli/src/license/License.service.ts
  packages/cli/src/license/license.controller.ts
  packages/cli/src/requests.d.ts
  packages/cli/src/telemetry/index.ts
  packages/cli/test/integration/license.api.test.ts
  packages/cli/test/integration/shared/types.d.ts
  packages/cli/test/integration/shared/utils.ts
  packages/cli/test/unit/Events.test.ts
  packages/cli/test/unit/Helpers.ts
  packages/cli/test/unit/License.test.ts
  packages/cli/test/unit/Telemetry.test.ts
  packages/design-system/src/components/N8nAlert/Alert.vue
  packages/editor-ui/package.json
  packages/editor-ui/src/Interface.ts
  packages/editor-ui/src/api/usage.ts
  packages/editor-ui/src/components/SettingsSidebar.vue
  packages/editor-ui/src/constants.ts
  packages/editor-ui/src/mixins/userHelpers.ts
  packages/editor-ui/src/plugins/i18n/locales/en.json
  packages/editor-ui/src/plugins/icons.ts
  packages/editor-ui/src/router.ts
  packages/editor-ui/src/stores/settings.ts
  packages/editor-ui/src/stores/usage.test.ts
  packages/editor-ui/src/stores/usage.ts
  packages/editor-ui/src/stores/users.ts
  packages/editor-ui/src/stores/workflows.ts
  packages/editor-ui/src/utils/userUtils.ts
  packages/editor-ui/src/views/SettingsUsageAndPlan.vue
  pnpm-lock.yaml
Labels: ui, n8n team

#4984 fix: Prevent keyboard shortcuts in expression editor modal
  packages/editor-ui/src/components/ExpressionEdit.vue
  packages/editor-ui/src/components/ExpressionEditorModal/ExpressionEditorModalInput.vue
Labels: ui, n8n team

#4982 fix: Update mapping gifs
  packages/editor-ui/public/static/data-mapping-gif.gif
  packages/editor-ui/public/static/json-mapping-gif.gif
Labels: ui, n8n team

#4981 fix: Keep expression when dropping mapped value
  packages/editor-ui/src/components/ParameterInput.vue
Labels: ui, n8n team

#4986 fix: Fix stickies resize
  packages/editor-ui/src/Interface.ts
  packages/editor-ui/src/components/Sticky.vue
Labels: ui, n8n team

#4990 ci: Break most of the circular dependencies in code (no-changelog)
  packages/cli/src/PublicApi/v1/handlers/credentials/credentials.service.ts
  packages/cli/src/PublicApi/v1/handlers/workflows/workflows.handler.ts
  packages/cli/src/Server.ts
  packages/cli/src/api/workflowStats.api.ts
  packages/cli/src/credentials/credentials.service.ts
  packages/cli/src/credentials/oauth2Credential.api.ts
  packages/cli/src/databases/entities/CredentialsEntity.ts
  packages/cli/src/databases/entities/InstalledNodes.ts
  packages/cli/src/databases/entities/InstalledPackages.ts
  packages/cli/src/databases/entities/Role.ts
  packages/cli/src/databases/entities/SharedCredentials.ts
  packages/cli/src/databases/entities/SharedWorkflow.ts
  packages/cli/src/databases/entities/TagEntity.ts
  packages/cli/src/databases/entities/User.ts
  packages/cli/src/databases/entities/WorkflowEntity.ts
  packages/cli/src/databases/entities/WorkflowStatistics.ts
  packages/cli/src/events/WorkflowStatistics.ts
  packages/cli/src/executions/executions.service.ts
  packages/cli/src/license/License.service.ts
  packages/cli/src/license/license.controller.ts
  packages/cli/src/workflows/workflows.controller.ee.ts
  packages/cli/src/workflows/workflows.controller.ts
  packages/cli/src/workflows/workflows.services.ts
  packages/core/src/NodeExecuteFunctions.ts
  packages/core/src/WorkflowExecute.ts
  packages/node-dev/src/Build.ts
  packages/node-dev/src/index.ts
  packages/nodes-base/nodes/ActionNetwork/descriptions/SharedFields.ts
  packages/nodes-base/nodes/ActionNetwork/types.d.ts
  packages/nodes-base/nodes/Google/Sheet/v2/helpers/GoogleSheets.utils.ts
  packages/nodes-base/nodes/SeaTable/Interfaces.ts
  packages/nodes-base/nodes/Todoist/v1/OperationHandler.ts
  packages/nodes-base/nodes/Todoist/v2/OperationHandler.ts
  packages/workflow/src/ExpressionError.ts
  packages/workflow/src/Interfaces.ts
  packages/workflow/src/WorkflowDataProxy.ts
Labels: node/improvement, core, n8n team

#4992 feat: Overhaul contextual translations
  packages/editor-ui/src/Interface.ts
  packages/editor-ui/src/components/CredentialEdit/CredentialSharing.ee.vue
  packages/editor-ui/src/components/MainHeader/WorkflowDetails.vue
  packages/editor-ui/src/components/WorkflowShareModal.ee.vue
  packages/editor-ui/src/plugins/i18n/locales/en.json
  packages/editor-ui/src/stores/settings.ts
  packages/editor-ui/src/stores/ui.ts
Labels: ui, n8n team

#4993 refactor(editor): Make `null` no longer conditionally displayed
  packages/editor-ui/src/mixins/expressionManager.ts
Labels: ui, n8n team

#4995 fix: View option for binary-data shouldn't download the file on Chrome/Edge
  packages/cli/src/Server.ts
  packages/editor-ui/src/Interface.ts
  packages/editor-ui/src/components/BinaryDataDisplay.vue
  packages/editor-ui/src/components/BinaryDataDisplayEmbed.vue
  packages/editor-ui/src/components/RunData.vue
  packages/editor-ui/src/mixins/restApi.ts
Labels: core, ui, n8n team

#4974 docs: Update LDAP link and help text
  packages/editor-ui/src/plugins/i18n/locales/en.json
Labels: ui, n8n team

#4888 refactor: Workflow sharing bug bash fixes
  packages/cli/src/Interfaces.ts
  packages/cli/src/InternalHooks.ts
  packages/cli/src/Server.ts
  packages/cli/src/UserManagement/PermissionChecker.ts
  packages/cli/src/UserManagement/UserManagementHelper.ts
  packages/cli/src/UserManagement/routes/users.ts
  packages/cli/src/WorkflowExecuteAdditionalData.ts
  packages/cli/src/WorkflowHelpers.ts
  packages/cli/src/WorkflowRunnerProcess.ts
  packages/cli/src/api/workflowStats.api.ts
  packages/cli/src/config/index.ts
  packages/cli/src/config/schema.ts
  packages/cli/src/executions/executions.controller.ee.ts
  packages/cli/src/role/role.service.ts
  packages/cli/src/user/user.service.ts
  packages/cli/src/workflows/workflows.controller.ee.ts
  packages/cli/src/workflows/workflows.controller.ts
  packages/cli/src/workflows/workflows.services.ee.ts
  packages/cli/src/workflows/workflows.services.ts
  packages/cli/test/integration/users.api.test.ts
  packages/cli/test/integration/workflows.controller.ee.test.ts
  packages/editor-ui/src/Interface.ts
  packages/editor-ui/src/components/CredentialEdit/CredentialConfig.vue
  packages/editor-ui/src/components/CredentialEdit/CredentialEdit.vue
  packages/editor-ui/src/components/CredentialEdit/CredentialSharing.ee.vue
  packages/editor-ui/src/components/MainHeader/WorkflowDetails.vue
  packages/editor-ui/src/components/NodeDetailsView.vue
  packages/editor-ui/src/components/WorkflowCard.vue
  packages/editor-ui/src/components/WorkflowSettings.vue
  packages/editor-ui/src/components/WorkflowShareModal.ee.vue
  packages/editor-ui/src/constants.ts
  packages/editor-ui/src/mixins/workflowHelpers.ts
  packages/editor-ui/src/permissions.ts
  packages/editor-ui/src/plugins/i18n/locales/en.json
  packages/editor-ui/src/router.ts
  packages/editor-ui/src/stores/settings.ts
  packages/editor-ui/src/stores/ui.ts
  packages/editor-ui/src/stores/webhooks.ts
  packages/editor-ui/src/stores/workflows.ee.ts
  packages/editor-ui/src/stores/workflows.ts
  packages/editor-ui/src/views/NodeView.vue
  packages/editor-ui/src/views/WorkflowsView.vue
  packages/workflow/src/Interfaces.ts
Labels: core, ui, n8n team

#4975 ci: Use a fixed version of NPM in the release process (no-changelog)
  docker/images/n8n-base/Dockerfile
  docker/images/n8n-debian/Dockerfile
  docker/images/n8n-rhel7/Dockerfile
Labels: n8n team

#4924 ci: Make custom images consistent with the release images (no-changelog)
  docker/images/n8n-custom/Dockerfile
  docker/images/n8n-custom/docker-entrypoint.sh
Labels: n8n team

#4959 Fix bugs in dynamodb connector - Fixes #4956 #4957
  packages/nodes-base/nodes/Aws/DynamoDB/GenericFunctions.ts
  packages/nodes-base/nodes/Aws/DynamoDB/utils.ts
Labels: node/improvement, community

#5002 fix: DynamoDB node type issues
  packages/nodes-base/nodes/Aws/DynamoDB/utils.ts
Labels: node/improvement, n8n team

#4996 ci: Setup `eslint-import-resolver-typescript` for improved TS linting
  .vscode/settings.default.json
  package.json
  packages/@n8n_io/eslint-config/base.js
  packages/@n8n_io/eslint-config/frontend.js
  packages/@n8n_io/eslint-config/package.json
  packages/@n8n_io/eslint-config/shared.js
  packages/cli/.eslintrc.js
  packages/core/.eslintrc.js
  packages/design-system/.eslintrc.js
  packages/editor-ui/.eslintrc.js
  packages/editor-ui/src/Interface.ts
  packages/editor-ui/src/mixins/pushConnection.ts
  packages/editor-ui/src/mixins/titleChange.ts
  packages/editor-ui/src/shims-vue.d.ts
  packages/editor-ui/src/stores/nodeCreator.ts
  packages/editor-ui/tsconfig.json
  packages/editor-ui/vite.config.ts
  packages/node-dev/.eslintrc.js
  packages/nodes-base/.eslintrc.js
  packages/workflow/.eslintrc.js
  pnpm-lock.yaml
Labels: node/improvement, core, ui, n8n team

#5000 fix: Remove circular dependencies from cli tests (no-changelog)
  packages/cli/test/integration/shared/testDb.ts
  packages/cli/test/unit/Events.test.ts
  packages/cli/test/unit/License.test.ts
  packages/cli/test/unit/PermissionChecker.test.ts
Labels: core, n8n team

#5004 fix: Restore missing tags in workflow retrieve
  packages/cli/src/workflows/workflows.controller.ee.ts
Labels: core, n8n team

#5003 fix(AWS DynamoDB Node): Add missing type assertion (no-changelog)
  packages/nodes-base/nodes/Aws/DynamoDB/utils.ts
  packages/workflow/src/index.ts
  packages/workflow/src/utils.ts
Labels: node/improvement, core, n8n team

#5006 docs: Fix OpenAI credential docs url (no-changelog)
  packages/nodes-base/credentials/OpenAiApi.credentials.ts
Labels: node/improvement, n8n team

#4994 fix(editor): Fix for executions preview scroll load and wrong execution displayed
  packages/editor-ui/src/components/ExecutionsList.vue
  packages/editor-ui/src/components/ExecutionsView/ExecutionsSidebar.vue
  packages/editor-ui/src/components/ExecutionsView/ExecutionsView.vue
  packages/editor-ui/src/stores/workflows.ts
  packages/editor-ui/src/views/NodeView.vue
Labels: ui, n8n team

#5008 docs: Update documentation url for n8n credentials (no-changelog)
  packages/nodes-base/credentials/N8nApi.credentials.ts
Labels: node/improvement, community

#5011 fix: Always return ids as strings
  packages/cli/src/credentials/credentials.controller.ee.ts
  packages/cli/src/credentials/credentials.controller.ts
  packages/cli/src/workflows/workflows.controller.ee.ts
Labels: core, n8n team

#5012 docs: Fix all credential documentation urls, and add a CI job to regularly validate these urls
  .github/workflows/check-documentation-urls.yml
  packages/editor-ui/src/components/CredentialEdit/CredentialConfig.vue
  packages/editor-ui/src/constants.ts
  packages/nodes-base/credentials/BaserowApi.credentials.ts
  packages/nodes-base/credentials/CiscoWebexOAuth2Api.credentials.ts
  packages/nodes-base/credentials/CitrixAdcApi.credentials.ts
  packages/nodes-base/credentials/FacebookGraphApi.credentials.ts
  packages/nodes-base/credentials/FacebookGraphAppApi.credentials.ts
  packages/nodes-base/credentials/GetResponseOAuth2Api.credentials.ts
  packages/nodes-base/credentials/GoogleOAuth2Api.credentials.ts
  packages/nodes-base/credentials/HarvestOAuth2Api.credentials.ts
  packages/nodes-base/credentials/MondayComOAuth2Api.credentials.ts
  packages/nodes-base/credentials/SendInBlueApi.credentials.ts
  packages/nodes-base/credentials/Smtp.credentials.ts
  packages/nodes-base/credentials/SshPassword.credentials.ts
  packages/nodes-base/credentials/SshPrivateKey.credentials.ts
  packages/nodes-base/credentials/VenafiTlsProtectCloudApi.credentials.ts
  packages/nodes-base/credentials/VenafiTlsProtectDatacenterApi.credentials.ts
  packages/nodes-base/nodes/Aws/CertificateManager/AwsCertificateManager.node.json
  packages/nodes-base/nodes/Aws/ELB/AwsElb.node.json
  packages/nodes-base/nodes/Citrix/ADC/CitrixAdc.node.json
  packages/nodes-base/nodes/Cron/Cron.node.json
  packages/nodes-base/nodes/EmailReadImap/EmailReadImap.node.json
  packages/nodes-base/nodes/Function/Function.node.json
  packages/nodes-base/nodes/FunctionItem/FunctionItem.node.json
  packages/nodes-base/nodes/Venafi/ProtectCloud/VenafiTlsProtectCloud.node.json
  scripts/validate-docs-links.js
Labels: node/improvement, ui, n8n team

#5010 test: Ensure all subworkflow execution policies are tested
  packages/cli/test/unit/PermissionChecker.test.ts
Labels: core, n8n team

#5022 ci: Enforce code formatting on editor-ui (no-changelog)
  packages/design-system/src/components/N8nAlert/Alert.vue
  packages/editor-ui/.eslintrc.js
  packages/editor-ui/src/components/ExecutionsList.vue
  packages/editor-ui/src/components/ExecutionsView/ExecutionsSidebar.vue
  packages/editor-ui/src/components/ExecutionsView/ExecutionsView.vue
  packages/editor-ui/src/components/MappingPill.vue
  packages/editor-ui/src/components/RunDataJson.vue
  packages/editor-ui/src/components/RunDataSchema.vue
  packages/editor-ui/src/components/RunDataTable.vue
  packages/editor-ui/src/router.ts
  packages/editor-ui/src/stores/workflows.ts
  packages/editor-ui/src/views/NodeView.vue
  packages/editor-ui/src/views/SettingsUsageAndPlan.vue
Labels: ui, n8n team

#5021 perf: Improve workflows list performance
  packages/cli/src/credentials/credentials.service.ts
  packages/cli/src/workflows/workflows.controller.ee.ts
  packages/cli/src/workflows/workflows.controller.ts
  packages/cli/src/workflows/workflows.services.ee.ts
  packages/cli/src/workflows/workflows.services.ts
Labels: core, n8n team

#5023 fix(core): Update license SDK to v1.8.0 (no-changelog)
  packages/cli/package.json
  pnpm-lock.yaml
Labels: core, n8n team

#5019 test: Add test case for when policy is set to any
  packages/cli/test/unit/PermissionChecker.test.ts
Labels: core, n8n team

#5020 fix: Fix automatic credential selection when credentials are shared
  packages/editor-ui/src/components/NodeCredentials.vue
  packages/editor-ui/src/stores/credentials.ts
  packages/editor-ui/src/stores/users.ts
  packages/editor-ui/src/views/NodeView.vue
Labels: ui, n8n team

#4884 refactor: Consolidate redundant code in workflow execution-functions (no-changelog)
  packages/core/src/Interfaces.ts
  packages/core/src/NodeExecuteFunctions.ts
  packages/nodes-base/nodes/Aws/AwsSnsTrigger.node.ts
  packages/nodes-base/nodes/Metabase/QuestionsDescription.ts
  packages/nodes-base/nodes/SendInBlue/GenericFunctions.ts
  packages/nodes-base/nodes/Splunk/GenericFunctions.ts
  packages/workflow/src/Interfaces.ts
  packages/workflow/src/RoutingNode.ts
Labels: core, n8n team

#5029 fix: update cred owner warning when sharing
  packages/editor-ui/src/plugins/i18n/locales/en.json
Labels: ui, n8n team

#5031 fix(core): Do not send credentials to browser console
  packages/nodes-base/nodes/HttpRequest/GenericFunctions.ts
  packages/nodes-base/nodes/HttpRequest/V1/HttpRequestV1.node.ts
  packages/nodes-base/nodes/HttpRequest/V2/HttpRequestV2.node.ts
  packages/nodes-base/nodes/HttpRequest/V3/HttpRequestV3.node.ts
Labels: node/improvement, n8n team

#5024 feat(editor): Improve UX for brace completion from selection
  packages/editor-ui/src/components/InlineExpressionEditor/InlineExpressionEditorInput.vue
  packages/editor-ui/src/plugins/codemirror/doubleBraceHandler.ts
Labels: ui, n8n team

#5033 fix(editor): Transparentize tertiary button on Usage page
  packages/editor-ui/src/views/SettingsUsageAndPlan.vue
Labels: ui, n8n team

#4960 feat(core): Implement webhook-only manual execution
  packages/cli/src/TestWebhooks.ts
  packages/cli/src/WebhookHelpers.ts
Labels: core, n8n team

#5035 fix(editor): Fix for loading executions that are not on the current executions list
  packages/editor-ui/src/api/workflows.ts
  packages/editor-ui/src/components/ExecutionsView/ExecutionsSidebar.vue
  packages/editor-ui/src/components/ExecutionsView/ExecutionsView.vue
  packages/editor-ui/src/plugins/i18n/locales/en.json
  packages/editor-ui/src/stores/workflows.ts
Labels: ui, n8n team

#5036 fix: Non owner should be permitted to use their own credentials
  packages/cli/src/UserManagement/PermissionChecker.ts
Labels: core, n8n team

#5037 refactor(editor): Tweak phrasing of `itemMatching()` (no-changelog)
  packages/editor-ui/src/plugins/i18n/locales/en.json
Labels: ui, n8n team

#5038 fix(editor): Display default missing value in table view as `undefined`
  packages/editor-ui/src/components/RunDataTable.vue
Labels: ui, n8n team
