Repository n8n-io/n8n, pull requests merged in 2022-11, with the labels that each got.

#4491 fix(core): fix workflow hasing for MySQL
  packages/cli/src/databases/entities/WorkflowEntity.ts
  packages/cli/src/utils.ts
Labels: core, n8n team

#4476 feat(Venafi TLS Protect Cloud Node): make issuing template depend on application
  packages/nodes-base/nodes/Venafi/ProtectCloud/CertificateRequestDescription.ts
  packages/nodes-base/nodes/Venafi/ProtectCloud/VenafiTlsProtectCloud.node.ts
Labels: node/improvement, n8n team

#4494 fix(editor): fix node creator search when there's active subcategory
  packages/editor-ui/src/components/Node/NodeCreator/CategorizedItems.vue
  packages/editor-ui/src/components/Node/NodeCreator/TriggerHelperPanel.vue
  packages/editor-ui/src/utils.ts
Labels: ui, n8n team

#4497 fix(editor): fix interim updates on executions view
  packages/editor-ui/src/components/ExecutionsView/ExecutionsView.vue
Labels: ui, n8n team

#4499 fix(editor): fix an issue with not being able to save some of the forms
  packages/design-system/src/components/N8nFormInput/FormInput.vue
Labels: ui, n8n team

#4493 fix(editor): disable settings link in executions view for unsaved workflows
  packages/design-system/src/components/N8nInfoAccordion/InfoAccordion.vue
  packages/editor-ui/src/components/ExecutionsView/ExecutionsInfoAccordion.vue
  packages/editor-ui/src/plugins/i18n/locales/en.json
Labels: ui, n8n team

#4460 fix: displayOptions not getting value of RLC
  packages/workflow/src/NodeHelpers.ts
Labels: core, n8n team

#4498 refactor(editor): put editor theme behind local storage flag
  packages/editor-ui/src/App.vue
  packages/editor-ui/src/constants.ts
Labels: ui, n8n team

#4508 fix(core): prevent double quotes on luxon datetimes
  packages/nodes-base/nodes/Code/utils.ts
Labels: node/improvement, n8n team

#4503 perf(editor): improve array intersection utility function
  packages/editor-ui/src/utils.test.ts
  packages/editor-ui/src/utils.ts
Labels: ui, n8n team

#4511 fix(editor): workflow settings link font size change (no-changelog)
  packages/editor-ui/src/components/ExecutionsView/ExecutionsInfoAccordion.vue
Labels: ui, n8n team

#4505 fix(core): make `deepCopy` backward compatible
  packages/nodes-base/nodes/Code/utils.ts
  packages/workflow/src/NodeErrors.ts
  packages/workflow/src/utils.ts
  packages/workflow/test/utils.test.ts
Labels: core, n8n team

#4504 :zap: Add pagination to synchronization table
  packages/cli/src/Ldap/helpers.ts
  packages/cli/src/Ldap/routes/ldap.controller.ee.ts
  packages/cli/src/Ldap/types.d.ts
  packages/editor-ui/package.json
  packages/editor-ui/src/api/ldap.ts
  packages/editor-ui/src/modules/settings.ts
  packages/editor-ui/src/views/SettingsLdapView.vue
Labels: core, ui, n8n team

#4496 refactor(editor): restrict mapping discoverability tooltip showing only on string input
  packages/editor-ui/src/components/ParameterInput.vue
  packages/editor-ui/src/components/ParameterInputFull.vue
  packages/editor-ui/src/components/ParameterInputWrapper.vue
  packages/editor-ui/src/plugins/i18n/index.ts
Labels: ui, n8n team

#4521 fix(editor): fix themes the monaco editor (no-changelog)
  packages/editor-ui/src/components/forms/CodeEditor.vue
Labels: ui, n8n team

#4522 refactor: consolidate database configs
  packages/cli/config/schema.ts
  packages/cli/src/Db.ts
  packages/cli/src/databases/config.ts
  packages/cli/src/databases/ormconfig.ts
Labels: core, n8n team

#4487 fix(HTTP Request Node): use the data in "Put Output in Field" field
  packages/nodes-base/nodes/HttpRequest/V3/HttpRequestV3.node.ts
Labels: node/improvement, n8n team

#4526 fix(editor): Curb arg linting for `$input.first()` and `$input.last()`
  packages/editor-ui/src/components/CodeNodeEditor/linter.ts
Labels: ui, n8n team

#4394 feat(API): Set up error tracking using Sentry
  .vscode/launch.json
  docker/images/n8n-debian/Dockerfile
  docker/images/n8n-rhel7/Dockerfile
  docker/images/n8n/Dockerfile
  package-lock.json
  packages/cli/config/schema.ts
  packages/cli/package.json
  packages/cli/src/ActiveWorkflowRunner.ts
  packages/cli/src/CommunityNodes/helpers.ts
  packages/cli/src/CredentialsHelper.ts
  packages/cli/src/ErrorReporting.ts
  packages/cli/src/LoadNodesAndCredentials.ts
  packages/cli/src/ResponseHelper.ts
  packages/cli/src/Server.ts
  packages/cli/src/UserManagement/email/NodeMailer.ts
  packages/cli/src/UserManagement/routes/users.ts
  packages/cli/src/WaitTracker.ts
  packages/cli/src/WebhookHelpers.ts
  packages/cli/src/WebhookServer.ts
  packages/cli/src/WorkflowExecuteAdditionalData.ts
  packages/cli/src/WorkflowHelpers.ts
  packages/cli/src/WorkflowRunner.ts
  packages/cli/src/WorkflowRunnerProcess.ts
  packages/core/src/UserSettings.ts
  packages/workflow/src/ErrorReporterProxy.ts
  packages/workflow/src/index.ts
  packages/workflow/src/utils.ts
Labels: core, n8n team

#4416 refactor(editor): Encapsulate canvas actions
  packages/editor-ui/src/components/CanvasControls.vue
  packages/editor-ui/src/components/mixins/moveNodeWorkflow.ts
  packages/editor-ui/src/declarations/normalize-wheel.d.ts
  packages/editor-ui/src/stores/canvas.ts
  packages/editor-ui/src/views/NodeView.vue
Labels: ui, n8n team

#4532 fix(API): Do not use names for typeorm connections
  packages/cli/src/databases/config.ts
Labels: core, n8n team

#4524 fix(editor): Switch `CodeNodeEditor` linter parser to `esprima-next`
  package-lock.json
  packages/editor-ui/package.json
  packages/editor-ui/src/components/CodeNodeEditor/linter.ts
  packages/editor-ui/src/components/CodeNodeEditor/utils.ts
Labels: ui, n8n team

#4513 fix(editor): Showing string numbers and null properly in JSON view
  package-lock.json
  packages/editor-ui/package.json
  packages/editor-ui/src/__tests__/setup.ts
  packages/editor-ui/src/components/RunData.vue
  packages/editor-ui/src/components/RunDataJson.test.ts
  packages/editor-ui/src/components/RunDataJson.vue
Labels: ui, n8n team

#4518 ci: Start supporting node.js 18
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/workflows/ci-master.yml
  .github/workflows/ci-postgres-mysql.yml
  .github/workflows/ci-pull-requests.yml
  .github/workflows/test-workflows.yml
  docker/images/n8n-custom/Dockerfile
  docker/images/n8n/README.md
  package-lock.json
  packages/cli/package.json
  packages/core/package.json
  packages/editor-ui/package.json
  packages/node-dev/package.json
  packages/nodes-base/package.json
  packages/workflow/package.json
Labels: core, ui, n8n team

#4536 refactor(core): Skip interim updates check (no-changelog)
  packages/cli/src/workflows/workflows.services.ts
  packages/cli/test/integration/workflows.controller.ee.test.ts
Labels: core, n8n team

#4538 fix(HTTP Request Node): Show error cause in the output
  packages/workflow/src/NodeErrors.ts
Labels: core, n8n team

#4535 fix(core): Fix manual execution of pinned trigger on main mode
  packages/cli/src/WorkflowRunner.ts
Labels: core, n8n team

#3490 feat: Add cypress e2e tests for signup and signin
  .github/workflows/ci-master.yml
  .github/workflows/ci-pull-requests.yml
  .gitignore
  cypress.config.js
  cypress/constants.ts
  cypress/e2e/0-smoke.cy.ts
  cypress/pages/base.ts
  cypress/pages/index.ts
  cypress/pages/signin.ts
  cypress/pages/signup.ts
  cypress/pages/workflows.ts
  cypress/support/commands.ts
  cypress/support/e2e.ts
  cypress/support/index.ts
  cypress/types.ts
  package-lock.json
  package.json
  packages/design-system/src/components/N8nFormInputs/FormInputs.vue
  packages/editor-ui/src/components/NodeDetailsView.vue
  packages/editor-ui/src/components/NodeSettings.vue
  packages/editor-ui/src/components/PersonalizationModal.vue
  packages/editor-ui/src/components/SaveButton.vue
  packages/editor-ui/src/views/AuthView.vue
  packages/editor-ui/src/views/SetupView.vue
  packages/editor-ui/src/views/SigninView.vue
Labels: ui, n8n team

#4357 fix(SendInBlue Trigger Node): fix typo in credential name
  packages/nodes-base/nodes/SendInBlue/GenericFunctions.ts
Labels: node/improvement, community

#4548 feat(API): Report unhandled app crashes to Sentry
  packages/cli/commands/executeBatch.ts
  packages/cli/commands/start.ts
  packages/cli/commands/webhook.ts
  packages/cli/commands/worker.ts
  packages/cli/src/CrashJournal.ts
  packages/cli/src/ErrorReporting.ts
  packages/cli/src/Server.ts
  packages/cli/src/WebhookServer.ts
  packages/cli/src/WorkflowRunnerProcess.ts
  packages/nodes-base/nodes/Discord/Discord.node.ts
  packages/nodes-base/nodes/HttpRequest/V1/HttpRequestV1.node.ts
  packages/nodes-base/nodes/HttpRequest/V2/HttpRequestV2.node.ts
  packages/nodes-base/nodes/HttpRequest/V3/HttpRequestV3.node.ts
  packages/nodes-base/nodes/RabbitMQ/GenericFunctions.ts
  packages/nodes-base/nodes/Twitter/GenericFunctions.ts
  packages/workflow/src/index.ts
  packages/workflow/src/utils.ts
Labels: node/improvement, core, n8n team

#4547 fix(editor): Fix for incorrect execution saving indicator in executions view
  packages/editor-ui/src/components/ExecutionsView/ExecutionsInfoAccordion.vue
Labels: ui

#4549 fix(editor): Fix workflow activation from the Workflows view
  packages/editor-ui/src/Interface.ts
  packages/editor-ui/src/components/WorkflowActivator.vue
  packages/editor-ui/src/components/WorkflowCard.vue
  packages/editor-ui/src/components/WorkflowSettings.vue
  packages/editor-ui/src/components/mixins/workflowHelpers.ts
  packages/editor-ui/src/stores/workflows.ts
  packages/editor-ui/src/views/NodeView.vue
Labels: ui, n8n team

#4542 fix(Raindrop Node): Update access token URL
  packages/nodes-base/credentials/RaindropOAuth2Api.credentials.ts
Labels: node/improvement, n8n team

#4546 fix(editor): Fix workflow back button navigation
  packages/editor-ui/src/App.vue
  packages/editor-ui/src/components/SettingsSidebar.vue
  packages/editor-ui/src/components/mixins/workflowHelpers.ts
  packages/editor-ui/src/router.ts
  packages/editor-ui/src/views/NodeView.vue
  packages/editor-ui/src/views/SettingsApiView.vue
  packages/editor-ui/src/views/SettingsCommunityNodesView.vue
  packages/editor-ui/src/views/SettingsFakeDoorView.vue
  packages/editor-ui/src/views/SettingsPersonalView.vue
  packages/editor-ui/src/views/SettingsUsersView.vue
  packages/editor-ui/src/views/SettingsView.vue
Labels: ui, n8n team

#4554 fix(Notion (Beta) Node): Fix import in credentials
  packages/nodes-base/credentials/NotionApi.credentials.ts
Labels: n8n team, node/issue

#4556 fix: Update E2E testing env variables
  package.json
Labels: n8n team

#4557 feat(editor): Add support for notice credentials properties
  packages/editor-ui/src/components/CredentialEdit/CredentialInputs.vue
Labels: ui, n8n team

#4550 fix(editor): Tweak dragged mapping state
  packages/editor-ui/src/components/ParameterInput.vue
Labels: ui, n8n team

#4559 fix(editor): Fix duplicate bug when new workflow is open
  packages/editor-ui/src/components/DuplicateWorkflowDialog.vue
Labels: ui, n8n team

#4560 fix(editor): Use base path in workflow preview component URL
  packages/editor-ui/src/components/WorkflowPreview.vue
  packages/editor-ui/src/stores/n8nRootStore.ts
Labels: ui, n8n team

#4429 feat: Switch from npm to pnpm
  .dockerignore
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/workflows/ci-master.yml
  .github/workflows/ci-postgres-mysql.yml
  .github/workflows/ci-pull-requests.yml
  .github/workflows/test-workflows.yml
  .gitignore
  .npmrc
  .vscode/settings.default.json
  CONTRIBUTING.md
  docker/images/n8n-custom/Dockerfile
  package-lock.json
  package.json
  packages/@n8n_io/eslint-config/frontend.js
  packages/@n8n_io/eslint-config/node.js
  packages/@n8n_io/eslint-config/package.json
  packages/cli/BREAKING-CHANGES.md
  packages/cli/package.json
  packages/core/package.json
  packages/design-system/README.md
  packages/design-system/package.json
  packages/editor-ui/README.md
  packages/editor-ui/package.json
  packages/editor-ui/src/plugins/i18n/docs/README.md
  packages/node-dev/package.json
  packages/nodes-base/package.json
  packages/workflow/package.json
  patches/quill@2.0.0-dev.4.patch
  pnpm-lock.yaml
  pnpm-workspace.yaml
  scripts/format.mjs
  tsconfig.json
  turbo.json
Labels: core, ui, n8n team

#4564 fix(editor): Prevent adding of the start node when importing workflow in the demo mode
  packages/editor-ui/src/views/canvasHelpers.ts
Labels: ui, n8n team

#4570 fix(HubSpot Node): Add notice to HubSpot credentials about API Key Sunset
  packages/nodes-base/credentials/HubspotApi.credentials.ts
Labels: node/improvement, n8n team

#4569 fix(core): Streamline multiple pinned triggers behavior
  packages/cli/src/workflows/workflows.controller.ts
  packages/cli/src/workflows/workflows.services.ts
Labels: core, n8n team

#4553 refactor(editor): Reintroduce `item` and `items` to `CodeNodeEditor`
  packages/editor-ui/src/components/CodeNodeEditor/completer.ts
  packages/editor-ui/src/components/CodeNodeEditor/completions/base.completions.ts
  packages/editor-ui/src/components/CodeNodeEditor/linter.ts
  packages/editor-ui/src/plugins/i18n/locales/en.json
  packages/nodes-base/nodes/Code/Code.node.ts
  packages/nodes-base/nodes/Code/Sandbox.ts
Labels: node/improvement, ui, n8n team

#4576 refactor: Replace recommended extension for Vue
  .vscode/extensions.json
Labels: n8n team

#4573 refactor(editor): Add Workflows view e2e tests
  cypress/e2e/1-workflows.cy.ts
  cypress/fixtures/Test_workflow_1.json
  cypress/fixtures/Test_workflow_2.json
  cypress/pages/workflow.ts
  cypress/pages/workflows.ts
  cypress/support/commands.ts
  cypress/support/index.ts
  cypress/types.ts
  packages/design-system/src/components/N8nActionToggle/ActionToggle.vue
  packages/editor-ui/src/components/MainHeader/WorkflowDetails.vue
  packages/editor-ui/src/components/WorkflowActivator.vue
  packages/editor-ui/src/components/WorkflowCard.vue
  packages/editor-ui/src/components/layouts/ResourcesListLayout.vue
  packages/editor-ui/src/views/WorkflowsView.vue
Labels: ui, n8n team

#4481 feat(core): Add credential runtime checks and prevent tampering in manual run
  packages/cli/src/UserManagement/PermissionChecker.ts
  packages/cli/src/UserManagement/UserManagementHelper.ts
  packages/cli/src/WorkflowExecuteAdditionalData.ts
  packages/cli/src/WorkflowRunner.ts
  packages/cli/src/WorkflowRunnerProcess.ts
  packages/cli/src/commands/worker.ts
  packages/cli/src/requests.d.ts
  packages/cli/src/workflows/workflows.controller.ee.ts
  packages/cli/src/workflows/workflows.controller.ts
  packages/cli/src/workflows/workflows.services.ee.ts
  packages/cli/src/workflows/workflows.services.ts
  packages/cli/test/integration/shared/random.ts
  packages/cli/test/integration/shared/testDb.ts
  packages/cli/test/integration/workflows.controller.ee.test.ts
  packages/cli/test/unit/Helpers.ts
  packages/cli/test/unit/PermissionChecker.test.ts
Labels: core, n8n team, User Management

#4319 fix(core): Deduplicate error handling in nodes
  packages/nodes-base/nodes/ActionNetwork/GenericFunctions.ts
  packages/nodes-base/nodes/Airtable/GenericFunctions.ts
  packages/nodes-base/nodes/Aws/Comprehend/GenericFunctions.ts
  packages/nodes-base/nodes/Aws/Rekognition/GenericFunctions.ts
  packages/nodes-base/nodes/Aws/S3/GenericFunctions.ts
  packages/nodes-base/nodes/Beeminder/GenericFunctions.ts
  packages/nodes-base/nodes/Calendly/GenericFunctions.ts
  packages/nodes-base/nodes/Clockify/GenericFunctions.ts
  packages/nodes-base/nodes/Cortex/GenericFunctions.ts
  packages/nodes-base/nodes/CustomerIo/GenericFunctions.ts
  packages/nodes-base/nodes/Dropcontact/GenericFunction.ts
  packages/nodes-base/nodes/ERPNext/GenericFunctions.ts
  packages/nodes-base/nodes/Ghost/GenericFunctions.ts
  packages/nodes-base/nodes/HighLevel/GenericFunctions.ts
  packages/nodes-base/nodes/Jira/GenericFunctions.ts
  packages/nodes-base/nodes/Lemlist/GenericFunctions.ts
  packages/nodes-base/nodes/Mailjet/GenericFunctions.ts
  packages/nodes-base/nodes/NextCloud/GenericFunctions.ts
  packages/nodes-base/nodes/NocoDB/GenericFunctions.ts
  packages/nodes-base/nodes/Rocketchat/GenericFunctions.ts
  packages/nodes-base/nodes/Segment/GenericFunctions.ts
  packages/nodes-base/nodes/SendGrid/GenericFunctions.ts
  packages/nodes-base/nodes/Shopify/GenericFunctions.ts
  packages/nodes-base/nodes/Stripe/helpers.ts
  packages/nodes-base/nodes/TheHive/GenericFunctions.ts
  packages/nodes-base/nodes/Trello/GenericFunctions.ts
  packages/nodes-base/nodes/Twake/GenericFunctions.ts
  packages/nodes-base/nodes/Twilio/GenericFunctions.ts
  packages/nodes-base/nodes/UrlScanIo/GenericFunctions.ts
  packages/nodes-base/nodes/Webflow/GenericFunctions.ts
  packages/nodes-base/nodes/Wekan/GenericFunctions.ts
  packages/nodes-base/nodes/WooCommerce/GenericFunctions.ts
  packages/nodes-base/nodes/Wufoo/GenericFunctions.ts
  packages/nodes-base/nodes/Zendesk/GenericFunctions.ts
  packages/workflow/src/NodeErrors.ts
Labels: node/improvement, n8n team

#4340 feat(Notion (Beta) Node): Use resource locator component for database and page parameters
  packages/core/src/NodeExecuteFunctions.ts
  packages/nodes-base/nodes/Notion/BlockDescription.ts
  packages/nodes-base/nodes/Notion/Blocks.ts
  packages/nodes-base/nodes/Notion/DatabaseDescription.ts
  packages/nodes-base/nodes/Notion/DatabasePageDescription.ts
  packages/nodes-base/nodes/Notion/Filters.ts
  packages/nodes-base/nodes/Notion/GenericFunctions.ts
  packages/nodes-base/nodes/Notion/NotionTrigger.node.ts
  packages/nodes-base/nodes/Notion/PageDescription.ts
  packages/nodes-base/nodes/Notion/SearchFunctions.ts
  packages/nodes-base/nodes/Notion/v1/NotionV1.node.ts
  packages/nodes-base/nodes/Notion/v2/NotionV2.node.ts
  packages/workflow/src/Interfaces.ts
Labels: node/improvement, n8n team

#4584 refactor: Remove unused vars to fix build (no-changelog)
  .github/workflows/ci-master.yml
  packages/@n8n_io/eslint-config/base.js
  packages/nodes-base/nodes/ActionNetwork/GenericFunctions.ts
  packages/nodes-base/nodes/Airtable/GenericFunctions.ts
  packages/nodes-base/nodes/Aws/Comprehend/GenericFunctions.ts
  packages/nodes-base/nodes/Aws/Rekognition/GenericFunctions.ts
  packages/nodes-base/nodes/Aws/S3/GenericFunctions.ts
  packages/nodes-base/nodes/Beeminder/GenericFunctions.ts
  packages/nodes-base/nodes/Calendly/GenericFunctions.ts
  packages/nodes-base/nodes/Clockify/GenericFunctions.ts
  packages/nodes-base/nodes/Cortex/GenericFunctions.ts
  packages/nodes-base/nodes/CustomerIo/GenericFunctions.ts
  packages/nodes-base/nodes/Dropcontact/GenericFunction.ts
  packages/nodes-base/nodes/Ghost/GenericFunctions.ts
  packages/nodes-base/nodes/Jira/GenericFunctions.ts
  packages/nodes-base/nodes/Lemlist/GenericFunctions.ts
  packages/nodes-base/nodes/Mailjet/GenericFunctions.ts
  packages/nodes-base/nodes/NextCloud/GenericFunctions.ts
  packages/nodes-base/nodes/NocoDB/GenericFunctions.ts
  packages/nodes-base/nodes/Notion/NotionTrigger.node.ts
  packages/nodes-base/nodes/Rocketchat/GenericFunctions.ts
  packages/nodes-base/nodes/Segment/GenericFunctions.ts
  packages/nodes-base/nodes/SendGrid/GenericFunctions.ts
  packages/nodes-base/nodes/Shopify/GenericFunctions.ts
  packages/nodes-base/nodes/Stripe/helpers.ts
  packages/nodes-base/nodes/TheHive/GenericFunctions.ts
  packages/nodes-base/nodes/Trello/GenericFunctions.ts
  packages/nodes-base/nodes/Twake/GenericFunctions.ts
  packages/nodes-base/nodes/Twilio/GenericFunctions.ts
  packages/nodes-base/nodes/UrlScanIo/GenericFunctions.ts
  packages/nodes-base/nodes/Webflow/GenericFunctions.ts
  packages/nodes-base/nodes/Wekan/GenericFunctions.ts
  packages/nodes-base/nodes/WooCommerce/GenericFunctions.ts
  packages/nodes-base/nodes/Wufoo/GenericFunctions.ts
  packages/nodes-base/nodes/Zendesk/GenericFunctions.ts
Labels: node/improvement, n8n team

#4585 fix: Fix inferred type of X cannot be named error after pnpm update (no-changelog)
  packages/cli/tsconfig.json
  tsconfig.json
Labels: n8n team

#4575 fix(editor): Fix for execution retry dropdown not closing
  packages/design-system/src/components/N8nActionDropdown/ActionDropdown.vue
  packages/editor-ui/src/components/ExecutionsView/ExecutionPreview.vue
  packages/editor-ui/src/components/ExecutionsView/ExecutionsView.vue
Labels: ui, n8n team

#4592 fix(editor): Skip optional chaining operators in Code Node editor linting
  packages/editor-ui/src/components/CodeNodeEditor/linter.ts
Labels: ui, n8n team

#4591 fix(editor): Curb direct item access linting
  packages/editor-ui/src/components/CodeNodeEditor/linter.ts
Labels: ui, n8n team

#4590 fix(editor): Fix expression editor variable selector filter
  packages/editor-ui/src/components/VariableSelector.vue
Labels: ui, n8n team

#4581 refactor: Remove Vetur config (no-changelog)
  vetur.config.js
Labels: n8n team

#4595 fix(editor): Hide pin data in production executions
  packages/editor-ui/src/components/ExecutionsView/ExecutionPreview.vue
  packages/editor-ui/src/components/InputPanel.vue
  packages/editor-ui/src/components/Node.vue
  packages/editor-ui/src/components/NodeDetailsView.vue
  packages/editor-ui/src/components/OutputPanel.vue
  packages/editor-ui/src/components/RunData.vue
  packages/editor-ui/src/components/WorkflowPreview.vue
  packages/editor-ui/src/views/NodeView.vue
Labels: ui, n8n team

#4589 build: Upgrade some of the backend dev-tooling (no-changelog)
  jest.config.js
  package.json
  packages/@n8n_io/eslint-config/package.json
  packages/cli/bin/n8n
  packages/cli/package.json
  packages/core/package.json
  packages/core/src/Interfaces.ts
  packages/core/src/NodeExecuteFunctions.ts
  packages/core/src/WorkflowExecute.ts
  packages/core/src/index.ts
  packages/editor-ui/package.json
  packages/nodes-base/package.json
  packages/workflow/src/Interfaces.ts
  packages/workflow/src/WorkflowHooks.ts
  pnpm-lock.yaml
Labels: core, ui, n8n team

#4582 refactor(core): Enable interim updates check
  packages/cli/src/workflows/workflows.services.ts
  packages/cli/test/integration/workflows.controller.ee.test.ts
Labels: core, n8n team

#4563 feat(editor): Integrate CodeMirror into expression editor modal
  packages/editor-ui/.eslintrc.js
  packages/editor-ui/src/components/ExpressionEdit.vue
  packages/editor-ui/src/components/ExpressionEditorModal/ExpressionModalInput.vue
  packages/editor-ui/src/components/ExpressionEditorModal/ExpressionModalOutput.vue
  packages/editor-ui/src/components/ExpressionEditorModal/braceHandler.ts
  packages/editor-ui/src/components/ExpressionEditorModal/colorDecorations.ts
  packages/editor-ui/src/components/ExpressionEditorModal/n8nLanguagePack/index.cjs
  packages/editor-ui/src/components/ExpressionEditorModal/n8nLanguagePack/index.d.cts
  packages/editor-ui/src/components/ExpressionEditorModal/n8nLanguagePack/index.d.ts
  packages/editor-ui/src/components/ExpressionEditorModal/n8nLanguagePack/index.js
  packages/editor-ui/src/components/ExpressionEditorModal/n8nLanguageSupport.ts
  packages/editor-ui/src/components/ExpressionEditorModal/resolvable.completions.ts
  packages/editor-ui/src/components/ExpressionEditorModal/theme.ts
  packages/editor-ui/src/components/ExpressionEditorModal/types.ts
  packages/editor-ui/src/components/VariableSelector.vue
  packages/editor-ui/src/components/VariableSelectorItem.vue
  packages/editor-ui/src/constants.ts
  packages/editor-ui/src/plugins/i18n/locales/en.json
Labels: ui, n8n team

#4600 feat(editor): Adjust resolved expression to match parameter input hint
  packages/editor-ui/src/components/ExpressionEditorModal/ExpressionModalInput.vue
  packages/editor-ui/src/components/ExpressionEditorModal/ExpressionModalOutput.vue
  packages/editor-ui/src/components/ExpressionEditorModal/colorDecorations.ts
  packages/editor-ui/src/components/ParameterInputWrapper.vue
  packages/editor-ui/tslint.json
Labels: ui, n8n team

#4606 fix: Change feature flag for starting at empty WF state for PH experiments (no-changelog)
  packages/editor-ui/src/router.ts
Labels: n8n team

#4370 feat: Add workflow sharing functionality and permissions
  packages/cli/src/config/schema.ts
  packages/design-system/src/components/N8nUsersList/UsersList.vue
  packages/editor-ui/src/Interface.ts
  packages/editor-ui/src/api/credentials.ts
  packages/editor-ui/src/api/workflows.ee.ts
  packages/editor-ui/src/components/CredentialEdit/CredentialSharing.ee.vue
  packages/editor-ui/src/components/MainHeader/WorkflowDetails.vue
  packages/editor-ui/src/components/Modals.vue
  packages/editor-ui/src/components/NodeCredentials.vue
  packages/editor-ui/src/components/NodeDetailsView.vue
  packages/editor-ui/src/components/NodeSettings.vue
  packages/editor-ui/src/components/WorkflowCard.vue
  packages/editor-ui/src/components/WorkflowShareModal.ee.vue
  packages/editor-ui/src/components/mixins/nodeHelpers.ts
  packages/editor-ui/src/components/mixins/pushConnection.ts
  packages/editor-ui/src/components/mixins/showMessage.ts
  packages/editor-ui/src/constants.ts
  packages/editor-ui/src/event-bus/node-view-event-bus.ts
  packages/editor-ui/src/permissions.ts
  packages/editor-ui/src/plugins/i18n/locales/en.json
  packages/editor-ui/src/stores/credentials.ts
  packages/editor-ui/src/stores/ui.ts
  packages/editor-ui/src/stores/users.ts
  packages/editor-ui/src/stores/workflows.ee.ts
  packages/editor-ui/src/stores/workflows.ts
  packages/editor-ui/src/views/NodeView.vue
  packages/editor-ui/src/views/WorkflowsView.vue
Labels: ui, n8n team

#3948 feat(Google Sheets Node): Overhaul of node
  packages/nodes-base/credentials/GoogleSheetsOAuth2Api.credentials.ts
  packages/nodes-base/nodes/Google/Sheet/GoogleSheets.node.ts
  packages/nodes-base/nodes/Google/Sheet/v1/GenericFunctions.ts
  packages/nodes-base/nodes/Google/Sheet/v1/GoogleSheet.ts
  packages/nodes-base/nodes/Google/Sheet/v1/GoogleSheetsV1.node.ts
  packages/nodes-base/nodes/Google/Sheet/v1/versionDescription.ts
  packages/nodes-base/nodes/Google/Sheet/v2/GoogleSheetsV2.node.ts
  packages/nodes-base/nodes/Google/Sheet/v2/actions/router.ts
  packages/nodes-base/nodes/Google/Sheet/v2/actions/sheet/Sheet.resource.ts
  packages/nodes-base/nodes/Google/Sheet/v2/actions/sheet/append.operation.ts
  packages/nodes-base/nodes/Google/Sheet/v2/actions/sheet/appendOrUpdate.operation.ts
  packages/nodes-base/nodes/Google/Sheet/v2/actions/sheet/clear.operation.ts
  packages/nodes-base/nodes/Google/Sheet/v2/actions/sheet/commonDescription.ts
  packages/nodes-base/nodes/Google/Sheet/v2/actions/sheet/create.operation.ts
  packages/nodes-base/nodes/Google/Sheet/v2/actions/sheet/delete.operation.ts
  packages/nodes-base/nodes/Google/Sheet/v2/actions/sheet/read.operation.ts
  packages/nodes-base/nodes/Google/Sheet/v2/actions/sheet/remove.operation.ts
  packages/nodes-base/nodes/Google/Sheet/v2/actions/sheet/update.operation.ts
  packages/nodes-base/nodes/Google/Sheet/v2/actions/spreadsheet/SpreadSheet.resource.ts
  packages/nodes-base/nodes/Google/Sheet/v2/actions/spreadsheet/create.operation.ts
  packages/nodes-base/nodes/Google/Sheet/v2/actions/spreadsheet/delete.operation.ts
  packages/nodes-base/nodes/Google/Sheet/v2/actions/versionDescription.ts
  packages/nodes-base/nodes/Google/Sheet/v2/helpers/GoogleSheet.ts
  packages/nodes-base/nodes/Google/Sheet/v2/helpers/GoogleSheets.types.ts
  packages/nodes-base/nodes/Google/Sheet/v2/helpers/GoogleSheets.utils.ts
  packages/nodes-base/nodes/Google/Sheet/v2/methods/credentialTest.ts
  packages/nodes-base/nodes/Google/Sheet/v2/methods/index.ts
  packages/nodes-base/nodes/Google/Sheet/v2/methods/listSearch.ts
  packages/nodes-base/nodes/Google/Sheet/v2/methods/loadOptions.ts
  packages/nodes-base/nodes/Google/Sheet/v2/transport/index.ts
Labels: node/improvement, n8n team

#4613 ci: Fix linting by ignoring eslintrc and jest.config again (no-changelog)
  packages/@n8n_io/eslint-config/base.js
Labels: n8n team

#4614 :zap: Flatten feature configuration
  packages/cli/src/Ldap/LdapService.ee.ts
  packages/cli/src/Ldap/LdapSync.ee.ts
  packages/cli/src/Ldap/constants.ts
  packages/cli/src/Ldap/helpers.ts
  packages/cli/src/Ldap/routes/ldap.controller.ee.ts
  packages/cli/src/Ldap/types.d.ts
  packages/cli/src/UserAuthentication/methods/ldap.ts
  packages/cli/test/integration/ldap/ldap.api.test.ts
  packages/editor-ui/src/Interface.ts
  packages/editor-ui/src/views/SettingsLdapView.vue
Labels: core, ui, n8n team

#4612 fix(editor): Fix zero treated as missing value in resource locator
  packages/workflow/src/NodeHelpers.ts
  packages/workflow/src/type-guards.ts
Labels: core, n8n team

#4562 feat(editor): Generate custom schema from data
  packages/editor-ui/src/Interface.ts
  packages/editor-ui/src/utils.test.ts
  packages/editor-ui/src/utils.ts
Labels: core, n8n team

#4617 fix: Add missing content type to controllers (no-changelog)
  packages/cli/src/credentials/credentials.controller.ee.ts
  packages/cli/src/workflows/workflows.controller.ee.ts
Labels: core, n8n team

#4620 feat(editor): Add date recognizer util function
  packages/editor-ui/src/utils.test.ts
  packages/editor-ui/src/utils.ts
Labels: ui, n8n team

#4605 feat(Compare Datasets Node): Node tweaks
  packages/nodes-base/nodes/CompareDatasets/CompareDatasets.node.ts
  packages/nodes-base/nodes/CompareDatasets/GenericFunctions.ts
Labels: node/improvement, n8n team, node/issue

#4625 feat(editor): Dynamically delay evaluation resolution
  packages/editor-ui/src/components/ExpressionEditorModal/ExpressionModalInput.vue
  packages/editor-ui/src/plugins/i18n/locales/en.json
Labels: ui, n8n team

#4624 fix: Fix storybook (no-changelog)
  packages/design-system/.eslintrc.js
  packages/design-system/src/components/N8nFormInput/FormInput.vue
  packages/design-system/src/components/N8nFormInput/validators.ts
  packages/design-system/src/components/N8nMenu/Menu.vue
  packages/design-system/src/components/N8nMenuItem/MenuItem.vue
  packages/design-system/src/components/N8nNotice/Notice.vue
  packages/design-system/src/components/N8nUserSelect/UserSelect.vue
  packages/design-system/src/components/utils/helpers.ts
Labels: ui, n8n team

#4628 :zap: Transform email user to LDAP user when possible
  packages/cli/src/Ldap/helpers.ts
  packages/cli/src/Ldap/routes/ldap.controller.ee.ts
  packages/cli/src/UserAuthentication/methods/ldap.ts
  packages/cli/src/databases/entities/User.ts
  packages/cli/test/integration/ldap/ldap.api.test.ts
Labels: core, n8n team

#4630 ci: Fix workflows tests (no-changelog)
  .github/workflows/test-workflows.yml
Labels: n8n team

#4627 refactor(editor): Pre-review cleanup
  docker/images/n8n-custom/Dockerfile
  package.json
  packages/editor-ui/package.json
  packages/editor-ui/src/components/ExpressionEdit.vue
  packages/editor-ui/src/components/ExpressionEditorModal/ExpressionModalOutput.vue
  packages/editor-ui/src/components/ExpressionEditorModal/resolvable.completions.ts
  packages/editor-ui/src/components/ExpressionInput.vue
  packages/editor-ui/src/components/VariableSelectorItem.vue
  packages/editor-ui/src/plugins/i18n/locales/en.json
  packages/workflow/src/Expression.ts
  patches/quill@2.0.0-dev.4.patch
  pnpm-lock.yaml
Labels: core, ui, n8n team

#4616 feat: Add duplicate workflow error handler
  packages/editor-ui/src/components/DuplicateWorkflowDialog.vue
  packages/editor-ui/src/plugins/i18n/locales/en.json
Labels: ui, n8n team

#4618 feat: Add workflow data reset action
  packages/editor-ui/src/stores/workflows.ee.ts
  packages/editor-ui/src/stores/workflows.ts
  packages/editor-ui/src/views/NodeView.vue
Labels: ui, n8n team

#4622 fix: Fix foreign credentials being shown for new nodes
  packages/editor-ui/src/Interface.ts
  packages/editor-ui/src/components/NodeDetailsView.vue
  packages/editor-ui/src/stores/credentials.ts
  packages/editor-ui/src/stores/workflows.ts
  packages/editor-ui/src/views/NodeView.vue
Labels: ui, n8n team

#4637 fix: store copy of workflow in workflowsById to prevent node data bugs
  packages/editor-ui/src/stores/workflows.ts
  packages/editor-ui/src/views/NodeView.vue
Labels: ui, n8n team

#4638 ci: Send Slack notifications when important builds fail (no-changelog)
  .github/workflows/ci-master.yml
  .github/workflows/ci-postgres-mysql.yml
  .github/workflows/test-workflows.yml
Labels: n8n team

#4629 :zap: Add on login disabled strategies
  packages/cli/src/Ldap/constants.ts
  packages/cli/src/Ldap/helpers.ts
  packages/cli/src/Ldap/types.d.ts
  packages/cli/src/UserAuthentication/methods/email.ts
  packages/cli/test/integration/ldap/ldap.api.test.ts
  packages/editor-ui/src/Interface.ts
  packages/editor-ui/src/views/SettingsLdapView.vue
Labels: core, ui, n8n team

#4635 refactor: Forbid access to workflows when enterprise features is unavailable
  packages/cli/src/ActiveWorkflowRunner.ts
  packages/cli/src/CredentialsHelper.ts
  packages/cli/src/Interfaces.ts
  packages/cli/src/Server.ts
  packages/cli/src/UserManagement/UserManagementHelper.ts
  packages/cli/src/WorkflowExecuteAdditionalData.ts
  packages/cli/src/WorkflowHelpers.ts
  packages/cli/src/workflows/workflows.controller.ee.ts
  packages/cli/src/workflows/workflows.controller.ts
  packages/cli/src/workflows/workflows.services.ee.ts
  packages/cli/src/workflows/workflows.services.ts
Labels: core, n8n team

#4643 fix(Google Sheets Node): Versioning fix
  packages/nodes-base/nodes/Google/Sheet/GoogleSheets.node.ts
  packages/nodes-base/nodes/Google/Sheet/v1/versionDescription.ts
  packages/nodes-base/nodes/Google/Sheet/v2/actions/versionDescription.ts
Labels: n8n team, node/issue

#4645 fix: Make users fakedoor route visible on cloud
  packages/editor-ui/src/components/SettingsSidebar.vue
Labels: ui, n8n team

#4652 fix: Add temporary slot syntax lint exceptions (no-changelog)
  packages/editor-ui/src/components/ResourceLocator/ResourceLocator.vue
  packages/editor-ui/src/components/ResourceLocator/ResourceLocatorDropdown.vue
Labels: ui, n8n team

#4659 fix(core): Fix for unused imports
  packages/nodes-base/nodes/DateTime/DateTime.node.ts
  packages/nodes-base/nodes/Discord/Discord.node.ts
  packages/nodes-base/nodes/Google/CloudNaturalLanguage/GoogleCloudNaturalLanguage.node.ts
  packages/nodes-base/nodes/Kitemaker/Kitemaker.node.ts
  packages/nodes-base/nodes/MQTT/Mqtt.node.ts
  packages/nodes-base/nodes/QuestDb/QuestDb.node.ts
Labels: n8n team, node/issue

#4660 refactor(editor): Apply styling feedback to expression editor modal
  packages/editor-ui/src/components/ExpressionEdit.vue
  packages/editor-ui/src/components/ExpressionEditorModal/ExpressionModalInput.vue
  packages/editor-ui/src/components/ExpressionEditorModal/ExpressionModalOutput.vue
  packages/editor-ui/src/components/ExpressionEditorModal/theme.ts
  packages/editor-ui/src/components/ParameterInputHint.vue
  packages/editor-ui/src/components/ParameterInputWrapper.vue
  packages/workflow/src/WorkflowDataProxy.ts
Labels: core, ui, n8n team

#4558 fix(Schedule Trigger Node): Fixes inconsitent behavior with cron and weekly intervals
  packages/nodes-base/nodes/Schedule/ScheduleTrigger.node.ts
Labels: node/improvement, n8n team

#4662 ci: Block execution of `npm install` (no-changelog)
  package.json
  scripts/block-npm-install.js
Labels: n8n team

#4655 fix(editor): Table view column limit tooltip
  packages/editor-ui/src/components/ResourceLocator/ResourceLocator.vue
  packages/editor-ui/src/components/RunDataTable.vue
  packages/editor-ui/src/plugins/i18n/locales/en.json
Labels: ui, n8n team

#4665 fix: Fix broken n8n-info-tip slots
  packages/design-system/src/components/N8nInfoTip/InfoTip.vue
Labels: ui, n8n team

#4668 fix: Community package uninstall button should show the confirmation modal (no-changelog)
  packages/editor-ui/src/components/CommunityPackageManageConfirmModal.vue
Labels: ui, n8n team

#4663 fix: Use the updated slots syntax in ResourceLocator (no-changelog)
  packages/editor-ui/src/components/ResourceLocator/ResourceLocator.vue
  packages/editor-ui/src/components/ResourceLocator/ResourceLocatorDropdown.vue
Labels: ui, n8n team

#4566 feat(core): Add license support to n8n
  packages/cli/package.json
  packages/cli/src/License.ts
  packages/cli/src/Server.ts
  packages/cli/src/UserManagement/UserManagementHelper.ts
  packages/cli/src/commands/license/clear.ts
  packages/cli/src/config/schema.ts
  packages/cli/src/constants.ts
  packages/cli/test/unit/License.test.ts
  pnpm-lock.yaml
Labels: core, n8n team

#4671 fix: Workflow activation should not crash if one of the credential is invalid
  packages/cli/src/workflows/workflows.services.ts
Labels: core, n8n team

#4674 feat: Use longer stack-traces when error-reporting is enabled
  packages/cli/src/ErrorReporting.ts
Labels: core, n8n team

#4670 fix(IF Node): Fix "Is Empty" and "Is Not Empty" operation fails for date objects
  packages/nodes-base/nodes/If/If.node.ts
Labels: node/improvement, n8n team

#4677 :zap: Add license SDK
  packages/cli/src/Ldap/helpers.ts
  packages/cli/src/License.ts
  packages/cli/src/constants.ts
Labels: core, n8n team

#4679 :zap: Improve LDAP logging
  packages/cli/src/Ldap/LdapService.ee.ts
  packages/cli/src/Ldap/LdapSync.ee.ts
  packages/cli/src/Ldap/helpers.ts
Labels: core, n8n team

#4657 n8n 5586 add telemetry
  packages/cli/src/Interfaces.ts
  packages/cli/src/InternalHooks.ts
  packages/cli/src/Ldap/LdapSync.ee.ts
  packages/cli/src/Ldap/constants.ts
  packages/cli/src/Ldap/helpers.ts
  packages/cli/src/Ldap/routes/ldap.controller.ee.ts
  packages/cli/src/Server.ts
  packages/cli/src/UserAuthentication/methods/email.ts
  packages/cli/src/UserAuthentication/methods/ldap.ts
  packages/cli/src/UserManagement/routes/passwordReset.ts
  packages/cli/src/UserManagement/routes/users.ts
  packages/cli/test/integration/ldap/ldap.api.test.ts
Labels: core, ui, n8n team

#4672 feat: Switch owner subview to all subview if has shared resources
  packages/editor-ui/src/components/layouts/ResourcesListLayout.vue
Labels: ui, n8n team

#4667 fix: Fix settings header text slot (no-changelog)
  packages/editor-ui/src/components/SettingsSidebar.vue
Labels: ui, n8n team

#4675 fix(core): Use CredentialsOverwrites when testing credentials
  packages/cli/src/CredentialsHelper.ts
  packages/editor-ui/src/components/CredentialEdit/CredentialEdit.vue
Labels: core, ui, n8n team

#4681 feat: Add share button to workflows list
  packages/editor-ui/src/components/MainHeader/WorkflowDetails.vue
  packages/editor-ui/src/components/Modals.vue
  packages/editor-ui/src/components/WorkflowCard.vue
  packages/editor-ui/src/components/WorkflowShareModal.ee.vue
  packages/editor-ui/src/components/mixins/workflowHelpers.ts
  packages/editor-ui/src/plugins/i18n/locales/en.json
Labels: ui, n8n team

#4682 fix: Update workflow title in workflowsById as well (no-changelog)
  packages/editor-ui/src/stores/workflows.ts
Labels: ui, n8n team

#4683 feat: Add save confirmation modal when leaving sharing modal
  packages/editor-ui/src/components/WorkflowShareModal.ee.vue
  packages/editor-ui/src/plugins/i18n/locales/en.json
Labels: ui, n8n team

#4686 feat: Show delete button based on workflow permissions
  packages/editor-ui/src/components/MainHeader/WorkflowDetails.vue
  packages/editor-ui/src/permissions.ts
Labels: ui, n8n team

#4685 refactor: Validate formatting in `nodes-base` (no-changelog)
  .prettierignore
  packages/nodes-base/.eslintrc.js
  packages/nodes-base/README.md
  packages/nodes-base/credentials/CloudflareApi.credentials.ts
  packages/nodes-base/credentials/HubspotAppToken.credentials.ts
  packages/nodes-base/credentials/MicrosoftSql.credentials.ts
  packages/nodes-base/credentials/RundeckApi.credentials.ts
  packages/nodes-base/credentials/VenafiTlsProtectDatacenterApi.credentials.ts
  packages/nodes-base/gulpfile.js
  packages/nodes-base/nodes/EmailReadImap/EmailReadImap.node.json
  packages/nodes-base/nodes/ErrorTrigger/ErrorTrigger.node.json
  packages/nodes-base/nodes/ExecuteWorkflowTrigger/ExecuteWorkflowTrigger.node.json
  packages/nodes-base/nodes/Interval/Interval.node.json
  packages/nodes-base/nodes/LocalFileTrigger/LocalFileTrigger.node.json
  packages/nodes-base/nodes/ManualTrigger/ManualTrigger.node.json
  packages/nodes-base/nodes/N8nTrigger/N8nTrigger.node.json
  packages/nodes-base/nodes/SseTrigger/SseTrigger.node.json
  packages/nodes-base/nodes/Stripe/README.md
  packages/nodes-base/nodes/WorkflowTrigger/WorkflowTrigger.node.json
  packages/nodes-base/package.json
  packages/nodes-base/tslint.json
Labels: node/improvement, n8n team

#4688 fix: Update subview switch condition (no-changelog)
  packages/editor-ui/src/components/layouts/ResourcesListLayout.vue
Labels: ui, n8n team

#4687 refactor: Improve warnings and error messages to users about sharing
  packages/cli/src/UserManagement/routes/auth.ts
  packages/cli/src/credentials/credentials.controller.ee.ts
  packages/cli/src/credentials/credentials.controller.ts
  packages/cli/src/workflows/workflows.controller.ee.ts
  packages/cli/src/workflows/workflows.controller.ts
  packages/cli/src/workflows/workflows.services.ts
  packages/cli/test/integration/workflows.controller.ee.test.ts
Labels: core, n8n team

#4689 fix: Expand `nodes-base` formatting validation (no-changelog)
  packages/nodes-base/nodes/Aws/ELB/ListenerCertificateDescription.ts
  packages/nodes-base/nodes/Aws/ELB/LoadBalancerDescription.ts
  packages/nodes-base/nodes/Citrix/ADC/CertificateDescription.ts
  packages/nodes-base/nodes/Citrix/ADC/FileDescription.ts
  packages/nodes-base/nodes/Citrix/ADC/GenericFunctions.ts
  packages/nodes-base/nodes/Cloudflare/GenericFunctions.ts
  packages/nodes-base/nodes/Cloudflare/ZoneCertificateDescription.ts
  packages/nodes-base/nodes/Elastic/Elasticsearch/GenericFunctions.ts
  packages/nodes-base/nodes/Elastic/Elasticsearch/descriptions/DocumentDescription.ts
  packages/nodes-base/nodes/ExecuteWorkflowTrigger/ExecuteWorkflowTrigger.node.ts
  packages/nodes-base/nodes/Google/Docs/interfaces.d.ts
  packages/nodes-base/nodes/HighLevel/description/TaskDescription.ts
  packages/nodes-base/nodes/If/If.node.ts
  packages/nodes-base/nodes/Keap/ContactTagDescription.ts
  packages/nodes-base/nodes/Mattermost/v1/actions/router.ts
  packages/nodes-base/nodes/Mattermost/v1/actions/user/index.ts
  packages/nodes-base/nodes/Microsoft/Outlook/FolderDescription.ts
  packages/nodes-base/nodes/Microsoft/Outlook/MessageDescription.ts
  packages/nodes-base/nodes/Microsoft/ToDo/MicrosoftToDo.node.ts
  packages/nodes-base/nodes/MondayCom/BoardItemDescription.ts
  packages/nodes-base/nodes/MongoDb/MongoDb.node.ts
  packages/nodes-base/nodes/NocoDB/OperationDescription.ts
  packages/nodes-base/nodes/Notion/BlockDescription.ts
  packages/nodes-base/nodes/Notion/Blocks.ts
  packages/nodes-base/nodes/Notion/DatabaseDescription.ts
  packages/nodes-base/nodes/Notion/DatabasePageDescription.ts
  packages/nodes-base/nodes/Notion/GenericFunctions.ts
  packages/nodes-base/nodes/Notion/PageDescription.ts
  packages/nodes-base/nodes/Notion/SearchFunctions.ts
  packages/nodes-base/nodes/PagerDuty/IncidentNoteDescription.ts
  packages/nodes-base/nodes/Phantombuster/AgentDescription.ts
  packages/nodes-base/nodes/Raindrop/GenericFunctions.ts
  packages/nodes-base/nodes/TheHive/descriptions/AlertDescription.ts
  packages/nodes-base/nodes/UProc/Json/Tools.ts
  packages/nodes-base/nodes/Venafi/Datacenter/CertificateDescription.ts
  packages/nodes-base/nodes/Venafi/ProtectCloud/CertificateDescription.ts
  packages/nodes-base/nodes/Venafi/ProtectCloud/CertificateRequestDescription.ts
  packages/nodes-base/nodes/Venafi/ProtectCloud/GenericFunctions.ts
  packages/nodes-base/package.json
Labels: node/improvement, n8n team

#4690 feat(editor): Add workflows list status filter
  packages/editor-ui/src/plugins/i18n/locales/en.json
  packages/editor-ui/src/views/WorkflowsView.vue
Labels: ui, n8n team

#4692 refactor: Consolidate `.prettierignore` patterns (no-changelog)
  .prettierignore
  .vscode/launch.json
  CHANGELOG.md
  cypress.config.js
  cypress/fixtures/Test_workflow_1.json
  cypress/fixtures/Test_workflow_2.json
  docker/compose/withPostgres/docker-compose.yml
  docker/compose/withPostgresAndWorker/README.md
  docker/compose/withPostgresAndWorker/docker-compose.yml
  packages/cli/nodemon.json
  packages/cli/package.json
  packages/cli/src/PublicApi/swaggerTheme.css
  packages/cli/src/PublicApi/v1/handlers/workflows/spec/schemas/node.yml
  packages/cli/src/PublicApi/v1/handlers/workflows/spec/schemas/parameters/workflowId.yml
  packages/cli/src/UserManagement/email/templates/passwordReset.html
  packages/cli/src/databases/migrations/mysqldb/1588157391238-InitialMigration.ts
  packages/cli/src/databases/migrations/mysqldb/1592447867632-WebhookModel.ts
  packages/cli/src/databases/migrations/mysqldb/1594902918301-CreateIndexStoppedAt.ts
  packages/cli/src/databases/migrations/mysqldb/1607431743767-MakeStoppedAtNullable.ts
  packages/cli/src/databases/migrations/mysqldb/1611149998770-AddWebhookId.ts
  packages/cli/src/databases/migrations/mysqldb/1615306975123-ChangeDataSize.ts
  packages/cli/src/databases/migrations/mysqldb/1617268711084-CreateTagEntity.ts
  packages/cli/src/databases/migrations/mysqldb/1620729500000-ChangeCredentialDataSize.ts
  packages/cli/src/databases/migrations/mysqldb/1620826335440-UniqueWorkflowNames.ts
  packages/cli/src/databases/migrations/mysqldb/1623936588000-CertifyCorrectCollation.ts
  packages/cli/src/databases/migrations/mysqldb/1626183952959-AddWaitColumn.ts
  packages/cli/src/databases/migrations/mysqldb/1652254514003-CommunityNodes.ts
  packages/cli/src/databases/migrations/mysqldb/1652905585850-AddAPIKeyColumn.ts
  packages/cli/src/databases/migrations/mysqldb/1654090101303-IntroducePinData.ts
  packages/cli/src/databases/migrations/mysqldb/1660062385367-CreateCredentialsUserRole.ts
  packages/cli/src/databases/migrations/postgresdb/1587669153312-InitialMigration.ts
  packages/cli/src/databases/migrations/postgresdb/1589476000887-WebhookModel.ts
  packages/cli/src/databases/migrations/postgresdb/1594828256133-CreateIndexStoppedAt.ts
  packages/cli/src/databases/migrations/postgresdb/1607431743768-MakeStoppedAtNullable.ts
  packages/cli/src/databases/migrations/postgresdb/1611144599516-AddWebhookId.ts
  packages/cli/src/databases/migrations/postgresdb/1617270242566-CreateTagEntity.ts
  packages/cli/src/databases/migrations/postgresdb/1626176912946-AddwaitTill.ts
  packages/cli/src/databases/migrations/postgresdb/1644422880309-AddExecutionEntityIndexes.ts
  packages/cli/src/databases/migrations/postgresdb/1646834195327-IncreaseTypeVarcharLimit.ts
  packages/cli/src/databases/migrations/postgresdb/1646992772331-CreateUserManagement.ts
  packages/cli/src/databases/migrations/postgresdb/1652254514002-CommunityNodes.ts
  packages/cli/src/databases/migrations/postgresdb/1652905585850-AddAPIKeyColumn.ts
  packages/cli/src/databases/migrations/postgresdb/1654090467022-IntroducePinData.ts
  packages/cli/src/databases/migrations/postgresdb/1660062385367-CreateCredentialsUserRole.ts
  packages/cli/src/databases/migrations/sqlite/1646992772331-CreateUserManagement.ts
  packages/cli/src/databases/migrations/sqlite/1652254514001-CommunityNodes.ts
  packages/cli/src/databases/migrations/sqlite/1654089251344-IntroducePinData.ts
  packages/cli/templates/oauth-callback.html
  packages/core/package.json
  packages/design-system/.prettierignore
  packages/design-system/package.json
  packages/node-dev/README.md
  packages/node-dev/package.json
  packages/node-dev/src/tsconfig-build.json
  packages/workflow/package.json
Labels: core, n8n team

#4669 perf(Code Node): Improve n8n item key validation performance
  packages/nodes-base/nodes/Code/Sandbox.ts
  packages/nodes-base/nodes/Code/utils.ts
Labels: node/improvement, n8n team

#4694 fix(core): Fix `$items().length` behavior in `executeOnce` mode
  packages/workflow/src/WorkflowDataProxy.ts
Labels: core, n8n team

#4639 fix: Remove redundant await in node's api request functions without try/catch
  packages/nodes-base/nodes/ActionNetwork/GenericFunctions.ts
  packages/nodes-base/nodes/Airtable/GenericFunctions.ts
  packages/nodes-base/nodes/Aws/Comprehend/GenericFunctions.ts
  packages/nodes-base/nodes/Aws/Rekognition/GenericFunctions.ts
  packages/nodes-base/nodes/Aws/S3/GenericFunctions.ts
  packages/nodes-base/nodes/Beeminder/GenericFunctions.ts
  packages/nodes-base/nodes/Calendly/GenericFunctions.ts
  packages/nodes-base/nodes/Clockify/GenericFunctions.ts
  packages/nodes-base/nodes/Cortex/GenericFunctions.ts
  packages/nodes-base/nodes/CustomerIo/GenericFunctions.ts
  packages/nodes-base/nodes/Dropcontact/GenericFunction.ts
  packages/nodes-base/nodes/Ghost/GenericFunctions.ts
  packages/nodes-base/nodes/HighLevel/GenericFunctions.ts
  packages/nodes-base/nodes/Jira/GenericFunctions.ts
  packages/nodes-base/nodes/Lemlist/GenericFunctions.ts
  packages/nodes-base/nodes/Mailjet/GenericFunctions.ts
  packages/nodes-base/nodes/NextCloud/GenericFunctions.ts
  packages/nodes-base/nodes/NocoDB/GenericFunctions.ts
  packages/nodes-base/nodes/Rocketchat/GenericFunctions.ts
  packages/nodes-base/nodes/Segment/GenericFunctions.ts
  packages/nodes-base/nodes/SendGrid/GenericFunctions.ts
  packages/nodes-base/nodes/Shopify/GenericFunctions.ts
  packages/nodes-base/nodes/Stripe/helpers.ts
  packages/nodes-base/nodes/TheHive/GenericFunctions.ts
  packages/nodes-base/nodes/Trello/GenericFunctions.ts
  packages/nodes-base/nodes/Twake/GenericFunctions.ts
  packages/nodes-base/nodes/Twilio/GenericFunctions.ts
  packages/nodes-base/nodes/UrlScanIo/GenericFunctions.ts
  packages/nodes-base/nodes/Webflow/GenericFunctions.ts
  packages/nodes-base/nodes/Wekan/GenericFunctions.ts
  packages/nodes-base/nodes/WooCommerce/GenericFunctions.ts
  packages/nodes-base/nodes/Wufoo/GenericFunctions.ts
  packages/nodes-base/nodes/Zendesk/GenericFunctions.ts
Labels: node/improvement, n8n team

#4693 feat(editor): Update `FormInputs` and `UserList` components to support LDAP featue
  packages/design-system/src/components/N8nFormInput/FormInput.vue
  packages/design-system/src/components/N8nFormInputs/FormInputs.stories.js
  packages/design-system/src/components/N8nFormInputs/FormInputs.vue
  packages/design-system/src/components/N8nUserInfo/UserInfo.vue
  packages/design-system/src/components/N8nUsersList/UsersList.stories.js
  packages/design-system/src/components/N8nUsersList/UsersList.vue
  packages/design-system/src/types/form.ts
  packages/design-system/src/types/user.ts
  packages/editor-ui/src/plugins/i18n/locales/en.json
  packages/editor-ui/src/views/SettingsLdapView.vue
Labels: ui, n8n team

#4601 feat(editor): Implement JSON Schema view UI functionalities
  packages/editor-ui/src/Interface.ts
  packages/editor-ui/src/components/Draggable.vue
  packages/editor-ui/src/components/NDVDraggablePanels.vue
  packages/editor-ui/src/components/RunData.vue
  packages/editor-ui/src/components/RunDataJson.vue
  packages/editor-ui/src/components/RunDataJsonSchema.vue
  packages/editor-ui/src/components/RunDataJsonSchemaItem.vue
  packages/editor-ui/src/plugins/i18n/locales/en.json
  packages/editor-ui/src/plugins/icons.ts
  packages/editor-ui/src/stores/ndv.ts
  packages/editor-ui/src/styles/css-animation-helpers.scss
  packages/editor-ui/src/utils.test.ts
  packages/editor-ui/src/utils.ts
Labels: ui, n8n team

#4700 refactor: Add credential information to workflow list
  packages/cli/src/workflows/workflows.services.ee.ts
  packages/cli/src/workflows/workflows.types.ts
Labels: core, n8n team

#4703 fix: Invalid credentials should throw 401 and not 500 (no-changelog)
  packages/cli/src/UserManagement/routes/auth.ts
Labels: core, n8n team

#4695 feat(editor): Add telemetry calls to JSON schema mapping
  packages/editor-ui/src/components/RunData.vue
  packages/editor-ui/src/components/RunDataJsonSchema.vue
  packages/editor-ui/src/mixins/externalHooks.ts
  packages/editor-ui/src/plugins/telemetry/index.ts
  packages/editor-ui/src/plugins/telemetry/telemetry.types.ts
Labels: ui, n8n team

#4707 fix(editor): Fix for missing node connections in dev environment
  packages/editor-ui/src/components/Node/NodeCreation.vue
  packages/editor-ui/src/components/Node/NodeCreator/NodeItem.vue
  packages/editor-ui/src/mixins/mouseSelect.ts
  packages/editor-ui/src/mixins/moveNodeWorkflow.ts
  packages/editor-ui/src/mixins/nodeBase.ts
  packages/editor-ui/src/stores/canvas.ts
  packages/editor-ui/src/stores/workflows.ts
  packages/editor-ui/src/utils/canvasUtils.ts
  packages/editor-ui/src/utils/nodeViewUtils.ts
  packages/editor-ui/src/views/NodeView.vue
Labels: ui, n8n team, Upcoming Release

#4709 ci: Make end-to-end testing independent of development environments (no-changelog)
  .github/workflows/ci-master.yml
  .github/workflows/ci-pull-requests.yml
  package.json
  packages/cli/src/UserManagement/email/NodeMailer.ts
  packages/cli/src/config/index.ts
  packages/core/src/UserSettings.ts
Labels: core, n8n team

#4640 refactor(core): Reduce memory usage in the Webhook node
  packages/cli/src/Server.ts
  packages/core/package.json
  packages/core/src/BinaryDataManager/FileSystem.ts
  packages/core/src/BinaryDataManager/index.ts
  packages/core/src/Interfaces.ts
  packages/core/src/NodeExecuteFunctions.ts
  packages/editor-ui/src/Interface.ts
  packages/editor-ui/src/components/BinaryDataDisplay.vue
  packages/editor-ui/src/components/BinaryDataDisplayEmbed.vue
  packages/editor-ui/src/components/RunData.vue
  packages/editor-ui/src/mixins/restApi.ts
  packages/editor-ui/src/plugins/i18n/locales/en.json
  packages/nodes-base/nodes/Wait/Wait.node.ts
  packages/nodes-base/nodes/Webhook/Webhook.node.ts
  packages/workflow/src/Interfaces.ts
  pnpm-lock.yaml
Labels: node/improvement, core, n8n team

#4720 fix: Fix Windows development environments (no-changelog)
  packages/core/bin/generate-known
Labels: core, n8n team

#4717 ci: Setup cypress tasks for resetting DB, and setting up an owner
  cypress.config.js
  cypress/e2e/0-smoke.cy.ts
  package.json
  packages/cli/src/Db.ts
  packages/cli/src/Server.ts
  packages/cli/src/api/e2e.api.ts
  packages/cli/src/config/index.ts
  pnpm-lock.yaml
Labels: core, n8n team

#4719 test: Add more tests for workflow/credential migrations when enabling UM
  cypress/e2e/3-default-owner.cy.ts
  cypress/pages/index.ts
  cypress/pages/modals/credentials-modal.ts
  cypress/pages/modals/index.ts
  cypress/pages/modals/message-box.ts
  cypress/pages/settings-users.ts
  cypress/pages/sidebar/index.ts
  cypress/pages/sidebar/main-sidebar.ts
  cypress/pages/sidebar/settings-sidebar.ts
  cypress/pages/workflow.ts
  packages/cli/src/databases/entities/Role.ts
  packages/design-system/src/components/N8nActionBox/ActionBox.vue
  packages/design-system/src/components/N8nActionBox/__tests__/__snapshots__/ActionBox.spec.ts.snap
  packages/design-system/src/components/N8nMenuItem/MenuItem.vue
  packages/editor-ui/src/components/SettingsSidebar.vue
Labels: ui, n8n team

#4713 fix(core): Mark binary data to be deleted when pruning executions
  packages/cli/src/WorkflowExecuteAdditionalData.ts
  packages/core/src/BinaryDataManager/index.ts
Labels: core, n8n team

#4678 refactor: Improve typings for element-ui imports (no-changelog)
  packages/design-system/.eslintrc.js
  packages/design-system/.gitignore
  packages/design-system/.storybook/main.js
  packages/design-system/.storybook/preview.js
  packages/design-system/package.json
  packages/design-system/src/components/N8nActionDropdown/ActionDropdown.vue
  packages/design-system/src/components/N8nActionToggle/ActionToggle.stories.ts
  packages/design-system/src/components/N8nActionToggle/ActionToggle.vue
  packages/design-system/src/components/N8nAvatar/Avatar.stories.ts
  packages/design-system/src/components/N8nBadge/Badge.stories.ts
  packages/design-system/src/components/N8nBlockUi/BlockUi.stories.ts
  packages/design-system/src/components/N8nCheckbox/Checkbox.vue
  packages/design-system/src/components/N8nFormBox/FormBox.stories.ts
  packages/design-system/src/components/N8nFormInput/FormInput.stories.ts
  packages/design-system/src/components/N8nFormInputs/FormInputs.stories.ts
  packages/design-system/src/components/N8nHeading/Heading.stories.ts
  packages/design-system/src/components/N8nIcon/Icon.stories.ts
  packages/design-system/src/components/N8nInput/Input.vue
  packages/design-system/src/components/N8nInputLabel/InputLabel.stories.ts
  packages/design-system/src/components/N8nInputNumber/InputNumber.stories.ts
  packages/design-system/src/components/N8nInputNumber/InputNumber.vue
  packages/design-system/src/components/N8nLink/Link.stories.ts
  packages/design-system/src/components/N8nLoading/Loading.stories.ts
  packages/design-system/src/components/N8nLoading/Loading.vue
  packages/design-system/src/components/N8nMarkdown/Markdown.stories.ts
  packages/design-system/src/components/N8nMenu/Menu.vue
  packages/design-system/src/components/N8nMenuItem/MenuItem.stories.ts
  packages/design-system/src/components/N8nMenuItem/MenuItem.vue
  packages/design-system/src/components/N8nOption/Option.vue
  packages/design-system/src/components/N8nPopover/Popover.stories.ts
  packages/design-system/src/components/N8nPopover/Popover.vue
  packages/design-system/src/components/N8nRadioButtons/RadioButtons.stories.ts
  packages/design-system/src/components/N8nResizeWrapper/ResizeWrapper.stories.ts
  packages/design-system/src/components/N8nSelect/Select.vue
  packages/design-system/src/components/N8nSpinner/Spinner.stories.ts
  packages/design-system/src/components/N8nSticky/Sticky.stories.ts
  packages/design-system/src/components/N8nTabs/Tabs.stories.ts
  packages/design-system/src/components/N8nTag/Tag.stories.ts
  packages/design-system/src/components/N8nTags/Tags.stories.ts
  packages/design-system/src/components/N8nText/Text.stories.ts
  packages/design-system/src/components/N8nTooltip/Tooltip.stories.ts
  packages/design-system/src/components/N8nTooltip/Tooltip.vue
  packages/design-system/src/components/N8nUserInfo/UserInfo.stories.ts
  packages/design-system/src/components/N8nUserSelect/UserSelect.stories.ts
  packages/design-system/src/components/N8nUserSelect/UserSelect.vue
  packages/design-system/src/components/N8nUsersList/UsersList.stories.ts
  packages/design-system/src/main.js
  packages/design-system/src/plugins/elementUIComponents.ts
  packages/design-system/src/shims-element-ui.d.ts
  packages/editor-ui/src/components/ExecutionsView/ExecutionPreview.vue
  packages/editor-ui/src/plugins/components.ts
  packages/editor-ui/src/shims-element-ui.d.ts
  pnpm-lock.yaml
Labels: ui, n8n team

#4721 fix(editor): Fix slots rendering of NodeCreator's NoResults component
  packages/editor-ui/src/components/Node/NodeCreator/CategorizedItems.vue
Labels: ui, n8n team

#4723 fix: Lint typescript stories (no-changelog)
  packages/design-system/.storybook/main.js
  packages/design-system/src/components/N8nActionToggle/ActionToggle.stories.ts
  packages/design-system/src/components/N8nAvatar/Avatar.stories.ts
  packages/design-system/src/components/N8nBadge/Badge.stories.ts
  packages/design-system/src/components/N8nBlockUi/BlockUi.stories.ts
  packages/design-system/src/components/N8nFormBox/FormBox.stories.ts
  packages/design-system/src/components/N8nFormInput/FormInput.stories.ts
  packages/design-system/src/components/N8nFormInputs/FormInputs.stories.ts
  packages/design-system/src/components/N8nHeading/Heading.stories.ts
  packages/design-system/src/components/N8nIcon/Icon.stories.ts
  packages/design-system/src/components/N8nInputLabel/InputLabel.stories.ts
  packages/design-system/src/components/N8nInputNumber/InputNumber.stories.ts
  packages/design-system/src/components/N8nLink/Link.stories.ts
  packages/design-system/src/components/N8nLoading/Loading.stories.ts
  packages/design-system/src/components/N8nMarkdown/Markdown.stories.ts
  packages/design-system/src/components/N8nPopover/Popover.stories.ts
  packages/design-system/src/components/N8nRadioButtons/RadioButtons.stories.ts
  packages/design-system/src/components/N8nResizeWrapper/ResizeWrapper.stories.js
  packages/design-system/src/components/N8nSpinner/Spinner.stories.ts
  packages/design-system/src/components/N8nSticky/Sticky.stories.ts
  packages/design-system/src/components/N8nTabs/Tabs.stories.ts
  packages/design-system/src/components/N8nTag/Tag.stories.ts
  packages/design-system/src/components/N8nTags/Tags.stories.ts
  packages/design-system/src/components/N8nText/Text.stories.ts
  packages/design-system/src/components/N8nTooltip/Tooltip.stories.ts
  packages/design-system/src/components/N8nUserInfo/UserInfo.stories.ts
  packages/design-system/src/components/N8nUserSelect/UserSelect.stories.ts
  packages/design-system/src/components/N8nUsersList/UsersList.stories.ts
Labels: ui, n8n team

#4718 test: Set up e2e tests for HTTP Request node
  cypress/e2e/4-http-request-node.cy.ts
  cypress/pages/workflow.ts
  cypress/pages/workflows.ts
  packages/editor-ui/src/components/Node.vue
  packages/editor-ui/src/components/Node/NodeCreation.vue
  packages/editor-ui/src/components/Node/NodeCreator/SearchBar.vue
  packages/editor-ui/src/components/NodeDetailsView.vue
  packages/editor-ui/src/components/ParameterInputExpanded.vue
  packages/editor-ui/src/components/ParameterInputWrapper.vue
  packages/editor-ui/src/views/CanvasAddButton.vue
Labels: ui, n8n team

#4714 test: Add basic e2e tests for node creator
  cypress/e2e/4-node-creator.cy.ts
  cypress/fixtures/Custom_node.json
  cypress/pages/features/node-creator.ts
  packages/editor-ui/src/components/Node/NodeCreator/CategorizedItems.vue
  packages/editor-ui/src/components/Node/NodeCreator/ItemIterator.vue
  packages/editor-ui/src/components/Node/NodeCreator/NodeCreator.vue
  packages/editor-ui/src/components/Node/NodeCreator/NodeItem.vue
  packages/editor-ui/src/components/Node/NodeCreator/SearchBar.vue
  packages/editor-ui/src/components/Node/NodeCreator/TypeSelector.vue
  packages/editor-ui/src/views/CanvasAddButton.vue
Labels: ui, n8n team

#4726 refactor: Trim down the response on the Workflows listing endpoint
  packages/cli/src/databases/entities/WorkflowEntity.ts
  packages/cli/src/workflows/workflows.controller.ee.ts
  packages/cli/src/workflows/workflows.services.ee.ts
  packages/cli/src/workflows/workflows.services.ts
Labels: core, n8n team

#4724 test: Setup e2e tests for workflow actions
  cypress/e2e/5-workflow-actions.cy.ts
  cypress/pages/workflow.ts
  packages/design-system/src/components/N8nActionToggle/ActionToggle.vue
  packages/editor-ui/src/components/MainHeader/WorkflowDetails.vue
  packages/editor-ui/src/components/ShortenName.vue
  packages/editor-ui/src/components/WorkflowActivator.vue
  packages/editor-ui/src/views/LoadingView.vue
  packages/editor-ui/src/views/NodeView.vue
Labels: ui, n8n team

#4733 test: Reset DB and skip set-up before running node creator e2e
  cypress/e2e/4-node-creator.cy.ts
  cypress/fixtures/Custom_node.json
  packages/editor-ui/src/components/Node/NodeCreator/CategoryItem.vue
Labels: ui, n8n team

#4734 fix(editor): Fix for broken selectors for workflows tests (no-changelog)
  cypress/e2e/5-workflow-actions.cy.ts
  cypress/pages/workflow.ts
  packages/design-system/src/components/N8nActionToggle/ActionToggle.vue
  packages/editor-ui/src/components/MainHeader/WorkflowDetails.vue
Labels: ui, n8n team

#4716 test: Update getters, add search and sort tests for credentials
  cypress/e2e/2-credentials.cy.ts
  cypress/pages/credentials.ts
  cypress/pages/modals/credentials-modal.ts
  cypress/pages/workflows.ts
  packages/editor-ui/src/components/CredentialCard.vue
  packages/editor-ui/src/components/WorkflowCard.vue
  packages/editor-ui/src/components/forms/ResourceFiltersDropdown.vue
  packages/editor-ui/src/components/layouts/ResourcesListLayout.vue
Labels: n8n team

#4738 fix: Update workflow share modal margins (no-changelog)
  packages/editor-ui/src/components/WorkflowShareModal.ee.vue
Labels: ui, n8n team

#4730 test: Set up e2e tests for Code node
  cypress/e2e/6-code-node.cy.ts
  cypress/pages/workflow.ts
  packages/editor-ui/src/components/RunData.vue
Labels: ui, n8n team

#4744 refactor: Upgrade license package version and create tenant id variable
  packages/cli/package.json
  packages/cli/src/License.ts
  packages/cli/src/config/schema.ts
  pnpm-lock.yaml
Labels: core, n8n team

#4735 feat: Reduce initial memory spike at server startup (no-changelog)
  packages/cli/package.json
  packages/cli/src/LoadNodesAndCredentials.ts
  packages/cli/src/Server.ts
  packages/cli/src/commands/start.ts
  packages/cli/src/constants.ts
  pnpm-lock.yaml
Labels: core, n8n team

#4739 feat: Make use of db:reset in all test suites (no-changelog)
  cypress.config.js
  cypress/e2e/0-smoke.cy.ts
  cypress/e2e/1-workflows.cy.ts
  cypress/e2e/2-credentials.cy.ts
  cypress/e2e/3-default-owner.cy.ts
  cypress/e2e/4-http-request-node.cy.ts
  cypress/e2e/4-node-creator.cy.ts
  cypress/e2e/5-workflow-actions.cy.ts
  cypress/support/commands.ts
  cypress/support/index.ts
  package.json
Labels: n8n team

#4746 fix: Fix the e2e tests on master (no-changelog)
  cypress/e2e/6-code-node.cy.ts
Labels: n8n team

#4742 feat: Update workflow hash change copy (no-changelog)
  packages/cli/src/workflows/workflows.services.ts
Labels: core, n8n team

#4747 fix: Update size of select components in filters dropdown
  packages/design-system/src/css/select.scss
  packages/editor-ui/src/components/forms/ResourceFiltersDropdown.vue
  packages/editor-ui/src/views/CredentialsView.vue
  packages/editor-ui/src/views/WorkflowsView.vue
Labels: ui, n8n team

#4748 fix: Remove background for resource ownership selector
  packages/design-system/src/components/N8nMenu/Menu.vue
  packages/editor-ui/src/components/forms/ResourceOwnershipSelect.ee.vue
Labels: ui, n8n team

#4749 fix: Update owner badge padding (no-changelog)
  packages/design-system/src/components/N8nBadge/Badge.vue
  packages/design-system/src/components/N8nBadge/__tests__/__snapshots__/Badge.spec.ts.snap
Labels: ui, n8n team
