Repository n8n-io/n8n, pull requests merged in 2022-08, with the labels that each got.

#3805 Adjust `nodes-base` formatting command
  .prettierignore
  packages/nodes-base/package.json
Labels: n8n team, tech debt

#3384 Add Docker Compose example for MariaDB
  docker/compose/withMariaDB/.env
  docker/compose/withMariaDB/README.md
  docker/compose/withMariaDB/docker-compose.yml
Labels: community

#3727 N8N-3352 N8nNodeIcon component
  packages/design-system/src/components/N8nNodeIcon/NodeIcon.stories.ts
  packages/design-system/src/components/N8nNodeIcon/NodeIcon.vue
  packages/design-system/src/components/N8nNodeIcon/index.ts
  packages/design-system/src/components/index.ts
  packages/editor-ui/src/components/NodeIcon.vue
  packages/editor-ui/src/components/NodeList.vue
  packages/editor-ui/src/components/TemplateDetails.vue
  packages/editor-ui/src/plugins/components.ts
  packages/editor-ui/src/shims-vue.d.ts
Labels: ui, n8n team

#3804 Fix telemetry tests
  packages/cli/test/unit/Telemetry.test.ts
Labels: core, n8n team

#3799 Refactor `nodeTypes` into store module
  packages/editor-ui/src/App.vue
  packages/editor-ui/src/Interface.ts
  packages/editor-ui/src/api/nodeTypes.ts
  packages/editor-ui/src/components/ActivationModal.vue
  packages/editor-ui/src/components/CredentialEdit/CredentialConfig.vue
  packages/editor-ui/src/components/CredentialIcon.vue
  packages/editor-ui/src/components/Error/NodeErrorView.vue
  packages/editor-ui/src/components/Node.vue
  packages/editor-ui/src/components/NodeCreator/NodeCreator.vue
  packages/editor-ui/src/components/NodeCredentials.vue
  packages/editor-ui/src/components/NodeDetailsView.vue
  packages/editor-ui/src/components/NodeExecuteButton.vue
  packages/editor-ui/src/components/NodeSettings.vue
  packages/editor-ui/src/components/OutputPanel.vue
  packages/editor-ui/src/components/ParameterInput.vue
  packages/editor-ui/src/components/ParameterInputList.vue
  packages/editor-ui/src/components/RunData.vue
  packages/editor-ui/src/components/Sticky.vue
  packages/editor-ui/src/components/TriggerPanel.vue
  packages/editor-ui/src/components/mixins/nodeBase.ts
  packages/editor-ui/src/components/mixins/nodeHelpers.ts
  packages/editor-ui/src/components/mixins/pushConnection.ts
  packages/editor-ui/src/components/mixins/restApi.ts
  packages/editor-ui/src/components/mixins/workflowHelpers.ts
  packages/editor-ui/src/modules/credentials.ts
  packages/editor-ui/src/modules/nodeTypes.ts
  packages/editor-ui/src/store.ts
  packages/editor-ui/src/utils.ts
  packages/editor-ui/src/views/NodeView.vue
Labels: ui, n8n team, tech debt

#3798 ✨ Implemented a single Callout component
  packages/design-system/src/components/N8nActionBox/ActionBox.vue
  packages/design-system/src/components/N8nCallout/Callout.stories.ts
  packages/design-system/src/components/N8nCallout/Callout.vue
  packages/design-system/src/components/N8nCallout/N8nCallout.stories.ts
  packages/design-system/src/components/N8nCallout/__tests__/Callout.spec.ts
  packages/design-system/src/components/N8nCallout/__tests__/__snapshots__/Callout.spec.ts.snap
  packages/design-system/src/components/N8nPanelCallout/PanelCallout.stories.js
  packages/design-system/src/components/N8nPanelCallout/PanelCallout.vue
  packages/design-system/src/components/N8nPanelCallout/index.ts
  packages/design-system/src/components/index.ts
  packages/editor-ui/src/components/RunData.vue
  packages/editor-ui/src/plugins/components.ts
  packages/editor-ui/src/views/SettingsCommunityNodesView.vue
Labels: ui, n8n team, tech debt

#3767 Suggestions for community nodes repo
  package-lock.json
  packages/cli/package.json
  packages/cli/src/CommunityNodes/helpers.ts
  packages/cli/src/CommunityNodes/packageModel.ts
  packages/cli/src/Interfaces.ts
  packages/cli/src/ResponseHelper.ts
  packages/cli/src/api/nodes.api.ts
  packages/cli/src/constants.ts
  packages/cli/src/requests.d.ts
  packages/cli/test/integration/nodes.api.test.ts
  packages/cli/test/integration/shared/types.d.ts
  packages/cli/test/integration/shared/utils.ts
  packages/cli/test/unit/CommunityNodeHelpers.test.ts
Labels: core, n8n team

#3793 N8n 4237 use node
  packages/editor-ui/src/Interface.ts
  packages/editor-ui/src/components/Node.vue
  packages/editor-ui/src/components/Sticky.vue
  packages/editor-ui/src/components/mixins/mouseSelect.ts
  packages/editor-ui/src/components/mixins/moveNodeWorkflow.ts
  packages/editor-ui/src/components/mixins/nodeBase.ts
  packages/editor-ui/src/components/mixins/nodeIndex.ts
  packages/editor-ui/src/constants.ts
  packages/editor-ui/src/store.ts
  packages/editor-ui/src/views/NodeView.vue
  packages/editor-ui/src/views/canvasHelpers.ts
Labels: ui, n8n team

#3803 N8N-4255: Remove request libraries from cli package
  packages/cli/package.json
  packages/cli/src/Server.ts
Labels: core, n8n team, tech debt

#3792 Fix: Problem saving workflow when tags disabled
  packages/cli/src/Interfaces.ts
  packages/cli/src/Server.ts
  packages/cli/src/api/workflows.api.ts
  packages/cli/src/databases/entities/WorkflowEntity.ts
Labels: core, n8n team

#3820 fix input label
  packages/design-system/src/components/N8nInputLabel/InputLabel.vue
Labels: ui, n8n team

#3822 Updated welcome sticky image and text
  packages/editor-ui/public/static/quickstart_thumbnail.png
  packages/editor-ui/src/plugins/i18n/locales/en.json
Labels: ui, n8n team

#3788 N8n 4168 add node ids
  packages/cli/commands/import/workflow.ts
  packages/cli/src/CredentialsHelper.ts
  packages/cli/src/PublicApi/v1/handlers/workflows/spec/schemas/node.yml
  packages/cli/src/PublicApi/v1/handlers/workflows/workflows.handler.ts
  packages/cli/src/PublicApi/v1/handlers/workflows/workflows.service.ts
  packages/cli/src/Server.ts
  packages/cli/src/WorkflowHelpers.ts
  packages/cli/src/api/workflows.api.ts
  packages/cli/src/databases/migrations/mysqldb/1658932910559-AddNodeIds.ts
  packages/cli/src/databases/migrations/mysqldb/index.ts
  packages/cli/src/databases/migrations/postgresdb/1658932090381-AddNodeIds.ts
  packages/cli/src/databases/migrations/postgresdb/index.ts
  packages/cli/src/databases/migrations/sqlite/1658930531669-AddNodeIds.ts
  packages/cli/src/databases/migrations/sqlite/index.ts
  packages/cli/test/integration/publicApi/workflows.test.ts
  packages/cli/test/integration/shared/testDb.ts
  packages/cli/test/integration/workflows.api.test.ts
  packages/cli/test/unit/CredentialsHelper.test.ts
  packages/core/src/LoadNodeParameterOptions.ts
  packages/core/test/WorkflowExecute.test.ts
  packages/editor-ui/src/Interface.ts
  packages/editor-ui/src/components/DuplicateWorkflowDialog.vue
  packages/editor-ui/src/components/MainSidebar.vue
  packages/editor-ui/src/components/Node.vue
  packages/editor-ui/src/components/Sticky.vue
  packages/editor-ui/src/components/mixins/mouseSelect.ts
  packages/editor-ui/src/components/mixins/moveNodeWorkflow.ts
  packages/editor-ui/src/components/mixins/nodeBase.ts
  packages/editor-ui/src/components/mixins/nodeIndex.ts
  packages/editor-ui/src/components/mixins/workflowHelpers.ts
  packages/editor-ui/src/constants.ts
  packages/editor-ui/src/store.ts
  packages/editor-ui/src/views/NodeView.vue
  packages/editor-ui/src/views/canvasHelpers.ts
  packages/workflow/src/Interfaces.ts
  packages/workflow/src/TelemetryHelpers.ts
  packages/workflow/test/Expression.test.ts
  packages/workflow/test/RoutingNode.test.ts
  packages/workflow/test/Workflow.test.ts
  packages/workflow/test/WorkflowDataProxy.test.ts
Labels: core, ui, n8n team

#3819 Fix node versioning in client
  packages/editor-ui/src/Interface.ts
  packages/editor-ui/src/components/NodeCreator/NodeCreator.vue
  packages/editor-ui/src/modules/credentials.ts
  packages/editor-ui/src/modules/nodeTypes.ts
Labels: ui, n8n team

#3771 Update README.md
  README.md
Labels: n8n team

#3746 SendInBlue Nodes
  packages/nodes-base/credentials/SendInBlueApi.credentials.ts
  packages/nodes-base/nodes/SendInBlue/AttributeDescription.ts
  packages/nodes-base/nodes/SendInBlue/ContactDescription.ts
  packages/nodes-base/nodes/SendInBlue/EmailDescription.ts
  packages/nodes-base/nodes/SendInBlue/GenericFunctions.ts
  packages/nodes-base/nodes/SendInBlue/SendInBlue.node.json
  packages/nodes-base/nodes/SendInBlue/SendInBlue.node.ts
  packages/nodes-base/nodes/SendInBlue/SendInBlueTrigger.node.json
  packages/nodes-base/nodes/SendInBlue/SendInBlueTrigger.node.ts
  packages/nodes-base/nodes/SendInBlue/SenderDescrition.ts
  packages/nodes-base/nodes/SendInBlue/sendinblue.svg
  packages/nodes-base/package.json
  packages/nodes-base/tslint.json
  packages/workflow/src/Interfaces.ts
  packages/workflow/src/RoutingNode.ts
Labels: node/new, core, n8n team

#3823 Support community nodes on Windows
  packages/cli/src/CommunityNodes/helpers.ts
  packages/cli/src/LoadNodesAndCredentials.ts
  packages/cli/src/api/nodes.api.ts
  packages/cli/src/constants.ts
Labels: core, n8n team, required for next release

#3784 update docs urls to reflect content split
  packages/editor-ui/src/components/RunData.vue
  packages/editor-ui/src/constants.ts
Labels: n8n team

#3832 add check for node ids migration
  packages/cli/src/databases/migrations/mysqldb/1658932910559-AddNodeIds.ts
Labels: core, n8n team

#3827 User Management: switch over to decorators to define routes
  packages/cli/src/ResponseHelper.ts
  packages/cli/src/UserManagement/controllers/AuthController.ts
  packages/cli/src/UserManagement/controllers/MeController.ts
  packages/cli/src/UserManagement/controllers/OwnerController.ts
  packages/cli/src/UserManagement/controllers/PasswordResetController.ts
  packages/cli/src/UserManagement/controllers/UserController.ts
  packages/cli/src/UserManagement/controllers/index.ts
  packages/cli/src/UserManagement/decorators.ts
  packages/cli/src/UserManagement/middlewares/auth.ts
  packages/cli/src/UserManagement/middlewares/index.ts
  packages/cli/src/UserManagement/routes/auth.ts
  packages/cli/src/UserManagement/routes/index.ts
  packages/cli/src/UserManagement/routes/me.ts
  packages/cli/src/UserManagement/routes/owner.ts
  packages/cli/src/UserManagement/routes/passwordReset.ts
  packages/cli/src/UserManagement/routes/users.ts
  packages/cli/test/integration/shared/utils.ts
Labels: core, n8n team

#3836 fix(build): fix nightly builds (#3836)
  package-lock.json
Labels: n8n team, Upcoming Release

#3802 refactor(design-system): replace functional components
  packages/design-system/src/components/N8nActionBox/ActionBox.vue
  packages/design-system/src/components/N8nAvatar/Avatar.vue
  packages/design-system/src/components/N8nBadge/Badge.vue
  packages/design-system/src/components/N8nBadge/__tests__/__snapshots__/Badge.spec.ts.snap
  packages/design-system/src/components/N8nCallout/Callout.vue
  packages/design-system/src/components/N8nCallout/__tests__/__snapshots__/Callout.spec.ts.snap
  packages/design-system/src/components/N8nCheckbox/Checkbox.vue
  packages/design-system/src/components/N8nFormBox/FormBox.vue
  packages/design-system/src/components/N8nHeading/Heading.vue
  packages/design-system/src/components/N8nIcon/Icon.vue
  packages/design-system/src/components/N8nIconButton/IconButton.vue
  packages/design-system/src/components/N8nInfoAccordion/InfoAccordion.vue
  packages/design-system/src/components/N8nInfoTip/InfoTip.vue
  packages/design-system/src/components/N8nInput/Input.vue
  packages/design-system/src/components/N8nInputLabel/InputLabel.vue
  packages/design-system/src/components/N8nLink/Link.vue
  packages/design-system/src/components/N8nLoading/Loading.vue
  packages/design-system/src/components/N8nMarkdown/Markdown.vue
  packages/design-system/src/components/N8nMenu/Menu.vue
  packages/design-system/src/components/N8nPulse/Pulse.vue
  packages/design-system/src/components/N8nRadioButtons/RadioButton.vue
  packages/design-system/src/components/N8nRadioButtons/RadioButtons.vue
  packages/design-system/src/components/N8nRoute/Route.vue
  packages/design-system/src/components/N8nSelect/Select.vue
  packages/design-system/src/components/N8nSpinner/Spinner.vue
  packages/design-system/src/components/N8nSquareButton/SquareButton.vue
  packages/design-system/src/components/N8nSticky/Resize.vue
  packages/design-system/src/components/N8nSticky/Sticky.vue
  packages/design-system/src/components/N8nTabs/Tabs.vue
  packages/design-system/src/components/N8nTag/Tag.vue
  packages/design-system/src/components/N8nTags/Tags.vue
  packages/design-system/src/components/N8nText/Text.vue
  packages/editor-ui/src/components/Badge.vue
  packages/editor-ui/src/components/NodeCreator/CreatorItem.vue
  packages/editor-ui/src/components/NodeTitle.vue
  packages/editor-ui/src/components/ParameterInput.vue
  packages/editor-ui/src/components/TagsDropdown.vue
  packages/editor-ui/src/components/TriggerIcon.vue
  packages/editor-ui/src/components/WarningTooltip.vue
  packages/editor-ui/src/plugins/components.ts
Labels: ui, n8n team, Upcoming Release, tech debt

#3840 Paired item support approach 1
  packages/core/src/Interfaces.ts
  packages/core/src/NodeExecuteFunctions.ts
  packages/workflow/src/Interfaces.ts
Labels: core, n8n team

#3796 N8N-3516 migrate from lerna to turborepo
  .github/workflows/test-workflows.yml
  .github/workflows/tests.yml
  .gitignore
  CONTRIBUTING.md
  docker/images/n8n-custom/Dockerfile
  docker/images/n8n-debian/Dockerfile
  docker/images/n8n-rhel7/Dockerfile
  docker/images/n8n/Dockerfile
  lerna.json
  package-lock.json
  package.json
  packages/cli/src/LoadNodesAndCredentials.ts
  packages/editor-ui/package.json
  packages/workflow/tsconfig.json
  turbo.json
Labels: core, n8n team, tech debt

#3850 N8N-4304 Agile CRM Paired-Item Support
  packages/nodes-base/nodes/AgileCrm/AgileCrm.node.ts
Labels: node/improvement, n8n team

#3853 fix-poll-trigger
  packages/cli/src/ActiveWorkflowRunner.ts
Labels: n8n team, node/issue

#3854 docs: Remove Node.js version number
  CONTRIBUTING.md
Labels: n8n team

#3852 [N8N-4145] Prevent non-hoisted dependencies from breaking docker images
  docker/images/n8n-custom/docker-entrypoint.sh
Labels: n8n team

#3834 :bug: Fix pagination issue in /executions - N8N-4236
  packages/cli/src/PublicApi/v1/handlers/executions/executions.service.ts
  packages/cli/test/integration/publicApi/executions.test.ts
Labels: core, n8n team

#3833 Synchronize default settings
  .gitignore
  .vscode/extensions.json
  .vscode/settings.default.json
  .vscode/suggested.settings.json
Labels: n8n team

#3848 N8N-4302 Affinity Node Paired-Item Support
  packages/nodes-base/nodes/Affinity/Affinity.node.ts
Labels: node/improvement, n8n team

#3847 N8N-4308 Active Network Node Paired-Item Support
  packages/nodes-base/nodes/ActiveCampaign/ActiveCampaign.node.ts
Labels: node/improvement, n8n team

#3772 Github Node - Add support for Paired Item
  packages/nodes-base/nodes/Github/Github.node.ts
Labels: node/improvement, core, n8n team

#3756 Fix crash caused by test webhooks
  packages/cli/src/TestWebhooks.ts
Labels: core, community

#3828 N8N-4286 DeepL Node Paired-Item Support
  packages/nodes-base/nodes/DeepL/DeepL.node.ts
Labels: node/improvement, n8n team

#3818 N8N-4273 Ghost Node Paired-Item Support
  packages/nodes-base/nodes/Ghost/Ghost.node.ts
Labels: node/improvement, n8n team

#3815 N8N-4269 Postgres Node PairedItem Support
  packages/nodes-base/nodes/Postgres/Postgres.node.functions.ts
  packages/nodes-base/nodes/Postgres/Postgres.node.ts
Labels: node/improvement, n8n team

#3779 Integrate PostHog - Part 2: Event capture
  packages/cli/src/InternalHooks.ts
  packages/cli/src/Server.ts
  packages/cli/src/telemetry/index.ts
  packages/cli/src/telemetry/scripts.ts
  packages/editor-ui/public/index.html
  packages/editor-ui/public/posthog-hooks.js
  packages/editor-ui/src/components/CredentialEdit/CredentialEdit.vue
  packages/editor-ui/src/components/CredentialsSelectModal.vue
  packages/editor-ui/src/components/ExpressionEdit.vue
  packages/editor-ui/src/components/NodeExecuteButton.vue
  packages/editor-ui/src/components/ParameterInput.vue
  packages/editor-ui/src/components/PersonalizationModal.vue
  packages/editor-ui/src/components/RunData.vue
  packages/editor-ui/src/components/RunDataTable.vue
  packages/editor-ui/src/components/Telemetry.vue
  packages/editor-ui/src/components/mixins/workflowActivate.ts
  packages/editor-ui/src/views/NodeView.vue
  packages/editor-ui/src/views/SettingsCommunityNodesView.vue
  packages/editor-ui/src/views/TemplatesCollectionView.vue
  packages/editor-ui/src/views/TemplatesWorkflowView.vue
Labels: core, ui, n8n team

#3789 Integrate PostHog - Part 3: Session recordings
  packages/cli/config/schema.ts
  packages/cli/src/Server.ts
  packages/cli/src/telemetry/index.ts
  packages/design-system/src/components/N8nUserInfo/UserInfo.vue
  packages/editor-ui/public/index.html
  packages/editor-ui/public/posthog-hooks.js
  packages/editor-ui/src/components/CopyInput.vue
  packages/editor-ui/src/components/CredentialsList.vue
  packages/editor-ui/src/components/ExecutionsList.vue
  packages/editor-ui/src/components/ExpressionEdit.vue
  packages/editor-ui/src/components/MainSidebar.vue
  packages/editor-ui/src/components/ParameterInput.vue
  packages/editor-ui/src/components/RunData.vue
  packages/editor-ui/src/components/Sticky.vue
  packages/editor-ui/src/components/VariableSelectorItem.vue
  packages/editor-ui/src/components/WorkflowOpen.vue
  packages/editor-ui/src/views/SettingsPersonalView.vue
Labels: core, ui, n8n team

#3825 Integrate PostHog - Part 4: Experiments
  packages/editor-ui/public/posthog-hooks.js
  packages/editor-ui/src/plugins/telemetry/telemetry.types.ts
  packages/editor-ui/src/views/NodeView.vue
Labels: ui, n8n team

#3812 N8N-4175 resource locator component
  packages/core/src/NodeExecuteFunctions.ts
  packages/design-system/theme/src/input.scss
  packages/editor-ui/src/components/DraggableTarget.vue
  packages/editor-ui/src/components/MainSidebar.vue
  packages/editor-ui/src/components/ParameterInput.vue
  packages/editor-ui/src/components/ParameterInputExpanded.vue
  packages/editor-ui/src/components/ParameterInputFull.vue
  packages/editor-ui/src/components/ParameterOptions.vue
  packages/editor-ui/src/components/ResourceLocator/ResourceLocator.vue
  packages/editor-ui/src/components/ResourceLocator/helpers.ts
  packages/editor-ui/src/components/helpers.ts
  packages/editor-ui/src/plugins/i18n/locales/en.json
  packages/editor-ui/src/plugins/icons.ts
  packages/nodes-base/nodes/Trello/BoardDescription.ts
  packages/workflow/src/Expression.ts
  packages/workflow/src/Interfaces.ts
  packages/workflow/src/NodeHelpers.ts
  packages/workflow/src/RoutingNode.ts
  packages/workflow/src/Workflow.ts
  packages/workflow/src/WorkflowDataProxy.ts
Labels: ui, n8n team

#3871 Enable community nodes based on npm availability
  packages/cli/src/Interfaces.ts
  packages/cli/src/Server.ts
  packages/editor-ui/src/Interface.ts
  packages/editor-ui/src/constants.ts
  packages/editor-ui/src/modules/settings.ts
  packages/editor-ui/src/plugins/i18n/locales/en.json
  packages/editor-ui/src/store.ts
  packages/editor-ui/src/views/SettingsCommunityNodesView.vue
Labels: core, ui, n8n team

#3868 Fix executions pagination for Public API
  packages/cli/src/PublicApi/v1/handlers/executions/executions.service.ts
  packages/cli/test/integration/publicApi/executions.test.ts
Labels: core, n8n team

#3875 ✨ Added Vue plugins that register design system and element UI components
  packages/design-system/src/components/index.ts
  packages/design-system/src/main.js
  packages/design-system/src/plugins/elementUIComponents.ts
  packages/design-system/src/plugins/n8nComponents.ts
  packages/editor-ui/src/components/DeleteUserModal.vue
  packages/editor-ui/src/plugins/components.ts
  packages/editor-ui/src/views/SettingsUsersView.vue
Labels: ui

#3867 Assign parent workflow ID to subworkflows from generic JSON
  packages/cli/src/WorkflowExecuteAdditionalData.ts
  packages/cli/src/WorkflowRunner.ts
  packages/cli/src/WorkflowRunnerProcess.ts
  packages/core/src/NodeExecuteFunctions.ts
  packages/workflow/src/Interfaces.ts
  packages/workflow/test/Helpers.ts
Labels: core, n8n team

#3877 🐛 Handling errors when opening settings and executions
  packages/editor-ui/src/components/ExecutionsList.vue
  packages/editor-ui/src/views/NodeView.vue
Labels: ui

#3874 fix(editor): improve expression and parameters performance
  packages/editor-ui/src/components/CodeEdit.vue
  packages/editor-ui/src/components/ExpressionInput.vue
  packages/editor-ui/src/components/Node.vue
  packages/editor-ui/src/components/NodeDetailsView.vue
  packages/editor-ui/src/components/ParameterInput.vue
  packages/editor-ui/src/components/VariableSelector.vue
  packages/editor-ui/src/components/mixins/pushConnection.ts
  packages/editor-ui/src/components/mixins/workflowHelpers.ts
  packages/editor-ui/src/components/mixins/workflowRun.ts
  packages/editor-ui/src/views/NodeView.vue
Labels: ui, n8n team

#3567 [Fix #3540] Handle iterator request bodies in `convertN8nRequestToAxios`
  packages/core/src/NodeExecuteFunctions.ts
Labels: core, community

#3890 💄 Added animated tooltip to draggable columns in input panel
  packages/editor-ui/public/static/data-mapping-gif.gif
  packages/editor-ui/src/components/RunDataTable.vue
  packages/editor-ui/src/plugins/i18n/locales/en.json
Labels: ui, n8n team

#3777 Add value extractor to routing node
  packages/core/src/NodeExecuteFunctions.ts
  packages/workflow/src/Interfaces.ts
  packages/workflow/src/RoutingNode.ts
  packages/workflow/test/RoutingNode.test.ts
Labels: core, n8n team

#3884 Updates
  packages/cli/config/schema.ts
  packages/cli/src/Server.ts
Labels: core, n8n team

#3899 fix(editor): connections lost when renaming
  packages/editor-ui/src/components/mixins/workflowHelpers.ts
Labels: ui, n8n team

#3369 [N8N-4265] Improve docker compose setup with postgres
  docker/compose/withPostgres/docker-compose.yml
  docker/compose/withPostgresAndWorker/.env
  docker/compose/withPostgresAndWorker/README.md
  docker/compose/withPostgresAndWorker/docker-compose.yml
  docker/compose/withPostgresAndWorker/init-data.sh
Labels: community

#3887 [N8N-4339] Unify all Cron-specific code. Improve typing, and add tests.
  packages/cli/test/integration/shared/types.d.ts
  packages/cli/test/integration/shared/utils.ts
  packages/core/src/ActiveWorkflows.ts
  packages/core/src/Interfaces.ts
  packages/nodes-base/nodes/Cron/Cron.node.ts
  packages/workflow/src/Cron.ts
  packages/workflow/src/NodeHelpers.ts
  packages/workflow/src/index.ts
  packages/workflow/test/Cron.test.ts
Labels: node/improvement, core, n8n team, tech debt

#3858 Support root-level formatting
  .eslintrc.js
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/workflows/docker-images.yml
  .github/workflows/test-workflows.yml
  .github/workflows/tests.yml
  .prettierignore
  .vscode/DEBUGGER.md
  .vscode/launch.json
  CHANGELOG.md
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
  CONTRIBUTOR_LICENSE_AGREEMENT.md
  docker/compose/subfolderWithSSL/README.md
  docker/compose/subfolderWithSSL/docker-compose.yml
  docker/compose/withMariaDB/README.md
  docker/compose/withPostgres/README.md
  docker/compose/withPostgres/docker-compose.yml
  docker/images/n8n-custom/README.md
  docker/images/n8n-debian/README.md
  docker/images/n8n-rhel7/README.md
  package.json
  scripts/format.mjs
  vetur.config.js
Labels: n8n team

#3894 fix(next-cloud-node): Fix issue with credential verification and sharing file
  packages/nodes-base/nodes/NextCloud/GenericFunctions.ts
  packages/nodes-base/nodes/NextCloud/NextCloud.node.ts
Labels: n8n team, node/issue

#3865 Integrate PostHog into n8n
  package-lock.json
  packages/cli/config/schema.ts
  packages/cli/package.json
  packages/cli/src/Interfaces.ts
  packages/cli/src/InternalHooks.ts
  packages/cli/src/Server.ts
  packages/cli/src/telemetry/index.ts
  packages/cli/src/telemetry/scripts.ts
  packages/cli/test/unit/Telemetry.test.ts
  packages/design-system/src/components/N8nUserInfo/UserInfo.vue
  packages/design-system/src/main.d.ts
  packages/editor-ui/src/components/CopyInput.vue
  packages/editor-ui/src/components/CredentialEdit/CredentialEdit.vue
  packages/editor-ui/src/components/CredentialsList.vue
  packages/editor-ui/src/components/CredentialsSelectModal.vue
  packages/editor-ui/src/components/ExecutionsList.vue
  packages/editor-ui/src/components/ExpressionEdit.vue
  packages/editor-ui/src/components/MainSidebar.vue
  packages/editor-ui/src/components/NodeExecuteButton.vue
  packages/editor-ui/src/components/ParameterInput.vue
  packages/editor-ui/src/components/PersonalizationModal.vue
  packages/editor-ui/src/components/RunData.vue
  packages/editor-ui/src/components/RunDataTable.vue
  packages/editor-ui/src/components/Sticky.vue
  packages/editor-ui/src/components/Telemetry.vue
  packages/editor-ui/src/components/VariableSelectorItem.vue
  packages/editor-ui/src/components/WorkflowOpen.vue
  packages/editor-ui/src/components/mixins/workflowActivate.ts
  packages/editor-ui/src/modules/users.ts
  packages/editor-ui/src/plugins/telemetry/index.ts
  packages/editor-ui/src/plugins/telemetry/rudder-sdk.d.ts
  packages/editor-ui/src/plugins/telemetry/telemetry.types.ts
  packages/editor-ui/src/views/NodeView.vue
  packages/editor-ui/src/views/SettingsCommunityNodesView.vue
  packages/editor-ui/src/views/SettingsPersonalView.vue
  packages/editor-ui/src/views/TemplatesCollectionView.vue
  packages/editor-ui/src/views/TemplatesWorkflowView.vue
Labels: core, ui, n8n team

#3895 Fix pinned trigger execution
  packages/cli/src/Server.ts
Labels: core, n8n team

#3913 Update CHANGELOG.md
  CHANGELOG.md
Labels: n8n team

#3914 Fix community package update for major zero version
  packages/cli/src/LoadNodesAndCredentials.ts
Labels: core, n8n team

#3912 Account for enabled state in first pinned trigger
  packages/cli/src/Server.ts
Labels: core, n8n team

#3896 n8n-4331-aws-ses-sending-emails-including-special-characters-fails
  packages/nodes-base/nodes/Aws/SES/AwsSes.node.ts
Labels: n8n team, node/issue

#3922 Remove leftover hook from design system
  packages/design-system/src/components/N8nUserInfo/UserInfo.vue
Labels: ui, n8n team

#3921 Fix excessive instantiation type error for flattened execution
  packages/cli/src/Interfaces.ts
  packages/cli/src/databases/entities/WorkflowEntity.ts
Labels: core, n8n team

#3923 fix(cli): tsc build errors should fail turborepo builds as well
  packages/cli/scripts/build.mjs
Labels: core, n8n team

#3927 Account for unparseable string in JSON key migration
  packages/cli/src/databases/migrations/sqlite/1659888469333-AddJsonKeyPinData.ts
  packages/cli/src/databases/utils/migrations.types.ts
Labels: core, n8n team

#3925 Fix excess `json` key from pindata in expressions
  packages/editor-ui/src/components/RunData.vue
  packages/editor-ui/src/store.ts
Labels: ui, n8n team

#3924 N8N-4134 Add AWS cred testing and http custom calls with credentials
  packages/core/src/NodeExecuteFunctions.ts
  packages/nodes-base/credentials/Aws.credentials.ts
  packages/nodes-base/nodes/Aws/Comprehend/GenericFunctions.ts
  packages/nodes-base/nodes/Aws/DynamoDB/GenericFunctions.ts
  packages/nodes-base/nodes/Aws/GenericFunctions.ts
  packages/nodes-base/nodes/Aws/Rekognition/GenericFunctions.ts
  packages/nodes-base/nodes/Aws/S3/GenericFunctions.ts
  packages/nodes-base/nodes/Aws/SES/GenericFunctions.ts
  packages/nodes-base/nodes/Aws/Textract/AwsTextract.node.ts
  packages/nodes-base/nodes/Aws/Textract/GenericFunctions.ts
Labels: node/improvement, core, n8n team

#3816 N8N-4126 credentials injection and testing on specific nodes
  packages/nodes-base/credentials/DropcontactApi.credentials.ts
  packages/nodes-base/credentials/LemlistApi.credentials.ts
  packages/nodes-base/credentials/MailgunApi.credentials.ts
  packages/nodes-base/credentials/PhantombusterApi.credentials.ts
  packages/nodes-base/credentials/SegmentApi.credentials.ts
  packages/nodes-base/credentials/SupabaseApi.credentials.ts
  packages/nodes-base/credentials/UProcApi.credentials.ts
  packages/nodes-base/nodes/Dropcontact/Dropcontact.node.ts
  packages/nodes-base/nodes/Dropcontact/GenericFunction.ts
  packages/nodes-base/nodes/Lemlist/GenericFunctions.ts
  packages/nodes-base/nodes/Mailgun/Mailgun.node.ts
  packages/nodes-base/nodes/Phantombuster/GenericFunctions.ts
  packages/nodes-base/nodes/Segment/GenericFunctions.ts
  packages/nodes-base/nodes/Supabase/GenericFunctions.ts
  packages/nodes-base/nodes/UProc/GenericFunctions.ts
Labels: node/improvement, n8n team

#3928 Check for PostHog before feature flag call
  packages/editor-ui/src/plugins/telemetry/telemetry.types.ts
  packages/editor-ui/src/views/NodeView.vue
Labels: ui, n8n team

#3919 feat(cli): notify external hooks about user profile and password changes
  packages/cli/src/UserManagement/routes/me.ts
Labels: core, n8n team

#3864 feat(editor): mapping expressions from input table
  packages/design-system/src/components/N8nTree/Tree.stories.ts
  packages/design-system/src/components/N8nTree/Tree.vue
  packages/design-system/src/components/N8nTree/__tests__/Tree.spec.ts
  packages/design-system/src/components/N8nTree/__tests__/__snapshots__/Tree.spec.ts.snap
  packages/design-system/src/components/N8nTree/index.ts
  packages/design-system/src/plugins/n8nComponents.ts
  packages/design-system/src/styleguide/colors.stories.mdx
  packages/design-system/theme/src/_tokens.scss
  packages/editor-ui/src/Interface.ts
  packages/editor-ui/src/components/Draggable.vue
  packages/editor-ui/src/components/DraggableTarget.vue
  packages/editor-ui/src/components/InputPanel.vue
  packages/editor-ui/src/components/NodeDetailsView.vue
  packages/editor-ui/src/components/OutputPanel.vue
  packages/editor-ui/src/components/ParameterInput.vue
  packages/editor-ui/src/components/RunData.vue
  packages/editor-ui/src/components/RunDataTable.vue
  packages/editor-ui/src/modules/ui.ts
  packages/editor-ui/src/plugins/i18n/locales/en.json
Labels: ui, n8n team

#3920 Add G2 review link to Value Survey
  packages/editor-ui/src/components/ValueSurvey.vue
Labels: ui, n8n team

#3935 fix(cli): fix the tests, that broke after #3919
  packages/cli/src/UserManagement/routes/me.ts
  packages/cli/test/integration/shared/utils.ts
Labels: core, n8n team

#3930 Introduce node deprecation
  packages/editor-ui/src/components/NodeCreator/NodeCreator.vue
  packages/editor-ui/src/constants.ts
  packages/nodes-base/nodes/Start/Start.node.ts
  packages/workflow/src/Interfaces.ts
Labels: node/improvement, core, ui, n8n team

#3844 n8n-4124-overhaul-gmail-node-trigger
  packages/nodes-base/nodes/Google/Gmail/GenericFunctions.ts
  packages/nodes-base/nodes/Google/Gmail/GmailTrigger.node.json
  packages/nodes-base/nodes/Google/Gmail/GmailTrigger.node.ts
  packages/nodes-base/package.json
Labels: node/new, n8n team

#3939 fix(ci): Run test/lint workflow on all pull requests
  .github/workflows/tests.yml
Labels: core, n8n team

#3938 fix(cli): Account for non-array in pindata migration
  packages/cli/src/databases/migrations/sqlite/1659888469333-AddJsonKeyPinData.ts
Labels: core, n8n team

#3941 update expr colors
  packages/editor-ui/src/components/ParameterInput.vue
Labels: ui, n8n team

#3944 Fix feature flag check when PH is unavailable
  packages/editor-ui/src/plugins/telemetry/telemetry.types.ts
  packages/editor-ui/src/views/NodeView.vue
Labels: ui, n8n team

#3951 fix(ci): Setup a separate workflow action to test for pushes on master
  .github/workflows/ci-master.yml
  .github/workflows/ci-pull-requests.yml
Labels: n8n team

#3929 N8n 4317 refactor nodes to support paired item
  packages/nodes-base/nodes/GraphQL/GraphQL.node.ts
  packages/nodes-base/nodes/Hubspot/Hubspot.node.ts
  packages/nodes-base/nodes/Microsoft/Sql/MicrosoftSql.node.ts
  packages/nodes-base/nodes/Twitter/Twitter.node.ts
  packages/nodes-base/nodes/UnleashedSoftware/UnleashedSoftware.node.ts
  packages/nodes-base/nodes/Webflow/Webflow.node.ts
  packages/nodes-base/nodes/WooCommerce/WooCommerce.node.ts
  packages/nodes-base/nodes/Wordpress/Wordpress.node.ts
  packages/nodes-base/nodes/Xero/Xero.node.ts
  packages/nodes-base/nodes/Zammad/Zammad.node.ts
  packages/nodes-base/nodes/Zendesk/Zendesk.node.ts
  packages/nodes-base/nodes/Zoho/ZohoCrm.node.ts
  packages/nodes-base/nodes/Zoom/Zoom.node.ts
Labels: node/improvement, n8n team

#3952 Moving /executions endpoints to separate file
  packages/cli/src/Server.ts
  packages/cli/src/api/executions.api.ts
Labels: n8n team, tech debt

#3931 Expand credential sharing tests for User Management
  packages/cli/src/credentials/credentials.types.ts
  packages/cli/test/integration/credentials.ee.test.ts
  packages/cli/test/integration/credentials.test.ts
Labels: core, n8n team

#3956 Fix all type errors in design system
  packages/design-system/src/components/N8nActionToggle/ActionToggle.vue
  packages/design-system/src/components/N8nAvatar/Avatar.vue
  packages/design-system/src/components/N8nCallout/Callout.vue
  packages/design-system/src/components/N8nCheckbox/Checkbox.vue
  packages/design-system/src/components/N8nFormBox/FormBox.vue
  packages/design-system/src/components/N8nFormInput/FormInput.vue
  packages/design-system/src/components/N8nFormInputs/FormInputs.vue
  packages/design-system/src/components/N8nHeading/Heading.vue
  packages/design-system/src/components/N8nIconButton/IconButton.vue
  packages/design-system/src/components/N8nInput/Input.vue
  packages/design-system/src/components/N8nLink/Link.vue
  packages/design-system/src/components/N8nMarkdown/Markdown.vue
  packages/design-system/src/components/N8nNotice/Notice.vue
  packages/design-system/src/components/N8nRadioButtons/RadioButtons.vue
  packages/design-system/src/components/N8nSelect/Select.vue
  packages/design-system/src/components/N8nSticky/Resize.vue
  packages/design-system/src/components/N8nSticky/Sticky.vue
  packages/design-system/src/components/N8nTabs/Tabs.vue
  packages/design-system/src/components/N8nText/Text.vue
  packages/design-system/src/components/N8nTree/Tree.vue
  packages/design-system/src/components/N8nUserSelect/UserSelect.vue
  packages/design-system/src/components/N8nUsersList/UsersList.vue
  packages/design-system/src/components/ResizeObserver/ResizeObserver.vue
  packages/design-system/src/main.d.ts
  packages/design-system/src/shims-element-ui.d.ts
  packages/design-system/src/shims-vue2-boring-avatars.d.ts
  packages/design-system/src/types/form.ts
  packages/design-system/src/types/user.ts
  vetur.config.js
Labels: ui, n8n team, tech debt

#3560 Use instance URL for OAuth callback
  packages/cli/src/api/oauth2Credential.api.ts
Labels: core, community

#3967 🐛 Fix issue where the QS would be ignored
  packages/nodes-base/credentials/Aws.credentials.ts
  packages/nodes-base/nodes/Aws/S3/GenericFunctions.ts
Labels: node/improvement, n8n team

#3945 docs(license): Introduce n8n Enterprise License
  LICENSE.md
  LICENSE_EE.md
  README.md
  packages/cli/LICENSE_EE.md
  packages/core/LICENSE.md
  packages/core/LICENSE_EE.md
  packages/design-system/LICENSE.md
  packages/design-system/LICENSE_EE.md
  packages/editor-ui/LICENSE.md
  packages/editor-ui/LICENSE_EE.md
  packages/editor-ui/src/plugins/i18n/locales/en.json
  packages/node-dev/LICENSE.md
  packages/node-dev/LICENSE_EE.md
  packages/nodes-base/LICENSE.md
  packages/nodes-base/LICENSE_EE.md
  packages/workflow/LICENSE.md
  packages/workflow/LICENSE_EE.md
Labels: n8n team

#3957 Add some tests to ActiveExecutions file
  .vscode/launch.json
  packages/cli/test/unit/ActiveExecutions.test.ts
Labels: core, n8n team

#3903 💄 Added instance ID to about modal and restyled credentials docs link
  packages/design-system/src/components/N8nNotice/Notice.vue
  packages/design-system/src/components/N8nNotice/__tests__/__snapshots__/Notice.spec.ts.snap
  packages/editor-ui/src/components/AboutModal.vue
  packages/editor-ui/src/components/CredentialEdit/CredentialConfig.vue
  packages/editor-ui/src/plugins/i18n/locales/en.json
Labels: ui, n8n team

#3608 Feature/gohighlevel node - N8N-3970
  packages/nodes-base/credentials/HighLevelApi.credentials.ts
  packages/nodes-base/nodes/HighLevel/GenericFunctions.ts
  packages/nodes-base/nodes/HighLevel/HighLevel.node.json
  packages/nodes-base/nodes/HighLevel/HighLevel.node.ts
  packages/nodes-base/nodes/HighLevel/description/ContactDescription.ts
  packages/nodes-base/nodes/HighLevel/description/OpportunityDescription.ts
  packages/nodes-base/nodes/HighLevel/description/TaskDescription.ts
  packages/nodes-base/nodes/HighLevel/highLevel.svg
  packages/nodes-base/package.json
Labels: node/new, n8n team

#3972 🐛 fix sending data as query on DELETE method
  packages/cli/src/UserManagement/routes/users.ts
  packages/cli/src/api/nodes.api.ts
  packages/cli/src/requests.d.ts
  packages/cli/test/integration/credentials.api.test.ts
  packages/cli/test/integration/nodes.api.test.ts
  packages/cli/test/integration/shared/random.ts
  packages/cli/test/integration/shared/testDb.ts
  packages/cli/test/integration/users.api.test.ts
  packages/editor-ui/src/api/helpers.ts
Labels: core, ui, n8n team

#3970 fix(npm): improve .npmignore to reduce the size of the published packages
  .npmignore
  packages/design-system/.npmignore
  packages/editor-ui/.npmignore
Labels: ui, n8n team

#3979 MysqlDB credentials_entity table not exists
  packages/cli/src/databases/migrations/mysqldb/1646992772331-CreateUserManagement.ts
Labels: core, community

#3977 N8N-4467 HTTP Request node: DigestAuth failed when using query Parameters
  packages/core/src/NodeExecuteFunctions.ts
Labels: node/improvement, n8n team

#3976 feat(editor): limit when to show mapping tooltip
  packages/editor-ui/src/components/RunDataTable.vue
Labels: ui, n8n team

#3973 feat(docker): reduce the size of alpine docker images
  .dockerignore
  .github/workflows/docker-base-image.yml
  .github/workflows/docker-images-nightly.yml
  docker/images/n8n-base/.npmrc
  docker/images/n8n-base/Dockerfile
  docker/images/n8n-custom/Dockerfile
  docker/images/n8n-custom/docker-entrypoint.sh
  docker/images/n8n/Dockerfile
  docker/images/n8n/docker-entrypoint.sh
  package-lock.json
  packages/cli/package.json
  packages/node-dev/package.json
  packages/nodes-base/package.json
Labels: core, n8n team

#3978 feat(design-system,editor-ui): upgrade some of the frontend dev dependencies
  package-lock.json
  packages/design-system/.gitignore
  packages/design-system/.storybook/main.js
  packages/design-system/package.json
  packages/design-system/postcss.config.js
  packages/editor-ui/package.json
Labels: ui, n8n team

#3986 Revert: switch over to decorators to define routes (#3827)
  packages/cli/src/UserManagement/controllers/AuthController.ts
  packages/cli/src/UserManagement/controllers/MeController.ts
  packages/cli/src/UserManagement/controllers/OwnerController.ts
  packages/cli/src/UserManagement/controllers/PasswordResetController.ts
  packages/cli/src/UserManagement/controllers/UserController.ts
  packages/cli/src/UserManagement/controllers/index.ts
  packages/cli/src/UserManagement/decorators.ts
  packages/cli/src/UserManagement/routes/auth.ts
  packages/cli/src/UserManagement/routes/index.ts
  packages/cli/src/UserManagement/routes/me.ts
  packages/cli/src/UserManagement/routes/owner.ts
  packages/cli/test/integration/shared/utils.ts
Labels: core, n8n team
