Repository n8n-io/n8n, pull requests merged in 2022-02, with the labels that each got.

#2743 Fix validation on deactivation at PATCH /workfows/:id
  packages/cli/src/Server.ts
Labels: feature, n8n team

#2756 N8n 2918 support telemetry page
  packages/cli/src/Interfaces.ts
  packages/cli/src/Server.ts
  packages/editor-ui/src/App.vue
  packages/editor-ui/src/Interface.ts
  packages/editor-ui/src/components/Telemetry.vue
  packages/editor-ui/src/modules/settings.ts
  packages/editor-ui/src/plugins/telemetry/index.ts
  packages/editor-ui/src/store.ts
  packages/editor-ui/src/views/NodeView.vue
Labels: feature, n8n team

#2749 :hammer: Changed NDV opening behavior on node duplication N8N-2896
  packages/editor-ui/src/views/NodeView.vue
Labels: ui, n8n team

#2672 Remove `fibers` to support Node LTS
  docker/images/n8n-custom/Dockerfile
  docker/images/n8n-debian/Dockerfile
  docker/images/n8n/Dockerfile
  package-lock.json
  packages/cli/bin/n8n
  packages/cli/package.json
  packages/design-system/package.json
  packages/editor-ui/package.json
  packages/nodes-base/package.json
Labels: core, n8n team

#2752 ✨ Add operation to list Github files
  packages/nodes-base/nodes/Github/Github.node.ts
Labels: node/improvement, community

#2742 Add codex file for BambooHR
  packages/nodes-base/nodes/BambooHr/BambooHr.node.json
Labels: n8n team, codex

#2732 Set up tests for user management backend
  package-lock.json
  packages/cli/jest.config.js
  packages/cli/package.json
  packages/cli/src/Db.ts
  packages/cli/src/GenericHelpers.ts
  packages/cli/src/ResponseHelper.ts
  packages/cli/src/Server.ts
  packages/cli/src/UserManagement/UserManagementHelper.ts
  packages/cli/src/UserManagement/routes/index.ts
  packages/cli/src/UserManagement/routes/me.ts
  packages/cli/src/databases/entities/User.ts
  packages/cli/src/databases/entities/WorkflowEntity.ts
  packages/cli/src/databases/mysqldb/migrations/1626183952959-AddWaitColumn.ts
  packages/cli/src/databases/mysqldb/migrations/1630451444017-UpdateWorkflowCredentials.ts
  packages/cli/src/databases/postgresdb/migrations/1626176912946-AddwaitTill.ts
  packages/cli/src/databases/postgresdb/migrations/1630419189837-UpdateWorkflowCredentials.ts
  packages/cli/src/databases/sqlite/migrations/1621707690587-AddWaitColumn.ts
  packages/cli/src/databases/sqlite/migrations/1630330987096-UpdateWorkflowCredentials.ts
  packages/cli/src/databases/utils/customValidators.ts
  packages/cli/test/auth.middleware.test.ts
  packages/cli/test/me.endpoints.test.ts
  packages/cli/test/placeholder.test.ts
  packages/cli/test/shared/augmentation.d.ts
  packages/cli/test/shared/constants.ts
  packages/cli/test/shared/utils.ts
  packages/core/package.json
  packages/design-system/package.json
  packages/editor-ui/package.json
  packages/editor-ui/tests/unit/placeholder.spec.ts
  packages/nodes-base/package.json
  packages/nodes-base/test/placeholder.test.ts
  packages/workflow/package.json
Labels: feature, n8n team

#2758 Add `/owner` tests for user management backend
  package-lock.json
  packages/cli/package.json
  packages/cli/src/GenericHelpers.ts
  packages/cli/src/Server.ts
  packages/cli/src/UserManagement/Interfaces.ts
  packages/cli/src/UserManagement/UserManagementHelper.ts
  packages/cli/src/UserManagement/routes/index.ts
  packages/cli/src/UserManagement/routes/me.ts
  packages/cli/src/UserManagement/routes/owner.ts
  packages/cli/src/UserManagement/routes/passwordReset.ts
  packages/cli/src/UserManagement/routes/users.ts
  packages/cli/src/databases/entities/User.ts
  packages/cli/src/requests.d.ts
  packages/cli/test/auth.middleware.test.ts
  packages/cli/test/owner.endpoints.test.ts
  packages/cli/test/shared/utils.ts
Labels: feature, n8n team

#2777 Add `/login` tests for user management
  package-lock.json
  packages/cli/src/CredentialsHelper.ts
  packages/cli/src/Db.ts
  packages/cli/src/ResponseHelper.ts
  packages/cli/src/UserManagement/routes/auth.ts
  packages/cli/src/UserManagement/routes/index.ts
  packages/cli/src/databases/entities/User.ts
  packages/cli/test/integration/auth.endpoints.test.ts
  packages/cli/test/integration/auth.middleware.test.ts
  packages/cli/test/integration/me.endpoints.test.ts
  packages/cli/test/integration/owner.endpoints.test.ts
  packages/cli/test/integration/shared/augmentation.d.ts
  packages/cli/test/integration/shared/constants.ts
  packages/cli/test/integration/shared/utils.ts
  packages/cli/test/unit/CredentialsHelper.test.ts
  packages/cli/test/unit/Helpers.ts
Labels: feature, n8n team

#2793 Encrypt SMTP pass for user management backend
  package-lock.json
  packages/cli/commands/Interfaces.d.ts
  packages/cli/commands/start.ts
  packages/cli/config/index.ts
  packages/cli/package.json
Labels: feature, n8n team

#2745 :zap: added /workflows/demo route
  packages/editor-ui/src/components/DataDisplay.vue
  packages/editor-ui/src/router.ts
  packages/editor-ui/src/views/NodeView.vue
  packages/editor-ui/src/views/canvasHelpers.ts
Labels: feature, n8n team

#2557 🐛 Fix confusing Item Lists placeholder text
  packages/nodes-base/nodes/ItemLists/ItemLists.node.ts
Labels: node/improvement, community

#2786 :sparkles: Add optional health check endpoint to worker
  packages/cli/commands/worker.ts
  packages/cli/config/index.ts
  packages/cli/package.json
Labels: core, n8n team

#2767 :sparkles: Linear Trigger
  packages/nodes-base/credentials/LinearApi.credentials.ts
  packages/nodes-base/nodes/Linear/GenericFunctions.ts
  packages/nodes-base/nodes/Linear/LinearTrigger.node.ts
  packages/nodes-base/nodes/Linear/linear.svg
  packages/nodes-base/package.json
Labels: node/new, n8n team

#2620 Feature/halopsa node WIP
  packages/nodes-base/credentials/HaloPSAApi.credentials.ts
  packages/nodes-base/nodes/HaloPSA/GenericFunctions.ts
  packages/nodes-base/nodes/HaloPSA/HaloPSA.node.json
  packages/nodes-base/nodes/HaloPSA/HaloPSA.node.ts
  packages/nodes-base/nodes/HaloPSA/descriptions/ClientDescription.ts
  packages/nodes-base/nodes/HaloPSA/descriptions/SiteDescription.ts
  packages/nodes-base/nodes/HaloPSA/descriptions/TicketDescription.ts
  packages/nodes-base/nodes/HaloPSA/descriptions/UserDescription.ts
  packages/nodes-base/nodes/HaloPSA/descriptions/index.ts
  packages/nodes-base/nodes/HaloPSA/halopsa.svg
  packages/nodes-base/package.json
Labels: node/new, n8n team

#2801 :zap: Add StatusCallback parameter - Twilio
  packages/nodes-base/nodes/Twilio/Twilio.node.ts
Labels: node/improvement, n8n team

#2621 Refactor Zammad node
  packages/nodes-base/credentials/ZammadBasicAuthApi.credentials.ts
  packages/nodes-base/credentials/ZammadTokenAuthApi.credentials.ts
  packages/nodes-base/nodes/Zammad/GenericFunctions.ts
  packages/nodes-base/nodes/Zammad/Zammad.node.json
  packages/nodes-base/nodes/Zammad/Zammad.node.ts
  packages/nodes-base/nodes/Zammad/descriptions/GroupDescription.ts
  packages/nodes-base/nodes/Zammad/descriptions/OrganizationDescription.ts
  packages/nodes-base/nodes/Zammad/descriptions/TicketDescription.ts
  packages/nodes-base/nodes/Zammad/descriptions/UserDescription.ts
  packages/nodes-base/nodes/Zammad/descriptions/index.ts
  packages/nodes-base/nodes/Zammad/types.d.ts
  packages/nodes-base/nodes/Zammad/zammad.svg
  packages/nodes-base/package.json
Labels: node/new, n8n team

#2792 Fix: [if] deleting condition leaves empty section
  packages/editor-ui/src/components/FixedCollectionParameter.vue
Labels: ui, community

#2776 Sanitize description in uProc node
  packages/nodes-base/nodes/UProc/UProc.node.ts
Labels: node/improvement, n8n team

#2803 N8n 2857 templates env
  packages/cli/config/index.ts
  packages/cli/src/Interfaces.ts
  packages/cli/src/Server.ts
  packages/editor-ui/src/Interface.ts
  packages/editor-ui/src/modules/settings.ts
Labels: feature, n8n team

#2790 Add `/users` tests for user management backend
  packages/cli/src/UserManagement/UserManagementHelper.ts
  packages/cli/src/UserManagement/routes/index.ts
  packages/cli/src/UserManagement/routes/owner.ts
  packages/cli/src/UserManagement/routes/users.ts
  packages/cli/src/databases/entities/User.ts
  packages/cli/src/requests.d.ts
  packages/cli/test/integration/auth.endpoints.test.ts
  packages/cli/test/integration/auth.middleware.test.ts
  packages/cli/test/integration/me.endpoints.test.ts
  packages/cli/test/integration/owner.endpoints.test.ts
  packages/cli/test/integration/shared/random.ts
  packages/cli/test/integration/shared/types.d.ts
  packages/cli/test/integration/shared/utils.ts
  packages/cli/test/integration/users.endpoints.test.ts
Labels: feature, n8n team

#2819 Fix validation at `PATCH /workfows/:id`
  packages/cli/src/Server.ts
Labels: feature, n8n team

#2794 :card_file_box: Add relevant indexes in execution_entity
  packages/cli/src/databases/entities/ExecutionEntity.ts
  packages/cli/src/databases/mysqldb/migrations/1644424784709-AddExecutionEntityIndexes.ts
  packages/cli/src/databases/mysqldb/migrations/index.ts
  packages/cli/src/databases/postgresdb/migrations/1644422880309-AddExecutionEntityIndexes.ts
  packages/cli/src/databases/postgresdb/migrations/index.ts
  packages/cli/src/databases/sqlite/migrations/1644421939510-AddExecutionEntityIndexes.ts
  packages/cli/src/databases/sqlite/migrations/index.ts
Labels: core, n8n team

#2827 :zap: Add extra large size option - Telegram trigger
  packages/nodes-base/nodes/Telegram/GenericFunctions.ts
  packages/nodes-base/nodes/Telegram/TelegramTrigger.node.ts
Labels: node/improvement, community

#2780 Update en.json
  packages/editor-ui/src/components/CredentialEdit/CredentialEdit.vue
  packages/editor-ui/src/components/CredentialsList.vue
  packages/editor-ui/src/components/Error/NodeErrorView.vue
  packages/editor-ui/src/components/ExecutionsList.vue
  packages/editor-ui/src/components/MainSidebar.vue
  packages/editor-ui/src/components/NodeWebhooks.vue
  packages/editor-ui/src/components/TagsManager/TagsManager.vue
  packages/editor-ui/src/components/WorkflowActivator.vue
  packages/editor-ui/src/components/WorkflowOpen.vue
  packages/editor-ui/src/components/WorkflowSettings.vue
  packages/editor-ui/src/components/mixins/pushConnection.ts
  packages/editor-ui/src/components/mixins/showMessage.ts
  packages/editor-ui/src/components/mixins/workflowHelpers.ts
  packages/editor-ui/src/components/mixins/workflowRun.ts
  packages/editor-ui/src/plugins/i18n/locales/en.json
  packages/editor-ui/src/views/NodeView.vue
Labels: ui, n8n team

#2824 Um fe issues
  packages/design-system/src/components/N8nUserSelect/UserSelect.stories.js
  packages/design-system/src/components/N8nUserSelect/UserSelect.vue
  packages/design-system/src/components/N8nUsersList/UsersList.stories.js
  packages/design-system/src/components/N8nUsersList/UsersList.vue
  packages/editor-ui/src/App.vue
  packages/editor-ui/src/Interface.ts
  packages/editor-ui/src/components/DeleteUserModal.vue
  packages/editor-ui/src/components/SettingsSidebar.vue
  packages/editor-ui/src/modules/users.ts
  packages/editor-ui/src/views/NodeView.vue
  packages/editor-ui/src/views/SettingsUsersView.vue
  packages/editor-ui/src/views/SigninView.vue
Labels: n8n team, Project: User Management

#2833 Um email invite fix
  packages/editor-ui/src/Interface.ts
  packages/editor-ui/src/api/users.ts
  packages/editor-ui/src/components/InviteUsersModal.vue
  packages/editor-ui/src/modules/users.ts
Labels: feature, n8n team

#2832 Templates Bugs / Fixed Various Bugs / Multiply Api Request, Carousel Gradient, Core Nodes Filters
  packages/design-system/src/components/N8nMarkdown/Markdown.vue
  packages/design-system/theme/src/skeleton.scss
  packages/editor-ui/src/App.vue
  packages/editor-ui/src/Interface.ts
  packages/editor-ui/src/components/CollectionsCarousel.vue
  packages/editor-ui/src/components/MainSidebar.vue
  packages/editor-ui/src/components/NodeList.vue
  packages/editor-ui/src/components/TemplateDetails.vue
  packages/editor-ui/src/components/TemplateFilters.vue
  packages/editor-ui/src/components/TemplateList.vue
  packages/editor-ui/src/components/WorkflowPreview.vue
  packages/editor-ui/src/components/helpers.ts
  packages/editor-ui/src/constants.ts
  packages/editor-ui/src/plugins/i18n/locales/en.json
  packages/editor-ui/src/plugins/icons.ts
  packages/editor-ui/src/router.ts
  packages/editor-ui/src/views/CollectionView.vue
  packages/editor-ui/src/views/TemplateView.vue
  packages/editor-ui/src/views/TemplatesView.vue
Labels: ui, n8n team

#2825 Correctly prepends the baseURL
  packages/core/src/NodeExecuteFunctions.ts
Labels: core, n8n team

#2795 Google Chat node
  packages/nodes-base/nodes/Google/Chat/GenericFunctions.ts
  packages/nodes-base/nodes/Google/Chat/GoogleChat.node.json
  packages/nodes-base/nodes/Google/Chat/GoogleChat.node.ts
  packages/nodes-base/nodes/Google/Chat/MessageInterface.ts
  packages/nodes-base/nodes/Google/Chat/descriptions/AttachmentDescription.ts
  packages/nodes-base/nodes/Google/Chat/descriptions/IncomingWebhookDescription.ts
  packages/nodes-base/nodes/Google/Chat/descriptions/MediaDescription.ts
  packages/nodes-base/nodes/Google/Chat/descriptions/MemberDescription.ts
  packages/nodes-base/nodes/Google/Chat/descriptions/MessageDescription.ts
  packages/nodes-base/nodes/Google/Chat/descriptions/SpaceDescription.ts
  packages/nodes-base/nodes/Google/Chat/descriptions/index.ts
  packages/nodes-base/nodes/Google/Chat/googleChat.svg
  packages/nodes-base/package.json
Labels: node/new, n8n team

#2710 General database fixes for user management
  packages/cli/src/ActiveWorkflowRunner.ts
  packages/cli/src/Interfaces.ts
  packages/cli/src/PersonalizationSurvey.ts
  packages/cli/src/Server.ts
  packages/cli/src/UserManagement/UserManagementHelper.ts
  packages/cli/src/UserManagement/email/templates/invite.html
  packages/cli/src/UserManagement/routes/passwordReset.ts
  packages/cli/src/UserManagement/routes/users.ts
  packages/cli/src/databases/entities/User.ts
  packages/cli/src/databases/mysqldb/migrations/1630451444017-UpdateWorkflowCredentials.ts
  packages/cli/src/databases/mysqldb/migrations/1636626154933-CreateUserManagement.ts
  packages/cli/src/databases/mysqldb/migrations/index.ts
  packages/cli/src/databases/postgresdb/migrations/1630419189837-UpdateWorkflowCredentials.ts
  packages/cli/src/databases/postgresdb/migrations/1636626154934-CreateUserManagement.ts
  packages/cli/src/databases/postgresdb/migrations/index.ts
  packages/cli/src/databases/sqlite/migrations/1630330987096-UpdateWorkflowCredentials.ts
  packages/cli/src/databases/sqlite/migrations/1636626154932-CreateUserManagement.ts
  packages/cli/src/databases/utils/migrationHelpers.ts
  packages/cli/test/integration/passwordReset.endpoints.test.ts
  packages/cli/test/integration/users.endpoints.test.ts
Labels: Project: User Management

#2841 Add DB state check tests for user management backend
  packages/cli/test/integration/auth.endpoints.test.ts
  packages/cli/test/integration/me.endpoints.test.ts
  packages/cli/test/integration/owner.endpoints.test.ts
Labels: feature, n8n team

#2836 Add logging to user management endpoints v2
  packages/cli/src/UserManagement/UserManagementHelper.ts
  packages/cli/src/UserManagement/email/NodeMailer.ts
  packages/cli/src/UserManagement/routes/index.ts
  packages/cli/src/UserManagement/routes/me.ts
  packages/cli/src/UserManagement/routes/owner.ts
  packages/cli/src/UserManagement/routes/passwordReset.ts
  packages/cli/src/UserManagement/routes/users.ts
  packages/cli/src/databases/mysqldb/migrations/1644424784709-AddExecutionEntityIndexes.ts
  packages/cli/src/databases/postgresdb/migrations/1644422880309-AddExecutionEntityIndexes.ts
  packages/cli/src/databases/sqlite/migrations/1644421939510-AddExecutionEntityIndexes.ts
  packages/cli/test/integration/auth.endpoints.test.ts
  packages/cli/test/integration/auth.middleware.test.ts
  packages/cli/test/integration/me.endpoints.test.ts
  packages/cli/test/integration/owner.endpoints.test.ts
  packages/cli/test/integration/passwordReset.endpoints.test.ts
Labels: feature, n8n team

#2859 Display hiring banner in browser console
  packages/cli/src/Interfaces.ts
  packages/cli/src/Server.ts
  packages/editor-ui/src/App.vue
  packages/editor-ui/src/Interface.ts
  packages/editor-ui/src/constants.ts
  packages/editor-ui/src/modules/settings.ts
Labels: ui, n8n team

#2831 Create credentials namespace and add tests
  packages/cli/src/Server.ts
  packages/cli/src/UserManagement/Interfaces.ts
  packages/cli/src/api/namespaces/credentials.ts
  packages/cli/src/databases/entities/CredentialsEntity.ts
  packages/cli/src/databases/entities/SharedCredentials.ts
  packages/cli/src/databases/entities/SharedWorkflow.ts
  packages/cli/src/requests.d.ts
  packages/cli/test/integration/auth.endpoints.test.ts
  packages/cli/test/integration/credentials.endpoints.test.ts
  packages/cli/test/integration/shared/constants.ts
  packages/cli/test/integration/shared/types.d.ts
  packages/cli/test/integration/shared/utils.ts
  packages/cli/test/integration/users.endpoints.test.ts
Labels: feature, n8n team

#2858 :bug: Swallow telemetry error and only log in warn and debug mode
  packages/cli/src/CredentialsHelper.ts
  packages/cli/src/NodeTypes.ts
  packages/cli/src/telemetry/index.ts
  packages/editor-ui/src/components/mixins/workflowHelpers.ts
  packages/workflow/src/Interfaces.ts
  packages/workflow/src/TelemetryHelpers.ts
  packages/workflow/test/Helpers.ts
  packages/workflow/test/RoutingNode.test.ts
Labels: core, n8n team

#2816 N8N-2925 Fix for VUE_APP_PUBLIC_PATH break
  packages/editor-ui/src/main.ts
  packages/editor-ui/src/public_path.js
  packages/editor-ui/vue.config.js
Labels: ui, n8n team

#2857 Fix placeholder display in creds config modal
  packages/editor-ui/src/plugins/i18n/index.ts
Labels: ui, n8n team

#2850 Add parent id to children blocks
  packages/nodes-base/nodes/Notion/v2/NotionV2.node.ts
Labels: node/improvement, n8n team

#2750 :bug: Fix bug and add improvements to Notion
  packages/nodes-base/nodes/Notion/GenericFunctions.ts
  packages/nodes-base/nodes/Notion/v1/NotionV1.node.ts
  packages/nodes-base/nodes/Notion/v2/NotionV2.node.ts
Labels: node/improvement, n8n team

#2853 Add auth middleware tests for user management backend
  packages/cli/src/UserManagement/UserManagementHelper.ts
  packages/cli/src/UserManagement/routes/auth.ts
  packages/cli/src/UserManagement/routes/index.ts
  packages/cli/src/UserManagement/routes/passwordReset.ts
  packages/cli/src/UserManagement/routes/users.ts
  packages/cli/test/integration/auth.middleware.test.ts
  packages/cli/test/integration/shared/constants.ts
Labels: feature, n8n team

#2874 Remove test description wrappers for user management backend
  packages/cli/test/integration/auth.endpoints.test.ts
  packages/cli/test/integration/me.endpoints.test.ts
  packages/cli/test/integration/owner.endpoints.test.ts
Labels: feature, n8n team

#2532 ✨ Add support for Asana Project Creation
  packages/nodes-base/nodes/Asana/Asana.node.ts
Labels: node/improvement, community

#2614 (fix) fix security vulnerability in the hive node
  packages/nodes-base/nodes/TheHive/GenericFunctions.ts
Labels: node/improvement, community

#2855 🐛 [Orbit] Use correct workspace identifier for API requests [N8N-3007]
  packages/nodes-base/nodes/Orbit/Orbit.node.ts
Labels: node/improvement, n8n team

#2697 Runtime checks for credentials load and execute workflows
  packages/cli/commands/execute.ts
  packages/cli/commands/executeBatch.ts
  packages/cli/commands/worker.ts
  packages/cli/src/ActiveWorkflowRunner.ts
  packages/cli/src/CredentialsHelper.ts
  packages/cli/src/Interfaces.ts
  packages/cli/src/Server.ts
  packages/cli/src/UserManagement/UserManagementHelper.ts
  packages/cli/src/WaitTracker.ts
  packages/cli/src/WaitingWebhooks.ts
  packages/cli/src/WebhookHelpers.ts
  packages/cli/src/WorkflowExecuteAdditionalData.ts
  packages/cli/src/WorkflowHelpers.ts
  packages/cli/src/WorkflowRunner.ts
  packages/cli/src/WorkflowRunnerProcess.ts
  packages/cli/src/api/namespaces/credentials.ts
  packages/cli/src/requests.d.ts
  packages/core/src/NodeExecuteFunctions.ts
  packages/core/test/Helpers.ts
  packages/workflow/src/Interfaces.ts
  packages/workflow/test/Helpers.ts
Labels: n8n team

#2839 Mautic node extended
  package-lock.json
  packages/nodes-base/nodes/Mautic/ContactDescription.ts
  packages/nodes-base/nodes/Mautic/GenericFunctions.ts
  packages/nodes-base/nodes/Mautic/Mautic.node.ts
  packages/nodes-base/nodes/Mautic/SegmentEmailDescription.ts
Labels: node/improvement, n8n team

#2845 Onfleet Node & Trigger
  packages/nodes-base/credentials/OnfleetApi.credentials.ts
  packages/nodes-base/nodes/Onfleet/GenericFunctions.ts
  packages/nodes-base/nodes/Onfleet/Onfleet.node.ts
  packages/nodes-base/nodes/Onfleet/Onfleet.svg
  packages/nodes-base/nodes/Onfleet/Onfleet.ts
  packages/nodes-base/nodes/Onfleet/OnfleetTrigger.node.ts
  packages/nodes-base/nodes/Onfleet/WebhookMapping.ts
  packages/nodes-base/nodes/Onfleet/descriptions/AdministratorDescription.ts
  packages/nodes-base/nodes/Onfleet/descriptions/ContainerDescription.ts
  packages/nodes-base/nodes/Onfleet/descriptions/DestinationDescription.ts
  packages/nodes-base/nodes/Onfleet/descriptions/HubDescription.ts
  packages/nodes-base/nodes/Onfleet/descriptions/OnfleetWebhookDescription.ts
  packages/nodes-base/nodes/Onfleet/descriptions/OrganizationDescription.ts
  packages/nodes-base/nodes/Onfleet/descriptions/RecipientDescription.ts
  packages/nodes-base/nodes/Onfleet/descriptions/TaskDescription.ts
  packages/nodes-base/nodes/Onfleet/descriptions/TeamDescription.ts
  packages/nodes-base/nodes/Onfleet/descriptions/WebhookDescription.ts
  packages/nodes-base/nodes/Onfleet/descriptions/WorkerDescription.ts
  packages/nodes-base/nodes/Onfleet/interfaces.ts
  packages/nodes-base/package.json
  packages/workflow/src/NodeErrors.ts
Labels: node/new, n8n team

#2882 Set up credentials router for user management backend
  packages/cli/src/Server.ts
  packages/cli/src/api/credentials.api.ts
  packages/cli/src/api/namespaces/credentials.ts
  packages/cli/test/integration/auth.endpoints.test.ts
  packages/cli/test/integration/auth.middleware.test.ts
  packages/cli/test/integration/credentials.api.test.ts
  packages/cli/test/integration/me.endpoints.test.ts
  packages/cli/test/integration/owner.endpoints.test.ts
  packages/cli/test/integration/passwordReset.endpoints.test.ts
  packages/cli/test/integration/shared/types.d.ts
  packages/cli/test/integration/shared/utils.ts
  packages/cli/test/integration/users.endpoints.test.ts
  packages/editor-ui/src/api/credentials.ts
Labels: feature, n8n team
