Repository n8n-io/n8n, pull requests merged in 2022-09, with the labels that each got.

#3991 Fix missing slash in oauth2 urls
  packages/cli/src/api/oauth2Credential.api.ts
Labels: core, n8n team

#3969 Create first PH experiment
  packages/editor-ui/src/plugins/telemetry/telemetry.types.ts
  packages/editor-ui/src/views/NodeView.vue
Labels: ui, n8n team

#3901 n8n-4344-insert-and-update-operations-post-null-values-MongoDB-node
  packages/nodes-base/nodes/MongoDb/MongoDb.node.ts
  packages/nodes-base/nodes/MongoDb/mongo.node.options.ts
  packages/nodes-base/nodes/MongoDb/mongo.node.utils.ts
Labels: n8n team, node/issue

#3966 N8N-4345 add testing to database and protocols
  packages/nodes-base/nodes/EmailReadImap/EmailReadImap.node.ts
  packages/nodes-base/nodes/Ftp/Ftp.node.ts
  packages/nodes-base/nodes/MQTT/Mqtt.node.ts
  packages/nodes-base/nodes/Microsoft/Sql/MicrosoftSql.node.ts
  packages/nodes-base/nodes/MySql/MySql.node.ts
  packages/nodes-base/nodes/Postgres/Postgres.node.ts
  packages/nodes-base/nodes/RabbitMQ/RabbitMQ.node.ts
  packages/nodes-base/nodes/Redis/Redis.node.ts
Labels: node/improvement, n8n team

#3997 🐛 initialize mailer just if connection can be verified
  packages/cli/src/UserManagement/email/UserManagementMailer.ts
Labels: core, n8n team

#3946 Fix disabled parent output in partial execution
  packages/core/src/WorkflowExecute.ts
  packages/editor-ui/src/components/mixins/workflowRun.ts
Labels: core, ui, n8n team

#4001 fix: remove duplicate wrap of paired item data
  packages/nodes-base/nodes/Hubspot/Hubspot.node.ts
  packages/nodes-base/nodes/Notion/v2/NotionV2.node.ts
  packages/nodes-base/nodes/Postgres/Postgres.node.functions.ts
  packages/nodes-base/nodes/Webflow/Webflow.node.ts
  packages/nodes-base/nodes/WooCommerce/WooCommerce.node.ts
  packages/nodes-base/nodes/Wordpress/Wordpress.node.ts
  packages/nodes-base/nodes/Xero/Xero.node.ts
  packages/nodes-base/nodes/Zammad/Zammad.node.ts
  packages/nodes-base/nodes/Zendesk/Zendesk.node.ts
  packages/nodes-base/nodes/Zoho/ZohoCrm.node.ts
  packages/nodes-base/nodes/Zoom/Zoom.node.ts
Labels: node/improvement, n8n team

#4009 Raindrop- Fix issue refreshing access token - N8N-4500
  packages/nodes-base/nodes/HttpRequest/HttpRequest.node.ts
  packages/nodes-base/nodes/Raindrop/GenericFunctions.ts
Labels: node/improvement, n8n team

#4006 feat (TelegramTrigger Node): added notice explaining behavior when several attachments are uploaded n8n-4310
  packages/nodes-base/nodes/Telegram/TelegramTrigger.node.ts
Labels: node/improvement, n8n team

#4012 feat: add possibility to configure stop time for workers
  packages/cli/commands/worker.ts
  packages/cli/config/schema.ts
Labels: n8n team

#3984 n8n-4479 - Pagination issue with Monica CRM - N8N-4479
  packages/nodes-base/nodes/MonicaCrm/GenericFunctions.ts
Labels: node/improvement, n8n team

#3996 n8n-4505 - Fixes Shopify Get All issue when empty query items are sent
  packages/nodes-base/nodes/Shopify/GenericFunctions.ts
Labels: n8n team, node/issue

#4004 n8n-4513 - Fixes request id not being sent in Beeminder node - N8N-4513
  packages/nodes-base/credentials/BeeminderApi.credentials.ts
  packages/nodes-base/nodes/Beeminder/Beeminder.node.ts
  packages/nodes-base/nodes/Beeminder/GenericFunctions.ts
Labels: node/improvement, n8n team

#3999 ⚡️ adjust credentials test route to also allow testing for sharees
  packages/cli/src/credentials/credentials.controller.ee.ts
  packages/editor-ui/src/components/CredentialEdit/CredentialEdit.vue
Labels: core, n8n team

#4016 n8n-4524 - fix graphql return items
  packages/nodes-base/nodes/GraphQL/GraphQL.node.ts
Labels: node/improvement, n8n team

#4017 n8n-4525 - Fix binary data not being returned in Github node
  packages/nodes-base/nodes/Github/Github.node.ts
Labels: node/improvement, n8n team

#4013 Fixes mysql migration issue with adding execution entity indexes
  packages/cli/src/databases/migrations/mysqldb/1644424784709-AddExecutionEntityIndexes.ts
  packages/cli/src/databases/migrations/mysqldb/1652905585850-AddAPIKeyColumn.ts
Labels: core, n8n team

#3988 feat(cli): add external hooks for when members are added or deleted
  packages/cli/src/UserManagement/routes/me.ts
  packages/cli/src/UserManagement/routes/users.ts
  packages/cli/test/integration/shared/utils.ts
Labels: core, n8n team

#3975 fix(Kafka): kafka trigger not work - N8N-4476
  packages/nodes-base/credentials/Kafka.credentials.ts
  packages/nodes-base/nodes/Kafka/Kafka.node.ts
  packages/nodes-base/nodes/Kafka/KafkaTrigger.node.ts
Labels: node/improvement, community

#4014 User management P2 Front End bug bash
  packages/design-system/src/components/N8nActionBox/ActionBox.vue
  packages/design-system/src/components/N8nActionBox/__tests__/ActionBox.spec.ts
  packages/design-system/src/components/N8nActionBox/__tests__/__snapshots__/ActionBox.spec.ts.snap
  packages/design-system/src/components/N8nBadge/Badge.vue
  packages/design-system/src/components/N8nCard/Card.vue
  packages/design-system/src/components/N8nCard/__tests__/__snapshots__/Card.spec.ts.snap
  packages/design-system/src/components/N8nInfoTip/InfoTip.vue
  packages/design-system/src/components/N8nInfoTip/__tests__/InfoTip.spec.ts
  packages/design-system/src/components/N8nInfoTip/__tests__/__snapshots__/InfoTip.spec.ts.snap
  packages/design-system/src/components/N8nInput/__tests__/Input.spec.ts
  packages/design-system/src/components/N8nInput/__tests__/__snapshots__/Input.spec.ts.snap
  packages/design-system/src/components/N8nPopover/Popover.stories.js
  packages/design-system/src/components/N8nPopover/Popover.vue
  packages/design-system/src/components/N8nPopover/index.ts
  packages/design-system/src/components/N8nUserInfo/UserInfo.vue
  packages/design-system/src/components/N8nUsersList/UsersList.vue
  packages/design-system/src/plugins/elementUIComponents.ts
  packages/design-system/src/plugins/n8nComponents.ts
  packages/design-system/theme/src/common/var.scss
  packages/design-system/theme/src/message-box.scss
  packages/design-system/theme/src/select-dropdown.scss
  packages/design-system/theme/src/select.scss
  packages/editor-ui/src/Interface.ts
  packages/editor-ui/src/api/nodes.ts
  packages/editor-ui/src/components/Banner.vue
  packages/editor-ui/src/components/CopyInput.vue
  packages/editor-ui/src/components/CredentialCard.vue
  packages/editor-ui/src/components/CredentialEdit/CredentialConfig.vue
  packages/editor-ui/src/components/CredentialEdit/CredentialEdit.vue
  packages/editor-ui/src/components/CredentialEdit/CredentialSharing.ee.vue
  packages/editor-ui/src/components/CredentialIcon.vue
  packages/editor-ui/src/components/FeatureComingSoon.vue
  packages/editor-ui/src/components/InlineNameEdit.vue
  packages/editor-ui/src/components/NodeTitle.vue
  packages/editor-ui/src/components/TimeAgo.vue
  packages/editor-ui/src/components/WorkflowCard.vue
  packages/editor-ui/src/components/layouts/PageViewLayout.vue
  packages/editor-ui/src/components/layouts/PageViewLayoutList.vue
  packages/editor-ui/src/components/mixins/nodeHelpers.ts
  packages/editor-ui/src/constants.ts
  packages/editor-ui/src/modules/credentials.ee.ts
  packages/editor-ui/src/modules/credentials.ts
  packages/editor-ui/src/permissions.ts
  packages/editor-ui/src/plugins/i18n/locales/en.json
  packages/editor-ui/src/store.ts
  packages/editor-ui/src/views/CredentialsView.vue
Labels: ui, n8n team

#4022 fix(Node Gmail): fixed bug related to paired items n8n-4526
  packages/nodes-base/nodes/Google/Gmail/Gmail.node.ts
Labels: n8n team, node/issue

#3955 [N8N-4399]: Audit the use of v-html
  packages/editor-ui/src/components/CommunityPackageInstallModal.vue
  packages/editor-ui/src/components/CommunityPackageManageConfirmModal.vue
  packages/editor-ui/src/components/MainHeader/ExecutionDetails/ReadOnly.vue
  packages/editor-ui/src/components/Node.vue
  packages/editor-ui/src/components/NodeCredentials.vue
  packages/editor-ui/src/components/NodeSettings.vue
  packages/editor-ui/src/components/ParameterIssues.vue
  packages/editor-ui/src/components/RunDataTable.vue
  packages/editor-ui/src/components/TitledList.vue
  packages/editor-ui/src/components/TriggerPanel.vue
  packages/editor-ui/src/components/WorkflowSettings.vue
  packages/editor-ui/src/main.ts
  packages/editor-ui/src/plugins/i18n/index.ts
  packages/editor-ui/src/plugins/i18n/locales/en.json
  packages/editor-ui/src/views/SettingsApiView.vue
  packages/editor-ui/src/views/SettingsUsersView.vue
Labels: ui, n8n team, tech debt

#3974 Trello and Airtable search backend
  packages/cli/src/Server.ts
  packages/nodes-base/nodes/Airtable/Airtable.node.ts
  packages/nodes-base/nodes/Trello/AttachmentDescription.ts
  packages/nodes-base/nodes/Trello/BoardDescription.ts
  packages/nodes-base/nodes/Trello/BoardMemberDescription.ts
  packages/nodes-base/nodes/Trello/CardCommentDescription.ts
  packages/nodes-base/nodes/Trello/CardDescription.ts
  packages/nodes-base/nodes/Trello/ChecklistDescription.ts
  packages/nodes-base/nodes/Trello/LabelDescription.ts
  packages/nodes-base/nodes/Trello/ListDescription.ts
  packages/nodes-base/nodes/Trello/Trello.node.ts
  packages/nodes-base/nodes/Trello/v1/AttachmentDescription.ts
  packages/nodes-base/nodes/Trello/v1/BoardDescription.ts
  packages/nodes-base/nodes/Trello/v1/CardCommentDescription.ts
  packages/nodes-base/nodes/Trello/v1/GenericFunctions.ts
  packages/nodes-base/nodes/Trello/v1/TrelloV1.node.ts
  packages/nodes-base/nodes/Trello/v1/VersionDescription.ts
  packages/nodes-base/nodes/Trello/v2/BoardMemberDescription.ts
  packages/nodes-base/nodes/Trello/v2/CardDescription.ts
  packages/nodes-base/nodes/Trello/v2/ChecklistDescription.ts
  packages/nodes-base/nodes/Trello/v2/GenericFunctions.ts
  packages/nodes-base/nodes/Trello/v2/LabelDescription.ts
  packages/nodes-base/nodes/Trello/v2/ListDescription.ts
  packages/nodes-base/nodes/Trello/v2/TrelloV2.node.ts
  packages/nodes-base/nodes/Trello/v2/VersionDescription.ts
Labels: node/improvement, node/new, core, n8n team

#3936 List mode search endpoint
  packages/cli/src/Server.ts
  packages/cli/src/requests.d.ts
  packages/core/src/LoadNodeListSearch.ts
  packages/core/src/index.ts
  packages/nodes-base/nodes/Airtable/Airtable.node.ts
  packages/nodes-base/nodes/Google/Drive/GoogleDrive.node.ts
  packages/nodes-base/nodes/Google/Drive/v1/GoogleDriveV1.node.ts
  packages/nodes-base/nodes/Google/Drive/v1/VersionDescription.ts
  packages/nodes-base/nodes/Google/Drive/v3/GoogleDriveV3.node.ts
  packages/nodes-base/nodes/Google/Drive/v3/VersionDescription.ts
  packages/nodes-base/nodes/Trello/AttachmentDescription.ts
  packages/nodes-base/nodes/Trello/BoardDescription.ts
  packages/nodes-base/nodes/Trello/BoardMemberDescription.ts
  packages/nodes-base/nodes/Trello/CardCommentDescription.ts
  packages/nodes-base/nodes/Trello/CardDescription.ts
  packages/nodes-base/nodes/Trello/ChecklistDescription.ts
  packages/nodes-base/nodes/Trello/LabelDescription.ts
  packages/nodes-base/nodes/Trello/ListDescription.ts
  packages/nodes-base/nodes/Trello/Trello.node.ts
  packages/nodes-base/nodes/Trello/v1/AttachmentDescription.ts
  packages/nodes-base/nodes/Trello/v1/BoardDescription.ts
  packages/nodes-base/nodes/Trello/v1/CardCommentDescription.ts
  packages/nodes-base/nodes/Trello/v1/GenericFunctions.ts
  packages/nodes-base/nodes/Trello/v1/TrelloV1.node.ts
  packages/nodes-base/nodes/Trello/v1/VersionDescription.ts
  packages/nodes-base/nodes/Trello/v2/BoardMemberDescription.ts
  packages/nodes-base/nodes/Trello/v2/CardDescription.ts
  packages/nodes-base/nodes/Trello/v2/ChecklistDescription.ts
  packages/nodes-base/nodes/Trello/v2/GenericFunctions.ts
  packages/nodes-base/nodes/Trello/v2/LabelDescription.ts
  packages/nodes-base/nodes/Trello/v2/ListDescription.ts
  packages/nodes-base/nodes/Trello/v2/TrelloV2.node.ts
  packages/nodes-base/nodes/Trello/v2/VersionDescription.ts
  packages/workflow/src/Interfaces.ts
Labels: node/improvement, core, n8n team

#4028 fix(cli): include "auth-excluded" endpoints on the history middleware as well
  packages/cli/src/Server.ts
Labels: core, n8n team

#4029 n8n-4535 - fix(awsLambda Node): fix json data being sent to AWS Lambda as string
  packages/nodes-base/nodes/Aws/GenericFunctions.ts
Labels: n8n team, node/issue

#4010 ci: check commit message format
  .github/workflows/ci-pull-requests.yml
  .gitignore
Labels: n8n team

#4032 🐛 Fixing email submission for invited users who opted to be contacted
  packages/editor-ui/src/modules/ui.ts
Labels: ui, n8n team

#4039 fix(aws): handle query string and body properly for aws related requests
  packages/core/src/NodeExecuteFunctions.ts
  packages/nodes-base/credentials/Aws.credentials.ts
  packages/nodes-base/nodes/Aws/S3/GenericFunctions.ts
Labels: node/improvement, core, n8n team

#4025 N8N-4531 update cloud coming soon features
  packages/editor-ui/src/Interface.ts
  packages/editor-ui/src/components/FeatureComingSoon.vue
  packages/editor-ui/src/modules/settings.ts
  packages/editor-ui/src/modules/ui.ts
  packages/editor-ui/src/plugins/i18n/locales/en.json
  packages/editor-ui/src/views/SettingsFakeDoorView.vue
Labels: ui, n8n team

#4023 N8N-4527 implementing credential sharing FE telemetry
  packages/editor-ui/src/components/CredentialEdit/CredentialEdit.vue
  packages/editor-ui/src/views/CredentialsView.vue
Labels: ui, n8n team

#4041 fix(editor-ui): Disable editing in Function nodes in executions view
  packages/editor-ui/src/components/CodeEdit.vue
  packages/editor-ui/src/components/ParameterInput.vue
Labels: ui, n8n team

#4043 fix(editor): Wrong popup title when "Click To Copy" on OAuth2 Redirect Url credentials
  packages/editor-ui/src/components/CredentialEdit/CredentialConfig.vue
Labels: ui, n8n team

#4048 fix(editor): use correct attribute on button to make it full width
  packages/editor-ui/src/components/MultipleParameter.vue
Labels: ui, n8n team

#4052 fix(gmail): fix node and improve helper so to avoid double wrapping in json key
  packages/core/src/NodeExecuteFunctions.ts
  packages/nodes-base/nodes/Google/Gmail/Gmail.node.ts
Labels: core, n8n team

#4057 refactor(nodes-base): Apply lint rule `cred-class-field-authenticate-type-assertion`
  .eslintrc.js
  packages/nodes-base/credentials/KoBoToolboxApi.credentials.ts
  packages/nodes-base/credentials/UrlScanIoApi.credentials.ts
Labels: n8n team, node/linting, tech debt

#4054 fix(Hubspot Node): Correct canvas name of HubSpot node
  packages/nodes-base/nodes/Hubspot/Hubspot.node.ts
Labels: node/improvement, n8n team

#4063 refactor(core): move tags endpoints to a separate file n8n-4580
  packages/cli/src/Server.ts
  packages/cli/src/api/tags.api.ts
Labels: n8n team, tech debt

#4040 refactor(editor-ui): Update telemetry
  packages/cli/src/InternalHooks.ts
  packages/cli/src/telemetry/index.ts
  packages/design-system/src/components/N8nMarkdown/Markdown.vue
  packages/design-system/src/components/N8nSticky/Sticky.vue
  packages/design-system/src/components/N8nUserInfo/UserInfo.vue
  packages/design-system/src/components/N8nUsersList/UsersList.vue
  packages/editor-ui/src/components/CopyInput.vue
  packages/editor-ui/src/components/CredentialsList.vue
  packages/editor-ui/src/components/ExecutionsList.vue
  packages/editor-ui/src/components/ExpressionEdit.vue
  packages/editor-ui/src/components/InlineNameEdit.vue
  packages/editor-ui/src/components/MainSidebar.vue
  packages/editor-ui/src/components/Node.vue
  packages/editor-ui/src/components/ParameterInput.vue
  packages/editor-ui/src/components/RunData.vue
  packages/editor-ui/src/components/Sticky.vue
  packages/editor-ui/src/components/Telemetry.vue
  packages/editor-ui/src/components/VariableSelectorItem.vue
  packages/editor-ui/src/components/WorkflowOpen.vue
  packages/editor-ui/src/plugins/telemetry/index.ts
  packages/editor-ui/src/views/SettingsApiView.vue
  packages/editor-ui/src/views/SettingsPersonalView.vue
Labels: core, ui, n8n team

#4066 fix(cli): password reset should trigger internal and external hooks
  packages/cli/src/UserManagement/routes/passwordReset.ts
  packages/cli/test/integration/shared/utils.ts
Labels: core, n8n team

#3892 Improve typing on Queue and Jobs
  packages/cli/commands/worker.ts
  packages/cli/src/Interfaces.ts
  packages/cli/src/Queue.ts
  packages/cli/src/WorkflowRunner.ts
Labels: core, n8n team, tech debt

#3876 [N8N-4332] Setup Typescript incremental builds
  packages/cli/tsconfig.json
  packages/core/tsconfig.json
  packages/design-system/tsconfig.json
  packages/editor-ui/tsconfig.json
  packages/node-dev/src/tsconfig-build.json
  packages/node-dev/tsconfig.json
  packages/nodes-base/tsconfig.json
  packages/workflow/tsconfig.json
Labels: core, ui, n8n team, tech debt

#4065 ci: trigger linting on PR title change
  .github/workflows/ci-pull-requests.yml
Labels: n8n team

#4045 feat(dt-functions): introduce date expression extensions
  .vscode/launch.json
  packages/workflow/src/Extensions/DateExtensions.ts
  packages/workflow/src/Extensions/ExpressionExtension.ts
  packages/workflow/test/ExpressionExtensions.test.ts
Labels: core, n8n team

#3958 fix(workflow): remove a few `ts-ignore` and `eslint-disable`
  packages/workflow/src/Expression.ts
  packages/workflow/src/Interfaces.ts
  packages/workflow/src/NodeErrors.ts
  packages/workflow/src/NodeHelpers.ts
  packages/workflow/src/WorkflowDataProxy.ts
  packages/workflow/src/types.d.ts
  packages/workflow/test/RoutingNode.test.ts
  packages/workflow/test/Workflow.test.ts
  packages/workflow/test/WorkflowDataProxy.test.ts
Labels: core, n8n team

#4049 fix(typescript): Use consistent typescript configs - N8N-4552
  docker/images/n8n-custom/Dockerfile
  packages/cli/jest.config.js
  packages/cli/tsconfig.json
  packages/core/package.json
  packages/core/tsconfig.json
  packages/design-system/.storybook/main.js
  packages/design-system/src/shims-tsx.d.ts
  packages/design-system/tsconfig.json
  packages/editor-ui/jest.config.js
  packages/editor-ui/src/shims-tsx.d.ts
  packages/editor-ui/tsconfig.json
  packages/node-dev/src/tsconfig-build.json
  packages/node-dev/tsconfig.json
  packages/nodes-base/package.json
  packages/nodes-base/tsconfig.json
  packages/workflow/package.json
  packages/workflow/tsconfig.json
  tsconfig.json
Labels: node/improvement, core, ui, n8n team

#3906 feat(cli): Load all nodes and credentials code in isolation - N8N-4362
  packages/cli/src/CommunityNodes/helpers.ts
  packages/cli/src/LoadNodesAndCredentials.ts
  packages/cli/src/WorkflowRunnerProcess.ts
Labels: core, n8n team

#4044 feat(dt-functions): introduce array expression extensions
  packages/workflow/src/Extensions/ArrayExtensions.ts
  packages/workflow/src/Extensions/ExpressionExtension.ts
  packages/workflow/test/ExpressionExtensions.test.ts
Labels: core, n8n team

#4046 feat(dt-functions): introduce number expression extensions
  packages/workflow/src/Expression.ts
  packages/workflow/src/Extensions/ArrayExtensions.ts
  packages/workflow/src/Extensions/DateExtensions.ts
  packages/workflow/src/Extensions/ExpressionExtension.ts
  packages/workflow/src/Extensions/ExtensionError.ts
  packages/workflow/src/Extensions/NumberExtensions.ts
  packages/workflow/src/Extensions/StringExtensions.ts
  packages/workflow/test/ExpressionExtensions.test.ts
Labels: core, n8n team

#3845 fix(core & function nodes): Update function nodes to work with binary-data-mode 'filesystem'.
  packages/core/src/BinaryDataManager/index.ts
  packages/core/src/Interfaces.ts
  packages/core/src/NodeExecuteFunctions.ts
  packages/core/test/NodeExecuteFunctions.test.ts
  packages/nodes-base/nodes/Function/Function.node.ts
  packages/nodes-base/nodes/FunctionItem/FunctionItem.node.ts
  packages/workflow/src/Interfaces.ts
Labels: node/improvement, core, community

#4073 refactor(nodes-base): Apply lint rule `node-param-display-name-not-first-position`
  .eslintrc.js
  packages/nodes-base/nodes/PostBin/BinDescription.ts
  packages/nodes-base/nodes/PostBin/RequestDescription.ts
  packages/nodes-base/nodes/SendInBlue/EmailDescription.ts
  packages/nodes-base/nodes/SendInBlue/SendInBlueTrigger.node.ts
  packages/nodes-base/nodes/Spotify/Spotify.node.ts
  packages/nodes-base/nodes/TheHive/descriptions/ObservableDescription.ts
Labels: n8n team, node/linting, tech debt

#4069 Serve CSS files for `editor-ui` Vite migration
  packages/cli/src/Server.ts
Labels: core, n8n team, tech debt

#4050 fix(eslint): setup eslint to run on every package - N8N-4553
  .eslintignore
  .eslintrc.js
  package-lock.json
  package.json
  packages/@n8n_io/eslint-config/base.js
  packages/@n8n_io/eslint-config/frontend.js
  packages/@n8n_io/eslint-config/node.js
  packages/@n8n_io/eslint-config/package.json
  packages/cli/.eslintrc.js
  packages/cli/package.json
  packages/cli/src/databases/entities/User.ts
  packages/core/.eslintrc.js
  packages/core/package.json
  packages/design-system/.eslintrc.js
  packages/design-system/package.json
  packages/editor-ui/.eslintrc.js
  packages/editor-ui/package.json
  packages/editor-ui/tests/e2e/.eslintrc.js
  packages/node-dev/.eslintrc.js
  packages/node-dev/package.json
  packages/nodes-base/.eslintrc.js
  packages/nodes-base/nodes/Spotify/Spotify.node.ts
  packages/nodes-base/package.json
  packages/workflow/.eslintrc.js
  packages/workflow/package.json
Labels: core, ui, n8n team

#4078 test: Add tests for Credential Types
  packages/cli/test/unit/CredentialTypes.test.ts
Labels: n8n team, tech debt

#4080 Suggestions for node renaming fix
  packages/workflow/src/Workflow.ts
Labels: core, n8n team

#4071 test: Add more tests to active executions file
  packages/cli/test/unit/ActiveExecutions.test.ts
Labels: core, n8n team

#4079 fix: Fixed bug causing instanceOwner to become credential owner on update.
  packages/editor-ui/src/components/CredentialEdit/CredentialConfig.vue
  packages/editor-ui/src/components/CredentialEdit/CredentialEdit.vue
  packages/editor-ui/src/modules/credentials.ts
Labels: ui, n8n team, Project: User Management

#4082 fix(cli): avoid scanning unnecessary directories on windows
  packages/cli/commands/import/credentials.ts
  packages/cli/commands/import/workflow.ts
  packages/cli/src/LoadNodesAndCredentials.ts
  packages/nodes-base/nodes/ReadBinaryFiles/ReadBinaryFiles.node.ts
Labels: node/improvement, core, n8n team

#4077 test(UM tests): add missing UM tests n8n-3648
  packages/cli/test/integration/users.api.test.ts
  packages/nodes-base/nodes/Function/Function.node.ts
  packages/nodes-base/nodes/FunctionItem/FunctionItem.node.ts
Labels: n8n team, tech debt

#4067 fix(core): fix issue with returnJsonArray helper breaking nodes that return no data
  packages/core/src/NodeExecuteFunctions.ts
Labels: core, n8n team

#4084 fix(cli): load nodes and credentials on windows using the correct file-path
  packages/cli/src/CommunityNodes/helpers.ts
Labels: core, n8n team

#3775 feat(Merge Node): overhaul of merge node N8N-4205
  packages/nodes-base/nodes/ItemLists/ItemLists.node.ts
  packages/nodes-base/nodes/Merge/Merge.node.json
  packages/nodes-base/nodes/Merge/Merge.node.ts
  packages/nodes-base/nodes/Merge/v1/MergeV1.node.ts
  packages/nodes-base/nodes/Merge/v2/GenericFunctions.ts
  packages/nodes-base/nodes/Merge/v2/MergeV2.node.ts
  packages/nodes-base/nodes/Merge/v2/OptionsDescription.ts
Labels: node/improvement, n8n team

#3983 feat: [N8N-4365] Google Cloud Storage Node
  packages/nodes-base/credentials/GoogleCloudStorageOAuth2Api.credentials.ts
  packages/nodes-base/nodes/Google/CloudStorage/BucketDescription.ts
  packages/nodes-base/nodes/Google/CloudStorage/GoogleCloudStorage.node.json
  packages/nodes-base/nodes/Google/CloudStorage/GoogleCloudStorage.node.ts
  packages/nodes-base/nodes/Google/CloudStorage/ObjectDescription.ts
  packages/nodes-base/nodes/Google/CloudStorage/googleCloudStorage.svg
  packages/nodes-base/package.json
Labels: node/new, n8n team

#4090 fix(node): Google Cloud Storage linting rules
  packages/nodes-base/nodes/Google/CloudStorage/ObjectDescription.ts
Labels: n8n team, node/linting

#4000 feat(editor): Show input number for multi-input nodes
  packages/editor-ui/src/components/InputPanel.vue
Labels: ui, n8n team

#4081 feat(editor): Implement HTML sanitization for Notification and Message components
  packages/editor-ui/src/App.vue
  packages/editor-ui/src/components/PageAlert.vue
  packages/editor-ui/src/components/mixins/globalLinkActions.ts
  packages/editor-ui/src/components/mixins/pushConnection.ts
  packages/editor-ui/src/components/mixins/showMessage.ts
  packages/editor-ui/src/plugins/i18n/locales/en.json
  packages/editor-ui/src/utils.ts
  packages/editor-ui/src/views/NodeView.vue
Labels: core, ui, n8n team, tech debt

#3883 fix(cli,core): Address Dependabot warnings [N8N-4121]
  package-lock.json
  package.json
  packages/cli/package.json
  packages/core/package.json
Labels: core, n8n team

#4091 fix(core): update oauth endpoints to use instance base url
  packages/cli/src/Server.ts
Labels: core, n8n team

#4083 test(cli): WorkflowCredentials Test Suite
  packages/cli/test/unit/WorkflowCredentials.test.ts
Labels: core, n8n team

#4099 fix(cli): use absolute paths for loading custom nodes and credentials
  packages/cli/commands/import/credentials.ts
  packages/cli/commands/import/workflow.ts
  packages/cli/src/LoadNodesAndCredentials.ts
Labels: core, n8n team

#4070 Expand obfuscation to User Management credential sharing
  packages/editor-ui/src/components/CredentialCard.vue
  packages/editor-ui/src/components/CredentialEdit/CredentialConfig.vue
  packages/editor-ui/src/components/Node.vue
  packages/editor-ui/src/components/NodeTitle.vue
  packages/editor-ui/src/views/CredentialsView.vue
Labels: ui, n8n team, Project: User Management

#4095 fix(MongoDb Node): update mongo driver to 4.9.1 n8n-2622
  packages/nodes-base/nodes/MongoDb/GenericFunctions.ts
  packages/nodes-base/nodes/MongoDb/MongoDb.node.ts
  packages/nodes-base/nodes/MongoDb/MongoDbDescription.ts
  packages/nodes-base/nodes/MongoDb/mongoDb.types.ts
  packages/nodes-base/package.json
Labels: n8n team, node/issue

#3102 feat(Adalo Node): MVP Adalo node N8N-3263
  packages/nodes-base/credentials/AdaloApi.credentials.ts
  packages/nodes-base/nodes/Adalo/Adalo.node.json
  packages/nodes-base/nodes/Adalo/Adalo.node.ts
  packages/nodes-base/nodes/Adalo/CollectionDescription.ts
  packages/nodes-base/nodes/Adalo/adalo.svg
  packages/nodes-base/nodes/Adalo/types.d.ts
  packages/nodes-base/package.json
Labels: node/new, n8n team

#4101 ci: fail the build if `package-lock.json` is out of sync
  .github/workflows/ci-master.yml
  .github/workflows/ci-pull-requests.yml
  .github/workflows/test-workflows.yml
  package-lock.json
Labels: n8n team

#4089 fix(public-api): Fix error updating workflow with property not defined in the schema
  packages/cli/src/PublicApi/v1/handlers/workflows/spec/schemas/workflow.yml
  packages/cli/src/PublicApi/v1/handlers/workflows/workflows.handler.ts
Labels: core, n8n team

#4060 refactor(editor): N8N-4540 Main navigation layout rework
  packages/design-system/theme/src/reset.scss
  packages/editor-ui/public/n8n-logo-collapsed.svg
  packages/editor-ui/public/n8n-logo-expanded.svg
  packages/editor-ui/src/App.vue
  packages/editor-ui/src/components/MainHeader/MainHeader.vue
  packages/editor-ui/src/components/MainSidebar.vue
  packages/editor-ui/src/components/TemplateList.vue
  packages/editor-ui/src/components/mixins/mouseSelect.ts
  packages/editor-ui/src/modules/ui.ts
  packages/editor-ui/src/n8n-theme.scss
  packages/editor-ui/src/plugins/icons.ts
  packages/editor-ui/src/views/NodeView.vue
  packages/editor-ui/src/views/TemplatesCollectionView.vue
  packages/editor-ui/src/views/TemplatesSearchView.vue
  packages/editor-ui/src/views/TemplatesView.vue
  packages/editor-ui/src/views/TemplatesWorkflowView.vue
  packages/editor-ui/src/views/canvasHelpers.ts
Labels: ui, n8n team

#4103 feat(core, editor-ui): Introduce node deprecation
  packages/editor-ui/src/components/NodeCreator/NodeCreator.vue
  packages/editor-ui/src/constants.ts
  packages/nodes-base/nodes/Start/Start.node.ts
  packages/workflow/src/Interfaces.ts
Labels: node/improvement, core, ui, n8n team

#4075 refactor(design-system): merge n8n square button into n8n button
  packages/design-system/src/components/N8nButton/Button.stories.ts
  packages/design-system/src/components/N8nButton/Button.vue
  packages/design-system/src/components/N8nButton/__tests__/Button.spec.ts
  packages/design-system/src/components/N8nButton/__tests__/__snapshots__/Button.spec.ts.snap
  packages/design-system/src/components/N8nIconButton/IconButton.stories.ts
  packages/design-system/src/components/N8nIconButton/IconButton.vue
  packages/design-system/src/components/N8nSquareButton/SquareButton.stories.js
  packages/design-system/src/components/N8nSquareButton/SquareButton.vue
  packages/design-system/src/components/N8nSquareButton/index.ts
  packages/design-system/src/plugins/n8nComponents.ts
  packages/editor-ui/src/components/ValueSurvey.vue
Labels: ui, n8n team, tech debt

#4105 fix(cli): use a non-env config flag to detect of enterprise features are enabled
  packages/cli/config/schema.ts
  packages/cli/src/Server.ts
  packages/cli/src/credentials/helpers.ts
Labels: core, n8n team

#4093 refactor(telemetry): Add personalization survey event to PostHog
  packages/cli/src/InternalHooks.ts
Labels: core, n8n team

#4107 fix: AWS credential testing issue
  packages/nodes-base/credentials/Aws.credentials.ts
Labels: n8n team, Upcoming Release, node/issue

#4108 feat(ExecuteWorkflowTrigger node): Implement ExecuteWorkflowTrigger node
  packages/editor-ui/src/components/Node.vue
  packages/nodes-base/nodes/ExecuteWorkflowTrigger/ExecuteWorkflowTrigger.node.json
  packages/nodes-base/nodes/ExecuteWorkflowTrigger/ExecuteWorkflowTrigger.node.ts
  packages/nodes-base/package.json
Labels: node/new, ui, n8n team

#4008 fix(cli): Fix issue with n8n crashing when error in poll method
  packages/cli/src/ActiveWorkflowRunner.ts
  packages/cli/src/GenericHelpers.ts
  packages/core/src/ActiveWorkflows.ts
  packages/workflow/src/Interfaces.ts
Labels: core, n8n team

#3902 fix(HTTP Node): fix instance crashing when batching enabled
  packages/core/src/NodeExecuteFunctions.ts
  packages/nodes-base/nodes/HttpRequest/HttpRequest.node.ts
Labels: node/improvement, n8n team

#4118 refactor(telemetry): Obfuscate code and JSON editors
  packages/editor-ui/src/components/ParameterInput.vue
  packages/editor-ui/src/components/forms/CodeEditor.vue
Labels: ui, n8n team

#4116 feat(editor): improve design and functionality of coming soon features
  packages/editor-ui/src/Interface.ts
  packages/editor-ui/src/components/FeatureComingSoon.vue
  packages/editor-ui/src/modules/ui.ts
  packages/editor-ui/src/plugins/i18n/locales/en.json
  packages/editor-ui/src/views/SettingsFakeDoorView.vue
Labels: ui, n8n team

#4111 fix(public-api): Create correct OAuth2 credential schema
  packages/cli/src/PublicApi/types.d.ts
  packages/cli/src/PublicApi/v1/handlers/credentials/credentials.service.ts
Labels: core, n8n team

#4125 fix: fix telemetry for credential creates and updates
  packages/cli/src/InternalHooks.ts
  packages/cli/src/InternalHooksManager.ts
  packages/cli/src/credentials/credentials.controller.ts
  packages/editor-ui/src/components/CredentialEdit/CredentialEdit.vue
Labels: Project: User Management

#4124 feat: Display errors due to missing credentials in the correct node
  packages/cli/commands/worker.ts
  packages/cli/src/UserManagement/UserManagementHelper.ts
  packages/cli/src/WorkflowHelpers.ts
  packages/cli/src/WorkflowRunner.ts
  packages/cli/src/WorkflowRunnerProcess.ts
Labels: core, n8n team

#4110 feat(ManualTrigger node): Implement ManualTrigger node
  packages/editor-ui/src/components/NodeExecuteButton.vue
  packages/editor-ui/src/constants.ts
  packages/editor-ui/src/plugins/icons.ts
  packages/nodes-base/nodes/ManualTrigger/ManualTrigger.node.json
  packages/nodes-base/nodes/ManualTrigger/ManualTrigger.node.ts
  packages/nodes-base/package.json
Labels: node/new, ui, n8n team

#4135 fix: revert CI checks to ensure that the package-lock.json file is up to date
  .github/workflows/ci-master.yml
  .github/workflows/ci-pull-requests.yml
  .github/workflows/test-workflows.yml
  docker/images/n8n-custom/Dockerfile
  package-lock.json
Labels: n8n team

#4059 refactor(editor): Showing errors in input pane
  packages/editor-ui/src/components/NodeDetailsView.vue
  packages/editor-ui/src/components/RunData.vue
  packages/editor-ui/src/plugins/i18n/locales/en.json
Labels: ui, n8n team

#4134 docs(license): add common header to packages/cli/LICENSE.md (no-changelog)
  packages/cli/LICENSE.md
Labels: core, n8n team

#4136 test(cli): Remove console.log
  packages/cli/test/unit/Helpers.ts
Labels: core, community

#4123 refactor(telemetry): Fix metadata on personalization survey
  packages/cli/src/InternalHooks.ts
  packages/editor-ui/src/components/PersonalizationModal.vue
Labels: core, ui, n8n team

#3933 N8 n 4179 resource locator list mode
  package-lock.json
  packages/design-system/src/components/N8nButton/Button.vue
  packages/design-system/src/components/N8nInput/Input.vue
  packages/design-system/src/components/N8nLink/Link.vue
  packages/design-system/theme/src/input.scss
  packages/editor-ui/package.json
  packages/editor-ui/src/Interface.ts
  packages/editor-ui/src/api/nodeTypes.ts
  packages/editor-ui/src/components/BreakpointsObserver.vue
  packages/editor-ui/src/components/CredentialsList.vue
  packages/editor-ui/src/components/ExpressionEdit.vue
  packages/editor-ui/src/components/NodeCredentials.vue
  packages/editor-ui/src/components/ParameterInput.vue
  packages/editor-ui/src/components/ParameterInputFull.vue
  packages/editor-ui/src/components/ParameterOptions.vue
  packages/editor-ui/src/components/ResourceLocator/ResourceLocator.vue
  packages/editor-ui/src/components/ResourceLocator/ResourceLocatorDropdown.vue
  packages/editor-ui/src/components/ResourceLocator/helpers.ts
  packages/editor-ui/src/components/helpers.ts
  packages/editor-ui/src/components/mixins/debounce.ts
  packages/editor-ui/src/components/mixins/genericHelpers.ts
  packages/editor-ui/src/modules/nodeTypes.ts
  packages/editor-ui/src/modules/ui.ts
  packages/editor-ui/src/plugins/i18n/locales/en.json
  packages/editor-ui/src/typeGuards.ts
  packages/editor-ui/src/views/NodeView.vue
  packages/editor-ui/src/views/TemplatesSearchView.vue
  packages/nodes-base/nodes/Airtable/Airtable.node.ts
  packages/nodes-base/nodes/Google/Drive/v3/VersionDescription.ts
  packages/nodes-base/nodes/Trello/AttachmentDescription.ts
  packages/nodes-base/nodes/Trello/BoardDescription.ts
  packages/nodes-base/nodes/Trello/CardCommentDescription.ts
  packages/nodes-base/nodes/Trello/CardDescription.ts
  packages/nodes-base/nodes/Trello/ChecklistDescription.ts
  packages/nodes-base/nodes/Trello/LabelDescription.ts
  packages/workflow/src/Interfaces.ts
  packages/workflow/src/NodeHelpers.ts
  packages/workflow/src/RoutingNode.ts
Labels: ui, n8n team

#4139 fix(expression): prevent calls to constructor to forbid arbitrary code execution
  packages/workflow/src/Expression.ts
Labels: core, n8n team

#4146 fix(xero Node): fix line amount types being ignored when creating new invoices
  packages/nodes-base/nodes/Xero/InvoiceInterface.ts
  packages/nodes-base/nodes/Xero/Xero.node.ts
Labels: n8n team, node/issue

#4147 fix(box Node): fix issue with response data not being returned
  packages/nodes-base/nodes/Box/Box.node.ts
Labels: node/improvement, n8n team

#4138 perf(ci): Cache npm dependencies
  .github/workflows/ci-pull-requests.yml
Labels: n8n team

#4102 refactor(nodes-base): Fix typo in ReleaseDescription.ts
  packages/nodes-base/nodes/SentryIo/ReleaseDescription.ts
Labels: node/improvement, community

#4148 fix(node-dev): fix the custom node build command
  package-lock.json
  packages/node-dev/commands/build.ts
  packages/node-dev/package.json
  packages/node-dev/src/Build.ts
  packages/node-dev/src/tsconfig-build.json
Labels: core, n8n team

#4137 refactor(ci): Lint PR diffs only
  .github/workflows/ci-pull-requests.yml
  package-lock.json
  packages/@n8n_io/eslint-config/base.js
  packages/@n8n_io/eslint-config/package.json
Labels: n8n team

#4154 feat(personalization): update personalizaton survey
  packages/editor-ui/src/components/PersonalizationModal.vue
  packages/editor-ui/src/constants.ts
  packages/editor-ui/src/plugins/i18n/locales/en.json
Labels: ui, n8n team

#4156 fix(editor): fix broken output panel for wait node executions
  packages/editor-ui/src/Interface.ts
  packages/editor-ui/src/components/CodeEdit.vue
  packages/editor-ui/src/components/NodeDetailsView.vue
  packages/editor-ui/src/components/OutputPanel.vue
  packages/editor-ui/src/components/RunData.vue
  packages/editor-ui/src/components/VariableSelector.vue
  packages/editor-ui/src/components/mixins/workflowHelpers.ts
  packages/editor-ui/src/store.ts
Labels: ui, n8n team

#4157 fix(editor): fix pin data button active state
  packages/editor-ui/src/components/RunData.vue
  packages/editor-ui/src/components/mixins/pinData.ts
Labels: ui, n8n team

#4152 refactor(editor-ui): update 'vue-json-pretty' and adjust component to preserve same behaviour
  package-lock.json
  packages/editor-ui/package.json
  packages/editor-ui/src/components/RunData.vue
  packages/editor-ui/src/components/mixins/pinData.ts
Labels: ui, n8n team

#4109 refactor: Resource locator review changes
  package-lock.json
  packages/core/src/ExtractValue.ts
  packages/core/src/NodeExecuteFunctions.ts
  packages/editor-ui/src/Interface.ts
  packages/nodes-base/nodes/Airtable/Airtable.node.ts
  packages/nodes-base/nodes/Google/Drive/GoogleDrive.node.ts
  packages/nodes-base/nodes/Google/Drive/v1/GoogleDriveV1.node.ts
  packages/nodes-base/nodes/Google/Drive/v1/VersionDescription.ts
  packages/nodes-base/nodes/Google/Drive/v3/GoogleDriveV3.node.ts
  packages/nodes-base/nodes/Google/Drive/v3/VersionDescription.ts
  packages/nodes-base/nodes/Trello/AttachmentDescription.ts
  packages/nodes-base/nodes/Trello/BoardDescription.ts
  packages/nodes-base/nodes/Trello/CardCommentDescription.ts
  packages/nodes-base/nodes/Trello/CardDescription.ts
  packages/nodes-base/nodes/Trello/ChecklistDescription.ts
  packages/nodes-base/nodes/Trello/GenericFunctions.ts
  packages/nodes-base/nodes/Trello/LabelDescription.ts
  packages/nodes-base/nodes/Trello/Trello.node.ts
  packages/nodes-base/package.json
  packages/workflow/src/Expression.ts
  packages/workflow/src/Interfaces.ts
Labels: core, n8n team

#3932 feat: add resource locator parameter
  package-lock.json
  packages/cli/src/Server.ts
  packages/cli/src/requests.d.ts
  packages/core/src/ExtractValue.ts
  packages/core/src/LoadNodeListSearch.ts
  packages/core/src/NodeExecuteFunctions.ts
  packages/core/src/index.ts
  packages/design-system/src/components/N8nButton/Button.vue
  packages/design-system/src/components/N8nButton/__tests__/__snapshots__/Button.spec.ts.snap
  packages/design-system/src/components/N8nInput/Input.vue
  packages/design-system/src/components/N8nLink/Link.vue
  packages/design-system/theme/src/input.scss
  packages/editor-ui/package.json
  packages/editor-ui/src/Interface.ts
  packages/editor-ui/src/api/nodeTypes.ts
  packages/editor-ui/src/components/BreakpointsObserver.vue
  packages/editor-ui/src/components/CredentialCard.vue
  packages/editor-ui/src/components/CredentialsList.vue
  packages/editor-ui/src/components/DraggableTarget.vue
  packages/editor-ui/src/components/ExpressionEdit.vue
  packages/editor-ui/src/components/MainSidebar.vue
  packages/editor-ui/src/components/NodeCredentials.vue
  packages/editor-ui/src/components/ParameterInput.vue
  packages/editor-ui/src/components/ParameterInputExpanded.vue
  packages/editor-ui/src/components/ParameterInputFull.vue
  packages/editor-ui/src/components/ParameterOptions.vue
  packages/editor-ui/src/components/ResourceLocator/ResourceLocator.vue
  packages/editor-ui/src/components/ResourceLocator/ResourceLocatorDropdown.vue
  packages/editor-ui/src/components/ResourceLocator/helpers.ts
  packages/editor-ui/src/components/helpers.ts
  packages/editor-ui/src/components/mixins/debounce.ts
  packages/editor-ui/src/components/mixins/genericHelpers.ts
  packages/editor-ui/src/modules/nodeTypes.ts
  packages/editor-ui/src/modules/ui.ts
  packages/editor-ui/src/plugins/i18n/locales/en.json
  packages/editor-ui/src/plugins/icons.ts
  packages/editor-ui/src/typeGuards.ts
  packages/editor-ui/src/views/CredentialsView.vue
  packages/editor-ui/src/views/NodeView.vue
  packages/editor-ui/src/views/TemplatesSearchView.vue
  packages/nodes-base/nodes/Airtable/Airtable.node.ts
  packages/nodes-base/nodes/Google/Drive/GoogleDrive.node.ts
  packages/nodes-base/nodes/Trello/AttachmentDescription.ts
  packages/nodes-base/nodes/Trello/BoardDescription.ts
  packages/nodes-base/nodes/Trello/CardCommentDescription.ts
  packages/nodes-base/nodes/Trello/CardDescription.ts
  packages/nodes-base/nodes/Trello/ChecklistDescription.ts
  packages/nodes-base/nodes/Trello/GenericFunctions.ts
  packages/nodes-base/nodes/Trello/LabelDescription.ts
  packages/nodes-base/nodes/Trello/Trello.node.ts
  packages/nodes-base/package.json
  packages/workflow/src/Expression.ts
  packages/workflow/src/Interfaces.ts
  packages/workflow/src/NodeHelpers.ts
  packages/workflow/src/RoutingNode.ts
  packages/workflow/src/Workflow.ts
  packages/workflow/src/WorkflowDataProxy.ts
  packages/workflow/test/RoutingNode.test.ts
Labels: node/improvement, core, ui, n8n team

#4164 fix: postgres migration missing schema name
  packages/cli/src/databases/migrations/postgresdb/1660062385367-CreateCredentialsUserRole.ts
Labels: core, n8n team

#4166 fix: mysql migration using incorrect syntax on insert
  packages/cli/src/databases/migrations/mysqldb/1660062385367-CreateCredentialsUserRole.ts
Labels: core, n8n team

#3994 MSSQL node support tdsVersion option
  packages/nodes-base/credentials/MicrosoftSql.credentials.ts
  packages/nodes-base/nodes/Microsoft/Sql/MicrosoftSql.node.ts
Labels: node/improvement, community

#4169 fix: fix expressions bug with numbers and booleans
  packages/editor-ui/src/components/ParameterInput.vue
Labels: ui, n8n team

#3980 feat(editor-ui): Resizable main panel
  package-lock.json
  packages/design-system/src/components/N8nResizeWrapper/ResizeWrapper.stories.js
  packages/design-system/src/components/N8nResizeWrapper/ResizeWrapper.vue
  packages/design-system/src/components/N8nResizeWrapper/index.js
  packages/design-system/src/components/N8nSticky/Sticky.vue
  packages/design-system/src/plugins/n8nComponents.ts
  packages/editor-ui/src/Interface.ts
  packages/editor-ui/src/components/NDVDraggablePanels.vue
  packages/editor-ui/src/components/NodeDetailsView.vue
  packages/editor-ui/src/components/NodeSettings.vue
  packages/editor-ui/src/components/PanelDragButton.vue
  packages/editor-ui/src/components/ResourceLocator/ResourceLocator.vue
  packages/editor-ui/src/components/ResourceLocator/ResourceLocatorDropdown.vue
  packages/editor-ui/src/components/helpers.ts
  packages/editor-ui/src/constants.ts
  packages/editor-ui/src/modules/ui.ts
Labels: ui, n8n team

#4173 fix: resolve RL values in expressions
  packages/core/src/ExtractValue.ts
  packages/core/src/NodeExecuteFunctions.ts
  packages/editor-ui/src/components/ParameterInput.vue
  packages/editor-ui/src/components/ParameterInputFull.vue
  packages/editor-ui/src/components/ResourceLocator/ResourceLocator.vue
  packages/editor-ui/src/typeGuards.ts
  packages/nodes-base/nodes/Airtable/Airtable.node.ts
  packages/nodes-base/nodes/Google/Drive/GoogleDrive.node.ts
  packages/nodes-base/nodes/Trello/Trello.node.ts
  packages/workflow/src/Interfaces.ts
  packages/workflow/src/RoutingNode.ts
  packages/workflow/src/WorkflowDataProxy.ts
Labels: node/improvement, core, ui, n8n team

#4179 fix(design-system): add missing event handler to accordion component
  packages/design-system/src/components/N8nInfoAccordion/InfoAccordion.stories.ts
Labels: ui, n8n team

#4180 refactor: migrate away from querystring n8n-4659
  packages/cli/src/credentials/oauth2Credential.api.ts
  packages/nodes-base/nodes/Jira/JiraTrigger.node.ts
  packages/nodes-base/nodes/TravisCi/GenericFunctions.ts
Labels: n8n team, tech debt

#4087 feat(eslint-config): add custom eslint rule 'no-uncaught-json-parse'
  package-lock.json
  packages/@n8n_io/eslint-config/base.js
  packages/@n8n_io/eslint-config/local-rules.js
  packages/@n8n_io/eslint-config/local-rules.test.js
  packages/@n8n_io/eslint-config/package.json
Labels: n8n team

#4186 fix: cardId property not showing up for completed checklist in Trello
  packages/nodes-base/nodes/Trello/ChecklistDescription.ts
Labels: node/improvement, n8n team

#4187 fix(editor): fix run data pagination selector not showing
  packages/editor-ui/src/components/RunData.vue
Labels: ui, n8n team

#4175 fix(editor): fix run data footer overflow
  packages/editor-ui/src/components/RunData.vue
Labels: ui, n8n team

#4193 fix(editor): fix copy pasting workflow into pin data code editor
  packages/editor-ui/src/components/RunData.vue
Labels: ui, n8n team

#4194 ci: Use `eslint-plugin-diff` only on the CI
  packages/@n8n_io/eslint-config/base.js
Labels: n8n team

#4190 fix(cli): Disable CORS on SSE connections in production
  packages/cli/src/Push.ts
Labels: core, n8n team

#4144 feat(editor): Main navigation redesign
  packages/design-system/src/components/N8nActionDropdown/ActionDropdown.stories.ts
  packages/design-system/src/components/N8nActionDropdown/ActionDropdown.vue
  packages/design-system/src/components/N8nActionDropdown/__tests__/ActionDropdown.spec.ts
  packages/design-system/src/components/N8nActionDropdown/__tests__/__snapshots__/ActionDropdown.spec.ts.snap
  packages/design-system/src/components/N8nActionDropdown/index.ts
  packages/design-system/src/css/reset.scss
  packages/design-system/src/plugins/n8nComponents.ts
  packages/editor-ui/public/favicon.ico
  packages/editor-ui/public/n8n-logo-collapsed.svg
  packages/editor-ui/public/n8n-logo-expanded.svg
  packages/editor-ui/src/App.vue
  packages/editor-ui/src/components/CredentialsList.vue
  packages/editor-ui/src/components/GiftNotificationIcon.vue
  packages/editor-ui/src/components/Logo.vue
  packages/editor-ui/src/components/MainHeader/MainHeader.vue
  packages/editor-ui/src/components/MainHeader/WorkflowDetails.vue
  packages/editor-ui/src/components/MainSidebar.vue
  packages/editor-ui/src/components/Modals.vue
  packages/editor-ui/src/components/NodeCreator/SearchBar.vue
  packages/editor-ui/src/components/SettingsSidebar.vue
  packages/editor-ui/src/components/TagsDropdown.vue
  packages/editor-ui/src/components/TemplateList.vue
  packages/editor-ui/src/components/WorkflowOpen.vue
  packages/editor-ui/src/components/layouts/PageViewLayout.vue
  packages/editor-ui/src/components/mixins/mouseSelect.ts
  packages/editor-ui/src/constants.ts
  packages/editor-ui/src/modules/ui.ts
  packages/editor-ui/src/n8n-theme.scss
  packages/editor-ui/src/plugins/i18n/locales/en.json
  packages/editor-ui/src/plugins/icons.ts
  packages/editor-ui/src/router.ts
  packages/editor-ui/src/views/NodeView.vue
  packages/editor-ui/src/views/TemplatesCollectionView.vue
  packages/editor-ui/src/views/TemplatesSearchView.vue
  packages/editor-ui/src/views/TemplatesView.vue
  packages/editor-ui/src/views/TemplatesWorkflowView.vue
  packages/editor-ui/src/views/canvasHelpers.ts
Labels: ui, n8n team

#4196 fix(build): Add typing for SSE channel
  packages/cli/src/Push.ts
Labels: core, n8n team

#4202 fix(editor-ui): fix `BASE_URL` replacement on windows
  packages/cli/src/Server.ts
  packages/editor-ui/index.html
  packages/editor-ui/package.json
  packages/editor-ui/src/router.ts
  packages/editor-ui/src/store.ts
  packages/editor-ui/vue.config.js
Labels: core, ui, n8n team

#4199 fix(editor): fix run selector not opening
  packages/editor-ui/src/components/RunData.vue
Labels: ui, n8n team

#4076 feat(n8nApi node): add core node for consuming the n8n API
  packages/nodes-base/credentials/N8nApi.credentials.ts
  packages/nodes-base/nodes/N8n/CredentialDescription.ts
  packages/nodes-base/nodes/N8n/ExecutionDescription.ts
  packages/nodes-base/nodes/N8n/GenericFunctions.ts
  packages/nodes-base/nodes/N8n/N8n.node.json
  packages/nodes-base/nodes/N8n/N8n.node.ts
  packages/nodes-base/nodes/N8n/WorkflowDescription.ts
  packages/nodes-base/nodes/N8n/WorkflowLocator.ts
  packages/nodes-base/nodes/N8n/n8n.svg
  packages/nodes-base/package.json
Labels: node/new, n8n team

#4209 fix(editor): Updating wrong i18n string reference
  packages/editor-ui/src/components/WorkflowOpen.vue
Labels: ui

#4208 fix: wrap external hooks calls in a try catch
  packages/cli/src/ExternalHooks.ts
Labels: core, n8n team

#4211 fix: remove --forceExit flag from cli tests
  packages/cli/package.json
Labels: core, n8n team

#4150 feat(editor-ui): Trigger tab redesign
  packages/editor-ui/public/static/webhook-icon.svg
  packages/editor-ui/src/Interface.ts
  packages/editor-ui/src/components/MainHeader/MainHeader.vue
  packages/editor-ui/src/components/NodeCreator/CategorizedItems.vue
  packages/editor-ui/src/components/NodeCreator/CategoryItem.vue
  packages/editor-ui/src/components/NodeCreator/CreatorItem.vue
  packages/editor-ui/src/components/NodeCreator/ItemIterator.vue
  packages/editor-ui/src/components/NodeCreator/MainPanel.vue
  packages/editor-ui/src/components/NodeCreator/NoResults.vue
  packages/editor-ui/src/components/NodeCreator/NodeCreator.vue
  packages/editor-ui/src/components/NodeCreator/NodeItem.vue
  packages/editor-ui/src/components/NodeCreator/SubcategoryItem.vue
  packages/editor-ui/src/components/NodeCreator/SubcategoryPanel.vue
  packages/editor-ui/src/components/NodeCreator/TriggerHelperPanel.vue
  packages/editor-ui/src/components/NodeCreator/helpers.ts
  packages/editor-ui/src/components/transitions/SlideTransition.vue
  packages/editor-ui/src/constants.ts
  packages/editor-ui/src/modules/nodeTypes.ts
  packages/editor-ui/src/modules/nodeTypesHelpers.ts
  packages/editor-ui/src/modules/ui.ts
  packages/editor-ui/src/plugins/i18n/locales/en.json
  packages/editor-ui/src/plugins/icons.ts
  packages/nodes-base/nodes/EmailReadImap/EmailReadImap.node.json
  packages/nodes-base/nodes/ErrorTrigger/ErrorTrigger.node.json
  packages/nodes-base/nodes/Interval/Interval.node.json
  packages/nodes-base/nodes/LocalFileTrigger/LocalFileTrigger.node.json
  packages/nodes-base/nodes/N8nTrigger/N8nTrigger.node.json
  packages/nodes-base/nodes/SseTrigger/SseTrigger.node.json
  packages/nodes-base/nodes/WorkflowTrigger/WorkflowTrigger.node.json
Labels: node/improvement, ui, n8n team

#4212 fix(Merge Node): update description in merge node n8n-4704
  packages/nodes-base/nodes/Merge/v2/MergeV2.node.ts
Labels: n8n team, node/issue

#4214 fix(core): remove commented out lines n8n-4659
  packages/cli/src/credentials/oauth2Credential.api.ts
Labels: n8n team, tech debt

#4215 fix(editor-ui): Fix ParameterInput inputField ref focus
  packages/editor-ui/src/components/CredentialsSelect.vue
Labels: ui, n8n team

#4184 feat: add support for unit testing using vitest in editor-ui
  package-lock.json
  packages/design-system/jest.config.js
  packages/design-system/package.json
  packages/design-system/tsconfig.json
  packages/editor-ui/package.json
  packages/editor-ui/src/__tests__/permissions.spec.ts
  packages/editor-ui/src/__tests__/setup.ts
  packages/editor-ui/src/permissions.ts
  packages/editor-ui/tsconfig.json
Labels: ui, n8n team

#4204 feat(editor-ui): Redesign search input inside node creator panel
  packages/editor-ui/src/components/NodeCreator/CategorizedItems.vue
  packages/editor-ui/src/components/NodeCreator/CreatorItem.vue
  packages/editor-ui/src/components/NodeCreator/ItemIterator.vue
  packages/editor-ui/src/components/NodeCreator/MainPanel.vue
  packages/editor-ui/src/components/NodeCreator/NoResults.vue
  packages/editor-ui/src/components/NodeCreator/NodeCreator.vue
  packages/editor-ui/src/components/NodeCreator/NodeItem.vue
  packages/editor-ui/src/components/NodeCreator/SearchBar.vue
  packages/editor-ui/src/components/NodeCreator/TriggerHelperPanel.vue
  packages/editor-ui/src/modules/ui.ts
  packages/editor-ui/src/n8n-theme-variables.scss
  packages/editor-ui/src/plugins/i18n/locales/en.json
Labels: ui, n8n team

#4224 fix(cli): Disable `X-Powered-By: Express` Header
  packages/cli/commands/worker.ts
  packages/cli/src/Server.ts
  packages/cli/src/WebhookServer.ts
Labels: core, n8n team

#4158 refactor(editor-ui): move json data view into its own component
  package-lock.json
  packages/editor-ui/package.json
  packages/editor-ui/src/components/Draggable.vue
  packages/editor-ui/src/components/PanelDragButton.vue
  packages/editor-ui/src/components/RunData.vue
  packages/editor-ui/src/components/RunDataJson.vue
  packages/editor-ui/src/components/RunDataJsonActions.vue
  packages/editor-ui/src/components/RunDataTable.vue
  packages/editor-ui/src/components/helpers.ts
  packages/editor-ui/src/declarations/vue-json-pretty.d.ts
  packages/editor-ui/src/plugins/i18n/locales/en.json
Labels: ui, n8n team

#3150 feat(Slack Node): operation get many for user resource n8n-3361
  packages/nodes-base/credentials/SlackOAuth2Api.credentials.ts
  packages/nodes-base/nodes/Slack/Slack.node.ts
  packages/nodes-base/nodes/Slack/UserDescription.ts
  packages/nodes-base/nodes/Slack/UserProfileDescription.ts
Labels: node/improvement, n8n team

#4182 feat(cli): Optimise serving static assets
  package-lock.json
  packages/cli/package.json
  packages/cli/src/Server.ts
Labels: core, n8n team

#4225 refactor: revert: "fix: wrap external hooks calls in a try catch"
  packages/cli/src/ExternalHooks.ts
Labels: core, n8n team

#4216 feat: share unshared credentials with owner on reset
  packages/cli/commands/user-management/reset.ts
Labels: core, n8n team

#4230 fix: fix slow loading times for nodeTypes, node creator vuex reference, and pushConnection in settings views
  packages/editor-ui/src/components/NodeCreator/NodeCreator.vue
  packages/editor-ui/src/components/SettingsSidebar.vue
  packages/editor-ui/src/components/mixins/pushConnection.ts
  packages/editor-ui/src/modules/nodeTypes.ts
  packages/editor-ui/src/views/CredentialsView.vue
  packages/editor-ui/src/views/NodeView.vue
Labels: ui, n8n team, tech debt

#4232 fix(build): Fix lint issue to fix build
  packages/nodes-base/nodes/NocoDB/OperationDescription.ts
Labels: node/improvement, n8n team

#3765 feat(core): Improve paired item and add additional variables
  packages/cli/src/InternalHooks.ts
  packages/core/src/NodeExecuteFunctions.ts
  packages/editor-ui/src/components/CodeEdit.vue
  packages/editor-ui/src/components/Error/NodeErrorView.vue
  packages/editor-ui/src/components/VariableSelector.vue
  packages/editor-ui/src/components/mixins/pushConnection.ts
  packages/editor-ui/src/components/mixins/showMessage.ts
  packages/editor-ui/src/components/mixins/workflowHelpers.ts
  packages/editor-ui/src/constants.ts
  packages/editor-ui/src/views/NodeView.vue
  packages/nodes-base/nodes/Wait/Wait.node.ts
  packages/workflow/src/ExpressionError.ts
  packages/workflow/src/Interfaces.ts
  packages/workflow/src/WorkflowDataProxy.ts
  packages/workflow/test/WorkflowDataProxy.test.ts
Labels: core, ui, n8n team

#3860 feat(HTTP Request Node): Redesign and add the ability to import cURL commands
  package-lock.json
  packages/cli/package.json
  packages/cli/src/CurlConverter.d.ts
  packages/cli/src/CurlConverterHelper.ts
  packages/cli/src/ResponseHelper.ts
  packages/cli/src/Server.ts
  packages/cli/src/requests.d.ts
  packages/cli/test/unit/CurlConverterHelper.test.ts
  packages/editor-ui/src/Interface.ts
  packages/editor-ui/src/api/curlHelper.ts
  packages/editor-ui/src/components/ImportCurlModal.vue
  packages/editor-ui/src/components/ImportParameter.vue
  packages/editor-ui/src/components/Modals.vue
  packages/editor-ui/src/components/NodeSettings.vue
  packages/editor-ui/src/components/ParameterInput.vue
  packages/editor-ui/src/components/ParameterInputList.vue
  packages/editor-ui/src/constants.ts
  packages/editor-ui/src/modules/settings.ts
  packages/editor-ui/src/modules/ui.ts
  packages/editor-ui/src/plugins/i18n/locales/en.json
  packages/nodes-base/nodes/HttpRequest/HttpRequest.node.ts
  packages/nodes-base/nodes/HttpRequest/V1/HttpRequestV1.node.ts
  packages/nodes-base/nodes/HttpRequest/V2/HttpRequestV2.node.ts
  packages/nodes-base/nodes/HttpRequest/V3/HttpRequestV3.node.ts
  packages/workflow/src/Interfaces.ts
Labels: node/new, core, ui, n8n team

#3659 feat(WhatsApp Business node): WhatsApp node
  packages/core/src/NodeExecuteFunctions.ts
  packages/nodes-base/credentials/WhatsAppApi.credentials.ts
  packages/nodes-base/nodes/WhatsApp/MediaDescription.ts
  packages/nodes-base/nodes/WhatsApp/MediaFunctions.ts
  packages/nodes-base/nodes/WhatsApp/MessageFunctions.ts
  packages/nodes-base/nodes/WhatsApp/MessagesDescription.ts
  packages/nodes-base/nodes/WhatsApp/WhatsApp.node.ts
  packages/nodes-base/nodes/WhatsApp/whatsapp.svg
  packages/nodes-base/package.json
  packages/workflow/src/RoutingNode.ts
Labels: node/new, core, n8n team

#4236 fix(editor): Updating leftover i18n references in NodeView
  packages/editor-ui/src/views/NodeView.vue
Labels: ui, n8n team
