Repository n8n-io/n8n, pull requests merged in 2022-06, with the labels that each got.

#3412 fix delete button hover spacing
  packages/editor-ui/src/components/ParameterInputList.vue
Labels: ui, n8n team

#3397 Add catch block to avoid crashes when running in queue mode
  packages/cli/commands/worker.ts
  packages/cli/src/WorkflowRunner.ts
Labels: n8n team

#3130 import/export tags
  packages/cli/commands/export/workflow.ts
  packages/cli/commands/import/workflow.ts
  packages/cli/src/Interfaces.ts
  packages/cli/src/Server.ts
  packages/cli/src/TagHelpers.ts
  packages/editor-ui/src/Interface.ts
  packages/editor-ui/src/components/MainSidebar.vue
  packages/editor-ui/src/modules/tags.ts
  packages/editor-ui/src/store.ts
  packages/editor-ui/src/views/NodeView.vue
Labels: core, ui, n8n team

#3428 fix stuck loading states
  packages/editor-ui/src/components/InputPanel.vue
  packages/editor-ui/src/components/NodeExecuteButton.vue
Labels: ui, n8n team

#3382 N8N-3654 Community nodes settings view
  packages/cli/src/Interfaces.ts
  packages/cli/src/Server.ts
  packages/design-system/src/components/N8nActionBox/ActionBox.stories.js
  packages/design-system/src/components/N8nActionBox/ActionBox.vue
  packages/design-system/src/components/N8nActionToggle/ActionToggle.vue
  packages/design-system/src/components/N8nCallout/Callout.stories.ts
  packages/design-system/src/components/N8nCallout/Callout.vue
  packages/design-system/src/components/N8nCallout/__tests__/Callout.spec.ts
  packages/design-system/src/components/N8nCallout/__tests__/__snapshots__/Callout.spec.ts.snap
  packages/design-system/src/components/N8nCallout/index.ts
  packages/design-system/src/components/index.ts
  packages/design-system/theme/src/_tokens.scss
  packages/editor-ui/src/Interface.ts
  packages/editor-ui/src/api/communityNodes.ts
  packages/editor-ui/src/api/settings.ts
  packages/editor-ui/src/components/CommunityPackageCard.vue
  packages/editor-ui/src/components/MainSidebar.vue
  packages/editor-ui/src/components/SettingsSidebar.vue
  packages/editor-ui/src/components/mixins/userHelpers.ts
  packages/editor-ui/src/constants.ts
  packages/editor-ui/src/modules/communityNodes.ts
  packages/editor-ui/src/modules/settings.ts
  packages/editor-ui/src/modules/userHelpers.ts
  packages/editor-ui/src/modules/users.ts
  packages/editor-ui/src/plugins/i18n/locales/en.json
  packages/editor-ui/src/plugins/icons.ts
  packages/editor-ui/src/router.ts
  packages/editor-ui/src/store.ts
  packages/editor-ui/src/views/SettingsCommunityNodesView.vue
Labels: core, ui, n8n team

#3441 Apply `node-param-description-miscased-url`
  .eslintrc.js
  packages/nodes-base/nodes/Bannerbear/ImageDescription.ts
  packages/nodes-base/nodes/Ghost/PostDescription.ts
  packages/nodes-base/nodes/HelpScout/CustomerDescription.ts
  packages/nodes-base/nodes/Intercom/LeadDescription.ts
  packages/nodes-base/nodes/Intercom/UserDescription.ts
  packages/nodes-base/nodes/Lemlist/descriptions/LeadDescription.ts
  packages/nodes-base/nodes/Markdown/Markdown.node.ts
  packages/nodes-base/nodes/Nasa/Nasa.node.ts
  packages/nodes-base/nodes/OneSimpleApi/OneSimpleApi.node.ts
  packages/nodes-base/nodes/Rocketchat/Rocketchat.node.ts
  packages/nodes-base/nodes/Segment/GroupDescription.ts
  packages/nodes-base/nodes/Segment/IdentifyDescription.ts
  packages/nodes-base/nodes/Segment/TrackDescription.ts
  packages/nodes-base/nodes/Slack/MessageDescription.ts
  packages/nodes-base/nodes/Telegram/Telegram.node.ts
  packages/nodes-base/nodes/Trello/BoardDescription.ts
  packages/nodes-base/nodes/Trello/CardDescription.ts
  packages/nodes-base/nodes/UptimeRobot/MonitorDescription.ts
Labels: node/improvement, n8n team

#3443 Activate rule node-param-placeholder-miscased-id
  .eslintrc.js
  packages/nodes-base/nodes/Aws/DynamoDB/ItemDescription.ts
  packages/nodes-base/nodes/CrateDb/CrateDb.node.ts
  packages/nodes-base/nodes/Google/BigQuery/RecordDescription.ts
  packages/nodes-base/nodes/Microsoft/GraphSecurity/descriptions/SecureScoreControlProfileDescription.ts
  packages/nodes-base/nodes/Microsoft/Sql/MicrosoftSql.node.ts
  packages/nodes-base/nodes/MySql/MySql.node.ts
  packages/nodes-base/nodes/Postgres/Postgres.node.ts
  packages/nodes-base/nodes/QuestDb/QuestDb.node.ts
  packages/nodes-base/nodes/QuickBase/RecordDescription.ts
  packages/nodes-base/nodes/Rundeck/Rundeck.node.ts
  packages/nodes-base/nodes/Snowflake/Snowflake.node.ts
  packages/nodes-base/nodes/Stackby/Stackby.node.ts
  packages/nodes-base/nodes/Strapi/EntryDescription.ts
  packages/nodes-base/nodes/TimescaleDb/TimescaleDb.node.ts
Labels: node/improvement, n8n team

#3446 n8n-3601-review-node-param-option-name-wrong-for-upsert
  .eslintrc.js
  packages/nodes-base/nodes/Autopilot/ContactDescription.ts
  packages/nodes-base/nodes/CustomerIo/CustomerDescription.ts
  packages/nodes-base/nodes/Google/Firebase/CloudFirestore/DocumentDescription.ts
  packages/nodes-base/nodes/HomeAssistant/StateDescription.ts
  packages/nodes-base/nodes/Hubspot/ContactDescription.ts
  packages/nodes-base/nodes/Iterable/UserDescription.ts
  packages/nodes-base/nodes/Keap/ContactDescription.ts
  packages/nodes-base/nodes/Orbit/MemberDescription.ts
  packages/nodes-base/nodes/QuickBase/RecordDescription.ts
  packages/nodes-base/nodes/SendGrid/ContactDescription.ts
Labels: n8n team, node/linting

#3442 Rule working for values of 0
  .eslintrc.js
Labels: n8n team

#3452 n8n-3439-review-node-param-default-wrong-for-string
  .eslintrc.js
Labels: n8n team, node/linting

#3451 n8n-3446-node-param-description-lowercase-first-char
  .eslintrc.js
  packages/nodes-base/nodes/AcuityScheduling/AcuitySchedulingTrigger.node.ts
  packages/nodes-base/nodes/Amqp/Amqp.node.ts
  packages/nodes-base/nodes/Amqp/AmqpTrigger.node.ts
  packages/nodes-base/nodes/Box/FileDescription.ts
  packages/nodes-base/nodes/Box/FolderDescription.ts
  packages/nodes-base/nodes/ClickUp/TaskDescription.ts
  packages/nodes-base/nodes/Freshdesk/Freshdesk.node.ts
  packages/nodes-base/nodes/HelpScout/CustomerDescription.ts
  packages/nodes-base/nodes/HomeAssistant/TemplateDescription.ts
  packages/nodes-base/nodes/Hubspot/TicketDescription.ts
  packages/nodes-base/nodes/Hunter/Hunter.node.ts
  packages/nodes-base/nodes/Iterable/EventDescription.ts
  packages/nodes-base/nodes/Jira/IssueCommentDescription.ts
  packages/nodes-base/nodes/Microsoft/Teams/ChannelDescription.ts
  packages/nodes-base/nodes/Notion/DatabaseDescription.ts
  packages/nodes-base/nodes/Paddle/PaymentDescription.ts
  packages/nodes-base/nodes/PagerDuty/IncidentDescription.ts
  packages/nodes-base/nodes/QuickBase/RecordDescription.ts
  packages/nodes-base/nodes/RenameKeys/RenameKeys.node.ts
  packages/nodes-base/nodes/Salesforce/ContactDescription.ts
  packages/nodes-base/nodes/SentryIo/ReleaseDescription.ts
  packages/nodes-base/nodes/Signl4/Signl4.node.ts
  packages/nodes-base/nodes/Slack/UserProfileDescription.ts
  packages/nodes-base/nodes/Splunk/descriptions/SearchResultDescription.ts
  packages/nodes-base/nodes/Supabase/GenericFunctions.ts
  packages/nodes-base/nodes/SyncroMSP/v1/actions/customer/getAll/description.ts
  packages/nodes-base/nodes/TheHive/descriptions/AlertDescription.ts
  packages/nodes-base/nodes/TheHive/descriptions/ObservableDescription.ts
  packages/nodes-base/nodes/Uplead/CompanyDesciption.ts
  packages/nodes-base/nodes/Vero/EventDescripion.ts
  packages/nodes-base/nodes/Vero/UserDescription.ts
  packages/nodes-base/nodes/WooCommerce/ProductDescription.ts
  packages/nodes-base/nodes/Xero/ContactDescription.ts
  packages/nodes-base/nodes/Xml/Xml.node.ts
  packages/nodes-base/nodes/Zendesk/TicketFieldDescription.ts
  packages/nodes-base/nodes/Zendesk/UserDescription.ts
Labels: n8n team, node/linting

#3434 Deduplicate encryption logic
  packages/cli/src/CredentialsHelper.ts
  packages/cli/src/api/credentials.api.ts
  packages/cli/test/integration/shared/testDb.ts
Labels: core, n8n team

#3433 Fix timeouts for users test suite
  packages/cli/test/integration/users.api.test.ts
Labels: core, n8n team

#3435 :zap: Change node-setting's parameters order
  packages/editor-ui/src/components/NodeSettings.vue
  packages/editor-ui/src/plugins/i18n/locales/en.json
Labels: ui, n8n team

#3247 GitHub node: Org option added and get all repos operation
  packages/nodes-base/credentials/GithubApi.credentials.ts
  packages/nodes-base/nodes/Github/GenericFunctions.ts
  packages/nodes-base/nodes/Github/Github.node.ts
Labels: node/improvement, community

#3426 n8n-3708-node-improvement-pr-hubspot-vid-fix
  packages/nodes-base/nodes/Hubspot/Hubspot.node.ts
Labels: n8n team, node/issue

#3470 feat(core): Run Error Workflow also on activation error
  packages/cli/src/ActiveWorkflowRunner.ts
  packages/cli/src/WorkflowExecuteAdditionalData.ts
  packages/core/src/ActiveWorkflows.ts
  packages/workflow/src/Interfaces.ts
  packages/workflow/src/WorkflowActivationError.ts
  packages/workflow/src/index.ts
Labels: core, n8n team

#3472 fix-aws-credentials-linter
  packages/nodes-base/credentials/Aws.credentials.ts
Labels: n8n team, node/issue

#3461 ⚡ Implemented automatic position detection for credential fields.
  packages/editor-ui/src/components/NodeCredentials.vue
  packages/editor-ui/src/components/ParameterInputList.vue
Labels: core, ui, n8n team

#3413 Pin data migrations for workflow entity
  packages/cli/src/Server.ts
  packages/cli/src/api/workflows.api.ts
  packages/cli/src/databases/entities/WorkflowEntity.ts
  packages/cli/src/databases/mysqldb/migrations/1654090101303-IntroducePinData.ts
  packages/cli/src/databases/mysqldb/migrations/index.ts
  packages/cli/src/databases/postgresdb/migrations/1654090467022-IntroducePinData.ts
  packages/cli/src/databases/postgresdb/migrations/index.ts
  packages/cli/src/databases/sqlite/migrations/1654089251344-IntroducePinData.ts
  packages/cli/src/databases/sqlite/migrations/index.ts
  packages/cli/test/integration/shared/testDb.ts
  packages/cli/test/integration/shared/types.d.ts
  packages/cli/test/integration/shared/utils.ts
  packages/cli/test/integration/workflows.api.test.ts
  packages/workflow/src/Interfaces.ts
Labels: feature, core, n8n team

#3497 🐛 Fixing a community nodes update detection bug
  packages/cli/src/api/nodes.api.ts
Labels: core, ui, n8n team

#3494 🐛 Reseting bin id regex between runs
  packages/nodes-base/nodes/PostBin/GenericFunctions.ts
Labels: node/improvement, n8n team, node/issue

#3501 Standardize error codes
  packages/cli/src/CommunityNodes/helpers.ts
  packages/cli/src/LoadNodesAndCredentials.ts
  packages/cli/src/api/nodes.api.ts
  packages/cli/src/constants.ts
  packages/cli/test/unit/CommunityNodeHelpers.test.ts
Labels: core, n8n team

#3499 Fix Public API failing to build on Windows
  .eslintignore
  package-lock.json
  packages/cli/package.json
  packages/cli/scripts/build.mjs
Labels: core, n8n team

#3479 Fix Misspelling of "Credentials" in multiple nodes - N8N-3845
  packages/nodes-base/nodes/Aws/Textract/AwsTextract.node.ts
  packages/nodes-base/nodes/Aws/Textract/GenericFunctions.ts
  packages/nodes-base/nodes/Dhl/Dhl.node.ts
  packages/nodes-base/nodes/Dhl/GenericFunctions.ts
  packages/nodes-base/nodes/Dropcontact/Dropcontact.node.ts
  packages/nodes-base/nodes/Dropcontact/GenericFunction.ts
  packages/nodes-base/nodes/HaloPSA/GenericFunctions.ts
  packages/nodes-base/nodes/HaloPSA/HaloPSA.node.ts
  packages/nodes-base/nodes/Linear/GenericFunctions.ts
  packages/nodes-base/nodes/Linear/Linear.node.ts
  packages/nodes-base/nodes/Notion/GenericFunctions.ts
  packages/nodes-base/nodes/Notion/v2/NotionV2.node.ts
Labels: node/improvement, community

#3477 Fix Typo in Google Calendar to Frequency - N8N-3846
  packages/nodes-base/nodes/Google/Calendar/EventDescription.ts
Labels: node/improvement, community

#3498 n8n-3711-node-fix-http-request-endpoint-returning-null
  packages/nodes-base/nodes/HttpRequest/GenericFunctions.ts
  packages/nodes-base/nodes/HttpRequest/HttpRequest.node.ts
Labels: n8n team, node/issue

#3468 Support getting Wise statements as JSON, CSV or PDF - N8N-3847
  packages/nodes-base/nodes/Wise/GenericFunctions.ts
  packages/nodes-base/nodes/Wise/Wise.node.ts
  packages/nodes-base/nodes/Wise/descriptions/AccountDescription.ts
Labels: node/improvement, community

#3489 Add client credentials grant type to OAuth2 - N8N-3836
  packages/core/src/NodeExecuteFunctions.ts
  packages/editor-ui/src/components/CredentialEdit/CredentialEdit.vue
  packages/nodes-base/credentials/AcuitySchedulingOAuth2Api.credentials.ts
  packages/nodes-base/credentials/AsanaOAuth2Api.credentials.ts
  packages/nodes-base/credentials/BitlyOAuth2Api.credentials.ts
  packages/nodes-base/credentials/BoxOAuth2Api.credentials.ts
  packages/nodes-base/credentials/CiscoWebexOAuth2Api.credentials.ts
  packages/nodes-base/credentials/ClickUpOAuth2Api.credentials.ts
  packages/nodes-base/credentials/DriftOAuth2Api.credentials.ts
  packages/nodes-base/credentials/DropboxOAuth2Api.credentials.ts
  packages/nodes-base/credentials/EventbriteOAuth2Api.credentials.ts
  packages/nodes-base/credentials/FormstackOAuth2Api.credentials.ts
  packages/nodes-base/credentials/GetResponseOAuth2Api.credentials.ts
  packages/nodes-base/credentials/GithubOAuth2Api.credentials.ts
  packages/nodes-base/credentials/GitlabOAuth2Api.credentials.ts
  packages/nodes-base/credentials/GoToWebinarOAuth2Api.credentials.ts
  packages/nodes-base/credentials/GoogleOAuth2Api.credentials.ts
  packages/nodes-base/credentials/HarvestOAuth2Api.credentials.ts
  packages/nodes-base/credentials/HelpScoutOAuth2Api.credentials.ts
  packages/nodes-base/credentials/HubspotDeveloperApi.credentials.ts
  packages/nodes-base/credentials/HubspotOAuth2Api.credentials.ts
  packages/nodes-base/credentials/KeapOAuth2Api.credentials.ts
  packages/nodes-base/credentials/LineNotifyOAuth2Api.credentials.ts
  packages/nodes-base/credentials/LinkedInOAuth2Api.credentials.ts
  packages/nodes-base/credentials/MailchimpOAuth2Api.credentials.ts
  packages/nodes-base/credentials/MauticOAuth2Api.credentials.ts
  packages/nodes-base/credentials/MediumOAuth2Api.credentials.ts
  packages/nodes-base/credentials/MicrosoftOAuth2Api.credentials.ts
  packages/nodes-base/credentials/MondayComOAuth2Api.credentials.ts
  packages/nodes-base/credentials/NextCloudOAuth2Api.credentials.ts
  packages/nodes-base/credentials/NotionOAuth2Api.credentials.ts
  packages/nodes-base/credentials/OAuth2Api.credentials.ts
  packages/nodes-base/credentials/PagerDutyOAuth2Api.credentials.ts
  packages/nodes-base/credentials/PhilipsHueOAuth2Api.credentials.ts
  packages/nodes-base/credentials/PipedriveOAuth2Api.credentials.ts
  packages/nodes-base/credentials/PushbulletOAuth2Api.credentials.ts
  packages/nodes-base/credentials/QuickBooksOAuth2Api.credentials.ts
  packages/nodes-base/credentials/RaindropOAuth2Api.credentials.ts
  packages/nodes-base/credentials/RedditOAuth2Api.credentials.ts
  packages/nodes-base/credentials/SalesforceOAuth2Api.credentials.ts
  packages/nodes-base/credentials/SentryIoOAuth2Api.credentials.ts
  packages/nodes-base/credentials/ServiceNowOAuth2Api.credentials.ts
  packages/nodes-base/credentials/SlackOAuth2Api.credentials.ts
  packages/nodes-base/credentials/SpotifyOAuth2Api.credentials.ts
  packages/nodes-base/credentials/StravaOAuth2Api.credentials.ts
  packages/nodes-base/credentials/SurveyMonkeyOAuth2Api.credentials.ts
  packages/nodes-base/credentials/TodoistOAuth2Api.credentials.ts
  packages/nodes-base/credentials/TwistOAuth2Api.credentials.ts
  packages/nodes-base/credentials/TypeformOAuth2Api.credentials.ts
  packages/nodes-base/credentials/WebflowOAuth2Api.credentials.ts
  packages/nodes-base/credentials/XeroOAuth2Api.credentials.ts
  packages/nodes-base/credentials/ZendeskOAuth2Api.credentials.ts
  packages/nodes-base/credentials/ZohoOAuth2Api.credentials.ts
  packages/nodes-base/credentials/ZoomOAuth2Api.credentials.ts
  packages/workflow/src/Interfaces.ts
Labels: node/improvement, core, ui, n8n team

#3505 Change output for install and update requests
  packages/cli/src/LoadNodesAndCredentials.ts
  packages/cli/src/api/nodes.api.ts
  packages/cli/src/constants.ts
Labels: n8n team

#3480 N8N-3656 install community package
  packages/editor-ui/public/static/community_package_tooltip_img.png
  packages/editor-ui/src/api/communityNodes.ts
  packages/editor-ui/src/components/CommunityPackageInstallModal.vue
  packages/editor-ui/src/components/Modals.vue
  packages/editor-ui/src/constants.ts
  packages/editor-ui/src/modules/communityNodes.ts
  packages/editor-ui/src/modules/ui.ts
  packages/editor-ui/src/plugins/i18n/locales/en.json
  packages/editor-ui/src/views/SettingsCommunityNodesView.vue
Labels: ui, n8n team

#3495 Post-release refactorings for Public API
  packages/cli/package.json
  packages/cli/src/Interfaces.ts
  packages/cli/src/PublicApi/index.ts
  packages/cli/src/PublicApi/v1/handlers/credentials/credentials.handler.ts
  packages/cli/src/PublicApi/v1/handlers/credentials/credentials.middleware.ts
  packages/cli/src/PublicApi/v1/handlers/credentials/credentials.service.ts
  packages/cli/src/PublicApi/v1/handlers/executions/executions.handler.ts
  packages/cli/src/PublicApi/v1/handlers/executions/executions.service.ts
  packages/cli/src/PublicApi/v1/handlers/workflows/workflows.handler.ts
  packages/cli/src/PublicApi/v1/handlers/workflows/workflows.service.ts
  packages/cli/src/PublicApi/v1/shared/middlewares/global.middleware.ts
  packages/cli/src/PublicApi/v1/shared/services/pagination.service.ts
  packages/cli/src/requests.d.ts
  packages/cli/test/integration/publicApi/credentials.test.ts
  packages/cli/test/integration/publicApi/executions.test.ts
  packages/cli/test/integration/publicApi/workflows.test.ts
  packages/cli/test/integration/shared/testDb.ts
  packages/cli/test/integration/shared/types.d.ts
  packages/cli/test/integration/shared/utils.ts
Labels: core, n8n team

#3467 Add ability to make a voice call on Twilio using TTS - N8N-3848
  packages/nodes-base/nodes/Twilio/GenericFunctions.ts
  packages/nodes-base/nodes/Twilio/Twilio.node.json
  packages/nodes-base/nodes/Twilio/Twilio.node.ts
Labels: node/improvement, community

#3510 Update README.md
  README.md
Labels: n8n team

#3504 N8N-3661 manage community packages
  package-lock.json
  packages/editor-ui/public/static/community_package_tooltip_img.png
  packages/editor-ui/src/Interface.ts
  packages/editor-ui/src/api/communityNodes.ts
  packages/editor-ui/src/api/helpers.ts
  packages/editor-ui/src/components/CommunityPackageCard.vue
  packages/editor-ui/src/components/CommunityPackageInstallModal.vue
  packages/editor-ui/src/components/CommunityPackageManageConfirmModal.vue
  packages/editor-ui/src/components/Modals.vue
  packages/editor-ui/src/constants.ts
  packages/editor-ui/src/modules/communityNodes.ts
  packages/editor-ui/src/modules/ui.ts
  packages/editor-ui/src/plugins/i18n/locales/en.json
  packages/editor-ui/src/views/SettingsCommunityNodesView.vue
Labels: ui, n8n team

#3517 Validate JSON on pinned data save
  packages/cli/src/Server.ts
  packages/cli/src/api/workflows.api.ts
  packages/cli/test/integration/workflows.api.test.ts
  packages/core/src/WorkflowExecute.ts
  packages/design-system/src/components/N8nButton/Button.vue
  packages/design-system/src/components/N8nButton/__tests__/__snapshots__/Button.spec.ts.snap
  packages/editor-ui/src/components/RunData.vue
  packages/editor-ui/src/plugins/i18n/locales/en.json
Labels: feature, ui, n8n team

#3523 N8N-3662 community nodes node view updates
  packages/design-system/src/components/N8nTabs/Tabs.vue
  packages/editor-ui/src/Interface.ts
  packages/editor-ui/src/components/NDVDraggablePanels.vue
  packages/editor-ui/src/components/NodeCreator/NodeItem.vue
  packages/editor-ui/src/components/NodeDetailsView.vue
  packages/editor-ui/src/components/NodeSettings.vue
  packages/editor-ui/src/components/NodeSettingsTabs.vue
  packages/editor-ui/src/components/helpers.ts
  packages/editor-ui/src/constants.ts
  packages/editor-ui/src/modules/communityNodes.ts
  packages/editor-ui/src/plugins/i18n/locales/en.json
  packages/editor-ui/src/store.ts
  packages/editor-ui/src/views/NodeView.vue
Labels: ui, n8n team

#3546 Enable node-class-description-empty-string
  .eslintrc.js
Labels: n8n team

#3550 Minor fixes in description and name and fixes path for credentials
  packages/nodes-base/credentials/AgileCrmApi.credentials.ts
  packages/nodes-base/credentials/CopperApi.credentials.ts
  packages/nodes-base/credentials/FormIoApi.credentials.ts
  packages/nodes-base/credentials/GoogleApi.credentials.ts
  packages/nodes-base/credentials/HaloPSAApi.credentials.ts
  packages/nodes-base/credentials/HubspotDeveloperApi.credentials.ts
  packages/nodes-base/credentials/JiraSoftwareCloudApi.credentials.ts
  packages/nodes-base/credentials/JiraSoftwareServerApi.credentials.ts
  packages/nodes-base/credentials/Kafka.credentials.ts
  packages/nodes-base/credentials/MicrosoftDynamicsOAuth2Api.credentials.ts
  packages/nodes-base/credentials/MispApi.credentials.ts
  packages/nodes-base/credentials/MongoDb.credentials.ts
  packages/nodes-base/credentials/SplunkApi.credentials.ts
  packages/nodes-base/credentials/StrapiApi.credentials.ts
  packages/nodes-base/credentials/TheHiveApi.credentials.ts
  packages/nodes-base/credentials/UProcApi.credentials.ts
  packages/nodes-base/credentials/ZammadBasicAuthApi.credentials.ts
  packages/nodes-base/credentials/ZammadTokenAuthApi.credentials.ts
  packages/nodes-base/credentials/ZendeskApi.credentials.ts
  packages/nodes-base/credentials/ZulipApi.credentials.ts
  packages/nodes-base/package.json
Labels: node/improvement, n8n team

#3478 :bug: Fix issue looking for error message when using Axios - N8N-3868
  packages/workflow/src/NodeErrors.ts
Labels: core, n8n team

#3522 :bug: Fix GET /workflows/:id not returning tags - N8N-3869
  packages/cli/src/PublicApi/v1/handlers/workflows/workflows.service.ts
  packages/cli/test/integration/publicApi/workflows.test.ts
Labels: core, n8n team

#3536 💄 Updating size of the `New Blank Workflow` button in templates page
  packages/editor-ui/src/views/TemplatesSearchView.vue
Labels: ui, n8n team

#3424 N8N-3776 Updated expressions allowlist and denylist.
  packages/workflow/package.json
  packages/workflow/src/Expression.ts
  packages/workflow/test/Expression.test.ts
Labels: n8n team

#3502 Improve DB dir setup
  packages/cli/migrations/ormconfig.ts
  packages/cli/src/Db.ts
  packages/cli/src/databases/MigrationHelpers.ts
  packages/cli/src/databases/migrations/mysqldb/1588157391238-InitialMigration.ts
  packages/cli/src/databases/migrations/mysqldb/1592447867632-WebhookModel.ts
  packages/cli/src/databases/migrations/mysqldb/1594902918301-CreateIndexStoppedAt.ts
  packages/cli/src/databases/migrations/mysqldb/1607431743767-MakeStoppedAtNullable.ts
  packages/cli/src/databases/migrations/mysqldb/1611149998770-AddWebhookId.ts
  packages/cli/src/databases/migrations/mysqldb/1615306975123-ChangeDataSize.ts
  packages/cli/src/databases/migrations/mysqldb/1617268711084-CreateTagEntity.ts
  packages/cli/src/databases/migrations/mysqldb/1620729500000-ChangeCredentialDataSize.ts
  packages/cli/src/databases/migrations/mysqldb/1620826335440-UniqueWorkflowNames.ts
  packages/cli/src/databases/migrations/mysqldb/1623936588000-CertifyCorrectCollation.ts
  packages/cli/src/databases/migrations/mysqldb/1626183952959-AddWaitColumn.ts
  packages/cli/src/databases/migrations/mysqldb/1630451444017-UpdateWorkflowCredentials.ts
  packages/cli/src/databases/migrations/mysqldb/1644424784709-AddExecutionEntityIndexes.ts
  packages/cli/src/databases/migrations/mysqldb/1646992772331-CreateUserManagement.ts
  packages/cli/src/databases/migrations/mysqldb/1648740597343-LowerCaseUserEmail.ts
  packages/cli/src/databases/migrations/mysqldb/1652367743993-AddUserSettings.ts
  packages/cli/src/databases/migrations/mysqldb/1652905585850-AddAPIKeyColumn.ts
  packages/cli/src/databases/migrations/mysqldb/index.ts
  packages/cli/src/databases/migrations/postgresdb/1587669153312-InitialMigration.ts
  packages/cli/src/databases/migrations/postgresdb/1589476000887-WebhookModel.ts
  packages/cli/src/databases/migrations/postgresdb/1594828256133-CreateIndexStoppedAt.ts
  packages/cli/src/databases/migrations/postgresdb/1607431743768-MakeStoppedAtNullable.ts
  packages/cli/src/databases/migrations/postgresdb/1611144599516-AddWebhookId.ts
  packages/cli/src/databases/migrations/postgresdb/1617270242566-CreateTagEntity.ts
  packages/cli/src/databases/migrations/postgresdb/1620824779533-UniqueWorkflowNames.ts
  packages/cli/src/databases/migrations/postgresdb/1626176912946-AddwaitTill.ts
  packages/cli/src/databases/migrations/postgresdb/1630419189837-UpdateWorkflowCredentials.ts
  packages/cli/src/databases/migrations/postgresdb/1644422880309-AddExecutionEntityIndexes.ts
  packages/cli/src/databases/migrations/postgresdb/1646834195327-IncreaseTypeVarcharLimit.ts
  packages/cli/src/databases/migrations/postgresdb/1646992772331-CreateUserManagement.ts
  packages/cli/src/databases/migrations/postgresdb/1648740597343-LowerCaseUserEmail.ts
  packages/cli/src/databases/migrations/postgresdb/1652367743993-AddUserSettings.ts
  packages/cli/src/databases/migrations/postgresdb/1652905585850-AddAPIKeyColumn.ts
  packages/cli/src/databases/migrations/postgresdb/index.ts
  packages/cli/src/databases/migrations/sqlite/1588102412422-InitialMigration.ts
  packages/cli/src/databases/migrations/sqlite/1592445003908-WebhookModel.ts
  packages/cli/src/databases/migrations/sqlite/1594825041918-CreateIndexStoppedAt.ts
  packages/cli/src/databases/migrations/sqlite/1607431743769-MakeStoppedAtNullable.ts
  packages/cli/src/databases/migrations/sqlite/1611071044839-AddWebhookId.ts
  packages/cli/src/databases/migrations/sqlite/1617213344594-CreateTagEntity.ts
  packages/cli/src/databases/migrations/sqlite/1620821879465-UniqueWorkflowNames.ts
  packages/cli/src/databases/migrations/sqlite/1621707690587-AddWaitColumn.ts
  packages/cli/src/databases/migrations/sqlite/1630330987096-UpdateWorkflowCredentials.ts
  packages/cli/src/databases/migrations/sqlite/1644421939510-AddExecutionEntityIndexes.ts
  packages/cli/src/databases/migrations/sqlite/1646992772331-CreateUserManagement.ts
  packages/cli/src/databases/migrations/sqlite/1648740597343-LowerCaseUserEmail.ts
  packages/cli/src/databases/migrations/sqlite/1652367743993-AddUserSettings.ts
  packages/cli/src/databases/migrations/sqlite/1652905585850-AddAPIKeyColumn.ts
  packages/cli/src/databases/migrations/sqlite/index.ts
  packages/cli/src/databases/ormconfig.ts
  packages/cli/src/databases/utils/migrationHelpers.ts
  packages/cli/test/integration/shared/testDb.ts
Labels: core, n8n team

#3515 Fix issue with public API tests - N8N-3843
  packages/cli/test/integration/publicApi/credentials.test.ts
  packages/cli/test/integration/publicApi/executions.test.ts
  packages/cli/test/integration/publicApi/workflows.test.ts
Labels: core, n8n team

#3556 :bug: Fix issue with credentials that define authenticate method - N8N-3907
  packages/cli/src/LoadNodesAndCredentials.ts
Labels: core, n8n team

#3431 Update icon, add cred injection and test, update url for integration
  packages/nodes-base/credentials/TwakeCloudApi.credentials.ts
  packages/nodes-base/nodes/Twake/GenericFunctions.ts
  packages/nodes-base/nodes/Twake/twake.png
Labels: node/improvement, n8n team

#3317 Add HubSpot Ticket Update Stage - N8N-3707
  packages/nodes-base/nodes/Hubspot/Hubspot.node.ts
  packages/nodes-base/nodes/Hubspot/TicketDescription.ts
Labels: node/improvement, community

#3521 feat: Added pin/unpin button and store mutations.
  packages/editor-ui/src/Interface.ts
  packages/editor-ui/src/components/RunData.vue
  packages/editor-ui/src/plugins/i18n/locales/en.json
  packages/editor-ui/src/plugins/icons.ts
  packages/editor-ui/src/store.ts
Labels: ui, n8n team

#3509 N8n 3196 trigger panel
  package-lock.json
  packages/design-system/src/components/N8nInfoAccordion/InfoAccordion.stories.ts
  packages/design-system/src/components/N8nInfoAccordion/InfoAccordion.vue
  packages/design-system/src/components/N8nInfoAccordion/index.ts
  packages/design-system/src/components/N8nNotice/Notice.vue
  packages/design-system/src/components/N8nPulse/Pulse.stories.ts
  packages/design-system/src/components/N8nPulse/Pulse.vue
  packages/design-system/src/components/N8nPulse/index.ts
  packages/design-system/src/components/N8nText/Text.vue
  packages/design-system/src/components/index.ts
  packages/editor-ui/src/components/ActivationModal.vue
  packages/editor-ui/src/components/CopyInput.vue
  packages/editor-ui/src/components/InputPanel.vue
  packages/editor-ui/src/components/MainHeader/MainHeader.vue
  packages/editor-ui/src/components/NDVDraggablePanels.vue
  packages/editor-ui/src/components/Node.vue
  packages/editor-ui/src/components/NodeDetailsView.vue
  packages/editor-ui/src/components/NodeExecuteButton.vue
  packages/editor-ui/src/components/NodeSettings.vue
  packages/editor-ui/src/components/NodeWebhooks.vue
  packages/editor-ui/src/components/OutputPanel.vue
  packages/editor-ui/src/components/ParameterInputList.vue
  packages/editor-ui/src/components/RunData.vue
  packages/editor-ui/src/components/TriggerPanel.vue
  packages/editor-ui/src/components/WorkflowActivator.vue
  packages/editor-ui/src/components/helpers.ts
  packages/editor-ui/src/components/mixins/pushConnection.ts
  packages/editor-ui/src/components/mixins/workflowActivate.ts
  packages/editor-ui/src/components/mixins/workflowHelpers.ts
  packages/editor-ui/src/components/mixins/workflowRun.ts
  packages/editor-ui/src/plugins/components.ts
  packages/editor-ui/src/plugins/i18n/locales/en.json
  packages/editor-ui/src/store.ts
  packages/editor-ui/src/views/NodeView.vue
  packages/nodes-base/nodes/Cron/Cron.node.ts
  packages/nodes-base/nodes/ErrorTrigger/ErrorTrigger.node.ts
  packages/nodes-base/nodes/Interval/Interval.node.ts
  packages/nodes-base/nodes/N8nTrigger/N8nTrigger.node.ts
  packages/nodes-base/nodes/Start/Start.node.ts
  packages/nodes-base/nodes/Webhook/Webhook.node.ts
  packages/nodes-base/nodes/WorkflowTrigger/WorkflowTrigger.node.ts
  packages/workflow/src/Interfaces.ts
  packages/workflow/src/NodeHelpers.ts
Labels: node/improvement, ui, n8n team

#3315 Enable Prettier for `/nodes-base`
  .prettierignore
  packages/nodes-base/src/NodeVersionedType.ts
  packages/nodes-base/src/index.ts
  packages/nodes-base/test/nodes/Postgres/Postgres.node.functions.test.js
  packages/nodes-base/test/nodes/Stripe/helpers.test.js
Labels: node/improvement, n8n team

#3544 ⬆️ Updating FontAwesome dependancies to v6
  packages/design-system/package.json
  packages/editor-ui/package.json
  packages/editor-ui/src/components/MainSidebar.vue
Labels: ui

#3547 ⬆️ upgrade dependencies
  packages/cli/package.json
  packages/core/package.json
  packages/editor-ui/package.json
  packages/node-dev/package.json
  packages/nodes-base/nodes/RabbitMQ/RabbitMQ.node.ts
  packages/nodes-base/package.json
  packages/workflow/package.json
Labels: dependency update, n8n team

#3074 Todoist: add move task between sections - N8N-3128
  packages/nodes-base/credentials/TodoistApi.credentials.ts
  packages/nodes-base/nodes/Todoist/GenericFunctions.ts
  packages/nodes-base/nodes/Todoist/OperationHandler.ts
  packages/nodes-base/nodes/Todoist/Service.ts
  packages/nodes-base/nodes/Todoist/Todoist.node.ts
Labels: node/improvement, community, n8n team

#3518 Add pinned data state banner
  packages/design-system/src/components/N8nCallout/Callout.vue
  packages/design-system/src/components/N8nCallout/N8nCallout.stories.ts
  packages/design-system/src/components/N8nCallout/index.ts
  packages/design-system/src/components/N8nLink/Link.vue
  packages/design-system/src/components/index.ts
  packages/design-system/theme/src/_tokens.scss
  packages/editor-ui/src/components/RunData.vue
  packages/editor-ui/src/constants.ts
  packages/editor-ui/src/plugins/components.ts
  packages/editor-ui/src/plugins/i18n/locales/en.json
  packages/editor-ui/src/plugins/icons.ts
Labels: feature, ui, n8n team

#3570 Hoist pin data on frontend
  packages/cli/src/Logger.ts
  packages/cli/src/Server.ts
  packages/cli/src/api/workflows.api.ts
  packages/cli/src/databases/entities/WorkflowEntity.ts
  packages/cli/src/databases/utils/transformers.ts
  packages/cli/test/integration/workflows.api.test.ts
  packages/editor-ui/src/Interface.ts
  packages/editor-ui/src/components/mixins/workflowHelpers.ts
  packages/editor-ui/src/components/mixins/workflowRun.ts
Labels: feature, core, ui, n8n team

#3568 N8N-3727 N8N-3725 pin data empty state and size check
  packages/cli/src/Logger.ts
  packages/cli/src/Server.ts
  packages/cli/src/api/workflows.api.ts
  packages/cli/src/databases/entities/WorkflowEntity.ts
  packages/cli/src/databases/utils/transformers.ts
  packages/cli/test/integration/workflows.api.test.ts
  packages/editor-ui/src/Interface.ts
  packages/editor-ui/src/components/NodeExecuteButton.vue
  packages/editor-ui/src/components/OutputPanel.vue
  packages/editor-ui/src/components/RunData.vue
  packages/editor-ui/src/components/helpers.ts
  packages/editor-ui/src/components/mixins/workflowHelpers.ts
  packages/editor-ui/src/components/mixins/workflowRun.ts
  packages/editor-ui/src/constants.ts
  packages/editor-ui/src/plugins/i18n/locales/en.json
  packages/editor-ui/src/store.ts
Labels: ui, n8n team

#3583 :bug: Fix logger error when logging circular json
  packages/cli/src/Logger.ts
Labels: core, n8n team

#3581 feat: Migrated to npm release of riot-tmpl fork.
  package-lock.json
  packages/cli/src/Logger.ts
  packages/workflow/package.json
  packages/workflow/src/Expression.ts
Labels: dependency update, n8n team

#3575 Correct misfix from `node-param-display-name-wrong-for-dynamic-multi-options`
  packages/cli/src/Logger.ts
  packages/nodes-base/nodes/Automizy/ContactDescription.ts
  packages/nodes-base/nodes/CoinGecko/CoinDescription.ts
  packages/nodes-base/nodes/Freshservice/descriptions/AgentDescription.ts
  packages/nodes-base/nodes/Google/GSuiteAdmin/UserDescription.ts
  packages/nodes-base/nodes/Hubspot/DealDescription.ts
Labels: n8n team, node/linting

#3563 🐛 Fixing credentials rendering when the node has no parameters
  packages/editor-ui/src/components/ParameterInputList.vue
Labels: ui, n8n team

#3520 Fix failing tests on MySQL for Public API
  packages/cli/src/databases/entities/User.ts
  packages/cli/src/databases/entities/WorkflowEntity.ts
  packages/cli/src/databases/utils/transformers.ts
  packages/cli/test/integration/publicApi/workflows.test.ts
Labels: core, n8n team

#3582 N8N-3939 Workflow canvas node design for pinned state
  packages/cli/src/Interfaces.ts
  packages/cli/src/requests.d.ts
  packages/cli/test/integration/publicApi/workflows.test.ts
  packages/core/src/WorkflowExecute.ts
  packages/editor-ui/src/Interface.ts
  packages/editor-ui/src/components/Node.vue
  packages/editor-ui/src/components/NodeExecuteButton.vue
  packages/editor-ui/src/components/RunData.vue
  packages/editor-ui/src/components/mixins/pinData.ts
  packages/editor-ui/src/components/mixins/workflowHelpers.ts
  packages/editor-ui/src/components/mixins/workflowRun.ts
  packages/editor-ui/src/store.ts
  packages/workflow/src/Interfaces.ts
Labels: ui, n8n team

#3597 Fixes issue with Reddit node not getting all posts
  packages/nodes-base/nodes/MonicaCrm/descriptions/ConversationMessageDescription.ts
  packages/nodes-base/nodes/Pipedrive/Pipedrive.node.ts
  packages/nodes-base/nodes/Reddit/PostDescription.ts
  packages/nodes-base/nodes/Splunk/descriptions/UserDescription.ts
  packages/nodes-base/nodes/Wait/Wait.node.ts
Labels: node/improvement, n8n team

#3571 Make oclif commands testable
  package-lock.json
  packages/cli/commands/BaseCommand.ts
  packages/cli/commands/user-management/reset.ts
  packages/cli/package.json
  packages/cli/src/Db.ts
  packages/cli/src/Logger.ts
  packages/cli/test/integration/commands/reset.cmd.test.ts
Labels: core, n8n team

#3503 Account for additional OAuth2 options in predefined credential call
  packages/nodes-base/nodes/HttpRequest/HttpRequest.node.ts
Labels: node/improvement, n8n team

#3599 n8n-3931 - Fixed issue with lead status not using name on update
  packages/nodes-base/nodes/Salesforce/Salesforce.node.ts
Labels: node/improvement, n8n team

#3591 :recycle: Add fileExtension from FileTypeResult to buffer data
  packages/core/src/NodeExecuteFunctions.ts
Labels: core, n8n team

#3590 feat(core): Expose item index being processed
  packages/core/src/NodeExecuteFunctions.ts
  packages/workflow/src/Interfaces.ts
  packages/workflow/test/Helpers.ts
  packages/workflow/test/RoutingNode.test.ts
Labels: core, n8n team

#3578 Authentication type rework
  packages/cli/src/CredentialsHelper.ts
  packages/cli/test/unit/CredentialsHelper.test.ts
  packages/nodes-base/credentials/AsanaApi.credentials.ts
  packages/nodes-base/credentials/CalApi.credentials.ts
  packages/nodes-base/credentials/GithubApi.credentials.ts
  packages/nodes-base/credentials/HttpHeaderAuth.credentials.ts
  packages/nodes-base/credentials/Magento2Api.credentials.ts
  packages/nodes-base/credentials/MailjetEmailApi.credentials.ts
  packages/nodes-base/credentials/MailjetSmsApi.credentials.ts
  packages/nodes-base/credentials/PipedriveApi.credentials.ts
  packages/nodes-base/credentials/ServiceNowBasicApi.credentials.ts
  packages/nodes-base/credentials/SlackApi.credentials.ts
  packages/nodes-base/credentials/TodoistApi.credentials.ts
  packages/nodes-base/credentials/TwakeCloudApi.credentials.ts
  packages/workflow/src/Interfaces.ts
Labels: node/improvement, core, n8n team

#3561 :lipstick: Add word-break: break-word to fix styling issue
  packages/editor-ui/src/n8n-theme.scss
Labels: ui, n8n team

#3606 n8n-3969 - Fetch all analyzers with Cortex
  packages/nodes-base/credentials/CortexApi.credentials.ts
  packages/nodes-base/nodes/Cortex/Cortex.node.ts
  packages/nodes-base/nodes/Cortex/GenericFunctions.ts
  packages/nodes-base/nodes/Cortex/ResponderDescription.ts
Labels: node/improvement, n8n team

#3611 Fix pindata items per run
  packages/core/src/WorkflowExecute.ts
Labels: core, n8n team

#3619 Metrics for pinned data
  packages/editor-ui/src/components/NodeDetailsView.vue
  packages/editor-ui/src/components/NodeExecuteButton.vue
  packages/editor-ui/src/components/OutputPanel.vue
  packages/editor-ui/src/components/RunData.vue
  packages/editor-ui/src/components/helpers.ts
  packages/editor-ui/src/components/mixins/pinData.ts
  packages/editor-ui/src/constants.ts
  packages/editor-ui/src/event-bus/data-pinning-event-bus.ts
Labels: feature, core, n8n team

#3585 N8N-3942 Various data pinning improvements
  packages/core/src/WorkflowExecute.ts
  packages/design-system/src/components/N8nCallout/Callout.vue
  packages/design-system/src/components/N8nLink/Link.vue
  packages/editor-ui/src/Interface.ts
  packages/editor-ui/src/components/NodeDetailsView.vue
  packages/editor-ui/src/components/NodeExecuteButton.vue
  packages/editor-ui/src/components/NodeSettings.vue
  packages/editor-ui/src/components/OutputPanel.vue
  packages/editor-ui/src/components/RunData.vue
  packages/editor-ui/src/components/forms/CodeEditor.vue
  packages/editor-ui/src/components/helpers.ts
  packages/editor-ui/src/components/mixins/pinData.ts
  packages/editor-ui/src/constants.ts
  packages/editor-ui/src/event-bus/data-pinning-event-bus.ts
  packages/editor-ui/src/modules/ui.ts
  packages/editor-ui/src/plugins/i18n/locales/en.json
  packages/editor-ui/src/store.ts
  packages/editor-ui/src/views/NodeView.vue
Labels: ui, n8n team

#3622 Stabilize tests
  packages/cli/config/index.ts
  packages/cli/test/integration/passwordReset.api.test.ts
  packages/cli/test/integration/publicApi/workflows.test.ts
  packages/cli/test/integration/shared/constants.ts
  packages/cli/test/integration/shared/testDb.ts
  packages/cli/test/integration/shared/types.d.ts
  packages/cli/test/setup.ts
Labels: core, n8n team
