Repository n8n-io/n8n, pull requests merged in 2023-03, with the labels that each got.

#5586 fix: Stop showing mapping hint after mapping
  packages/editor-ui/src/Interface.ts
  packages/editor-ui/src/components/InputPanel.vue
  packages/editor-ui/src/components/ParameterInputFull.vue
  packages/editor-ui/src/components/RunData.vue
  packages/editor-ui/src/components/RunDataJson.vue
  packages/editor-ui/src/constants.ts
  packages/editor-ui/src/stores/ndv.ts
Labels: ui, n8n team

#5588 feat: Add distribution test tracking
  packages/editor-ui/src/constants.ts
Labels: ui, n8n team

#5554 feat(Telegram Node): Add Parse Mode to Send Document operation
  packages/nodes-base/nodes/Telegram/Telegram.node.ts
Labels: node/improvement, n8n team

#5589 feat(Jira Software Node): Support binary streaming for very large binary files
  packages/nodes-base/nodes/Jira/Jira.node.ts
Labels: node/improvement, n8n team

#5574 feat(core): Add SAML settings and consolidate LDAP under SSO
  packages/cli/src/Interfaces.ts
  packages/cli/src/Ldap/constants.ts
  packages/cli/src/Server.ts
  packages/cli/src/config/schema.ts
  packages/cli/src/sso/saml/constants.ts
  packages/cli/src/sso/saml/middleware/samlEnabledMiddleware.ts
  packages/cli/src/sso/saml/routes/saml.controller.protected.ee.ts
  packages/cli/src/sso/saml/saml.service.ee.ts
  packages/cli/src/sso/saml/samlHelpers.ts
  packages/cli/src/sso/saml/types/samlPreferences.ts
  packages/editor-ui/src/Interface.ts
  packages/editor-ui/src/stores/settings.ts
Labels: core, ui, n8n team

#5591 fix: Fix mapping paths when appending to empty expression
  cypress/e2e/14-mapping.cy.ts
  cypress/pages/ndv.ts
  packages/design-system/src/types/button.ts
  packages/editor-ui/src/components/Draggable.vue
  packages/editor-ui/src/components/ParameterInputFull.vue
  packages/editor-ui/src/stores/ndv.ts
  packages/editor-ui/src/utils/__tests__/mappingUtils.test.ts
  packages/editor-ui/src/utils/__tests__/typesUtils.test.ts
  packages/editor-ui/src/utils/mappingUtils.ts
Labels: ui, n8n team

#5596 feat(OpenAI Node): Add support for ChatGPT
  packages/nodes-base/nodes/OpenAi/ChatDescription.ts
  packages/nodes-base/nodes/OpenAi/OpenAi.node.ts
Labels: node/improvement, n8n team

#5598 fix: Show RabbitMQ node in nodes panel
  packages/nodes-base/nodes/RabbitMQ/RabbitMQ.node.ts
Labels: node/improvement, n8n team

#5445 ci(editor): Run e2e tests in parallel and improve build caching
  .github/workflows/ci-pull-requests.yml
  .github/workflows/e2e-reusable.yml
  .github/workflows/e2e-tests-pr.yml
  .github/workflows/e2e-tests.yml
  cypress.config.js
  cypress/e2e/10-settings-log-streaming.cy.ts
  cypress/e2e/11-inline-expression-editor.cy.ts
  cypress/e2e/14-data-transformation-expressions.cy.ts
  cypress/e2e/14-mapping.cy.ts
  cypress/e2e/15-scheduler-node.cy.ts
  cypress/e2e/16-webhook-node.cy.ts
  cypress/e2e/17-sharing.cy.ts
  cypress/e2e/17-workflow-tags.cy.ts
  cypress/e2e/19-execution.cy.ts
  cypress/e2e/2-credentials.cy.ts
  cypress/e2e/20-workflow-executions.cy.ts
  cypress/e2e/3-default-owner.cy.ts
  cypress/e2e/4-node-creator.cy.ts
  cypress/e2e/5-ndv.cy.ts
  cypress/e2e/7-workflow-actions.cy.ts
  cypress/pages/credentials.ts
  cypress/pages/modals/credentials-modal.ts
  cypress/pages/workflow-executions-tab.ts
  cypress/pages/workflow.ts
  cypress/pages/workflows.ts
  cypress/support/commands.ts
  package.json
  packages/cli/src/constants.ts
  packages/editor-ui/src/components/ResourceLocator/ResourceLocator.vue
  packages/editor-ui/src/views/NodeView.vue
  pnpm-lock.yaml
Labels: core, ui, n8n team

#5577 feat(core): Limit user changes when saml is enabled
  packages/cli/src/controllers/me.controller.ts
  packages/cli/src/sso/saml/middleware/samlEnabledMiddleware.ts
  packages/cli/src/sso/saml/samlHelpers.ts
  packages/cli/src/sso/ssoHelpers.ts
  packages/cli/test/integration/saml/saml.api.test.ts
Labels: core, ui, n8n team

#5609 fix(OpenAI Node): Fix issue with expressions not working with chat complete
  packages/nodes-base/nodes/OpenAi/ChatDescription.ts
  packages/nodes-base/nodes/OpenAi/ChatFunctions.ts
Labels: node/improvement, n8n team

#5612 feat(Slack Node): Move from Binary Buffer to Binary streaming
  packages/nodes-base/nodes/Slack/V2/SlackV2.node.ts
Labels: node/improvement, n8n team

#5614 refactor: `catch` doesn't need to have a param (no-changelog)
  packages/cli/src/CommunityNodes/helpers.ts
  packages/cli/src/CurlConverterHelper.ts
  packages/cli/src/LoadNodesAndCredentials.ts
  packages/cli/src/PublicApi/v1/handlers/credentials/credentials.middleware.ts
  packages/cli/src/api/nodes.api.ts
  packages/cli/src/controllers/translation.controller.ts
  packages/cli/src/databases/migrations/sqlite/1659888469333-AddJsonKeyPinData.ts
  packages/cli/src/eventbus/MessageEventBusDestination/MessageEventBusDestinationWebhook.ee.ts
  packages/core/src/DirectoryLoader.ts
  packages/editor-ui/src/components/CodeNodeEditor/CodeNodeEditor.vue
  packages/editor-ui/src/components/CodeNodeEditor/completer.ts
  packages/editor-ui/src/components/CodeNodeEditor/completions/jsonField.completions.ts
  packages/editor-ui/src/components/CodeNodeEditor/linter.ts
  packages/editor-ui/src/components/NodeSettings.vue
  packages/editor-ui/src/plugins/codemirror/completions/bracketAccess.completions.ts
  packages/editor-ui/src/plugins/codemirror/completions/datatype.completions.ts
  packages/nodes-base/nodes/HttpRequest/V1/HttpRequestV1.node.ts
  packages/nodes-base/nodes/HttpRequest/V2/HttpRequestV2.node.ts
  packages/nodes-base/nodes/HttpRequest/V3/HttpRequestV3.node.ts
  packages/workflow/src/TelemetryHelpers.ts
Labels: node/improvement, core, ui, n8n team, skip-e2e

#5616 refactor: Fix some typos (no-changelog)
  .vscode/extensions.json
  packages/cli/src/eventbus/MessageEventBusDestination/MessageEventBusDestinationWebhook.ee.ts
  packages/editor-ui/src/views/NodeView.vue
  packages/nodes-base/nodes/Affinity/AffinityTrigger.node.ts
  packages/nodes-base/nodes/Asana/AsanaTrigger.node.ts
  packages/nodes-base/nodes/Box/BoxTrigger.node.ts
  packages/nodes-base/nodes/Cal/CalTrigger.node.ts
  packages/nodes-base/nodes/Calendly/CalendlyTrigger.node.ts
  packages/nodes-base/nodes/Cisco/Webex/CiscoWebexTrigger.node.ts
  packages/nodes-base/nodes/Egoi/GenericFunctions.ts
  packages/nodes-base/nodes/Figma/FigmaTrigger.node.ts
  packages/nodes-base/nodes/Formstack/FormstackTrigger.node.ts
  packages/nodes-base/nodes/Github/GithubTrigger.node.ts
  packages/nodes-base/nodes/Gitlab/GitlabTrigger.node.ts
  packages/nodes-base/nodes/HelpScout/HelpScoutTrigger.node.ts
  packages/nodes-base/nodes/Html/Html.node.ts
  packages/nodes-base/nodes/HtmlExtract/HtmlExtract.node.ts
  packages/nodes-base/nodes/HttpRequest/V1/HttpRequestV1.node.ts
  packages/nodes-base/nodes/HttpRequest/V2/HttpRequestV2.node.ts
  packages/nodes-base/nodes/HttpRequest/V3/HttpRequestV3.node.ts
  packages/nodes-base/nodes/If/If.node.ts
  packages/nodes-base/nodes/InvoiceNinja/InvoiceNinjaTrigger.node.ts
  packages/nodes-base/nodes/Jira/JiraTrigger.node.ts
  packages/nodes-base/nodes/Keap/KeapTrigger.node.ts
  packages/nodes-base/nodes/Linear/LinearTrigger.node.ts
  packages/nodes-base/nodes/Mailchimp/MailchimpTrigger.node.ts
  packages/nodes-base/nodes/MailerLite/MailerLiteTrigger.node.ts
  packages/nodes-base/nodes/PayPal/PayPalTrigger.node.ts
  packages/nodes-base/nodes/Pipedrive/GenericFunctions.ts
  packages/nodes-base/nodes/Pipedrive/PipedriveTrigger.node.ts
  packages/nodes-base/nodes/PostBin/BinDescription.ts
  packages/nodes-base/nodes/PostBin/GenericFunctions.ts
  packages/nodes-base/nodes/Postmark/PostmarkTrigger.node.ts
  packages/nodes-base/nodes/Pushcut/PushcutTrigger.node.ts
  packages/nodes-base/nodes/SendInBlue/EmailDescription.ts
  packages/nodes-base/nodes/SendInBlue/GenericFunctions.ts
  packages/nodes-base/nodes/SendInBlue/SendInBlueTrigger.node.ts
  packages/nodes-base/nodes/Strava/StravaTrigger.node.ts
  packages/nodes-base/nodes/Stripe/StripeTrigger.node.ts
  packages/nodes-base/nodes/SurveyMonkey/SurveyMonkeyTrigger.node.ts
  packages/nodes-base/nodes/Switch/Switch.node.ts
  packages/nodes-base/nodes/TheHive/TheHiveTrigger.node.ts
  packages/nodes-base/nodes/Trello/TrelloTrigger.node.ts
  packages/nodes-base/nodes/Typeform/TypeformTrigger.node.ts
  packages/nodes-base/nodes/Venafi/ProtectCloud/VenafiTlsProtectCloudTrigger.node.ts
  packages/nodes-base/nodes/Wait/Wait.node.ts
  packages/nodes-base/nodes/WhatsApp/MessagesDescription.ts
  packages/nodes-base/nodes/Wordpress/Wordpress.node.ts
  packages/nodes-base/nodes/Workable/WorkableTrigger.node.ts
  packages/nodes-base/nodes/Zendesk/OrganizationDescription.ts
  packages/nodes-base/nodes/Zendesk/TriggerPlaceholders.ts
  packages/nodes-base/nodes/Zoho/descriptions/DealDescription.ts
  packages/nodes-base/nodes/Zoom/MeetingRegistrantDescription.ts
Labels: skip-e2e

#5618 fix(OpenAI Node): Simplify code
  packages/nodes-base/nodes/OpenAi/ChatDescription.ts
  packages/nodes-base/nodes/OpenAi/ChatFunctions.ts
Labels: node/improvement, n8n team

#5622 refactor(editor): Add spec input to e2e-tests workflow (no-changelog)
  .github/workflows/e2e-tests.yml
Labels: n8n team

#5600 feat(core): Add SAML XML validation
  packages/cli/package.json
  packages/cli/src/Server.ts
  packages/cli/src/sso/saml/routes/saml.controller.protected.ee.ts
  packages/cli/src/sso/saml/saml.service.ee.ts
  packages/cli/src/sso/saml/samlValidator.ts
  packages/cli/src/sso/saml/schema/saml-schema-assertion-2.0.xsd.ts
  packages/cli/src/sso/saml/schema/saml-schema-metadata-2.0.xsd.ts
  packages/cli/src/sso/saml/schema/saml-schema-protocol-2.0.xsd.ts
  packages/cli/src/sso/saml/schema/xenc-schema.xsd.ts
  packages/cli/src/sso/saml/schema/xml.xsd.ts
  packages/cli/src/sso/saml/schema/xmldsig-core-schema.xsd.ts
  packages/cli/src/sso/saml/serviceProvider.ee.ts
  packages/cli/src/sso/saml/types/samlPreferences.ts
  packages/cli/src/sso/ssoHelpers.ts
  packages/cli/tsconfig.json
  pnpm-lock.yaml
Labels: core, n8n team

#5617 ci: Disable provenance attestation on docker images to work around docker/buildx#1533
  .github/workflows/docker-base-image.yml
  .github/workflows/docker-images-nightly.yml
  .github/workflows/docker-images.yml
Labels: n8n team, skip-e2e

#5625 ci: Add migrations code owners
  .github/CODEOWNERS
Labels: n8n team, skip-e2e

#5626 fix(core): Allow serving icons for custom nodes with npm scoped names
  packages/cli/src/Server.ts
Labels: core, n8n team

#5630 feat(Mattermost Node): Add self signed certificate support
  packages/nodes-base/credentials/MattermostApi.credentials.ts
  packages/nodes-base/nodes/Mattermost/v1/transport/index.ts
Labels: node/improvement, n8n team

#5636 ci: Remove second code owners for migrations
  .github/CODEOWNERS
Labels: skip-e2e

#5638 feat(core): Add advancedFilters feature flag
  packages/cli/src/Interfaces.ts
  packages/cli/src/License.ts
  packages/cli/src/Server.ts
  packages/cli/src/config/schema.ts
  packages/cli/src/constants.ts
  packages/cli/src/executions/executionHelpers.ts
Labels: core, n8n team

#5639 chore: Clean up distribution test
  packages/editor-ui/src/constants.ts
Labels: ui, n8n team, skip-e2e

#5640 fix: Fix color discrepancies for executions list items
  packages/editor-ui/src/components/ExecutionsList.vue
Labels: ui, n8n team

#5641 fix(core): Add a helper function for stringify a binary stream (no-changelog)
  packages/core/src/BinaryDataManager/index.ts
  packages/core/src/BinaryDataManager/utils.ts
  packages/core/src/NodeExecuteFunctions.ts
Labels: core, n8n team, skip-e2e

#5635 ci: Setup TS project references for nodes-base, and stop packaging tests in the npm package (no-changelog)
  packages/nodes-base/package.json
  packages/nodes-base/tsconfig.build.json
  packages/nodes-base/tsconfig.json
Labels: node/improvement, n8n team, skip-e2e

#5629 feat(editor): Redirect users to canvas if they don't have any workflows
  cypress/e2e/1-workflows.cy.ts
  cypress/e2e/10-undo-redo.cy.ts
  cypress/e2e/12-canvas.cy.ts
  cypress/e2e/13-pinning.cy.ts
  cypress/e2e/14-mapping.cy.ts
  cypress/e2e/15-scheduler-node.cy.ts
  cypress/e2e/16-webhook-node.cy.ts
  cypress/e2e/17-sharing.cy.ts
  cypress/e2e/17-workflow-tags.cy.ts
  cypress/e2e/19-execution.cy.ts
  cypress/e2e/2-credentials.cy.ts
  cypress/e2e/20-workflow-executions.cy.ts
  cypress/e2e/3-default-owner.cy.ts
  cypress/e2e/4-node-creator.cy.ts
  cypress/e2e/5-ndv.cy.ts
  cypress/e2e/6-code-node.cy.ts
  cypress/e2e/7-workflow-actions.cy.ts
  cypress/e2e/8-http-request-node.cy.ts
  cypress/pages/settings-users.ts
  cypress/pages/workflow.ts
  cypress/support/commands.ts
  cypress/support/e2e.ts
  packages/editor-ui/src/views/WorkflowsView.vue
Labels: ui, n8n team

#5331 fix(Cal Trigger Node): Update to support v2 webhooks
  packages/nodes-base/nodes/Cal/CalTrigger.node.ts
Labels: node/improvement, community

#5551 docs(Github Trigger Node): Add notice and more meaningful error around permissions
  packages/nodes-base/nodes/Github/GithubTrigger.node.ts
Labels: node/improvement, n8n team

#5446 refactor(editor): Remove monaco editor
  packages/editor-ui/package.json
  packages/editor-ui/src/components/CodeEdit.vue
  packages/editor-ui/src/components/CodeNodeEditor/CodeNodeEditor.vue
  packages/editor-ui/src/components/CodeNodeEditor/languages/javaScript/constants.ts
  packages/editor-ui/src/components/CodeNodeEditor/languages/python/constants.ts
  packages/editor-ui/src/components/CodeNodeEditor/theme.ts
  packages/editor-ui/src/components/ParameterInput.vue
  packages/editor-ui/src/components/RunData.vue
  packages/editor-ui/src/components/forms/CodeEditor.vue
  packages/editor-ui/src/components/forms/index.ts
  packages/editor-ui/vite.config.ts
  packages/nodes-base/nodes/Code/Code.node.ts
  pnpm-lock.yaml
Labels: node/improvement, core, ui, n8n team

#5637 feat(core): Refactor and add SAML preferences for service provider instance
  packages/cli/src/sso/saml/routes/saml.controller.protected.ee.ts
  packages/cli/src/sso/saml/routes/saml.controller.public.ee.ts
  packages/cli/src/sso/saml/saml.service.ee.ts
  packages/cli/src/sso/saml/serviceProvider.ee.ts
  packages/cli/src/sso/saml/types/samlPreferences.ts
Labels: core, n8n team

#5619 fix(core): Use new version of riot-tmpl in workflow package (no-changelog)
  packages/workflow/package.json
  pnpm-lock.yaml
Labels: core, n8n team, skip-e2e

#5160 feat(Microsoft SQL Node): Add support for self signed certs
  packages/nodes-base/credentials/MicrosoftSql.credentials.ts
  packages/nodes-base/nodes/Microsoft/Sql/MicrosoftSql.node.ts
Labels: node/improvement, n8n team

#5559 feat(Mindee Node): Add support for v4 API
  packages/nodes-base/nodes/Mindee/GenericFunctions.ts
  packages/nodes-base/nodes/Mindee/Mindee.node.ts
Labels: node/improvement, n8n team

#5611 refactor(core): Convert more routes to use the decorator pattern (no-changelog)
  packages/cli/src/Ldap/routes/ldap.controller.ee.ts
  packages/cli/src/Server.ts
  packages/cli/src/api/tags.api.ts
  packages/cli/src/controllers/index.ts
  packages/cli/src/controllers/ldap.controller.ts
  packages/cli/src/controllers/nodeTypes.controller.ts
  packages/cli/src/controllers/nodes.controller.ts
  packages/cli/src/controllers/tags.controller.ts
  packages/cli/src/decorators/Middleware.ts
  packages/cli/src/decorators/Route.ts
  packages/cli/src/decorators/constants.ts
  packages/cli/src/decorators/index.ts
  packages/cli/src/decorators/registerController.ts
  packages/cli/src/decorators/types.ts
  packages/cli/src/index.ts
  packages/cli/src/middlewares/auth.ts
  packages/cli/src/requests.ts
  packages/cli/test/integration/ldap/ldap.api.test.ts
  packages/cli/test/integration/shared/utils.ts
Labels: core, n8n team, skip-e2e

#5656 feat(core): Allow using middlewares with decorators on a per-route basis (no-changelog)
  packages/cli/src/decorators/Route.ts
  packages/cli/src/decorators/registerController.ts
  packages/cli/src/decorators/types.ts
Labels: core, n8n team, skip-e2e

#5644 feat(editor): Do not automatically add manual trigger on node plus
  cypress/e2e/4-node-creator.cy.ts
  cypress/pages/workflow.ts
  cypress/support/commands.ts
  packages/editor-ui/src/Interface.ts
  packages/editor-ui/src/components/Node/NodeCreation.vue
  packages/editor-ui/src/constants.ts
  packages/editor-ui/src/stores/nodeCreator.ts
  packages/editor-ui/src/views/NodeView.vue
Labels: ui, n8n team

#5654 feat(editor): Only redirect new users to blank canvas (no-changelog)
  cypress/e2e/1-workflows.cy.ts
  cypress/pages/settings-users.ts
  cypress/support/commands.ts
  packages/editor-ui/src/views/SetupView.vue
  packages/editor-ui/src/views/SignupView.vue
  packages/editor-ui/src/views/WorkflowsView.vue
Labels: ui, n8n team

#5610 feat(HTTP Request Node): Move from Binary Buffer to Binary streaming
  packages/core/src/NodeExecuteFunctions.ts
  packages/nodes-base/nodes/HttpRequest/V3/HttpRequestV3.node.ts
  packages/workflow/src/Interfaces.ts
Labels: node/improvement, n8n team, skip-e2e

#5657 fix(core): Fix issues with LDAP reset and LDAP init (no-changelog)
  packages/cli/src/commands/ldap/reset.ts
  packages/cli/src/commands/start.ts
Labels: core, n8n team, skip-e2e

#5658 ci: Fix e2e tests (no-changelog)
  .github/workflows/ci-pull-requests.yml
  cypress/support/commands.ts
Labels: n8n team, skip-e2e

#5660 fix(core): Fix trying to pipe a non stream on errors (no-changelog)
  packages/core/src/NodeExecuteFunctions.ts
Labels: core, n8n team, skip-e2e

#5663 fix(HTTP Request Node): Remove streaming response
  packages/nodes-base/nodes/HttpRequest/V3/HttpRequestV3.node.ts
Labels: node/improvement, n8n team, skip-e2e

#5634 fix(editor): Display correct error message
  packages/workflow/src/WorkflowDataProxy.ts
Labels: core, n8n team

#5669 ci: Setup code-coverage reporting (no-changelog)
  .github/workflows/ci-master.yml
  .github/workflows/ci-pull-requests.yml
  .gitignore
  jest.config.js
  packages/cli/jest.config.js
  packages/cli/test/integration/commands/reset.cmd.test.ts
  packages/design-system/.gitignore
  packages/nodes-base/jest.config.js
  packages/nodes-base/test/nodes/Helpers.ts
Labels: core, ui, n8n team, skip-e2e

#5673 fix(core): Initialize License and LDAP in the correct order
  packages/cli/src/Server.ts
  packages/cli/src/commands/BaseCommand.ts
  packages/cli/src/commands/start.ts
Labels: core, n8n team

#5653 feat(core): Convert saml controller to decorator style
  packages/cli/src/Server.ts
  packages/cli/src/sso/saml/routes/saml.controller.ee.ts
  packages/cli/src/sso/saml/routes/saml.controller.protected.ee.ts
  packages/cli/src/sso/saml/routes/saml.controller.public.ee.ts
  packages/cli/src/sso/saml/saml.service.ee.ts
  packages/cli/src/sso/saml/samlHelpers.ts
  packages/cli/src/sso/saml/serviceProvider.ee.ts
  packages/cli/src/sso/saml/types/samlPreferences.ts
  packages/cli/src/sso/ssoHelpers.ts
Labels: core, n8n team

#5671 feat: Add Mirage.js server to enable editor-ui unit tests
  packages/editor-ui/package.json
  packages/editor-ui/src/__tests__/server/endpoints/credential.ts
  packages/editor-ui/src/__tests__/server/endpoints/credentialType.ts
  packages/editor-ui/src/__tests__/server/endpoints/index.ts
  packages/editor-ui/src/__tests__/server/endpoints/user.ts
  packages/editor-ui/src/__tests__/server/factories/credential.ts
  packages/editor-ui/src/__tests__/server/factories/credentialType.ts
  packages/editor-ui/src/__tests__/server/factories/index.ts
  packages/editor-ui/src/__tests__/server/factories/user.ts
  packages/editor-ui/src/__tests__/server/index.ts
  packages/editor-ui/src/__tests__/server/models/credential.ts
  packages/editor-ui/src/__tests__/server/models/credentialType.ts
  packages/editor-ui/src/__tests__/server/models/index.ts
  packages/editor-ui/src/__tests__/server/models/user.ts
  packages/editor-ui/src/__tests__/server/types.ts
  packages/editor-ui/src/stores/__tests__/credentials.spec.ts
  pnpm-lock.yaml
Labels: n8n team

#5678 ci: Add e2e checklist
  CHECKLIST.yml
Labels: n8n team

#5680 feat(core): Improve SAML connection test
  packages/cli/src/sso/saml/middleware/samlEnabledMiddleware.ts
  packages/cli/src/sso/saml/routes/saml.controller.ee.ts
  packages/cli/src/sso/saml/types/requests.ts
Labels: core, n8n team

#5679 ci: Setup code-coverage reporting for frontend packages (no-changelog)
  .github/workflows/ci-master.yml
  .github/workflows/ci-pull-requests.yml
  packages/design-system/package.json
  packages/design-system/vite.config.ts
  packages/editor-ui/package.json
  packages/editor-ui/vite.config.ts
  pnpm-lock.yaml
Labels: ui, n8n team, skip-e2e

#5648 feat(Item Lists Node): Update actions
  packages/nodes-base/nodes/ItemLists/V2/ItemListsV2.node.ts
Labels: node/improvement, n8n team

#5497 test: Add expression transform tests
  packages/workflow/src/Expression.ts
  packages/workflow/src/Extensions/ExpressionExtension.ts
  packages/workflow/test/Expression.test.ts
  packages/workflow/test/ExpressionFixtures/base.ts
Labels: core, n8n team

#5683 feat(editor): Do not show actions panel for single-action nodes
  cypress/e2e/4-node-creator.cy.ts
  packages/editor-ui/src/stores/nodeCreator.ts
Labels: ui, n8n team

#5655 feat(Split In Batches Node): Make it easy to combine processed data
  packages/nodes-base/nodes/SplitInBatches/SplitInBatches.node.ts
  packages/nodes-base/nodes/SplitInBatches/test/SplitInBatches.combineData.json
Labels: node/improvement, n8n team

#5689 ci: Copy jest.config.js to the Docker container on deployment (no-changelog)
  docker/images/n8n-custom/Dockerfile
Labels: n8n team

#5665 fix(Metabase Node): Fix issue with question results not correctly being returned
  packages/nodes-base/nodes/Metabase/QuestionsDescription.ts
Labels: node/improvement, n8n team

#5692 feat(OpenAI Node): Add support for gpt4 on chat completion
  packages/nodes-base/nodes/OpenAi/ChatDescription.ts
Labels: node/improvement, n8n team

#5696 refactor: Rewrite workflow public-api tests to avoid timeouts (no-changelog)
  packages/cli/src/PublicApi/v1/handlers/workflows/workflows.handler.ts
  packages/cli/src/PublicApi/v1/handlers/workflows/workflows.service.ts
  packages/cli/test/integration/publicApi/workflows.test.ts
  packages/cli/test/integration/shared/testDb.ts
Labels: skip-e2e

#5688 feat(editor): Add support for schema view in the NDV output
  cypress/e2e/5-ndv.cy.ts
  cypress/e2e/7-workflow-actions.cy.ts
  cypress/fixtures/Test_workflow_schema_test.json
  cypress/pages/ndv.ts
  cypress/support/commands.ts
  cypress/support/index.ts
  packages/editor-ui/src/components/RunData.vue
  packages/editor-ui/src/components/RunDataSchema.test.ts
  packages/editor-ui/src/components/RunDataSchema.vue
  packages/editor-ui/src/components/RunDataSchemaItem.vue
  packages/editor-ui/src/components/__snapshots__/RunDataSchema.test.ts.snap
Labels: ui, n8n team

#5695 fix(editor): Fix autocomplete for complex expresions
  packages/editor-ui/src/plugins/codemirror/completions/__tests__/completions.test.ts
  packages/editor-ui/src/plugins/codemirror/completions/utils.ts
Labels: ui, n8n team

#5702 feat(IF Node): Node description update no-changelog
  packages/nodes-base/nodes/If/If.node.ts
Labels: node/improvement, n8n team

#5703 fix(editor): Properly handle mapping of dragged expression if it contains hyphen
  packages/editor-ui/src/utils/__tests__/mappingUtils.test.ts
  packages/editor-ui/src/utils/mappingUtils.ts
Labels: ui, n8n team

#5690 refactor(core): Use an IoC container to manage singleton classes [Part-2] (no-changelog)
  packages/cli/src/AbstractServer.ts
  packages/cli/src/ActiveExecutions.ts
  packages/cli/src/ActiveWorkflowRunner.ts
  packages/cli/src/Ldap/helpers.ts
  packages/cli/src/License.ts
  packages/cli/src/PublicApi/types.d.ts
  packages/cli/src/PublicApi/v1/shared/middlewares/global.middleware.ts
  packages/cli/src/Queue.ts
  packages/cli/src/Server.ts
  packages/cli/src/UserManagement/UserManagementHelper.ts
  packages/cli/src/UserManagement/email/Interfaces.ts
  packages/cli/src/UserManagement/email/NodeMailer.ts
  packages/cli/src/UserManagement/email/UserManagementMailer.ts
  packages/cli/src/UserManagement/email/index.ts
  packages/cli/src/WaitTracker.ts
  packages/cli/src/WaitingWebhooks.ts
  packages/cli/src/WorkflowExecuteAdditionalData.ts
  packages/cli/src/WorkflowHelpers.ts
  packages/cli/src/WorkflowRunner.ts
  packages/cli/src/WorkflowRunnerProcess.ts
  packages/cli/src/commands/execute.ts
  packages/cli/src/commands/start.ts
  packages/cli/src/commands/worker.ts
  packages/cli/src/controllers/passwordReset.controller.ts
  packages/cli/src/eventbus/MessageEventBus/MessageEventBusHelper.ts
  packages/cli/src/executions/executionHelpers.ts
  packages/cli/src/executions/executions.service.ts
  packages/cli/src/index.ts
  packages/cli/src/license/License.service.ts
  packages/cli/src/license/license.controller.ts
  packages/cli/src/requests.ts
  packages/cli/src/sso/saml/saml.service.ee.ts
  packages/cli/src/sso/saml/samlHelpers.ts
  packages/cli/src/telemetry/index.ts
  packages/cli/src/utils.ts
  packages/cli/test/integration/shared/utils.ts
  packages/cli/test/integration/users.api.test.ts
  packages/cli/test/unit/ActiveWorkflowRunner.test.ts
  packages/cli/test/unit/Telemetry.test.ts
Labels: core, n8n team

#5706 test(core): Use instance owner instead of owner shell for SAML tests (no-changelog)
  packages/cli/test/integration/saml/saml.api.test.ts
Labels: core, n8n team

#5606 fix(editor): Fix execution list item selection
  packages/cli/src/executions/executions.service.ts
  packages/editor-ui/package.json
  packages/editor-ui/src/components/ExecutionsList.vue
  packages/editor-ui/src/components/__tests__/ExecutionsList.test.ts
  packages/editor-ui/src/plugins/i18n/locales/en.json
  pnpm-lock.yaml
Labels: ui, n8n team

#5712 fix(core): Fix telemetry execution status for manual workflows executions
  packages/cli/src/InternalHooks.ts
Labels: core, n8n team

#5713 refactor: Improve typings for webhook methods (no-changelog)
  packages/nodes-base/nodes/ActiveCampaign/ActiveCampaignTrigger.node.ts
  packages/nodes-base/nodes/AcuityScheduling/AcuitySchedulingTrigger.node.ts
  packages/nodes-base/nodes/Affinity/AffinityTrigger.node.ts
  packages/nodes-base/nodes/Asana/AsanaTrigger.node.ts
  packages/nodes-base/nodes/Autopilot/AutopilotTrigger.node.ts
  packages/nodes-base/nodes/Bitbucket/BitbucketTrigger.node.ts
  packages/nodes-base/nodes/Box/BoxTrigger.node.ts
  packages/nodes-base/nodes/Calendly/CalendlyTrigger.node.ts
  packages/nodes-base/nodes/Cisco/Webex/CiscoWebexTrigger.node.ts
  packages/nodes-base/nodes/ClickUp/ClickUpTrigger.node.ts
  packages/nodes-base/nodes/ConvertKit/ConvertKitTrigger.node.ts
  packages/nodes-base/nodes/Copper/CopperTrigger.node.ts
  packages/nodes-base/nodes/CustomerIo/CustomerIoTrigger.node.ts
  packages/nodes-base/nodes/Eventbrite/EventbriteTrigger.node.ts
  packages/nodes-base/nodes/Facebook/FacebookTrigger.node.ts
  packages/nodes-base/nodes/Figma/FigmaTrigger.node.ts
  packages/nodes-base/nodes/Flow/FlowTrigger.node.ts
  packages/nodes-base/nodes/FormIo/FormIoTrigger.node.ts
  packages/nodes-base/nodes/Formstack/FormstackTrigger.node.ts
  packages/nodes-base/nodes/GetResponse/GetResponseTrigger.node.ts
  packages/nodes-base/nodes/Gitlab/GitlabTrigger.node.ts
  packages/nodes-base/nodes/Gumroad/GumroadTrigger.node.ts
  packages/nodes-base/nodes/HelpScout/HelpScoutTrigger.node.ts
  packages/nodes-base/nodes/Hubspot/HubspotTrigger.node.ts
  packages/nodes-base/nodes/InvoiceNinja/InvoiceNinjaTrigger.node.ts
  packages/nodes-base/nodes/JotForm/JotFormTrigger.node.ts
  packages/nodes-base/nodes/Keap/KeapTrigger.node.ts
  packages/nodes-base/nodes/Lemlist/LemlistTrigger.node.ts
  packages/nodes-base/nodes/Linear/LinearTrigger.node.ts
  packages/nodes-base/nodes/Mailchimp/MailchimpTrigger.node.ts
  packages/nodes-base/nodes/MailerLite/MailerLiteTrigger.node.ts
  packages/nodes-base/nodes/Mailjet/MailjetTrigger.node.ts
  packages/nodes-base/nodes/Mautic/MauticTrigger.node.ts
  packages/nodes-base/nodes/Pushcut/PushcutTrigger.node.ts
  packages/nodes-base/nodes/SendInBlue/SendInBlueTrigger.node.ts
  packages/nodes-base/nodes/Strava/StravaTrigger.node.ts
  packages/nodes-base/nodes/Taiga/TaigaTrigger.node.ts
  packages/nodes-base/nodes/TheHive/TheHiveTrigger.node.ts
  packages/nodes-base/nodes/Trello/TrelloTrigger.node.ts
  packages/nodes-base/nodes/Typeform/TypeformTrigger.node.ts
  packages/nodes-base/nodes/Workable/WorkableTrigger.node.ts
  packages/workflow/src/Interfaces.ts
  packages/workflow/src/Workflow.ts
Labels: node/improvement, n8n team, skip-e2e

#3572 feat(QuickChart Node): Add QuickChart node
  packages/nodes-base/nodes/QuickChart/QuickChart.node.json
  packages/nodes-base/nodes/QuickChart/QuickChart.node.ts
  packages/nodes-base/nodes/QuickChart/constants.ts
  packages/nodes-base/nodes/QuickChart/quickChart.svg
  packages/nodes-base/nodes/QuickChart/test/QuickChart.node.test.ts
  packages/nodes-base/nodes/QuickChart/test/QuickChart.workflow.json
  packages/nodes-base/nodes/QuickChart/types.ts
  packages/nodes-base/package.json
Labels: node/new, n8n team

#5708 fix(editor): Fix redo in code and expression editor
  packages/editor-ui/src/components/CodeNodeEditor/baseExtensions.ts
  packages/editor-ui/src/components/ExpressionEditorModal/ExpressionEditorModalInput.vue
  packages/editor-ui/src/components/HtmlEditor/HtmlEditor.vue
  packages/editor-ui/src/components/InlineExpressionEditor/InlineExpressionEditorInput.vue
Labels: ui, n8n team

#5715 fix(editor): Disable tooltip for display modes that don't support mapping
  packages/editor-ui/src/components/ParameterInputFull.vue
Labels: ui, n8n team

#5711 fix(editor): Remove cloud check when pre-selecting auth options (no-changelog)
  packages/editor-ui/src/utils/nodeTypesUtils.ts
Labels: ui, n8n team

#5718 ci: Refactor cli tests to speed up CI (no-changelog)
  jest.config.js
  package.json
  packages/cli/src/index.ts
  packages/cli/test/integration/auth.api.test.ts
  packages/cli/test/integration/auth.mw.test.ts
  packages/cli/test/integration/credentials.ee.test.ts
  packages/cli/test/integration/credentials.test.ts
  packages/cli/test/integration/eventbus.test.ts
  packages/cli/test/integration/ldap/ldap.api.test.ts
  packages/cli/test/integration/license.api.test.ts
  packages/cli/test/integration/me.api.test.ts
  packages/cli/test/integration/nodes.api.test.ts
  packages/cli/test/integration/owner.api.test.ts
  packages/cli/test/integration/passwordReset.api.test.ts
  packages/cli/test/integration/publicApi/credentials.test.ts
  packages/cli/test/integration/publicApi/executions.test.ts
  packages/cli/test/integration/publicApi/workflows.test.ts
  packages/cli/test/integration/saml/saml.api.test.ts
  packages/cli/test/integration/shared/augmentation.d.ts
  packages/cli/test/integration/shared/utils.ts
  packages/cli/test/integration/users.api.test.ts
  packages/cli/test/integration/workflows.controller.ee.test.ts
  packages/cli/test/integration/workflows.controller.test.ts
  packages/cli/test/unit/ActiveWorkflowRunner.test.ts
  packages/cli/test/unit/CredentialsHelper.test.ts
  packages/cli/test/unit/Events.test.ts
  packages/cli/test/unit/Helpers.ts
  packages/cli/test/unit/PermissionChecker.test.ts
  pnpm-lock.yaml
Labels: skip-e2e

#5719 feat(editor): Move canvas by holding Space or Middle mouse button
  packages/editor-ui/src/mixins/mouseSelect.ts
  packages/editor-ui/src/mixins/moveNodeWorkflow.ts
  packages/editor-ui/src/views/NodeView.vue
Labels: ui, n8n team

#5698 fix(core): Fix calling error workflows in main mode recovery
  packages/cli/src/eventbus/MessageEventBus/recoverEvents.ts
Labels: core, n8n team

#5615 feat(editor): SSO login button
  packages/cli/src/sso/saml/routes/saml.controller.ee.ts
  packages/design-system/src/components/N8nFormBox/FormBox.vue
  packages/editor-ui/src/Interface.ts
  packages/editor-ui/src/api/sso.ts
  packages/editor-ui/src/components/SSOLogin.vue
  packages/editor-ui/src/constants.ts
  packages/editor-ui/src/plugins/i18n/locales/en.json
  packages/editor-ui/src/router.ts
  packages/editor-ui/src/stores/settings.ts
  packages/editor-ui/src/stores/sso.ts
  packages/editor-ui/src/views/AuthView.vue
  packages/editor-ui/src/views/SigninView.vue
Labels: ui, n8n team

#5735 test(Date & Time Node): Skip the test when local timezone is not in UTC (no-changelog)
  packages/nodes-base/nodes/DateTime/test/node/DateTime.test.ts
Labels: node/improvement, n8n team

#5699 fix(core): Improve axios error handling in nodes
  packages/core/package.json
  packages/core/src/NodeExecuteFunctions.ts
  pnpm-lock.yaml
Labels: core, n8n team, skip-e2e

#5729 fix(core): Upgrade convict to address CVE-2023-0163
  packages/cli/package.json
  packages/cli/src/config/index.ts
  pnpm-lock.yaml
Labels: core, n8n team, skip-e2e, security

#5732 fix(core): Upgrade `sqlite3` to address CVE-2022-43441
  packages/cli/package.json
  pnpm-lock.yaml
Labels: core, n8n team, skip-e2e, security

#5730 fix(core): Upgrade `simple-git` to address CVE-2022-25912
  packages/nodes-base/package.json
  pnpm-lock.yaml
Labels: n8n team, skip-e2e, security

#5731 fix(core): Upgrade `luxon` to address CVE-2023-22467
  packages/cli/package.json
  packages/editor-ui/package.json
  packages/nodes-base/package.json
  packages/workflow/package.json
  pnpm-lock.yaml
Labels: core, ui, n8n team, skip-e2e, security

#5740 ci: Fix linting issues on master (no-changelog)
  packages/cli/src/CommunityNodes/helpers.ts
  packages/cli/src/eventbus/MessageEventBusWriter/MessageEventBusLogWriter.ts
  packages/cli/src/sso/saml/middleware/samlEnabledMiddleware.ts
  packages/cli/src/sso/saml/routes/saml.controller.ee.ts
  packages/cli/src/sso/saml/types/requests.ts
  packages/cli/src/sso/saml/views/initSsoRedirect.ts
Labels: core, n8n team, skip-e2e

#5739 fix(editor): Suppress requesting current executions if metadata is used in filter
  packages/editor-ui/src/components/ExecutionFilter.vue
  packages/editor-ui/src/components/ExecutionsList.vue
  packages/editor-ui/src/stores/workflows.ts
Labels: ui, n8n team

#5734 fix(core): Force-upgrade `decode-uri-component` to address CVE-2022-38900
  package.json
  pnpm-lock.yaml
Labels: n8n team, skip-e2e, security

#5733 fix(core): Force-upgrade `http-cache-semantics` to address CVE-2022-25881
  package.json
  pnpm-lock.yaml
Labels: n8n team, skip-e2e, security

#5701 fix(HTTP Request Node): Add streaming to binary response
  packages/nodes-base/nodes/HttpRequest/V3/HttpRequestV3.node.ts
Labels: node/improvement, n8n team

#5555 feat(core): Make OAuth2 error handling consistent with success handling
  packages/cli/package.json
  packages/cli/src/Server.ts
  packages/cli/src/credentials/oauth2Credential.api.ts
  packages/cli/templates/oauth-error-callback.handlebars
  pnpm-lock.yaml
Labels: core, community, skip-e2e

#5742 refactor(core): Stop importing LoggerProxy and createDeferredPromise in nodes-base (no-changelog)
  packages/core/src/NodeExecuteFunctions.ts
  packages/nodes-base/nodes/EmailReadImap/v1/EmailReadImapV1.node.ts
  packages/nodes-base/nodes/EmailReadImap/v2/EmailReadImapV2.node.ts
  packages/nodes-base/nodes/Google/Gmail/GmailTrigger.node.ts
  packages/nodes-base/nodes/RabbitMQ/RabbitMQTrigger.node.ts
  packages/nodes-base/nodes/Salesforce/GenericFunctions.ts
  packages/nodes-base/nodes/Salesforce/Salesforce.node.ts
  packages/workflow/src/DeferredPromise.ts
  packages/workflow/src/Interfaces.ts
Labels: node/improvement, core, n8n team

#5724 feat(Filter Node): New node
  packages/nodes-base/nodes/Filter/Filter.node.json
  packages/nodes-base/nodes/Filter/Filter.node.ts
  packages/nodes-base/nodes/Filter/GenericFunctions.ts
  packages/nodes-base/nodes/Filter/test/Filter.node.test.ts
  packages/nodes-base/nodes/Filter/test/workflow.json
  packages/nodes-base/package.json
Labels: node/new, n8n team

#5751 fix(HTTP Request Node): Fix AWS credentials to automatically deconstruct the url
  packages/nodes-base/credentials/Aws.credentials.ts
Labels: node/improvement, n8n team

#5693 fix: Update Posthog no-capture
  packages/editor-ui/src/components/ExecutionsList.vue
  packages/editor-ui/src/components/InputPanel.vue
  packages/editor-ui/src/components/ParameterInputWrapper.vue
  packages/editor-ui/src/components/ResourceLocator/ResourceLocatorDropdown.vue
  packages/editor-ui/src/components/RunData.vue
  packages/editor-ui/src/components/RunDataHtml.vue
  packages/editor-ui/src/components/RunDataJson.test.ts
  packages/editor-ui/src/components/RunDataJson.vue
  packages/editor-ui/src/components/RunDataSchemaItem.vue
  packages/editor-ui/src/components/RunDataTable.vue
  packages/editor-ui/src/components/VariableSelectorItem.vue
  packages/editor-ui/src/components/__snapshots__/RunDataJson.test.ts.snap
  packages/editor-ui/src/components/__snapshots__/RunDataSchema.test.ts.snap
  packages/editor-ui/src/components/layouts/ResourcesListLayout.vue
Labels: ui, n8n team

#5760 fix(editor): Use credentials when fetching node and credential types
  packages/editor-ui/src/api/credentials.ts
  packages/editor-ui/src/api/nodeTypes.ts
Labels: ui, n8n team

#5752 feat(Google Sheets Node): Implement Resource mapper in Google Sheets node
  packages/cli/src/Server.ts
  packages/cli/src/requests.ts
  packages/core/src/LoadMappingOptions.ts
  packages/core/src/index.ts
  packages/editor-ui/src/Interface.ts
  packages/editor-ui/src/api/nodeTypes.ts
  packages/editor-ui/src/components/ParameterInput.vue
  packages/editor-ui/src/components/ResourceMapper/ResourceMapper.vue
  packages/editor-ui/src/stores/nodeTypes.ts
  packages/nodes-base/nodes/Google/Sheet/GoogleSheets.node.ts
  packages/nodes-base/nodes/Google/Sheet/v2/GoogleSheetsV2.node.ts
  packages/nodes-base/nodes/Google/Sheet/v2/actions/sheet/append.operation.ts
  packages/nodes-base/nodes/Google/Sheet/v2/actions/sheet/appendOrUpdate.operation.ts
  packages/nodes-base/nodes/Google/Sheet/v2/actions/sheet/update.operation.ts
  packages/nodes-base/nodes/Google/Sheet/v2/actions/versionDescription.ts
  packages/nodes-base/nodes/Google/Sheet/v2/helpers/GoogleSheets.utils.ts
  packages/nodes-base/nodes/Google/Sheet/v2/methods/index.ts
  packages/nodes-base/nodes/Google/Sheet/v2/methods/resourceMapping.ts
  packages/workflow/src/Interfaces.ts
Labels: node/improvement, core, ui, n8n team

#5763 docs: Refer to docker.n8n.io/n8nio/n8n for pulling n8n docker images (no-changelog)
  docker/compose/subfolderWithSSL/docker-compose.yml
  docker/compose/withMariaDB/docker-compose.yml
  docker/compose/withPostgres/docker-compose.yml
  docker/compose/withPostgresAndWorker/docker-compose.yml
  docker/images/n8n/README.md
  packages/cli/README.md
Labels: core, n8n team

#5766 fix(core): Initialize queue in the webhook server as well
  packages/cli/src/commands/webhook.ts
Labels: core, n8n team, skip-e2e

#5773 fix(core): Assign properties.success earlier to set executionStatus correctly
  packages/cli/src/InternalHooks.ts
Labels: skip-e2e

#5642 feat: Add test overrides
  packages/editor-ui/src/Interface.ts
  packages/editor-ui/src/constants.ts
  packages/editor-ui/src/stores/posthog.test.ts
  packages/editor-ui/src/stores/posthog.ts
  packages/editor-ui/src/stores/settings.ts
Labels: ui, n8n team

#5778 test(editor): Update Cypress and configure `numTestsKeptInMemory` and `experimentalMemoryManagement` (no-changelog)
  cypress.config.js
  package.json
  pnpm-lock.yaml
Labels: n8n team

#5608 fix(core): Improve community nodes loading
  packages/cli/src/CredentialsHelper.ts
  packages/cli/src/LoadNodesAndCredentials.ts
  packages/cli/src/commands/start.ts
  packages/cli/src/constants.ts
  packages/cli/src/controllers/nodes.controller.ts
  packages/cli/test/integration/nodes.api.test.ts
  packages/nodes-base/.eslintrc.js
  packages/nodes-base/index.js
  packages/nodes-base/package.json
Labels: node/improvement, core, n8n team, skip-e2e

#5771 feat(core): Improve ldap/saml toggle and tests
  packages/cli/src/Ldap/helpers.ts
  packages/cli/src/controllers/auth.controller.ts
  packages/cli/src/sso/saml/samlHelpers.ts
  packages/cli/src/sso/ssoHelpers.ts
  packages/cli/test/integration/ldap/ldap.api.test.ts
  packages/cli/test/integration/saml/saml.api.test.ts
  packages/cli/test/integration/saml/sampleMetadata.ts
  packages/cli/test/integration/shared/types.d.ts
  packages/cli/test/integration/shared/utils.ts
Labels: core, n8n team

#5770 fix(Google Sheets Node): Fix insertOrUpdate cell update with object
  packages/nodes-base/nodes/Google/Sheet/v2/helpers/GoogleSheet.ts
Labels: n8n team, node/issue

#5790 fix(HTTP Request Node): Fix AWS credentials to stop removing url params for STS
  packages/nodes-base/credentials/Aws.credentials.ts
Labels: node/improvement, n8n team

#5776 fix(Google Sheets Node): Unit tests
  packages/nodes-base/nodes/Google/Sheet/test/v2/utils/utils.test.ts
Labels: n8n team, tech debt

#5750 feat: Add Variables UI page and $vars global property
  packages/core/src/NodeExecuteFunctions.ts
  packages/design-system/src/components/N8nDatatable/Datatable.vue
  packages/design-system/src/components/N8nDatatable/__tests__/Datatable.spec.ts
  packages/design-system/src/components/N8nDatatable/__tests__/__snapshots__/Datatable.spec.ts.snap
  packages/design-system/src/plugins/n8nComponents.ts
  packages/design-system/src/types/datatable.ts
  packages/design-system/src/types/index.ts
  packages/editor-ui/package.json
  packages/editor-ui/src/Interface.ts
  packages/editor-ui/src/__tests__/server/endpoints/index.ts
  packages/editor-ui/src/__tests__/server/endpoints/settings.ts
  packages/editor-ui/src/__tests__/server/endpoints/user.ts
  packages/editor-ui/src/__tests__/server/endpoints/variable.ts
  packages/editor-ui/src/__tests__/server/factories/index.ts
  packages/editor-ui/src/__tests__/server/factories/variable.ts
  packages/editor-ui/src/__tests__/server/index.ts
  packages/editor-ui/src/__tests__/server/models/index.ts
  packages/editor-ui/src/__tests__/server/models/variable.ts
  packages/editor-ui/src/__tests__/setup.ts
  packages/editor-ui/src/api/environments.ee.ts
  packages/editor-ui/src/components/CodeEdit.vue
  packages/editor-ui/src/components/CodeNodeEditor/completer.ts
  packages/editor-ui/src/components/CodeNodeEditor/completions/base.completions.ts
  packages/editor-ui/src/components/CodeNodeEditor/completions/variables.completions.ts
  packages/editor-ui/src/components/MainSidebar.vue
  packages/editor-ui/src/components/VariablesRow.vue
  packages/editor-ui/src/components/__tests__/VariablesRow.spec.ts
  packages/editor-ui/src/components/__tests__/__snapshots__/VariablesRow.spec.ts.snap
  packages/editor-ui/src/components/layouts/ResourcesListLayout.vue
  packages/editor-ui/src/composables/index.ts
  packages/editor-ui/src/composables/useCopyToClipboard.ts
  packages/editor-ui/src/composables/useExternalHooks.ts
  packages/editor-ui/src/composables/useI18n.ts
  packages/editor-ui/src/composables/useMessage.ts
  packages/editor-ui/src/composables/useTelemetry.ts
  packages/editor-ui/src/composables/useToast.ts
  packages/editor-ui/src/composables/useUpgradeLink.ts
  packages/editor-ui/src/constants.ts
  packages/editor-ui/src/mixins/workflowHelpers.ts
  packages/editor-ui/src/plugins/codemirror/completions/datatype.completions.ts
  packages/editor-ui/src/plugins/components.ts
  packages/editor-ui/src/plugins/i18n/index.ts
  packages/editor-ui/src/plugins/i18n/locales/en.json
  packages/editor-ui/src/plugins/icons.ts
  packages/editor-ui/src/router.ts
  packages/editor-ui/src/stores/__tests__/environments.spec.ts
  packages/editor-ui/src/stores/__tests__/usage.test.ts
  packages/editor-ui/src/stores/environments.ee.ts
  packages/editor-ui/src/stores/index.ts
  packages/editor-ui/src/stores/ui.ts
  packages/editor-ui/src/views/CredentialsView.vue
  packages/editor-ui/src/views/NodeView.vue
  packages/editor-ui/src/views/VariablesView.vue
  packages/editor-ui/src/views/__tests__/VariablesView.spec.ts
  pnpm-lock.yaml
Labels: ui, n8n team

#5791 feat(ServiceNow Node): Add support for work notes when updating an incident
  packages/nodes-base/nodes/ServiceNow/IncidentDescription.ts
Labels: node/improvement, n8n team

#5772 ci: Improve categorisation of errors in the Test-Workflow
  packages/cli/src/commands/executeBatch.ts
Labels: core, n8n team, skip-e2e

#5797 feat(core): Read ephemeral license from environment and clean up ee flags
  packages/cli/package.json
  packages/cli/src/Ldap/constants.ts
  packages/cli/src/Ldap/helpers.ts
  packages/cli/src/License.ts
  packages/cli/src/Server.ts
  packages/cli/src/UserManagement/UserManagementHelper.ts
  packages/cli/src/api/e2e.api.ts
  packages/cli/src/config/index.ts
  packages/cli/src/config/schema.ts
  packages/cli/src/eventbus/MessageEventBus/MessageEventBusHelper.ts
  packages/cli/src/executions/executionHelpers.ts
  packages/cli/src/sso/saml/constants.ts
  packages/cli/src/sso/saml/samlHelpers.ts
  packages/cli/test/integration/eventbus.test.ts
  packages/cli/test/integration/ldap/ldap.api.test.ts
  packages/cli/test/integration/saml/saml.api.test.ts
  packages/cli/test/integration/shared/utils.ts
  packages/cli/test/integration/workflows.controller.ee.test.ts
Labels: core, n8n team

#5801 fix(core): Update lock file
  pnpm-lock.yaml
Labels: n8n team

#5816 Revert "feat(core): Read ephemeral license from environment and cleanup ee flags (#5797)"
  packages/cli/package.json
  packages/cli/src/Ldap/constants.ts
  packages/cli/src/Ldap/helpers.ts
  packages/cli/src/License.ts
  packages/cli/src/Server.ts
  packages/cli/src/UserManagement/UserManagementHelper.ts
  packages/cli/src/api/e2e.api.ts
  packages/cli/src/config/index.ts
  packages/cli/src/config/schema.ts
  packages/cli/src/eventbus/MessageEventBus/MessageEventBusHelper.ts
  packages/cli/src/executions/executionHelpers.ts
  packages/cli/src/sso/saml/constants.ts
  packages/cli/src/sso/saml/samlHelpers.ts
  packages/cli/test/integration/eventbus.test.ts
  packages/cli/test/integration/ldap/ldap.api.test.ts
  packages/cli/test/integration/saml/saml.api.test.ts
  packages/cli/test/integration/shared/utils.ts
  packages/cli/test/integration/workflows.controller.ee.test.ts
  pnpm-lock.yaml
Labels: core, n8n team, skip-e2e

#5795 refactor(core): Use typedi to manage EventBus singletons (no-changelog)
  packages/cli/src/InternalHooks.ts
  packages/cli/src/Server.ts
  packages/cli/src/WorkflowRunner.ts
  packages/cli/src/api/e2e.api.ts
  packages/cli/src/commands/start.ts
  packages/cli/src/eventbus/MessageEventBus/MessageEventBus.ts
  packages/cli/src/eventbus/MessageEventBus/recoverEvents.ts
  packages/cli/src/eventbus/MessageEventBusWriter/MessageEventBusLogWriter.ts
  packages/cli/src/eventbus/MessageEventBusWriter/MessageEventBusLogWriterWorker.ts
  packages/cli/src/eventbus/eventBus.controller.ts
  packages/cli/src/eventbus/index.ts
  packages/cli/src/push/abstract.push.ts
  packages/cli/test/integration/eventbus.test.ts
  packages/cli/test/integration/shared/utils.ts
  packages/cli/test/unit/ActiveWorkflowRunner.test.ts
Labels: core, n8n team, skip-e2e

#5812 fix(core): Handle Date and RegExp correctly in jsonStringify
  packages/workflow/src/utils.ts
  packages/workflow/test/utils.test.ts
Labels: core, n8n team, skip-e2e

#5809 fix(core): Handle Date and RegExp objects in AugmentObject
  packages/workflow/src/AugmentObject.ts
  packages/workflow/test/AugmentObject.test.ts
Labels: core, n8n team, skip-e2e

#5814 feat(Postgres Node): Add resource mapper to new version of Postgres node
  packages/nodes-base/credentials/Postgres.credentials.ts
  packages/nodes-base/nodes/CrateDb/CrateDb.node.ts
  packages/nodes-base/nodes/Postgres/Postgres.node.ts
  packages/nodes-base/nodes/Postgres/test/v2/operations.test.ts
  packages/nodes-base/nodes/Postgres/test/v2/runQueries.test.ts
  packages/nodes-base/nodes/Postgres/test/v2/utils.test.ts
  packages/nodes-base/nodes/Postgres/v1/PostgresV1.node.ts
  packages/nodes-base/nodes/Postgres/v1/genericFunctions.ts
  packages/nodes-base/nodes/Postgres/v2/PostgresV2.node.ts
  packages/nodes-base/nodes/Postgres/v2/actions/common.descriptions.ts
  packages/nodes-base/nodes/Postgres/v2/actions/database/Database.resource.ts
  packages/nodes-base/nodes/Postgres/v2/actions/database/deleteTable.operation.ts
  packages/nodes-base/nodes/Postgres/v2/actions/database/executeQuery.operation.ts
  packages/nodes-base/nodes/Postgres/v2/actions/database/insert.operation.ts
  packages/nodes-base/nodes/Postgres/v2/actions/database/select.operation.ts
  packages/nodes-base/nodes/Postgres/v2/actions/database/update.operation.ts
  packages/nodes-base/nodes/Postgres/v2/actions/database/upsert.operation.ts
  packages/nodes-base/nodes/Postgres/v2/actions/node.type.ts
  packages/nodes-base/nodes/Postgres/v2/actions/router.ts
  packages/nodes-base/nodes/Postgres/v2/actions/versionDescription.ts
  packages/nodes-base/nodes/Postgres/v2/helpers/interfaces.ts
  packages/nodes-base/nodes/Postgres/v2/helpers/utils.ts
  packages/nodes-base/nodes/Postgres/v2/methods/credentialTest.ts
  packages/nodes-base/nodes/Postgres/v2/methods/index.ts
  packages/nodes-base/nodes/Postgres/v2/methods/listSearch.ts
  packages/nodes-base/nodes/Postgres/v2/methods/loadOptions.ts
  packages/nodes-base/nodes/Postgres/v2/methods/resourceMapping.ts
  packages/nodes-base/nodes/Postgres/v2/transport/index.ts
  packages/nodes-base/nodes/QuestDb/QuestDb.node.ts
  packages/nodes-base/nodes/TimescaleDb/TimescaleDb.node.ts
  packages/nodes-base/test/nodes/Postgres/Postgres.node.functions.test.js
  packages/workflow/src/Interfaces.ts
Labels: node/improvement, node/new, n8n team

#5827 fix(core): Service account private key as a password field
  packages/nodes-base/credentials/GoogleApi.credentials.ts
Labels: node/improvement, n8n team, node/issue

#5811 fix(core): Waiting workflows not stopping
  packages/cli/src/Interfaces.ts
  packages/cli/src/WaitTracker.ts
  packages/cli/src/databases/entities/ExecutionEntity.ts
  packages/workflow/src/Interfaces.ts
Labels: core, n8n team, skip-e2e

#5820 ci: Upgrade pnpm and turborepo (no-changelog)
  .github/workflows/test-workflows.yml
  package.json
  pnpm-lock.yaml
Labels: n8n team, skip-e2e

#5835 ci: Drop support for Node.js 14
  .github/workflows/ci-master.yml
  .github/workflows/e2e-tests.yml
  packages/cli/BREAKING-CHANGES.md
  packages/cli/bin/n8n
  packages/cli/package.json
Labels: core, n8n team, skip-e2e

#5788 feat(core): Prevent non owners password reset when saml is enabled
  packages/cli/src/controllers/passwordReset.controller.ts
  packages/cli/test/integration/passwordReset.api.test.ts
Labels: core, n8n team, skip-e2e

#5834 feat(Schedule Trigger Node): Linking to crontab.guru examples (no-changelog)
  packages/nodes-base/nodes/Schedule/ScheduleTrigger.node.ts
Labels: node/improvement, n8n team

#5817 fix(editor): Fix issue preventing execution preview loading when in an iframe
  packages/editor-ui/src/views/NodeView.vue
Labels: ui, n8n team

#5836 fix(core): Do not user `util.types.isProxy` for tracking of augmented objects
  packages/workflow/src/AugmentObject.ts
Labels: skip-e2e

#5828 fix(editor): Fix connection lost hover text not showing
  packages/editor-ui/src/components/PushConnectionTracker.vue
Labels: ui, n8n team

#5755 feat: Upgrade TypeScript to v5 (no-changelog)
  cypress/tsconfig.json
  package.json
  packages/nodes-base/nodes/Autopilot/GenericFunctions.ts
  packages/nodes-base/nodes/Aws/Rekognition/GenericFunctions.ts
  packages/nodes-base/nodes/Aws/S3/GenericFunctions.ts
  packages/nodes-base/nodes/ClickUp/GenericFunctions.ts
  packages/nodes-base/nodes/Clockify/GenericFunctions.ts
  packages/nodes-base/nodes/GoToWebinar/GenericFunctions.ts
  packages/nodes-base/nodes/HelpScout/GenericFunctions.ts
  packages/nodes-base/nodes/Hubspot/GenericFunctions.ts
  packages/nodes-base/nodes/Microsoft/Teams/GenericFunctions.ts
  packages/nodes-base/nodes/Notion/GenericFunctions.ts
  packages/nodes-base/nodes/Orbit/GenericFunctions.ts
  packages/nodes-base/nodes/S3/GenericFunctions.ts
  packages/nodes-base/nodes/SendGrid/GenericFunctions.ts
  packages/nodes-base/nodes/SentryIo/GenericFunctions.ts
  packages/nodes-base/nodes/Taiga/GenericFunctions.ts
  packages/nodes-base/nodes/Zendesk/GenericFunctions.ts
  packages/workflow/src/Extensions/ArrayExtensions.ts
  packages/workflow/src/Extensions/DateExtensions.ts
  pnpm-lock.yaml
Labels: node/improvement, core, n8n team, skip-e2e

#5818 ci: Run db tests with a table-prefix as well (no-changelog)
  .github/workflows/ci-postgres-mysql.yml
  packages/cli/package.json
  packages/cli/test/integration/shared/testDb.ts
Labels: core, n8n team, skip-e2e

#5840 fix(core): Deactivate active workflows during import
  packages/cli/src/commands/import/workflow.ts
  packages/cli/test/integration/commands/import.cmd.test.ts
  packages/cli/test/integration/commands/importWorkflows/combined/combined.json
  packages/cli/test/integration/commands/importWorkflows/separate/001-activeWorkflow.json
  packages/cli/test/integration/commands/importWorkflows/separate/002-inactiveWorkflow.json
  packages/cli/test/integration/shared/testDb.ts
Labels: core, n8n team

#5837 fix(editor): Fix mapping with special characters
  cypress/e2e/14-mapping.cy.ts
  packages/editor-ui/src/components/ExpressionEditorModal/ExpressionEditorModalOutput.vue
  packages/editor-ui/src/components/InlineExpressionEditor/InlineExpressionEditorOutput.vue
  packages/editor-ui/src/components/__snapshots__/RunDataSchema.test.ts.snap
  packages/editor-ui/src/utils/__tests__/mappingUtils.test.ts
  packages/editor-ui/src/utils/__tests__/typesUtils.test.ts
  packages/editor-ui/src/utils/mappingUtils.ts
Labels: ui, n8n team, skip-e2e

#5813 fix(editor): Show correct status on canceled executions
  packages/editor-ui/src/components/ExecutionFilter.vue
  packages/editor-ui/src/components/ExecutionsList.vue
  packages/editor-ui/src/components/ExecutionsView/ExecutionCard.vue
  packages/editor-ui/src/mixins/executionsHelpers.ts
  packages/editor-ui/src/plugins/i18n/locales/en.json
Labels: ui, n8n team, skip-e2e

#5832 fix(Redis Node): Fix issue with hash set not working as expected
  packages/nodes-base/nodes/Redis/Redis.node.ts
Labels: node/improvement, n8n team

#5841 fix(Date & Time Node): Add info box at top of date and time explaining expressions
  packages/nodes-base/nodes/DateTime/DateTime.node.ts
Labels: node/improvement, n8n team, node/issue

#5845 fix(editor): Support backspacing with modifier key
  packages/editor-ui/src/components/CodeNodeEditor/baseExtensions.ts
Labels: ui, n8n team

#5785 feat(Filter Node): Show discarded items
  packages/editor-ui/src/components/RunData.vue
  packages/editor-ui/src/constants.ts
  packages/nodes-base/nodes/Filter/Filter.node.ts
Labels: node/improvement, n8n team

#5855 feat(editor): Allow `tab` to accept completion
  packages/editor-ui/src/components/ExpressionEditorModal/ExpressionEditorModalInput.vue
  packages/editor-ui/src/components/InlineExpressionEditor/InlineExpressionEditorInput.vue
Labels: ui, n8n team

#5858 fix(editor): Add $if, $min, $max to root expression autocomplete
  packages/editor-ui/src/components/CodeNodeEditor/completions/base.completions.ts
  packages/editor-ui/src/plugins/i18n/index.ts
  packages/editor-ui/src/plugins/i18n/locales/en.json
Labels: ui, n8n team

#5853 fix(editor): Disable password reset on desktop with no user management
  packages/editor-ui/src/views/SigninView.vue
Labels: ui, n8n team

#5838 fix: Add droppable state for booleans when mapping
  cypress/e2e/14-mapping.cy.ts
  packages/editor-ui/src/components/ParameterInput.vue
Labels: ui, n8n team, skip-e2e

#5852 fix(HTML Extract Node): Support for dot notation in JSON property
  packages/nodes-base/nodes/HtmlExtract/HtmlExtract.node.ts
  packages/nodes-base/nodes/HtmlExtract/test/HtmlExtract.node.test.ts
  packages/nodes-base/nodes/HtmlExtract/test/workflow.dotNotation.json
Labels: node/improvement, n8n team, node/issue

#5851 fix(core): Fix curl import error when no data
  packages/cli/src/CurlConverterHelper.ts
Labels: node/improvement, n8n team, node/issue

#5854 fix(HubSpot Trigger Node): Developer API key is required for webhooks
  packages/nodes-base/credentials/HubspotDeveloperApi.credentials.ts
Labels: node/improvement, n8n team, node/issue

#5865 fix(editor): Curb overeager item access linting
  packages/editor-ui/src/components/CodeNodeEditor/linter.ts
Labels: ui, n8n team

#5808 feat(core): Read ephemeral license from environment and clean up ee flags
  packages/cli/package.json
  packages/cli/src/Ldap/constants.ts
  packages/cli/src/Ldap/helpers.ts
  packages/cli/src/License.ts
  packages/cli/src/Server.ts
  packages/cli/src/UserManagement/UserManagementHelper.ts
  packages/cli/src/api/e2e.api.ts
  packages/cli/src/config/index.ts
  packages/cli/src/config/schema.ts
  packages/cli/src/eventbus/MessageEventBus/MessageEventBusHelper.ts
  packages/cli/src/executions/executionHelpers.ts
  packages/cli/src/sso/saml/constants.ts
  packages/cli/src/sso/saml/samlHelpers.ts
  packages/cli/test/integration/eventbus.test.ts
  packages/cli/test/integration/ldap/ldap.api.test.ts
  packages/cli/test/integration/saml/saml.api.test.ts
  packages/cli/test/integration/shared/utils.ts
  packages/cli/test/integration/workflows.controller.ee.test.ts
  pnpm-lock.yaml
Labels: core, n8n team, skip-e2e

#5856 feat(editor): Enable saving workflow when node details view is open
  cypress/e2e/5-ndv.cy.ts
  packages/editor-ui/src/components/NodeDetailsView.vue
  packages/editor-ui/src/plugins/i18n/locales/en.json
  packages/editor-ui/src/views/NodeView.vue
Labels: ui, n8n team

#5864 fix: Fix parameter inputField ref not yet mounted (no-changelog)
  packages/editor-ui/src/components/ParameterInput.vue
Labels: ui, n8n team

#5720 fix(LinkedIn Node): Update the version of the API
  packages/nodes-base/nodes/LinkedIn/GenericFunctions.ts
  packages/nodes-base/nodes/LinkedIn/LinkedIn.node.ts
Labels: node/improvement, n8n team

#5868 refactor: Add lint rule `no-unused-param-in-catch-clause`
  packages/@n8n_io/eslint-config/base.js
  packages/@n8n_io/eslint-config/local-rules.js
  packages/cli/src/CommunityNodes/helpers.ts
  packages/nodes-base/nodes/Github/SearchFunctions.ts
  packages/workflow/src/Extensions/StringExtensions.ts
Labels: node/improvement, core, n8n team

#5869 fix(editor): Fix focused state in Code node editor
  packages/editor-ui/src/components/CodeNodeEditor/theme.ts
Labels: ui, n8n team

#5871 feat(SSH Node): Hide the private key within the ssh credential
  packages/nodes-base/credentials/SshPrivateKey.credentials.ts
Labels: node/improvement, n8n team

#5867 fix(HTTP Request Node): Support for dot notation in JSON body
  packages/nodes-base/nodes/HttpRequest/GenericFunctions.ts
  packages/nodes-base/nodes/HttpRequest/HttpRequest.node.ts
  packages/nodes-base/nodes/HttpRequest/V3/HttpRequestV3.node.ts
  packages/nodes-base/nodes/HttpRequest/test/utils/utils.test.ts
Labels: node/improvement, n8n team, node/issue

#5875 ci: Fix catch clause lint rule
  packages/@n8n_io/eslint-config/local-rules.js
Labels: n8n team
