Repository n8n-io/n8n, pull requests merged in 2023-08, with the labels that each got.

#6808 feat(Facebook Graph API Node): Add support for v16 and v17
  packages/nodes-base/nodes/Facebook/FacebookGraphApi.node.ts
Labels: node/improvement, n8n team

#6709 fix(Postgres Trigger Node): Imposible to cancell execution manually
  packages/nodes-base/nodes/Postgres/PostgresTrigger.functions.ts
  packages/nodes-base/nodes/Postgres/PostgresTrigger.node.ts
Labels: n8n team, node/issue

#6817 ci: Fix lint to fix build (no-changelog)
  packages/nodes-base/nodes/Microsoft/Sql/MicrosoftSql.node.ts
Labels: skip-e2e

#6820 fix: Fix all modal sizes
  packages/design-system/src/css/dialog.scss
  packages/design-system/src/css/mixins/utils.scss
  packages/design-system/src/utils.scss
  packages/editor-ui/src/components/Modal.vue
  packages/editor-ui/src/components/NodeDetailsView.vue
  packages/editor-ui/src/n8n-theme.scss
  packages/editor-ui/src/views/SettingsUsageAndPlan.vue
Labels: ui, n8n team

#6821 fix: Remove tag animation
  packages/editor-ui/src/components/Badge.vue
  packages/editor-ui/src/components/TagsContainer.vue
Labels: ui, n8n team

#6809 fix: Fix RLC and select dropdown styling and functionality (no-changelog)
  packages/design-system/src/css/input.scss
  packages/editor-ui/src/components/ParameterInput.vue
  packages/editor-ui/src/components/ResourceLocator/ResourceLocator.vue
  packages/editor-ui/src/components/ResourceLocator/ResourceLocatorDropdown.vue
Labels: ui, n8n team

#6826 fix: Handle subtitle errors when pasting workflow
  packages/editor-ui/src/mixins/nodeHelpers.ts
Labels: ui, n8n team

#6816 refactor: Consolidate tsconfig and eslintrc files (no-changelog)
  docker/images/n8n-custom/Dockerfile
  jest.config.js
  package.json
  packages/@n8n/client-oauth2/tsconfig.build.json
  packages/cli/jest.config.js
  packages/cli/package.json
  packages/cli/tsconfig.build.json
  packages/cli/tsconfig.json
  packages/core/tsconfig.build.json
  packages/core/tsconfig.json
  packages/design-system/tsconfig.json
  packages/editor-ui/tsconfig.json
  packages/node-dev/tsconfig.json
  packages/nodes-base/jest.config.js
  packages/nodes-base/tsconfig.build.json
  packages/nodes-base/tsconfig.json
  packages/workflow/tsconfig.build.json
  packages/workflow/tsconfig.json
  pnpm-lock.yaml
  tsconfig.backend.json
  tsconfig.build.json
  tsconfig.json
Labels: node/improvement, core, ui, n8n team

#6818 fix(Code Node): Consistent redirection of stdout for JS and Python sandboxes
  packages/nodes-base/nodes/Code/Code.node.ts
  packages/nodes-base/nodes/Code/JavaScriptSandbox.ts
  packages/nodes-base/nodes/Code/PythonSandbox.ts
  packages/nodes-base/nodes/Code/Sandbox.ts
  packages/nodes-base/nodes/Code/test/Code.node.test.ts
Labels: node/improvement, n8n team

#6831 ci: Fix linting (no-changelog)
  package.json
  pnpm-lock.yaml
Labels: n8n team

#6833 fix(editor): Fix redo when adding node on connection
  cypress/e2e/10-undo-redo.cy.ts
  cypress/support/commands.ts
  packages/editor-ui/src/views/NodeView.vue
Labels: ui, n8n team

#6719 feat(core): Make Redis available for backend communication
  packages/cli/package.json
  packages/cli/src/AbstractServer.ts
  packages/cli/src/GenericHelpers.ts
  packages/cli/src/Queue.ts
  packages/cli/src/config/schema.ts
  packages/cli/src/services/cache.service.ts
  packages/cli/src/services/ownership.service.ts
  packages/cli/src/services/redis.service.ts
  packages/cli/src/services/redis/RedisServiceBaseClasses.ts
  packages/cli/src/services/redis/RedisServiceCommands.ts
  packages/cli/src/services/redis/RedisServiceHelper.ts
  packages/cli/src/services/redis/RedisServiceListReceiver.ts
  packages/cli/src/services/redis/RedisServiceListSender.ts
  packages/cli/src/services/redis/RedisServicePubSubPublisher.ts
  packages/cli/src/services/redis/RedisServicePubSubSubscriber.ts
  packages/cli/src/services/redis/RedisServiceStreamConsumer.ts
  packages/cli/src/services/redis/RedisServiceStreamProducer.ts
  packages/cli/test/unit/services/cache.service.test.ts
  packages/cli/test/unit/services/redis.service.test.ts
  pnpm-lock.yaml
Labels: core, n8n team

#6828 fix: Fix saving workflow sharing (no-changelog)
  packages/editor-ui/src/components/WorkflowShareModal.ee.vue
Labels: ui, n8n team

#6832 fix: Fix replacing node empty string value with default value (no-changelog)
  packages/workflow/src/NodeHelpers.ts
Labels: core, n8n team

#6829 fix: Fix double hiring banner logging (no-changelog)
  packages/editor-ui/src/App.vue
Labels: ui, n8n team

#6830 fix: Fix horizontal overflow for dialogs
  packages/design-system/src/css/dialog.scss
Labels: ui, n8n team

#6827 fix(core): Change VariablesService to DI and use caching
  packages/cli/src/WorkflowHelpers.ts
  packages/cli/src/environments/sourceControl/sourceControlExport.service.ee.ts
  packages/cli/src/environments/sourceControl/sourceControlImport.service.ee.ts
  packages/cli/src/environments/variables/variables.controller.ee.ts
  packages/cli/src/environments/variables/variables.controller.ts
  packages/cli/src/environments/variables/variables.service.ee.ts
  packages/cli/src/environments/variables/variables.service.ts
  packages/cli/test/integration/shared/testDb.ts
  packages/cli/test/integration/variables.test.ts
  packages/cli/test/unit/ActiveWorkflowRunner.test.ts
  packages/cli/test/unit/services/cache.service.test.ts
Labels: core, n8n team

#6819 ci: Parallelize `ci-master` (no-changelog)
  .github/workflows/ci-master.yml
Labels: n8n team

#6803 perf(core): Cache roles
  packages/cli/src/Db.ts
  packages/cli/src/InternalHooks.ts
  packages/cli/src/Ldap/helpers.ts
  packages/cli/src/PublicApi/v1/handlers/credentials/credentials.service.ts
  packages/cli/src/PublicApi/v1/handlers/users/users.service.ts
  packages/cli/src/PublicApi/v1/handlers/workflows/workflows.handler.ts
  packages/cli/src/Server.ts
  packages/cli/src/UserManagement/PermissionChecker.ts
  packages/cli/src/UserManagement/UserManagementHelper.ts
  packages/cli/src/WorkflowHelpers.ts
  packages/cli/src/commands/import/credentials.ts
  packages/cli/src/commands/import/workflow.ts
  packages/cli/src/commands/user-management/reset.ts
  packages/cli/src/controllers/e2e.controller.ts
  packages/cli/src/controllers/users.controller.ts
  packages/cli/src/credentials/credentials.service.ee.ts
  packages/cli/src/credentials/credentials.service.ts
  packages/cli/src/databases/entities/Role.ts
  packages/cli/src/databases/repositories/role.repository.ts
  packages/cli/src/environments/sourceControl/sourceControlImport.service.ee.ts
  packages/cli/src/role/role.service.ts
  packages/cli/src/services/ownership.service.ts
  packages/cli/src/services/role.service.ts
  packages/cli/src/sso/saml/samlHelpers.ts
  packages/cli/src/workflows/workflows.controller.ee.ts
  packages/cli/src/workflows/workflows.controller.ts
  packages/cli/src/workflows/workflows.services.ee.ts
  packages/cli/test/integration/shared/random.ts
  packages/cli/test/integration/shared/testDb.ts
  packages/cli/test/integration/shared/utils/testServer.ts
  packages/cli/test/unit/repositories/role.repository.test.ts
  packages/cli/test/unit/services/ownership.service.test.ts
  packages/cli/test/unit/services/role.service.test.ts
Labels: core, n8n team

#6842 fix(core): Fix property existence checks on AugmentObject
  packages/workflow/src/AugmentObject.ts
  packages/workflow/test/AugmentObject.test.ts
Labels: core, n8n team

#6836 fix: Auth.api user limit test expecting incorrect status
  packages/cli/test/integration/auth.api.test.ts
  packages/cli/test/integration/shared/utils/testServer.ts
Labels: core, n8n team, skip-e2e

#6839 fix(core): Fix source control name and email being switched
  packages/cli/src/environments/sourceControl/sourceControlGit.service.ee.ts
Labels: core, community

#6844 fix(core): Update packages to address CVE-2023-2142 and CVE-2020-28469
  packages/cli/package.json
  packages/nodes-base/nodes/MQTT/Mqtt.node.ts
  packages/nodes-base/nodes/MQTT/MqttTrigger.node.ts
  packages/nodes-base/package.json
  pnpm-lock.yaml
Labels: node/improvement, core, n8n team

#6848 fix(editor): Fix value syncing in SQL and HTML editor
  packages/editor-ui/src/components/HtmlEditor/HtmlEditor.vue
  packages/editor-ui/src/components/SqlEditor/SqlEditor.vue
Labels: ui, n8n team

#6825 perf(core): Cache webhooks
  packages/cli/src/ActiveWorkflowRunner.ts
  packages/cli/src/databases/entities/WebhookEntity.ts
  packages/cli/src/services/cache.service.ts
  packages/cli/src/services/webhook.service.ts
  packages/cli/test/unit/ActiveWorkflowRunner.test.ts
  packages/cli/test/unit/services/webhook.service.test.ts
Labels: core, n8n team

#6853 feat(core): Create a dsl for writing db agnostic migrations
  packages/cli/package.json
  packages/cli/src/databases/dsl/Column.ts
  packages/cli/src/databases/dsl/Indices.ts
  packages/cli/src/databases/dsl/Table.ts
  packages/cli/src/databases/dsl/index.ts
  packages/cli/src/databases/types.ts
  packages/cli/src/databases/utils/migrationHelpers.ts
  pnpm-lock.yaml
Labels: core, n8n team

#6847 fix(core): OAuth1 authentication fix for Clever Cloud API
  packages/cli/src/Server.ts
  packages/core/src/NodeExecuteFunctions.ts
Labels: n8n team, node/issue, tech debt

#6854 fix(core): Handle empty keys in cache service (no-changelog)
  packages/cli/src/services/cache.service.ts
  packages/cli/test/unit/services/cache-mock.service.test.ts
  packages/cli/test/unit/services/cache.service.test.ts
Labels: core, n8n team, skip-e2e

#6846 feat(core): Add metrics option to cache
  packages/cli/src/Server.ts
  packages/cli/src/config/schema.ts
  packages/cli/src/eventbus/MessageEventBus/MessageEventBus.ts
  packages/cli/src/eventbus/MessageEventBusDestination/Helpers.ee.ts
  packages/cli/src/eventbus/MessageEventBusDestination/MessageEventBusDestinationFromDb.ts
  packages/cli/src/metrics/index.ts
  packages/cli/src/services/cache.service.ts
  packages/cli/src/services/metrics.service.ts
  packages/cli/test/integration/metrics.test.ts
  packages/cli/test/integration/shared/types.ts
  packages/cli/test/integration/shared/utils/testServer.ts
  packages/cli/test/unit/services/cache.service.test.ts
Labels: core, n8n team

#6855 fix(editor): Avoid infinite loops when resolving the expression `{{ $parameter }}` (no-changelog)
  cypress/e2e/11-inline-expression-editor.cy.ts
  packages/editor-ui/src/mixins/workflowHelpers.ts
  packages/workflow/src/WorkflowDataProxy.ts
Labels: core, ui, n8n team

#6856 fix(Email Trigger (IMAP) Node): UTF-8 attachments are not correctly named
  packages/nodes-base/nodes/EmailReadImap/v2/EmailReadImapV2.node.ts
  packages/nodes-base/package.json
  pnpm-lock.yaml
Labels: n8n team, node/issue, tech debt

#6864 fix(Netlify Node): Update Netlify logo (no-changelog)
  packages/nodes-base/nodes/Netlify/netlify.svg
Labels: node/improvement, n8n team

#6863 feat(core): Add unique id to instances
  packages/cli/package.json
  packages/cli/src/AbstractServer.ts
  packages/cli/src/Interfaces.ts
  packages/cli/src/Server.ts
  packages/cli/src/WebhookServer.ts
  packages/cli/src/commands/webhook.ts
  packages/cli/src/commands/worker.ts
  packages/cli/src/databases/utils/generators.ts
Labels: core, n8n team

#6862 fix(editor): Do not show mapping discoverability tooltip after dismiss
  cypress/e2e/14-mapping.cy.ts
  packages/design-system/src/components/N8nTooltip/Tooltip.stories.ts
  packages/design-system/src/components/N8nTooltip/__tests__/Tooltip.spec.ts
  packages/editor-ui/src/components/ParameterInputFull.vue
Labels: ui, n8n team

#6870 fix: Fix execution card router link (no-changelog)
  packages/editor-ui/src/components/ExecutionsView/ExecutionCard.vue
Labels: ui, n8n team

#6860 refactor(core): Move tag collection into repository (no-changelog)
  packages/cli/src/Db.ts
  packages/cli/src/Interfaces.ts
  packages/cli/src/PublicApi/v1/handlers/workflows/workflows.service.ts
  packages/cli/src/Server.ts
  packages/cli/src/TagHelpers.ts
  packages/cli/src/commands/import/workflow.ts
  packages/cli/src/controllers/tags.controller.ts
  packages/cli/src/environments/sourceControl/sourceControl.service.ee.ts
  packages/cli/src/environments/sourceControl/sourceControlExport.service.ee.ts
  packages/cli/src/environments/sourceControl/sourceControlImport.service.ee.ts
  packages/cli/src/workflows/workflows.controller.ee.ts
  packages/cli/src/workflows/workflows.controller.ts
  packages/cli/test/integration/shared/testDb.ts
  packages/cli/test/integration/shared/utils/testServer.ts
  packages/cli/test/integration/tags.api.test.ts
Labels: core, n8n team

#6872 fix(core): Add sharing data to workflows in EE executions
  packages/cli/src/executions/executions.service.ee.ts
Labels: core, n8n team

#6877 feat(HTTP Request Node): Add cURL alias no-changelog
  packages/nodes-base/nodes/HttpRequest/HttpRequest.node.json
Labels: node/improvement, n8n team

#6865 fix(GoToWebinar Node): Fix issue with timezone incorrectly being required
  packages/nodes-base/nodes/GoToWebinar/descriptions/WebinarDescription.ts
Labels: node/improvement, n8n team

#6873 feat: Clean up onboarding experiment
  packages/editor-ui/src/constants.ts
  packages/editor-ui/src/stores/posthog.store.ts
  packages/editor-ui/src/stores/segment.store.ts
Labels: ui, n8n team

#6875 fix(editor): Fix credential errors in executions view for workflow sharee
  packages/editor-ui/src/mixins/nodeHelpers.ts
  packages/editor-ui/src/views/NodeView.vue
Labels: ui, n8n team

#6876 refactor(core): Adjust index handling in new migrations DSL (no-changelog)
  packages/cli/src/databases/dsl/Indices.ts
  packages/cli/src/databases/dsl/index.ts
  packages/cli/src/databases/migrations/common/1691088862123-CreateWorkflowNameIndex.ts
Labels: core, n8n team

#6879 ci: Upgrade nodelinter to 1.16.0 (no-changelog)
  packages/nodes-base/credentials/CiscoUmbrellaApi.credentials.ts
  packages/nodes-base/credentials/CrowdStrikeOAuth2Api.credentials.ts
  packages/nodes-base/credentials/MetabaseApi.credentials.ts
  packages/nodes-base/credentials/VenafiTlsProtectDatacenterApi.credentials.ts
  packages/nodes-base/credentials/WekanApi.credentials.ts
  packages/nodes-base/nodes/Cisco/Webex/descriptions/MeetingDescription.ts
  packages/nodes-base/nodes/GoToWebinar/descriptions/WebinarDescription.ts
  packages/nodes-base/nodes/Google/GSuiteAdmin/UserDescription.ts
  packages/nodes-base/nodes/Jira/JiraTrigger.node.ts
  packages/nodes-base/nodes/Ldap/Ldap.node.ts
  packages/nodes-base/package.json
  pnpm-lock.yaml
Labels: node/improvement, n8n team

#6887 ci: Fix occasional failure of 19-execution.cy.ts (no-changelog)
  cypress/e2e/19-execution.cy.ts
Labels: n8n team

#6883 feat(Pipedrive Node): Add option to update the file name and description
  packages/nodes-base/nodes/Pipedrive/Pipedrive.node.ts
Labels: node/improvement, community

#6845 perf(core): Add filtering and pagination to `GET /workflows`
  packages/@n8n_io/eslint-config/base.js
  packages/cli/src/ResponseHelper.ts
  packages/cli/src/databases/dsl/Indices.ts
  packages/cli/src/databases/dsl/index.ts
  packages/cli/src/databases/migrations/common/1691088862123-CreateWorkflowNameIndex.ts
  packages/cli/src/databases/migrations/mysqldb/index.ts
  packages/cli/src/databases/migrations/postgresdb/index.ts
  packages/cli/src/databases/migrations/sqlite/index.ts
  packages/cli/src/middlewares/index.ts
  packages/cli/src/middlewares/listQuery/error.ts
  packages/cli/src/middlewares/listQuery/filter.ts
  packages/cli/src/middlewares/listQuery/index.ts
  packages/cli/src/middlewares/listQuery/pagination.ts
  packages/cli/src/middlewares/listQuery/schema.ts
  packages/cli/src/middlewares/listQuery/select.ts
  packages/cli/src/middlewares/listQuery/workflow.schema.ts
  packages/cli/src/requests.ts
  packages/cli/src/services/cache.service.ts
  packages/cli/src/utils.ts
  packages/cli/src/workflows/workflows.controller.ee.ts
  packages/cli/src/workflows/workflows.controller.ts
  packages/cli/src/workflows/workflows.services.ee.ts
  packages/cli/src/workflows/workflows.services.ts
  packages/cli/test/unit/middleware/listQuery.test.ts
Labels: core, n8n team

#6890 fix(core): Log crash causes to console when sentry is disabled
  packages/cli/src/ErrorReporting.ts
  packages/cli/src/config/schema.ts
Labels: core, n8n team

#6824 fix: Fix issue with key based credentials not being read correctly
  packages/nodes-base/nodes/Ftp/Ftp.node.ts
  packages/nodes-base/nodes/Google/GenericFunctions.ts
  packages/nodes-base/nodes/MQTT/Mqtt.node.ts
  packages/nodes-base/nodes/MQTT/MqttTrigger.node.ts
  packages/nodes-base/nodes/MySql/v2/transport/index.ts
  packages/nodes-base/nodes/Postgres/v2/transport/index.ts
  packages/nodes-base/nodes/RabbitMQ/GenericFunctions.ts
  packages/nodes-base/nodes/RabbitMQ/RabbitMQ.node.ts
  packages/nodes-base/nodes/Ssh/Ssh.node.ts
  packages/nodes-base/utils/utilities.ts
Labels: node/improvement, n8n team

#6893 docs: Fix missing and invalid documentation urls for various credentials (no-changelog)
  packages/nodes-base/credentials/AlienVaultApi.credentials.ts
  packages/nodes-base/credentials/Auth0ManagementApi.credentials.ts
  packages/nodes-base/credentials/CiscoMerakiApi.credentials.ts
  packages/nodes-base/credentials/CiscoSecureEndpointApi.credentials.ts
  packages/nodes-base/credentials/CiscoUmbrellaApi.credentials.ts
  packages/nodes-base/credentials/CrowdStrikeOAuth2Api.credentials.ts
  packages/nodes-base/credentials/F5BigIpApi.credentials.ts
  packages/nodes-base/credentials/FortiGateApi.credentials.ts
  packages/nodes-base/credentials/HybridAnalysisApi.credentials.ts
  packages/nodes-base/credentials/ImpervaWafApi.credentials.ts
  packages/nodes-base/credentials/KibanaApi.credentials.ts
  packages/nodes-base/credentials/MicrosoftEntraOAuth2Api.credentials.ts
  packages/nodes-base/credentials/OktaApi.credentials.ts
  packages/nodes-base/credentials/OpenCTIApi.credentials.ts
  packages/nodes-base/credentials/TrellixEpoApi.credentials.ts
  packages/nodes-base/credentials/VirusTotalApi.credentials.ts
  packages/nodes-base/credentials/ZscalerZiaApi.credentials.ts
Labels: node/improvement, n8n team

#6888 feat(core): Debug in Editor flag (no-changelog)
  packages/cli/src/License.ts
  packages/cli/src/Server.ts
  packages/cli/src/constants.ts
  packages/cli/src/controllers/e2e.controller.ts
  packages/cli/src/executions/executionHelpers.ts
  packages/workflow/src/Interfaces.ts
Labels: core, n8n team

#6896 fix: Fix issue with key formatting introduced in 1.2.0
  packages/nodes-base/nodes/MySql/v2/transport/index.ts
  packages/nodes-base/nodes/Postgres/v2/transport/index.ts
  packages/nodes-base/utils/utilities.ts
  pnpm-lock.yaml
Labels: node/improvement, n8n team

#6897 fix(core): Don't let bull override the default redis config
  packages/cli/src/services/redis/RedisServiceHelper.ts
Labels: core, n8n team

#6894 fix: Nodes-base lint fail on first command (no-changelog)
  packages/nodes-base/package.json
Labels: n8n team

#6886 fix(Email Trigger (IMAP) Node): Fix connection issue with unexpected spaces in host
  packages/nodes-base/nodes/EmailReadImap/v1/EmailReadImapV1.node.ts
  packages/nodes-base/nodes/EmailReadImap/v2/EmailReadImapV2.node.ts
Labels: node/improvement, n8n team

#6902 fix(editor): Fix post-migration CSS inconsistencies (no-changelog)
  packages/design-system/src/components/N8nTooltip/Tooltip.vue
  packages/design-system/src/css/index.scss
  packages/design-system/src/css/popper.scss
  packages/design-system/src/css/tooltip.scss
  packages/editor-ui/src/components/NodeExecuteButton.vue
  packages/editor-ui/src/components/NodeSettings.vue
  packages/editor-ui/src/n8n-theme.scss
  packages/editor-ui/src/views/CanvasAddButton.vue
Labels: ui, n8n team

#6901 fix(core): Fix fetching of EE executions
  packages/cli/src/executions/executions.service.ee.ts
Labels: core, n8n team

#6903 fix(editor): Fix multiOptions parameters resetting on initial load
  packages/editor-ui/src/components/NodeSettings.vue
Labels: ui, n8n team

#6904 docs(Code Node): Update description to include Python (no-changelog)
  packages/nodes-base/nodes/Code/Code.node.ts
Labels: node/improvement, community

#5927 refactor(core): Abstract away duplication when finding first pinned trigger (no-changelog)
  packages/cli/src/WorkflowHelpers.ts
  packages/cli/src/WorkflowRunner.ts
  packages/cli/src/WorkflowRunnerProcess.ts
  packages/cli/test/unit/WorkflowHelpers.test.ts
Labels: n8n team, tech debt

#6907 refactor: Enable `cred-class-field-documentation-url-missing` (no-changelog)
  packages/nodes-base/.eslintrc.js
Labels: node/improvement, n8n team

#6911 fix(core): Restore body parsing for all content-types for non webhook routes
  packages/cli/src/AbstractServer.ts
  packages/cli/src/WebhookHelpers.ts
  packages/cli/src/middlewares/bodyParser.ts
  packages/cli/test/integration/shared/utils/testServer.ts
Labels: core, n8n team

#6869 fix(editor): Disable telemetry in dev mode and in E2E tests
  cypress.config.js
  package.json
  packages/editor-ui/index.html
  packages/editor-ui/src/plugins/telemetry/index.ts
  packages/editor-ui/src/plugins/telemetry/telemetry.types.ts
  packages/editor-ui/vite.config.ts
  pnpm-lock.yaml
Labels: ui, n8n team

#6916 fix: Add only necessary information to executions (no-changelog)
  packages/cli/src/Interfaces.ts
  packages/cli/src/executions/executions.service.ee.ts
Labels: core, n8n team

#6921 fix(Respond to Webhook Node): Return headers in response
  packages/cli/src/WebhookHelpers.ts
  packages/cli/test/unit/webhooks.test.ts
Labels: core, n8n team

#6922 fix(editor): Fix event emit on credential sharing
  packages/editor-ui/src/components/CredentialEdit/CredentialEdit.vue
  packages/editor-ui/src/components/CredentialEdit/CredentialSharing.ee.vue
Labels: ui, n8n team

#6923 fix: Prevent workflow breaking when credential type is unknown
  packages/editor-ui/src/components/CredentialCard.vue
  packages/editor-ui/src/components/CredentialEdit/CredentialEdit.vue
  packages/editor-ui/src/components/CredentialsSelect.vue
  packages/editor-ui/src/components/NodeCredentials.vue
  packages/editor-ui/src/components/ScopesNotice.vue
  packages/editor-ui/src/mixins/nodeHelpers.ts
  packages/editor-ui/src/stores/credentials.store.ts
  packages/editor-ui/src/utils/nodeTypesUtils.ts
Labels: ui, n8n team

#6925 fix(HTTP Request Node): Improve error handling for TCP socket errors when `Continue On Fail` is enabled
  packages/cli/src/ErrorReporting.ts
  packages/core/src/NodeExecuteFunctions.ts
Labels: core, n8n team

#6841 feat(core): Descriptive message for common nodeJS errors
  packages/workflow/src/NodeErrors.ts
  packages/workflow/test/NodeErrors.test.ts
Labels: n8n team, tech debt

#3742 feat: Add support for not requiring SMTP auth with user management
  packages/cli/src/UserManagement/UserManagementHelper.ts
  packages/cli/src/UserManagement/email/NodeMailer.ts
Labels: core, community

#6835 fix(editor): Fix n8n reference toggle tracking (no-changelog)
  packages/editor-ui/src/plugins/telemetry/index.ts
Labels: ui, n8n team

#6929 refactor(editor): Cleanup template variant experiment
  packages/editor-ui/src/constants.ts
  packages/editor-ui/src/views/TemplatesSearchView.vue
Labels: ui, n8n team

#6931 fix(editor): Fix code node’s content property to be reactive
  packages/editor-ui/src/components/CodeNodeEditor/CodeNodeEditor.vue
Labels: ui, n8n team

#6933 fix(editor): Fix callout text not showing in action box (no-changelog)
  packages/design-system/src/components/N8nActionBox/ActionBox.vue
Labels: ui, n8n team

#6935 fix(editor): Fix delete variable dialog actions (no-changelog)
  packages/editor-ui/src/composables/useMessage.ts
  packages/editor-ui/src/views/VariablesView.vue
Labels: ui, n8n team

#6849 feat(core): Show a banner when running a non-prod license (no-changelog)
  packages/cli/src/Server.ts
  packages/cli/src/constants.ts
  packages/cli/src/controllers/e2e.controller.ts
  packages/editor-ui/src/__tests__/server/endpoints/settings.ts
  packages/workflow/src/Interfaces.ts
Labels: core, ui, n8n team

#6295 feat: Enable parallel processing on multiple queue nodes
  packages/nodes-base/credentials/Amqp.credentials.ts
  packages/nodes-base/nodes/Amqp/Amqp.node.ts
  packages/nodes-base/nodes/Amqp/AmqpTrigger.node.ts
  packages/nodes-base/nodes/MQTT/MqttTrigger.node.ts
Labels: node/improvement, n8n team

#6672 feat(editor): Ask AI
  cypress/e2e/6-code-node.cy.ts
  cypress/pages/ndv.ts
  packages/cli/src/Server.ts
  packages/cli/src/config/index.ts
  packages/cli/src/config/schema.ts
  packages/design-system/src/components/N8nCircleLoader/CircleLoader.stories.ts
  packages/design-system/src/components/N8nCircleLoader/CircleLoader.vue
  packages/design-system/src/components/N8nCircleLoader/__tests__/CircleLoader.spec.ts
  packages/design-system/src/components/N8nCircleLoader/__tests__/__snapshots__/CircleLoader.spec.ts.snap
  packages/design-system/src/components/N8nCircleLoader/index.ts
  packages/design-system/src/components/index.ts
  packages/design-system/src/plugin.ts
  packages/editor-ui/src/api/ai.ts
  packages/editor-ui/src/components/AskAiModal.vue
  packages/editor-ui/src/components/CodeNodeEditor/AskAI/AskAI.vue
  packages/editor-ui/src/components/CodeNodeEditor/CodeNodeEditor.vue
  packages/editor-ui/src/components/CodeNodeEditor/linter.ts
  packages/editor-ui/src/components/Modals.vue
  packages/editor-ui/src/components/RunDataSchema.vue
  packages/editor-ui/src/composables/__tests__/useDataSchema.test.ts
  packages/editor-ui/src/composables/index.ts
  packages/editor-ui/src/composables/useDataSchema.ts
  packages/editor-ui/src/constants.ts
  packages/editor-ui/src/n8n-theme.scss
  packages/editor-ui/src/plugins/i18n/locales/en.json
  packages/editor-ui/src/plugins/telemetry/index.ts
  packages/editor-ui/src/stores/ui.store.ts
  packages/editor-ui/src/utils/__tests__/typesUtils.test.ts
  packages/editor-ui/src/utils/typesUtils.ts
  packages/workflow/src/Interfaces.ts
Labels: core, ui, n8n team

#6941 fix: Fix lag when node parameters are updated
  packages/editor-ui/src/components/NodeSettings.vue
  packages/editor-ui/src/mixins/nodeHelpers.ts
Labels: ui, n8n team

#6938 fix: Update UI wording (no-changelog)
  packages/editor-ui/src/plugins/i18n/locales/en.json
  packages/editor-ui/src/utils/apiUtils.ts
Labels: ui, n8n team

#6939 fix(core): Fix `continueOnFail` for expression error in Set
  packages/core/src/NodeExecuteFunctions.ts
Labels: core, n8n team

#6934 fix(editor): Prevent Code node linter from erroring on `null` parse
  packages/editor-ui/src/components/CodeNodeEditor/linter.ts
Labels: ui, n8n team

#6946 ci: Fix executeBatch command to fix workflow tests (no-changelog)
  packages/cli/src/commands/executeBatch.ts
Labels: core, n8n team

#6926 refactor(editor): Remove sign-in type from user dropdowns
  packages/design-system/src/components/N8nUserInfo/UserInfo.vue
Labels: ui, n8n team

#6953 fix(editor): Fix formatting on editors (no-changelog)
  packages/editor-ui/src/components/CodeNodeEditor/CodeNodeEditor.vue
  packages/editor-ui/src/components/HtmlEditor/HtmlEditor.vue
Labels: ui, n8n team

#6952 refactor: Remove `prettierPath` config option (no-changelog)
  .vscode/settings.default.json
Labels: n8n team

#6930 fix(editor): Trial banner does not disappear after sign out (no-changelog)
  cypress/e2e/27-opt-in-trial-banner.cy.ts
  cypress/fixtures/Plan_data_opt_in_trial.json
  cypress/pages/bannerStack.ts
  cypress/pages/index.ts
  cypress/pages/sidebar/main-sidebar.ts
  packages/editor-ui/src/App.vue
  packages/editor-ui/src/stores/cloudPlan.store.ts
  packages/editor-ui/src/stores/ui.store.ts
  packages/editor-ui/src/stores/users.store.ts
  packages/editor-ui/src/views/SigninView.vue
Labels: ui, n8n team

#6950 fix(editor): Fix telemetry initialization (no-changelog)
  packages/editor-ui/src/plugins/telemetry/index.ts
Labels: ui, n8n team

#6940 fix(editor): Fix Remove all fields not removing values in resource mapper
  packages/design-system/src/components/N8nActionToggle/ActionToggle.vue
  packages/design-system/src/components/N8nInputLabel/InputLabel.vue
  packages/editor-ui/src/components/ParameterInputWrapper.vue
  packages/editor-ui/src/components/ResourceMapper/MappingFields.vue
  packages/editor-ui/src/components/ResourceMapper/MatchingColumnsSelect.vue
  packages/editor-ui/src/components/ResourceMapper/ResourceMapper.vue
  packages/editor-ui/src/components/__tests__/ResourceMapper.test.ts
  packages/editor-ui/src/components/__tests__/utils/ResourceMapper.utils.ts
Labels: ui, n8n team

#6954 feat(core): Add support for ready hooks, and credentials overwrite endpoint in workers
  packages/cli/src/commands/worker.ts
Labels: core, n8n team

#6958 fix(Salesforce Node): Fix Account update owner operation
  packages/nodes-base/nodes/Salesforce/Salesforce.node.ts
Labels: node/improvement, n8n team

#6915 feat: Remove PostHog event calls
  packages/cli/src/InternalHooks.ts
  packages/cli/src/Server.ts
  packages/cli/src/config/schema.ts
  packages/cli/src/controllers/owner.controller.ts
  packages/cli/src/telemetry/index.ts
  packages/editor-ui/src/Interface.ts
  packages/editor-ui/src/api/users.ts
  packages/editor-ui/src/components/PersonalizationModal.vue
  packages/editor-ui/src/plugins/telemetry/index.ts
  packages/editor-ui/src/stores/posthog.store.ts
  packages/editor-ui/src/stores/users.store.ts
  packages/editor-ui/src/views/TemplatesCollectionView.vue
  packages/editor-ui/src/views/TemplatesWorkflowView.vue
Labels: core, ui, n8n team

#6932 fix(editor): Do not flag dynamic load options issue on expression
  packages/editor-ui/src/components/ParameterInput.vue
Labels: ui, n8n team

#6955 fix(GraphQL Node): Improve error handling
  packages/nodes-base/nodes/GraphQL/GraphQL.node.ts
Labels: node/improvement, n8n team

#6968 fix(editor): Revert Fix telemetry initialization (no-changelog)
  cypress.config.js
  package.json
  packages/editor-ui/index.html
  packages/editor-ui/src/plugins/telemetry/index.ts
  packages/editor-ui/src/plugins/telemetry/telemetry.types.ts
  packages/editor-ui/vite.config.ts
  pnpm-lock.yaml
Labels: ui, n8n team

#6969 fix(core): Replace throw with warning when deactivating a non-active workflow
  packages/cli/src/ActiveWorkflowRunner.ts
  packages/core/src/ActiveWorkflows.ts
Labels: core, n8n team

#6970 fix(Google Sheets Trigger Node): Support sheet names with non-latin characters
  packages/nodes-base/nodes/Google/Sheet/GoogleSheetsTrigger.node.ts
Labels: node/improvement, n8n team

#6960 fix(core): Set up OAuth2 cred test
  packages/cli/src/CredentialsHelper.ts
  packages/cli/src/constants.ts
  packages/cli/src/databases/migrations/common/1659888469333-AddJsonKeyPinData.ts
  packages/cli/src/utils.ts
Labels: core, n8n team

#6962 fix(core): Add recoveryInProgress flag file
  packages/cli/src/eventbus/MessageEventBus/MessageEventBus.ts
  packages/cli/src/eventbus/MessageEventBusWriter/MessageEventBusLogWriter.ts
  packages/cli/src/eventbus/MessageEventBusWriter/MessageEventBusLogWriterWorker.ts
Labels: core, n8n team

#6977 test: Fix license tests when `tenantId` is not default (no-changelog)
  packages/cli/test/unit/License.test.ts
Labels: core, n8n team

#6972 fix(Shopify Node): Fix pagination when using options
  packages/nodes-base/nodes/Shopify/GenericFunctions.ts
Labels: node/improvement, n8n team

#6978 feat(Send Email Node): Add support for sending text and html email simultaneously
  packages/nodes-base/nodes/EmailSend/v2/send.operation.ts
Labels: node/improvement, community

#6981 fix(editor): Fix LDAP view info tip color (no-changelog)
  packages/editor-ui/src/views/SettingsLdapView.vue
Labels: ui, n8n team

#6984 ci: Fix versions of all external Github actions (no-changelog)
  .github/workflows/check-documentation-urls.yml
  .github/workflows/check-pr-title.yml
  .github/workflows/check-tests.yml
  .github/workflows/checklist.yml
  .github/workflows/ci-master.yml
  .github/workflows/ci-postgres-mysql.yml
  .github/workflows/ci-pull-requests.yml
  .github/workflows/docker-base-image.yml
  .github/workflows/docker-images-nightly.yml
  .github/workflows/docker-images.yml
  .github/workflows/e2e-reusable.yml
  .github/workflows/release-create-pr.yml
  .github/workflows/release-publish.yml
  .github/workflows/release-push-to-channel.yml
  .github/workflows/test-workflows.yml
  package.json
Labels: n8n team

#6920 refactor(core): Move remaining tags logic to service (no-changelog)
  packages/cli/src/PublicApi/v1/handlers/workflows/workflows.service.ts
  packages/cli/src/TagHelpers.ts
  packages/cli/src/commands/import/workflow.ts
  packages/cli/src/controllers/tags.controller.ts
  packages/cli/src/environments/sourceControl/sourceControl.service.ee.ts
  packages/cli/src/environments/sourceControl/sourceControlImport.service.ee.ts
  packages/cli/src/services/tag.service.ts
  packages/cli/src/workflows/workflows.controller.ee.ts
  packages/cli/src/workflows/workflows.controller.ts
  packages/cli/src/workflows/workflows.services.ts
Labels: core, n8n team

#6982 fix(editor): Fix parsing for single quoted resolvables
  packages/editor-ui/package.json
  pnpm-lock.yaml
Labels: ui, n8n team

#6892 refactor: Consolidate `WorkflowService.getMany()` (no-changelog)
  packages/cli/src/middlewares/listQuery/dtos/pagination.dto.ts
  packages/cli/src/middlewares/listQuery/dtos/workflow.filter.dto.ts
  packages/cli/src/middlewares/listQuery/dtos/workflow.select.dto.ts
  packages/cli/src/middlewares/listQuery/error.ts
  packages/cli/src/middlewares/listQuery/filter.ts
  packages/cli/src/middlewares/listQuery/pagination.ts
  packages/cli/src/middlewares/listQuery/schema.ts
  packages/cli/src/middlewares/listQuery/select.ts
  packages/cli/src/middlewares/listQuery/workflow.schema.ts
  packages/cli/src/requests.ts
  packages/cli/src/services/ownership.service.ts
  packages/cli/src/workflows/workflows.controller.ee.ts
  packages/cli/src/workflows/workflows.controller.ts
  packages/cli/src/workflows/workflows.services.ee.ts
  packages/cli/src/workflows/workflows.services.ts
  packages/cli/src/workflows/workflows.types.ts
  packages/cli/test/integration/shared/testDb.ts
  packages/cli/test/integration/workflows.controller.ee.test.ts
  packages/cli/test/integration/workflows.controller.test.ts
  packages/cli/test/unit/middleware/listQuery.test.ts
Labels: core, n8n team

#6988 ci: Remove `--report-unused-disable-directives` to speed up CI
  packages/@n8n/client-oauth2/package.json
  packages/cli/package.json
  packages/core/package.json
  packages/design-system/package.json
  packages/editor-ui/package.json
  packages/node-dev/package.json
  packages/nodes-base/package.json
  packages/workflow/package.json
Labels: core, ui, n8n team

#6985 ci: Improve the performance of the `import/no-cycle` linting rule (no-changelog)
  packages/@n8n_io/eslint-config/base.js
Labels: n8n team

#6961 feat(core): Add a warning to error workflows that cannot be started due to permission or settings
  packages/cli/src/WorkflowHelpers.ts
  packages/editor-ui/src/mixins/executionsHelpers.ts
  packages/workflow/src/WorkflowErrors.ts
Labels: core, ui, n8n team

#6910 refactor(core): Move all user DB access to `UserRepository`
  packages/cli/src/Server.ts
  packages/cli/src/UserManagement/PermissionChecker.ts
  packages/cli/src/WorkflowHelpers.ts
  packages/cli/src/controllers/auth.controller.ts
  packages/cli/src/controllers/me.controller.ts
  packages/cli/src/controllers/owner.controller.ts
  packages/cli/src/controllers/passwordReset.controller.ts
  packages/cli/src/controllers/users.controller.ts
  packages/cli/src/credentials/credentials.service.ee.ts
  packages/cli/src/services/events.service.ts
  packages/cli/src/services/ownership.service.ts
  packages/cli/src/services/user.service.ts
  packages/cli/src/user/user.service.ts
  packages/cli/src/workflows/workflows.services.ee.ts
  packages/cli/test/integration/shared/utils/testServer.ts
  packages/cli/test/unit/PermissionChecker.test.ts
  packages/cli/test/unit/controllers/me.controller.test.ts
  packages/cli/test/unit/controllers/owner.controller.test.ts
  packages/cli/test/unit/services/events.service.test.ts
  packages/cli/test/unit/services/ownership.service.test.ts
Labels: core, n8n team

#6976 fix(editor): Ensure community node install button tracks user agreement
  packages/editor-ui/src/components/CommunityPackageInstallModal.vue
  packages/editor-ui/src/components/__tests__/CommunityPackageInstallModal.spec.ts
Labels: ui, n8n team

#6989 fix(Google Sheets Node): Fix short sheet name interpreted as range
  packages/nodes-base/nodes/Google/Sheet/v2/helpers/GoogleSheet.ts
Labels: node/improvement, n8n team

#6991 fix(Mautic Node): Fix issue with owner not being set correctly
  packages/nodes-base/nodes/Mautic/Mautic.node.ts
Labels: node/improvement, n8n team

#6995 feat: Add N8nAddInputEndpoint for JsPlumb setup
  packages/@n8n/nodes-langchain/nodes/LangChain/LangChain.node.ts
  packages/editor-ui/src/components/Node.vue
  packages/editor-ui/src/main.ts
  packages/editor-ui/src/mixins/nodeBase.ts
  packages/editor-ui/src/plugins/jsplumb/N8nAddInputEndpointRenderer.ts
  packages/editor-ui/src/plugins/jsplumb/N8nAddInputEndpointType.ts
  packages/editor-ui/src/plugins/jsplumb/N8nPlusEndpointRenderer.ts
  packages/editor-ui/src/plugins/jsplumb/N8nPlusEndpointType.ts
  packages/editor-ui/src/plugins/jsplumb/index.ts
  packages/editor-ui/src/stores/canvas.store.ts
  packages/editor-ui/src/utils/nodeViewUtils.ts
  packages/editor-ui/src/views/NodeView.vue
Labels: ui, n8n team

#6996 fix(core): Fix `import:workflow` command
  packages/cli/src/commands/import/workflow.ts
Labels: core, n8n team

#6997 fix(Agile CRM Node): Fix issue with company address not working
  packages/nodes-base/nodes/AgileCrm/AgileCrm.node.ts
  packages/nodes-base/nodes/AgileCrm/CompanyDescription.ts
Labels: node/improvement, n8n team

#6928 fix(core): Throw `NodeSSLError` only for nodes that allow ignoring SSL issues
  packages/core/src/NodeExecuteFunctions.ts
Labels: core, n8n team

#7006 fix(core): Fix AddMfaColumns migration for sqlite (no-changelog)
  cypress/e2e/27-two-factor-authentication.cy.ts
  cypress/pages/settings-personal.ts
  cypress/support/commands.ts
  cypress/support/index.ts
  packages/cli/src/databases/migrations/sqlite/1690000000040-AddMfaColumns.ts
  packages/cli/src/databases/migrations/sqlite/index.ts
Labels: core, n8n team

#7002 fix(editor): Fix sending of Ask AI tracking events
  packages/editor-ui/src/components/CodeNodeEditor/AskAI/AskAI.vue
  packages/editor-ui/src/plugins/telemetry/index.ts
Labels: ui, n8n team

#7008 refactor(core): Do not import BaseCommand outside `src/commands` (no-changelog)
  packages/cli/src/commands/BaseCommand.ts
  packages/cli/src/commands/import/credentials.ts
  packages/cli/src/commands/import/workflow.ts
  packages/cli/src/constants.ts
  packages/cli/src/environments/sourceControl/sourceControlImport.service.ee.ts
Labels: core, n8n team

#6834 feat(editor): Debug execution
  cypress/e2e/28-debug.cy.ts
  cypress/pages/index.ts
  cypress/pages/workflow-executions-tab.ts
  packages/editor-ui/src/Interface.ts
  packages/editor-ui/src/__tests__/router.test.ts
  packages/editor-ui/src/components/DebugPaywallModal.vue
  packages/editor-ui/src/components/ExecutionsView/ExecutionPreview.vue
  packages/editor-ui/src/components/ExecutionsView/__tests__/ExecutionPreview.test.ts
  packages/editor-ui/src/components/MainHeader/MainHeader.vue
  packages/editor-ui/src/components/Modals.vue
  packages/editor-ui/src/composables/index.ts
  packages/editor-ui/src/composables/useExecutionDebugging.ts
  packages/editor-ui/src/composables/useMessage.ts
  packages/editor-ui/src/constants.ts
  packages/editor-ui/src/mixins/genericHelpers.ts
  packages/editor-ui/src/plugins/i18n/locales/en.json
  packages/editor-ui/src/router.ts
  packages/editor-ui/src/stores/ui.store.ts
  packages/editor-ui/src/stores/workflows.store.ts
  packages/editor-ui/src/views/NodeView.vue
Labels: ui, n8n team

#7004 feat: AI tool creation UI enhancements
  packages/editor-ui/src/Interface.ts
  packages/editor-ui/src/components/Node.vue
  packages/editor-ui/src/components/Node/NodeCreator/Panel/NodesListPanel.vue
  packages/editor-ui/src/components/Node/NodeCreator/viewsData.ts
  packages/editor-ui/src/constants.ts
  packages/editor-ui/src/mixins/nodeBase.ts
  packages/editor-ui/src/plugins/i18n/locales/en.json
  packages/editor-ui/src/plugins/jsplumb/N8nAddInputEndpointRenderer.ts
  packages/editor-ui/src/plugins/jsplumb/N8nAddInputEndpointType.ts
  packages/editor-ui/src/utils/nodeViewUtils.ts
  packages/editor-ui/src/views/NodeView.vue
Labels: ui, n8n team

#6956 ci: Use an init container to fix mounted-path permissions in docker compose
  docker/compose/subfolderWithSSL/docker-compose.yml
Labels: n8n team

#6986 fix(Webhook Node): Fix URL params for webhooks
  packages/cli/src/ActiveWorkflowRunner.ts
  packages/cli/src/TestWebhooks.ts
  packages/cli/src/WaitingWebhooks.ts
  packages/cli/test/integration/webhooks.api.test.ts
  packages/nodes-base/nodes/Webhook/Webhook.node.ts
Labels: node/improvement, core, n8n team

#6966 feat(Code Node)!: Add a flag to disable forwarding of code logging to stdout
  packages/cli/BREAKING-CHANGES.md
  packages/nodes-base/nodes/Code/Code.node.ts
Labels: node/improvement, n8n team

#7020 fix(Microsoft Excel 365 Node): Support for more extensions in workbook rlc
  packages/nodes-base/nodes/Microsoft/Excel/v2/methods/listSearch.ts
Labels: n8n team, node/issue

#7019 refactor(Item Lists Node): Delete duplicate code for sorting via code (no-changelog)
  packages/nodes-base/nodes/ItemLists/V1/ItemListsV1.node.ts
  packages/nodes-base/nodes/ItemLists/V2/ItemListsV2.node.ts
  packages/nodes-base/nodes/ItemLists/V3/actions/itemList/sort.operation.ts
  packages/nodes-base/nodes/ItemLists/V3/helpers/utils.ts
Labels: node/improvement, n8n team

#7025 refactor: Upgrade to pnpm 8.7 (no-changelog)
  .github/workflows/test-workflows.yml
  CONTRIBUTING.md
  package.json
Labels: n8n team

#6866 fix(core): Setup websocket keep-live messages
  package.json
  packages/cli/src/push/index.ts
  packages/cli/src/push/websocket.push.ts
  patches/@types__ws@8.5.4.patch
  pnpm-lock.yaml
Labels: core, n8n team

#6994 feat(core): Add filtering, selection and pagination to users
  packages/cli/src/Interfaces.ts
  packages/cli/src/UserManagement/UserManagementHelper.ts
  packages/cli/src/controllers/auth.controller.ts
  packages/cli/src/controllers/me.controller.ts
  packages/cli/src/controllers/owner.controller.ts
  packages/cli/src/controllers/users.controller.ts
  packages/cli/src/middlewares/listQuery/dtos/base.filter.dto.ts
  packages/cli/src/middlewares/listQuery/dtos/base.select.dto.ts
  packages/cli/src/middlewares/listQuery/dtos/user.filter.dto.ts
  packages/cli/src/middlewares/listQuery/dtos/user.select.dto.ts
  packages/cli/src/middlewares/listQuery/dtos/workflow.filter.dto.ts
  packages/cli/src/middlewares/listQuery/dtos/workflow.select.dto.ts
  packages/cli/src/middlewares/listQuery/filter.ts
  packages/cli/src/middlewares/listQuery/pagination.ts
  packages/cli/src/middlewares/listQuery/select.ts
  packages/cli/src/requests.ts
  packages/cli/src/services/user.service.ts
  packages/cli/test/integration/ldap/ldap.api.test.ts
  packages/cli/test/integration/shared/testDb.ts
  packages/cli/test/integration/users.api.test.ts
  packages/cli/test/integration/users.controller.test.ts
  packages/cli/test/unit/controllers/me.controller.test.ts
  packages/cli/test/unit/middleware/listQuery.test.ts
Labels: core, n8n team

#7035 refactor: Move node i18n logic to `NodeTypes` (no-changelog)
  packages/cli/src/NodeTypes.ts
  packages/cli/src/TranslationHelpers.ts
  packages/cli/src/controllers/nodeTypes.controller.ts
Labels: core, n8n team

#7034 refactor: Skip resource mapper test causing timeouts (no-changelog)
  packages/editor-ui/src/components/__tests__/ResourceMapper.test.ts
Labels: ui, n8n team

#7038 fix(core): Invalid NODES_INCLUDE should not crash the app
  packages/core/src/DirectoryLoader.ts
Labels: core, n8n team

#7031 feat: Create workflow history database migration
  packages/cli/src/databases/dsl/Column.ts
  packages/cli/src/databases/migrations/common/1692967111175-CreateWorkflowHistoryTable.ts
  packages/cli/src/databases/migrations/mysqldb/index.ts
  packages/cli/src/databases/migrations/postgresdb/index.ts
  packages/cli/src/databases/migrations/sqlite/index.ts
Labels: core, n8n team

#7027 fix(editor): Adjust Ask AI tracking events & pass NDV session id (no-changelog)
  cypress/e2e/6-code-node.cy.ts
  packages/editor-ui/src/api/ai.ts
  packages/editor-ui/src/components/CodeNodeEditor/AskAI/AskAI.vue
  packages/editor-ui/src/components/NodeExecuteButton.vue
  packages/editor-ui/src/plugins/telemetry/index.ts
  packages/editor-ui/src/stores/ndv.store.ts
  packages/editor-ui/src/views/NodeView.vue
Labels: ui, n8n team

#7043 feat(editor): Show AI nodes in a separate view
  packages/@n8n/nodes-langchain/nodes/LangChain/LangChain.node.ts
  packages/@n8n/nodes-langchain/nodes/chains/ChainRetrievalQA/ChainRetrievalQA.node.ts
  packages/@n8n/nodes-langchain/nodes/chains/ChainVectorStoreQA/ChainVectorStoreQA.node.ts
  packages/@n8n/nodes-langchain/nodes/document_loaders/DocumentBinaryInputLoader/DocumentBinaryInputLoader.node.ts
  packages/@n8n/nodes-langchain/nodes/document_loaders/DocumentGithubLoader/DocumentGithubLoader.node.ts
  packages/@n8n/nodes-langchain/nodes/document_loaders/DocumentJSONInputLoader/DocumentJSONInputLoader.node.ts
  packages/@n8n/nodes-langchain/nodes/embeddings/EmbeddingsOpenAI/EmbeddingsOpenAI.node.ts
  packages/@n8n/nodes-langchain/nodes/llms/LMChatOpenAi/LMChatOpenAi.node.ts
  packages/@n8n/nodes-langchain/nodes/llms/LMCohere/LMCohere.node.ts
  packages/@n8n/nodes-langchain/nodes/llms/LMOpenAi/LMOpenAi.node.ts
  packages/@n8n/nodes-langchain/nodes/llms/LMOpenHuggingFaceInference/LMOpenHuggingFaceInference.node.ts
  packages/@n8n/nodes-langchain/nodes/memory/MemoryMotorhead/MemoryMotorhead.node.ts
  packages/@n8n/nodes-langchain/nodes/memory/MemoryXata/MemoryXata.node.ts
  packages/@n8n/nodes-langchain/nodes/retrievers/RetrieverVectorStore/RetrieverVectorStore.node.ts
  packages/@n8n/nodes-langchain/nodes/text_splitters/TextSplitterCharacterTextSplitter/TextSplitterCharacterTextSplitter.node.ts
  packages/@n8n/nodes-langchain/nodes/text_splitters/TextSplitterTokenSplitter/TextSplitterTokenSplitter.node.ts
  packages/@n8n/nodes-langchain/nodes/tools/ToolCalculator/ToolCalculator.node.ts
  packages/@n8n/nodes-langchain/nodes/tools/ToolDynamicTool/ToolDynamicTool.node.ts
  packages/@n8n/nodes-langchain/nodes/tools/ToolSerpApi/ToolSerpApi.node.ts
  packages/@n8n/nodes-langchain/nodes/tools/ToolWikipedia/ToolWikipedia.node.ts
  packages/@n8n/nodes-langchain/nodes/vector_store/InMemoryVectorStore/InMemoryVectorStore.node.ts
  packages/@n8n/nodes-langchain/nodes/vector_store/VectorStorePineconeInsert/VectorStorePineconeInsert.node.ts
  packages/@n8n/nodes-langchain/nodes/vector_store/VectorStorePineconeLoad/VectorStorePineconeLoad.node.ts
  packages/editor-ui/src/components/Node/NodeCreator/Modes/NodesMode.vue
  packages/editor-ui/src/components/Node/NodeCreator/Panel/NodesListPanel.vue
  packages/editor-ui/src/components/Node/NodeCreator/utils.ts
  packages/editor-ui/src/components/Node/NodeCreator/viewsData.ts
  packages/editor-ui/src/constants.ts
  packages/editor-ui/src/plugins/i18n/locales/en.json
  packages/editor-ui/src/plugins/icons/index.ts
Labels: ui, n8n team

#7044 docs(editor): Update docs links for community nodes
  packages/editor-ui/src/constants.ts
  packages/editor-ui/src/views/SettingsCommunityNodesView.vue
Labels: ui, n8n team

#6990 fix(MongoDB Node): Stringify response ObjectIDs
  packages/nodes-base/nodes/MongoDb/GenericFunctions.ts
  packages/nodes-base/nodes/MongoDb/MongoDb.node.ts
  packages/nodes-base/nodes/MongoDb/MongoDbDescription.ts
  packages/nodes-base/nodes/MongoDb/MongoDbProperties.ts
Labels: node/improvement, n8n team

#7018 fix(Code Node): Switch over to vm2 fork
  packages/nodes-base/nodes/Code/JavaScriptSandbox.ts
  packages/nodes-base/nodes/Code/test/Code.node.test.ts
  packages/nodes-base/nodes/Function/Function.node.ts
  packages/nodes-base/nodes/FunctionItem/FunctionItem.node.ts
  packages/nodes-base/nodes/ItemLists/V3/helpers/utils.ts
  packages/nodes-base/package.json
  pnpm-lock.yaml
Labels: node/improvement, n8n team

#7039 feat(RSS Read Node): Add support for self signed certificates
  packages/nodes-base/nodes/RssFeedRead/RssFeedRead.node.ts
Labels: node/improvement, n8n team

#7048 feat(Strapi Node): Add token credentials
  packages/nodes-base/credentials/StrapiTokenApi.credentials.ts
  packages/nodes-base/nodes/Strapi/GenericFunctions.ts
  packages/nodes-base/nodes/Strapi/Strapi.node.ts
  packages/nodes-base/package.json
Labels: node/improvement, n8n team

#6987 fix: Load remote resources even if expressions in non requried parameters resolve
  cypress/e2e/26-resource-locator.cy.ts
  cypress/e2e/28-resource-mapper.cy.ts
  cypress/e2e/5-ndv.cy.ts
  cypress/pages/ndv.ts
  cypress/pages/workflow.ts
  cypress/utils/popper.ts
  packages/cli/src/LoadNodesAndCredentials.ts
  packages/editor-ui/src/components/ParameterInput.vue
  packages/editor-ui/src/components/ParameterIssues.vue
  packages/editor-ui/src/components/ResourceLocator/ResourceLocator.vue
  packages/editor-ui/src/components/ResourceLocator/ResourceLocatorDropdown.vue
  packages/editor-ui/src/components/ResourceMapper/ResourceMapper.vue
  packages/editor-ui/src/components/__tests__/ResourceMapper.test.ts
  packages/editor-ui/src/mixins/workflowHelpers.ts
  packages/nodes-base/nodes/E2eTest/E2eTest.node.json
  packages/nodes-base/nodes/E2eTest/E2eTest.node.ts
  packages/nodes-base/nodes/E2eTest/mock.ts
  packages/nodes-base/package.json
Labels: ui, n8n team
