Repository n8n-io/n8n, pull requests merged in 2023-10, with the labels that each got.

#7305 fix(core): Account for itemless case on restoring binary data ID
  packages/cli/src/executionLifecycleHooks/restoreBinaryDataId.ts
  packages/cli/test/unit/execution.lifecycle.test.ts
Labels: core, n8n team

#7312 fix(editor): Separate cloud endpoint calls
  packages/editor-ui/src/App.vue
  packages/editor-ui/src/stores/__tests__/ui.test.ts
  packages/editor-ui/src/stores/cloudPlan.store.ts
Labels: ui, n8n team

#7321 fix(Acuity Scheduling Trigger Node): Update logo for Acuity Scheduling (no-changelog)
  packages/nodes-base/nodes/AcuityScheduling/acuityScheduling.png
Labels: ui, node/issue

#7317 Debs editing
  packages/@n8n/chat/README.md
  packages/@n8n/nodes-langchain/nodes/chains/ChainRetrievalQA/ChainRetrievalQa.node.ts
  packages/@n8n/nodes-langchain/nodes/code/Code.node.ts
Labels: n8n team

#7322 fix(Jira Software Node): Get all users in dropdown/RLC
  packages/nodes-base/nodes/Jira/GenericFunctions.ts
  packages/nodes-base/nodes/Jira/Jira.node.ts
Labels: node/improvement, n8n team

#7313 fix(Set Node): Do not stringify null and undefined
  packages/nodes-base/nodes/Set/Set.node.ts
  packages/nodes-base/nodes/Set/v2/SetV2.node.ts
  packages/nodes-base/nodes/Set/v2/helpers/utils.ts
  packages/nodes-base/nodes/Set/v2/manual.mode.ts
Labels: n8n team, node/issue

#7183 feat(core): Add "Sent by n8n" attribution
  packages/core/src/NodeExecuteFunctions.ts
  packages/editor-ui/src/constants.ts
  packages/editor-ui/src/plugins/telemetry/index.ts
  packages/nodes-base/nodes/EmailSend/EmailSend.node.ts
  packages/nodes-base/nodes/EmailSend/v2/EmailSendV2.node.ts
  packages/nodes-base/nodes/EmailSend/v2/send.operation.ts
  packages/nodes-base/nodes/Google/Gmail/GenericFunctions.ts
  packages/nodes-base/nodes/Google/Gmail/Gmail.node.ts
  packages/nodes-base/nodes/Google/Gmail/v2/GmailV2.node.ts
  packages/nodes-base/nodes/Google/Gmail/v2/MessageDescription.ts
  packages/nodes-base/nodes/Microsoft/Teams/ChannelMessageDescription.ts
  packages/nodes-base/nodes/Microsoft/Teams/ChatMessageDescription.ts
  packages/nodes-base/nodes/Microsoft/Teams/GenericFunctions.ts
  packages/nodes-base/nodes/Microsoft/Teams/MicrosoftTeams.node.ts
  packages/nodes-base/nodes/Slack/V2/GenericFunctions.ts
  packages/nodes-base/nodes/Slack/V2/MessageDescription.ts
  packages/nodes-base/nodes/Slack/V2/SlackV2.node.ts
  packages/nodes-base/nodes/Telegram/GenericFunctions.ts
  packages/nodes-base/nodes/Telegram/Telegram.node.ts
  packages/workflow/src/Interfaces.ts
Labels: node/improvement, n8n team

#7330 fix(core): Use regular LLM chain if there's no output parser
  packages/@n8n/nodes-langchain/nodes/chains/ChainLLM/ChainLlm.node.ts
  packages/@n8n/nodes-langchain/utils/logWrapper.ts
Labels: n8n team

#7332 docs: Add LangChain section to README
  README.md
Labels: n8n team

#7323 ci: Make builds release-channel aware. Add support for scheduled beta builds
  .github/workflows/docker-image-beta.yml
  .github/workflows/docker-images-nightly.yml
  docker/images/n8n-custom/Dockerfile
  docker/images/n8n/Dockerfile
  packages/cli/src/Server.ts
  packages/cli/src/config/schema.ts
  packages/editor-ui/public/n8n-dev-logo.svg
  packages/editor-ui/public/n8n-nightly-logo.svg
  packages/editor-ui/src/components/Logo.vue
  packages/editor-ui/src/components/MainSidebar.vue
  packages/editor-ui/src/composables/useTitleChange.ts
  packages/editor-ui/src/stores/ui.store.ts
  packages/workflow/src/Interfaces.ts
Labels: core, ui, n8n team

#7339 ci: Remove scheduled build for beta, and fix the inputs (no-changelog)
  .github/workflows/docker-image-beta.yml
  docker/images/n8n-custom/Dockerfile
Labels: n8n team

#7341 fix(editor): Fix rare dragging exception and unify LLM chain outputKey
  packages/@n8n/nodes-langchain/nodes/chains/ChainLLM/ChainLlm.node.ts
  packages/editor-ui/src/components/RunDataJson.vue
  packages/editor-ui/src/components/WorkflowLMChat.vue
  packages/editor-ui/src/views/NodeView.vue
Labels: ui, n8n team

#7298 fix(editor): Display value of selected matching column in RMC
  packages/editor-ui/src/components/ResourceMapper/MatchingColumnsSelect.vue
  packages/editor-ui/src/components/__tests__/ResourceMapper.test.ts
Labels: ui, n8n team

#7315 fix(Typeform Trigger Node): Change output format for TypeForm trigger to object instead of array
  packages/nodes-base/nodes/Typeform/TypeformTrigger.node.ts
Labels: node/improvement, n8n team

#7318 fix(Convert to/from binary data Node): Rename 'Move Binary Data' to 'Convert to/from binary data'
  cypress/e2e/16-webhook-node.cy.ts
  packages/nodes-base/nodes/MoveBinaryData/MoveBinaryData.node.json
  packages/nodes-base/nodes/MoveBinaryData/MoveBinaryData.node.ts
Labels: node/improvement, ui, n8n team

#7340 fix(editor): Disable email confirmation banner for trialing users
  packages/editor-ui/src/plugins/i18n/locales/en.json
  packages/editor-ui/src/stores/__tests__/ui.test.ts
  packages/editor-ui/src/stores/__tests__/utils/cloudStoreUtils.ts
  packages/editor-ui/src/stores/cloudPlan.store.ts
Labels: ui, n8n team

#7314 docs(editor): New Nodes Panel title for triggers
  cypress/e2e/4-node-creator.cy.ts
  packages/editor-ui/src/components/Node/NodeCreator/__tests__/NodesListPanel.test.ts
  packages/editor-ui/src/plugins/i18n/locales/en.json
Labels: ui, n8n team

#7333 fix(core): Fix pruning of non-finished executions
  packages/cli/src/config/schema.ts
  packages/cli/src/constants.ts
  packages/cli/src/databases/repositories/execution.repository.ts
  packages/cli/test/integration/repositories/execution.repository.test.ts
  packages/cli/test/integration/shared/testDb.ts
  packages/cli/test/unit/repositories/execution.repository.test.ts
Labels: core, n8n team

#7295 fix(editor): Fix RLC not loading when an expression can't resolve
  cypress/e2e/26-resource-locator.cy.ts
  packages/editor-ui/src/components/ResourceLocator/ResourceLocator.vue
  packages/editor-ui/src/mixins/workflowHelpers.ts
Labels: ui, n8n team

#7346 fix(editor): Fix canvas endpoint snapping when dragging connection
  packages/editor-ui/src/views/NodeView.vue
Labels: ui, n8n team

#7310 feat(editor): Workflow history [WIP]- Add workflow history opening button to main header component (no-changelog)
  packages/editor-ui/src/__tests__/utils.ts
  packages/editor-ui/src/components/MainHeader/WorkflowDetails.vue
  packages/editor-ui/src/components/WorkflowHistory/WorkflowHistoryContent.vue
  packages/editor-ui/src/components/WorkflowHistory/WorkflowHistoryList.vue
  packages/editor-ui/src/components/WorkflowHistory/WorkflowHistoryListItem.vue
  packages/editor-ui/src/components/WorkflowHistory/__tests__/WorkflowHistoryList.test.ts
  packages/editor-ui/src/components/WorkflowHistory/__tests__/WorkflowHistoryListItem.test.ts
  packages/editor-ui/src/plugins/i18n/locales/en.json
  packages/editor-ui/src/plugins/icons/index.ts
  packages/editor-ui/src/router.ts
  packages/editor-ui/src/stores/__tests__/utils/workflowHistoryTestUtils.ts
  packages/editor-ui/src/stores/__tests__/workflowHistory.store.test.ts
  packages/editor-ui/src/stores/workflowHistory.store.ts
  packages/editor-ui/src/views/WorkflowHistory.vue
  packages/editor-ui/src/views/__tests__/WorkflowHistory.test.ts
Labels: ui, n8n team

#7345 feat: Update chat widget to work without bundler (no-changelog)
  packages/@n8n/chat/README.md
  packages/@n8n/chat/package.json
  packages/@n8n/chat/resources/workflow.json
  packages/@n8n/chat/scripts/postbuild.js
  packages/@n8n/chat/src/components/Chat.vue
  packages/@n8n/chat/src/components/Input.vue
  packages/@n8n/chat/src/components/MessagesList.vue
  packages/@n8n/chat/src/composables/index.ts
  packages/@n8n/chat/src/composables/useChat.ts
  packages/@n8n/chat/src/constants/symbols.ts
  packages/@n8n/chat/src/index.ts
  packages/@n8n/chat/src/plugins/chat.ts
  packages/@n8n/chat/src/plugins/index.ts
  packages/@n8n/chat/src/stores/chat.ts
  packages/@n8n/chat/src/types/chat.ts
  packages/@n8n/chat/src/types/index.ts
  packages/@n8n/chat/vite.config.ts
  packages/editor-ui/src/components/ChatEmbedModal.vue
  pnpm-lock.yaml
Labels: n8n team

#7356 ci: Fix WorkflowHistoryManager tests (no-changelog)
  packages/cli/src/workflows/workflowHistory/workflowHistoryManager.ee.ts
  packages/cli/test/integration/shared/testDb.ts
  packages/cli/test/integration/workflowHistoryManager.test.ts
Labels: core, n8n team

#7238 refactor: Add log messages to debug worker init issues
  packages/cli/src/commands/start.ts
  packages/cli/src/commands/webhook.ts
  packages/cli/src/commands/worker.ts
Labels: core, n8n team

#7351 fix(editor): Use display option's @Version specifier
  packages/editor-ui/src/components/Node/NodeCreator/__tests__/useActionsGeneration.test.ts
  packages/editor-ui/src/components/Node/NodeCreator/composables/useActionsGeneration.ts
  packages/workflow/src/Interfaces.ts
Labels: core, ui, n8n team

#7358 fix(Set Node): Increase search priority
  cypress/e2e/4-node-creator.cy.ts
  packages/nodes-base/nodes/ExecutionData/ExecutionData.node.json
  packages/nodes-base/nodes/Set/Set.node.json
Labels: n8n team, node/issue

#7253 feat(core): Integrate object store as binary data manager
  packages/cli/src/License.ts
  packages/cli/src/Server.ts
  packages/cli/src/WorkflowExecuteAdditionalData.ts
  packages/cli/src/commands/BaseCommand.ts
  packages/cli/src/config/schema.ts
  packages/cli/src/constants.ts
  packages/cli/src/controllers/e2e.controller.ts
  packages/cli/src/executionLifecycleHooks/restoreBinaryDataId.ts
  packages/cli/src/requests.ts
  packages/cli/test/integration/commands/worker.cmd.test.ts
  packages/cli/test/integration/shared/utils/index.ts
  packages/cli/test/unit/execution.lifecycle.test.ts
  packages/core/src/BinaryData/BinaryData.service.ts
  packages/core/src/BinaryData/FileSystem.manager.ts
  packages/core/src/BinaryData/ObjectStore.manager.ts
  packages/core/src/BinaryData/errors.ts
  packages/core/src/BinaryData/types.ts
  packages/core/src/ObjectStore/ObjectStore.service.ee.ts
  packages/core/src/ObjectStore/errors.ts
  packages/core/src/ObjectStore/types.ts
  packages/core/src/ObjectStore/utils.ts
  packages/core/src/index.ts
  packages/core/test/ObjectStore.manager.test.ts
  packages/core/test/ObjectStore.service.test.ts
  packages/core/test/ObjectStore.test.ts
  packages/core/test/utils.ts
  packages/editor-ui/src/stores/workflows.store.ts
  packages/nodes-base/test/nodes/Helpers.ts
Labels: core, ui, n8n team

#7353 feat(editor): Workflow history [WIP]- Improve switching between workflow history and editor (no-changelog)
  packages/editor-ui/src/components/MainHeader/WorkflowDetails.vue
  packages/editor-ui/src/stores/__tests__/utils/workflowHistoryTestUtils.ts
  packages/editor-ui/src/stores/__tests__/workflowHistory.store.test.ts
  packages/editor-ui/src/stores/workflowHistory.store.ts
  packages/editor-ui/src/types/workflowHistory.ts
  packages/editor-ui/src/views/WorkflowHistory.vue
  packages/editor-ui/src/views/__tests__/WorkflowHistory.test.ts
Labels: ui, n8n team

#7355 feat: Improve error msg when attempting to redeem the same activation code multiple times (no-changelog)
  packages/cli/src/license/license.controller.ts
  packages/cli/test/integration/license.api.test.ts
Labels: core, n8n team

#7192 fix: Flaky mfa e2e tests (no-changelog)
  cypress/e2e/27-two-factor-authentication.cy.ts
  cypress/pages/settings-personal.ts
Labels: n8n team

#7316 feat(editor): Support autologin for upgrade path
  packages/editor-ui/src/Interface.ts
  packages/editor-ui/src/api/cloudPlans.ts
  packages/editor-ui/src/components/CredentialEdit/CredentialSharing.ee.vue
  packages/editor-ui/src/components/ExecutionFilter.vue
  packages/editor-ui/src/components/ExecutionsUsage.vue
  packages/editor-ui/src/components/MainHeader/WorkflowDetails.vue
  packages/editor-ui/src/components/WorkflowShareModal.ee.vue
  packages/editor-ui/src/components/banners/TrialBanner.vue
  packages/editor-ui/src/components/banners/TrialOverBanner.vue
  packages/editor-ui/src/composables/useExecutionDebugging.ts
  packages/editor-ui/src/plugins/i18n/locales/en.json
  packages/editor-ui/src/stores/__tests__/ui.test.ts
  packages/editor-ui/src/stores/cloudPlan.store.ts
  packages/editor-ui/src/stores/ui.store.ts
  packages/editor-ui/src/views/SettingsApiView.vue
  packages/editor-ui/src/views/SettingsAuditLogs.vue
  packages/editor-ui/src/views/SettingsCommunityNodesView.vue
  packages/editor-ui/src/views/SettingsExternalSecrets.vue
  packages/editor-ui/src/views/SettingsLdapView.vue
  packages/editor-ui/src/views/SettingsLogStreamingView.vue
  packages/editor-ui/src/views/SettingsSourceControl.vue
  packages/editor-ui/src/views/SettingsSso.vue
  packages/editor-ui/src/views/SettingsUsageAndPlan.vue
  packages/editor-ui/src/views/SettingsUsersView.vue
  packages/editor-ui/src/views/VariablesView.vue
  packages/editor-ui/src/views/WorkflowHistory.vue
Labels: ui, n8n team

#7354 fix(Google BigQuery Node): Location default to jobReference
  packages/nodes-base/nodes/Google/BigQuery/v2/actions/database/executeQuery.operation.ts
  packages/nodes-base/nodes/Google/BigQuery/v2/helpers/interfaces.ts
Labels: n8n team, node/issue

#7304 feat(Notion Node): Fetch child blocks recursively
  packages/nodes-base/nodes/Notion/BlockDescription.ts
  packages/nodes-base/nodes/Notion/GenericFunctions.ts
  packages/nodes-base/nodes/Notion/v2/NotionV2.node.ts
Labels: node/improvement, n8n team

#7303 refactor(core): Have one orchestration service per instance type
  packages/cli/src/AbstractServer.ts
  packages/cli/src/ExternalSecrets/ExternalSecretsManager.ee.ts
  packages/cli/src/commands/start.ts
  packages/cli/src/commands/webhook.ts
  packages/cli/src/commands/worker.ts
  packages/cli/src/controllers/orchestration.controller.ts
  packages/cli/src/eventbus/MessageEventBus/MessageEventBus.ts
  packages/cli/src/services/orchestration.base.service.ts
  packages/cli/src/services/orchestration.handler.base.service.ts
  packages/cli/src/services/orchestration.handler.service.ts
  packages/cli/src/services/orchestration.service.ts
  packages/cli/src/services/orchestration/helpers.ts
  packages/cli/src/services/orchestration/main/handleCommandMessageMain.ts
  packages/cli/src/services/orchestration/main/handleWorkerResponseMessageMain.ts
  packages/cli/src/services/orchestration/main/orchestration.handler.main.service.ts
  packages/cli/src/services/orchestration/main/orchestration.main.service.ts
  packages/cli/src/services/orchestration/webhook/handleCommandMessageWebhook.ts
  packages/cli/src/services/orchestration/webhook/orchestration.handler.webhook.service.ts
  packages/cli/src/services/orchestration/webhook/orchestration.webhook.service.ts
  packages/cli/src/services/orchestration/worker/handleCommandMessageWorker.ts
  packages/cli/src/services/orchestration/worker/orchestration.handler.worker.service.ts
  packages/cli/src/services/orchestration/worker/orchestration.worker.service.ts
  packages/cli/test/integration/commands/worker.cmd.test.ts
  packages/cli/test/integration/eventbus.ee.test.ts
  packages/cli/test/unit/services/orchestration.service.test.ts
Labels: core, n8n team, skip-e2e

#7228 feat(Loop Over Items (Split in Batches) Node): Automatically add a loop + rename
  cypress/e2e/29-sql-editor.cy.ts
  cypress/e2e/4-node-creator.cy.ts
  packages/editor-ui/src/Interface.ts
  packages/editor-ui/src/components/Node/NodeCreation.vue
  packages/editor-ui/src/components/Node/NodeCreator/ItemTypes/ActionItem.vue
  packages/editor-ui/src/components/Node/NodeCreator/ItemTypes/NodeItem.vue
  packages/editor-ui/src/components/Node/NodeCreator/Modes/ActionsMode.vue
  packages/editor-ui/src/components/Node/NodeCreator/Modes/NodesMode.vue
  packages/editor-ui/src/components/Node/NodeCreator/NodeCreator.vue
  packages/editor-ui/src/components/Node/NodeCreator/__tests__/useActions.test.ts
  packages/editor-ui/src/components/Node/NodeCreator/composables/useActions.ts
  packages/editor-ui/src/constants.ts
  packages/editor-ui/src/plugins/i18n/locales/en.json
  packages/editor-ui/src/views/NodeView.vue
  packages/nodes-base/nodes/SplitInBatches/SplitInBatches.node.json
  packages/nodes-base/nodes/SplitInBatches/SplitInBatches.node.ts
  packages/nodes-base/nodes/SplitInBatches/v3/SplitInBatchesV3.node.ts
  turbo.json
Labels: node/improvement, node/new, ui, n8n team

#7366 fix(core): Prevent object deletion request on no prefix match
  packages/core/src/ObjectStore/ObjectStore.service.ee.ts
  packages/core/test/ObjectStore.service.test.ts
Labels: core, n8n team

#7363 refactor(core): Create controller for binary data (no-changelog)
  packages/cli/src/ResponseHelper.ts
  packages/cli/src/Server.ts
  packages/cli/src/controllers/binaryData.controller.ts
  packages/cli/test/integration/binaryData.api.test.ts
  packages/cli/test/integration/shared/types.ts
  packages/cli/test/integration/shared/utils/testServer.ts
  packages/core/src/BinaryData/utils.ts
  packages/core/src/index.ts
  packages/editor-ui/src/stores/workflows.store.ts
Labels: core, ui, n8n team

#7299 refactor(core): Move `copyInputItems` to node helpers (no-changelog)
  packages/core/src/NodeExecuteFunctions.ts
  packages/core/test/NodeExecuteFunctions.test.ts
  packages/nodes-base/nodes/MySql/v1/GenericFunctions.ts
  packages/nodes-base/nodes/MySql/v1/MySqlV1.node.ts
  packages/nodes-base/nodes/MySql/v2/actions/database/insert.operation.ts
  packages/nodes-base/nodes/MySql/v2/helpers/utils.ts
  packages/nodes-base/nodes/Snowflake/GenericFunctions.ts
  packages/nodes-base/nodes/Snowflake/Snowflake.node.ts
  packages/workflow/src/Interfaces.ts
Labels: node/improvement, core, n8n team

#7289 feat(Execute Workflow Node): Run once for each item mode
  packages/nodes-base/nodes/ExecuteWorkflow/ExecuteWorkflow.node.ts
  packages/nodes-base/nodes/ExecuteWorkflow/GenericFunctions.ts
  packages/nodes-base/utils/utilities.ts
Labels: node/improvement, n8n team, node/issue

#7360 feat(core): Add Job Summary to Worker response
  packages/cli/src/commands/worker.ts
  packages/cli/src/services/orchestration.handler.base.service.ts
  packages/cli/src/services/orchestration/helpers.ts
  packages/cli/src/services/orchestration/main/handleWorkerResponseMessageMain.ts
  packages/cli/src/services/orchestration/worker/handleCommandMessageWorker.ts
  packages/cli/src/services/orchestration/worker/orchestration.handler.worker.service.ts
  packages/cli/src/services/orchestration/worker/types.ts
  packages/cli/src/services/redis/RedisServiceCommands.ts
Labels: core, n8n team

#7369 fix(Google Drive Trigger Node): Add Shared Drives support
  packages/nodes-base/nodes/Google/Drive/GoogleDriveTrigger.node.ts
Labels: node/improvement, n8n team

#7362 refactor(core): Refactor InMemory Vector Store to support Inser & Load
  packages/@n8n/nodes-langchain/nodes/memory/MemoryBufferWindow/MemoryBufferWindow.node.ts
  packages/@n8n/nodes-langchain/nodes/vector_store/VectorStoreInMemoryInsert/VectorStoreInMemoryInsert.node.ts
  packages/@n8n/nodes-langchain/nodes/vector_store/VectorStoreInMemoryLoad/VectorStoreInMemoryLoad.node.ts
  packages/@n8n/nodes-langchain/nodes/vector_store/VectorStorePineconeInsert/VectorStorePineconeInsert.node.ts
  packages/@n8n/nodes-langchain/nodes/vector_store/VectorStoreSupabaseInsert/VectorStoreSupabaseInsert.node.ts
  packages/@n8n/nodes-langchain/nodes/vector_store/VectorStoreZepInsert/VectorStoreZepInsert.node.ts
  packages/@n8n/nodes-langchain/nodes/vector_store/shared/MemoryVectorStoreManager.ts
  packages/@n8n/nodes-langchain/nodes/vector_store/shared/processDocuments.ts
  packages/@n8n/nodes-langchain/package.json
Labels: n8n team

#7372 fix(editor): Remove excess margin below run data editor
  packages/editor-ui/src/components/RunData.vue
Labels: ui, n8n team

#7374 fix: Add role check for upgrade path
  packages/editor-ui/src/api/cloudPlans.ts
  packages/editor-ui/src/stores/__tests__/ui.test.ts
  packages/editor-ui/src/stores/ui.store.ts
Labels: ui, n8n team

#7359 feat(editor): Workflow history [WIP]- Add restore and clone into new workflow actions (no-changelog)
  packages/editor-ui/src/components/Modals.vue
  packages/editor-ui/src/components/WorkflowHistory/WorkflowHistoryList.vue
  packages/editor-ui/src/components/WorkflowHistory/WorkflowHistoryListItem.vue
  packages/editor-ui/src/components/WorkflowHistory/WorkflowHistoryVersionRestoreModal.vue
  packages/editor-ui/src/components/WorkflowHistory/__tests__/WorkflowHistoryList.test.ts
  packages/editor-ui/src/components/WorkflowHistory/__tests__/WorkflowHistoryListItem.test.ts
  packages/editor-ui/src/constants.ts
  packages/editor-ui/src/plugins/i18n/locales/en.json
  packages/editor-ui/src/stores/ui.store.ts
  packages/editor-ui/src/stores/workflowHistory.store.ts
  packages/editor-ui/src/views/WorkflowHistory.vue
Labels: ui, n8n team

#6889 fix(core): Add an option to enable postgres ssl with default certs
  packages/cli/src/Db.ts
  packages/cli/src/config/schema.ts
Labels: core, n8n team

#7383 fix(Notion Node): Handle empty values correctly for Notion selects + multi selects
  packages/nodes-base/nodes/Notion/GenericFunctions.ts
Labels: node/improvement, n8n team

#7382 fix(editor): Fix completions for `.json` on quoted node name in Code node
  packages/editor-ui/src/components/CodeNodeEditor/completions/jsonField.completions.ts
Labels: ui, n8n team

#7307 feat(core): Switch binary filesystem mode to nested path structure
  packages/cli/src/executionLifecycleHooks/restoreBinaryDataId.ts
  packages/cli/src/workflows/workflows.services.ts
  packages/cli/test/unit/execution.lifecycle.test.ts
  packages/core/src/BinaryData/BinaryData.service.ts
  packages/core/src/BinaryData/FileSystem.manager.ts
  packages/core/src/BinaryData/errors.ts
  packages/core/src/BinaryData/types.ts
  packages/core/src/BinaryData/utils.ts
  packages/core/src/index.ts
  packages/core/test/FileSystem.manager.test.ts
  packages/core/test/NodeExecuteFunctions.test.ts
  packages/core/test/ObjectStore.manager.test.ts
  packages/core/test/utils.ts
Labels: core, n8n team

#7376 fix(editor): Implement canvas zoom UX improvements
  cypress/e2e/12-canvas.cy.ts
  cypress/pages/workflow.ts
  packages/editor-ui/package.json
  packages/editor-ui/src/Interface.ts
  packages/editor-ui/src/composables/useCanvasMouseSelect.ts
  packages/editor-ui/src/declarations/normalize-wheel.d.ts
  packages/editor-ui/src/stores/canvas.store.ts
  packages/editor-ui/src/utils/canvasUtils.ts
  packages/editor-ui/vite.config.ts
  pnpm-lock.yaml
Labels: ui, n8n team

#7388 ci: Identify NPM releases as `stable` (no-changelog)
  .github/workflows/release-publish.yml
Labels: n8n team

#7393 refactor: Upgrade to pnpm 8.9 (no-changelog)
  .github/workflows/test-workflows.yml
  CONTRIBUTING.md
  package.json
Labels: n8n team

#7392 fix(editor): Make workflow history button available only for dev builds
  packages/editor-ui/src/components/MainHeader/WorkflowDetails.vue
  packages/editor-ui/src/stores/settings.store.ts
Labels: ui, n8n team

#7385 fix(Webhook Node): Backward compatible form-data parsing for non-array files
  packages/cli/src/WebhookHelpers.ts
  packages/cli/test/integration/webhooks.api.test.ts
Labels: core, n8n team

#7395 fix(core): Fetch Ollama models dynamically
  packages/@n8n/nodes-langchain/nodes/llms/LMChatOllama/LmChatOllama.node.ts
  packages/@n8n/nodes-langchain/nodes/llms/LMOllama/LmOllama.node.ts
Labels: n8n team

#7326 fix(core): Missing pairing info
  packages/nodes-base/nodes/Airtable/test/v2/node/base/getMany.test.ts
  packages/nodes-base/nodes/Airtable/test/v2/node/helpers.ts
  packages/nodes-base/nodes/Airtable/test/v2/node/record/search.test.ts
  packages/nodes-base/nodes/Airtable/v1/AirtableV1.node.ts
  packages/nodes-base/nodes/Airtable/v2/actions/base/getMany.operation.ts
  packages/nodes-base/nodes/Airtable/v2/actions/record/search.operation.ts
  packages/nodes-base/nodes/CompareDatasets/GenericFunctions.ts
  packages/nodes-base/nodes/Filter/Filter.node.ts
  packages/nodes-base/nodes/Google/BigQuery/v1/GoogleBigQueryV1.node.ts
  packages/nodes-base/nodes/Google/BigQuery/v2/actions/database/insert.operation.ts
  packages/nodes-base/nodes/Google/Firebase/CloudFirestore/GoogleFirebaseCloudFirestore.node.ts
  packages/nodes-base/nodes/Google/Sheet/v1/GoogleSheetsV1.node.ts
  packages/nodes-base/nodes/Google/Sheet/v2/actions/sheet/append.operation.ts
  packages/nodes-base/nodes/Google/Sheet/v2/actions/sheet/appendOrUpdate.operation.ts
  packages/nodes-base/nodes/Google/Sheet/v2/actions/sheet/create.operation.ts
  packages/nodes-base/nodes/Google/Sheet/v2/actions/sheet/delete.operation.ts
  packages/nodes-base/nodes/Google/Sheet/v2/actions/sheet/read.operation.ts
  packages/nodes-base/nodes/Google/Sheet/v2/actions/sheet/remove.operation.ts
  packages/nodes-base/nodes/Google/Sheet/v2/actions/sheet/update.operation.ts
  packages/nodes-base/nodes/Google/Sheet/v2/actions/spreadsheet/create.operation.ts
  packages/nodes-base/nodes/Google/Sheet/v2/actions/spreadsheet/delete.operation.ts
  packages/nodes-base/nodes/Hubspot/V2/HubspotV2.node.ts
  packages/nodes-base/nodes/If/If.node.ts
  packages/nodes-base/nodes/Kafka/Kafka.node.ts
  packages/nodes-base/nodes/Merge/v2/GenericFunctions.ts
  packages/nodes-base/nodes/Microsoft/Excel/test/v2/utils/utils.test.ts
  packages/nodes-base/nodes/Microsoft/Excel/v1/MicrosoftExcelV1.node.ts
  packages/nodes-base/nodes/Microsoft/Excel/v2/actions/table/append.operation.ts
  packages/nodes-base/nodes/Microsoft/Excel/v2/actions/worksheet/update.operation.ts
  packages/nodes-base/nodes/Microsoft/Excel/v2/actions/worksheet/upsert.operation.ts
  packages/nodes-base/nodes/Microsoft/Excel/v2/helpers/utils.ts
  packages/nodes-base/nodes/Microsoft/Sql/MicrosoftSql.node.ts
  packages/nodes-base/nodes/MongoDb/MongoDb.node.ts
  packages/nodes-base/nodes/MySql/test/v2/operations.test.ts
  packages/nodes-base/nodes/MySql/test/v2/runQueries.test.ts
  packages/nodes-base/nodes/MySql/v2/helpers/utils.ts
  packages/nodes-base/nodes/NextCloud/NextCloud.node.ts
  packages/nodes-base/nodes/Pipedrive/Pipedrive.node.ts
  packages/nodes-base/nodes/Postgres/test/v2/runQueries.test.ts
  packages/nodes-base/nodes/Postgres/v2/helpers/utils.ts
  packages/nodes-base/nodes/QuickBase/QuickBase.node.ts
  packages/nodes-base/nodes/ReadBinaryFiles/ReadBinaryFiles.node.ts
  packages/nodes-base/nodes/RssFeedRead/RssFeedRead.node.ts
  packages/nodes-base/nodes/Set/v1/SetV1.node.ts
  packages/nodes-base/nodes/Set/v2/helpers/utils.ts
  packages/nodes-base/nodes/Set/v2/manual.mode.ts
  packages/nodes-base/nodes/Set/v2/raw.mode.ts
  packages/nodes-base/nodes/SpreadsheetFile/v1/SpreadsheetFileV1.node.ts
  packages/nodes-base/nodes/SpreadsheetFile/v2/SpreadsheetFileV2.node.ts
  packages/nodes-base/nodes/Stackby/Stackby.node.ts
  packages/nodes-base/nodes/Wekan/Wekan.node.ts
  packages/nodes-base/utils/utilities.ts
Labels: n8n team, node/issue

#7297 feat(Item Lists Node): Split merge binary data
  packages/nodes-base/nodes/ItemLists/V3/actions/itemList/concatenateItems.operation.ts
  packages/nodes-base/nodes/ItemLists/V3/actions/itemList/splitOutItems.operation.ts
  packages/nodes-base/nodes/ItemLists/V3/helpers/utils.ts
Labels: node/improvement, n8n team

#7378 feat(editor): Workflow history [WIP]- Create workflow history item preview component (no-changelog)
  packages/design-system/src/components/N8nActionDropdown/ActionDropdown.vue
  packages/design-system/src/components/N8nActionToggle/ActionToggle.vue
  packages/editor-ui/src/components/MainHeader/WorkflowDetails.vue
  packages/editor-ui/src/components/WorkflowHistory/WorkflowHistoryContent.vue
  packages/editor-ui/src/components/WorkflowHistory/WorkflowHistoryList.vue
  packages/editor-ui/src/components/WorkflowHistory/WorkflowHistoryListItem.vue
  packages/editor-ui/src/components/WorkflowHistory/__tests__/WorkflowHistoryContent.test.ts
  packages/editor-ui/src/components/WorkflowHistory/__tests__/WorkflowHistoryList.test.ts
  packages/editor-ui/src/components/WorkflowHistory/__tests__/WorkflowHistoryListItem.test.ts
  packages/editor-ui/src/components/WorkflowPreview.vue
  packages/editor-ui/src/plugins/i18n/locales/en.json
  packages/editor-ui/src/stores/workflowHistory.store.ts
  packages/editor-ui/src/views/WorkflowHistory.vue
  packages/editor-ui/src/views/__tests__/WorkflowHistory.test.ts
Labels: ui, n8n team

#7399 fix(core): Fix error on missing paired item data
  packages/workflow/src/WorkflowDataProxy.ts
Labels: core, n8n team

#7403 ci: Enable ARM64 builds for beta images (no-changelog)
  .github/workflows/docker-image-beta.yml
Labels: n8n team

#7368 fix(core): Fix ignoring crashed executions without event msgs
  packages/cli/src/eventbus/MessageEventBus/MessageEventBus.ts
  packages/cli/src/eventbus/MessageEventBus/recoverEvents.ts
  packages/cli/test/integration/eventbus.ee.test.ts
Labels: core, n8n team, skip-e2e

#7396 refactor(core): Move frontend settings to service (no-changelog)
  packages/cli/src/Server.ts
  packages/cli/src/services/frontend.service.ts
Labels: core, n8n team

#7417 fix(core): Pg-promise de-initialization fix
  packages/nodes-base/nodes/CrateDb/CrateDb.node.ts
  packages/nodes-base/nodes/Microsoft/Sql/MicrosoftSql.node.ts
  packages/nodes-base/nodes/Postgres/PostgresTrigger.functions.ts
  packages/nodes-base/nodes/Postgres/PostgresTrigger.node.ts
  packages/nodes-base/nodes/Postgres/v1/PostgresV1.node.ts
  packages/nodes-base/nodes/QuestDb/QuestDb.node.ts
  packages/nodes-base/nodes/TimescaleDb/TimescaleDb.node.ts
Labels: n8n team, node/issue

#7320 fix(editor): Fix remote options fetching on every keystroke
  cypress/e2e/26-resource-locator.cy.ts
  cypress/e2e/28-resource-mapper.cy.ts
  cypress/e2e/5-ndv.cy.ts
  cypress/pages/ndv.ts
  packages/editor-ui/src/components/ParameterInput.vue
Labels: ui, n8n team

#7419 fix: Prevent undefined issues when restoring binary data
  packages/cli/src/executionLifecycleHooks/restoreBinaryDataId.ts
  packages/cli/test/unit/execution.lifecycle.test.ts
Labels: core, n8n team

#7416 fix(Set Node): Null should not throw an error
  packages/nodes-base/nodes/Set/Set.node.ts
  packages/nodes-base/nodes/Set/test/Set.workflow.null_values.json
  packages/nodes-base/nodes/Set/v2/SetV2.node.ts
  packages/nodes-base/nodes/Set/v2/helpers/utils.ts
  packages/nodes-base/nodes/Set/v2/manual.mode.ts
Labels: n8n team, node/issue

#7424 fix(core): Fix expression with paired item with multi-input node
  cypress/e2e/24-ndv-paired-item.cy.ts
  cypress/fixtures/expression_with_paired_item_in_multi_input_node.json
  packages/workflow/src/WorkflowDataProxy.ts
Labels: core, n8n team

#7431 ci: Fix wrong ref in PR workflows which broke external builds
  .github/workflows/ci-pull-requests.yml
  .github/workflows/e2e-tests-pr.yml
Labels: community

#7421 test(core): Add test for suppressing error on non-existing filepath (no-changelog)
  packages/core/test/FileSystem.manager.test.ts
Labels: core, n8n team

#7404 fix(core): Add check that queue is defined and remove cyclic dependency
  packages/cli/src/Queue.ts
  packages/cli/src/WebhookHelpers.ts
  packages/cli/src/WorkflowRunner.ts
  packages/cli/src/commands/worker.ts
  packages/cli/src/helpers/decodeWebhookResponse.ts
Labels: core, n8n team

#7433 fix: Fix flaky remote options loading test
  cypress/e2e/5-ndv.cy.ts
Labels: n8n team

#7281 docs: Mention UID in the docker examples
  docker/images/n8n/README.md
Labels: community

#7432 fix(Ldap Node): Fix issue with connections not closing correctly
  packages/nodes-base/credentials/Ldap.credentials.ts
  packages/nodes-base/nodes/Ldap/Helpers.ts
  packages/nodes-base/nodes/Ldap/Ldap.node.ts
Labels: node/improvement, community

#7412 refactor(core): Add binary data S3 to telemetry
  packages/cli/src/Interfaces.ts
  packages/cli/src/License.ts
  packages/cli/src/Server.ts
  packages/cli/src/services/frontend.service.ts
  packages/workflow/src/Interfaces.ts
Labels: core, n8n team

#7435 fix(core): Prevent false stalled jobs in queue mode from displaying as errored
  packages/cli/src/WorkflowRunner.ts
  packages/cli/test/unit/WorkflowRunner.test.ts
Labels: core, n8n team

#7436 feat(Google Calendar Trigger Node): Add support for cancelled events
  packages/nodes-base/nodes/Google/Calendar/GoogleCalendarTrigger.node.ts
Labels: node/improvement, n8n team

#7446 fix(Convert to/from binary data Node): Change Mime to MIME (no-changelog)
  packages/nodes-base/nodes/MoveBinaryData/MoveBinaryData.node.ts
Labels: node/improvement, n8n team

#7130 feat(n8n Form Trigger Node): New node
  .prettierignore
  cypress/e2e/16-form-trigger-node.cy.ts
  packages/cli/src/WebhookHelpers.ts
  packages/cli/templates/form-trigger-404.handlebars
  packages/cli/templates/form-trigger.handlebars
  packages/editor-ui/public/static/form-grey.svg
  packages/editor-ui/src/components/FixedCollectionParameter.vue
  packages/editor-ui/src/components/Node.vue
  packages/editor-ui/src/components/Node/NodeCreator/__tests__/NodesListPanel.test.ts
  packages/editor-ui/src/components/Node/NodeCreator/viewsData.ts
  packages/editor-ui/src/components/NodeExecuteButton.vue
  packages/editor-ui/src/components/NodeWebhooks.vue
  packages/editor-ui/src/components/TriggerPanel.vue
  packages/editor-ui/src/constants.ts
  packages/editor-ui/src/mixins/workflowRun.ts
  packages/editor-ui/src/plugins/i18n/locales/en.json
  packages/editor-ui/src/utils/executionUtils.ts
  packages/editor-ui/src/views/NodeView.vue
  packages/nodes-base/nodes/Form/FormTrigger.node.json
  packages/nodes-base/nodes/Form/FormTrigger.node.ts
  packages/nodes-base/nodes/Form/form.svg
  packages/nodes-base/nodes/Form/interfaces.ts
  packages/nodes-base/nodes/Form/utils.ts
  packages/nodes-base/package.json
  packages/workflow/src/Constants.ts
  packages/workflow/src/Interfaces.ts
Labels: node/new, n8n team

#7450 fix(TheHive 5 Node): Observable encoding in alert > create fix
  packages/nodes-base/nodes/TheHiveProject/actions/alert/create.operation.ts
Labels: n8n team, node/issue

#7357 fix(Google Sheets Node): Tweaks
  packages/nodes-base/nodes/Google/Sheet/GoogleSheets.node.ts
  packages/nodes-base/nodes/Google/Sheet/v2/actions/sheet/append.operation.ts
  packages/nodes-base/nodes/Google/Sheet/v2/actions/sheet/appendOrUpdate.operation.ts
  packages/nodes-base/nodes/Google/Sheet/v2/actions/sheet/commonDescription.ts
  packages/nodes-base/nodes/Google/Sheet/v2/actions/sheet/read.operation.ts
  packages/nodes-base/nodes/Google/Sheet/v2/actions/sheet/update.operation.ts
  packages/nodes-base/nodes/Google/Sheet/v2/actions/versionDescription.ts
  packages/nodes-base/nodes/Google/Sheet/v2/helpers/GoogleSheet.ts
  packages/nodes-base/nodes/Google/Sheet/v2/helpers/GoogleSheets.utils.ts
  packages/nodes-base/nodes/Google/Sheet/v2/methods/resourceMapping.ts
Labels: node/improvement, n8n team, node/issue

#7439 feat(core): Make executions pruning interval configurable
  packages/cli/src/config/schema.ts
  packages/cli/src/databases/repositories/execution.repository.ts
Labels: core, n8n team

#7461 fix(core): Handle gzip and deflate compressed request payloads
  packages/cli/src/middlewares/bodyParser.ts
  packages/cli/test/integration/middlewares/bodyParser.test.ts
Labels: core, n8n team

#7386 feat(RSS Feed Trigger Node): Add RSS feed trigger node
  packages/nodes-base/nodes/RssFeedRead/RssFeedReadTrigger.node.json
  packages/nodes-base/nodes/RssFeedRead/RssFeedReadTrigger.node.ts
  packages/nodes-base/package.json
Labels: node/new, n8n team

#7463 fix(Google Sheets Node): Append or update runs forever when without column headers
  packages/nodes-base/nodes/Google/Sheet/v2/actions/sheet/appendOrUpdate.operation.ts
  packages/nodes-base/nodes/Google/Sheet/v2/actions/sheet/update.operation.ts
Labels: n8n team, node/issue

#7465 fix(core): Do not return `inviteAcceptUrl` in response if email was sent
  packages/cli/src/Server.ts
  packages/cli/src/UserManagement/UserManagementHelper.ts
  packages/cli/src/UserManagement/email/UserManagementMailer.ts
  packages/cli/src/controllers/passwordReset.controller.ts
  packages/cli/src/controllers/users.controller.ts
  packages/cli/src/services/frontend.service.ts
  packages/cli/test/integration/ldap/ldap.api.test.ts
  packages/cli/test/integration/passwordReset.api.test.ts
  packages/cli/test/integration/shared/utils/testServer.ts
  packages/cli/test/integration/users.api.test.ts
  packages/cli/test/unit/UserManagementMailer.test.ts
Labels: core, n8n team

#7405 feat(editor): Workflow history [WIP] - Add cloned workflow link to success toast message (no-changelog)
  packages/editor-ui/src/composables/useToast.ts
  packages/editor-ui/src/plugins/i18n/locales/en.json
  packages/editor-ui/src/stores/workflowHistory.store.ts
  packages/editor-ui/src/views/WorkflowHistory.vue
  packages/editor-ui/src/views/__tests__/WorkflowHistory.test.ts
Labels: ui, n8n team

#7466 fix(editor): Fix canvas selection breaking after interacting with node actions
  cypress/e2e/12-canvas-actions.cy.ts
  cypress/pages/workflow.ts
  packages/editor-ui/src/stores/canvas.store.ts
  packages/editor-ui/src/views/NodeView.vue
Labels: ui, n8n team

#7464 fix(MySQL Node): Resolve expressions in v1
  packages/nodes-base/nodes/MySql/test/v1/executeQuery.test.ts
  packages/nodes-base/nodes/MySql/test/v1/executeQuery.workflow.json
  packages/nodes-base/nodes/MySql/v1/MySqlV1.node.ts
Labels: n8n team, node/issue

#7472 fix(n8n Form Trigger Node): Fix typos (no-changelog)
  packages/nodes-base/nodes/Form/FormTrigger.node.ts
Labels: node/improvement, n8n team, skip-e2e

#7418 feat(core): Update LLM applications building support (no-changelog)
  packages/core/src/NodeExecuteFunctions.ts
  packages/editor-ui/src/components/ChatEmbedModal.vue
  packages/editor-ui/src/components/NodeDetailsView.vue
  packages/editor-ui/src/components/NodeExecuteButton.vue
  packages/editor-ui/src/components/NodeSettings.vue
  packages/editor-ui/src/components/OutputPanel.vue
  packages/editor-ui/src/components/RunData.vue
  packages/editor-ui/src/components/RunDataJson.vue
  packages/editor-ui/src/components/VariableSelector.vue
  packages/editor-ui/src/components/WorkflowLMChat.vue
  packages/editor-ui/src/constants.ts
  packages/editor-ui/src/mixins/workflowHelpers.ts
  packages/editor-ui/src/views/NodeView.vue
  packages/workflow/src/Interfaces.ts
Labels: core, ui, n8n team

#7407 feat(core): Improve structured schema & add maxIteration for agents
  packages/@n8n/nodes-langchain/nodes/agents/Agent/agents/ConversationalAgent/description.ts
  packages/@n8n/nodes-langchain/nodes/agents/Agent/agents/ConversationalAgent/execute.ts
  packages/@n8n/nodes-langchain/nodes/agents/Agent/agents/OpenAiFunctionsAgent/description.ts
  packages/@n8n/nodes-langchain/nodes/agents/Agent/agents/OpenAiFunctionsAgent/execute.ts
  packages/@n8n/nodes-langchain/nodes/output_parser/OutputParserStructured/OutputParserStructured.node.ts
Labels: n8n team

#7311 feat(core): Add support for oauth based service accounts with UM SMTP
  packages/cli/src/UserManagement/email/NodeMailer.ts
  packages/cli/src/config/schema.ts
Labels: core, n8n team

#7113 feat(Facebook Lead Ads Trigger Node): Add Facebook Lead Ads Trigger Node
  packages/core/bin/generate-ui-types
  packages/editor-ui/src/components/NodeWebhooks.vue
  packages/nodes-base/credentials/FacebookLeadAdsOAuth2Api.credentials.ts
  packages/nodes-base/nodes/Facebook/FacebookTrigger.node.ts
  packages/nodes-base/nodes/Facebook/types.ts
  packages/nodes-base/nodes/FacebookLeadAds/FacebookLeadAdsTrigger.node.json
  packages/nodes-base/nodes/FacebookLeadAds/FacebookLeadAdsTrigger.node.ts
  packages/nodes-base/nodes/FacebookLeadAds/GenericFunctions.ts
  packages/nodes-base/nodes/FacebookLeadAds/facebook.svg
  packages/nodes-base/nodes/FacebookLeadAds/methods/index.ts
  packages/nodes-base/nodes/FacebookLeadAds/methods/listSearch.ts
  packages/nodes-base/nodes/FacebookLeadAds/types.ts
  packages/nodes-base/package.json
  packages/workflow/src/Interfaces.ts
Labels: node/new, n8n team

#7458 fix(editor): Allow importing the same workflow multiple times
  packages/editor-ui/src/components/MainHeader/WorkflowDetails.vue
Labels: ui, n8n team

#7469 refactor(core): Limit soft-deletions to pruning only
  packages/cli/src/PublicApi/v1/handlers/executions/executions.handler.ts
  packages/cli/src/WorkflowExecuteAdditionalData.ts
  packages/cli/src/WorkflowRunner.ts
  packages/cli/src/databases/repositories/execution.repository.ts
  packages/cli/test/integration/repositories/execution.repository.test.ts
Labels: core, n8n team

#7479 fix(core): Reduce logging overhead for levels that do not output
  packages/cli/src/Logger.ts
  packages/core/bin/generate-known
  packages/core/bin/generate-ui-types
  packages/workflow/src/LoggerProxy.ts
Labels: core, n8n team

#7483 fix(editor): Fix connections disappearing after reactivating canvas and renaming a node
  cypress/e2e/12-canvas.cy.ts
  packages/editor-ui/src/views/NodeView.vue
Labels: ui, n8n team

#7488 feat(Ghost Node): Add support for lexical format
  packages/nodes-base/nodes/Ghost/Ghost.node.ts
  packages/nodes-base/nodes/Ghost/PostDescription.ts
Labels: node/improvement, community

#7485 fix(Customer.io Node): Fix api endpoint when using EU region
  packages/nodes-base/nodes/CustomerIo/GenericFunctions.ts
Labels: node/improvement, community

#7428 fix: Save new version of the workflow instead of the previous (no-changelog)
  packages/cli/src/PublicApi/v1/handlers/workflows/workflows.handler.ts
  packages/cli/src/workflows/workflowHistory/workflowHistory.service.ee.ts
  packages/cli/src/workflows/workflows.controller.ts
  packages/cli/src/workflows/workflows.services.ts
  packages/cli/test/integration/publicApi/workflows.test.ts
  packages/cli/test/integration/workflows.controller.test.ts
Labels: core, n8n team

#7496 fix(core): Fix `frontend.settings` external hook execution
  packages/cli/src/services/frontend.service.ts
Labels: core, n8n team

#7486 feat: Collect usage metrics on license renewal (no-changelog)
  packages/cli/package.json
  packages/cli/src/License.ts
  packages/cli/test/unit/License.test.ts
  pnpm-lock.yaml
Labels: core, n8n team

#7498 fix(MQTT Trigger Node): Fix node causing a start up hang when active
  packages/nodes-base/nodes/MQTT/MqttTrigger.node.ts
Labels: node/improvement, n8n team

#7501 fix(core): Always derive `instanceId` from the encryption key (no-changlog)
  packages/core/src/InstanceSettings.ts
  packages/core/test/InstanceSettings.test.ts
Labels: core, n8n team

#7482 refactor(core): Make pruning via lifecycle configuration in S3 mode mandatory
  packages/cli/src/databases/repositories/execution.repository.ts
  packages/core/src/BinaryData/BinaryData.service.ts
  packages/core/src/BinaryData/ObjectStore.manager.ts
  packages/core/src/BinaryData/types.ts
  packages/core/test/ObjectStore.manager.test.ts
Labels: core, n8n team

#7467 fix(Microsoft SQL Node): Prevent SQL injection
  packages/nodes-base/nodes/Microsoft/Sql/GenericFunctions.ts
  packages/nodes-base/nodes/Microsoft/Sql/MicrosoftSql.node.ts
  packages/nodes-base/nodes/Microsoft/Sql/interfaces.ts
  packages/nodes-base/nodes/Microsoft/Sql/test/utils.test.ts
Labels: n8n team, node/issue

#7475 feat(core): Add support to include system/ai/human pre-messages for LLM Chain
  packages/@n8n/nodes-langchain/nodes/chains/ChainLLM/ChainLlm.node.ts
Labels: n8n team

#7506 fix(core): Create instance settings directory recursively (no-changelog)
  packages/core/src/InstanceSettings.ts
  packages/core/test/InstanceSettings.test.ts
Labels: core, n8n team

#7505 fix(Spreadsheet File Node): Fix include empty cells not working with v2
  packages/nodes-base/nodes/SpreadsheetFile/test/SpreadsheetFile.test.ts
  packages/nodes-base/nodes/SpreadsheetFile/test/includeempty.csv
  packages/nodes-base/nodes/SpreadsheetFile/test/workflow.empty.json
  packages/nodes-base/nodes/SpreadsheetFile/v2/SpreadsheetFileV2.node.ts
Labels: node/improvement, n8n team

#7480 refactor(core): Make executions pruning more resilient
  packages/cli/src/databases/repositories/execution.repository.ts
  packages/cli/test/integration/repositories/execution.repository.test.ts
Labels: core, n8n team

#7491 feat(core): Add support for metadata setting and filtering from vector stores
  packages/@n8n/nodes-langchain/nodes/document_loaders/DocumentBinaryInputLoader/DocumentBinaryInputLoader.node.ts
  packages/@n8n/nodes-langchain/nodes/document_loaders/DocumentJSONInputLoader/DocumentJsonInputLoader.node.ts
  packages/@n8n/nodes-langchain/nodes/vector_store/VectorStorePineconeLoad/VectorStorePineconeLoad.node.ts
  packages/@n8n/nodes-langchain/nodes/vector_store/VectorStoreSupabaseLoad/VectorStoreSupabaseLoad.node.ts
  packages/@n8n/nodes-langchain/nodes/vector_store/VectorStoreZepLoad/VectorStoreZepLoad.node.ts
  packages/@n8n/nodes-langchain/package.json
  packages/@n8n/nodes-langchain/utils/N8nBinaryLoader.ts
  packages/@n8n/nodes-langchain/utils/N8nJsonLoader.ts
  packages/@n8n/nodes-langchain/utils/helpers.ts
  packages/@n8n/nodes-langchain/utils/sharedFields.ts
  pnpm-lock.yaml
Labels: n8n team

#7511 feat(editor): Add PH tracking to event
  packages/editor-ui/src/views/NodeView.vue
Labels: ui, n8n team

#7500 fix(core): Ensure nodes post-processors run in the correct order
  packages/cli/src/Server.ts
  packages/cli/src/WorkflowRunnerProcess.ts
  packages/cli/src/commands/BaseCommand.ts
  packages/cli/src/services/frontend.service.ts
Labels: core, n8n team

#7499 feat(Switch Node): Add support for infinite Switch outputs
  cypress/e2e/10-undo-redo.cy.ts
  cypress/e2e/12-canvas-actions.cy.ts
  cypress/e2e/12-canvas.cy.ts
  packages/editor-ui/src/components/Node.vue
  packages/editor-ui/src/components/RunData.vue
  packages/editor-ui/src/constants.ts
  packages/editor-ui/src/mixins/nodeBase.ts
  packages/editor-ui/src/plugins/jsplumb/N8nPlusEndpointType.ts
  packages/editor-ui/src/utils/nodeViewUtils.ts
  packages/nodes-base/nodes/Switch/Switch.node.ts
  packages/nodes-base/nodes/Switch/V1/SwitchV1.node.ts
  packages/nodes-base/nodes/Switch/V1/test/switch.expression.workflow.json
  packages/nodes-base/nodes/Switch/V1/test/switch.node.test.ts
  packages/nodes-base/nodes/Switch/V1/test/switch.rules.workflow.json
  packages/nodes-base/nodes/Switch/V2/SwitchV2.node.ts
  packages/nodes-base/nodes/Switch/V2/test/switch.expression.workflow.json
  packages/nodes-base/nodes/Switch/V2/test/switch.node.test.ts
  packages/nodes-base/nodes/Switch/V2/test/switch.rules.workflow.json
  packages/workflow/src/NodeHelpers.ts
Labels: node/improvement, node/new, ui, n8n team

#7481 fix(core): Ensure execution deletion in worker lifecycle hook
  packages/cli/src/WorkflowExecuteAdditionalData.ts
Labels: core, n8n team

#7516 fix(editor): Fixes the issue that Switch Node can not be created
  cypress/e2e/12-canvas.cy.ts
  packages/editor-ui/src/views/NodeView.vue
Labels: ui, n8n team

#7519 fix(core): Upgrade crypto-js to address CVE-2023-46233
  packages/core/jest.config.js
  packages/core/package.json
  packages/core/src/Cipher.ts
  packages/core/test/Cipher.test.ts
  packages/core/test/setup-mocks.ts
  packages/workflow/package.json
  pnpm-lock.yaml
Labels: core, n8n team

#7518 refactor(Google Sheets Node): Prevent reporting to Sentry failure to find spreadsheet (no-changelog)
  packages/nodes-base/nodes/Google/Sheet/v2/actions/router.ts
  packages/nodes-base/nodes/Google/Sheet/v2/helpers/GoogleSheets.utils.ts
  packages/nodes-base/nodes/Google/Sheet/v2/methods/listSearch.ts
  packages/nodes-base/nodes/Google/Sheet/v2/methods/loadOptions.ts
  packages/nodes-base/nodes/Google/Sheet/v2/methods/resourceMapping.ts
Labels: node/improvement, n8n team

#7521 refactor(Airtable Node): Prevent reporting to Sentry failure to find table (no-changelog)
  packages/nodes-base/nodes/Airtable/v2/methods/listSearch.ts
  packages/nodes-base/nodes/Airtable/v2/methods/loadOptions.ts
  packages/nodes-base/nodes/Airtable/v2/methods/resourceMapping.ts
Labels: node/improvement, n8n team

#7520 refactor(FileMaker Node): Prevent reporting to Sentry attempted `loadOptions` calls without credentials (no-changelog)
  packages/nodes-base/nodes/FileMaker/FileMaker.node.ts
Labels: node/improvement, n8n team

#7523 fix(core): Handle missing resultData in runData
  packages/cli/src/WorkflowRunner.ts
  packages/cli/src/executionLifecycleHooks/shared/sharedHookFunctions.ts
Labels: core, n8n team

#7370 refactor(core): Move execution save settings into lifecycle function (no-changelog)
  packages/cli/src/WorkflowExecuteAdditionalData.ts
  packages/cli/src/config/schema.ts
  packages/cli/src/executionLifecycleHooks/toSaveSettings.ts
  packages/cli/test/unit/execution.lifecycle.test.ts
Labels: core, n8n team

#7515 refactor(core)!: Remove webhook deregistration at startup and shutdown
  packages/cli/BREAKING-CHANGES.md
  packages/cli/src/ActiveWorkflowRunner.ts
  packages/cli/src/TestWebhooks.ts
  packages/cli/src/commands/BaseCommand.ts
  packages/cli/src/commands/start.ts
  packages/cli/src/services/webhook.service.ts
  packages/cli/test/unit/ActiveWorkflowRunner.test.ts
  packages/cli/test/unit/services/webhook.service.test.ts
Labels: core, n8n team

#7526 feat(core): Make queue mode settings configurable
  packages/cli/src/Queue.ts
  packages/cli/src/config/schema.ts
Labels: core, n8n team

#7528 fix(editor): Do not truncate form inputs
  packages/editor-ui/src/components/ParameterInput.vue
Labels: ui, n8n team

#7434 fix(editor): Fix editor route component caching and incorrect use of array reduce method
  cypress/e2e/30-editor-after-route-changes.cy.ts
  cypress/pages/index.ts
  cypress/pages/workflow-history.ts
  cypress/pages/workflow.ts
  packages/editor-ui/src/App.vue
  packages/editor-ui/src/components/MainHeader/WorkflowDetails.vue
  packages/editor-ui/src/components/WorkflowHistory/WorkflowHistoryContent.vue
  packages/editor-ui/src/components/WorkflowHistory/WorkflowHistoryList.vue
  packages/editor-ui/src/plugins/codemirror/completions/utils.ts
  packages/editor-ui/src/router.ts
  packages/editor-ui/src/stores/workflowHistory.store.ts
  packages/editor-ui/src/utils/nodeViewUtils.ts
  packages/editor-ui/src/views/WorkflowHistory.vue
Labels: ui, n8n team

#7525 refactor(core): Stop reporting non-error to sentry (issue 4229454473) (no-changelog)
  packages/cli/src/ActiveExecutions.ts
  packages/workflow/src/WorkflowErrors.ts
Labels: core, n8n team

#7534 fix(Jira Software Node): Handle missing issue types in issue types loader
  packages/nodes-base/nodes/Jira/Jira.node.ts
Labels: node/improvement, n8n team

#7533 refactor(core): Stop reporting to Sentry non-execution of workflow with issues
  packages/core/src/WorkflowExecute.ts
Labels: core, n8n team

#6909 fix(editor): Fix executions sidebar height (no-changelog)
  packages/editor-ui/src/components/ExecutionsView/ExecutionsSidebar.vue
Labels: ui, n8n team

#7348 fix(editor): Handle `localStorage` being blocked/unavailable
  packages/editor-ui/package.json
  packages/editor-ui/src/App.vue
  packages/editor-ui/src/components/NDVDraggablePanels.vue
  packages/editor-ui/src/components/Node.vue
  packages/editor-ui/src/components/RunData.vue
  packages/editor-ui/src/mixins/workflowActivate.ts
  packages/editor-ui/src/router.ts
  packages/editor-ui/src/stores/ndv.store.ts
  packages/editor-ui/src/stores/posthog.store.ts
  pnpm-lock.yaml
Labels: ui, n8n team

#7541 refactor(core): Stop reporting to Sentry stopping execution with wrong status (no-changelog)
  packages/cli/src/WaitTracker.ts
Labels: core, n8n team

#7542 refactor(Slack Node): Stop reporting to Sentry errors from missing scopes (no-changelog)
  packages/nodes-base/nodes/Slack/V2/GenericFunctions.ts
Labels: node/improvement, n8n team

#7543 refactor(core): Remove webhook deregistration on shutdown flag
  packages/cli/src/config/schema.ts
Labels: core, n8n team, skip-e2e

#7532 fix(editor): Fix NDV unexpected re-render
  packages/editor-ui/src/components/InputPanel.vue
  packages/editor-ui/src/components/NodeDetailsView.vue
Labels: ui, n8n team

#7548 refactor: Upgrade to pnpm 8.10 (no-changelog)
  .github/workflows/test-workflows.yml
  CONTRIBUTING.md
  package.json
Labels: n8n team

#7545 docs: Fix spelling issue in Gmail trigger node
  packages/nodes-base/nodes/Google/Gmail/GmailTrigger.node.ts
Labels: node/improvement, community

#7552 refactor(GitHub Trigger Node): Stop reporting to Sentry permission errors (no-changelog)
  packages/nodes-base/nodes/Github/GithubTrigger.node.ts
Labels: node/improvement, n8n team

#7544 fix(editor): Fix NDV close after using input select
  cypress/e2e/5-ndv.cy.ts
  cypress/support/commands.ts
  cypress/support/index.ts
  packages/editor-ui/src/components/NodeDetailsView.vue
Labels: ui, n8n team

#7527 feat(core): Set up leader selection for multiple main instances
  packages/cli/src/ExternalSecrets/ExternalSecretsManager.ee.ts
  packages/cli/src/License.ts
  packages/cli/src/commands/start.ts
  packages/cli/src/config/schema.ts
  packages/cli/src/constants.ts
  packages/cli/src/controllers/e2e.controller.ts
  packages/cli/src/controllers/orchestration.controller.ts
  packages/cli/src/eventbus/MessageEventBus/MessageEventBus.ts
  packages/cli/src/services/orchestration.base.service.ts
  packages/cli/src/services/orchestration/main/MultiMainInstance.publisher.ee.ts
  packages/cli/src/services/orchestration/main/SingleMainInstance.publisher.ts
  packages/cli/src/services/orchestration/main/handleCommandMessageMain.ts
  packages/cli/src/services/orchestration/main/orchestration.main.service.ts
  packages/cli/src/services/redis/RedisServicePubSubPublisher.ts
  packages/cli/test/unit/services/orchestration.service.test.ts
Labels: core, n8n team

#7460 feat(core): Add optional Error-Output
  packages/cli/src/PublicApi/v1/handlers/workflows/spec/schemas/node.yml
  packages/core/src/NodeExecuteFunctions.ts
  packages/core/src/WorkflowExecute.ts
  packages/core/test/workflows/error_outputs.json
  packages/editor-ui/src/components/Node.vue
  packages/editor-ui/src/components/NodeDetailsView.vue
  packages/editor-ui/src/components/NodeSettings.vue
  packages/editor-ui/src/mixins/nodeBase.ts
  packages/editor-ui/src/mixins/workflowHelpers.ts
  packages/editor-ui/src/n8n-theme.scss
  packages/editor-ui/src/plugins/i18n/locales/en.json
  packages/editor-ui/src/plugins/jsplumb/N8nPlusEndpointType.ts
  packages/editor-ui/src/utils/nodeViewUtils.ts
  packages/editor-ui/src/views/NodeView.vue
  packages/nodes-base/nodes/Code/Code.node.ts
  packages/nodes-base/nodes/Code/Sandbox.ts
  packages/workflow/src/Interfaces.ts
  packages/workflow/src/NodeHelpers.ts
  packages/workflow/src/RoutingNode.ts
  packages/workflow/src/WorkflowDataProxy.ts
Labels: node/improvement, core, ui, n8n team

#7555 fix(Switch Node): Allow sortable Switch rules
  packages/nodes-base/nodes/Switch/V2/SwitchV2.node.ts
Labels: node/improvement, n8n team

#7557 fix(editor): Keep NodeView component alive for `TEMPLATE_IMPORT` and `WORKFLOW_ONBOARDING` routes (no-changelog)
  packages/editor-ui/src/router.ts
Labels: ui, n8n team

#7562 update vector store links
  packages/@n8n/nodes-langchain/nodes/vector_store/VectorStoreInMemoryInsert/VectorStoreInMemoryInsert.node.ts
  packages/@n8n/nodes-langchain/nodes/vector_store/VectorStoreInMemoryLoad/VectorStoreInMemoryLoad.node.ts
  packages/@n8n/nodes-langchain/nodes/vector_store/VectorStorePineconeInsert/VectorStorePineconeInsert.node.ts
  packages/@n8n/nodes-langchain/nodes/vector_store/VectorStoreSupabaseInsert/VectorStoreSupabaseInsert.node.ts
  packages/@n8n/nodes-langchain/nodes/vector_store/VectorStoreZepInsert/VectorStoreZepInsert.node.ts
Labels: n8n team

#7560 fix(core): Fix data decryption on credentials import
  packages/cli/src/commands/import/credentials.ts
  packages/cli/test/integration/commands/credentials.cmd.test.ts
  packages/cli/test/integration/commands/importCredentials/credentials.json
  packages/cli/test/integration/shared/testDb.ts
Labels: core, n8n team

#7563 feat(core): Add support for Huggin Face inference endpoints to LM and embs
  packages/@n8n/nodes-langchain/nodes/embeddings/EmbeddingsHuggingFaceInference/EmbeddingsHuggingFaceInference.node.ts
  packages/@n8n/nodes-langchain/nodes/embeddings/EmbeddingsHuggingFaceInference/HuggingFaceEmbeddings.ts
  packages/@n8n/nodes-langchain/nodes/llms/LMOpenHuggingFaceInference/HuggingFaceInferenceEndpoints.ts
  packages/@n8n/nodes-langchain/nodes/llms/LMOpenHuggingFaceInference/LmOpenHuggingFaceInference.node.ts
  packages/@n8n/nodes-langchain/package.json
  pnpm-lock.yaml
Labels: n8n team

#7565 fix(editor): Rename and move `isObjectLiteral` utility function (no-changelog)
  packages/editor-ui/src/mixins/nodeHelpers.ts
  packages/editor-ui/src/stores/workflows.store.ts
  packages/editor-ui/src/utils/__tests__/objectUtils.test.ts
  packages/editor-ui/src/utils/index.ts
  packages/editor-ui/src/utils/objectUtils.ts
  packages/editor-ui/src/utils/typesUtils.ts
Labels: ui, n8n team
