Repository n8n-io/n8n, pull requests merged in 2023-12, with the labels that each got.

#7889 fix(core): Allow grace period for binary data deletion after manual execution
  packages/cli/src/WorkflowExecuteAdditionalData.ts
Labels: core, n8n team

#7892 refactor(core): Add log about removed TTL keys for binary data
  packages/cli/src/commands/BaseCommand.ts
Labels: core, n8n team

#7894 docs: Update breaking changes with binary data TTL note
  packages/cli/BREAKING-CHANGES.md
Labels: core, n8n team, skip-e2e

#7893 ci: Fix Docker build and use multi-step approach (no-changelog)
  docker/images/n8n/Dockerfile
Labels: n8n team

#7904 perf(editor): Improve node rendering performance when opening large workflows
  packages/editor-ui/src/components/Node.vue
  packages/editor-ui/src/mixins/nodeBase.ts
  packages/editor-ui/src/views/NodeView.vue
Labels: ui, n8n team

#7899 feat(editor): Allow partial template credential setup (no-changelog)
  cypress/e2e/34-template-credentials-setup.cy.ts
  packages/editor-ui/src/plugins/i18n/locales/en.json
  packages/editor-ui/src/views/SetupWorkflowFromTemplateView/SetupWorkflowFromTemplateView.vue
  packages/editor-ui/src/views/SetupWorkflowFromTemplateView/setupTemplate.store.ts
Labels: ui, n8n team

#7901 perf(editor): Improve performance when opening large workflows with node issues
  cypress/e2e/28-debug.cy.ts
  packages/editor-ui/src/mixins/nodeHelpers.ts
  packages/editor-ui/src/mixins/workflowHelpers.ts
  packages/editor-ui/src/views/NodeView.vue
Labels: ui, n8n team

#7903 fix(editor): Tune credential template layout (no-changelog)
  packages/editor-ui/src/views/SetupWorkflowFromTemplateView/SetupWorkflowFromTemplateView.vue
Labels: ui, n8n team

#7919 fix(editor): Add missing activeNode check for redrawing (no-changelog)
  packages/editor-ui/src/components/NodeDetailsView.vue
Labels: ui, n8n team

#7921 fix(editor): Use hasOwnProperty to check for canvas key on connector (no-changelog)
  packages/editor-ui/src/views/NodeView.vue
Labels: ui, n8n team

#7918 fix(editor): Add missing workflow id from route (no-changelog)
  packages/editor-ui/src/components/ExecutionsView/ExecutionsList.vue
Labels: ui, n8n team

#7914 refactor: Switch plain errors in `nodes-base` to `ApplicationError` (no-changelog)
  packages/nodes-base/credentials/CustomerIoApi.credentials.ts
  packages/nodes-base/credentials/ZscalerZiaApi.credentials.ts
  packages/nodes-base/nodes/Airtable/v2/helpers/utils.ts
  packages/nodes-base/nodes/Airtable/v2/transport/index.ts
  packages/nodes-base/nodes/Aws/DynamoDB/GenericFunctions.ts
  packages/nodes-base/nodes/Aws/DynamoDB/utils.ts
  packages/nodes-base/nodes/Code/test/Code.node.test.ts
  packages/nodes-base/nodes/CompareDatasets/GenericFunctions.ts
  packages/nodes-base/nodes/DebugHelper/DebugHelper.node.ts
  packages/nodes-base/nodes/FileMaker/GenericFunctions.ts
  packages/nodes-base/nodes/FormIo/GenericFunctions.ts
  packages/nodes-base/nodes/Formstack/GenericFunctions.ts
  packages/nodes-base/nodes/Google/BigQuery/v2/actions/database/executeQuery.operation.ts
  packages/nodes-base/nodes/Google/Sheet/v2/helpers/GoogleSheet.ts
  packages/nodes-base/nodes/ItemLists/V3/helpers/utils.ts
  packages/nodes-base/nodes/LoneScale/GenericFunctions.ts
  packages/nodes-base/nodes/Magento/GenericFunctions.ts
  packages/nodes-base/nodes/Mailcheck/GenericFunctions.ts
  packages/nodes-base/nodes/Merge/v2/GenericFunctions.ts
  packages/nodes-base/nodes/Microsoft/Outlook/v2/helpers/utils.ts
  packages/nodes-base/nodes/MongoDb/MongoDb.node.ts
  packages/nodes-base/nodes/MySql/v2/transport/index.ts
  packages/nodes-base/nodes/Postgres/PostgresTrigger.functions.ts
  packages/nodes-base/nodes/Postgres/v1/genericFunctions.ts
  packages/nodes-base/nodes/Set/v2/helpers/utils.ts
  packages/nodes-base/nodes/TheHive/GenericFunctions.ts
  packages/nodes-base/nodes/TheHiveProject/helpers/utils.ts
  packages/nodes-base/nodes/Todoist/v1/OperationHandler.ts
  packages/nodes-base/nodes/Todoist/v2/OperationHandler.ts
  packages/nodes-base/nodes/Twitter/V2/GenericFunctions.ts
  packages/nodes-base/nodes/Venafi/Datacenter/GenericFunctions.ts
  packages/nodes-base/test/nodes/Helpers.ts
  packages/nodes-base/utils/utilities.ts
Labels: node/improvement, n8n team

#7917 fix: Return scopes on invitation accept endpoint (no-changelog)
  packages/cli/src/controllers/invitation.controller.ts
  packages/cli/test/integration/invitations.api.test.ts
Labels: core, n8n team

#7878 feat(BambooHR Node): Add support for Only Current on company reports
  packages/nodes-base/nodes/BambooHr/v1/actions/companyReport/get/description.ts
  packages/nodes-base/nodes/BambooHr/v1/actions/companyReport/get/execute.ts
Labels: node/improvement, n8n team

#7929 ci: Remove `master` from autocancelling redundant CI jobs (no-changelog)
  .github/workflows/ci-master.yml
Labels: n8n team

#7933 feat: Add admin role to public API (no-changelog)
  packages/cli/src/PublicApi/v1/handlers/audit/audit.handler.ts
  packages/cli/src/PublicApi/v1/handlers/credentials/credentials.handler.ts
  packages/cli/src/PublicApi/v1/handlers/executions/executions.handler.ts
  packages/cli/src/PublicApi/v1/handlers/sourceControl/sourceControl.handler.ts
  packages/cli/src/PublicApi/v1/handlers/users/users.handler.ee.ts
  packages/cli/src/PublicApi/v1/handlers/workflows/workflows.handler.ts
  packages/cli/src/PublicApi/v1/handlers/workflows/workflows.service.ts
  packages/cli/src/PublicApi/v1/shared/middlewares/global.middleware.ts
Labels: core, n8n team

#7848 fix(core): Fix hard deletes stopping if database query throws
  packages/cli/src/services/pruning.service.ts
Labels: core, community

#7936 fix(core): Make sure mfa secret and recovery codes are not returned on login
  packages/cli/src/services/user.service.ts
  packages/cli/test/integration/auth.api.test.ts
Labels: core, n8n team

#7913 fix(core): Fix user comparison in same-user subworkflow caller policy
  packages/cli/src/UserManagement/PermissionChecker.ts
  packages/cli/src/WorkflowExecuteAdditionalData.ts
  packages/cli/src/WorkflowHelpers.ts
  packages/cli/test/unit/PermissionChecker.test.ts
  packages/core/src/NodeExecuteFunctions.ts
  packages/workflow/src/Interfaces.ts
  packages/workflow/src/errors/workflow-operation.error.ts
Labels: core, n8n team

#7930 refactor: Migrate externalHooks mixin to composables (no-changelog)
  packages/editor-ui/src/App.vue
  packages/editor-ui/src/Interface.ts
  packages/editor-ui/src/components/CredentialEdit/CredentialEdit.vue
  packages/editor-ui/src/components/CredentialsSelectModal.vue
  packages/editor-ui/src/components/ExecutionsList.vue
  packages/editor-ui/src/components/ExecutionsView/ExecutionsList.vue
  packages/editor-ui/src/components/ExpressionEdit.vue
  packages/editor-ui/src/components/MainHeader/MainHeader.vue
  packages/editor-ui/src/components/MainSidebar.vue
  packages/editor-ui/src/components/Node.vue
  packages/editor-ui/src/components/Node/NodeCreator/Modes/ActionsMode.vue
  packages/editor-ui/src/components/Node/NodeCreator/composables/useActions.ts
  packages/editor-ui/src/components/NodeDetailsView.vue
  packages/editor-ui/src/components/NodeExecuteButton.vue
  packages/editor-ui/src/components/NodeSettings.vue
  packages/editor-ui/src/components/NodeSettingsTabs.vue
  packages/editor-ui/src/components/ParameterInput.vue
  packages/editor-ui/src/components/ParameterInputFull.vue
  packages/editor-ui/src/components/PersonalizationModal.vue
  packages/editor-ui/src/components/RunData.vue
  packages/editor-ui/src/components/RunDataJson.vue
  packages/editor-ui/src/components/RunDataSchema.vue
  packages/editor-ui/src/components/RunDataTable.vue
  packages/editor-ui/src/components/Sticky.vue
  packages/editor-ui/src/components/Telemetry.vue
  packages/editor-ui/src/components/VariableSelectorItem.vue
  packages/editor-ui/src/components/WorkerList.ee.vue
  packages/editor-ui/src/components/WorkflowActivator.vue
  packages/editor-ui/src/components/WorkflowLMChat.vue
  packages/editor-ui/src/components/WorkflowSettings.vue
  packages/editor-ui/src/composables/useExternalHooks.ts
  packages/editor-ui/src/hooks/register.ts
  packages/editor-ui/src/mixins/externalHooks.ts
  packages/editor-ui/src/mixins/pinData.ts
  packages/editor-ui/src/mixins/pushConnection.ts
  packages/editor-ui/src/mixins/workflowActivate.ts
  packages/editor-ui/src/mixins/workflowHelpers.ts
  packages/editor-ui/src/mixins/workflowRun.ts
  packages/editor-ui/src/router.ts
  packages/editor-ui/src/utils/externalHooks.ts
  packages/editor-ui/src/views/NodeView.vue
  packages/editor-ui/src/views/SettingsCommunityNodesView.vue
  packages/editor-ui/src/views/SetupWorkflowFromTemplateView/SetupWorkflowFromTemplateView.vue
  packages/editor-ui/src/views/SetupWorkflowFromTemplateView/setupTemplate.store.ts
  packages/editor-ui/src/views/TemplatesCollectionView.vue
  packages/editor-ui/src/views/TemplatesWorkflowView.vue
Labels: ui, n8n team

#7928 fix: Run dev command only for core packages (no-changelog)
  package.json
  packages/@n8n/chat/package.json
  packages/design-system/package.json
  packages/editor-ui/src/components/ChatEmbedModal.vue
  turbo.json
Labels: ui, n8n team

#7804 fix(Webhook Node): Binary data handling
  packages/cli/src/WebhookHelpers.ts
  packages/nodes-base/nodes/Webhook/Webhook.node.ts
  packages/nodes-base/nodes/Webhook/description.ts
Labels: node/improvement, n8n team, node/issue

#7943 fix(core): Ensure inviter and invitee are set correctly in invite link
  packages/cli/src/controllers/users.controller.ts
  packages/cli/src/services/user.service.ts
  packages/cli/test/unit/services/user.service.test.ts
Labels: core, n8n team

#7947 fix: Ensure external hooks post workflow execute run in queue mode
  packages/cli/src/WorkflowExecuteAdditionalData.ts
  packages/cli/src/WorkflowRunner.ts
Labels: core, n8n team

#7945 feat(editor): Add AppCues tracking for onboarding event
  packages/editor-ui/src/Interface.ts
  packages/editor-ui/src/plugins/__tests__/telemetry.test.ts
  packages/editor-ui/src/plugins/telemetry/index.ts
  packages/editor-ui/src/views/NodeView.vue
Labels: ui, n8n team

#7926 fix(editor): Send correct telemetry events in credential setup (no-changelog)
  packages/editor-ui/src/views/SetupWorkflowFromTemplateView/SetupWorkflowFromTemplateView.vue
  packages/editor-ui/src/views/SetupWorkflowFromTemplateView/setupTemplate.store.ts
Labels: ui, n8n team

#7951 fix(editor): Separate data and sharee update on credential
  packages/editor-ui/src/components/CredentialEdit/CredentialConfig.vue
  packages/editor-ui/src/components/CredentialEdit/CredentialEdit.vue
  packages/editor-ui/src/components/CredentialEdit/CredentialInfo.vue
  packages/editor-ui/src/components/CredentialEdit/CredentialSharing.ee.vue
  packages/editor-ui/src/mixins/nodeHelpers.ts
  packages/editor-ui/src/permissions.ts
  packages/editor-ui/src/stores/credentials.store.ts
  packages/editor-ui/src/stores/users.store.ts
Labels: ui, n8n team

#7960 fix(core): Fix expression evaluator filename typo (no-changelog)
  packages/cli/src/ExpressionEvaluator.ts
  packages/cli/src/commands/BaseCommand.ts
Labels: core, n8n team

#7954 test(core): Improve tests for subworkflow caller policy checks (no-changelog)
  packages/cli/test/unit/PermissionChecker.test.ts
Labels: core, n8n team

#7958 feat(core): Add package name tag to Sentry errors (no-changelog)
  packages/cli/src/ErrorReporting.ts
  packages/workflow/package.json
  packages/workflow/src/errors/application.error.ts
  pnpm-lock.yaml
Labels: core, n8n team

#7961 ci: Introduce `no-plain-errors` lint rule for BE packages (no-changelog)
  packages/@n8n/client-oauth2/.eslintrc.js
  packages/@n8n/nodes-langchain/nodes/chains/ChainLLM/ChainLlm.node.ts
  packages/@n8n_io/eslint-config/base.js
  packages/@n8n_io/eslint-config/frontend.js
  packages/@n8n_io/eslint-config/local-rules.js
  packages/cli/src/environments/sourceControl/sourceControl.service.ee.ts
  packages/cli/src/environments/sourceControl/sourceControlExport.service.ee.ts
  packages/cli/src/environments/sourceControl/sourceControlPreferences.service.ee.ts
  packages/node-dev/.eslintrc.js
  packages/nodes-base/nodes/CompareDatasets/GenericFunctions.ts
  packages/nodes-base/nodes/Kafka/Kafka.node.ts
  packages/nodes-base/nodes/TheHive/GenericFunctions.ts
Labels: node/improvement, core, n8n team

#7963 refactor(core): Remove unneeded high-frequency log (no-changelog)
  packages/core/src/NodeExecuteFunctions.ts
Labels: core, n8n team, skip-e2e

#7844 feat: Introduce advanced permissions
  cypress/e2e/17-sharing.cy.ts
  cypress/e2e/18-user-management.cy.ts
  cypress/e2e/35-admin-user-smoke-test.cy.ts
  cypress/pages/modals/credentials-modal.ts
  cypress/pages/settings-users.ts
  cypress/pages/settings.ts
  packages/cli/src/controllers/users.controller.ts
  packages/design-system/src/components/N8nFormInput/FormInput.vue
  packages/design-system/src/types/form.ts
  packages/editor-ui/src/Interface.ts
  packages/editor-ui/src/__tests__/router.test.ts
  packages/editor-ui/src/api/invitation.ts
  packages/editor-ui/src/components/CredentialEdit/CredentialConfig.vue
  packages/editor-ui/src/components/CredentialEdit/CredentialEdit.vue
  packages/editor-ui/src/components/CredentialEdit/CredentialInfo.vue
  packages/editor-ui/src/components/CredentialEdit/CredentialSharing.ee.vue
  packages/editor-ui/src/components/InviteUsersModal.vue
  packages/editor-ui/src/components/WorkflowShareModal.ee.vue
  packages/editor-ui/src/constants.ts
  packages/editor-ui/src/mixins/nodeHelpers.ts
  packages/editor-ui/src/permissions.ts
  packages/editor-ui/src/plugins/i18n/locales/en.json
  packages/editor-ui/src/stores/credentials.store.ts
  packages/editor-ui/src/stores/ui.store.ts
  packages/editor-ui/src/stores/users.store.ts
  packages/editor-ui/src/views/SettingsUsersView.vue
Labels: ui, n8n team

#7949 feat: AI nodes usability fixes + Summarization Chain V2
  packages/@n8n/nodes-langchain/nodes/agents/OpenAiAssistant/OpenAiAssistant.node.ts
  packages/@n8n/nodes-langchain/nodes/chains/ChainLLM/ChainLlm.node.ts
  packages/@n8n/nodes-langchain/nodes/chains/ChainSummarization/ChainSummarization.node.ts
  packages/@n8n/nodes-langchain/nodes/chains/ChainSummarization/V1/ChainSummarizationV1.node.ts
  packages/@n8n/nodes-langchain/nodes/chains/ChainSummarization/V2/ChainSummarizationV2.node.ts
  packages/@n8n/nodes-langchain/nodes/chains/ChainSummarization/helpers.ts
  packages/@n8n/nodes-langchain/nodes/document_loaders/DocumentBinaryInputLoader/DocumentBinaryInputLoader.node.ts
  packages/@n8n/nodes-langchain/nodes/document_loaders/DocumentDefaultDataLoader/DocumentDefaultDataLoader.node.ts
  packages/@n8n/nodes-langchain/nodes/document_loaders/DocumentJSONInputLoader/DocumentJsonInputLoader.node.ts
  packages/@n8n/nodes-langchain/utils/N8nBinaryLoader.ts
  packages/@n8n/nodes-langchain/utils/N8nJsonLoader.ts
  packages/@n8n/nodes-langchain/utils/logWrapper.ts
  packages/core/src/NodeExecuteFunctions.ts
  packages/design-system/src/components/N8nNodeCreatorNode/NodeCreatorNode.vue
  packages/design-system/src/components/N8nNotice/Notice.vue
  packages/editor-ui/src/Interface.ts
  packages/editor-ui/src/__tests__/setup.ts
  packages/editor-ui/src/components/Node.vue
  packages/editor-ui/src/components/Node/NodeCreator/ItemTypes/ViewItem.vue
  packages/editor-ui/src/components/Node/NodeCreator/composables/useActions.ts
  packages/editor-ui/src/components/Node/NodeCreator/viewsData.ts
  packages/editor-ui/src/components/RunDataAi/useAiContentParsers.ts
  packages/editor-ui/src/components/WorkflowLMChat.vue
  packages/editor-ui/src/composables/useGlobalLinkActions.ts
  packages/editor-ui/src/constants.ts
  packages/editor-ui/src/mixins/workflowHelpers.ts
  packages/editor-ui/src/mixins/workflowRun.ts
  packages/editor-ui/src/plugins/i18n/locales/en.json
  packages/editor-ui/src/utils/nodeViewUtils.ts
  packages/editor-ui/src/views/NodeView.vue
  packages/editor-ui/src/views/TemplatesWorkflowView.vue
  packages/nodes-base/nodes/OpenAi/OpenAi.node.ts
Labels: core, ui, n8n team

#7946 fix(editor): Return early in ws message handler if no 'command' keyword is found
  packages/editor-ui/src/components/WorkflowPreview.vue
  packages/editor-ui/src/components/__tests__/WorkflowPreview.test.ts
  packages/editor-ui/src/views/NodeView.vue
Labels: ui, n8n team

#7966 ci: Fix lint in `nodes-base` to fix build (no-changelog)
  packages/nodes-base/nodes/Transform/utils/utils.ts
Labels: node/improvement, n8n team

#7962 feat(Google Ads Node): Update to support v15
  packages/nodes-base/nodes/Google/Ads/CampaignDescription.ts
  packages/nodes-base/nodes/Google/Ads/GoogleAds.node.ts
Labels: node/improvement, n8n team

#7968 fix(editor): Prevent opening NDV search if `/` is typed in a contenteditable element
  packages/editor-ui/src/components/RunDataSearch.vue
  packages/editor-ui/src/components/__tests__/RunDataSearch.test.ts
Labels: ui, n8n team

#7972 fix(Google Sheets Node): Prevent erroring when fetching mapping columns
  packages/nodes-base/nodes/Google/Sheet/v2/methods/resourceMapping.ts
Labels: node/improvement, n8n team

#7971 fix(editor): Add missing string for worker in log streaming
  packages/editor-ui/src/plugins/i18n/locales/en.json
Labels: ui, n8n team

#7970 refactor(core): Instrument multi-main to report failures to renew lease
  packages/cli/src/services/orchestration/main/MultiMainSetup.ee.ts
  packages/workflow/src/ErrorReporterProxy.ts
  packages/workflow/src/errors/application.error.ts
Labels: core, n8n team

#7978 fix(editor): Fix collection select label (no-changelog)
  packages/editor-ui/src/components/CollectionParameter.vue
  packages/editor-ui/src/components/__tests__/CollectionParameter.test.ts
Labels: ui, n8n team

#7965 refactor(core): Log any hard-deletion errors during pruning (no-changelog)
  packages/cli/src/services/pruning.service.ts
Labels: node/improvement, core, n8n team

#7981 ci: Send doc URL check result to `#mission-docs` (no-changelog)
  .github/workflows/check-documentation-urls.yml
Labels: n8n team

#7982 refactor(core): Upgrade backend Sentry dependencies to 7.86 (no-changelog)
  packages/cli/package.json
  pnpm-lock.yaml
Labels: core, n8n team

#7973 docs: Replace references to set node (no-changelog)
  packages/editor-ui/src/plugins/i18n/locales/en.json
  packages/nodes-base/nodes/Google/BigQuery/v2/actions/database/insert.operation.ts
  packages/nodes-base/nodes/Google/Sheet/v2/actions/sheet/append.operation.ts
  packages/nodes-base/nodes/MySql/v2/actions/database/insert.operation.ts
  packages/nodes-base/nodes/MySql/v2/actions/database/update.operation.ts
  packages/nodes-base/nodes/MySql/v2/actions/database/upsert.operation.ts
  packages/nodes-base/nodes/NocoDB/OperationDescription.ts
  packages/nodes-base/nodes/Postgres/v2/actions/database/insert.operation.ts
  packages/nodes-base/nodes/Postgres/v2/actions/database/update.operation.ts
  packages/nodes-base/nodes/Postgres/v2/actions/database/upsert.operation.ts
Labels: node/improvement, ui, n8n team

#7985 refactor(core): Introduce naming service (no-changelog)
  packages/cli/src/GenericHelpers.ts
  packages/cli/src/credentials/credentials.controller.ts
  packages/cli/src/services/naming.service.ts
  packages/cli/src/workflows/workflows.controller.ts
  packages/cli/test/unit/services/naming.service.test.ts
Labels: core, n8n team

#7942 feat(Local File Trigger Node): Add polling option typically good to watch network files/folders
  packages/nodes-base/nodes/LocalFileTrigger/LocalFileTrigger.node.ts
Labels: node/improvement, n8n team

#7980 refactor(core): Move instance owner retrieval to ownership service (no-changelog)
  packages/cli/src/UserManagement/UserManagementHelper.ts
  packages/cli/src/commands/execute.ts
  packages/cli/src/commands/executeBatch.ts
  packages/cli/src/environments/sourceControl/sourceControlGit.service.ee.ts
  packages/cli/src/services/ownership.service.ts
  packages/cli/test/unit/services/ownership.service.test.ts
Labels: core, n8n team

#7987 refactor(core): Add project reference for `@n8n/permissions` (no-changelog)
  packages/cli/tsconfig.json
Labels: core, n8n team

#7975 fix(Postgres Node): Do not include id column in upsert fields selection if it's not unique
  packages/nodes-base/nodes/Postgres/v2/methods/resourceMapping.ts
Labels: n8n team, node/issue

#7994 refactor(editor): Rename CollectionCard and CollectionCardCarousel
  packages/editor-ui/src/components/TemplatesInfoCard.vue
  packages/editor-ui/src/components/TemplatesInfoCarousel.vue
  packages/editor-ui/src/components/__tests__/TemplatesInfoCard.test.ts
  packages/editor-ui/src/views/TemplatesSearchView.vue
Labels: ui, n8n team

#7979 refactor(core): Introduce password utility (no-changelog)
  packages/cli/src/Server.ts
  packages/cli/src/UserManagement/UserManagementHelper.ts
  packages/cli/src/auth/methods/email.ts
  packages/cli/src/constants.ts
  packages/cli/src/controllers/e2e.controller.ts
  packages/cli/src/controllers/invitation.controller.ts
  packages/cli/src/controllers/me.controller.ts
  packages/cli/src/controllers/owner.controller.ts
  packages/cli/src/controllers/passwordReset.controller.ts
  packages/cli/src/databases/entities/User.ts
  packages/cli/src/services/password.utility.ts
  packages/cli/src/sso/saml/samlHelpers.ts
  packages/cli/test/integration/invitations.api.test.ts
  packages/cli/test/integration/passwordReset.api.test.ts
  packages/cli/test/integration/shared/random.ts
  packages/cli/test/integration/shared/utils/testServer.ts
  packages/cli/test/unit/controllers/owner.controller.test.ts
  packages/cli/test/unit/utilities/password.utility.test.ts
Labels: core, n8n team

#7989 feat(editor): Show template credential setup based on feature flag
  cypress/e2e/34-template-credentials-setup.cy.ts
  cypress/pages/template-credential-setup.ts
  cypress/support/index.ts
  packages/editor-ui/src/constants.ts
  packages/editor-ui/src/stores/posthog.store.ts
  packages/editor-ui/src/utils/featureFlag.ts
  packages/editor-ui/src/utils/templates/templateActions.ts
  packages/editor-ui/src/views/TemplatesCollectionView.vue
  packages/editor-ui/src/views/TemplatesWorkflowView.vue
Labels: ui, n8n team

#7996 ci: Update PR template to simplify (no-changelog)
  .github/pull_request_template.md
Labels: n8n team

#8002 refactor(core): Don't use DB transactions on ExecutionRepository.createNewExecution
  packages/cli/src/ActiveExecutions.ts
  packages/cli/src/databases/repositories/execution.repository.ts
  packages/cli/test/integration/database/repositories/execution.repository.test.ts
  packages/cli/test/unit/ActiveExecutions.test.ts
Labels: core, n8n team

#7991 feat(core): Add multi-main setup debug endpoint (no-changelog)
  packages/cli/src/ActiveWorkflowRunner.ts
  packages/cli/src/Server.ts
  packages/cli/src/controllers/debug.controller.ts
  packages/cli/src/services/orchestration/main/MultiMainSetup.ee.ts
  packages/cli/test/integration/debug.controller.test.ts
  packages/cli/test/integration/shared/types.ts
  packages/cli/test/integration/shared/utils/testServer.ts
Labels: core, n8n team

#7995 feat: Add config option for external secret update interval
  packages/cli/src/ExternalSecrets/ExternalSecretsManager.ee.ts
  packages/cli/src/ExternalSecrets/constants.ts
  packages/cli/src/ExternalSecrets/externalSecretsHelper.ee.ts
  packages/cli/src/config/schema.ts
Labels: core, n8n team

#7988 fix: Fix issue preventing secrets from loading if the path contains - or /
  packages/cli/src/ExternalSecrets/constants.ts
Labels: core, n8n team

#7908 docs: Replace `http://faircode.io` to `https://faircode.io` in `.md` files
  README.md
  docker/images/n8n/README.md
  packages/@n8n/chat/README.md
  packages/@n8n/nodes-langchain/README.md
  packages/cli/README.md
  packages/core/README.md
  packages/design-system/README.md
  packages/editor-ui/README.md
  packages/node-dev/README.md
  packages/nodes-base/README.md
  packages/workflow/README.md
Labels: node/improvement, core, ui, community

#8000 fix(Webhook Node): Do not create binary data when there is no data in the request
  packages/nodes-base/nodes/Webhook/Webhook.node.ts
Labels: n8n team, node/issue

#8008 docs(editor): Change to Summarize icon and Advanced section description (no-changelog)
  packages/editor-ui/src/plugins/i18n/locales/en.json
  packages/nodes-base/nodes/Transform/Summarize/summarize.svg
Labels: node/improvement, ui, n8n team

#7969 refactor(core): Add telemetry for RBAC roles
  packages/cli/src/Interfaces.ts
  packages/cli/src/InternalHooks.ts
  packages/cli/src/controllers/users.controller.ts
  packages/cli/src/services/user.service.ts
Labels: core, n8n team

#8010 docs: Add aliases to compare datasets node
  packages/nodes-base/nodes/CompareDatasets/CompareDatasets.node.json
Labels: node/improvement, n8n team

#8011 fix(editor): Fix Webhook URL expansion icon
  packages/editor-ui/src/components/NodeWebhooks.vue
Labels: ui, n8n team

#7812 fix(core): Prevent workflow history saving error from happening
  packages/cli/src/workflows/workflowHistory/workflowHistory.service.ee.ts
  packages/cli/src/workflows/workflows.services.ts
  packages/cli/test/unit/WorkflowHelpers.test.ts
  packages/cli/test/unit/services/ownership.service.test.ts
  packages/cli/test/unit/services/workflowHistory.service.ee.test.ts
  packages/cli/test/unit/shared/mockObjects.ts
Labels: core, n8n team

#8015 fix(Postgres Trigger Node): Increase manual trigger timeout from 30 to 60 seconds
  packages/nodes-base/nodes/Postgres/PostgresTrigger.node.ts
Labels: node/improvement, n8n team

#7490 feat(editor): Filter component + implement in If node
  cypress/constants.ts
  cypress/e2e/30-if-node.cy.ts
  cypress/e2e/4-node-creator.cy.ts
  cypress/fixtures/Test_workflow_filter.json
  cypress/pages/ndv.ts
  packages/@n8n/nodes-langchain/nodes/document_loaders/DocumentBinaryInputLoader/DocumentBinaryInputLoader.node.ts
  packages/core/src/ExtractValue.ts
  packages/core/src/NodeExecuteFunctions.ts
  packages/design-system/src/components/N8nInputLabel/InputLabel.vue
  packages/design-system/src/components/ResizeObserver/ResizeObserver.vue
  packages/design-system/src/components/index.ts
  packages/design-system/src/css/common/var.scss
  packages/design-system/src/css/input.scss
  packages/design-system/src/css/select.scss
  packages/design-system/src/plugin.ts
  packages/editor-ui/src/Interface.ts
  packages/editor-ui/src/components/DraggableTarget.vue
  packages/editor-ui/src/components/ExpressionParameterInput.vue
  packages/editor-ui/src/components/FilterConditions/CombinatorSelect.vue
  packages/editor-ui/src/components/FilterConditions/Condition.vue
  packages/editor-ui/src/components/FilterConditions/FilterConditions.vue
  packages/editor-ui/src/components/FilterConditions/OperatorSelect.vue
  packages/editor-ui/src/components/FilterConditions/constants.ts
  packages/editor-ui/src/components/FilterConditions/types.ts
  packages/editor-ui/src/components/FixedCollectionParameter.vue
  packages/editor-ui/src/components/InlineExpressionEditor/theme.ts
  packages/editor-ui/src/components/ParameterInput.vue
  packages/editor-ui/src/components/ParameterInputFull.vue
  packages/editor-ui/src/components/ParameterInputList.vue
  packages/editor-ui/src/components/ParameterInputWrapper.vue
  packages/editor-ui/src/components/ResourceLocator/ResourceLocator.vue
  packages/editor-ui/src/components/ResourceMapper/MappingFields.vue
  packages/editor-ui/src/components/__tests__/FilterConditions.test.ts
  packages/editor-ui/src/plugins/i18n/locales/en.json
  packages/editor-ui/src/stores/ndv.store.ts
  packages/nodes-base/nodes/If/If.node.ts
  packages/nodes-base/nodes/If/V1/IfV1.node.ts
  packages/nodes-base/nodes/If/V2/IfV2.node.ts
  packages/nodes-base/nodes/If/test/v1/IF.boolean.json
  packages/nodes-base/nodes/If/test/v1/IF.date-time.json
  packages/nodes-base/nodes/If/test/v1/IF.number.json
  packages/nodes-base/nodes/If/test/v1/IF.string.json
  packages/nodes-base/nodes/If/test/v1/If.node.test.ts
  packages/nodes-base/nodes/If/test/v2/IfV2.date-time.json
  packages/nodes-base/nodes/If/test/v2/IfV2.node.test.ts
  packages/nodes-base/nodes/If/test/v2/IfV2.number.json
  packages/nodes-base/nodes/If/test/v2/IfV2.other.json
  packages/nodes-base/nodes/If/test/v2/IfV2.string.json
  packages/workflow/src/Interfaces.ts
  packages/workflow/src/NodeHelpers.ts
  packages/workflow/src/NodeParameters/FilterParameter.ts
  packages/workflow/src/TypeValidation.ts
  packages/workflow/src/index.ts
  packages/workflow/src/type-guards.ts
  packages/workflow/test/FilterParameter.test.ts
  packages/workflow/test/TypeValidation.test.ts
Labels: node/improvement, node/new, core, ui, n8n team

#8014 feat: Extend executions page redirect guard
  cypress/e2e/20-workflow-executions.cy.ts
  cypress/pages/workflow-executions-tab.ts
  packages/editor-ui/src/components/ExecutionsList.vue
  packages/editor-ui/src/components/__tests__/ExecutionsList.test.ts
Labels: ui, n8n team

#8013 fix(editor): Fix bug with node names with certain characters
  packages/editor-ui/src/composables/__tests__/useNodeHelpers.test.ts
  packages/editor-ui/src/composables/useNodeHelpers.ts
Labels: ui, n8n team

#7571 feat(n8n Form Trigger Node): Improvements
  cypress/e2e/16-form-trigger-node.cy.ts
  packages/cli/src/AbstractServer.ts
  packages/cli/src/ResponseHelper.ts
  packages/cli/src/WaitingForms.ts
  packages/cli/src/WaitingWebhooks.ts
  packages/cli/src/WebhookHelpers.ts
  packages/cli/src/WorkflowExecuteAdditionalData.ts
  packages/cli/src/config/schema.ts
  packages/cli/src/services/frontend.service.ts
  packages/cli/templates/form-trigger.handlebars
  packages/cli/test/unit/webhooks.test.ts
  packages/core/src/NodeExecuteFunctions.ts
  packages/editor-ui/src/Interface.ts
  packages/editor-ui/src/__tests__/server/endpoints/settings.ts
  packages/editor-ui/src/__tests__/utils.ts
  packages/editor-ui/src/components/CodeNodeEditor/completions/execution.completions.ts
  packages/editor-ui/src/components/NodeWebhooks.vue
  packages/editor-ui/src/components/VariableSelector.vue
  packages/editor-ui/src/mixins/workflowHelpers.ts
  packages/editor-ui/src/mixins/workflowRun.ts
  packages/editor-ui/src/plugins/i18n/index.ts
  packages/editor-ui/src/plugins/i18n/locales/en.json
  packages/editor-ui/src/stores/n8nRoot.store.ts
  packages/editor-ui/src/stores/settings.store.ts
  packages/editor-ui/src/stores/workflows.store.ts
  packages/editor-ui/src/views/NodeView.vue
  packages/nodes-base/nodes/Form/FormTrigger.node.ts
  packages/nodes-base/nodes/Form/common.descriptions.ts
  packages/nodes-base/nodes/Form/interfaces.ts
  packages/nodes-base/nodes/Form/utils.ts
  packages/nodes-base/nodes/Form/v1/FormTriggerV1.node.ts
  packages/nodes-base/nodes/Form/v2/FormTriggerV2.node.ts
  packages/nodes-base/nodes/RespondToWebhook/RespondToWebhook.node.ts
  packages/nodes-base/nodes/Wait/Wait.node.ts
  packages/nodes-base/nodes/Webhook/description.ts
  packages/workflow/src/Interfaces.ts
  packages/workflow/src/TypeValidation.ts
Labels: node/improvement, n8n team

#8017 fix(ActiveCampaign Node): Fix pagination issue when loading tags
  packages/nodes-base/nodes/ActiveCampaign/ActiveCampaign.node.ts
Labels: node/improvement, n8n team

#8020 fix(editor): Show credential share info only to appropriate users
  cypress/e2e/17-sharing.cy.ts
  packages/editor-ui/src/components/CredentialEdit/CredentialSharing.ee.vue
  packages/editor-ui/src/plugins/i18n/locales/en.json
Labels: ui, n8n team

#8005 fix(editor): Turn off executions list auto-refresh after leaving the page
  cypress/e2e/20-workflow-executions.cy.ts
  cypress/pages/workflow-executions-tab.ts
  packages/editor-ui/src/components/ExecutionsList.vue
  packages/editor-ui/src/components/ExecutionsView/ExecutionsList.vue
  packages/editor-ui/src/components/__tests__/ExecutionsList.test.ts
Labels: ui, n8n team

#8022 perf(editor): Improve canvas rendering performance
  packages/editor-ui/src/components/Node.vue
  packages/editor-ui/src/plugins/i18n/index.ts
  packages/editor-ui/src/plugins/jsplumb/N8nAddInputEndpointRenderer.ts
  packages/editor-ui/src/plugins/jsplumb/N8nAddInputEndpointType.ts
  packages/editor-ui/src/plugins/jsplumb/N8nPlusEndpointType.ts
  packages/editor-ui/src/stores/workflows.store.ts
  packages/editor-ui/src/views/NodeView.vue
Labels: ui, n8n team

#7986 fix(editor): Fix dialogVisibleChanged hooks event when meta.value is undefined (no-changelog)
  packages/editor-ui/src/hooks/cloud.ts
Labels: ui, n8n team

#7983 fix(editor): Disable auto scroll and list size check when clicking on executions
  packages/editor-ui/src/components/ExecutionsView/ExecutionsSidebar.vue
Labels: ui, n8n team

#8023 fix(editor): Add back credential `use` permission
  cypress/e2e/17-sharing.cy.ts
  packages/editor-ui/src/composables/useNodeHelpers.ts
  packages/editor-ui/src/permissions.ts
  packages/editor-ui/src/stores/users.store.ts
Labels: ui, n8n team

#8025 fix(core): Initialize queue once in queue mode
  packages/cli/src/commands/worker.ts
  packages/cli/test/integration/commands/worker.cmd.test.ts
Labels: core, n8n team

#8031 fix(core): Restore workflow ID during execution creation
  packages/cli/src/commands/worker.ts
  packages/cli/src/databases/repositories/execution.repository.ts
  packages/cli/test/integration/database/repositories/execution.repository.test.ts
  packages/workflow/src/Workflow.ts
Labels: core, n8n team

#8032 docs: Two small UI copy fixes in sub-nodes
  packages/@n8n/nodes-langchain/nodes/output_parser/OutputParserItemList/OutputParserItemList.node.ts
  packages/@n8n/nodes-langchain/nodes/tools/ToolSerpApi/ToolSerpApi.node.ts
Labels: n8n team

#8034 refactor(core): Warn on sqlite DB detected during init on queue mode
  packages/cli/src/commands/BaseCommand.ts
Labels: core, n8n team

#8016 feat(Filter Node): Overhaul UI by adding the new filter component
  packages/nodes-base/nodes/Filter/Filter.node.ts
  packages/nodes-base/nodes/Filter/V1/FilterV1.node.ts
  packages/nodes-base/nodes/Filter/V1/GenericFunctions.ts
  packages/nodes-base/nodes/Filter/V2/FilterV2.node.ts
  packages/nodes-base/nodes/Filter/test/workflow_v1.json
  packages/nodes-base/nodes/Filter/test/workflow_v2.json
Labels: node/improvement, node/new, n8n team

#8038 refactor(core): Remove ID-less workflow reporting (no-changelog)
  packages/cli/src/commands/worker.ts
  packages/workflow/src/Workflow.ts
Labels: core, n8n team

#8033 refactor(core): Make workflow services injectable (no-changelog)
  packages/cli/src/ActiveWorkflowRunner.ts
  packages/cli/src/PublicApi/v1/handlers/workflows/workflows.handler.ts
  packages/cli/src/WebhookHelpers.ts
  packages/cli/src/WorkflowExecuteAdditionalData.ts
  packages/cli/src/executions/executions.service.ee.ts
  packages/cli/src/workflows/workflow.service.ee.ts
  packages/cli/src/workflows/workflow.service.ts
  packages/cli/src/workflows/workflows.controller.ee.ts
  packages/cli/src/workflows/workflows.controller.ts
  packages/cli/test/integration/ActiveWorkflowRunner.test.ts
  packages/cli/test/integration/publicApi/workflows.test.ts
  packages/cli/test/integration/workflow.service.test.ts
  packages/cli/test/integration/workflows.controller.ee.test.ts
Labels: core, n8n team

#8043 fix(core): Remove circular references before serializing executions in public API
  packages/cli/src/PublicApi/v1/handlers/executions/executions.handler.ts
  packages/core/package.json
  packages/workflow/src/index.ts
  packages/workflow/src/utils.ts
  pnpm-lock.yaml
Labels: core, n8n team

#8044 fix(core): Public API support node's deprecated continueOnFail to upload old workflows (no-changelog)
  packages/cli/src/PublicApi/v1/handlers/workflows/spec/schemas/node.yml
Labels: core, n8n team

#8046 fix(core): Handle multiple termination signals correctly
  packages/cli/src/commands/BaseCommand.ts
Labels: core, n8n team

#8030 fix(HTTP Request Node): Do not create circular references in HTTP request node output
  packages/nodes-base/nodes/HttpRequest/V1/HttpRequestV1.node.ts
  packages/nodes-base/nodes/HttpRequest/V2/HttpRequestV2.node.ts
  packages/nodes-base/nodes/HttpRequest/V3/HttpRequestV3.node.ts
Labels: node/improvement, core, n8n team

#8049 feat: Add config option to prefer GET request over LIST when using Hashicorp Vault
  packages/cli/src/ExternalSecrets/externalSecretsHelper.ee.ts
  packages/cli/src/ExternalSecrets/providers/vault.ts
  packages/cli/src/config/schema.ts
Labels: core, n8n team

#8053 fix(editor): Cleanup Executions page component
  packages/editor-ui/src/components/ExecutionsList.vue
Labels: ui, n8n team

#8047 fix(core): Fix shutdown if terminating before hooks are initialized
  packages/cli/src/commands/BaseCommand.ts
  packages/cli/src/commands/start.ts
  packages/cli/src/commands/webhook.ts
  packages/cli/src/commands/worker.ts
Labels: core, n8n team

#8054 fix(editor): Update wording when an instance owner or admin is viewing a credential they do not own
  packages/editor-ui/src/plugins/i18n/locales/en.json
Labels: ui, n8n team

#8050 fix(core): Consider timeout in shutdown an error
  packages/cli/src/commands/BaseCommand.ts
  packages/cli/src/commands/start.ts
  packages/cli/src/commands/webhook.ts
  packages/cli/src/commands/worker.ts
  packages/cli/src/config/schema.ts
Labels: core, n8n team

#8071 ci(core): Improve circular dependency reporting in typedi (no-changelog)
  patches/typedi@0.10.0.patch
  pnpm-lock.yaml
Labels: n8n team

#8068 feat(core): Add N8N_GRACEFUL_SHUTDOWN_TIMEOUT env var
  packages/cli/src/commands/BaseCommand.ts
  packages/cli/src/commands/worker.ts
  packages/cli/src/config/schema.ts
Labels: core, n8n team

#8026 refactor(core): Update backend sentry setup to reduce noise (no-changelog)
  packages/cli/package.json
  packages/cli/src/ErrorReporting.ts
  pnpm-lock.yaml
Labels: core, n8n team

#8066 refactor(core): Inject dependencies into workflow services (no-changelog)
  packages/cli/src/executions/executions.service.ee.ts
  packages/cli/src/workflows/workflow.service.ee.ts
  packages/cli/src/workflows/workflow.service.ts
  packages/cli/src/workflows/workflows.controller.ee.ts
  packages/cli/test/integration/publicApi/workflows.test.ts
  packages/cli/test/integration/workflow.service.test.ts
  packages/cli/test/integration/workflows.controller.ee.test.ts
  packages/cli/test/integration/workflows.controller.test.ts
Labels: core, n8n team

#8072 refactor(editor): Add telemetry for workflow history (no-changelog)
  packages/editor-ui/src/views/WorkflowHistory.vue
  packages/editor-ui/src/views/__tests__/WorkflowHistory.test.ts
Labels: ui, n8n team

#8074 refactor(core): Move license endpoints to a decorated controller class (no-changelog)
  packages/@n8n/permissions/src/types.ts
  packages/cli/src/Server.ts
  packages/cli/src/databases/repositories/workflow.repository.ts
  packages/cli/src/license/License.service.ts
  packages/cli/src/license/license.controller.ts
  packages/cli/src/license/license.service.ts
  packages/cli/src/permissions/roles.ts
  packages/cli/src/telemetry/index.ts
  packages/cli/test/integration/license.api.test.ts
  packages/cli/test/integration/shared/utils/testServer.ts
  packages/cli/test/unit/License.test.ts
  packages/cli/test/unit/Telemetry.test.ts
  packages/cli/test/unit/license/license.service.test.ts
Labels: core, n8n team

#8073 refactor(editor): Add telemetry for debug in editor (no-changelog)
  packages/editor-ui/src/Interface.ts
  packages/editor-ui/src/composables/useExecutionDebugging.ts
Labels: ui, n8n team

#8086 fix(core): Use relative imports for dynamic imports in SecurityAuditService
  packages/cli/src/security-audit/SecurityAudit.service.ts
Labels: core, n8n team

#8075 refactor(editor): Add telemetry for log streaming (no-changelog)
  packages/editor-ui/src/components/SettingsLogStreaming/EventDestinationSettingsModal.ee.vue
Labels: ui, n8n team

#8076 ci: Remove unnecessary async/await, enable await-thenable linting rule (no-changelog)
  packages/@n8n_io/eslint-config/base.js
  packages/cli/package.json
  packages/cli/src/ActiveWorkflowRunner.ts
  packages/cli/src/CredentialsHelper.ts
  packages/cli/src/Server.ts
  packages/cli/src/UserManagement/PermissionChecker.ts
  packages/cli/src/UserManagement/UserManagementHelper.ts
  packages/cli/src/WorkflowHelpers.ts
  packages/cli/src/commands/start.ts
  packages/cli/src/controllers/passwordReset.controller.ts
  packages/cli/src/controllers/workflowStatistics.controller.ts
  packages/cli/src/credentials/credentials.controller.ee.ts
  packages/cli/src/credentials/credentials.controller.ts
  packages/cli/src/credentials/credentials.service.ee.ts
  packages/cli/src/credentials/credentials.service.ts
  packages/cli/src/databases/entities/User.ts
  packages/cli/src/databases/repositories/sharedCredentials.repository.ts
  packages/cli/src/decorators/registerController.ts
  packages/cli/src/executions/executions.service.ts
  packages/cli/src/workflows/workflow.service.ts
  packages/cli/src/workflows/workflowHistory/workflowHistory.service.ee.ts
  packages/cli/src/workflows/workflows.controller.ee.ts
  packages/cli/src/workflows/workflows.controller.ts
  packages/cli/test/unit/repositories/sharedCredentials.repository.test.ts
  packages/nodes-base/nodes/Redis/Redis.node.ts
  packages/workflow/test/RoutingNode.test.ts
  pnpm-lock.yaml
Labels: core, n8n team

#7826 feat: Add opt-in enterprise license trial checkbox (no-changelog)
  packages/design-system/src/components/N8nFormInputs/FormInputs.vue
  packages/editor-ui/src/api/usage.ts
  packages/editor-ui/src/components/PersonalizationModal.vue
  packages/editor-ui/src/plugins/i18n/locales/en.json
  packages/editor-ui/src/stores/usage.store.ts
  packages/editor-ui/src/utils/apiUtils.ts
Labels: ui, n8n team

#8095 refactor(Discord Node): Stop reporting to Sentry inaccessible guild error (no-changelog)
  packages/nodes-base/nodes/Discord/v2/helpers/utils.ts
Labels: node/improvement, n8n team

#8007 fix(core): Do not display error when stopping jobless execution in queue mode
  packages/cli/src/Server.ts
Labels: core, n8n team

#7713 fix: Upgrade axios to address CVE-2023-45857
  packages/@n8n/client-oauth2/package.json
  packages/cli/package.json
  packages/cli/src/ExternalSecrets/providers/vault.ts
  packages/cli/src/eventbus/MessageEventBusDestination/MessageEventBusDestinationWebhook.ee.ts
  packages/core/package.json
  packages/core/src/NodeExecuteFunctions.ts
  packages/core/src/ObjectStore/ObjectStore.service.ee.ts
  packages/core/src/ObjectStore/types.ts
  packages/editor-ui/package.json
  packages/editor-ui/src/utils/apiUtils.ts
  pnpm-lock.yaml
Labels: core, ui, n8n team

#8090 feat(core): Upgrade Rudderstack SDK (no-changelog)
  packages/cli/package.json
  packages/cli/src/telemetry/index.ts
  pnpm-lock.yaml
Labels: core, n8n team

#8056 refactor: Add telemetry for RBAC (no-changelog)
  packages/cli/src/databases/repositories/role.repository.ts
  packages/cli/src/telemetry/index.ts
  packages/cli/test/integration/role.repository.test.ts
  packages/editor-ui/src/Interface.ts
  packages/editor-ui/src/components/InviteUsersModal.vue
Labels: core, ui, n8n team

#8094 feat(editor): De-duplicate frontend devDependencies (no-changelog)
  packages/@n8n/chat/package.json
  packages/@n8n_io/eslint-config/package.json
  packages/design-system/package.json
  packages/editor-ui/package.json
  pnpm-lock.yaml
Labels: ui, n8n team

#8100 feat(editor): Upgrade frontend tooling to address a few vulnerabilities
  package.json
  packages/@n8n/chat/package.json
  packages/design-system/package.json
  packages/design-system/src/components/N8nActionBox/__tests__/__snapshots__/ActionBox.spec.ts.snap
  packages/design-system/src/components/N8nActionDropdown/__tests__/__snapshots__/ActionDropdown.spec.ts.snap
  packages/design-system/src/components/N8nBadge/__tests__/__snapshots__/Badge.spec.ts.snap
  packages/design-system/src/components/N8nButton/__tests__/__snapshots__/Button.spec.ts.snap
  packages/design-system/src/components/N8nCallout/__tests__/__snapshots__/Callout.spec.ts.snap
  packages/design-system/src/components/N8nCard/__tests__/__snapshots__/Card.spec.ts.snap
  packages/design-system/src/components/N8nCircleLoader/__tests__/__snapshots__/CircleLoader.spec.ts.snap
  packages/design-system/src/components/N8nDatatable/__tests__/__snapshots__/Datatable.spec.ts.snap
  packages/design-system/src/components/N8nInfoTip/__tests__/__snapshots__/InfoTip.spec.ts.snap
  packages/design-system/src/components/N8nInput/__tests__/__snapshots__/Input.spec.ts.snap
  packages/design-system/src/components/N8nNotice/__tests__/__snapshots__/Notice.spec.ts.snap
  packages/design-system/src/components/N8nRecycleScroller/__tests__/__snapshots__/RecycleScroller.spec.ts.snap
  packages/design-system/src/components/N8nSelect/__tests__/__snapshots__/Select.spec.ts.snap
  packages/design-system/src/components/N8nTree/__tests__/__snapshots__/Tree.spec.ts.snap
  pnpm-lock.yaml
Labels: ui, n8n team

#8091 ci: Suggestions for #8082 (no-changelog)
  packages/cli/src/WorkflowExecuteAdditionalData.ts
  packages/cli/src/executionLifecycleHooks/restoreBinaryDataId.ts
  packages/cli/test/unit/execution-lifecyle/restoreBinaryDataId.test.ts
Labels: core, n8n team

#8103 fix(editor): Fix copy/paste issue when switch node is in workflow
  cypress/e2e/10-undo-redo.cy.ts
  cypress/fixtures/Test_workflow_form_switch.json
  cypress/pages/workflow.ts
  packages/editor-ui/src/components/Node.vue
  packages/editor-ui/src/stores/nodeTypes.store.ts
Labels: ui, n8n team

#8009 fix(editor): Ensure execution data overrides pinned data when copying in executions view
  packages/editor-ui/src/components/RunDataJsonActions.vue
Labels: ui, n8n team

#8102 refactor(editor): Add telemetry for SSO/SAML (no-changelog)
  packages/editor-ui/src/views/SettingsSso.vue
Labels: ui, n8n team

#8067 fix(editor): Move versions check to init function and refactor store (no-changelog)
  cypress/composables/versions.ts
  cypress/e2e/36-versions.cy.ts
  packages/editor-ui/src/App.vue
  packages/editor-ui/src/__tests__/init.test.ts
  packages/editor-ui/src/components/MainSidebar.vue
  packages/editor-ui/src/components/UpdatesPanel.vue
  packages/editor-ui/src/components/VersionCard.vue
  packages/editor-ui/src/init.ts
  packages/editor-ui/src/mixins/newVersions.ts
  packages/editor-ui/src/stores/versions.store.ts
Labels: ui, n8n team

#8107 fix(core): Downgrade Rudderstack SDK (no-changelog)
  packages/cli/package.json
  packages/cli/src/telemetry/index.ts
  pnpm-lock.yaml
Labels: core, n8n team

#8024 fix(editor): Make keyboard shortcuts more strict; don't accept extra Ctrl/Alt/Shift keys
  cypress/e2e/25-stickies.cy.ts
  packages/editor-ui/src/views/NodeView.vue
Labels: ui, n8n team

#8106 ci: Fix Postgres and MySQL tests (no-changelog)
  .github/workflows/ci-postgres-mysql.yml
  packages/cli/package.json
  packages/cli/src/databases/repositories/role.repository.ts
Labels: core, n8n team

#8051 docs: Add notice to TheHive triggers to highlight manual steps
  packages/nodes-base/nodes/TheHive/TheHiveTrigger.node.ts
  packages/nodes-base/nodes/TheHiveProject/TheHiveProjectTrigger.node.ts
Labels: node/improvement, n8n team

#8113 feat: Add option to `returnIntermediateSteps` for AI agents
  packages/@n8n/nodes-langchain/nodes/agents/Agent/agents/ConversationalAgent/description.ts
  packages/@n8n/nodes-langchain/nodes/agents/Agent/agents/ConversationalAgent/execute.ts
  packages/@n8n/nodes-langchain/nodes/agents/Agent/agents/OpenAiFunctionsAgent/description.ts
  packages/@n8n/nodes-langchain/nodes/agents/Agent/agents/OpenAiFunctionsAgent/execute.ts
  packages/@n8n/nodes-langchain/nodes/agents/Agent/agents/ReActAgent/description.ts
  packages/@n8n/nodes-langchain/nodes/agents/Agent/agents/ReActAgent/execute.ts
  packages/@n8n/nodes-langchain/nodes/tools/ToolWikipedia/ToolWikipedia.node.ts
Labels: n8n team

#8082 fix: Stop binary data restoration from preventing execution from finishing
  packages/cli/src/executionLifecycleHooks/restoreBinaryDataId.ts
  packages/cli/test/unit/execution-lifecyle/restoreBinaryDataId.test.ts
Labels: core, n8n team

#8093 feat(Respond to Webhook Node): Overhaul with improvements like returning all items
  packages/nodes-base/nodes/RespondToWebhook/RespondToWebhook.node.ts
Labels: node/improvement, n8n team

#8104 feat(core): Remove discontinued crypto-js
  packages/cli/BREAKING-CHANGES.md
  packages/workflow/package.json
  packages/workflow/src/Extensions/StringExtensions.ts
  packages/workflow/test/ExpressionExtensions/StringExtensions.test.ts
  pnpm-lock.yaml
Labels: core, n8n team

#8089 ci: Add lint rule `no-dynamic-import-template` (no-changelog)
  packages/@n8n_io/eslint-config/local-rules.js
  packages/cli/.eslintrc.js
Labels: core, n8n team

#8006 refactor(core): Move error execution creation to execution service (no-changelog)
  packages/cli/src/ActiveWorkflowRunner.ts
  packages/cli/src/GenericHelpers.ts
  packages/cli/src/UserManagement/UserManagementHelper.ts
  packages/cli/src/credentials/credentials.service.ts
  packages/cli/src/executions/executions.service.ts
  packages/cli/test/integration/ActiveWorkflowRunner.test.ts
  packages/cli/test/integration/auth.mw.test.ts
  packages/cli/test/integration/publicApi/workflows.test.ts
  packages/cli/test/integration/shared/utils/index.ts
  packages/cli/test/integration/users.api.test.ts
Labels: core, n8n team

#7708 feat(core): Add closeFunction support to Sub-Nodes
  packages/@n8n/nodes-langchain/nodes/memory/MemoryRedisChat/MemoryRedisChat.node.ts
  packages/core/src/NodeExecuteFunctions.ts
  packages/core/src/WorkflowExecute.ts
  packages/workflow/src/Interfaces.ts
  packages/workflow/src/RoutingNode.ts
  packages/workflow/src/Workflow.ts
Labels: core, n8n team

#8110 feat: Add new versions of AI nodes with new chat trigger defaults
  packages/@n8n/nodes-langchain/nodes/agents/Agent/Agent.node.ts
  packages/@n8n/nodes-langchain/nodes/agents/Agent/agents/ConversationalAgent/description.ts
  packages/@n8n/nodes-langchain/nodes/agents/Agent/agents/OpenAiFunctionsAgent/description.ts
  packages/@n8n/nodes-langchain/nodes/agents/Agent/agents/PlanAndExecuteAgent/description.ts
  packages/@n8n/nodes-langchain/nodes/agents/Agent/agents/ReActAgent/description.ts
  packages/@n8n/nodes-langchain/nodes/agents/OpenAiAssistant/OpenAiAssistant.node.ts
  packages/@n8n/nodes-langchain/nodes/chains/ChainLLM/ChainLlm.node.ts
  packages/@n8n/nodes-langchain/nodes/chains/ChainRetrievalQA/ChainRetrievalQa.node.ts
  packages/@n8n/nodes-langchain/nodes/memory/MemoryBufferWindow/MemoryBufferWindow.node.ts
  packages/@n8n/nodes-langchain/nodes/memory/MemoryMotorhead/MemoryMotorhead.node.ts
  packages/@n8n/nodes-langchain/nodes/memory/MemoryRedisChat/MemoryRedisChat.node.ts
  packages/@n8n/nodes-langchain/nodes/memory/MemoryXata/MemoryXata.node.ts
  packages/@n8n/nodes-langchain/nodes/memory/MemoryZep/MemoryZep.node.ts
  packages/@n8n/nodes-langchain/nodes/trigger/ChatTrigger/ChatTrigger.node.ts
  packages/editor-ui/src/__tests__/defaults.ts
  packages/editor-ui/src/components/WorkflowLMChat.vue
  packages/editor-ui/src/composables/useNodeHelpers.ts
  packages/editor-ui/src/stores/workflows.store.ts
Labels: ui, n8n team

#8087 feat(Snowflake Node): Update snowflake-sdk (no-changelog)
  packages/nodes-base/package.json
  pnpm-lock.yaml
Labels: n8n team

#8109 fix: Show public API upgrade CTA when feature is not enabled
  cypress/e2e/27-cloud.cy.ts
  cypress/e2e/27-opt-in-trial-banner.cy.ts
  cypress/fixtures/Plan_data_opt_in_trial.json
  cypress/pages/index.ts
  cypress/pages/settings-public-api.ts
  packages/editor-ui/src/router.ts
  packages/editor-ui/src/views/SettingsApiView.vue
Labels: ui, n8n team

#8128 fix(core): Remove circular dependency in WorkflowService and ActiveWorkflowRunner
  packages/cli/src/ActiveWorkflowRunner.ts
  packages/cli/src/WebhookHelpers.ts
  packages/cli/src/WorkflowExecuteAdditionalData.ts
  packages/cli/src/databases/repositories/workflow.repository.ts
  packages/cli/src/executions/executions.service.ee.ts
  packages/cli/src/workflows/workflow.service.ee.ts
  packages/cli/src/workflows/workflow.service.ts
  packages/cli/src/workflows/workflowStaticData.service.ts
  packages/cli/src/workflows/workflows.controller.ee.ts
Labels: core, n8n team

#8125 refactor(Peekalink Node): Stricter typing for Peekalink api call + Tests (no-changelog)
  packages/nodes-base/.eslintrc.js
  packages/nodes-base/nodes/Peekalink/GenericFunctions.ts
  packages/nodes-base/nodes/Peekalink/Peekalink.node.ts
  packages/nodes-base/nodes/Peekalink/test/Peekalink.node.test.ts
  packages/nodes-base/test/nodes/ExecuteWorkflow.ts
  packages/nodes-base/test/nodes/Helpers.ts
Labels: node/improvement, n8n team

#8129 fix(Redis Trigger Node): Activating a workflow with a Redis trigger fails
  packages/nodes-base/nodes/Redis/RedisTrigger.node.ts
Labels: node/improvement, n8n team

#8114 fix(editor): Fix operation change failing in certain conditions
  cypress/e2e/5-ndv.cy.ts
  cypress/pages/ndv.ts
  packages/editor-ui/src/components/NodeSettings.vue
Labels: ui, n8n team

#8118 fix(editor): Prevent canvas undo/redo when NDV is open
  cypress/e2e/10-undo-redo.cy.ts
  packages/editor-ui/src/components/AboutModal.vue
  packages/editor-ui/src/composables/__tests__/useHistoryHelper.test.ts
  packages/editor-ui/src/composables/useHistoryHelper.ts
  packages/editor-ui/src/stores/ndv.store.ts
  packages/editor-ui/src/stores/ui.store.ts
Labels: ui, n8n team

#8099 feat: Update Chat Trigger node (no-changelog)
  packages/@n8n/chat/README.md
  packages/@n8n/chat/build.config.js
  packages/@n8n/chat/package.json
  packages/@n8n/chat/resources/workflow-manual.json
  packages/@n8n/chat/resources/workflow.json
  packages/@n8n/chat/scripts/postbuild.js
  packages/@n8n/chat/src/App.vue
  packages/@n8n/chat/src/__stories__/App.stories.ts
  packages/@n8n/chat/src/__tests__/index.spec.ts
  packages/@n8n/chat/src/__tests__/utils/create.ts
  packages/@n8n/chat/src/__tests__/utils/fetch.ts
  packages/@n8n/chat/src/__tests__/utils/selectors.ts
  packages/@n8n/chat/src/api/message.ts
  packages/@n8n/chat/src/components/Chat.vue
  packages/@n8n/chat/src/components/ChatWindow.vue
  packages/@n8n/chat/src/components/GetStarted.vue
  packages/@n8n/chat/src/components/GetStartedFooter.vue
  packages/@n8n/chat/src/components/Input.vue
  packages/@n8n/chat/src/components/Layout.vue
  packages/@n8n/chat/src/components/Message.vue
  packages/@n8n/chat/src/components/MessageTyping.vue
  packages/@n8n/chat/src/components/MessagesList.vue
  packages/@n8n/chat/src/composables/useChat.ts
  packages/@n8n/chat/src/composables/useI18n.ts
  packages/@n8n/chat/src/composables/useOptions.ts
  packages/@n8n/chat/src/constants/defaults.ts
  packages/@n8n/chat/src/constants/symbols.ts
  packages/@n8n/chat/src/css/_tokens.scss
  packages/@n8n/chat/src/css/index.scss
  packages/@n8n/chat/src/event-buses/chatEventBus.ts
  packages/@n8n/chat/src/index.ts
  packages/@n8n/chat/src/main.scss
  packages/@n8n/chat/src/plugins/chat.ts
  packages/@n8n/chat/src/types/chat.ts
  packages/@n8n/chat/src/types/options.ts
  packages/@n8n/chat/tsconfig.json
  packages/@n8n/chat/vite.config.ts
  packages/@n8n/nodes-langchain/nodes/trigger/ChatTrigger/ChatTrigger.node.ts
  packages/@n8n/nodes-langchain/nodes/trigger/ChatTrigger/templates.ts
  packages/design-system/src/css/_tokens.scss
  packages/editor-ui/package.json
  packages/editor-ui/src/components/ChatEmbedModal.vue
  packages/editor-ui/src/components/NodeDetailsView.vue
  packages/editor-ui/src/components/NodeExecuteButton.vue
  packages/editor-ui/src/components/NodeWebhooks.vue
  packages/editor-ui/src/components/ParameterInputList.vue
  packages/editor-ui/src/components/TriggerPanel.vue
  packages/editor-ui/src/components/WorkflowLMChat.vue
  packages/editor-ui/src/constants.ts
  packages/editor-ui/src/mixins/genericHelpers.ts
  packages/editor-ui/src/n8n-theme.scss
  packages/editor-ui/src/plugins/i18n/locales/en.json
  packages/editor-ui/src/rbac/middleware/guest.ts
  packages/editor-ui/src/views/SigninView.vue
  packages/editor-ui/tsconfig.json
  packages/editor-ui/vite.config.mts
  packages/workflow/src/Interfaces.ts
  pnpm-lock.yaml
Labels: n8n team

#8101 refactor(core): Move active workflows endpoints to a decorated controller class (no-changelog)
  cypress/e2e/30-editor-after-route-changes.cy.ts
  packages/cli/src/ActiveWorkflowRunner.ts
  packages/cli/src/Server.ts
  packages/cli/src/controllers/activeWorkflows.controller.ts
  packages/cli/src/databases/repositories/sharedWorkflow.repository.ts
  packages/cli/src/databases/repositories/workflow.repository.ts
  packages/cli/src/services/activeWorkflows.service.ts
  packages/cli/test/integration/ActiveWorkflowRunner.test.ts
  packages/cli/test/unit/services/activeWorkflows.service.test.ts
  packages/core/src/ActiveWorkflows.ts
  packages/editor-ui/src/api/workflows.ts
  packages/editor-ui/src/stores/workflows.store.ts
Labels: core, n8n team

#8105 refactor(core): Upgrade more dependencies to remove axios 0.x (no-changelog)
  docker/images/n8n/README.md
  package.json
  packages/cli/package.json
  packages/cli/src/commands/start.ts
  pnpm-lock.yaml
Labels: core, n8n team

#8097 feat(core): Unify application components shutdown
  packages/cli/src/AbstractServer.ts
  packages/cli/src/ActiveWorkflowRunner.ts
  packages/cli/src/License.ts
  packages/cli/src/Server.ts
  packages/cli/src/WebhookServer.ts
  packages/cli/src/commands/BaseCommand.ts
  packages/cli/src/commands/start.ts
  packages/cli/src/commands/webhook.ts
  packages/cli/src/decorators/OnShutdown.ts
  packages/cli/src/push/abstract.push.ts
  packages/cli/src/push/index.ts
  packages/cli/src/services/pruning.service.ts
  packages/cli/src/shutdown/Shutdown.service.ts
  packages/cli/test/unit/decorators/OnShutdown.test.ts
  packages/cli/test/unit/shutdown/Shutdown.service.test.ts
Labels: core, n8n team

#8124 feat(editor): Add node execution status indicator to output panel
  cypress/e2e/5-ndv.cy.ts
  cypress/pages/ndv.ts
  packages/design-system/src/components/N8nInfoTip/InfoTip.vue
  packages/design-system/src/components/N8nInfoTip/__tests__/__snapshots__/InfoTip.spec.ts.snap
  packages/design-system/src/components/N8nTooltip/Tooltip.vue
  packages/editor-ui/src/components/OutputPanel.vue
  packages/editor-ui/src/components/RunInfo.vue
  packages/editor-ui/src/components/__tests__/__snapshots__/RunDataSchema.test.ts.snap
  packages/editor-ui/src/mixins/executionsHelpers.ts
  packages/editor-ui/src/mixins/genericHelpers.ts
  packages/editor-ui/src/plugins/i18n/locales/en.json
  packages/editor-ui/src/utils/formatters/dateFormatter.ts
Labels: ui, n8n team

#8139 refactor(core): Move some `typeorm` operators to repositories (no-changelog)
  packages/cli/src/databases/repositories/tag.repository.ts
  packages/cli/src/databases/repositories/workflow.repository.ts
  packages/cli/src/workflows/workflow.service.ee.ts
  packages/cli/src/workflows/workflow.service.ts
  packages/cli/src/workflows/workflows.controller.ee.ts
  packages/cli/src/workflows/workflows.controller.ts
Labels: core, n8n team

#8116 fix(editor): Prevent browser zoom when scrolling inside sticky edit mode
  packages/design-system/src/components/N8nSticky/Sticky.vue
Labels: ui, n8n team

#8126 fix(editor): Avoid sanitizing output to search node data
  cypress/e2e/5-ndv.cy.ts
  cypress/fixtures/Test_workflow_xml_output.json
  packages/editor-ui/src/components/RunDataJson.vue
  packages/editor-ui/src/components/RunDataSchemaItem.vue
  packages/editor-ui/src/components/RunDataTable.vue
  packages/editor-ui/src/components/TextWithHighlights.vue
  packages/editor-ui/src/components/__tests__/TextWithHIghlights.test.ts
  packages/editor-ui/src/utils/__tests__/htmlUtils.test.ts
  packages/editor-ui/src/utils/htmlUtils.ts
Labels: ui, n8n team

#8088 feat(editor): Add template Id to workflow metadata
  cypress/e2e/29-templates.cy.ts
  cypress/pages/templates.ts
  packages/editor-ui/src/Interface.ts
  packages/editor-ui/src/components/MainHeader/WorkflowDetails.vue
  packages/editor-ui/src/mixins/workflowHelpers.ts
  packages/editor-ui/src/stores/workflows.store.ts
  packages/editor-ui/src/views/NodeView.vue
Labels: ui, n8n team

#8141 refactor(core): Move all base URLs to UrlService (no-changelog)
  packages/cli/src/GenericHelpers.ts
  packages/cli/src/PublicApi/index.ts
  packages/cli/src/UserManagement/UserManagementHelper.ts
  packages/cli/src/WebhookHelpers.ts
  packages/cli/src/WorkflowExecuteAdditionalData.ts
  packages/cli/src/commands/start.ts
  packages/cli/src/controllers/oauth/abstractOAuth.controller.ts
  packages/cli/src/controllers/passwordReset.controller.ts
  packages/cli/src/environments/variables/environmentHelpers.ts
  packages/cli/src/environments/variables/variables.service.ee.ts
  packages/cli/src/services/frontend.service.ts
  packages/cli/src/services/url.service.ts
  packages/cli/src/services/user.service.ts
  packages/cli/src/sso/saml/routes/saml.controller.ee.ts
  packages/cli/src/sso/saml/saml.service.ee.ts
  packages/cli/src/sso/saml/serviceProvider.ee.ts
Labels: core, n8n team

#8140 docs: Improve documentation for the toTitleCase function
  packages/workflow/src/Extensions/StringExtensions.ts
Labels: core, n8n team

#8142 refactor(core): Delete unused code, and fix typings in tests (no-changelog)
  packages/cli/src/WorkflowCredentials.ts
  packages/cli/test/integration/credentials.controller.test.ts
  packages/cli/test/integration/database/repositories/execution.repository.test.ts
  packages/cli/test/unit/CredentialsHelper.test.ts
  packages/cli/test/unit/InternalHooks.test.ts
  packages/cli/test/unit/Telemetry.test.ts
  packages/cli/test/unit/WorkflowCredentials.test.ts
Labels: core, n8n team

#8143 refactor(core): Move more `typeorm` operators to repositories (no-changelog)
  packages/cli/src/credentials/credentials.controller.ee.ts
  packages/cli/src/credentials/credentials.service.ee.ts
  packages/cli/src/databases/repositories/credentials.repository.ts
  packages/cli/src/databases/repositories/execution.repository.ts
  packages/cli/src/databases/repositories/executionData.repository.ts
  packages/cli/src/databases/repositories/workflow.repository.ts
  packages/cli/src/databases/repositories/workflowHistory.repository.ts
  packages/cli/src/security-audit/risk-reporters/CredentialsRiskReporter.ts
  packages/cli/src/services/naming.service.ts
  packages/cli/src/workflows/workflowHistory/workflowHistoryManager.ee.ts
  packages/cli/test/unit/services/naming.service.test.ts
Labels: core, n8n team

#8145 refactor(core): Move `typeorm` operators from `PruningService` to `ExecutionRepository` (no-changelog)
  packages/cli/src/databases/repositories/execution.repository.ts
  packages/cli/src/services/pruning.service.ts
Labels: core, n8n team
