Repository n8n-io/n8n, pull requests merged in 2023-02, with the labels that each got.

#5319 fix(core): Revert back to console logging in config (no-changelog)
  packages/cli/src/config/index.ts
Labels: core, n8n team, skip-e2e

#5321 fix(YouTube Node): Update description for channel id (no-changelog)
  packages/nodes-base/nodes/Google/YouTube/ChannelDescription.ts
Labels: node/improvement, n8n team

#5320 feat(YouTube Node): Switch upload operation over to streaming and resumable uploads api
  packages/nodes-base/nodes/Google/YouTube/YouTube.node.ts
Labels: node/improvement, n8n team, skip-e2e

#5217 fix(core): Fix value resolution in declarative node design
  packages/workflow/src/RoutingNode.ts
  packages/workflow/test/RoutingNode.test.ts
Labels: core, n8n team

#5161 feat(core): Simplify pagination in declarative node design
  packages/workflow/src/Interfaces.ts
  packages/workflow/src/RoutingNode.ts
Labels: core, n8n team

#5259 fix(editor): Stop unsaved changes popup display when navigating away from an untouched workflow
  packages/editor-ui/src/components/ExecutionsView/ExecutionsList.vue
  packages/editor-ui/src/stores/workflows.ts
  packages/editor-ui/src/utils/canvasUtils.ts
  packages/editor-ui/src/views/NodeView.vue
Labels: ui, n8n team

#5314 fix: Update app screenshot in README to match latest design (no-changelog)
  assets/n8n-screenshot.png
Labels: community

#5235 feat(Salesforce Node): Add HasOptedOutOfEmail field to lead resource
  packages/nodes-base/nodes/Salesforce/LeadDescription.ts
  packages/nodes-base/nodes/Salesforce/LeadInterface.ts
  packages/nodes-base/nodes/Salesforce/Salesforce.node.ts
Labels: node/improvement, n8n team

#5327 fix(core): Fix oauth2 client credentials not always working
  packages/core/src/NodeExecuteFunctions.ts
Labels: core, n8n team, skip-e2e

#5133 fix(Schedule Trigger Node): Change scheduler behaviour for intervals days and hours
  packages/nodes-base/nodes/Schedule/GenericFunctions.ts
  packages/nodes-base/nodes/Schedule/ScheduleTrigger.node.ts
  packages/nodes-base/nodes/Schedule/SchedulerInterface.ts
Labels: node/improvement, n8n team

#5328 fix(Mailchimp Trigger Node): Fix webhook recreation
  packages/cli/src/workflows/workflows.services.ts
  packages/nodes-base/nodes/Mailchimp/MailchimpTrigger.node.ts
Labels: node/improvement, core, n8n team, skip-e2e

#5324 fix(Linear Node): Fix pagination issue for get all issues
  packages/nodes-base/nodes/Linear/Queries.ts
Labels: node/improvement, n8n team, skip-e2e

#5332 refactor(Code Node): Remove disallowed syntax checks
  packages/nodes-base/nodes/Code/Sandbox.ts
Labels: node/improvement, n8n team

#5302 fix(editor): Set max width for executions list
  packages/editor-ui/src/App.vue
  packages/editor-ui/src/components/ExecutionsList.vue
  packages/editor-ui/src/components/layouts/PageViewLayout.vue
  packages/editor-ui/src/views/NodeView.vue
Labels: ui, n8n team

#5322 feat(core): Set custom Cache-Control headers for static assets
  packages/cli/src/Server.ts
Labels: core, n8n team, skip-e2e

#5130 feat(editor): Completions for extensions in expression editor
  cypress/e2e/11-inline-expression-editor.cy.ts
  cypress/e2e/9-expression-editor-modal.cy.ts
  packages/cli/BREAKING-CHANGES.md
  packages/editor-ui/package.json
  packages/editor-ui/src/components/ExpressionEdit.vue
  packages/editor-ui/src/components/ExpressionEditorModal/ExpressionEditorModalInput.vue
  packages/editor-ui/src/components/ExpressionParameterInput.vue
  packages/editor-ui/src/components/InlineExpressionEditor/InlineExpressionEditorInput.vue
  packages/editor-ui/src/components/ParameterInput.vue
  packages/editor-ui/src/components/ResourceLocator/ResourceLocator.vue
  packages/editor-ui/src/mixins/completionManager.ts
  packages/editor-ui/src/mixins/expressionManager.ts
  packages/editor-ui/src/mixins/workflowHelpers.ts
  packages/editor-ui/src/plugins/codemirror/completions/__tests__/alpha.completions.test.ts
  packages/editor-ui/src/plugins/codemirror/completions/__tests__/completions.test.ts
  packages/editor-ui/src/plugins/codemirror/completions/__tests__/luxon.completions.test.ts
  packages/editor-ui/src/plugins/codemirror/completions/__tests__/mock.ts
  packages/editor-ui/src/plugins/codemirror/completions/__tests__/proxy.completions.test.ts
  packages/editor-ui/src/plugins/codemirror/completions/__tests__/proxyMocks.ts
  packages/editor-ui/src/plugins/codemirror/completions/__tests__/root.completions.test.ts
  packages/editor-ui/src/plugins/codemirror/completions/alpha.completions.ts
  packages/editor-ui/src/plugins/codemirror/completions/blank.completions.ts
  packages/editor-ui/src/plugins/codemirror/completions/bracketAccess.completions.ts
  packages/editor-ui/src/plugins/codemirror/completions/datatype.completions.ts
  packages/editor-ui/src/plugins/codemirror/completions/dollar.completions.ts
  packages/editor-ui/src/plugins/codemirror/completions/luxon.completions.ts
  packages/editor-ui/src/plugins/codemirror/completions/nonDollar.completions.ts
  packages/editor-ui/src/plugins/codemirror/completions/proxy.completions.ts
  packages/editor-ui/src/plugins/codemirror/completions/root.completions.ts
  packages/editor-ui/src/plugins/codemirror/completions/types.ts
  packages/editor-ui/src/plugins/codemirror/completions/utils.ts
  packages/editor-ui/src/plugins/codemirror/inputHandlers/expression.inputHandler.ts
  packages/editor-ui/src/plugins/codemirror/n8nLang.ts
  packages/editor-ui/src/plugins/i18n/index.ts
  packages/editor-ui/src/plugins/i18n/locales/en.json
  packages/editor-ui/src/types/expressions.ts
  packages/workflow/package.json
  packages/workflow/src/Expression.ts
  packages/workflow/src/ExpressionError.ts
  packages/workflow/src/Extensions/ArrayExtensions.ts
  packages/workflow/src/Extensions/DateExtensions.ts
  packages/workflow/src/Extensions/ExpressionExtension.ts
  packages/workflow/src/Extensions/Extensions.ts
  packages/workflow/src/Extensions/NumberExtensions.ts
  packages/workflow/src/Extensions/ObjectExtensions.ts
  packages/workflow/src/Extensions/StringExtensions.ts
  packages/workflow/src/Extensions/index.ts
  packages/workflow/src/NativeMethods/String.methods.ts
  packages/workflow/src/NativeMethods/index.ts
  packages/workflow/src/WorkflowDataProxy.ts
  packages/workflow/src/index.ts
  packages/workflow/test/ExpressionExtensions/ArrayExtensions.test.ts
  packages/workflow/test/ExpressionExtensions/DateExtensions.test.ts
  packages/workflow/test/ExpressionExtensions/ExpressionExtension.test.ts
  packages/workflow/test/ExpressionExtensions/GenericExtensions.test.ts
  packages/workflow/test/ExpressionExtensions/NumberExtensions.test.ts
  packages/workflow/test/ExpressionExtensions/StringExtensions.test.ts
  pnpm-lock.yaml
Labels: core, ui, n8n team

#5137 feat(OpenAI Node): Add frequency-penalty and presence-penalty
  packages/nodes-base/nodes/OpenAi/TextDescription.ts
Labels: node/improvement, community, skip-e2e

#5285 feat(editor): Adjust HTML editor component for use in params
  packages/editor-ui/src/components/HtmlEditor/HtmlEditor.vue
  packages/editor-ui/src/components/HtmlEditor/theme.ts
  packages/editor-ui/src/components/ParameterInput.vue
  packages/editor-ui/src/components/ParameterOptions.vue
  packages/editor-ui/src/plugins/i18n/locales/en.json
  packages/nodes-base/nodes/Mailgun/Mailgun.node.ts
Labels: node/improvement, ui, n8n team

#5335 fix(core): Load config values from files using `_FILE` env variables (no-changelog)
  packages/cli/src/config/index.ts
Labels: core, n8n team, skip-e2e

#5303 feat(core): Fix populating of node custom api call options
  cypress/e2e/5-ndv.cy.ts
  cypress/pages/ndv.ts
  packages/cli/src/api/nodeTypes.api.ts
  packages/core/src/Constants.ts
  packages/core/src/DirectoryLoader.ts
  packages/editor-ui/src/components/Node/NodeCreator/TriggerHelperPanel.vue
  packages/editor-ui/src/components/NodeSettings.vue
  packages/editor-ui/src/stores/nodeCreator.ts
Labels: core, ui, n8n team

#5339 fix(core): Fix env file config loading (no-changelog)
  packages/cli/src/config/index.ts
Labels: skip-e2e

#5334 fix(core): Prevent shared user details being saved alongside execution data
  packages/cli/src/WorkflowExecuteAdditionalData.ts
Labels: core, n8n team, skip-e2e

#5340 fix: Prevent unnecessarily touching updatedAt when n8n starts
  packages/cli/src/ActiveWorkflowRunner.ts
  packages/cli/src/workflows/workflows.services.ts
Labels: n8n team, skip-e2e

#5345 fix(core): Revert custom API option injecting
  cypress/e2e/5-ndv.cy.ts
  cypress/pages/ndv.ts
  packages/cli/src/api/nodeTypes.api.ts
  packages/core/src/Constants.ts
  packages/core/src/DirectoryLoader.ts
  packages/editor-ui/src/components/Node/NodeCreator/TriggerHelperPanel.vue
  packages/editor-ui/src/components/NodeSettings.vue
  packages/editor-ui/src/stores/nodeCreator.ts
Labels: core, ui, n8n team

#5346 fix(core): Use custom cache control only on editor-ui assets (no-changelog)
  packages/cli/src/Server.ts
Labels: skip-e2e

#5347 feat(core): Fix populating of node custom api call options
  cypress/e2e/2-credentials.cy.ts
  cypress/e2e/4-node-creator.cy.ts
  cypress/e2e/5-ndv.cy.ts
  cypress/fixtures/Custom_credential.json
  cypress/fixtures/Custom_node_custom_credential.json
  cypress/fixtures/Custom_node_n8n_credential.json
  cypress/pages/ndv.ts
  cypress/support/commands.ts
  cypress/support/e2e.ts
  packages/cli/src/LoadNodesAndCredentials.ts
  packages/cli/src/api/nodeTypes.api.ts
  packages/cli/src/constants.ts
  packages/core/src/DirectoryLoader.ts
  packages/editor-ui/src/components/Node/NodeCreator/TriggerHelperPanel.vue
  packages/editor-ui/src/components/NodeSettings.vue
  packages/editor-ui/src/stores/nodeCreator.ts
Labels: core, ui, n8n team, skip-e2e

#5342 fix(core): Error reporter should log all error on an error-chain (no-changelog)
  packages/workflow/src/ErrorReporterProxy.ts
Labels: core, n8n team, skip-e2e

#5341 fix(editor): Workflow executions view is broken
  packages/editor-ui/src/components/ExecutionsView/ExecutionsList.vue
Labels: ui, n8n team

#5349 fix(editor): Change executions title to match menu
  packages/editor-ui/src/components/ExecutionsList.vue
  packages/editor-ui/src/plugins/i18n/locales/en.json
  packages/editor-ui/src/views/TemplatesView.vue
Labels: ui, n8n team

#4587 feat(Slack Node): Revamp the node with more functionalities in a new version
  packages/nodes-base/credentials/SlackOAuth2Api.credentials.ts
  packages/nodes-base/nodes/Slack/Slack.node.ts
  packages/nodes-base/nodes/Slack/V1/ChannelDescription.ts
  packages/nodes-base/nodes/Slack/V1/FileDescription.ts
  packages/nodes-base/nodes/Slack/V1/GenericFunctions.ts
  packages/nodes-base/nodes/Slack/V1/MessageDescription.ts
  packages/nodes-base/nodes/Slack/V1/MessageInterface.ts
  packages/nodes-base/nodes/Slack/V1/ReactionDescription.ts
  packages/nodes-base/nodes/Slack/V1/SlackV1.node.ts
  packages/nodes-base/nodes/Slack/V1/StarDescription.ts
  packages/nodes-base/nodes/Slack/V1/UserDescription.ts
  packages/nodes-base/nodes/Slack/V1/UserGroupDescription.ts
  packages/nodes-base/nodes/Slack/V1/UserProfileDescription.ts
  packages/nodes-base/nodes/Slack/V2/ChannelDescription.ts
  packages/nodes-base/nodes/Slack/V2/FileDescription.ts
  packages/nodes-base/nodes/Slack/V2/GenericFunctions.ts
  packages/nodes-base/nodes/Slack/V2/MessageDescription.ts
  packages/nodes-base/nodes/Slack/V2/MessageInterface.ts
  packages/nodes-base/nodes/Slack/V2/ReactionDescription.ts
  packages/nodes-base/nodes/Slack/V2/SlackV2.node.ts
  packages/nodes-base/nodes/Slack/V2/StarDescription.ts
  packages/nodes-base/nodes/Slack/V2/UserDescription.ts
  packages/nodes-base/nodes/Slack/V2/UserGroupDescription.ts
Labels: node/improvement, node/new, n8n team

#5354 fix: Improve README (no-changelog)
  README.md
Labels: community, skip-e2e

#5364 fix(editor): Fix merge node connectors
  packages/editor-ui/src/stores/workflows.ts
  packages/editor-ui/src/views/NodeView.vue
Labels: ui, n8n team

#5366 fix(editor): Fix multiple-output endpoints success style after connection is detached
  packages/editor-ui/src/components/Node.vue
  packages/editor-ui/src/plugins/endpoints/N8nPlusEndpointType.ts
Labels: ui, n8n team

#5367 fix(editor): Fix mapping to empty expression input
  packages/editor-ui/src/components/ParameterInputFull.vue
Labels: skip-e2e

#5368 fix(core): CORS middleware should not process the entire handler chain on OPTIONS requests (no-changelog)
  packages/cli/src/middlewares/cors.ts
Labels: core, n8n team, skip-e2e

#5380 test: Automatically load workflow nodes in node tests
  packages/nodes-base/test/nodes/Airtable/Airtable.node.test.ts
  packages/nodes-base/test/nodes/Helpers.ts
  packages/nodes-base/test/nodes/If/If.node.test.ts
  packages/nodes-base/test/nodes/Set/SetNode.test.ts
  packages/nodes-base/test/nodes/Start/StartNode.test.ts
Labels: node/improvement, n8n team

#5379 fix(editor): Fix resolvable highlighting for HTML editor
  packages/editor-ui/src/mixins/expressionManager.ts
Labels: ui, n8n team

#5376 test(editor): Improve canvas e2e tests reliability
  cypress/e2e/10-undo-redo.cy.ts
  cypress/e2e/12-canvas.cy.ts
  cypress/pages/workflow.ts
Labels: n8n team

#5384 fix(editor): Correctly show OAuth reconnect button
  packages/editor-ui/src/components/CredentialEdit/CredentialConfig.vue
Labels: ui, n8n team

#5372 test: Add data mapping test
  cypress/e2e/10-undo-redo.cy.ts
  cypress/e2e/12-canvas.cy.ts
  cypress/e2e/14-mapping.cy.ts
  cypress/e2e/5-ndv.cy.ts
  cypress/pages/canvas-node.ts
  cypress/pages/index.ts
  cypress/pages/ndv.ts
  cypress/support/commands.ts
  cypress/support/index.ts
  packages/editor-ui/src/components/InputPanel.vue
  packages/editor-ui/src/components/RunData.vue
Labels: ui, n8n team

#5371 test(Item Lists Node): Unit tests (no-changelog)
  package.json
  packages/nodes-base/nodes/ItemLists/test/node/ItemLists.test.ts
  packages/nodes-base/nodes/ItemLists/test/node/workflow.aggregateItems.json
  packages/nodes-base/nodes/ItemLists/test/node/workflow.limit.json
  packages/nodes-base/nodes/ItemLists/test/node/workflow.removeDuplicates.json
  packages/nodes-base/nodes/ItemLists/test/node/workflow.sort.json
  packages/nodes-base/nodes/ItemLists/test/node/workflow.splitOutItems.json
  packages/nodes-base/nodes/ItemLists/test/node/workflow.summarize.json
  packages/nodes-base/test/nodes/ExecuteWorkflow.ts
  packages/nodes-base/test/nodes/Helpers.ts
Labels: n8n team, tech debt

#5387 fix(core): Do not block app startup by telemetry (no-changelog)
  packages/cli/src/Server.ts
Labels: core, n8n team, skip-e2e

#5391 ci: Add E2E test for scheduled trigger
  cypress/e2e/15-scheduler-node.cy.ts
  packages/cli/src/config/index.ts
Labels: core, n8n team

#5392 fix(core): Disable transactions on sqlite migrations that use `PRAGMA foreign_keys`
  packages/cli/src/databases/migrations/sqlite/1652367743993-AddUserSettings.ts
  packages/cli/src/databases/migrations/sqlite/1652905585850-AddAPIKeyColumn.ts
  packages/cli/src/databases/migrations/sqlite/1673268682475-DeleteExecutionsWithWorkflows.ts
Labels: core, n8n team, skip-e2e

#5386 refactor(core): Add unit tests for all external auth middlewares (no-changelog)
  package.json
  packages/cli/package.json
  packages/cli/src/Server.ts
  packages/cli/src/api/workflowStats.api.ts
  packages/cli/src/middlewares/basicAuth.ts
  packages/cli/src/middlewares/externalJWTAuth.ts
  packages/cli/test/unit/middlewares/basicAuth.test.ts
  packages/cli/test/unit/middlewares/externalJWTAuth.test.ts
  packages/nodes-base/package.json
  pnpm-lock.yaml
Labels: core, n8n team, skip-e2e

#5393 test(editor): Enable adding nodes in between any two nodes on canvas in e2e tests (no-changelog)
  cypress/e2e/10-undo-redo.cy.ts
  cypress/e2e/12-canvas.cy.ts
  cypress/pages/workflow.ts
  packages/editor-ui/src/utils/nodeViewUtils.ts
  packages/editor-ui/src/views/NodeView.vue
Labels: ui, n8n team

#5390 refactor: Change permission check to be based on workflow settings
  packages/cli/src/WorkflowHelpers.ts
Labels: core, n8n team

#5402 ci: Add E2E tests for Webhook node
  cypress.config.js
  cypress/e2e/16-webhook-node.cy.ts
  cypress/support/binaryTestFiles.ts
Labels: n8n team

#5396 test(Merge Node): Unit tests (no-changelog)
  packages/nodes-base/nodes/Merge/test/node/Merge.test.ts
  packages/nodes-base/nodes/Merge/test/node/workflow.append.json
  packages/nodes-base/nodes/Merge/test/node/workflow.chooseBranch.json
  packages/nodes-base/nodes/Merge/test/node/workflow.combine.mergeByFields.json
  packages/nodes-base/nodes/Merge/test/node/workflow.combine.mergeByPosition.json
  packages/nodes-base/nodes/Merge/test/node/workflow.combine.multiplex.json
Labels: n8n team, tech debt

#5375 test: Add e2e for data transformation expressions
  cypress/e2e/14-data-transformation-expressions.cy.ts
  cypress/pages/ndv.ts
  cypress/pages/workflow.ts
Labels: n8n team

#5312 feat: Change desktop UM experience
  packages/cli/src/Interfaces.ts
  packages/cli/src/Server.ts
  packages/cli/src/UserManagement/UserManagementHelper.ts
  packages/cli/src/controllers/users.controller.ts
  packages/cli/src/middlewares/auth.ts
  packages/design-system/src/components/N8nActionBox/ActionBox.vue
  packages/editor-ui/src/Interface.ts
  packages/editor-ui/src/components/CredentialEdit/CredentialSharing.ee.vue
  packages/editor-ui/src/components/FeatureComingSoon.vue
  packages/editor-ui/src/components/MainHeader/WorkflowDetails.vue
  packages/editor-ui/src/components/PersonalizationModal.vue
  packages/editor-ui/src/components/WorkflowShareModal.ee.vue
  packages/editor-ui/src/constants.ts
  packages/editor-ui/src/plugins/i18n/locales/en.json
  packages/editor-ui/src/router.ts
  packages/editor-ui/src/stores/ui.ts
  packages/editor-ui/src/stores/users.ts
  packages/editor-ui/src/views/SettingsCommunityNodesView.vue
  packages/editor-ui/src/views/SettingsUsersView.vue
Labels: n8n team, skip-e2e

#3530 feat: Add tracking code to hiring link (no-changelog)
  packages/editor-ui/src/constants.ts
Labels: ui, n8n team

#5407 feat(editor): Add `Object` global completions
  packages/editor-ui/src/plugins/codemirror/completions/__tests__/completions.test.ts
  packages/editor-ui/src/plugins/codemirror/completions/datatype.completions.ts
  packages/editor-ui/src/plugins/codemirror/completions/nonDollar.completions.ts
  packages/editor-ui/src/plugins/i18n/index.ts
  packages/editor-ui/src/plugins/i18n/locales/en.json
Labels: ui, n8n team

#5381 test(Split In Batches Node): Add test for Split in Batches node (no-changelog)
  packages/nodes-base/nodes/SplitInBatches/test/SplitInBatches.node.test.ts
  packages/nodes-base/nodes/SplitInBatches/test/SplitInBatches.workflow.json
  packages/nodes-base/test/nodes/Airtable/Airtable.node.test.ts
  packages/nodes-base/test/nodes/If/If.node.test.ts
  packages/nodes-base/test/nodes/Set/SetNode.test.ts
  packages/nodes-base/test/nodes/Start/StartNode.test.ts
Labels: node/improvement, n8n team

#5378 test(Switch Node): Add test for switch node (no-changelog)
  packages/nodes-base/nodes/Switch/test/switch.expression.workflow.json
  packages/nodes-base/nodes/Switch/test/switch.node.test.ts
  packages/nodes-base/nodes/Switch/test/switch.rules.workflow.json
Labels: node/improvement, n8n team, skip-e2e

#5374 test(Execute Command Node): Unit tests (no-changelog)
  packages/nodes-base/nodes/ExecuteCommand/test/ExecuteCommand.node.test.ts
  packages/nodes-base/nodes/ExecuteCommand/test/workflow.json
Labels: n8n team

#5277 docs(Google Sheets Node): Description updates for fields (no-changelog)
  packages/nodes-base/nodes/Google/Sheet/v2/actions/sheet/commonDescription.ts
Labels: node/improvement, n8n team, skip-e2e

#5408 feat(HubSpot Trigger Node): Add Conversation events
  packages/nodes-base/nodes/Hubspot/HubspotTrigger.node.ts
Labels: node/improvement, community

#5357 docs(Spreadsheet File Node): Update descriptions and Alias (no-changelog)
  packages/nodes-base/nodes/SpreadsheetFile/SpreadsheetFile.node.json
  packages/nodes-base/nodes/SpreadsheetFile/SpreadsheetFile.node.ts
Labels: skip-e2e

#5406 test(editor): Add canvas dragging tests (no-changelog)
  cypress/constants.ts
  cypress/e2e/12-canvas.cy.ts
  cypress/pages/workflow.ts
  cypress/support/commands.ts
  packages/editor-ui/src/mixins/nodeBase.ts
Labels: ui, n8n team

#5404 test(IF Node): Unit tests (no-changelog)
  packages/nodes-base/nodes/If/test/IF.boolean.json
  packages/nodes-base/nodes/If/test/IF.date-time.json
  packages/nodes-base/nodes/If/test/IF.number.json
  packages/nodes-base/nodes/If/test/IF.string.json
  packages/nodes-base/nodes/If/test/If.node.test.ts
  packages/nodes-base/test/nodes/If/If.node.test.ts
  packages/nodes-base/test/nodes/If/workflow.json
Labels: n8n team

#5409 test(Set Node): Add tests for Set Node (no-changelog)
  packages/nodes-base/nodes/Set/test/Set.node.test.ts
  packages/nodes-base/nodes/Set/test/Set.workflow.json
  packages/nodes-base/test/nodes/Set/SetNode.test.ts
Labels: n8n team

#5419 fix(core): Stop copying icons to cache
  packages/cli/src/LoadNodesAndCredentials.ts
  packages/cli/src/NodeTypes.ts
  packages/cli/src/Server.ts
  packages/core/bin/generate-ui-types
  packages/core/src/DirectoryLoader.ts
  packages/workflow/src/NodeHelpers.ts
Labels: core, n8n team, skip-e2e

#4939 feat(core): Live reload node/credential descriptions in development (no-changelog)
  package.json
  packages/cli/.npmignore
  packages/cli/package.json
  packages/cli/src/Interfaces.ts
  packages/cli/src/NodeTypes.ts
  packages/cli/src/ReloadNodesAndCredentials.ts
  packages/cli/src/Server.ts
  packages/core/src/DirectoryLoader.ts
  packages/editor-ui/src/mixins/pushConnection.ts
  pnpm-lock.yaml
Labels: core, ui, n8n team, skip-e2e

#5412 feat: Add e2e user invite test suite (no-changelog)
  cypress/e2e/17-sharing.cy.ts
  cypress/pages/index.ts
  cypress/pages/settings-users.ts
  cypress/pages/sidebar/main-sidebar.ts
  cypress/pages/workflow.ts
  cypress/support/commands.ts
  cypress/support/index.ts
  packages/editor-ui/src/components/InviteUsersModal.vue
  packages/editor-ui/src/components/MainHeader/WorkflowDetails.vue
  packages/editor-ui/src/components/MainSidebar.vue
  packages/editor-ui/src/constants.ts
  packages/editor-ui/src/router.ts
  packages/editor-ui/src/views/SettingsUsersView.vue
  packages/editor-ui/src/views/SignoutView.vue
Labels: ui, n8n team

#5420 feat(Edit Image Node): Allow WebP as an image format
  packages/nodes-base/nodes/EditImage/EditImage.node.ts
  packages/nodes-base/package.json
  pnpm-lock.yaml
Labels: node/improvement, n8n team, skip-e2e

#5385 test(Spreadsheet File Node): Unit tests (no-changelog)
  packages/nodes-base/nodes/SpreadsheetFile/test/SpreadsheetFile.test.ts
  packages/nodes-base/nodes/SpreadsheetFile/test/spreadsheet.csv
  packages/nodes-base/nodes/SpreadsheetFile/test/workflow.json
  packages/nodes-base/test/nodes/Airtable/Airtable.node.test.ts
  packages/nodes-base/test/nodes/Helpers.ts
Labels: node/improvement, n8n team

#5382 feat(editor): Bring completions to HTML editor
  packages/editor-ui/src/components/HtmlEditor/HtmlEditor.vue
  packages/editor-ui/src/components/ParameterInput.vue
  packages/editor-ui/src/plugins/codemirror/completions/addCompletions.ts
  packages/editor-ui/src/plugins/codemirror/n8nLang.ts
Labels: ui, n8n team

#5411 test: Add e2e workflow tags (no-changelog)
  cypress/e2e/17-workflow-tags.cy.ts
  cypress/e2e/7-workflow-actions.cy.ts
  cypress/pages/workflow.ts
  packages/editor-ui/src/components/TagsManager/TagsView/TagsTable.vue
  packages/editor-ui/src/components/TagsManager/TagsView/TagsView.vue
Labels: ui, n8n team

#5423 refactor(core): Upgrade typeorm (no-changelog)
  packages/cli/package.json
  packages/cli/src/license/License.service.ts
  pnpm-lock.yaml
Labels: core, n8n team, skip-e2e

#5426 test(XML Node): Unit tests (no-changelog)
  packages/nodes-base/nodes/Xml/Xml.node.ts
  packages/nodes-base/nodes/Xml/test/node/Xml.test.ts
  packages/nodes-base/nodes/Xml/test/node/workflow.xml.json
Labels: n8n team, tech debt, skip-e2e

#5410 test(HTTP Request Node): Unit tests (no-changelog)
  packages/nodes-base/nodes/HttpRequest/test/node/HttpRequest.test.ts
  packages/nodes-base/nodes/HttpRequest/test/node/workflow.delete.json
  packages/nodes-base/nodes/HttpRequest/test/node/workflow.get.json
  packages/nodes-base/nodes/HttpRequest/test/node/workflow.patch.json
  packages/nodes-base/nodes/HttpRequest/test/node/workflow.post.json
  packages/nodes-base/nodes/HttpRequest/test/node/workflow.put.json
  packages/nodes-base/test/nodes/Helpers.ts
Labels: n8n team, tech debt, skip-e2e

#5427 test(Stop and Error Node): Unit tests (no-changelog)
  packages/nodes-base/nodes/StopAndError/test/node/StopAndError.test.ts
Labels: n8n team, tech debt, skip-e2e

#5431 fix(core): Stop creating icons directories (no-changelog)
  packages/cli/src/LoadNodesAndCredentials.ts
Labels: skip-e2e

#5428 test(Rename Keys Node): Unit tests (no-changelog)
  packages/nodes-base/nodes/RenameKeys/test/RenameKeys.test.ts
  packages/nodes-base/nodes/RenameKeys/test/RenameKeys.workflow.json
Labels: tech debt, skip-e2e

#5433 test(Crypto Node): Unit tests (no-changelog)
  packages/nodes-base/nodes/Crypto/test/Crypto.test.ts
  packages/nodes-base/nodes/Crypto/test/CryptoTest.workflow.json
Labels: n8n team, tech debt, skip-e2e

#5373 test(Code Node): Unit tests (no-changelog)
  packages/nodes-base/nodes/Code/test/Code.node.test.ts
  packages/nodes-base/nodes/Code/test/Code.workflow.json
Labels: n8n team, tech debt

#5415 test(Date & Time Node): Unit tests (no-changelog)
  packages/nodes-base/nodes/DateTime/test/node/DateTime.test.ts
  packages/nodes-base/nodes/DateTime/test/node/DateTimeWorklfow.test.json
Labels: n8n team, tech debt, skip-e2e

#5370 fix: Expression extension failing with optional chaining
  packages/workflow/package.json
  packages/workflow/src/Expression.ts
  packages/workflow/src/Extensions/ExpressionExtension.ts
  packages/workflow/src/Extensions/index.ts
  packages/workflow/test/ExpressionExtensions/ExpressionExtension.test.ts
  pnpm-lock.yaml
Labels: core, n8n team

#5437 test(RSS Read Node): Unit tests (no-changelog)
  packages/nodes-base/nodes/RssFeedRead/test/node/RssFeedRead.test.ts
  packages/nodes-base/nodes/RssFeedRead/test/node/workflow.rss.json
Labels: n8n team, tech debt, skip-e2e

#5403 fix(core): Fix import command for workflows with old format(pre UM)
  packages/cli/src/commands/import/workflow.ts
Labels: core, n8n team, skip-e2e

#5436 test(Read Binary File Node): Unit tests (no-changelog)
  packages/nodes-base/nodes/ReadBinaryFile/test/ReadBinaryFile.test.ts
  packages/nodes-base/nodes/ReadBinaryFile/test/ReadBinaryFile.workflow.json
  packages/nodes-base/nodes/ReadBinaryFile/test/image.jpg
Labels: n8n team, tech debt, skip-e2e

#5422 ci(editor): Faster builds on the CI (no-changelog)
  packages/editor-ui/vite.config.ts
  packages/editor-ui/vue.config.js
Labels: ui, n8n team

#5389 test: Add more data mapping tests
  cypress/e2e/14-data-transformation-expressions.cy.ts
  cypress/e2e/14-mapping.cy.ts
  cypress/e2e/16-webhook-node.cy.ts
  cypress/fixtures/Test_workflow_3.json
  cypress/pages/canvas-node.ts
  cypress/pages/ndv.ts
  cypress/support/commands.ts
  cypress/support/index.ts
  packages/editor-ui/src/components/ParameterInputWrapper.vue
  packages/editor-ui/src/views/NodeView.vue
Labels: n8n team, skip-e2e

#5438 test(editor): Add user management e2e tests
  cypress/e2e/17-sharing.cy.ts
  cypress/e2e/18-user-management.cy.ts
  cypress/pages/settings-users.ts
  packages/design-system/src/components/N8nActionToggle/ActionToggle.vue
  packages/design-system/src/components/N8nUsersList/UsersList.vue
  packages/editor-ui/src/components/DeleteUserModal.vue
Labels: ui, n8n team

#5434 test(Compression Node): Unit tests (no-changelog)
  packages/nodes-base/nodes/Compression/test/node/Compression.test.ts
  packages/nodes-base/nodes/Compression/test/node/lorem.txt
  packages/nodes-base/nodes/Compression/test/node/workflow.compression.json
Labels: n8n team, tech debt, skip-e2e

#5435 fix(Linear Node): Fix issue with Issue States not loading correctly
  packages/nodes-base/nodes/Linear/Linear.node.ts
  packages/nodes-base/nodes/Linear/Queries.ts
Labels: node/improvement, n8n team

#5441 fix: MySQL migration parses database contents if necessary (fix for MariaDB)
  packages/cli/src/databases/migrations/mysqldb/1675940580449-PurgeInvalidWorkflowConnections.ts
Labels: n8n team, skip-e2e

#5307 test: Upgrade `vitest` (no-changelog)
  packages/design-system/package.json
  packages/editor-ui/package.json
  pnpm-lock.yaml
Labels: ui, n8n team, skip-e2e

#5440 test(Write Binary File Node): Unit tests (no-changelog)
  packages/nodes-base/nodes/WriteBinaryFile/test/WriteBinaryFile.test.ts
  packages/nodes-base/nodes/WriteBinaryFile/test/WriteBinaryFile.workflow.json
  packages/nodes-base/nodes/WriteBinaryFile/test/image.jpg
  packages/nodes-base/test/nodes/Helpers.ts
Labels: node/improvement, n8n team, tech debt, skip-e2e

#5439 test(core): Add basic expression tests
  packages/workflow/test/Expression.test.ts
  packages/workflow/test/ExpressionExtensions/ExpressionExtension.test.ts
  packages/workflow/test/ExpressionExtensions/Helpers.ts
  packages/workflow/test/ExpressionFixtures/base.ts
Labels: core, n8n team

#5448 test(Compare Datasets Node): Unit tests (no-changelog)
  packages/nodes-base/nodes/CompareDatasets/test/node/CompareDatasets.test.ts
  packages/nodes-base/nodes/CompareDatasets/test/node/workflow.compareDatasets.fuzzy.json
  packages/nodes-base/nodes/CompareDatasets/test/node/workflow.compareDatasets.json
Labels: n8n team, tech debt, skip-e2e

#5449 test(Markdown Node): Unit tests (no-changelog)
  packages/nodes-base/nodes/Markdown/test/node/Markdown.test.ts
  packages/nodes-base/nodes/Markdown/test/node/workflow.markdown.json
Labels: n8n team, tech debt, skip-e2e

#5450 test(iCalendar Node): Unit tests (no-changelog)
  packages/nodes-base/nodes/ICalendar/test/node/ICalendar.test.ts
  packages/nodes-base/nodes/ICalendar/test/node/workflow.iCalendar.json
Labels: n8n team, tech debt, skip-e2e

#5451 test(editor): Add e2e tests for personal settings page
  cypress/e2e/18-user-management.cy.ts
  cypress/pages/modals/change-password-modal.ts
  cypress/pages/settings-personal.ts
  packages/editor-ui/src/components/ChangePasswordModal.vue
  packages/editor-ui/src/views/SettingsPersonalView.vue
Labels: ui, n8n team

#5452 refactor(core): Delete duplicate code across all commands
  packages/cli/src/ActiveWorkflowRunner.ts
  packages/cli/src/LoadNodesAndCredentials.ts
  packages/cli/src/PublicApi/v1/handlers/workflows/workflows.service.ts
  packages/cli/src/Queue.ts
  packages/cli/src/WorkflowRunnerProcess.ts
  packages/cli/src/commands/BaseCommand.ts
  packages/cli/src/commands/Interfaces.d.ts
  packages/cli/src/commands/audit.ts
  packages/cli/src/commands/db/revert.ts
  packages/cli/src/commands/execute.ts
  packages/cli/src/commands/executeBatch.ts
  packages/cli/src/commands/export/credentials.ts
  packages/cli/src/commands/export/workflow.ts
  packages/cli/src/commands/import/credentials.ts
  packages/cli/src/commands/import/workflow.ts
  packages/cli/src/commands/ldap/reset.ts
  packages/cli/src/commands/license/clear.ts
  packages/cli/src/commands/list/workflow.ts
  packages/cli/src/commands/start.ts
  packages/cli/src/commands/update/workflow.ts
  packages/cli/src/commands/user-management/reset.ts
  packages/cli/src/commands/webhook.ts
  packages/cli/src/commands/worker.ts
  packages/cli/src/constants.ts
  packages/cli/src/utils.ts
  packages/workflow/src/LoggerProxy.ts
Labels: core, n8n team, skip-e2e

#5443 feat(core): Add support for WebSockets as an alternative to Server-Sent Events
  packages/cli/package.json
  packages/cli/src/AbstractServer.ts
  packages/cli/src/Interfaces.ts
  packages/cli/src/Push.ts
  packages/cli/src/ReloadNodesAndCredentials.ts
  packages/cli/src/Server.ts
  packages/cli/src/TestWebhooks.ts
  packages/cli/src/WorkflowExecuteAdditionalData.ts
  packages/cli/src/WorkflowRunner.ts
  packages/cli/src/api/nodes.api.ts
  packages/cli/src/config/schema.ts
  packages/cli/src/index.ts
  packages/cli/src/push/abstract.push.ts
  packages/cli/src/push/index.ts
  packages/cli/src/push/sse.push.ts
  packages/cli/src/push/types.ts
  packages/cli/src/push/websocket.push.ts
  packages/cli/src/sse-channel.d.ts
  packages/cli/test/setup-mocks.ts
  packages/editor-ui/src/Interface.ts
  packages/editor-ui/src/mixins/pushConnection.ts
  packages/editor-ui/src/stores/settings.ts
  pnpm-lock.yaml
Labels: core, n8n team, skip-e2e

#5278 test: Add tests for ActiveWorkflowRunner class
  packages/cli/src/ActiveWorkflowRunner.ts
  packages/cli/test/unit/ActiveWorkflowRunner.test.ts
  packages/cli/test/unit/Helpers.ts
  packages/cli/test/unit/PermissionChecker.test.ts
Labels: core, n8n team, skip-e2e

#5442 test(Move Binary Data Node): Unit tests (no-changelog)
  packages/nodes-base/nodes/MoveBinaryData/test/MoveBinaryData.test.ts
  packages/nodes-base/nodes/MoveBinaryData/test/MoveBinaryData.workflow.json
  packages/nodes-base/nodes/MoveBinaryData/test/data/sample.json
Labels: n8n team, tech debt, skip-e2e

#5453 test(Read PDF Node): Unit tests (no-changelog)
  packages/nodes-base/nodes/ReadPdf/test/ReadPDF.test.ts
  packages/nodes-base/nodes/ReadPdf/test/ReadPDF.workflow.json
  packages/nodes-base/nodes/ReadPdf/test/sample.pdf
Labels: n8n team, tech debt, skip-e2e

#5457 test: Change workflows to test from safe list to skip list
  .github/workflows/test-workflows.yml
  packages/cli/src/events/index.ts
Labels: skip-e2e

#5313 fix(core): Handle versioned custom nodes correctly
  packages/core/src/DirectoryLoader.ts
  packages/workflow/src/NodeHelpers.ts
  packages/workflow/src/index.ts
Labels: core, n8n team, skip-e2e

#5461 fix(core): Fix issue that worker and webhook service close directly
  packages/cli/src/commands/webhook.ts
  packages/cli/src/commands/worker.ts
Labels: core, n8n team

#5458 test(editor): Add e2e tests for executions preview
  cypress/e2e/20-workflow-executions.cy.ts
  cypress/fixtures/Test_workflow_4_executions_view.json
  cypress/pages/workflow-executions-tab.ts
  cypress/pages/workflow.ts
  packages/design-system/src/components/N8nRadioButtons/RadioButton.vue
  packages/editor-ui/src/components/ExecutionsView/ExecutionCard.vue
  packages/editor-ui/src/components/ExecutionsView/ExecutionPreview.vue
  packages/editor-ui/src/components/ExecutionsView/ExecutionsSidebar.vue
Labels: ui, n8n team

#5472 docs: Update release notes link
  README.md
Labels: n8n team, Upcoming Release

#5454 feat(editor): Upgrade to Storybook v7 (no-changelog)
  packages/design-system/.storybook/main.js
  packages/design-system/package.json
  pnpm-lock.yaml
Labels: ui, n8n team

#5473 ci: Update the "Check Documentation URLs" workflow (no-changelog)
  .github/workflows/check-documentation-urls.yml
  package.json
  packages/nodes-base/nodes/HtmlExtract/HtmlExtract.node.json
  pnpm-lock.yaml
Labels: n8n team, skip-e2e

#5463 feat: Add workflow and credential sharing access e2e tests
  cypress/e2e/17-sharing.cy.ts
  cypress/pages/modals/credentials-modal.ts
  cypress/pages/modals/index.ts
  cypress/pages/modals/workflow-sharing-modal.ts
  cypress/pages/ndv.ts
  cypress/pages/workflow.ts
  cypress/support/commands.ts
  packages/editor-ui/src/components/CredentialEdit/CredentialSharing.ee.vue
  packages/editor-ui/src/components/NodeCredentials.vue
  packages/editor-ui/src/components/WorkflowShareModal.ee.vue
Labels: ui, n8n team

#5475 fix(editor): Fix Vite dev mode (no-changelog)
  packages/editor-ui/vite.config.ts
Labels: ui, n8n team, skip-e2e

#5476 fix(core): Use stricter typing on queries in cli commands (no-changelog)
  packages/cli/src/commands/export/credentials.ts
  packages/cli/src/commands/export/workflow.ts
  packages/cli/src/commands/list/workflow.ts
  packages/cli/src/commands/update/workflow.ts
Labels: core, n8n team, skip-e2e

#5479 ci(core): Add unit tests for "me" controller (no-changelog)
  package.json
  packages/cli/test/unit/controllers/me.controller.test.ts
  pnpm-lock.yaml
Labels: core, n8n team, skip-e2e

#5338 fix(core): Fix data transformation function that are reported not to work properly
  packages/editor-ui/src/components/RunDataJson.vue
  packages/editor-ui/src/components/RunDataTable.vue
  packages/editor-ui/src/utils/typesUtils.ts
  packages/workflow/package.json
  packages/workflow/src/Expression.ts
  packages/workflow/src/Extensions/ArrayExtensions.ts
  packages/workflow/src/Extensions/DateExtensions.ts
  packages/workflow/src/Extensions/NumberExtensions.ts
  packages/workflow/src/Extensions/ObjectExtensions.ts
  packages/workflow/src/Extensions/StringExtensions.ts
  packages/workflow/src/Extensions/utils.ts
  packages/workflow/test/ExpressionExtensions/ArrayExtensions.test.ts
  packages/workflow/test/ExpressionExtensions/DateExtensions.test.ts
  packages/workflow/test/ExpressionExtensions/Helpers.ts
  packages/workflow/test/ExpressionExtensions/NumberExtensions.test.ts
  packages/workflow/test/ExpressionExtensions/ObjectExtensions.test.ts
  pnpm-lock.yaml
Labels: core, ui, n8n team

#5253 feat(Github Trigger Node): Use resource locator component
  packages/nodes-base/nodes/Github/GenericFunctions.ts
  packages/nodes-base/nodes/Github/GithubTrigger.node.ts
  packages/nodes-base/nodes/Github/SearchFunctions.ts
Labels: node/improvement, n8n team

#5474 feat(editor): Update to personalization survey v4
  packages/editor-ui/src/Interface.ts
  packages/editor-ui/src/__tests__/setup.ts
  packages/editor-ui/src/__tests__/utils.ts
  packages/editor-ui/src/components/PersonalizationModal.vue
  packages/editor-ui/src/components/__tests__/PersonalizationModal.spec.ts
  packages/editor-ui/src/components/__tests__/__snapshots__/PersonalizationModal.spec.ts.snap
  packages/editor-ui/src/constants.ts
  packages/editor-ui/src/plugins/i18n/locales/en.json
  packages/editor-ui/src/utils/userUtils.ts
Labels: ui, n8n team

#5481 fix(core): Fix issues with community node installation (no-changelog)
  packages/cli/src/CommunityNodes/packageModel.ts
  packages/cli/src/LoadNodesAndCredentials.ts
  packages/cli/src/ReloadNodesAndCredentials.ts
  packages/cli/src/Server.ts
  packages/core/src/DirectoryLoader.ts
Labels: core, n8n team, skip-e2e

#5468 feat(Notion Node): Add icon support for page and database page creation
  packages/nodes-base/nodes/Notion/DatabasePageDescription.ts
  packages/nodes-base/nodes/Notion/PageDescription.ts
  packages/nodes-base/nodes/Notion/v1/NotionV1.node.ts
  packages/nodes-base/nodes/Notion/v2/NotionV2.node.ts
Labels: node/improvement, n8n team

#5483 fix(Bubble Node): Fix pagination issue when returning all objects
  packages/nodes-base/nodes/Bubble/GenericFunctions.ts
Labels: node/improvement, n8n team

#5311 fix(core): Remove unnecessary info from `GET /workflows` response
  packages/cli/src/workflows/workflows.controller.ee.ts
  packages/cli/src/workflows/workflows.services.ee.ts
  packages/cli/src/workflows/workflows.services.ts
  packages/cli/src/workflows/workflows.types.ts
  packages/cli/test/integration/workflows.controller.ee.test.ts
Labels: core, n8n team

#5429 test(editor): Execution testing from UI perspective (no-changelog)
  cypress/e2e/19-execution.cy.ts
  cypress/fixtures/Manual_wait_set.json
  cypress/fixtures/Webhook_wait_set.json
  cypress/pages/workflow.ts
  packages/editor-ui/src/views/NodeView.vue
Labels: ui, n8n team

#5488 feat(Slack Node): Add support for manually inputting a channel name
  packages/nodes-base/nodes/Slack/V2/GenericFunctions.ts
  packages/nodes-base/nodes/Slack/V2/MessageDescription.ts
Labels: node/improvement, n8n team

#5486 feat(editor): Add most important native props and methods to autocomplete
  packages/editor-ui/src/main.ts
  packages/editor-ui/src/plugins/codemirror/completions/__tests__/completions.test.ts
  packages/editor-ui/src/plugins/codemirror/completions/datatype.completions.ts
  packages/editor-ui/src/plugins/i18n/index.ts
  packages/editor-ui/src/styles/autocomplete-theme.scss
  packages/workflow/src/Extensions/Extensions.ts
  packages/workflow/src/NativeMethods/Array.methods.ts
  packages/workflow/src/NativeMethods/Number.methods.ts
  packages/workflow/src/NativeMethods/Object.Methods.ts
  packages/workflow/src/NativeMethods/String.methods.ts
  packages/workflow/src/NativeMethods/index.ts
Labels: core, ui, n8n team

#5489 feat(Github Node): Use resource locator component
  packages/nodes-base/nodes/Github/Github.node.ts
Labels: node/improvement, n8n team, skip-e2e

#5482 feat: Update telemetry api endpoints
  packages/cli/src/config/schema.ts
  packages/cli/src/telemetry/index.ts
  packages/editor-ui/src/plugins/telemetry/index.ts
Labels: core, n8n team

#5494 feat(core): Add saml feature flag
  packages/cli/src/Interfaces.ts
  packages/cli/src/License.ts
  packages/cli/src/Saml/helpers.ts
  packages/cli/src/Server.ts
  packages/cli/src/config/schema.ts
  packages/cli/src/constants.ts
Labels: core, n8n team

#5498 refactor(core): Delete unused `GET /me` endpoint (no-changelog)
  packages/cli/src/controllers/me.controller.ts
  packages/cli/test/integration/me.api.test.ts
  packages/cli/test/integration/shared/constants.ts
  packages/editor-ui/src/api/users.ts
  packages/editor-ui/src/stores/users.ts
Labels: core, ui, n8n team, skip-e2e

#5499 refactor(core): Improve instance owner setup and add unit tests (no-changelog)
  packages/cli/src/controllers/owner.controller.ts
  packages/cli/src/requests.ts
  packages/cli/test/integration/owner.api.test.ts
  packages/cli/test/integration/shared/constants.ts
  packages/cli/test/unit/controllers/me.controller.test.ts
  packages/cli/test/unit/controllers/owner.controller.test.ts
  packages/cli/test/unit/shared/testData.ts
  packages/editor-ui/src/api/users.ts
  packages/editor-ui/src/stores/users.ts
  packages/editor-ui/src/views/SetupView.vue
Labels: core, ui, n8n team, skip-e2e

#5315 feat(editor): Unify regular and trigger panels
  cypress/e2e/11-inline-expression-editor.cy.ts
  cypress/e2e/12-canvas.cy.ts
  cypress/e2e/13-pinning.cy.ts
  cypress/e2e/14-data-transformation-expressions.cy.ts
  cypress/e2e/14-mapping.cy.ts
  cypress/e2e/2-credentials.cy.ts
  cypress/e2e/4-node-creator.cy.ts
  cypress/e2e/5-ndv.cy.ts
  cypress/e2e/6-code-node.cy.ts
  cypress/e2e/8-http-request-node.cy.ts
  cypress/e2e/9-expression-editor-modal.cy.ts
  cypress/pages/canvas-node.ts
  cypress/pages/features/node-creator.ts
  cypress/pages/index.ts
  cypress/pages/ndv.ts
  cypress/pages/workflow.ts
  packages/design-system/src/components/N8nNodeCreatorNode/NodeCreatorNode.vue
  packages/design-system/src/components/N8nNodeCreatorNode/TriggerIcon.vue
  packages/design-system/src/components/N8nNodeIcon/NodeIcon.vue
  packages/editor-ui/public/suggestednodes.png
  packages/editor-ui/src/Interface.ts
  packages/editor-ui/src/components/Node.vue
  packages/editor-ui/src/components/Node/NodeCreator/CategorizedItems.vue
  packages/editor-ui/src/components/Node/NodeCreator/CategoryItem.vue
  packages/editor-ui/src/components/Node/NodeCreator/ItemIterator.vue
  packages/editor-ui/src/components/Node/NodeCreator/MainPanel.vue
  packages/editor-ui/src/components/Node/NodeCreator/NodeCreator.vue
  packages/editor-ui/src/components/Node/NodeCreator/NodeItem.vue
  packages/editor-ui/src/components/Node/NodeCreator/SearchBar.vue
  packages/editor-ui/src/components/Node/NodeCreator/SubcategoryItem.vue
  packages/editor-ui/src/components/Node/NodeCreator/TriggerHelperPanel.vue
  packages/editor-ui/src/components/Node/NodeCreator/TypeSelector.vue
  packages/editor-ui/src/components/Node/NodeCreator/ViewItem.vue
  packages/editor-ui/src/components/Node/NodeCreator/useMainPanelView.ts
  packages/editor-ui/src/components/PersonalizationModal.vue
  packages/editor-ui/src/components/__tests__/__snapshots__/PersonalizationModal.spec.ts.snap
  packages/editor-ui/src/constants.ts
  packages/editor-ui/src/plugins/i18n/locales/en.json
  packages/editor-ui/src/plugins/icons.ts
  packages/editor-ui/src/stores/nodeCreator.ts
  packages/editor-ui/src/utils/nodeTypesUtils.ts
  packages/editor-ui/src/views/NodeView.vue
  packages/nodes-base/nodes/EditImage/EditImage.node.ts
  packages/nodes-base/nodes/EmailSend/v2/EmailSendV2.node.ts
  packages/nodes-base/nodes/N8n/N8n.node.json
  packages/nodes-base/nodes/N8n/N8n.node.ts
  packages/nodes-base/nodes/N8nTrigger/N8nTrigger.node.json
  packages/nodes-base/nodes/N8nTrigger/N8nTrigger.node.ts
  packages/nodes-base/nodes/SpreadsheetFile/SpreadsheetFile.node.ts
Labels: ui, n8n team

#5505 feat(core): Add configurable execution history limit
  packages/cli/src/WorkflowExecuteAdditionalData.ts
  packages/cli/src/config/schema.ts
Labels: core, n8n team

#5518 fix(editor): Fix adding of wrong actions when filtering in the node actions panel (no-changelog)
  cypress/e2e/4-node-creator.cy.ts
  packages/editor-ui/src/components/Node.vue
  packages/editor-ui/src/components/Node/NodeCreator/MainPanel.vue
  packages/editor-ui/src/plugins/i18n/locales/en.json
Labels: ui, n8n team

#5490 feat: Deprecate Read Binary File node
  packages/nodes-base/nodes/ReadBinaryFile/ReadBinaryFile.node.ts
Labels: node/improvement, n8n team, skip-e2e

#5514 fix(S3 Node): Fix issue with get many buckets not outputting data
  packages/nodes-base/nodes/S3/S3.node.ts
Labels: node/improvement, n8n team

#5519 fix(Baserow Node): Fix issue with get all not correctly using filters
  packages/nodes-base/nodes/Baserow/Baserow.node.ts
Labels: node/improvement, n8n team

#5511 feat: Support feature flag evaluation server side
  packages/cli/src/Interfaces.ts
  packages/cli/src/InternalHooksManager.ts
  packages/cli/src/Server.ts
  packages/cli/src/UserManagement/UserManagementHelper.ts
  packages/cli/src/WorkflowRunnerProcess.ts
  packages/cli/src/commands/BaseCommand.ts
  packages/cli/src/commands/start.ts
  packages/cli/src/controllers/auth.controller.ts
  packages/cli/src/controllers/users.controller.ts
  packages/cli/src/posthog/index.ts
  packages/cli/src/telemetry/index.ts
  packages/cli/src/telemetry/scripts.ts
  packages/cli/test/integration/shared/utils.ts
  packages/cli/test/unit/PostHog.test.ts
  packages/cli/test/unit/Telemetry.test.ts
  packages/editor-ui/index.html
  packages/editor-ui/src/App.vue
  packages/editor-ui/src/Interface.ts
  packages/editor-ui/src/api/users.ts
  packages/editor-ui/src/components/Telemetry.vue
  packages/editor-ui/src/constants.ts
  packages/editor-ui/src/plugins/telemetry/index.ts
  packages/editor-ui/src/plugins/telemetry/telemetry.types.ts
  packages/editor-ui/src/stores/posthog.ts
  packages/editor-ui/src/stores/telemetry.ts
  packages/editor-ui/src/stores/users.ts
  packages/editor-ui/src/views/NodeView.vue
  packages/editor-ui/src/views/WorkflowsView.vue
  packages/workflow/src/Interfaces.ts
Labels: core, ui, n8n team

#5522 fix(core): Do not allow arbitrary path traversal in the credential-translation endpoint
  packages/cli/src/Server.ts
  packages/cli/src/TranslationHelpers.ts
  packages/cli/src/controllers/index.ts
  packages/cli/src/controllers/translation.controller.ts
  packages/cli/test/setup-mocks.ts
  packages/cli/test/unit/controllers/translation.controller.test.ts
Labels: core, n8n team, skip-e2e

#5523 fix(core): Do not allow arbitrary path traversal in BinaryDataManager
  packages/cli/src/Server.ts
  packages/core/src/BinaryDataManager/FileSystem.ts
  packages/core/src/errors.ts
  packages/core/src/index.ts
Labels: core, n8n team, skip-e2e

#5526 fix(core): User update endpoint should only allow updating email, firstName, and lastName
  packages/cli/package.json
  packages/cli/src/GenericHelpers.ts
  packages/cli/src/controllers/me.controller.ts
  packages/cli/src/databases/entities/User.ts
  packages/cli/src/requests.ts
  packages/cli/test/unit/controllers/me.controller.test.ts
  pnpm-lock.yaml
Labels: core, n8n team, skip-e2e

#5525 fix(core): Do not explicitly bypass auth on urls containing `.svg`
  packages/cli/src/middlewares/auth.ts
Labels: core, n8n team, skip-e2e

#5516 fix(Postgres Node): Fix for tables containing field named json
  packages/nodes-base/nodes/Postgres/Postgres.node.functions.ts
  packages/nodes-base/nodes/Postgres/Postgres.node.ts
Labels: n8n team, node/issue

#5504 ci: Setup a semi-automated release process (no-changelog)
  .github/scripts/bump-versions.mjs
  .github/scripts/package.json
  .github/workflows/check-pr-title.yml
  .github/workflows/release-create-pr.yml
  .github/workflows/release-publish.yml
  CONTRIBUTING.md
  package.json
  packages/cli/package.json
  packages/core/package.json
  packages/editor-ui/package.json
  packages/editor-ui/vite.config.ts
  packages/node-dev/package.json
  packages/nodes-base/package.json
  packages/workflow/package.json
  pnpm-lock.yaml
Labels: core, ui, n8n team, skip-e2e

#5530 feat: Add new event hooks
  packages/editor-ui/src/components/ParameterInputFull.vue
  packages/editor-ui/src/constants.ts
  packages/editor-ui/src/stores/posthog.ts
Labels: ui, n8n team, skip-e2e

#5512 fix(Compare Datasets Node): UI tweaks and fixes
  packages/nodes-base/nodes/CompareDatasets/CompareDatasets.node.ts
  packages/nodes-base/nodes/CompareDatasets/GenericFunctions.ts
  packages/nodes-base/nodes/Merge/v2/GenericFunctions.ts
  packages/nodes-base/test/utils/utilities.test.ts
  packages/nodes-base/utils/utilities.ts
Labels: node/improvement, n8n team, node/issue

#5369 feat: Add Required path name mapping to multiple nodes
  packages/nodes-base/nodes/Airtable/Airtable.node.ts
  packages/nodes-base/nodes/Airtable/AirtableTrigger.node.ts
  packages/nodes-base/nodes/MySql/MySql.node.ts
  packages/nodes-base/nodes/Postgres/Postgres.node.ts
  packages/nodes-base/nodes/RenameKeys/RenameKeys.node.ts
  packages/nodes-base/nodes/Set/Set.node.ts
Labels: node/improvement, n8n team

#5535 ci: Release process improvements (no-changelog)
  .github/workflows/check-documentation-urls.yml
  .github/workflows/docker-images.yml
  .github/workflows/release-create-pr.yml
Labels: skip-e2e

#5520 fix(Discourse Node): Fix issue with credential test not working
  packages/nodes-base/credentials/DiscourseApi.credentials.ts
Labels: node/improvement, n8n team

#5540 ci: Merge back released tag to master as Jan (no-changelog)
  .github/workflows/release-publish.yml
Labels: n8n team

#5533 fix(core): Fix execution status filters
  packages/cli/src/Interfaces.ts
  packages/cli/src/Server.ts
  packages/cli/src/WaitTracker.ts
  packages/cli/src/databases/migrations/mysqldb/1676996103000-MigrateExecutionStatus.ts
  packages/cli/src/databases/migrations/mysqldb/index.ts
  packages/cli/src/databases/migrations/postgresdb/1676996103000-MigrateExecutionStatus.ts
  packages/cli/src/databases/migrations/postgresdb/index.ts
  packages/cli/src/databases/migrations/sqlite/1676996103000-MigrateExecutionStatus.ts
  packages/cli/src/databases/migrations/sqlite/index.ts
  packages/cli/src/executions/executionHelpers.ts
  packages/cli/src/executions/executions.service.ts
  packages/editor-ui/src/Interface.ts
Labels: core, ui, n8n team

#5545 ci: Check PR title on all branches, except release branches (no-changelog)
  .github/workflows/check-pr-title.yml
Labels: n8n team, skip-e2e

#5546 fix(core): Do not remove empty output connections arrays in PurgeInvalidWorkflowConnections migration
  packages/cli/src/databases/migrations/mysqldb/1675940580449-PurgeInvalidWorkflowConnections.ts
  packages/cli/src/databases/migrations/postgresdb/1675940580449-PurgeInvalidWorkflowConnections.ts
  packages/cli/src/databases/migrations/sqlite/1675940580449-PurgeInvalidWorkflowConnections.ts
Labels: core, n8n team

#5544 refactor(WhatsApp Node): Avoid using BinaryDataManager directly from n8n-core
  packages/nodes-base/nodes/WhatsApp/MediaFunctions.ts
  packages/nodes-base/nodes/WhatsApp/MessageFunctions.ts
Labels: node/improvement, n8n team, skip-e2e

#5534 feat: Hide sensible value in Auth Header Credentials and Auth Query Credentials
  packages/nodes-base/credentials/HttpHeaderAuth.credentials.ts
  packages/nodes-base/credentials/HttpQueryAuth.credentials.ts
Labels: ui, n8n team
