Repository n8n-io/n8n, pull requests merged in 2023-04, with the labels that each got.

#5876 fix(editor): Update execution loading parameters after pushing test values (no-changelog)
  packages/editor-ui/src/components/ExecutionsView/ExecutionsList.vue
Labels: ui, n8n team

#5873 fix(Gmail Node): Gmail luxon object support, fix for timestamp
  packages/nodes-base/nodes/Google/Gmail/GenericFunctions.ts
  packages/nodes-base/nodes/Google/Gmail/GmailTrigger.node.ts
  packages/nodes-base/nodes/Google/Gmail/test/v2/utils.test.ts
  packages/nodes-base/nodes/Google/Gmail/v2/GmailV2.node.ts
Labels: node/improvement, n8n team, node/issue

#5888 fix(core): Fix the issue of nodes not loading when run via npx
  packages/cli/src/LoadNodesAndCredentials.ts
Labels: core, n8n team, skip-e2e

#5887 fix(core): Use table-prefixes in queries in import commands
  packages/cli/src/commands/import/credentials.ts
  packages/cli/src/commands/import/workflow.ts
Labels: core, n8n team

#5550 feat(Postgres Node): Overhaul node
  packages/nodes-base/credentials/Postgres.credentials.ts
  packages/nodes-base/nodes/CrateDb/CrateDb.node.ts
  packages/nodes-base/nodes/Postgres/Postgres.node.ts
  packages/nodes-base/nodes/Postgres/test/v2/operations.test.ts
  packages/nodes-base/nodes/Postgres/test/v2/runQueries.test.ts
  packages/nodes-base/nodes/Postgres/test/v2/utils.test.ts
  packages/nodes-base/nodes/Postgres/v1/PostgresV1.node.ts
  packages/nodes-base/nodes/Postgres/v1/genericFunctions.ts
  packages/nodes-base/nodes/Postgres/v2/PostgresV2.node.ts
  packages/nodes-base/nodes/Postgres/v2/actions/common.descriptions.ts
  packages/nodes-base/nodes/Postgres/v2/actions/database/Database.resource.ts
  packages/nodes-base/nodes/Postgres/v2/actions/database/deleteTable.operation.ts
  packages/nodes-base/nodes/Postgres/v2/actions/database/executeQuery.operation.ts
  packages/nodes-base/nodes/Postgres/v2/actions/database/insert.operation.ts
  packages/nodes-base/nodes/Postgres/v2/actions/database/select.operation.ts
  packages/nodes-base/nodes/Postgres/v2/actions/database/update.operation.ts
  packages/nodes-base/nodes/Postgres/v2/actions/database/upsert.operation.ts
  packages/nodes-base/nodes/Postgres/v2/actions/node.type.ts
  packages/nodes-base/nodes/Postgres/v2/actions/router.ts
  packages/nodes-base/nodes/Postgres/v2/actions/versionDescription.ts
  packages/nodes-base/nodes/Postgres/v2/helpers/interfaces.ts
  packages/nodes-base/nodes/Postgres/v2/helpers/utils.ts
  packages/nodes-base/nodes/Postgres/v2/methods/credentialTest.ts
  packages/nodes-base/nodes/Postgres/v2/methods/index.ts
  packages/nodes-base/nodes/Postgres/v2/methods/listSearch.ts
  packages/nodes-base/nodes/Postgres/v2/methods/loadOptions.ts
  packages/nodes-base/nodes/Postgres/v2/transport/index.ts
  packages/nodes-base/nodes/QuestDb/QuestDb.node.ts
  packages/nodes-base/nodes/TimescaleDb/TimescaleDb.node.ts
  packages/nodes-base/test/nodes/Postgres/Postgres.node.functions.test.js
Labels: node/improvement, n8n team

#5893 fix(core): Prevent augmentObject from creating infinitely deep proxies
  packages/workflow/src/AugmentObject.ts
Labels: core, n8n team, skip-e2e

#5872 fix(core): `augmentObject` should use existing property descriptors whenever possible
  packages/workflow/src/AugmentObject.ts
  packages/workflow/test/AugmentObject.test.ts
Labels: core, n8n team, skip-e2e

#5896 fix(HTTP Request Node): Detect mime-type from streaming responses
  packages/core/src/NodeExecuteFunctions.ts
Labels: core, n8n team, skip-e2e

#5891 fix(core): Improve axios error handling in nodes
  packages/core/package.json
  packages/core/src/NodeExecuteFunctions.ts
  packages/nodes-base/nodes/HttpRequest/V3/HttpRequestV3.node.ts
  pnpm-lock.yaml
Labels: core, n8n team, skip-e2e

#5800 fix(Compare Datasets Node): Support for dot notation in skip fields
  packages/nodes-base/nodes/CompareDatasets/CompareDatasets.node.ts
  packages/nodes-base/nodes/CompareDatasets/GenericFunctions.ts
  packages/nodes-base/nodes/CompareDatasets/test/node/workflow.compareDatasets.skipFields.json
Labels: node/improvement, n8n team, node/issue

#5902 fix(core): `augmentObject` should clone Buffer/Uint8Array instead of wrapping them in a proxy
  packages/workflow/src/AugmentObject.ts
Labels: core, n8n team

#5903 fix: Improve variables listing and disabled case, fix resource sorting (no-changelog)
  packages/design-system/src/components/N8nDatatable/Datatable.vue
  packages/design-system/src/components/N8nDatatable/__tests__/Datatable.spec.ts
  packages/design-system/src/types/datatable.ts
  packages/editor-ui/src/components/VariablesRow.vue
  packages/editor-ui/src/components/__tests__/VariablesRow.spec.ts
  packages/editor-ui/src/components/__tests__/__snapshots__/VariablesRow.spec.ts.snap
  packages/editor-ui/src/components/layouts/ResourcesListLayout.vue
  packages/editor-ui/src/plugins/i18n/locales/en.json
  packages/editor-ui/src/views/VariablesView.vue
Labels: ui, n8n team

#5863 refactor: Upsert workflow statistics to suppress unnecessary error messages
  packages/cli/src/events/WorkflowStatistics.ts
  packages/cli/test/unit/Events.test.ts
Labels: core, n8n team

#5849 fix(Date & Time Node): Convert luxon DateTime object to ISO
  packages/nodes-base/nodes/DateTime/DateTime.node.ts
  packages/nodes-base/nodes/DateTime/test/node/workflow.luxonDateTime.json
Labels: node/improvement, n8n team, node/issue

#5908 ci(editor): Apply monaco-editor alias override only during tests (no-changelog)
  packages/editor-ui/vite.config.ts
Labels: ui, n8n team

#5909 fix(core): Make WorkflowStatistics tests pass on all databases (no-changelog)
  packages/cli/src/events/WorkflowStatistics.ts
  packages/cli/test/unit/Events.test.ts
Labels: core, n8n team

#5861 fix(HTTP Request Node): Refresh token properly on never fail option
  packages/core/src/NodeExecuteFunctions.ts
Labels: core, n8n team

#5895 feat(HTTP Request Node): Follow redirects by default
  packages/nodes-base/nodes/HttpRequest/V3/HttpRequestV3.node.ts
Labels: node/improvement, n8n team, skip-e2e

#5870 feat: Add Sentry sourcemap uploading for editor-ui (no-changelog)
  .github/workflows/release-publish.yml
  package.json
  packages/editor-ui/package.json
  packages/editor-ui/vite.config.ts
  patches/@sentry__cli@2.17.0.patch
  pnpm-lock.yaml
Labels: ui, n8n team

#5727 fix(core): Do not execute `workflowExecuteBefore` hook when resuming executions from a waiting state
  packages/cli/src/Interfaces.ts
  packages/cli/src/WorkflowRunner.ts
  packages/cli/src/WorkflowRunnerProcess.ts
  packages/core/src/WorkflowExecute.ts
  packages/workflow/src/Interfaces.ts
Labels: core, n8n team, skip-e2e

#5911 fix(core): App should not crash with a custom rest endpoint
  packages/cli/src/Server.ts
  packages/cli/src/commands/start.ts
  packages/editor-ui/index.html
  packages/editor-ui/src/Interface.ts
  packages/editor-ui/src/shims.d.ts
  packages/editor-ui/src/stores/n8nRootStore.ts
Labels: core, ui, n8n team

#5905 fix(core): Fix sub workflows running forever after failing validation
  packages/cli/src/WorkflowExecuteAdditionalData.ts
  packages/cli/src/WorkflowRunner.ts
  packages/cli/src/eventbus/MessageEventBus/recoverEvents.ts
Labels: core, n8n team

#5915 fix: Make sure retryOf does not take null value (no-changelog)
  packages/workflow/src/WorkflowHooks.ts
Labels: core, n8n team

#5928 refactor(editor): Replace this.$props (no-changelog)
  packages/design-system/src/components/ResizeObserver/ResizeObserver.vue
  packages/editor-ui/src/components/BreakpointsObserver.vue
  packages/editor-ui/src/components/ExpandableInput/ExpandableInputBase.vue
  packages/editor-ui/src/components/ExpandableInput/ExpandableInputEdit.vue
  packages/editor-ui/src/components/InlineTextEdit.vue
  packages/editor-ui/src/components/IntersectionObserved.vue
  packages/editor-ui/src/components/IntersectionObserver.vue
  packages/editor-ui/src/components/Modal.vue
  packages/editor-ui/src/components/ModalDrawer.vue
  packages/editor-ui/src/components/ParameterInputExpanded.vue
  packages/editor-ui/src/components/SettingsLogStreaming/EventDestinationSettingsModal.ee.vue
  packages/editor-ui/src/components/TagsContainer.vue
  packages/editor-ui/src/components/TagsDropdown.vue
  packages/editor-ui/src/components/TagsManager/TagsView/TagsTable.vue
  packages/editor-ui/src/components/TagsManager/TagsView/TagsView.vue
Labels: ui, n8n team

#5906 feat(editor): SAML paywall state
  packages/editor-ui/src/plugins/i18n/locales/en.json
  packages/editor-ui/src/router.ts
  packages/editor-ui/src/views/SettingsSso.vue
Labels: ui, n8n team

#5922 feat(editor): SAML login disables Invite button
  packages/editor-ui/src/plugins/i18n/locales/en.json
  packages/editor-ui/src/views/SettingsUsersView.vue
Labels: ui, n8n team

#5901 feat: Create TOTP node
  packages/editor-ui/src/plugins/icons.ts
  packages/nodes-base/credentials/TotpApi.credentials.ts
  packages/nodes-base/nodes/Totp/Totp.node.json
  packages/nodes-base/nodes/Totp/Totp.node.ts
  packages/nodes-base/nodes/Totp/test/Totp.node.test.ts
  packages/nodes-base/nodes/Totp/test/Totp.workflow.test.json
  packages/nodes-base/package.json
  packages/nodes-base/test/nodes/FakeCredentialsMap.ts
  packages/nodes-base/test/nodes/Helpers.ts
  pnpm-lock.yaml
Labels: node/new, n8n team

#5943 fix(editor): Drop mergeDeep in favor of lodash merge
  packages/editor-ui/src/components/RunDataSchema.vue
  packages/editor-ui/src/utils/__tests__/typesUtils.test.ts
  packages/editor-ui/src/utils/typesUtils.ts
Labels: ui, n8n team

#5947 fix(Code Node): Update vm2 to address CVE-2023-29017
  packages/nodes-base/package.json
  pnpm-lock.yaml
Labels: n8n team

#5948 fix(core): Update xml2js to address CVE-2023-0842
  package.json
  packages/nodes-base/package.json
  packages/workflow/package.json
  pnpm-lock.yaml
Labels: core, n8n team

#5933 docs: Fix typo in AWS S3 and S3 nodes for parent folder key
  packages/nodes-base/nodes/Aws/S3/FileDescription.ts
Labels: node/improvement, n8n team

#5677 feat(editor): Add user activation survey
  cypress/e2e/22-user-activation-modal.cy.ts
  cypress/fixtures/Settings_user_activation_modal_enabled.json
  cypress/pages/modals/index.ts
  cypress/pages/modals/user-activation-survey-modal.ts
  packages/cli/src/Interfaces.ts
  packages/cli/src/Server.ts
  packages/cli/src/UserManagement/UserManagementHelper.ts
  packages/cli/src/WorkflowHelpers.ts
  packages/cli/src/config/schema.ts
  packages/cli/src/controllers/me.controller.ts
  packages/cli/src/events/WorkflowStatistics.ts
  packages/cli/src/executions/executions.service.ts
  packages/cli/src/requests.ts
  packages/cli/src/user/user.service.ts
  packages/cli/test/unit/Events.test.ts
  packages/editor-ui/package.json
  packages/editor-ui/src/Interface.ts
  packages/editor-ui/src/api/users.ts
  packages/editor-ui/src/api/workflows.ts
  packages/editor-ui/src/components/Modals.vue
  packages/editor-ui/src/components/UserActivationSurveyModal.vue
  packages/editor-ui/src/constants.ts
  packages/editor-ui/src/main.ts
  packages/editor-ui/src/plugins/i18n/locales/en.json
  packages/editor-ui/src/stores/settings.ts
  packages/editor-ui/src/stores/ui.ts
  packages/editor-ui/src/stores/users.ts
  packages/editor-ui/src/stores/workflows.ts
  packages/workflow/src/Interfaces.ts
  pnpm-lock.yaml
Labels: core, ui, n8n team

#5955 Start connection before getting InternalHook instance from the container
  packages/cli/src/WorkflowRunnerProcess.ts
Labels: core, n8n team

#5960 ci: Fix E2E tests on master (no-changelog)
  cypress/e2e/22-user-activation-modal.cy.ts
Labels: n8n team

#5959 fix(HTTP Request Node): Show detailed error message in the UI again
  packages/core/jest.config.js
  packages/core/src/NodeExecuteFunctions.ts
  packages/core/test/NodeExecuteFunctions.test.ts
  packages/core/test/WorkflowExecute.test.ts
  packages/core/test/setup.ts
  packages/core/test/utils.ts
  packages/nodes-base/nodes/HttpRequest/V3/HttpRequestV3.node.ts
Labels: node/improvement, core, n8n team

#5938 fix(NocoDB Node): Fix for updating or deleting rows with not default primary keys
  packages/nodes-base/credentials/NocoDbApiToken.credentials.ts
  packages/nodes-base/nodes/NocoDB/NocoDB.node.ts
  packages/nodes-base/nodes/NocoDB/OperationDescription.ts
Labels: n8n team, node/issue

#5862 ci: Validate load options methods in nodes-base
  packages/core/bin/generate-ui-types
  packages/core/src/DirectoryLoader.ts
  packages/nodes-base/nodes/FreshworksCrm/descriptions/ContactDescription.ts
  packages/nodes-base/nodes/Paddle/PaymentDescription.ts
  packages/nodes-base/package.json
  packages/nodes-base/scripts/validate-load-options-methods.js
  packages/workflow/src/Interfaces.ts
Labels: node/improvement, core, n8n team

#5830 fix(Github Trigger Node): Remove content_reference event
  packages/nodes-base/nodes/Github/GithubTrigger.node.ts
Labels: node/improvement, n8n team

#5414 ci: Add test for wait node
  packages/nodes-base/nodes/Wait/test/Wait.node.test.ts
  packages/nodes-base/nodes/Wait/test/Wait.workflow.json
Labels: n8n team

#5805 fix(OpenAI Node): Update models to only show those supported
  packages/nodes-base/nodes/OpenAi/ChatDescription.ts
  packages/nodes-base/nodes/OpenAi/TextDescription.ts
Labels: node/improvement, n8n team

#5604 feat(MySQL Node): Overhaul
  packages/nodes-base/credentials/MySql.credentials.ts
  packages/nodes-base/nodes/MySql/MySql.node.ts
  packages/nodes-base/nodes/MySql/test/v2/operations.test.ts
  packages/nodes-base/nodes/MySql/test/v2/runQueries.test.ts
  packages/nodes-base/nodes/MySql/test/v2/utils.test.ts
  packages/nodes-base/nodes/MySql/v1/GenericFunctions.ts
  packages/nodes-base/nodes/MySql/v1/MySqlV1.node.ts
  packages/nodes-base/nodes/MySql/v2/MySqlV2.node.ts
  packages/nodes-base/nodes/MySql/v2/actions/common.descriptions.ts
  packages/nodes-base/nodes/MySql/v2/actions/database/Database.resource.ts
  packages/nodes-base/nodes/MySql/v2/actions/database/deleteTable.operation.ts
  packages/nodes-base/nodes/MySql/v2/actions/database/executeQuery.operation.ts
  packages/nodes-base/nodes/MySql/v2/actions/database/insert.operation.ts
  packages/nodes-base/nodes/MySql/v2/actions/database/select.operation.ts
  packages/nodes-base/nodes/MySql/v2/actions/database/update.operation.ts
  packages/nodes-base/nodes/MySql/v2/actions/database/upsert.operation.ts
  packages/nodes-base/nodes/MySql/v2/actions/node.type.ts
  packages/nodes-base/nodes/MySql/v2/actions/router.ts
  packages/nodes-base/nodes/MySql/v2/actions/versionDescription.ts
  packages/nodes-base/nodes/MySql/v2/helpers/interfaces.ts
  packages/nodes-base/nodes/MySql/v2/helpers/utils.ts
  packages/nodes-base/nodes/MySql/v2/methods/credentialTest.ts
  packages/nodes-base/nodes/MySql/v2/methods/index.ts
  packages/nodes-base/nodes/MySql/v2/methods/listSearch.ts
  packages/nodes-base/nodes/MySql/v2/methods/loadOptions.ts
  packages/nodes-base/nodes/MySql/v2/transport/index.ts
  packages/nodes-base/test/nodes/Helpers.ts
Labels: node/improvement, n8n team

#5961 fix(editor): Redirect to home page after saving data on SAML onboarding page
  packages/editor-ui/src/stores/sso.ts
  packages/editor-ui/src/views/SamlOnboarding.vue
Labels: ui, n8n team

#5966 fix(core): Skip SAML onboarding for users with first- and lastname
  packages/cli/src/sso/saml/routes/saml.controller.ee.ts
  packages/cli/src/sso/saml/saml.service.ee.ts
Labels: core, n8n team

#5967 fix(core): Fix lint on SAML controller (no-changelog)
  packages/cli/src/sso/saml/routes/saml.controller.ee.ts
  packages/cli/src/sso/saml/types/requests.ts
Labels: core, n8n team

#5946 test(editor): SSO tests
  packages/editor-ui/src/components/__tests__/ExecutionsList.test.ts
  packages/editor-ui/src/components/__tests__/SSOLogin.test.ts
  packages/editor-ui/src/stores/__tests__/sso.test.ts
  packages/editor-ui/src/stores/sso.ts
  packages/editor-ui/src/utils/__tests__/userUtils.test.ts
  packages/editor-ui/src/utils/testUtils.ts
  packages/editor-ui/src/views/SettingsSso.vue
  packages/editor-ui/src/views/__tests__/AuthView.test.ts
  packages/editor-ui/src/views/__tests__/SamlOnboarding.test.ts
  packages/editor-ui/src/views/__tests__/SettingsSso.test.ts
Labels: ui, n8n team

#5968 fix(editor): Only treat as CTRL pressed by default on touch devices for MouseEvent
  packages/editor-ui/src/composables/useDeviceSupport.ts
  packages/editor-ui/src/mixins/deviceSupportHelpers.ts
Labels: ui, n8n team

#5977 feat(core): Support for google service account in HTTP node
  packages/nodes-base/credentials/GoogleApi.credentials.ts
  packages/nodes-base/nodes/HttpRequest/V3/HttpRequestV3.node.ts
Labels: node/improvement, n8n team

#5975 test(editor): Move test utils to the proper place
  packages/editor-ui/src/__tests__/utils.ts
  packages/editor-ui/src/components/__tests__/ExecutionsList.test.ts
  packages/editor-ui/src/components/__tests__/SSOLogin.test.ts
  packages/editor-ui/src/stores/__tests__/sso.test.ts
  packages/editor-ui/src/utils/__tests__/userUtils.test.ts
  packages/editor-ui/src/utils/testUtils.ts
  packages/editor-ui/src/views/__tests__/SamlOnboarding.test.ts
  packages/editor-ui/src/views/__tests__/SettingsSso.test.ts
Labels: ui, n8n team

#5976 test(editor): Set 'data-test-id' in unit tests, so they match with Cypress
  packages/editor-ui/src/__tests__/setup.ts
  packages/editor-ui/src/components/ExecutionFilter.vue
  packages/editor-ui/src/components/ExecutionsList.vue
  packages/editor-ui/src/components/__tests__/SSOLogin.test.ts
  packages/editor-ui/src/views/SettingsSso.vue
  packages/editor-ui/src/views/__tests__/AuthView.test.ts
Labels: ui, n8n team

#5910 feat: Add variables input validation and permissions (no-changelog)
  packages/design-system/src/components/N8nDatatable/Datatable.vue
  packages/design-system/src/components/N8nDatatable/__tests__/__snapshots__/Datatable.spec.ts.snap
  packages/design-system/src/components/N8nDatatable/__tests__/data.ts
  packages/design-system/src/components/N8nFormInput/FormInput.vue
  packages/design-system/src/components/N8nFormInput/validators.ts
  packages/design-system/src/components/N8nPagination/Pagination.vue
  packages/design-system/src/plugins/n8nComponents.ts
  packages/design-system/src/types/datatable.ts
  packages/design-system/src/types/form.ts
  packages/editor-ui/src/components/ExecutionFilter.vue
  packages/editor-ui/src/components/ExecutionsList.vue
  packages/editor-ui/src/components/VariablesRow.vue
  packages/editor-ui/src/components/__tests__/VariablesRow.spec.ts
  packages/editor-ui/src/components/__tests__/__snapshots__/VariablesRow.spec.ts.snap
  packages/editor-ui/src/components/layouts/PageViewLayoutList.vue
  packages/editor-ui/src/components/layouts/ResourcesListLayout.vue
  packages/editor-ui/src/permissions.ts
  packages/editor-ui/src/plugins/codemirror/completions/datatype.completions.ts
  packages/editor-ui/src/plugins/i18n/locales/en.json
  packages/editor-ui/src/styles/autocomplete-theme.scss
  packages/editor-ui/src/views/VariablesView.vue
Labels: ui, n8n team

#5898 fix(core): Fix paired item returning wrong data
  cypress/e2e/13-pinning.cy.ts
  packages/editor-ui/src/mixins/workflowHelpers.ts
  packages/workflow/src/WorkflowDataProxy.ts
Labels: core, ui, n8n team

#5980 fix(editor): Make sure to redirect to blank canvas after personalisation modal
  packages/editor-ui/src/components/PersonalizationModal.vue
Labels: ui, n8n team

#5839 ci: Add a workflow to push n8n releases to release channels (no-changelog)
  .github/workflows/release-push-to-channel.yml
Labels: n8n team, skip-e2e

#5964 fix(IF Node): Fix typo in combine description (no-changelog)
  packages/core/test/Helpers.ts
  packages/nodes-base/nodes/If/If.node.ts
Labels: node/improvement, community

#5981 fix(core): Improve SAML connection test result views
  packages/cli/src/sso/saml/routes/saml.controller.ee.ts
  packages/cli/src/sso/saml/saml.service.ee.ts
  packages/cli/src/sso/saml/samlHelpers.ts
  packages/cli/src/sso/saml/views/samlConnectionTestFailed.ts
  packages/cli/src/sso/saml/views/samlConnectionTestSuccess.ts
Labels: core, n8n team

#5985 ci: Add checklist item hinting at not adding new dependencies for nodes (no-changelog)
  CHECKLIST.yml
Labels: n8n team

#5936 fix(Google Sheets Trigger Node): Return actual error message
  packages/nodes-base/nodes/Google/Sheet/v2/transport/index.ts
Labels: n8n team, node/issue

#5823 fix(OpenAI Node): Update OpenAI Text Moderate input placeholder text
  packages/nodes-base/nodes/OpenAi/TextDescription.ts
Labels: node/improvement, community, skip-e2e

#5987 build: Update license SDK to v2.1.0 (no-changelog)
  packages/cli/package.json
  pnpm-lock.yaml
Labels: core, n8n team

#5621 feat(GitLab Node): Add Additional parameters for File List
  packages/nodes-base/nodes/Gitlab/Gitlab.node.ts
Labels: node/improvement, community

#5930 refactor(editor): Refactor history and debounce mixins to composables (no-changelog)
  packages/editor-ui/src/App.vue
  packages/editor-ui/src/composables/__tests__/useDebounce.test.ts
  packages/editor-ui/src/composables/__tests__/useHistoryHelper.test.ts
  packages/editor-ui/src/composables/useDebounce.ts
  packages/editor-ui/src/composables/useHistoryHelper.ts
  packages/editor-ui/src/mixins/history.ts
Labels: ui, n8n team

#5991 fix(HTTP Request Node): Fix itemIndex in HTTP Request errors
  packages/nodes-base/nodes/HttpRequest/V1/HttpRequestV1.node.ts
  packages/nodes-base/nodes/HttpRequest/V2/HttpRequestV2.node.ts
  packages/nodes-base/nodes/HttpRequest/V3/HttpRequestV3.node.ts
Labels: node/improvement, n8n team

#5996 fix(editor): Fix moving canvas on middle click preventing lasso selection
  packages/editor-ui/src/mixins/moveNodeWorkflow.ts
Labels: ui, n8n team

#5997 ci: Improve test for wait node
  packages/nodes-base/nodes/Wait/test/Wait.node.test.ts
  packages/nodes-base/nodes/Wait/test/Wait.workflow.json
Labels: node/improvement, n8n team

#5974 fix(editor): Cleanup demo/video experiment
  packages/editor-ui/src/constants.ts
  packages/editor-ui/src/utils/nodeViewUtils.ts
  packages/editor-ui/src/views/NodeView.vue
  packages/editor-ui/src/views/SetupView.vue
  packages/editor-ui/src/views/WorkflowsView.vue
Labels: ui, n8n team

#5962 fix: Small changes to user activation modal (no-changelog)
  cypress/e2e/22-user-activation-modal.cy.ts
  packages/editor-ui/src/components/UserActivationSurveyModal.vue
  packages/editor-ui/src/main.ts
Labels: ui, n8n team

#6000 feat(core): Add versionControl feature flag
  packages/cli/src/Interfaces.ts
  packages/cli/src/License.ts
  packages/cli/src/Server.ts
  packages/cli/src/api/e2e.api.ts
  packages/cli/src/constants.ts
  packages/cli/src/environment/versionControl/versionControlHelper.ts
  packages/editor-ui/src/constants.ts
Labels: core, ui, n8n team

#5874 fix(editor): Add padding to prepend input
  packages/design-system/src/components/N8nSelect/Select.vue
Labels: ui, n8n team

#6005 refactor(editor): Remove checklist experiment (no-changelog)
  packages/editor-ui/src/constants.ts
  packages/editor-ui/src/stores/posthog.ts
  packages/editor-ui/src/stores/segment.ts
Labels: ui, n8n team

#5995 fix(editor): Enterprise features missing with UM
  packages/editor-ui/src/router.ts
Labels: ui, n8n team

#5994 refactor(editor): Go to upgrade page
  packages/editor-ui/src/components/CredentialEdit/CredentialSharing.ee.vue
  packages/editor-ui/src/components/ExecutionFilter.vue
  packages/editor-ui/src/components/MainHeader/WorkflowDetails.vue
  packages/editor-ui/src/components/WorkflowShareModal.ee.vue
  packages/editor-ui/src/components/__tests__/ExecutionFilter.test.ts
  packages/editor-ui/src/stores/__tests__/ui.test.ts
  packages/editor-ui/src/stores/ui.ts
  packages/editor-ui/src/views/SettingsUsersView.vue
Labels: ui, n8n team

#6011 fix(core): Use tablePrefix in the CreateVariables migration (no-changelog)
  packages/cli/src/databases/migrations/postgresdb/1677501636754-CreateVariables.ts
Labels: core, n8n team

#6002 refactor(Code Node): Constently handle various kinds of data returned by user code
  packages/nodes-base/nodes/Code/Code.node.ts
  packages/nodes-base/nodes/Code/Sandbox.ts
  packages/nodes-base/nodes/Code/test/Code.node.test.ts
  packages/nodes-base/nodes/Code/utils.ts
  packages/workflow/src/Interfaces.ts
  packages/workflow/src/WorkflowDataProxy.ts
Labels: node/improvement, n8n team

#5676 feat(core): Add support for digestAuth to httpRequest and declarative style
  packages/cli/src/CredentialsHelper.ts
  packages/core/src/NodeExecuteFunctions.ts
  packages/workflow/src/Interfaces.ts
Labels: core, n8n team

#4877 feat(Google BigQuery Node): Node improvements
  packages/nodes-base/credentials/GoogleBigQueryOAuth2Api.credentials.ts
  packages/nodes-base/nodes/Google/BigQuery/GoogleBigQuery.node.ts
  packages/nodes-base/nodes/Google/BigQuery/test/v2/node/executeQuery.test.ts
  packages/nodes-base/nodes/Google/BigQuery/test/v2/node/executeQuery.workflow.json
  packages/nodes-base/nodes/Google/BigQuery/test/v2/node/insert.autoMapMode.test.ts
  packages/nodes-base/nodes/Google/BigQuery/test/v2/node/insert.autoMapMode.workflow.json
  packages/nodes-base/nodes/Google/BigQuery/test/v2/node/insert.manualMode.test.ts
  packages/nodes-base/nodes/Google/BigQuery/test/v2/node/insert.manualMode.workflow.json
  packages/nodes-base/nodes/Google/BigQuery/test/v2/utils/utils.test.ts
  packages/nodes-base/nodes/Google/BigQuery/v1/GenericFunctions.ts
  packages/nodes-base/nodes/Google/BigQuery/v1/GoogleBigQueryV1.node.ts
  packages/nodes-base/nodes/Google/BigQuery/v1/RecordDescription.ts
  packages/nodes-base/nodes/Google/BigQuery/v2/GoogleBigQueryV2.node.ts
  packages/nodes-base/nodes/Google/BigQuery/v2/actions/commonDescriptions/RLC.description.ts
  packages/nodes-base/nodes/Google/BigQuery/v2/actions/database/Database.resource.ts
  packages/nodes-base/nodes/Google/BigQuery/v2/actions/database/executeQuery.operation.ts
  packages/nodes-base/nodes/Google/BigQuery/v2/actions/database/insert.operation.ts
  packages/nodes-base/nodes/Google/BigQuery/v2/actions/node.type.ts
  packages/nodes-base/nodes/Google/BigQuery/v2/actions/router.ts
  packages/nodes-base/nodes/Google/BigQuery/v2/actions/versionDescription.ts
  packages/nodes-base/nodes/Google/BigQuery/v2/helpers/interfaces.ts
  packages/nodes-base/nodes/Google/BigQuery/v2/helpers/utils.ts
  packages/nodes-base/nodes/Google/BigQuery/v2/methods/index.ts
  packages/nodes-base/nodes/Google/BigQuery/v2/methods/listSearch.ts
  packages/nodes-base/nodes/Google/BigQuery/v2/methods/loadOptions.ts
  packages/nodes-base/nodes/Google/BigQuery/v2/transport/index.ts
  packages/nodes-base/package.json
Labels: node/improvement, n8n team

#6016 fix(editor): Update SSO upgrade link
  packages/editor-ui/src/views/SettingsSso.vue
Labels: ui, n8n team

#6006 feat(core): Add SSH key generation
  packages/cli/package.json
  packages/cli/src/License.ts
  packages/cli/src/Server.ts
  packages/cli/src/environment/versionControl/versionControlHelper.ee.ts
  packages/cli/src/environment/versionControl/versionControlHelper.ts
  packages/cli/src/environments/versionControl/constants.ts
  packages/cli/src/environments/versionControl/middleware/versionControlEnabledMiddleware.ts
  packages/cli/src/environments/versionControl/types/keyPair.ts
  packages/cli/src/environments/versionControl/types/versionControlPreferences.ts
  packages/cli/src/environments/versionControl/versionControl.controller.ee.ts
  packages/cli/src/environments/versionControl/versionControl.service.ee.ts
  packages/cli/src/environments/versionControl/versionControlHelper.ts
  packages/cli/src/sso/saml/saml.service.ee.ts
  packages/cli/test/integration/environments/VersionControl.test.ts
  packages/cli/test/integration/shared/types.d.ts
  packages/cli/test/integration/shared/utils.ts
  packages/cli/test/unit/VersionControl.test.ts
  pnpm-lock.yaml
Labels: core, n8n team

#6010 fix(core): Improve domain and url matching for extractDomain and extractUrl
  packages/workflow/src/Extensions/StringExtensions.ts
  packages/workflow/test/ExpressionExtensions/StringExtensions.test.ts
Labels: core, n8n team

#6018 docs: Update the info URL for updating n8n (no-changelog)
  cypress/fixtures/Settings_user_activation_modal_enabled.json
Labels: n8n team

#6025 fix(editor): SettingsSidebar should disconnect from push when navigating away
  packages/editor-ui/src/components/SettingsSidebar.vue
  packages/editor-ui/src/views/SettingsCommunityNodesView.vue
Labels: ui, n8n team

#6021 fix(editor): Fix memory leak in Node Detail View by correctly unsubscribing from event buses
  cypress/e2e/14-data-transformation-expressions.cy.ts
  cypress/e2e/14-mapping.cy.ts
  cypress/e2e/16-webhook-node.cy.ts
  packages/editor-ui/src/components/ExpandableInput/ExpandableInputEdit.vue
  packages/editor-ui/src/components/Modal.vue
  packages/editor-ui/src/components/ModalDrawer.vue
  packages/editor-ui/src/components/NodeDetailsView.vue
  packages/editor-ui/src/components/NodeSettings.vue
  packages/editor-ui/src/components/RunData.vue
  packages/editor-ui/src/components/SettingsLogStreaming/EventDestinationCard.ee.vue
  packages/editor-ui/src/components/TagsDropdown.vue
  packages/editor-ui/src/views/NodeView.vue
  packages/editor-ui/src/views/SettingsLogStreamingView.vue
Labels: ui, n8n team

#6023 fix(editor): Clean up demo and template callouts from workflows page
  packages/editor-ui/src/plugins/i18n/locales/en.json
  packages/editor-ui/src/views/WorkflowsView.vue
Labels: ui, n8n team

#6022 fix(Notion Node): Update credential test to not require user permissions
  packages/nodes-base/credentials/NotionApi.credentials.ts
Labels: node/improvement, n8n team

#6024 docs: Add api notice to credentials for google sheets nodes (no-changelog)
  packages/nodes-base/credentials/GoogleSheetsOAuth2Api.credentials.ts
  packages/nodes-base/credentials/GoogleSheetsTriggerOAuth2Api.credentials.ts
Labels: node/improvement, n8n team

#6028 fix(editor): Add correct add variable button message when no variables created (no-changelog)
  packages/editor-ui/src/plugins/i18n/locales/en.json
  packages/editor-ui/src/views/VariablesView.vue
Labels: ui, n8n team

#6027 feat: Add variables e2e tests (no-changelog)
  cypress/e2e/23-variables.cy.ts
  cypress/pages/variables.ts
  packages/editor-ui/src/components/VariablesRow.vue
  packages/editor-ui/src/components/__tests__/__snapshots__/VariablesRow.spec.ts.snap
  packages/editor-ui/src/views/VariablesView.vue
Labels: ui, n8n team

#6014 refactor: Accumulate `loadOptions` from all node versions to validate (no-changelog)
  packages/core/bin/generate-ui-types
  packages/core/src/DirectoryLoader.ts
Labels: core, n8n team

#5455 test(n8n Node): Unit tests (no-changelog)
  packages/nodes-base/nodes/N8n/test/node/N8n.test.ts
  packages/nodes-base/nodes/N8n/test/node/workflow.n8n.workflows.json
Labels: n8n team, tech debt, skip-e2e

#6038 docs: Add proprietary license text (no-changelog)
  README.md
  packages/cli/README.md
  packages/core/README.md
  packages/design-system/README.md
  packages/editor-ui/README.md
  packages/node-dev/README.md
  packages/nodes-base/README.md
  packages/workflow/README.md
Labels: node/improvement, core, ui, n8n team

#6039 fix(Code Node): Update vm2 to address CVE-2023-30547
  packages/nodes-base/package.json
  pnpm-lock.yaml
Labels: n8n team

#6042 feat(core): Upgrade google-timezones-json to use the correct timezone for Sao Paulo
  packages/cli/package.json
  pnpm-lock.yaml
Labels: core, n8n team

#5963 feat(editor): Add disable template experiment
  packages/editor-ui/src/constants.ts
  packages/editor-ui/src/router.ts
  packages/editor-ui/src/stores/posthog.ts
  packages/editor-ui/src/stores/settings.ts
  packages/editor-ui/src/utils/nodeTypesUtils.ts
Labels: ui, n8n team

#6030 feat(editor): Version control paywall (WIP)
  packages/editor-ui/src/plugins/i18n/locales/en.json
  packages/editor-ui/src/stores/versionControl.ts
  packages/editor-ui/src/views/SettingsVersionControl.vue
  packages/editor-ui/src/views/__tests__/SettingsVersionControl.test.ts
Labels: ui, n8n team

#6048 fix(core): Add breaking change record for domain and url matching (no-changelog)
  packages/cli/BREAKING-CHANGES.md
Labels: core, n8n team

#6051 refactor(core): Sort variables files under variables folder
  packages/cli/src/Server.ts
  packages/cli/src/environment/versionControl/versionControlHelper.ee.ts
  packages/cli/src/environments/variables/enviromentHelpers.ts
  packages/cli/src/environments/variables/variables.controller.ee.ts
  packages/cli/src/environments/variables/variables.controller.ts
  packages/cli/src/environments/variables/variables.service.ee.ts
  packages/cli/src/environments/variables/variables.service.ts
  packages/cli/test/integration/shared/utils.ts
Labels: core, n8n team

#5929 refactor(core): Forbid raw enums (no-changelog)
  packages/@n8n_io/eslint-config/base.js
  packages/cli/src/CurlConverterHelper.ts
  packages/cli/src/constants.ts
  packages/cli/src/databases/entities/WorkflowStatistics.ts
  packages/cli/src/events/WorkflowStatistics.ts
  packages/editor-ui/src/Interface.ts
  packages/editor-ui/src/constants.ts
  packages/editor-ui/src/models/history.ts
  packages/editor-ui/src/permissions.ts
  packages/nodes-base/.eslintrc.js
  packages/nodes-base/nodes/Aws/DynamoDB/types.d.ts
  packages/nodes-base/nodes/Clockify/CommonDtos.ts
  packages/nodes-base/nodes/Clockify/EntryTypeEnum.ts
  packages/nodes-base/nodes/Clockify/ProjectInterfaces.ts
  packages/nodes-base/nodes/Clockify/UserDtos.ts
  packages/nodes-base/nodes/Clockify/WorkpaceInterfaces.ts
  packages/nodes-base/nodes/Cortex/AnalyzerInterface.ts
  packages/nodes-base/nodes/Formstack/GenericFunctions.ts
  packages/nodes-base/nodes/Freshdesk/Freshdesk.node.ts
  packages/nodes-base/nodes/Google/Chat/MessageInterface.ts
  packages/nodes-base/nodes/Google/Sheet/v2/helpers/GoogleSheets.types.ts
  packages/nodes-base/nodes/ItemLists/V1/summarize.operation.ts
  packages/nodes-base/nodes/ItemLists/V2/summarize.operation.ts
  packages/nodes-base/nodes/Mailchimp/Mailchimp.node.ts
  packages/nodes-base/nodes/PayPal/PaymentInteface.ts
  packages/nodes-base/nodes/SendInBlue/GenericFunctions.ts
  packages/nodes-base/nodes/TheHive/interfaces/AlertInterface.ts
  packages/nodes-base/nodes/TheHive/interfaces/CaseInterface.ts
  packages/nodes-base/nodes/TheHive/interfaces/LogInterface.ts
  packages/nodes-base/nodes/TheHive/interfaces/ObservableInterface.ts
  packages/nodes-base/nodes/TheHive/interfaces/TaskInterface.ts
  packages/nodes-base/nodes/Todoist/v1/OperationHandler.ts
  packages/nodes-base/nodes/Todoist/v1/Service.ts
  packages/nodes-base/nodes/Todoist/v1/TodoistV1.node.ts
  packages/nodes-base/nodes/Todoist/v2/OperationHandler.ts
  packages/nodes-base/nodes/Todoist/v2/Service.ts
  packages/nodes-base/nodes/Todoist/v2/TodoistV2.node.ts
  packages/workflow/src/Interfaces.ts
  packages/workflow/src/MessageEventBus.ts
Labels: n8n team, tech debt

#6055 refactor(editor): Consolidate IN8nUISettings interface
  packages/cli/src/Interfaces.ts
  packages/cli/src/Server.ts
  packages/editor-ui/src/Interface.ts
  packages/editor-ui/src/__tests__/server/endpoints/settings.ts
  packages/editor-ui/src/api/settings.ts
  packages/editor-ui/src/components/WorkflowSettings.vue
  packages/editor-ui/src/stores/__tests__/posthog.test.ts
  packages/editor-ui/src/stores/__tests__/sso.test.ts
  packages/editor-ui/src/stores/settings.ts
  packages/editor-ui/src/utils/__tests__/userUtils.test.ts
  packages/workflow/src/Interfaces.ts
Labels: core, ui, n8n team

#6052 ci(editor): Do not run parallel jobs for a single spec
  .github/workflows/e2e-reusable.yml
  .github/workflows/e2e-tests-pr.yml
Labels: n8n team

#5859 fix(editor): Resolve expressions for grandparent nodes
  cypress/e2e/14-mapping.cy.ts
  cypress/e2e/24-ndv-paired-item.cy.ts
  cypress/e2e/5-ndv.cy.ts
  cypress/fixtures/Test_workflow_5.json
  cypress/pages/ndv.ts
  packages/editor-ui/src/components/ExpressionParameterInput.vue
  packages/editor-ui/src/components/ParameterInputWrapper.vue
  packages/editor-ui/src/components/RunData.vue
  packages/editor-ui/src/components/RunDataTable.vue
  packages/editor-ui/src/mixins/expressionManager.ts
  packages/editor-ui/src/mixins/workflowHelpers.ts
  packages/editor-ui/src/stores/ndv.ts
  packages/editor-ui/src/stores/workflows.ts
Labels: ui, n8n team

#6057 refactor: Patch to adjust `consistent-type-imports` (no-changelog)
  package.json
  patches/@typescript-eslint__eslint-plugin@5.45.0.patch
  pnpm-lock.yaml
Labels: n8n team

#5413 test: Add stickies tests
  cypress/e2e/25-stickies.cy.ts
  cypress/pages/workflow.ts
  cypress/support/commands.ts
  cypress/support/index.ts
  packages/editor-ui/src/components/Node/NodeCreation.vue
  packages/editor-ui/src/components/Sticky.vue
Labels: ui, n8n team

#6059 refactor(editor): Turn titleChange mixin to composable
  packages/editor-ui/src/components/MainHeader/WorkflowDetails.vue
  packages/editor-ui/src/components/MainSidebar.vue
  packages/editor-ui/src/composables/useTitleChange.ts
  packages/editor-ui/src/mixins/pushConnection.ts
  packages/editor-ui/src/mixins/titleChange.ts
  packages/editor-ui/src/mixins/workflowRun.ts
  packages/editor-ui/src/views/NodeView.vue
Labels: ui, n8n team

#6050 feat: Replace this.$refs.refName as Vue with InstanceType<T> (no-changelog)
  packages/design-system/src/components/N8nButton/overrides/ElButton.vue
  packages/design-system/src/components/N8nInput/Input.vue
  packages/design-system/src/components/N8nSelect/Select.vue
  packages/design-system/src/components/index.ts
  packages/design-system/src/main.ts
  packages/design-system/src/plugin.ts
  packages/design-system/src/plugins/n8nComponents.ts
  packages/editor-ui/src/components/CodeNodeEditor/CodeNodeEditor.vue
  packages/editor-ui/src/components/CollectionsCarousel.vue
  packages/editor-ui/src/components/CredentialEdit/CredentialEdit.vue
  packages/editor-ui/src/components/CredentialsSelect.vue
  packages/editor-ui/src/components/CredentialsSelectModal.vue
  packages/editor-ui/src/components/DraggableTarget.vue
  packages/editor-ui/src/components/DuplicateWorkflowDialog.vue
  packages/editor-ui/src/components/ExecutionsView/ExecutionPreview.vue
  packages/editor-ui/src/components/ExecutionsView/ExecutionsSidebar.vue
  packages/editor-ui/src/components/ExpressionParameterInput.vue
  packages/editor-ui/src/components/HtmlEditor/HtmlEditor.vue
  packages/editor-ui/src/components/InlineNameEdit.vue
  packages/editor-ui/src/components/MainHeader/WorkflowDetails.vue
  packages/editor-ui/src/components/NodeTitle.vue
  packages/editor-ui/src/components/OutputPanel.vue
  packages/editor-ui/src/components/ParameterInput.vue
  packages/editor-ui/src/components/ParameterInputExpanded.vue
  packages/editor-ui/src/components/ParameterInputFull.vue
  packages/editor-ui/src/components/ParameterInputWrapper.vue
  packages/editor-ui/src/components/ResourceLocator/ResourceLocator.vue
  packages/editor-ui/src/components/ResourceLocator/ResourceLocatorDropdown.vue
  packages/editor-ui/src/components/RunData.vue
  packages/editor-ui/src/components/RunDataTable.vue
  packages/editor-ui/src/components/TagsDropdown.vue
  packages/editor-ui/src/components/TagsManager/TagsView/TagsTable.vue
  packages/editor-ui/src/components/TemplateList.vue
  packages/editor-ui/src/components/TriggerPanel.vue
  packages/editor-ui/src/components/WorkflowCard.vue
  packages/editor-ui/src/components/WorkflowPreview.vue
  packages/editor-ui/src/components/layouts/ResourcesListLayout.vue
  packages/editor-ui/src/mixins/emitter.ts
  packages/editor-ui/src/plugins/components.ts
  packages/editor-ui/src/views/NodeView.vue
  packages/editor-ui/src/views/SettingsLdapView.vue
Labels: ui, n8n team

#6047 feat(core): Add license:info command
  packages/cli/package.json
  packages/cli/src/License.ts
  packages/cli/src/commands/license/info.ts
  packages/cli/src/config/schema.ts
  packages/cli/src/license/license.controller.ts
  pnpm-lock.yaml
Labels: core, n8n team

#5940 feat(core): Add migration to add property userActivated to user settings (no-changelog)
  packages/cli/src/Interfaces.ts
  packages/cli/src/databases/migrations/mysqldb/1681134145996-AddUserActivatedProperty.ts
  packages/cli/src/databases/migrations/mysqldb/index.ts
  packages/cli/src/databases/migrations/postgresdb/1681134145996-AddUserActivatedProperty.ts
  packages/cli/src/databases/migrations/postgresdb/index.ts
  packages/cli/src/databases/migrations/sqlite/1681134145996-AddUserActivatedProperty.ts
  packages/cli/src/databases/migrations/sqlite/index.ts
Labels: core, n8n team

#5970 feat(core): Resource editor componend P0
  packages/editor-ui/src/components/ParameterInput.vue
  packages/editor-ui/src/components/ParameterInputFull.vue
  packages/editor-ui/src/components/ParameterInputList.vue
  packages/editor-ui/src/components/ParameterInputWrapper.vue
  packages/editor-ui/src/components/ResourceMapper/MappingModeSelect.vue
  packages/editor-ui/src/components/ResourceMapper/MatchingColumnsSelect.vue
  packages/editor-ui/src/components/ResourceMapper/ResourceMapper.vue
  packages/editor-ui/src/components/__tests__/ResourceMapper.test.ts
  packages/editor-ui/src/components/__tests__/utils/ResourceMapper.utils.ts
  packages/editor-ui/src/constants.ts
  packages/editor-ui/src/plugins/i18n/locales/en.json
  packages/editor-ui/src/stores/nodeTypes.ts
  packages/editor-ui/src/utils/typeGuards.ts
  packages/nodes-base/nodes/Google/Sheet/v2/actions/sheet/append.operation.ts
  packages/nodes-base/nodes/Google/Sheet/v2/actions/sheet/appendOrUpdate.operation.ts
  packages/nodes-base/nodes/Google/Sheet/v2/actions/sheet/update.operation.ts
  packages/nodes-base/nodes/Google/Sheet/v2/helpers/GoogleSheets.utils.ts
  packages/nodes-base/nodes/Google/Sheet/v2/methods/resourceMapping.ts
  packages/nodes-base/nodes/Postgres/v2/actions/database/insert.operation.ts
  packages/nodes-base/nodes/Postgres/v2/actions/database/update.operation.ts
  packages/nodes-base/nodes/Postgres/v2/actions/database/upsert.operation.ts
  packages/nodes-base/nodes/Postgres/v2/helpers/utils.ts
  packages/nodes-base/nodes/Postgres/v2/methods/resourceMapping.ts
  packages/nodes-base/nodes/Postgres/v2/transport/index.ts
  packages/workflow/src/Interfaces.ts
Labels: node/improvement, core, ui, n8n team

#6065 refactor(editor): Remove the `restApi` mixin
  packages/editor-ui/src/App.vue
  packages/editor-ui/src/Interface.ts
  packages/editor-ui/src/components/BinaryDataDisplay.vue
  packages/editor-ui/src/components/BinaryDataDisplayEmbed.vue
  packages/editor-ui/src/components/CredentialEdit/CredentialConfig.vue
  packages/editor-ui/src/components/DuplicateWorkflowDialog.vue
  packages/editor-ui/src/components/ExecutionsList.vue
  packages/editor-ui/src/components/ExecutionsView/ExecutionCard.vue
  packages/editor-ui/src/components/ExecutionsView/ExecutionPreview.vue
  packages/editor-ui/src/components/ExecutionsView/ExecutionsList.vue
  packages/editor-ui/src/components/MainHeader/WorkflowDetails.vue
  packages/editor-ui/src/components/MainSidebar.vue
  packages/editor-ui/src/components/NodeCredentials.vue
  packages/editor-ui/src/components/NodeExecuteButton.vue
  packages/editor-ui/src/components/RunData.vue
  packages/editor-ui/src/components/UserActivationSurveyModal.vue
  packages/editor-ui/src/components/WorkflowActivator.vue
  packages/editor-ui/src/components/WorkflowCard.vue
  packages/editor-ui/src/components/WorkflowSettings.vue
  packages/editor-ui/src/components/WorkflowShareModal.ee.vue
  packages/editor-ui/src/components/__tests__/ExecutionsList.test.ts
  packages/editor-ui/src/mixins/nodeHelpers.ts
  packages/editor-ui/src/mixins/workflowHelpers.ts
  packages/editor-ui/src/mixins/workflowRun.ts
  packages/editor-ui/src/stores/credentials.ts
  packages/editor-ui/src/stores/settings.ts
  packages/editor-ui/src/stores/workflows.ts
  packages/editor-ui/src/utils/apiUtils.ts
  packages/editor-ui/src/views/NodeView.vue
  packages/editor-ui/src/views/SetupView.vue
Labels: ui, n8n team

#5787 refactor(core): Setup decorator based RBAC (no-changelog)
  packages/cli/src/UserManagement/UserManagementHelper.ts
  packages/cli/src/controllers/auth.controller.ts
  packages/cli/src/controllers/ldap.controller.ts
  packages/cli/src/controllers/me.controller.ts
  packages/cli/src/controllers/nodeTypes.controller.ts
  packages/cli/src/controllers/nodes.controller.ts
  packages/cli/src/controllers/owner.controller.ts
  packages/cli/src/controllers/passwordReset.controller.ts
  packages/cli/src/controllers/tags.controller.ts
  packages/cli/src/controllers/translation.controller.ts
  packages/cli/src/controllers/users.controller.ts
  packages/cli/src/decorators/Authorized.ts
  packages/cli/src/decorators/constants.ts
  packages/cli/src/decorators/index.ts
  packages/cli/src/decorators/registerController.ts
  packages/cli/src/decorators/types.ts
  packages/cli/src/eventbus/eventBus.controller.ts
  packages/cli/src/middlewares/auth.ts
  packages/cli/src/middlewares/isOwner.ts
  packages/cli/src/sso/saml/middleware/samlEnabledMiddleware.ts
  packages/cli/src/sso/saml/routes/saml.controller.ee.ts
  packages/cli/test/integration/shared/constants.ts
  packages/cli/test/integration/users.api.test.ts
Labels: core, n8n team

#5923 SSO/SAML : add Base URL to redirects in acsHandler
  packages/cli/src/sso/saml/routes/saml.controller.ee.ts
Labels: core, community

#6071 docs: Remove version notice from overhauled nodes (no-changelog)
  packages/nodes-base/nodes/EmailSend/v1/EmailSendV1.node.ts
  packages/nodes-base/nodes/Google/BigQuery/v1/GoogleBigQueryV1.node.ts
  packages/nodes-base/nodes/MySql/v1/MySqlV1.node.ts
  packages/nodes-base/nodes/Postgres/v1/PostgresV1.node.ts
Labels: node/improvement, n8n team

#6074 refactor(editor): Delete leftover restApi mixin file (no-changelog)
  packages/editor-ui/src/components/MainHeader/WorkflowDetails.vue
  packages/editor-ui/src/components/UserActivationSurveyModal.vue
  packages/editor-ui/src/components/WorkflowCard.vue
  packages/editor-ui/src/components/WorkflowShareModal.ee.vue
  packages/editor-ui/src/mixins/restApi.ts
  packages/editor-ui/src/plugins/i18n/locales/en.json
  packages/editor-ui/src/stores/workflows.ts
Labels: ui, n8n team

#6007 feat(core): Add instanceId to n8n.ready hook (no-changelog)
  packages/cli/src/AbstractServer.ts
  packages/cli/src/Server.ts
Labels: core, n8n team

#6069 fix(editor): Update LDAP and Log streaming paywalls
  packages/editor-ui/src/plugins/i18n/locales/en.json
  packages/editor-ui/src/views/SettingsLdapView.vue
  packages/editor-ui/src/views/SettingsLogStreamingView.vue
  packages/editor-ui/src/views/SettingsSso.vue
Labels: ui, n8n team

#6075 ci: Fix linting error on `master` (no-changelog)
  packages/core/src/BinaryDataManager/index.ts
Labels: core, n8n team

#6079 feat(core): Manage version control settings
  packages/cli/src/environments/versionControl/middleware/versionControlEnabledMiddleware.ts
  packages/cli/src/environments/versionControl/types/requests.ts
  packages/cli/src/environments/versionControl/types/versionControlPreferences.ts
  packages/cli/src/environments/versionControl/versionControl.controller.ee.ts
  packages/cli/src/environments/versionControl/versionControl.service.ee.ts
  packages/cli/src/environments/versionControl/versionControlHelper.ts
Labels: core, n8n team

#6084 refactor(editor): Track advanced filter custom data usage
  packages/editor-ui/src/components/ExecutionFilter.vue
  packages/editor-ui/src/components/__tests__/ExecutionFilter.test.ts
Labels: ui, n8n team

#5517 feat(editor): Add SQL editor support
  packages/editor-ui/package.json
  packages/editor-ui/src/components/ParameterInput.vue
  packages/editor-ui/src/components/SqlEditor/SqlEditor.vue
  packages/nodes-base/nodes/CrateDb/CrateDb.node.ts
  packages/nodes-base/nodes/Google/BigQuery/v2/actions/database/executeQuery.operation.ts
  packages/nodes-base/nodes/Microsoft/Sql/MicrosoftSql.node.ts
  packages/nodes-base/nodes/MySql/v1/MySqlV1.node.ts
  packages/nodes-base/nodes/MySql/v2/actions/database/executeQuery.operation.ts
  packages/nodes-base/nodes/Postgres/v1/PostgresV1.node.ts
  packages/nodes-base/nodes/Postgres/v2/actions/database/executeQuery.operation.ts
  packages/nodes-base/nodes/QuestDb/QuestDb.node.ts
  packages/nodes-base/nodes/Snowflake/Snowflake.node.ts
  packages/nodes-base/nodes/TimescaleDb/TimescaleDb.node.ts
  packages/workflow/src/Interfaces.ts
  pnpm-lock.yaml
Labels: node/improvement, core, ui, n8n team

#6058 fix(editor): Make the frontend work again when `NODE_FUNCTION_ALLOW_EXTERNAL` is set (no-changelog)
  packages/cli/src/config/index.ts
  packages/editor-ui/src/stores/settings.ts
Labels: ui, n8n team

#5954 feat(editor): Enhance Node Creator actions view
  cypress/e2e/11-inline-expression-editor.cy.ts
  cypress/e2e/13-pinning.cy.ts
  cypress/e2e/4-node-creator.cy.ts
  cypress/e2e/9-expression-editor-modal.cy.ts
  cypress/pages/features/node-creator.ts
  cypress/pages/workflow.ts
  packages/design-system/src/components/N8nCallout/Callout.vue
  packages/design-system/src/components/N8nCallout/__tests__/__snapshots__/Callout.spec.ts.snap
  packages/design-system/src/components/N8nNodeCreatorNode/NodeCreatorNode.vue
  packages/design-system/src/components/N8nNodeIcon/NodeIcon.vue
  packages/editor-ui/package.json
  packages/editor-ui/src/Interface.ts
  packages/editor-ui/src/components/Node/NodeCreator/CategorizedItems.vue
  packages/editor-ui/src/components/Node/NodeCreator/CategoryItem.vue
  packages/editor-ui/src/components/Node/NodeCreator/ItemIterator.vue
  packages/editor-ui/src/components/Node/NodeCreator/ItemTypes/ActionItem.vue
  packages/editor-ui/src/components/Node/NodeCreator/ItemTypes/CategoryItem.vue
  packages/editor-ui/src/components/Node/NodeCreator/ItemTypes/LabelItem.vue
  packages/editor-ui/src/components/Node/NodeCreator/ItemTypes/NodeItem.vue
  packages/editor-ui/src/components/Node/NodeCreator/ItemTypes/SubcategoryItem.vue
  packages/editor-ui/src/components/Node/NodeCreator/ItemTypes/ViewItem.vue
  packages/editor-ui/src/components/Node/NodeCreator/MainPanel.vue
  packages/editor-ui/src/components/Node/NodeCreator/Modes/ActionsMode.vue
  packages/editor-ui/src/components/Node/NodeCreator/Modes/NodesMode.vue
  packages/editor-ui/src/components/Node/NodeCreator/NodeCreator.vue
  packages/editor-ui/src/components/Node/NodeCreator/Panel/NoResults.vue
  packages/editor-ui/src/components/Node/NodeCreator/Panel/NoResultsIcon.vue
  packages/editor-ui/src/components/Node/NodeCreator/Panel/NodesListPanel.vue
  packages/editor-ui/src/components/Node/NodeCreator/Panel/SearchBar.vue
  packages/editor-ui/src/components/Node/NodeCreator/Renderers/CategorizedItemsRenderer.vue
  packages/editor-ui/src/components/Node/NodeCreator/Renderers/ItemsRenderer.vue
  packages/editor-ui/src/components/Node/NodeCreator/__tests__/CategoryItem.test.ts
  packages/editor-ui/src/components/Node/NodeCreator/__tests__/ItemsRenderer.test.ts
  packages/editor-ui/src/components/Node/NodeCreator/__tests__/NodesListPanel.test.ts
  packages/editor-ui/src/components/Node/NodeCreator/__tests__/useKeyboardNavigation.test.ts
  packages/editor-ui/src/components/Node/NodeCreator/__tests__/utils.ts
  packages/editor-ui/src/components/Node/NodeCreator/composables/useActions.ts
  packages/editor-ui/src/components/Node/NodeCreator/composables/useActionsGeneration.ts
  packages/editor-ui/src/components/Node/NodeCreator/composables/useKeyboardNavigation.ts
  packages/editor-ui/src/components/Node/NodeCreator/composables/useViewStacks.ts
  packages/editor-ui/src/components/Node/NodeCreator/useMainPanelView.ts
  packages/editor-ui/src/components/Node/NodeCreator/utils.ts
  packages/editor-ui/src/components/Node/NodeCreator/viewsData.ts
  packages/editor-ui/src/components/transitions/SlideTransition.vue
  packages/editor-ui/src/constants.ts
  packages/editor-ui/src/main.ts
  packages/editor-ui/src/plugins/i18n/locales/en.json
  packages/editor-ui/src/plugins/telemetry/index.ts
  packages/editor-ui/src/stores/nodeCreator.ts
  packages/editor-ui/src/stores/nodeTypes.ts
  packages/editor-ui/src/utils/nodeTypesUtils.ts
  packages/editor-ui/src/views/NodeView.vue
  packages/workflow/src/Interfaces.ts
  pnpm-lock.yaml
Labels: core, ui, n8n team

#6086 fix(core): Serialize dates and regexps when reading from augmented objects
  packages/workflow/src/AugmentObject.ts
  packages/workflow/test/AugmentObject.test.ts
Labels: core, n8n team

#6088 ci: Update the release workflow (no-changelog)
  .github/workflows/release-publish.yml
Labels: n8n team

#6036 feat(editor): Add version controls settings (WIP)
  packages/editor-ui/src/App.vue
  packages/editor-ui/src/Interface.ts
  packages/editor-ui/src/api/versionControl.ts
  packages/editor-ui/src/components/MainSidebar.vue
  packages/editor-ui/src/composables/useMessage.ts
  packages/editor-ui/src/plugins/i18n/locales/en.json
  packages/editor-ui/src/stores/versionControl.ts
  packages/editor-ui/src/views/SettingsVersionControl.vue
Labels: ui, n8n team

#6097 fix(Mattermost Node): Fix base url trailing slash error
  packages/nodes-base/credentials/MattermostApi.credentials.ts
  packages/nodes-base/nodes/Mattermost/v1/transport/index.ts
Labels: node/improvement, n8n team

#6098 fix(Compression Node): Fix issue with decompression failing with uppercase extensions
  packages/nodes-base/nodes/Compression/Compression.node.ts
Labels: node/improvement, n8n team

#6099 fix(HTTP Request Node): Always lowercase headers
  packages/nodes-base/nodes/HttpRequest/V3/HttpRequestV3.node.ts
  packages/nodes-base/test/utils/utilities.test.ts
  packages/nodes-base/utils/utilities.ts
Labels: n8n team, node/issue

#6104 fix(editor): Disable changing of email and pw when SAML login enabled
  packages/editor-ui/src/views/SettingsPersonalView.vue
Labels: ui, n8n team

#6106 fix(core): Skip auth for controllers/routes that don't use the `Authorized` decorator, or use `Authorized('none')`
  packages/cli/src/decorators/registerController.ts
  packages/cli/src/middlewares/auth.ts
Labels: core, n8n team

#6105 ci: Additionally checkout PR head for e2e tests (no-changelog)
  .github/workflows/ci-pull-requests.yml
  .github/workflows/e2e-reusable.yml
Labels: n8n team

#6100 fix(editor): Loading state for executions tab
  packages/editor-ui/src/components/ExecutionsView/ExecutionsList.vue
  packages/editor-ui/src/components/ExecutionsView/ExecutionsSidebar.vue
Labels: ui, n8n team

#6108 fix(editor): Show error in RLC if credentials are not set
  packages/editor-ui/src/components/ResourceLocator/ResourceLocator.vue
  packages/editor-ui/src/plugins/i18n/locales/en.json
Labels: ui, n8n team

#6093 fix(editor): Remove pagination from binary data output
  packages/editor-ui/src/components/RunData.vue
Labels: ui, n8n team

#6114 fix(HTTP Request Node): Add description for 'Specify Body' option
  packages/nodes-base/nodes/HttpRequest/V3/HttpRequestV3.node.ts
Labels: node/improvement, n8n team

#6092 refactor(editor): Add skip option to activation modal
  cypress/e2e/22-user-activation-modal.cy.ts
  cypress/pages/modals/user-activation-survey-modal.ts
  packages/editor-ui/src/components/UserActivationSurveyModal.vue
  packages/editor-ui/src/plugins/i18n/locales/en.json
Labels: ui, n8n team

#6096 fix(editor): Change wording for Variables feature available plans
  packages/editor-ui/src/plugins/i18n/locales/en.json
Labels: ui, n8n team

#6121 fix(core): Only take into account users that active for the first time to show activation modal
  packages/cli/src/events/WorkflowStatistics.ts
Labels: core, n8n team

#6124 fix(core): Fix `hasOwnProperty` on augmented objects
  packages/workflow/src/AugmentObject.ts
  packages/workflow/test/AugmentObject.test.ts
Labels: core, n8n team

#6101 feat(editor): Add support for `loadOptionsDependsOn` to RLC
  cypress/e2e/26-resource-locator.cy.ts
  cypress/pages/ndv.ts
  packages/editor-ui/src/components/ParameterInput.vue
  packages/editor-ui/src/components/ResourceLocator/ResourceLocator.vue
  packages/editor-ui/src/components/ResourceLocator/ResourceLocatorDropdown.vue
  packages/nodes-base/nodes/Google/Sheet/v2/actions/sheet/Sheet.resource.ts
Labels: node/improvement, ui, n8n team

#6120 fix(editor): Change execution list tab loader design
  packages/editor-ui/src/components/ExecutionsView/ExecutionsSidebar.vue
Labels: ui, n8n team

#6131 fix(core): Avoid using `Object.keys` on Buffer and other non-plain objects
  packages/core/src/NodeExecuteFunctions.ts
  packages/nodes-base/credentials/Aws.credentials.ts
  packages/workflow/src/index.ts
  packages/workflow/src/utils.ts
  packages/workflow/test/utils.test.ts
Labels: node/improvement, core, n8n team

#6133 fix(editor): Fix unscrollable node settings
  packages/editor-ui/src/components/NodeSettings.vue
Labels: ui, n8n team

#6125 fix(editor): Fix missing `Stop Listening` button
  packages/editor-ui/src/components/TriggerPanel.vue
Labels: ui, n8n team

#6134 fix(editor): Fix unique names for node duplication
  packages/editor-ui/src/components/VariablesRow.vue
  packages/editor-ui/src/composables/__tests__/useUniqueNodeName.test.ts
  packages/editor-ui/src/composables/useI18n.ts
  packages/editor-ui/src/composables/useToast.ts
  packages/editor-ui/src/composables/useUniqueNodeName.ts
  packages/editor-ui/src/composables/useUpgradeLink.ts
  packages/editor-ui/src/stores/workflows.ts
  packages/editor-ui/src/views/NodeView.vue
  packages/editor-ui/src/views/VariablesView.vue
Labels: ui, n8n team

#6138 fix(editor): Fix sidebar button styling
  packages/editor-ui/src/components/MainSidebar.vue
Labels: ui, n8n team

#6113 fix(editor): Fix `Show details` summary
  packages/editor-ui/src/constants.ts
  packages/editor-ui/src/utils/htmlUtils.ts
Labels: ui, n8n team

#6137 fix: Prevent endless timer in execution list
  packages/editor-ui/src/components/ExecutionsList.vue
  packages/editor-ui/src/plugins/i18n/locales/en.json
Labels: ui, n8n team

#6107 fix(core): Improve saml endpoints and audit events
  packages/cli/src/Interfaces.ts
  packages/cli/src/InternalHooks.ts
  packages/cli/src/Server.ts
  packages/cli/src/controllers/auth.controller.ts
  packages/cli/src/eventbus/EventMessageClasses/index.ts
  packages/cli/src/sso/saml/routes/saml.controller.ee.ts
  packages/cli/test/integration/saml/saml.api.test.ts
Labels: core, n8n team

#6123 fix(Merge Node): Do not error if expected key is missing
  packages/nodes-base/nodes/CompareDatasets/CompareDatasets.node.ts
  packages/nodes-base/nodes/CompareDatasets/GenericFunctions.ts
  packages/nodes-base/nodes/CompareDatasets/test/node/workflow.update_2_2.json
  packages/nodes-base/nodes/CompareDatasets/test/utils/utils.test.ts
  packages/nodes-base/nodes/ItemLists/ItemLists.node.ts
  packages/nodes-base/nodes/ItemLists/V2/ItemListsV2.node.ts
  packages/nodes-base/nodes/ItemLists/V2/summarize.operation.ts
  packages/nodes-base/nodes/ItemLists/test/node/workflow.update_2_1.json
  packages/nodes-base/nodes/Merge/Merge.node.ts
  packages/nodes-base/nodes/Merge/test/node/workflow.update_2_1.json
  packages/nodes-base/nodes/Merge/v2/MergeV2.node.ts
Labels: n8n team, node/issue
