Repository n8n-io/n8n, pull requests merged in 2023-01, with the labels that each got.

#5065 refactor: Add lint rule `node-class-description-name-miscased` (no-changelog)
  packages/nodes-base/.eslintrc.js
  packages/nodes-base/nodes/Brandfetch/Brandfetch.node.ts
  packages/nodes-base/nodes/HaloPSA/HaloPSA.node.ts
  packages/nodes-base/nodes/ReadPdf/ReadPDF.node.ts
  packages/nodes-base/package.json
  pnpm-lock.yaml
Labels: node/improvement, n8n team

#5061 perf: Lazy-load queue-mode and analytics dependencies
  packages/cli/package.json
  packages/cli/src/ErrorReporting.ts
  packages/cli/src/InternalHooksManager.ts
  packages/cli/src/Queue.ts
  packages/cli/src/Server.ts
  packages/cli/src/WebhookServer.ts
  packages/cli/src/WorkflowRunner.ts
  packages/cli/src/WorkflowRunnerProcess.ts
  packages/cli/src/commands/execute.ts
  packages/cli/src/commands/executeBatch.ts
  packages/cli/src/commands/start.ts
  packages/cli/src/commands/webhook.ts
  packages/cli/src/commands/worker.ts
  packages/cli/src/executions/executions.service.ts
  packages/cli/src/telemetry/index.ts
  packages/cli/test/unit/Telemetry.test.ts
  pnpm-lock.yaml
Labels: core, n8n team

#5049 perf: Lazy-load public-api dependencies to reduce baseline memory usage
  packages/cli/src/Interfaces.ts
  packages/cli/src/PublicApi/index.ts
  packages/cli/src/Server.ts
  packages/cli/src/config/index.ts
  packages/cli/src/config/schema.ts
  packages/editor-ui/src/Interface.ts
  packages/editor-ui/src/plugins/i18n/locales/en.json
  packages/editor-ui/src/stores/settings.ts
  packages/editor-ui/src/views/SettingsApiView.vue
Labels: core, n8n team

#5069 refactor(Read Binary File Node): Use node streams for to reduce memory usage
  packages/core/package.json
  packages/core/src/BinaryDataManager/FileSystem.ts
  packages/core/src/BinaryDataManager/index.ts
  packages/core/src/Interfaces.ts
  packages/core/src/NodeExecuteFunctions.ts
  packages/nodes-base/nodes/ReadBinaryFile/ReadBinaryFile.node.ts
  packages/nodes-base/nodes/ReadBinaryFiles/ReadBinaryFiles.node.ts
  packages/workflow/src/Interfaces.ts
  pnpm-lock.yaml
Labels: node/improvement, core, n8n team

#5066 fix(editor): Clear node creator and scrim on workspace reset
  packages/editor-ui/src/views/NodeView.vue
Labels: ui, n8n team

#5068 fix(editor): Prevent scrim on executable triggers
  packages/editor-ui/src/components/NodeDetailsView.vue
  packages/editor-ui/src/constants.ts
Labels: ui, n8n team

#5076 feat(editor): Add SSO fakedoor feature
  packages/editor-ui/src/Interface.ts
  packages/editor-ui/src/constants.ts
  packages/editor-ui/src/plugins/i18n/locales/en.json
  packages/editor-ui/src/stores/ui.ts
  packages/editor-ui/src/views/SettingsUsersView.vue
Labels: ui, n8n team

#5077 fix(core): Upgrade `riot-tmpl` fork to 2.0.0 (no-changelog)
  packages/workflow/package.json
  pnpm-lock.yaml
Labels: core, n8n team

#5017 refactor(Google Drive Node): Use node streams for uploading and downloading files
  packages/core/src/BinaryDataManager/FileSystem.ts
  packages/core/src/BinaryDataManager/index.ts
  packages/core/src/Interfaces.ts
  packages/core/src/NodeExecuteFunctions.ts
  packages/nodes-base/nodes/Google/Drive/GoogleDrive.node.ts
  packages/workflow/src/Interfaces.ts
Labels: node/improvement, core, n8n team

#4862 feat(Compare Datasets Node): Fuzzy compare option
  packages/nodes-base/nodes/CompareDatasets/CompareDatasets.node.ts
  packages/nodes-base/nodes/CompareDatasets/GenericFunctions.ts
  packages/nodes-base/nodes/Merge/v2/GenericFunctions.ts
  packages/nodes-base/nodes/Merge/v2/OptionsDescription.ts
Labels: node/improvement, n8n team, node/issue

#5085 feat: Add FE inviteAcceptUrl integration
  packages/design-system/src/components/N8nUsersList/UsersList.stories.ts
  packages/design-system/src/components/N8nUsersList/UsersList.vue
  packages/design-system/src/locale/lang/en.js
  packages/design-system/src/types/user.ts
  packages/editor-ui/src/Interface.ts
  packages/editor-ui/src/components/CredentialEdit/CredentialSharing.ee.vue
  packages/editor-ui/src/components/InviteUsersModal.vue
  packages/editor-ui/src/components/WorkflowShareModal.ee.vue
  packages/editor-ui/src/plugins/i18n/locales/en.json
  packages/editor-ui/src/stores/users.ts
  packages/editor-ui/src/views/SettingsUsersView.vue
Labels: ui, n8n team

#5079 refactor: Return invite link URLs when inviting users
  packages/cli/src/UserManagement/Interfaces.ts
  packages/cli/src/UserManagement/UserManagementHelper.ts
  packages/cli/src/UserManagement/email/Interfaces.ts
  packages/cli/src/UserManagement/email/NodeMailer.ts
  packages/cli/src/UserManagement/email/UserManagementMailer.ts
  packages/cli/src/UserManagement/routes/passwordReset.ts
  packages/cli/src/UserManagement/routes/users.ts
  packages/cli/src/requests.d.ts
  packages/cli/test/integration/users.api.test.ts
  packages/design-system/src/types/user.ts
  packages/editor-ui/src/Interface.ts
  packages/editor-ui/src/components/InviteUsersModal.vue
  packages/editor-ui/src/plugins/i18n/locales/en.json
  packages/editor-ui/src/views/SettingsUsersView.vue
Labels: core, n8n team

#5072 fix: Apply credential overwrites recursively
  packages/cli/package.json
  packages/cli/src/CredentialTypes.ts
  packages/cli/src/CredentialsHelper.ts
  packages/cli/src/CredentialsOverwrites.ts
  packages/cli/src/LoadNodesAndCredentials.ts
  packages/cli/test/integration/shared/utils.ts
  packages/cli/test/unit/CredentialTypes.test.ts
  packages/cli/test/unit/CredentialsHelper.test.ts
  packages/cli/test/unit/PermissionChecker.test.ts
  packages/workflow/src/Interfaces.ts
  pnpm-lock.yaml
Labels: core, n8n team

#5088 fix(Respond to Webhook Node): Fix issue that content-type header gets overwritten
  packages/nodes-base/nodes/RespondToWebhook/RespondToWebhook.node.ts
Labels: node/improvement, n8n team

#5015 fix(core): Fixes issue with workflow lastUpdated field
  packages/cli/src/Server.ts
  packages/cli/src/api/workflowStats.api.ts
  packages/cli/src/commands/execute.ts
  packages/cli/src/commands/executeBatch.ts
  packages/cli/src/databases/entities/WorkflowEntity.ts
  packages/cli/src/databases/entities/WorkflowStatistics.ts
  packages/cli/src/databases/migrations/mysqldb/1671726148420-RemoveWorkflowDataLoadedFlag.ts
  packages/cli/src/databases/migrations/mysqldb/index.ts
  packages/cli/src/databases/migrations/postgresdb/1671726148421-RemoveWorkflowDataLoadedFlag.ts
  packages/cli/src/databases/migrations/postgresdb/index.ts
  packages/cli/src/databases/migrations/sqlite/1671726148419-RemoveWorkflowDataLoadedFlag.ts
  packages/cli/src/databases/migrations/sqlite/index.ts
  packages/cli/src/events/WorkflowStatistics.ts
  packages/cli/src/events/index.ts
  packages/cli/src/index.ts
  packages/cli/test/unit/Events.test.ts
Labels: core, n8n team

#5092 fix(Slack Node): Add missing channels:read OAuth2 scope
  packages/nodes-base/credentials/SlackOAuth2Api.credentials.ts
Labels: node/improvement, n8n team

#5084 feat: Add user management invite links without SMTP set up
  packages/cli/src/InternalHooks.ts
  packages/cli/src/UserManagement/Interfaces.ts
  packages/cli/src/UserManagement/UserManagementHelper.ts
  packages/cli/src/UserManagement/email/Interfaces.ts
  packages/cli/src/UserManagement/email/NodeMailer.ts
  packages/cli/src/UserManagement/email/UserManagementMailer.ts
  packages/cli/src/UserManagement/routes/passwordReset.ts
  packages/cli/src/UserManagement/routes/users.ts
  packages/cli/src/requests.d.ts
  packages/cli/test/integration/users.api.test.ts
  packages/design-system/src/components/N8nUsersList/UsersList.stories.ts
  packages/design-system/src/components/N8nUsersList/UsersList.vue
  packages/design-system/src/locale/lang/en.js
  packages/design-system/src/types/user.ts
  packages/editor-ui/src/Interface.ts
  packages/editor-ui/src/api/users.ts
  packages/editor-ui/src/components/CredentialEdit/CredentialSharing.ee.vue
  packages/editor-ui/src/components/InviteUsersModal.vue
  packages/editor-ui/src/components/WorkflowShareModal.ee.vue
  packages/editor-ui/src/plugins/i18n/locales/en.json
  packages/editor-ui/src/stores/users.ts
  packages/editor-ui/src/views/SettingsUsersView.vue
Labels: ui, n8n team

#5078 fix(Google Sheets Node): Fix for auto-range detection
  packages/nodes-base/nodes/Google/Sheet/v2/helpers/GoogleSheet.ts
  packages/nodes-base/nodes/Google/Sheet/v2/helpers/GoogleSheets.utils.ts
Labels: n8n team, node/issue

#5075 feat(editor): Introduce proxy completions to expressions
  packages/editor-ui/package.json
  packages/editor-ui/src/components/CodeNodeEditor/baseExtensions.ts
  packages/editor-ui/src/components/CodeNodeEditor/completer.ts
  packages/editor-ui/src/components/CodeNodeEditor/completions/jsonField.completions.ts
  packages/editor-ui/src/components/CodeNodeEditor/completions/luxon.completions.ts
  packages/editor-ui/src/components/CodeNodeEditor/inputHandler.ts
  packages/editor-ui/src/components/CodeNodeEditor/utils.ts
  packages/editor-ui/src/components/ExpressionEditorModal/ExpressionEditorModalInput.vue
  packages/editor-ui/src/components/InlineExpressionEditor/InlineExpressionEditorInput.vue
  packages/editor-ui/src/mixins/workflowHelpers.ts
  packages/editor-ui/src/plugins/codemirror/completions/__tests__/alpha.completions.test.ts
  packages/editor-ui/src/plugins/codemirror/completions/__tests__/luxon.completions.test.ts
  packages/editor-ui/src/plugins/codemirror/completions/__tests__/proxy.completions.test.ts
  packages/editor-ui/src/plugins/codemirror/completions/__tests__/proxyMocks.ts
  packages/editor-ui/src/plugins/codemirror/completions/__tests__/root.completions.test.ts
  packages/editor-ui/src/plugins/codemirror/completions/alpha.completions.ts
  packages/editor-ui/src/plugins/codemirror/completions/luxon.completions.ts
  packages/editor-ui/src/plugins/codemirror/completions/proxy.completions.ts
  packages/editor-ui/src/plugins/codemirror/completions/root.completions.ts
  packages/editor-ui/src/plugins/codemirror/completions/utils.ts
  packages/editor-ui/src/plugins/codemirror/inputHandlers/code.inputHandler.ts
  packages/editor-ui/src/plugins/codemirror/inputHandlers/expression.inputHandler.ts
  packages/editor-ui/src/plugins/codemirror/n8nLang.ts
  packages/editor-ui/src/plugins/codemirror/n8nLanguageSupport.ts
  packages/editor-ui/src/plugins/codemirror/resolvable.completions.ts
  packages/editor-ui/src/plugins/i18n/index.ts
  packages/editor-ui/src/types/completions.ts
  packages/workflow/src/Expression.ts
  packages/workflow/src/WorkflowDataProxy.ts
  pnpm-lock.yaml
Labels: core, ui, n8n team

#5095 fix: Stop OOM crashes in Execution Data pruning
  packages/cli/src/WorkflowExecuteAdditionalData.ts
Labels: core, n8n team

#5100 fix(Read Binary File Node): Do not crash the execution when the source file does not exist
  packages/core/src/NodeExecuteFunctions.ts
  packages/nodes-base/nodes/ReadBinaryFile/ReadBinaryFile.node.ts
  packages/nodes-base/nodes/ReadBinaryFiles/ReadBinaryFiles.node.ts
  packages/workflow/src/Interfaces.ts
  packages/workflow/src/NodeErrors.ts
Labels: node/improvement, core, n8n team

#5101 refactor(core): Add more overloads for string-type node parameters (no-changelog)
  packages/cli/BREAKING-CHANGES.md
  packages/nodes-base/nodes/Aws/Rekognition/AwsRekognition.node.ts
  packages/nodes-base/nodes/Aws/S3/AwsS3.node.ts
  packages/nodes-base/nodes/Aws/Textract/AwsTextract.node.ts
  packages/nodes-base/nodes/BambooHr/v1/actions/employeeDocument/upload/execute.ts
  packages/nodes-base/nodes/BambooHr/v1/actions/file/upload/execute.ts
  packages/nodes-base/nodes/Box/Box.node.ts
  packages/nodes-base/nodes/Cisco/Webex/CiscoWebex.node.ts
  packages/nodes-base/nodes/Compression/Compression.node.ts
  packages/nodes-base/nodes/Cortex/Cortex.node.ts
  packages/nodes-base/nodes/Crypto/Crypto.node.ts
  packages/nodes-base/nodes/DateTime/DateTime.node.ts
  packages/nodes-base/nodes/Dropbox/Dropbox.node.ts
  packages/nodes-base/nodes/EditImage/EditImage.node.ts
  packages/nodes-base/nodes/Facebook/FacebookGraphApi.node.ts
  packages/nodes-base/nodes/Ftp/Ftp.node.ts
  packages/nodes-base/nodes/Github/Github.node.ts
  packages/nodes-base/nodes/Google/Chat/GoogleChat.node.ts
  packages/nodes-base/nodes/Google/Drive/GoogleDrive.node.ts
  packages/nodes-base/nodes/GraphQL/GraphQL.node.ts
  packages/nodes-base/nodes/HomeAssistant/HomeAssistant.node.ts
  packages/nodes-base/nodes/HtmlExtract/HtmlExtract.node.ts
  packages/nodes-base/nodes/HttpRequest/V1/HttpRequestV1.node.ts
  packages/nodes-base/nodes/HttpRequest/V2/HttpRequestV2.node.ts
  packages/nodes-base/nodes/HumanticAI/HumanticAi.node.ts
  packages/nodes-base/nodes/ICalendar/ICalendar.node.ts
  packages/nodes-base/nodes/Jira/Jira.node.ts
  packages/nodes-base/nodes/Keap/Keap.node.ts
  packages/nodes-base/nodes/KoBoToolbox/KoBoToolbox.node.ts
  packages/nodes-base/nodes/LinkedIn/LinkedIn.node.ts
  packages/nodes-base/nodes/Matrix/GenericFunctions.ts
  packages/nodes-base/nodes/Microsoft/OneDrive/MicrosoftOneDrive.node.ts
  packages/nodes-base/nodes/Microsoft/Outlook/MicrosoftOutlook.node.ts
  packages/nodes-base/nodes/Mindee/Mindee.node.ts
  packages/nodes-base/nodes/Nasa/Nasa.node.ts
  packages/nodes-base/nodes/NextCloud/NextCloud.node.ts
  packages/nodes-base/nodes/Pipedrive/Pipedrive.node.ts
  packages/nodes-base/nodes/Pushbullet/Pushbullet.node.ts
  packages/nodes-base/nodes/QuickBase/QuickBase.node.ts
  packages/nodes-base/nodes/ReadBinaryFile/ReadBinaryFile.node.ts
  packages/nodes-base/nodes/ReadBinaryFiles/ReadBinaryFiles.node.ts
  packages/nodes-base/nodes/ReadPdf/ReadPDF.node.ts
  packages/nodes-base/nodes/S3/S3.node.ts
  packages/nodes-base/nodes/Salesforce/Salesforce.node.ts
  packages/nodes-base/nodes/SecurityScorecard/SecurityScorecard.node.ts
  packages/nodes-base/nodes/Slack/Slack.node.ts
  packages/nodes-base/nodes/SpreadsheetFile/SpreadsheetFile.node.ts
  packages/nodes-base/nodes/Ssh/Ssh.node.ts
  packages/nodes-base/nodes/Telegram/Telegram.node.ts
  packages/nodes-base/nodes/WriteBinaryFile/WriteBinaryFile.node.ts
  packages/nodes-base/nodes/Xml/Xml.node.ts
  packages/nodes-base/nodes/Zulip/Zulip.node.ts
  packages/workflow/src/Interfaces.ts
Labels: node/improvement, core, n8n team

#5099 fix: Remove anonymous ID from tracking calls
  packages/cli/src/telemetry/index.ts
Labels: core, n8n team

#5091 fix(editor): Prevent refresh on submit in credential edit modal
  packages/editor-ui/src/components/CredentialEdit/CredentialInputs.vue
Labels: ui, n8n team

#5108 test: Fix e2e tests for inline expression editor
  cypress/e2e/11-inline-expression-editor.cy.ts
Labels: n8n team

#5098 fix(editor): Omit `pairedItem` from proxy completions
  packages/editor-ui/src/plugins/codemirror/completions/__tests__/proxyMocks.ts
  packages/editor-ui/src/plugins/codemirror/completions/proxy.completions.ts
Labels: ui, n8n team

#5109 fix: Update links for user management and SMTP help
  packages/editor-ui/src/plugins/i18n/locales/en.json
Labels: Upcoming Release

#5106 fix: Do not attempt to save data for unsaved workflows
  packages/cli/src/events/WorkflowStatistics.ts
Labels: core, n8n team

#5097 feat: Add source to all View Plans links (no-changelog)
  packages/editor-ui/src/components/CredentialEdit/CredentialSharing.ee.vue
  packages/editor-ui/src/components/MainHeader/WorkflowDetails.vue
  packages/editor-ui/src/components/WorkflowShareModal.ee.vue
  packages/editor-ui/src/views/SettingsUsageAndPlan.vue
Labels: ui, n8n team, Upcoming Release

#5111 fix(editor): Disable data pinning on multiple output node types
  packages/editor-ui/src/constants.ts
  packages/editor-ui/src/mixins/pinData.ts
Labels: ui, n8n team

#5104 refactor: Reduce custom docker image size by about 30%
  docker/images/n8n-custom/Dockerfile
Labels: n8n team

#5113 test: Fix default owner test to be able to reach setup page
  cypress/pages/settings-users.ts
Labels: n8n team

#5102 refactor: On workflow deletion, cascade delete all entities associated with it
  packages/cli/src/PublicApi/v1/handlers/workflows/workflows.handler.ts
  packages/cli/src/databases/migrations/mysqldb/1673268682475-DeleteExecutionsWithWorkflows.ts
  packages/cli/src/databases/migrations/mysqldb/index.ts
  packages/cli/src/databases/migrations/postgresdb/1673268682475-DeleteExecutionsWithWorkflows.ts
  packages/cli/src/databases/migrations/postgresdb/index.ts
  packages/cli/src/databases/migrations/sqlite/1673268682475-DeleteExecutionsWithWorkflows.ts
  packages/cli/src/databases/migrations/sqlite/index.ts
  packages/cli/src/workflows/workflows.controller.ts
  packages/cli/src/workflows/workflows.services.ts
Labels: core, n8n team

#5114 feat(editor): Remove prevent-ndv-auto-open feature flag
  packages/editor-ui/src/views/NodeView.vue
Labels: ui, n8n team

#5117 refactor(TelegramTrigger Node, ShopifyTrigger Node): Standardize node triggers actions
  packages/editor-ui/src/stores/nodeCreator.ts
  packages/nodes-base/nodes/Shopify/ShopifyTrigger.node.ts
  packages/nodes-base/nodes/Telegram/TelegramTrigger.node.ts
Labels: node/improvement, ui, n8n team

#5119 fix(editor): Fixes event bus test
  cypress/e2e/10-settings-log-streaming.cy.ts
Labels: n8n team

#4372 feat: Expression extension framework
  .vscode/launch.json
  packages/editor-ui/tsconfig.json
  packages/editor-ui/vite.config.ts
  packages/workflow/package.json
  packages/workflow/src/Expression.ts
  packages/workflow/src/ExpressionError.ts
  packages/workflow/src/Extensions/ArrayExtensions.ts
  packages/workflow/src/Extensions/DateExtensions.ts
  packages/workflow/src/Extensions/ExpressionExtension.ts
  packages/workflow/src/Extensions/ExpressionParser.ts
  packages/workflow/src/Extensions/ExtendedFunctions.ts
  packages/workflow/src/Extensions/Extensions.ts
  packages/workflow/src/Extensions/NumberExtensions.ts
  packages/workflow/src/Extensions/ObjectExtensions.ts
  packages/workflow/src/Extensions/StringExtensions.ts
  packages/workflow/src/Extensions/index.ts
  packages/workflow/test/ExpressionExtensions/ArrayExtensions.test.ts
  packages/workflow/test/ExpressionExtensions/DateExtensions.test.ts
  packages/workflow/test/ExpressionExtensions/ExpressionExtension.test.ts
  packages/workflow/test/ExpressionExtensions/GenericExtensions.test.ts
  packages/workflow/test/ExpressionExtensions/Helpers.ts
  packages/workflow/test/ExpressionExtensions/NumberExtensions.test.ts
  packages/workflow/test/ExpressionExtensions/ObjectExtensions.test.ts
  packages/workflow/test/ExpressionExtensions/StringExtensions.test.ts
  pnpm-lock.yaml
Labels: core, n8n team

#5120 docs: Update the contribution guidelines for node creation
  CONTRIBUTING.md
Labels: n8n team

#5121 fix(editor): Recover from unsaved finished execution
  packages/editor-ui/src/Interface.ts
  packages/editor-ui/src/plugins/i18n/locales/en.json
  packages/editor-ui/src/stores/workflows.ts
  packages/editor-ui/src/views/NodeView.vue
Labels: ui, n8n team

#5124 refactor(core): Diverge syntax error handling in expressions
  packages/workflow/src/Expression.ts
Labels: core, n8n team

#5118 fix(core): Fixes event msg confirmations if no subscribers present
  .vscode/launch.json
  packages/cli/src/eventbus/EventMessageClasses/Helpers.ts
  packages/cli/src/eventbus/MessageEventBus/MessageEventBus.ts
  packages/cli/src/eventbus/MessageEventBusWriter/MessageEventBusLogWriter.ts
  packages/cli/src/eventbus/eventBusRoutes.ts
  packages/cli/test/integration/eventbus.test.ts
  packages/editor-ui/src/Interface.ts
  packages/editor-ui/src/mixins/restApi.ts
  packages/editor-ui/src/plugins/i18n/locales/en.json
  packages/workflow/src/MessageEventBus.ts
Labels: core, ui, n8n team

#5089 refactor(editor): Overhaul workflow level executions list
  packages/editor-ui/src/components/ExecutionsList.vue
  packages/editor-ui/src/components/ExecutionsView/ExecutionCard.vue
  packages/editor-ui/src/components/ExecutionsView/ExecutionsInfoAccordion.vue
  packages/editor-ui/src/components/ExecutionsView/ExecutionsLandingPage.vue
  packages/editor-ui/src/components/ExecutionsView/ExecutionsList.vue
  packages/editor-ui/src/components/ExecutionsView/ExecutionsSidebar.vue
  packages/editor-ui/src/components/MainHeader/MainHeader.vue
  packages/editor-ui/src/mixins/executionsHelpers.ts
  packages/editor-ui/src/mixins/genericHelpers.ts
  packages/editor-ui/src/plugins/i18n/locales/en.json
Labels: ui, n8n team

#5125 feat(editor): Load workflow sharedWith info only when opening share modal
  packages/editor-ui/src/api/workflows.ts
  packages/editor-ui/src/components/WorkflowShareModal.ee.vue
  packages/editor-ui/src/stores/workflows.ts
Labels: ui, n8n team

#5127 fix: Report app startup and DB migration errors to Sentry
  packages/cli/src/commands/start.ts
  packages/cli/src/commands/webhook.ts
  packages/cli/src/commands/worker.ts
  packages/workflow/src/ErrorReporterProxy.ts
Labels: core, n8n team

#5129 fix: Run every DB migration inside a transaction
  packages/cli/src/Db.ts
  packages/cli/src/databases/migrations/sqlite/1621707690587-AddWaitColumn.ts
  packages/cli/src/databases/migrations/sqlite/1652367743993-AddUserSettings.ts
  packages/cli/src/databases/migrations/sqlite/1652905585850-AddAPIKeyColumn.ts
  packages/cli/src/databases/migrations/sqlite/1673268682475-DeleteExecutionsWithWorkflows.ts
Labels: core, n8n team

#5131 fix: DB revert command shouldn't run full migrations before each revert
  packages/cli/src/Db.ts
  packages/cli/src/commands/db/revert.ts
Labels: core, n8n team

#5135 fix(editor): Do not overwrite window.onerror in production
  packages/editor-ui/src/main.ts
Labels: ui, n8n team

#5132 ci: Disable CI jobs on nodejs 14.x (no-changelog)
  .github/workflows/ci-master.yml
  .github/workflows/ci-pull-requests.yml
  .github/workflows/e2e-tests.yml
Labels: n8n team

#5139 fix: Upgrade `class-validator` to address CVE-2019-18413
  packages/cli/package.json
  pnpm-lock.yaml
Labels: core, n8n team

#5140 fix: First/last being extended on proxy objects
  packages/workflow/src/Extensions/ExpressionExtension.ts
Labels: core, n8n team

#5142 fix: Test failing for toDate from string extension test (no-changelog)
  packages/workflow/test/ExpressionExtensions/DateExtensions.test.ts
  packages/workflow/test/ExpressionExtensions/Helpers.ts
Labels: core, n8n team

#5141 feat: Add demo experiment to help users activate
  packages/design-system/src/components/N8nCallout/Callout.vue
  packages/design-system/src/components/N8nCallout/__tests__/__snapshots__/Callout.spec.ts.snap
  packages/design-system/src/components/N8nLink/Link.vue
  packages/editor-ui/public/static/quickstart_thumbnail.png
  packages/editor-ui/src/App.vue
  packages/editor-ui/src/components/MainSidebar.vue
  packages/editor-ui/src/components/layouts/ResourcesListLayout.vue
  packages/editor-ui/src/constants.ts
  packages/editor-ui/src/plugins/i18n/locales/en.json
  packages/editor-ui/src/utils/nodeViewUtils.ts
  packages/editor-ui/src/views/NodeView.vue
  packages/editor-ui/src/views/WorkflowsView.vue
Labels: ui, n8n team

#5126 feat(editor): Update callout component design
  packages/design-system/src/components/N8nCallout/Callout.stories.ts
  packages/design-system/src/components/N8nCallout/Callout.vue
  packages/design-system/src/components/N8nCallout/__tests__/__snapshots__/Callout.spec.ts.snap
Labels: ui, n8n team

#5147 fix: Handle memory issues gracefully
  packages/editor-ui/src/mixins/pushConnection.ts
  packages/editor-ui/src/plugins/i18n/locales/en.json
Labels: ui, n8n team

#5122 fix(editor): Execution page bug fixes
  packages/editor-ui/src/components/ExecutionsList.vue
  packages/editor-ui/src/components/ExecutionsView/ExecutionCard.vue
  packages/editor-ui/src/plugins/i18n/locales/en.json
Labels: ui, n8n team

#5145 fix(editor): Hide data pinning discoverability tooltip in execution view
  packages/editor-ui/src/components/OutputPanel.vue
  packages/editor-ui/src/components/RunData.vue
Labels: ui, n8n team

#5134 fix(core): Remove threads pkg, rewrite log writer worker
  packages/cli/package.json
  packages/cli/src/config/schema.ts
  packages/cli/src/eventbus/EventMessageClasses/AbstractEventMessage.ts
  packages/cli/src/eventbus/EventMessageClasses/EventMessageAudit.ts
  packages/cli/src/eventbus/MessageEventBus/MessageEventBus.ts
  packages/cli/src/eventbus/MessageEventBusDestination/Helpers.ee.ts
  packages/cli/src/eventbus/MessageEventBusDestination/MessageEventBusDestination.ee.ts
  packages/cli/src/eventbus/MessageEventBusDestination/MessageEventBusDestinationSentry.ee.ts
  packages/cli/src/eventbus/MessageEventBusDestination/MessageEventBusDestinationSyslog.ee.ts
  packages/cli/src/eventbus/MessageEventBusDestination/MessageEventBusDestinationWebhook.ee.ts
  packages/cli/src/eventbus/MessageEventBusWriter/MessageEventBusLogWriter.ts
  packages/cli/src/eventbus/MessageEventBusWriter/MessageEventBusLogWriterWorker.ts
  packages/cli/src/eventbus/eventBusRoutes.ts
  packages/cli/test/integration/eventbus.test.ts
  pnpm-lock.yaml
Labels: core, n8n team

#5156 fix(Zoom Node): Add notice about deprecation of Zoom JWT app support
  packages/nodes-base/credentials/ZoomApi.credentials.ts
Labels: node/improvement, n8n team

#5150 fix(PayPal Trigger Node): Omit verification on sandbox env
  packages/nodes-base/nodes/PayPal/PayPalTrigger.node.ts
Labels: node/improvement, n8n team

#5116 fix: Upgrade `jsonwebtoken` to address CVE-2022-23540
  package.json
  packages/cli/package.json
  packages/cli/src/UserManagement/auth/jwt.ts
  packages/nodes-base/package.json
  pnpm-lock.yaml
Labels: core, n8n team

#4651 refactor(editor): Remove old execution view route and its dependants
  packages/editor-ui/src/components/MainHeader/ExecutionDetails/ExecutionDetails.vue
  packages/editor-ui/src/components/MainHeader/ExecutionDetails/ReadOnly.vue
  packages/editor-ui/src/components/MainHeader/MainHeader.vue
  packages/editor-ui/src/constants.ts
  packages/editor-ui/src/router.ts
  packages/editor-ui/src/stores/ui.ts
  packages/editor-ui/src/utils/canvasUtils.ts
  packages/editor-ui/src/views/NodeView.vue
Labels: ui, n8n team

#5148 feat(Google Drive Trigger Node): Use resource locator component
  packages/nodes-base/nodes/Google/Drive/GoogleDrive.node.ts
  packages/nodes-base/nodes/Google/Drive/GoogleDriveTrigger.node.ts
  packages/nodes-base/nodes/Google/Drive/SearchFunctions.ts
Labels: node/improvement, n8n team

#5171 fix: Add `cli` to fix Postgres and MySQL test runs
  .github/workflows/ci-postgres-mysql.yml
Labels: n8n team

#5170 fix: Extend date functions clobbering plus/minus
  packages/workflow/src/Extensions/DateExtensions.ts
Labels: core, n8n team

#5149 feat(editor): Supress validation errors for freshly added nodes
  cypress/e2e/5-ndv.cy.ts
  cypress/fixtures/Test_workflow_ndv_errors.json
  cypress/pages/workflow.ts
  packages/editor-ui/src/Interface.ts
  packages/editor-ui/src/components/NodeCredentials.vue
  packages/editor-ui/src/components/NodeSettings.vue
  packages/editor-ui/src/components/ParameterInputFull.vue
  packages/editor-ui/src/components/ParameterInputList.vue
  packages/editor-ui/src/components/ResourceLocator/ResourceLocator.vue
  packages/editor-ui/src/stores/workflows.ts
  packages/editor-ui/src/views/NodeView.vue
Labels: ui, n8n team

#5172 fix: Extension deep compare not quite working for some primitives
  packages/workflow/src/Extensions/ArrayExtensions.ts
Labels: core, n8n team

#5176 test: Add e2e tests for PRs
  .github/workflows/e2e-tests-pr.yml
Labels: n8n team

#4621 feat: (Google Sheets Trigger Node): Trigger for Google Sheets
  packages/nodes-base/credentials/GoogleSheetsTriggerOAuth2Api.credentials.ts
  packages/nodes-base/nodes/Google/Sheet/GoogleSheetsTrigger.node.json
  packages/nodes-base/nodes/Google/Sheet/GoogleSheetsTrigger.node.ts
  packages/nodes-base/nodes/Google/Sheet/GoogleSheetsTrigger.utils.ts
  packages/nodes-base/nodes/Google/Sheet/v2/actions/sheet/Sheet.resource.ts
  packages/nodes-base/nodes/Google/Sheet/v2/helpers/GoogleSheet.ts
  packages/nodes-base/nodes/Google/Sheet/v2/methods/listSearch.ts
  packages/nodes-base/nodes/Google/Sheet/v2/transport/index.ts
  packages/nodes-base/package.json
Labels: node/improvement, node/new, n8n team, Upcoming Release

#5180 fix(core): Restore community nodes installation
  packages/cli/src/CommunityNodes/packageModel.ts
Labels: core, n8n team

#4574 feat(Item Lists Node): Table tranformation
  packages/nodes-base/nodes/ItemLists/ItemLists.node.json
  packages/nodes-base/nodes/ItemLists/ItemLists.node.ts
  packages/nodes-base/nodes/ItemLists/summarize.operation.ts
Labels: node/improvement, n8n team, Upcoming Release

#5173 fix(Gmail Trigger Node): Filter by labels not working
  packages/nodes-base/nodes/Google/Gmail/GmailTrigger.node.ts
Labels: node/improvement, n8n team

#5189 fix(HTTP Request Node): Response format to text is ignored for JSON responses
  packages/nodes-base/nodes/HttpRequest/V3/HttpRequestV3.node.ts
Labels: n8n team, node/issue

#5157 test: Add tests for pinning data
  cypress/e2e/10-undo-redo.cy.ts
  cypress/e2e/11-inline-expression-editor.cy.ts
  cypress/e2e/13-pinning.cy.ts
  cypress/e2e/5-ndv.cy.ts
  cypress/e2e/6-code-node.cy.ts
  cypress/e2e/8-http-request-node.cy.ts
  cypress/e2e/9-expression-editor-modal.cy.ts
  cypress/pages/ndv.ts
  cypress/pages/workflow.ts
  packages/editor-ui/src/components/NodeExecuteButton.vue
  packages/editor-ui/src/components/NodeSettings.vue
  packages/editor-ui/src/components/OutputPanel.vue
  packages/editor-ui/src/components/RunData.vue
Labels: ui, n8n team

#5196 fix(editor): Allow special chars in node selector completion
  packages/editor-ui/src/components/CodeNodeEditor/completions/itemIndex.completions.ts
Labels: ui, n8n team

#5166 fix(GitLab Node): Update credential test endpoint
  packages/nodes-base/credentials/GitlabApi.credentials.ts
Labels: node/improvement, community

#5190 fix(HTTP Request Node): Bug - node requires string instead of json
  packages/nodes-base/nodes/HttpRequest/V3/HttpRequestV3.node.ts
Labels: n8n team, node/issue

#5165 docs: Update the contribution guidelines (no-changelog)
  CONTRIBUTING.md
Labels: community

#5187 feat(core): Add more Prometheus metrics (experimental)
  packages/cli/package.json
  packages/cli/src/Server.ts
  packages/cli/src/config/schema.ts
  packages/cli/src/eventbus/MessageEventBus/MessageEventBus.ts
  packages/cli/src/eventbus/MessageEventBusDestination/Helpers.ee.ts
  packages/cli/src/metrics/index.ts
  pnpm-lock.yaml
Labels: core, n8n team

#5177 feat(core): Add Prometheus metrics for n8n events and api invocations (experimental)
  packages/cli/package.json
  packages/cli/src/InternalHooks.ts
  packages/cli/src/Server.ts
  packages/cli/src/config/schema.ts
  packages/cli/src/eventbus/EventMessageClasses/EventMessageAudit.ts
  packages/cli/src/eventbus/EventMessageClasses/EventMessageNode.ts
  packages/cli/src/eventbus/MessageEventBus/MessageEventBus.ts
  packages/cli/src/eventbus/MessageEventBusDestination/Helpers.ee.ts
  packages/cli/src/eventbus/eventBusRoutes.ts
  packages/cli/src/metrics/index.ts
  pnpm-lock.yaml
Labels: core, n8n team

#5201 fix(core): Fix url in error handelling for the error Trigger
  packages/cli/src/WorkflowExecuteAdditionalData.ts
  packages/nodes-base/nodes/ErrorTrigger/ErrorTrigger.node.ts
Labels: node/improvement, core, n8n team

#5182 fix(Notion (Beta) Node): Fix create database page fails if relation param is empty/undefined
  packages/nodes-base/nodes/Notion/GenericFunctions.ts
  packages/nodes-base/nodes/Notion/v1/NotionV1.node.ts
  packages/nodes-base/nodes/Notion/v2/NotionV2.node.ts
Labels: node/improvement, n8n team

#5206 test: Skip some syslog tests (no-changelog)
  packages/cli/test/integration/eventbus.test.ts
Labels: core, n8n team

#5202 refactor(editor): Decouple REST calls from views (no-changelog)
  packages/editor-ui/src/api/eventbus.ee.ts
  packages/editor-ui/src/components/SettingsLogStreaming/EventDestinationCard.ee.vue
  packages/editor-ui/src/components/SettingsLogStreaming/EventDestinationSettingsModal.ee.vue
  packages/editor-ui/src/components/SettingsLogStreaming/Helpers.ee.ts
  packages/editor-ui/src/stores/logStreamingStore.ts
  packages/editor-ui/src/views/SettingsLogStreamingView.vue
Labels: ui, n8n team

#4838 refactor: Update Notion nodes to remove beta from name
  packages/nodes-base/nodes/Notion/DatabaseDescription.ts
  packages/nodes-base/nodes/Notion/Notion.node.ts
  packages/nodes-base/nodes/Notion/NotionTrigger.node.ts
  packages/nodes-base/nodes/Notion/v1/VersionDescription.ts
  packages/nodes-base/nodes/Notion/v2/VersionDescription.ts
Labels: node/improvement, n8n team

#5193 fix(Linear Node): Fix issue with single item not being returned
  packages/nodes-base/credentials/LinearApi.credentials.ts
  packages/nodes-base/nodes/Linear/GenericFunctions.ts
  packages/nodes-base/nodes/Linear/Linear.node.ts
  packages/nodes-base/nodes/Linear/Queries.ts
Labels: node/improvement, n8n team

#3862 feat(Google Analytics Node): Overhaul for google analytics node
  packages/nodes-base/nodes/Google/Analytics/GoogleAnalytics.node.ts
  packages/nodes-base/nodes/Google/Analytics/v1/GenericFunctions.ts
  packages/nodes-base/nodes/Google/Analytics/v1/GoogleAnalyticsV1.node.ts
  packages/nodes-base/nodes/Google/Analytics/v1/Interfaces.ts
  packages/nodes-base/nodes/Google/Analytics/v1/ReportDescription.ts
  packages/nodes-base/nodes/Google/Analytics/v1/UserActivityDescription.ts
  packages/nodes-base/nodes/Google/Analytics/v2/GoogleAnalyticsV2.node.ts
  packages/nodes-base/nodes/Google/Analytics/v2/actions/node.type.ts
  packages/nodes-base/nodes/Google/Analytics/v2/actions/report/FiltersDescription.ts
  packages/nodes-base/nodes/Google/Analytics/v2/actions/report/Report.resource.ts
  packages/nodes-base/nodes/Google/Analytics/v2/actions/report/get.ga4.operation.ts
  packages/nodes-base/nodes/Google/Analytics/v2/actions/report/get.universal.operation.ts
  packages/nodes-base/nodes/Google/Analytics/v2/actions/router.ts
  packages/nodes-base/nodes/Google/Analytics/v2/actions/userActivity/UserActivity.resource.ts
  packages/nodes-base/nodes/Google/Analytics/v2/actions/userActivity/search.operation.ts
  packages/nodes-base/nodes/Google/Analytics/v2/actions/versionDescription.ts
  packages/nodes-base/nodes/Google/Analytics/v2/helpers/Interfaces.ts
  packages/nodes-base/nodes/Google/Analytics/v2/helpers/utils.ts
  packages/nodes-base/nodes/Google/Analytics/v2/methods/index.ts
  packages/nodes-base/nodes/Google/Analytics/v2/methods/listSearch.ts
  packages/nodes-base/nodes/Google/Analytics/v2/methods/loadOptions.ts
  packages/nodes-base/nodes/Google/Analytics/v2/transport/index.ts
Labels: node/improvement, n8n team

#5195 fix(editor): Making parameter input components label configurable
  packages/editor-ui/src/components/CredentialEdit/CredentialInputs.vue
  packages/editor-ui/src/components/ParameterInputExpanded.vue
  packages/editor-ui/src/components/ParameterInputFull.vue
  packages/workflow/src/Interfaces.ts
Labels: core, ui, n8n team

#5218 fix: Add schema to postgres migrations
  packages/cli/src/databases/migrations/mysqldb/1673268682475-DeleteExecutionsWithWorkflows.ts
  packages/cli/src/databases/migrations/postgresdb/1673268682475-DeleteExecutionsWithWorkflows.ts
  packages/cli/src/databases/migrations/sqlite/1673268682475-DeleteExecutionsWithWorkflows.ts
Labels: core, n8n team

#5219 fix(core): Fix expression extension misdetection
  packages/workflow/src/Expression.ts
  packages/workflow/src/Extensions/ExpressionExtension.ts
Labels: core, n8n team

#5223 fix(core): Make pindata with webhook responding on last node manual-only
  packages/cli/src/WorkflowHelpers.ts
Labels: core, n8n team

#5211 fix(core): Fix execute-once incoming data handling
  packages/workflow/src/Workflow.ts
  packages/workflow/src/WorkflowDataProxy.ts
Labels: core, n8n team

#5221 fix: IsWeekend not checking if DateTime
  packages/workflow/src/Extensions/DateExtensions.ts
  packages/workflow/test/ExpressionExtensions/DateExtensions.test.ts
  packages/workflow/test/ExpressionExtensions/Helpers.ts
Labels: core, n8n team

#5174 fix(editor): Remove infinite loading in not found workflow level execution
  packages/editor-ui/src/components/ExecutionsView/ExecutionsList.vue
Labels: ui, n8n team

#5227 ci: Fix typing issues in cli tests (no-changelog)
  packages/cli/test/integration/audit/instance.risk.test.ts
  packages/cli/test/integration/audit/nodes.risk.test.ts
  packages/cli/test/integration/eventbus.test.ts
Labels: core, n8n team

#5233 refactor(core): Add support for implicit schema in postgres migrations
  packages/cli/src/Db.ts
  packages/cli/src/commands/start.ts
  packages/cli/src/databases/config.ts
  packages/cli/src/databases/migrations/postgresdb/1587669153312-InitialMigration.ts
  packages/cli/src/databases/migrations/postgresdb/1589476000887-WebhookModel.ts
  packages/cli/src/databases/migrations/postgresdb/1594828256133-CreateIndexStoppedAt.ts
  packages/cli/src/databases/migrations/postgresdb/1607431743768-MakeStoppedAtNullable.ts
  packages/cli/src/databases/migrations/postgresdb/1611144599516-AddWebhookId.ts
  packages/cli/src/databases/migrations/postgresdb/1617270242566-CreateTagEntity.ts
  packages/cli/src/databases/migrations/postgresdb/1620824779533-UniqueWorkflowNames.ts
  packages/cli/src/databases/migrations/postgresdb/1626176912946-AddwaitTill.ts
  packages/cli/src/databases/migrations/postgresdb/1630419189837-UpdateWorkflowCredentials.ts
  packages/cli/src/databases/migrations/postgresdb/1644422880309-AddExecutionEntityIndexes.ts
  packages/cli/src/databases/migrations/postgresdb/1646834195327-IncreaseTypeVarcharLimit.ts
  packages/cli/src/databases/migrations/postgresdb/1646992772331-CreateUserManagement.ts
  packages/cli/src/databases/migrations/postgresdb/1648740597343-LowerCaseUserEmail.ts
  packages/cli/src/databases/migrations/postgresdb/1652254514002-CommunityNodes.ts
  packages/cli/src/databases/migrations/postgresdb/1652367743993-AddUserSettings.ts
  packages/cli/src/databases/migrations/postgresdb/1652905585850-AddAPIKeyColumn.ts
  packages/cli/src/databases/migrations/postgresdb/1654090467022-IntroducePinData.ts
  packages/cli/src/databases/migrations/postgresdb/1658932090381-AddNodeIds.ts
  packages/cli/src/databases/migrations/postgresdb/1660062385367-CreateCredentialsUserRole.ts
  packages/cli/src/databases/migrations/postgresdb/1664196174001-WorkflowStatistics.ts
  packages/cli/src/databases/migrations/postgresdb/1669739707126-AddWorkflowVersionIdColumn.ts
  packages/cli/src/databases/migrations/postgresdb/1669823906995-AddTriggerCountColumn.ts
  packages/cli/src/databases/migrations/postgresdb/1671726148421-RemoveWorkflowDataLoadedFlag.ts
  packages/cli/src/databases/utils/migrationHelpers.ts
  packages/cli/test/integration/shared/testDb.ts
Labels: core, n8n team, skip-e2e

#5207 feat(Send Email Node): Overhaul
  packages/nodes-base/nodes/EmailSend/EmailSend.node.json
  packages/nodes-base/nodes/EmailSend/EmailSend.node.ts
  packages/nodes-base/nodes/EmailSend/v1/EmailSendV1.node.ts
  packages/nodes-base/nodes/EmailSend/v2/EmailSendV2.node.ts
  packages/nodes-base/nodes/EmailSend/v2/send.operation.ts
  packages/nodes-base/nodes/Microsoft/Sql/MicrosoftSql.node.ts
  packages/nodes-base/utils/allCurrencies.ts
  packages/nodes-base/utils/utilities.ts
Labels: node/improvement, n8n team, Upcoming Release

#5232 fix: Extension being too eager and making calls when it shouldn't
  packages/workflow/src/Extensions/ExpressionExtension.ts
  packages/workflow/test/ExpressionExtensions/ExpressionExtension.test.ts
Labels: core, n8n team

#5230 fix(editor): Prevent workflow execution list infinite no network error
  packages/editor-ui/src/components/ExecutionsView/ExecutionsList.vue
  packages/editor-ui/src/utils/apiUtils.ts
Labels: ui, n8n team

#5240 fix(Google Drive Node): Use the correct mimetype on converted downloads
  packages/nodes-base/nodes/Google/Drive/GoogleDrive.node.ts
Labels: node/improvement, n8n team, skip-e2e

#5213 ci: Publish n8n docker images to GHCR
  .github/workflows/docker-images.yml
Labels: community, skip-e2e

#5090 feat(Jira Software Node): Use resource locator component
  packages/nodes-base/nodes/Jira/GenericFunctions.ts
  packages/nodes-base/nodes/Jira/IssueDescription.ts
  packages/nodes-base/nodes/Jira/Jira.node.ts
  packages/nodes-base/nodes/Jira/JiraTrigger.node.ts
Labels: node/improvement, n8n team

#5231 fix(core): Upsert credentials and workflows in the import:* commands
  packages/cli/src/commands/import/credentials.ts
  packages/cli/src/commands/import/workflow.ts
  packages/cli/src/databases/utils/commandHelpers.ts
Labels: core, n8n team, skip-e2e

#5243 ci: Simplify DB truncate in tests (no-changelog)
  packages/cli/test/integration/me.api.test.ts
  packages/cli/test/integration/shared/constants.ts
  packages/cli/test/integration/shared/testDb.ts
  packages/cli/test/integration/shared/types.d.ts
  packages/cli/test/integration/shared/utils.ts
  packages/cli/test/unit/PermissionChecker.test.ts
Labels: core, n8n team, skip-e2e

#5242 fix(core): Handle missing binary metadata in download urls
  packages/cli/src/Server.ts
  packages/cli/src/requests.d.ts
  packages/editor-ui/src/Interface.ts
  packages/editor-ui/src/components/BinaryDataDisplayEmbed.vue
  packages/editor-ui/src/components/RunData.vue
  packages/editor-ui/src/mixins/restApi.ts
Labels: core, ui, n8n team

#5245 fix(editor): Fix the element-ui imports in SettingsLdapView (no-changelog)
  packages/editor-ui/src/views/SettingsLdapView.vue
Labels: skip-e2e

#5246 fix(editor): Do not request workflow data twice when opening a workflow
  packages/editor-ui/src/views/NodeView.vue
Labels: ui, n8n team

#5239 fix(HelpScout Node): Fix tag search not working when getting all conversations
  packages/nodes-base/nodes/HelpScout/ConversationInterface.ts
  packages/nodes-base/nodes/HelpScout/HelpScout.node.ts
Labels: node/improvement, n8n team

#5247 fix(editor): Fix save modal appearing post duplication of a workflow
  packages/editor-ui/src/mixins/workflowHelpers.ts
Labels: ui, n8n team

#5244 fix(editor): Execution list micro optimization
  packages/editor-ui/src/components/ExecutionsList.vue
  packages/editor-ui/src/components/ExecutionsView/ExecutionsList.vue
Labels: ui, n8n team

#5107 feat: HTML node
  packages/editor-ui/package.json
  packages/editor-ui/src/Interface.ts
  packages/editor-ui/src/components/HtmlEditor/HtmlEditor.vue
  packages/editor-ui/src/components/HtmlEditor/theme.ts
  packages/editor-ui/src/components/HtmlEditor/types.ts
  packages/editor-ui/src/components/HtmlEditor/utils.ts
  packages/editor-ui/src/components/ParameterInput.vue
  packages/editor-ui/src/components/ParameterOptions.vue
  packages/editor-ui/src/components/RunData.vue
  packages/editor-ui/src/components/RunDataHtml.vue
  packages/editor-ui/src/constants.ts
  packages/editor-ui/src/event-bus/html-editor-event-bus.ts
  packages/editor-ui/src/mixins/expressionManager.ts
  packages/editor-ui/src/plugins/codemirror/inputHandlers/expression.inputHandler.ts
  packages/editor-ui/src/types/expressions.ts
  packages/nodes-base/nodes/Html/Html.node.json
  packages/nodes-base/nodes/Html/Html.node.ts
  packages/nodes-base/nodes/Html/html.svg
  packages/nodes-base/nodes/Html/placeholder.ts
  packages/nodes-base/nodes/Html/types.ts
  packages/nodes-base/nodes/Html/utils.ts
  packages/nodes-base/nodes/HtmlExtract/HtmlExtract.node.ts
  packages/nodes-base/package.json
  packages/workflow/src/Interfaces.ts
  pnpm-lock.yaml
Labels: node/new, core, ui, n8n team

#5250 ci: Fix CI timeout issues (no-changelog)
  packages/cli/src/PublicApi/index.ts
  packages/cli/src/config/index.ts
  packages/cli/test/integration/publicApi/credentials.test.ts
  packages/cli/test/integration/publicApi/executions.test.ts
  packages/cli/test/integration/publicApi/workflows.test.ts
  packages/cli/test/integration/shared/testDb.ts
  packages/cli/test/integration/shared/utils.ts
Labels: core, n8n team, skip-e2e

#5251 fix(core): Validate numeric ids in the public API
  packages/cli/src/PublicApi/v1/handlers/credentials/spec/paths/credentials.id.yml
  packages/cli/src/PublicApi/v1/handlers/credentials/spec/schemas/credential.yml
  packages/cli/src/PublicApi/v1/handlers/executions/spec/schemas/execution.yml
  packages/cli/src/PublicApi/v1/handlers/executions/spec/schemas/parameters/executionId.yml
  packages/cli/src/PublicApi/v1/handlers/workflows/spec/schemas/parameters/workflowId.yml
  packages/cli/src/PublicApi/v1/handlers/workflows/spec/schemas/tag.yml
  packages/cli/src/PublicApi/v1/handlers/workflows/spec/schemas/workflow.yml
  packages/cli/src/PublicApi/v1/handlers/workflows/spec/schemas/workflowSettings.yml
Labels: core, n8n team, skip-e2e

#5252 fix(core): Do not crash express app on unhandled rejected promises
  packages/cli/bin/n8n
  packages/cli/package.json
  pnpm-lock.yaml
Labels: core, n8n team, skip-e2e

#5188 feat(editor): Update design-system and editor dependencies (no-changelog)
  packages/cli/src/commands/start.ts
  packages/design-system/package.json
  packages/design-system/src/components/N8nActionBox/__tests__/__snapshots__/ActionBox.spec.ts.snap
  packages/design-system/src/components/N8nActionDropdown/__tests__/__snapshots__/ActionDropdown.spec.ts.snap
  packages/design-system/src/components/N8nBadge/__tests__/__snapshots__/Badge.spec.ts.snap
  packages/design-system/src/components/N8nButton/__tests__/__snapshots__/Button.spec.ts.snap
  packages/design-system/src/components/N8nCallout/__tests__/__snapshots__/Callout.spec.ts.snap
  packages/design-system/src/components/N8nCard/__tests__/__snapshots__/Card.spec.ts.snap
  packages/design-system/src/components/N8nInfoTip/__tests__/__snapshots__/InfoTip.spec.ts.snap
  packages/design-system/src/components/N8nNotice/__tests__/__snapshots__/Notice.spec.ts.snap
  packages/design-system/src/components/N8nSelect/__tests__/__snapshots__/Select.spec.ts.snap
  packages/design-system/src/components/N8nTree/__tests__/__snapshots__/Tree.spec.ts.snap
  packages/design-system/vite.config.ts
  packages/editor-ui/package.json
  packages/editor-ui/src/components/__snapshots__/RunDataSchema.test.ts.snap
  packages/editor-ui/src/shims.d.ts
  packages/editor-ui/src/stores/n8nRootStore.ts
  packages/editor-ui/vite.config.ts
  packages/editor-ui/vue.config.js
  pnpm-lock.yaml
Labels: ui, n8n team

#5260 fix(Notion (Beta) Node): Fix create database page with multiple relation ids not working
  packages/nodes-base/nodes/Notion/GenericFunctions.ts
Labels: node/improvement, n8n team

#5181 feat: Improve workflow list performance using RecycleScroller and on-demand sharing data loading
  cypress/e2e/8-http-request-node.cy.ts
  packages/design-system/src/components/N8nRecycleScroller/RecycleScroller.stories.ts
  packages/design-system/src/components/N8nRecycleScroller/RecycleScroller.vue
  packages/design-system/src/components/N8nRecycleScroller/index.ts
  packages/design-system/src/components/N8nTags/Tags.vue
  packages/design-system/src/plugins/n8nComponents.ts
  packages/editor-ui/src/api/workflows.ts
  packages/editor-ui/src/components/WorkflowCard.vue
  packages/editor-ui/src/components/WorkflowShareModal.ee.vue
  packages/editor-ui/src/components/layouts/PageViewLayoutList.vue
  packages/editor-ui/src/components/layouts/ResourcesListLayout.vue
  packages/editor-ui/src/plugins/components.ts
  packages/editor-ui/src/stores/workflows.ts
  packages/editor-ui/src/views/CredentialsView.vue
  packages/editor-ui/src/views/WorkflowsView.vue
Labels: ui, n8n team

#5067 feat(editor): Simplify NDV by moving authentication details to credentials modal
  cypress/constants.ts
  cypress/e2e/2-credentials.cy.ts
  cypress/pages/modals/credentials-modal.ts
  cypress/pages/workflow.ts
  packages/editor-ui/src/Interface.ts
  packages/editor-ui/src/components/CredentialEdit/AuthTypeSelector.vue
  packages/editor-ui/src/components/CredentialEdit/CredentialConfig.vue
  packages/editor-ui/src/components/CredentialEdit/CredentialEdit.vue
  packages/editor-ui/src/components/Node/NodeCreator/TriggerHelperPanel.vue
  packages/editor-ui/src/components/NodeCredentials.vue
  packages/editor-ui/src/components/NodeSettings.vue
  packages/editor-ui/src/components/ParameterInputList.vue
  packages/editor-ui/src/components/ParameterInputWrapper.vue
  packages/editor-ui/src/components/ParameterOptions.vue
  packages/editor-ui/src/constants.ts
  packages/editor-ui/src/mixins/nodeHelpers.ts
  packages/editor-ui/src/plugins/i18n/locales/en.json
  packages/editor-ui/src/stores/credentials.ts
  packages/editor-ui/src/stores/ui.ts
  packages/editor-ui/src/utils/nodeTypesUtils.ts
  packages/editor-ui/src/utils/typeGuards.ts
Labels: ui, n8n team

#5264 fix: Fix formatting/linting for CI (no-changelog)
  .github/workflows/docker-images.yml
  .vscode/launch.json
  .vscode/settings.default.json
  CHANGELOG.md
  CONTRIBUTING.md
  cypress/e2e/12-canvas.cy.ts
  cypress/e2e/13-pinning.cy.ts
  cypress/e2e/2-credentials.cy.ts
  cypress/e2e/5-ndv.cy.ts
  cypress/e2e/7-workflow-actions.cy.ts
  cypress/fixtures/Test_workflow_ndv_errors.json
  cypress/pages/modals/credentials-modal.ts
  cypress/pages/ndv.ts
  cypress/pages/settings-usage.ts
  package.json
  packages/cli/src/databases/migrations/mysqldb/1669823906994-AddTriggerCountColumn.ts
  packages/cli/src/databases/migrations/mysqldb/1671726148420-RemoveWorkflowDataLoadedFlag.ts
  packages/cli/src/eventbus/EventMessageClasses/EventMessageAudit.ts
  packages/cli/src/eventbus/EventMessageClasses/EventMessageNode.ts
  packages/cli/src/eventbus/EventMessageClasses/EventMessageWorkflow.ts
  pnpm-lock.yaml
Labels: core, n8n team

#5261 refactor(Telegram Node): Stream binary data for uploads and downloads
  packages/nodes-base/nodes/Telegram/Telegram.node.ts
Labels: node/improvement, n8n team, skip-e2e

#5265 ci: Run pnpm format and pnpm lintfix (no-changelog)
  packages/editor-ui/src/plugins/N8nCustomConnectorType.js
  packages/nodes-base/credentials/Aws.credentials.ts
  packages/nodes-base/nodes/ActionNetwork/types.d.ts
  packages/nodes-base/nodes/Airtable/Airtable.node.ts
Labels: node/improvement, ui, n8n team

#5262 fix(editor): Re-enable the element-ui memory-leak fix (no-changelog)
  package.json
  pnpm-lock.yaml
Labels: n8n team, skip-e2e

#5269 ci: Use the same version of prettier across the repo (no-changelog)
  package.json
  packages/editor-ui/package.json
  pnpm-lock.yaml
Labels: ui, n8n team, skip-e2e

#5268 fix(editor): Fix node authentication options ordering and hiding options based on node version
  packages/editor-ui/src/components/CredentialEdit/AuthTypeSelector.vue
  packages/editor-ui/src/utils/nodeTypesUtils.ts
Labels: ui, n8n team

#5167 feat(GitLab Node): Add file operations (create, delete, edit, get, list)
  packages/nodes-base/nodes/Gitlab/Gitlab.node.ts
Labels: node/improvement, community

#5272 fix: Fix RecycleScroller end index (no-changelog)
  packages/design-system/src/components/N8nRecycleScroller/RecycleScroller.vue
Labels: ui, n8n team

#5271 fix(editor): Handling router errors when navigation is canceled by user
  packages/editor-ui/src/components/MainSidebar.vue
  packages/editor-ui/src/components/WorkflowShareModal.ee.vue
Labels: ui, n8n team

#5284 ci(core): Fix docker nightly/custom image build (no-changelog)
  docker/images/n8n-custom/Dockerfile
  patches/element-ui@2.15.12.patch
  pnpm-lock.yaml
Labels: n8n team, skip-e2e

#4890 test: Add unit testing to nodes (no-changelog)
  packages/nodes-base/test/nodes/Airtable/Airtable.node.test.ts
  packages/nodes-base/test/nodes/Airtable/workflow.json
  packages/nodes-base/test/nodes/ExecuteWorkflow.ts
  packages/nodes-base/test/nodes/Helpers.ts
  packages/nodes-base/test/nodes/If/If.node.test.ts
  packages/nodes-base/test/nodes/If/workflow.json
  packages/nodes-base/test/nodes/Set/SetNode.test.ts
  packages/nodes-base/test/nodes/Start/StartNode.test.ts
  packages/nodes-base/test/nodes/types.ts
Labels: n8n team

#5191 feat(editor): Add mapping support for data paths
  packages/editor-ui/src/components/ParameterInputFull.vue
  packages/editor-ui/src/components/RunDataJson.vue
  packages/editor-ui/src/components/RunDataSchema.test.ts
  packages/editor-ui/src/components/RunDataSchemaItem.vue
  packages/editor-ui/src/components/RunDataTable.vue
  packages/editor-ui/src/components/__snapshots__/RunDataSchema.test.ts.snap
  packages/editor-ui/src/utils/__tests__/typesUtils.test.ts
  packages/editor-ui/src/utils/mappingUtils.ts
  packages/editor-ui/src/utils/typesUtils.ts
  packages/nodes-base/nodes/CompareDatasets/CompareDatasets.node.ts
  packages/nodes-base/nodes/ItemLists/ItemLists.node.ts
  packages/nodes-base/nodes/ItemLists/summarize.operation.ts
  packages/nodes-base/nodes/Merge/v2/MergeV2.node.ts
  packages/workflow/src/Interfaces.ts
Labels: node/improvement, core, ui, n8n team

#5287 ci(editor): Update RunDataSchema test (no-changelog)
  packages/editor-ui/src/components/__snapshots__/RunDataSchema.test.ts.snap
Labels: ui, n8n team, skip-e2e

#5276 feat: Add multiple workflows text search filtering E2E test scenarios (no-changelog)
  cypress/e2e/1-workflows.cy.ts
Labels: n8n team

#5283 refactor(core): Load and validate all config at startup (no-changelog)
  packages/cli/src/CredentialsOverwrites.ts
  packages/cli/src/Db.ts
  packages/cli/src/GenericHelpers.ts
  packages/cli/src/Server.ts
  packages/cli/src/UserManagement/email/UserManagementMailer.ts
  packages/cli/src/WaitTracker.ts
  packages/cli/src/WorkflowRunnerProcess.ts
  packages/cli/src/commands/db/revert.ts
  packages/cli/src/commands/execute.ts
  packages/cli/src/commands/executeBatch.ts
  packages/cli/src/commands/start.ts
  packages/cli/src/commands/webhook.ts
  packages/cli/src/commands/worker.ts
  packages/cli/src/config/index.ts
  packages/cli/src/databases/config.ts
  packages/cli/src/executions/executions.service.ts
Labels: core, n8n team, skip-e2e

#5290 fix(n8n Trigger Node): Use the new icon for N8N Trigger node (no-changelog)
  packages/nodes-base/nodes/N8nTrigger/n8nTrigger.svg
Labels: node/improvement, n8n team, skip-e2e

#5282 refactor: Clean up workflow stats test file
  packages/cli/test/unit/Events.test.ts
Labels: core, n8n team

#5294 feat(core): Export OpenAPI spec for external tools
  packages/cli/src/PublicApi/index.ts
Labels: core, n8n team, skip-e2e

#4989 refactor(editor): Upgrade to jsPlumb 5
  cypress/e2e/10-undo-redo.cy.ts
  cypress/e2e/12-canvas.cy.ts
  cypress/e2e/2-credentials.cy.ts
  cypress/e2e/5-ndv.cy.ts
  cypress/pages/workflow.ts
  cypress/support/commands.ts
  package.json
  packages/editor-ui/package.json
  packages/editor-ui/src/Interface.ts
  packages/editor-ui/src/components/Node.vue
  packages/editor-ui/src/components/NodeSettings.vue
  packages/editor-ui/src/components/Sticky.vue
  packages/editor-ui/src/main.ts
  packages/editor-ui/src/mixins/mouseSelect.ts
  packages/editor-ui/src/mixins/nodeBase.ts
  packages/editor-ui/src/mixins/nodeHelpers.ts
  packages/editor-ui/src/models/history.ts
  packages/editor-ui/src/plugins/N8nCustomConnectorType.js
  packages/editor-ui/src/plugins/PlusEndpointType.js
  packages/editor-ui/src/plugins/connectors/N8nCustomConnector.ts
  packages/editor-ui/src/plugins/endpoints/N8nPlusEndpointRenderer.ts
  packages/editor-ui/src/plugins/endpoints/N8nPlusEndpointType.ts
  packages/editor-ui/src/stores/canvas.ts
  packages/editor-ui/src/stores/ui.ts
  packages/editor-ui/src/stores/workflows.ts
  packages/editor-ui/src/utils/canvasUtils.ts
  packages/editor-ui/src/utils/nodeViewUtils.ts
  packages/editor-ui/src/views/CanvasAddButton.vue
  packages/editor-ui/src/views/NodeView.vue
  pnpm-lock.yaml
Labels: core, ui, n8n team

#5289 feat(editor): Continue to show mapping tooltip after dismiss
  packages/editor-ui/src/components/ParameterInputFull.vue
Labels: ui, n8n team, skip-e2e

#5257 fix(Set Node): Fix behaviour when selecting continueOnFail & PairedItem
  packages/core/src/NodeExecuteFunctions.ts
Labels: core, n8n team, Upcoming Release

#5301 refactor(core): Luxon dependency update
  packages/editor-ui/package.json
  packages/nodes-base/package.json
  packages/workflow/package.json
  pnpm-lock.yaml
Labels: core, ui, n8n team

#5293 refactor: Reduce payload size when fetching workflows to prevent memory issues
  packages/cli/src/executions/executions.service.ts
Labels: core, n8n team, skip-e2e

#5305 feat(SSH Node): Stream binary data for uploads and downloads
  packages/nodes-base/nodes/Ssh/Ssh.node.ts
Labels: node/improvement, n8n team, skip-e2e

#5308 fix(core): Allow listing users when logged in (no-changelog)
  packages/cli/src/middlewares/auth.ts
Labels: core, n8n team, skip-e2e

#5300 feat(editor): Append expressions in fixed values when mapping to string/json inputs
  packages/editor-ui/src/components/ParameterInputFull.vue
Labels: ui, n8n team

#5309 fix(editor): Fix `json` field completions while typing
  packages/editor-ui/src/components/CodeNodeEditor/completions/jsonField.completions.ts
Labels: ui, n8n team

#5310 feat(editor): Roll out schema view
  packages/editor-ui/src/components/RunData.vue
  packages/editor-ui/src/stores/ndv.ts
Labels: ui, n8n team

#5306 feat(Write Binary File Node): Stream binary data for writes
  packages/nodes-base/nodes/WriteBinaryFile/WriteBinaryFile.node.ts
Labels: node/improvement, n8n team, skip-e2e

#5220 fix: Add paired item to the most used nodes
  packages/nodes-base/nodes/Aws/DynamoDB/AwsDynamoDB.node.ts
  packages/nodes-base/nodes/Aws/S3/AwsS3.node.ts
  packages/nodes-base/nodes/Aws/SES/AwsSes.node.ts
  packages/nodes-base/nodes/Dropcontact/Dropcontact.node.ts
  packages/nodes-base/nodes/Dropcontact/GenericFunction.ts
  packages/nodes-base/nodes/Ftp/Ftp.node.ts
  packages/nodes-base/nodes/Grist/Grist.node.ts
  packages/nodes-base/nodes/HomeAssistant/HomeAssistant.node.ts
  packages/nodes-base/nodes/LinkedIn/LinkedIn.node.ts
  packages/nodes-base/nodes/Matrix/Matrix.node.ts
  packages/nodes-base/nodes/Microsoft/Outlook/MicrosoftOutlook.node.ts
  packages/nodes-base/nodes/N8nTrainingCustomerDatastore/N8nTrainingCustomerDatastore.node.ts
  packages/nodes-base/nodes/N8nTrainingCustomerMessenger/N8nTrainingCustomerMessenger.node.ts
  packages/nodes-base/nodes/Odoo/Odoo.node.ts
  packages/nodes-base/nodes/Phantombuster/Phantombuster.node.ts
  packages/nodes-base/nodes/PhilipsHue/PhilipsHue.node.ts
  packages/nodes-base/nodes/Pushover/Pushover.node.ts
  packages/nodes-base/nodes/Rocketchat/Rocketchat.node.ts
  packages/nodes-base/nodes/Snowflake/Snowflake.node.ts
  packages/nodes-base/nodes/Supabase/GenericFunctions.ts
  packages/nodes-base/nodes/Supabase/Supabase.node.ts
  packages/nodes-base/nodes/TheHive/TheHive.node.ts
  packages/nodes-base/nodes/Todoist/v2/TodoistV2.node.ts
  packages/nodes-base/nodes/Zulip/Zulip.node.ts
Labels: node/improvement, n8n team
