Repository n8n-io/n8n, pull requests merged in 2023-06, with the labels that each got.

#6305 fix: Prevent redirect when outside of executions home (no-changelog)
  packages/editor-ui/src/components/ExecutionsView/ExecutionsList.vue
Labels: ui, n8n team

#6349 refactor: Add deprecation notice for basic auth and JWT auth
  packages/cli/src/commands/BaseCommand.ts
  packages/cli/src/config/schema.ts
  packages/cli/src/constants.ts
Labels: core, n8n team

#6347 refactor: Revert 30k stars banner (no-changelog)
  packages/editor-ui/src/components/layouts/ResourcesListLayout.vue
  packages/editor-ui/src/constants.ts
  packages/editor-ui/src/plugins/i18n/locales/en.json
  packages/editor-ui/src/plugins/icons/index.ts
Labels: ui, n8n team

#6355 fix: Improve executions list polling performance
  packages/editor-ui/src/components/ExecutionsList.vue
  packages/editor-ui/src/components/ExecutionsView/ExecutionsList.vue
  packages/editor-ui/src/components/ExecutionsView/ExecutionsSidebar.vue
  packages/editor-ui/src/components/__tests__/ExecutionsList.test.ts
Labels: ui, n8n team

#6302 fix: Show actual execution data for production executions even if pin data exists
  packages/editor-ui/src/components/WorkflowPreview.vue
  packages/editor-ui/src/mixins/workflowHelpers.ts
  packages/editor-ui/src/stores/__tests__/workflows.test.ts
  packages/editor-ui/src/stores/workflows.store.ts
  packages/editor-ui/src/views/NodeView.vue
Labels: ui, n8n team

#6357 fix(core): Upgrade @n8n_io/riot-tmpl (no-changelog)
  packages/workflow/package.json
  pnpm-lock.yaml
Labels: core, n8n team

#6335 ci: Set up Turborepo cache for GitHub actions runner (no-changelog)
  .github/workflows/ci-master.yml
  .github/workflows/ci-postgres-mysql.yml
  .github/workflows/ci-pull-requests.yml
Labels: n8n team

#6346 fix(editor): Pin all data regardless of pagination
  packages/editor-ui/src/components/RunData.vue
Labels: ui, n8n team

#6363 feat(core): Remove conditional defaults in V1 release
  packages/cli/src/WebhookHelpers.ts
  packages/cli/src/commands/BaseCommand.ts
  packages/cli/src/config/schema.ts
  packages/cli/src/constants.ts
  packages/nodes-base/nodes/Code/Code.node.ts
  packages/nodes-base/utils/constants.ts
Labels: v1

#6367 refactor: Add deprecation notice for UM disabled mode
  packages/cli/src/commands/BaseCommand.ts
  packages/cli/src/config/schema.ts
Labels: v1

#6366 ci: Update the release process for v1 release
  .github/workflows/docker-image-v1-rc.yml
  .github/workflows/release-create-pr.yml
  .github/workflows/release-publish.yml
Labels: v1

#5793 ci: Add support for Node.js 18
  .github/workflows/check-documentation-urls.yml
  .github/workflows/check-pr-title.yml
  .github/workflows/ci-master.yml
  .github/workflows/ci-postgres-mysql.yml
  .github/workflows/ci-pull-requests.yml
  .github/workflows/docker-base-image.yml
  .github/workflows/docker-image-v1-rc.yml
  .github/workflows/e2e-reusable.yml
  .github/workflows/e2e-tests-pr.yml
  .github/workflows/e2e-tests.yml
  .github/workflows/release-create-pr.yml
  .github/workflows/release-publish.yml
  .github/workflows/release-push-to-channel.yml
  .github/workflows/test-workflows.yml
  docker/images/n8n-custom/Dockerfile
  package.json
  packages/cli/BREAKING-CHANGES.md
  packages/nodes-base/nodes/Crypto/Crypto.node.ts
  packages/nodes-base/nodes/Crypto/test/CryptoTest.workflow.json
  pnpm-lock.yaml
Labels: core, n8n team

#6372 fix(editor): Fix hard-coded parameter names for code editors
  packages/editor-ui/src/components/ParameterInput.vue
Labels: ui, n8n team

#6374 fix(editor): Fix typing `$` in inline expression field reloading node parameters form
  packages/editor-ui/src/components/ParameterInput.vue
  packages/editor-ui/src/components/ParameterInputList.vue
  packages/editor-ui/src/components/ResourceLocator/ResourceLocator.vue
  packages/editor-ui/src/components/ResourceMapper/MappingFields.vue
  packages/editor-ui/src/components/ResourceMapper/ResourceMapper.vue
Labels: ui, n8n team

#6290 ci: Improve Test-worklows messages
  .github/workflows/test-workflows.yml
  packages/cli/src/commands/Interfaces.d.ts
  packages/cli/src/commands/executeBatch.ts
Labels: core, n8n team

#6376 docs: Fix trigger node link for Lonescale
  packages/nodes-base/nodes/LoneScale/LoneScaleTrigger.node.json
Labels: node/improvement, n8n team

#6341 fix(editor): Deal with null settings
  packages/editor-ui/src/views/SettingsUsersView.vue
Labels: ui, n8n team

#6361 refactor(editor): Remove user activation modal (no-changelog)
  cypress/e2e/22-user-activation-modal.cy.ts
  cypress/fixtures/Settings_user_activation_modal_enabled.json
  cypress/pages/modals/index.ts
  cypress/pages/modals/user-activation-survey-modal.ts
  packages/cli/src/Server.ts
  packages/cli/src/config/schema.ts
  packages/cli/src/events/WorkflowStatistics.ts
  packages/cli/src/requests.ts
  packages/editor-ui/package.json
  packages/editor-ui/src/__tests__/server/endpoints/settings.ts
  packages/editor-ui/src/__tests__/utils.ts
  packages/editor-ui/src/components/Modals.vue
  packages/editor-ui/src/components/UserActivationSurveyModal.vue
  packages/editor-ui/src/constants.ts
  packages/editor-ui/src/main.ts
  packages/editor-ui/src/plugins/i18n/locales/en.json
  packages/editor-ui/src/stores/settings.store.ts
  packages/editor-ui/src/stores/ui.store.ts
  packages/editor-ui/src/stores/users.store.ts
  packages/workflow/src/Interfaces.ts
  pnpm-lock.yaml
Labels: core, ui, n8n team

#6380 fix(editor): Adding branch color
  packages/cli/src/environments/versionControl/types/versionControlPreferences.ts
  packages/cli/src/environments/versionControl/versionControl.controller.ee.ts
  packages/cli/src/environments/versionControl/versionControl.service.ee.ts
  packages/cli/src/environments/versionControl/versionControlPreferences.service.ee.ts
  packages/editor-ui/src/api/versionControl.ts
  packages/editor-ui/src/components/MainSidebarVersionControl.vue
  packages/editor-ui/src/stores/versionControl.store.ts
  packages/editor-ui/src/views/SettingsVersionControl.vue
Labels: ui, n8n team

#6379 ci: Fix build (no-changelog)
  packages/design-system/src/utils/__tests__/event-bus.spec.ts
Labels: ui, n8n team

#6390 fix(editor): Remove explicit parameter name scanning for code editors
  packages/editor-ui/src/components/ParameterInput.vue
Labels: ui, n8n team

#6356 fix(editor): Add Set up version control CTA
  packages/design-system/src/components/N8nMenu/Menu.vue
  packages/editor-ui/src/components/MainSidebar.vue
  packages/editor-ui/src/components/MainSidebarVersionControl.vue
  packages/editor-ui/src/components/SettingsSidebar.vue
  packages/editor-ui/src/components/__tests__/MainSidebarVersionControl.test.ts
  packages/editor-ui/src/plugins/i18n/locales/en.json
Labels: ui, n8n team

#6387 fix(editor): Add button to refresh branches
  packages/editor-ui/src/plugins/i18n/locales/en.json
  packages/editor-ui/src/views/SettingsVersionControl.vue
Labels: ui, n8n team

#6391 ci: Fix build (no-changelog)
  packages/editor-ui/src/stores/ui.store.ts
  packages/nodes-base/credentials/Ldap.credentials.ts
  packages/nodes-base/nodes/LoneScale/LoneScaleList.node.ts
  packages/nodes-base/nodes/LoneScale/LoneScaleTrigger.node.ts
  packages/nodes-base/nodes/Postgres/v2/helpers/utils.ts
Labels: node/improvement, ui, n8n team

#6393 fix(editor): Update version control setup CTA tooltip
  packages/editor-ui/src/plugins/i18n/locales/en.json
Labels: ui, n8n team

#6337 refactor(LoneScale List Node)!: Rename to LoneScale
  packages/cli/BREAKING-CHANGES.md
  packages/nodes-base/nodes/LoneScale/LoneScale.node.ts
  packages/nodes-base/package.json
Labels: core, n8n team

#6368 refactor(core): Google service account remove duplicated functions (no-changelog)
  packages/nodes-base/nodes/Google/BigQuery/v1/GenericFunctions.ts
  packages/nodes-base/nodes/Google/BigQuery/v2/transport/index.ts
  packages/nodes-base/nodes/Google/Books/GenericFunctions.ts
  packages/nodes-base/nodes/Google/Chat/GenericFunctions.ts
  packages/nodes-base/nodes/Google/Docs/GenericFunctions.ts
  packages/nodes-base/nodes/Google/Drive/GenericFunctions.ts
  packages/nodes-base/nodes/Google/GenericFunctions.ts
  packages/nodes-base/nodes/Google/Gmail/GenericFunctions.ts
  packages/nodes-base/nodes/Google/Sheet/v1/GenericFunctions.ts
  packages/nodes-base/nodes/Google/Sheet/v1/GoogleSheetsV1.node.ts
  packages/nodes-base/nodes/Google/Sheet/v2/methods/credentialTest.ts
  packages/nodes-base/nodes/Google/Sheet/v2/transport/index.ts
  packages/nodes-base/nodes/Google/Slides/GenericFunctions.ts
  packages/nodes-base/nodes/Google/Translate/GenericFunctions.ts
Labels: n8n team, tech debt

#6385 fix(Date & Time Node): Reset responseData at end of loop
  packages/nodes-base/nodes/DateTime/V2/DateTimeV2.node.ts
Labels: node/improvement, n8n team

#6395 build: Update pnpm lock file (no-changelog)
  .github/workflows/test-workflows.yml
  package.json
  pnpm-lock.yaml
Labels: n8n team

#5495 feat: New trigger PostgreSQL
  packages/nodes-base/nodes/Postgres/PostgresInterface.ts
  packages/nodes-base/nodes/Postgres/PostgresTrigger.functions.ts
  packages/nodes-base/nodes/Postgres/PostgresTrigger.node.json
  packages/nodes-base/nodes/Postgres/PostgresTrigger.node.ts
  packages/nodes-base/nodes/Postgres/v1/genericFunctions.ts
  packages/nodes-base/package.json
Labels: node/improvement, node/new, n8n team, node/name

#6371 fix(Ldap Node): Add DN field to update operation
  packages/nodes-base/nodes/Ldap/LdapDescription.ts
Labels: node/improvement, n8n team

#6392 fix(editor): Remove root level tag selector from css module to avoid making it a global style
  packages/editor-ui/src/views/SettingsVersionControl.vue
Labels: ui, n8n team

#6397 fix(core): RMC boolean value fix
  packages/editor-ui/src/components/ResourceMapper/MappingFields.vue
Labels: n8n team, node/issue

#6386 fix(core): Allow all executions to be stopped
  packages/cli/src/Server.ts
  packages/cli/src/WaitTracker.ts
  packages/editor-ui/src/mixins/executionsHelpers.ts
Labels: core, ui, n8n team

#6352 fix(core)!: Allow syntax errors and expression errors to fail executions
  cypress/e2e/11-inline-expression-editor.cy.ts
  cypress/e2e/9-expression-editor-modal.cy.ts
  packages/core/src/NodeExecuteFunctions.ts
  packages/workflow/src/Expression.ts
  packages/workflow/src/ExpressionError.ts
  packages/workflow/src/WorkflowDataProxy.ts
  packages/workflow/src/utils.ts
  packages/workflow/test/Expression.test.ts
Labels: core, n8n team, v1

#6323 refactor: Separate execution data to its own table
  packages/cli/src/ActiveExecutions.ts
  packages/cli/src/Db.ts
  packages/cli/src/GenericHelpers.ts
  packages/cli/src/Interfaces.ts
  packages/cli/src/InternalHooks.ts
  packages/cli/src/PublicApi/v1/handlers/executions/executions.handler.ts
  packages/cli/src/PublicApi/v1/handlers/executions/executions.service.ts
  packages/cli/src/ResponseHelper.ts
  packages/cli/src/Server.ts
  packages/cli/src/WaitTracker.ts
  packages/cli/src/WaitingWebhooks.ts
  packages/cli/src/WorkflowExecuteAdditionalData.ts
  packages/cli/src/WorkflowRunner.ts
  packages/cli/src/audit/risks/credentials.risk.ts
  packages/cli/src/commands/worker.ts
  packages/cli/src/databases/entities/ExecutionData.ts
  packages/cli/src/databases/entities/ExecutionEntity.ts
  packages/cli/src/databases/entities/index.ts
  packages/cli/src/databases/migrations/mysqldb/1690000000030-SeparateExecutionData.ts
  packages/cli/src/databases/migrations/mysqldb/index.ts
  packages/cli/src/databases/migrations/postgresdb/1690000000020-SeparateExecutionData.ts
  packages/cli/src/databases/migrations/postgresdb/index.ts
  packages/cli/src/databases/migrations/sqlite/1690000000002-MigrateIntegerKeysToString.ts
  packages/cli/src/databases/migrations/sqlite/1690000000010-SeparateExecutionData.ts
  packages/cli/src/databases/migrations/sqlite/index.ts
  packages/cli/src/databases/repositories/execution.repository.ts
  packages/cli/src/databases/repositories/executionData.repository.ts
  packages/cli/src/databases/repositories/index.ts
  packages/cli/src/environments/variables/variables.service.ee.ts
  packages/cli/src/eventbus/MessageEventBus/recoverEvents.ts
  packages/cli/src/executions/executionHelpers.ts
  packages/cli/src/executions/executions.service.ts
  packages/cli/test/integration/audit/credentials.risk.test.ts
  packages/cli/test/integration/shared/testDb.ts
  packages/cli/test/unit/ActiveExecutions.test.ts
  packages/editor-ui/src/utils/executionUtils.ts
  pnpm-lock.yaml
Labels: core, n8n team

#6404 fix: Fist name to First Name in certain nodes (no-changelog)
  packages/nodes-base/nodes/Affinity/PersonDescription.ts
  packages/nodes-base/nodes/Salesforce/LeadDescription.ts
  packages/nodes-base/nodes/Uplead/PersonDescription.ts
Labels: node/improvement, n8n team

#6408 test(editor): Unit test Version control frontend components
  packages/design-system/package.json
  packages/design-system/src/components/N8nSelect/__tests__/Select.spec.ts
  packages/editor-ui/src/__tests__/server/endpoints/index.ts
  packages/editor-ui/src/__tests__/server/endpoints/versionControl.ts
  packages/editor-ui/src/__tests__/server/index.ts
  packages/editor-ui/src/views/SettingsVersionControl.vue
  packages/editor-ui/src/views/__tests__/SettingsVersionControl.test.ts
  pnpm-lock.yaml
Labels: ui, n8n team

#6403 docs: Fix Postgres trigger docs URL
  packages/nodes-base/nodes/Postgres/PostgresTrigger.node.json
Labels: node/improvement, n8n team

#6414 fix(LinkedIn Node): Fix issue with posting as user or organization
  packages/nodes-base/credentials/LinkedInOAuth2Api.credentials.ts
  packages/nodes-base/nodes/LinkedIn/GenericFunctions.ts
  packages/nodes-base/nodes/LinkedIn/LinkedIn.node.ts
Labels: node/improvement, n8n team

#6419 fix(editor): Hide version control main menu component if no feature flag
  packages/editor-ui/src/components/MainSidebarVersionControl.vue
  packages/editor-ui/src/components/__tests__/MainSidebarVersionControl.test.ts
Labels: ui, n8n team

#6401 fix(Schedule Trigger Node): Follow the correct Unix cron format for month and days of the week
  packages/nodes-base/nodes/Schedule/GenericFunctions.ts
  packages/nodes-base/nodes/Schedule/ScheduleTrigger.node.ts
Labels: node/improvement, n8n team

#6420 fix(core): Prevent arbitrary code execution via expressions
  packages/workflow/src/Expression.ts
  packages/workflow/test/Expression.test.ts
Labels: core, n8n team

#6427 fix(Zulip Node): Remove trailing slash from the url
  packages/nodes-base/nodes/Zulip/GenericFunctions.ts
Labels: node/improvement, n8n team

#6407 fix(Google Sheets Node): Return empty response if no rows updated
  packages/nodes-base/nodes/Google/Sheet/v2/actions/sheet/update.operation.ts
Labels: n8n team, node/issue

#6433 ci: Fix docs urls (no-changelog)
  packages/nodes-base/credentials/Ldap.credentials.ts
  packages/nodes-base/credentials/LoneScaleApi.credentials.ts
  packages/nodes-base/nodes/ExecutionData/ExecutionData.node.json
  packages/nodes-base/nodes/Ldap/Ldap.node.json
Labels: node/improvement, n8n team

#6418 feat: Audit Logs - add new page [WIP] (no-changelog)
  packages/cli/src/Server.ts
  packages/editor-ui/src/__tests__/server/endpoints/settings.ts
  packages/editor-ui/src/__tests__/utils.ts
  packages/editor-ui/src/components/SettingsSidebar.vue
  packages/editor-ui/src/constants.ts
  packages/editor-ui/src/plugins/i18n/locales/en.json
  packages/editor-ui/src/plugins/icons/index.ts
  packages/editor-ui/src/router.ts
  packages/editor-ui/src/stores/auditLogs.store.ts
  packages/editor-ui/src/stores/index.ts
  packages/editor-ui/src/views/SettingsAuditLogs.vue
  packages/editor-ui/src/views/__tests__/SettingsAuditLogs.test.ts
  packages/workflow/src/Interfaces.ts
Labels: ui, n8n team

#6435 fix(core)!: Make date extensions outputs match inputs
  packages/workflow/src/Extensions/DateExtensions.ts
  packages/workflow/test/ExpressionExtensions/DateExtensions.test.ts
Labels: core, n8n team, v1

#6440 fix(editor): Update version control docs links
  packages/editor-ui/src/views/SettingsVersionControl.vue
Labels: ui, n8n team

#6430 fix: Fix randomly failing scheduler node e2e tests (no-changelog)
  cypress/constants.ts
  cypress/e2e/15-scheduler-node.cy.ts
  cypress/e2e/16-webhook-node.cy.ts
Labels: n8n team

#6442 fix: Add .gitattributes to preserve line endings (no-changelog)
  .gitattributes
Labels: n8n team

#6190 feat(Item Lists Node): Improvements
  packages/nodes-base/nodes/ItemLists/ItemLists.node.ts
  packages/nodes-base/nodes/ItemLists/V2/ItemListsV2.node.ts
  packages/nodes-base/nodes/ItemLists/test/node/workflow.update_2_2.json
Labels: node/improvement, n8n team, tech debt

#6436 fix(editor): Update data pinning tooltip to match current behaviour
  packages/editor-ui/src/plugins/i18n/locales/en.json
Labels: ui, n8n team

#6451 fix(editor): Show confirm on pull only when http response status is 409
  packages/editor-ui/src/__tests__/server/endpoints/versionControl.ts
  packages/editor-ui/src/components/MainSidebarVersionControl.vue
  packages/editor-ui/src/components/__tests__/MainSidebarVersionControl.test.ts
  packages/editor-ui/src/plugins/i18n/locales/en.json
  packages/editor-ui/src/views/SettingsVersionControl.vue
Labels: ui, n8n team

#6445 fix: Remove Vue.component usage and refactor plugins into Vue Plugins (no-changelog)
  packages/editor-ui/src/__tests__/setup.ts
  packages/editor-ui/src/components/CredentialCard.vue
  packages/editor-ui/src/components/CredentialIcon.vue
  packages/editor-ui/src/components/NodeTitle.vue
  packages/editor-ui/src/components/TemplateCard.vue
  packages/editor-ui/src/components/VersionCard.vue
  packages/editor-ui/src/components/WorkflowCard.vue
  packages/editor-ui/src/main.ts
  packages/editor-ui/src/plugins/components.ts
  packages/editor-ui/src/plugins/directives.ts
  packages/editor-ui/src/plugins/i18n/index.ts
  packages/editor-ui/src/plugins/icons/index.ts
  packages/editor-ui/src/stores/communityNodes.store.ts
  packages/editor-ui/src/stores/credentials.store.ts
  packages/editor-ui/src/stores/tags.store.ts
  packages/editor-ui/src/stores/workflows.store.ts
Labels: ui, n8n team

#6453 feat(Gmail Node): Add reply to email
  packages/nodes-base/nodes/Google/Gmail/GenericFunctions.ts
  packages/nodes-base/nodes/Google/Gmail/v2/DraftDescription.ts
  packages/nodes-base/nodes/Google/Gmail/v2/GmailV2.node.ts
  packages/nodes-base/nodes/Google/Gmail/v2/MessageDescription.ts
Labels: node/improvement, community

#6437 fix(Split In Batches Node): Add "done" context to allow simple reset
  packages/nodes-base/nodes/SplitInBatches/test/SplitInBatches.workflow_v2_done_variable.json
  packages/nodes-base/nodes/SplitInBatches/v2/SplitInBatchesV2.node.ts
Labels: node/improvement, n8n team

#6446 fix(LinkedIn Node): Remove unsupported description from image posts
  packages/nodes-base/nodes/LinkedIn/LinkedIn.node.ts
  packages/nodes-base/nodes/LinkedIn/PostDescription.ts
Labels: node/improvement, n8n team

#6452 ci: Prevent e2e failure on `commented` type review (no-changelog)
  .github/workflows/e2e-tests-pr.yml
Labels: n8n team

#6456 feat: Remove vue-fragment (no-changelog)
  packages/editor-ui/package.json
  packages/editor-ui/src/components/Badge.vue
  packages/editor-ui/src/components/PageAlert.vue
  packages/editor-ui/src/components/Telemetry.vue
  packages/editor-ui/src/plugins/components.ts
  pnpm-lock.yaml
Labels: ui, n8n team

#6459 fix(editor): Fix DNV header disappearing when scrolling the code editor content
  packages/editor-ui/src/components/NodeSettings.vue
Labels: ui, n8n team

#6460 fix(editor): Remove `$if`, `$min` and `$max` from code node autocomplete
  packages/editor-ui/src/components/CodeNodeEditor/completions/base.completions.ts
Labels: ui, n8n team

#6466 fix(core): Fix the url sent in the password-reset emails
  packages/cli/src/controllers/passwordReset.controller.ts
Labels: core, n8n team

#6461 feat: Add support for large files with declarative nodes
  packages/core/src/NodeExecuteFunctions.ts
Labels: core, n8n team

#6475 fix(editor): Update git repo URL validation to prevent using https protocol
  packages/editor-ui/src/views/SettingsVersionControl.vue
Labels: ui, n8n team

#6463 feat(Webhook Node): Stream binary response in `lastNode.firstEntryBinary` mode
  packages/cli/src/WebhookHelpers.ts
  packages/core/src/BinaryDataManager/index.ts
  packages/core/src/NodeExecuteFunctions.ts
Labels: core, n8n team

#6443 feat(editor): Add v1 banner
  packages/cli/src/Server.ts
  packages/cli/src/config/types.d.ts
  packages/cli/src/controllers/owner.controller.ts
  packages/cli/src/databases/repositories/settings.repository.ts
  packages/design-system/src/components/N8nCallout/Callout.vue
  packages/editor-ui/src/App.vue
  packages/editor-ui/src/Interface.ts
  packages/editor-ui/src/__tests__/server/endpoints/settings.ts
  packages/editor-ui/src/api/ui.ts
  packages/editor-ui/src/components/V1Banner.vue
  packages/editor-ui/src/main.ts
  packages/editor-ui/src/plugins/i18n/locales/en.json
  packages/editor-ui/src/plugins/icons/custom.ts
  packages/editor-ui/src/plugins/icons/index.ts
  packages/editor-ui/src/stores/settings.store.ts
  packages/editor-ui/src/stores/ui.store.ts
  packages/workflow/src/Interfaces.ts
Labels: core, ui, n8n team, v1

#6409 fix(core): Fix issue with multi-input-nodes that have multiple runs
  packages/core/src/WorkflowExecute.ts
  packages/core/test/WorkflowExecute.test.ts
Labels: node/improvement, core, n8n team, v1

#6246 feat(core): Change node execution order (most top-left one first)
  cypress/e2e/24-ndv-paired-item.cy.ts
  cypress/pages/ndv.ts
  packages/core/src/WorkflowExecute.ts
  packages/core/test/WorkflowExecute.test.ts
Labels: core, n8n team, v1

#6482 feat(Stripe Trigger Node): Add action required trigger for payment intents
  packages/nodes-base/nodes/Stripe/StripeTrigger.node.ts
Labels: node/improvement, n8n team

#6406 feat(DebugHelper Node): Fix and include in main app
  packages/nodes-base/nodes/DebugHelper/DebugHelper.node.json
  packages/nodes-base/nodes/DebugHelper/DebugHelper.node.ts
  packages/nodes-base/nodes/DebugHelper/DebugHelper.svg
  packages/nodes-base/nodes/DebugHelper/functions.ts
  packages/nodes-base/nodes/DebugHelper/randomData.ts
  packages/nodes-base/package.json
  pnpm-lock.yaml
Labels: node/new, n8n team

#6454 feat(editor): Replace root events with event bus events (no-changelog)
  cypress/e2e/5-ndv.cy.ts
  packages/editor-ui/src/components/IntersectionObserved.vue
  packages/editor-ui/src/components/IntersectionObserver.vue
  packages/editor-ui/src/components/MainHeader/WorkflowDetails.vue
  packages/editor-ui/src/components/ParameterInput.vue
  packages/editor-ui/src/components/ParameterInputExpanded.vue
  packages/editor-ui/src/components/ParameterInputFull.vue
  packages/editor-ui/src/components/ParameterInputWrapper.vue
  packages/editor-ui/src/components/ResourceLocator/ResourceLocator.vue
  packages/editor-ui/src/components/ResourceLocator/ResourceLocatorDropdown.vue
  packages/editor-ui/src/components/TagsContainer.vue
  packages/editor-ui/src/composables/useGlobalLinkActions.ts
  packages/editor-ui/src/event-bus/index.ts
  packages/editor-ui/src/event-bus/link-actions.ts
  packages/editor-ui/src/mixins/emitter.ts
  packages/editor-ui/src/mixins/pushConnection.ts
  packages/editor-ui/src/views/NodeView.vue
Labels: ui, n8n team

#6485 fix(editor): Pay 548 hide the set up version control button
  packages/editor-ui/src/components/MainSidebarSourceControl.vue
  packages/editor-ui/src/components/__tests__/MainSidebarSourceControl.test.ts
  packages/editor-ui/src/plugins/i18n/locales/en.json
  packages/nodes-base/nodes/DebugHelper/DebugHelper.node.json
  packages/nodes-base/nodes/DebugHelper/DebugHelper.node.ts
  packages/nodes-base/nodes/DebugHelper/DebugHelper.svg
  packages/nodes-base/nodes/DebugHelper/functions.ts
  packages/nodes-base/nodes/DebugHelper/randomData.ts
  packages/nodes-base/package.json
  pnpm-lock.yaml
Labels: node/new, ui, n8n team

#6455 build: Check test files
  .github/scripts/check-tests.mjs
  .github/scripts/package.json
  .github/workflows/check-tests.yml
Labels: n8n team

#6488 fix(editor): Update source control docs links
  cypress/e2e/5-ndv.cy.ts
  packages/editor-ui/src/components/IntersectionObserved.vue
  packages/editor-ui/src/components/IntersectionObserver.vue
  packages/editor-ui/src/components/MainHeader/WorkflowDetails.vue
  packages/editor-ui/src/components/ParameterInput.vue
  packages/editor-ui/src/components/ParameterInputExpanded.vue
  packages/editor-ui/src/components/ParameterInputFull.vue
  packages/editor-ui/src/components/ParameterInputWrapper.vue
  packages/editor-ui/src/components/ResourceLocator/ResourceLocator.vue
  packages/editor-ui/src/components/ResourceLocator/ResourceLocatorDropdown.vue
  packages/editor-ui/src/components/TagsContainer.vue
  packages/editor-ui/src/composables/useGlobalLinkActions.ts
  packages/editor-ui/src/event-bus/index.ts
  packages/editor-ui/src/event-bus/link-actions.ts
  packages/editor-ui/src/mixins/emitter.ts
  packages/editor-ui/src/mixins/pushConnection.ts
  packages/editor-ui/src/plugins/i18n/locales/en.json
  packages/editor-ui/src/views/NodeView.vue
Labels: ui, n8n team

#6492 fix(HTTP Request Node): "Ignore SSL issues" should also ignore legacy renegotiation issues
  packages/core/src/NodeExecuteFunctions.ts
Labels: core, n8n team

#6493 fix(editor): Fix resource mapper dropdown width and disabled styling
  packages/editor-ui/src/components/ResourceMapper/MappingFields.vue
  packages/editor-ui/src/n8n-theme.scss
Labels: ui, n8n team

#6405 fix(core): Fix pairedItem for alwaysOutputData & multi identical resolve
  packages/core/src/WorkflowExecute.ts
  packages/core/test/Helpers.ts
  packages/core/test/NodeExecuteFunctions.test.ts
  packages/core/test/WorkflowExecute.test.ts
  packages/core/test/helpers/constants.ts
  packages/core/test/helpers/index.ts
  packages/core/test/helpers/utils.ts
  packages/core/test/workflows/paired_items_fix.json
  packages/nodes-base/test/nodes/Helpers.ts
  packages/nodes-base/test/nodes/types.ts
  packages/workflow/src/Interfaces.ts
  packages/workflow/src/WorkflowDataProxy.ts
Labels: core, n8n team

#6324 feat(core): Add PKCE for OAuth2
  package.json
  packages/cli/package.json
  packages/cli/src/credentials/oauth2Credential.api.ts
  packages/core/src/NodeExecuteFunctions.ts
  packages/editor-ui/src/components/CredentialEdit/CredentialEdit.vue
  packages/nodes-base/credentials/AirtableOAuth2Api.credentials.ts
  packages/nodes-base/credentials/OAuth2Api.credentials.ts
  packages/nodes-base/nodes/Airtable/Airtable.node.ts
  packages/nodes-base/package.json
  packages/workflow/src/Interfaces.ts
  patches/pkce-challenge@3.0.0.patch
  pnpm-lock.yaml
Labels: node/improvement, core, ui, n8n team

#6499 docs(DebugHelper Node): Update codex for debughelper (no-changelog)
  packages/nodes-base/nodes/DebugHelper/DebugHelper.node.json
Labels: node/improvement, n8n team

#6500 fix(core): Fix OAuth2 callback for `grantType=clientCredentials`
  packages/cli/src/credentials/oauth2Credential.api.ts
Labels: core, n8n team

#6495 refactor: Remove pre-setup prompt on owner setup
  packages/cli/src/controllers/owner.controller.ts
  packages/cli/test/integration/shared/constants.ts
  packages/cli/test/unit/controllers/owner.controller.test.ts
  packages/editor-ui/src/api/users.ts
  packages/editor-ui/src/plugins/i18n/locales/en.json
  packages/editor-ui/src/stores/users.store.ts
  packages/editor-ui/src/views/SetupView.vue
Labels: core, ui, n8n team, v1

#6360 feat(core): Add GET /users endpoints to public API
  packages/cli/src/License.ts
  packages/cli/src/PublicApi/v1/handlers/users/spec/paths/users.id.yml
  packages/cli/src/PublicApi/v1/handlers/users/spec/paths/users.yml
  packages/cli/src/PublicApi/v1/handlers/users/spec/schemas/parameters/includeRole.yml
  packages/cli/src/PublicApi/v1/handlers/users/spec/schemas/parameters/userIdentifier.yml
  packages/cli/src/PublicApi/v1/handlers/users/spec/schemas/role.yml
  packages/cli/src/PublicApi/v1/handlers/users/spec/schemas/user.yml
  packages/cli/src/PublicApi/v1/handlers/users/spec/schemas/userList.yml
  packages/cli/src/PublicApi/v1/handlers/users/users.handler.ee.ts
  packages/cli/src/PublicApi/v1/handlers/users/users.service.ee.ts
  packages/cli/src/PublicApi/v1/handlers/users/users.service.ts
  packages/cli/src/PublicApi/v1/handlers/workflows/workflows.handler.ts
  packages/cli/src/PublicApi/v1/handlers/workflows/workflows.service.ts
  packages/cli/src/PublicApi/v1/openapi.yml
  packages/cli/src/PublicApi/v1/shared/middlewares/global.middleware.ts
  packages/cli/src/PublicApi/v1/shared/spec/parameters/_index.yml
  packages/cli/src/PublicApi/v1/shared/spec/schemas/_index.yml
  packages/cli/src/constants.ts
  packages/cli/src/license/license.controller.ts
  packages/cli/test/integration/publicApi/users.ee.test.ts
Labels: core, n8n team

#6502 fix(core): Use correct scopes-separator when generating authorization urls
  packages/@n8n/client-oauth2/src/ClientOAuth2.ts
  packages/@n8n/client-oauth2/src/ClientOAuth2Token.ts
  packages/@n8n/client-oauth2/src/CodeFlow.ts
  packages/@n8n/client-oauth2/src/CredentialsFlow.ts
  packages/@n8n/client-oauth2/src/types.ts
  packages/@n8n/client-oauth2/src/utils.ts
  packages/@n8n/client-oauth2/test/CodeFlow.test.ts
  packages/cli/src/credentials/oauth2Credential.api.ts
Labels: core, n8n team

#6498 fix: Make MySQL migration for nano id change compatible with version 5.7
  .github/workflows/ci-postgres-mysql.yml
  packages/cli/package.json
  packages/cli/src/databases/migrations/mysqldb/1690000000001-MigrateIntegerKeysToString.ts
  packages/cli/src/databases/migrations/postgresdb/1690000000000-MigrateIntegerKeysToString.ts
  packages/cli/src/databases/migrations/sqlite/1690000000002-MigrateIntegerKeysToString.ts
Labels: core, n8n team

#6501 fix(Zendesk Node): Fix issue with group assignment not working
  packages/nodes-base/credentials/ZendeskApi.credentials.ts
  packages/nodes-base/nodes/Zendesk/TicketInterface.ts
  packages/nodes-base/nodes/Zendesk/Zendesk.node.ts
Labels: node/improvement, n8n team

#6506 fix(core): Fix the `db:revert` command (no-changelog)
  packages/cli/src/commands/db/revert.ts
  packages/cli/src/databases/utils/migrationHelpers.ts
  packages/cli/test/integration/shared/testDb.ts
Labels: core, n8n team

#6515 fix(core): Fix `import:credential` on postgres (no-changelog)
  packages/cli/src/commands/import/credentials.ts
Labels: core, n8n team

#6513 fix(Edit Image Node): Fix transparent operation
  packages/nodes-base/nodes/EditImage/EditImage.node.ts
Labels: node/improvement, n8n team

#6519 fix(core): All migrations should run in a transaction
  package.json
  packages/cli/src/databases/migrations/mysqldb/1690000000001-MigrateIntegerKeysToString.ts
  packages/cli/src/databases/migrations/postgresdb/1690000000000-MigrateIntegerKeysToString.ts
  packages/cli/src/databases/migrations/sqlite/1652367743993-AddUserSettings.ts
  packages/cli/src/databases/migrations/sqlite/1652905585850-AddAPIKeyColumn.ts
  packages/cli/src/databases/migrations/sqlite/1673268682475-DeleteExecutionsWithWorkflows.ts
  packages/cli/src/databases/migrations/sqlite/1690000000002-MigrateIntegerKeysToString.ts
  packages/cli/src/databases/types.ts
  patches/typeorm@0.3.12.patch
  pnpm-lock.yaml
Labels: core, n8n team

#6524 ci: Refactor e2e tests to delete boilerplate code (no-changelog)
  .dockerignore
  .github/workflows/ci-pull-requests.yml
  cypress.config.js
  cypress/constants.ts
  cypress/e2e/0-smoke.cy.ts
  cypress/e2e/1-workflows.cy.ts
  cypress/e2e/10-settings-log-streaming.cy.ts
  cypress/e2e/10-undo-redo.cy.ts
  cypress/e2e/11-inline-expression-editor.cy.ts
  cypress/e2e/12-canvas-actions.cy.ts
  cypress/e2e/12-canvas.cy.ts
  cypress/e2e/13-pinning.cy.ts
  cypress/e2e/14-data-transformation-expressions.cy.ts
  cypress/e2e/14-mapping.cy.ts
  cypress/e2e/15-scheduler-node.cy.ts
  cypress/e2e/16-webhook-node.cy.ts
  cypress/e2e/17-sharing.cy.ts
  cypress/e2e/17-workflow-tags.cy.ts
  cypress/e2e/18-user-management.cy.ts
  cypress/e2e/19-execution.cy.ts
  cypress/e2e/2-credentials.cy.ts
  cypress/e2e/20-workflow-executions.cy.ts
  cypress/e2e/21-community-nodes.cy.ts
  cypress/e2e/23-variables.cy.ts
  cypress/e2e/24-ndv-paired-item.cy.ts
  cypress/e2e/25-stickies.cy.ts
  cypress/e2e/26-resource-locator.cy.ts
  cypress/e2e/4-node-creator.cy.ts
  cypress/e2e/5-ndv.cy.ts
  cypress/e2e/6-code-node.cy.ts
  cypress/e2e/7-workflow-actions.cy.ts
  cypress/e2e/8-http-request-node.cy.ts
  cypress/e2e/9-expression-editor-modal.cy.ts
  cypress/pages/index.ts
  cypress/pages/sidebar/main-sidebar.ts
  cypress/pages/signin.ts
  cypress/pages/signup.ts
  cypress/support/commands.ts
  cypress/support/e2e.ts
  cypress/support/index.ts
  package.json
  packages/cli/.npmignore
  packages/cli/package.json
  packages/cli/src/License.ts
  packages/cli/src/Server.ts
  packages/cli/src/api/e2e.api.ts
  packages/cli/src/config/index.ts
  packages/cli/src/controllers/e2e.controller.ts
  packages/cli/src/requests.ts
  pnpm-lock.yaml
Labels: n8n team, v1

#6496 fix: Show error when referencing node that exist but has not been executed
  cypress/e2e/14-mapping.cy.ts
  packages/workflow/src/WorkflowDataProxy.ts
  packages/workflow/test/WorkflowDataProxy.test.ts
Labels: core, n8n team, v1

#4853 refactor: Remove `executeSingle` (no-changelog)
  packages/core/src/DirectoryLoader.ts
  packages/node-dev/README.md
  packages/workflow/src/Interfaces.ts
  packages/workflow/src/Workflow.ts
Labels: core, n8n team, v1

#4238 feat(core)!: Change data processing for multi-input-nodes
  packages/core/src/WorkflowExecute.ts
  packages/core/test/WorkflowExecute.test.ts
  packages/core/test/helpers/constants.ts
  packages/nodes-base/nodes/CompareDatasets/CompareDatasets.node.ts
  packages/nodes-base/nodes/CompareDatasets/test/node/workflow.compareDatasets.forceInputNodeExecution.json
  packages/nodes-base/nodes/Merge/Merge.node.ts
  packages/nodes-base/nodes/Merge/test/node/workflow.mixed.forceInputNodeExecution.json
  packages/nodes-base/nodes/Merge/test/node/workflow.mixed.not.forceInputNodeExecution.json
  packages/nodes-base/nodes/Merge/v1/MergeV1.node.ts
  packages/nodes-base/nodes/Merge/v2/MergeV2.node.ts
  packages/workflow/src/Expression.ts
  packages/workflow/src/Interfaces.ts
  packages/workflow/src/Workflow.ts
Labels: core, ui, n8n team, v1

#6518 feat: Add missing input panels to some trigger nodes
  packages/nodes-base/nodes/EmailReadImap/v1/EmailReadImapV1.node.ts
  packages/nodes-base/nodes/EmailReadImap/v2/EmailReadImapV2.node.ts
  packages/nodes-base/nodes/LocalFileTrigger/LocalFileTrigger.node.ts
  packages/nodes-base/nodes/MQTT/MqttTrigger.node.ts
  packages/nodes-base/nodes/Postgres/PostgresTrigger.node.ts
  packages/nodes-base/nodes/RabbitMQ/RabbitMQTrigger.node.ts
  packages/nodes-base/nodes/SseTrigger/SseTrigger.node.ts
Labels: node/improvement, n8n team

#6528 fix(core): Rename to credential_stubs and variable_stubs.json
  packages/cli/src/environments/sourceControl/constants.ts
Labels: core, n8n team

#6531 fix(Notion Node): Version fix
  packages/nodes-base/nodes/Notion/DatabaseDescription.ts
  packages/nodes-base/nodes/Notion/DatabasePageDescription.ts
  packages/nodes-base/nodes/Notion/GenericFunctions.ts
  packages/nodes-base/nodes/Notion/PageDescription.ts
  packages/nodes-base/nodes/Notion/v1/VersionDescription.ts
  packages/nodes-base/nodes/Notion/v2/NotionV2.node.ts
  packages/nodes-base/nodes/Notion/v2/VersionDescription.ts
Labels: n8n team, node/issue

#6525 fix(Google Sheets Node): Incorrect read of 0 and false
  packages/nodes-base/nodes/Google/Sheet/test/v2/utils/utils.test.ts
  packages/nodes-base/nodes/Google/Sheet/v2/helpers/GoogleSheets.utils.ts
Labels: n8n team, node/issue

#6527 fix(Google Drive Node): URL parsing
  packages/nodes-base/nodes/Google/Drive/GoogleDrive.node.ts
  packages/nodes-base/nodes/Google/Drive/GoogleDriveTrigger.node.ts
  packages/nodes-base/nodes/Google/Sheet/GoogleSheetsTrigger.node.ts
  packages/nodes-base/nodes/Google/Sheet/v2/actions/sheet/Sheet.resource.ts
  packages/nodes-base/nodes/Google/Sheet/v2/actions/spreadsheet/delete.operation.ts
Labels: n8n team, node/issue

#6532 fix(core): Add empty credential value marker to show empty pw field
  packages/cli/src/credentials/credentials.service.ts
  packages/editor-ui/src/components/ParameterInput.vue
  packages/workflow/src/Constants.ts
Labels: core, ui, n8n team

#6535 feat(editor): Ensure we use `v1.0.1` for `@n8n/codemirror-lang-sql` (no-changelog)
  packages/editor-ui/package.json
  pnpm-lock.yaml
Labels: ui, n8n team

#6489 fix: Minor grammar adjustments (no-changelog)
  CONTRIBUTING.md
  packages/node-dev/README.md
Labels: community

#6511 ci: Automate `no-changelog` removal in generated changelog (no-changelog)
  .github/scripts/package.json
  .github/scripts/update-changelog.mjs
  .github/workflows/release-create-pr.yml
Labels: n8n team

#6541 fix(editor): Change default branchColor and remove label
  packages/editor-ui/src/components/__tests__/MainSidebarSourceControl.test.ts
  packages/editor-ui/src/plugins/i18n/locales/en.json
  packages/editor-ui/src/stores/sourceControl.store.ts
  packages/editor-ui/src/views/SettingsSourceControl.vue
Labels: ui, n8n team

#6512 refactor: Remove triggers and actions experiment (no-changelog)
  cypress/e2e/4-node-creator.cy.ts
  cypress/pages/workflow.ts
  packages/editor-ui/src/components/Node/NodeCreator/Modes/ActionsMode.vue
  packages/editor-ui/src/constants.ts
Labels: ui, n8n team

#6536 feat(Matrix Node): Allow setting filename if the binary data has none
  packages/nodes-base/nodes/Matrix/GenericFunctions.ts
  packages/nodes-base/nodes/Matrix/MediaDescription.ts
Labels: node/improvement, n8n team

#6543 fix(editor): Add default author name and email to source control settings
  packages/editor-ui/src/stores/sourceControl.store.ts
Labels: ui, n8n team

#6539 refactor(editor): Update endpoint to retrieve limits (no-changelog)
  packages/editor-ui/src/api/cloudPlans.ts
Labels: ui, n8n team

#5941 feat(Google Drive Node): Overhaul
  packages/nodes-base/credentials/GoogleDriveOAuth2Api.credentials.ts
  packages/nodes-base/nodes/Google/Drive/GoogleDrive.node.ts
  packages/nodes-base/nodes/Google/Drive/GoogleDriveTrigger.node.ts
  packages/nodes-base/nodes/Google/Drive/test/v2/node/drive/create.test.ts
  packages/nodes-base/nodes/Google/Drive/test/v2/node/drive/deleteDrive.test.ts
  packages/nodes-base/nodes/Google/Drive/test/v2/node/drive/get.test.ts
  packages/nodes-base/nodes/Google/Drive/test/v2/node/drive/list.test.ts
  packages/nodes-base/nodes/Google/Drive/test/v2/node/drive/update.test.ts
  packages/nodes-base/nodes/Google/Drive/test/v2/node/file/copy.test.ts
  packages/nodes-base/nodes/Google/Drive/test/v2/node/file/createFromText.test.ts
  packages/nodes-base/nodes/Google/Drive/test/v2/node/file/deleteFile.test.ts
  packages/nodes-base/nodes/Google/Drive/test/v2/node/file/download.test.ts
  packages/nodes-base/nodes/Google/Drive/test/v2/node/file/move.test.ts
  packages/nodes-base/nodes/Google/Drive/test/v2/node/file/share.test.ts
  packages/nodes-base/nodes/Google/Drive/test/v2/node/file/update.test.ts
  packages/nodes-base/nodes/Google/Drive/test/v2/node/file/upload.test.ts
  packages/nodes-base/nodes/Google/Drive/test/v2/node/fileFolder/search.test.ts
  packages/nodes-base/nodes/Google/Drive/test/v2/node/folder/create.test.ts
  packages/nodes-base/nodes/Google/Drive/test/v2/node/folder/deleteFolder.test.ts
  packages/nodes-base/nodes/Google/Drive/test/v2/node/folder/share.test.ts
  packages/nodes-base/nodes/Google/Drive/test/v2/node/helpers.ts
  packages/nodes-base/nodes/Google/Drive/test/v2/utils.test.ts
  packages/nodes-base/nodes/Google/Drive/v1/GenericFunctions.ts
  packages/nodes-base/nodes/Google/Drive/v1/GoogleDriveV1.node.ts
  packages/nodes-base/nodes/Google/Drive/v1/SearchFunctions.ts
  packages/nodes-base/nodes/Google/Drive/v2/GoogleDriveV2.node.ts
  packages/nodes-base/nodes/Google/Drive/v2/actions/common.descriptions.ts
  packages/nodes-base/nodes/Google/Drive/v2/actions/drive/Drive.resource.ts
  packages/nodes-base/nodes/Google/Drive/v2/actions/drive/create.operation.ts
  packages/nodes-base/nodes/Google/Drive/v2/actions/drive/deleteDrive.operation.ts
  packages/nodes-base/nodes/Google/Drive/v2/actions/drive/get.operation.ts
  packages/nodes-base/nodes/Google/Drive/v2/actions/drive/list.operation.ts
  packages/nodes-base/nodes/Google/Drive/v2/actions/drive/update.operation.ts
  packages/nodes-base/nodes/Google/Drive/v2/actions/file/File.resource.ts
  packages/nodes-base/nodes/Google/Drive/v2/actions/file/copy.operation.ts
  packages/nodes-base/nodes/Google/Drive/v2/actions/file/createFromText.operation.ts
  packages/nodes-base/nodes/Google/Drive/v2/actions/file/deleteFile.operation.ts
  packages/nodes-base/nodes/Google/Drive/v2/actions/file/download.operation.ts
  packages/nodes-base/nodes/Google/Drive/v2/actions/file/move.operation.ts
  packages/nodes-base/nodes/Google/Drive/v2/actions/file/share.operation.ts
  packages/nodes-base/nodes/Google/Drive/v2/actions/file/update.operation.ts
  packages/nodes-base/nodes/Google/Drive/v2/actions/file/upload.operation.ts
  packages/nodes-base/nodes/Google/Drive/v2/actions/fileFolder/FileFolder.resource.ts
  packages/nodes-base/nodes/Google/Drive/v2/actions/fileFolder/search.operation.ts
  packages/nodes-base/nodes/Google/Drive/v2/actions/folder/Folder.resource.ts
  packages/nodes-base/nodes/Google/Drive/v2/actions/folder/create.operation.ts
  packages/nodes-base/nodes/Google/Drive/v2/actions/folder/deleteFolder.operation.ts
  packages/nodes-base/nodes/Google/Drive/v2/actions/folder/share.operation.ts
  packages/nodes-base/nodes/Google/Drive/v2/actions/node.type.ts
  packages/nodes-base/nodes/Google/Drive/v2/actions/router.ts
  packages/nodes-base/nodes/Google/Drive/v2/actions/versionDescription.ts
  packages/nodes-base/nodes/Google/Drive/v2/helpers/interfaces.ts
  packages/nodes-base/nodes/Google/Drive/v2/helpers/utils.ts
  packages/nodes-base/nodes/Google/Drive/v2/methods/index.ts
  packages/nodes-base/nodes/Google/Drive/v2/methods/listSearch.ts
  packages/nodes-base/nodes/Google/Drive/v2/transport/index.ts
Labels: node/improvement, n8n team

#6549 fix(editor): Update external secrets paywall
  packages/editor-ui/src/plugins/i18n/locales/en.json
  packages/editor-ui/src/stores/externalSecrets.ee.store.ts
  packages/editor-ui/src/views/SettingsExternalSecrets.vue
Labels: ui, n8n team

#6497 feat(editor): Prevent saving of workflow when canvas is loading
  cypress/e2e/7-workflow-actions.cy.ts
  cypress/pages/workflow.ts
  cypress/pages/workflows.ts
  packages/cli/src/api/e2e.api.ts
  packages/editor-ui/src/components/ExpressionEdit.vue
  packages/editor-ui/src/components/NodeCredentials.vue
  packages/editor-ui/src/components/RunData.vue
  packages/editor-ui/src/components/RunDataJsonActions.vue
  packages/editor-ui/src/mixins/genericHelpers.ts
  packages/editor-ui/src/mixins/workflowHelpers.ts
  packages/editor-ui/src/views/NodeView.vue
Labels: ui, n8n team

#6530 fix(Sendy Node): Fix issue with brand id not being sent
  packages/nodes-base/nodes/Sendy/Sendy.node.ts
Labels: node/improvement, community

#5757 feat(Microsoft To Do Node): Add an option to set a reminder when creating a task
  packages/nodes-base/nodes/Microsoft/ToDo/MicrosoftToDo.node.ts
  packages/nodes-base/nodes/Microsoft/ToDo/TaskDescription.ts
Labels: node/improvement, community

#6547 fix(core): Use owners file to export wf owners
  packages/cli/src/environments/sourceControl/constants.ts
  packages/cli/src/environments/sourceControl/sourceControl.service.ee.ts
  packages/cli/src/environments/sourceControl/sourceControlExport.service.ee.ts
  packages/cli/src/environments/sourceControl/sourceControlImport.service.ee.ts
  packages/cli/src/environments/sourceControl/types/exportableWorkflow.ts
  packages/cli/src/environments/sourceControl/types/sourceControlledFile.ts
Labels: core, n8n team

#4788 feat(Twitter Node): Node overhaul
  packages/@n8n/client-oauth2/src/CodeFlow.ts
  packages/@n8n/client-oauth2/src/CredentialsFlow.ts
  packages/nodes-base/credentials/TwitterOAuth1Api.credentials.ts
  packages/nodes-base/credentials/TwitterOAuth2Api.credentials.ts
  packages/nodes-base/nodes/Twitter/Twitter.node.json
  packages/nodes-base/nodes/Twitter/Twitter.node.ts
  packages/nodes-base/nodes/Twitter/V1/DirectMessageDescription.ts
  packages/nodes-base/nodes/Twitter/V1/GenericFunctions.ts
  packages/nodes-base/nodes/Twitter/V1/TweetDescription.ts
  packages/nodes-base/nodes/Twitter/V1/TweetInterface.ts
  packages/nodes-base/nodes/Twitter/V1/TwitterV1.node.ts
  packages/nodes-base/nodes/Twitter/V2/DirectMessageDescription.ts
  packages/nodes-base/nodes/Twitter/V2/GenericFunctions.ts
  packages/nodes-base/nodes/Twitter/V2/ListDescription.ts
  packages/nodes-base/nodes/Twitter/V2/TweetDescription.ts
  packages/nodes-base/nodes/Twitter/V2/TweetInterface.ts
  packages/nodes-base/nodes/Twitter/V2/TwitterV2.node.ts
  packages/nodes-base/nodes/Twitter/V2/UserDescription.ts
  packages/nodes-base/nodes/Twitter/test/Twitter.test.ts
  packages/nodes-base/nodes/Twitter/test/Workflow_Twitter_UnitTest.json
  packages/nodes-base/package.json
  packages/nodes-base/test/nodes/FakeCredentialsMap.ts
Labels: node/improvement, n8n team

#6533 feat: Add various source control improvements
  packages/design-system/src/components/N8nBadge/Badge.vue
  packages/editor-ui/src/Interface.ts
  packages/editor-ui/src/components/MainHeader/WorkflowDetails.vue
  packages/editor-ui/src/components/MainSidebarSourceControl.vue
  packages/editor-ui/src/components/Modals.vue
  packages/editor-ui/src/components/SourceControlPullModal.ee.vue
  packages/editor-ui/src/components/SourceControlPushModal.ee.vue
  packages/editor-ui/src/components/__tests__/MainSidebarSourceControl.test.ts
  packages/editor-ui/src/constants.ts
  packages/editor-ui/src/plugins/i18n/locales/en.json
  packages/editor-ui/src/stores/ui.store.ts
  packages/editor-ui/src/views/SettingsSourceControl.vue
Labels: ui, n8n team

#6558 docs: Add irreversible change warning for n8n@0.234.0 (no-changelog)
  packages/cli/BREAKING-CHANGES.md
Labels: core, n8n team

#6559 refactor: Update v1 banner confirm button copy
  packages/editor-ui/src/plugins/i18n/locales/en.json
Labels: ui, n8n team

#5798 feat(HTTP Request Node): New http request generic custom auth credential
  packages/nodes-base/credentials/HttpCustomAuth.credentials.ts
  packages/nodes-base/nodes/GraphQL/GraphQL.node.ts
  packages/nodes-base/nodes/HttpRequest/V3/HttpRequestV3.node.ts
  packages/nodes-base/package.json
Labels: node/improvement, n8n team

#6565 fix(XML Node): Fix issue with not returning valid data
  packages/nodes-base/nodes/Xml/Xml.node.ts
  packages/nodes-base/nodes/Xml/test/node/workflow.xml-valid-data.json
Labels: node/improvement, n8n team

#6521 fix(Brevo Node): Rename SendInBlue node to Brevo node
  packages/nodes-base/credentials/BrevoApi.credentials.ts
  packages/nodes-base/nodes/Brevo/AttributeDescription.ts
  packages/nodes-base/nodes/Brevo/Brevo.node.json
  packages/nodes-base/nodes/Brevo/Brevo.node.ts
  packages/nodes-base/nodes/Brevo/BrevoTrigger.node.json
  packages/nodes-base/nodes/Brevo/BrevoTrigger.node.ts
  packages/nodes-base/nodes/Brevo/ContactDescription.ts
  packages/nodes-base/nodes/Brevo/EmailDescription.ts
  packages/nodes-base/nodes/Brevo/GenericFunctions.ts
  packages/nodes-base/nodes/Brevo/SenderDescrition.ts
  packages/nodes-base/nodes/Brevo/brevo.svg
  packages/nodes-base/nodes/SendInBlue/sendinblue.svg
  packages/nodes-base/package.json
Labels: n8n team

#6572 fix(core): Route `/rest/workflows/new` correctly (no-changelog)
  packages/cli/src/workflows/workflows.controller.ee.ts
  packages/cli/test/integration/workflows.controller.ee.test.ts
Labels: core, n8n team

#5295 ci: Add Github Action to enforce template to issues
  .github/workflows/check-issue-template.yml
Labels: n8n team

#6571 fix(editor): Fix various element-plus styles
  packages/design-system/src/components/N8nButton/Button.vue
  packages/design-system/src/components/N8nSelect/Select.vue
  packages/design-system/src/css/checkbox.scss
  packages/design-system/src/css/dialog.scss
  packages/design-system/src/css/icon.scss
  packages/design-system/src/css/message-box.scss
  packages/design-system/src/css/notification.scss
  packages/design-system/src/css/select.scss
  packages/design-system/src/css/tag.scss
  packages/editor-ui/src/App.vue
  packages/editor-ui/src/components/Modal.vue
  packages/editor-ui/src/components/TagsDropdown.vue
  packages/editor-ui/src/components/forms/ResourceFiltersDropdown.vue
  packages/editor-ui/src/components/layouts/ResourcesListLayout.vue
  packages/editor-ui/src/n8n-theme.scss
  packages/editor-ui/src/views/CredentialsView.vue
Labels: ui, n8n team

#6578 fix(editor): Fix loading in production mode [Vue 3]
  package.json
  packages/editor-ui/package.json
  packages/editor-ui/vite.config.ts
  pnpm-lock.yaml
Labels: ui, n8n team
