Repository n8n-io/n8n, pull requests merged in 2023-09, with the labels that each got.

#7068 refactor(core): Remove slow LDAP query and unused telemetry event
  packages/cli/src/InternalHooks.ts
  packages/cli/src/Ldap/LdapSync.ee.ts
  packages/cli/src/Ldap/helpers.ts
Labels: core, n8n team

#7072 refactor(core): Remove unneeded call from `CreateWorkflowHistoryTable` migration (no-changelog)
  packages/cli/src/databases/migrations/common/1692967111175-CreateWorkflowHistoryTable.ts
Labels: core, n8n team

#7063 ci: Fix prettier auto-formatting (no-changelog)
  .github/scripts/check-tests.mjs
  .prettierignore
  .vscode/settings.default.json
  cypress/e2e/26-resource-locator.cy.ts
  cypress/e2e/27-two-factor-authentication.cy.ts
  cypress/e2e/28-debug.cy.ts
  cypress/e2e/28-resource-mapper.cy.ts
  cypress/e2e/5-ndv.cy.ts
  cypress/e2e/6-code-node.cy.ts
  cypress/pages/ndv.ts
  cypress/pages/settings-personal.ts
  cypress/pages/workflow.ts
  package.json
  packages/cli/BREAKING-CHANGES.md
  packages/cli/src/ActiveExecutions.ts
  packages/cli/src/Server.ts
  packages/cli/src/environments/sourceControl/sourceControl.controller.ee.ts
  packages/cli/src/executions/executions.service.ts
  packages/design-system/src/utils/__tests__/event-bus.spec.ts
  packages/editor-ui/package.json
  packages/editor-ui/src/views/NodeView.vue
  pnpm-lock.yaml
Labels: core, ui, n8n team

#7066 fix(core): Prevent bots from scanning the application (no-changelog)
  packages/cli/package.json
  packages/cli/src/AbstractServer.ts
  packages/nodes-base/package.json
  pnpm-lock.yaml
Labels: core, n8n team

#6973 refactor: Move community package logic to service (no-changelog)
  packages/cli/src/CommunityNodes/helpers.ts
  packages/cli/src/CommunityNodes/packageModel.ts
  packages/cli/src/LoadNodesAndCredentials.ts
  packages/cli/src/audit/risks/nodes.risk.ts
  packages/cli/src/commands/start.ts
  packages/cli/src/controllers/nodes.controller.ts
  packages/cli/src/databases/repositories/installedPackages.repository.ts
  packages/cli/src/services/communityPackage.service.ts
  packages/cli/test/integration/audit/nodes.risk.test.ts
  packages/cli/test/integration/nodes.api.test.ts
  packages/cli/test/integration/shared/testDb.ts
  packages/cli/test/integration/shared/types.ts
  packages/cli/test/integration/shared/utils/communityNodes.ts
  packages/cli/test/unit/CommunityNodeHelpers.test.ts
  packages/cli/test/unit/services/communityPackage.service.test.ts
Labels: core, n8n team

#7073 refactor(core): Add `addColumns` and `dropColumns` to the migrations DSL (no-changelog)
  packages/cli/package.json
  packages/cli/src/databases/dsl/Column.ts
  packages/cli/src/databases/dsl/Table.ts
  packages/cli/src/databases/dsl/index.ts
  packages/cli/src/databases/migrations/common/1690000000030-RemoveResetPasswordColumns.ts
  packages/cli/src/databases/migrations/common/1690000000040-AddMfaColumns.ts
  pnpm-lock.yaml
Labels: core, n8n team

#7075 chore(core): Langchain package linting fixes
  packages/@n8n/nodes-langchain/.eslintrc.js
  packages/@n8n/nodes-langchain/nodes/agents/ConversationalAgent/ConversationalAgent.node.ts
  packages/@n8n/nodes-langchain/nodes/chains/ChainLLM/ChainLlm.node.ts
  packages/@n8n/nodes-langchain/nodes/chains/ChainRetrievalQA/ChainRetrievalQa.node.ts
  packages/@n8n/nodes-langchain/nodes/chains/ChainStructuredOutput/ChainStructuredOutput.node.ts
  packages/@n8n/nodes-langchain/nodes/chains/ChainSummarization/ChainSummarization.node.ts
  packages/@n8n/nodes-langchain/nodes/chains/ChainVectorStoreQA/ChainVectorStoreQa.node.ts
  packages/@n8n/nodes-langchain/nodes/document_loaders/DocumentBinaryInputLoader/DocumentBinaryInputLoader.node.ts
  packages/@n8n/nodes-langchain/nodes/document_loaders/DocumentGithubLoader/DocumentGithubLoader.node.ts
  packages/@n8n/nodes-langchain/nodes/document_loaders/DocumentJSONInputLoader/DocumentJSONInputLoader.node.ts
  packages/@n8n/nodes-langchain/nodes/document_loaders/DocumentJSONInputLoader/DocumentJsonInputLoader.node.ts
  packages/@n8n/nodes-langchain/nodes/embeddings/EmbeddingsOpenAI/EmbeddingsOpenAi.node.ts
  packages/@n8n/nodes-langchain/nodes/llms/LMChatOpenAi/LmChatOpenAi.node.ts
  packages/@n8n/nodes-langchain/nodes/llms/LMCohere/LmCohere.node.ts
  packages/@n8n/nodes-langchain/nodes/llms/LMOpenAi/LmOpenAi.node.ts
  packages/@n8n/nodes-langchain/nodes/llms/LMOpenHuggingFaceInference/LmOpenHuggingFaceInference.node.ts
  packages/@n8n/nodes-langchain/nodes/memory/MemoryBufferWindow/MemoryBufferWindow.node.ts
  packages/@n8n/nodes-langchain/nodes/memory/MemoryXata/MemoryXata.node.ts
  packages/@n8n/nodes-langchain/nodes/memory/MemoryXata/xata.png
  packages/@n8n/nodes-langchain/nodes/memory/MemoryXata/xata.svg
  packages/@n8n/nodes-langchain/nodes/retrievers/RetrieverVectorStore/RetrieverVectorStore.node.ts
  packages/@n8n/nodes-langchain/nodes/text_splitters/TextSplitterCharacterTextSplitter/TextSplitterCharacterTextSplitter.node.ts
  packages/@n8n/nodes-langchain/nodes/text_splitters/TextSplitterRecursiveCharacterTextSplitter/TextSplitterRecursiveCharacterTextSplitter.node.ts
  packages/@n8n/nodes-langchain/nodes/tools/ToolCode/ToolCode.node.ts
  packages/@n8n/nodes-langchain/nodes/tools/ToolSerpApi/ToolSerpApi.node.ts
  packages/@n8n/nodes-langchain/nodes/tools/ToolWolframAlpha/ToolWolframAlpha.node.ts
  packages/@n8n/nodes-langchain/nodes/tools/ToolWolframAlpha/wolfram-alpha.png
  packages/@n8n/nodes-langchain/nodes/tools/ToolWolframAlpha/wolfram-alpha.svg
  packages/@n8n/nodes-langchain/nodes/tools/ToolWorkflow/ToolWorkflow.node.ts
  packages/@n8n/nodes-langchain/nodes/vector_store/InMemoryVectorStore/InMemoryVectorStore.node.ts
  packages/@n8n/nodes-langchain/nodes/vector_store/VectorStorePineconeInsert/VectorStorePineconeInsert.node.ts
  packages/@n8n/nodes-langchain/nodes/vector_store/VectorStorePineconeInsert/pinecone.png
  packages/@n8n/nodes-langchain/nodes/vector_store/VectorStorePineconeInsert/pinecone.svg
  packages/@n8n/nodes-langchain/nodes/vector_store/VectorStorePineconeLoad/VectorStorePineconeLoad.node.ts
  packages/@n8n/nodes-langchain/nodes/vector_store/VectorStorePineconeLoad/pinecone.png
  packages/@n8n/nodes-langchain/nodes/vector_store/VectorStorePineconeLoad/pinecone.svg
  packages/@n8n/nodes-langchain/package.json
  packages/@n8n/nodes-langchain/tsconfig.json
  packages/@n8n/nodes-langchain/tslint.json
  packages/@n8n/nodes-langchain/utils/EpubLoader.ts
  packages/@n8n/nodes-langchain/utils/N8nBinaryLoader.ts
  packages/@n8n/nodes-langchain/utils/N8nJsonLoader.ts
  packages/@n8n/nodes-langchain/utils/logWrapper.ts
  pnpm-lock.yaml
Labels: n8n team

#7076 ci: Fix lint to fix build
  packages/cli/src/controllers/nodes.controller.ts
Labels: core, n8n team, skip-e2e

#7074 fix(Postgres Node): Connection pool of the database object has been destroyed
  packages/nodes-base/nodes/Postgres/test/v2/operations.test.ts
  packages/nodes-base/nodes/Postgres/v2/actions/database/insert.operation.ts
  packages/nodes-base/nodes/Postgres/v2/actions/database/update.operation.ts
  packages/nodes-base/nodes/Postgres/v2/actions/database/upsert.operation.ts
  packages/nodes-base/nodes/Postgres/v2/actions/router.ts
  packages/nodes-base/nodes/Postgres/v2/helpers/interfaces.ts
  packages/nodes-base/nodes/Postgres/v2/helpers/utils.ts
  packages/nodes-base/nodes/Postgres/v2/methods/listSearch.ts
  packages/nodes-base/nodes/Postgres/v2/methods/loadOptions.ts
  packages/nodes-base/nodes/Postgres/v2/methods/resourceMapping.ts
Labels: n8n team, node/issue

#7028 refactor(core): Consolidate `CredentialsService.getMany()` (no-changelog)
  packages/cli/src/WorkflowHelpers.ts
  packages/cli/src/credentials/credentials.controller.ee.ts
  packages/cli/src/credentials/credentials.controller.ts
  packages/cli/src/credentials/credentials.service.ee.ts
  packages/cli/src/credentials/credentials.service.ts
  packages/cli/src/credentials/credentials.types.ts
  packages/cli/src/requests.ts
  packages/cli/src/services/ownership.service.ts
  packages/cli/src/workflows/workflows.controller.ee.ts
  packages/cli/src/workflows/workflows.services.ee.ts
  packages/cli/test/integration/credentials.ee.test.ts
  packages/cli/test/integration/credentials.test.ts
  packages/cli/test/unit/services/ownership.service.test.ts
Labels: core, n8n team

#7060 docs(Strapi Node): Update Strapi.node.json with correct credentials URL
  packages/nodes-base/nodes/Strapi/Strapi.node.json
Labels: node/improvement, n8n team

#7087 fix(Postgres Node): Tunnel doesn't always close
  packages/nodes-base/nodes/Postgres/v2/actions/database/insert.operation.ts
  packages/nodes-base/nodes/Postgres/v2/actions/database/update.operation.ts
  packages/nodes-base/nodes/Postgres/v2/actions/database/upsert.operation.ts
  packages/nodes-base/nodes/Postgres/v2/methods/resourceMapping.ts
Labels: n8n team, node/issue

#7089 feat(editor): Add Log view also to Chat
  packages/editor-ui/src/components/RunData.vue
  packages/editor-ui/src/components/RunDataAi.vue
  packages/editor-ui/src/components/WorkflowLMChat.vue
  packages/editor-ui/src/plugins/i18n/locales/en.json
Labels: ui, n8n team

#7088 feat(core): Migration for soft deletions for executions
  packages/cli/src/databases/entities/ExecutionEntity.ts
  packages/cli/src/databases/migrations/common/1693491613982-ExecutionSoftDelete.ts
  packages/cli/src/databases/migrations/mysqldb/index.ts
  packages/cli/src/databases/migrations/postgresdb/index.ts
  packages/cli/src/databases/migrations/sqlite/1693491613982-ExecutionSoftDelete.ts
  packages/cli/src/databases/migrations/sqlite/index.ts
Labels: core, n8n team

#7041 feat(core): Add list query middleware to credentials
  packages/cli/src/WorkflowHelpers.ts
  packages/cli/src/credentials/credentials.controller.ts
  packages/cli/src/credentials/credentials.service.ts
  packages/cli/src/middlewares/listQuery/dtos/credentials.filter.dto.ts
  packages/cli/src/middlewares/listQuery/dtos/credentials.select.dto.ts
  packages/cli/src/middlewares/listQuery/filter.ts
  packages/cli/src/middlewares/listQuery/select.ts
  packages/cli/src/workflows/workflows.services.ee.ts
  packages/cli/test/integration/credentials.controller.test.ts
Labels: core, n8n team

#7090 feat(core): Add support for floating licenses
  packages/cli/package.json
  packages/cli/src/License.ts
  packages/cli/src/commands/start.ts
  pnpm-lock.yaml
Labels: core, n8n team

#7093 fix(editor): Standardize save text
  packages/editor-ui/src/components/WorkflowSettings.vue
  packages/editor-ui/src/plugins/i18n/locales/en.json
Labels: ui, n8n team

#7099 ci: Fix linting (no-changelog)
  packages/cli/src/workflows/workflows.services.ee.ts
Labels: core, n8n team

#7096 refactor(core): Disable slow-query log by default (no-changelog)
  packages/cli/src/config/schema.ts
Labels: core, n8n team

#7097 refactor(core): Add an option to use simple recovery process by default
  packages/cli/src/config/schema.ts
  packages/cli/src/databases/repositories/execution.repository.ts
  packages/cli/src/eventbus/MessageEventBus/MessageEventBus.ts
Labels: core, n8n team

#7105 fix(editor): Add @lezer/common to deps
  packages/editor-ui/package.json
  pnpm-lock.yaml
Labels: ui, n8n team

#7103 refactor(core): Set up `ExecutionMetadata` service (no-changelog)
  packages/cli/src/WorkflowExecuteAdditionalData.ts
  packages/cli/src/services/executionMetadata.service.ts
  packages/cli/test/unit/WorkflowExecuteAdditionalData.test.ts
Labels: core, n8n team

#7102 ci: Test Postgres and MySQL on migration PRs (no-changelog)
  .github/workflows/ci-postgres-mysql.yml
Labels: n8n team

#7101 fix: Change the name for checking issue template content (no-changelog)
  .github/workflows/check-issue-template.yml
Labels: n8n team

#7107 fix(core): Split event bus controller into community and ee
  packages/cli/src/Server.ts
  packages/cli/src/eventbus/eventBus.controller.ee.ts
  packages/cli/src/eventbus/eventBus.controller.ts
  packages/cli/src/eventbus/middleware/logStreamingEnabled.middleware.ee.ts
  packages/cli/test/integration/eventbus.ee.test.ts
  packages/cli/test/integration/eventbus.test.ts
  packages/cli/test/integration/shared/utils/testServer.ts
Labels: core, n8n team

#7104 refactor(core): Move static data handling to workflow service (no-changelog)
  packages/cli/src/ActiveWorkflowRunner.ts
  packages/cli/src/WebhookHelpers.ts
  packages/cli/src/WorkflowExecuteAdditionalData.ts
  packages/cli/src/WorkflowHelpers.ts
  packages/cli/src/workflows/workflows.services.ts
Labels: core, n8n team

#7110 ci: Fix linting (no-changelog)
  packages/cli/test/integration/shared/utils/index.ts
Labels: core, n8n team

#7111 fix(core): Lazy-load express-openapi-validator to reduce initial memory spike (no-changelog)
  packages/cli/src/PublicApi/index.ts
Labels: core, n8n team

#7114 fix(editor): Fix connection retrieval by taking the connection scope into account
  packages/editor-ui/src/components/Node.vue
  packages/editor-ui/src/views/NodeView.vue
Labels: ui, n8n team

#7047 fix(core): Add support for in-transit encryption (TLS) on Redis connections
  packages/cli/src/config/schema.ts
  packages/cli/src/services/redis/RedisServiceHelper.ts
Labels: core, n8n team

#7115 refactor: Use actual nodes/credentials in cli and core tests (no-changelog)
  packages/cli/test/integration/publicApi/credentials.test.ts
  packages/cli/test/integration/shared/utils/index.ts
  packages/core/package.json
  packages/core/test/helpers/constants.ts
  pnpm-lock.yaml
Labels: core, n8n team

#7095 refactor(Spreadsheet File Node): Reduce memory usage when loading CSV files
  packages/nodes-base/nodes/SpreadsheetFile/SpreadsheetFile.node.ts
  packages/nodes-base/nodes/SpreadsheetFile/description.ts
  packages/nodes-base/nodes/SpreadsheetFile/v1/SpreadsheetFileV1.node.ts
  packages/nodes-base/nodes/SpreadsheetFile/v2/SpreadsheetFileV2.node.ts
  packages/nodes-base/package.json
  packages/nodes-base/utils/utilities.ts
  pnpm-lock.yaml
Labels: node/improvement, n8n team

#7071 feat: Add workflow history repository files
  packages/cli/src/Db.ts
  packages/cli/src/Interfaces.ts
  packages/cli/src/databases/entities/WorkflowHistory.ts
  packages/cli/src/databases/entities/index.ts
  packages/cli/src/databases/repositories/index.ts
  packages/cli/src/databases/repositories/workflowHistory.repository.ts
  packages/cli/src/workflows/workflowHistory/workflowHistoryService.ee.ts
Labels: core, n8n team

#7032 feat(HTTP Request Node): Determine binary file name from content-disposition headers
  packages/cli/package.json
  packages/cli/src/middlewares/bodyParser.ts
  packages/core/package.json
  packages/core/src/NodeExecuteFunctions.ts
  packages/nodes-base/nodes/HttpRequest/V1/HttpRequestV1.node.ts
  packages/nodes-base/nodes/HttpRequest/V2/HttpRequestV2.node.ts
  packages/nodes-base/nodes/HttpRequest/V3/HttpRequestV3.node.ts
  packages/nodes-base/nodes/HttpRequest/test/binaryData/HttpRequest.test.ts
  packages/nodes-base/nodes/HttpRequest/test/binaryData/binaryData.test.json
  packages/workflow/src/index.ts
  pnpm-lock.yaml
Labels: node/improvement, core, n8n team

#7122 fix(Code Node): Disable WASM to address CVE-2023-37903
  packages/nodes-base/nodes/Code/JavaScriptSandbox.ts
Labels: node/improvement, n8n team

#7124 docs: Docs links for TheHive and TheHive5
  packages/nodes-base/nodes/TheHive/TheHive.node.json
  packages/nodes-base/nodes/TheHiveProject/TheHiveProject.node.json
  packages/nodes-base/nodes/TheHiveProject/TheHiveProjectTrigger.node.json
Labels: node/improvement, n8n team

#7030 feat(Salesforce Node): Add fax field to lead option
  packages/nodes-base/nodes/Salesforce/LeadDescription.ts
  packages/nodes-base/nodes/Salesforce/LeadInterface.ts
  packages/nodes-base/nodes/Salesforce/Salesforce.node.ts
Labels: node/improvement, community

#7125 fix(core): Disable Node.js custom inspection to address CVE-2023-37903
  packages/cli/bin/n8n
Labels: core, n8n team

#7127 docs: Add email alias to Outlook and GMail
  packages/nodes-base/nodes/Google/Gmail/Gmail.node.json
  packages/nodes-base/nodes/Microsoft/Outlook/MicrosoftOutlook.node.json
Labels: node/improvement, n8n team

#7123 fix(Code Node): Upgrade vm2 to address CVE-2023-37466
  packages/nodes-base/package.json
  pnpm-lock.yaml
Labels: node/improvement, n8n team

#7029 feat(core): Add commands to workers to respond with current state
  packages/cli/src/AbstractServer.ts
  packages/cli/src/Server.ts
  packages/cli/src/commands/BaseCommand.ts
  packages/cli/src/commands/worker.ts
  packages/cli/src/commands/workerCommandHandler.ts
  packages/cli/src/controllers/orchestration.controller.ts
  packages/cli/src/eventbus/EventMessageClasses/index.ts
  packages/cli/src/eventbus/MessageEventBus/MessageEventBus.ts
  packages/cli/src/requests.ts
  packages/cli/src/services/orchestration.service.ts
  packages/cli/src/services/redis/RedisServiceCommands.ts
  packages/cli/src/services/redis/RedisServicePubSubSubscriber.ts
  packages/cli/test/integration/commands/worker.cmd.test.ts
  packages/cli/test/unit/services/orchestration.service.test.ts
Labels: core, n8n team

#7131 refactor(core): Use a Set for `deletedProperties` in `AugmentObject` (no-changelog)
  packages/workflow/src/AugmentObject.ts
Labels: core, n8n team

#7118 feat(core): Add an option to enable WAL mode for SQLite
  packages/cli/src/config/schema.ts
  packages/cli/src/databases/config.ts
  packages/cli/test/integration/shared/testDb.ts
Labels: core, n8n team

#7132 feat(core): Add Chat Memory Retriever
  packages/@n8n/nodes-langchain/nodes/memory/MemoryChatRetriever/MemoryChatRetriever.node.ts
  packages/@n8n/nodes-langchain/package.json
Labels: n8n team

#7133 docs: Add concatenate alias to Split in Batches
  packages/nodes-base/nodes/SplitInBatches/SplitInBatches.node.json
Labels: node/improvement, n8n team

#7140 feat(core): Add SqlAgent node
  packages/@n8n/nodes-langchain/nodes/agents/SqlAgent/SqlAgent.node.ts
  packages/@n8n/nodes-langchain/nodes/agents/SqlAgent/handlers/mysql.ts
  packages/@n8n/nodes-langchain/nodes/agents/SqlAgent/handlers/postgres.ts
  packages/@n8n/nodes-langchain/nodes/agents/SqlAgent/handlers/sqlite.ts
  packages/@n8n/nodes-langchain/nodes/agents/SqlAgent/prompts.ts
  packages/@n8n/nodes-langchain/nodes/chains/ChainStructuredOutput/ChainStructuredOutput.node.ts
  packages/@n8n/nodes-langchain/package.json
  pnpm-lock.yaml
Labels: n8n team

#6959 fix(Zoho CRM Node): Fix issue with Sales Order not updating
  packages/nodes-base/nodes/Zoho/GenericFunctions.ts
  packages/nodes-base/nodes/Zoho/ZohoCrm.node.ts
Labels: node/improvement, n8n team

#7151 fix(editor): Update git repo url validation regex
  packages/editor-ui/src/views/SettingsSourceControl.vue
  packages/editor-ui/src/views/__tests__/SettingsSourceControl.test.ts
Labels: ui, n8n team

#7150 docs(editor): Update .round() function in NumberExtensions.ts for clarity
  packages/workflow/src/Extensions/NumberExtensions.ts
Labels: core, n8n team

#7136 fix(Google Cloud Firestore Node): Fix empty string interpreted as number
  packages/nodes-base/nodes/Google/Firebase/CloudFirestore/GenericFunctions.ts
Labels: node/improvement, community

#5582 fix(HubSpot Node): Fix issue with contact lists not working
  packages/nodes-base/credentials/HubspotOAuth2Api.credentials.ts
  packages/nodes-base/nodes/Hubspot/V2/ContactListDescription.ts
  packages/nodes-base/nodes/Hubspot/V2/HubspotV2.node.ts
Labels: node/improvement, n8n team

#7153 fix(core): Ignore missing user-agent on bot check (no-changelog)
  packages/cli/src/AbstractServer.ts
Labels: core, n8n team

#7129 fix(editor): Rebind endpoint events when component activated
  cypress/e2e/7-workflow-actions.cy.ts
  packages/editor-ui/src/views/NodeView.vue
Labels: ui, n8n team

#7094 fix: Account for nanoid workflow ids for subworkflow execute policy
  packages/editor-ui/src/components/WorkflowSettings.vue
  packages/editor-ui/src/components/__tests__/WorkflowSettings.spec.ts
  packages/editor-ui/src/composables/useExternalHooks.ts
Labels: ui, n8n team

#7108 fix(editor): Tweak hover area of workflow / cred cards
  packages/design-system/src/components/N8nCard/Card.vue
  packages/editor-ui/src/components/CredentialCard.vue
  packages/editor-ui/src/components/SettingsLogStreaming/EventDestinationCard.ee.vue
  packages/editor-ui/src/components/WorkflowCard.vue
Labels: ui, n8n team

#7159 ci: Add reusable unit test workflow (no-changelog)
  .github/workflows/ci-master.yml
  .github/workflows/ci-pull-requests.yml
  .github/workflows/units-tests-dispatch.yml
  .github/workflows/units-tests-reusable.yml
Labels: n8n team

#7163 fix(editor): Prevent duplicate creation of credential for OAuth2
  packages/editor-ui/src/components/CredentialEdit/GoogleAuthButton.vue
  packages/editor-ui/src/components/CredentialEdit/OauthButton.vue
Labels: ui, n8n team

#7138 refactor(core): Move event and telemetry handling into workers in queue mode
  packages/cli/src/ActiveExecutions.ts
  packages/cli/src/InternalHooks.ts
  packages/cli/src/Queue.ts
  packages/cli/src/WebhookHelpers.ts
  packages/cli/src/WorkflowExecuteAdditionalData.ts
  packages/cli/src/WorkflowRunner.ts
  packages/cli/src/commands/worker.ts
  packages/cli/src/eventbus/EventMessageClasses/EventMessageWorkflow.ts
  packages/cli/src/executionLifecycleHooks/shared/sharedHookFunctions.ts
  packages/cli/src/worker/workerCommandHandler.ts
Labels: core, n8n team

#7152 feat(core): Add support for Supabase Vector Store
  packages/@n8n/nodes-langchain/nodes/vector_store/VectorStoreSupabaseInsert/VectorStoreSupabaseInsert.node.ts
  packages/@n8n/nodes-langchain/nodes/vector_store/VectorStoreSupabaseInsert/supabase.svg
  packages/@n8n/nodes-langchain/nodes/vector_store/VectorStoreSupabaseLoad/VectorStoreSupabaseLoad.node.ts
  packages/@n8n/nodes-langchain/nodes/vector_store/VectorStoreSupabaseLoad/supabase.svg
  packages/@n8n/nodes-langchain/package.json
  pnpm-lock.yaml
Labels: n8n team

#7165 fix(editor): Testing flaky resource mapper feature in e2e tests
  cypress/e2e/28-resource-mapper.cy.ts
  cypress/pages/ndv.ts
  packages/editor-ui/src/components/ParameterInputWrapper.vue
  packages/editor-ui/src/components/ResourceMapper/MappingFields.vue
  packages/editor-ui/src/components/__tests__/ResourceMapper.test.ts
  packages/nodes-base/nodes/E2eTest/E2eTest.node.ts
  packages/nodes-base/nodes/E2eTest/mock.ts
Labels: node/improvement, ui, n8n team

#7154 feat(core): Add rsa option to ssh key generation
  packages/cli/src/config/schema.ts
  packages/cli/src/environments/sourceControl/sourceControl.controller.ee.ts
  packages/cli/src/environments/sourceControl/sourceControlHelper.ee.ts
  packages/cli/src/environments/sourceControl/sourceControlPreferences.service.ee.ts
  packages/cli/src/environments/sourceControl/types/keyPairType.ts
  packages/cli/src/environments/sourceControl/types/requests.ts
  packages/cli/src/environments/sourceControl/types/sourceControlGenerateKeyPair.ts
  packages/cli/src/environments/sourceControl/types/sourceControlPreferences.ts
  packages/cli/test/integration/environments/SourceControl.test.ts
  packages/cli/test/unit/SourceControl.test.ts
Labels: core, n8n team

#7172 fix(editor): Add ssh key type selection to source control settings when regenerating key
  packages/editor-ui/src/Interface.ts
  packages/editor-ui/src/__tests__/server/endpoints/sourceControl.ts
  packages/editor-ui/src/api/sourceControl.ts
  packages/editor-ui/src/stores/sourceControl.store.ts
  packages/editor-ui/src/utils/typeHelpers.ts
  packages/editor-ui/src/views/SettingsSourceControl.vue
  packages/editor-ui/src/views/__tests__/SettingsSourceControl.test.ts
Labels: ui, n8n team

#7167 feat(editor): Implement AI tree-execution view
  packages/@n8n/nodes-langchain/nodes/agents/ConversationalAgent/ConversationalAgent.node.ts
  packages/@n8n/nodes-langchain/utils/logWrapper.ts
  packages/editor-ui/src/Interface.ts
  packages/editor-ui/src/components/Node.vue
  packages/editor-ui/src/components/Node/NodeCreator/Modes/NodesMode.vue
  packages/editor-ui/src/components/NodeExecuteButton.vue
  packages/editor-ui/src/components/OutputPanel.vue
  packages/editor-ui/src/components/RunData.vue
  packages/editor-ui/src/components/RunDataAi.vue
  packages/editor-ui/src/components/RunDataAi/AiRunContentBlock.vue
  packages/editor-ui/src/components/RunDataAi/RunDataAi.vue
  packages/editor-ui/src/components/RunDataAi/RunDataAiContent.vue
  packages/editor-ui/src/components/RunDataAi/useAiContentParsers.ts
  packages/editor-ui/src/components/RunDataAiContent.vue
  packages/editor-ui/src/components/WorkflowLMChat.vue
  packages/editor-ui/src/plugins/i18n/locales/en.json
Labels: ui, n8n team

#7175 ci: Remove eslint diff plugin. Run full linting on PRs (no-changelog)
  .github/workflows/ci-pull-requests.yml
  packages/@n8n_io/eslint-config/base.js
  packages/@n8n_io/eslint-config/package.json
  packages/editor-ui/src/components/__tests__/ResourceMapper.test.ts
  pnpm-lock.yaml
Labels: ui, n8n team

#7148 feat(editor): Restyle supplemental connectors
  packages/@n8n/nodes-langchain/nodes/agents/ConversationalAgent/ConversationalAgent.node.ts
  packages/@n8n/nodes-langchain/nodes/agents/SqlAgent/SqlAgent.node.ts
  packages/@n8n/nodes-langchain/nodes/chains/ChainLLM/ChainLlm.node.ts
  packages/@n8n/nodes-langchain/nodes/chains/ChainRetrievalQA/ChainRetrievalQa.node.ts
  packages/@n8n/nodes-langchain/nodes/chains/ChainStructuredOutput/ChainStructuredOutput.node.ts
  packages/@n8n/nodes-langchain/nodes/chains/ChainSummarization/ChainSummarization.node.ts
  packages/@n8n/nodes-langchain/nodes/chains/ChainVectorStoreQA/ChainVectorStoreQa.node.ts
  packages/@n8n/nodes-langchain/nodes/output_parser/OutputParserAutofixing/OutputParserAutofixing.node.ts
  packages/design-system/src/components/N8nNodeIcon/NodeIcon.vue
  packages/editor-ui/src/Interface.ts
  packages/editor-ui/src/components/Node.vue
  packages/editor-ui/src/components/Node/NodeCreator/ItemTypes/SubcategoryItem.vue
  packages/editor-ui/src/components/Node/NodeCreator/Modes/NodesMode.vue
  packages/editor-ui/src/components/Node/NodeCreator/Panel/NodesListPanel.vue
  packages/editor-ui/src/components/Node/NodeCreator/composables/useViewStacks.ts
  packages/editor-ui/src/components/Node/NodeCreator/viewsData.ts
  packages/editor-ui/src/components/RunDataAi/AiRunContentBlock.vue
  packages/editor-ui/src/components/RunDataAi/RunDataAi.vue
  packages/editor-ui/src/components/RunDataAi/RunDataAiContent.vue
  packages/editor-ui/src/components/RunDataAi/useAiContentParsers.ts
  packages/editor-ui/src/constants.ts
  packages/editor-ui/src/mixins/nodeBase.ts
  packages/editor-ui/src/n8n-theme-variables.scss
  packages/editor-ui/src/n8n-theme.scss
  packages/editor-ui/src/plugins/i18n/locales/en.json
  packages/editor-ui/src/plugins/jsplumb/N8nAddInputEndpointRenderer.ts
  packages/editor-ui/src/plugins/jsplumb/N8nAddInputEndpointType.ts
  packages/editor-ui/src/utils/htmlUtils.ts
  packages/editor-ui/src/utils/nodeViewUtils.ts
  packages/editor-ui/src/views/NodeView.vue
Labels: ui, n8n team

#7182 fix(editor): No need to add click emitting click events, VUE delegates the handler to the root element of the component
  packages/editor-ui/src/components/CredentialEdit/OauthButton.vue
  packages/editor-ui/src/components/CredentialEdit/__tests__/OauthButton.test.ts
Labels: ui, n8n team

#7106 ci: Disable intermittently failing MFA e2e tests (no-changelog)
  cypress/e2e/27-two-factor-authentication.cy.ts
Labels: n8n team

#7161 feat(editor): Add Workflow history route and base page (no-changelog)
  packages/cli/src/Server.ts
  packages/editor-ui/src/constants.ts
  packages/editor-ui/src/plugins/i18n/locales/en.json
  packages/editor-ui/src/router.ts
  packages/editor-ui/src/views/WorkflowHistory.vue
  packages/workflow/src/Interfaces.ts
Labels: core, ui, n8n team

#7179 fix(X (Formerly Twitter) Node): Rename Twitter to X (keep Twitter alias)
  packages/nodes-base/credentials/TwitterOAuth1Api.credentials.ts
  packages/nodes-base/credentials/TwitterOAuth2Api.credentials.ts
  packages/nodes-base/nodes/Twitter/Twitter.node.json
  packages/nodes-base/nodes/Twitter/Twitter.node.ts
  packages/nodes-base/nodes/Twitter/V2/TwitterV2.node.ts
  packages/nodes-base/nodes/Twitter/twitter.svg
  packages/nodes-base/nodes/Twitter/x.svg
Labels: node/improvement, n8n team

#7184 feat(core): Add command to trigger license refresh on workers
  packages/cli/package.json
  packages/cli/src/License.ts
  packages/cli/src/Server.ts
  packages/cli/src/commands/BaseCommand.ts
  packages/cli/src/commands/start.ts
  packages/cli/src/commands/webhook.ts
  packages/cli/src/commands/worker.ts
  packages/cli/src/controllers/e2e.controller.ts
  packages/cli/src/controllers/orchestration.controller.ts
  packages/cli/src/eventbus/MessageEventBus/MessageEventBus.ts
  packages/cli/src/services/orchestration.service.ts
  packages/cli/src/services/orchestration/handleCommandMessage.ts
  packages/cli/src/services/orchestration/handleWorkerResponseMessage.ts
  packages/cli/src/services/orchestration/helpers.ts
  packages/cli/src/services/redis/RedisServiceBaseClasses.ts
  packages/cli/src/services/redis/RedisServiceCommands.ts
  packages/cli/src/services/redis/RedisServicePubSubSubscriber.ts
  packages/cli/src/worker/workerCommandHandler.ts
  packages/cli/test/integration/eventbus.ee.test.ts
  packages/cli/test/unit/License.test.ts
  packages/cli/test/unit/services/orchestration.service.test.ts
  pnpm-lock.yaml
Labels: core, n8n team

#7155 feat: AI tool creation custom node
  packages/@n8n/nodes-langchain/nodes/code/Code.node.ts
  packages/@n8n/nodes-langchain/nodes/tools/ToolCode/ToolCode.node.ts
  packages/@n8n/nodes-langchain/package.json
  packages/cli/src/config/schema.ts
  packages/core/src/NodeExecuteFunctions.ts
  packages/editor-ui/src/components/InputPanel.vue
  packages/editor-ui/src/components/Node.vue
  packages/editor-ui/src/components/NodeDetailsView.vue
  packages/editor-ui/src/components/RunData.vue
  packages/editor-ui/src/components/WorkflowLMChat.vue
  packages/editor-ui/src/constants.ts
  packages/editor-ui/src/mixins/nodeBase.ts
  packages/editor-ui/src/mixins/nodeHelpers.ts
  packages/editor-ui/src/mixins/workflowHelpers.ts
  packages/editor-ui/src/stores/nodeTypes.store.ts
  packages/editor-ui/src/views/NodeView.vue
  packages/nodes-base/nodes/Code/JavaScriptSandbox.ts
  packages/nodes-base/nodes/Code/PythonSandbox.ts
  packages/nodes-base/nodes/Code/Sandbox.ts
  packages/workflow/src/ExpressionEvaluatorProxy.ts
  packages/workflow/src/Interfaces.ts
  packages/workflow/src/NodeHelpers.ts
  pnpm-lock.yaml
Labels: core, ui, n8n team

#7194 fix(Spotify Node): Fix typos in descriptions (no-changelog)
  packages/nodes-base/nodes/Spotify/Spotify.node.ts
Labels: node/improvement, n8n team

#7180 fix(seven Node): Rename sms77 to seven, fix credentials test
  packages/nodes-base/credentials/Sms77Api.credentials.ts
  packages/nodes-base/nodes/Sms77/GenericFunctions.ts
  packages/nodes-base/nodes/Sms77/Sms77.node.json
  packages/nodes-base/nodes/Sms77/Sms77.node.ts
  packages/nodes-base/nodes/Sms77/seven.svg
  packages/nodes-base/nodes/Sms77/sms77.png
Labels: node/improvement, n8n team

#7204 fix: Attempt license renewal when n8n starts (no-changelog)
  packages/cli/src/License.ts
  packages/cli/test/unit/License.test.ts
Labels: core, n8n team

#7208 ci: Fix tests failing on MySQL (no-changelog)
  packages/cli/test/integration/credentials.controller.test.ts
Labels: core, n8n team

#7206 fix(core): Resolve domains to IPv4 first
  packages/cli/bin/n8n
  packages/cli/src/WorkflowRunnerProcess.ts
Labels: core, n8n team

#7210 refactor: Ignore large-scale revisions (no-changelog)
  .git-blame-ignore-revs
Labels: n8n team

#7201 feat(Linear Node): Add support for OAuth2
  packages/nodes-base/credentials/LinearOAuth2Api.credentials.ts
  packages/nodes-base/nodes/Linear/GenericFunctions.ts
  packages/nodes-base/nodes/Linear/Linear.node.ts
  packages/nodes-base/nodes/Linear/LinearTrigger.node.ts
  packages/nodes-base/package.json
Labels: node/improvement, n8n team

#7216 feat(editor): Group supplemental inputs by required state and scale nodes infinitely in width
  packages/editor-ui/src/components/Node.vue
  packages/editor-ui/src/mixins/nodeBase.ts
  packages/editor-ui/src/utils/nodeViewUtils.ts
Labels: ui, n8n team

#7209 fix: Color and scale up only endpoints with valid input/output compatibility
  packages/editor-ui/src/components/Node.vue
  packages/editor-ui/src/mixins/nodeBase.ts
  packages/editor-ui/src/utils/nodeViewUtils.ts
  packages/editor-ui/src/views/NodeView.vue
Labels: ui, n8n team

#7177 fix(HTTP Request Node): Decrease default timeout to 5min
  packages/nodes-base/nodes/HttpRequest/V3/HttpRequestV3.node.ts
Labels: node/improvement, n8n team

#7196 fix(HTML Node): Add pairedItem support for 'Convert to HTML Table' operation
  packages/nodes-base/nodes/Html/Html.node.ts
Labels: node/improvement, n8n team

#7217 fix(core): Make parsing of content-type and content-disposition headers more flexible
  packages/core/package.json
  packages/core/src/NodeExecuteFunctions.ts
  packages/core/test/NodeExecuteFunctions.test.ts
  pnpm-lock.yaml
Labels: core, n8n team

#7211 docs(Google Sheets Node): Operations naming update (no-changelog)
  packages/nodes-base/nodes/Google/Sheet/v2/actions/sheet/Sheet.resource.ts
  packages/nodes-base/nodes/Google/Sheet/v2/actions/spreadsheet/SpreadSheet.resource.ts
Labels: node/improvement, n8n team

#7092 refactor(core): Implement soft-deletions for executions
  packages/cli/src/ActiveExecutions.ts
  packages/cli/src/GenericHelpers.ts
  packages/cli/src/Interfaces.ts
  packages/cli/src/PublicApi/v1/handlers/executions/executions.handler.ts
  packages/cli/src/PublicApi/v1/handlers/executions/executions.service.ts
  packages/cli/src/Server.ts
  packages/cli/src/WorkflowExecuteAdditionalData.ts
  packages/cli/src/WorkflowHelpers.ts
  packages/cli/src/WorkflowRunner.ts
  packages/cli/src/commands/BaseCommand.ts
  packages/cli/src/commands/start.ts
  packages/cli/src/config/schema.ts
  packages/cli/src/constants.ts
  packages/cli/src/databases/entities/ExecutionEntity.ts
  packages/cli/src/databases/repositories/execution.repository.ts
  packages/cli/src/executionLifecycleHooks/shared/sharedHookFunctions.ts
  packages/cli/src/executions/executions.service.ts
  packages/cli/test/integration/audit/credentials.risk.test.ts
  packages/cli/test/integration/audit/database.risk.test.ts
  packages/cli/test/integration/audit/filesystem.risk.test.ts
  packages/cli/test/integration/audit/instance.risk.test.ts
  packages/cli/test/integration/audit/nodes.risk.test.ts
  packages/cli/test/integration/commands/import.cmd.test.ts
  packages/cli/test/integration/executions.controller.test.ts
  packages/cli/test/integration/ldap/ldap.api.test.ts
  packages/cli/test/integration/publicApi/executions.test.ts
  packages/cli/test/integration/shared/testDb.ts
  packages/cli/test/integration/shared/types.ts
  packages/cli/test/integration/shared/utils/testServer.ts
  packages/cli/test/unit/PermissionChecker.test.ts
  packages/cli/test/unit/repositories/execution.repository.test.ts
  packages/core/src/BinaryDataManager/FileSystem.ts
  packages/core/src/BinaryDataManager/index.ts
  packages/core/src/Interfaces.ts
  packages/core/test/NodeExecuteFunctions.test.ts
  packages/nodes-base/test/nodes/Helpers.ts
Labels: node/improvement, core, n8n team

#7215 fix: Ensure new Set node is on top of search list
  cypress/e2e/4-node-creator.cy.ts
  packages/editor-ui/src/components/Node/NodeCreator/utils.ts
  packages/editor-ui/src/utils/sortUtils.ts
Labels: node/improvement, ui, n8n team

#7205 feat(editor): Rework banners framework and add email confirmation banner
  packages/editor-ui/src/App.vue
  packages/editor-ui/src/Interface.ts
  packages/editor-ui/src/api/cloudPlans.ts
  packages/editor-ui/src/components/MainHeader/WorkflowDetails.vue
  packages/editor-ui/src/components/__tests__/BannersStack.test.ts
  packages/editor-ui/src/components/banners/BannerStack.vue
  packages/editor-ui/src/components/banners/BaseBanner.vue
  packages/editor-ui/src/components/banners/EmailConfirmationBanner.vue
  packages/editor-ui/src/constants.ts
  packages/editor-ui/src/plugins/i18n/locales/en.json
  packages/editor-ui/src/stores/__tests__/ui.test.ts
  packages/editor-ui/src/stores/__tests__/utils/cloudStoreUtils.ts
  packages/editor-ui/src/stores/cloudPlan.store.ts
  packages/editor-ui/src/stores/settings.store.ts
  packages/editor-ui/src/stores/ui.store.ts
  packages/editor-ui/src/stores/users.store.ts
  packages/editor-ui/src/views/SigninView.vue
  packages/workflow/src/Interfaces.ts
Labels: ui, n8n team

#7188 fix: Issue enforcing user limits on start plan
  packages/cli/src/controllers/passwordReset.controller.ts
  packages/cli/test/integration/passwordReset.api.test.ts
Labels: core, n8n team

#7227 fix(Airtable Node): Attachments field type fix
  packages/nodes-base/nodes/Airtable/v2/methods/resourceMapping.ts
Labels: n8n team, node/issue

#7229 fix(core): Handle filename* with quotes in Content-Disposition header
  packages/core/src/NodeExecuteFunctions.ts
  packages/core/test/NodeExecuteFunctions.test.ts
Labels: core, n8n team

#6964 feat(core): Add Tournament as the new default expression evaluator
  packages/cli/src/ExpressionEvalator.ts
  packages/cli/src/Server.ts
  packages/cli/src/commands/BaseCommand.ts
  packages/cli/src/config/schema.ts
  packages/editor-ui/src/App.vue
  packages/workflow/package.json
  packages/workflow/src/Expression.ts
  packages/workflow/src/ExpressionEvaluatorProxy.ts
  packages/workflow/src/Interfaces.ts
  packages/workflow/src/index.ts
  packages/workflow/test/Expression.test.ts
  pnpm-lock.yaml
Labels: core, ui, n8n team

#7226 fix(APITemplate.io Node): Fix action description for create pdf (no-changelog)
  packages/nodes-base/nodes/ApiTemplateIo/ApiTemplateIo.node.ts
Labels: node/improvement, n8n team

#7237 refactor(core): Log binary data file write errors (no-changelog)
  packages/core/src/BinaryDataManager/FileSystem.ts
  packages/core/src/BinaryDataManager/index.ts
  packages/core/src/LoadNodeDetails.ts
  packages/core/src/WorkflowExecute.ts
  packages/core/src/decorators/LogCatch.decorator.ts
  packages/core/test/helpers/index.ts
  packages/core/tsconfig.json
Labels: core, n8n team

#7236 fix(editor): Fix SQL editor issue
  cypress/e2e/13-pinning.cy.ts
  cypress/e2e/16-webhook-node.cy.ts
  cypress/e2e/29-sql-editor.cy.ts
  packages/editor-ui/src/components/CodeNodeEditor/CodeNodeEditor.vue
  packages/editor-ui/src/components/CodeNodeEditor/theme.ts
  packages/editor-ui/src/components/ParameterInput.vue
  packages/editor-ui/src/components/SqlEditor/SqlEditor.vue
Labels: ui, n8n team

#7240 fix(editor): Add debug feature docs link
  packages/editor-ui/src/components/DebugPaywallModal.vue
  packages/editor-ui/src/plugins/i18n/locales/en.json
Labels: ui, n8n team

#7164 refactor(core): Generalize binary data manager interface (no-changelog)
  packages/cli/src/Server.ts
  packages/cli/src/WebhookHelpers.ts
  packages/cli/src/WorkflowRunnerProcess.ts
  packages/cli/src/commands/BaseCommand.ts
  packages/cli/src/commands/execute.ts
  packages/cli/src/commands/executeBatch.ts
  packages/cli/src/commands/start.ts
  packages/cli/src/commands/webhook.ts
  packages/cli/src/commands/worker.ts
  packages/cli/src/config/schema.ts
  packages/cli/src/config/types.ts
  packages/cli/src/config/utils.ts
  packages/cli/src/databases/repositories/execution.repository.ts
  packages/cli/test/integration/commands/worker.cmd.test.ts
  packages/cli/test/integration/publicApi/executions.test.ts
  packages/cli/test/integration/shared/utils/index.ts
  packages/core/package.json
  packages/core/src/BinaryData/BinaryData.service.ts
  packages/core/src/BinaryData/FileSystem.manager.ts
  packages/core/src/BinaryData/types.ts
  packages/core/src/BinaryData/utils.ts
  packages/core/src/BinaryDataManager/FileSystem.ts
  packages/core/src/BinaryDataManager/index.ts
  packages/core/src/BinaryDataManager/utils.ts
  packages/core/src/Interfaces.ts
  packages/core/src/NodeExecuteFunctions.ts
  packages/core/src/index.ts
  packages/core/test/NodeExecuteFunctions.test.ts
  packages/nodes-base/nodes/Aws/S3/test/V1/AwsS3.node.test.ts
  packages/nodes-base/nodes/Aws/S3/test/V2/AwsS3.node.test.ts
  packages/nodes-base/nodes/Code/test/Code.node.test.ts
  packages/nodes-base/nodes/Compression/test/node/Compression.test.ts
  packages/nodes-base/nodes/Crypto/test/Crypto.test.ts
  packages/nodes-base/nodes/HttpRequest/test/binaryData/HttpRequest.test.ts
  packages/nodes-base/nodes/HttpRequest/test/node/HttpRequest.test.ts
  packages/nodes-base/nodes/ICalendar/test/node/ICalendar.test.ts
  packages/nodes-base/nodes/MoveBinaryData/test/MoveBinaryData.test.ts
  packages/nodes-base/nodes/QuickChart/test/QuickChart.node.test.ts
  packages/nodes-base/nodes/ReadBinaryFile/test/ReadBinaryFile.test.ts
  packages/nodes-base/nodes/ReadBinaryFiles/test/ReadBinaryFiles.test.ts
  packages/nodes-base/nodes/ReadPdf/test/ReadPDF.test.ts
  packages/nodes-base/nodes/SpreadsheetFile/test/SpreadsheetFile.test.ts
  packages/nodes-base/nodes/WriteBinaryFile/test/WriteBinaryFile.test.ts
  packages/nodes-base/package.json
  packages/nodes-base/test/nodes/Helpers.ts
  pnpm-lock.yaml
Labels: core, n8n team

#7222 feat(editor): Update node styling, connector styling and grouping
  packages/@n8n/nodes-langchain/nodes/agents/OpenAiFunctionsAgent/OpenAiFunctionsAgent.node.ts
  packages/@n8n/nodes-langchain/nodes/chains/ChainLLM/ChainLlm.node.ts
  packages/@n8n/nodes-langchain/nodes/chains/ChainRetrievalQA/ChainRetrievalQa.node.ts
  packages/@n8n/nodes-langchain/nodes/chains/ChainStructuredOutput/ChainStructuredOutput.node.ts
  packages/@n8n/nodes-langchain/nodes/chains/ChainSummarization/ChainSummarization.node.ts
  packages/@n8n/nodes-langchain/nodes/chains/ChainVectorStoreQA/ChainVectorStoreQa.node.ts
  packages/@n8n/nodes-langchain/nodes/code/Code.node.ts
  packages/@n8n/nodes-langchain/nodes/document_loaders/DocumentBinaryInputLoader/DocumentBinaryInputLoader.node.ts
  packages/@n8n/nodes-langchain/nodes/document_loaders/DocumentBinaryInputLoader/binary.svg
  packages/@n8n/nodes-langchain/nodes/document_loaders/DocumentGithubLoader/DocumentGithubLoader.node.ts
  packages/@n8n/nodes-langchain/nodes/document_loaders/DocumentGithubLoader/github.svg
  packages/@n8n/nodes-langchain/nodes/document_loaders/DocumentJSONInputLoader/DocumentJsonInputLoader.node.ts
  packages/@n8n/nodes-langchain/nodes/document_loaders/DocumentJSONInputLoader/json.svg
  packages/@n8n/nodes-langchain/nodes/embeddings/EmbeddingsOpenAI/EmbeddingsOpenAi.node.ts
  packages/@n8n/nodes-langchain/nodes/embeddings/EmbeddingsOpenAI/openAi.svg
  packages/@n8n/nodes-langchain/nodes/llms/LMChatAnthropic/LmChatAnthropic.node.ts
  packages/@n8n/nodes-langchain/nodes/llms/LMChatOllama/LmChatOllama.node.ts
  packages/@n8n/nodes-langchain/nodes/llms/LMChatOpenAi/LmChatOpenAi.node.ts
  packages/@n8n/nodes-langchain/nodes/llms/LMOllama/LmOllama.node.ts
  packages/@n8n/nodes-langchain/nodes/llms/LMOpenAi/LmOpenAi.node.ts
  packages/@n8n/nodes-langchain/nodes/llms/LMOpenHuggingFaceInference/LmOpenHuggingFaceInference.node.ts
  packages/@n8n/nodes-langchain/nodes/memory/MemoryBufferWindow/MemoryBufferWindow.node.ts
  packages/@n8n/nodes-langchain/nodes/memory/MemoryChatRetriever/MemoryChatRetriever.node.ts
  packages/@n8n/nodes-langchain/nodes/memory/MemoryMotorhead/MemoryMotorhead.node.ts
  packages/@n8n/nodes-langchain/nodes/memory/MemoryRedisChat/MemoryRedisChat.node.ts
  packages/@n8n/nodes-langchain/nodes/memory/MemoryXata/MemoryXata.node.ts
  packages/@n8n/nodes-langchain/nodes/memory/MemoryXata/xata.svg
  packages/@n8n/nodes-langchain/nodes/output_parser/OutputParserAutofixing/OutputParserAutofixing.node.ts
  packages/@n8n/nodes-langchain/nodes/output_parser/OutputParserItemList/OutputParserItemList.node.ts
  packages/@n8n/nodes-langchain/nodes/output_parser/OutputParserStructured/OutputParserStructured.node.ts
  packages/@n8n/nodes-langchain/nodes/retrievers/RetrieverVectorStore/RetrieverVectorStore.node.ts
  packages/@n8n/nodes-langchain/nodes/text_splitters/TextSplitterCharacterTextSplitter/TextSplitterCharacterTextSplitter.node.ts
  packages/@n8n/nodes-langchain/nodes/text_splitters/TextSplitterRecursiveCharacterTextSplitter/TextSplitterRecursiveCharacterTextSplitter.node.ts
  packages/@n8n/nodes-langchain/nodes/text_splitters/TextSplitterTokenSplitter/TextSplitterTokenSplitter.node.ts
  packages/@n8n/nodes-langchain/nodes/tools/ToolCalculator/ToolCalculator.node.ts
  packages/@n8n/nodes-langchain/nodes/tools/ToolCode/ToolCode.node.ts
  packages/@n8n/nodes-langchain/nodes/tools/ToolSerpApi/ToolSerpApi.node.ts
  packages/@n8n/nodes-langchain/nodes/tools/ToolSerpApi/serpApi.svg
  packages/@n8n/nodes-langchain/nodes/tools/ToolWikipedia/ToolWikipedia.node.ts
  packages/@n8n/nodes-langchain/nodes/tools/ToolWolframAlpha/ToolWolframAlpha.node.ts
  packages/@n8n/nodes-langchain/nodes/tools/ToolWorkflow/ToolWorkflow.node.ts
  packages/@n8n/nodes-langchain/nodes/vector_store/InMemoryVectorStore/InMemoryVectorStore.node.ts
  packages/@n8n/nodes-langchain/nodes/vector_store/VectorStorePineconeInsert/VectorStorePineconeInsert.node.ts
  packages/@n8n/nodes-langchain/nodes/vector_store/VectorStorePineconeInsert/pinecone.svg
  packages/@n8n/nodes-langchain/nodes/vector_store/VectorStorePineconeLoad/VectorStorePineconeLoad.node.ts
  packages/@n8n/nodes-langchain/nodes/vector_store/VectorStorePineconeLoad/pinecone.svg
  packages/@n8n/nodes-langchain/nodes/vector_store/VectorStoreSupabaseInsert/VectorStoreSupabaseInsert.node.ts
  packages/@n8n/nodes-langchain/nodes/vector_store/VectorStoreSupabaseLoad/VectorStoreSupabaseLoad.node.ts
  packages/editor-ui/src/components/Node.vue
  packages/editor-ui/src/components/NodeIcon.vue
  packages/editor-ui/src/constants.ts
  packages/editor-ui/src/mixins/nodeBase.ts
  packages/editor-ui/src/n8n-theme.scss
  packages/editor-ui/src/utils/nodeViewUtils.ts
Labels: n8n team

#7195 feat(core): Remove `storeMetadata` and `getSize` from binary data manager interface (no-changelog)
  packages/core/src/BinaryData/BinaryData.service.ts
  packages/core/src/BinaryData/FileSystem.manager.ts
  packages/core/src/BinaryData/errors.ts
  packages/core/src/BinaryData/types.ts
  packages/core/src/BinaryData/utils.ts
  packages/core/src/NodeExecuteFunctions.ts
  packages/workflow/src/Interfaces.ts
Labels: core, n8n team

#7232 feat: Add user cloud it to telemetry
  packages/editor-ui/src/plugins/__tests__/telemetry.test.ts
  packages/editor-ui/src/plugins/telemetry/index.ts
  packages/workflow/src/Interfaces.ts
Labels: core, ui, n8n team

#7212 feat: Add onboarding flow
  cypress/e2e/29-templates.cy.ts
  cypress/fixtures/Onboarding_workflow.json
  cypress/pages/templates.ts
  cypress/pages/workflow.ts
  packages/cli/src/databases/entities/WorkflowEntity.ts
  packages/cli/src/databases/migrations/common/1695128658538-AddWorkflowMetadata.ts
  packages/cli/src/databases/migrations/mysqldb/index.ts
  packages/cli/src/databases/migrations/postgresdb/index.ts
  packages/cli/src/databases/migrations/sqlite/1695128658538-AddWorkflowMetadata.ts
  packages/cli/src/databases/migrations/sqlite/index.ts
  packages/cli/src/requests.ts
  packages/editor-ui/src/Interface.ts
  packages/editor-ui/src/constants.ts
  packages/editor-ui/src/mixins/workflowHelpers.ts
  packages/editor-ui/src/plugins/i18n/locales/en.json
  packages/editor-ui/src/router.ts
  packages/editor-ui/src/stores/__tests__/workflows.spec.ts
  packages/editor-ui/src/stores/templates.store.ts
  packages/editor-ui/src/stores/workflows.store.ts
  packages/editor-ui/src/views/NodeView.vue
  packages/editor-ui/src/views/WorkflowOnboardingView.vue
  packages/workflow/src/Interfaces.ts
Labels: core, ui, n8n team

#7250 fix: Bug when trailing user reset password on instance (no-changelog)
  packages/cli/test/integration/passwordReset.api.test.ts
Labels: core, n8n team

#7251 fix(core): Fix binary data manager check on pruning
  packages/core/src/BinaryData/BinaryData.service.ts
Labels: core, n8n team

#7247 refactor(core)!: Make `getBinaryStream` async
  packages/cli/BREAKING-CHANGES.md
  packages/cli/src/WebhookHelpers.ts
  packages/core/src/BinaryData/BinaryData.service.ts
  packages/core/src/BinaryData/FileSystem.manager.ts
  packages/core/src/BinaryData/types.ts
  packages/core/src/NodeExecuteFunctions.ts
  packages/nodes-base/nodes/Aws/S3/V2/AwsS3V2.node.ts
  packages/nodes-base/nodes/Crypto/Crypto.node.ts
  packages/nodes-base/nodes/Ftp/Ftp.node.ts
  packages/nodes-base/nodes/Google/CloudStorage/ObjectDescription.ts
  packages/nodes-base/nodes/Google/Drive/v1/GoogleDriveV1.node.ts
  packages/nodes-base/nodes/Google/Drive/v2/helpers/utils.ts
  packages/nodes-base/nodes/Google/YouTube/YouTube.node.ts
  packages/nodes-base/nodes/HttpRequest/GenericFunctions.ts
  packages/nodes-base/nodes/HttpRequest/V3/HttpRequestV3.node.ts
  packages/nodes-base/nodes/HttpRequest/test/utils/utils.test.ts
  packages/nodes-base/nodes/Jira/Jira.node.ts
  packages/nodes-base/nodes/Slack/V2/SlackV2.node.ts
  packages/nodes-base/nodes/SpreadsheetFile/v2/SpreadsheetFileV2.node.ts
  packages/nodes-base/nodes/Ssh/Ssh.node.ts
  packages/nodes-base/nodes/Telegram/Telegram.node.ts
  packages/nodes-base/nodes/WriteBinaryFile/WriteBinaryFile.node.ts
  packages/workflow/src/Interfaces.ts
Labels: node/improvement, core, n8n team

#7220 refactor(core): Include workflow ID in binary data writes (no-changelog)
  packages/cli/src/ActiveWebhooks.ts
  packages/cli/src/ActiveWorkflowRunner.ts
  packages/cli/src/workflows/workflows.services.ts
  packages/cli/test/unit/ActiveWorkflowRunner.test.ts
  packages/core/src/BinaryData/BinaryData.service.ts
  packages/core/src/BinaryData/FileSystem.manager.ts
  packages/core/src/BinaryData/types.ts
  packages/core/src/NodeExecuteFunctions.ts
  packages/workflow/src/Workflow.ts
Labels: core, ui, n8n team

#7252 fix(core): Make senderId required for all command messages
  packages/cli/package.json
  packages/cli/src/AbstractServer.ts
  packages/cli/src/License.ts
  packages/cli/src/Server.ts
  packages/cli/src/commands/BaseCommand.ts
  packages/cli/src/commands/start.ts
  packages/cli/src/commands/webhook.ts
  packages/cli/src/commands/worker.ts
  packages/cli/src/config/schema.ts
  packages/cli/src/eventbus/MessageEventBus/MessageEventBus.ts
  packages/cli/src/eventbus/MessageEventBusWriter/MessageEventBusLogWriter.ts
  packages/cli/src/services/orchestration.service.ts
  packages/cli/src/services/orchestration/handleCommandMessage.ts
  packages/cli/src/services/redis/RedisServiceBaseClasses.ts
  packages/cli/src/services/redis/RedisServiceCommands.ts
  packages/cli/src/services/redis/RedisServiceListSender.ts
  packages/cli/src/services/redis/RedisServicePubSubPublisher.ts
  packages/cli/src/services/redis/RedisServiceStreamProducer.ts
  packages/cli/src/worker/workerCommandHandler.ts
  packages/cli/test/integration/commands/worker.cmd.test.ts
  packages/cli/test/unit/License.test.ts
  packages/cli/test/unit/services/orchestration.service.test.ts
  pnpm-lock.yaml
Labels: core, n8n team

#7257 fix(editor): Fix issue that double incoming connection often does not resolve expression (no-changelog)
  packages/editor-ui/src/mixins/__tests__/workflowHelpers.spec.ts
  packages/editor-ui/src/mixins/workflowHelpers.ts
Labels: ui, n8n team

#7260 perf(core): Skip unneeded calls on every pruning cycle
  packages/cli/src/databases/repositories/execution.repository.ts
Labels: core, n8n team

#7262 ci: Adjust Postgres/MySQL failure notification (no-changelog)
  .github/workflows/ci-postgres-mysql.yml
Labels: n8n team

#7264 feat: Add various AI Tool UX improvements (no-changelog)
  packages/@n8n/nodes-langchain/nodes/agents/OpenAiFunctionsAgent/OpenAiFunctionsAgent.node.ts
  packages/@n8n/nodes-langchain/nodes/trigger/ManualChatTrigger/ManualChatTrigger.node.ts
  packages/editor-ui/src/components/NDVDraggablePanels.vue
  packages/editor-ui/src/components/Node.vue
  packages/editor-ui/src/components/OutputPanel.vue
  packages/editor-ui/src/components/ParameterInputList.vue
  packages/editor-ui/src/components/RunDataAi/AiRunContentBlock.vue
  packages/editor-ui/src/components/WorkflowLMChat.vue
  packages/editor-ui/src/constants.ts
  packages/editor-ui/src/event-bus/index.ts
  packages/editor-ui/src/event-bus/ndv.ts
  packages/editor-ui/src/mixins/nodeBase.ts
  packages/editor-ui/src/plugins/jsplumb/N8nAddInputEndpointType.ts
  packages/editor-ui/src/stores/ndv.store.ts
  packages/editor-ui/src/views/NodeView.vue
  packages/workflow/src/Interfaces.ts
Labels: core, ui, n8n team

#7225 feat(core): Introduce object store service
  packages/cli/src/databases/repositories/execution.repository.ts
  packages/core/package.json
  packages/core/src/BinaryData/BinaryData.service.ts
  packages/core/src/BinaryData/FileSystem.manager.ts
  packages/core/src/BinaryData/types.ts
  packages/core/src/BinaryData/utils.ts
  packages/core/src/NodeExecuteFunctions.ts
  packages/core/src/ObjectStore/ObjectStore.service.ee.ts
  packages/core/src/ObjectStore/errors.ts
  packages/core/src/ObjectStore/types.ts
  packages/core/src/ObjectStore/utils.ts
  packages/core/src/index.ts
  packages/core/test/NodeExecuteFunctions.test.ts
  packages/core/test/ObjectStore.test.ts
  pnpm-lock.yaml
Labels: core, n8n team

#7269 docs: Update alias for iCalendar node
  packages/nodes-base/nodes/ICalendar/ICalendar.node.json
Labels: node/improvement, n8n team

#7271 fix(core): Do not set ttl globally in test (no-changelog)
  packages/cli/test/unit/services/cache.service.test.ts
Labels: core, n8n team

#7268 feat(MISP Node): Update credential to support HTTP Request node
  packages/nodes-base/credentials/MispApi.credentials.ts
  packages/nodes-base/nodes/Misp/GenericFunctions.ts
Labels: node/improvement, n8n team

#7272 fix(core): Make DNS resolution order configurable
  packages/cli/bin/n8n
  packages/cli/src/WorkflowRunnerProcess.ts
Labels: core, n8n team

#7261 fix(core): Prevent executions from displaying Running status incorrectly
  packages/core/src/WorkflowExecute.ts
Labels: core, n8n team

#7274 fix(editor): Update cloud endpoint paths (no-changelog)
  packages/editor-ui/src/api/cloudPlans.ts
Labels: ui, n8n team

#7273 ci: Update pnpm-lock.yaml (no-changelog)
  .prettierignore
  pnpm-lock.yaml
Labels: n8n team

#7234 feat(core): Initial workflow history API
  packages/cli/src/PublicApi/v1/handlers/workflows/workflows.handler.ts
  packages/cli/src/Server.ts
  packages/cli/src/databases/entities/WorkflowHistory.ts
  packages/cli/src/databases/repositories/execution.repository.ts
  packages/cli/src/requests.ts
  packages/cli/src/workflows/workflowHistory/workflowHistory.controller.ee.ts
  packages/cli/src/workflows/workflowHistory/workflowHistory.service.ee.ts
  packages/cli/src/workflows/workflowHistory/workflowHistoryHelper.ee.ts
  packages/cli/src/workflows/workflowHistory/workflowHistoryService.ee.ts
  packages/cli/src/workflows/workflows.services.ts
  packages/cli/test/integration/shared/testDb.ts
  packages/cli/test/integration/shared/types.ts
  packages/cli/test/integration/shared/utils/testServer.ts
  packages/cli/test/integration/workflowHistory.api.test.ts
Labels: core, n8n team

#7279 fix(core): Bump License SDK Version (no-changelog)
  packages/cli/package.json
  pnpm-lock.yaml
Labels: skip-e2e

#6948 fix(core): Use consistent timezone-aware timestamps in postgres
  packages/cli/src/databases/entities/AbstractEntity.ts
  packages/cli/src/databases/migrations/postgresdb/1694091729095-MigrateToTimestampTz.ts
  packages/cli/src/databases/migrations/postgresdb/index.ts
Labels: core, n8n team

#7286 fix(Item Lists Node): Concatenate operation pairedItems fix
  packages/nodes-base/nodes/ItemLists/V2/ItemListsV2.node.ts
  packages/nodes-base/nodes/ItemLists/V3/actions/itemList/concatenateItems.operation.ts
  packages/nodes-base/nodes/ItemLists/test/node/workflow.concatenate_pairedItems.json
Labels: n8n team, node/issue

#7282 fix(core): WorkflowHistory nodes/connections columns should be json
  packages/cli/src/databases/migrations/common/1695829275184-ModifyWorkflowHistoryNodesAndConnections.ts
  packages/cli/src/databases/migrations/mysqldb/index.ts
  packages/cli/src/databases/migrations/postgresdb/index.ts
  packages/cli/src/databases/migrations/sqlite/index.ts
Labels: core, n8n team

#7293 fix(HTTP Request Node): Add suggestion how to fix '429 - too many requests' errors
  packages/editor-ui/src/plugins/i18n/locales/en.json
  packages/nodes-base/nodes/HttpRequest/V3/HttpRequestV3.node.ts
  packages/workflow/src/NodeErrors.ts
Labels: node/improvement, core, ui, n8n team

#7292 ci: Refactor DB tests (no-changelog)
  .github/docker-compose.yml
  .github/workflows/ci-postgres-mysql.yml
  jest.config.js
  packages/cli/test/integration/credentials.test.ts
Labels: n8n team

#7176 fix(Notion Node): Rename Notion API Key to Internal Integration Token
  cypress/e2e/17-sharing.cy.ts
  cypress/e2e/2-credentials.cy.ts
  packages/nodes-base/credentials/NotionApi.credentials.ts
Labels: node/improvement, n8n team

#7302 feat(core): AI Nodes text changes
  packages/@n8n/nodes-langchain/nodes/agents/Agent/Agent.node.ts
  packages/@n8n/nodes-langchain/nodes/chains/ChainLLM/ChainLlm.node.ts
  packages/@n8n/nodes-langchain/nodes/document_loaders/DocumentBinaryInputLoader/DocumentBinaryInputLoader.node.ts
  packages/@n8n/nodes-langchain/nodes/document_loaders/DocumentJSONInputLoader/DocumentJsonInputLoader.node.ts
  packages/@n8n/nodes-langchain/nodes/llms/LMChatAnthropic/LmChatAnthropic.node.ts
  packages/@n8n/nodes-langchain/nodes/llms/LMChatOllama/LmChatOllama.node.ts
  packages/@n8n/nodes-langchain/nodes/llms/LMChatOpenAi/LmChatOpenAi.node.ts
  packages/@n8n/nodes-langchain/nodes/llms/LMCohere/LmCohere.node.ts
  packages/@n8n/nodes-langchain/nodes/llms/LMOllama/LmOllama.node.ts
  packages/@n8n/nodes-langchain/nodes/llms/LMOpenAi/LmOpenAi.node.ts
  packages/@n8n/nodes-langchain/nodes/llms/LMOpenHuggingFaceInference/LmOpenHuggingFaceInference.node.ts
  packages/@n8n/nodes-langchain/nodes/text_splitters/TextSplitterRecursiveCharacterTextSplitter/TextSplitterRecursiveCharacterTextSplitter.node.ts
  packages/@n8n/nodes-langchain/nodes/trigger/ManualChatTrigger/ManualChatTrigger.node.ts
  packages/design-system/src/components/N8nNodeCreatorNode/NodeCreatorNode.vue
  packages/editor-ui/src/components/Node/NodeCreator/ItemTypes/NodeItem.vue
  packages/editor-ui/src/components/Node/NodeCreator/Modes/NodesMode.vue
  packages/editor-ui/src/components/Node/NodeCreator/Panel/NodesListPanel.vue
  packages/editor-ui/src/components/Node/NodeCreator/Renderers/ItemsRenderer.vue
  packages/editor-ui/src/components/Node/NodeCreator/composables/useViewStacks.ts
  packages/editor-ui/src/components/Node/NodeCreator/viewsData.ts
  packages/editor-ui/src/plugins/i18n/locales/en.json
Labels: ui, n8n team

#7291 feat(editor): Implement beta release UI changes
  packages/cli/src/Server.ts
  packages/cli/src/config/schema.ts
  packages/editor-ui/public/n8n-beta-logo.svg
  packages/editor-ui/src/App.vue
  packages/editor-ui/src/components/Logo.vue
  packages/editor-ui/src/components/MainSidebar.vue
  packages/editor-ui/src/composables/useTitleChange.ts
  packages/workflow/src/Interfaces.ts
Labels: core, ui, n8n team

#7300 fix(Postgres Node): Node requires comma-separated string even when using a single parameter through an expression
  packages/nodes-base/nodes/Postgres/v2/actions/database/executeQuery.operation.ts
Labels: n8n team, node/issue

#7275 ci: Fix typescript incremental builds (no-changelog)
  packages/@n8n/client-oauth2/tsconfig.build.json
  packages/cli/tsconfig.build.json
  packages/cli/tsconfig.json
  packages/core/tsconfig.build.json
  packages/core/tsconfig.json
  packages/node-dev/tsconfig.json
  packages/nodes-base/tsconfig.build.json
  packages/nodes-base/tsconfig.json
  packages/workflow/tsconfig.build.json
  packages/workflow/tsconfig.json
  tsconfig.backend.json
  tsconfig.build.json
Labels: node/improvement, core, n8n team

#7296 feat(core): Add plan name to telemetry (no-changelog)
  packages/cli/src/Interfaces.ts
  packages/cli/src/InternalHooks.ts
  packages/cli/src/Server.ts
  packages/cli/test/unit/InternalHooks.test.ts
Labels: core, n8n team

#7306 feat(core): Allow to override agent/chain system messages
  packages/@n8n/nodes-langchain/nodes/agents/Agent/agents/ConversationalAgent/description.ts
  packages/@n8n/nodes-langchain/nodes/agents/Agent/agents/ConversationalAgent/execute.ts
  packages/@n8n/nodes-langchain/nodes/agents/Agent/agents/ConversationalAgent/prompt.ts
  packages/@n8n/nodes-langchain/nodes/agents/Agent/agents/OpenAiFunctionsAgent/description.ts
  packages/@n8n/nodes-langchain/nodes/agents/Agent/agents/OpenAiFunctionsAgent/execute.ts
  packages/@n8n/nodes-langchain/nodes/agents/Agent/agents/OpenAiFunctionsAgent/prompt.ts
  packages/@n8n/nodes-langchain/nodes/agents/Agent/agents/ReActAgent/description.ts
  packages/@n8n/nodes-langchain/nodes/agents/Agent/agents/ReActAgent/execute.ts
  packages/@n8n/nodes-langchain/nodes/agents/Agent/agents/ReActAgent/prompt.ts
  packages/@n8n/nodes-langchain/nodes/chains/ChainLLM/ChainLlm.node.ts
  packages/@n8n/nodes-langchain/nodes/chains/ChainSummarization/ChainSummarization.node.ts
  packages/@n8n/nodes-langchain/nodes/chains/ChainSummarization/prompt.ts
Labels: n8n team

#7186 feat(editor): Workflow history [WIP]- create workflow history list component (no-changelog)
  packages/cli/src/Server.ts
  packages/editor-ui/src/__tests__/router.test.ts
  packages/editor-ui/src/api/workflowHistory.ts
  packages/editor-ui/src/components/WorkflowHistory/WorkflowHistoryContent.vue
  packages/editor-ui/src/components/WorkflowHistory/WorkflowHistoryList.vue
  packages/editor-ui/src/components/WorkflowHistory/WorkflowHistoryListItem.vue
  packages/editor-ui/src/components/WorkflowHistory/__tests__/WorkflowHistoryList.test.ts
  packages/editor-ui/src/components/WorkflowHistory/__tests__/WorkflowHistoryListItem.test.ts
  packages/editor-ui/src/plugins/i18n/locales/en.json
  packages/editor-ui/src/router.ts
  packages/editor-ui/src/stores/workflowHistory.store.ts
  packages/editor-ui/src/types/workflowHistory.ts
  packages/editor-ui/src/views/WorkflowHistory.vue
  packages/editor-ui/src/views/__tests__/WorkflowHistory.test.ts
Labels: ui, n8n team

#7309 feat(core): Support some of the Postgres SSL opens in AI Agent
  packages/@n8n/nodes-langchain/nodes/agents/Agent/agents/SqlAgent/other/handlers/postgres.ts
Labels: n8n team
