Repository n8n-io/n8n, pull requests merged in 2023-07, with the labels that each got.

#6579 fix(editor): First round of e2e tests fixes with Vue 3
  cypress/e2e/1-workflows.cy.ts
  cypress/pages/credentials.ts
  cypress/pages/modals/credentials-modal.ts
  cypress/pages/modals/message-box.ts
  cypress/pages/workflow.ts
  cypress/pages/workflows.ts
  packages/design-system/src/components/N8nActionDropdown/ActionDropdown.vue
  packages/editor-ui/src/components/CredentialCard.vue
  packages/editor-ui/src/components/NodeCredentials.vue
  packages/editor-ui/src/components/WorkflowCard.vue
  packages/editor-ui/src/components/layouts/ResourcesListLayout.vue
Labels: ui, n8n team

#6082 feat: Add crowd.dev node and trigger node
  packages/nodes-base/credentials/CrowdDevApi.credentials.ts
  packages/nodes-base/nodes/CrowdDev/CrowdDev.node.json
  packages/nodes-base/nodes/CrowdDev/CrowdDev.node.ts
  packages/nodes-base/nodes/CrowdDev/CrowdDevTrigger.node.json
  packages/nodes-base/nodes/CrowdDev/CrowdDevTrigger.node.ts
  packages/nodes-base/nodes/CrowdDev/GenericFunctions.ts
  packages/nodes-base/nodes/CrowdDev/crowdDev.svg
  packages/nodes-base/nodes/CrowdDev/descriptions/activityFields.ts
  packages/nodes-base/nodes/CrowdDev/descriptions/automationFields.ts
  packages/nodes-base/nodes/CrowdDev/descriptions/index.ts
  packages/nodes-base/nodes/CrowdDev/descriptions/memberFields.ts
  packages/nodes-base/nodes/CrowdDev/descriptions/noteFields.ts
  packages/nodes-base/nodes/CrowdDev/descriptions/organizationFields.ts
  packages/nodes-base/nodes/CrowdDev/descriptions/resources.ts
  packages/nodes-base/nodes/CrowdDev/descriptions/shared.ts
  packages/nodes-base/nodes/CrowdDev/descriptions/taskFields.ts
  packages/nodes-base/nodes/CrowdDev/descriptions/utils.ts
  packages/nodes-base/package.json
Labels: node/new, community

#6575 refactor(Item Lists Node): Refactoring
  packages/nodes-base/nodes/ItemLists/ItemLists.node.ts
  packages/nodes-base/nodes/ItemLists/V3/ItemListsV3.node.ts
  packages/nodes-base/nodes/ItemLists/V3/actions/common.descriptions.ts
  packages/nodes-base/nodes/ItemLists/V3/actions/itemList/concatenateItems.operation.ts
  packages/nodes-base/nodes/ItemLists/V3/actions/itemList/index.ts
  packages/nodes-base/nodes/ItemLists/V3/actions/itemList/limit.operation.ts
  packages/nodes-base/nodes/ItemLists/V3/actions/itemList/removeDuplicates.operation.ts
  packages/nodes-base/nodes/ItemLists/V3/actions/itemList/sort.operation.ts
  packages/nodes-base/nodes/ItemLists/V3/actions/itemList/splitOutItems.operation.ts
  packages/nodes-base/nodes/ItemLists/V3/actions/itemList/summarize.operation.ts
  packages/nodes-base/nodes/ItemLists/V3/actions/node.type.ts
  packages/nodes-base/nodes/ItemLists/V3/actions/router.ts
  packages/nodes-base/nodes/ItemLists/V3/actions/versionDescription.ts
  packages/nodes-base/nodes/ItemLists/V3/helpers/utils.ts
  packages/nodes-base/nodes/ItemLists/test/node/workflow.update_3.json
Labels: n8n team, tech debt

#4991 fix(Strapi Node): Fix issue with pagination
  packages/nodes-base/nodes/Strapi/GenericFunctions.ts
Labels: node/improvement, community, in linear

#6587 fix(editor): Show retry information in execution list only when it exists
  .github/scripts/check-tests.mjs
  packages/editor-ui/src/components/ExecutionsList.vue
  packages/editor-ui/src/components/__tests__/ExecutionsList.test.ts
  packages/workflow/src/Interfaces.ts
Labels: core, ui, n8n team

#6577 fix(core): Update pruning related config defaults for v1
  packages/cli/src/config/schema.ts
Labels: core, n8n team, v1

#6591 fix(core): Fix migrations for MySQL/MariaDB
  packages/cli/src/databases/migrations/mysqldb/1690000000030-SeparateExecutionData.ts
  packages/cli/src/databases/migrations/mysqldb/1690000000031-FixExecutionDataType.ts
  packages/cli/src/databases/migrations/mysqldb/index.ts
Labels: core, n8n team

#6464 refactor: Setup node context API, and consolidate code between Webhook and Wait nodes (no-changelog)
  packages/cli/src/WaitingWebhooks.ts
  packages/editor-ui/src/constants.ts
  packages/nodes-base/nodes/Wait/Wait.node.ts
  packages/nodes-base/nodes/Webhook/Webhook.node.ts
  packages/nodes-base/nodes/Webhook/description.ts
  packages/nodes-base/nodes/Webhook/error.ts
  packages/workflow/src/Interfaces.ts
  packages/workflow/src/Workflow.ts
Labels: node/improvement, core, n8n team

#5670 feat(Notion Node): Add option to update icon when updating a page
  packages/nodes-base/nodes/Notion/DatabasePageDescription.ts
  packages/nodes-base/nodes/Notion/v2/NotionV2.node.ts
Labels: node/improvement, community, in linear

#5883 feat(Strava Node): Add hide_from_home field in Activity Update
  packages/nodes-base/nodes/Strava/ActivityDescription.ts
  packages/nodes-base/nodes/Strava/Strava.node.ts
Labels: node/improvement, community

#6570 refactor: Remove basic auth env vars from docker compose stacks
  docker/compose/subfolderWithSSL/.env
  docker/compose/withMariaDB/.env
  docker/compose/withMariaDB/README.md
  docker/compose/withMariaDB/docker-compose.yml
  docker/compose/withPostgres/.env
  docker/compose/withPostgresAndWorker/.env
Labels: n8n team, v1

#6566 fix: Restore expression completions
  packages/editor-ui/src/plugins/codemirror/completions/utils.ts
Labels: ui, n8n team, v1

#6594 fix(core): Remove typeorm patches, but still enforce transactions on every migration
  package.json
  packages/cli/src/databases/migrations/sqlite/1652367743993-AddUserSettings.ts
  packages/cli/src/databases/migrations/sqlite/1652905585850-AddAPIKeyColumn.ts
  packages/cli/src/databases/migrations/sqlite/1673268682475-DeleteExecutionsWithWorkflows.ts
  packages/cli/src/databases/migrations/sqlite/1690000000002-MigrateIntegerKeysToString.ts
  packages/cli/src/databases/types.ts
  packages/cli/src/databases/utils/migrationHelpers.ts
  patches/typeorm@0.3.12.patch
  pnpm-lock.yaml
Labels: core, n8n team

#6598 fix(Salesforce Node): Fix typo for adding a contact to a campaign
  packages/nodes-base/nodes/Salesforce/ContactDescription.ts
Labels: node/improvement, n8n team

#6529 refactor: Switch cloud plan retrieval endpoint (no-changelog)
  packages/editor-ui/src/api/cloudPlans.ts
  packages/editor-ui/src/stores/cloudPlan.store.ts
Labels: ui, n8n team

#6522 fix(core): Improve the performance of last 2 sqlite migrations
  packages/cli/src/databases/migrations/sqlite/1690000000002-MigrateIntegerKeysToString.ts
  packages/cli/src/databases/migrations/sqlite/1690000000010-SeparateExecutionData.ts
  packages/cli/src/databases/utils/migrationHelpers.ts
Labels: core, n8n team

#6600 fix: Fix migrations for postgres and mysql (no-changelog)
  packages/cli/src/databases/utils/migrationHelpers.ts
Labels: core, n8n team

#6507 fix(core): Make node execution order configurable, and backward-compatible
  packages/cli/src/commands/start.ts
  packages/core/src/WorkflowExecute.ts
  packages/core/test/WorkflowExecute.test.ts
  packages/core/test/helpers/constants.ts
  packages/editor-ui/src/Interface.ts
  packages/editor-ui/src/api/workflows.ts
  packages/editor-ui/src/components/WorkflowSettings.vue
  packages/editor-ui/src/plugins/i18n/locales/en.json
  packages/editor-ui/src/stores/workflows.store.ts
  packages/editor-ui/src/views/NodeView.vue
  packages/nodes-base/nodes/CompareDatasets/CompareDatasets.node.ts
  packages/nodes-base/nodes/CompareDatasets/test/node/workflow.compareDatasets.forceInputNodeExecution.json
  packages/nodes-base/nodes/Merge/test/node/workflow.mixed.not.forceInputNodeExecution.json
  packages/nodes-base/nodes/Merge/v1/MergeV1.node.ts
  packages/nodes-base/nodes/Merge/v2/MergeV2.node.ts
  packages/nodes-base/test/nodes/ExecuteWorkflow.ts
  packages/workflow/src/Interfaces.ts
  packages/workflow/src/Workflow.ts
Labels: core, ui, n8n team, v1

#6540 feat(HTML Node): 'Convert to table operation
  packages/nodes-base/nodes/Html/Html.node.json
  packages/nodes-base/nodes/Html/Html.node.ts
Labels: node/improvement, n8n team

#6607 fix(Google Drive Node): Fix regex in file RLC
  packages/nodes-base/nodes/Google/Drive/GoogleDriveTrigger.node.ts
  packages/nodes-base/nodes/Google/Drive/v1/GoogleDriveV1.node.ts
  packages/nodes-base/nodes/Google/Drive/v2/actions/common.descriptions.ts
  packages/nodes-base/nodes/Google/Sheet/GoogleSheetsTrigger.node.ts
  packages/nodes-base/nodes/Google/Sheet/v2/actions/sheet/Sheet.resource.ts
  packages/nodes-base/nodes/Google/Sheet/v2/actions/spreadsheet/delete.operation.ts
  packages/nodes-base/nodes/Google/constants.ts
Labels: n8n team, node/issue

#6610 fix(editor): Show appropriate empty workflow list content when instance environment is readonly
  packages/editor-ui/src/App.vue
  packages/editor-ui/src/plugins/i18n/locales/en.json
  packages/editor-ui/src/views/WorkflowsView.vue
Labels: ui, n8n team

#6613 fix(editor): Prevent keyboard shortcuts to edit workflows in readonly mode
  packages/editor-ui/src/components/WorkflowSettings.vue
  packages/editor-ui/src/mixins/genericHelpers.ts
  packages/editor-ui/src/views/NodeView.vue
  packages/editor-ui/src/views/WorkflowsView.vue
Labels: ui, n8n team

#6614 refactor(core): Load `cookieParser` middleware only once (no-changelog)
  packages/cli/src/middlewares/auth.ts
  packages/cli/test/integration/shared/utils.ts
Labels: core, n8n team

#6619 fix(editor): Make Source control branch select required
  packages/editor-ui/src/views/SettingsSourceControl.vue
Labels: ui, n8n team

#6622 feat(core): Only show V1 banner to users who migrated
  packages/cli/src/databases/migrations/mysqldb/1646992772331-CreateUserManagement.ts
  packages/cli/src/databases/migrations/postgresdb/1646992772331-CreateUserManagement.ts
  packages/cli/src/databases/migrations/sqlite/1646992772331-CreateUserManagement.ts
Labels: core, n8n team

#6568 fix(Code Node): Install python modules always in a user-writable folder
  package.json
  packages/core/src/NodeExecuteFunctions.ts
  packages/nodes-base/nodes/Code/Code.node.ts
  packages/nodes-base/nodes/Code/Pyodide.ts
  packages/nodes-base/nodes/Code/PythonSandbox.ts
  packages/nodes-base/nodes/Code/Sandbox.ts
  packages/nodes-base/nodes/Code/descriptions/PythonCodeDescription.ts
  packages/nodes-base/package.json
  packages/workflow/src/AugmentObject.ts
  packages/workflow/src/Interfaces.ts
  packages/workflow/src/ObservableObject.ts
  packages/workflow/src/WorkflowDataProxy.ts
  packages/workflow/test/AugmentObject.test.ts
  patches/pyodide@0.23.4.patch
  pnpm-lock.yaml
Labels: node/improvement, core, n8n team

#6628 ci: Fix v1 banner migration (no-changelog)
  packages/cli/src/databases/migrations/mysqldb/1646992772331-CreateUserManagement.ts
  packages/cli/src/databases/migrations/postgresdb/1646992772331-CreateUserManagement.ts
Labels: core, n8n team

#6629 fix: Add postAuthenticate hook for source control preferences (no-changelog)
  packages/editor-ui/src/App.vue
  packages/editor-ui/src/__tests__/server/endpoints/sourceControl.ts
  packages/editor-ui/src/views/SettingsSourceControl.vue
  packages/editor-ui/src/views/__tests__/SettingsSourceControl.test.ts
Labels: ui, n8n team

#6618 fix(editor): Extend menu item and use it as a recursive component
  packages/design-system/src/components/N8nMenuItem/MenuItem.vue
  packages/design-system/src/types/menu.ts
  packages/editor-ui/src/components/MainSidebar.vue
  packages/editor-ui/src/plugins/i18n/locales/en.json
Labels: ui, n8n team

#6611 feat(Slack Node): Add option to include link to workflow in Slack node
  packages/cli/src/WorkflowExecuteAdditionalData.ts
  packages/core/src/NodeExecuteFunctions.ts
  packages/editor-ui/src/components/NodeSettings.vue
  packages/editor-ui/src/plugins/telemetry/index.ts
  packages/nodes-base/nodes/Slack/Slack.node.ts
  packages/nodes-base/nodes/Slack/V2/GenericFunctions.ts
  packages/nodes-base/nodes/Slack/V2/MessageDescription.ts
  packages/nodes-base/nodes/Slack/V2/SlackV2.node.ts
  packages/workflow/src/Interfaces.ts
Labels: node/improvement, core, ui, n8n team

#6632 feat(editor): Load fixed template list as experiment
  packages/editor-ui/src/components/CollectionsCarousel.vue
  packages/editor-ui/src/components/TemplateDetails.vue
  packages/editor-ui/src/components/TemplateList.vue
  packages/editor-ui/src/constants.ts
  packages/editor-ui/src/plugins/i18n/locales/en.json
  packages/editor-ui/src/router.ts
  packages/editor-ui/src/stores/posthog.store.ts
  packages/editor-ui/src/views/TemplatesSearchView.vue
Labels: ui, n8n team

#6615 fix(core): Fix credentials lazy-loading (no-changelog)
  packages/cli/src/CredentialTypes.ts
  packages/cli/src/LoadNodesAndCredentials.ts
  packages/core/bin/generate-known
  packages/core/src/DirectoryLoader.ts
  packages/workflow/src/Interfaces.ts
Labels: node/improvement, core, n8n team

#6634 refactor: Stop using `.d.ts` files for type-collection files (no-changelog)
  packages/cli/src/PublicApi/types.ts
  packages/cli/src/commands/Interfaces.ts
  packages/cli/src/commands/executeBatch.ts
  packages/cli/src/config/types.ts
  packages/cli/test/integration/shared/types.ts
  packages/nodes-base/nodes/ActionNetwork/types.ts
  packages/nodes-base/nodes/Adalo/types.ts
  packages/nodes-base/nodes/Aws/DynamoDB/types.ts
  packages/nodes-base/nodes/Baserow/types.ts
  packages/nodes-base/nodes/Copper/utils/types.ts
  packages/nodes-base/nodes/Elastic/ElasticSecurity/types.ts
  packages/nodes-base/nodes/Elastic/Elasticsearch/types.ts
  packages/nodes-base/nodes/Freshservice/types.ts
  packages/nodes-base/nodes/FreshworksCrm/types.ts
  packages/nodes-base/nodes/Google/Docs/interfaces.ts
  packages/nodes-base/nodes/Google/Perspective/types.ts
  packages/nodes-base/nodes/Grafana/types.ts
  packages/nodes-base/nodes/Grist/types.ts
  packages/nodes-base/nodes/Magento/GenericFunctions.ts
  packages/nodes-base/nodes/Magento/Magento2.node.ts
  packages/nodes-base/nodes/Magento/types.ts
  packages/nodes-base/nodes/Marketstack/types.ts
  packages/nodes-base/nodes/Misp/types.ts
  packages/nodes-base/nodes/MonicaCrm/types.ts
  packages/nodes-base/nodes/QuickBooks/types.ts
  packages/nodes-base/nodes/SeaTable/types.ts
  packages/nodes-base/nodes/Splunk/types.ts
  packages/nodes-base/nodes/Taiga/types.ts
  packages/nodes-base/nodes/Zammad/types.ts
  packages/nodes-base/nodes/Zoho/types.ts
  packages/workflow/src/ExecutionStatus.ts
Labels: node/improvement, core, n8n team

#6636 refactor: License typings suggestions for users quota guards
  packages/cli/src/Interfaces.ts
  packages/cli/src/License.ts
  packages/cli/src/constants.ts
  packages/cli/src/controllers/e2e.controller.ts
  packages/cli/test/unit/License.test.ts
Labels: core, n8n team

#6633 fix(core): Reduce memory consumption on `BinaryDataManager.init`
  packages/cli/src/PublicApi/v1/handlers/executions/executions.handler.ts
  packages/cli/src/databases/repositories/execution.repository.ts
  packages/core/src/BinaryDataManager/FileSystem.ts
  packages/core/src/BinaryDataManager/index.ts
  packages/core/src/Interfaces.ts
Labels: core, n8n team

#6642 fix(core): Update docker compose setup for V1 images
  docker/compose/withPostgres/docker-compose.yml
  docker/compose/withPostgresAndWorker/docker-compose.yml
  docker/images/n8n/docker-entrypoint.sh
Labels: n8n team

#6643 fix(Postgres Node): Upsert does not fetch columns when schema other then public
  packages/nodes-base/nodes/MySql/v2/actions/common.descriptions.ts
  packages/nodes-base/nodes/MySql/v2/actions/database/executeQuery.operation.ts
  packages/nodes-base/nodes/MySql/v2/actions/database/insert.operation.ts
  packages/nodes-base/nodes/MySql/v2/actions/database/update.operation.ts
  packages/nodes-base/nodes/MySql/v2/actions/database/upsert.operation.ts
  packages/nodes-base/nodes/Postgres/v2/actions/common.descriptions.ts
  packages/nodes-base/nodes/Postgres/v2/actions/database/executeQuery.operation.ts
  packages/nodes-base/nodes/Postgres/v2/actions/database/insert.operation.ts
  packages/nodes-base/nodes/Postgres/v2/actions/database/update.operation.ts
  packages/nodes-base/nodes/Postgres/v2/actions/database/upsert.operation.ts
  packages/nodes-base/nodes/Postgres/v2/helpers/utils.ts
  packages/nodes-base/nodes/Postgres/v2/methods/resourceMapping.ts
Labels: n8n team, node/issue

#6590 fix(HTTP Request Node): Cleanup circular references in response
  packages/nodes-base/nodes/HttpRequest/V1/HttpRequestV1.node.ts
  packages/nodes-base/nodes/HttpRequest/V2/HttpRequestV2.node.ts
  packages/nodes-base/nodes/HttpRequest/V3/HttpRequestV3.node.ts
  packages/workflow/src/Expression.ts
  packages/workflow/src/NodeErrors.ts
  packages/workflow/src/index.ts
  packages/workflow/src/utils.ts
Labels: node/improvement, community

#6645 ci: Run checklist job as a separate workflow (no-changelog)
  .github/workflows/checklist.yml
  .github/workflows/ci-pull-requests.yml
Labels: n8n team

#6644 feat(OpenAI Node): Update max token limit to support newer model limits
  packages/nodes-base/nodes/OpenAi/ChatDescription.ts
  packages/nodes-base/nodes/OpenAi/TextDescription.ts
Labels: node/improvement, community

#6434 feat(API): Implement users account quota guards
  packages/cli/src/Interfaces.ts
  packages/cli/src/Ldap/helpers.ts
  packages/cli/src/License.ts
  packages/cli/src/PublicApi/v1/handlers/users/users.service.ee.ts
  packages/cli/src/PublicApi/v1/handlers/users/users.service.ts
  packages/cli/src/PublicApi/v1/handlers/workflows/workflows.handler.ts
  packages/cli/src/PublicApi/v1/handlers/workflows/workflows.service.ts
  packages/cli/src/Server.ts
  packages/cli/src/UserManagement/UserManagementHelper.ts
  packages/cli/src/auth/jwt.ts
  packages/cli/src/constants.ts
  packages/cli/src/controllers/auth.controller.ts
  packages/cli/src/controllers/e2e.controller.ts
  packages/cli/src/controllers/passwordReset.controller.ts
  packages/cli/src/controllers/users.controller.ts
  packages/cli/src/databases/entities/User.ts
  packages/cli/src/license/license.controller.ts
  packages/cli/src/push/index.ts
  packages/cli/src/sso/saml/samlHelpers.ts
  packages/cli/test/integration/auth.api.test.ts
  packages/cli/test/integration/auth.mw.test.ts
  packages/cli/test/integration/credentials.ee.test.ts
  packages/cli/test/integration/credentials.test.ts
  packages/cli/test/integration/license.api.test.ts
  packages/cli/test/integration/saml/saml.api.test.ts
  packages/cli/test/integration/shared/testDb.ts
  packages/cli/test/integration/shared/utils.ts
  packages/cli/test/integration/variables.test.ts
  packages/cli/test/integration/workflows.controller.ee.test.ts
  packages/cli/test/unit/License.test.ts
  packages/editor-ui/src/stores/settings.store.ts
  packages/editor-ui/src/views/SettingsUsersView.vue
  packages/workflow/src/Interfaces.ts
Labels: core, ui, n8n team

#6649 ci!: Drop support for Node.js 16. Add initial support for Node.js 20
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/workflows/ci-master.yml
  .github/workflows/docker-base-image.yml
  .github/workflows/docker-image-v1-rc.yml
  docker/images/n8n-base/Dockerfile
  docker/images/n8n/Dockerfile
  package.json
  packages/cli/BREAKING-CHANGES.md
  packages/cli/bin/n8n
  packages/cli/package.json
Labels: core, n8n team, v1

#6658 refactor: Move CLI commands types to own dir (no-changelog)
  packages/cli/src/commands/executeBatch.ts
  packages/cli/src/types/commands.types.ts
Labels: core, n8n team

#6652 fix(editor): Remove duplicated action box to upgrade on UsersSettngsView (no-changelog)
  packages/editor-ui/src/views/SettingsUsersView.vue
Labels: ui, n8n team

#5746 feat(Telegram Node): Add support for sending messages to forum topics
  packages/nodes-base/nodes/Telegram/Telegram.node.ts
Labels: node/improvement, community

#6659 fix(editor): Update design system menu item component
  packages/design-system/src/components/N8nMenuItem/MenuItem.stories.ts
  packages/design-system/src/components/N8nMenuItem/MenuItem.vue
  packages/design-system/src/types/menu.ts
  packages/editor-ui/src/components/MainSidebar.vue
Labels: ui, n8n team

#6626 fix: Minor grammar adjustment (no-changelog)
  docker/images/n8n/README.md
Labels: community

#6663 fix(core): Use lower cased email for SAML email attribute
  packages/cli/src/sso/saml/saml.service.ee.ts
  packages/cli/src/sso/saml/samlHelpers.ts
Labels: core, n8n team

#6661 fix(editor): Increase contrast ratio in execution list workflow names
  packages/editor-ui/src/components/ExecutionsList.vue
Labels: ui, n8n team

#6666 fix(core): Handle all uncaught exception, not just the ones from Axios
  packages/cli/src/ErrorReporting.ts
Labels: core, n8n team

#6603 feat(editor): Implement new banners framework
  cypress/e2e/10-undo-redo.cy.ts
  cypress/e2e/12-canvas-actions.cy.ts
  cypress/e2e/12-canvas.cy.ts
  cypress/e2e/25-stickies.cy.ts
  cypress/support/commands.ts
  packages/cli/src/Server.ts
  packages/cli/src/config/types.ts
  packages/cli/src/controllers/e2e.controller.ts
  packages/cli/src/controllers/owner.controller.ts
  packages/cli/src/databases/migrations/mysqldb/1646992772331-CreateUserManagement.ts
  packages/cli/src/databases/migrations/postgresdb/1646992772331-CreateUserManagement.ts
  packages/cli/src/databases/migrations/sqlite/1646992772331-CreateUserManagement.ts
  packages/cli/src/databases/repositories/settings.repository.ts
  packages/cli/src/requests.ts
  packages/design-system/src/components/N8nCallout/Callout.vue
  packages/design-system/src/components/N8nCallout/__tests__/__snapshots__/Callout.spec.ts.snap
  packages/editor-ui/src/App.vue
  packages/editor-ui/src/Interface.ts
  packages/editor-ui/src/__tests__/server/endpoints/settings.ts
  packages/editor-ui/src/api/ui.ts
  packages/editor-ui/src/components/ActivationModal.vue
  packages/editor-ui/src/components/BreakpointsObserver.vue
  packages/editor-ui/src/components/CanvasControls.vue
  packages/editor-ui/src/components/MainHeader/MainHeader.vue
  packages/editor-ui/src/components/MainHeader/TabBar.vue
  packages/editor-ui/src/components/MainSidebar.vue
  packages/editor-ui/src/components/Node/NodeCreation.vue
  packages/editor-ui/src/components/Node/NodeCreator/NodeCreator.vue
  packages/editor-ui/src/components/SettingsSidebar.vue
  packages/editor-ui/src/components/V1Banner.vue
  packages/editor-ui/src/components/__tests__/BannersStack.test.ts
  packages/editor-ui/src/components/__tests__/MainSidebarSourceControl.test.ts
  packages/editor-ui/src/components/banners/BannerStack.vue
  packages/editor-ui/src/components/banners/BaseBanner.vue
  packages/editor-ui/src/components/banners/TrialBanner.vue
  packages/editor-ui/src/components/banners/TrialOverBanner.vue
  packages/editor-ui/src/components/banners/V1Banner.vue
  packages/editor-ui/src/composables/useCanvasMouseSelect.ts
  packages/editor-ui/src/main.ts
  packages/editor-ui/src/n8n-theme-variables.scss
  packages/editor-ui/src/plugins/i18n/locales/en.json
  packages/editor-ui/src/stores/settings.store.ts
  packages/editor-ui/src/stores/ui.store.ts
  packages/editor-ui/src/utils/htmlUtils.ts
  packages/editor-ui/src/utils/nodeViewUtils.ts
  packages/editor-ui/src/views/NodeView.vue
  packages/workflow/src/Interfaces.ts
Labels: ui, n8n team, node/name

#6669 fix(editor): Fix mysql migration query for v1 banner (no-changelog)
  packages/cli/src/databases/migrations/mysqldb/1646992772331-CreateUserManagement.ts
Labels: core, n8n team

#6670 fix(TimescaleDB Node): Update TimescaleDB logo (no-changelog)
  packages/nodes-base/nodes/TimescaleDb/timescale.svg
Labels: node/improvement, community

#6675 fix: Remove duplicate source control preferences fetching (no-changelog)
  packages/editor-ui/src/App.vue
Labels: ui, n8n team

#6668 fix(Slack Node): Add UTM params to n8n reference in Slack message (no-changelog)
  packages/nodes-base/nodes/Slack/V2/GenericFunctions.ts
Labels: node/improvement, n8n team

#6585 fix(FileMaker Node): Improve returned error responses
  packages/nodes-base/nodes/FileMaker/FileMaker.node.ts
  packages/nodes-base/nodes/FileMaker/GenericFunctions.ts
  packages/nodes-base/nodes/FileMaker/filemaker.png
Labels: node/improvement, community

#6583 fix(Microsoft Outlook Node): Fix issue with category not correctly applying
  packages/nodes-base/nodes/Microsoft/Outlook/MicrosoftOutlook.node.ts
Labels: node/improvement, n8n team

#6200 feat(Airtable Node): Overhaul
  cypress/e2e/17-sharing.cy.ts
  cypress/e2e/5-ndv.cy.ts
  packages/editor-ui/src/components/ResourceMapper/MappingFields.vue
  packages/editor-ui/src/components/ResourceMapper/MatchingColumnsSelect.vue
  packages/editor-ui/src/components/ResourceMapper/ResourceMapper.vue
  packages/nodes-base/credentials/AirtableTokenApi.credentials.ts
  packages/nodes-base/nodes/Airtable/Airtable.node.ts
  packages/nodes-base/nodes/Airtable/AirtableTrigger.node.ts
  packages/nodes-base/nodes/Airtable/test/v2/node/base/getMany.test.ts
  packages/nodes-base/nodes/Airtable/test/v2/node/base/getSchema.test.ts
  packages/nodes-base/nodes/Airtable/test/v2/node/helpers.ts
  packages/nodes-base/nodes/Airtable/test/v2/node/record/create.test.ts
  packages/nodes-base/nodes/Airtable/test/v2/node/record/deleteRecord.test.ts
  packages/nodes-base/nodes/Airtable/test/v2/node/record/get.test.ts
  packages/nodes-base/nodes/Airtable/test/v2/node/record/search.test.ts
  packages/nodes-base/nodes/Airtable/test/v2/node/record/update.test.ts
  packages/nodes-base/nodes/Airtable/test/v2/utils.test.ts
  packages/nodes-base/nodes/Airtable/v1/AirtableV1.node.ts
  packages/nodes-base/nodes/Airtable/v1/GenericFunctions.ts
  packages/nodes-base/nodes/Airtable/v2/AirtableV2.node.ts
  packages/nodes-base/nodes/Airtable/v2/actions/base/Base.resource.ts
  packages/nodes-base/nodes/Airtable/v2/actions/base/getMany.operation.ts
  packages/nodes-base/nodes/Airtable/v2/actions/base/getSchema.operation.ts
  packages/nodes-base/nodes/Airtable/v2/actions/common.descriptions.ts
  packages/nodes-base/nodes/Airtable/v2/actions/node.type.ts
  packages/nodes-base/nodes/Airtable/v2/actions/record/Record.resource.ts
  packages/nodes-base/nodes/Airtable/v2/actions/record/create.operation.ts
  packages/nodes-base/nodes/Airtable/v2/actions/record/deleteRecord.operation.ts
  packages/nodes-base/nodes/Airtable/v2/actions/record/get.operation.ts
  packages/nodes-base/nodes/Airtable/v2/actions/record/search.operation.ts
  packages/nodes-base/nodes/Airtable/v2/actions/record/update.operation.ts
  packages/nodes-base/nodes/Airtable/v2/actions/record/upsert.operation.ts
  packages/nodes-base/nodes/Airtable/v2/actions/router.ts
  packages/nodes-base/nodes/Airtable/v2/actions/versionDescription.ts
  packages/nodes-base/nodes/Airtable/v2/helpers/interfaces.ts
  packages/nodes-base/nodes/Airtable/v2/helpers/utils.ts
  packages/nodes-base/nodes/Airtable/v2/methods/index.ts
  packages/nodes-base/nodes/Airtable/v2/methods/listSearch.ts
  packages/nodes-base/nodes/Airtable/v2/methods/loadOptions.ts
  packages/nodes-base/nodes/Airtable/v2/methods/resourceMapping.ts
  packages/nodes-base/nodes/Airtable/v2/transport/index.ts
  packages/workflow/src/Interfaces.ts
Labels: node/improvement, n8n team

#6679 fix(editor): Add paywall state to non owner users for Variables
  packages/editor-ui/src/plugins/i18n/locales/en.json
  packages/editor-ui/src/views/VariablesView.vue
  packages/editor-ui/src/views/__tests__/VariablesView.spec.ts
Labels: ui, n8n team

#6617 refactor(core): Refactor WorkflowStatistics code (no-changelog)
  packages/cli/src/Interfaces.ts
  packages/cli/src/InternalHooks.ts
  packages/cli/src/Server.ts
  packages/cli/src/WebhookHelpers.ts
  packages/cli/src/WorkflowExecuteAdditionalData.ts
  packages/cli/src/api/workflowStats.api.ts
  packages/cli/src/commands/execute.ts
  packages/cli/src/commands/executeBatch.ts
  packages/cli/src/controllers/index.ts
  packages/cli/src/controllers/workflowStatistics.controller.ts
  packages/cli/src/databases/repositories/workflowStatistics.repository.ts
  packages/cli/src/eventbus/MessageEventBus/recoverEvents.ts
  packages/cli/src/events/WorkflowStatistics.ts
  packages/cli/src/events/index.ts
  packages/cli/src/push/abstract.push.ts
  packages/cli/src/push/index.ts
  packages/cli/src/services/events.service.ts
  packages/cli/test/unit/services/events.service.test.ts
  packages/core/src/EventEmitter.ts
  packages/core/src/index.ts
Labels: core, n8n team

#6684 fix(editor): Hide Execute Node button for unknown nodes
  packages/editor-ui/src/components/NodeSettings.vue
Labels: ui, n8n team

#6687 feat: Allow hiding credential params on cloud
  packages/editor-ui/src/components/CredentialEdit/CredentialEdit.vue
  packages/nodes-base/credentials/GoogleSheetsOAuth2Api.credentials.ts
  packages/nodes-base/credentials/GoogleSheetsTriggerOAuth2Api.credentials.ts
  packages/workflow/src/Interfaces.ts
Labels: node/improvement, core, ui, n8n team

#6689 fix(core): Upgrade semver to address CVE-2022-25883
  .github/scripts/package.json
  package.json
  packages/cli/package.json
  packages/nodes-base/package.json
  pnpm-lock.yaml
Labels: core, n8n team

#6682 ci: Fix test checker glob (no changelog)
  .github/scripts/check-tests.mjs
Labels: n8n team

#6686 fix(API): Do not add starting node on workflow creation
  packages/cli/src/ActiveWorkflowRunner.ts
  packages/cli/src/PublicApi/v1/handlers/workflows/workflows.handler.ts
  packages/cli/src/PublicApi/v1/handlers/workflows/workflows.service.ts
  packages/cli/src/PublicApi/v1/openapi.yml
  packages/cli/src/constants.ts
  packages/cli/src/utils.ts
  packages/cli/test/integration/publicApi/workflows.test.ts
Labels: core, n8n team

#6690 fix(core): Load SAML libraries dynamically
  packages/cli/src/sso/saml/routes/saml.controller.ee.ts
  packages/cli/src/sso/saml/saml.service.ee.ts
  packages/cli/src/sso/saml/samlValidator.ts
  packages/cli/src/sso/saml/serviceProvider.ee.ts
Labels: core, n8n team

#6696 fix(crowd.dev Node): Fix documentation urls for crowd.dev credentials and nodes
  packages/nodes-base/credentials/CrowdDevApi.credentials.ts
  packages/nodes-base/nodes/CrowdDev/CrowdDev.node.json
  packages/nodes-base/nodes/CrowdDev/CrowdDevTrigger.node.json
Labels: node/improvement, n8n team

#6694 feat: Allow `eslint-config` to be externally consumable
  packages/@n8n/client-oauth2/.eslintrc.js
  packages/@n8n_io/eslint-config/shared.js
  packages/cli/.eslintrc.js
  packages/core/.eslintrc.js
  packages/design-system/.eslintrc.js
  packages/editor-ui/.eslintrc.js
  packages/node-dev/.eslintrc.js
  packages/nodes-base/.eslintrc.js
  packages/workflow/.eslintrc.js
Labels: node/improvement, core, ui, n8n team

#6692 fix(Contentful Node): Fix typo in credential name (no-changelog)
  packages/nodes-base/credentials/ContentfulApi.credentials.ts
  packages/nodes-base/nodes/Contentful/Contentful.node.ts
  packages/nodes-base/nodes/Contentful/GenericFunctions.ts
Labels: node/improvement, n8n team

#6677 fix(editor): Ensure default credential values are not detected as dirty state
  packages/editor-ui/src/components/CredentialEdit/CredentialEdit.vue
Labels: ui, n8n team

#6462 feat(Google Cloud Storage Node): Use streaming for file uploads
  packages/core/src/NodeExecuteFunctions.ts
  packages/nodes-base/nodes/Google/CloudStorage/ObjectDescription.ts
  packages/workflow/package.json
  packages/workflow/src/Interfaces.ts
  packages/workflow/src/utils.ts
  pnpm-lock.yaml
Labels: node/improvement, core, n8n team

#6695 fix(editor): Prevent RMC from loading schema if it's already cached
  packages/editor-ui/src/components/ParameterOptions.vue
  packages/editor-ui/src/components/ResourceMapper/ResourceMapper.vue
  packages/editor-ui/src/components/__tests__/ResourceMapper.test.ts
Labels: ui, n8n team

#6699 fix(API): Fix issue with workflow setting not supporting newer nanoids
  packages/cli/src/PublicApi/v1/handlers/workflows/spec/schemas/workflowSettings.yml
Labels: core, n8n team

#6700 fix(core): Banner dismissal should also work for users migrating to v1 (no-changelog)
  packages/cli/src/databases/repositories/settings.repository.ts
Labels: core, n8n team

#6703 fix(Postgres Node): For select queries, empty result should be be replaced with `{"success":true}`
  packages/nodes-base/nodes/Postgres/v2/actions/router.ts
  packages/nodes-base/nodes/Postgres/v2/helpers/utils.ts
Labels: node/improvement, n8n team

#6674 feat(editor): Removing `ph-no-capture` class from some elements
  packages/design-system/src/components/N8nCheckbox/__tests__/__snapshots__/Checkbox.spec.ts.snap
  packages/design-system/src/components/N8nInput/Input.vue
  packages/design-system/src/components/N8nInput/__tests__/Input.spec.ts
  packages/design-system/src/components/N8nInputLabel/InputLabel.vue
  packages/design-system/src/components/N8nMarkdown/Markdown.vue
  packages/design-system/src/components/N8nSticky/Sticky.vue
  packages/design-system/src/components/N8nUserInfo/UserInfo.vue
  packages/design-system/src/components/N8nUsersList/UsersList.vue
  packages/editor-ui/src/Interface.ts
  packages/editor-ui/src/components/CodeNodeEditor/CodeNodeEditor.vue
  packages/editor-ui/src/components/CopyInput.vue
  packages/editor-ui/src/components/CredentialCard.vue
  packages/editor-ui/src/components/CredentialEdit/CredentialConfig.vue
  packages/editor-ui/src/components/ExecutionFilter.vue
  packages/editor-ui/src/components/ExecutionsList.vue
  packages/editor-ui/src/components/ExpressionEdit.vue
  packages/editor-ui/src/components/ExpressionEditorModal/ExpressionEditorModalInput.vue
  packages/editor-ui/src/components/ExpressionEditorModal/ExpressionEditorModalOutput.vue
  packages/editor-ui/src/components/HtmlEditor/HtmlEditor.vue
  packages/editor-ui/src/components/InlineExpressionEditor/InlineExpressionEditorInput.vue
  packages/editor-ui/src/components/InlineExpressionEditor/InlineExpressionEditorOutput.vue
  packages/editor-ui/src/components/InlineNameEdit.vue
  packages/editor-ui/src/components/InputPanel.vue
  packages/editor-ui/src/components/Node.vue
  packages/editor-ui/src/components/NodeTitle.vue
  packages/editor-ui/src/components/ParameterInput.vue
  packages/editor-ui/src/components/ParameterInputWrapper.vue
  packages/editor-ui/src/components/ResourceLocator/ResourceLocatorDropdown.vue
  packages/editor-ui/src/components/RunDataHtml.vue
  packages/editor-ui/src/components/RunDataJson.vue
  packages/editor-ui/src/components/RunDataSchemaItem.vue
  packages/editor-ui/src/components/RunDataTable.vue
  packages/editor-ui/src/components/SettingsLogStreaming/EventDestinationCard.ee.vue
  packages/editor-ui/src/components/SqlEditor/SqlEditor.vue
  packages/editor-ui/src/components/VariableSelector.vue
  packages/editor-ui/src/components/VariableSelectorItem.vue
  packages/editor-ui/src/components/WorkflowCard.vue
  packages/editor-ui/src/components/__tests__/CopyInput.test.ts
  packages/editor-ui/src/components/__tests__/RunDataJson.test.ts
  packages/editor-ui/src/components/__tests__/__snapshots__/PersonalizationModal.spec.ts.snap
  packages/editor-ui/src/components/__tests__/__snapshots__/RunDataJson.test.ts.snap
  packages/editor-ui/src/components/__tests__/__snapshots__/RunDataSchema.test.ts.snap
  packages/editor-ui/src/components/__tests__/__snapshots__/VariablesRow.spec.ts.snap
  packages/editor-ui/src/stores/posthog.store.ts
  packages/editor-ui/src/views/SettingsApiView.vue
  packages/editor-ui/src/views/SettingsPersonalView.vue
Labels: ui, n8n team

#6673 fix: Enforce tag name uniqueness on sqlite
  packages/cli/src/databases/migrations/sqlite/1690000000020-FixMissingIndicesFromStringIdMigration.ts
  packages/cli/src/databases/migrations/sqlite/index.ts
  packages/cli/test/integration/shared/types.ts
  packages/cli/test/integration/shared/utils/testServer.ts
  packages/cli/test/integration/tags.api.test.ts
Labels: core, n8n team

#6710 fix(core): Redirect user to previous url after SSO signin
  packages/cli/src/sso/saml/routes/saml.controller.ee.ts
  packages/cli/src/sso/saml/saml.service.ee.ts
Labels: core, n8n team

#6707 fix(FTP Node): List recursive ignore . and .. to prevent infinite loops
  packages/nodes-base/nodes/Ftp/Ftp.node.ts
Labels: node/improvement, n8n team

#6715 fix(Google BigQuery Node): Error description improvement
  packages/nodes-base/nodes/Google/BigQuery/v2/actions/database/executeQuery.operation.ts
Labels: n8n team, node/issue

#6711 fix(GitLab Trigger Node): Fix trigger activation 404 error
  packages/nodes-base/nodes/Gitlab/GitlabTrigger.node.ts
Labels: node/improvement, n8n team

#6708 fix(core): Support redis cluster in queue mode
  packages/cli/src/AbstractServer.ts
  packages/cli/src/GenericHelpers.ts
  packages/cli/src/Queue.ts
  packages/cli/src/config/schema.ts
Labels: core, n8n team

#6721 fix(editor): Skip error line highlighting if out of range
  packages/editor-ui/src/components/CodeNodeEditor/CodeNodeEditor.vue
  packages/editor-ui/src/components/SqlEditor/SqlEditor.vue
Labels: ui, n8n team

#6542 fix(AwsS3 Node): Fix issue if bucket name contains a '.'
  packages/nodes-base/nodes/Aws/S3/V2/AwsS3V2.node.ts
Labels: node/improvement, community, in linear

#6723 test(editor): Add canvas actions E2E tests
  cypress/e2e/12-canvas-actions.cy.ts
  cypress/pages/workflow.ts
  cypress/support/commands.ts
  cypress/support/index.ts
  packages/editor-ui/src/components/Node/NodeCreator/ItemTypes/NodeItem.vue
Labels: ui, n8n team

#5633 feat(Rundeck Node): Add support for node filters
  packages/nodes-base/nodes/Rundeck/Rundeck.node.ts
  packages/nodes-base/nodes/Rundeck/RundeckApi.ts
Labels: node/improvement, community

#6727 fix(Gmail Trigger Node): Early returns in case of no data
  packages/nodes-base/nodes/Google/Gmail/GmailTrigger.node.ts
Labels: n8n team, node/issue

#6716 fix(editor): Drop click outside directive from NodeCreator
  packages/editor-ui/src/components/Node/NodeCreator/NodeCreator.vue
Labels: ui, n8n team

#6714 fix(core): Use JWT as reset password token
  packages/cli/src/Server.ts
  packages/cli/src/UserManagement/UserManagementHelper.ts
  packages/cli/src/auth/jwt.ts
  packages/cli/src/controllers/passwordReset.controller.ts
  packages/cli/src/controllers/users.controller.ts
  packages/cli/src/databases/entities/User.ts
  packages/cli/src/databases/migrations/common/1690000000030-RemoveResetPasswordColumns.ts
  packages/cli/src/databases/migrations/mysqldb/index.ts
  packages/cli/src/databases/migrations/postgresdb/index.ts
  packages/cli/src/databases/migrations/sqlite/index.ts
  packages/cli/src/services/jwt.service.ts
  packages/cli/src/user/user.service.ts
  packages/cli/test/integration/passwordReset.api.test.ts
  packages/cli/test/integration/shared/utils/testServer.ts
  packages/cli/test/integration/users.api.test.ts
  packages/cli/test/unit/services/jwt.service.test.ts
  packages/editor-ui/src/api/users.ts
  packages/editor-ui/src/stores/users.store.ts
  packages/editor-ui/src/views/ChangePasswordView.vue
Labels: core, n8n team

#6728 refactor(core): Prevent community packages queries if feature is disabled
  packages/cli/src/commands/start.ts
Labels: core, n8n team

#6576 refactor: Remove deprecated `$data`
  packages/editor-ui/src/components/BreakpointsObserver.vue
  packages/editor-ui/src/components/InlineTextEdit.vue
  packages/editor-ui/src/components/IntersectionObserver.vue
  packages/editor-ui/src/components/MainHeader/WorkflowDetails.vue
  packages/editor-ui/src/components/PersonalizationModal.vue
  packages/editor-ui/src/components/TagsContainer.vue
  packages/editor-ui/src/components/TagsDropdown.vue
  packages/editor-ui/src/components/TagsManager/TagsManager.vue
  packages/editor-ui/src/components/TagsManager/TagsView/TagsView.vue
  packages/editor-ui/src/views/SettingsCommunityNodesView.vue
Labels: ui, n8n team

#6736 Revert "test(editor): Add canvas actions E2E tests"
  cypress/e2e/12-canvas-actions.cy.ts
  cypress/pages/workflow.ts
  cypress/support/commands.ts
  cypress/support/index.ts
  packages/editor-ui/src/components/Node/NodeCreator/ItemTypes/NodeItem.vue
Labels: ui, n8n team

#6718 fix(Postgres Node): Arrays in query replacement fix
  packages/nodes-base/nodes/Postgres/test/v2/operations.test.ts
  packages/nodes-base/nodes/Postgres/v2/actions/database/executeQuery.operation.ts
Labels: n8n team, node/issue

#6730 fix(Telegram Trigger Node): Add guard to 'include' call on null or undefined
  packages/nodes-base/nodes/Telegram/TelegramTrigger.node.ts
Labels: n8n team, node/issue

#6732 fix(core): Use `exec` in docker images to forward signals correctly
  docker/images/n8n/docker-entrypoint.sh
Labels: community

#6706 refactor(core): Move webhook DB access to repository (no-changelog)
  packages/cli/src/AbstractServer.ts
  packages/cli/src/ActiveWorkflowRunner.ts
  packages/cli/src/WorkflowRunnerProcess.ts
  packages/cli/test/unit/ActiveWorkflowRunner.test.ts
Labels: core, n8n team

#6653 fix: Use alternate method for conflict resolution
  packages/cli/src/InternalHooks.ts
  packages/cli/src/Ldap/helpers.ts
  packages/cli/src/PublicApi/v1/handlers/sourceControl/sourceControl.handler.ts
  packages/cli/src/environments/sourceControl/constants.ts
  packages/cli/src/environments/sourceControl/sourceControl.controller.ee.ts
  packages/cli/src/environments/sourceControl/sourceControl.service.ee.ts
  packages/cli/src/environments/sourceControl/sourceControlExport.service.ee.ts
  packages/cli/src/environments/sourceControl/sourceControlGit.service.ee.ts
  packages/cli/src/environments/sourceControl/sourceControlHelper.ee.ts
  packages/cli/src/environments/sourceControl/sourceControlImport.service.ee.ts
  packages/cli/src/environments/sourceControl/sourceControlPreferences.service.ee.ts
  packages/cli/src/environments/sourceControl/types/exportResult.ts
  packages/cli/src/environments/sourceControl/types/exportableWorkflow.ts
  packages/cli/src/environments/sourceControl/types/requests.ts
  packages/cli/src/environments/sourceControl/types/sourceControlGetStatus.ts
  packages/cli/src/environments/sourceControl/types/sourceControlPreferences.ts
  packages/cli/src/environments/sourceControl/types/sourceControlPullWorkFolder.ts
  packages/cli/src/environments/sourceControl/types/sourceControlPushWorkFolder.ts
  packages/cli/src/environments/sourceControl/types/sourceControlWorkflowVersionId.ts
  packages/cli/src/environments/sourceControl/types/sourceControlledFile.ts
  packages/cli/src/environments/variables/variables.service.ee.ts
  packages/cli/src/telemetry/index.ts
  packages/cli/src/workflows/workflows.services.ts
  packages/cli/test/integration/environments/SourceControl.test.ts
  packages/cli/test/integration/environments/VersionControl.test.ts
  packages/cli/test/integration/workflows.controller.ee.test.ts
  packages/cli/test/unit/SourceControl.test.ts
  packages/cli/test/unit/VersionControl.test.ts
  packages/editor-ui/src/Interface.ts
  packages/editor-ui/src/__tests__/server/endpoints/sourceControl.ts
  packages/editor-ui/src/api/sourceControl.ts
  packages/editor-ui/src/components/MainHeader/WorkflowDetails.vue
  packages/editor-ui/src/components/MainSidebarSourceControl.vue
  packages/editor-ui/src/components/NodeSettings.vue
  packages/editor-ui/src/components/RunData.vue
  packages/editor-ui/src/components/SettingsSidebar.vue
  packages/editor-ui/src/components/SourceControlPullModal.ee.vue
  packages/editor-ui/src/components/SourceControlPushModal.ee.vue
  packages/editor-ui/src/components/__tests__/MainSidebarSourceControl.test.ts
  packages/editor-ui/src/components/layouts/ResourcesListLayout.vue
  packages/editor-ui/src/event-bus/source-control.ts
  packages/editor-ui/src/mixins/workflowActivate.ts
  packages/editor-ui/src/mixins/workflowHelpers.ts
  packages/editor-ui/src/plugins/i18n/locales/en.json
  packages/editor-ui/src/router.ts
  packages/editor-ui/src/stores/sourceControl.store.ts
  packages/editor-ui/src/stores/ui.store.ts
  packages/editor-ui/src/views/NodeView.vue
  packages/editor-ui/src/views/SettingsSourceControl.vue
  packages/editor-ui/src/views/WorkflowsView.vue
  packages/editor-ui/src/views/__tests__/SettingsSourceControl.test.ts
Labels: core, ui, n8n team

#6739 fix(core): Fix RemoveResetPasswordColumns migration for sqlite (no-changelog)
  packages/cli/src/databases/migrations/common/1690000000030-RemoveResetPasswordColumns.ts
  packages/cli/src/databases/migrations/sqlite/1690000000030-RemoveResetPasswordColumns.ts
  packages/cli/src/databases/migrations/sqlite/index.ts
Labels: core, n8n team

#6744 fix(editor): Adjust spacing in templates for Vue 3
  packages/editor-ui/src/components/TemplateDetails.vue
Labels: ui, n8n team

#6742 fix(editor): Adjust NDV height for Vue 3
  packages/editor-ui/src/components/NodeDetailsView.vue
Labels: ui, n8n team

#6743 fix(editor): Restore collapsed sidebar items for Vue 3
  packages/design-system/src/components/N8nMenuItem/MenuItem.vue
Labels: ui, n8n team

#6745 refactor: Remove webhook from `IDatabaseCollections` (no-changelog)
  packages/cli/src/Db.ts
  packages/cli/src/Interfaces.ts
Labels: core, n8n team

#6734 fix(Lemlist Node): Fix pagination issues with campaigns and activities
  packages/nodes-base/nodes/Lemlist/GenericFunctions.ts
  packages/nodes-base/nodes/Lemlist/Lemlist.node.ts
Labels: node/improvement, n8n team

#6747 ci: Fix linting issues (no-changelog)
  packages/cli/src/Db.ts
  packages/cli/src/Interfaces.ts
Labels: core, n8n team

#6748 fix(editor): Fix Vue 3 linting issues
  packages/editor-ui/src/App.vue
  packages/editor-ui/src/__tests__/utils.ts
  packages/editor-ui/src/components/BreakpointsObserver.vue
  packages/editor-ui/src/components/CollectionsCarousel.vue
  packages/editor-ui/src/components/DuplicateWorkflowDialog.vue
  packages/editor-ui/src/components/IntersectionObserved.vue
  packages/editor-ui/src/components/MainHeader/MainHeader.vue
  packages/editor-ui/src/components/MainSidebar.vue
  packages/editor-ui/src/components/Node.vue
  packages/editor-ui/src/components/NodeDetailsView.vue
  packages/editor-ui/src/components/NodeExecuteButton.vue
  packages/editor-ui/src/components/NodeTitle.vue
  packages/editor-ui/src/components/ParameterInput.vue
  packages/editor-ui/src/components/SettingsLogStreaming/EventDestinationSettingsModal.ee.vue
  packages/editor-ui/src/components/Sticky.vue
  packages/editor-ui/src/components/TextEdit.vue
  packages/editor-ui/src/components/VariablesRow.vue
  packages/editor-ui/src/components/WorkflowActivator.vue
  packages/editor-ui/src/components/layouts/ResourcesListLayout.vue
  packages/editor-ui/src/views/NodeView.vue
  packages/editor-ui/src/views/SettingsCommunityNodesView.vue
  pnpm-lock.yaml
Labels: ui, n8n team

#6702 fix(core): Allow ignoring SSL issues on generic oauth2 credentials
  packages/@n8n/client-oauth2/src/ClientOAuth2.ts
  packages/@n8n/client-oauth2/src/CodeFlow.ts
  packages/@n8n/client-oauth2/src/utils.ts
  packages/cli/src/credentials/oauth2Credential.api.ts
  packages/core/src/NodeExecuteFunctions.ts
  packages/nodes-base/credentials/OAuth2Api.credentials.ts
  packages/workflow/src/Interfaces.ts
  packages/workflow/src/NodeHelpers.ts
Labels: node/improvement, core, n8n team

#6750 fix(editor): Fix settings initialisation
  packages/editor-ui/src/App.vue
Labels: ui, n8n team

#6751 refactor: Remove all references to the resetPasswordToken field (no-changelog)
  packages/cli/src/commands/user-management/reset.ts
  packages/cli/test/integration/auth.api.test.ts
  packages/cli/test/integration/commands/reset.cmd.test.ts
  packages/cli/test/integration/me.api.test.ts
  packages/cli/test/integration/owner.api.test.ts
  packages/cli/test/integration/publicApi/users.ee.test.ts
Labels: core, n8n team

#6616 refactor(core): Use mixins to delete redundant code between Entity classes (no-changelog)
  packages/cli/src/databases/entities/AbstractEntity.ts
  packages/cli/src/databases/entities/AuthIdentity.ts
  packages/cli/src/databases/entities/CredentialsEntity.ts
  packages/cli/src/databases/entities/EventDestinations.ts
  packages/cli/src/databases/entities/InstalledPackages.ts
  packages/cli/src/databases/entities/Role.ts
  packages/cli/src/databases/entities/SharedCredentials.ts
  packages/cli/src/databases/entities/SharedWorkflow.ts
  packages/cli/src/databases/entities/TagEntity.ts
  packages/cli/src/databases/entities/User.ts
  packages/cli/src/databases/entities/Variables.ts
  packages/cli/src/databases/entities/WorkflowEntity.ts
  packages/cli/src/environments/sourceControl/sourceControlImport.service.ee.ts
  packages/cli/test/integration/audit/filesystem.risk.test.ts
  packages/cli/test/integration/audit/nodes.risk.test.ts
  packages/cli/test/integration/shared/testDb.ts
Labels: core, n8n team

#6755 fix(editor): Redraw node connections if adding more than one node to canvas
  packages/editor-ui/src/views/NodeView.vue
Labels: ui, n8n team

#6756 fix: Display source control buttons properly
  packages/editor-ui/src/components/MainSidebarSourceControl.vue
  packages/editor-ui/src/components/__tests__/MainSidebarSourceControl.test.ts
Labels: ui, n8n team

#6758 fix(editor): Fix `ResourceMapper` unit tests
  packages/editor-ui/src/components/ResourceMapper/MatchingColumnsSelect.vue
  packages/editor-ui/src/components/__tests__/ResourceMapper.test.ts
Labels: ui, n8n team

#6764 fix: Fix value survey styles
  packages/editor-ui/src/components/ModalDrawer.vue
  packages/editor-ui/src/components/ValueSurvey.vue
Labels: ui, n8n team

#6767 fix: Fix drawer animation
  packages/design-system/src/css/drawer.scss
Labels: ui, n8n team

#6768 fix(editor): Fix App loading & auth
  packages/editor-ui/src/App.vue
  packages/editor-ui/src/views/NodeView.vue
Labels: ui, n8n team

#6773 perf(editor): Memoize locale translate calls during actions generation
  packages/editor-ui/src/components/Node/NodeCreator/composables/useActionsGeneration.ts
Labels: ui, n8n team

#6766 fix(editor): Close tags dropdown when modal is opened
  cypress/e2e/17-workflow-tags.cy.ts
  cypress/pages/workflow.ts
  packages/design-system/src/css/drawer.scss
  packages/editor-ui/src/components/TagsDropdown.vue
Labels: ui, n8n team

#6777 fix: Show NodeIcon tooltips by removing pointer-events: none
  packages/design-system/src/components/N8nNodeIcon/NodeIcon.vue
Labels: ui, n8n team

#6771 fix: Respect set modal widths
  packages/design-system/src/css/dialog.scss
  packages/design-system/src/utils.scss
  packages/editor-ui/src/App.vue
Labels: ui, n8n team

#6776 fix(editor): Fix tooltip opening delay prop name
  packages/design-system/src/components/N8nMenuItem/MenuItem.vue
  packages/editor-ui/src/components/MainSidebarSourceControl.vue
  packages/editor-ui/src/components/RunDataTable.vue
  packages/editor-ui/src/views/CanvasAddButton.vue
Labels: ui, n8n team

#6778 fix(editor): Fix collapsed sub menu elements
  packages/design-system/src/components/N8nMenuItem/MenuItem.vue
Labels: ui, n8n team

#6782 fix: Remove number input arrows (no-changelog)
  packages/design-system/src/css/input-number.scss
Labels: ui, n8n team

#6780 ci: Update most of the dev tooling (no-changelog)
  package.json
  packages/@n8n/client-oauth2/src/ClientOAuth2.ts
  packages/@n8n/client-oauth2/src/ClientOAuth2Token.ts
  packages/@n8n/client-oauth2/src/utils.ts
  packages/@n8n_io/eslint-config/base.js
  packages/@n8n_io/eslint-config/package.json
  packages/cli/package.json
  packages/design-system/.storybook/main.js
  packages/design-system/.storybook/main.ts
  packages/design-system/package.json
  packages/design-system/src/components/N8nActionBox/__tests__/__snapshots__/ActionBox.spec.ts.snap
  packages/design-system/src/components/N8nActionDropdown/__tests__/__snapshots__/ActionDropdown.spec.ts.snap
  packages/design-system/src/components/N8nBadge/__tests__/__snapshots__/Badge.spec.ts.snap
  packages/design-system/src/components/N8nButton/__tests__/__snapshots__/Button.spec.ts.snap
  packages/design-system/src/components/N8nCallout/__tests__/__snapshots__/Callout.spec.ts.snap
  packages/design-system/src/components/N8nCard/__tests__/__snapshots__/Card.spec.ts.snap
  packages/design-system/src/components/N8nCheckbox/__tests__/__snapshots__/Checkbox.spec.ts.snap
  packages/design-system/src/components/N8nColorPicker/__tests__/__snapshots__/ColorPicker.spec.ts.snap
  packages/design-system/src/components/N8nDatatable/__tests__/__snapshots__/Datatable.spec.ts.snap
  packages/design-system/src/components/N8nInfoTip/__tests__/__snapshots__/InfoTip.spec.ts.snap
  packages/design-system/src/components/N8nInput/__tests__/__snapshots__/Input.spec.ts.snap
  packages/design-system/src/components/N8nNotice/__tests__/__snapshots__/Notice.spec.ts.snap
  packages/design-system/src/components/N8nRecycleScroller/__tests__/__snapshots__/RecycleScroller.spec.ts.snap
  packages/design-system/src/components/N8nSelect/__tests__/__snapshots__/Select.spec.ts.snap
  packages/design-system/src/components/N8nTree/__tests__/__snapshots__/Tree.spec.ts.snap
  packages/design-system/vite.config.ts
  packages/editor-ui/.eslintrc.js
  packages/editor-ui/package.json
  packages/editor-ui/src/Interface.ts
  packages/editor-ui/src/components/ExecutionFilter.vue
  packages/editor-ui/src/components/ResourceLocator/ResourceLocator.vue
  packages/editor-ui/src/components/VariableSelector.vue
  packages/editor-ui/src/components/__tests__/ExecutionFilter.test.ts
  packages/editor-ui/src/components/__tests__/ExecutionsList.test.ts
  packages/editor-ui/src/components/__tests__/__snapshots__/RunDataJson.test.ts.snap
  packages/editor-ui/src/components/__tests__/__snapshots__/RunDataSchema.test.ts.snap
  packages/editor-ui/src/plugins/codemirror/resolvableHighlighter.ts
  packages/editor-ui/src/plugins/connectors/N8nCustomConnector.ts
  packages/editor-ui/src/stores/sourceControl.store.ts
  packages/editor-ui/src/views/WorkflowsView.vue
  packages/editor-ui/vite.config.ts
  packages/node-dev/package.json
  pnpm-lock.yaml
Labels: core, ui, n8n team

#6787 test(editor): Prevent node view unload by default in e2e run
  cypress/e2e/14-data-transformation-expressions.cy.ts
  cypress/e2e/14-mapping.cy.ts
  cypress/e2e/16-webhook-node.cy.ts
  cypress/e2e/25-stickies.cy.ts
  cypress/pages/workflow.ts
Labels: n8n team

#6779 fix(editor): Resolve vue 3 related console-warnings
  packages/design-system/src/components/N8nPopover/Popover.vue
  packages/editor-ui/src/components/NodeExecuteButton.vue
  packages/editor-ui/src/components/WarningTooltip.vue
  packages/editor-ui/src/plugins/i18n/locales/en.json
Labels: ui, n8n team

#6783 fix(editor): Vue3 - Fix modal positioning and multi-select tag sizing
  cypress/e2e/11-inline-expression-editor.cy.ts
  cypress/e2e/18-user-management.cy.ts
  cypress/pages/settings-personal.ts
  packages/design-system/src/components/N8nFormInput/FormInput.vue
  packages/design-system/src/components/N8nFormInputs/FormInputs.vue
  packages/editor-ui/src/components/NodeDetailsView.vue
  packages/editor-ui/src/components/PersonalizationModal.vue
  packages/editor-ui/src/n8n-theme.scss
Labels: ui, n8n team

#6788 ci: Fix linting issues (no-changelog)
  package.json
  packages/cli/.eslintrc.js
  packages/cli/src/ActiveWorkflowRunner.ts
  packages/cli/src/CredentialsHelper.ts
  packages/cli/src/CredentialsOverwrites.ts
  packages/cli/src/TestWebhooks.ts
  packages/cli/src/WaitingWebhooks.ts
  packages/cli/src/commands/execute.ts
  packages/cli/src/controllers/translation.controller.ts
  packages/cli/src/eventbus/EventMessageClasses/AbstractEventMessage.ts
  packages/cli/src/eventbus/MessageEventBusDestination/MessageEventBusDestination.ee.ts
  packages/cli/src/eventbus/MessageEventBusDestination/MessageEventBusDestinationSentry.ee.ts
  packages/cli/src/eventbus/MessageEventBusDestination/MessageEventBusDestinationSyslog.ee.ts
  packages/cli/src/telemetry/index.ts
  packages/cli/src/workflows/workflows.controller.ts
  packages/cli/src/workflows/workflows.services.ee.ts
  packages/cli/test/integration/shared/testDb.ts
  packages/core/src/BinaryDataManager/index.ts
  packages/core/src/UserSettings.ts
  packages/design-system/.eslintrc.js
  packages/editor-ui/.eslintrc.js
  packages/editor-ui/package.json
  packages/nodes-base/.eslintrc.js
  packages/nodes-base/nodes/Amqp/AmqpTrigger.node.ts
  packages/nodes-base/nodes/Aws/S3/V2/AwsS3V2.node.ts
  packages/nodes-base/nodes/EmailReadImap/v1/EmailReadImapV1.node.ts
  packages/nodes-base/nodes/EmailReadImap/v2/EmailReadImapV2.node.ts
  packages/nodes-base/nodes/FileMaker/GenericFunctions.ts
  packages/nodes-base/nodes/ItemLists/V1/ItemListsV1.node.ts
  packages/nodes-base/nodes/ItemLists/V2/ItemListsV2.node.ts
  packages/nodes-base/nodes/ItemLists/V3/actions/itemList/removeDuplicates.operation.ts
  packages/nodes-base/nodes/Npm/PackageDescription.ts
  packages/nodes-base/nodes/Rundeck/Rundeck.node.ts
  packages/nodes-base/nodes/SeaTable/types.ts
  packages/nodes-base/nodes/TheHive/QueryFunctions.ts
  packages/nodes-base/nodes/Webhook/error.ts
  packages/nodes-base/nodes/WooCommerce/GenericFunctions.ts
  packages/workflow/.eslintrc.js
  packages/workflow/src/Interfaces.ts
  pnpm-lock.yaml
Labels: node/improvement, core, ui, n8n team

#6791 fix(editor): Fix code node highlight error
  packages/editor-ui/src/components/CodeNodeEditor/CodeNodeEditor.vue
Labels: ui, n8n team

#6775 feat(core): Credentials for popular SecOps services, Part 1
  packages/nodes-base/credentials/AlienVaultApi.credentials.ts
  packages/nodes-base/credentials/Auth0ManagementApi.credentials.ts
  packages/nodes-base/credentials/Aws.credentials.ts
  packages/nodes-base/credentials/CarbonBlackApi.credentials.ts
  packages/nodes-base/credentials/CiscoMerakiApi.credentials.ts
  packages/nodes-base/credentials/CiscoSecureEndpointApi.credentials.ts
  packages/nodes-base/credentials/CiscoUmbrellaApi.credentials.ts
  packages/nodes-base/credentials/CiscoWebexOAuth2Api.credentials.ts
  packages/nodes-base/credentials/CrowdStrikeOAuth2Api.credentials.ts
  packages/nodes-base/credentials/F5BigIpApi.credentials.ts
  packages/nodes-base/credentials/FortiGateApi.credentials.ts
  packages/nodes-base/credentials/GoogleApi.credentials.ts
  packages/nodes-base/credentials/GoogleOAuth2Api.credentials.ts
  packages/nodes-base/credentials/HybridAnalysisApi.credentials.ts
  packages/nodes-base/credentials/ImpervaWafApi.credentials.ts
  packages/nodes-base/credentials/KibanaApi.credentials.ts
  packages/nodes-base/credentials/MicrosoftEntraOAuth2Api.credentials.ts
  packages/nodes-base/credentials/MicrosoftOAuth2Api.credentials.ts
  packages/nodes-base/credentials/MistApi.credentials.ts
  packages/nodes-base/credentials/OktaApi.credentials.ts
  packages/nodes-base/credentials/OpenCTIApi.credentials.ts
  packages/nodes-base/credentials/QRadarApi.credentials.ts
  packages/nodes-base/credentials/QualysApi.credentials.ts
  packages/nodes-base/credentials/RecordedFutureApi.credentials.ts
  packages/nodes-base/credentials/SekoiaApi.credentials.ts
  packages/nodes-base/credentials/ShufflerApi.credentials.ts
  packages/nodes-base/credentials/TrellixEpoApi.credentials.ts
  packages/nodes-base/credentials/VirusTotalApi.credentials.ts
  packages/nodes-base/credentials/ZscalerZiaApi.credentials.ts
  packages/nodes-base/credentials/icons/AWS.svg
  packages/nodes-base/credentials/icons/AlienVault.png
  packages/nodes-base/credentials/icons/Auth0.svg
  packages/nodes-base/credentials/icons/Azure.svg
  packages/nodes-base/credentials/icons/Cisco.svg
  packages/nodes-base/credentials/icons/CrowdStrike.svg
  packages/nodes-base/credentials/icons/F5.svg
  packages/nodes-base/credentials/icons/Fortinet.svg
  packages/nodes-base/credentials/icons/Google.svg
  packages/nodes-base/credentials/icons/Hybrid.png
  packages/nodes-base/credentials/icons/IBM.svg
  packages/nodes-base/credentials/icons/Imperva.svg
  packages/nodes-base/credentials/icons/Kibana.svg
  packages/nodes-base/credentials/icons/Microsoft.svg
  packages/nodes-base/credentials/icons/Mist.svg
  packages/nodes-base/credentials/icons/Okta.svg
  packages/nodes-base/credentials/icons/OpenCTI.png
  packages/nodes-base/credentials/icons/Qualys.svg
  packages/nodes-base/credentials/icons/RecordedFuture.svg
  packages/nodes-base/credentials/icons/Sekoia.svg
  packages/nodes-base/credentials/icons/Shuffler.svg
  packages/nodes-base/credentials/icons/Trellix.svg
  packages/nodes-base/credentials/icons/VirusTotal.svg
  packages/nodes-base/credentials/icons/Wazuh.png
  packages/nodes-base/credentials/icons/Zscaler.svg
  packages/nodes-base/credentials/icons/vmware.svg
  packages/nodes-base/package.json
Labels: node/new, n8n team

#6738 refactor(core): Cache workflow ownership
  packages/cli/src/UserManagement/PermissionChecker.ts
  packages/cli/src/UserManagement/UserManagementHelper.ts
  packages/cli/src/WaitTracker.ts
  packages/cli/src/WaitingWebhooks.ts
  packages/cli/src/WebhookHelpers.ts
  packages/cli/src/WorkflowExecuteAdditionalData.ts
  packages/cli/src/commands/worker.ts
  packages/cli/src/services/cache.service.ts
  packages/cli/src/services/events.service.ts
  packages/cli/src/services/ownership.service.ts
  packages/cli/test/unit/PermissionChecker.test.ts
  packages/cli/test/unit/services/events.service.test.ts
  packages/cli/test/unit/services/ownership.service.test.ts
Labels: core, n8n team

#6781 fix(editor): Prevent text edit dialog from re-opening in same tick
  packages/editor-ui/src/components/ParameterInput.vue
Labels: ui, n8n team

#6800 test(editor): Do not chain invoke calls after assertions in 24-ndv-paired-item e2e spec (no-changelog)
  cypress/e2e/24-ndv-paired-item.cy.ts
Labels: n8n team

#6799 fix(Todoist Node): Fix issue with section id being ignored
  packages/nodes-base/nodes/Todoist/v2/OperationHandler.ts
Labels: node/improvement, n8n team

#6790 test(editor): Add canvas actions E2E tests (#6723)
  cypress/e2e/12-canvas-actions.cy.ts
  cypress/pages/workflow.ts
  cypress/support/commands.ts
  cypress/support/index.ts
  packages/editor-ui/src/components/Node/NodeCreator/ItemTypes/NodeItem.vue
Labels: ui, n8n team

#6797 fix(core): Add missing primary key on the `execution_data` table on postgres
  packages/cli/src/databases/migrations/postgresdb/1690787606731-AddMissingPrimaryKeyOnExecutionData.ts
  packages/cli/src/databases/migrations/postgresdb/index.ts
Labels: core, n8n team

#6582 fix(core): Restrict read/write file paths access
  packages/cli/src/config/schema.ts
  packages/core/src/Constants.ts
  packages/core/src/NodeExecuteFunctions.ts
  packages/nodes-base/nodes/ReadBinaryFile/ReadBinaryFile.node.ts
  packages/nodes-base/nodes/ReadBinaryFiles/ReadBinaryFiles.node.ts
  packages/nodes-base/nodes/WriteBinaryFile/WriteBinaryFile.node.ts
  packages/nodes-base/utils/utilities.ts
  packages/workflow/src/Interfaces.ts
Labels: n8n team, security

#6804 ci: Downgrade prettier (no-changelog)
  package.json
  packages/editor-ui/.eslintrc.js
  packages/editor-ui/package.json
  pnpm-lock.yaml
Labels: ui, n8n team

#6802 fix(editor): Remove additional margin on tooltip
  packages/design-system/src/css/popper.scss
  packages/design-system/src/css/tooltip.scss
Labels: ui, n8n team

#6805 fix(core): Serialize BigInts
  packages/workflow/src/types.d.ts
  packages/workflow/src/utils.ts
Labels: core, n8n team

#6807 fix(core): Fix loading of scoped-community packages
  packages/cli/src/LoadNodesAndCredentials.ts
Labels: core, n8n team

#6806 docs: Update quick start video (no-changelog)
  README.md
Labels: n8n team
