Repository n8n-io/n8n, pull requests merged in 2023-11, with the labels that each got.

#7559 feat(editor): Implement the `UserStack` design system component
  packages/design-system/src/components/N8nUserStack/UserStack.stories.ts
  packages/design-system/src/components/N8nUserStack/UserStack.vue
  packages/design-system/src/components/N8nUserStack/__tests__/UserStack.spec.ts
  packages/design-system/src/components/N8nUserStack/index.ts
  packages/design-system/src/components/index.ts
  packages/design-system/src/plugin.ts
  packages/design-system/src/types/user.ts
Labels: ui, n8n team

#7474 feat(n8n Form Trigger Node): Add text area and password input types
  packages/cli/templates/form-trigger.handlebars
  packages/nodes-base/nodes/Form/FormTrigger.node.ts
  packages/nodes-base/nodes/Form/interfaces.ts
  packages/nodes-base/nodes/Form/utils.ts
Labels: node/improvement, core, community

#7569 fix(core): Prevent executions from becoming forever running
  packages/cli/src/InternalHooks.ts
  packages/cli/src/WorkflowRunner.ts
  packages/cli/src/commands/worker.ts
  packages/cli/src/databases/repositories/execution.repository.ts
Labels: core, n8n team

#5993 feat(HTTP Request Node): Add pagination support
  packages/core/src/Constants.ts
  packages/core/src/NodeExecuteFunctions.ts
  packages/editor-ui/src/mixins/workflowHelpers.ts
  packages/nodes-base/nodes/HttpRequest/V3/HttpRequestV3.node.ts
  packages/nodes-base/nodes/HttpRequest/test/node/HttpRequest.test.ts
  packages/nodes-base/nodes/HttpRequest/test/node/workflow.pagination.json
  packages/workflow/src/Interfaces.ts
Labels: node/improvement, core, n8n team

#7573 fix: Fix dark mode small issues
  packages/design-system/src/components/N8nMarkdown/Markdown.vue
  packages/design-system/src/css/_tokens.dark.scss
  packages/design-system/src/css/_tokens.scss
  packages/editor-ui/src/components/CollectionParameter.vue
  packages/editor-ui/src/utils/nodeViewUtils.ts
Labels: ui, n8n team

#7575 fix: Update colors of syntax errors
  packages/editor-ui/src/components/CodeNodeEditor/theme.ts
Labels: ui, n8n team

#7572 feat(HTTP Request Node): Update icon and default color
  packages/nodes-base/nodes/HttpRequest/HttpRequest.node.ts
  packages/nodes-base/nodes/HttpRequest/V3/HttpRequestV3.node.ts
  packages/nodes-base/nodes/HttpRequest/httprequest.svg
Labels: node/improvement, n8n team

#7574 refactor(editor): Dark theme improvements (no-changelog)
  packages/editor-ui/src/components/CodeNodeEditor/theme.ts
  packages/editor-ui/src/components/Node.vue
  packages/editor-ui/src/mixins/nodeBase.ts
  packages/editor-ui/src/stores/ui.store.ts
  packages/editor-ui/src/utils/htmlUtils.ts
  packages/editor-ui/src/utils/nodeViewUtils.ts
Labels: ui, n8n team

#7576 fix(core): Permission check for subworkflow properly checking for workflow settings
  packages/cli/src/UserManagement/PermissionChecker.ts
  packages/cli/test/unit/PermissionChecker.test.ts
Labels: core, n8n team

#7539 feat(core): Merge & refactor vector store nodes & allow for similiarity retrieval
  packages/@n8n/nodes-langchain/nodes/chains/ChainSummarization/ChainSummarization.node.ts
  packages/@n8n/nodes-langchain/nodes/vector_store/VectorStoreInMemory/VectorStoreInMemory.node.ts
  packages/@n8n/nodes-langchain/nodes/vector_store/VectorStoreInMemoryInsert/VectorStoreInMemoryInsert.node.ts
  packages/@n8n/nodes-langchain/nodes/vector_store/VectorStoreInMemoryLoad/VectorStoreInMemoryLoad.node.ts
  packages/@n8n/nodes-langchain/nodes/vector_store/VectorStorePinecone/VectorStorePinecone.node.ts
  packages/@n8n/nodes-langchain/nodes/vector_store/VectorStorePinecone/pinecone.svg
  packages/@n8n/nodes-langchain/nodes/vector_store/VectorStorePineconeInsert/VectorStorePineconeInsert.node.ts
  packages/@n8n/nodes-langchain/nodes/vector_store/VectorStorePineconeLoad/VectorStorePineconeLoad.node.ts
  packages/@n8n/nodes-langchain/nodes/vector_store/VectorStoreSupabase/VectorStoreSupabase.node.ts
  packages/@n8n/nodes-langchain/nodes/vector_store/VectorStoreSupabase/supabase.svg
  packages/@n8n/nodes-langchain/nodes/vector_store/VectorStoreSupabaseInsert/VectorStoreSupabaseInsert.node.ts
  packages/@n8n/nodes-langchain/nodes/vector_store/VectorStoreSupabaseLoad/VectorStoreSupabaseLoad.node.ts
  packages/@n8n/nodes-langchain/nodes/vector_store/VectorStoreZep/VectorStoreZep.node.ts
  packages/@n8n/nodes-langchain/nodes/vector_store/VectorStoreZep/zep.png
  packages/@n8n/nodes-langchain/nodes/vector_store/VectorStoreZepInsert/VectorStoreZepInsert.node.ts
  packages/@n8n/nodes-langchain/nodes/vector_store/VectorStoreZepLoad/VectorStoreZepLoad.node.ts
  packages/@n8n/nodes-langchain/nodes/vector_store/shared/createVectorStoreNode.ts
  packages/@n8n/nodes-langchain/nodes/vector_store/shared/processDocuments.ts
  packages/@n8n/nodes-langchain/package.json
  packages/@n8n/nodes-langchain/utils/N8nBinaryLoader.ts
  packages/@n8n/nodes-langchain/utils/N8nJsonLoader.ts
  packages/@n8n/nodes-langchain/utils/logWrapper.ts
  packages/editor-ui/src/components/InputPanel.vue
  packages/editor-ui/src/components/Node/NodeCreator/composables/useViewStacks.ts
  packages/editor-ui/src/stores/nodeTypes.store.ts
  packages/nodes-base/credentials/SupabaseApi.credentials.ts
Labels: node/improvement, n8n team

#7408 fix(core): Fix issue that prevents owner logging in when using ldap
  packages/cli/src/Ldap/helpers.ts
  packages/cli/src/auth/methods/email.ts
  packages/cli/src/controllers/auth.controller.ts
  packages/cli/test/integration/ldap/ldap.api.test.ts
Labels: core, n8n team

#7577 ci: Remove PR checklist action (no-changelog)
  .github/workflows/checklist.yml
  CHECKLIST.yml
Labels: n8n team

#6685 feat: Handle pin data edge cases and unify validation (no-changelog)
  .github/workflows/e2e-reusable.yml
  cypress.config.js
  cypress/e2e/13-pinning.cy.ts
  cypress/pages/ndv.ts
  cypress/pages/workflow.ts
  packages/editor-ui/src/components/NodeDetailsView.vue
  packages/editor-ui/src/components/NodeExecuteButton.vue
  packages/editor-ui/src/components/RunData.vue
  packages/editor-ui/src/constants.ts
  packages/editor-ui/src/mixins/pinData.ts
  packages/editor-ui/src/plugins/i18n/locales/en.json
  packages/editor-ui/src/shims.d.ts
  packages/editor-ui/src/stores/workflows.store.ts
  packages/editor-ui/src/views/NodeView.vue
  scripts/run-e2e.js
Labels: ui, n8n team

#7578 fix(editor): Fix more dark mode issues (no-changelog)
  packages/design-system/src/css/_primitives.scss
  packages/design-system/src/css/_tokens.dark.scss
  packages/design-system/src/css/_tokens.scss
  packages/editor-ui/src/components/Node.vue
Labels: core, n8n team

#7581 feat(core): Add support for AWS Bedrock LMs & Embeddings
  packages/@n8n/nodes-langchain/nodes/embeddings/EmbeddingsAwsBedrock/EmbeddingsAwsBedrock.node.ts
  packages/@n8n/nodes-langchain/nodes/embeddings/EmbeddingsAwsBedrock/bedrock.svg
  packages/@n8n/nodes-langchain/nodes/embeddings/EmbeddingsHuggingFaceInference/EmbeddingsHuggingFaceInference.node.ts
  packages/@n8n/nodes-langchain/nodes/embeddings/EmbeddingsHuggingFaceInference/HuggingFaceEmbeddings.ts
  packages/@n8n/nodes-langchain/nodes/llms/LMOpenHuggingFaceInference/HuggingFaceInferenceEndpoints.ts
  packages/@n8n/nodes-langchain/nodes/llms/LMOpenHuggingFaceInference/LmOpenHuggingFaceInference.node.ts
  packages/@n8n/nodes-langchain/nodes/llms/LmChatAwsBedrock/LmChatAwsBedrock.node.ts
  packages/@n8n/nodes-langchain/nodes/llms/LmChatAwsBedrock/bedrock.svg
  packages/@n8n/nodes-langchain/nodes/vector_store/VectorStorePinecone/VectorStorePinecone.node.ts
  packages/@n8n/nodes-langchain/nodes/vector_store/VectorStorePineconeInsert/VectorStorePineconeInsert.node.ts
  packages/@n8n/nodes-langchain/nodes/vector_store/VectorStorePineconeLoad/VectorStorePineconeLoad.node.ts
  packages/@n8n/nodes-langchain/package.json
  pnpm-lock.yaml
Labels: n8n team

#7564 refactor(core): Create pruning service (no-changelog)
  packages/cli/src/Db.ts
  packages/cli/src/commands/start.ts
  packages/cli/src/databases/repositories/execution.repository.ts
  packages/cli/src/services/orchestration/main/MultiMainInstance.publisher.ee.ts
  packages/cli/src/services/pruning.service.ts
  packages/cli/test/integration/pruning.service.test.ts
Labels: core, n8n team

#7589 refactor: Rearrange Supabase & Pinecone vector store fields
  packages/@n8n/nodes-langchain/nodes/vector_store/VectorStorePinecone/VectorStorePinecone.node.ts
  packages/@n8n/nodes-langchain/nodes/vector_store/VectorStoreSupabase/VectorStoreSupabase.node.ts
  packages/editor-ui/src/components/Node.vue
Labels: ui, n8n team

#7586 feat(core): Log executed migrations with info level
  packages/cli/src/databases/utils/migrationHelpers.ts
Labels: core, n8n team

#7558 refactor(core): Ensure only leader handles licensing in multi-main scenario
  packages/cli/src/License.ts
  packages/cli/src/commands/BaseCommand.ts
  packages/cli/test/integration/commands/start.cmd.test.ts
Labels: core, n8n team

#7449 feat(core): Add the node version to telemetry in node_graph_string
  packages/workflow/src/Interfaces.ts
  packages/workflow/src/TelemetryHelpers.ts
Labels: n8n team

#7591 fix(editor): Allow overriding theme from query params
  cypress/e2e/31-demo.cy.ts
  cypress/pages/demo.ts
  cypress/pages/templates.ts
  packages/editor-ui/src/stores/ui.store.ts
  packages/editor-ui/src/stores/ui.utils.ts
Labels: ui, n8n team

#7587 refactor(core): Stop reporting to Sentry node parameter value extraction failure (no-changelog)
  packages/core/src/ExtractValue.ts
Labels: core, n8n team

#7582 fix(editor): Remove unknown credentials on pasting workflow
  cypress/e2e/12-canvas.cy.ts
  cypress/fixtures/workflow-with-unknown-credentials.json
  packages/editor-ui/src/views/NodeView.vue
Labels: ui, n8n team

#7594 docs: Update vector-store docs links
  packages/@n8n/nodes-langchain/nodes/vector_store/VectorStoreInMemory/VectorStoreInMemory.node.ts
  packages/@n8n/nodes-langchain/nodes/vector_store/VectorStorePinecone/VectorStorePinecone.node.ts
  packages/@n8n/nodes-langchain/nodes/vector_store/VectorStoreSupabase/VectorStoreSupabase.node.ts
  packages/@n8n/nodes-langchain/nodes/vector_store/VectorStoreZep/VectorStoreZep.node.ts
Labels: n8n team

#7489 feat(LinkedIn Node): Add support for Article thumbnails
  packages/nodes-base/nodes/LinkedIn/LinkedIn.node.ts
  packages/nodes-base/nodes/LinkedIn/PostDescription.ts
Labels: node/improvement, n8n team

#7585 refactor(core): Consolidate binary file not found errors (no-changelog)
  packages/core/src/BinaryData/BinaryData.service.ts
  packages/core/src/BinaryData/FileSystem.manager.ts
  packages/core/src/BinaryData/utils.ts
  packages/core/src/decorators/LogCatch.decorator.ts
  packages/core/src/errors.ts
  packages/core/test/FileSystem.manager.test.ts
Labels: core, n8n team

#7568 refactor(editor): Simplify data count in NDV (no-changelog)
  packages/editor-ui/src/components/InputPanel.vue
  packages/editor-ui/src/components/OutputPanel.vue
  packages/editor-ui/src/components/RunData.vue
Labels: ui, n8n team

#7597 fix(editor): Hide not supported node options
  packages/editor-ui/src/components/NodeSettings.vue
Labels: ui, n8n team

#7598 fix(core): Decrease reset password token expire time
  packages/cli/src/UserManagement/email/templates/passwordReset.html
  packages/cli/src/controllers/passwordReset.controller.ts
Labels: core, n8n team

#7601 feat(editor): Update storybook to 7.5.2 (no-changelog)
  packages/design-system/.storybook/main.ts
  packages/design-system/package.json
  packages/design-system/public/.nojekyll
  pnpm-lock.yaml
Labels: ui, n8n team

#7556 refactor(core): Migrate from crypto-js to native crypto
  packages/core/package.json
  packages/core/src/Cipher.ts
  packages/core/test/Cipher.test.ts
  pnpm-lock.yaml
Labels: core, n8n team

#7602 fix(editor): Zoom in/out on canvas the same amount on scroll/gesture
  cypress/e2e/12-canvas.cy.ts
  cypress/pages/workflow.ts
  packages/editor-ui/src/utils/canvasUtils.ts
Labels: ui, n8n team

#7567 feat(editor): Improve performance by importing routes dynamically and add route guards (no-changelog)
  cypress/e2e/10-undo-redo.cy.ts
  cypress/e2e/12-canvas.cy.ts
  cypress/e2e/17-sharing.cy.ts
  cypress/e2e/25-stickies.cy.ts
  cypress/e2e/27-opt-in-trial-banner.cy.ts
  cypress/e2e/7-workflow-actions.cy.ts
  cypress/pages/ndv.ts
  cypress/pages/workflow.ts
  cypress/support/commands.ts
  cypress/support/e2e.ts
  cypress/support/index.ts
  packages/design-system/src/css/reset.scss
  packages/editor-ui/src/App.vue
  packages/editor-ui/src/Interface.ts
  packages/editor-ui/src/__tests__/router.test.ts
  packages/editor-ui/src/__tests__/server/endpoints/settings.ts
  packages/editor-ui/src/components/layouts/PageViewLayout.vue
  packages/editor-ui/src/main.ts
  packages/editor-ui/src/router.ts
  packages/editor-ui/src/stores/settings.store.ts
  packages/editor-ui/src/stores/users.store.ts
Labels: ui, n8n team

#7583 feat(editor): Fix some UTM tags (no-changelog)
  packages/editor-ui/src/components/CredentialEdit/CredentialConfig.vue
  packages/editor-ui/src/components/MainSidebar.vue
Labels: ui, n8n team

#5973 refactor(core): Convert OAuth1/OAuth2 controllers to decorated controller classes (no-changelog)
  packages/cli/src/CredentialsHelper.ts
  packages/cli/src/Server.ts
  packages/cli/src/controllers/index.ts
  packages/cli/src/controllers/oauth/abstractOAuth.controller.ts
  packages/cli/src/controllers/oauth/oAuth1Credential.controller.ts
  packages/cli/src/controllers/oauth/oAuth2Credential.controller.ts
  packages/cli/src/credentials/oauth2Credential.api.ts
  packages/cli/src/databases/repositories/sharedCredentials.repository.ts
  packages/cli/src/decorators/Route.ts
  packages/cli/src/decorators/registerController.ts
  packages/cli/src/decorators/types.ts
  packages/cli/src/middlewares/auth.ts
  packages/cli/src/requests.ts
  packages/cli/templates/oauth-callback.handlebars
  packages/cli/test/unit/controllers/oAuth1Credential.controller.test.ts
  packages/cli/test/unit/controllers/oAuth2Credential.controller.test.ts
  packages/cli/test/unit/repositories/sharedCredentials.repository.test.ts
Labels: core, n8n team

#7604 feat(core): Rate limit forgot password endpoint
  packages/cli/package.json
  packages/cli/src/AbstractServer.ts
  packages/cli/src/config/schema.ts
  packages/cli/src/controllers/passwordReset.controller.ts
  packages/editor-ui/src/plugins/i18n/locales/en.json
  packages/editor-ui/src/views/ForgotMyPasswordView.vue
  pnpm-lock.yaml
Labels: core, n8n team

#7610 fix(editor): Focus mfa token input (no-changelog)
  packages/editor-ui/src/views/MfaView.vue
Labels: ui, n8n team

#7617 refactor(Google Sheets Node): Stop reporting to Sentry sheet not found error (no-changelog)
  packages/nodes-base/nodes/Google/Sheet/GoogleSheetsTrigger.node.ts
  packages/nodes-base/nodes/Google/Sheet/v2/actions/router.ts
  packages/nodes-base/nodes/Google/Sheet/v2/helpers/GoogleSheet.ts
  packages/nodes-base/nodes/Google/Sheet/v2/methods/loadOptions.ts
  packages/nodes-base/nodes/Google/Sheet/v2/methods/resourceMapping.ts
Labels: node/improvement, n8n team

#7621 fix(core): Ensure `init` before checking leader or follower in multi-main scenario
  packages/cli/src/License.ts
  packages/cli/src/commands/BaseCommand.ts
  packages/cli/src/commands/start.ts
  packages/cli/src/services/orchestration/main/MultiMainInstance.publisher.ee.ts
  packages/cli/src/services/pruning.service.ts
Labels: core, n8n team

#7596 fix(editor): Fix issue that frontend breaks with unkown nodes
  cypress/e2e/12-canvas.cy.ts
  cypress/fixtures/workflow-with-unknown-nodes.json
  packages/editor-ui/src/components/Node.vue
Labels: ui, n8n team

#7618 fix(core): Fix accessor error when running partial execution
  packages/core/src/WorkflowExecute.ts
Labels: core, n8n team

#7624 fix(editor): More dark-mode fixes (no-changelog)
  packages/editor-ui/src/components/MfaSetupModal.vue
  packages/editor-ui/src/components/SSOLogin.vue
  packages/editor-ui/src/views/MfaView.vue
Labels: ui, n8n team

#7625 fix(editor): Reset canvas zoom before workspace reset in node view
  cypress/e2e/30-editor-after-route-changes.cy.ts
  cypress/fixtures/Lots_of_nodes.json
  packages/editor-ui/src/views/NodeView.vue
Labels: ui, n8n team

#7603 fix(editor): Fix local storage flags defaulting to undefined string
  packages/editor-ui/src/components/ActivationModal.vue
  packages/editor-ui/src/components/NDVDraggablePanels.vue
  packages/editor-ui/src/components/Node.vue
  packages/editor-ui/src/components/RunData.vue
  packages/editor-ui/src/composables/useStorage.test.ts
  packages/editor-ui/src/composables/useStorage.ts
  packages/editor-ui/src/mixins/workflowActivate.ts
  packages/editor-ui/src/router.ts
  packages/editor-ui/src/stores/__tests__/posthog.test.ts
  packages/editor-ui/src/stores/ndv.store.ts
  packages/editor-ui/src/stores/posthog.store.ts
  packages/editor-ui/src/stores/ui.utils.ts
Labels: ui, n8n team

#7566 feat(core): Coordinate workflow activation in multiple main scenario in internal API
  packages/cli/src/ActiveWorkflowRunner.ts
  packages/cli/src/Interfaces.ts
  packages/cli/src/Server.ts
  packages/cli/src/commands/start.ts
  packages/cli/src/databases/entities/WorkflowEntity.ts
  packages/cli/src/databases/repositories/workflow.repository.ts
  packages/cli/src/services/orchestration.base.service.ts
  packages/cli/src/services/orchestration/main/MultiMainInstance.publisher.ee.ts
  packages/cli/test/integration/ActiveWorkflowRunner.test.ts
  packages/cli/test/integration/shared/testDb.ts
  packages/cli/test/integration/shared/utils/index.ts
  packages/cli/test/unit/ActiveWorkflowRunner.test.ts
  packages/core/src/ActiveWorkflows.ts
  packages/workflow/src/Interfaces.ts
  packages/workflow/src/WorkflowActivationError.ts
Labels: core, n8n team

#7626 fix(core): Ensure pruning starts only after migrations have completed
  packages/cli/src/Db.ts
  packages/cli/src/commands/start.ts
  packages/cli/src/services/pruning.service.ts
Labels: core, n8n team

#7638 docs: Update two docs links
  packages/@n8n/nodes-langchain/nodes/memory/MemoryChatRetriever/MemoryChatRetriever.node.ts
  packages/@n8n/nodes-langchain/nodes/trigger/ManualChatTrigger/ManualChatTrigger.node.ts
Labels: n8n team

#7633 fix: Error handling on forgot password page (no-changelog)
  packages/cli/src/controllers/passwordReset.controller.ts
  packages/editor-ui/src/views/ForgotMyPasswordView.vue
Labels: core, ui, n8n team

#7622 fix(core): Make password-reset urls valid only for single-use
  packages/cli/src/Server.ts
  packages/cli/src/auth/jwt.ts
  packages/cli/src/controllers/passwordReset.controller.ts
  packages/cli/src/controllers/users.controller.ts
  packages/cli/src/services/jwt.service.ts
  packages/cli/src/services/user.service.ts
  packages/cli/test/integration/mfa/mfa.api.test.ts
  packages/cli/test/integration/passwordReset.api.test.ts
  packages/cli/test/integration/shared/utils/testServer.ts
  packages/cli/test/unit/services/user.service.test.ts
  packages/editor-ui/src/plugins/i18n/locales/en.json
  packages/editor-ui/src/views/ChangePasswordView.vue
  packages/editor-ui/src/views/SignupView.vue
Labels: core, n8n team

#7550 ci(core): Load config schema after process.env has been overwritten (no-changelog)
  packages/cli/src/Server.ts
  packages/cli/src/commands/start.ts
  packages/cli/src/config/index.ts
  packages/cli/src/constants.ts
  packages/cli/src/services/frontend.service.ts
  packages/cli/test/integration/commands/start.cmd.test.ts
  packages/core/src/InstanceSettings.ts
Labels: core, n8n team

#7641 ci: Conditionally re-enable coverage for frontend packages (no-changelog)
  packages/design-system/vite.config.ts
Labels: ui, n8n team

#7570 feat(core): Initial support for two-way communication over websockets
  packages/cli/src/Interfaces.ts
  packages/cli/src/LoadNodesAndCredentials.ts
  packages/cli/src/collaboration/collaboration.message.ts
  packages/cli/src/collaboration/collaboration.service.ts
  packages/cli/src/collaboration/collaboration.state.ts
  packages/cli/src/controllers/communityPackages.controller.ts
  packages/cli/src/eventbus/MessageEventBus/recoverEvents.ts
  packages/cli/src/push/abstract.push.ts
  packages/cli/src/push/index.ts
  packages/cli/src/push/sse.push.ts
  packages/cli/src/push/types.ts
  packages/cli/src/push/websocket.push.ts
  packages/cli/test/unit/collaboration/collaboration.service.test.ts
  packages/cli/test/unit/push/websocket.push.test.ts
Labels: core, n8n team

#7634 fix(core): Comply with custom default for workflow saving settings
  packages/cli/src/executionLifecycleHooks/toSaveSettings.ts
  packages/cli/test/unit/execution.lifecycle.test.ts
Labels: core, n8n team

#7644 fix(editor): Fix workflow history prune time limit (getting hours instead of days)
  packages/editor-ui/src/views/WorkflowHistory.vue
Labels: ui, n8n team

#7648 refactor(core): Stop reporting to Sentry missing-node-on-retry error (no-changelog)
  packages/cli/src/executions/executions.service.ts
Labels: core, n8n team, skip-e2e

#7616 fix(Facebook Lead Ads Trigger Node): Fix issue with missing scope for business management
  packages/nodes-base/credentials/FacebookLeadAdsOAuth2Api.credentials.ts
Labels: node/improvement, community

#7329 feat(NocoDB Node): Add new data apis and workspace support
  packages/nodes-base/nodes/NocoDB/NocoDB.node.ts
  packages/nodes-base/nodes/NocoDB/OperationDescription.ts
  packages/nodes-base/nodes/NocoDB/nocodb.svg
Labels: node/improvement, community, in linear

#7619 fix(Crypto Node): Fix issue with value not appearing for Sign action
  packages/nodes-base/nodes/Crypto/Crypto.node.ts
Labels: node/improvement, n8n team

#7456 feat(editor): Add workflow filters to querystring
  cypress/e2e/30-workflow-filters.cy.ts
  cypress/pages/workflows.ts
  packages/design-system/src/components/N8nUserInfo/UserInfo.vue
  packages/design-system/src/components/N8nUserSelect/UserSelect.vue
  packages/editor-ui/src/components/TagsDropdown.vue
  packages/editor-ui/src/components/layouts/ResourcesListLayout.vue
  packages/editor-ui/src/views/WorkflowsView.vue
Labels: ui, n8n team

#7640 feat(core): Langchain nodes tweaks
  packages/@n8n/nodes-langchain/nodes/agents/Agent/Agent.node.ts
  packages/@n8n/nodes-langchain/nodes/agents/Agent/agents/ConversationalAgent/execute.ts
  packages/@n8n/nodes-langchain/nodes/chains/ChainLLM/ChainLlm.node.ts
  packages/@n8n/nodes-langchain/nodes/chains/ChainRetrievalQA/ChainRetrievalQa.node.ts
  packages/@n8n/nodes-langchain/nodes/chains/ChainSummarization/ChainSummarization.node.ts
  packages/@n8n/nodes-langchain/nodes/tools/ToolCalculator/ToolCalculator.node.ts
  packages/@n8n/nodes-langchain/nodes/tools/ToolCode/ToolCode.node.ts
  packages/@n8n/nodes-langchain/nodes/tools/ToolSerpApi/ToolSerpApi.node.ts
  packages/@n8n/nodes-langchain/nodes/tools/ToolWorkflow/ToolWorkflow.node.ts
  packages/@n8n/nodes-langchain/nodes/vector_store/VectorStoreZepInsert/VectorStoreZepInsert.node.ts
  packages/@n8n/nodes-langchain/utils/logWrapper.ts
  packages/editor-ui/src/components/WorkflowLMChat.vue
  packages/nodes-base/credentials/OpenAiApi.credentials.ts
  packages/nodes-base/nodes/Code/JavaScriptSandbox.ts
Labels: node/improvement, n8n team

#7654 ci(core): Reduce memory usage in tests (part-1) (no-changelog)
  packages/cli/src/Server.ts
  packages/cli/src/WorkflowRunner.ts
  packages/cli/src/controllers/index.ts
  packages/cli/src/controllers/mfa.controller.ts
  packages/cli/test/integration/ActiveWorkflowRunner.test.ts
  packages/cli/test/integration/ExternalSecrets/externalSecrets.api.test.ts
  packages/cli/test/integration/auth.api.test.ts
  packages/cli/test/integration/auth.mw.test.ts
  packages/cli/test/integration/binaryData.api.test.ts
  packages/cli/test/integration/commands/credentials.cmd.test.ts
  packages/cli/test/integration/commands/import.cmd.test.ts
  packages/cli/test/integration/commands/reset.cmd.test.ts
  packages/cli/test/integration/community-packages.api.test.ts
  packages/cli/test/integration/credentials.controller.test.ts
  packages/cli/test/integration/credentials.ee.test.ts
  packages/cli/test/integration/credentials.test.ts
  packages/cli/test/integration/environments/SourceControl.test.ts
  packages/cli/test/integration/eventbus.ee.test.ts
  packages/cli/test/integration/eventbus.test.ts
  packages/cli/test/integration/executions.controller.test.ts
  packages/cli/test/integration/ldap/ldap.api.test.ts
  packages/cli/test/integration/license.api.test.ts
  packages/cli/test/integration/me.api.test.ts
  packages/cli/test/integration/mfa/mfa.api.test.ts
  packages/cli/test/integration/owner.api.test.ts
  packages/cli/test/integration/passwordReset.api.test.ts
  packages/cli/test/integration/pruning.service.test.ts
  packages/cli/test/integration/publicApi/credentials.test.ts
  packages/cli/test/integration/publicApi/executions.test.ts
  packages/cli/test/integration/publicApi/users.ee.test.ts
  packages/cli/test/integration/publicApi/workflows.test.ts
  packages/cli/test/integration/saml/saml.api.test.ts
  packages/cli/test/integration/shared/db/credentials.ts
  packages/cli/test/integration/shared/db/executions.ts
  packages/cli/test/integration/shared/db/roles.ts
  packages/cli/test/integration/shared/db/tags.ts
  packages/cli/test/integration/shared/db/users.ts
  packages/cli/test/integration/shared/db/workflowHistory.ts
  packages/cli/test/integration/shared/db/workflows.ts
  packages/cli/test/integration/shared/testDb.ts
  packages/cli/test/integration/shared/types.ts
  packages/cli/test/integration/shared/utils/index.ts
  packages/cli/test/integration/shared/utils/testServer.ts
  packages/cli/test/integration/tags.api.test.ts
  packages/cli/test/integration/users.api.test.ts
  packages/cli/test/integration/users.controller.test.ts
  packages/cli/test/integration/variables.test.ts
  packages/cli/test/integration/webhooks.api.test.ts
  packages/cli/test/integration/workflowHistory.api.test.ts
  packages/cli/test/integration/workflowHistoryManager.test.ts
  packages/cli/test/integration/workflows.controller.ee.test.ts
  packages/cli/test/integration/workflows.controller.test.ts
  packages/cli/test/unit/CredentialsHelper.test.ts
  packages/cli/test/unit/InternalHooks.test.ts
  packages/cli/test/unit/PermissionChecker.test.ts
  packages/cli/test/unit/WorkflowRunner.test.ts
  packages/cli/test/unit/controllers/me.controller.test.ts
  packages/cli/test/unit/controllers/owner.controller.test.ts
Labels: core, n8n team

#7650 feat: Add permissions package (no-changelog)
  packages/@n8n/permissions/.eslintrc.js
  packages/@n8n/permissions/jest.config.js
  packages/@n8n/permissions/package.json
  packages/@n8n/permissions/src/hasScope.ts
  packages/@n8n/permissions/src/index.ts
  packages/@n8n/permissions/src/types.ts
  packages/@n8n/permissions/test/hasScope.test.ts
  packages/@n8n/permissions/tsconfig.build.json
  packages/@n8n/permissions/tsconfig.json
  pnpm-lock.yaml
Labels: n8n team

#7668 ci: Disable Workflow filters e2e tests to unblock the CI (no-changelog)
  cypress/e2e/30-workflow-filters.cy.ts
Labels: n8n team

#7669 ci: Stop disabling linting rules that are explicitly set to `warn` (no-changelog)
  packages/cli/src/ActiveExecutions.ts
  packages/cli/src/ExternalHooks.ts
  packages/cli/src/ExternalSecrets/ExternalSecrets.service.ee.ts
  packages/cli/src/ExternalSecrets/providers/vault.ts
  packages/cli/src/Interfaces.ts
  packages/cli/src/Logger.ts
  packages/cli/src/ResponseHelper.ts
  packages/cli/src/WebhookHelpers.ts
  packages/cli/src/WorkflowExecuteAdditionalData.ts
  packages/cli/src/WorkflowHelpers.ts
  packages/cli/src/WorkflowRunner.ts
  packages/cli/src/WorkflowRunnerProcess.ts
  packages/cli/src/credentials/credentials.service.ts
  packages/cli/src/decorators/Authorized.ts
  packages/cli/src/eventbus/MessageEventBusDestination/MessageEventBusDestinationWebhook.ee.ts
  packages/cli/src/eventbus/MessageEventBusWriter/MessageEventBusLogWriterWorker.ts
  packages/cli/src/eventbus/eventBus.controller.ee.ts
  packages/cli/src/executions/executions.service.ts
  packages/cli/test/integration/eventbus.ee.test.ts
  packages/cli/test/integration/shared/testDb.ts
  packages/cli/test/integration/workflowHistory.api.test.ts
  packages/cli/test/unit/execution.lifecycle.test.ts
  packages/cli/test/unit/services/cache.service.test.ts
  packages/cli/test/unit/services/orchestration.service.test.ts
  packages/cli/test/unit/services/redis.service.test.ts
Labels: core, n8n team

#7663 fix(core): Reduce memory usage in credentials risk auditing
  packages/cli/src/audit/risks/credentials.risk.ts
Labels: core, ui, n8n team

#7659 feat(Microsoft Excel 365 Node): Alias update (no-changelog)
  packages/nodes-base/nodes/Google/Sheet/GoogleSheets.node.json
  packages/nodes-base/nodes/Microsoft/Excel/MicrosoftExcel.node.json
  packages/nodes-base/nodes/SpreadsheetFile/SpreadsheetFile.node.json
Labels: node/improvement, n8n team

#7661 feat(Date & Time Node): Option to include other fields in output item
  packages/nodes-base/nodes/DateTime/DateTime.node.ts
  packages/nodes-base/nodes/DateTime/V2/AddToDateDescription.ts
  packages/nodes-base/nodes/DateTime/V2/CurrentDateDescription.ts
  packages/nodes-base/nodes/DateTime/V2/DateTimeV2.node.ts
  packages/nodes-base/nodes/DateTime/V2/ExtractDateDescription.ts
  packages/nodes-base/nodes/DateTime/V2/FormatDateDescription.ts
  packages/nodes-base/nodes/DateTime/V2/GetTimeBetweenDates.ts
  packages/nodes-base/nodes/DateTime/V2/RoundDateDescription.ts
  packages/nodes-base/nodes/DateTime/V2/SubtractFromDateDescription.ts
  packages/nodes-base/nodes/DateTime/V2/common.descriptions.ts
  packages/nodes-base/nodes/DateTime/test/node/workflow.includeInputFields_v2.json
Labels: node/improvement, n8n team, node/issue

#7667 docs(Send Email Node): Add description to Email Format (no-changelog)
  packages/nodes-base/nodes/EmailSend/v2/send.operation.ts
Labels: node/improvement, n8n team

#7670 refactor: Add rule `no-constant-binary-expression` (no-changelog)
  packages/@n8n_io/eslint-config/base.js
  packages/cli/src/PublicApi/index.ts
  packages/cli/src/environments/sourceControl/sourceControlGit.service.ee.ts
  packages/core/src/WorkflowExecutionMetadata.ts
  packages/design-system/src/components/N8nMarkdown/Markdown.vue
  packages/editor-ui/src/components/Node/NodeCreator/Renderers/ItemsRenderer.vue
  packages/editor-ui/src/views/NodeView.vue
  packages/nodes-base/nodes/ClickUp/ClickUp.node.ts
  packages/nodes-base/nodes/HaloPSA/GenericFunctions.ts
  packages/nodes-base/nodes/Odoo/GenericFunctions.ts
  packages/nodes-base/utils/utilities.ts
Labels: node/improvement, core, ui, n8n team

#7632 feat: Add Plan and Execute Agent Type
  packages/@n8n/nodes-langchain/nodes/agents/Agent/Agent.node.ts
  packages/@n8n/nodes-langchain/nodes/agents/Agent/agents/PlanAndExecuteAgent/description.ts
  packages/@n8n/nodes-langchain/nodes/agents/Agent/agents/PlanAndExecuteAgent/execute.ts
  packages/@n8n/nodes-langchain/nodes/agents/Agent/agents/PlanAndExecuteAgent/prompt.ts
Labels: community

#7664 fix(editor): Fix resource mapper component being truncated
  packages/editor-ui/src/components/NodeSettings.vue
  packages/editor-ui/src/components/ResourceLocator/ResourceLocatorDropdown.vue
Labels: ui, n8n team

#7675 fix(Date & Time Node): Add fromFormat option to solve ambiguous date strings
  packages/nodes-base/nodes/DateTime/V2/DateTimeV2.node.ts
  packages/nodes-base/nodes/DateTime/V2/FormatDateDescription.ts
  packages/nodes-base/nodes/DateTime/V2/GenericFunctions.ts
Labels: node/improvement, n8n team

#7656 ci: Auto-cancel redundant CI jobs (no-changelog)
  .github/workflows/ci-master.yml
  .github/workflows/ci-postgres-mysql.yml
  .github/workflows/e2e-tests-pr.yml
Labels: n8n team

#7658 test: Unify users.controller.test and users.api.test (no-changelog)
  packages/cli/test/integration/users.api.test.ts
  packages/cli/test/integration/users.controller.test.ts
Labels: core, n8n team

#7600 feat(editor): Adds a EE view to show worker details and job status
  cypress/e2e/32-worker-view.cy.ts
  cypress/pages/index.ts
  cypress/pages/workerView.ts
  cypress/support/commands.ts
  cypress/support/index.ts
  packages/cli/src/Interfaces.ts
  packages/cli/src/License.ts
  packages/cli/src/constants.ts
  packages/cli/src/controllers/e2e.controller.ts
  packages/cli/src/controllers/orchestration.controller.ts
  packages/cli/src/services/frontend.service.ts
  packages/cli/src/services/orchestration/main/handleWorkerResponseMessageMain.ts
  packages/cli/src/services/orchestration/worker/handleCommandMessageWorker.ts
  packages/cli/src/services/redis/RedisServiceCommands.ts
  packages/editor-ui/package.json
  packages/editor-ui/src/Interface.ts
  packages/editor-ui/src/__tests__/server/endpoints/settings.ts
  packages/editor-ui/src/api/orchestration.ts
  packages/editor-ui/src/components/MainSidebar.vue
  packages/editor-ui/src/components/WorkerList.ee.vue
  packages/editor-ui/src/components/Workers/WorkerAccordion.ee.vue
  packages/editor-ui/src/components/Workers/WorkerCard.ee.vue
  packages/editor-ui/src/components/Workers/WorkerChartsAccordion.ee.vue
  packages/editor-ui/src/components/Workers/WorkerJobAccordion.ee.vue
  packages/editor-ui/src/components/Workers/WorkerNetAccordion.ee.vue
  packages/editor-ui/src/constants.ts
  packages/editor-ui/src/main.ts
  packages/editor-ui/src/mixins/pushConnection.ts
  packages/editor-ui/src/plugins/chartjs.ts
  packages/editor-ui/src/plugins/i18n/locales/en.json
  packages/editor-ui/src/plugins/icons/index.ts
  packages/editor-ui/src/plugins/index.ts
  packages/editor-ui/src/router.ts
  packages/editor-ui/src/stores/orchestration.store.ts
  packages/editor-ui/src/stores/settings.store.ts
  packages/editor-ui/src/utils/workerUtils.ts
  packages/editor-ui/src/views/WorkerView.vue
  packages/workflow/src/Interfaces.ts
  pnpm-lock.yaml
Labels: core, ui, n8n team

#7689 feat(Venafi TLS Protect Cloud Node): Add region parameter to Venafi protect cloud
  packages/nodes-base/credentials/VenafiTlsProtectCloudApi.credentials.ts
  packages/nodes-base/nodes/Venafi/ProtectCloud/GenericFunctions.ts
Labels: node/improvement, n8n team

#7696 perf(core): Lazyload security audit reporters
  packages/cli/src/PublicApi/types.ts
  packages/cli/src/PublicApi/v1/handlers/audit/audit.handler.ts
  packages/cli/src/audit/index.ts
  packages/cli/src/audit/risks/credentials.risk.ts
  packages/cli/src/audit/risks/database.risk.ts
  packages/cli/src/audit/risks/filesystem.risk.ts
  packages/cli/src/audit/risks/instance.risk.ts
  packages/cli/src/audit/risks/nodes.risk.ts
  packages/cli/src/commands/audit.ts
  packages/cli/src/security-audit/SecurityAudit.service.ts
  packages/cli/src/security-audit/constants.ts
  packages/cli/src/security-audit/risk-reporters/CredentialsRiskReporter.ts
  packages/cli/src/security-audit/risk-reporters/DatabaseRiskReporter.ts
  packages/cli/src/security-audit/risk-reporters/FilesystemRiskReporter.ts
  packages/cli/src/security-audit/risk-reporters/InstanceRiskReporter.ts
  packages/cli/src/security-audit/risk-reporters/NodesRiskReporter.ts
  packages/cli/src/security-audit/types.ts
  packages/cli/src/security-audit/utils.ts
  packages/cli/test/integration/security-audit/CredentialsRiskReporter.test.ts
  packages/cli/test/integration/security-audit/DatabaseRiskReporter.test.ts
  packages/cli/test/integration/security-audit/FilesystemRiskReporter.test.ts
  packages/cli/test/integration/security-audit/InstanceRiskReporter.test.ts
  packages/cli/test/integration/security-audit/NodesRiskReporter.test.ts
  packages/cli/test/integration/security-audit/utils.ts
Labels: core, n8n team

#7697 fix(core): Send pairedItem error to Posthog (no-changelog)
  packages/editor-ui/src/mixins/pushConnection.ts
Labels: n8n team

#7660 feat(core): Expression function $ifEmpty
  packages/editor-ui/src/components/CodeNodeEditor/completions/base.completions.ts
  packages/editor-ui/src/constants.ts
  packages/editor-ui/src/plugins/codemirror/completions/dollar.completions.ts
  packages/editor-ui/src/plugins/i18n/index.ts
  packages/editor-ui/src/plugins/i18n/locales/en.json
  packages/workflow/src/Extensions/ExtendedFunctions.ts
  packages/workflow/test/ExpressionExtensions/ExpressionExtension.test.ts
Labels: n8n team

#7672 fix(HubSpot Node): Fetching available parameters fails when using expressions
  packages/workflow/src/NodeHelpers.ts
  packages/workflow/test/NodeHelpers.test.ts
Labels: core, n8n team

#7695 ci: Rename build alerts channel (no-changelog)
  .github/workflows/check-documentation-urls.yml
  .github/workflows/ci-master.yml
  .github/workflows/ci-postgres-mysql.yml
  .github/workflows/e2e-tests.yml
  .github/workflows/test-workflows.yml
Labels: n8n team

#5491 feat: Rewrite Front End cloud and posthog hooks using TypeScript (no-changelog)
  packages/editor-ui/package.json
  packages/editor-ui/src/App.vue
  packages/editor-ui/src/Interface.ts
  packages/editor-ui/src/components/MainSidebar.vue
  packages/editor-ui/src/components/Node/NodeCreator/Modes/ActionsMode.vue
  packages/editor-ui/src/components/Node/NodeCreator/Panel/SearchBar.vue
  packages/editor-ui/src/components/Node/NodeCreator/composables/useActions.ts
  packages/editor-ui/src/components/ParameterInput.vue
  packages/editor-ui/src/components/PersonalizationModal.vue
  packages/editor-ui/src/components/RunDataSchema.vue
  packages/editor-ui/src/components/VariablesRow.vue
  packages/editor-ui/src/components/__tests__/BannersStack.test.ts
  packages/editor-ui/src/components/__tests__/VariablesRow.spec.ts
  packages/editor-ui/src/components/banners/TrialBanner.vue
  packages/editor-ui/src/components/banners/TrialOverBanner.vue
  packages/editor-ui/src/components/banners/V1Banner.vue
  packages/editor-ui/src/composables/useExternalHooks.ts
  packages/editor-ui/src/hooks/cloud.ts
  packages/editor-ui/src/hooks/index.ts
  packages/editor-ui/src/hooks/init.ts
  packages/editor-ui/src/hooks/segment/getters.ts
  packages/editor-ui/src/hooks/segment/index.ts
  packages/editor-ui/src/hooks/types.ts
  packages/editor-ui/src/hooks/utils/hooksAddAdminIcon.ts
  packages/editor-ui/src/hooks/utils/hooksAddAutoLoginToAdminPanelButton.ts
  packages/editor-ui/src/hooks/utils/hooksAddFakeDoorFeatures.ts
  packages/editor-ui/src/hooks/utils/hooksNodesPanel.ts
  packages/editor-ui/src/hooks/utils/index.ts
  packages/editor-ui/src/main.ts
  packages/editor-ui/src/mixins/externalHooks.ts
  packages/editor-ui/src/router.ts
  packages/editor-ui/src/shims.d.ts
  packages/editor-ui/src/stores/posthog.store.ts
  packages/editor-ui/src/stores/segment.store.ts
  packages/editor-ui/src/stores/settings.store.ts
  packages/editor-ui/src/stores/webhooks.store.ts
  packages/editor-ui/src/types/externalHooks.ts
  packages/editor-ui/src/types/index.ts
  packages/editor-ui/src/utils/externalHooks.ts
  packages/editor-ui/src/views/__tests__/SettingsExternalSecrets.test.ts
  packages/editor-ui/src/views/__tests__/SettingsPersonalView.test.ts
Labels: core, ui, n8n team

#7693 fix(Convert to/from binary data Node): Better mime type defaults
  packages/nodes-base/nodes/MoveBinaryData/MoveBinaryData.node.ts
  packages/nodes-base/nodes/MoveBinaryData/test/MoveBinaryData.test.ts
Labels: node/improvement, n8n team, node/issue

#7699 fix(core): Consider subworkflows successfully run when in waiting state
  packages/cli/src/WorkflowExecuteAdditionalData.ts
Labels: core, n8n team, skip-e2e

#7701 fix(Spreadsheet File Node): Read file as utf-8 in v1
  packages/nodes-base/nodes/SpreadsheetFile/test/SpreadsheetFile.test.ts
  packages/nodes-base/nodes/SpreadsheetFile/test/utf8.csv
  packages/nodes-base/nodes/SpreadsheetFile/test/workflow.utf8.json
  packages/nodes-base/nodes/SpreadsheetFile/v1/SpreadsheetFileV1.node.ts
Labels: node/improvement, n8n team

#7679 feat(Telegram Node): Add support for markdownv2
  packages/nodes-base/nodes/Telegram/Telegram.node.ts
Labels: node/improvement, n8n team

#7655 feat(OpenAI Node): Add dall-e-3 support
  packages/nodes-base/nodes/OpenAi/ChatDescription.ts
  packages/nodes-base/nodes/OpenAi/ImageDescription.ts
  packages/nodes-base/nodes/OpenAi/TextDescription.ts
Labels: node/improvement, n8n team

#7680 fix: Prevent hanging AI executions
  packages/@n8n/nodes-langchain/nodes/agents/Agent/agents/PlanAndExecuteAgent/execute.ts
  packages/@n8n/nodes-langchain/nodes/agents/Agent/agents/ReActAgent/execute.ts
  packages/@n8n/nodes-langchain/nodes/agents/Agent/agents/SqlAgent/execute.ts
  packages/@n8n/nodes-langchain/nodes/chains/ChainSummarization/ChainSummarization.node.ts
  packages/@n8n/nodes-langchain/nodes/llms/LMChatOpenAi/LmChatOpenAi.node.ts
  packages/@n8n/nodes-langchain/nodes/llms/LMOpenAi/LmOpenAi.node.ts
  packages/@n8n/nodes-langchain/utils/logWrapper.ts
  packages/cli/src/ActiveExecutions.ts
  packages/cli/src/Interfaces.ts
  packages/cli/src/WorkflowExecuteAdditionalData.ts
  packages/cli/src/WorkflowRunner.ts
  packages/cli/src/WorkflowRunnerProcess.ts
  packages/cli/src/commands/worker.ts
  packages/core/src/NodeExecuteFunctions.ts
  packages/core/src/WorkflowExecute.ts
  packages/editor-ui/src/mixins/pushConnection.ts
  packages/nodes-base/nodes/Wait/Wait.node.ts
  packages/workflow/src/Interfaces.ts
  packages/workflow/src/RoutingNode.ts
  packages/workflow/src/Workflow.ts
Labels: node/improvement, core, n8n team

#7599 fix(editor): Dark mode switch style fix and other tweaks (no-changelog)
  packages/design-system/src/components/N8nBlockUi/BlockUi.vue
  packages/design-system/src/components/N8nLink/Link.vue
  packages/design-system/src/css/_primitives.scss
  packages/design-system/src/css/_tokens.dark.scss
  packages/design-system/src/css/_tokens.scss
  packages/design-system/src/css/common/var.scss
  packages/design-system/src/css/switch.scss
  packages/editor-ui/src/components/NodeDetailsView.vue
  packages/editor-ui/src/n8n-theme.scss
  packages/editor-ui/src/views/SettingsUsageAndPlan.vue
Labels: ui, n8n team

#7529 feat(GitLab Node): Add support for pagination on getIssues
  packages/nodes-base/nodes/Gitlab/Gitlab.node.ts
Labels: node/improvement, community

#7686 fix(HTTP Request Node): Support generic credentials when using pagination
  packages/core/src/NodeExecuteFunctions.ts
  packages/nodes-base/nodes/HttpRequest/V3/HttpRequestV3.node.ts
Labels: node/improvement, core, n8n team

#7711 fix(HubSpot Node): Fix typo in Company update fields (no-changelog)
  packages/nodes-base/nodes/Hubspot/V2/CompanyDescription.ts
Labels: node/improvement, n8n team

#7688 fix(core): Fix named parameter resolution in migrations
  packages/cli/src/databases/migrations/common/1620821879465-UniqueWorkflowNames.ts
  packages/cli/src/databases/migrations/common/1630330987096-UpdateWorkflowCredentials.ts
  packages/cli/src/databases/migrations/common/1658930531669-AddNodeIds.ts
  packages/cli/src/databases/migrations/common/1669739707124-AddWorkflowVersionIdColumn.ts
  packages/cli/src/databases/migrations/common/1675940580449-PurgeInvalidWorkflowConnections.ts
  packages/cli/src/databases/types.ts
  packages/cli/src/databases/utils/migrationHelpers.ts
Labels: core, n8n team

#7684 fix(Google Sheets Node): Append exceeding grid limits
  packages/nodes-base/nodes/Google/Sheet/v2/actions/sheet/append.operation.ts
  packages/nodes-base/nodes/Google/Sheet/v2/actions/sheet/appendOrUpdate.operation.ts
  packages/nodes-base/nodes/Google/Sheet/v2/helpers/GoogleSheet.ts
Labels: n8n team, node/issue

#7677 docs(Google Sheets Node): Change Get Many to Get Row(s)
  packages/nodes-base/nodes/Google/Sheet/v2/actions/sheet/Sheet.resource.ts
Labels: node/improvement, n8n team

#7674 feat(Discourse Node): Add new options to Get Users
  packages/nodes-base/nodes/Discourse/Discourse.node.ts
  packages/nodes-base/nodes/Discourse/UserDescription.ts
Labels: node/improvement, n8n team

#7676 docs(DebugHelper Node): Add aliases to improve discoverability
  packages/nodes-base/nodes/DebugHelper/DebugHelper.node.json
Labels: node/improvement, n8n team

#7698 test: Add vitest workspace config so VS Code vitest extension works with 1 click (no-changelog)
  vitest.workspace.ts
Labels: n8n team

#7547 feat(RabbitMQ Trigger Node): Add exchange and routing key options
  packages/nodes-base/nodes/RabbitMQ/GenericFunctions.ts
  packages/nodes-base/nodes/RabbitMQ/RabbitMQTrigger.node.ts
Labels: node/improvement, community

#7707 fix(core): Initialize JWT Secret before it's used anywhere
  packages/cli/src/auth/jwt.ts
  packages/cli/src/commands/start.ts
  packages/cli/src/middlewares/auth.ts
  packages/cli/src/services/jwt.service.ts
  packages/cli/src/services/user.service.ts
  packages/cli/test/integration/passwordReset.api.test.ts
  packages/cli/test/unit/services/jwt.service.test.ts
Labels: core, n8n team

#7714 refactor: Use POST /users to re-invite users (no-changelog)
  packages/cli/src/controllers/users.controller.ts
  packages/cli/test/integration/auth.mw.test.ts
  packages/cli/test/integration/users.api.test.ts
  packages/editor-ui/src/stores/users.store.ts
  packages/editor-ui/src/views/SettingsUsersView.vue
Labels: core, ui, n8n team

#7716 fix(editor): Dark mode sticky notes (no-changelog)
  packages/design-system/src/components/N8nMarkdown/Markdown.vue
  packages/design-system/src/components/N8nSticky/Sticky.vue
  packages/design-system/src/css/_primitives.scss
  packages/design-system/src/css/_tokens.dark.scss
  packages/design-system/src/css/_tokens.scss
  packages/design-system/src/styleguide/colorsprimitives.stories.mdx
  packages/editor-ui/src/components/Sticky.vue
Labels: ui, n8n team

#7503 feat(editor): Node IO filter
  cypress/e2e/32-node-io-filter.cy.ts
  cypress/fixtures/Node_IO_filter.json
  cypress/pages/ndv.ts
  packages/editor-ui/src/components/InputPanel.vue
  packages/editor-ui/src/components/NodeDetailsView.vue
  packages/editor-ui/src/components/OutputPanel.vue
  packages/editor-ui/src/components/RunData.vue
  packages/editor-ui/src/components/RunDataJson.vue
  packages/editor-ui/src/components/RunDataSchema.vue
  packages/editor-ui/src/components/RunDataSchemaItem.vue
  packages/editor-ui/src/components/RunDataSearch.vue
  packages/editor-ui/src/components/RunDataTable.vue
  packages/editor-ui/src/components/__tests__/RunDataSearch.test.ts
  packages/editor-ui/src/constants.ts
  packages/editor-ui/src/plugins/i18n/locales/en.json
  packages/editor-ui/src/utils/__tests__/htmlUtils.test.ts
  packages/editor-ui/src/utils/htmlUtils.ts
  packages/editor-ui/src/utils/objectUtils.ts
Labels: ui, n8n team

#7724 fix(core): Correct permissions for getstatus
  packages/cli/src/controllers/orchestration.controller.ts
Labels: core, n8n team

#7727 ci: Push to Channel workflow should update the tags on GCR as well (no-changelog)
  .github/workflows/release-push-to-channel.yml
Labels: n8n team

#7730 fix(editor): Make sure LineController is registered with chart.js
  packages/editor-ui/src/plugins/chartjs.ts
Labels: ui, n8n team

#7718 feat: Add scopes to /login endpoint (no-changelog)
  packages/@n8n/permissions/src/types.ts
  packages/cli/package.json
  packages/cli/src/Interfaces.ts
  packages/cli/src/controllers/auth.controller.ts
  packages/cli/src/databases/entities/User.ts
  packages/cli/src/permissions/roles.ts
  packages/cli/src/services/user.service.ts
  packages/cli/test/integration/auth.api.test.ts
  pnpm-lock.yaml
Labels: core, n8n team

#7729 fix(Google Sheets Node): Check for `null` before destructuring
  packages/nodes-base/nodes/Google/Sheet/v2/methods/loadOptions.ts
Labels: node/improvement, n8n team, skip-e2e

#7735 fix(core): Account for activation error caused by follower `main` instance
  packages/cli/src/Interfaces.ts
  packages/cli/src/services/orchestration/main/MultiMainSetup.ee.ts
  packages/cli/src/services/orchestration/main/handleCommandMessageMain.ts
  packages/cli/src/services/redis/RedisServiceCommands.ts
  packages/cli/src/workflows/workflows.services.ts
  packages/editor-ui/src/Interface.ts
  packages/editor-ui/src/mixins/pushConnection.ts
Labels: core, ui, n8n team

#7736 ci: Skip the regularly failing tests in 2-credentials.cy.ts (no-changelog)
  cypress/e2e/2-credentials.cy.ts
Labels: n8n team

#7723 fix(editor): Handle permission edge cases (empty scopes)
  packages/@n8n/permissions/src/hasScope.ts
  packages/@n8n/permissions/src/types.ts
  packages/@n8n/permissions/test/hasScope.test.ts
  packages/cli/src/databases/entities/User.ts
Labels: n8n team

#7726 refactor: Extract Invitation routes to InvitationController (no-changelog)
  packages/cli/src/Server.ts
  packages/cli/src/controllers/invitation.controller.ts
  packages/cli/src/controllers/users.controller.ts
  packages/cli/src/middlewares/auth.ts
  packages/cli/src/requests.ts
  packages/cli/src/services/user.service.ts
  packages/cli/test/integration/auth.mw.test.ts
  packages/cli/test/integration/invitations.api.test.ts
  packages/cli/test/integration/shared/types.ts
  packages/cli/test/integration/shared/utils/testServer.ts
  packages/cli/test/integration/users.api.test.ts
  packages/cli/test/unit/services/user.service.test.ts
  packages/editor-ui/src/api/invitation.ts
  packages/editor-ui/src/api/users.ts
  packages/editor-ui/src/stores/users.store.ts
  packages/editor-ui/src/utils/apiUtils.ts
  packages/editor-ui/src/views/SignupView.vue
Labels: core, ui, n8n team

#7741 ci: Fix DB tests and Workflow tests (no-changelog)
  .github/workflows/ci-postgres-mysql.yml
  .github/workflows/test-workflows.yml
Labels: n8n team

#7742 fix(core): Account for non-ASCII chars in filename on binary data download
  packages/cli/src/controllers/binaryData.controller.ts
  packages/cli/test/integration/binaryData.api.test.ts
Labels: core, n8n team

#7728 refactor(core): Stop reporting to Sentry unrecognized node errors (no-changelog)
  cypress/e2e/12-canvas.cy.ts
  packages/cli/src/NodeTypes.ts
Labels: core, n8n team, skip-e2e

#7743 refactor: Stop reporting to Sentry Facebook multi-webhook error (no-changelog)
  packages/nodes-base/nodes/Facebook/FacebookTrigger.node.ts
  packages/nodes-base/nodes/FacebookLeadAds/FacebookLeadAdsTrigger.node.ts
Labels: node/improvement, n8n team

#7284 refactor(core): Convert dynamic node-parameter routes to a decorated controller (no-changelog)
  cypress/e2e/5-ndv.cy.ts
  packages/cli/src/Server.ts
  packages/cli/src/controllers/dynamicNodeParameters.controller.ts
  packages/cli/src/requests.ts
  packages/cli/src/services/dynamicNodeParameters.service.ts
  packages/core/src/LoadMappingOptions.ts
  packages/core/src/LoadNodeDetails.ts
  packages/core/src/LoadNodeListSearch.ts
  packages/core/src/LoadNodeParameterOptions.ts
  packages/core/src/index.ts
  packages/editor-ui/src/Interface.ts
  packages/editor-ui/src/api/nodeTypes.ts
  packages/editor-ui/src/components/ResourceLocator/ResourceLocator.vue
  packages/editor-ui/src/stores/nodeTypes.store.ts
Labels: core, ui, n8n team

#7745 fix(core): Fix all dependency versions for backend packages (no-changelog)
  packages/@n8n/client-oauth2/package.json
  packages/cli/package.json
  packages/core/package.json
  packages/nodes-base/package.json
  packages/workflow/package.json
  pnpm-lock.yaml
Labels: core, n8n team

#7722 fix(editor): Show v1 banner dismiss button if owner
  packages/editor-ui/src/components/banners/V1Banner.vue
  packages/editor-ui/src/components/banners/__tests__/V1Banner.spec.ts
  packages/editor-ui/src/components/banners/__tests__/__snapshots__/V1Banner.spec.ts.snap
Labels: ui, n8n team

#7733 fix(editor): Remove `n8nHooksNext` flag (no-changelog)
  packages/editor-ui/src/hooks/init.ts
  packages/editor-ui/src/main.ts
  packages/editor-ui/src/shims.d.ts
Labels: ui, n8n team

#7739 feat: Enable to input image in Basic LLM Chain & render it in the execution log
  packages/@n8n/nodes-langchain/nodes/chains/ChainLLM/ChainLlm.node.ts
  packages/@n8n/nodes-langchain/nodes/llms/LMChatOpenAi/LmChatOpenAi.node.ts
  packages/@n8n/nodes-langchain/package.json
  packages/editor-ui/src/components/RunDataAi/useAiContentParsers.ts
  pnpm-lock.yaml
Labels: ui, n8n team

#7752 refactor(core): Stop reporting to Sentry unknown cred on mapping (no-changelog)
  packages/cli/src/UserManagement/PermissionChecker.ts
Labels: core, n8n team

#7751 fix(JotForm Trigger Node): Fix iteration on form loader
  packages/nodes-base/nodes/JotForm/JotFormTrigger.node.ts
Labels: node/improvement, n8n team

#7750 fix(core): Guard against node not found on cancelling test webhook
  packages/workflow/src/Workflow.ts
Labels: core, n8n team

#7753 refactor(core): Stop reporting to Sentry `NodeApiError` outside 500 range (no-changelog)
  packages/workflow/src/NodeErrors.ts
Labels: core, n8n team

#7746 fix: Include cypress TypeScript types in /cypress folder (no-changelog)
  cypress/tsconfig.json
  tsconfig.json
Labels: n8n team

#7721 feat: Add Creator hub link to Templates page
  packages/design-system/src/components/N8nActionBox/__tests__/__snapshots__/ActionBox.spec.ts.snap
  packages/design-system/src/components/N8nButton/Button.vue
  packages/editor-ui/src/constants.ts
  packages/editor-ui/src/plugins/i18n/locales/en.json
  packages/editor-ui/src/views/TemplatesSearchView.vue
Labels: ui, n8n team, skip-e2e

#7620 feat(editor): Add node context menu
  cypress/e2e/10-undo-redo.cy.ts
  cypress/e2e/12-canvas-actions.cy.ts
  cypress/e2e/12-canvas.cy.ts
  cypress/e2e/13-pinning.cy.ts
  cypress/e2e/25-stickies.cy.ts
  cypress/pages/ndv.ts
  cypress/pages/workflow.ts
  packages/design-system/src/components/N8nActionDropdown/ActionDropdown.stories.ts
  packages/design-system/src/components/N8nActionDropdown/ActionDropdown.vue
  packages/design-system/src/components/N8nActionDropdown/__tests__/__snapshots__/ActionDropdown.spec.ts.snap
  packages/design-system/src/components/N8nKeyboardShortcut/KeyboardShortcut.stories.ts
  packages/design-system/src/components/N8nKeyboardShortcut/N8nKeyboardShortcut.vue
  packages/design-system/src/components/N8nKeyboardShortcut/index.ts
  packages/design-system/src/components/index.ts
  packages/design-system/src/composables/index.ts
  packages/design-system/src/composables/useDeviceSupport.ts
  packages/design-system/src/css/_tokens.dark.scss
  packages/design-system/src/css/_tokens.scss
  packages/design-system/src/css/common/transition.scss
  packages/design-system/src/css/common/var.scss
  packages/design-system/src/css/dropdown.scss
  packages/design-system/src/css/popper.scss
  packages/design-system/src/main.ts
  packages/design-system/src/plugin.ts
  packages/design-system/src/types/index.ts
  packages/design-system/src/types/keyboardshortcut.ts
  packages/editor-ui/src/Interface.ts
  packages/editor-ui/src/components/CanvasControls.vue
  packages/editor-ui/src/components/ContextMenu/ContextMenu.vue
  packages/editor-ui/src/components/KeyboardShortcutTooltip.vue
  packages/editor-ui/src/components/Node.vue
  packages/editor-ui/src/components/Node/NodeCreation.vue
  packages/editor-ui/src/components/NodeDetailsView.vue
  packages/editor-ui/src/components/SaveButton.vue
  packages/editor-ui/src/components/Sticky.vue
  packages/editor-ui/src/composables/__tests__/__snapshots__/useContextMenu.test.ts.snap
  packages/editor-ui/src/composables/__tests__/useContextMenu.test.ts
  packages/editor-ui/src/composables/index.ts
  packages/editor-ui/src/composables/useCanvasMouseSelect.ts
  packages/editor-ui/src/composables/useContextMenu.ts
  packages/editor-ui/src/composables/useHistoryHelper.ts
  packages/editor-ui/src/constants.ts
  packages/editor-ui/src/mixins/pinData.ts
  packages/editor-ui/src/plugins/i18n/locales/en.json
  packages/editor-ui/src/stores/ui.store.ts
  packages/editor-ui/src/views/NodeView.vue
Labels: ui, n8n team

#7758 docs: Update docs links for data transformation functions and ifEmpty
  packages/workflow/src/Extensions/ArrayExtensions.ts
  packages/workflow/src/Extensions/DateExtensions.ts
  packages/workflow/src/Extensions/ExtendedFunctions.ts
  packages/workflow/src/Extensions/NumberExtensions.ts
  packages/workflow/src/Extensions/ObjectExtensions.ts
  packages/workflow/src/Extensions/StringExtensions.ts
Labels: core, n8n team

#7744 fix(core): Ensure failed executions are saved in queue mode
  packages/cli/src/WorkflowRunner.ts
  packages/cli/src/executionLifecycleHooks/shared/sharedHookFunctions.ts
Labels: core, n8n team

#7678 fix(Item Lists Node): Don't check same type in remove duplicates operation
  packages/nodes-base/nodes/ItemLists/ItemLists.node.ts
  packages/nodes-base/nodes/ItemLists/V3/actions/itemList/removeDuplicates.operation.ts
  packages/nodes-base/nodes/ItemLists/V3/actions/versionDescription.ts
  packages/nodes-base/nodes/ItemLists/V3/helpers/utils.ts
  packages/nodes-base/nodes/ItemLists/test/node/workflow.removeDuplicates_3_1.json
Labels: node/improvement, n8n team

#7764 fix(editor): Use project diagram icon for worker view
  packages/editor-ui/src/components/SettingsSidebar.vue
  packages/editor-ui/src/plugins/icons/index.ts
Labels: ui, n8n team

#7766 fix(editor): Only show push to git menu item to owners
  cypress/e2e/7-workflow-actions.cy.ts
  cypress/pages/workflow.ts
  packages/editor-ui/src/components/MainHeader/WorkflowDetails.vue
Labels: ui, n8n team

#7768 refactor: Upgrade to TypeScript 5.3 (no-changelog)
  package.json
  pnpm-lock.yaml
Labels: n8n team

#7769 refactor(core): Include execution progress in save settings (no-changelog)
  packages/cli/src/WorkflowExecuteAdditionalData.ts
  packages/cli/src/executionLifecycleHooks/toSaveSettings.ts
  packages/cli/test/unit/execution-lifecyle/toSaveSettings.test.ts
  packages/cli/test/unit/execution.lifecycle.test.ts
Labels: core, n8n team

#7772 feat(core): Make postgres pool-size configurable (no-changelog)
  packages/cli/src/config/schema.ts
  packages/cli/src/databases/config.ts
Labels: core, n8n team

#7608 fix(editor): Validate user info before submiting
  cypress/e2e/33-settings-personal.cy.ts
  packages/cli/src/databases/utils/customValidators.ts
  packages/cli/test/unit/databases/utils/customValidators.test.ts
  packages/design-system/src/components/N8nFormBox/FormBox.vue
Labels: core, ui, n8n team

#7777 docs: Add workflow template contribution to the contributing guide
  CONTRIBUTING.md
Labels: n8n team

#7779 fix(core): Pass correct node reference to NodeExecuteFunctions.getLoadOptionsFunctions (no-changelog)
  packages/cli/src/services/dynamicNodeParameters.service.ts
Labels: core, n8n team

#7783 fix(core): Show webhook urls for all webhook nodes (no-changelog)
  packages/core/bin/generate-ui-types
  packages/editor-ui/src/components/NodeWebhooks.vue
  packages/workflow/src/Interfaces.ts
Labels: core, ui, n8n team

#7455 feat(core): Add Support for custom CORS origins for webhooks
  packages/cli/src/ActiveWorkflowRunner.ts
  packages/cli/src/Interfaces.ts
  packages/cli/src/TestWebhooks.ts
  packages/cli/src/WebhookHelpers.ts
  packages/cli/test/unit/WebhookHelpers.test.ts
  packages/cli/test/unit/webhooks.test.ts
  packages/nodes-base/nodes/Webhook/Webhook.node.ts
  packages/workflow/src/Interfaces.ts
  packages/workflow/src/NodeHelpers.ts
Labels: n8n team, node/issue

#7763 feat(editor): Show avatars for users currently working on the same workflow
  packages/cli/src/Server.ts
  packages/cli/src/collaboration/collaboration.service.ts
  packages/cli/src/collaboration/collaboration.state.ts
  packages/cli/src/push/index.ts
  packages/cli/test/unit/collaboration/collaboration.state.test.ts
  packages/design-system/src/components/N8nUserStack/UserStack.vue
  packages/editor-ui/src/App.vue
  packages/editor-ui/src/Interface.ts
  packages/editor-ui/src/components/MainHeader/CollaborationPane.vue
  packages/editor-ui/src/components/MainHeader/MainHeader.vue
  packages/editor-ui/src/components/MainHeader/WorkflowDetails.vue
  packages/editor-ui/src/components/__tests__/CollaborationPane.test.ts
  packages/editor-ui/src/constants.ts
  packages/editor-ui/src/mixins/pushConnection.ts
  packages/editor-ui/src/stores/collaboration.store.ts
  packages/editor-ui/src/stores/index.ts
  packages/editor-ui/src/stores/pushConnection.store.ts
  packages/editor-ui/src/views/NodeView.vue
Labels: core, ui, n8n team

#7784 build: Upgrade to Vite 5
  package.json
  packages/cli/src/config/types.ts
  packages/cli/src/databases/migrations/common/1674509946020-CreateLdapEntities.ts
  packages/cli/src/decorators/Authorized.ts
  packages/editor-ui/package.json
  packages/editor-ui/src/components/ExpressionEditorModal/ExpressionEditorModalOutput.vue
  packages/editor-ui/src/components/InlineExpressionEditor/InlineExpressionEditorOutput.vue
  packages/editor-ui/src/components/Node.vue
  packages/editor-ui/src/components/OutputPanel.vue
  packages/editor-ui/src/components/Sticky.vue
  packages/editor-ui/src/components/TriggerPanel.vue
  packages/editor-ui/src/hooks/segment/getters.ts
  packages/editor-ui/src/mixins/pushConnection.ts
  packages/editor-ui/src/mixins/workflowHelpers.ts
  packages/editor-ui/src/plugins/connectors/N8nCustomConnector.ts
  packages/editor-ui/src/stores/canvas.store.ts
  packages/editor-ui/src/utils/pairedItemUtils.ts
  packages/editor-ui/tsconfig.json
  packages/editor-ui/vite.config.mts
  packages/nodes-base/nodes/Code/Code.node.ts
  packages/nodes-base/nodes/Discord/v1/DiscordV1.node.ts
  packages/nodes-base/nodes/Discord/v2/actions/channel/index.ts
  packages/nodes-base/nodes/Discord/v2/actions/member/index.ts
  packages/nodes-base/nodes/Discord/v2/actions/message/index.ts
  packages/nodes-base/nodes/Discord/v2/helpers/utils.ts
  packages/nodes-base/nodes/EmailSend/v2/send.operation.ts
  packages/nodes-base/nodes/Google/CloudStorage/ObjectDescription.ts
  packages/nodes-base/nodes/Grist/GenericFunctions.ts
  packages/nodes-base/nodes/Grist/Grist.node.ts
  packages/nodes-base/nodes/HaloPSA/GenericFunctions.ts
  packages/nodes-base/nodes/HttpRequest/test/node/HttpRequest.test.ts
  pnpm-lock.yaml
Labels: ui, n8n team

#7782 fix(HTTP Request Node): Enable expressions for binary input data fields
  packages/nodes-base/nodes/HttpRequest/V3/HttpRequestV3.node.ts
Labels: node/improvement, n8n team

#7788 fix(core): Tighten checks for multi-main setup usage
  packages/cli/src/ActiveWorkflowRunner.ts
  packages/cli/src/License.ts
  packages/cli/src/commands/start.ts
  packages/cli/src/services/orchestration/main/MultiMainSetup.ee.ts
  packages/cli/src/services/pruning.service.ts
  packages/cli/src/workflows/workflows.services.ts
Labels: core, n8n team

#7776 feat(editor): Floating NDV connected nodes
  cypress/e2e/19-execution.cy.ts
  cypress/e2e/5-ndv.cy.ts
  cypress/fixtures/Floating_Nodes.json
  packages/design-system/src/components/N8nNodeIcon/NodeIcon.vue
  packages/editor-ui/src/components/NDVDraggablePanels.vue
  packages/editor-ui/src/components/NDVFloatingNodes.vue
  packages/editor-ui/src/components/NodeDetailsView.vue
  packages/editor-ui/src/components/NodeIcon.vue
  packages/editor-ui/src/views/NodeView.vue
Labels: ui, n8n team

#7781 feat: Add global admin role (no-changelog)
  packages/cli/src/databases/entities/User.ts
  packages/cli/src/databases/migrations/common/1700571993961-AddGlobalAdminRole.ts
  packages/cli/src/databases/migrations/mysqldb/index.ts
  packages/cli/src/databases/migrations/postgresdb/index.ts
  packages/cli/src/databases/migrations/sqlite/index.ts
Labels: core, n8n team

#7789 fix(editor): Disable context menu actions in read-only mode
  packages/editor-ui/src/components/ContextMenu/ContextMenu.vue
  packages/editor-ui/src/components/Sticky.vue
  packages/editor-ui/src/composables/__tests__/__snapshots__/useContextMenu.test.ts.snap
  packages/editor-ui/src/composables/__tests__/useContextMenu.test.ts
  packages/editor-ui/src/composables/useContextMenu.ts
  packages/editor-ui/src/plugins/i18n/locales/en.json
Labels: ui, n8n team

#7731 feat(editor): Add node name and version to NDV node settings
  cypress/e2e/5-ndv.cy.ts
  cypress/fixtures/Test_workflow_ndv_version.json
  cypress/pages/ndv.ts
  packages/design-system/src/components/N8nTabs/Tabs.vue
  packages/editor-ui/src/components/NodeSettings.vue
  packages/editor-ui/src/plugins/i18n/locales/en.json
  packages/editor-ui/src/stores/nodeTypes.store.ts
Labels: ui, n8n team

#7803 test: Remove obsolete snapshot
  packages/editor-ui/src/components/banners/__tests__/__snapshots__/V1Banner.spec.ts.snap
Labels: ui, n8n team
