Repository n8n-io/n8n, pull requests merged in 2023-05, with the labels that each got.

#5810 fix(Date & Time Node): Numbers conversions fix
  packages/nodes-base/nodes/DateTime/DateTime.node.ts
  packages/nodes-base/nodes/DateTime/test/node/DateTimeWorklfow.test.json
  packages/nodes-base/nodes/DateTime/test/node/workflow.timestamp.json
Labels: n8n team, node/issue

#6129 fix(editor): Fix cropped off completions docstrings
  packages/editor-ui/src/styles/autocomplete-theme.scss
Labels: ui, n8n team

#6128 fix(editor): Fix quote handling on dollar-sign variable completions
  packages/editor-ui/src/plugins/codemirror/completions/__tests__/completions.test.ts
  packages/editor-ui/src/plugins/codemirror/completions/datatype.completions.ts
Labels: ui, n8n team

#6109 fix(core): Account for nodes with renamable content
  packages/workflow/src/Constants.ts
  packages/workflow/src/Workflow.ts
  packages/workflow/test/Workflow.test.ts
Labels: core, n8n team

#6112 fix(editor): Fix copy selection behavior
  packages/editor-ui/src/components/RunDataJson.vue
  packages/editor-ui/src/components/RunDataJsonActions.vue
Labels: ui, n8n team

#6140 fix(editor): Fix focus jumping when using chrome autofill
  packages/editor-ui/src/components/ParameterInput.vue
Labels: ui, n8n team

#6147 ci: Expand ESLint to tests in BE packages (no-changelog)
  packages/@n8n_io/eslint-config/base.js
  packages/cli/test/integration/commands/import.cmd.test.ts
  packages/cli/test/integration/credentials.ee.test.ts
  packages/cli/test/integration/credentials.test.ts
  packages/cli/test/integration/eventbus.test.ts
  packages/cli/test/integration/ldap/ldap.api.test.ts
  packages/cli/test/integration/license.api.test.ts
  packages/cli/test/integration/passwordReset.api.test.ts
  packages/cli/test/integration/publicApi/executions.test.ts
  packages/cli/test/integration/publicApi/workflows.test.ts
  packages/cli/test/integration/saml/saml.api.test.ts
  packages/cli/test/integration/shared/constants.ts
  packages/cli/test/integration/shared/testDb.ts
  packages/cli/test/integration/shared/utils.ts
  packages/cli/test/integration/users.api.test.ts
  packages/cli/test/integration/variables.test.ts
  packages/cli/test/integration/workflows.controller.test.ts
  packages/cli/test/teardown.ts
  packages/cli/test/unit/ActiveExecutions.test.ts
  packages/cli/test/unit/ActiveWorkflowRunner.test.ts
  packages/cli/test/unit/CommunityNodeHelpers.test.ts
  packages/cli/test/unit/CredentialsHelper.test.ts
  packages/cli/test/unit/CurlConverterHelper.test.ts
  packages/cli/test/unit/Events.test.ts
  packages/cli/test/unit/Helpers.ts
  packages/cli/test/unit/PermissionChecker.test.ts
  packages/cli/test/unit/PostHog.test.ts
  packages/cli/test/unit/WorkflowCredentials.test.ts
  packages/cli/test/unit/WorkflowHelpers.test.ts
  packages/cli/test/unit/controllers/me.controller.test.ts
  packages/cli/test/unit/controllers/translation.controller.test.ts
  packages/cli/test/unit/repositories/role.repository.test.ts
  packages/core/test/Helpers.ts
  packages/core/test/NodeExecuteFunctions.test.ts
  packages/core/test/WorkflowExecute.test.ts
  packages/core/test/utils.ts
  packages/nodes-base/package.json
  packages/nodes-base/test/nodes/Airtable/Airtable.node.test.ts
  packages/nodes-base/test/nodes/ExecuteWorkflow.ts
  packages/nodes-base/test/nodes/FakeCredentialsMap.ts
  packages/nodes-base/test/nodes/Helpers.ts
  packages/nodes-base/test/nodes/Postgres/Postgres.node.functions.test.ts
  packages/nodes-base/test/nodes/Start/StartNode.test.ts
  packages/nodes-base/test/nodes/Stripe/helpers.test.ts
  packages/nodes-base/test/nodes/types.ts
  packages/nodes-base/tsconfig.json
  packages/workflow/test/AugmentObject.test.ts
  packages/workflow/test/Expression.test.ts
  packages/workflow/test/ExpressionExtensions/ArrayExtensions.test.ts
  packages/workflow/test/ExpressionExtensions/DateExtensions.test.ts
  packages/workflow/test/ExpressionExtensions/ExpressionExtension.test.ts
  packages/workflow/test/ExpressionExtensions/Helpers.ts
  packages/workflow/test/ExpressionExtensions/NumberExtensions.test.ts
  packages/workflow/test/ExpressionExtensions/ObjectExtensions.test.ts
  packages/workflow/test/ExpressionExtensions/StringExtensions.test.ts
  packages/workflow/test/Helpers.ts
  packages/workflow/test/RoutingNode.test.ts
  packages/workflow/test/Workflow.test.ts
  packages/workflow/test/WorkflowDataProxy.test.ts
Labels: core, n8n team

#6142 fix(core): Fix canceled execution status
  packages/cli/src/InternalHooks.ts
  packages/cli/src/WorkflowExecuteAdditionalData.ts
  packages/cli/src/WorkflowRunnerProcess.ts
  packages/core/src/WorkflowExecute.ts
Labels: core, n8n team

#6144 feat(core): Add notice to alert users a new version is available
  packages/nodes-base/nodes/Google/Analytics/v1/GoogleAnalyticsV1.node.ts
  packages/nodes-base/nodes/Google/BigQuery/v1/GoogleBigQueryV1.node.ts
  packages/nodes-base/nodes/Google/Gmail/v1/GmailV1.node.ts
  packages/nodes-base/nodes/Google/Sheet/v1/versionDescription.ts
  packages/nodes-base/nodes/Merge/v1/MergeV1.node.ts
  packages/nodes-base/nodes/MySql/v1/MySqlV1.node.ts
  packages/nodes-base/nodes/Postgres/v1/PostgresV1.node.ts
  packages/nodes-base/nodes/Slack/V1/SlackV1.node.ts
  packages/nodes-base/utils/descriptions.ts
Labels: node/improvement, n8n team

#6148 ci: Restore load options methods validation (no-changelog)
  packages/nodes-base/package.json
Labels: n8n team

#6143 fix(core): Remove SAML config metadataUrl if XML metadata is set directly
  packages/cli/src/sso/saml/saml.service.ee.ts
Labels: core, n8n team

#6153 fix(AWS S3 Node): Fix File upload, and add node tests
  packages/nodes-base/credentials/Aws.credentials.ts
  packages/nodes-base/jest.config.js
  packages/nodes-base/nodes/Aws/S3/test/AwsS3.file.upload.workflow.json
  packages/nodes-base/nodes/Aws/S3/test/AwsS3.node.test.ts
  packages/nodes-base/test/nodes/FakeCredentialsMap.ts
  packages/nodes-base/test/nodes/Helpers.ts
  packages/nodes-base/tsconfig.json
  packages/workflow/src/NodeErrors.ts
Labels: node/improvement, core, n8n team

#6110 fix(core): Assign Unknown Error only if message or description not present in error
  packages/workflow/src/NodeErrors.ts
  packages/workflow/test/NodeErrors.test.ts
Labels: n8n team, node/issue

#6003 fix(editor): Restrict `[empty]` in parameter input hint to zero-length string
  cypress/e2e/14-mapping.cy.ts
  packages/editor-ui/src/components/ParameterInputHint.vue
  packages/editor-ui/src/components/ParameterInputWrapper.vue
Labels: ui, n8n team

#6154 fix: Prevent invocations of 'GET /rest/license' from returning an error when ephemeral licenses are used
  packages/cli/src/License.ts
  packages/cli/test/unit/License.test.ts
Labels: core, n8n team

#6157 fix(core): Fix bug running addUserActivatedColumn migration on MariaDB
  packages/cli/src/databases/migrations/mysqldb/1681134145996-AddUserActivatedProperty.ts
Labels: core, n8n team

#6161 fix(core): Better errors for common status codes fix
  packages/workflow/src/NodeErrors.ts
  packages/workflow/test/NodeErrors.test.ts
Labels: n8n team, node/issue

#6085 test: Address flaky setup e2e (no-changelog)
  cypress.config.js
  cypress/e2e/23-variables.cy.ts
  cypress/e2e/3-default-owner.cy.ts
  cypress/support/commands.ts
  cypress/support/index.ts
  packages/cli/src/api/e2e.api.ts
Labels: n8n team

#6165 fix: Log unhandled errors during license activation (no-changelog)
  packages/cli/src/license/license.controller.ts
  packages/cli/test/integration/license.api.test.ts
Labels: core, n8n team

#6164 fix(editor): Faster reconnects for push (no-changelog)
  packages/editor-ui/src/mixins/pushConnection.ts
Labels: ui, n8n team

#6127 fix(editor): Flag issues only on workflow activation
  packages/editor-ui/src/mixins/workflowActivate.ts
Labels: ui, n8n team

#6169 fix(MySQL Node): Node should return date types as strings
  packages/nodes-base/nodes/MySql/MySql.node.ts
  packages/nodes-base/nodes/MySql/v2/actions/router.ts
  packages/nodes-base/nodes/MySql/v2/actions/versionDescription.ts
  packages/nodes-base/nodes/MySql/v2/transport/index.ts
Labels: n8n team, node/issue

#6132 fix(HTTP Request Node): Correctly doesn't redirect on non GET method
  packages/nodes-base/nodes/HttpRequest/HttpRequest.node.ts
  packages/nodes-base/nodes/HttpRequest/V3/HttpRequestV3.node.ts
Labels: node/improvement, n8n team

#6135 fix(editor): Remove duplicate mapping of `item.json` key in data pinning
  packages/editor-ui/src/components/RunData.vue
  packages/editor-ui/src/components/__tests__/RunData.test.ts
Labels: ui, n8n team

#6160 feat(Airtable Node): Access token support
  packages/nodes-base/credentials/AirtableApi.credentials.ts
  packages/nodes-base/credentials/AirtableTokenApi.credentials.ts
  packages/nodes-base/nodes/Airtable/Airtable.node.ts
  packages/nodes-base/nodes/Airtable/AirtableTrigger.node.ts
  packages/nodes-base/nodes/Airtable/GenericFunctions.ts
  packages/nodes-base/package.json
Labels: node/improvement, n8n team

#6136 fix(AWS Rekognition Node): Fix all different action type
  packages/nodes-base/nodes/Aws/Rekognition/AwsRekognition.node.ts
  packages/nodes-base/nodes/Aws/Rekognition/test/AwsRekognition.node.test.ts
  packages/nodes-base/nodes/Aws/Rekognition/test/AwsRekognitionTestWorkflow.json
Labels: node/improvement, n8n team

#6183 fix(editor): Show the correct actions count in the nodes list
  packages/editor-ui/src/components/Node/NodeCreator/Renderers/CategorizedItemsRenderer.vue
Labels: ui, n8n team

#6158 fix: Revert change that hid the SSH private key (no-changelog)
  packages/nodes-base/credentials/SshPrivateKey.credentials.ts
Labels: node/improvement, community

#6145 fix(Postgres Node): Always return TIMESTAMP and TIMESTAMPZ as ISO string
  packages/nodes-base/nodes/Postgres/Postgres.node.ts
  packages/nodes-base/nodes/Postgres/v2/actions/router.ts
  packages/nodes-base/nodes/Postgres/v2/actions/versionDescription.ts
  packages/nodes-base/nodes/Postgres/v2/methods/listSearch.ts
  packages/nodes-base/nodes/Postgres/v2/methods/loadOptions.ts
  packages/nodes-base/nodes/Postgres/v2/transport/index.ts
Labels: node/improvement, node/new, n8n team

#6180 fix(editor): Update and fix storybook (was failing to run in local dev mode)
  packages/design-system/.storybook/main.js
  packages/design-system/.storybook/preview.js
  packages/design-system/package.json
  packages/design-system/src/docs/Introduction.stories.mdx
  pnpm-lock.yaml
Labels: ui, n8n team

#4295 feat(Code Node): Add Python support
  packages/editor-ui/package.json
  packages/editor-ui/src/components/CodeNodeEditor/CodeNodeEditor.vue
  packages/editor-ui/src/components/CodeNodeEditor/completer.ts
  packages/editor-ui/src/components/CodeNodeEditor/completions/base.completions.ts
  packages/editor-ui/src/components/CodeNodeEditor/completions/itemField.completions.ts
  packages/editor-ui/src/components/CodeNodeEditor/completions/require.completions.ts
  packages/editor-ui/src/components/CodeNodeEditor/constants.ts
  packages/editor-ui/src/components/CodeNodeEditor/linter.ts
  packages/editor-ui/src/components/CodeNodeEditor/types.ts
  packages/editor-ui/src/components/ParameterInput.vue
  packages/editor-ui/src/views/NodeView.vue
  packages/nodes-base/nodes/Code/Code.node.json
  packages/nodes-base/nodes/Code/Code.node.ts
  packages/nodes-base/nodes/Code/JavaScriptSandbox.ts
  packages/nodes-base/nodes/Code/Pyodide.ts
  packages/nodes-base/nodes/Code/PythonSandbox.ts
  packages/nodes-base/nodes/Code/Sandbox.ts
  packages/nodes-base/nodes/Code/descriptions/JavascriptCodeDescription.ts
  packages/nodes-base/nodes/Code/descriptions/PythonCodeDescription.ts
  packages/nodes-base/nodes/Code/test/Code.node.test.ts
  packages/nodes-base/nodes/Code/utils.ts
  packages/nodes-base/package.json
  packages/workflow/src/Constants.ts
  packages/workflow/src/Interfaces.ts
  pnpm-lock.yaml
Labels: core, ui, n8n team

#6178 fix(editor): Update and add design system checkbox component to Editor
  packages/design-system/src/components/N8nCheckbox/Checkbox.vue
  packages/design-system/src/components/N8nCheckbox/__tests__/Checkbox.spec.ts
  packages/design-system/src/components/N8nCheckbox/__tests__/__snapshots__/Checkbox.spec.ts.snap
  packages/design-system/src/components/index.ts
  packages/design-system/src/plugin.ts
Labels: ui, n8n team

#6186 ci: Fix linting issues on master (no-changelog)
  packages/nodes-base/nodes/Code/Code.node.ts
  packages/workflow/src/Interfaces.ts
Labels: node/improvement, core, n8n team

#6188 ci: Fix test database cleanup (no-changelog)
  packages/cli/test/integration/shared/testDb.ts
  packages/cli/test/integration/shared/utils.ts
  packages/cli/test/teardown.ts
Labels: core, n8n team

#6170 fix(FTP Node): Use filename instead of remote filepath for downloaded binary data
  packages/nodes-base/nodes/Ftp/Ftp.node.ts
Labels: node/improvement, n8n team

#6193 fix(core): Move nodeExecute InternalHook calls to hookFunctionsSave
  packages/cli/src/WorkflowExecuteAdditionalData.ts
Labels: core, n8n team

#5666 test: Create custom jest error messages using jest-expect-message (no-changelog)
  jest.config.js
  package.json
  packages/nodes-base/test/nodes/Helpers.ts
  pnpm-lock.yaml
  tsconfig.json
Labels: node/improvement, n8n team

#6189 refactor: Add deprecation notice for MySQL and MariaDB
  packages/cli/src/commands/BaseCommand.ts
  packages/cli/src/config/schema.ts
Labels: core, n8n team, skip-e2e

#5459 test(Read Binary Files Node): Unit tests (no-changelog)
  packages/nodes-base/nodes/ReadBinaryFiles/test/ReadBinaryFiles.test.ts
  packages/nodes-base/nodes/ReadBinaryFiles/test/ReadBinaryFiles.workflow.json
  packages/nodes-base/nodes/ReadBinaryFiles/test/data/sample.json
  packages/nodes-base/nodes/ReadBinaryFiles/test/data/sample2.json
Labels: n8n team

#6196 feat(core): Update config defaults for for v1 (no-changelog)
  packages/cli/src/config/schema.ts
  packages/cli/src/constants.ts
Labels: core, n8n team

#6195 refactor(core): Add deprecation notice for own mode
  packages/cli/src/commands/BaseCommand.ts
  packages/cli/src/config/schema.ts
Labels: core, n8n team

#4337 feat(HubSpot Node): Overhaul the HubSpot Node
  packages/nodes-base/nodes/Hubspot/Hubspot.node.ts
  packages/nodes-base/nodes/Hubspot/HubspotTrigger.node.ts
  packages/nodes-base/nodes/Hubspot/V1/CompanyDescription.ts
  packages/nodes-base/nodes/Hubspot/V1/ContactDescription.ts
  packages/nodes-base/nodes/Hubspot/V1/ContactListDescription.ts
  packages/nodes-base/nodes/Hubspot/V1/DealDescription.ts
  packages/nodes-base/nodes/Hubspot/V1/DealInterface.ts
  packages/nodes-base/nodes/Hubspot/V1/EngagementDescription.ts
  packages/nodes-base/nodes/Hubspot/V1/FormDescription.ts
  packages/nodes-base/nodes/Hubspot/V1/FormInterface.ts
  packages/nodes-base/nodes/Hubspot/V1/GenericFunctions.ts
  packages/nodes-base/nodes/Hubspot/V1/HubspotV1.node.ts
  packages/nodes-base/nodes/Hubspot/V1/TicketDescription.ts
  packages/nodes-base/nodes/Hubspot/V2/CompanyDescription.ts
  packages/nodes-base/nodes/Hubspot/V2/ContactDescription.ts
  packages/nodes-base/nodes/Hubspot/V2/ContactListDescription.ts
  packages/nodes-base/nodes/Hubspot/V2/DealDescription.ts
  packages/nodes-base/nodes/Hubspot/V2/DealInterface.ts
  packages/nodes-base/nodes/Hubspot/V2/EngagementDescription.ts
  packages/nodes-base/nodes/Hubspot/V2/FormDescription.ts
  packages/nodes-base/nodes/Hubspot/V2/FormInterface.ts
  packages/nodes-base/nodes/Hubspot/V2/GenericFunctions.ts
  packages/nodes-base/nodes/Hubspot/V2/HubspotV2.node.ts
  packages/nodes-base/nodes/Hubspot/V2/TicketDescription.ts
Labels: node/improvement, node/new, n8n team

#5904 feat(Date & Time Node): Overhaul of the node
  packages/nodes-base/nodes/DateTime/DateTime.node.ts
  packages/nodes-base/nodes/DateTime/V1/DateTimeV1.node.ts
  packages/nodes-base/nodes/DateTime/V2/AddToDateDescription.ts
  packages/nodes-base/nodes/DateTime/V2/CurrentDateDescription.ts
  packages/nodes-base/nodes/DateTime/V2/DateTimeV2.node.ts
  packages/nodes-base/nodes/DateTime/V2/ExtractDateDescription.ts
  packages/nodes-base/nodes/DateTime/V2/FormatDateDescription.ts
  packages/nodes-base/nodes/DateTime/V2/GenericFunctions.ts
  packages/nodes-base/nodes/DateTime/V2/GetTimeBetweenDates.ts
  packages/nodes-base/nodes/DateTime/V2/RoundDateDescription.ts
  packages/nodes-base/nodes/DateTime/V2/SubtractFromDateDescription.ts
  packages/nodes-base/nodes/DateTime/test/node/DateTimeWorkflowV2.json
  packages/nodes-base/nodes/DateTime/test/node/workflow.timestamp_v2.json
  packages/nodes-base/test/nodes/ExecuteWorkflow.ts
  packages/nodes-base/test/nodes/Helpers.ts
  packages/nodes-base/test/nodes/types.ts
Labels: node/improvement, node/new, n8n team

#6192 fix: Correctly save executions that failed when polling as error instead of new
  packages/cli/src/GenericHelpers.ts
Labels: n8n team, skip-e2e

#6210 refactor(editor): Add date check to GitHub 30k stars banner
  packages/editor-ui/src/components/layouts/ResourcesListLayout.vue
  packages/editor-ui/src/constants.ts
Labels: ui, n8n team

#6184 fix(editor): Add loading skeletons to Executions list page
  packages/editor-ui/src/components/ExecutionFilter.vue
  packages/editor-ui/src/components/ExecutionsList.vue
Labels: ui, n8n team

#6204 refactor(editor): Add GitHub 30k stars banner (no-changelog)
  packages/editor-ui/src/components/layouts/ResourcesListLayout.vue
  packages/editor-ui/src/constants.ts
  packages/editor-ui/src/plugins/i18n/locales/en.json
  packages/editor-ui/src/plugins/icons/index.ts
Labels: ui, n8n team

#6205 feat(core): Improve health check
  packages/cli/src/AbstractServer.ts
  packages/cli/src/CredentialsHelper.ts
  packages/cli/src/Db.ts
  packages/cli/src/Server.ts
  packages/cli/src/WorkflowExecuteAdditionalData.ts
  packages/cli/src/commands/BaseCommand.ts
  packages/cli/src/commands/start.ts
  packages/cli/src/commands/webhook.ts
  packages/cli/test/integration/shared/testDb.ts
Labels: core, n8n team

#6217 ci: Fix linting issue on master (no-changelog)
  packages/cli/src/AbstractServer.ts
Labels: core, n8n team

#6130 fix(editor): Fix polling trigger check for `runData`
  packages/editor-ui/src/mixins/pushConnection.ts
Labels: ui, n8n team

#6177 feat: Create NPM node
  packages/core/src/NodeExecuteFunctions.ts
  packages/nodes-base/credentials/NpmApi.credentials.ts
  packages/nodes-base/nodes/Npm/DistTagDescription.ts
  packages/nodes-base/nodes/Npm/Npm.node.json
  packages/nodes-base/nodes/Npm/Npm.node.ts
  packages/nodes-base/nodes/Npm/PackageDescription.ts
  packages/nodes-base/nodes/Npm/npm.svg
  packages/nodes-base/nodes/Npm/test/Npm.node.test.ts
  packages/nodes-base/nodes/Npm/test/Npm.workflow.test.json
  packages/nodes-base/package.json
  packages/nodes-base/test/nodes/FakeCredentialsMap.ts
  pnpm-lock.yaml
Labels: node/new, core, n8n team

#6201 fix: Prevent unnecessary error messages also for data loaded flag
  packages/cli/src/events/WorkflowStatistics.ts
  packages/cli/test/unit/Events.test.ts
Labels: core, n8n team

#6218 fix(editor): Fix viewing and downloading of binary data
  packages/editor-ui/src/stores/workflows.store.ts
Labels: ui, n8n team

#6221 ci: Increase timeout for DB tests (no-changelog)
  .github/workflows/ci-postgres-mysql.yml
Labels: n8n team

#6220 fix(core): Ensure DB repositories are initialized before the DB migrations are run
  packages/cli/src/Db.ts
  packages/cli/src/Interfaces.ts
Labels: core, n8n team

#6222 ci: Fix linting issue on master (no-changelog)
  packages/cli/test/integration/shared/testDb.ts
Labels: core, n8n team

#6224 ci: Code coverage should include `.vue` files as well (no-changelog)
  packages/design-system/vite.config.ts
  packages/editor-ui/vite.config.ts
Labels: ui, n8n team

#6226 ci: Fix published nodes-base package's dependencies (no-changelog)
  package.json
  packages/nodes-base/package.json
  pnpm-lock.yaml
Labels: n8n team

#6179 feat(editor): Add color picker design system component
  packages/design-system/src/components/N8nColorPicker/ColorPicker.stories.ts
  packages/design-system/src/components/N8nColorPicker/ColorPicker.vue
  packages/design-system/src/components/N8nColorPicker/__tests__/ColorPicker.spec.ts
  packages/design-system/src/components/N8nColorPicker/__tests__/__snapshots__/ColorPicker.spec.ts.snap
  packages/design-system/src/components/N8nColorPicker/index.ts
  packages/design-system/src/components/index.ts
  packages/design-system/src/plugin.ts
Labels: ui, n8n team

#6230 fix(core): Make sure that special polling parameters are available on community nodes as well
  packages/cli/src/NodeTypes.ts
  packages/cli/src/commands/BaseCommand.ts
Labels: core, n8n team

#6231 fix(Code Node): Restore help text
  packages/nodes-base/nodes/Code/Code.node.ts
Labels: node/improvement, n8n team

#6229 fix: Prevent type error messages for manual executions (no-changelog)
  packages/core/src/WorkflowExecute.ts
Labels: core, n8n team

#6232 ci: Fix linting issue on master (no-changelog)
  packages/cli/src/commands/BaseCommand.ts
Labels: core, n8n team

#6233 feat(editor): Version Control settings update (WIP)
  packages/editor-ui/src/Interface.ts
  packages/editor-ui/src/plugins/i18n/locales/en.json
  packages/editor-ui/src/stores/versionControl.store.ts
  packages/editor-ui/src/views/SettingsVersionControl.vue
Labels: ui, n8n team

#6228 feat(editor): Updating node reference pattern in expression editor
  cypress/e2e/14-mapping.cy.ts
  packages/editor-ui/src/components/ExpressionEdit.vue
  packages/editor-ui/src/components/VariableSelector.vue
  packages/editor-ui/src/components/__tests__/__snapshots__/RunDataJson.test.ts.snap
  packages/editor-ui/src/utils/__tests__/mappingUtils.test.ts
  packages/editor-ui/src/utils/mappingUtils.ts
Labels: ui, n8n team

#6241 refactor(editor): Add missing interface IUserListAction (no-changelog)
  packages/editor-ui/src/Interface.ts
Labels: ui, n8n team

#6187 feat: Block api feature using licenses, show notice page for trial cloud users
  packages/cli/src/License.ts
  packages/cli/src/PublicApi/index.ts
  packages/cli/src/Server.ts
  packages/cli/src/audit/risks/instance.risk.ts
  packages/cli/src/constants.ts
  packages/editor-ui/src/App.vue
  packages/editor-ui/src/Interface.ts
  packages/editor-ui/src/components/ExecutionsUsage.vue
  packages/editor-ui/src/constants.ts
  packages/editor-ui/src/plugins/i18n/locales/en.json
  packages/editor-ui/src/stores/cloudPlan.store.ts
  packages/editor-ui/src/stores/n8nRoot.store.ts
  packages/editor-ui/src/views/SettingsApiView.vue
Labels: core, ui, n8n team

#6239 feat(editor): Drop support for legacy browsers that do not have native ESM support
  package.json
  packages/editor-ui/vite.config.ts
  pnpm-lock.yaml
Labels: ui, n8n team

#6235 feat(core): Reduce the number of events sent to Sentry
  packages/cli/src/ErrorReporting.ts
  packages/cli/src/UserManagement/PermissionChecker.ts
  packages/core/src/NodeExecuteFunctions.ts
  packages/workflow/src/NodeErrors.ts
  packages/workflow/src/RoutingNode.ts
Labels: core, n8n team

#6253 feat(core): Add experimental proxy support to License-SDK (no-changelog)
  packages/cli/package.json
  pnpm-lock.yaml
Labels: core, n8n team

#6159 feat(editor): Add cloud ExecutionsUsage and API blocking using licenses
  packages/cli/src/License.ts
  packages/cli/src/PublicApi/index.ts
  packages/cli/src/Server.ts
  packages/cli/src/audit/risks/instance.risk.ts
  packages/cli/src/constants.ts
  packages/design-system/src/components/N8nButton/Button.vue
  packages/design-system/src/components/N8nMenu/Menu.vue
  packages/editor-ui/src/App.vue
  packages/editor-ui/src/Interface.ts
  packages/editor-ui/src/api/cloudPlans.ts
  packages/editor-ui/src/components/ExecutionsUsage.vue
  packages/editor-ui/src/components/MainSidebar.vue
  packages/editor-ui/src/constants.ts
  packages/editor-ui/src/plugins/i18n/locales/en.json
  packages/editor-ui/src/plugins/icons/index.ts
  packages/editor-ui/src/stores/cloudPlan.store.ts
  packages/editor-ui/src/stores/index.ts
  packages/editor-ui/src/stores/n8nRoot.store.ts
  packages/editor-ui/src/utils/apiUtils.ts
  packages/editor-ui/src/views/SettingsApiView.vue
Labels: ui, n8n team

#6238 fix: Add itemSize config to workflows view recycle scroller (no-changelog)
  cypress/e2e/17-sharing.cy.ts
  packages/design-system/src/components/N8nRecycleScroller/__tests__/RecycleScroller.spec.ts
  packages/design-system/src/components/N8nRecycleScroller/__tests__/__snapshots__/RecycleScroller.spec.ts.snap
  packages/editor-ui/src/components/layouts/ResourcesListLayout.vue
  packages/editor-ui/src/views/WorkflowsView.vue
Labels: ui, n8n team

#5794 feat(core): Return OAuth2 error body if available
  packages/cli/src/credentials/oauth2Credential.api.ts
  packages/cli/templates/oauth-error-callback.handlebars
Labels: core, community, n8n team

#6116 fix: Remove workflow execution credential error message when instance owner
  packages/editor-ui/src/mixins/nodeHelpers.ts
Labels: ui, n8n team

#6056 feat(core): Replace client-oauth2 with an in-repo package
  .github/workflows/ci-master.yml
  .github/workflows/ci-pull-requests.yml
  packages/@n8n/client-oauth2/.eslintrc.js
  packages/@n8n/client-oauth2/jest.config.js
  packages/@n8n/client-oauth2/package.json
  packages/@n8n/client-oauth2/src/ClientOAuth2.ts
  packages/@n8n/client-oauth2/src/ClientOAuth2Token.ts
  packages/@n8n/client-oauth2/src/CodeFlow.ts
  packages/@n8n/client-oauth2/src/CredentialsFlow.ts
  packages/@n8n/client-oauth2/src/constants.ts
  packages/@n8n/client-oauth2/src/index.ts
  packages/@n8n/client-oauth2/src/types.ts
  packages/@n8n/client-oauth2/src/utils.ts
  packages/@n8n/client-oauth2/test/CodeFlow.test.ts
  packages/@n8n/client-oauth2/test/CredentialsFlow.test.ts
  packages/@n8n/client-oauth2/test/config.ts
  packages/@n8n/client-oauth2/tsconfig.build.json
  packages/@n8n/client-oauth2/tsconfig.json
  packages/cli/package.json
  packages/cli/src/credentials/oauth2Credential.api.ts
  packages/cli/tsconfig.json
  packages/core/package.json
  packages/core/src/NodeExecuteFunctions.ts
  packages/core/src/OAuth2Helper.ts
  packages/core/tsconfig.json
  pnpm-lock.yaml
  pnpm-workspace.yaml
Labels: core, n8n team

#5613 feat(Respond to Webhook Node): Move from Binary Buffer to Binary streaming
  packages/cli/src/WebhookHelpers.ts
  packages/nodes-base/nodes/RespondToWebhook/RespondToWebhook.node.ts
  packages/workflow/src/Interfaces.ts
Labels: node/improvement, n8n team, skip-e2e

#6269 fix(SSH Node): Replace ~ with /home/username
  packages/nodes-base/nodes/Ssh/Ssh.node.ts
Labels: n8n team, node/issue

#6270 fix(OpenAI Node): Descriptive errors
  packages/nodes-base/nodes/OpenAi/ChatDescription.ts
  packages/nodes-base/nodes/OpenAi/GenericFunctions.ts
  packages/nodes-base/nodes/OpenAi/ImageDescription.ts
  packages/nodes-base/nodes/OpenAi/OpenAi.node.ts
  packages/nodes-base/nodes/OpenAi/TextDescription.ts
Labels: n8n team, node/issue

#6166 docs: Remove missed beta text from Notion node (no-changelog)
  packages/nodes-base/nodes/Notion/NotionTrigger.node.ts
  packages/nodes-base/nodes/Notion/v1/VersionDescription.ts
  packages/nodes-base/nodes/Notion/v2/VersionDescription.ts
Labels: node/improvement, n8n team

#6053 feat(Gotify Node): Add support for self signed certificates
  packages/nodes-base/credentials/GotifyApi.credentials.ts
  packages/nodes-base/nodes/Gotify/GenericFunctions.ts
Labels: node/improvement, community

#6274 fix(Google Calendar Node): All day option fix
  packages/nodes-base/nodes/Google/Calendar/EventDescription.ts
  packages/nodes-base/nodes/Google/Calendar/GoogleCalendar.node.ts
Labels: n8n team, node/issue

#6275 feat(core): Include openssh in the base docker image (no-changelog)
  docker/images/n8n-base/Dockerfile
Labels: n8n team

#3632 feat(Send Email Node): Add content-id for email attachments
  packages/nodes-base/nodes/EmailSend/v2/send.operation.ts
Labels: node/improvement, community, in linear

#6279 feat(SSH Node): Credentials test
  packages/nodes-base/nodes/Ssh/Ssh.node.ts
Labels: n8n team, node/issue

#6277 fix(Strava Trigger Node): Fix issue with delete events failing to display data
  packages/nodes-base/nodes/Strava/StravaTrigger.node.ts
Labels: node/improvement, n8n team

#6259 fix(Postgres Node): Remove reusable connections (no-changelog)
  packages/nodes-base/nodes/Postgres/v2/actions/database/update.operation.ts
  packages/nodes-base/nodes/Postgres/v2/actions/database/upsert.operation.ts
  packages/nodes-base/nodes/Postgres/v2/actions/router.ts
  packages/nodes-base/nodes/Postgres/v2/methods/credentialTest.ts
  packages/nodes-base/nodes/Postgres/v2/methods/listSearch.ts
  packages/nodes-base/nodes/Postgres/v2/methods/loadOptions.ts
  packages/nodes-base/nodes/Postgres/v2/transport/index.ts
Labels: n8n team, node/issue

#6278 fix(core): Prevent app crashes because of unhandled promises in poll and trigger nodes
  packages/cli/src/ActiveWorkflowRunner.ts
Labels: core, n8n team

#6291 fix(editor): UI copy fix for Date & Time node (no-changelog)
  packages/nodes-base/nodes/DateTime/V2/CurrentDateDescription.ts
Labels: node/improvement, n8n team

#6225 feat(RabbitMQ Node): Add mode for acknowledging and deleting from queue later in workflow
  packages/nodes-base/nodes/RabbitMQ/RabbitMQ.node.ts
  packages/nodes-base/nodes/RabbitMQ/RabbitMQTrigger.node.ts
Labels: node/improvement, n8n team

#6292 feat: Add dangerouslyUseHTMLString where needed (no-changelog)
  packages/editor-ui/src/App.vue
  packages/editor-ui/src/components/ParameterInputFull.vue
  packages/editor-ui/src/components/WorkflowActivator.vue
  packages/editor-ui/src/components/WorkflowShareModal.ee.vue
  packages/editor-ui/src/composables/useToast.ts
  packages/editor-ui/src/mixins/genericHelpers.ts
  packages/editor-ui/src/mixins/pushConnection.ts
  packages/editor-ui/src/mixins/workflowHelpers.ts
  packages/editor-ui/src/views/NodeView.vue
  packages/editor-ui/src/views/SetupView.vue
Labels: ui, n8n team

#6296 fix(Wekan Node): Handle response correctly
  packages/nodes-base/nodes/Wekan/Wekan.node.ts
Labels: node/improvement, n8n team

#6297 fix(core): Optimize SharedWorkflow queries
  packages/cli/src/ActiveWorkflowRunner.ts
  packages/cli/src/PublicApi/v1/handlers/workflows/workflows.service.ts
  packages/cli/src/Server.ts
  packages/cli/src/UserManagement/PermissionChecker.ts
Labels: core, n8n team

#6298 fix(SSH Node): Private key field as password and credential test
  packages/nodes-base/credentials/SshPrivateKey.credentials.ts
  packages/nodes-base/nodes/Ssh/Ssh.node.ts
Labels: n8n team, node/issue

#6300 fix: Prevent removing manual executions when setting says to save
  packages/cli/src/WorkflowExecuteAdditionalData.ts
Labels: core, n8n team

#6301 fix: Initialize license in queue mode correctly
  packages/cli/src/License.ts
  packages/cli/src/commands/BaseCommand.ts
  packages/cli/src/commands/start.ts
  packages/cli/src/commands/webhook.ts
  packages/cli/src/commands/worker.ts
Labels: core, n8n team

#5146 feat(LoneScale Node): Add LoneScale node and Trigger node
  packages/nodes-base/credentials/LoneScaleApi.credentials.ts
  packages/nodes-base/nodes/LoneScale/GenericFunctions.ts
  packages/nodes-base/nodes/LoneScale/LoneScale.node.json
  packages/nodes-base/nodes/LoneScale/LoneScaleList.node.ts
  packages/nodes-base/nodes/LoneScale/LoneScaleTrigger.node.json
  packages/nodes-base/nodes/LoneScale/LoneScaleTrigger.node.ts
  packages/nodes-base/nodes/LoneScale/constants.ts
  packages/nodes-base/nodes/LoneScale/lonescale-logo.svg
  packages/nodes-base/package.json
Labels: node/new, community

#6303 fix(editor): Link to log streaming doc from log streaming (no-changelog)
  packages/editor-ui/src/plugins/i18n/locales/en.json
Labels: ui, n8n team

#6285 fix(editor): Fix inverted checks on modal confirmation results
  packages/editor-ui/src/components/CredentialEdit/CredentialEdit.vue
  packages/editor-ui/src/plugins/i18n/locales/en.json
Labels: ui, n8n team

#6281 feat(core): Remove all floating promises. Enforce `@typescript-eslint/no-floating-promises`
  packages/@n8n_io/eslint-config/base.js
  packages/cli/src/ActiveWorkflowRunner.ts
  packages/cli/src/Server.ts
  packages/cli/src/TestWebhooks.ts
  packages/cli/src/WaitTracker.ts
  packages/cli/src/WaitingWebhooks.ts
  packages/cli/src/WorkflowRunner.ts
  packages/cli/src/WorkflowRunnerProcess.ts
  packages/cli/src/commands/start.ts
  packages/cli/src/commands/worker.ts
  packages/cli/src/middlewares/basicAuth.ts
  packages/cli/src/middlewares/externalJWTAuth.ts
  packages/cli/test/integration/credentials.ee.test.ts
  packages/cli/test/integration/credentials.test.ts
  packages/cli/test/integration/eventbus.test.ts
  packages/cli/test/integration/ldap/ldap.api.test.ts
  packages/cli/test/integration/nodes.api.test.ts
  packages/cli/test/integration/publicApi/credentials.test.ts
  packages/cli/test/integration/publicApi/executions.test.ts
  packages/cli/test/integration/publicApi/workflows.test.ts
  packages/cli/test/integration/shared/utils.ts
  packages/cli/test/integration/users.api.test.ts
  packages/cli/test/integration/variables.test.ts
  packages/cli/test/unit/ActiveExecutions.test.ts
  packages/cli/test/unit/PermissionChecker.test.ts
  packages/cli/test/unit/PostHog.test.ts
  packages/cli/test/unit/Telemetry.test.ts
  packages/cli/test/unit/WorkflowCredentials.test.ts
  packages/cli/test/unit/controllers/me.controller.test.ts
  packages/cli/test/unit/controllers/owner.controller.test.ts
  packages/cli/test/unit/controllers/translation.controller.test.ts
  packages/cli/test/unit/middlewares/basicAuth.test.ts
  packages/cli/test/unit/repositories/role.repository.test.ts
Labels: core, n8n team

#6199 ci: Forbid skipping tests (no-changelog)
  packages/@n8n_io/eslint-config/base.js
  packages/@n8n_io/eslint-config/local-rules.js
  packages/cli/test/integration/commands/reset.cmd.test.ts
  packages/cli/test/integration/eventbus.test.ts
  packages/cli/test/integration/publicApi/executions.test.ts
Labels: core, n8n team

#6299 ci: Add rule `dangerously-use-html-string-missing`
  packages/@n8n_io/eslint-config/frontend.js
  packages/@n8n_io/eslint-config/local-rules.js
  packages/design-system/.eslintrc.js
Labels: n8n team

#6247 feat(Execution Data Node): New node
  packages/nodes-base/nodes/ExecutionData/ExecutionData.node.json
  packages/nodes-base/nodes/ExecutionData/ExecutionData.node.ts
  packages/nodes-base/package.json
Labels: node/new, n8n team

#6284 fix(editor): Fix design system button with icon vertical alignment
  packages/design-system/src/components/N8nButton/Button.vue
Labels: ui, n8n team

#6311 feat: Add tab visibility change detection when polling executions (no-changelog)
  packages/editor-ui/src/components/ExecutionsList.vue
  packages/editor-ui/src/components/ExecutionsView/ExecutionsSidebar.vue
Labels: ui, n8n team

#6318 fix(Code Node): Update vm2 to address CVE-2023-32313
  packages/nodes-base/nodes/Code/JavaScriptSandbox.ts
  packages/nodes-base/nodes/Function/Function.node.ts
  packages/nodes-base/nodes/FunctionItem/FunctionItem.node.ts
  packages/nodes-base/package.json
  pnpm-lock.yaml
Labels: node/improvement, n8n team, security

#6307 feat(editor): Bring back checklist experiment (no-changelog)
  packages/editor-ui/src/constants.ts
  packages/editor-ui/src/stores/posthog.store.ts
  packages/editor-ui/src/stores/segment.store.ts
Labels: ui, n8n team

#6314 fix(core): Optimize getSharedWorkflowIds query
  jest.config.js
  packages/cli/src/WorkflowHelpers.ts
  packages/cli/src/config/index.ts
  packages/cli/src/workflows/workflows.services.ts
  packages/cli/test/integration/workflows.controller.ee.test.ts
Labels: core, n8n team

#6322 fix(core): Do not track errored workflow executions for automated executions (no-changelog)
  packages/cli/src/telemetry/index.ts
  packages/cli/test/unit/Telemetry.test.ts
Labels: core, n8n team

#6333 fix(editor): Fix Luxon date parsing of ExecutionsUsage component
  packages/editor-ui/src/App.vue
  packages/editor-ui/src/mixins/nodeHelpers.ts
  packages/editor-ui/src/stores/cloudPlan.store.ts
Labels: ui, n8n team

#6328 feat: Add manual login option and password reset link for SSO
  packages/cli/src/Interfaces.ts
  packages/cli/src/controllers/auth.controller.ts
  packages/cli/src/controllers/passwordReset.controller.ts
  packages/cli/src/controllers/users.controller.ts
  packages/cli/src/databases/entities/User.ts
  packages/cli/src/requests.ts
  packages/cli/src/user/user.service.ts
  packages/design-system/src/components/N8nUserInfo/UserInfo.vue
  packages/design-system/src/components/N8nUsersList/UsersList.vue
  packages/editor-ui/src/Interface.ts
  packages/editor-ui/src/api/users.ts
  packages/editor-ui/src/plugins/i18n/locales/en.json
  packages/editor-ui/src/stores/users.store.ts
  packages/editor-ui/src/views/SettingsUsersView.vue
  packages/workflow/src/Interfaces.ts
Labels: core, ui, n8n team

#6331 fix(Code Node): Fix `item` and `items` alias regression
  packages/nodes-base/nodes/Code/Code.node.ts
  packages/nodes-base/nodes/Code/test/Code.workflow.json
Labels: node/improvement, n8n team

#6313 refactor: Add telemetry to upgrade paths (no-changelog)
  packages/editor-ui/src/components/ExecutionsUsage.vue
  packages/editor-ui/src/components/MainHeader/WorkflowDetails.vue
  packages/editor-ui/src/stores/cloudPlan.store.ts
  packages/editor-ui/src/stores/ui.store.ts
  packages/editor-ui/src/views/SettingsApiView.vue
  packages/editor-ui/src/views/SettingsUsersView.vue
  packages/editor-ui/src/views/VariablesView.vue
Labels: ui, n8n team

#6336 fix: Show `Ask AI` only on Code Node
  packages/editor-ui/src/components/CodeNodeEditor/CodeNodeEditor.vue
  packages/editor-ui/src/components/ParameterInput.vue
Labels: ui, n8n team
