Repository n8n-io/n8n, pull requests merged in 2024-08, with the labels that each got.

#10247 fix(core): Fix expressions in webhook nodes(Form, Webhook) to access previous node's data
  packages/cli/src/WebhookHelpers.ts
  packages/core/src/NodeExecuteFunctions.ts
  packages/workflow/src/Interfaces.ts
  packages/workflow/src/Workflow.ts
Labels: core, n8n team

#10243 fix(n8n Form Trigger Node): Improve copy and a few tweaks (no-changelog)
  packages/cli/templates/form-trigger.handlebars
  packages/nodes-base/nodes/Form/common.descriptions.ts
Labels: node/improvement, n8n team

#10272 fix(core): Fix oauth2 callback and add integration tests (no-changelog)
  packages/cli/src/controllers/oauth/abstractOAuth.controller.ts
  packages/cli/src/controllers/oauth/oAuth1Credential.controller.ts
  packages/cli/src/controllers/oauth/oAuth2Credential.controller.ts
  packages/cli/src/requests.ts
  packages/cli/test/integration/controllers/oauth/oauth2.api.test.ts
  packages/cli/test/integration/shared/types.ts
  packages/cli/test/integration/shared/utils/testServer.ts
Labels: core, n8n team

#10264 refactor(core): Decouple workflow created, saved, deleted events from internal hooks (no-changelog)
  packages/cli/src/InternalHooks.ts
  packages/cli/src/PublicApi/v1/handlers/workflows/workflows.handler.ts
  packages/cli/src/eventbus/__tests__/audit-event-relay.service.test.ts
  packages/cli/src/eventbus/audit-event-relay.service.ts
  packages/cli/src/eventbus/event.types.ts
  packages/cli/src/telemetry/telemetry-event-relay.service.ts
  packages/cli/src/workflows/workflow.service.ts
  packages/cli/src/workflows/workflows.controller.ts
Labels: core, n8n team

#10271 fix(editor): Enable moving resources only if team projects are available by the license
  packages/editor-ui/src/components/CredentialCard.test.ts
  packages/editor-ui/src/components/CredentialCard.vue
  packages/editor-ui/src/components/Projects/ProjectNavigation.vue
  packages/editor-ui/src/components/WorkflowCard.test.ts
  packages/editor-ui/src/components/WorkflowCard.vue
  packages/editor-ui/src/stores/projects.store.ts
Labels: ui, n8n team, release/backport

#10267 fix(core): Surface enterprise trial error message
  packages/cli/src/license/license.controller.ts
Labels: core, n8n team

#10254 ci: Introduce lint rule `no-type-unsafe-event-emitter` (no-changelog)
  packages/@n8n_io/eslint-config/local-rules.js
  packages/cli/.eslintrc.js
  packages/cli/src/eventbus/MessageEventBus/MessageEventBus.ts
Labels: core, n8n team

#10269 feat(core): Support create, read, update, delete projects in Public API
  packages/cli/src/PublicApi/v1/handlers/projects/projects.handler.ts
  packages/cli/src/PublicApi/v1/handlers/projects/spec/paths/projects.projectId.yml
  packages/cli/src/PublicApi/v1/handlers/projects/spec/paths/projects.yml
  packages/cli/src/PublicApi/v1/handlers/projects/spec/schemas/parameters/projectId.yml
  packages/cli/src/PublicApi/v1/handlers/projects/spec/schemas/project.yml
  packages/cli/src/PublicApi/v1/handlers/projects/spec/schemas/projectList.yml
  packages/cli/src/PublicApi/v1/openapi.yml
  packages/cli/test/integration/publicApi/projects.test.ts
  packages/cli/test/integration/shared/db/projects.ts
  packages/cli/test/integration/shared/db/users.ts
Labels: core, n8n team

#10259 feat(core): Allow transferring credentials in Public API
  packages/cli/src/PublicApi/types.ts
  packages/cli/src/PublicApi/v1/handlers/credentials/credentials.handler.ts
  packages/cli/src/PublicApi/v1/handlers/credentials/spec/paths/credentials.id.transfer.yml
  packages/cli/src/PublicApi/v1/handlers/credentials/spec/schemas/parameters/credentialId.yml
  packages/cli/src/PublicApi/v1/openapi.yml
  packages/cli/test/integration/publicApi/credentials.test.ts
  packages/cli/test/integration/publicApi/workflows.test.ts
  packages/cli/test/integration/shared/db/credentials.ts
Labels: core, n8n team

#10280 refactor(core): Decouple post workflow execute event from internal hooks (no-changelog)
  packages/cli/src/InternalHooks.ts
  packages/cli/src/WorkflowExecuteAdditionalData.ts
  packages/cli/src/WorkflowRunner.ts
  packages/cli/src/eventbus/__tests__/audit-event-relay.service.test.ts
  packages/cli/src/eventbus/audit-event-relay.service.ts
  packages/cli/src/eventbus/event.types.ts
  packages/cli/src/executions/execution-recovery.service.ts
  packages/cli/src/telemetry/telemetry-event-relay.service.ts
Labels: core, n8n team

#10282 ci: Fix DB tests (no-changelog)
  packages/cli/test/integration/prometheus-metrics.test.ts
Labels: core, n8n team

#10283 refactor(core): Mark schema env vars used by cloud hooks (no-changelog)
  packages/cli/src/config/schema.ts
Labels: core, n8n team

#10276 fix(core): Make execution and its data creation atomic
  packages/cli/src/ActiveExecutions.ts
  packages/cli/src/databases/repositories/execution.repository.ts
  packages/cli/src/databases/repositories/executionData.repository.ts
  packages/cli/test/integration/database/repositories/execution.repository.test.ts
Labels: core, n8n team

#10250 feat(core): Allow filtering executions and users by project in Public API
  packages/cli/src/PublicApi/types.ts
  packages/cli/src/PublicApi/v1/handlers/executions/executions.handler.ts
  packages/cli/src/PublicApi/v1/handlers/executions/spec/paths/executions.yml
  packages/cli/src/PublicApi/v1/handlers/users/spec/paths/users.yml
  packages/cli/src/PublicApi/v1/handlers/users/users.handler.ee.ts
  packages/cli/src/PublicApi/v1/handlers/users/users.service.ee.ts
  packages/cli/src/PublicApi/v1/handlers/workflows/workflows.service.ts
  packages/cli/src/databases/repositories/projectRelation.repository.ts
  packages/cli/src/requests.ts
  packages/cli/src/workflows/workflowSharing.service.ts
  packages/cli/test/integration/publicApi/executions.test.ts
  packages/cli/test/integration/publicApi/users.ee.test.ts
Labels: core, n8n team

#10242 refactor(core): Move instanceRole to InstanceSettings (no-changelog)
  packages/cli/src/License.ts
  packages/cli/src/commands/start.ts
  packages/cli/src/config/schema.ts
  packages/cli/src/executions/__tests__/execution-recovery.service.test.ts
  packages/cli/src/executions/execution-recovery.service.ts
  packages/cli/src/services/orchestration.service.ts
  packages/cli/src/services/orchestration/main/MultiMainSetup.ee.ts
  packages/cli/src/services/pruning.service.ts
  packages/cli/test/integration/pruning.service.test.ts
  packages/cli/test/unit/WaitTracker.test.ts
  packages/cli/test/unit/services/orchestration.service.test.ts
  packages/core/src/InstanceSettings.ts
Labels: core, n8n team

#10248 feat(core): Show sub-node error on the logs pane. Open logs pane on sub-node error
  cypress/constants.ts
  cypress/e2e/233-AI-switch-to-logs-on-error.cy.ts
  cypress/pages/ndv.ts
  packages/@n8n/nodes-langchain/nodes/tools/ToolCode/ToolCode.node.ts
  packages/editor-ui/src/components/Error/NodeErrorView.vue
  packages/editor-ui/src/components/OutputPanel.vue
  packages/editor-ui/src/components/RunData.vue
Labels: ui, n8n team

#10275 fix(editor): Fix execution retry button
  packages/editor-ui/src/components/executions/workflow/WorkflowExecutionsCard.test.ts
  packages/editor-ui/src/composables/__tests__/useExecutionHelpers.test.ts
  packages/editor-ui/src/composables/useExecutionHelpers.ts
Labels: ui, n8n team, release/backport

#10284 refactor(core): Clean up event relays (no-changelog)
  packages/cli/src/ExternalSecrets/ExternalSecretsManager.ee.ts
  packages/cli/src/InternalHooks.ts
  packages/cli/src/Ldap/ldap.controller.ee.ts
  packages/cli/src/Ldap/ldap.service.ee.ts
  packages/cli/src/PublicApi/index.ts
  packages/cli/src/PublicApi/v1/handlers/credentials/credentials.service.ts
  packages/cli/src/PublicApi/v1/handlers/sourceControl/sourceControl.handler.ts
  packages/cli/src/PublicApi/v1/handlers/workflows/workflows.handler.ts
  packages/cli/src/Server.ts
  packages/cli/src/UserManagement/email/UserManagementMailer.ts
  packages/cli/src/WorkflowExecuteAdditionalData.ts
  packages/cli/src/WorkflowRunner.ts
  packages/cli/src/auth/methods/email.ts
  packages/cli/src/auth/methods/ldap.ts
  packages/cli/src/commands/BaseCommand.ts
  packages/cli/src/commands/start.ts
  packages/cli/src/commands/worker.ts
  packages/cli/src/concurrency/__tests__/concurrency-control.service.test.ts
  packages/cli/src/concurrency/concurrency-control.service.ts
  packages/cli/src/controllers/auth.controller.ts
  packages/cli/src/controllers/communityPackages.controller.ts
  packages/cli/src/controllers/invitation.controller.ts
  packages/cli/src/controllers/me.controller.ts
  packages/cli/src/controllers/passwordReset.controller.ts
  packages/cli/src/controllers/project.controller.ts
  packages/cli/src/controllers/users.controller.ts
  packages/cli/src/credentials/credentials.controller.ts
  packages/cli/src/decorators/Redactable.ts
  packages/cli/src/environments/sourceControl/sourceControl.controller.ee.ts
  packages/cli/src/environments/sourceControl/sourceControl.service.ee.ts
  packages/cli/src/environments/variables/variables.service.ee.ts
  packages/cli/src/errors/redactable.error.ts
  packages/cli/src/eventbus/event.service.ts
  packages/cli/src/events/__tests__/log-streaming-event-relay.test.ts
  packages/cli/src/events/event-relay.ts
  packages/cli/src/events/event.service.ts
  packages/cli/src/events/log-streaming-event-relay.ts
  packages/cli/src/events/relay-event-map.ts
  packages/cli/src/events/telemetry-event-relay.ts
  packages/cli/src/executions/execution-recovery.service.ts
  packages/cli/src/license/license.service.ts
  packages/cli/src/services/user.service.ts
  packages/cli/src/sso/saml/routes/saml.controller.ee.ts
  packages/cli/src/workflows/workflow.service.ts
  packages/cli/src/workflows/workflows.controller.ts
  packages/cli/test/integration/ExternalSecrets/externalSecrets.api.test.ts
  packages/cli/test/integration/commands/worker.cmd.test.ts
  packages/cli/test/integration/shared/utils/testCommand.ts
  packages/cli/test/unit/license/license.service.test.ts
Labels: core, n8n team

#10286 refactor(core): Port cache config (no-changelog)
  packages/@n8n/config/src/configs/cache.ts
  packages/@n8n/config/src/configs/credentials.ts
  packages/@n8n/config/src/configs/database.ts
  packages/@n8n/config/src/configs/email.ts
  packages/@n8n/config/src/configs/endpoints.ts
  packages/@n8n/config/src/configs/event-bus.ts
  packages/@n8n/config/src/configs/external-secrets.ts
  packages/@n8n/config/src/configs/external-storage.ts
  packages/@n8n/config/src/configs/nodes.ts
  packages/@n8n/config/src/configs/public-api.ts
  packages/@n8n/config/src/configs/templates.ts
  packages/@n8n/config/src/configs/version-notifications.ts
  packages/@n8n/config/src/configs/workflows.ts
  packages/@n8n/config/src/index.ts
  packages/@n8n/config/test/config.test.ts
  packages/cli/src/config/schema.ts
  packages/cli/src/services/cache/cache.service.ts
  packages/cli/test/integration/activation-errors.service.test.ts
  packages/cli/test/integration/prometheus-metrics.test.ts
  packages/cli/test/unit/services/cache.service.test.ts
Labels: core, n8n team

#10290 fix(core): Webhook and form baseUrl missing
  packages/cli/src/WorkflowExecuteAdditionalData.ts
Labels: core, n8n team

#10228 feat(core): Support community packages in scaling-mode
  packages/@n8n/config/src/configs/nodes.ts
  packages/@n8n/config/test/config.test.ts
  packages/cli/src/commands/BaseCommand.ts
  packages/cli/src/commands/execute.ts
  packages/cli/src/commands/executeBatch.ts
  packages/cli/src/commands/start.ts
  packages/cli/src/commands/webhook.ts
  packages/cli/src/commands/worker.ts
  packages/cli/src/controllers/communityPackages.controller.ts
  packages/cli/src/services/__tests__/communityPackages.service.test.ts
  packages/cli/src/services/communityPackages.service.ts
  packages/cli/src/services/orchestration/main/handleCommandMessageMain.ts
  packages/cli/src/services/orchestration/webhook/handleCommandMessageWebhook.ts
  packages/cli/src/services/orchestration/worker/handleCommandMessageWorker.ts
  packages/cli/src/services/redis/RedisServiceCommands.ts
  packages/cli/test/integration/community-packages.api.test.ts
  packages/editor-ui/src/constants.ts
  packages/editor-ui/src/plugins/i18n/locales/en.json
  packages/editor-ui/src/views/SettingsCommunityNodesView.vue
Labels: core, n8n team

#10292 refactor(core): Decouple user events from internal hooks (no-changelog)
  packages/cli/src/Interfaces.ts
  packages/cli/src/InternalHooks.ts
  packages/cli/src/PublicApi/v1/handlers/executions/executions.handler.ts
  packages/cli/src/PublicApi/v1/handlers/users/users.handler.ee.ts
  packages/cli/src/PublicApi/v1/handlers/workflows/workflows.handler.ts
  packages/cli/src/auth/methods/ldap.ts
  packages/cli/src/controllers/__tests__/me.controller.test.ts
  packages/cli/src/controllers/invitation.controller.ts
  packages/cli/src/controllers/me.controller.ts
  packages/cli/src/controllers/passwordReset.controller.ts
  packages/cli/src/controllers/users.controller.ts
  packages/cli/src/events/__tests__/log-streaming-event-relay.test.ts
  packages/cli/src/events/relay-event-map.ts
  packages/cli/src/events/telemetry-event-relay.ts
  packages/cli/src/services/user.service.ts
Labels: core, n8n team

#10295 refactor(core): Remove stray log from telemetry event relay (no-changelog)
  packages/cli/src/events/telemetry-event-relay.ts
Labels: skip-e2e

#10293 fix(core): Fix user telemetry bugs
  packages/cli/src/controllers/__tests__/me.controller.test.ts
  packages/cli/src/controllers/__tests__/users.controller.test.ts
  packages/cli/src/controllers/me.controller.ts
  packages/cli/src/controllers/users.controller.ts
Labels: core, n8n team

#10245 feat(editor): Auto-add LLM chain for new LLM nodes on empty canvas
  cypress/constants.ts
  cypress/e2e/233-AI-switch-to-logs-on-error.cy.ts
  cypress/e2e/30-langchain.cy.ts
  packages/@n8n/nodes-langchain/nodes/llms/LMChatAnthropic/LmChatAnthropic.node.ts
  packages/@n8n/nodes-langchain/nodes/llms/LMChatOllama/LmChatOllama.node.ts
  packages/@n8n/nodes-langchain/nodes/llms/LMChatOpenAi/LmChatOpenAi.node.ts
  packages/@n8n/nodes-langchain/nodes/llms/LMCohere/LmCohere.node.ts
  packages/@n8n/nodes-langchain/nodes/llms/LMOllama/LmOllama.node.ts
  packages/@n8n/nodes-langchain/nodes/llms/LMOpenAi/LmOpenAi.node.ts
  packages/@n8n/nodes-langchain/nodes/llms/LMOpenHuggingFaceInference/LmOpenHuggingFaceInference.node.ts
  packages/@n8n/nodes-langchain/nodes/llms/LmChatAwsBedrock/LmChatAwsBedrock.node.ts
  packages/@n8n/nodes-langchain/nodes/llms/LmChatAzureOpenAi/LmChatAzureOpenAi.node.ts
  packages/@n8n/nodes-langchain/nodes/llms/LmChatGoogleGemini/LmChatGoogleGemini.node.ts
  packages/@n8n/nodes-langchain/nodes/llms/LmChatGooglePalm/LmChatGooglePalm.node.ts
  packages/@n8n/nodes-langchain/nodes/llms/LmChatGoogleVertex/LmChatGoogleVertex.node.ts
  packages/@n8n/nodes-langchain/nodes/llms/LmChatGroq/LmChatGroq.node.ts
  packages/@n8n/nodes-langchain/nodes/llms/LmChatMistralCloud/LmChatMistralCloud.node.ts
  packages/@n8n/nodes-langchain/nodes/llms/LmGooglePalm/LmGooglePalm.node.ts
  packages/editor-ui/src/Interface.ts
  packages/editor-ui/src/components/Node/NodeCreator/composables/useActions.ts
  packages/editor-ui/src/views/NodeView.vue
Labels: ui, n8n team

#10237 fix(core): Move error obfuscation to FE (no-changelog)
  packages/core/src/WorkflowExecute.ts
  packages/editor-ui/src/components/Error/NodeErrorView.vue
  packages/editor-ui/src/plugins/i18n/locales/en.json
  packages/workflow/src/errors/node-operation.error.ts
  packages/workflow/test/errors/node.error.test.ts
Labels: core, ui, n8n team

#10294 refactor(editor): Boost n8n Form Trigger in nodes-panel search results
  packages/editor-ui/src/utils/sortUtils.ts
  packages/nodes-base/nodes/Form/FormTrigger.node.json
Labels: node/improvement, ui, n8n team

#10299 fix(core): Revert transactions until we remove the legacy sqlite driver
  .github/workflows/test-workflows.yml
  packages/cli/src/databases/repositories/execution.repository.ts
  packages/cli/src/databases/repositories/executionData.repository.ts
  packages/cli/test/integration/database/repositories/execution.repository.test.ts
Labels: core, n8n team

#10203 feat(Postgres Chat Memory, Redis Chat Memory, Xata): Add support for context window length
  packages/@n8n/nodes-langchain/nodes/memory/MemoryBufferWindow/MemoryBufferWindow.node.ts
  packages/@n8n/nodes-langchain/nodes/memory/MemoryPostgresChat/MemoryPostgresChat.node.ts
  packages/@n8n/nodes-langchain/nodes/memory/MemoryRedisChat/MemoryRedisChat.node.ts
  packages/@n8n/nodes-langchain/nodes/memory/MemoryXata/MemoryXata.node.ts
  packages/@n8n/nodes-langchain/nodes/memory/descriptions.ts
Labels: n8n team

#10302 fix(core): Ensure OAuth token data is not stubbed in source control
  packages/cli/src/environments/sourceControl/__tests__/source-control-export.service.test.ts
  packages/cli/src/environments/sourceControl/sourceControlExport.service.ee.ts
  packages/cli/src/environments/sourceControl/sourceControlImport.service.ee.ts
  packages/core/src/NodeExecuteFunctions.ts
Labels: core, n8n team

#10307 docs(Slack Node): Get user operation typo fix in ui
  packages/nodes-base/nodes/Slack/V2/UserDescription.ts
Labels: node/improvement, n8n team

#10298 fix(core): VM2 sandbox should not throw on `new Promise`
  packages/@n8n/nodes-langchain/package.json
  packages/nodes-base/nodes/Code/test/Code.workflow.json
  packages/nodes-base/package.json
  pnpm-lock.yaml
Labels: node/improvement, n8n team, release/backport

#10300 fix(editor): Update project tabs test (no-changelog)
  packages/design-system/src/components/N8nTabs/Tabs.vue
  packages/editor-ui/src/components/Projects/ProjectTabs.test.ts
Labels: ui, n8n team

#10308 fix(editor): Update design system Avatar component to show initials also when only firstName or lastName is given
  packages/design-system/src/components/N8nAvatar/Avatar.vue
  packages/design-system/src/components/N8nAvatar/__tests__/Avatar.test.ts
Labels: ui, n8n team

#10257 docs: Fix links to license files in readme (no-changelog)
  README.md
  docker/images/n8n/README.md
  packages/@n8n/chat/README.md
  packages/@n8n/nodes-langchain/README.md
  packages/cli/README.md
  packages/cli/src/PublicApi/v1/openapi.yml
  packages/core/README.md
  packages/design-system/README.md
  packages/editor-ui/README.md
  packages/editor-ui/src/components/AboutModal.vue
  packages/node-dev/README.md
  packages/nodes-base/README.md
  packages/workflow/README.md
Labels: node/improvement, core, ui, n8n team

#10129 feat(Calendly Trigger Node): Update event names (no-changelog)
  packages/nodes-base/nodes/Calendly/CalendlyTrigger.node.ts
Labels: node/improvement, community, in linear

#10311 feat(Lemlist Trigger Node): Update Trigger events
  packages/nodes-base/nodes/Lemlist/GenericFunctions.ts
  packages/nodes-base/nodes/Lemlist/LemlistTrigger.node.ts
Labels: node/improvement, n8n team

#10310 feat: Return scopes on executions (no-changelog)
  packages/cli/src/databases/repositories/projectRelation.repository.ts
  packages/cli/src/databases/repositories/sharedWorkflow.repository.ts
  packages/cli/src/executions/__tests__/execution.service.test.ts
  packages/cli/src/executions/__tests__/executions.controller.test.ts
  packages/cli/src/executions/execution.service.ts
  packages/cli/src/executions/execution.types.ts
  packages/cli/src/executions/executions.controller.ts
  packages/cli/src/workflows/workflowSharing.service.ts
  packages/cli/test/integration/execution.service.integration.test.ts
  packages/cli/test/integration/executions.controller.test.ts
Labels: core, n8n team

#10246 feat(HTTP Request Tool Node): Use DynamicStructureTool with models supporting it (no-changelog)
  packages/@n8n/nodes-langchain/nodes/agents/Agent/agents/OpenAiFunctionsAgent/execute.ts
  packages/@n8n/nodes-langchain/nodes/agents/Agent/agents/ToolsAgent/execute.ts
  packages/@n8n/nodes-langchain/nodes/agents/OpenAiAssistant/OpenAiAssistant.node.ts
  packages/@n8n/nodes-langchain/nodes/tools/ToolHttpRequest/ToolHttpRequest.node.ts
  packages/@n8n/nodes-langchain/nodes/tools/ToolHttpRequest/utils.ts
  packages/@n8n/nodes-langchain/nodes/tools/ToolWorkflow/ToolWorkflow.node.ts
  packages/@n8n/nodes-langchain/nodes/vendors/OpenAi/actions/assistant/message.operation.ts
  packages/@n8n/nodes-langchain/nodes/vendors/OpenAi/actions/text/message.operation.ts
  packages/@n8n/nodes-langchain/utils/N8nTool.test.ts
  packages/@n8n/nodes-langchain/utils/N8nTool.ts
  packages/@n8n/nodes-langchain/utils/helpers.ts
Labels: n8n team

#10196 fix(Invoice Ninja Node): Fix payment types
  packages/nodes-base/nodes/InvoiceNinja/ExpenseDescription.ts
  packages/nodes-base/nodes/InvoiceNinja/PaymentDescription.ts
Labels: node/improvement, community, in linear

#9956 feat(Stripe Trigger Node): Add Stripe webhook descriptions based on the workflow ID and name
  packages/nodes-base/nodes/Stripe/StripeTrigger.node.ts
Labels: node/improvement, community, in linear

#9940 feat(Elasticsearch Node): Add bulk operations for Elasticsearch
  packages/nodes-base/nodes/Elastic/Elasticsearch/Elasticsearch.node.ts
  packages/nodes-base/nodes/Elastic/Elasticsearch/GenericFunctions.ts
  packages/nodes-base/nodes/Elastic/Elasticsearch/descriptions/DocumentDescription.ts
Labels: node/improvement, community, in linear

#10313 feat(MySQL Node): Return decimal types as numbers
  packages/nodes-base/nodes/MySql/v2/actions/common.descriptions.ts
  packages/nodes-base/nodes/MySql/v2/transport/index.ts
Labels: node/improvement, n8n team

#9835 refactor(core): Centralize scaling mode (no-changelog)
  packages/cli/src/Interfaces.ts
  packages/cli/src/Queue.ts
  packages/cli/src/Server.ts
  packages/cli/src/WorkflowRunner.ts
  packages/cli/src/commands/webhook.ts
  packages/cli/src/commands/worker.ts
  packages/cli/src/errors/max-stalled-count.error.ts
  packages/cli/src/executions/__tests__/execution.service.test.ts
  packages/cli/src/executions/execution-recovery.service.ts
  packages/cli/src/executions/execution.service.ts
  packages/cli/src/scaling/constants.ts
  packages/cli/src/scaling/job-processor.ts
  packages/cli/src/scaling/scaling.service.ts
  packages/cli/src/scaling/types.ts
  packages/cli/src/services/orchestration/worker/types.ts
  packages/cli/src/webhooks/WebhookHelpers.ts
  packages/cli/test/integration/commands/worker.cmd.test.ts
Labels: core, n8n team

#10319 refactor(core): Remove skipped telemetry tests (no-changelog)
  packages/@n8n_io/eslint-config/local-rules.js
  packages/cli/src/telemetry/__tests__/telemetry.test.ts
  packages/cli/test/shared/flushPromises.ts
Labels: core, n8n team

#10305 refactor(core): Decouple lifecycle events from internal hooks (no-changelog)
  packages/cli/src/InternalHooks.ts
  packages/cli/src/commands/start.ts
  packages/cli/src/controllers/__tests__/owner.controller.test.ts
  packages/cli/src/controllers/owner.controller.ts
  packages/cli/src/events/relay-event-map.ts
  packages/cli/src/events/telemetry-event-relay.ts
  packages/cli/src/services/__tests__/workflow-statistics.service.test.ts
  packages/cli/src/services/frontend.service.ts
  packages/cli/src/services/workflow-statistics.service.ts
  packages/cli/src/telemetry/__tests__/telemetry.test.ts
  packages/cli/src/telemetry/index.ts
Labels: core, n8n team

#10322 test(core): Expand log streaming event relay tests (no-changelog)
  packages/cli/src/events/__tests__/log-streaming-event-relay.test.ts
Labels: core, n8n team

#10320 test(core): Add tests for scaling service (no-changelog)
  packages/cli/src/scaling/__tests__/scaling.service.test.ts
  packages/cli/src/scaling/job-processor.ts
  packages/cli/src/scaling/scaling.service.ts
Labels: core, n8n team

#10324 refactor(core): Stop reporting disk I/O error to Sentry (no-changelog)
  packages/cli/src/ErrorReporting.ts
Labels: core, n8n team

#10326 refactor(core): Decouple emailing and workflow sharing from internal hooks (no-changelog)
  packages/cli/src/InternalHooks.ts
  packages/cli/src/UserManagement/email/UserManagementMailer.ts
  packages/cli/src/controllers/passwordReset.controller.ts
  packages/cli/src/events/__tests__/log-streaming-event-relay.test.ts
  packages/cli/src/events/relay-event-map.ts
  packages/cli/src/events/telemetry-event-relay.ts
  packages/cli/src/services/user.service.ts
  packages/cli/src/workflows/workflows.controller.ts
Labels: core, n8n team

#10330 fix(core): Rate limit MFA activation and verification endpoints
  packages/cli/src/controllers/mfa.controller.ts
Labels: core, n8n team

#10329 fix(editor): Fixing XSS vulnerability in toast messages
  packages/editor-ui/src/components/NpsSurvey.vue
  packages/editor-ui/src/composables/useExecutionDebugging.ts
  packages/editor-ui/src/composables/usePushConnection.ts
  packages/editor-ui/src/composables/useToast.ts
  packages/editor-ui/src/utils/htmlUtils.ts
Labels: ui, n8n team

#10327 docs: Update wording in X credentials
  packages/nodes-base/credentials/TwitterOAuth1Api.credentials.ts
  packages/nodes-base/credentials/TwitterOAuth2Api.credentials.ts
Labels: node/improvement, n8n team

#10334 docs: Change display name for WhatsApp Trigger API Credential
  packages/nodes-base/credentials/WhatsAppApi.credentials.ts
  packages/nodes-base/credentials/WhatsAppTriggerApi.credentials.ts
Labels: node/improvement, n8n team

#10337 refactor(editor): Convert ChangePasswordModal to composition api (no-changelog)
  packages/editor-ui/src/components/ChangePasswordModal.vue
Labels: ui, n8n team

#10144 feat: Allow sharing to and from team projects (no-changelog)
  packages/cli/src/credentials/credentials.controller.ts
  packages/cli/src/credentials/credentials.service.ee.ts
  packages/cli/src/credentials/credentials.service.ts
  packages/cli/src/databases/repositories/sharedCredentials.repository.ts
  packages/cli/src/permissions/project-roles.ts
  packages/cli/test/integration/credentials/credentials.api.ee.test.ts
  packages/cli/test/integration/credentials/credentials.api.test.ts
Labels: core, n8n team

#10301 refactor(core): Extract webhook request handler to own file
  packages/cli/src/AbstractServer.ts
  packages/cli/src/webhooks/WebhookHelpers.ts
  packages/cli/src/webhooks/WebhookRequestHandler.ts
  packages/cli/src/webhooks/__tests__/WebhookHelpers.test.ts
  packages/cli/src/webhooks/__tests__/WebhookRequestHandler.test.ts
  packages/cli/src/webhooks/webhook.types.ts
Labels: core, n8n team

#10233 fix(editor): Enable credential sharing between all types of projects
  cypress/composables/projects.ts
  cypress/e2e/17-sharing.cy.ts
  cypress/e2e/39-projects.cy.ts
  packages/editor-ui/src/components/CredentialEdit/CredentialEdit.vue
  packages/editor-ui/src/components/CredentialEdit/CredentialSharing.ee.vue
  packages/editor-ui/src/components/DeleteUserModal.vue
  packages/editor-ui/src/components/Projects/ProjectCardBadge.vue
  packages/editor-ui/src/components/Projects/ProjectSharing.vue
  packages/editor-ui/src/plugins/i18n/locales/en.json
  packages/editor-ui/src/stores/credentials.store.ts
  packages/editor-ui/src/views/ProjectSettings.test.ts
  packages/editor-ui/src/views/ProjectSettings.vue
  packages/editor-ui/src/views/SettingsUsersView.test.ts
Labels: ui, n8n team

#10339 fix(core): Prevent XSS via static cache dir
  packages/cli/BREAKING-CHANGES.md
  packages/cli/src/config/schema.ts
  packages/core/src/NodeExecuteFunctions.ts
  packages/core/test/NodeExecuteFunctions.test.ts
Labels: core, n8n team

#10340 refactor(core): Tear down internal hooks (no-changelog)
  packages/cli/src/ExternalSecrets/__tests__/ExternalSecretsManager.ee.test.ts
  packages/cli/src/InternalHooks.ts
  packages/cli/src/UserManagement/email/UserManagementMailer.ts
  packages/cli/src/commands/BaseCommand.ts
  packages/cli/src/controllers/__tests__/me.controller.test.ts
  packages/cli/src/controllers/auth.controller.ts
  packages/cli/src/controllers/passwordReset.controller.ts
  packages/cli/src/events/relay-event-map.ts
  packages/cli/src/events/telemetry-event-relay.ts
  packages/cli/src/executions/__tests__/execution-recovery.service.test.ts
  packages/cli/src/services/user.service.ts
  packages/cli/test/integration/commands/credentials.cmd.test.ts
  packages/cli/test/integration/commands/import.cmd.test.ts
  packages/cli/test/integration/commands/ldap/reset.test.ts
  packages/cli/test/integration/commands/license.cmd.test.ts
  packages/cli/test/integration/commands/reset.cmd.test.ts
  packages/cli/test/integration/commands/update/workflow.test.ts
  packages/cli/test/integration/commands/worker.cmd.test.ts
  packages/cli/test/integration/controllers/invitation/invitation.controller.integration.test.ts
  packages/cli/test/integration/shared/utils/testCommand.ts
  packages/cli/test/integration/shared/utils/testServer.ts
  packages/cli/test/integration/webhooks.api.test.ts
  packages/cli/test/integration/webhooks.test.ts
Labels: core, n8n team

#10321 refactor(core): Port scaling mode config (no-changelog)
  packages/@n8n/config/src/configs/scaling-mode.config.ts
  packages/@n8n/config/src/index.ts
  packages/@n8n/config/test/config.test.ts
  packages/cli/src/WorkflowRunner.ts
  packages/cli/src/commands/worker.ts
  packages/cli/src/config/schema.ts
  packages/cli/src/scaling/scaling.service.ts
  packages/cli/src/services/redis/redis-client.service.ts
Labels: core, n8n team

#10343 fix(core): Account for cancelling an execution with no workers available
  packages/cli/src/scaling/__tests__/scaling.service.test.ts
  packages/cli/src/scaling/scaling.service.ts
Labels: core, n8n team

#10346 fix(core): Enforce shutdown timer and sequence on `SIGINT` for main
  packages/cli/src/commands/BaseCommand.ts
  packages/cli/src/commands/start.ts
Labels: core, n8n team

#10351 ci: Fix scaling mode tests (no-changelog)
  packages/cli/src/scaling/__tests__/scaling.service.test.ts
Labels: core, n8n team

#10356 feat(editor): Enable NodeView version switcher by default on internal (no-changelog)
  packages/editor-ui/src/components/MainHeader/WorkflowDetails.vue
Labels: ui, n8n team

#10341 fix: Require mfa code for password change if its enabled
  packages/cli/src/Mfa/mfa.service.ts
  packages/cli/src/controllers/__tests__/me.controller.test.ts
  packages/cli/src/controllers/me.controller.ts
  packages/cli/src/requests.ts
  packages/editor-ui/src/api/users.ts
  packages/editor-ui/src/components/ChangePasswordModal.vue
  packages/editor-ui/src/components/__tests__/ChangePasswordModal.test.ts
  packages/editor-ui/src/components/__tests__/__snapshots__/ChangePasswordModal.test.ts.snap
  packages/editor-ui/src/plugins/i18n/locales/en.json
  packages/editor-ui/src/stores/users.store.ts
Labels: core, ui, n8n team

#9976 feat(editor): Add schema view to expression modal
  cypress/e2e/14-mapping.cy.ts
  cypress/pages/ndv.ts
  cypress/support/commands.ts
  cypress/support/index.ts
  packages/design-system/src/css/_tokens.dark.scss
  packages/design-system/src/css/_tokens.scss
  packages/editor-ui/src/Interface.ts
  packages/editor-ui/src/components/DraggableTarget.vue
  packages/editor-ui/src/components/ExpressionEdit.vue
  packages/editor-ui/src/components/ExpressionEditModal.vue
  packages/editor-ui/src/components/ExpressionEditorModal/ExpressionEditorModalInput.vue
  packages/editor-ui/src/components/ExpressionEditorModal/theme.ts
  packages/editor-ui/src/components/ExpressionParameterInput.vue
  packages/editor-ui/src/components/InlineExpressionEditor/InlineExpressionEditorInput.vue
  packages/editor-ui/src/components/InlineExpressionEditor/InlineExpressionEditorOutput.vue
  packages/editor-ui/src/components/InlineExpressionEditor/OutputItemSelect.vue
  packages/editor-ui/src/components/InlineExpressionEditor/theme.ts
  packages/editor-ui/src/components/ParameterInput.vue
  packages/editor-ui/src/components/ParameterInputFull.vue
  packages/editor-ui/src/components/RunData.vue
  packages/editor-ui/src/components/RunDataSchema.vue
  packages/editor-ui/src/components/VariableSelector.vue
  packages/editor-ui/src/components/VariableSelectorItem.vue
  packages/editor-ui/src/plugins/codemirror/__tests__/dragAndDrop.test.ts
  packages/editor-ui/src/plugins/codemirror/dragAndDrop.ts
  packages/editor-ui/src/plugins/i18n/locales/en.json
  packages/editor-ui/src/types/externalHooks.ts
  packages/editor-ui/src/utils/__tests__/expressions.test.ts
  packages/editor-ui/src/utils/expressions.ts
Labels: ui, n8n team

#10278 feat(Okta Node): Add Okta Node
  packages/core/bin/generate-ui-types
  packages/editor-ui/src/stores/credentials.store.ts
  packages/nodes-base/credentials/OktaApi.credentials.ts
  packages/nodes-base/nodes/Okta/Okta.dark.svg
  packages/nodes-base/nodes/Okta/Okta.node.ts
  packages/nodes-base/nodes/Okta/Okta.svg
  packages/nodes-base/nodes/Okta/UserDescription.ts
  packages/nodes-base/nodes/Okta/UserFunctions.ts
  packages/nodes-base/nodes/Okta/test/UserFunctions.test.ts
  packages/nodes-base/package.json
  packages/workflow/src/Interfaces.ts
Labels: node/new, n8n team

#10363 ci: Upgrade @apidevtools/json-schema-ref-parser to address AIKIDO-2024-10043 (no-changelog)
  packages/cli/package.json
  pnpm-lock.yaml
Labels: security

#10360 fix(editor): Fix bug causing connections to not get created on new canvas (no-changelog)
  packages/editor-ui/src/views/NodeView.v2.vue
Labels: ui, n8n team

#10361 ci: Upgrade mappersmith in the dependency tree (no-changelog)
  pnpm-lock.yaml
Labels: security

#10362 ci: Upgrade picocolors to address AIKIDO-2024-10093 (no-changelog)
  .github/scripts/package.json
  packages/cli/package.json
  pnpm-lock.yaml
Labels: core, n8n team, security

#10365 ci: Upgrade axios to address CVE-2024-39338 (no-changelog)
  package.json
  packages/cli/package.json
  pnpm-lock.yaml
  pnpm-workspace.yaml
Labels: core, n8n team, security

#10358 feat(editor): Upgrade markdown-it to address AIKIDO-2024-10034 (no-changelog)
  packages/@n8n/chat/package.json
  packages/design-system/package.json
  packages/editor-ui/package.json
  pnpm-lock.yaml
  pnpm-workspace.yaml
Labels: ui, n8n team

#10364 fix(n8n Form Trigger Node): Fix issue preventing v1 node from working
  packages/nodes-base/nodes/Form/utils.ts
Labels: node/improvement, n8n team, release/backport

#10355 refactor(core): Rename ActiveWebhooks to LiveWebhooks (no-changelog)
  packages/cli/src/AbstractServer.ts
  packages/cli/src/webhooks/LiveWebhooks.ts
  packages/cli/test/integration/webhooks.test.ts
Labels: core, n8n team

#10353 fix(core): Fix worker shutdown errors when active executions
  packages/cli/src/commands/BaseCommand.ts
  packages/cli/src/commands/worker.ts
  packages/cli/src/scaling/__tests__/scaling.service.test.ts
  packages/cli/src/scaling/scaling.service.ts
Labels: core, n8n team

#10372 fix(Okta Node): Add missing codex file (no-changelog)
  packages/nodes-base/nodes/Okta/Okta.node.json
Labels: node/new, n8n team

#10350 fix(editor): Revert change that hid swagger docs in the ui
  packages/editor-ui/src/views/SettingsApiView.vue
Labels: ui, n8n team

#10369 refactor(core): Remove unused constants in Redis channels (no-changelog)
  packages/cli/src/services/redis/RedisConstants.ts
Labels: core, n8n team

#10367 refactor(editor): Add typed event bus (no-changelog)
  packages/design-system/src/components/N8nFormBox/FormBox.vue
  packages/design-system/src/components/N8nFormInputs/FormInputs.vue
  packages/design-system/src/utils/__tests__/event-bus.spec.ts
  packages/design-system/src/utils/event-bus.ts
  packages/design-system/src/utils/form-event-bus.ts
  packages/design-system/src/utils/index.ts
Labels: ui, n8n team

#10380 ci: Disable turbo cache when running tests for coverage collection (no-changelog)
  .github/workflows/units-tests-reusable.yml
  turbo.json
Labels: n8n team

#10345 fix: Require mfa code to disable mfa
  packages/cli/src/Mfa/mfa.service.ts
  packages/cli/src/controllers/__tests__/me.controller.test.ts
  packages/cli/src/controllers/me.controller.ts
  packages/cli/src/controllers/mfa.controller.ts
  packages/cli/src/errors/response-errors/invalid-mfa-code.error.ts
  packages/cli/src/requests.ts
  packages/cli/test/integration/mfa/mfa.api.test.ts
  packages/editor-ui/src/api/mfa.ts
  packages/editor-ui/src/components/Modal.vue
  packages/editor-ui/src/components/Modals.vue
  packages/editor-ui/src/components/PromptMfaCodeModal/PromptMfaCodeModal.vue
  packages/editor-ui/src/constants.ts
  packages/editor-ui/src/event-bus/mfa.ts
  packages/editor-ui/src/plugins/i18n/locales/en.json
  packages/editor-ui/src/stores/ui.store.ts
  packages/editor-ui/src/stores/users.store.ts
  packages/editor-ui/src/views/SettingsPersonalView.vue
Labels: core, ui, n8n team

#9913 fix(editor): Connect up new project viewer role to the FE
  cypress/composables/projects.ts
  cypress/e2e/12-canvas-actions.cy.ts
  cypress/e2e/17-sharing.cy.ts
  cypress/e2e/39-projects.cy.ts
  packages/@n8n/permissions/src/constants.ts
  packages/@n8n/permissions/src/index.ts
  packages/@n8n/permissions/src/types.ts
  packages/design-system/src/components/N8nActionBox/ActionBox.vue
  packages/design-system/src/components/N8nActionBox/__tests__/__snapshots__/ActionBox.spec.ts.snap
  packages/design-system/src/components/N8nActionDropdown/ActionDropdown.vue
  packages/design-system/src/css/dropdown.scss
  packages/editor-ui/src/components/CredentialCard.vue
  packages/editor-ui/src/components/CredentialEdit/CredentialConfig.vue
  packages/editor-ui/src/components/CredentialEdit/CredentialEdit.vue
  packages/editor-ui/src/components/CredentialEdit/CredentialSharing.ee.vue
  packages/editor-ui/src/components/MainHeader/WorkflowDetails.vue
  packages/editor-ui/src/components/MainSidebar.vue
  packages/editor-ui/src/components/Projects/ProjectTabs.vue
  packages/editor-ui/src/components/VariablesRow.vue
  packages/editor-ui/src/components/WorkflowActivator.vue
  packages/editor-ui/src/components/WorkflowCard.vue
  packages/editor-ui/src/components/WorkflowSettings.spec.ts
  packages/editor-ui/src/components/WorkflowSettings.vue
  packages/editor-ui/src/components/WorkflowShareModal.ee.vue
  packages/editor-ui/src/components/executions/global/GlobalExecutionsList.test.ts
  packages/editor-ui/src/components/executions/global/GlobalExecutionsList.vue
  packages/editor-ui/src/components/executions/global/GlobalExecutionsListItem.test.ts
  packages/editor-ui/src/components/executions/global/GlobalExecutionsListItem.vue
  packages/editor-ui/src/components/executions/workflow/WorkflowExecutionsCard.test.ts
  packages/editor-ui/src/components/executions/workflow/WorkflowExecutionsCard.vue
  packages/editor-ui/src/components/executions/workflow/WorkflowExecutionsInfoAccordion.vue
  packages/editor-ui/src/components/executions/workflow/WorkflowExecutionsLandingPage.vue
  packages/editor-ui/src/components/executions/workflow/WorkflowExecutionsList.vue
  packages/editor-ui/src/components/executions/workflow/WorkflowExecutionsPreview.test.ts
  packages/editor-ui/src/components/executions/workflow/WorkflowExecutionsPreview.vue
  packages/editor-ui/src/components/executions/workflow/WorkflowExecutionsSidebar.vue
  packages/editor-ui/src/components/layouts/ResourcesListLayout.vue
  packages/editor-ui/src/composables/__tests__/useContextMenu.test.ts
  packages/editor-ui/src/composables/useContextMenu.ts
  packages/editor-ui/src/permissions.spec.ts
  packages/editor-ui/src/permissions.ts
  packages/editor-ui/src/plugins/i18n/locales/en.json
  packages/editor-ui/src/stores/canvas.store.ts
  packages/editor-ui/src/stores/roles.store.test.ts
  packages/editor-ui/src/stores/roles.store.ts
  packages/editor-ui/src/utils/typeGuards.ts
  packages/editor-ui/src/views/CredentialsView.vue
  packages/editor-ui/src/views/NodeView.vue
  packages/editor-ui/src/views/ProjectSettings.vue
  packages/editor-ui/src/views/VariablesView.vue
  packages/editor-ui/src/views/WorkflowExecutionsView.vue
  packages/editor-ui/src/views/WorkflowHistory.vue
  packages/editor-ui/src/views/WorkflowsView.vue
  packages/workflow/package.json
  packages/workflow/src/Interfaces.ts
  pnpm-lock.yaml
Labels: ui, n8n team

#10382 fix(core): Filter out prototype and constructor lookups in expressions
  packages/workflow/package.json
  packages/workflow/src/Expression.ts
  packages/workflow/src/ExpressionEvaluatorProxy.ts
  packages/workflow/src/ExpressionSandboxing.ts
  packages/workflow/test/Expression.test.ts
  packages/workflow/test/ExpressionSandboxing.test.ts
  pnpm-lock.yaml
Labels: core, n8n team

#10371 fix: Fix issue with some errors not being handled correctly (no-changelog)
  packages/workflow/src/errors/abstract/node.error.ts
  packages/workflow/test/NodeErrors.test.ts
Labels: core, n8n team

#10384 fix(editor): Fix bug causing workflow debugging to not work in new canvas (no-changelog)
  packages/editor-ui/src/views/NodeView.v2.vue
Labels: ui, n8n team

#10370 feat(core): Upgrade DB drivers (no-changelog)
  packages/@n8n/nodes-langchain/package.json
  packages/cli/package.json
  packages/nodes-base/package.json
  pnpm-lock.yaml
Labels: core, n8n team

#10325 feat(core): Allow overriding npm registry for community packages
  packages/@n8n/config/src/configs/nodes.ts
  packages/@n8n/config/test/config.test.ts
  packages/cli/src/License.ts
  packages/cli/src/constants.ts
  packages/cli/src/controllers/e2e.controller.ts
  packages/cli/src/services/__tests__/communityPackages.service.test.ts
  packages/cli/src/services/communityPackages.service.ts
Labels: core, n8n team

#10392 fix(core): Fix duplicate Redis publisher
  packages/cli/src/services/redis/RedisServiceBaseClasses.ts
Labels: core, n8n team

#10391 test(core): Cover telemetry event relay in tests (no-changelog)
  packages/cli/src/events/__tests__/telemetry-event-relay.test.ts
Labels: core, n8n team

#10393 refactor(core): Make new configs consistent (no-changelog)
  packages/@n8n/config/src/configs/cache.config.ts
  packages/@n8n/config/src/configs/credentials.config.ts
  packages/@n8n/config/src/configs/database.config.ts
  packages/@n8n/config/src/configs/endpoints.config.ts
  packages/@n8n/config/src/configs/event-bus.config.ts
  packages/@n8n/config/src/configs/external-secrets.config.ts
  packages/@n8n/config/src/configs/external-storage.config.ts
  packages/@n8n/config/src/configs/nodes.config.ts
  packages/@n8n/config/src/configs/public-api.config.ts
  packages/@n8n/config/src/configs/templates.config.ts
  packages/@n8n/config/src/configs/user-management.config.ts
  packages/@n8n/config/src/configs/version-notifications.config.ts
  packages/@n8n/config/src/configs/workflows.config.ts
  packages/@n8n/config/src/index.ts
Labels: n8n team

#10399 fix(editor): Remove `@n8n/permissions` from `n8n-workflow` (no-changelog)
  packages/editor-ui/src/Interface.ts
  packages/editor-ui/src/components/executions/global/GlobalExecutionsList.vue
  packages/editor-ui/src/components/executions/workflow/WorkflowExecutionsPreview.test.ts
  packages/editor-ui/src/stores/executions.store.ts
  packages/workflow/package.json
  packages/workflow/src/Interfaces.ts
  pnpm-lock.yaml
Labels: core, ui, n8n team

#10400 fix: Remove node (no-changelog)
  packages/@n8n/nodes-langchain/nodes/trigger/ManualChatTrigger/ManualChatTrigger.node.ts
  packages/cli/src/controllers/dynamicNodeParameters.controller.ts
  packages/cli/src/requests.ts
  packages/cli/src/services/dynamicNodeParameters.service.ts
  packages/editor-ui/src/Interface.ts
  packages/editor-ui/src/api/nodeTypes.ts
  packages/editor-ui/src/components/ButtonParameter/ButtonParameter.vue
  packages/editor-ui/src/components/ButtonParameter/utils.ts
  packages/editor-ui/src/components/CodeNodeEditor/CodeNodeEditor.vue
  packages/editor-ui/src/components/JsEditor/JsEditor.vue
  packages/editor-ui/src/components/Node/NodeCreator/utils.ts
  packages/editor-ui/src/components/Node/NodeCreator/viewsData.ts
  packages/editor-ui/src/components/ParameterInput.vue
  packages/editor-ui/src/components/ParameterInputList.vue
  packages/editor-ui/src/components/__tests__/ButtonParameter.test.ts
  packages/editor-ui/src/constants.ts
  packages/editor-ui/src/stores/nodeTypes.store.ts
  packages/editor-ui/src/stores/posthog.store.ts
  packages/nodes-base/nodes/AiTransform/AiTransform.node.json
  packages/nodes-base/nodes/AiTransform/AiTransform.node.ts
  packages/nodes-base/nodes/AiTransform/aitransform.svg
  packages/nodes-base/package.json
  packages/workflow/src/Interfaces.ts
Labels: core, ui, n8n team

#10405 feat(AI Transform Node): New node
  packages/@n8n/nodes-langchain/nodes/trigger/ManualChatTrigger/ManualChatTrigger.node.ts
  packages/cli/src/controllers/dynamicNodeParameters.controller.ts
  packages/cli/src/requests.ts
  packages/cli/src/services/dynamicNodeParameters.service.ts
  packages/editor-ui/src/Interface.ts
  packages/editor-ui/src/api/nodeTypes.ts
  packages/editor-ui/src/components/ButtonParameter/ButtonParameter.vue
  packages/editor-ui/src/components/ButtonParameter/utils.ts
  packages/editor-ui/src/components/CodeNodeEditor/CodeNodeEditor.vue
  packages/editor-ui/src/components/JsEditor/JsEditor.vue
  packages/editor-ui/src/components/Node/NodeCreator/utils.ts
  packages/editor-ui/src/components/Node/NodeCreator/viewsData.ts
  packages/editor-ui/src/components/ParameterInput.vue
  packages/editor-ui/src/components/ParameterInputList.vue
  packages/editor-ui/src/components/__tests__/ButtonParameter.test.ts
  packages/editor-ui/src/constants.ts
  packages/editor-ui/src/stores/nodeTypes.store.ts
  packages/editor-ui/src/stores/posthog.store.ts
  packages/nodes-base/nodes/AiTransform/AiTransform.node.json
  packages/nodes-base/nodes/AiTransform/AiTransform.node.ts
  packages/nodes-base/nodes/AiTransform/aitransform.svg
  packages/nodes-base/package.json
  packages/workflow/src/Constants.ts
  packages/workflow/src/Interfaces.ts
Labels: node/new, core, ui, n8n team

#10406 fix(AI Agent Node): Fix issues with some tools not populating
  packages/@n8n/nodes-langchain/utils/helpers.ts
Labels: n8n team, release/backport

#10409 ci: Trigger Docker releases on tag creation instead of release publishing (no-changelog)
  .github/workflows/docker-images.yml
Labels: n8n team

#10408 fix: Add better error handling for chat errors
  packages/editor-ui/src/utils/apiUtils.ts
Labels: ui, n8n team

#10402 refactor(editor): Remove deleted event name from UI
  packages/cli/src/eventbus/EventMessageClasses/index.ts
  packages/cli/src/eventbus/MessageEventBusWriter/MessageEventBusLogWriter.ts
Labels: core, n8n team

#10354 fix: Require mfa code to change email
  packages/cli/src/controllers/__tests__/me.controller.test.ts
  packages/cli/src/controllers/me.controller.ts
  packages/cli/src/requests.ts
  packages/editor-ui/src/api/users.ts
  packages/editor-ui/src/event-bus/mfa.ts
  packages/editor-ui/src/stores/users.store.ts
  packages/editor-ui/src/views/SettingsPersonalView.vue
  packages/editor-ui/src/views/__tests__/SettingsPersonalView.test.ts
Labels: core, ui, n8n team

#10413 fix(core): Fix payload property in `workflow-post-execute` event
  packages/cli/src/events/__tests__/log-streaming-event-relay.test.ts
  packages/cli/src/events/log-streaming-event-relay.ts
Labels: core, n8n team, release/backport

#10417 fix: Project Viewer always seeing a connection error when testing credentials
  packages/cli/src/credentials/credentials.controller.ts
  packages/cli/src/credentials/credentials.service.ts
  packages/cli/test/integration/credentials/credentials.service.test.ts
Labels: core, n8n team

#10397 refactor(core): Simplify Redis client types (no-changelog)
  packages/cli/src/services/cache/cache.service.ts
  packages/cli/src/services/redis/RedisServiceBaseClasses.ts
  packages/cli/src/services/redis/RedisServicePubSubPublisher.ts
  packages/cli/src/services/redis/RedisServicePubSubSubscriber.ts
  packages/cli/src/services/redis/redis-client.service.ts
  packages/cli/src/services/redis/redis.types.ts
Labels: core, n8n team

#10422 refactor: Update to license SDK v2.13.1 to address dependency updates
  packages/cli/package.json
  pnpm-lock.yaml
Labels: core, n8n team

#10396 refactor(editor): Type node view event bus (no-changelog)
  packages/editor-ui/src/event-bus/node-view.ts
Labels: ui, n8n team

#10429 feat: Improve minimap design and position in new canvas (no-changelog)
  packages/editor-ui/src/components/canvas/Canvas.vue
  packages/editor-ui/src/styles/plugins/_vueflow.scss
Labels: ui, n8n team

#10430 feat(editor): Improve node selection outline in new canvas (no-changelog)
  packages/design-system/src/css/_tokens.dark.scss
  packages/design-system/src/css/_tokens.scss
  packages/editor-ui/src/components/canvas/elements/nodes/render-types/CanvasNodeDefault.vue
Labels: ui, n8n team

#10431 fix(editor): Remove item count from pinned data status icon in new canvas (no-changelog)
  packages/editor-ui/src/components/canvas/elements/nodes/render-types/parts/CanvasNodeStatusIcons.spec.ts
  packages/editor-ui/src/components/canvas/elements/nodes/render-types/parts/CanvasNodeStatusIcons.vue
Labels: ui, n8n team

#10433 fix(core): Use explicit types in configs to ensure valid decorator metadata
  packages/@n8n/config/src/configs/cache.config.ts
  packages/@n8n/config/src/configs/credentials.config.ts
  packages/@n8n/config/src/configs/database.config.ts
  packages/@n8n/config/src/configs/endpoints.config.ts
  packages/@n8n/config/src/configs/event-bus.config.ts
  packages/@n8n/config/src/configs/external-secrets.config.ts
  packages/@n8n/config/src/configs/external-storage.config.ts
  packages/@n8n/config/src/configs/nodes.config.ts
  packages/@n8n/config/src/configs/public-api.config.ts
  packages/@n8n/config/src/configs/scaling-mode.config.ts
  packages/@n8n/config/src/configs/templates.config.ts
  packages/@n8n/config/src/configs/user-management.config.ts
  packages/@n8n/config/src/configs/version-notifications.config.ts
  packages/@n8n/config/src/configs/workflows.config.ts
  packages/@n8n/config/src/decorators.ts
  packages/@n8n/config/src/index.ts
  packages/@n8n/config/test/config.test.ts
Labels: n8n team, release/backport

#10427 fix(editor): Truncate long data pill labels in schema view
  packages/editor-ui/src/components/RunDataSchema.vue
  packages/editor-ui/src/components/RunDataSchemaItem.vue
Labels: ui, n8n team

#10419 feat(Facebook Graph API Node): Update node to support API v18 - v20
  packages/nodes-base/nodes/Facebook/FacebookGraphApi.node.ts
Labels: node/improvement, n8n team

#10436 ci: Introduce lint rule `no-untyped-config-class-field` (no-changelog)
  packages/@n8n/config/.eslintrc.js
  packages/@n8n_io/eslint-config/local-rules.js
Labels: n8n team

#10426 fix(editor): Show item count in output panel schema view
  packages/editor-ui/src/components/RunData.vue
Labels: ui, n8n team

#10443 fix(Google Sheets Node): Update name and hint for useAppend option
  packages/nodes-base/nodes/Google/Sheet/v2/actions/sheet/append.operation.ts
  packages/nodes-base/nodes/Google/Sheet/v2/actions/sheet/appendOrUpdate.operation.ts
  packages/nodes-base/nodes/Google/Sheet/v2/actions/sheet/commonDescription.ts
  packages/nodes-base/nodes/Google/Sheet/v2/actions/versionDescription.ts
Labels: node/improvement, n8n team

#10359 feat(editor): Add `registerCustomAction` to new canvas (no-changelog)
  packages/editor-ui/src/App.vue
  packages/editor-ui/src/composables/useGlobalLinkActions.ts
  packages/editor-ui/src/views/NodeView.v2.vue
  packages/editor-ui/src/views/NodeView.vue
Labels: ui, n8n team

#9886 fix(Respond to Webhook Node): Fix issue preventing the chat trigger from working
  packages/nodes-base/nodes/RespondToWebhook/RespondToWebhook.node.ts
Labels: node/improvement, n8n team

#10424 fix(core): Fix XSS validation and separate URL validation
  packages/cli/package.json
  packages/cli/src/GenericHelpers.ts
  packages/cli/src/databases/entities/User.ts
  packages/cli/src/databases/utils/__tests__/customValidators.test.ts
  packages/cli/src/databases/utils/customValidators.ts
  packages/cli/src/requests.ts
  packages/cli/src/validators/__tests__/no-url.validator.test.ts
  packages/cli/src/validators/__tests__/no-xss.validator.test.ts
  packages/cli/src/validators/no-url.validator.ts
  packages/cli/src/validators/no-xss.validator.ts
  pnpm-lock.yaml
Labels: core, n8n team, release/backport

#10449 refactor(editor): Remove `id` param from PATCH /me calls (no-changelog)
  packages/editor-ui/src/api/users.ts
  packages/editor-ui/src/stores/sso.store.ts
  packages/editor-ui/src/views/SettingsPersonalView.vue
Labels: ui, n8n team

#10439 fix(editor): Buffer json chunks in stream response
  packages/editor-ui/src/api/assistant.ts
  packages/editor-ui/src/plugins/i18n/locales/en.json
  packages/editor-ui/src/utils/__tests__/apiUtils.spec.ts
  packages/editor-ui/src/utils/apiUtils.ts
Labels: ui, n8n team, release/backport

#10454 fix(editor): Fix lazy loaded component not using suspense (no-changelog)
  packages/editor-ui/src/components/RunData.vue
Labels: ui, n8n team

#10432 feat(editor): Improve node label readability in new canvas (no-changelog)
  packages/editor-ui/src/components/canvas/elements/nodes/render-types/CanvasNodeDefault.vue
Labels: ui, n8n team

#10455 fix(editor): Add workflow scopes when initializing workflow
  cypress/e2e/1858-PAY-can-use-context-menu.ts
  cypress/e2e/33-settings-personal.cy.ts
  packages/editor-ui/src/__tests__/mocks.ts
  packages/editor-ui/src/composables/__tests__/useWorkflowHelpers.spec.ts
  packages/editor-ui/src/composables/useWorkflowHelpers.ts
  packages/editor-ui/src/stores/workflows.store.ts
Labels: ui, n8n team

#10453 fix(editor): Fix flaky mapping tests
  cypress/e2e/14-mapping.cy.ts
  cypress/e2e/33-settings-personal.cy.ts
  cypress/pages/ndv.ts
  cypress/support/e2e.ts
  packages/cli/src/validators/__tests__/no-url.validator.test.ts
  packages/cli/src/validators/no-url.validator.ts
Labels: n8n team

#10435 feat(editor): Update canvas control buttons design and behaviour in new canvas (no-changelog)
  packages/editor-ui/src/components/canvas/Canvas.spec.ts
  packages/editor-ui/src/components/canvas/Canvas.vue
  packages/editor-ui/src/components/canvas/elements/buttons/CanvasControlButtons.spec.ts
  packages/editor-ui/src/components/canvas/elements/buttons/CanvasControlButtons.vue
  packages/editor-ui/src/components/canvas/elements/buttons/__snapshots__/CanvasControlButtons.spec.ts.snap
  packages/editor-ui/src/styles/plugins/_vueflow.scss
Labels: ui, n8n team

#10448 fix(OpenAI Node): Throw node operations error in case of openAi client error
  packages/@n8n/nodes-langchain/nodes/vendors/OpenAi/actions/assistant/message.operation.ts
Labels: node/improvement, n8n team, node/issue

#10442 fix(Google Sheets Node): Better error when column to match on is empty
  packages/editor-ui/src/components/ResourceMapper/MatchingColumnsSelect.vue
  packages/editor-ui/src/components/__tests__/ResourceMapper.test.ts
  packages/editor-ui/src/plugins/i18n/locales/en.json
  packages/nodes-base/nodes/Google/Sheet/v2/actions/sheet/appendOrUpdate.operation.ts
  packages/nodes-base/nodes/Google/Sheet/v2/actions/sheet/update.operation.ts
  packages/nodes-base/nodes/Postgres/v2/actions/database/update.operation.ts
Labels: node/improvement, n8n team, node/issue

#10440 fix(Google Sheets Node): Update to returnAllMatches option
  packages/nodes-base/nodes/Google/Sheet/GoogleSheets.node.ts
  packages/nodes-base/nodes/Google/Sheet/v2/actions/sheet/read.operation.ts
  packages/nodes-base/nodes/Google/Sheet/v2/actions/versionDescription.ts
Labels: node/improvement, n8n team, node/issue

#10457 fix: Better errors in Switch, If and Filter nodes
  packages/nodes-base/nodes/Filter/V2/FilterV2.node.ts
  packages/nodes-base/nodes/If/V2/IfV2.node.ts
  packages/nodes-base/nodes/Switch/V3/SwitchV3.node.ts
Labels: n8n team, node/issue

#10451 refactor(editor): Add types to ndv event bus (no-changelog)
  packages/editor-ui/src/components/NodeSettings.vue
  packages/editor-ui/src/event-bus/ndv.ts
Labels: ui, n8n team

#10462 fix(Invoice Ninja Node): Fix payment types 2
  packages/nodes-base/nodes/InvoiceNinja/ExpenseDescription.ts
  packages/nodes-base/nodes/InvoiceNinja/PaymentDescription.ts
Labels: node/improvement, community, in linear

#10463 fix(Read/Write Files from Disk Node): Better error handling when file name missing (no-changelog)
  packages/nodes-base/nodes/Files/ReadWriteFile/actions/read.operation.ts
  packages/nodes-base/nodes/Files/ReadWriteFile/actions/write.operation.ts
Labels: node/improvement, n8n team

#10469 fix(editor): Adjust default zoom level in new canvas (no-changelog)
  packages/editor-ui/src/components/canvas/Canvas.vue
Labels: ui, n8n team

#10434 fix: Show input names when node has multiple inputs
  packages/editor-ui/src/components/InputNodeSelect.vue
  packages/editor-ui/src/components/RunDataSchema.vue
  packages/editor-ui/src/stores/ndv.store.ts
Labels: ui, n8n team

#10471 fix(editor): Add missing control button events to new canvas (no-changelog)
  packages/editor-ui/src/components/canvas/Canvas.vue
  packages/editor-ui/src/components/canvas/elements/buttons/CanvasControlButtons.vue
Labels: ui, n8n team

#10472 feat(editor): Update cursor behaviour in new canvas (no-changelog)
  packages/editor-ui/src/styles/plugins/_vueflow.scss
Labels: ui, n8n team

#10473 feat(editor): Add old execution status rendering in new canvas (no-changelog)
  packages/editor-ui/src/components/canvas/elements/nodes/render-types/CanvasNodeDefault.vue
  packages/editor-ui/src/components/canvas/elements/nodes/render-types/parts/CanvasNodeStatusIcons.vue
Labels: ui, n8n team

#10475 fix(editor): Fix edge button background color in dark mode in new canvas (no-changelog)
  packages/editor-ui/src/components/canvas/elements/edges/CanvasEdgeToolbar.vue
Labels: ui, n8n team

#10395 refactor(editor): Type source control event bus (no-changelog)
  packages/editor-ui/src/event-bus/source-control.ts
Labels: ui, n8n team

#10456 fix: Filter component - improve errors
  packages/editor-ui/src/components/Error/NodeErrorView.vue
  packages/nodes-base/nodes/Filter/Filter.node.ts
  packages/nodes-base/nodes/Filter/V2/FilterV2.node.ts
  packages/nodes-base/nodes/If/If.node.ts
  packages/nodes-base/nodes/If/V2/IfV2.node.ts
  packages/nodes-base/nodes/If/V2/utils.ts
  packages/nodes-base/nodes/Switch/Switch.node.ts
  packages/nodes-base/nodes/Switch/V3/SwitchV3.node.ts
  packages/nodes-base/utils/descriptions.ts
  packages/workflow/src/NodeParameters/FilterParameter.ts
Labels: n8n team, node/issue

#10441 ci: Add workflow to build benchmark cli (no-changelog)
  .github/workflows/docker-images-benchmark.yml
Labels: n8n team

#10452 refactor(editor): Add types to global link actions event bus (no-changelog)
  packages/editor-ui/src/composables/useGlobalLinkActions.ts
  packages/editor-ui/src/event-bus/global-link-actions.ts
  packages/editor-ui/src/event-bus/index.ts
  packages/editor-ui/src/event-bus/link-actions.ts
Labels: ui, n8n team

#10377 feat(core): Support bidirectional communication between specific mains and specific workers
  packages/cli/src/commands/start.ts
  packages/cli/src/services/__tests__/orchestration.service.test.ts
  packages/cli/src/services/orchestration.handler.base.service.ts
  packages/cli/src/services/orchestration/main/handleWorkerResponseMessageMain.ts
  packages/cli/src/services/orchestration/main/orchestration.handler.main.service.ts
  packages/cli/src/services/orchestration/main/types.ts
  packages/cli/src/services/redis/RedisServiceCommands.ts
Labels: core, n8n team

#10476 test(editor): Add AI Assistant e2e tests (no-changelog)
  cypress/e2e/45-ai-assistant.cy.ts
  cypress/fixtures/aiAssistant/apply_code_diff_response.json
  cypress/fixtures/aiAssistant/code_diff_suggestion_response.json
  cypress/fixtures/aiAssistant/end_session_response.json
  cypress/fixtures/aiAssistant/quick_reply_message_response.json
  cypress/fixtures/aiAssistant/simple_message_response.json
  cypress/fixtures/aiAssistant/test_workflow.json
  cypress/pages/features/ai-assistant.ts
  packages/design-system/src/components/AskAssistantChat/AskAssistantChat.vue
  packages/design-system/src/components/CodeDiff/CodeDiff.vue
  packages/editor-ui/src/components/AskAssistant/AskAssistantChat.vue
  packages/editor-ui/src/components/AskAssistant/AskAssistantFloatingButton.vue
  packages/editor-ui/src/components/AskAssistant/NewAssistantSessionModal.vue
  packages/editor-ui/src/components/Error/NodeErrorView.vue
Labels: ui, n8n team

#10481 fix: Rename Assistant back
  packages/design-system/src/locale/lang/en.ts
Labels: ui, n8n team, release/backport

#10483 refactor(core): Track metrics state and categories in telemetry (no-changelog)
  packages/cli/src/events/__tests__/telemetry-event-relay.test.ts
  packages/cli/src/events/telemetry-event-relay.ts
Labels: core, n8n team

#10479 fix(core): Replace `sanitize-html` with `xss` in XSS validator constraint
  packages/cli/package.json
  packages/cli/src/validators/__tests__/no-xss.validator.test.ts
  packages/cli/src/validators/no-xss.validator.ts
  pnpm-lock.yaml
Labels: core, n8n team

#10478 feat(editor): Add more onboarding options experiment (no-changelog)
  packages/editor-ui/src/components/MainSidebar.vue
  packages/editor-ui/src/components/PersonalizationModal.vue
  packages/editor-ui/src/constants.ts
  packages/editor-ui/src/plugins/i18n/locales/en.json
  packages/editor-ui/src/views/SetupView.vue
  packages/editor-ui/src/views/WorkflowsView.vue
Labels: ui, n8n team

#10281 feat(editor): Update `element-plus` to 2.4.3 (no-changelog)
  cypress/e2e/11-inline-expression-editor.cy.ts
  cypress/e2e/17-workflow-tags.cy.ts
  cypress/e2e/2-credentials.cy.ts
  cypress/pages/ndv.ts
  cypress/utils/popper.ts
  packages/design-system/.storybook/preview.js
  packages/design-system/package.json
  packages/design-system/src/components/N8nCheckbox/__tests__/__snapshots__/Checkbox.spec.ts.snap
  packages/design-system/src/components/N8nColorPicker/__tests__/__snapshots__/ColorPicker.spec.ts.snap
  packages/design-system/src/components/N8nDatatable/__tests__/Datatable.spec.ts
  packages/design-system/src/components/N8nDatatable/__tests__/__snapshots__/Datatable.spec.ts.snap
  packages/design-system/src/components/N8nSelect/__tests__/Select.spec.ts
  packages/design-system/src/components/N8nSelect/__tests__/__snapshots__/Select.spec.ts.snap
  packages/design-system/src/utils/index.ts
  packages/design-system/src/utils/testUtils.ts
  packages/editor-ui/src/__tests__/utils.ts
  packages/editor-ui/src/components/ContextMenu/ContextMenu.vue
  packages/editor-ui/src/components/ExpandableInput/ExpandableInputEdit.vue
  packages/editor-ui/src/components/ExpressionParameterInput.vue
  packages/editor-ui/src/components/NDVSubConnections.vue
  packages/editor-ui/src/components/Projects/ProjectSharing.test.ts
  packages/editor-ui/src/components/ResourceLocator/ResourceLocator.vue
  packages/editor-ui/src/components/Sticky.vue
  packages/editor-ui/src/components/TagsDropdown.vue
  packages/editor-ui/src/components/__tests__/WorkflowLMChatModal.test.ts
  packages/editor-ui/src/plugins/directives.ts
  packages/editor-ui/src/views/__tests__/SettingsSourceControl.test.ts
  pnpm-lock.yaml
Labels: ui, n8n team

#10491 fix(editor): Fix overflow in AI Assistant chat messages
  packages/design-system/src/components/AskAssistantChat/AskAssistantChat.vue
Labels: ui, n8n team

#10378 fix(Calendly Trigger Node): Fix issue with webhook url matching
  packages/nodes-base/nodes/Calendly/CalendlyTrigger.node.ts
Labels: node/improvement, community, in linear
