Repository n8n-io/n8n, pull requests merged in 2024-09, with the labels that each got.

#10538 refactor(editor): Migrate `MainSidebar.vue` to composition API (no-changelog)
  packages/editor-ui/src/App.vue
  packages/editor-ui/src/components/MainSidebar.vue
Labels: ui, n8n team

#10632 test: Add JS CodeNode benchmark scenario
  packages/@n8n/benchmark/scenarios/jsCodeNodeOnceForEach/jsCodeNodeOnceForEach.json
  packages/@n8n/benchmark/scenarios/jsCodeNodeOnceForEach/jsCodeNodeOnceForEach.manifest.json
  packages/@n8n/benchmark/scenarios/jsCodeNodeOnceForEach/jsCodeNodeOnceForEach.script.js
Labels: n8n team

#10633 fix(core): Flush responses for ai streaming endpoints
  packages/cli/src/controllers/ai-assistant.controller.ts
Labels: core, n8n team

#10639 feat(core): Use ES2021 as the tsconfig target for all backend packages (no-changelog)
  packages/@n8n/nodes-langchain/tsconfig.json
  packages/node-dev/src/tsconfig-build.json
  packages/nodes-base/tsconfig.json
  packages/workflow/tsconfig.json
  tsconfig.json
Labels: node/improvement, core, n8n team

#10635 fix(editor): Allow disabling SSO when config request fails
  packages/editor-ui/src/views/SettingsSso.test.ts
  packages/editor-ui/src/views/SettingsSso.vue
Labels: ui, n8n team

#10568 feat(editor): AI assistant UX improvements (no-changelog)
  cypress/e2e/45-ai-assistant.cy.ts
  cypress/fixtures/aiAssistant/node_execution_error_response.json
  cypress/pages/features/ai-assistant.ts
  packages/design-system/src/components/AskAssistantChat/AskAssistantChat.stories.ts
  packages/design-system/src/components/AskAssistantChat/AskAssistantChat.vue
  packages/design-system/src/components/AskAssistantChat/__tests__/__snapshots__/AskAssistantChat.spec.ts.snap
  packages/design-system/src/components/AskAssistantLoadingMessage/AssistantLoadingMessage.stories.ts
  packages/design-system/src/components/AskAssistantLoadingMessage/AssistantLoadingMessage.vue
  packages/design-system/src/components/AskAssistantLoadingMessage/DemoComponent.stories.ts
  packages/design-system/src/components/AskAssistantLoadingMessage/DemoComponent.vue
  packages/design-system/src/components/AskAssistantLoadingMessage/__tests__/AskAssistantLoadingMessage.spec.ts
  packages/design-system/src/components/AskAssistantLoadingMessage/__tests__/__snapshots__/AskAssistantLoadingMessage.spec.ts.snap
  packages/design-system/src/locale/lang/en.ts
  packages/design-system/src/types/assistant.ts
  packages/editor-ui/src/components/AskAssistant/AskAssistantChat.vue
  packages/editor-ui/src/composables/useToast.ts
  packages/editor-ui/src/plugins/i18n/locales/en.json
  packages/editor-ui/src/stores/__tests__/assistant.store.test.ts
  packages/editor-ui/src/stores/assistant.store.ts
  packages/editor-ui/src/types/assistant.types.ts
Labels: ui, n8n team

#10517 feat(Postgres PGVector Store Node): Add PGVector vector store node
  packages/@n8n/nodes-langchain/nodes/vector_store/VectorStorePGVector/VectorStorePGVector.node.ts
  packages/@n8n/nodes-langchain/nodes/vector_store/VectorStorePGVector/postgres.svg
  packages/@n8n/nodes-langchain/package.json
Labels: n8n team

#10643 refactor(core): Improve license lifecycle logging (no-changelog)
  packages/cli/src/license.ts
  packages/cli/src/services/__tests__/orchestration.service.test.ts
  packages/cli/src/services/orchestration/main/handle-command-message-main.ts
Labels: core, n8n team

#10646 fix(core): Tighten check for company size survey answer
  packages/cli/src/controllers/__tests__/me.controller.test.ts
  packages/cli/src/controllers/survey-answers.dto.ts
  packages/cli/test/integration/me.api.test.ts
Labels: core, n8n team

#10637 feat(editor): Overhaul node insert position computation in new canvas (no-changelog)
  packages/editor-ui/src/Interface.ts
  packages/editor-ui/src/__tests__/mocks.ts
  packages/editor-ui/src/components/Node/NodeCreation.vue
  packages/editor-ui/src/components/Node/NodeCreator/NodeCreator.vue
  packages/editor-ui/src/components/canvas/Canvas.vue
  packages/editor-ui/src/components/canvas/elements/nodes/render-types/CanvasNodeDefault.vue
  packages/editor-ui/src/composables/__tests__/__snapshots__/useCanvasOperations.spec.ts.snap
  packages/editor-ui/src/composables/__tests__/useCanvasOperations.spec.ts
  packages/editor-ui/src/composables/useCanvasOperations.ts
  packages/editor-ui/src/stores/credentials.store.ts
  packages/editor-ui/src/stores/nodeCreator.store.ts
  packages/editor-ui/src/stores/ui.store.ts
  packages/editor-ui/src/utils/canvasUtilsV2.ts
  packages/editor-ui/src/utils/nodeViewUtils.ts
  packages/editor-ui/src/views/NodeView.v2.vue
Labels: ui, n8n team

#10627 build: Add `reset` script
  package.json
  pnpm-lock.yaml
  scripts/ensure-zx.mjs
  scripts/reset.mjs
Labels: core, ui, n8n team

#10648 feat(benchmark): Add benchmark scenario for binary files
  packages/@n8n/benchmark/scenarios/binaryData/binaryData.json
  packages/@n8n/benchmark/scenarios/binaryData/binaryData.manifest.json
  packages/@n8n/benchmark/scenarios/binaryData/binaryData.script.js
  packages/@n8n/benchmark/src/testExecution/k6Executor.ts
Labels: n8n team

#10647 feat(benchmark): Add scenario for expressions with Set node
  packages/@n8n/benchmark/scenarios/setNodeExpressions/setNodeExpressions.json
  packages/@n8n/benchmark/scenarios/setNodeExpressions/setNodeExpressions.manifest.json
  packages/@n8n/benchmark/scenarios/setNodeExpressions/setNodeExpressions.script.js
Labels: n8n team

#10602 feat: Reintroduce collaboration feature
  packages/cli/src/collaboration/__tests__/collaboration.state.test.ts
  packages/cli/src/collaboration/collaboration.message.ts
  packages/cli/src/collaboration/collaboration.service.ts
  packages/cli/src/collaboration/collaboration.state.ts
  packages/cli/src/collaboration/collaboration.types.ts
  packages/cli/src/interfaces.ts
  packages/cli/src/push/__tests__/websocket.push.test.ts
  packages/cli/src/push/abstract.push.ts
  packages/cli/src/push/index.ts
  packages/cli/src/push/sse.push.ts
  packages/cli/src/push/types.ts
  packages/cli/src/push/websocket.push.ts
  packages/cli/src/server.ts
  packages/cli/test/integration/collaboration/collaboration.service.test.ts
  packages/editor-ui/src/Interface.ts
  packages/editor-ui/src/components/MainHeader/CollaborationPane.vue
  packages/editor-ui/src/components/MainHeader/WorkflowDetails.vue
  packages/editor-ui/src/components/__tests__/CollaborationPane.test.ts
  packages/editor-ui/src/composables/useBeforeUnload.ts
  packages/editor-ui/src/constants.ts
  packages/editor-ui/src/stores/collaboration.store.ts
  packages/editor-ui/src/views/NodeView.v2.vue
Labels: core, ui, n8n team

#10650 fix(core): Declutter webhook insertion errors
  packages/cli/src/webhooks/__tests__/webhook.service.test.ts
  packages/cli/src/webhooks/webhook.service.ts
Labels: core, n8n team

#10649 refactor(editor): Remove Trial logic in personalization modal and port to script setup
  packages/editor-ui/src/components/PersonalizationModal.test.ts
  packages/editor-ui/src/components/PersonalizationModal.vue
  packages/editor-ui/src/components/__tests__/PersonalizationModal.spec.ts
Labels: ui, n8n team

#10641 feat(core): Implement wrapping of regular nodes as AI Tools
  packages/@n8n/nodes-langchain/utils/helpers.ts
  packages/cli/src/load-nodes-and-credentials.ts
  packages/cli/src/node-types.ts
  packages/core/package.json
  packages/core/src/CreateNodeAsTool.ts
  packages/core/src/DirectoryLoader.ts
  packages/core/src/NodeExecuteFunctions.ts
  packages/core/test/CreateNodeAsTool.test.ts
  packages/editor-ui/src/components/Node/NodeCreator/composables/useActionsGeneration.ts
  packages/workflow/src/Interfaces.ts
  packages/workflow/src/NodeHelpers.ts
  packages/workflow/test/NodeHelpers.test.ts
  pnpm-lock.yaml
Labels: core, ui, n8n team

#10657 refactor(benchmark): Separate cloud env provisioning from running benchmarks
  .github/workflows/benchmark-nightly.yml
  packages/@n8n/benchmark/package.json
  packages/@n8n/benchmark/scripts/clients/terraformClient.mjs
  packages/@n8n/benchmark/scripts/destroyCloudEnv.mjs
  packages/@n8n/benchmark/scripts/provisionCloudEnv.mjs
  packages/@n8n/benchmark/scripts/run.mjs
  packages/@n8n/benchmark/scripts/runInCloud.mjs
Labels: n8n team

#10655 fix(editor): Fix workflow loading after switching to executions view in new canvas (no-changelog)
  packages/editor-ui/src/router.ts
  packages/editor-ui/src/stores/workflows.store.ts
  packages/editor-ui/src/views/NodeView.v2.vue
  packages/editor-ui/src/views/WorkflowExecutionsView.vue
Labels: ui, n8n team

#10638 feat(editor): Make highlighted data pane floating
  packages/editor-ui/src/components/TagsDropdown.vue
  packages/editor-ui/src/components/executions/workflow/WorkflowExecutionAnnotationPanel.vue
  packages/editor-ui/src/components/executions/workflow/WorkflowExecutionsList.vue
  packages/editor-ui/src/components/executions/workflow/WorkflowExecutionsPreview.vue
Labels: core, n8n team

#10513 fix(AI Agent Node): Fix tools agent when using memory and Anthropic models
  packages/@n8n/nodes-langchain/nodes/agents/Agent/agents/ToolsAgent/execute.ts
Labels: core, n8n team

#10652 fix(editor): Fix opening executions tab from a new, unsaved workflow
  cypress/e2e/20-workflow-executions.cy.ts
  cypress/pages/workflow-executions-tab.ts
  packages/editor-ui/src/components/executions/workflow/WorkflowExecutionsLandingPage.vue
  packages/editor-ui/src/stores/workflows.store.ts
Labels: ui, n8n team

#10565 feat: More hints to nodes
  packages/editor-ui/src/components/RunData.vue
  packages/editor-ui/src/constants.ts
  packages/editor-ui/src/utils/__tests__/nodeViewUtils.spec.ts
  packages/editor-ui/src/utils/nodeViewUtils.ts
  packages/nodes-base/nodes/HttpRequest/V3/HttpRequestV3.node.ts
  packages/nodes-base/nodes/Transform/Aggregate/Aggregate.node.ts
Labels: node/improvement, n8n team, node/issue

#10668 feat(editor): Change selection to be default canvas behaviour (no-changelog)
  packages/editor-ui/src/components/canvas/Canvas.vue
  packages/editor-ui/src/styles/plugins/_vueflow.scss
Labels: ui, n8n team

#10666 fix(editor): Set minimum zoom to 0 to allow fitting very large workflows in new canvas (no-changelog)
  packages/editor-ui/src/components/canvas/Canvas.vue
Labels: ui, n8n team

#10659 feat(editor): Add support for nodes with multiple main inputs in new canvas (no-changelog)
  packages/editor-ui/src/components/canvas/elements/nodes/render-types/CanvasNodeDefault.spec.ts
  packages/editor-ui/src/components/canvas/elements/nodes/render-types/CanvasNodeDefault.vue
  packages/editor-ui/src/components/canvas/elements/nodes/render-types/__snapshots__/CanvasNodeDefault.spec.ts.snap
Labels: ui, n8n team

#10670 feat(core): Make Postgres connection timeout configurable
  packages/@n8n/config/src/configs/database.config.ts
  packages/@n8n/config/test/config.test.ts
  packages/cli/src/databases/config.ts
Labels: core, n8n team

#10667 feat(Text Classifier Node): Add output fixing parser
  packages/@n8n/nodes-langchain/nodes/chains/SentimentAnalysis/SentimentAnalysis.node.ts
  packages/@n8n/nodes-langchain/nodes/chains/TextClassifier/TextClassifier.node.ts
Labels: n8n team

#10600 fix(editor): Fix configurable node width in new canvas (no-changelog)
  packages/editor-ui/src/components/canvas/elements/nodes/render-types/CanvasNodeDefault.vue
  packages/editor-ui/src/components/canvas/elements/nodes/render-types/__snapshots__/CanvasNodeDefault.spec.ts.snap
Labels: ui, n8n team

#10658 feat(editor): Change order of zoom control buttons in new canvas (no-changelog)
  packages/editor-ui/src/components/canvas/elements/buttons/CanvasControlButtons.spec.ts
  packages/editor-ui/src/components/canvas/elements/buttons/CanvasControlButtons.vue
  packages/editor-ui/src/components/canvas/elements/buttons/__snapshots__/CanvasControlButtons.spec.ts.snap
Labels: ui, n8n team

#10664 feat(editor): Add A/B testing feature flag for credential docs modal
  packages/editor-ui/src/components/CredentialEdit/CredentialConfig.vue
  packages/editor-ui/src/constants.ts
Labels: ui, n8n team

#10656 feat(editor): Add AI Assistant support chat
  cypress/e2e/45-ai-assistant.cy.ts
  cypress/fixtures/aiAssistant/end_session_response.json
  cypress/pages/features/ai-assistant.ts
  packages/design-system/src/components/AskAssistantChat/AskAssistantChat.stories.ts
  packages/design-system/src/components/AskAssistantChat/AskAssistantChat.vue
  packages/design-system/src/components/AskAssistantChat/__tests__/__snapshots__/AskAssistantChat.spec.ts.snap
  packages/design-system/src/locale/lang/en.ts
  packages/design-system/src/types/assistant.ts
  packages/editor-ui/src/components/AskAssistant/AskAssistantChat.vue
  packages/editor-ui/src/components/NDVFloatingNodes.vue
  packages/editor-ui/src/stores/assistant.store.ts
  packages/editor-ui/src/types/assistant.types.ts
Labels: ui, n8n team

#10661 feat(core): Introduce DB health check
  packages/cli/src/abstract-server.ts
  packages/cli/src/commands/worker.ts
  packages/cli/test/integration/healthcheck.controller.test.ts
  packages/cli/test/integration/shared/test-db.ts
  packages/cli/test/integration/shared/types.ts
  packages/cli/test/integration/shared/utils/test-server.ts
Labels: core, n8n team

#10679 ci: Remove benchmark VM entra login
  packages/@n8n/benchmark/infra/modules/benchmark-vm/vm.tf
Labels: n8n team

#10678 fix(editor): Add sticky note readonly state in new canvas
  packages/editor-ui/src/__tests__/data/canvas.ts
  packages/editor-ui/src/components/canvas/elements/nodes/CanvasNode.vue
  packages/editor-ui/src/components/canvas/elements/nodes/CanvasNodeToolbar.spec.ts
  packages/editor-ui/src/components/canvas/elements/nodes/CanvasNodeToolbar.vue
  packages/editor-ui/src/components/canvas/elements/nodes/render-types/CanvasNodeStickyNote.spec.ts
  packages/editor-ui/src/components/canvas/elements/nodes/render-types/CanvasNodeStickyNote.vue
  packages/editor-ui/src/components/canvas/elements/nodes/render-types/__snapshots__/CanvasNodeStickyNote.spec.ts.snap
  packages/editor-ui/src/composables/useCanvasNode.ts
  packages/editor-ui/src/types/canvas.ts
Labels: ui, n8n team

#10677 feat(editor): Show minimap only while panning, zooming or while minimap is hovered (no-changelog)
  packages/editor-ui/src/components/canvas/Canvas.spec.ts
  packages/editor-ui/src/components/canvas/Canvas.vue
Labels: ui, n8n team

#10695 fix: Fix the issue in Trigger Nodes where poll time was not loaded
  packages/cli/src/node-types.ts
  packages/workflow/src/NodeHelpers.ts
Labels: release/backport

#10690 fix: More hints to nodes - regression for sub nodes (no-changelog)
  packages/editor-ui/src/components/RunData.vue
Labels: n8n team, node/issue, release/backport

#10687 fix(n8n Form Trigger Node): Do not rerun trigger when it has run data
  packages/editor-ui/src/composables/useRunWorkflow.ts
  packages/editor-ui/src/utils/__tests__/executionUtils.spec.ts
  packages/editor-ui/src/utils/executionUtils.ts
Labels: n8n team, node/issue

#10681 feat(editor): Logs markdown block improvements
  packages/@n8n/chat/package.json
  packages/editor-ui/package.json
  packages/editor-ui/src/components/RunDataAi/AiRunContentBlock.vue
  packages/editor-ui/src/components/RunDataAi/useAiContentParsers.ts
  pnpm-lock.yaml
  pnpm-workspace.yaml
Labels: ui, n8n team

#10697 fix: Tweak the copy for Add more warnings to nodes (no-changelog)
  packages/editor-ui/src/utils/__tests__/nodeViewUtils.spec.ts
  packages/editor-ui/src/utils/nodeViewUtils.ts
  packages/nodes-base/nodes/HttpRequest/V3/HttpRequestV3.node.ts
Labels: release/backport

#10682 fix: Show a more user friendly error message if initial Db connection times out
  packages/cli/src/databases/config.ts
  packages/cli/src/db.ts
  packages/workflow/src/errors/db-connection-timeout-error.ts
  packages/workflow/src/errors/ensure-error.ts
  packages/workflow/src/errors/index.ts
Labels: release/backport

#10707 fix: Prevent AI assistant session reset when workflow is saved
  cypress/e2e/45-ai-assistant.cy.ts
  packages/design-system/src/components/N8nAvatar/Avatar.vue
  packages/editor-ui/src/stores/assistant.store.ts
Labels: release/backport

#10705 refactor(core): Increase Postgres connection timeout to 20 seconds
  packages/@n8n/config/src/configs/database.config.ts
  packages/@n8n/config/test/config.test.ts
Labels: release/backport

#10689 fix(Email Trigger (IMAP) Node): Ensure connection close does not block deactivation
  packages/nodes-base/nodes/EmailReadImap/v2/EmailReadImapV2.node.ts
Labels: release/backport

#10662 fix(OpenAI Chat Model Node): Prevent filtering of fine-tuned models in model selector
  packages/@n8n/nodes-langchain/nodes/llms/LMChatOpenAi/LmChatOpenAi.node.ts
  packages/@n8n/nodes-langchain/nodes/vendors/OpenAi/methods/listSearch.ts
Labels: n8n team

#10554 fix(Webflow Node): Update scopes to include forms
  packages/nodes-base/credentials/WebflowOAuth2Api.credentials.ts
Labels: node/improvement, community, in linear

#10717 fix(Gmail Trigger Node): Change Gmail Trigger dedupe logic
  packages/nodes-base/nodes/Google/Gmail/GmailTrigger.node.ts
Labels: node/improvement, n8n team, tests-needed

#10739 fix(editor): Prevent action's panel flickering while dragging a node
  packages/editor-ui/src/components/Node/NodeCreator/Modes/ActionsMode.vue
  packages/editor-ui/src/components/Node/NodeCreator/Modes/NodesMode.vue
Labels: ui, n8n team

#10684 fix(editor): Follow up fixes and improvements to viewer role
  packages/editor-ui/src/components/CredentialCard.test.ts
  packages/editor-ui/src/components/CredentialCard.vue
  packages/editor-ui/src/components/CredentialEdit/CredentialEdit.vue
  packages/editor-ui/src/components/WorkflowCard.test.ts
  packages/editor-ui/src/components/WorkflowCard.vue
  packages/editor-ui/src/components/executions/workflow/WorkflowExecutionsPreview.test.ts
  packages/editor-ui/src/components/executions/workflow/WorkflowExecutionsPreview.vue
  packages/editor-ui/src/plugins/i18n/locales/en.json
  packages/editor-ui/src/views/CredentialsView.test.ts
  packages/editor-ui/src/views/CredentialsView.vue
Labels: ui, n8n team

#10750 fix(editor): Show docs link in credential modal when docs sidebar is hidden
  packages/editor-ui/src/components/CredentialEdit/CredentialConfig.vue
Labels: ui, n8n team, release/backport

#10718 fix(Telegram Trigger Node): Use timing-safe string comparison (no-changelog)
  packages/nodes-base/nodes/Telegram/TelegramTrigger.node.ts
Labels: node/improvement, n8n team, tests-needed

#10660 docs: Fix broken PostgREST guide link in Supabase node
  packages/nodes-base/nodes/Supabase/GenericFunctions.ts
Labels: node/improvement, community, in linear

#10700 fix: Google Contacts node warm up request, Google Calendar node events>getAll fields option
  packages/nodes-base/nodes/Google/Calendar/EventDescription.ts
  packages/nodes-base/nodes/Google/Calendar/GoogleCalendar.node.ts
  packages/nodes-base/nodes/Google/Contacts/GoogleContacts.node.ts
Labels: node/improvement, n8n team, node/issue, tests-needed

#10723 refactor(editor): Migrate `ActivationModal.vue` to composition API
  packages/editor-ui/src/components/ActivationModal.vue
Labels: ui, n8n team

#10722 refactor(editor): Migrate `AboutModal.vue` to composition API
  packages/editor-ui/src/components/AboutModal.vue
Labels: ui, n8n team

#10724 refactor(editor): Migrate `SettingsCommunityNodesView.vue` to composition API
  packages/editor-ui/src/views/SettingsCommunityNodesView.vue
Labels: ui, n8n team

#10721 refactor(editor): Migrate `RunInfo.vue` to composition API
  packages/editor-ui/src/components/RunInfo.vue
Labels: ui, n8n team

#10757 fix(editor): Increase connector snap radius
  packages/editor-ui/src/components/canvas/Canvas.vue
Labels: ui, n8n team

#10720 refactor(editor): Migrate `SignoutView.vue` to composition API
  packages/editor-ui/src/views/SignoutView.vue
Labels: ui, n8n team

#10753 fix(core): Do not serialize CredentialsEntity.shared anymore (no-changelog)
  packages/cli/src/credentials/credentials.controller.ts
  packages/cli/src/credentials/credentials.service.ts
  packages/cli/src/databases/entities/credentials-entity.ts
  packages/cli/test/integration/credentials/credentials.api.ee.test.ts
Labels: core, n8n team

#10762 fix(editor): Close Push connection in NodeView v2 (no-changelog)
  packages/editor-ui/src/views/NodeView.v2.vue
Labels: ui, n8n team

#10759 refactor: Update Langchain packages (no-changelog)
  packages/@n8n/nodes-langchain/nodes/embeddings/EmbeddingsOllama/EmbeddingsOllama.node.ts
  packages/@n8n/nodes-langchain/nodes/llms/LmChatAwsBedrock/LmChatAwsBedrock.node.ts
  packages/@n8n/nodes-langchain/package.json
  packages/core/package.json
  packages/workflow/package.json
  pnpm-lock.yaml
  pnpm-workspace.yaml
Labels: core, n8n team

#10761 fix(benchmark): Make benchmark checks more robust
  packages/@n8n/benchmark/scenarios/httpNode/httpNode.script.js
  packages/@n8n/benchmark/scenarios/jsCodeNodeOnceForEach/jsCodeNodeOnceForEach.script.js
Labels: n8n team

#10743 feat(editor): Add lint for $('Node').item in runOnceForAllItems mode
  cypress/e2e/6-code-node.cy.ts
  packages/editor-ui/src/components/CodeNodeEditor/linter.ts
  packages/editor-ui/src/styles/plugins/_codemirror.scss
Labels: node/improvement, n8n team

#10755 fix(editor): Restrict when the collision avoidance algorithm is used
  packages/editor-ui/src/components/canvas/elements/edges/CanvasConnectionLine.spec.ts
  packages/editor-ui/src/components/canvas/elements/edges/utils/edgePath.ts
Labels: ui, n8n team

#10766 fix(benchmark): Fix args formatting & validate scaling mode env vars
  packages/@n8n/benchmark/scripts/runForN8nSetup.mjs
  packages/@n8n/benchmark/scripts/utils/flags.mjs
Labels: n8n team

#10764 fix(core): Update subworkflow execution status correctly
  packages/cli/src/__tests__/active-executions.test.ts
  packages/cli/src/__tests__/workflow-helpers.test.ts
  packages/cli/src/active-executions.ts
  packages/cli/src/commands/execute-batch.ts
  packages/cli/src/commands/execute.ts
  packages/cli/src/commands/start.ts
  packages/cli/src/events/relay-event-map.ts
  packages/cli/src/executions/execution.service.ts
  packages/cli/src/interfaces.ts
  packages/cli/src/wait-tracker.ts
  packages/cli/src/webhooks/webhook-helpers.ts
  packages/cli/src/workflow-execute-additional-data.ts
  packages/cli/src/workflow-helpers.ts
  packages/cli/src/workflow-runner.ts
  packages/cli/src/workflows/workflow-execution.service.ts
  packages/workflow/src/Interfaces.ts
Labels: core, n8n team, tests-needed

#10725 fix(YouTube Node): Fix Date filters
  packages/nodes-base/nodes/Google/YouTube/YouTube.node.ts
Labels: node/improvement, n8n team

#10767 perf(editor): Fix WorkflowDetails excessive re-rendering
  packages/editor-ui/src/components/MainHeader/MainHeader.vue
  packages/editor-ui/src/components/MainHeader/WorkflowDetails.spec.ts
  packages/editor-ui/src/components/MainHeader/WorkflowDetails.vue
Labels: ui, n8n team

#10760 build(core): Allow adding tests side by side with the code
  packages/core/tsconfig.build.json
  packages/workflow/tsconfig.build.json
Labels: core, n8n team

#10769 fix(If Node): Update copy for type conversion parameter
  packages/design-system/src/components/N8nInputLabel/InputLabel.vue
  packages/nodes-base/utils/constants.ts
  packages/nodes-base/utils/descriptions.ts
  packages/workflow/src/NodeParameters/FilterParameter.ts
Labels: node/improvement, core, ui, n8n team

#10756 refactor(editor): Enable collaboration features only in NodeView v2 (no-changelog)
  packages/cli/src/collaboration/__tests__/collaboration.state.test.ts
  packages/cli/src/collaboration/collaboration.service.ts
  packages/cli/src/collaboration/collaboration.state.ts
  packages/cli/src/collaboration/collaboration.types.ts
  packages/cli/src/databases/entities/user.ts
  packages/cli/src/interfaces.ts
  packages/cli/test/integration/collaboration/collaboration.service.test.ts
  packages/editor-ui/src/Interface.ts
  packages/editor-ui/src/components/MainHeader/CollaborationPane.vue
  packages/editor-ui/src/components/MainHeader/WorkflowDetails.vue
  packages/editor-ui/src/components/__tests__/CollaborationPane.test.ts
  packages/editor-ui/src/composables/__tests__/useBeforeUnload.test.ts
  packages/editor-ui/src/composables/useBeforeUnload.ts
  packages/editor-ui/src/stores/collaboration.store.ts
  packages/editor-ui/src/stores/pushConnection.store.ts
  packages/editor-ui/src/views/NodeView.v2.vue
  packages/editor-ui/src/views/NodeViewSwitcher.vue
Labels: ui, n8n team

#10771 fix(editor): Revert remove tooltip from info tip (no-changelog)
  cypress/e2e/5-ndv.cy.ts
  packages/design-system/src/components/N8nInfoTip/InfoTip.stories.ts
  packages/design-system/src/components/N8nInfoTip/InfoTip.vue
  packages/design-system/src/components/N8nInfoTip/__tests__/InfoTip.spec.ts
  packages/design-system/src/components/N8nInfoTip/__tests__/__snapshots__/InfoTip.spec.ts.snap
Labels: ui, n8n team

#10735 feat(OpenAI Node): Add Max Tools Iteration parameter and prevent tool calling after execution is aborted
  packages/@n8n/nodes-langchain/nodes/vendors/OpenAi/actions/text/message.operation.ts
  packages/@n8n/nodes-langchain/nodes/vendors/OpenAi/actions/versionDescription.ts
  packages/@n8n/nodes-langchain/nodes/vendors/OpenAi/test/OpenAi.node.test.ts
Labels: n8n team

#10688 fix(editor): Fix error rendering and indexing of LLM sub-node outputs
  packages/@n8n/nodes-langchain/nodes/llms/N8nLlmTracing.ts
  packages/editor-ui/src/components/RunData.vue
  packages/editor-ui/src/components/RunDataAi/AiRunContentBlock.vue
  packages/editor-ui/src/components/RunDataAi/RunDataAiContent.vue
Labels: ui, n8n team

#10736 feat: Add credential help to Assistant (no-changelog)
  cypress/e2e/45-ai-assistant.cy.ts
  cypress/pages/features/ai-assistant.ts
  packages/editor-ui/src/App.vue
  packages/editor-ui/src/components/AskAssistant/AskAssistantChat.vue
  packages/editor-ui/src/components/AskAssistant/AskAssistantFloatingButton.vue
  packages/editor-ui/src/components/AskAssistant/NewAssistantSessionModal.vue
  packages/editor-ui/src/components/CredentialEdit/CredentialConfig.vue
  packages/editor-ui/src/components/Error/NodeErrorView.vue
  packages/editor-ui/src/stores/__tests__/assistant.store.test.ts
  packages/editor-ui/src/stores/assistant.store.ts
  packages/editor-ui/src/types/assistant.types.ts
Labels: core, n8n team

#10772 feat(editor): Show Collaboration pane only when there are multiple active users
  packages/editor-ui/src/components/MainHeader/CollaborationPane.vue
  packages/editor-ui/src/components/MainHeader/WorkflowDetails.vue
  packages/editor-ui/src/components/__tests__/CollaborationPane.test.ts
Labels: ui, n8n team

#10773 ci(benchmark): Add missing license cert
  .github/workflows/benchmark-nightly.yml
Labels: n8n team

#10752 refactor(core): Revamp subworkflow policy checker errors
  packages/cli/src/collaboration/collaboration.service.ts
  packages/cli/src/errors/subworkflow-policy-denial.error.ts
  packages/cli/src/services/__tests__/ownership.service.test.ts
  packages/cli/src/services/__tests__/workflow-statistics.service.test.ts
  packages/cli/src/services/access.service.ts
  packages/cli/src/services/ownership.service.ts
  packages/cli/src/services/workflow-statistics.service.ts
  packages/cli/src/subworkflows/__tests__/subworkflow-policy-checker.test.ts
  packages/cli/src/subworkflows/subworkflow-policy-checker.service.ts
  packages/cli/src/user-management/permission-checker.ts
  packages/cli/src/workflow-execute-additional-data.ts
  packages/cli/test/integration/permission-checker.test.ts
Labels: core, n8n team

#10780 fix(benchmark): Fix scaling mode setup
  packages/@n8n/benchmark/scripts/n8nSetups/scaling/docker-compose.yml
  packages/@n8n/benchmark/scripts/n8nSetups/scaling/setup.mjs
Labels: n8n team

#10782 fix(core): Fix the type for InstalledNodes.latestVersion (no-changelog)
  packages/cli/src/databases/entities/installed-nodes.ts
  packages/cli/src/databases/repositories/installed-packages.repository.ts
  packages/cli/test/integration/security-audit/utils.ts
  packages/cli/test/integration/shared/utils/community-nodes.ts
  packages/workflow/src/Interfaces.ts
Labels: core, n8n team

#10785 ci: Upgrade express to address CVE-2024-43796 (no-changelog)
  packages/cli/package.json
  pnpm-lock.yaml
Labels: core, n8n team

#10784 ci: Upgrade `validate-n8n-pull-request-title` to v2.2.0
  .github/pull_request_title_conventions.md
  .github/workflows/check-pr-title.yml
Labels: n8n team

#10768 refactor(core): Include AI events in log streaming relay
  packages/@n8n/nodes-langchain/nodes/llms/N8nLlmTracing.ts
  packages/@n8n/nodes-langchain/nodes/vector_store/shared/createVectorStoreNode.ts
  packages/@n8n/nodes-langchain/utils/helpers.ts
  packages/@n8n/nodes-langchain/utils/logWrapper.ts
  packages/cli/src/__tests__/workflow-execute-additional-data.test.ts
  packages/cli/src/eventbus/event-message-classes/event-message-ai-node.ts
  packages/cli/src/eventbus/event-message-classes/index.ts
  packages/cli/src/events/__tests__/log-streaming-event-relay.test.ts
  packages/cli/src/events/ai-event-map.ts
  packages/cli/src/events/event.service.ts
  packages/cli/src/events/log-streaming-event-relay.ts
  packages/cli/src/events/relay-event-map.ts
  packages/cli/src/workflow-execute-additional-data.ts
  packages/core/src/NodeExecuteFunctions.ts
  packages/workflow/src/Interfaces.ts
Labels: core, n8n team

#10783 refactor(benchmark): Rename scaling mode setups
  packages/@n8n/benchmark/scripts/n8nSetups/postgres/setup.mjs
  packages/@n8n/benchmark/scripts/n8nSetups/scaling-multi-main/docker-compose.yml
  packages/@n8n/benchmark/scripts/n8nSetups/scaling-multi-main/nginx.conf
  packages/@n8n/benchmark/scripts/n8nSetups/scaling-multi-main/setup.mjs
  packages/@n8n/benchmark/scripts/n8nSetups/scaling-single-main/docker-compose.yml
  packages/@n8n/benchmark/scripts/n8nSetups/scaling-single-main/setup.mjs
  packages/@n8n/benchmark/scripts/n8nSetups/sqlite-legacy/setup.mjs
  packages/@n8n/benchmark/scripts/n8nSetups/sqlite/setup.mjs
  packages/@n8n/benchmark/scripts/runForN8nSetup.mjs
Labels: n8n team

#10781 fix(core): Restore queue listeners for `webhook` process
  packages/cli/src/scaling/__tests__/scaling.service.test.ts
  packages/cli/src/scaling/scaling.service.ts
Labels: release/backport

#10703 refactor(editor): Convert `NodeExecuteButton` to composition api
  packages/editor-ui/src/components/NodeExecuteButton.vue
Labels: ui, n8n team

#10791 ci(benchmark): Run 3 times a night to account for fluctuations
  .github/workflows/benchmark-nightly.yml
Labels: n8n team

#10799 fix(editor): Render the current first in CollaborationPane (no-changelog)
  packages/editor-ui/src/components/MainHeader/CollaborationPane.vue
  packages/editor-ui/src/components/__tests__/CollaborationPane.test.ts
Labels: ui, n8n team

#10801 feat(OpenAI Node): Include O1 models in the models select
  packages/@n8n/nodes-langchain/nodes/llms/LMChatOpenAi/LmChatOpenAi.node.ts
  packages/@n8n/nodes-langchain/nodes/vendors/OpenAi/methods/listSearch.ts
Labels: n8n team

#10800 fix(editor): Fix completion on $input.item. in Code node
  packages/editor-ui/src/components/CodeNodeEditor/completions/__tests__/itemField.completions.test.ts
  packages/editor-ui/src/components/CodeNodeEditor/completions/itemField.completions.ts
  packages/editor-ui/src/components/CodeNodeEditor/completions/package.json
Labels: ui, n8n team

#10807 fix(editor): Make schema view search copy more clear
  packages/editor-ui/src/plugins/i18n/locales/en.json
Labels: ui, n8n team

#10742 refactor(core): Move push message types to a new shared package (no-changelog)
  .github/workflows/check-documentation-urls.yml
  packages/@n8n/api-types/.eslintrc.js
  packages/@n8n/api-types/README.md
  packages/@n8n/api-types/jest.config.js
  packages/@n8n/api-types/package.json
  packages/@n8n/api-types/src/datetime.ts
  packages/@n8n/api-types/src/index.ts
  packages/@n8n/api-types/src/push/collaboration.ts
  packages/@n8n/api-types/src/push/debug.ts
  packages/@n8n/api-types/src/push/execution.ts
  packages/@n8n/api-types/src/push/hot-reload.ts
  packages/@n8n/api-types/src/push/index.ts
  packages/@n8n/api-types/src/push/webhook.ts
  packages/@n8n/api-types/src/push/worker.ts
  packages/@n8n/api-types/src/push/workflow.ts
  packages/@n8n/api-types/src/scaling.ts
  packages/@n8n/api-types/src/user.ts
  packages/@n8n/api-types/tsconfig.build.json
  packages/@n8n/api-types/tsconfig.json
  packages/cli/package.json
  packages/cli/src/collaboration/collaboration.service.ts
  packages/cli/src/collaboration/collaboration.state.ts
  packages/cli/src/controllers/e2e.controller.ts
  packages/cli/src/interfaces.ts
  packages/cli/src/load-nodes-and-credentials.ts
  packages/cli/src/push/__tests__/websocket.push.test.ts
  packages/cli/src/push/abstract.push.ts
  packages/cli/src/push/index.ts
  packages/cli/src/scaling/job-processor.ts
  packages/cli/src/scaling/scaling.types.ts
  packages/cli/src/services/orchestration/helpers.ts
  packages/cli/src/services/orchestration/main/handle-worker-response-message-main.ts
  packages/cli/src/services/orchestration/pubsub/pubsub-message-map.ts
  packages/cli/src/services/orchestration/worker/handle-command-message-worker.ts
  packages/cli/src/services/orchestration/worker/types.ts
  packages/cli/src/services/redis/redis-service-commands.ts
  packages/cli/src/workflow-execute-additional-data.ts
  packages/cli/tsconfig.json
  packages/editor-ui/package.json
  packages/editor-ui/src/Interface.ts
  packages/editor-ui/src/components/WorkerList.ee.vue
  packages/editor-ui/src/components/Workers/WorkerCard.ee.vue
  packages/editor-ui/src/components/Workers/WorkerJobAccordion.ee.vue
  packages/editor-ui/src/components/Workers/WorkerNetAccordion.ee.vue
  packages/editor-ui/src/composables/__tests__/usePushConnection.spec.ts
  packages/editor-ui/src/composables/usePushConnection.ts
  packages/editor-ui/src/composables/useRunWorkflow.ts
  packages/editor-ui/src/stores/assistant.store.ts
  packages/editor-ui/src/stores/collaboration.store.ts
  packages/editor-ui/src/stores/orchestration.store.ts
  packages/editor-ui/src/stores/pushConnection.store.ts
  packages/editor-ui/src/stores/workflows.store.ts
  packages/editor-ui/src/types/pushConnection.ts
  packages/editor-ui/src/views/NodeView.vue
  pnpm-lock.yaml
  turbo.json
Labels: core, n8n team

#10806 fix(editor): Make expression edit modal read-only in executions view
  packages/editor-ui/src/components/ExpressionEditModal.test.ts
  packages/editor-ui/src/components/ExpressionEditModal.vue
  packages/editor-ui/src/components/ParameterInputList.vue
  packages/editor-ui/src/components/ResourceMapper/MappingFields.vue
  packages/editor-ui/src/components/ResourceMapper/MappingModeSelect.vue
  packages/editor-ui/src/components/ResourceMapper/MatchingColumnsSelect.vue
  packages/editor-ui/src/components/ResourceMapper/ResourceMapper.vue
  packages/editor-ui/src/components/__tests__/ResourceMapper.test.ts
Labels: ui, n8n team

#10808 fix(HTTP Request Tool Node): Fix subsequent tool calls reusung the same options
  packages/@n8n/nodes-langchain/nodes/tools/ToolHttpRequest/utils.ts
Labels: n8n team, tests-needed

#10811 refactor(core): Simplify createDeferredPromise, and add tests (no-changelog)
  packages/cli/src/__tests__/active-executions.test.ts
  packages/cli/src/active-executions.ts
  packages/cli/src/webhooks/webhook-helpers.ts
  packages/core/test/WorkflowExecute.test.ts
  packages/nodes-base/nodes/Amqp/AmqpTrigger.node.ts
  packages/nodes-base/nodes/EmailReadImap/v1/EmailReadImapV1.node.ts
  packages/nodes-base/nodes/EmailReadImap/v2/EmailReadImapV2.node.ts
  packages/nodes-base/nodes/Kafka/KafkaTrigger.node.ts
  packages/nodes-base/nodes/MQTT/MqttTrigger.node.ts
  packages/nodes-base/nodes/RabbitMQ/RabbitMQTrigger.node.ts
  packages/nodes-base/test/nodes/ExecuteWorkflow.ts
  packages/workflow/src/DeferredPromise.ts
  packages/workflow/src/Interfaces.ts
  packages/workflow/test/DeferredPromise.test.ts
Labels: node/improvement, core, n8n team

#10805 fix(editor): Prevent clipboard XSS injection
  packages/editor-ui/src/composables/__tests__/useClipboard.test.ts
  packages/editor-ui/src/composables/useClipboard.ts
  packages/editor-ui/src/composables/useMessage.ts
  packages/editor-ui/src/utils/htmlUtils.ts
Labels: ui, n8n team

#10822 chore: Upgrade to TypeScript 5.6
  package.json
  packages/cli/src/controllers/e2e.controller.ts
  packages/editor-ui/src/views/NodeView.vue
  pnpm-lock.yaml
Labels: core, ui, n8n team

#10749 test(core): Tests for task broker
  packages/cli/src/runners/__tests__/task-broker.test.ts
  packages/cli/src/runners/task-broker.service.ts
Labels: core, n8n team

#10826 refactor(core): Remove unused disable directives from backend packages
  packages/cli/src/environments/source-control/__tests__/source-control-export.service.test.ts
  packages/cli/src/eventbus/event-message-classes/abstract-event-message.ts
  packages/cli/src/events/telemetry-event-relay.ts
Labels: core, n8n team

#10825 refactor: Remove unused disable directives from `nodes-base`
  packages/nodes-base/nodes/AiTransform/AiTransform.node.ts
  packages/nodes-base/nodes/CompareDatasets/CompareDatasets.node.ts
  packages/nodes-base/nodes/Cron/Cron.node.ts
  packages/nodes-base/nodes/EmailReadImap/v1/EmailReadImapV1.node.ts
  packages/nodes-base/nodes/EmailReadImap/v2/EmailReadImapV2.node.ts
  packages/nodes-base/nodes/Form/v1/FormTriggerV1.node.ts
  packages/nodes-base/nodes/Form/v2/FormTriggerV2.node.ts
  packages/nodes-base/nodes/Google/Analytics/v1/GoogleAnalyticsV1.node.ts
  packages/nodes-base/nodes/Interval/Interval.node.ts
  packages/nodes-base/nodes/SplitInBatches/v2/SplitInBatchesV2.node.ts
  packages/nodes-base/nodes/SplitInBatches/v3/SplitInBatchesV3.node.ts
  packages/nodes-base/nodes/Start/Start.node.ts
  packages/nodes-base/nodes/StickyNote/StickyNote.node.ts
  packages/nodes-base/nodes/StopAndError/StopAndError.node.ts
  packages/nodes-base/nodes/Webflow/V1/WebflowTriggerV1.node.ts
  packages/nodes-base/nodes/Webflow/V2/WebflowTriggerV2.node.ts
  packages/nodes-base/nodes/Webhook/Webhook.node.ts
  packages/nodes-base/utils/descriptions.ts
Labels: node/improvement, n8n team

#10828 fix: Fix telemetry causing console error
  packages/editor-ui/src/stores/__tests__/assistant.store.test.ts
  packages/editor-ui/src/stores/assistant.store.ts
Labels: ui, n8n team, release/backport

#10813 fix: Prevent copying workflow when copying outside of canvas
  cypress/e2e/45-ai-assistant.cy.ts
  cypress/fixtures/aiAssistant/code_snippet_response.json
  cypress/pages/features/ai-assistant.ts
  packages/design-system/src/components/AskAssistantChat/AskAssistantChat.vue
  packages/design-system/src/components/AskAssistantChat/__tests__/AskAssistantChat.spec.ts
  packages/design-system/src/components/AskAssistantChat/__tests__/__snapshots__/AskAssistantChat.spec.ts.snap
  packages/editor-ui/src/components/AskAssistant/AskAssistantChat.vue
Labels: ui, n8n team, release/backport

#10827 ci(benchmark): Always perform az login before teardown
  .github/workflows/benchmark-nightly.yml
Labels: n8n team

#10640 refactor(core): Move `instanceType` to `InstanceSettings` (no-changelog)
  packages/cli/src/__tests__/license.test.ts
  packages/cli/src/abstract-server.ts
  packages/cli/src/commands/base-command.ts
  packages/cli/src/commands/start.ts
  packages/cli/src/commands/webhook.ts
  packages/cli/src/commands/worker.ts
  packages/cli/src/config/schema.ts
  packages/cli/src/databases/utils/generators.ts
  packages/cli/src/interfaces.ts
  packages/cli/src/license.ts
  packages/cli/src/scaling/__tests__/scaling.service.test.ts
  packages/cli/src/scaling/scaling.service.ts
  packages/cli/src/services/__tests__/orchestration.service.test.ts
  packages/cli/src/services/orchestration.service.ts
  packages/cli/src/services/orchestration/main/handle-command-message-main.ts
  packages/cli/src/services/orchestration/webhook/handle-command-message-webhook.ts
  packages/cli/src/services/orchestration/webhook/orchestration.webhook.service.ts
  packages/cli/src/services/orchestration/worker/orchestration.worker.service.ts
  packages/cli/src/services/pruning.service.ts
  packages/cli/src/workflow-runner.ts
  packages/cli/test/integration/commands/worker.cmd.test.ts
  packages/cli/test/integration/webhooks.api.test.ts
  packages/cli/test/integration/webhooks.test.ts
  packages/core/src/InstanceSettings.ts
  packages/core/src/index.ts
Labels: core, n8n team

#10829 fix(editor): Render image binary-data using img tags
  packages/editor-ui/src/components/BinaryDataDisplayEmbed.vue
Labels: ui, n8n team

#10533 ci: Ignore certain paths for e2e tests for PRs (no-changelog)
  .github/workflows/chromatic.yml
  .github/workflows/ci-postgres-mysql.yml
  .github/workflows/e2e-tests-pr.yml
Labels: n8n team

#10824 test(core): Fix license mock in worker test
  packages/cli/test/integration/commands/worker.cmd.test.ts
Labels: core, n8n team

#10823 test(core): Mock filesystem in tests
  packages/cli/src/environments/source-control/source-control-export.service.ee.ts
  packages/cli/src/environments/source-control/source-control-import.service.ee.ts
  packages/cli/test/integration/webhooks.api.test.ts
  packages/cli/test/setup-mocks.ts
Labels: core, n8n team

#10770 fix(Google Vertex Chat Model Node): Clean service account private key
  packages/@n8n/nodes-langchain/nodes/llms/LmChatGoogleVertex/LmChatGoogleVertex.node.ts
Labels: n8n team

#10814 refactor(core): Set up worker server
  packages/cli/src/commands/worker.ts
  packages/cli/src/errors/credentials-overwrites-already-set.error.ts
  packages/cli/src/errors/non-json-body.error.ts
  packages/cli/src/errors/port-taken.error.ts
  packages/cli/src/scaling/__tests__/worker-server.test.ts
  packages/cli/src/scaling/worker-server.ts
Labels: core, n8n team

#10840 refactor(core): Have `WorkerServer` use `InstanceSettings`
  packages/cli/src/scaling/__tests__/worker-server.test.ts
  packages/cli/src/scaling/worker-server.ts
Labels: core, n8n team

#10389 feat(Invoice Ninja Node): Add actions for bank transactions
  packages/nodes-base/nodes/InvoiceNinja/BankTransactionDescription.ts
  packages/nodes-base/nodes/InvoiceNinja/BankTransactionInterface.ts
  packages/nodes-base/nodes/InvoiceNinja/InvoiceNinja.node.ts
Labels: node/improvement, community, in linear

#10844 fix(core): Prevent shutdown error in regular mode
  packages/cli/src/commands/worker.ts
Labels: core, n8n team

#10843 fix(editor): Minimap Show nodes outside viewport
  packages/editor-ui/src/components/canvas/Canvas.vue
Labels: ui, n8n team

#10848 fix(Invoice Ninja Node): Fix lint error (no-changelog)
  packages/nodes-base/nodes/InvoiceNinja/BankTransactionDescription.ts
Labels: node/improvement, n8n team

#10849 fix(editor): Allow custom git repo urls in source control settings
  packages/editor-ui/src/views/SettingsSourceControl.test.ts
  packages/editor-ui/src/views/SettingsSourceControl.vue
Labels: ui, n8n team

#10842 feat(editor): Add truncate directive
  packages/design-system/src/directives/index.ts
  packages/design-system/src/directives/n8n-truncate.test.ts
  packages/design-system/src/directives/n8n-truncate.ts
  packages/design-system/src/main.ts
  packages/design-system/src/plugin.ts
  packages/design-system/src/utils/string.test.ts
  packages/design-system/src/utils/string.ts
Labels: ui, n8n team

#10846 refactor: Set up import/order eslint rule for workflow
  packages/workflow/.eslintrc.js
  packages/workflow/src/ErrorReporterProxy.ts
  packages/workflow/src/Expression.ts
  packages/workflow/src/ExpressionEvaluatorProxy.ts
  packages/workflow/src/ExpressionSandboxing.ts
  packages/workflow/src/Extensions/ArrayExtensions.ts
  packages/workflow/src/Extensions/DateExtensions.ts
  packages/workflow/src/Extensions/ExpressionExtension.ts
  packages/workflow/src/Extensions/ExtendedFunctions.ts
  packages/workflow/src/Extensions/NumberExtensions.ts
  packages/workflow/src/Extensions/ObjectExtensions.ts
  packages/workflow/src/Extensions/StringExtensions.ts
  packages/workflow/src/Extensions/utils.ts
  packages/workflow/src/Interfaces.ts
  packages/workflow/src/MessageEventBus.ts
  packages/workflow/src/NativeMethods/index.ts
  packages/workflow/src/NodeHelpers.ts
  packages/workflow/src/NodeParameters/FilterParameter.ts
  packages/workflow/src/RoutingNode.ts
  packages/workflow/src/TelemetryHelpers.ts
  packages/workflow/src/TypeValidation.ts
  packages/workflow/src/Workflow.ts
  packages/workflow/src/WorkflowDataProxy.ts
  packages/workflow/src/errors/abstract/node.error.ts
  packages/workflow/src/errors/application.error.ts
  packages/workflow/src/errors/credential-access-error.ts
  packages/workflow/src/errors/expression.error.ts
  packages/workflow/src/errors/node-api.error.ts
  packages/workflow/src/errors/node-operation.error.ts
  packages/workflow/src/errors/trigger-close.error.ts
  packages/workflow/src/errors/workflow-activation.error.ts
  packages/workflow/src/errors/workflow-operation.error.ts
  packages/workflow/src/utils.ts
  packages/workflow/test/AugmentObject.test.ts
  packages/workflow/test/Expression.test.ts
  packages/workflow/test/ExpressionExtensions/ArrayExtensions.test.ts
  packages/workflow/test/ExpressionExtensions/BooleanExtensions.test.ts
  packages/workflow/test/ExpressionExtensions/DateExtensions.test.ts
  packages/workflow/test/ExpressionExtensions/ExpressionExtension.test.ts
  packages/workflow/test/ExpressionExtensions/Helpers.ts
  packages/workflow/test/ExpressionExtensions/NumberExtensions.test.ts
  packages/workflow/test/ExpressionExtensions/ObjectExtensions.test.ts
  packages/workflow/test/ExpressionExtensions/StringExtensions.test.ts
  packages/workflow/test/ExpressionFixtures/base.ts
  packages/workflow/test/ExpressionSandboxing.test.ts
  packages/workflow/test/FilterParameter.test.ts
  packages/workflow/test/Helpers.ts
  packages/workflow/test/NodeErrors.test.ts
  packages/workflow/test/NodeHelpers.test.ts
  packages/workflow/test/NodeTypes.ts
  packages/workflow/test/RoutingNode.test.ts
  packages/workflow/test/TelemetryHelpers.test.ts
  packages/workflow/test/TypeValidation.test.ts
  packages/workflow/test/Workflow.test.ts
  packages/workflow/test/WorkflowDataProxy.test.ts
  packages/workflow/test/errors/node.error.test.ts
Labels: core, n8n team

#10855 fix(RSS Feed Trigger Node): Handle empty items gracefully
  packages/nodes-base/nodes/RssFeedRead/RssFeedReadTrigger.node.ts
  packages/nodes-base/nodes/RssFeedRead/test/RssFeedRead.test.ts
  packages/nodes-base/nodes/RssFeedRead/test/node/RssFeedRead.test.ts
Labels: node/improvement, n8n team

#10616 refactor(core): Flatten Redis pubsub class hierarchy (no-changelog)
  packages/cli/src/__tests__/wait-tracker.test.ts
  packages/cli/src/commands/start.ts
  packages/cli/src/commands/worker.ts
  packages/cli/src/license.ts
  packages/cli/src/scaling/__tests__/publisher.service.test.ts
  packages/cli/src/scaling/__tests__/subscriber.service.test.ts
  packages/cli/src/scaling/pubsub/publisher.service.ts
  packages/cli/src/scaling/pubsub/pubsub.types.ts
  packages/cli/src/scaling/pubsub/subscriber.service.ts
  packages/cli/src/services/__tests__/orchestration.service.test.ts
  packages/cli/src/services/__tests__/redis.service.test.ts
  packages/cli/src/services/orchestration.handler.base.service.ts
  packages/cli/src/services/orchestration.service.ts
  packages/cli/src/services/orchestration/main/multi-main-setup.ee.ts
  packages/cli/src/services/orchestration/main/orchestration.handler.main.service.ts
  packages/cli/src/services/orchestration/main/types.ts
  packages/cli/src/services/orchestration/webhook/orchestration.handler.webhook.service.ts
  packages/cli/src/services/orchestration/worker/handle-command-message-worker.ts
  packages/cli/src/services/orchestration/worker/orchestration.handler.worker.service.ts
  packages/cli/src/services/orchestration/worker/types.ts
  packages/cli/src/services/redis.service.ts
  packages/cli/src/services/redis/redis-service-commands.ts
  packages/cli/src/services/redis/redis-service-pub-sub-publisher.ts
  packages/cli/src/services/redis/redis-service-pub-sub-subscriber.ts
Labels: core, n8n team

#10857 feat(core): Allow customizing max file size in form-data payloads for webhooks
  packages/@n8n/config/src/configs/endpoints.config.ts
  packages/@n8n/config/test/config.test.ts
  packages/cli/src/webhooks/webhook-helpers.ts
Labels: core, n8n team

#10851 fix(Azure OpenAI Chat Model Node): Add response format option
  packages/@n8n/nodes-langchain/nodes/llms/LmChatAzureOpenAi/LmChatAzureOpenAi.node.ts
Labels: n8n team

#10854 build(benchmark): Fix docker image build
  .devcontainer/devcontainer.json
  docker/images/n8n-custom/Dockerfile
  package.json
  packages/@n8n/benchmark/Dockerfile
  scripts/prepare.mjs
Labels: n8n team

#10856 refactor(core): Move frontend settings to @n8n/api-types (no-changelog)
  cypress/package.json
  cypress/support/commands.ts
  cypress/support/index.ts
  packages/@n8n/api-types/src/frontend-settings.ts
  packages/@n8n/api-types/src/index.ts
  packages/cli/src/events/relay-event-map.ts
  packages/cli/src/interfaces.ts
  packages/cli/src/server.ts
  packages/cli/src/services/frontend.service.ts
  packages/editor-ui/src/Interface.ts
  packages/editor-ui/src/__tests__/defaults.ts
  packages/editor-ui/src/api/settings.ts
  packages/editor-ui/src/components/Telemetry.vue
  packages/editor-ui/src/plugins/telemetry/index.ts
  packages/editor-ui/src/stores/__tests__/posthog.test.ts
  packages/editor-ui/src/stores/__tests__/sso.test.ts
  packages/editor-ui/src/stores/__tests__/workflowHistory.store.test.ts
  packages/editor-ui/src/stores/settings.store.ts
  packages/editor-ui/src/stores/versions.store.ts
  packages/editor-ui/src/views/ProjectSettings.test.ts
  packages/workflow/src/Authentication.ts
  packages/workflow/src/Interfaces.ts
  packages/workflow/src/index.ts
  pnpm-lock.yaml
Labels: core, ui, n8n team

#10859 ci(benchmark): Benchmark vm before n8n benchmark
  packages/@n8n/benchmark/scripts/bootstrap.sh
  packages/@n8n/benchmark/scripts/run-in-cloud.mjs
  packages/@n8n/benchmark/scripts/vm-benchmark.sh
Labels: n8n team

#10860 fix(core): Upgrade `uuid` (no-changelog)
  pnpm-lock.yaml
  pnpm-workspace.yaml
Labels: node/improvement, n8n team

#10804 fix(editor): Replace v-html with custom directive to sanitize html
  packages/design-system/package.json
  packages/design-system/src/components/AskAssistantChat/AskAssistantChat.vue
  packages/design-system/src/components/AskAssistantChat/__tests__/AskAssistantChat.spec.ts
  packages/design-system/src/components/AskAssistantChat/__tests__/__snapshots__/AskAssistantChat.spec.ts.snap
  packages/design-system/src/components/N8nActionBox/ActionBox.vue
  packages/design-system/src/components/N8nInfoAccordion/InfoAccordion.vue
  packages/design-system/src/components/N8nInputLabel/InputLabel.vue
  packages/design-system/src/components/N8nMarkdown/Markdown.vue
  packages/design-system/src/components/N8nMarkdown/__tests__/Markdown.spec.ts
  packages/design-system/src/components/N8nNotice/Notice.vue
  packages/design-system/src/components/N8nNotice/__tests__/Notice.spec.ts
  packages/design-system/src/components/N8nSticky/Sticky.vue
  packages/design-system/src/components/N8nTabs/Tabs.vue
  packages/design-system/src/components/N8nTooltip/Tooltip.vue
  packages/design-system/src/directives/index.ts
  packages/design-system/src/directives/n8n-html.test.ts
  packages/design-system/src/directives/n8n-html.ts
  packages/editor-ui/src/components/Error/NodeErrorView.vue
  packages/editor-ui/src/components/ExpressionEditModal.vue
  packages/editor-ui/src/components/FeatureComingSoon.vue
  packages/editor-ui/src/components/InlineExpressionEditor/InlineExpressionTip.vue
  packages/editor-ui/src/components/InputPanel.vue
  packages/editor-ui/src/components/MappingPill.vue
  packages/editor-ui/src/components/Node.vue
  packages/editor-ui/src/components/Node/NodeCreator/ItemTypes/NodeItem.vue
  packages/editor-ui/src/components/Node/NodeCreator/Modes/ActionsMode.vue
  packages/editor-ui/src/components/Node/NodeCreator/Renderers/CategorizedItemsRenderer.vue
  packages/editor-ui/src/components/ParameterInput.vue
  packages/editor-ui/src/components/ParameterInputHint.vue
  packages/editor-ui/src/components/PushConnectionTracker.vue
  packages/editor-ui/src/components/ResourceMapper/MappingModeSelect.vue
  packages/editor-ui/src/components/RunData.vue
  packages/editor-ui/src/components/RunInfo.vue
  packages/editor-ui/src/components/TitledList.vue
  packages/editor-ui/src/components/TriggerPanel.vue
  packages/editor-ui/src/components/VersionCard.vue
  packages/editor-ui/src/components/WorkflowActivator.vue
  packages/editor-ui/src/components/WorkflowSettings.vue
  packages/editor-ui/src/components/banners/V1Banner.vue
  packages/editor-ui/src/components/banners/__tests__/V1Banner.spec.ts
  packages/editor-ui/src/components/banners/__tests__/__snapshots__/V1Banner.spec.ts.snap
  packages/editor-ui/src/components/canvas/elements/nodes/render-types/CanvasNodeDefault.vue
  packages/editor-ui/src/components/executions/workflow/WorkflowExecutionAnnotationPanel.vue
  packages/editor-ui/src/views/SettingsLdapView.vue
  packages/editor-ui/src/views/SettingsLogStreamingView.vue
  packages/editor-ui/src/views/SetupWorkflowFromTemplateView/AppsRequiringCredsNotice.vue
  packages/editor-ui/src/views/SetupWorkflowFromTemplateView/SetupTemplateFormStep.vue
  packages/editor-ui/src/views/TemplatesSearchView.vue
  pnpm-lock.yaml
Labels: ui, n8n team

#10841 fix(editor): Restore V1 keybinding, Space Key to toggle panning
  packages/editor-ui/src/components/canvas/Canvas.spec.ts
  packages/editor-ui/src/components/canvas/Canvas.vue
Labels: ui, n8n team

#10866 fix: Fix lint issues (no-changelog)
  packages/design-system/src/components/AskAssistantChat/__tests__/AskAssistantChat.spec.ts
  packages/design-system/src/components/N8nMarkdown/__tests__/Markdown.spec.ts
  packages/design-system/src/directives/n8n-html.test.ts
Labels: ui, n8n team

#10797 fix(OpenAI Node, Basic LLM Chain Node, Tool Agent Node): Better OpenAI API rate limit errors
  packages/@n8n/nodes-langchain/nodes/chains/ChainLLM/ChainLlm.node.ts
  packages/@n8n/nodes-langchain/nodes/llms/LMChatOpenAi/LmChatOpenAi.node.ts
  packages/@n8n/nodes-langchain/nodes/vendors/OpenAi/actions/router.ts
  packages/@n8n/nodes-langchain/nodes/vendors/OpenAi/helpers/error-handling.ts
Labels: n8n team

#10850 feat(core): Introduce worker metrics
  packages/cli/src/commands/worker.ts
  packages/cli/src/metrics/__tests__/prometheus-metrics.service.test.ts
  packages/cli/src/metrics/prometheus-metrics.service.ts
  packages/cli/src/scaling/__tests__/worker-server.test.ts
  packages/cli/src/scaling/worker-server.ts
Labels: core, n8n team

#10865 ci: Disallow `v-html` directive
  packages/@n8n_io/eslint-config/frontend.js
Labels: n8n team

#10869 ci: Fix nightly docker builds (no-changelog)
  docker/images/n8n-custom/Dockerfile
Labels: n8n team

#10256 feat: Implement new partial execution logic for acyclic workflows (no-changelog)
  cypress/e2e/19-execution.cy.ts
  cypress/e2e/28-debug.cy.ts
  cypress/e2e/30-editor-after-route-changes.cy.ts
  cypress/pages/workflow-executions-tab.ts
  cypress/utils/executions.ts
  packages/cli/src/config/schema.ts
  packages/cli/src/workflow-runner.ts
  packages/cli/src/workflows/workflow-execution.service.ts
  packages/cli/src/workflows/workflow.request.ts
  packages/cli/src/workflows/workflows.controller.ts
  packages/core/src/PartialExecutionUtils/DirectedGraph.ts
  packages/core/src/PartialExecutionUtils/__tests__/DirectedGraph.test.ts
  packages/core/src/PartialExecutionUtils/__tests__/findStartNodes.test.ts
  packages/core/src/PartialExecutionUtils/__tests__/findSubgraph.test.ts
  packages/core/src/PartialExecutionUtils/__tests__/getSourceDataGroups.test.ts
  packages/core/src/PartialExecutionUtils/__tests__/helpers.ts
  packages/core/src/PartialExecutionUtils/__tests__/recreateNodeExecutionStack.test.ts
  packages/core/src/PartialExecutionUtils/__tests__/toIConnections.test.ts
  packages/core/src/PartialExecutionUtils/__tests__/toITaskData.test.ts
  packages/core/src/PartialExecutionUtils/findCycles.ts
  packages/core/src/PartialExecutionUtils/findStartNodes.ts
  packages/core/src/PartialExecutionUtils/findSubgraph.ts
  packages/core/src/PartialExecutionUtils/findTriggerForPartialExecution.ts
  packages/core/src/PartialExecutionUtils/getIncomingData.ts
  packages/core/src/PartialExecutionUtils/getSourceDataGroups.ts
  packages/core/src/PartialExecutionUtils/index.ts
  packages/core/src/PartialExecutionUtils/recreateNodeExecutionStack.ts
  packages/core/src/WorkflowExecute.ts
  packages/editor-ui/src/composables/useRunWorkflow.ts
  packages/editor-ui/src/stores/workflows.store.ts
  packages/workflow/src/Interfaces.ts
Labels: core, ui, n8n team

#10874 ci(editor): Use eslint-plugin-prettier for vue files during development (no-changelog)
  packages/@n8n_io/eslint-config/frontend.js
  packages/@n8n_io/eslint-config/package.json
  pnpm-lock.yaml
Labels: n8n team

#10873 fix(MQTT Node): Close connection if connection attempt fails
  packages/nodes-base/nodes/MQTT/GenericFunctions.ts
  packages/nodes-base/nodes/MQTT/Mqtt.node.ts
  packages/nodes-base/nodes/MQTT/test/GenericFunctions.test.ts
Labels: node/improvement, n8n team

#10713 refactor(editor): Migrate `AuthView` and associated components to composition api
  packages/editor-ui/src/views/AuthView.vue
  packages/editor-ui/src/views/ChangePasswordView.vue
  packages/editor-ui/src/views/ForgotMyPasswordView.vue
  packages/editor-ui/src/views/SamlOnboarding.vue
  packages/editor-ui/src/views/SetupView.vue
  packages/editor-ui/src/views/SigninView.vue
Labels: node/improvement, n8n team

#10864 refactor(core): Organize Redis under scaling mode
  packages/cli/src/scaling/__tests__/publisher.service.test.ts
  packages/cli/src/scaling/__tests__/subscriber.service.test.ts
  packages/cli/src/scaling/constants.ts
  packages/cli/src/scaling/pubsub/publisher.service.ts
  packages/cli/src/scaling/pubsub/pubsub.types.ts
  packages/cli/src/scaling/pubsub/subscriber.service.ts
  packages/cli/src/scaling/redis/redis-service-commands.ts
  packages/cli/src/scaling/redis/redis.types.ts
  packages/cli/src/scaling/scaling.service.ts
  packages/cli/src/scaling/scaling.types.ts
  packages/cli/src/services/__tests__/orchestration.service.test.ts
  packages/cli/src/services/cache/cache.service.ts
  packages/cli/src/services/orchestration.service.ts
  packages/cli/src/services/orchestration/helpers.ts
  packages/cli/src/services/orchestration/main/handle-worker-response-message-main.ts
  packages/cli/src/services/orchestration/main/multi-main-setup.ee.ts
  packages/cli/src/services/orchestration/main/orchestration.handler.main.service.ts
  packages/cli/src/services/orchestration/pubsub/pubsub-message-map.ts
  packages/cli/src/services/orchestration/webhook/orchestration.handler.webhook.service.ts
  packages/cli/src/services/orchestration/worker/handle-command-message-worker.ts
  packages/cli/src/services/orchestration/worker/types.ts
  packages/cli/src/services/redis-client.service.ts
  packages/cli/src/services/redis/redis-constants.ts
  packages/cli/src/services/redis/redis-service-base-classes.ts
Labels: core, n8n team

#10878 ci: Upgrade storybook and chromatic (no-changelog)
  packages/@n8n/storybook/package.json
  pnpm-lock.yaml
Labels: n8n team

#10882 fix(editor): Update gird size when opening credentials support chat
  packages/editor-ui/src/stores/assistant.store.ts
Labels: ui, n8n team

#10838 perf(editor): Use virtual scrolling in `RunDataJson.vue`
  packages/editor-ui/src/components/RunDataJson.vue
  packages/editor-ui/src/components/__tests__/RunDataJson.test.ts
  packages/editor-ui/src/components/__tests__/__snapshots__/RunDataJson.test.ts.snap
Labels: ui, n8n team

#10719 refactor(editor): Migrate `LogStreaming.store.ts` to composition API
  packages/editor-ui/src/stores/logStreaming.store.ts
  packages/editor-ui/src/views/SettingsLogStreamingView.vue
Labels: node/improvement, n8n team

#10879 fix(benchmark): Simplify binary data scenario setup and use larger binary file
  packages/@n8n/benchmark/scenarios/binary-data/binary-data.script.js
  packages/@n8n/benchmark/src/test-execution/k6-executor.ts
Labels: n8n team

#10876 ci: Remove eslint-plugin-prettier again (no-changelog)
  package.json
  packages/@n8n_io/eslint-config/frontend.js
  packages/@n8n_io/eslint-config/package.json
  packages/editor-ui/package.json
  packages/editor-ui/src/components/Draggable.vue
  packages/editor-ui/src/components/InputPanel.vue
  packages/editor-ui/src/components/Projects/ProjectSharing.vue
  packages/editor-ui/src/components/RBAC.vue
  packages/editor-ui/src/components/SaveButton.vue
  packages/editor-ui/src/components/WorkflowSelectorParameterInput/WorkflowSelectorParameterInput.vue
  packages/editor-ui/src/components/canvas/elements/handles/render-types/CanvasHandleMainOutput.vue
  packages/editor-ui/src/components/executions/workflow/WorkflowExecutionsList.vue
  packages/editor-ui/src/views/NodeView.v2.vue
  packages/editor-ui/src/views/NodeView.vue
  packages/editor-ui/src/views/VariablesView.vue
  pnpm-lock.yaml
Labels: ui, n8n team

#10890 refactor(editor): Stop importing Vue compiler macros
  packages/design-system/src/components/AskAssistantLoadingMessage/AssistantLoadingMessage.vue
  packages/editor-ui/src/components/AnnotationTagsContainer.vue
  packages/editor-ui/src/components/NodeExecuteButton.vue
  packages/editor-ui/src/components/executions/ExecutionsTime.vue
  packages/editor-ui/src/components/executions/workflow/VoteButtons.vue
Labels: ui, n8n team

#10894 fix(editor): Prevent clipboard xss injection
  packages/editor-ui/src/composables/__tests__/useClipboard.test.ts
  packages/editor-ui/src/composables/useClipboard.ts
  packages/editor-ui/src/utils/__tests__/htmlUtils.spec.ts
  packages/editor-ui/src/utils/htmlUtils.ts
Labels: ui, n8n team, release/backport

#10897 fix(core): Fix webhook binary data max size configuration
  packages/cli/src/webhooks/webhook-helpers.ts
Labels: core, n8n team, release/backport

#10884 refactor(editor): Clean all instances of `isDesktopDeployment`
  packages/cli/src/services/frontend.service.ts
  packages/editor-ui/src/components/PersonalizationModal.test.ts
  packages/editor-ui/src/components/PersonalizationModal.vue
  packages/editor-ui/src/plugins/i18n/locales/en.json
  packages/editor-ui/src/router.ts
  packages/editor-ui/src/stores/settings.store.ts
  packages/editor-ui/src/stores/ui.store.ts
  packages/editor-ui/src/stores/usage.store.ts
  packages/editor-ui/src/views/SettingsCommunityNodesView.vue
  packages/editor-ui/src/views/SettingsUsageAndPlan.vue
  packages/editor-ui/src/views/SigninView.vue
Labels: ui, n8n team
