Repository n8n-io/n8n, pull requests merged in 2024-03, with the labels that each got.

#8778 fix: Simplify Structured Output Parser wrapping and fix auto-fixing output parser
  packages/@n8n/nodes-langchain/nodes/output_parser/OutputParserStructured/OutputParserStructured.node.ts
  packages/@n8n/nodes-langchain/utils/logWrapper.ts
Labels: n8n team

#8695 feat(editor): Add project settings page
  cypress/composables/projects.ts
  cypress/e2e/39-projects.cy.ts
  packages/design-system/src/components/N8nMenuItem/MenuItem.vue
  packages/design-system/src/types/menu.ts
  packages/editor-ui/src/components/MainSidebar.vue
  packages/editor-ui/src/constants.ts
  packages/editor-ui/src/features/projects/ProjectNavigation.vue
  packages/editor-ui/src/features/projects/components/ProjectNavigation.vue
  packages/editor-ui/src/features/projects/components/ProjectSettings.vue
  packages/editor-ui/src/features/projects/components/ProjectTabs.vue
  packages/editor-ui/src/features/projects/components/__tests__/ProjectTabs.test.ts
  packages/editor-ui/src/features/projects/projects.api.ts
  packages/editor-ui/src/features/projects/projects.routes.ts
  packages/editor-ui/src/features/projects/projects.store.ts
  packages/editor-ui/src/features/projects/projects.types.ts
  packages/editor-ui/src/init.ts
  packages/editor-ui/src/plugins/i18n/locales/en.json
  packages/editor-ui/src/stores/workflows.store.ts
  packages/editor-ui/src/views/CredentialsView.vue
  packages/editor-ui/src/views/WorkflowsView.vue
Labels: ui, n8n team, feature/rbac

#8780 fix(TheHive 5 Node): The Hive - Custom fields are no longer working
  packages/nodes-base/nodes/TheHiveProject/actions/alert/update.operation.ts
  packages/nodes-base/nodes/TheHiveProject/actions/case/update.operation.ts
Labels: n8n team, node/issue

#8781 fix(n8n Form Trigger Node): Do not open pop up when data is pinned in trigger
  packages/editor-ui/src/composables/useRunWorkflow.ts
Labels: n8n team, node/issue

#8775 feat: Make `GET /workflows` return all workflows the user is allowed to see based on the `workflow:read` scope
  packages/cli/src/executions/executions.controller.ts
  packages/cli/src/workflows/workflowSharing.service.ts
  packages/cli/src/workflows/workflows.controller.ts
  packages/cli/test/integration/executions.controller.test.ts
  packages/cli/test/integration/shared/db/workflows.ts
  packages/cli/test/integration/workflows/workflowSharing.service.test.ts
  packages/cli/test/integration/workflows/workflows.controller.ee.test.ts
Labels: core, n8n team

#8783 fix(Wait Node): Change default wait period to 5 seconds
  packages/nodes-base/nodes/Wait/Wait.node.ts
Labels: node/improvement, n8n team, node/issue

#8787 ci(editor): Start optionally type-checking frontend code during build (no-changelog)
  package.json
  packages/@n8n/chat/vite.config.ts
  packages/design-system/vite.config.mts
  packages/editor-ui/vite.config.mts
  pnpm-lock.yaml
Labels: ui, n8n team

#8785 feat(editor): Show home project in card components
  packages/editor-ui/src/Interface.ts
  packages/editor-ui/src/components/CredentialCard.vue
  packages/editor-ui/src/components/WorkflowCard.vue
  packages/editor-ui/src/components/__tests__/CredentialCard.test.ts
  packages/editor-ui/src/components/__tests__/WorkflowCard.test.ts
Labels: ui, n8n team

#8786 fix(Google Drive Node): Add supportsAllDrives: true to update and download
  packages/nodes-base/nodes/Google/Drive/test/v2/node/file/download.test.ts
  packages/nodes-base/nodes/Google/Drive/v2/actions/file/download.operation.ts
  packages/nodes-base/nodes/Google/Drive/v2/actions/file/update.operation.ts
Labels: node/improvement, n8n team

#8771 fix(editor): Set correct type for right input in filter component
  packages/editor-ui/src/components/FilterConditions/Condition.vue
  packages/editor-ui/src/components/FilterConditions/__tests__/FilterConditions.test.ts
Labels: ui, n8n team

#8782 fix(editor): Update assignment hint when user hovers table row
  cypress/e2e/14-mapping.cy.ts
  cypress/fixtures/Test_workflow_3.json
  packages/editor-ui/src/components/AssignmentCollection/Assignment.vue
Labels: ui, n8n team

#8806 perf: Upgrade Vue
  package.json
  packages/design-system/package.json
  packages/editor-ui/package.json
  pnpm-lock.yaml
Labels: ui, n8n team

#8807 fix(editor): Fix retrieving of messages from memory in chat modal
  packages/@n8n/nodes-langchain/utils/logWrapper.ts
  packages/editor-ui/src/components/WorkflowLMChat.vue
Labels: ui, n8n team

#8809 fix(editor): Fix opening of node creator for sub-nodes connection hint link
  cypress/e2e/5-ndv.cy.ts
  cypress/fixtures/open_node_creator_for_connection.json
  packages/@n8n/nodes-langchain/utils/sharedFields.ts
Labels: n8n team

#8788 feat(Notion Node): Continue on fail support
  packages/nodes-base/nodes/Notion/NotionTrigger.node.ts
  packages/nodes-base/nodes/Notion/shared/GenericFunctions.ts
  packages/nodes-base/nodes/Notion/shared/descriptions/BlockDescription.ts
  packages/nodes-base/nodes/Notion/shared/descriptions/Blocks.ts
  packages/nodes-base/nodes/Notion/shared/descriptions/DatabaseDescription.ts
  packages/nodes-base/nodes/Notion/shared/descriptions/DatabasePageDescription.ts
  packages/nodes-base/nodes/Notion/shared/descriptions/Filters.ts
  packages/nodes-base/nodes/Notion/shared/descriptions/PageDescription.ts
  packages/nodes-base/nodes/Notion/shared/descriptions/UserDescription.ts
  packages/nodes-base/nodes/Notion/shared/methods/index.ts
  packages/nodes-base/nodes/Notion/shared/methods/listSearch.ts
  packages/nodes-base/nodes/Notion/test/GenericFunctions.test.ts
  packages/nodes-base/nodes/Notion/v1/NotionV1.node.ts
  packages/nodes-base/nodes/Notion/v1/VersionDescription.ts
  packages/nodes-base/nodes/Notion/v2/NotionV2.node.ts
  packages/nodes-base/nodes/Notion/v2/VersionDescription.ts
  packages/nodes-base/nodes/Notion/v2/methods/index.ts
  packages/nodes-base/nodes/Notion/v2/methods/loadOptions.ts
Labels: node/improvement, n8n team, node/issue

#8804 fix(OpenAI Node): Message text operation parameters case fix
  packages/@n8n/nodes-langchain/nodes/vendors/OpenAi/actions/text/message.operation.ts
Labels: n8n team, node/issue

#8810 feat(core): Update hashing strategy for JWTs
  packages/cli/src/auth/auth.service.ts
  packages/cli/test/unit/auth/auth.service.test.ts
Labels: core, n8n team

#8808 fix(editor): Fix NDV output tabs resetting on any click
  packages/editor-ui/src/components/ExpressionParameterInput.vue
  packages/editor-ui/src/components/RunData.vue
  packages/editor-ui/src/components/__tests__/ExpressionParameterInput.test.ts
Labels: ui, n8n team

#8774 feat: Track node errors on PostHog
  packages/editor-ui/src/components/RunData.vue
Labels: node/improvement, n8n team

#8811 feat(core): Upgrade expressjs (no-changelog)
  packages/cli/package.json
  pnpm-lock.yaml
Labels: core, n8n team

#8816 fix(editor): Upgrade sanitize-html to address CVE-2024-21501
  packages/design-system/package.json
  pnpm-lock.yaml
Labels: ui, n8n team

#8817 fix(Basic LLM Chain Node): Fix retrieving of prompt parameter for v1.3 of the node
  packages/@n8n/nodes-langchain/nodes/chains/ChainLLM/ChainLlm.node.ts
Labels: n8n team

#8815 fix(core): Refactor push sessionid validation, and add unit tests (no-changelog)
  packages/cli/src/push/index.ts
  packages/cli/src/push/types.ts
  packages/cli/test/unit/push/index.test.ts
Labels: core, n8n team

#8812 feat(core)!: Set the `secure` flag on issued cookies
  packages/cli/BREAKING-CHANGES.md
  packages/cli/src/auth/auth.service.ts
  packages/cli/src/config/index.ts
  packages/cli/src/config/schema.ts
  packages/cli/test/unit/auth/auth.service.test.ts
  packages/cli/test/unit/controllers/me.controller.test.ts
Labels: core, n8n team

#8776 fix: PermissionChecker integration tests (no-changelog)
  packages/cli/test/integration/PermissionChecker.test.ts
Labels: core, n8n team

#8790 feat: Make `GET /credentials` return all credentials the user is allowed to see based on the `credential:read` scope
  packages/cli/src/UserManagement/PermissionChecker.ts
  packages/cli/src/credentials/credentials.service.ts
  packages/cli/src/databases/repositories/sharedCredentials.repository.ts
  packages/cli/test/integration/credentials.ee.test.ts
  packages/cli/test/integration/shared/db/credentials.ts
  packages/cli/test/integration/shared/testDb.ts
  packages/cli/test/integration/shared/types.ts
  packages/cli/test/unit/PermissionChecker.test.ts
Labels: core, n8n team

#8743 docs: Update OpenAI Node primaryDocumentation URL to match docs URL change
  packages/@n8n/nodes-langchain/nodes/vendors/OpenAi/actions/versionDescription.ts
Labels: community

#8801 feat: Track self serve trial (no-changelog)
  packages/editor-ui/src/components/PersonalizationModal.vue
  packages/editor-ui/src/components/__tests__/PersonalizationModal.spec.ts
Labels: ui, n8n team

#8824 docs(AwsS3 Node): Update tooltip message for Source Path
  packages/nodes-base/nodes/Aws/S3/V1/FileDescription.ts
  packages/nodes-base/nodes/Aws/S3/V2/FileDescription.ts
Labels: node/improvement, community

#8819 fix: Fix indentation in bash script for docker postgres init (no-changelog)
  docker/compose/withPostgres/init-data.sh
Labels: community

#8798 fix(GitHub Document Loader Node): Fix issue with ignore paths not working correctly
  packages/@n8n/nodes-langchain/nodes/document_loaders/DocumentGithubLoader/DocumentGithubLoader.node.ts
Labels: community

#8830 fix: Always register webhooks on startup
  packages/cli/src/services/orchestration.service.ts
  packages/cli/test/unit/services/orchestration.service.test.ts
Labels: core, n8n team

#8720 feat(editor): Add sections to autocomplete dropdown
  cypress/e2e/13-pinning.cy.ts
  packages/design-system/src/css/_tokens.dark.scss
  packages/design-system/src/css/_tokens.scss
  packages/editor-ui/src/Interface.ts
  packages/editor-ui/src/components/CodeNodeEditor/baseExtensions.ts
  packages/editor-ui/src/components/CodeNodeEditor/completer.ts
  packages/editor-ui/src/components/ExpressionEditorModal/ExpressionEditorModalInput.vue
  packages/editor-ui/src/components/HtmlEditor/HtmlEditor.vue
  packages/editor-ui/src/components/InlineExpressionEditor/InlineExpressionEditorInput.vue
  packages/editor-ui/src/components/JsEditor/JsEditor.vue
  packages/editor-ui/src/components/JsonEditor/JsonEditor.vue
  packages/editor-ui/src/components/SqlEditor/SqlEditor.vue
  packages/editor-ui/src/mixins/completionManager.ts
  packages/editor-ui/src/mixins/expressionManager.ts
  packages/editor-ui/src/plugins/codemirror/completions/__tests__/completions.test.ts
  packages/editor-ui/src/plugins/codemirror/completions/constants.ts
  packages/editor-ui/src/plugins/codemirror/completions/datatype.completions.ts
  packages/editor-ui/src/plugins/codemirror/completions/dollar.completions.ts
  packages/editor-ui/src/plugins/codemirror/completions/nativesAutocompleteDocs/luxon.instance.docs.ts
  packages/editor-ui/src/plugins/codemirror/completions/types.ts
  packages/editor-ui/src/plugins/codemirror/completions/utils.ts
  packages/editor-ui/src/plugins/codemirror/keymap.ts
  packages/editor-ui/src/plugins/codemirror/n8nLang.ts
  packages/editor-ui/src/plugins/codemirror/resolvableHighlighter.ts
  packages/editor-ui/src/plugins/i18n/index.ts
  packages/editor-ui/src/plugins/i18n/locales/en.json
  packages/editor-ui/src/styles/plugins/_codemirror.scss
  packages/editor-ui/src/utils/expressions.ts
  packages/workflow/src/Extensions/DateExtensions.ts
  packages/workflow/src/Extensions/Extensions.ts
  packages/workflow/src/Extensions/ObjectExtensions.ts
  packages/workflow/src/Extensions/StringExtensions.ts
  packages/workflow/src/NativeMethods/Object.Methods.ts
  packages/workflow/src/NativeMethods/String.methods.ts
  packages/workflow/test/ExpressionExtensions/ObjectExtensions.test.ts
Labels: core, ui, n8n team

#8644 feat(editor): Improve errors in output panel
  packages/@n8n/nodes-langchain/nodes/vendors/OpenAi/actions/router.ts
  packages/cli/src/services/frontend.service.ts
  packages/editor-ui/src/Interface.ts
  packages/editor-ui/src/__tests__/server/endpoints/settings.ts
  packages/editor-ui/src/__tests__/utils.ts
  packages/editor-ui/src/components/Error/NodeErrorView.vue
  packages/editor-ui/src/components/RunData.vue
  packages/editor-ui/src/plugins/i18n/locales/en.json
  packages/editor-ui/src/stores/n8nRoot.store.ts
  packages/editor-ui/src/stores/settings.store.ts
  packages/nodes-base/nodes/Airtable/v2/actions/base/getSchema.operation.ts
  packages/nodes-base/nodes/Airtable/v2/actions/record/create.operation.ts
  packages/nodes-base/nodes/Airtable/v2/actions/record/deleteRecord.operation.ts
  packages/nodes-base/nodes/Airtable/v2/actions/record/get.operation.ts
  packages/nodes-base/nodes/Airtable/v2/actions/record/update.operation.ts
  packages/nodes-base/nodes/Airtable/v2/actions/record/upsert.operation.ts
  packages/nodes-base/nodes/Airtable/v2/helpers/utils.ts
  packages/nodes-base/nodes/Cal/GenericFunctions.ts
  packages/nodes-base/nodes/Code/Code.node.ts
  packages/nodes-base/nodes/Filter/V2/FilterV2.node.ts
  packages/nodes-base/nodes/Google/Drive/v2/transport/index.ts
  packages/nodes-base/nodes/Google/Sheet/v2/actions/router.ts
  packages/nodes-base/nodes/Google/Sheet/v2/actions/sheet/remove.operation.ts
  packages/nodes-base/nodes/Google/Sheet/v2/helpers/GoogleSheet.ts
  packages/nodes-base/nodes/Google/Sheet/v2/transport/index.ts
  packages/nodes-base/nodes/HttpRequest/V3/HttpRequestV3.node.ts
  packages/nodes-base/nodes/Hubspot/V2/HubspotV2.node.ts
  packages/nodes-base/nodes/If/V2/IfV2.node.ts
  packages/nodes-base/nodes/Switch/V3/SwitchV3.node.ts
  packages/nodes-base/nodes/UProc/GenericFunctions.ts
  packages/workflow/src/Constants.ts
  packages/workflow/src/Interfaces.ts
  packages/workflow/src/RoutingNode.ts
  packages/workflow/src/errors/abstract/node.error.ts
  packages/workflow/src/errors/node-api.error.ts
  packages/workflow/src/errors/node-operation.error.ts
  packages/workflow/test/NodeErrors.test.ts
  packages/workflow/test/errors/node.error.test.ts
Labels: ui, n8n team

#8838 fix: Correct misspelling from omited to omitted (no-changelog)
  packages/nodes-base/credentials/CustomerIoApi.credentials.ts
  packages/nodes-base/nodes/Filter/Filter.node.json
Labels: node/improvement, community

#8832 fix: Improve filter component error handling
  packages/editor-ui/src/components/FilterConditions/Condition.vue
  packages/editor-ui/src/components/FilterConditions/utils.ts
  packages/nodes-base/nodes/Filter/V2/FilterV2.node.ts
  packages/nodes-base/nodes/If/V2/IfV2.node.ts
  packages/nodes-base/nodes/Switch/V3/SwitchV3.node.ts
  packages/workflow/src/NodeParameters/FilterParameter.ts
  packages/workflow/test/FilterParameter.test.ts
Labels: node/improvement, core, ui, n8n team

#8834 fix: Display readable error when manual executions contains large payload
  packages/editor-ui/src/plugins/i18n/locales/en.json
  packages/editor-ui/src/stores/workflows.store.ts
  packages/editor-ui/src/utils/apiUtils.ts
Labels: ui, n8n team

#8842 fix(core): Add fallback for pairedItem info in runPartialWorkflow
  packages/core/src/WorkflowExecute.ts
Labels: core, n8n team

#8849 feat: Update Pinecone Vector Store node to support serverless environments
  packages/@n8n/nodes-langchain/credentials/PineconeApi.credentials.ts
  packages/@n8n/nodes-langchain/nodes/vector_store/VectorStorePinecone/VectorStorePinecone.node.ts
  packages/@n8n/nodes-langchain/package.json
  pnpm-lock.yaml
Labels: n8n team

#8847 refactor: Update Mistral langchain module (no-changelog)
  packages/@n8n/nodes-langchain/package.json
  pnpm-lock.yaml
Labels: n8n team, node/issue

#8858 fix(editor): Do not throw an error when calculating dynamic inputs/outputs (no-changelog)
  packages/@n8n/nodes-langchain/nodes/agents/Agent/Agent.node.ts
  packages/@n8n/nodes-langchain/nodes/chains/ChainLLM/ChainLlm.node.ts
  packages/workflow/src/NodeHelpers.ts
Labels: core, n8n team

#8841 fix: Allow sharee to use workflows with http request node without credential access
  packages/editor-ui/src/composables/useNodeHelpers.ts
Labels: ui, n8n team

#8848 fix: Disable pinning for root nodes from canvas
  packages/editor-ui/src/composables/__tests__/useContextMenu.test.ts
  packages/editor-ui/src/composables/useContextMenu.ts
Labels: ui, n8n team

#8863 fix: Ignore semver range when upgrading comunity packages
  packages/cli/src/services/communityPackages.service.ts
  packages/cli/test/unit/services/communityPackages.service.test.ts
Labels: core, n8n team

#8844 feat: Remove user from SharedCredentials and update most credential related code to work with projects instead of users
  packages/cli/src/CredentialsHelper.ts
  packages/cli/src/PublicApi/v1/handlers/credentials/credentials.service.ts
  packages/cli/src/commands/import/credentials.ts
  packages/cli/src/commands/user-management/reset.ts
  packages/cli/src/controllers/oauth/abstractOAuth.controller.ts
  packages/cli/src/controllers/users.controller.ts
  packages/cli/src/credentials/credentials.controller.ts
  packages/cli/src/credentials/credentials.service.ee.ts
  packages/cli/src/credentials/credentials.service.ts
  packages/cli/src/databases/entities/SharedCredentials.ts
  packages/cli/src/databases/entities/User.ts
  packages/cli/src/databases/migrations/common/1705928727784-CreateProject.ts
  packages/cli/src/databases/repositories/credentials.repository.ts
  packages/cli/src/databases/repositories/sharedCredentials.repository.ts
  packages/cli/src/databases/repositories/workflow.repository.ts
  packages/cli/src/environments/sourceControl/sourceControlImport.service.ee.ts
  packages/cli/src/executions/execution.service.ee.ts
  packages/cli/src/requests.ts
  packages/cli/src/services/ownership.service.ts
  packages/cli/src/workflows/workflow.service.ee.ts
  packages/cli/src/workflows/workflows.controller.ts
  packages/cli/src/workflows/workflows.types.ts
  packages/cli/test/integration/CredentialsHelper.test.ts
  packages/cli/test/integration/PermissionChecker.test.ts
  packages/cli/test/integration/credentials.controller.test.ts
  packages/cli/test/integration/credentials.ee.test.ts
  packages/cli/test/integration/credentials.test.ts
  packages/cli/test/integration/publicApi/credentials.test.ts
  packages/cli/test/integration/shared/db/credentials.ts
  packages/cli/test/integration/users.api.test.ts
  packages/cli/test/integration/workflows/workflows.controller.ee.test.ts
  packages/cli/test/integration/workflows/workflows.controller.test.ts
  packages/cli/test/unit/repositories/sharedCredentials.repository.test.ts
  packages/cli/test/unit/services/ownership.service.test.ts
Labels: core, n8n team

#8839 fix(editor): Fix workflow card open action
  packages/editor-ui/src/components/WorkflowCard.vue
  packages/editor-ui/src/components/__tests__/WorkflowCard.test.ts
Labels: ui, n8n team

#8866 fix: OpenAI node text > message hide tools connector for unsupported models
  packages/@n8n/nodes-langchain/nodes/vendors/OpenAi/actions/text/message.operation.ts
  packages/@n8n/nodes-langchain/nodes/vendors/OpenAi/actions/versionDescription.ts
  packages/@n8n/nodes-langchain/nodes/vendors/OpenAi/helpers/constants.ts
Labels: node/improvement, n8n team, node/issue

#8865 docs: Update docs URLs and skip URL checking for hidden nodes (no-changelog)
  .github/scripts/package.json
  .github/scripts/validate-docs-links.js
  packages/nodes-base/nodes/Microsoft/Outlook/MicrosoftOutlookTrigger.node.json
  packages/nodes-base/nodes/OpenAi/OpenAi.node.json
Labels: node/improvement, n8n team

#8814 feat(editor): Add project sharing
  packages/editor-ui/src/Interface.ts
  packages/editor-ui/src/__tests__/data/projects.ts
  packages/editor-ui/src/__tests__/mocks.ts
  packages/editor-ui/src/components/CredentialCard.vue
  packages/editor-ui/src/components/CredentialEdit/CredentialEdit.vue
  packages/editor-ui/src/components/CredentialEdit/CredentialSharing.ee.vue
  packages/editor-ui/src/components/WorkflowCard.vue
  packages/editor-ui/src/components/WorkflowShareModal.ee.vue
  packages/editor-ui/src/features/projects/__tests__/projects.utils.test.ts
  packages/editor-ui/src/features/projects/components/ProjectNavigation.vue
  packages/editor-ui/src/features/projects/components/ProjectSettings.vue
  packages/editor-ui/src/features/projects/components/ProjectSharing.vue
  packages/editor-ui/src/features/projects/components/ProjectSharingInfo.vue
  packages/editor-ui/src/features/projects/components/ProjectTabs.vue
  packages/editor-ui/src/features/projects/components/__tests__/ProjectSharing.test.ts
  packages/editor-ui/src/features/projects/projects.types.ts
  packages/editor-ui/src/features/projects/projects.utils.ts
  packages/editor-ui/src/plugins/i18n/locales/en.json
  packages/editor-ui/src/stores/credentials.store.ts
  packages/editor-ui/src/stores/workflows.ee.store.ts
  packages/editor-ui/src/views/NodeView.vue
  packages/editor-ui/src/views/SetupWorkflowFromTemplateView/__tests__/setupTemplate.store.testData.ts
  packages/workflow/src/Interfaces.ts
Labels: ui, n8n team

#8877 feat(core): Update some packages to address CVE-2022-29622 (no-changelog)
  package.json
  packages/@n8n/nodes-langchain/package.json
  packages/cli/package.json
  packages/cli/test/integration/ldap/ldap.api.test.ts
  pnpm-lock.yaml
Labels: core, n8n team

#8869 feat(editor): Help users discover expressions when using drag n drop
  cypress/e2e/14-mapping.cy.ts
  cypress/e2e/16-form-trigger-node.cy.ts
  cypress/e2e/16-webhook-node.cy.ts
  cypress/e2e/24-ndv-paired-item.cy.ts
  cypress/pages/ndv.ts
  packages/design-system/src/css/_tokens.dark.scss
  packages/editor-ui/public/static/json-mapping-gif.gif
  packages/editor-ui/public/static/schema-mapping-gif.gif
  packages/editor-ui/src/Interface.ts
  packages/editor-ui/src/components/AssignmentCollection/Assignment.vue
  packages/editor-ui/src/components/ExpressionParameterInput.vue
  packages/editor-ui/src/components/InlineExpressionEditor/InlineExpressionEditorInput.vue
  packages/editor-ui/src/components/InlineExpressionEditor/InlineExpressionEditorOutput.vue
  packages/editor-ui/src/components/InlineExpressionEditor/InlineExpressionTip.vue
  packages/editor-ui/src/components/ParameterInput.vue
  packages/editor-ui/src/components/ParameterInputFull.vue
  packages/editor-ui/src/components/RunDataJson.vue
  packages/editor-ui/src/components/RunDataSchema.vue
  packages/editor-ui/src/components/RunDataSchemaItem.vue
  packages/editor-ui/src/components/RunDataTable.vue
  packages/editor-ui/src/constants.ts
  packages/editor-ui/src/mixins/completionManager.ts
  packages/editor-ui/src/plugins/codemirror/completions/__tests__/completions.test.ts
  packages/editor-ui/src/plugins/codemirror/completions/datatype.completions.ts
  packages/editor-ui/src/plugins/codemirror/completions/types.ts
  packages/editor-ui/src/plugins/codemirror/completions/utils.ts
  packages/editor-ui/src/plugins/i18n/locales/en.json
  packages/editor-ui/src/stores/ndv.store.ts
Labels: ui, n8n team

#8860 fix(Notion Node): Regex for block id
  packages/nodes-base/nodes/Notion/Notion.node.ts
  packages/nodes-base/nodes/Notion/shared/GenericFunctions.ts
  packages/nodes-base/nodes/Notion/shared/descriptions/BlockDescription.ts
  packages/nodes-base/nodes/Notion/v2/NotionV2.node.ts
  packages/nodes-base/nodes/Notion/v2/VersionDescription.ts
Labels: n8n team, node/issue

#8805 feat: Add AI Error Debugging using OpenAI
  packages/cli/package.json
  packages/cli/src/Server.ts
  packages/cli/src/config/schema.ts
  packages/cli/src/controllers/ai.controller.ts
  packages/cli/src/errors/response-errors/failed-dependency.error.ts
  packages/cli/src/requests.ts
  packages/cli/src/services/ai.service.ts
  packages/cli/src/services/ai/prompts/debugError.ts
  packages/cli/src/services/ai/providers/openai.ts
  packages/cli/src/services/ai/providers/unknown.ts
  packages/cli/src/services/ai/utils/summarizeNodeTypeProperties.ts
  packages/cli/src/services/frontend.service.ts
  packages/cli/src/types/ai.types.ts
  packages/cli/test/unit/controllers/ai.controller.test.ts
  packages/cli/test/unit/services/ai.service.test.ts
  packages/cli/test/unit/services/ai/utils/summarizeNodeTypeProperties.test.ts
  packages/editor-ui/src/api/ai.ts
  packages/editor-ui/src/components/Error/NodeErrorView.vue
  packages/editor-ui/src/components/Feedback.spec.ts
  packages/editor-ui/src/components/Feedback.vue
  packages/editor-ui/src/plugins/i18n/locales/en.json
  packages/editor-ui/src/plugins/icons/index.ts
  packages/editor-ui/src/stores/ai.store.spec.ts
  packages/editor-ui/src/stores/ai.store.ts
  packages/workflow/src/Interfaces.ts
  pnpm-lock.yaml
Labels: core, ui, n8n team

#8882 feat(core): Update `ws` and `handlebars` to match langchain peer-dependencies (no-changelog)
  packages/cli/package.json
  pnpm-lock.yaml
Labels: core, n8n team

#8881 fix(core): Update xml2js to address CVE-2023-0842 (no-changelog)
  package.json
  packages/@n8n/nodes-langchain/package.json
  packages/cli/package.json
  packages/core/package.json
  packages/nodes-base/package.json
  packages/workflow/package.json
  pnpm-lock.yaml
Labels: core, n8n team

#8875 fix: Chat Trigger exclude summarization node from valid ai nodes
  packages/editor-ui/src/components/WorkflowLMChat.vue
  packages/editor-ui/src/components/__tests__/WorkflowLMChatModal.test.ts
  packages/editor-ui/src/constants.ts
Labels: n8n team, node/issue

#8878 fix: Validate custom tool names for forbidden chars
  cypress/e2e/5-ndv.cy.ts
  packages/@n8n/nodes-langchain/nodes/tools/ToolCode/ToolCode.node.ts
  packages/@n8n/nodes-langchain/nodes/tools/ToolWorkflow/ToolWorkflow.node.ts
  packages/workflow/src/Interfaces.ts
  packages/workflow/src/TypeValidation.ts
Labels: core, n8n team

#8794 refactor(editor): Port more components over to composition API (no-changelog)
  packages/design-system/src/components/N8nActionBox/ActionBox.vue
  packages/design-system/src/components/N8nActionBox/__tests__/__snapshots__/ActionBox.spec.ts.snap
  packages/design-system/src/components/N8nActionDropdown/ActionDropdown.vue
  packages/design-system/src/components/N8nActionToggle/ActionToggle.vue
  packages/design-system/src/components/N8nAlert/Alert.vue
  packages/design-system/src/components/N8nAvatar/Avatar.vue
  packages/design-system/src/components/N8nBadge/Badge.vue
  packages/design-system/src/components/N8nButton/Button.vue
  packages/design-system/src/components/N8nCallout/Callout.vue
  packages/design-system/src/components/N8nCallout/index.ts
  packages/design-system/src/components/N8nCard/Card.vue
  packages/design-system/src/components/N8nCheckbox/Checkbox.vue
  packages/design-system/src/components/N8nColorPicker/ColorPicker.vue
  packages/design-system/src/components/N8nDatatable/Datatable.vue
  packages/design-system/src/components/N8nDatatable/__tests__/__snapshots__/Datatable.spec.ts.snap
  packages/design-system/src/components/N8nFormBox/FormBox.vue
  packages/design-system/src/components/N8nFormInput/FormInput.vue
  packages/design-system/src/components/N8nHeading/Heading.vue
  packages/design-system/src/components/N8nIcon/Icon.vue
  packages/design-system/src/components/N8nIconButton/IconButton.vue
  packages/design-system/src/components/N8nInfoAccordion/InfoAccordion.vue
  packages/design-system/src/components/N8nInfoTip/InfoTip.vue
  packages/design-system/src/components/N8nInput/Input.vue
  packages/design-system/src/components/N8nInputLabel/InputLabel.vue
  packages/design-system/src/components/N8nLink/Link.vue
  packages/design-system/src/components/N8nLoading/Loading.vue
  packages/design-system/src/components/N8nMarkdown/Markdown.vue
  packages/design-system/src/components/N8nMenu/Menu.vue
  packages/design-system/src/components/N8nMenuItem/MenuItem.vue
  packages/design-system/src/components/N8nNodeIcon/NodeIcon.vue
  packages/design-system/src/components/N8nPagination/Pagination.vue
  packages/design-system/src/components/N8nRoute/Route.vue
  packages/design-system/src/components/N8nRoute/index.ts
  packages/design-system/src/components/N8nSpinner/Spinner.vue
  packages/design-system/src/components/N8nSticky/Sticky.vue
  packages/design-system/src/components/N8nTag/Tag.vue
  packages/design-system/src/components/N8nTags/Tags.vue
  packages/design-system/src/components/N8nText/Text.vue
  packages/design-system/src/components/N8nUserInfo/UserInfo.vue
  packages/design-system/src/components/N8nUsersList/UsersList.vue
  packages/design-system/src/components/utils/helpers.ts
  packages/design-system/src/composables/useDeviceSupport.test.ts
  packages/design-system/src/mixins/locale.ts
  packages/design-system/src/shims-markdown-it.d.ts
  packages/design-system/src/types/button.ts
  packages/design-system/src/types/icon.ts
  packages/design-system/src/types/text.ts
  packages/design-system/tsconfig.json
Labels: ui, n8n team

#8883 fix(editor): Add proper scroll to Environments push modal
  packages/editor-ui/src/components/SourceControlPushModal.ee.vue
Labels: ui, n8n team

#8722 feat(core): Add support for SQLite connection pooling
  .github/workflows/ci-postgres-mysql.yml
  packages/@n8n/nodes-langchain/package.json
  packages/cli/package.json
  packages/cli/src/config/schema.ts
  packages/cli/src/databases/config.ts
  pnpm-lock.yaml
Labels: core, n8n team

#8890 feat(editor): Add simple project deletion
  packages/editor-ui/src/features/projects/components/ProjectSettings.vue
  packages/editor-ui/src/features/projects/components/__tests__/ProjectSettings.test.ts
  packages/editor-ui/src/features/projects/projects.api.ts
  packages/editor-ui/src/features/projects/projects.store.ts
  packages/editor-ui/src/plugins/i18n/locales/en.json
Labels: ui, n8n team

#8589 refactor(core): Ensure runtime checks rely on roles and scopes
  packages/cli/src/ActiveWebhooks.ts
  packages/cli/src/ActiveWorkflowRunner.ts
  packages/cli/src/Interfaces.ts
  packages/cli/src/UserManagement/PermissionChecker.ts
  packages/cli/src/WaitTracker.ts
  packages/cli/src/WaitingWebhooks.ts
  packages/cli/src/WebhookHelpers.ts
  packages/cli/src/WorkflowExecuteAdditionalData.ts
  packages/cli/src/WorkflowRunner.ts
  packages/cli/src/commands/worker.ts
  packages/cli/src/databases/repositories/sharedCredentials.repository.ts
  packages/cli/src/databases/repositories/sharedWorkflow.repository.ts
  packages/cli/src/jest.d.ts
  packages/cli/src/services/events.service.ts
  packages/cli/src/services/ownership.service.ts
  packages/cli/src/services/project.service.ts
  packages/cli/src/services/role.service.ts
  packages/cli/src/workflows/workflow.request.ts
  packages/cli/src/workflows/workflowExecution.service.ts
  packages/cli/src/workflows/workflows.controller.ts
  packages/cli/test/extend-expect.ts
  packages/cli/test/integration/PermissionChecker.test.ts
  packages/cli/test/integration/database/repositories/project.repository.test.ts
  packages/cli/test/integration/project.service.integration.test.ts
  packages/cli/test/integration/shared/db/projects.ts
  packages/cli/test/integration/shared/testDb.ts
  packages/cli/test/integration/workflows/workflows.controller.test.ts
  packages/cli/test/unit/PermissionChecker.test.ts
  packages/cli/test/unit/services/events.service.test.ts
  packages/cli/test/unit/services/ownership.service.test.ts
  packages/editor-ui/src/stores/workflows.store.ts
  packages/workflow/src/Interfaces.ts
Labels: core, n8n team, feature/rbac

#8892 fix(editor): Fix typechecking with vue-tsc 2.x (no-changelog)
  package.json
  packages/@n8n/chat/package.json
  packages/design-system/package.json
  packages/editor-ui/package.json
  patches/vite-plugin-checker@0.6.4.patch
  pnpm-lock.yaml
Labels: ui, n8n team

#8891 fix(editor): Fix source control docs link in add workflow button tooltip
  packages/editor-ui/src/plugins/i18n/locales/en.json
  packages/editor-ui/src/views/WorkflowsView.vue
Labels: ui, n8n team

#8900 fix(editor): Improve expression editor performance by removing watcher
  packages/editor-ui/src/components/HtmlEditor/HtmlEditor.vue
  packages/editor-ui/src/components/InlineExpressionEditor/InlineExpressionEditorInput.vue
  packages/editor-ui/src/components/SqlEditor/SqlEditor.vue
Labels: ui, n8n team

#8886 feat(core): Make sure that `SharedWorkflow.userId` is not used anymore
  packages/cli/src/ActiveWebhooks.ts
  packages/cli/src/ActiveWorkflowRunner.ts
  packages/cli/src/Ldap/helpers.ts
  packages/cli/src/PublicApi/v1/handlers/executions/executions.handler.ts
  packages/cli/src/PublicApi/v1/handlers/workflows/workflows.handler.ts
  packages/cli/src/PublicApi/v1/handlers/workflows/workflows.service.ts
  packages/cli/src/WebhookHelpers.ts
  packages/cli/src/commands/user-management/reset.ts
  packages/cli/src/controllers/users.controller.ts
  packages/cli/src/controllers/workflowStatistics.controller.ts
  packages/cli/src/credentials/credentials.service.ts
  packages/cli/src/databases/entities/SharedWorkflow.ts
  packages/cli/src/databases/migrations/common/1705928727784-CreateProject.ts
  packages/cli/src/databases/repositories/projectRelation.repository.ts
  packages/cli/src/databases/repositories/sharedCredentials.repository.ts
  packages/cli/src/databases/repositories/sharedWorkflow.repository.ts
  packages/cli/src/databases/repositories/workflow.repository.ts
  packages/cli/src/databases/repositories/workflowStatistics.repository.ts
  packages/cli/src/environments/sourceControl/sourceControlExport.service.ee.ts
  packages/cli/src/environments/sourceControl/sourceControlImport.service.ee.ts
  packages/cli/src/services/activeWorkflows.service.ts
  packages/cli/src/services/import.service.ts
  packages/cli/src/services/project.service.ts
  packages/cli/src/services/userOnboarding.service.ts
  packages/cli/src/workflows/workflow.service.ee.ts
  packages/cli/src/workflows/workflow.service.ts
  packages/cli/src/workflows/workflowHistory/workflowHistory.service.ee.ts
  packages/cli/src/workflows/workflows.controller.ts
  packages/cli/test/integration/PermissionChecker.test.ts
  packages/cli/test/integration/import.service.test.ts
  packages/cli/test/integration/publicApi/workflows.test.ts
  packages/cli/test/integration/shared/db/users.ts
  packages/cli/test/integration/shared/db/workflows.ts
  packages/cli/test/integration/users.api.test.ts
  packages/cli/test/integration/workflows/workflow.service.ee.test.ts
  packages/cli/test/integration/workflows/workflows.controller.ee.test.ts
  packages/cli/test/integration/workflows/workflows.controller.test.ts
  packages/cli/test/unit/services/activeWorkflows.service.test.ts
  packages/cli/test/unit/services/ownership.service.test.ts
  pnpm-lock.yaml
Labels: core, n8n team

#8870 feat(editor): Setup Chromatic for design-system (no-changelog)
  .github/workflows/chromatic.yml
  .gitignore
  packages/@n8n/storybook/main.ts
  packages/@n8n/storybook/package.json
  packages/design-system/chromatic.config.json
  packages/design-system/package.json
  pnpm-lock.yaml
Labels: ui, n8n team

#8902 fix(core): Update `follow-redirects` to address CVE-2024-28849
  pnpm-lock.yaml
Labels: core, n8n team

#8894 feat(editor): Refactor expression editors and mixins to composition API
  cypress/e2e/14-data-transformation-expressions.cy.ts
  cypress/pages/ndv.ts
  packages/editor-ui/src/components/ExpressionEditorModal/ExpressionEditorModalInput.vue
  packages/editor-ui/src/components/ExpressionParameterInput.vue
  packages/editor-ui/src/components/HtmlEditor/HtmlEditor.vue
  packages/editor-ui/src/components/InlineExpressionEditor/InlineExpressionEditorInput.vue
  packages/editor-ui/src/components/ParameterInput.vue
  packages/editor-ui/src/components/SqlEditor/SqlEditor.vue
  packages/editor-ui/src/components/__tests__/ExpressionEditorModalInput.test.ts
  packages/editor-ui/src/components/__tests__/ExpressionParameterInput.test.ts
  packages/editor-ui/src/components/__tests__/HtmlEditor.test.ts
  packages/editor-ui/src/components/__tests__/SQLEditor.test.ts
  packages/editor-ui/src/composables/__tests__/useAutocompleteTelemetry.test.ts
  packages/editor-ui/src/composables/__tests__/useExpressionEditor.test.ts
  packages/editor-ui/src/composables/useAutocompleteTelemetry.ts
  packages/editor-ui/src/composables/useExpressionEditor.ts
  packages/editor-ui/src/mixins/completionManager.ts
  packages/editor-ui/src/mixins/expressionManager.ts
  packages/editor-ui/src/utils/expressions.ts
Labels: ui, n8n team

#8913 fix(editor): Fix an issue with an empty chat response if not in `output` property
  packages/@n8n/chat/src/plugins/chat.ts
  packages/@n8n/chat/src/types/webhook.ts
Labels: n8n team

#8888 fix(editor): Remove `isOwner` from IUser interface
  packages/editor-ui/src/Interface.ts
  packages/editor-ui/src/__tests__/permissions.spec.ts
  packages/editor-ui/src/__tests__/server/factories/user.ts
  packages/editor-ui/src/api/users.ts
  packages/editor-ui/src/api/workflow-webhooks.ts
  packages/editor-ui/src/components/InviteUsersModal.vue
  packages/editor-ui/src/components/MainHeader/CollaborationPane.vue
  packages/editor-ui/src/components/__tests__/BannersStack.test.ts
  packages/editor-ui/src/components/__tests__/CollaborationPane.test.ts
  packages/editor-ui/src/components/__tests__/PersonalizationModal.spec.ts
  packages/editor-ui/src/components/banners/__tests__/V1Banner.spec.ts
  packages/editor-ui/src/constants.ts
  packages/editor-ui/src/permissions.ts
  packages/editor-ui/src/rbac/checks/__tests__/hasRole.test.ts
  packages/editor-ui/src/rbac/checks/hasRole.ts
  packages/editor-ui/src/rbac/middleware/__tests__/role.test.ts
  packages/editor-ui/src/stores/__tests__/ui.test.ts
  packages/editor-ui/src/stores/cloudPlan.store.ts
  packages/editor-ui/src/stores/ui.store.ts
  packages/editor-ui/src/stores/users.store.ts
  packages/editor-ui/src/utils/userUtils.ts
  packages/editor-ui/src/views/SettingsUsageAndPlan.vue
  packages/editor-ui/src/views/SettingsUsersView.vue
  packages/editor-ui/src/views/__tests__/SettingsPersonalView.test.ts
Labels: ui, n8n team

#8906 feat(editor): Block the frontend when trying to access n8n from another host over http
  packages/cli/src/services/frontend.service.ts
  packages/editor-ui/src/__tests__/defaults.ts
  packages/editor-ui/src/__tests__/server/endpoints/settings.ts
  packages/editor-ui/src/__tests__/utils.ts
  packages/editor-ui/src/constants.ts
  packages/editor-ui/src/stores/__tests__/posthog.test.ts
  packages/editor-ui/src/stores/settings.store.ts
  packages/workflow/src/Interfaces.ts
Labels: core, ui, n8n team

#8910 fix(core): Improve handling of invalid objects in `cleanupParameterData` (no-chanhelog)
  packages/core/src/NodeExecuteFunctions.ts
  packages/core/test/NodeExecuteFunctions.test.ts
Labels: core, n8n team

#8911 fix(editor): Fix a link routing regression in N8nRoute, and add tests (no-changelog)
  packages/design-system/src/components/N8nRoute/Route.vue
  packages/design-system/src/components/N8nRoute/__tests__/Route.spec.ts
  packages/design-system/src/components/N8nRoute/__tests__/__snapshots__/Route.spec.ts.snap
Labels: ui, n8n team

#8918 feat(editor): Release `@n8n/chat@0.9.1`
  packages/@n8n/chat/package.json
  packages/@n8n/storybook/package.json
Labels: n8n team

#8916 fix(Cohere Model Node): Fix issue with credential test
  packages/@n8n/nodes-langchain/credentials/CohereApi.credentials.ts
Labels: n8n team

#8742 feat: Add Onedrive Trigger Node
  packages/nodes-base/nodes/Microsoft/OneDrive/GenericFunctions.ts
  packages/nodes-base/nodes/Microsoft/OneDrive/MicrosoftOneDriveTrigger.node.json
  packages/nodes-base/nodes/Microsoft/OneDrive/MicrosoftOneDriveTrigger.node.ts
  packages/nodes-base/nodes/Microsoft/OneDrive/TriggerDescription.ts
  packages/nodes-base/nodes/Microsoft/OneDrive/constants.ts
  packages/nodes-base/package.json
Labels: node/improvement, node/new, community

#8904 feat(core): Implement project deletion
  packages/cli/src/ActiveWorkflowRunner.ts
  packages/cli/src/controllers/project.controller.ts
  packages/cli/src/credentials/credentials.service.ts
  packages/cli/src/databases/repositories/sharedWorkflow.repository.ts
  packages/cli/src/permissions/project-roles.ts
  packages/cli/src/requests.ts
  packages/cli/src/services/project.service.ts
  packages/cli/src/workflows/workflow.service.ts
  packages/cli/test/integration/credentials.test.ts
  packages/cli/test/integration/project.api.test.ts
  packages/cli/test/integration/shared/db/workflows.ts
  packages/cli/test/integration/workflows/workflow.service.test.ts
  packages/cli/test/integration/workflows/workflows.controller.test.ts
Labels: core, n8n team

#8843 feat(editor): Add type information to autocomplete dropdown
  packages/editor-ui/src/plugins/codemirror/completions/__tests__/completions.test.ts
  packages/editor-ui/src/plugins/codemirror/completions/datatype.completions.ts
  packages/editor-ui/src/styles/plugins/_codemirror.scss
Labels: ui, n8n team

#8923 fix(editor): Fix design system component props
  packages/design-system/src/components/N8nActionDropdown/ActionDropdown.vue
  packages/design-system/src/components/N8nActionDropdown/__tests__/__snapshots__/ActionDropdown.spec.ts.snap
  packages/design-system/src/components/N8nAvatar/Avatar.vue
  packages/design-system/src/components/N8nBadge/Badge.vue
Labels: ui, n8n team

#8845 feat(editor): Add missing extension methods for expressions
  packages/editor-ui/src/Interface.ts
  packages/editor-ui/src/components/ParameterInputFull.vue
  packages/editor-ui/src/composables/useWorkflowHelpers.ts
  packages/editor-ui/src/plugins/codemirror/completions/__tests__/completions.test.ts
  packages/editor-ui/src/plugins/codemirror/completions/constants.ts
  packages/editor-ui/src/plugins/codemirror/completions/datatype.completions.ts
  packages/editor-ui/src/plugins/codemirror/completions/dollar.completions.ts
  packages/editor-ui/src/plugins/codemirror/completions/types.ts
  packages/editor-ui/src/plugins/codemirror/completions/utils.ts
  packages/editor-ui/src/plugins/i18n/index.ts
  packages/editor-ui/src/plugins/i18n/locales/en.json
  packages/editor-ui/src/stores/ndv.store.ts
  packages/workflow/src/Extensions/ArrayExtensions.ts
  packages/workflow/src/Extensions/BooleanExtensions.ts
  packages/workflow/src/Extensions/DateExtensions.ts
  packages/workflow/src/Extensions/ExpressionExtension.ts
  packages/workflow/src/Extensions/NumberExtensions.ts
  packages/workflow/src/Extensions/ObjectExtensions.ts
  packages/workflow/src/Extensions/StringExtensions.ts
  packages/workflow/src/NativeMethods/Boolean.methods.ts
  packages/workflow/src/NativeMethods/Number.methods.ts
  packages/workflow/src/NativeMethods/index.ts
  packages/workflow/test/ExpressionExtensions/ArrayExtensions.test.ts
  packages/workflow/test/ExpressionExtensions/BooleanExtensions.test.ts
  packages/workflow/test/ExpressionExtensions/DateExtensions.test.ts
  packages/workflow/test/ExpressionExtensions/NumberExtensions.test.ts
  packages/workflow/test/ExpressionExtensions/ObjectExtensions.test.ts
  packages/workflow/test/ExpressionExtensions/StringExtensions.test.ts
Labels: core, ui, n8n team

#8928 fix(core): Work around flaky unit tests when using sqlite with a connection pool
  packages/cli/src/InternalHooks.ts
Labels: core, n8n team

#8924 feat(core): Allow migrating workflows and credentials when deleting projects
  packages/cli/src/controllers/project.controller.ts
  packages/cli/src/credentials/credentials.service.ts
  packages/cli/src/databases/repositories/sharedCredentials.repository.ts
  packages/cli/src/databases/repositories/sharedWorkflow.repository.ts
  packages/cli/src/requests.ts
  packages/cli/src/services/project.service.ts
  packages/cli/src/workflows/workflow.service.ts
  packages/cli/src/workflows/workflows.controller.ts
  packages/cli/test/integration/project.api.test.ts
  packages/cli/test/integration/services/project.service.test.ts
Labels: core, n8n team

#8789 fix(editor): Fix opening of chat window when executing a child node
  cypress/composables/modals/chat-modal.ts
  cypress/e2e/30-langchain.cy.ts
  packages/editor-ui/src/components/NodeExecuteButton.vue
  packages/editor-ui/src/components/WorkflowLMChat.vue
  packages/editor-ui/src/components/__tests__/WorkflowLMChatModal.test.ts
  packages/editor-ui/src/composables/usePinnedData.ts
  packages/editor-ui/src/composables/useRunWorkflow.ts
  packages/editor-ui/src/n8n-theme-variables.scss
  packages/editor-ui/src/n8n-theme.scss
  packages/editor-ui/src/plugins/i18n/locales/en.json
  packages/editor-ui/src/stores/workflows.store.ts
Labels: ui, n8n team

#8930 docs: Fix the Microsoft OneDrive Trigger docs link
  packages/nodes-base/nodes/Microsoft/OneDrive/MicrosoftOneDriveTrigger.node.json
Labels: node/improvement, n8n team

#8940 fix(MySQL Node): Set paired items correctly in single query batch mode
  packages/nodes-base/nodes/MySql/test/v2/runQueries.test.ts
  packages/nodes-base/nodes/MySql/v2/helpers/utils.ts
Labels: node/improvement, n8n team

#8938 test(core): Add test that makes sure the api returns a 403 when trying to delete a project that does not exist
  packages/cli/test/integration/project.api.test.ts
Labels: core, n8n team

#8941 fix(core): Ensure the generic OAuth2 API credential uses the OAuth2 credential test
  packages/cli/src/services/credentials-tester.service.ts
  packages/cli/test/unit/credentials-tester.unit.test.ts
Labels: core, n8n team

#8926 fix(editor): Decouple project sharing component from project type
  packages/editor-ui/src/components/CredentialEdit/CredentialSharing.ee.vue
  packages/editor-ui/src/components/WorkflowShareModal.ee.vue
  packages/editor-ui/src/features/projects/components/ProjectSharing.vue
  packages/editor-ui/src/features/projects/components/__tests__/ProjectSharing.test.ts
  packages/editor-ui/src/features/projects/projects.store.ts
Labels: ui, n8n team

#8765 fix: Overhaul expression error messages related to paired item
  packages/editor-ui/src/components/Error/NodeErrorView.vue
  packages/editor-ui/src/constants.ts
  packages/editor-ui/src/plugins/i18n/locales/en.json
  packages/workflow/src/WorkflowDataProxy.ts
  packages/workflow/src/errors/expression.error.ts
  packages/workflow/test/WorkflowDataProxy.test.ts
Labels: core, ui, n8n team

#8937 fix(editor): Add projects select to project delete dialog
  packages/editor-ui/src/features/projects/components/ProjectDeleteDialog.vue
  packages/editor-ui/src/features/projects/components/ProjectSettings.vue
  packages/editor-ui/src/features/projects/components/ProjectSharing.vue
  packages/editor-ui/src/features/projects/components/__tests__/ProjectSettings.test.ts
  packages/editor-ui/src/features/projects/projects.api.ts
  packages/editor-ui/src/features/projects/projects.store.ts
  packages/editor-ui/src/plugins/i18n/locales/en.json
Labels: ui, n8n team

#8950 fix(editor): Fix error message color in output panel for dark mode (no-changelog)
  packages/design-system/src/css/_tokens.dark.scss
  packages/design-system/src/css/_tokens.scss
  packages/editor-ui/src/components/Error/NodeErrorView.vue
Labels: ui, n8n team

#8944 docs(Microsoft Outlook Trigger Node): Copy tweak (no-changelog)
  packages/nodes-base/nodes/Microsoft/Outlook/MicrosoftOutlookTrigger.node.ts
Labels: node/improvement, n8n team

#8942 feat: Fetch user cloud role and pass it on in website links
  cypress/e2e/29-templates.cy.ts
  packages/editor-ui/src/Interface.ts
  packages/editor-ui/src/components/MainSidebar.vue
  packages/editor-ui/src/constants.ts
  packages/editor-ui/src/plugins/i18n/locales/en.json
  packages/editor-ui/src/plugins/icons/index.ts
  packages/editor-ui/src/stores/templates.store.ts
  packages/editor-ui/src/views/WorkflowsView.vue
Labels: ui, n8n team

#8953 fix(Anthropic Chat Model Node): Fix detection of chat models in docker build & add support Claude Haiku
  packages/@n8n/nodes-langchain/nodes/llms/LMChatAnthropic/LmChatAnthropic.node.ts
  packages/@n8n/nodes-langchain/utils/helpers.ts
Labels: n8n team

#8933 fix(editor): Use bracket notation for all invalid identifiers in expressions
  packages/editor-ui/src/utils/__tests__/mappingUtils.test.ts
  packages/editor-ui/src/utils/mappingUtils.ts
Labels: ui, n8n team

#8959 fix(core): Stringify all Luxon DateTimes in cleanupParameterData
  packages/core/src/NodeExecuteFunctions.ts
  packages/core/test/NodeExecuteFunctions.test.ts
Labels: core, n8n team

#8949 feat: Add includeScopes query param to credentials, workflows, and projects
  packages/@n8n/permissions/src/combineScopes.ts
  packages/@n8n/permissions/src/hasScope.ts
  packages/@n8n/permissions/src/index.ts
  packages/cli/src/controllers/project.controller.ts
  packages/cli/src/controllers/role.controller.ts
  packages/cli/src/credentials/credentials.controller.ts
  packages/cli/src/credentials/credentials.service.ts
  packages/cli/src/requests.ts
  packages/cli/src/services/ownership.service.ts
  packages/cli/src/services/role.service.ts
  packages/cli/src/workflows/workflow.request.ts
  packages/cli/src/workflows/workflow.service.ts
  packages/cli/src/workflows/workflows.controller.ts
  packages/cli/test/integration/credentials.test.ts
  packages/cli/test/integration/role.api.test.ts
  packages/cli/test/integration/shared/db/workflows.ts
  packages/cli/test/integration/workflows/workflows.controller.test.ts
Labels: core, n8n team, feature/rbac

#8958 feat(core): Refactor user deletion to support projects
  packages/cli/src/controllers/users.controller.ts
  packages/cli/src/databases/repositories/sharedCredentials.repository.ts
  packages/cli/src/databases/repositories/sharedWorkflow.repository.ts
  packages/cli/src/services/project.service.ts
  packages/cli/test/integration/shared/db/credentials.ts
  packages/cli/test/integration/users.api.test.ts
Labels: core, n8n team

#8943 refactor(core): Unify `failed` and `error` execution status (no-changelog)
  packages/cli/src/WorkflowExecuteAdditionalData.ts
  packages/cli/src/WorkflowHelpers.ts
  packages/cli/src/databases/migrations/common/1711018413374-RemoveFailedExecutionStatus.ts
  packages/cli/src/databases/migrations/mysqldb/index.ts
  packages/cli/src/databases/migrations/postgresdb/index.ts
  packages/cli/src/databases/migrations/sqlite/index.ts
  packages/cli/src/databases/repositories/execution.repository.ts
  packages/cli/src/eventbus/executionDataRecovery.service.ts
  packages/cli/src/executionLifecycleHooks/shared/sharedHookFunctions.ts
  packages/cli/src/executions/executionHelpers.ts
  packages/cli/test/integration/pruning.service.test.ts
  packages/cli/test/integration/shared/db/executions.ts
  packages/core/src/NodeExecuteFunctions.ts
  packages/editor-ui/src/components/ExecutionsList.vue
  packages/editor-ui/src/components/ExecutionsView/__tests__/ExecutionPreview.test.ts
  packages/editor-ui/src/components/Node.vue
  packages/editor-ui/src/components/__tests__/ExecutionsList.test.ts
  packages/editor-ui/src/mixins/executionsHelpers.ts
  packages/editor-ui/src/utils/executionUtils.ts
  packages/workflow/src/ExecutionStatus.ts
Labels: core, ui, n8n team

#8947 refactor(core): Remove dead utils (no-changelog)
  packages/cli/src/utils.ts
  packages/core/src/utils.ts
  packages/core/test/utils.test.ts
Labels: core, n8n team

#8946 test(core): Improve coverage for `ActiveWorkflowRunner` (no-changelog)
  packages/cli/src/ActiveWorkflowRunner.ts
  packages/cli/test/integration/ActiveWorkflowRunner.test.ts
  packages/cli/test/integration/active-workflow-runner.test.ts
  packages/cli/test/integration/shared/utils/index.ts
Labels: core, n8n team

#8945 fix(editor): Nodes connectors improvements
  packages/design-system/src/css/_tokens.dark.scss
  packages/design-system/src/css/_tokens.scss
  packages/editor-ui/src/components/Node.vue
  packages/editor-ui/src/mixins/nodeBase.ts
  packages/editor-ui/src/plugins/jsplumb/N8nPlusEndpointType.ts
Labels: ui, n8n team

#8968 fix(Pinecone Vector Store Node): Fix vector store nodes execution issue
  packages/@n8n/nodes-langchain/utils/helpers.ts
Labels: n8n team

#8971 fix(editor): Fix accidental IDE code addition
  packages/editor-ui/src/views/SettingsUsersView.vue
Labels: ui, n8n team

#8931 feat(editor): Show tip when user can type dot after an expression
  cypress/e2e/14-mapping.cy.ts
  packages/editor-ui/src/Interface.ts
  packages/editor-ui/src/components/ExpressionParameterInput.vue
  packages/editor-ui/src/components/InlineExpressionEditor/InlineExpressionEditorInput.vue
  packages/editor-ui/src/components/InlineExpressionEditor/InlineExpressionEditorOutput.vue
  packages/editor-ui/src/components/InlineExpressionEditor/InlineExpressionTip.vue
  packages/editor-ui/src/components/InlineExpressionEditor/__tests__/InlineExpressionTip.test.ts
  packages/editor-ui/src/components/NodeExecuteButton.vue
  packages/editor-ui/src/components/ParameterInputFull.vue
  packages/editor-ui/src/components/RunDataJson.vue
  packages/editor-ui/src/components/RunDataSchema.vue
  packages/editor-ui/src/components/RunDataTable.vue
  packages/editor-ui/src/composables/useExpressionEditor.ts
  packages/editor-ui/src/plugins/codemirror/completions/datatype.completions.ts
  packages/editor-ui/src/plugins/codemirror/completions/utils.ts
  packages/editor-ui/src/plugins/i18n/locales/en.json
  packages/editor-ui/src/stores/ndv.store.ts
Labels: ui, n8n team

#8955 fix(core): Assign credential ownership correctly in source control import
  packages/cli/src/databases/repositories/sharedCredentials.repository.ts
  packages/cli/src/environments/sourceControl/sourceControlExport.service.ee.ts
  packages/cli/src/environments/sourceControl/sourceControlImport.service.ee.ts
  packages/cli/src/environments/sourceControl/types/exportableCredential.ts
  packages/cli/src/environments/sourceControl/types/sourceControlPullWorkFolder.ts
  packages/cli/test/integration/environments/source-control-import.service.test.ts
  packages/cli/test/integration/shared/db/users.ts
Labels: core, n8n team

#8976 fix(core): Add missing `nodeCause` to paired item error
  packages/workflow/src/WorkflowDataProxy.ts
Labels: core, n8n team

#8965 refactor(core): Store SSH key pair for source control in DB settings
  packages/cli/src/databases/migrations/common/1711390882123-MoveSshKeysToDatabase.ts
  packages/cli/src/databases/migrations/mysqldb/index.ts
  packages/cli/src/databases/migrations/postgresdb/index.ts
  packages/cli/src/databases/migrations/sqlite/index.ts
  packages/cli/src/environments/sourceControl/sourceControl.controller.ee.ts
  packages/cli/src/environments/sourceControl/sourceControl.service.ee.ts
  packages/cli/src/environments/sourceControl/sourceControlGit.service.ee.ts
  packages/cli/src/environments/sourceControl/sourceControlPreferences.service.ee.ts
Labels: core, n8n team

#8974 fix(editor): Load credentials after workflow is loaded
  packages/editor-ui/src/features/projects/projects.store.ts
  packages/editor-ui/src/views/NodeView.vue
Labels: ui, n8n team

#8980 fix(editor): Make inputs in the filter component regular inputs by default
  cypress/e2e/30-if-node.cy.ts
  packages/editor-ui/src/components/FilterConditions/FilterConditions.vue
  packages/editor-ui/src/components/FilterConditions/__tests__/FilterConditions.test.ts
Labels: ui, n8n team

#8964 fix(editor): Use projects instead of users in resource filter
  packages/editor-ui/src/components/forms/ResourceFiltersDropdown.vue
  packages/editor-ui/src/components/layouts/ResourcesListLayout.vue
  packages/editor-ui/src/features/projects/components/ProjectSharing.vue
  packages/editor-ui/src/features/projects/projects.store.ts
  packages/editor-ui/src/plugins/i18n/locales/en.json
  packages/editor-ui/src/views/CredentialsView.vue
  packages/editor-ui/src/views/WorkflowsView.vue
  packages/editor-ui/src/views/__tests__/WorkflowsView.test.ts
Labels: ui, n8n team

#8956 fix(editor): Transfer data to personal project instead of user when d…
  packages/editor-ui/src/__tests__/data/users.ts
  packages/editor-ui/src/__tests__/utils.ts
  packages/editor-ui/src/components/DeleteUserModal.vue
  packages/editor-ui/src/features/projects/components/__tests__/ProjectSettings.test.ts
  packages/editor-ui/src/features/projects/components/__tests__/ProjectSharing.test.ts
  packages/editor-ui/src/plugins/i18n/locales/en.json
  packages/editor-ui/src/views/SettingsUsersView.vue
  packages/editor-ui/src/views/__tests__/SettingsUsersView.test.ts
Labels: ui, n8n team

#8977 fix(editor): Add scopes to resources
  packages/editor-ui/src/Interface.ts
  packages/editor-ui/src/api/credentials.ts
  packages/editor-ui/src/api/workflows.ts
  packages/editor-ui/src/composables/useNodeHelpers.ts
  packages/editor-ui/src/features/projects/projects.api.ts
  packages/editor-ui/src/features/projects/projects.types.ts
  packages/editor-ui/src/permissions.ts
  packages/editor-ui/src/stores/credentials.store.ts
  packages/editor-ui/src/stores/rbac.store.ts
  packages/editor-ui/src/stores/users.store.ts
Labels: ui, n8n team

#8981 feat: Telemetry include basic llm optional promps, trigger on save workflow event
  packages/cli/src/InternalHooks.ts
  packages/workflow/src/Constants.ts
  packages/workflow/src/TelemetryHelpers.ts
Labels: n8n team

#8987 refactor: Merge tag n8n@1.34.2
  CHANGELOG.md
  packages/@n8n/chat/package.json
  packages/@n8n/nodes-langchain/package.json
  packages/cli/package.json
  packages/core/package.json
  packages/design-system/package.json
  packages/editor-ui/package.json
  packages/node-dev/package.json
  packages/nodes-base/package.json
  packages/workflow/package.json
Labels: core, ui, n8n team

#8978 feat(core): Create and keep names of personal projects up to date
  packages/cli/src/Ldap/helpers.ts
  packages/cli/src/Mfa/mfa.service.ts
  packages/cli/src/commands/mfa/disable.ts
  packages/cli/src/databases/config.ts
  packages/cli/src/databases/entities/Project.ts
  packages/cli/src/databases/entities/index.ts
  packages/cli/src/databases/migrations/common/1705928727784-CreateProject.ts
  packages/cli/src/databases/repositories/user.repository.ts
  packages/cli/src/services/user.service.ts
  packages/cli/test/integration/auth.api.test.ts
  packages/cli/test/integration/me.api.test.ts
  packages/cli/test/unit/Ldap/helpers.test.ts
  packages/cli/test/unit/services/user.service.test.ts
  packages/cli/test/unit/sso/saml/samlHelpers.test.ts
Labels: core, n8n team

#8889 feat(Webhook Node): Overhaul
  cypress/e2e/16-webhook-node.cy.ts
  packages/cli/src/AbstractServer.ts
  packages/cli/src/WebhookHelpers.ts
  packages/cli/src/errors/response-errors/webhook-not-found.error.ts
  packages/cli/src/services/test-webhook-registrations.service.ts
  packages/core/src/NodeExecuteFunctions.ts
  packages/nodes-base/credentials/icons/jwt.svg
  packages/nodes-base/credentials/jwtAuth.credentials.ts
  packages/nodes-base/nodes/RespondToWebhook/RespondToWebhook.node.ts
  packages/nodes-base/nodes/Webhook/Webhook.node.ts
  packages/nodes-base/nodes/Webhook/description.ts
  packages/nodes-base/nodes/Webhook/test/Webhook.test.ts
  packages/nodes-base/nodes/Webhook/utils.ts
  packages/nodes-base/package.json
  packages/workflow/src/Interfaces.ts
  packages/workflow/src/NodeHelpers.ts
  packages/workflow/src/Workflow.ts
Labels: node/improvement, n8n team

#8983 feat(core): Return all team projects if the user has global `project:read` permissions
  packages/cli/src/controllers/project.controller.ts
  packages/cli/src/requests.ts
  packages/cli/test/integration/project.api.test.ts
Labels: core, n8n team

#8989 fix(core): Fail correctly when trying to transfer resources to the user that is being deleted
  packages/cli/src/controllers/users.controller.ts
  packages/cli/test/integration/users.api.test.ts
Labels: core, n8n team

#8984 fix(editor): Make only projects scrollable in the sidebar
  packages/design-system/src/components/N8nMenu/Menu.vue
  packages/design-system/src/components/N8nMenuItem/MenuItem.vue
  packages/editor-ui/src/features/projects/components/ProjectNavigation.vue
Labels: ui, n8n team

#8992 fix: Get all parent nodes > useRunWorkflow (no-changelog)
  packages/editor-ui/src/composables/useRunWorkflow.ts
Labels: ui, n8n team

#8982 feat(core): Introduce AWS secrets manager as external secrets store
  packages/cli/package.json
  packages/cli/src/ExternalSecrets/ExternalSecretsManager.ee.ts
  packages/cli/src/ExternalSecrets/ExternalSecretsProviders.ee.ts
  packages/cli/src/ExternalSecrets/providers/aws-secrets/aws-secrets-client.ts
  packages/cli/src/ExternalSecrets/providers/aws-secrets/aws-secrets-manager.ts
  packages/cli/src/ExternalSecrets/providers/aws-secrets/types.ts
  packages/cli/src/Interfaces.ts
  packages/cli/src/SecretsHelpers.ts
  packages/cli/src/errors/unknown-auth-type.error.ts
  packages/core/src/Secrets.ts
  packages/editor-ui/src/assets/images/aws-secrets-manager.svg
  packages/editor-ui/src/components/ExternalSecretsProviderCard.ee.vue
  packages/editor-ui/src/components/ExternalSecretsProviderImage.ee.vue
  packages/workflow/src/Interfaces.ts
  pnpm-lock.yaml
Labels: core, ui, n8n team

#8998 fix: Front end fixes to permissions, project sharing, and layout
  packages/cli/src/controllers/project.controller.ts
  packages/cli/src/requests.ts
  packages/cli/src/services/role.service.ts
  packages/cli/test/integration/project.api.test.ts
  packages/editor-ui/src/features/projects/components/ProjectNavigation.vue
  packages/editor-ui/src/features/projects/components/ProjectTabs.vue
  packages/editor-ui/src/features/projects/components/__tests__/ProjectTabs.test.ts
  packages/editor-ui/src/features/projects/projects.store.ts
  packages/editor-ui/src/features/projects/projects.types.ts
  packages/editor-ui/src/permissions.ts
Labels: core, ui, n8n team

#8859 feat: Add Twilio Trigger Node
  packages/nodes-base/nodes/Twilio/GenericFunctions.ts
  packages/nodes-base/nodes/Twilio/TwilioTrigger.node.json
  packages/nodes-base/nodes/Twilio/TwilioTrigger.node.ts
  packages/nodes-base/package.json
Labels: node/improvement, node/new, community

#8996 fix(editor): UI enhancements and fixes for expression inputs
  packages/editor-ui/src/__tests__/setup.ts
  packages/editor-ui/src/components/AssignmentCollection/Assignment.vue
  packages/editor-ui/src/components/FilterConditions/Condition.vue
  packages/editor-ui/src/components/InlineExpressionEditor/InlineExpressionEditorOutput.vue
  packages/editor-ui/src/components/ParameterInputFull.vue
  packages/editor-ui/src/components/__tests__/ExpressionEditorModalInput.test.ts
  packages/editor-ui/src/components/__tests__/HtmlEditor.test.ts
  packages/editor-ui/src/composables/__tests__/useAutocompleteTelemetry.test.ts
  packages/editor-ui/src/composables/__tests__/useExpressionEditor.test.ts
  packages/editor-ui/src/composables/useExpressionEditor.ts
  packages/workflow/src/Extensions/StringExtensions.ts
  packages/workflow/test/ExpressionExtensions/StringExtensions.test.ts
Labels: core, ui, n8n team

#9002 fix(editor): Hover and active states not showing in execution list on dark mode
  packages/design-system/src/css/_tokens.dark.scss
  packages/design-system/src/css/_tokens.scss
  packages/editor-ui/src/components/ExecutionsView/ExecutionCard.vue
Labels: ui, n8n team
