Repository n8n-io/n8n, pull requests merged in 2024-06, with the labels that each got.

#9572 feat(editor): Clean up lead enrichment experiment (no-changelog)
  cypress/e2e/36-suggested-templates.cy.ts
  cypress/fixtures/Suggested_Templates.json
  cypress/pages/workflows.ts
  packages/design-system/src/components/N8nRecycleScroller/RecycleScroller.vue
  packages/design-system/src/components/N8nRecycleScroller/__tests__/__snapshots__/RecycleScroller.spec.ts.snap
  packages/editor-ui/src/Interface.ts
  packages/editor-ui/src/api/cloudPlans.ts
  packages/editor-ui/src/components/Modals.vue
  packages/editor-ui/src/components/SuggestedTemplates/SuggestedTemplatesPage.vue
  packages/editor-ui/src/components/SuggestedTemplates/SuggestedTemplatesPreviewModal.vue
  packages/editor-ui/src/components/SuggestedTemplates/SuggestedTemplatesSection.vue
  packages/editor-ui/src/components/layouts/ResourcesListLayout.vue
  packages/editor-ui/src/constants.ts
  packages/editor-ui/src/plugins/i18n/locales/en.json
  packages/editor-ui/src/stores/cloudPlan.store.ts
  packages/editor-ui/src/stores/ui.store.ts
  packages/editor-ui/src/views/WorkflowsView.vue
Labels: ui, n8n team

#9593 fix(core): Fix license autorenewal disabled warning
  packages/cli/src/License.ts
  packages/cli/src/commands/start.ts
Labels: core, n8n team

#9592 fix(editor): Fix ts and eslint errors in various components (no-changelog)
  packages/editor-ui/src/components/TagsContainer.vue
  packages/editor-ui/src/components/TagsDropdown.vue
  packages/editor-ui/src/components/TagsManager/TagsView/TagsView.vue
  packages/editor-ui/src/components/Telemetry.vue
  packages/editor-ui/src/components/TimeAgo.vue
  packages/editor-ui/src/components/TitledList.vue
Labels: ui, n8n team

#9585 fix: Fix TS issues in connectors (no-changelog)
  packages/editor-ui/src/plugins/connectors/N8nCustomConnector.ts
  packages/editor-ui/src/plugins/jsplumb/N8nAddInputEndpointRenderer.ts
  packages/editor-ui/src/plugins/jsplumb/N8nAddInputEndpointType.ts
  packages/editor-ui/src/plugins/jsplumb/N8nPlusEndpointType.ts
Labels: ui, n8n team

#9576 fix(editor): Fix most ts errors in credential components (no-changelog)
  packages/editor-ui/src/Interface.ts
  packages/editor-ui/src/components/CredentialCard.vue
  packages/editor-ui/src/components/CredentialEdit/CredentialEdit.vue
  packages/editor-ui/src/components/CredentialEdit/CredentialSharing.ee.vue
  packages/editor-ui/src/components/CredentialEdit/__tests__/OauthButton.test.ts
  packages/editor-ui/src/components/CredentialsSelect.vue
Labels: ui, n8n team

#9554 feat(HighLevel Node): Api v2 support, new node version
  packages/cli/src/constants.ts
  packages/cli/src/controllers/oauth/oAuth2Credential.controller.ts
  packages/nodes-base/credentials/HighLevelOAuth2Api.credentials.ts
  packages/nodes-base/credentials/OAuth2Api.credentials.ts
  packages/nodes-base/nodes/HighLevel/HighLevel.node.ts
  packages/nodes-base/nodes/HighLevel/v1/GenericFunctions.ts
  packages/nodes-base/nodes/HighLevel/v1/HighLevelV1.node.ts
  packages/nodes-base/nodes/HighLevel/v1/description/ContactDescription.ts
  packages/nodes-base/nodes/HighLevel/v1/description/OpportunityDescription.ts
  packages/nodes-base/nodes/HighLevel/v1/description/TaskDescription.ts
  packages/nodes-base/nodes/HighLevel/v2/GenericFunctions.ts
  packages/nodes-base/nodes/HighLevel/v2/HighLevelV2.node.ts
  packages/nodes-base/nodes/HighLevel/v2/description/ContactDescription.ts
  packages/nodes-base/nodes/HighLevel/v2/description/OpportunityDescription.ts
  packages/nodes-base/nodes/HighLevel/v2/description/TaskDescription.ts
Labels: node/improvement, n8n team, node/issue

#9591 fix: Do not show [object Object] in error message when validating type (no-changelog)
  packages/nodes-base/nodes/Set/v2/helpers/utils.ts
  packages/workflow/src/TypeValidation.ts
  packages/workflow/test/TypeValidation.test.ts
Labels: n8n team

#9522 feat(core): Allow customizing rate limits on a per-route basis, and add rate limiting to more endpoints
  packages/cli/src/controllers/auth.controller.ts
  packages/cli/src/controllers/invitation.controller.ts
  packages/cli/src/controllers/passwordReset.controller.ts
  packages/cli/src/decorators/Route.ts
  packages/cli/src/decorators/registerController.ts
  packages/cli/src/decorators/types.ts
  packages/cli/test/unit/decorators/registerController.test.ts
Labels: core, n8n team

#9583 refactor(editor): Fix typescript issues in composables and misc files (no-changelog)
  packages/editor-ui/src/Interface.ts
  packages/editor-ui/src/__tests__/defaults.ts
  packages/editor-ui/src/__tests__/server/endpoints/settings.ts
  packages/editor-ui/src/__tests__/server/endpoints/sourceControl.ts
  packages/editor-ui/src/__tests__/server/endpoints/sso.ts
  packages/editor-ui/src/__tests__/server/factories/tag.ts
  packages/editor-ui/src/__tests__/server/factories/workflow.ts
  packages/editor-ui/src/components/SettingsLogStreaming/EventDestinationCard.ee.vue
  packages/editor-ui/src/components/SettingsLogStreaming/EventSelection.ee.vue
  packages/editor-ui/src/components/VariableSelector.vue
  packages/editor-ui/src/components/VariablesRow.vue
  packages/editor-ui/src/components/WorkflowLMChat.vue
  packages/editor-ui/src/composables/__tests__/useHistoryHelper.test.ts
  packages/editor-ui/src/composables/__tests__/useUniqueNodeName.test.ts
  packages/editor-ui/src/composables/useHistoryHelper.ts
  packages/editor-ui/src/composables/useNodeHelpers.ts
  packages/editor-ui/src/composables/useRunWorkflow.test.ts
  packages/editor-ui/src/utils/apiUtils.ts
  packages/editor-ui/src/views/WorkflowsView.vue
Labels: ui, n8n team

#9577 fix(Code Node): Replace tab character with spaces in placeholder (no-changelog)
  packages/editor-ui/src/components/CodeNodeEditor/constants.ts
Labels: node/improvement, n8n team

#9344 ci: Update Chromatic setup (no-changelog)
  .github/workflows/chromatic.yml
Labels: ui, n8n team

#9586 fix: Force type safety in design system (no-changelog)
  packages/design-system/vite.config.mts
Labels: ui, n8n team

#9595 fix(editor): Attempt to make cloud plan tests less flaky (no-changelog)
  cypress/e2e/27-cloud.cy.ts
Labels: n8n team

#9551 refactor(core): Remove crash recovery from `error` executions (no-changelog)
  packages/cli/src/WorkflowRunner.ts
Labels: core, n8n team

#9599 refactor(editor): Fix typecheck for design-system and chat packages (no-changelog)
  packages/design-system/src/__tests__/setup.ts
  packages/design-system/src/components/N8nActionBox/ActionBox.vue
  packages/design-system/src/components/N8nActionDropdown/ActionDropdown.vue
  packages/design-system/src/components/N8nActionToggle/ActionToggle.vue
  packages/design-system/src/components/N8nBadge/Badge.vue
  packages/design-system/src/components/N8nButton/Button.vue
  packages/design-system/src/components/N8nCallout/Callout.vue
  packages/design-system/src/components/N8nCheckbox/Checkbox.vue
  packages/design-system/src/components/N8nColorPicker/ColorPicker.vue
  packages/design-system/src/components/N8nFormBox/FormBox.vue
  packages/design-system/src/components/N8nFormInputs/FormInputs.vue
  packages/design-system/src/components/N8nIcon/Icon.vue
  packages/design-system/src/components/N8nIconButton/IconButton.vue
  packages/design-system/src/components/N8nInfoAccordion/InfoAccordion.vue
  packages/design-system/src/components/N8nInput/Input.vue
  packages/design-system/src/components/N8nInputLabel/InputLabel.vue
  packages/design-system/src/components/N8nInputNumber/InputNumber.vue
  packages/design-system/src/components/N8nLink/Link.vue
  packages/design-system/src/components/N8nMarkdown/Markdown.vue
  packages/design-system/src/components/N8nMenu/Menu.vue
  packages/design-system/src/components/N8nMenuItem/routerUtil.ts
  packages/design-system/src/components/N8nNotice/__tests__/Notice.spec.ts
  packages/design-system/src/components/N8nResizeWrapper/ResizeWrapper.vue
  packages/design-system/src/components/N8nSelect/Select.vue
  packages/design-system/src/components/N8nSpinner/Spinner.vue
  packages/design-system/src/components/N8nSticky/Sticky.vue
  packages/design-system/src/components/N8nTabs/Tabs.vue
  packages/design-system/src/components/N8nText/Text.vue
  packages/design-system/src/components/N8nTooltip/Tooltip.vue
  packages/design-system/src/components/N8nTree/Tree.vue
  packages/design-system/src/components/N8nUserStack/UserStack.vue
  packages/design-system/src/components/N8nUserStack/__tests__/UserStack.spec.ts
  packages/design-system/src/components/N8nUsersList/UsersList.stories.ts
  packages/design-system/src/composables/useDeviceSupport.test.ts
  packages/design-system/src/locale/index.ts
  packages/design-system/src/locale/lang/en.ts
  packages/design-system/src/types/action-dropdown.ts
  packages/design-system/src/utils/__tests__/valueByPath.spec.ts
  packages/design-system/tsconfig.json
  packages/editor-ui/tsconfig.json
Labels: ui, n8n team

#9601 refactor(core): Remove dead code that disabled auto-generated ids during import (no-changelog)
  packages/cli/src/commands/import/credentials.ts
  packages/cli/src/commands/import/workflow.ts
  packages/cli/src/databases/utils/commandHelpers.ts
Labels: core, n8n team

#9581 refactor(editor): Fix NodeView/Canvas related TS errors
  packages/editor-ui/src/Interface.ts
  packages/editor-ui/src/components/AIAssistantChat/AIAssistantChat.vue
  packages/editor-ui/src/components/MainHeader/WorkflowDetails.vue
  packages/editor-ui/src/composables/useCanvasMouseSelect.ts
  packages/editor-ui/src/composables/useCanvasPanning.ts
  packages/editor-ui/src/composables/useMessage.ts
  packages/editor-ui/src/composables/useWorkflowHelpers.ts
  packages/editor-ui/src/constants.ts
  packages/editor-ui/src/jsplumb.d.ts
  packages/editor-ui/src/router.ts
  packages/editor-ui/src/shims.d.ts
  packages/editor-ui/src/stores/canvas.store.ts
  packages/editor-ui/src/stores/workflows.store.ts
  packages/editor-ui/src/types/externalHooks.ts
  packages/editor-ui/src/utils/canvasUtilsV2.spec.ts
  packages/editor-ui/src/utils/testData/templateTestData.ts
  packages/editor-ui/src/utils/typeGuards.ts
  packages/editor-ui/src/views/NodeView.v2.vue
  packages/editor-ui/src/views/NodeView.vue
  packages/editor-ui/src/views/SettingsView.vue
  packages/editor-ui/src/views/WorkflowOnboardingView.vue
  packages/workflow/src/Interfaces.ts
  packages/workflow/src/Workflow.ts
Labels: core, ui, n8n team

#9534 feat(core): Allow transferring workflows from any project to any team project
  packages/@n8n/permissions/src/types.ts
  packages/cli/src/errors/response-errors/not-found.error.ts
  packages/cli/src/errors/response-errors/transfer-workflow.error.ts
  packages/cli/src/permissions/global-roles.ts
  packages/cli/src/permissions/project-roles.ts
  packages/cli/src/permissions/resource-roles.ts
  packages/cli/src/workflows/workflow.request.ts
  packages/cli/src/workflows/workflow.service.ee.ts
  packages/cli/src/workflows/workflows.controller.ts
  packages/cli/test/integration/credentials/credentials.api.test.ts
  packages/cli/test/integration/workflows/workflows.controller-with-active-workflow-manager.ee.test.ts
  packages/cli/test/integration/workflows/workflows.controller.ee.test.ts
  packages/cli/test/integration/workflows/workflows.controller.test.ts
  packages/workflow/src/errors/abstract/execution-base.error.ts
Labels: core, n8n team

#9600 fix(core): Start WaitTracker only in the main container
  packages/cli/src/WaitTracker.ts
  packages/cli/src/commands/start.ts
  packages/cli/test/unit/WaitTracker.test.ts
Labels: core, n8n team

#9558 fix(editor): Type errors in `VariablesView.vue` (no-changelog)
  packages/editor-ui/src/Interface.ts
  packages/editor-ui/src/api/environments.ee.ts
  packages/editor-ui/src/components/VariablesRow.vue
  packages/editor-ui/src/components/__tests__/VariablesRow.spec.ts
  packages/editor-ui/src/components/layouts/ResourcesListLayout.vue
  packages/editor-ui/src/views/VariablesView.vue
Labels: ui, n8n team

#9486 feat: Run once for each item tooltip
  packages/editor-ui/src/components/NodeDetailsView.vue
  packages/editor-ui/src/components/NodeExecuteButton.vue
  packages/editor-ui/src/components/NodeSettings.vue
  packages/editor-ui/src/plugins/i18n/locales/en.json
  packages/workflow/src/Constants.ts
  packages/workflow/src/NodeHelpers.ts
  packages/workflow/test/NodeHelpers.test.ts
Labels: ui, n8n team

#9606 ci: Upgrade pnpm (no-changelog)
  CONTRIBUTING.md
  package.json
  pnpm-lock.yaml
Labels: n8n team

#9610 fix(editor): Skip disabled nodes when detecting workflow issues
  cypress/e2e/7-workflow-actions.cy.ts
  cypress/pages/workflow.ts
  packages/editor-ui/src/stores/workflows.store.ts
Labels: ui, n8n team

#9563 feat(core): Allow transferring credentials from any project to any team project
  packages/cli/src/credentials/credentials.controller.ts
  packages/cli/src/credentials/credentials.service.ee.ts
  packages/cli/src/errors/response-errors/transfer-credential.error.ts
  packages/cli/src/requests.ts
  packages/cli/src/workflows/workflow.service.ee.ts
  packages/cli/test/integration/credentials/credentials.api.ee.test.ts
  packages/cli/test/integration/shared/db/credentials.ts
  packages/cli/test/integration/workflows/workflows.controller.ee.test.ts
Labels: core, n8n team

#9602 feat(editor): Add remove node and connections functionality to canvas v2
  packages/editor-ui/src/__tests__/mocks.ts
  packages/editor-ui/src/components/canvas/Canvas.vue
  packages/editor-ui/src/components/canvas/elements/edges/CanvasEdge.vue
  packages/editor-ui/src/components/canvas/elements/nodes/CanvasNode.vue
  packages/editor-ui/src/components/canvas/elements/nodes/CanvasNodeToolbar.vue
  packages/editor-ui/src/composables/useCanvasOperations.spec.ts
  packages/editor-ui/src/composables/useCanvasOperations.ts
  packages/editor-ui/src/plugins/i18n/locales/en.json
  packages/editor-ui/src/router.ts
  packages/editor-ui/src/stores/workflows.store.ts
  packages/editor-ui/src/utils/canvasUtilsV2.spec.ts
  packages/editor-ui/src/utils/canvasUtilsV2.ts
  packages/editor-ui/src/views/NodeView.v2.vue
Labels: ui, n8n team

#9617 ci: Remove the cyclic peer-dependency (no-changelog)
  packages/core/package.json
  packages/core/test/helpers/constants.ts
  pnpm-lock.yaml
Labels: core, n8n team

#9618 feat(editor): Chat Trigger tweaks
  packages/@n8n/chat/src/components/Message.vue
  packages/@n8n/nodes-langchain/nodes/trigger/ChatTrigger/ChatTrigger.node.ts
  packages/@n8n/nodes-langchain/nodes/trigger/ManualChatTrigger/ManualChatTrigger.node.ts
  packages/@n8n/nodes-langchain/nodes/vendors/OpenAi/actions/versionDescription.ts
  packages/core/src/ActiveWorkflows.ts
  packages/core/src/DirectoryLoader.ts
  packages/core/src/NodeExecuteFunctions.ts
  packages/core/src/WorkflowExecute.ts
  packages/editor-ui/src/components/WorkflowLMChat.vue
  packages/editor-ui/src/plugins/i18n/locales/en.json
  packages/editor-ui/src/views/NodeView.vue
Labels: core, ui, n8n team

#9609 refactor: Enforce `strict` mode for design system
  packages/design-system/src/mixins/locale.ts
  packages/design-system/tsconfig.json
Labels: ui, n8n team

#9620 refactor: Update typings of `/me/settings` and `/users/:id/settings` endpoints (no-changelog)
  packages/cli/src/requests.ts
  packages/editor-ui/src/api/users.ts
  packages/editor-ui/src/stores/users.store.ts
Labels: core, ui, n8n team

#9619 fix(editor): Commit theme change from Save button
  packages/editor-ui/src/views/SettingsPersonalView.vue
  packages/editor-ui/src/views/__tests__/SettingsPersonalView.test.ts
Labels: ui, n8n team

#9612 fix(HTTP Request Node): Sanitize secrets of predefined credentials
  packages/core/src/NodeExecuteFunctions.ts
  packages/nodes-base/nodes/HttpRequest/GenericFunctions.ts
  packages/nodes-base/nodes/HttpRequest/V3/HttpRequestV3.node.ts
  packages/nodes-base/nodes/HttpRequest/test/utils/utils.test.ts
  packages/workflow/src/Interfaces.ts
Labels: node/improvement, core, n8n team

#9604 ci: Consistent tsconfig setup for backend packages and fix pnpm typecheck for composite packages (no-changelog)
  .github/workflows/ci-pull-requests.yml
  package.json
  packages/@n8n/client-oauth2/package.json
  packages/@n8n/client-oauth2/tsconfig.build.json
  packages/@n8n/client-oauth2/tsconfig.json
  packages/@n8n/codemirror-lang/tsconfig.json
  packages/@n8n/imap/package.json
  packages/@n8n/imap/tsconfig.build.json
  packages/@n8n/imap/tsconfig.json
  packages/@n8n/nodes-langchain/package.json
  packages/@n8n/nodes-langchain/tsconfig.build.json
  packages/@n8n/nodes-langchain/tsconfig.json
  packages/@n8n/permissions/package.json
  packages/@n8n/permissions/tsconfig.build.json
  packages/@n8n/permissions/tsconfig.json
  packages/cli/package.json
  packages/core/package.json
  packages/core/tsconfig.build.json
  packages/core/tsconfig.json
  packages/design-system/src/mixins/locale.ts
  packages/design-system/tsconfig.json
  packages/nodes-base/nodes/Peekalink/test/Peekalink.node.test.ts
  packages/nodes-base/nodes/StopAndError/test/node/StopAndError.test.ts
  packages/nodes-base/package.json
  packages/workflow/package.json
  packages/workflow/tsconfig.build.json
  packages/workflow/tsconfig.json
  tsconfig.backend.json
  tsconfig.build.json
Labels: node/improvement, core, n8n team

#9621 refactor(core): Restore test for execution pagination in Public API (no-changelog)
  packages/cli/test/integration/publicApi/executions.test.ts
Labels: core, n8n team

#9605 refactor(core): Move curl endpoint to its own controller (no-changelog)
  packages/cli/src/ResponseHelper.ts
  packages/cli/src/Server.ts
  packages/cli/src/controllers/curl.controller.ts
  packages/cli/src/requests.ts
  packages/cli/src/services/curl.service.ts
  packages/cli/test/unit/controllers/curl.controller.test.ts
  packages/cli/test/unit/services/curl.service.test.ts
  packages/editor-ui/src/api/curlHelper.ts
Labels: core, ui, n8n team

#9630 ci: Fix typecheck for nodes-base (no-changelog)
  packages/nodes-base/test/nodes/Helpers.ts
Labels: node/improvement, n8n team

#9629 fix(core): Ensure ID is a positive integer when fetching execution
  packages/cli/src/executions/executions.controller.ts
  packages/cli/src/utils.ts
  packages/cli/test/unit/controllers/executions.controller.test.ts
Labels: core, n8n team

#9627 fix: Prevent NodeApiError rewraping (no-changelog)
  packages/workflow/src/errors/node-api.error.ts
  packages/workflow/src/errors/node-operation.error.ts
  packages/workflow/test/errors/node.error.test.ts
Labels: node/improvement, n8n team, node/issue

#9632 fix(editor): Improve error messages around pinned data
  cypress/e2e/13-pinning.cy.ts
  cypress/pages/ndv.ts
  packages/editor-ui/src/components/RunData.vue
  packages/editor-ui/src/composables/usePinnedData.ts
  packages/editor-ui/src/plugins/i18n/locales/en.json
  packages/editor-ui/src/utils/typesUtils.ts
Labels: ui, n8n team

#9615 fix(editor): Filter credentials by project ID also for new workflow
  cypress/e2e/39-projects.cy.ts
  packages/editor-ui/src/api/credentials.ts
  packages/editor-ui/src/stores/credentials.store.ts
  packages/editor-ui/src/views/NodeView.vue
Labels: ui, n8n team

#9634 fix(Jira Software Node): Fix comments limit and add sorting
  packages/nodes-base/nodes/Jira/IssueCommentDescription.ts
  packages/nodes-base/nodes/Jira/Jira.node.ts
Labels: node/improvement, community

#9631 fix: Make AWS credential work with global AWS services
  packages/nodes-base/credentials/Aws.credentials.ts
  packages/nodes-base/credentials/test/Aws.credentials.test.ts
  packages/nodes-base/tsconfig.build.json
Labels: node/improvement, n8n team

#9628 refactor(editor): Fix eslint errors in Node.vue (no-changelog)
  packages/editor-ui/src/components/Node.vue
Labels: ui, n8n team

#9635 fix(X (Formerly Twitter) Node): Change how tweet id is retrieved from quote URL
  packages/nodes-base/nodes/Twitter/V2/GenericFunctions.ts
  packages/nodes-base/nodes/Twitter/test/Twitter.test.ts
Labels: node/improvement, n8n team

#9639 fix(Jira Software Node): Fix the order by feature
  packages/nodes-base/nodes/Jira/IssueCommentDescription.ts
Labels: community

#9644 fix(editor): Prevent running workflows using keyboard shortcuts if execution is disabled
  cypress/e2e/7-workflow-actions.cy.ts
  packages/editor-ui/src/views/NodeView.vue
Labels: ui, n8n team

#9611 feat(core): Implement `project:viewer` role
  packages/cli/src/credentials/credentials.service.ts
  packages/cli/src/databases/entities/ProjectRelation.ts
  packages/cli/src/permissions/project-roles.ts
  packages/cli/src/services/role.service.ts
  packages/cli/test/integration/credentials/credentials.api.ee.test.ts
  packages/cli/test/integration/credentials/credentials.api.test.ts
  packages/cli/test/integration/executions.controller.test.ts
  packages/cli/test/integration/project.api.test.ts
  packages/cli/test/integration/workflows/workflows.controller.ee.test.ts
  packages/cli/test/unit/repositories/sharedCredentials.repository.test.ts
Labels: core, n8n team

#9641 fix(n8n Form Trigger Node): Error if Respond to Webhook and respond node not in workflow
  packages/nodes-base/nodes/Form/utils.ts
Labels: node/improvement, n8n team, node/issue

#9646 refactor(core): Support writing tests in `cli/src` (no-changelog)
  jest.config.js
  packages/cli/tsconfig.build.json
  packages/cli/tsconfig.json
Labels: core, n8n team

#9647 fix(Gotify Node): Fix issue with self signed certificates not working
  packages/nodes-base/nodes/Gotify/GenericFunctions.ts
Labels: node/improvement, n8n team

#8951 feat: Initial Dev Containers setup (no-changelog)
  .devcontainer/Dockerfile
  .devcontainer/devcontainer.json
  .devcontainer/docker-compose.yml
  .npmrc
  CONTRIBUTING.md
  n8n.code-workspace
Labels: community

#9653 fix: Fix AWS credential test (no-changelog)
  packages/nodes-base/credentials/test/Aws.credentials.test.ts
Labels: node/improvement, n8n team

#9642 fix(Remove Duplicates Node): Tolerate null fields
  packages/nodes-base/nodes/Transform/RemoveDuplicates/RemoveDuplicates.node.ts
  packages/nodes-base/nodes/Transform/RemoveDuplicates/test/RemoveDuplicates.test.ts
  packages/nodes-base/nodes/Transform/RemoveDuplicates/utils.ts
Labels: node/improvement, n8n team, node/issue

#9650 fix(editor): Remove transparency from dark mode callouts
  packages/design-system/src/css/_tokens.dark.scss
  packages/editor-ui/src/components/banners/BaseBanner.vue
Labels: ui, n8n team

#9648 refactor(editor): Apply latest UX changes to concurrency control
  packages/editor-ui/src/components/executions/global/GlobalExecutionsList.vue
  packages/editor-ui/src/components/executions/global/GlobalExecutionsListItem.vue
  packages/editor-ui/src/components/executions/workflow/WorkflowExecutionsCard.vue
  packages/editor-ui/src/plugins/i18n/locales/en.json
Labels: ui, n8n team

#9652 fix: Reset pagination when output size changes
  cypress/e2e/2230-ADO-ndv-reset-data-pagination.cy.ts
  cypress/fixtures/NDV-debug-generate-data.json
  packages/editor-ui/src/components/RunData.vue
Labels: ui, n8n team

#8885 feat(core): Add batching and other options to declarative nodes
  packages/editor-ui/src/components/NodeSettings.vue
  packages/workflow/src/NodeHelpers.ts
  packages/workflow/src/RoutingNode.ts
  packages/workflow/test/RoutingNode.test.ts
Labels: core, n8n team

#9658 refactor(core): Run enqueued executions on startup
  packages/cli/src/commands/start.ts
  packages/cli/src/executions/execution.service.ts
Labels: core, n8n team

#9664 fix(Chat Trigger Node): Fix public chat container dimensions
  packages/@n8n/nodes-langchain/nodes/trigger/ChatTrigger/templates.ts
Labels: n8n team

#9603 feat: Release floating entitlements on license:clear command (no-changelog)
  packages/cli/src/commands/license/clear.ts
  packages/cli/test/integration/commands/license.cmd.test.ts
Labels: core, n8n team

#9645 feat(editor): Add isEmpty on DateTime, add is empty to all types in filter component
  packages/editor-ui/src/components/FilterConditions/constants.ts
  packages/workflow/src/Extensions/ArrayExtensions.ts
  packages/workflow/src/Extensions/DateExtensions.ts
  packages/workflow/src/Extensions/ObjectExtensions.ts
  packages/workflow/src/Extensions/StringExtensions.ts
  packages/workflow/src/NodeParameters/FilterParameter.ts
  packages/workflow/test/FilterParameter.test.ts
Labels: core, ui, n8n team

#9660 feat(OpenAI Node): Allow to select Image analyze model & improve types
  packages/@n8n/nodes-langchain/nodes/vendors/OpenAi/actions/assistant/create.operation.ts
  packages/@n8n/nodes-langchain/nodes/vendors/OpenAi/actions/assistant/update.operation.ts
  packages/@n8n/nodes-langchain/nodes/vendors/OpenAi/actions/descriptions.ts
  packages/@n8n/nodes-langchain/nodes/vendors/OpenAi/actions/image/analyze.operation.ts
  packages/@n8n/nodes-langchain/nodes/vendors/OpenAi/actions/text/message.operation.ts
  packages/@n8n/nodes-langchain/nodes/vendors/OpenAi/actions/versionDescription.ts
  packages/@n8n/nodes-langchain/nodes/vendors/OpenAi/methods/listSearch.ts
Labels: n8n team

#9667 fix(core): Fix optional chaining in continue on fail check
  packages/core/src/WorkflowExecute.ts
Labels: core, n8n team

#9669 fix(editor): Color node connections correctly in execution preview for nodes that have pinned data
  cypress/e2e/20-workflow-executions.cy.ts
  cypress/e2e/2106-ADO-pinned-data-execution-preview.cy.ts
  cypress/fixtures/Webhook_set_pinned.json
  cypress/pages/workflow-executions-tab.ts
  packages/editor-ui/src/components/Node.vue
  packages/editor-ui/src/components/WorkflowPreview.vue
  packages/editor-ui/src/composables/useContextMenu.ts
  packages/editor-ui/src/constants.ts
  packages/editor-ui/src/views/NodeView.vue
Labels: ui, n8n team

#9659 fix(editor): Indent on tabs in expression fields
  packages/editor-ui/src/components/InlineExpressionEditor/InlineExpressionEditorInput.vue
  packages/editor-ui/src/composables/__tests__/useExpressionEditor.test.ts
  packages/editor-ui/src/plugins/codemirror/keymap.ts
Labels: ui, n8n team

#9656 fix(editor): Improve dragndrop of input pills with spaces
  packages/editor-ui/src/components/AssignmentCollection/AssignmentCollection.vue
  packages/editor-ui/src/components/AssignmentCollection/__tests__/utils.test.ts
  packages/editor-ui/src/components/AssignmentCollection/utils.ts
  packages/editor-ui/src/utils/__tests__/mappingUtils.test.ts
  packages/editor-ui/src/utils/mappingUtils.ts
Labels: ui, n8n team

#9613 refactor(core): Revamp crash recovery mechanism for main mode
  packages/cli/src/constants.ts
  packages/cli/src/errors/node-crashed.error.ts
  packages/cli/src/errors/workflow-crashed.error.ts
  packages/cli/src/eventbus/MessageEventBus/MessageEventBus.ts
  packages/cli/src/eventbus/executionDataRecovery.service.ts
  packages/cli/src/executions/__tests__/execution-recovery.service.test.ts
  packages/cli/src/executions/execution-recovery.service.ts
  packages/cli/test/integration/eventbus.ee.test.ts
  packages/cli/test/integration/eventbus.test.ts
  packages/cli/test/integration/metrics.test.ts
Labels: core, n8n team

#9662 fix: Fix typo with submitted (no-changelog)
  packages/cli/templates/form-trigger.handlebars
  packages/nodes-base/nodes/Wait/Wait.node.ts
Labels: node/improvement, core, community, in linear

#9672 refactor(editor): Stop expecting `null` execution status (no-changelog)
  packages/cli/src/Interfaces.ts
  packages/editor-ui/src/Interface.ts
  packages/editor-ui/src/components/executions/global/GlobalExecutionsListItem.vue
  packages/editor-ui/src/composables/useExecutionHelpers.ts
  packages/editor-ui/src/stores/executions.store.ts
  packages/editor-ui/src/utils/apiUtils.ts
  packages/workflow/src/Interfaces.ts
Labels: core, ui, n8n team

#9673 fix(editor): Remove template creds setup from workflow when copied (no-changelog)
  cypress/e2e/34-template-credentials-setup.cy.ts
  packages/editor-ui/src/Interface.ts
  packages/editor-ui/src/components/MainHeader/WorkflowDetails.vue
  packages/editor-ui/src/views/NodeView.vue
Labels: ui, n8n team

#9684 fix(editor): Fix node connection showing incorrect item count during …
  packages/editor-ui/src/components/Node.vue
Labels: ui, n8n team

#9670 fix(editor): Prevent saving already saved workflows
  cypress/e2e/7-workflow-actions.cy.ts
  packages/editor-ui/src/views/NodeView.vue
Labels: ui, n8n team

#9682 fix(editor): Node background for executing nodes in dark mode
  packages/design-system/src/css/_tokens.dark.scss
  packages/design-system/src/css/_tokens.scss
  packages/editor-ui/src/components/NDVFloatingNodes.vue
  packages/editor-ui/src/components/NDVSubConnections.vue
  packages/editor-ui/src/components/Node.vue
  packages/editor-ui/src/components/canvas/elements/nodes/render-types/CanvasNodeConfigurable.vue
  packages/editor-ui/src/components/canvas/elements/nodes/render-types/CanvasNodeDefault.vue
  packages/editor-ui/src/n8n-theme-variables.scss
Labels: ui, n8n team

#9687 refactor(core): Use `@Licensed()` in event bus controller (no-changelog)
  packages/cli/src/eventbus/eventBus.controller.ee.ts
  packages/cli/src/eventbus/middleware/logStreamingEnabled.middleware.ee.ts
Labels: core, n8n team

#9689 ci: Fix e2e tests (no-changelog)
  .github/workflows/e2e-reusable.yml
Labels: n8n team

#9688 refactor(core): Merge event bus controllers and remove dead code (no-changelog)
  packages/@n8n/permissions/src/types.ts
  packages/cli/src/Server.ts
  packages/cli/src/eventbus/MessageEventBusWriter/MessageEventBusLogWriter.ts
  packages/cli/src/eventbus/MessageEventBusWriter/MessageEventBusLogWriterWorker.ts
  packages/cli/src/eventbus/eventBus.controller.ee.ts
  packages/cli/src/eventbus/eventBus.controller.ts
  packages/cli/src/permissions/global-roles.ts
  packages/cli/test/integration/shared/utils/testServer.ts
  packages/editor-ui/src/api/eventbus.ee.ts
  packages/editor-ui/src/stores/rbac.store.ts
  packages/editor-ui/src/stores/workflows.store.ts
Labels: core, ui, n8n team

#9690 refactor(core): Remove event bus helpers (no-changelog)
  packages/cli/src/eventbus/MessageEventBus/MessageEventBus.ts
  packages/cli/src/eventbus/MessageEventBus/MessageEventBusHelper.ts
  packages/cli/src/eventbus/MessageEventBusDestination/Helpers.ee.ts
  packages/cli/src/eventbus/MessageEventBusDestination/MessageEventBusDestination.ee.ts
  packages/cli/src/eventbus/MessageEventBusDestination/MessageEventBusDestinationSentry.ee.ts
  packages/cli/src/eventbus/MessageEventBusDestination/MessageEventBusDestinationSyslog.ee.ts
  packages/cli/src/eventbus/MessageEventBusDestination/MessageEventBusDestinationWebhook.ee.ts
  packages/cli/src/eventbus/index.ts
  packages/cli/src/services/metrics.service.ts
Labels: core, n8n team

#9663 refactor(core): Remove event bus channel (no-changelog)
  packages/cli/src/commands/worker.ts
  packages/cli/src/eventbus/MessageEventBus/MessageEventBus.ts
  packages/cli/src/services/orchestration/main/orchestration.handler.main.service.ts
  packages/cli/src/services/orchestration/worker/orchestration.worker.service.ts
  packages/cli/src/services/redis/RedisServiceHelper.ts
  packages/cli/src/services/redis/RedisServicePubSubPublisher.ts
  packages/cli/src/services/redis/RedisServicePubSubSubscriber.ts
  packages/cli/test/integration/commands/worker.cmd.test.ts
Labels: core, n8n team

#9638 feat: Update NPS Value Survey
  cypress/e2e/12-canvas-actions.cy.ts
  cypress/e2e/13-pinning.cy.ts
  cypress/e2e/1338-ADO-ndv-missing-input-panel.cy.ts
  cypress/e2e/18-user-management.cy.ts
  cypress/e2e/19-execution.cy.ts
  cypress/e2e/2-credentials.cy.ts
  cypress/e2e/2230-ADO-ndv-reset-data-pagination.cy.ts
  cypress/e2e/33-settings-personal.cy.ts
  cypress/e2e/39-import-workflow.cy.ts
  cypress/e2e/42-nps-survey.cy.ts
  cypress/e2e/5-ndv.cy.ts
  cypress/e2e/6-code-node.cy.ts
  cypress/e2e/7-workflow-actions.cy.ts
  cypress/package.json
  cypress/pages/notifications.ts
  cypress/pages/npsSurvey.ts
  cypress/pages/workflow.ts
  cypress/support/commands.ts
  cypress/support/index.ts
  packages/cli/src/Server.ts
  packages/cli/src/controllers/userSettings.controller.ts
  packages/cli/src/databases/migrations/mysqldb/1717498465931-AddActivatedAtUserSetting.ts
  packages/cli/src/databases/migrations/mysqldb/index.ts
  packages/cli/src/databases/migrations/postgresdb/1717498465931-AddActivatedAtUserSetting.ts
  packages/cli/src/databases/migrations/postgresdb/index.ts
  packages/cli/src/databases/migrations/sqlite/1717498465931-AddActivatedAtUserSetting.ts
  packages/cli/src/databases/migrations/sqlite/index.ts
  packages/cli/src/requests.ts
  packages/cli/src/services/events.service.ts
  packages/cli/test/unit/controllers/userSettings.controller.test.ts
  packages/design-system/src/css/_tokens.dark.scss
  packages/design-system/src/css/_tokens.scss
  packages/editor-ui/src/Interface.ts
  packages/editor-ui/src/__tests__/utils.ts
  packages/editor-ui/src/api/npsSurvey.ts
  packages/editor-ui/src/api/settings.ts
  packages/editor-ui/src/components/ContactPromptModal.vue
  packages/editor-ui/src/components/MainHeader/WorkflowDetails.vue
  packages/editor-ui/src/components/Modal.vue
  packages/editor-ui/src/components/ModalRoot.vue
  packages/editor-ui/src/components/Modals.vue
  packages/editor-ui/src/components/NpsSurvey.vue
  packages/editor-ui/src/components/ValueSurvey.vue
  packages/editor-ui/src/components/executions/workflow/WorkflowExecutionsInfoAccordion.vue
  packages/editor-ui/src/components/executions/workflow/WorkflowExecutionsList.vue
  packages/editor-ui/src/composables/useWorkflowActivate.ts
  packages/editor-ui/src/constants.ts
  packages/editor-ui/src/plugins/i18n/locales/en.json
  packages/editor-ui/src/plugins/telemetry/index.ts
  packages/editor-ui/src/plugins/telemetry/telemetry.types.ts
  packages/editor-ui/src/stores/npsStore.store.spec.ts
  packages/editor-ui/src/stores/npsSurvey.store.ts
  packages/editor-ui/src/stores/settings.store.ts
  packages/editor-ui/src/stores/ui.store.ts
  packages/editor-ui/src/stores/users.store.ts
  packages/editor-ui/src/views/NodeView.vue
  packages/workflow/src/Interfaces.ts
  pnpm-lock.yaml
Labels: core, ui, n8n team

#9694 ci: Remove unused WaitTracker mocking (no-changelog)
  packages/cli/test/integration/commands/ldap/reset.test.ts
  packages/cli/test/integration/environments/SourceControl.test.ts
  packages/cli/test/integration/executions.controller.test.ts
  packages/cli/test/integration/workflows/workflows.controller-with-active-workflow-manager.ee.test.ts
Labels: core, n8n team

#9697 refactor(core): Remove more dead code from event bus (no-changelog)
  packages/cli/src/eventbus/EventMessageClasses/Helpers.ts
  packages/cli/src/eventbus/MessageEventBusWriter/MessageEventBusLogWriter.ts
Labels: core, n8n team

#9698 fix(editor): Un-skip workflow save test (no-changelog)
  cypress/e2e/7-workflow-actions.cy.ts
Labels: n8n team

#9685 ci(editor): Enforce type-safety in @n8n/chat builds as well (no-changelog)
  packages/@n8n/chat/package.json
  packages/@n8n/chat/vite.config.mts
  packages/@n8n/chat/vitest.config.mts
  packages/@n8n/chat/vitest.config.ts
Labels: n8n team

#9671 fix(editor): Improve large data warning in input/output panel
  packages/editor-ui/src/components/RunData.vue
  packages/editor-ui/src/constants.ts
  packages/editor-ui/src/plugins/i18n/locales/en.json
Labels: ui, n8n team

#8962 fix: Introduce `HooksService`
  packages/cli/src/Interfaces.ts
  packages/cli/src/databases/entities/AuthUser.ts
  packages/cli/src/services/hooks.service.ts
  packages/cli/src/services/user.service.ts
  packages/cli/test/unit/services/hooks.service.test.ts
Labels: core, n8n team

#9654 feat(editor): Add move resources option to workflows and credentials on
  cypress/composables/projects.ts
  cypress/e2e/39-projects.cy.ts
  cypress/pages/credentials.ts
  cypress/pages/workflows.ts
  packages/editor-ui/src/api/credentials.ee.ts
  packages/editor-ui/src/api/workflows.ee.ts
  packages/editor-ui/src/components/CredentialCard.test.ts
  packages/editor-ui/src/components/CredentialCard.vue
  packages/editor-ui/src/components/Modals.vue
  packages/editor-ui/src/components/Projects/ProjectMoveResourceConfirmModal.vue
  packages/editor-ui/src/components/Projects/ProjectMoveResourceModal.vue
  packages/editor-ui/src/components/Projects/ProjectSettings.vue
  packages/editor-ui/src/components/WorkflowCard.test.ts
  packages/editor-ui/src/components/WorkflowCard.vue
  packages/editor-ui/src/components/layouts/ResourcesListLayout.vue
  packages/editor-ui/src/constants.ts
  packages/editor-ui/src/permissions.spec.ts
  packages/editor-ui/src/permissions.ts
  packages/editor-ui/src/plugins/i18n/locales/en.json
  packages/editor-ui/src/stores/projects.store.ts
  packages/editor-ui/src/stores/ui.store.ts
  packages/editor-ui/src/views/CredentialsView.vue
Labels: ui, n8n team

#9695 ci: Refactor e2e tests to be less flaky (no-changelog)
  .github/workflows/e2e-reusable.yml
  cypress/.eslintrc.js
  cypress/constants.ts
  cypress/e2e/10-undo-redo.cy.ts
  cypress/e2e/12-canvas-actions.cy.ts
  cypress/e2e/12-canvas.cy.ts
  cypress/e2e/17-sharing.cy.ts
  cypress/e2e/18-user-management.cy.ts
  cypress/e2e/25-stickies.cy.ts
  cypress/e2e/27-cloud.cy.ts
  cypress/e2e/27-two-factor-authentication.cy.ts
  cypress/e2e/28-debug.cy.ts
  cypress/e2e/29-templates.cy.ts
  cypress/e2e/30-editor-after-route-changes.cy.ts
  cypress/e2e/32-worker-view.cy.ts
  cypress/e2e/34-template-credentials-setup.cy.ts
  cypress/e2e/35-admin-user-smoke-test.cy.ts
  cypress/e2e/36-versions.cy.ts
  cypress/e2e/39-projects.cy.ts
  cypress/e2e/5-ndv.cy.ts
  cypress/e2e/7-workflow-actions.cy.ts
  cypress/fixtures/templates_search/all_templates_search_response.json
  cypress/fixtures/templates_search/test_template_import.json
  cypress/fixtures/templates_search/test_template_preview.json
  cypress/package.json
  cypress/pages/ndv.ts
  cypress/pages/settings-personal.ts
  cypress/pages/template-credential-setup.ts
  cypress/pages/template-workflow.ts
  cypress/pages/templates.ts
  cypress/pages/workflow.ts
  cypress/scripts/run-e2e.js
  cypress/support/commands.ts
  cypress/support/e2e.ts
  cypress/support/index.ts
  cypress/tsconfig.json
  packages/@n8n_io/eslint-config/base.js
  packages/editor-ui/src/components/NodeIcon.vue
  pnpm-lock.yaml
Labels: n8n team

#9702 ci: Fix custom docker builds (no-changelog)
  cypress/package.json
  packages/editor-ui/package.json
  pnpm-lock.yaml
Labels: ui, n8n team

#9699 feat(editor): Add canvas edge toolbar hover show/hide support (no-changelog)
  packages/editor-ui/src/components/canvas/Canvas.vue
  packages/editor-ui/src/components/canvas/elements/edges/CanvasEdge.spec.ts
  packages/editor-ui/src/components/canvas/elements/edges/CanvasEdge.vue
  packages/editor-ui/src/components/canvas/elements/edges/CanvasEdgeToolbar.spec.ts
  packages/editor-ui/src/components/canvas/elements/edges/CanvasEdgeToolbar.vue
Labels: ui, n8n team

#9704 fix(editor): Add back credential type icon (no-changelog)
  cypress/e2e/39-projects.cy.ts
  packages/editor-ui/src/components/CredentialCard.vue
  packages/editor-ui/src/components/CredentialIcon.vue
  packages/editor-ui/src/components/layouts/ResourcesListLayout.vue
  packages/editor-ui/src/views/CredentialsView.test.ts
  packages/editor-ui/src/views/CredentialsView.vue
Labels: ui, n8n team

#9709 fix(editor): Persist tag filter when clicking tag directly in workflows page
  packages/editor-ui/src/views/WorkflowsView.test.ts
  packages/editor-ui/src/views/WorkflowsView.vue
Labels: ui, n8n team

#9711 ci: Update pull_request_template.md (no-changelog)
  .github/pull_request_template.md
Labels: n8n team

#9675 fix(editor): Improve touch device detection
  packages/design-system/src/composables/useDeviceSupport.test.ts
  packages/design-system/src/composables/useDeviceSupport.ts
  packages/editor-ui/src/__tests__/setup.ts
Labels: ui, n8n team

#9710 fix: Fix sending pin data twice causing payload too large errors
  cypress/e2e/19-execution.cy.ts
  packages/cli/src/workflows/workflow.request.ts
  packages/cli/src/workflows/workflowExecution.service.ts
  packages/editor-ui/src/Interface.ts
  packages/editor-ui/src/composables/useRunWorkflow.ts
Labels: core, ui, n8n team

#9453 perf(core): Introduce concurrency control for main mode
  packages/cli/src/ActiveExecutions.ts
  packages/cli/src/InternalHooks.ts
  packages/cli/src/PublicApi/v1/handlers/executions/executions.handler.ts
  packages/cli/src/commands/start.ts
  packages/cli/src/commands/worker.ts
  packages/cli/src/concurrency/__tests__/concurrency-control.service.test.ts
  packages/cli/src/concurrency/__tests__/concurrency-queue.test.ts
  packages/cli/src/concurrency/concurrency-control.service.ts
  packages/cli/src/concurrency/concurrency-queue.ts
  packages/cli/src/config/schema.ts
  packages/cli/src/databases/repositories/execution.repository.ts
  packages/cli/src/errors/invalid-concurrency-limit.error.ts
  packages/cli/src/errors/queued-execution-retry.error.ts
  packages/cli/src/errors/unknown-execution-mode.error.ts
  packages/cli/src/eventbus/MessageEventBus/MessageEventBus.ts
  packages/cli/src/executions/execution.service.ts
  packages/cli/src/executions/execution.types.ts
  packages/cli/src/executions/executions.controller.ts
  packages/cli/test/integration/commands/ldap/reset.test.ts
  packages/cli/test/integration/environments/SourceControl.test.ts
  packages/cli/test/integration/execution.service.integration.test.ts
  packages/cli/test/integration/executions.controller.test.ts
  packages/cli/test/integration/publicApi/executions.test.ts
  packages/cli/test/integration/publicApi/workflows.test.ts
  packages/cli/test/integration/users.api.test.ts
  packages/cli/test/integration/webhooks.api.test.ts
  packages/cli/test/integration/workflows/workflows.controller-with-active-workflow-manager.ee.test.ts
  packages/cli/test/unit/ActiveExecutions.test.ts
  packages/cli/test/unit/WorkflowRunner.test.ts
  packages/cli/test/unit/controllers/executions.controller.test.ts
  packages/workflow/src/ExecutionStatus.ts
Labels: core, n8n team

#9719 fix(Slack Trigger Node): Wrong file naming fix (no-changelog)
  packages/nodes-base/nodes/Slack/SlackTrigger.node.json
Labels: n8n team

#9717 test: Use nanoid instead of UUID in e2e tests for wf names (no-changelog)
  cypress/e2e/1-workflows.cy.ts
  cypress/e2e/1338-ADO-ndv-missing-input-panel.cy.ts
  cypress/e2e/16-webhook-node.cy.ts
  cypress/e2e/19-execution.cy.ts
  cypress/e2e/2106-ADO-pinned-data-execution-preview.cy.ts
  cypress/e2e/24-ndv-paired-item.cy.ts
  cypress/e2e/5-ndv.cy.ts
  cypress/package.json
  cypress/pages/workflow.ts
  cypress/scripts/run-e2e.js
  cypress/support/commands.ts
  cypress/support/index.ts
  cypress/utils/workflowUtils.ts
  pnpm-lock.yaml
Labels: n8n team

#9726 refactor(core): Remove license from execution repository (no-changelog)
  packages/cli/src/databases/repositories/execution.repository.ts
  packages/cli/src/executions/execution.service.ts
  packages/cli/src/executions/executionHelpers.ts
  packages/cli/test/unit/services/execution.service.test.ts
Labels: core, n8n team

#9727 fix(core): Update transactional email links for RBAC
  packages/cli/src/UserManagement/email/UserManagementMailer.ts
Labels: core, n8n team

#9728 fix(AI Agent Node): Exclude tools agent from unsupported node versions
  packages/@n8n/nodes-langchain/nodes/agents/Agent/Agent.node.ts
Labels: n8n team

#9725 refactor(core): Include logless case in crash recovery (no-changelog)
  packages/cli/src/databases/repositories/execution.repository.ts
  packages/cli/src/eventbus/MessageEventBus/MessageEventBus.ts
  packages/cli/src/executions/__tests__/execution-recovery.service.test.ts
  packages/cli/src/executions/execution-recovery.service.ts
Labels: core, n8n team

#9714 ci: Refactor linting workflow (no-changelog)
  .github/workflows/ci-master.yml
  .github/workflows/ci-pull-requests.yml
  .github/workflows/linting-reusable.yml
  .github/workflows/units-tests-reusable.yml
  package.json
Labels: n8n team

#9740 refactor(editor): Migrate ErrorView component to Vue 3 (no-changelog)
  packages/editor-ui/src/views/ErrorView.vue
Labels: ui, n8n team

#9720 fix(editor): Add telemetry to resource moving
  packages/editor-ui/src/components/CredentialCard.vue
  packages/editor-ui/src/components/Projects/ProjectMoveResourceConfirmModal.vue
  packages/editor-ui/src/components/Projects/ProjectMoveResourceModal.vue
  packages/editor-ui/src/components/WorkflowCard.vue
Labels: ui, n8n team

#9743 refactor(editor): Migrate `SignupView` to composition api (no-changelog)
  packages/editor-ui/src/views/SignupView.vue
Labels: ui, n8n team

#9747 refactor: Migrate ColorCircles to composition api (no-changelog)
  packages/design-system/src/styleguide/ColorCircles.utils.ts
  packages/design-system/src/styleguide/ColorCircles.vue
Labels: ui, n8n team

#9748 refactor: Migrate sizes to composition api (no-changelog)
  packages/design-system/src/styleguide/Sizes.vue
Labels: ui, n8n team

#9745 refactor: Migrate `ResizeObserver` to composition API (no-changelog)
  packages/design-system/src/components/ResizeObserver/ResizeObserver.vue
Labels: ui, n8n team

#9718 fix: When editing nodes only show the credentials in the dropdown that the user is allowed to use in that workflow
  cypress/composables/projects.ts
  cypress/e2e/17-sharing.cy.ts
  cypress/e2e/30-editor-after-route-changes.cy.ts
  cypress/pages/modals/credentials-modal.ts
  cypress/support/index.ts
  packages/cli/src/credentials/credentials.controller.ts
  packages/cli/src/credentials/credentials.service.ts
  packages/cli/src/databases/repositories/credentials.repository.ts
  packages/cli/src/databases/repositories/user.repository.ts
  packages/cli/src/requests.ts
  packages/cli/src/services/role.service.ts
  packages/cli/test/integration/credentials/credentials.api.ee.test.ts
  packages/editor-ui/src/api/credentials.ts
  packages/editor-ui/src/components/Projects/ProjectSettings.vue
  packages/editor-ui/src/stores/credentials.store.ts
  packages/editor-ui/src/views/NodeView.vue
Labels: core, ui, n8n team, release/backport

#9749 refactor(editor): Migrate `TimeAgo` component to composition API (no-changelog)
  packages/editor-ui/src/components/TimeAgo.vue
Labels: ui, n8n team

#9737 refactor(editor): Migrate `userHelpers` mixin to composable (no-changelog)
  packages/editor-ui/src/App.vue
  packages/editor-ui/src/components/MainSidebar.vue
  packages/editor-ui/src/components/SettingsSidebar.vue
  packages/editor-ui/src/composables/useUserHelpers.ts
  packages/editor-ui/src/mixins/userHelpers.ts
Labels: ui, n8n team

#9754 refactor: Migrate `Option` to composition API (no-changelog)
  packages/design-system/src/components/N8nOption/Option.vue
Labels: ui, n8n team

#9756 refactor: Migrate `FormInputs` to composition API (no-changelog)
  packages/design-system/src/components/N8nFormBox/FormBox.vue
  packages/design-system/src/components/N8nFormInputs/FormInputs.vue
Labels: ui, n8n team

#9750 refactor: Migrate `Select` to composition API (no-changelog)
  packages/design-system/src/components/N8nDatatable/__tests__/Datatable.spec.ts
  packages/design-system/src/components/N8nDatatable/__tests__/__snapshots__/Datatable.spec.ts.snap
  packages/design-system/src/components/N8nSelect/Select.vue
Labels: ui, n8n team

#9764 refactor(editor): Migrate `MfaView.vue` to use script setup (no-changelog)
  packages/editor-ui/src/constants.ts
  packages/editor-ui/src/views/MfaView.vue
  packages/editor-ui/src/views/SigninView.vue
Labels: ui, n8n team

#9765 refactor(editor): Migrate `MfaSetupModal.vue` to use script setup (no-changelog)
  packages/editor-ui/src/components/MfaSetupModal.vue
Labels: ui, n8n team

#9766 refactor(editor): Migrate `CommunityNodes.store` to use composition API (no-changelog)
  packages/editor-ui/src/stores/communityNodes.store.ts
Labels: ui, n8n team

#9746 refactor(editor): Migrate `SettingsView` to composition api (no-changelog)
  packages/editor-ui/src/utils/typeGuards.ts
  packages/editor-ui/src/views/SettingsView.vue
Labels: ui, n8n team

#9767 refactor(editor): Migrate `Credentials.store` to use composition API (no-changelog)
  packages/editor-ui/src/stores/credentials.store.ts
Labels: ui, n8n team

#9775 test: Add resource moving modal tests (no-changelog)
  packages/editor-ui/src/components/Projects/ProjectMoveResourceConfirmModal.test.ts
  packages/editor-ui/src/components/Projects/ProjectMoveResourceModal.test.ts
Labels: ui, n8n team

#9752 refactor: Migrate `Pagination` to composition API (no-changelog)
  packages/design-system/src/components/N8nDatatable/Datatable.vue
  packages/design-system/src/components/N8nDatatable/__tests__/Datatable.spec.ts
  packages/design-system/src/components/N8nDatatable/__tests__/__snapshots__/Datatable.spec.ts.snap
  packages/design-system/src/components/N8nPagination/Pagination.vue
  packages/editor-ui/src/components/layouts/ResourcesListLayout.vue
Labels: ui, n8n team

#9759 refactor(core): Remove unused execution status `warning` (no-changelog)
  packages/cli/src/types/commands.types.ts
  packages/workflow/src/ExecutionStatus.ts
Labels: core, n8n team

#9705 feat: Add custom data to public API execution endpoints
  packages/cli/src/Interfaces.ts
  packages/cli/src/PublicApi/v1/handlers/executions/spec/schemas/execution.yml
  packages/cli/src/databases/repositories/execution.repository.ts
  packages/cli/test/integration/publicApi/executions.test.ts
Labels: core, n8n team

#9779 fix(editor): Use BroadcastChannel instead of window.opener for OAuth callback window
  cypress/e2e/43-oauth-flow.cy.ts
  cypress/pages/modals/credentials-modal.ts
  packages/cli/templates/oauth-callback.handlebars
  packages/cli/templates/oauth-error-callback.handlebars
  packages/editor-ui/src/components/CredentialEdit/CredentialConfig.vue
  packages/editor-ui/src/components/CredentialEdit/CredentialEdit.vue
Labels: core, ui, n8n team

#9712 feat(editor): Add capability to open NDV and rename node (no-changelog)
  packages/editor-ui/src/__tests__/mocks.ts
  packages/editor-ui/src/components/canvas/Canvas.vue
  packages/editor-ui/src/components/canvas/elements/nodes/CanvasNode.vue
  packages/editor-ui/src/composables/useCanvasOperations.spec.ts
  packages/editor-ui/src/composables/useCanvasOperations.ts
  packages/editor-ui/src/stores/nodeCreator.store.ts
  packages/editor-ui/src/stores/workflows.store.ts
  packages/editor-ui/src/views/NodeView.v2.vue
Labels: ui, n8n team

#9780 fix: Fix `ColorCircles` and `Sizes` initial render (no-changelog)
  package.json
  packages/design-system/src/styleguide/ColorCircles.vue
  packages/design-system/src/styleguide/Sizes.vue
  packages/design-system/src/styleguide/__tests__/ColorCircles.spec.ts
  packages/design-system/src/styleguide/__tests__/Sizes.spec.ts
  packages/design-system/src/styleguide/__tests__/__snapshots__/ColorCircles.spec.ts.snap
  packages/design-system/src/styleguide/__tests__/__snapshots__/Sizes.spec.ts.snap
  pnpm-lock.yaml
Labels: ui, n8n team

#9722 fix(SalesforceTrigger Node): Add missing codex (no-changelog)
  packages/nodes-base/nodes/Salesforce/SalesforceTrigger.node.json
Labels: node/new, n8n team

#9778 fix(editor): Active toggle incorrectly displayed as inactive in execution view
  packages/editor-ui/src/components/MainHeader/MainHeader.vue
Labels: ui, n8n team

#9762 refactor(editor): Migrate `NodeDetailsView.vue` to use script setup (no-changelog)
  packages/editor-ui/src/components/NodeDetailsView.vue
Labels: ui, n8n team

#9784 fix(core): Make enterprise trial requests via the backend (no-changelog)
  packages/cli/src/license/license.controller.ts
  packages/cli/src/license/license.service.ts
  packages/cli/test/integration/license.api.test.ts
  packages/editor-ui/src/api/usage.ts
  packages/editor-ui/src/stores/usage.store.ts
Labels: core, ui, n8n team

#9788 fix(editor): Set default value for `isProductionExecutionPreview` in `NodeDetaillsView.vue` (no-changelog)
  packages/editor-ui/src/components/NodeDetailsView.vue
Labels: ui, n8n team

#9782 fix(editor): Fix node icon in node creator header
  packages/editor-ui/src/components/Node/NodeCreator/Modes/NodesMode.vue
  packages/editor-ui/src/components/NodeIcon.vue
  packages/editor-ui/src/utils/nodeTypesUtils.ts
Labels: ui, n8n team

#9758 refactor(editor): Migrate `BreakpointsObserver` component to Vue 3 syntax (no-changelog)
  packages/editor-ui/src/components/BreakpointsObserver.vue
Labels: ui, n8n team

#9668 feat(Set Node): Preserve binary data by default
  cypress/e2e/5-ndv.cy.ts
  cypress/fixtures/Test_workflow_ndv_version.json
  packages/editor-ui/src/components/NodeIcon.vue
  packages/nodes-base/nodes/Set/Set.node.ts
  packages/nodes-base/nodes/Set/test/v2/utils.test.ts
  packages/nodes-base/nodes/Set/v2/SetV2.node.ts
  packages/nodes-base/nodes/Set/v2/helpers/interfaces.ts
  packages/nodes-base/nodes/Set/v2/helpers/utils.ts
  packages/nodes-base/nodes/Set/v2/manual.mode.ts
  packages/nodes-base/nodes/Set/v2/raw.mode.ts
Labels: node/improvement, n8n team

#9753 refactor(editor): Refactor BinaryDataDisplay components to Vue 3 syntax (no-changelog)
  packages/editor-ui/src/components/BinaryDataDisplay.vue
  packages/editor-ui/src/components/BinaryDataDisplayEmbed.vue
  packages/editor-ui/src/components/RunData.vue
Labels: ui, n8n team

#9731 refactor(core): Refactor cli command tests (no-changelog)
  packages/cli/src/commands/worker.ts
  packages/cli/test/integration/commands/credentials.cmd.test.ts
  packages/cli/test/integration/commands/import.cmd.test.ts
  packages/cli/test/integration/commands/ldap/reset.test.ts
  packages/cli/test/integration/commands/license.cmd.test.ts
  packages/cli/test/integration/commands/reset.cmd.test.ts
  packages/cli/test/integration/commands/update/workflow.test.ts
  packages/cli/test/integration/commands/worker.cmd.test.ts
  packages/cli/test/integration/shared/utils/testCommand.ts
Labels: core, n8n team

#9785 fix(core): Ensure followers do not recover executions from logs
  packages/cli/src/executions/__tests__/execution-recovery.service.test.ts
  packages/cli/src/executions/execution-recovery.service.ts
Labels: core, n8n team

#9681 fix(editor): Error dropdown in resource locator disappears when search filter is required
  cypress/e2e/26-resource-locator.cy.ts
  cypress/pages/ndv.ts
  packages/editor-ui/src/components/ResourceLocator/ResourceLocator.vue
  packages/editor-ui/src/components/ResourceLocator/ResourceLocatorDropdown.vue
Labels: ui, n8n team

#9643 fix(Slack Node): Do not try to parse block if it's already object
  packages/core/src/NodeExecuteFunctions.ts
  packages/core/test/NodeExecuteFunctions.test.ts
  packages/nodes-base/nodes/Slack/V2/GenericFunctions.ts
  packages/workflow/src/Interfaces.ts
Labels: node/improvement, n8n team, node/issue

#9744 refactor: Refactor input components to composition API (no-changelog)
  packages/editor-ui/src/components/CopyInput.vue
  packages/editor-ui/src/components/CredentialEdit/CredentialConfig.vue
  packages/editor-ui/src/components/CredentialEdit/CredentialInputs.vue
  packages/editor-ui/src/components/ExpandableInput/ExpandableInputBase.vue
  packages/editor-ui/src/components/ExpandableInput/ExpandableInputEdit.vue
  packages/editor-ui/src/components/ExpandableInput/ExpandableInputPreview.vue
  packages/editor-ui/src/components/FilterConditions/Condition.vue
  packages/editor-ui/src/components/ParameterInputExpanded.vue
  packages/editor-ui/src/components/ParameterInputFull.vue
  packages/editor-ui/src/components/ParameterInputHint.vue
  packages/editor-ui/src/components/ParameterInputList.vue
  packages/editor-ui/src/components/ParameterInputWrapper.vue
Labels: ui, n8n team

#9783 refactor(editor): Enable @typescript-eslint/no-base-to-string lint rule, fix errors (no-changelog)
  packages/editor-ui/.eslintrc.js
  packages/editor-ui/src/components/CredentialEdit/CredentialEdit.vue
  packages/editor-ui/src/components/RunDataAi/useAiContentParsers.ts
  packages/editor-ui/src/components/SettingsLogStreaming/EventDestinationSettingsModal.ee.vue
  packages/editor-ui/src/composables/useRunWorkflow.ts
  packages/editor-ui/src/utils/mappingUtils.ts
Labels: ui, n8n team

#9676 feat(core): Expand crash recovery to cover queue mode
  packages/cli/src/Queue.ts
  packages/cli/src/commands/start.ts
  packages/cli/src/config/schema.ts
  packages/cli/src/databases/repositories/execution.repository.ts
  packages/cli/src/executions/__tests__/execution-recovery.service.test.ts
  packages/cli/src/executions/execution-recovery.service.ts
  packages/cli/src/executions/execution.types.ts
  packages/cli/src/services/orchestration/main/MultiMainSetup.ee.ts
Labels: core, n8n team

#9742 refactor(editor): Migrate nodeBase mixin to composable (no-changelog)
  packages/editor-ui/src/__tests__/defaults.ts
  packages/editor-ui/src/components/Node.vue
  packages/editor-ui/src/components/Sticky.vue
  packages/editor-ui/src/composables/useNodeBase.spec.ts
  packages/editor-ui/src/composables/useNodeBase.ts
  packages/editor-ui/src/mixins/nodeBase.ts
Labels: ui, n8n team

#9792 ci: Fix typecheck to fix build (no-changelog)
  packages/editor-ui/src/components/ParameterInputList.vue
Labels: ui, n8n team

#9796 refactor(editor): Use typed-mocks to speed up tests and type-checking (no-changelog)
  packages/editor-ui/src/__tests__/defaults.ts
  packages/editor-ui/src/__tests__/mocks.ts
  packages/editor-ui/src/components/__tests__/CredentialIcon.test.ts
  packages/editor-ui/src/components/__tests__/NodeDetailsView.test.ts
  packages/editor-ui/src/components/__tests__/WorkflowLMChatModal.test.ts
  packages/editor-ui/src/components/__tests__/testData/nodeTypesTestData.ts
  packages/editor-ui/src/composables/__tests__/useActiveNode.test.ts
  packages/editor-ui/src/composables/__tests__/useCanvasMapping.spec.ts
  packages/editor-ui/src/composables/__tests__/useCanvasOperations.spec.ts
  packages/editor-ui/src/composables/__tests__/useNodeBase.spec.ts
  packages/editor-ui/src/composables/__tests__/useNodeConnections.spec.ts
  packages/editor-ui/src/composables/__tests__/usePushConnection.spec.ts
  packages/editor-ui/src/composables/__tests__/useRunWorkflow.spec.ts
  packages/editor-ui/src/composables/__tests__/useWorkflowHelpers.spec.ts
  packages/editor-ui/src/composables/useNodeBase.ts
  packages/editor-ui/src/plugins/codemirror/completions/__tests__/completions.test.ts
  packages/editor-ui/src/plugins/codemirror/completions/__tests__/mock.ts
  packages/editor-ui/src/utils/__tests__/canvasUtilsV2.spec.ts
  packages/editor-ui/src/utils/__tests__/projects.utils.test.ts
  packages/editor-ui/src/utils/__tests__/rbacUtils.test.ts
  packages/editor-ui/src/utils/templates/__tests__/templateActions.test.ts
  packages/editor-ui/src/utils/templates/__tests__/templateTransforms.test.ts
  packages/editor-ui/src/utils/testData/credentialTypeTestData.ts
  packages/editor-ui/src/utils/testData/nodeTypeTestData.ts
  packages/editor-ui/src/utils/testData/templateTestData.ts
  packages/editor-ui/src/views/SetupWorkflowFromTemplateView/__tests__/setupTemplate.store.test.ts
  packages/editor-ui/src/views/SetupWorkflowFromTemplateView/__tests__/setupTemplate.store.testData.ts
  packages/editor-ui/src/views/SetupWorkflowFromTemplateView/__tests__/useCredentialSetupState.test.ts
Labels: ui, n8n team

#9793 fix(core): Ensure execution recovery skips successful executions
  packages/cli/src/executions/__tests__/execution-recovery.service.test.ts
  packages/cli/src/executions/execution-recovery.service.ts
Labels: core, n8n team

#9228 feat: HTTP request tool
  packages/@n8n/nodes-langchain/nodes/tools/ToolHttpRequest/ToolHttpRequest.node.ts
  packages/@n8n/nodes-langchain/nodes/tools/ToolHttpRequest/descriptions.ts
  packages/@n8n/nodes-langchain/nodes/tools/ToolHttpRequest/httprequest.dark.svg
  packages/@n8n/nodes-langchain/nodes/tools/ToolHttpRequest/httprequest.svg
  packages/@n8n/nodes-langchain/nodes/tools/ToolHttpRequest/interfaces.ts
  packages/@n8n/nodes-langchain/nodes/tools/ToolHttpRequest/utils.ts
  packages/@n8n/nodes-langchain/package.json
  packages/core/src/Constants.ts
  packages/core/src/NodeExecuteFunctions.ts
  packages/nodes-base/nodes/Splunk/splunk.svg
  packages/workflow/src/Constants.ts
  packages/workflow/src/Interfaces.ts
  packages/workflow/src/TelemetryHelpers.ts
  pnpm-lock.yaml
Labels: node/new, n8n team

#9781 refactor(core): Auto-register controllers at startup (no-changelog)
  packages/cli/src/Server.ts
  packages/cli/src/controllers/auth.controller.ts
  packages/cli/src/decorators/Licensed.ts
  packages/cli/src/decorators/Middleware.ts
  packages/cli/src/decorators/RestController.ts
  packages/cli/src/decorators/Route.ts
  packages/cli/src/decorators/Scoped.ts
  packages/cli/src/decorators/constants.ts
  packages/cli/src/decorators/controller.registry.ts
  packages/cli/src/decorators/index.ts
  packages/cli/src/decorators/registerController.ts
  packages/cli/src/decorators/types.ts
  packages/cli/test/integration/shared/utils/testServer.ts
  packages/cli/test/unit/decorators/controller.registry.test.ts
  packages/cli/test/unit/decorators/registerController.test.ts
Labels: core, n8n team

#9800 fix(editor): Revert header toggle fix
  packages/editor-ui/src/components/MainHeader/MainHeader.vue
Labels: ui, n8n team

#9806 ci: Publish packages to NPM with provenance statements (no-changelog)
  .github/workflows/release-publish.yml
Labels: n8n team, security

#9804 refactor(core): Send active workflow IDs during license renewal
  packages/cli/package.json
  packages/cli/src/License.ts
  packages/cli/src/services/usageMetrics.service.ts
  packages/cli/test/integration/database/repositories/workflow.repository.test.ts
  packages/cli/test/integration/usage-metrics.service.test.ts
  packages/cli/test/unit/License.test.ts
  pnpm-lock.yaml
Labels: core, n8n team
