Repository n8n-io/n8n, pull requests merged in 2024-01, with the labels that each got.

#8144 feat(core): Add user.profile.beforeUpdate hook
  packages/cli/src/ResponseHelper.ts
  packages/cli/src/controllers/me.controller.ts
  packages/cli/test/unit/controllers/me.controller.test.ts
Labels: core, n8n team

#8154 fix(Microsoft Excel 365 Node): Ensure arg is string during worksheet table search
  packages/nodes-base/nodes/Microsoft/Excel/v2/methods/listSearch.ts
Labels: node/improvement, n8n team

#8153 fix(Notion Node): Ensure arg is string during page ID extraction
  packages/nodes-base/nodes/Notion/GenericFunctions.ts
Labels: node/improvement, n8n team

#8185 fix(Schedule Trigger Node): Use the correct `moment` import
  packages/nodes-base/nodes/Schedule/GenericFunctions.ts
  packages/nodes-base/nodes/Schedule/ScheduleTrigger.node.ts
Labels: node/improvement, n8n team

#8196 fix(editor): Fix templates view layout
  cypress/pages/workflows.ts
  packages/editor-ui/src/components/CollectionWorkflowCard.vue
  packages/editor-ui/src/components/TemplatesInfoCarousel.vue
Labels: ui, n8n team

#8186 refactor(core): Continue moving `typeorm` operators to repositories (no-changelog)
  packages/cli/src/PublicApi/v1/handlers/workflows/workflows.handler.ts
  packages/cli/src/PublicApi/v1/handlers/workflows/workflows.service.ts
  packages/cli/src/UserManagement/PermissionChecker.ts
  packages/cli/src/collaboration/collaboration.service.ts
  packages/cli/src/commands/export/credentials.ts
  packages/cli/src/commands/export/workflow.ts
  packages/cli/src/commands/ldap/reset.ts
  packages/cli/src/commands/list/workflow.ts
  packages/cli/src/commands/update/workflow.ts
  packages/cli/src/controllers/auth.controller.ts
  packages/cli/src/controllers/invitation.controller.ts
  packages/cli/src/controllers/me.controller.ts
  packages/cli/src/controllers/owner.controller.ts
  packages/cli/src/controllers/passwordReset.controller.ts
  packages/cli/src/controllers/users.controller.ts
  packages/cli/src/credentials/credentials.service.ee.ts
  packages/cli/src/databases/repositories/sharedCredentials.repository.ts
  packages/cli/src/databases/repositories/sharedWorkflow.repository.ts
  packages/cli/src/databases/repositories/tag.repository.ts
  packages/cli/src/databases/repositories/user.repository.ts
  packages/cli/src/databases/repositories/workflow.repository.ts
  packages/cli/src/environments/variables/variables.service.ee.ts
  packages/cli/src/eventbus/MessageEventBusDestination/MessageEventBusDestination.ee.ts
  packages/cli/src/eventbus/eventBus.controller.ee.ts
  packages/cli/src/services/import.service.ts
  packages/cli/src/services/role.service.ts
  packages/cli/src/services/tag.service.ts
  packages/cli/src/services/user.service.ts
  packages/cli/src/services/webhook.service.ts
  packages/cli/src/workflows/workflow.service.ee.ts
  packages/cli/src/workflows/workflow.service.ts
  packages/cli/src/workflows/workflows.controller.ts
  packages/cli/test/unit/collaboration/collaboration.service.test.ts
  packages/cli/test/unit/controllers/me.controller.test.ts
  packages/cli/test/unit/controllers/owner.controller.test.ts
Labels: core, n8n team

#8190 fix(GitHub Node): Fix issue that File->Get did not run once per item
  packages/nodes-base/nodes/Github/Github.node.ts
Labels: node/improvement, n8n team

#8189 fix(core): Better input validation for the changeRole endpoint
  packages/cli/src/GenericHelpers.ts
  packages/cli/src/controllers/users.controller.ts
  packages/cli/src/requests.ts
  packages/cli/test/integration/users.api.test.ts
  packages/editor-ui/src/api/users.ts
  packages/editor-ui/src/stores/users.store.ts
  packages/editor-ui/src/views/SettingsUsersView.vue
Labels: core, ui, n8n team

#8200 fix(Invoice Ninja Node): Fix issue with custom invoice numbers not working with v5
  packages/nodes-base/nodes/InvoiceNinja/InvoiceNinja.node.ts
  packages/nodes-base/nodes/InvoiceNinja/QuoteInterface.ts
  packages/nodes-base/nodes/InvoiceNinja/invoiceInterface.ts
Labels: node/improvement, n8n team

#8060 fix(Discord Node): Remove unnecessary requirement on parameters
  packages/nodes-base/nodes/Discord/v2/actions/common.description.ts
  packages/nodes-base/nodes/Discord/v2/actions/message/send.operation.ts
  packages/nodes-base/nodes/Discord/v2/helpers/utils.ts
Labels: node/improvement, community

#8080 feat(Qdrant Vector Store Node): Qdrant vector store support
  packages/@n8n/nodes-langchain/credentials/QdrantApi.credentials.ts
  packages/@n8n/nodes-langchain/nodes/vector_store/VectorStoreQdrant/VectorStoreQdrant.node.ts
  packages/@n8n/nodes-langchain/nodes/vector_store/VectorStoreQdrant/qdrant.svg
  packages/@n8n/nodes-langchain/nodes/vector_store/shared/descriptions.ts
  packages/@n8n/nodes-langchain/nodes/vector_store/shared/methods/listSearch.ts
  packages/@n8n/nodes-langchain/package.json
  pnpm-lock.yaml
Labels: community

#8198 fix(editor): Fix UI urls when hosted behind a path prefix
  packages/editor-ui/src/stores/n8nRoot.store.ts
Labels: ui, n8n team

#8199 feat(Wordpress Node): Add option to ignore error when using self signed certificates
  packages/nodes-base/credentials/WordpressApi.credentials.ts
  packages/nodes-base/nodes/Wordpress/GenericFunctions.ts
Labels: node/improvement, n8n team

#8183 docs: Update workflow link from ai-beta to master
  packages/@n8n/chat/README.md
Labels: community

#8148 fix(editor): Items count display in running workflow
  packages/editor-ui/src/mixins/pushConnection.ts
  packages/editor-ui/src/stores/pushConnection.store.ts
Labels: ui, n8n team

#8197 fix(core): Unsafe isAxiosError property access (no-changelog)
  packages/workflow/src/RoutingNode.ts
Labels: n8n team, node/issue

#8219 fix: Stop showing fake door templates when user clicks on "use template" (no-changelog)
  packages/editor-ui/src/components/SuggestedTemplates/SuggestedTemplatesPreviewModal.vue
Labels: ui, n8n team

#8208 fix: Fix template credential setup for nodes that dont have credentials
  cypress/e2e/34-template-credentials-setup.cy.ts
  cypress/fixtures/Test_Template_2.json
  cypress/pages/template-credential-setup.ts
  packages/editor-ui/src/utils/nodeTypes/nodeTypeTransforms.ts
  packages/editor-ui/src/utils/nodes/nodeTransforms.ts
  packages/editor-ui/src/utils/templates/__tests__/templateTransforms.test.ts
  packages/editor-ui/src/utils/templates/templateActions.ts
  packages/editor-ui/src/utils/templates/templateTransforms.ts
  packages/editor-ui/src/utils/testData/credentialTypeTestData.ts
  packages/editor-ui/src/utils/testData/nodeTypeTestData.ts
  packages/editor-ui/src/utils/testData/templateTestData.ts
  packages/editor-ui/src/views/SetupWorkflowFromTemplateView/__tests__/setupTemplate.store.test.ts
  packages/editor-ui/src/views/SetupWorkflowFromTemplateView/__tests__/setupTemplate.store.testData.ts
  packages/editor-ui/src/views/SetupWorkflowFromTemplateView/setupTemplate.store.ts
  packages/workflow/src/NodeHelpers.ts
Labels: core, ui, n8n team

#7855 feat(Switch Node): Overhaul
  packages/editor-ui/src/components/FilterConditions/Condition.vue
  packages/editor-ui/src/components/FilterConditions/FilterConditions.vue
  packages/editor-ui/src/components/ParameterInputFull.vue
  packages/editor-ui/src/components/ParameterInputList.vue
  packages/editor-ui/src/components/__tests__/FilterConditions.test.ts
  packages/nodes-base/nodes/Switch/Switch.node.ts
  packages/nodes-base/nodes/Switch/V2/SwitchV2.node.ts
  packages/nodes-base/nodes/Switch/V3/SwitchV3.node.ts
  packages/nodes-base/nodes/Switch/V3/test/switch.expression.workflow.json
  packages/nodes-base/nodes/Switch/V3/test/switch.node.test.ts
  packages/nodes-base/nodes/Switch/V3/test/switch.rules.workflow.json
Labels: node/improvement, n8n team

#8207 feat(editor): Migrate pinData mixin to usePinnedData composable (no-changelog)
  packages/editor-ui/src/components/CodeNodeEditor/completions/jsonField.completions.ts
  packages/editor-ui/src/components/InputPanel.vue
  packages/editor-ui/src/components/Node.vue
  packages/editor-ui/src/components/Node/NodeCreator/ItemTypes/NodeItem.vue
  packages/editor-ui/src/components/NodeDetailsView.vue
  packages/editor-ui/src/components/NodeExecuteButton.vue
  packages/editor-ui/src/components/OutputPanel.vue
  packages/editor-ui/src/components/RunData.vue
  packages/editor-ui/src/components/RunDataJsonActions.vue
  packages/editor-ui/src/components/__tests__/RunData.test.ts
  packages/editor-ui/src/composables/__tests__/useActiveNode.test.ts
  packages/editor-ui/src/composables/__tests__/useNodeType.test.ts
  packages/editor-ui/src/composables/__tests__/usePinnedData.test.ts
  packages/editor-ui/src/composables/useActiveNode.ts
  packages/editor-ui/src/composables/useNodeHelpers.ts
  packages/editor-ui/src/composables/useNodeType.ts
  packages/editor-ui/src/composables/usePinnedData.ts
  packages/editor-ui/src/mixins/nodeBase.ts
  packages/editor-ui/src/mixins/workflowHelpers.ts
  packages/editor-ui/src/stores/workflows.store.ts
  packages/editor-ui/src/views/NodeView.vue
Labels: ui, n8n team

#8224 feat(HTTP Request Node): Interval Between Requests option for pagination
  packages/core/src/NodeExecuteFunctions.ts
  packages/nodes-base/nodes/HttpRequest/V3/HttpRequestV3.node.ts
  packages/workflow/src/Interfaces.ts
Labels: node/improvement, n8n team, node/issue

#8228 fix(editor): Only load suggested templates for owners
  packages/editor-ui/src/stores/cloudPlan.store.ts
Labels: ui, n8n team

#8084 feat(editor): Add fullscreen view to code editor
  cypress/e2e/26-resource-locator.cy.ts
  cypress/e2e/5-ndv.cy.ts
  cypress/pages/ndv.ts
  cypress/support/commands.ts
  packages/design-system/src/css/dialog.scss
  packages/editor-ui/src/components/CodeNodeEditor/CodeNodeEditor.vue
  packages/editor-ui/src/components/CodeNodeEditor/baseExtensions.ts
  packages/editor-ui/src/components/CodeNodeEditor/theme.ts
  packages/editor-ui/src/components/HtmlEditor/HtmlEditor.vue
  packages/editor-ui/src/components/HtmlEditor/theme.ts
  packages/editor-ui/src/components/JsEditor/JsEditor.vue
  packages/editor-ui/src/components/JsonEditor/JsonEditor.vue
  packages/editor-ui/src/components/NodeSettings.vue
  packages/editor-ui/src/components/ParameterInput.vue
  packages/editor-ui/src/components/SqlEditor/SqlEditor.vue
  packages/editor-ui/src/n8n-theme.scss
  packages/nodes-base/nodes/Code/descriptions/JavascriptCodeDescription.ts
  packages/nodes-base/nodes/Code/descriptions/PythonCodeDescription.ts
  packages/nodes-base/nodes/Google/BigQuery/v2/actions/database/executeQuery.operation.ts
  packages/nodes-base/nodes/Microsoft/Sql/MicrosoftSql.node.ts
  packages/nodes-base/nodes/MySql/v1/MySqlV1.node.ts
  packages/nodes-base/nodes/MySql/v2/actions/database/executeQuery.operation.ts
  packages/nodes-base/nodes/Postgres/v1/PostgresV1.node.ts
  packages/nodes-base/nodes/Postgres/v2/actions/database/executeQuery.operation.ts
  packages/nodes-base/nodes/QuestDb/QuestDb.node.ts
  packages/nodes-base/nodes/Set/v2/raw.mode.ts
  packages/nodes-base/nodes/Snowflake/Snowflake.node.ts
  packages/nodes-base/nodes/TimescaleDb/TimescaleDb.node.ts
Labels: ui, n8n team

#8226 fix: Add template id to workflows created from templates (no-changelog)
  cypress/e2e/34-template-credentials-setup.cy.ts
  packages/editor-ui/src/utils/templates/templateActions.ts
Labels: ui, n8n team

#8235 fix(NocoDB Node): Download attachments
  packages/nodes-base/nodes/NocoDB/GenericFunctions.ts
Labels: n8n team, node/issue

#8233 fix(Set Node): Field not excluded if dot notation disabled and field was set by using drag-and-drop from ui
  packages/nodes-base/nodes/Set/v2/helpers/utils.ts
Labels: n8n team, node/issue

#8232 fix: Adjust 'use template' feature telemetry (no-changelog)
  packages/editor-ui/src/stores/templates.store.ts
  packages/editor-ui/src/utils/templates/__tests__/templateActions.test.ts
  packages/editor-ui/src/utils/templates/templateActions.ts
  packages/editor-ui/src/utils/templates/templateTransforms.ts
  packages/editor-ui/src/utils/testData/nodeTypeTestData.ts
  packages/editor-ui/src/utils/testData/templateTestData.ts
  packages/editor-ui/src/views/SetupWorkflowFromTemplateView/setupTemplate.store.ts
  packages/editor-ui/src/views/TemplatesCollectionView.vue
  packages/editor-ui/src/views/TemplatesWorkflowView.vue
Labels: ui, n8n team

#8234 fix(Nextcloud Node): Throw an actual error if server responded with Fatal error
  packages/nodes-base/nodes/NextCloud/GenericFunctions.ts
  packages/nodes-base/nodes/Yourls/GenericFunctions.ts
  test-results.json
Labels: n8n team, node/issue

#8213 perf(core): Improve caching service
  packages/cli/BREAKING-CHANGES.md
  packages/cli/package.json
  packages/cli/src/ActivationErrors.service.ts
  packages/cli/src/TestWebhooks.ts
  packages/cli/src/config/schema.ts
  packages/cli/src/controllers/e2e.controller.ts
  packages/cli/src/environments/variables/variables.service.ee.ts
  packages/cli/src/errors/cache-errors/malformed-refresh-value.error.ts
  packages/cli/src/errors/cache-errors/uncacheable-value.error.ts
  packages/cli/src/services/cache.service.ts
  packages/cli/src/services/cache/cache.service.ts
  packages/cli/src/services/cache/cache.types.ts
  packages/cli/src/services/cache/redis.cache-manager.ts
  packages/cli/src/services/metrics.service.ts
  packages/cli/src/services/ownership.service.ts
  packages/cli/src/services/role.service.ts
  packages/cli/src/services/test-webhook-registrations.service.ts
  packages/cli/src/services/webhook.service.ts
  packages/cli/test/integration/commands/worker.cmd.test.ts
  packages/cli/test/unit/services/cache-mock.service.test.ts
  packages/cli/test/unit/services/cache.service.test.ts
  packages/cli/test/unit/services/role.service.test.ts
  packages/cli/test/unit/services/test-webhook-registrations.service.test.ts
  packages/cli/test/unit/services/webhook.service.test.ts
  pnpm-lock.yaml
Labels: core, n8n team

#8220 refactor: Migrate `genericHelpers` mixin to composable
  packages/editor-ui/src/components/BreakpointsObserver.vue
  packages/editor-ui/src/components/CollectionWorkflowCard.vue
  packages/editor-ui/src/components/ExecutionTime.vue
  packages/editor-ui/src/components/ExecutionsList.vue
  packages/editor-ui/src/components/ExpressionEdit.vue
  packages/editor-ui/src/components/MainHeader/WorkflowDetails.vue
  packages/editor-ui/src/components/MainSidebar.vue
  packages/editor-ui/src/components/NodeCredentials.vue
  packages/editor-ui/src/components/NodeList.vue
  packages/editor-ui/src/components/OutputPanel.vue
  packages/editor-ui/src/components/ParameterInput.vue
  packages/editor-ui/src/components/ResourceLocator/ResourceLocator.vue
  packages/editor-ui/src/components/RunData.vue
  packages/editor-ui/src/components/RunDataJsonActions.vue
  packages/editor-ui/src/components/TemplateCard.vue
  packages/editor-ui/src/components/TemplateFilters.vue
  packages/editor-ui/src/components/TemplateList.vue
  packages/editor-ui/src/components/TemplatesInfoCard.vue
  packages/editor-ui/src/components/TemplatesInfoCarousel.vue
  packages/editor-ui/src/components/WorkerList.ee.vue
  packages/editor-ui/src/components/WorkflowSettings.vue
  packages/editor-ui/src/composables/useHistoryHelper.ts
  packages/editor-ui/src/composables/useLoadingService.ts
  packages/editor-ui/src/composables/useNodeHelpers.ts
  packages/editor-ui/src/constants.ts
  packages/editor-ui/src/mixins/executionsHelpers.ts
  packages/editor-ui/src/mixins/genericHelpers.ts
  packages/editor-ui/src/mixins/workflowHelpers.ts
  packages/editor-ui/src/plugins/i18n/index.ts
  packages/editor-ui/src/router.ts
  packages/editor-ui/src/stores/canvas.store.ts
  packages/editor-ui/src/types/router.ts
  packages/editor-ui/src/utils/formatters/dateFormatter.ts
  packages/editor-ui/src/views/MfaView.vue
  packages/editor-ui/src/views/NodeView.vue
  packages/editor-ui/src/views/SigninView.vue
  packages/editor-ui/src/views/TemplatesSearchView.vue
  packages/editor-ui/src/views/WorkflowsView.vue
Labels: ui, n8n team

#8236 fix: Make params panel double width for all SQL nodes
  packages/nodes-base/nodes/Microsoft/Sql/MicrosoftSql.node.ts
  packages/nodes-base/nodes/MySql/MySql.node.ts
  packages/nodes-base/nodes/Postgres/Postgres.node.ts
  packages/nodes-base/nodes/QuestDb/QuestDb.node.ts
  packages/nodes-base/nodes/Snowflake/Snowflake.node.ts
  packages/nodes-base/nodes/TimescaleDb/TimescaleDb.node.ts
Labels: node/improvement, n8n team

#8230 fix(Postgres Node): Stop marking autogenerated columns as required
  packages/nodes-base/nodes/Postgres/v2/helpers/interfaces.ts
  packages/nodes-base/nodes/Postgres/v2/helpers/utils.ts
  packages/nodes-base/nodes/Postgres/v2/methods/resourceMapping.ts
  packages/workflow/src/NodeHelpers.ts
Labels: node/improvement, core, n8n team

#8212 refactor(core): Continue moving `typeorm` operators to repositories (no-changelog)
  packages/cli/src/WorkflowHelpers.ts
  packages/cli/src/controllers/users.controller.ts
  packages/cli/src/credentials/credentials.controller.ee.ts
  packages/cli/src/databases/repositories/role.repository.ts
  packages/cli/src/databases/repositories/sharedCredentials.repository.ts
  packages/cli/src/databases/repositories/sharedWorkflow.repository.ts
  packages/cli/src/databases/repositories/workflow.repository.ts
  packages/cli/src/environments/sourceControl/sourceControlImport.service.ee.ts
  packages/cli/src/workflows/workflow.service.ee.ts
  packages/cli/src/workflows/workflows.controller.ts
Labels: core, n8n team

#8242 perf(core): Optimize workflow activation errors
  packages/cli/src/ActivationErrors.service.ts
  packages/cli/src/ActiveWorkflowRunner.ts
  packages/cli/test/integration/activation-errors.service.test.ts
Labels: core, n8n team

#8231 fix(editor): Vertically center workflow preview loading state
  packages/editor-ui/src/components/WorkflowPreview.vue
Labels: ui, n8n team

#8137 feat(editor): Update copy: `Execute` --> `Test`
  cypress/constants.ts
  cypress/e2e/13-pinning.cy.ts
  cypress/e2e/4-node-creator.cy.ts
  cypress/e2e/5-ndv.cy.ts
  cypress/fixtures/Floating_Nodes.json
  cypress/fixtures/Lots_of_nodes.json
  cypress/fixtures/Node_IO_filter.json
  cypress/fixtures/Suggested_Templates.json
  cypress/fixtures/Test_workflow_5.json
  cypress/fixtures/Test_workflow_filter.json
  cypress/fixtures/Test_workflow_ndv_version.json
  cypress/fixtures/Test_workflow_schema_test.json
  cypress/fixtures/Test_workflow_schema_test_pinned_data.json
  cypress/fixtures/Test_workflow_webhook_with_pin_data.json
  cypress/fixtures/Test_workflow_xml_output.json
  cypress/fixtures/expression_with_paired_item_in_multi_input_node.json
  cypress/fixtures/workflow-with-unknown-credentials.json
  cypress/fixtures/workflow-with-unknown-nodes.json
  packages/editor-ui/src/components/Node.vue
  packages/editor-ui/src/components/NodeExecuteButton.vue
  packages/editor-ui/src/composables/__tests__/__snapshots__/useContextMenu.test.ts.snap
  packages/editor-ui/src/composables/useContextMenu.ts
  packages/editor-ui/src/plugins/i18n/locales/en.json
  packages/editor-ui/src/views/NodeView.vue
  packages/nodes-base/nodes/Cron/Cron.node.ts
  packages/nodes-base/nodes/Interval/Interval.node.ts
  packages/nodes-base/nodes/ManualTrigger/ManualTrigger.node.ts
  packages/nodes-base/nodes/Schedule/ScheduleTrigger.node.ts
Labels: ui, n8n team

#8240 feat: Enable cred setup for workflows created from templates (no-changelog)
  cypress/e2e/16-form-trigger-node.cy.ts
  packages/editor-ui/src/components/CredentialPicker/CredentialPicker.vue
  packages/editor-ui/src/components/MainHeader/MainHeader.vue
  packages/editor-ui/src/components/Modal.vue
  packages/editor-ui/src/components/Modals.vue
  packages/editor-ui/src/components/SetupWorkflowCredentialsButton/SetupWorkflowCredentialsButton.vue
  packages/editor-ui/src/components/SetupWorkflowCredentialsModal/SetupWorkflowCredentialsModal.vue
  packages/editor-ui/src/components/SetupWorkflowCredentialsModal/useSetupWorkflowCredentialsModalState.ts
  packages/editor-ui/src/constants.ts
  packages/editor-ui/src/plugins/i18n/locales/en.json
  packages/editor-ui/src/stores/ui.store.ts
  packages/editor-ui/src/utils/nodes/nodeTransforms.ts
  packages/editor-ui/src/utils/templates/templateActions.ts
  packages/editor-ui/src/utils/templates/templateTransforms.ts
  packages/editor-ui/src/views/NodeView.vue
  packages/editor-ui/src/views/SetupWorkflowFromTemplateView/AppsRequiringCredsNotice.vue
  packages/editor-ui/src/views/SetupWorkflowFromTemplateView/SetupTemplateFormStep.vue
  packages/editor-ui/src/views/SetupWorkflowFromTemplateView/SetupWorkflowFromTemplateView.vue
  packages/editor-ui/src/views/SetupWorkflowFromTemplateView/__tests__/setupTemplate.store.test.ts
  packages/editor-ui/src/views/SetupWorkflowFromTemplateView/__tests__/useCredentialSetupState.test.ts
  packages/editor-ui/src/views/SetupWorkflowFromTemplateView/setupTemplate.store.ts
  packages/editor-ui/src/views/SetupWorkflowFromTemplateView/useCredentialSetupState.ts
Labels: ui, n8n team

#8245 test: Add e2e tests for cred setup on workflow editor (no-changelog)
  cypress/composables/modals/workflow-credential-setup-modal.ts
  cypress/composables/setup-template-form-step.ts
  cypress/composables/setup-workflow-credentials-button.ts
  cypress/e2e/34-template-credentials-setup.cy.ts
  cypress/pages/template-credential-setup.ts
  cypress/support/commands.ts
  cypress/support/e2e.ts
  cypress/support/index.ts
  packages/editor-ui/src/components/Modals.vue
Labels: ui, n8n team

#8250 fix: Resolve expressions in credentials following paired item
  packages/cli/BREAKING-CHANGES.md
  packages/cli/src/CredentialsHelper.ts
  packages/cli/src/controllers/oauth/abstractOAuth.controller.ts
  packages/cli/src/eventbus/MessageEventBusDestination/MessageEventBusDestinationWebhook.ee.ts
  packages/core/src/NodeExecuteFunctions.ts
  packages/nodes-base/nodes/HttpRequest/V3/HttpRequestV3.node.ts
  packages/workflow/src/Interfaces.ts
Labels: core, n8n team

#8201 fix(core): Do not add Authentication header when `authentication` type is `body`
  packages/@n8n/client-oauth2/src/ClientOAuth2.ts
  packages/@n8n/client-oauth2/src/CredentialsFlow.ts
  packages/@n8n/client-oauth2/src/index.ts
  packages/@n8n/client-oauth2/src/types.ts
  packages/@n8n/client-oauth2/test/CredentialsFlow.test.ts
  packages/cli/src/controllers/oauth/oAuth2Credential.controller.ts
  packages/core/src/NodeExecuteFunctions.ts
  packages/core/src/OAuth2Helper.ts
  packages/workflow/src/Interfaces.ts
Labels: node/improvement, core, n8n team

#8253 refactor(core): Convert workflows controller to DI (no-changelog)
  packages/cli/src/Server.ts
  packages/cli/src/UserManagement/UserManagementHelper.ts
  packages/cli/src/controllers/activeWorkflows.controller.ts
  packages/cli/src/credentials/credentials.controller.ee.ts
  packages/cli/src/requests.ts
  packages/cli/src/utils.ts
  packages/cli/src/workflows/workflow.request.ts
  packages/cli/src/workflows/workflow.service.ts
  packages/cli/src/workflows/workflows.controller.ts
  packages/cli/test/integration/shared/utils/testServer.ts
Labels: core, n8n team

#8252 fix: Adjust telemetry from canvas (no-changelog)
  packages/editor-ui/src/components/SetupWorkflowCredentialsModal/SetupWorkflowCredentialsModal.vue
  packages/editor-ui/src/stores/credentials.store.ts
  packages/editor-ui/src/stores/ui.store.ts
  packages/editor-ui/src/utils/templates/templateActions.ts
  packages/editor-ui/src/views/SetupWorkflowFromTemplateView/SetupWorkflowFromTemplateView.vue
  packages/editor-ui/src/views/TemplatesCollectionView.vue
  packages/editor-ui/src/views/TemplatesWorkflowView.vue
Labels: ui, n8n team

#8255 fix: Hide cred setup button from canvas (no-changelog)
  cypress/e2e/34-template-credentials-setup.cy.ts
  packages/cli/src/workflows/workflow.service.ts
  packages/cli/test/integration/workflows.controller.test.ts
  packages/editor-ui/src/Interface.ts
  packages/editor-ui/src/components/SetupWorkflowCredentialsButton/SetupWorkflowCredentialsButton.vue
  packages/editor-ui/src/utils/nodes/nodeTransforms.ts
Labels: core, ui, n8n team

#8244 feat(editor): Migrate debounce mixin to useDebounce composable (no-changelog)
  packages/editor-ui/src/components/BreakpointsObserver.vue
  packages/editor-ui/src/components/ExecutionFilter.vue
  packages/editor-ui/src/components/ExecutionsView/ExecutionsList.vue
  packages/editor-ui/src/components/ExpressionEdit.vue
  packages/editor-ui/src/components/FilterConditions/FilterConditions.vue
  packages/editor-ui/src/components/MainSidebar.vue
  packages/editor-ui/src/components/NDVDraggablePanels.vue
  packages/editor-ui/src/components/Node.vue
  packages/editor-ui/src/components/ParameterInput.vue
  packages/editor-ui/src/components/ResourceLocator/ResourceLocator.vue
  packages/editor-ui/src/components/layouts/ResourcesListLayout.vue
  packages/editor-ui/src/composables/__tests__/useDebounce.test.ts
  packages/editor-ui/src/composables/useClipboard.ts
  packages/editor-ui/src/composables/useDebounce.ts
  packages/editor-ui/src/composables/useHistoryHelper.ts
  packages/editor-ui/src/mixins/debounce.ts
  packages/editor-ui/src/stores/posthog.store.ts
  packages/editor-ui/src/views/NodeView.vue
  packages/editor-ui/src/views/TemplatesSearchView.vue
Labels: ui, n8n team

#8257 feat: Rename template cred setup feature flag (no-changelog)
  cypress/pages/template-credential-setup.ts
  packages/editor-ui/src/constants.ts
Labels: ui, n8n team

#8258 fix(editor): Unify canvas button positioning
  packages/editor-ui/src/components/CanvasControls.vue
  packages/editor-ui/src/components/Node/NodeCreation.vue
  packages/editor-ui/src/views/NodeView.vue
Labels: ui, n8n team

#8259 fix: Adjust set up template button styles (no-changelog)
  cypress/composables/setup-workflow-credentials-button.ts
  cypress/e2e/34-template-credentials-setup.cy.ts
  packages/editor-ui/src/components/SetupWorkflowCredentialsButton/SetupWorkflowCredentialsButton.vue
  packages/editor-ui/src/plugins/i18n/locales/en.json
Labels: ui, n8n team

#8239 feat: Implement MistralCloud Chat & Embeddings nodes
  package.json
  packages/@n8n/nodes-langchain/credentials/MistralCloudApi.credentials.ts
  packages/@n8n/nodes-langchain/nodes/embeddings/EmbeddingsMistralCloud/EmbeddingsMistralCloud.node.ts
  packages/@n8n/nodes-langchain/nodes/embeddings/EmbeddingsMistralCloud/mistral.svg
  packages/@n8n/nodes-langchain/nodes/llms/LmChatMistralCloud/LmChatMistralCloud.node.ts
  packages/@n8n/nodes-langchain/nodes/llms/LmChatMistralCloud/mistral.svg
  packages/@n8n/nodes-langchain/package.json
  pnpm-lock.yaml
Labels: n8n team

#8262 fix(core): Avoid wrapping `ExecutionBaseError` to prevent misreporting to Sentry (no-changelog)
  packages/core/src/NodeExecuteFunctions.ts
Labels: core, n8n team

#8206 fix(editor): Tweaking button sizes in execution preview
  packages/editor-ui/src/components/ExecutionsView/ExecutionPreview.vue
Labels: ui, n8n team

#8265 fix(Github Trigger Node): Enforce SSL validation by default
  packages/nodes-base/nodes/Github/GithubTrigger.node.ts
Labels: node/improvement, n8n team, security

#8270 docs: Update primaryDocumentation urls for nodes updated in #7651 (no-changelog)
  packages/nodes-base/nodes/ICalendar/ICalendar.node.json
  packages/nodes-base/nodes/MoveBinaryData/MoveBinaryData.node.json
  packages/nodes-base/nodes/ReadBinaryFile/ReadBinaryFile.node.json
  packages/nodes-base/nodes/ReadBinaryFiles/ReadBinaryFiles.node.json
  packages/nodes-base/nodes/ReadPdf/ReadPDF.node.json
  packages/nodes-base/nodes/SpreadsheetFile/SpreadsheetFile.node.json
  packages/nodes-base/nodes/WriteBinaryFile/WriteBinaryFile.node.json
Labels: node/improvement, n8n team

#8261 fix: Fix user reinvites on FE and BE
  packages/cli/src/services/user.service.ts
  packages/cli/test/integration/invitations.api.test.ts
  packages/editor-ui/src/Interface.ts
  packages/editor-ui/src/api/invitation.ts
  packages/editor-ui/src/stores/users.store.ts
  packages/editor-ui/src/utils/apiUtils.ts
  packages/editor-ui/src/views/SettingsUsersView.vue
Labels: core, ui, n8n team

#8273 docs: Update links in deprecated langchain nodes to avoid linting errors (no-changelog)
  packages/@n8n/nodes-langchain/credentials/GooglePalmApi.credentials.ts
  packages/@n8n/nodes-langchain/credentials/MistralCloudApi.credentials.ts
  packages/@n8n/nodes-langchain/credentials/SerpApi.credentials.ts
  packages/@n8n/nodes-langchain/nodes/document_loaders/DocumentBinaryInputLoader/DocumentBinaryInputLoader.node.ts
  packages/@n8n/nodes-langchain/nodes/document_loaders/DocumentJSONInputLoader/DocumentJsonInputLoader.node.ts
  packages/@n8n/nodes-langchain/nodes/vector_store/VectorStoreInMemoryInsert/VectorStoreInMemoryInsert.node.ts
  packages/@n8n/nodes-langchain/nodes/vector_store/VectorStoreInMemoryLoad/VectorStoreInMemoryLoad.node.ts
  packages/@n8n/nodes-langchain/nodes/vector_store/VectorStorePineconeInsert/VectorStorePineconeInsert.node.ts
  packages/@n8n/nodes-langchain/nodes/vector_store/VectorStorePineconeLoad/VectorStorePineconeLoad.node.ts
  packages/@n8n/nodes-langchain/nodes/vector_store/VectorStoreSupabaseInsert/VectorStoreSupabaseInsert.node.ts
  packages/@n8n/nodes-langchain/nodes/vector_store/VectorStoreSupabaseLoad/VectorStoreSupabaseLoad.node.ts
  packages/@n8n/nodes-langchain/nodes/vector_store/VectorStoreZepInsert/VectorStoreZepInsert.node.ts
  packages/@n8n/nodes-langchain/nodes/vector_store/VectorStoreZepLoad/VectorStoreZepLoad.node.ts
Labels: n8n team

#8247 fix(core): Fix test webhook deregistration
  packages/cli/src/TestWebhooks.ts
  packages/cli/src/workflows/workflow.service.ts
  packages/cli/test/unit/TestWebhooks.test.ts
  packages/workflow/src/Interfaces.ts
Labels: core, n8n team

#8276 ci: Fix codecov reporting, and include all packages (no-changelog)
  .github/workflows/units-tests-reusable.yml
  jest.config.js
  packages/design-system/vite.config.mts
Labels: ui, n8n team

#8275 ci: Fix lint setup in `chat` package (no-changelog)
  packages/@n8n/chat/.eslintrc.cjs
  packages/@n8n/chat/package.json
  packages/@n8n/chat/src/App.vue
  packages/@n8n/chat/src/__stories__/App.stories.ts
  packages/@n8n/chat/src/components/Chat.vue
  packages/@n8n/chat/src/components/ChatWindow.vue
  packages/@n8n/chat/src/components/Input.vue
  packages/@n8n/chat/src/components/Layout.vue
  packages/@n8n/chat/src/components/Message.vue
  packages/@n8n/chat/src/components/MessageTyping.vue
  packages/@n8n/chat/src/plugins/chat.ts
  packages/@n8n/chat/src/types/chat.ts
  packages/@n8n_io/eslint-config/frontend.js
  packages/design-system/.eslintrc.js
  packages/editor-ui/.eslintrc.js
Labels: ui, n8n team

#8131 fix(FTP Node): FTP connection failed due to missing password credential in node
  packages/nodes-base/nodes/Ftp/Ftp.node.ts
Labels: node/improvement, community

#7771 feat(Coda Node): Add User-Agent for requests to Coda (no-changelog)
  packages/nodes-base/nodes/Coda/GenericFunctions.ts
Labels: node/improvement, community

#8237 fix: Fix issue with API key being required for the Qdrant Node
  packages/@n8n/nodes-langchain/credentials/QdrantApi.credentials.ts
Labels: community

#8280 fix: Small ui fixes to workflow cred setup modal (no-changelog)
  cypress/composables/modals/workflow-credential-setup-modal.ts
  cypress/e2e/34-template-credentials-setup.cy.ts
  packages/editor-ui/src/components/SetupWorkflowCredentialsModal/SetupWorkflowCredentialsModal.vue
  packages/editor-ui/src/plugins/i18n/locales/en.json
Labels: ui, n8n team

#8271 ci: Validate docs urls for langchain nodes as well (no-changelog)
  .github/scripts/package.json
  .github/scripts/validate-docs-links.js
  .github/workflows/check-documentation-urls.yml
Labels: n8n team

#8254 fix(Monday.com Node): Migrate to api 2023-10
  packages/cli/BREAKING-CHANGES.md
  packages/nodes-base/credentials/MondayComApi.credentials.ts
  packages/nodes-base/nodes/MondayCom/GenericFunctions.ts
  packages/nodes-base/nodes/MondayCom/MondayCom.node.ts
Labels: node/improvement, n8n team, node/issue

#8282 ci: Update Cypress & increase amount of e2e containers
  .github/workflows/e2e-reusable.yml
  cypress/e2e/29-templates.cy.ts
  cypress/e2e/5-ndv.cy.ts
  cypress/pages/workflow.ts
  package.json
  pnpm-lock.yaml
Labels: n8n team

#8286 ci: Add support for optionally including ARM64 support in custom images (no-changelog)
  .github/workflows/docker-images-nightly.yml
Labels: n8n team

#8274 feat: Update @n8n/chat exports and add example images (no-changelog)
  packages/@n8n/chat/README.md
  packages/@n8n/chat/package.json
Labels: n8n team

#8266 feat(MongoDB Node): Add support for TLS
  packages/nodes-base/credentials/MongoDb.credentials.ts
  packages/nodes-base/nodes/MongoDb/GenericFunctions.ts
  packages/nodes-base/nodes/MongoDb/MongoDb.node.ts
Labels: node/improvement, n8n team

#8241 feat(Google Sheets Node): Add "By Name" option to selector for Sheets
  packages/nodes-base/nodes/Google/Sheet/GoogleSheetsTrigger.node.ts
  packages/nodes-base/nodes/Google/Sheet/v2/actions/router.ts
  packages/nodes-base/nodes/Google/Sheet/v2/actions/sheet/Sheet.resource.ts
  packages/nodes-base/nodes/Google/Sheet/v2/helpers/GoogleSheet.ts
  packages/nodes-base/nodes/Google/Sheet/v2/helpers/GoogleSheets.types.ts
  packages/nodes-base/nodes/Google/Sheet/v2/helpers/GoogleSheets.utils.ts
  packages/nodes-base/nodes/Google/Sheet/v2/methods/loadOptions.ts
  packages/nodes-base/nodes/Google/Sheet/v2/methods/resourceMapping.ts
Labels: node/improvement, n8n team

#8246 fix(MySQL Node): Only escape table names when needed
  packages/nodes-base/nodes/MySql/test/v2/utils.test.ts
  packages/nodes-base/nodes/MySql/v2/actions/database/deleteTable.operation.ts
  packages/nodes-base/nodes/MySql/v2/actions/database/insert.operation.ts
  packages/nodes-base/nodes/MySql/v2/actions/database/select.operation.ts
  packages/nodes-base/nodes/MySql/v2/actions/database/update.operation.ts
  packages/nodes-base/nodes/MySql/v2/actions/database/upsert.operation.ts
  packages/nodes-base/nodes/MySql/v2/helpers/utils.ts
  packages/nodes-base/nodes/MySql/v2/methods/loadOptions.ts
Labels: node/improvement, n8n team

#8288 fix: Store workflow settings when saving an execution
  packages/cli/src/databases/repositories/execution.repository.ts
  packages/cli/test/integration/database/repositories/execution.repository.test.ts
Labels: core, n8n team

#8289 feat(editor): Migrate deviceSupportHelpers mixin to useDeviceSupport composable (no-changelog)
  packages/design-system/src/composables/useDeviceSupport.test.ts
  packages/design-system/src/composables/useDeviceSupport.ts
  packages/editor-ui/src/components/CanvasControls.vue
  packages/editor-ui/src/components/Node.vue
  packages/editor-ui/src/components/NodeDetailsView.vue
  packages/editor-ui/src/components/Sticky.vue
  packages/editor-ui/src/composables/useCanvasMouseSelect.ts
  packages/editor-ui/src/composables/useHistoryHelper.ts
  packages/editor-ui/src/mixins/deviceSupportHelpers.ts
  packages/editor-ui/src/mixins/moveNodeWorkflow.ts
  packages/editor-ui/src/mixins/nodeBase.ts
  packages/editor-ui/src/views/NodeView.vue
Labels: ui, n8n team, tech debt

#8284 fix: Properly output saml validation errors
  packages/cli/src/sso/saml/samlValidator.ts
Labels: core, n8n team

#8294 fix: Adjust cred setup telemetry (no-changelog)
  packages/editor-ui/src/views/SetupWorkflowFromTemplateView/setupTemplate.store.ts
Labels: ui, n8n team

#8297 fix: Fix node graph telemetry with default values
  packages/workflow/src/TelemetryHelpers.ts
  packages/workflow/test/Helpers.ts
  packages/workflow/test/NodeTypes.ts
  packages/workflow/test/TelemetryHelpers.test.ts
Labels: core, n8n team

#8300 fix(API): Fix manual chat trigger execution
  packages/cli/src/TestWebhooks.ts
  packages/cli/src/workflows/workflow.service.ts
Labels: core, n8n team

#8303 fix(editor): Remove pinData mixin (no-changelog)
  packages/editor-ui/src/mixins/pinData.ts
Labels: ui, n8n team

#8304 fix: Disable `@typescript-eslint/no-use-before-define` rule (no-changelog)
  packages/@n8n_io/eslint-config/frontend.js
  packages/editor-ui/.eslintrc.js
Labels: ui, n8n team

#8310 ci: Add `@aws-sdk/credential-provider-node` and `@aws-sdk/types` modules (no-changelog)
  packages/@n8n/nodes-langchain/nodes/llms/LmChatAwsBedrock/LmChatAwsBedrock.node.ts
  packages/@n8n/nodes-langchain/package.json
  pnpm-lock.yaml
Labels: n8n team

#8302 feat: Redirect users without feature flag from template cred setup (no-changelog)
  cypress/composables/featureFlags.ts
  cypress/e2e/34-template-credentials-setup.cy.ts
  cypress/pages/template-credential-setup.ts
  cypress/pages/template-workflow.ts
  packages/editor-ui/src/stores/posthog.store.ts
  packages/editor-ui/src/utils/templates/__tests__/templateActions.test.ts
  packages/editor-ui/src/utils/templates/templateActions.ts
  packages/editor-ui/src/views/NodeView.vue
  packages/editor-ui/src/views/SetupWorkflowFromTemplateView/SetupWorkflowFromTemplateView.vue
  packages/editor-ui/src/views/SetupWorkflowFromTemplateView/setupTemplate.store.ts
Labels: ui, n8n team

#8267 feat(core): Implement inter-main communication for test webhooks in multi-main setup
  packages/cli/src/TestWebhooks.ts
  packages/cli/src/constants.ts
  packages/cli/src/push/abstract.push.ts
  packages/cli/src/push/index.ts
  packages/cli/src/push/sse.push.ts
  packages/cli/src/push/websocket.push.ts
  packages/cli/src/services/cache/cache.service.ts
  packages/cli/src/services/cache/redis.cache-manager.ts
  packages/cli/src/services/orchestration/main/MultiMainSetup.ee.ts
  packages/cli/src/services/orchestration/main/handleCommandMessageMain.ts
  packages/cli/src/services/orchestration/worker/handleCommandMessageWorker.ts
  packages/cli/src/services/redis/RedisServiceCommands.ts
  packages/cli/src/services/test-webhook-registrations.service.ts
  packages/cli/src/workflows/workflow.service.ts
  packages/cli/test/integration/workflow.service.test.ts
  packages/cli/test/unit/TestWebhooks.test.ts
  packages/cli/test/unit/push/websocket.push.test.ts
Labels: core, n8n team

#8311 fix(Supabase Node): Pagination for get all rows
  packages/nodes-base/nodes/Supabase/Supabase.node.ts
Labels: n8n team, node/issue

#8315 fix(core): Prevent invalid compressed responses from making executions stuck forever
  packages/core/src/BinaryData/utils.ts
  packages/core/test/BinaryData/utils.test.ts
Labels: core, n8n team

#8320 ci: Update the validate-n8n-pull-request-title action (no-changelog)
  .github/workflows/check-pr-title.yml
Labels: n8n team

#8308 fix: Add fallback resolver for langchain modules
  packages/@n8n/nodes-langchain/nodes/code/Code.node.ts
Labels: n8n team

#8127 feat: Implement Chat Memory Manager node
  packages/@n8n/nodes-langchain/nodes/agents/Agent/Agent.node.ts
  packages/@n8n/nodes-langchain/nodes/memory/MemoryChatRetriever/MemoryChatRetriever.node.ts
  packages/@n8n/nodes-langchain/nodes/memory/MemoryManager/MemoryManager.node.ts
  packages/@n8n/nodes-langchain/nodes/memory/MemoryMotorhead/MemoryMotorhead.node.ts
  packages/@n8n/nodes-langchain/nodes/memory/MemoryXata/MemoryXata.node.ts
  packages/@n8n/nodes-langchain/nodes/trigger/ChatTrigger/ChatTrigger.node.ts
  packages/@n8n/nodes-langchain/package.json
Labels: n8n team

#8328 docs: Update link in manual chat trigger node (no-changelog)
  packages/@n8n/nodes-langchain/nodes/trigger/ManualChatTrigger/ManualChatTrigger.node.ts
Labels: n8n team

#8313 fix(OpenAI Node): Load correct models for operation
  packages/nodes-base/nodes/OpenAi/ChatDescription.ts
  packages/nodes-base/nodes/OpenAi/ImageDescription.ts
  packages/nodes-base/nodes/OpenAi/OpenAi.node.ts
  packages/nodes-base/nodes/OpenAi/TextDescription.ts
Labels: n8n team, node/issue

#8248 refactor(core): Use DI for LDAP code (no-changelog)
  packages/cli/src/Ldap/LdapManager.ee.ts
  packages/cli/src/Ldap/LdapService.ee.ts
  packages/cli/src/Ldap/LdapSync.ee.ts
  packages/cli/src/Ldap/helpers.ts
  packages/cli/src/Ldap/ldap.controller.ts
  packages/cli/src/Ldap/ldap.service.ts
  packages/cli/src/Server.ts
  packages/cli/src/auth/methods/ldap.ts
  packages/cli/src/controllers/passwordReset.controller.ts
  packages/cli/test/integration/ldap/ldap.api.test.ts
  packages/cli/test/integration/shared/utils/testServer.ts
Labels: core, n8n team

#8327 fix(editor): Fix issue with synchronization table on LDAP not loading data
  packages/editor-ui/src/views/SettingsLdapView.vue
Labels: ui, n8n team

#8326 fix(Venafi TLS Protect Cloud Trigger Node): Handle new webhook payload format
  packages/nodes-base/nodes/Venafi/ProtectCloud/VenafiTlsProtectCloudTrigger.node.ts
Labels: node/improvement, n8n team

#8324 fix: Typos in nodes infoboxes (no-changelog)
  packages/nodes-base/nodes/Cron/Cron.node.ts
  packages/nodes-base/nodes/Interval/Interval.node.ts
  packages/nodes-base/nodes/Schedule/ScheduleTrigger.node.ts
Labels: node/improvement, n8n team

#8325 fix(Venafi TLS Protect Cloud Node): Remove parameter `Application Server Type`
  packages/nodes-base/nodes/Venafi/ProtectCloud/CertificateRequestDescription.ts
  packages/nodes-base/nodes/Venafi/ProtectCloud/VenafiTlsProtectCloud.node.ts
Labels: node/improvement, n8n team

#8337 fix(core): Replace all `moment` imports with `moment-timezone`
  packages/nodes-base/nodes/Airtable/AirtableTrigger.node.ts
  packages/nodes-base/nodes/BambooHr/v1/actions/employee/create/execute.ts
  packages/nodes-base/nodes/BambooHr/v1/actions/employee/update/execute.ts
  packages/nodes-base/nodes/Cortex/GenericFunctions.ts
  packages/nodes-base/nodes/DateTime/V2/GenericFunctions.ts
  packages/nodes-base/nodes/DateTime/test/node/DateTime.test.ts
  packages/nodes-base/nodes/Filter/V1/GenericFunctions.ts
  packages/nodes-base/nodes/GoToWebinar/GenericFunctions.ts
  packages/nodes-base/nodes/Google/Calendar/GoogleCalendarTrigger.node.ts
  packages/nodes-base/nodes/Google/Contacts/GoogleContacts.node.ts
  packages/nodes-base/nodes/Google/Drive/GoogleDriveTrigger.node.ts
  packages/nodes-base/nodes/Hubspot/V1/GenericFunctions.ts
  packages/nodes-base/nodes/Hubspot/V2/GenericFunctions.ts
  packages/nodes-base/nodes/If/V1/IfV1.node.ts
  packages/nodes-base/nodes/Mailchimp/Mailchimp.node.ts
  packages/nodes-base/nodes/Mandrill/Mandrill.node.ts
  packages/nodes-base/nodes/Nasa/Nasa.node.ts
  packages/nodes-base/nodes/Notion/NotionTrigger.node.ts
  packages/nodes-base/nodes/Orbit/Orbit.node.ts
  packages/nodes-base/nodes/Oura/Oura.node.ts
  packages/nodes-base/nodes/Paddle/Paddle.node.ts
  packages/nodes-base/nodes/RssFeedRead/RssFeedReadTrigger.node.ts
  packages/nodes-base/nodes/SeaTable/SeaTableTrigger.node.ts
  packages/nodes-base/nodes/SecurityScorecard/SecurityScorecard.node.ts
  packages/nodes-base/nodes/Slack/V1/SlackV1.node.ts
  packages/nodes-base/nodes/Slack/V2/SlackV2.node.ts
  packages/nodes-base/nodes/Spontit/Spontit.node.ts
  packages/nodes-base/nodes/Strava/Strava.node.ts
  packages/nodes-base/nodes/TheHive/GenericFunctions.ts
  packages/nodes-base/nodes/Toggl/TogglTrigger.node.ts
  packages/nodes-base/nodes/Twist/Twist.node.ts
  packages/nodes-base/nodes/UnleashedSoftware/UnleashedSoftware.node.ts
  packages/nodes-base/nodes/Venafi/Datacenter/VenafiTlsProtectDatacenterTrigger.node.ts
  packages/nodes-base/package.json
  pnpm-lock.yaml
Labels: node/improvement, n8n team

#7642 fix(Google Drive Node): Fix issue preventing service account from downloading files
  packages/nodes-base/nodes/Google/Drive/test/v2/node/file/download.test.ts
  packages/nodes-base/nodes/Google/Drive/v2/actions/file/download.operation.ts
  packages/nodes-base/nodes/Google/Drive/v2/transport/index.ts
Labels: node/improvement, n8n team

#8312 fix(AwsS3 Node): Return confirmation of success after upload
  packages/nodes-base/nodes/Aws/S3/V2/AwsS3V2.node.ts
Labels: n8n team, node/issue

#8334 fix(Microsoft SQL Node): Fix "Maximum call stack size exceeded" error on too many rows
  packages/nodes-base/nodes/Microsoft/Sql/MicrosoftSql.node.ts
Labels: node/improvement, n8n team

#8227 feat(editor): Add new `/templates/search` endpoint
  cypress/e2e/29-templates.cy.ts
  cypress/fixtures/templates_search/all_templates_search_response.json
  cypress/fixtures/templates_search/sales_templates_search_response.json
  cypress/fixtures/templates_search/test_template_import.json
  cypress/fixtures/templates_search/test_template_preview.json
  cypress/pages/templates.ts
  packages/editor-ui/src/Interface.ts
  packages/editor-ui/src/api/templates.ts
  packages/editor-ui/src/components/TemplateFilters.vue
  packages/editor-ui/src/components/TemplateList.vue
  packages/editor-ui/src/stores/templates.store.ts
  packages/editor-ui/src/views/TemplatesSearchView.vue
Labels: ui, n8n team

#8338 fix: Change setup credentials modal title (no-changelog)
  packages/editor-ui/src/plugins/i18n/locales/en.json
Labels: ui, n8n team

#8329 fix(core): Account for immediate confirmation request during test webhook creation
  packages/cli/src/TestWebhooks.ts
  packages/cli/test/unit/TestWebhooks.test.ts
Labels: core, n8n team

#8292 refactor(core): Eliminate dead Redis code (no-changelog)
  packages/cli/src/services/redis.service.ts
  packages/cli/src/services/redis/RedisServiceListReceiver.ts
  packages/cli/src/services/redis/RedisServiceListSender.ts
  packages/cli/src/services/redis/RedisServiceStreamConsumer.ts
  packages/cli/src/services/redis/RedisServiceStreamProducer.ts
  packages/cli/test/unit/services/redis.service.test.ts
Labels: core, n8n team

#8299 refactor: Make execution IDs mandatory in BE
  packages/cli/src/ActiveExecutions.ts
  packages/cli/src/Interfaces.ts
  packages/cli/src/PublicApi/v1/handlers/executions/executions.handler.ts
  packages/cli/src/ResponseHelper.ts
  packages/cli/src/WaitTracker.ts
  packages/cli/src/WaitingWebhooks.ts
  packages/cli/src/WorkflowExecuteAdditionalData.ts
  packages/cli/src/WorkflowRunnerProcess.ts
  packages/cli/src/commands/start.ts
  packages/cli/src/commands/worker.ts
  packages/cli/src/config/schema.ts
  packages/cli/src/databases/repositories/execution.repository.ts
  packages/cli/src/executionLifecycleHooks/shared/sharedHookFunctions.ts
  packages/cli/src/executions/executions.service.ts
  packages/cli/test/unit/WaitTracker.test.ts
  packages/workflow/src/Interfaces.ts
Labels: core, n8n team

#8319 refactor(core): Move `typeorm` operators from Public API (no-changelog)
  packages/cli/src/PublicApi/v1/handlers/executions/executions.handler.ts
  packages/cli/src/PublicApi/v1/handlers/executions/executions.service.ts
  packages/cli/src/databases/repositories/execution.repository.ts
  packages/cli/src/databases/types.ts
  packages/cli/src/executions/executions.service.ts
Labels: core, n8n team

#8344 refactor(core): Use DI in PermissionChecker (no-changelog)
  packages/cli/src/UserManagement/PermissionChecker.ts
  packages/cli/src/WorkflowExecuteAdditionalData.ts
  packages/cli/src/WorkflowHelpers.ts
  packages/cli/src/WorkflowRunner.ts
  packages/cli/src/WorkflowRunnerProcess.ts
  packages/cli/src/commands/worker.ts
  packages/cli/test/unit/PermissionChecker.test.ts
Labels: core, n8n team

#8301 fix(core): Prevent NodeErrors from being wrapped multiple times
  packages/workflow/src/errors/abstract/node.error.ts
  packages/workflow/test/errors/node.error.test.ts
Labels: core, n8n team

#8349 refactor(core): Consolidate executions controllers (no-changelog)
  packages/cli/src/Server.ts
  packages/cli/src/controllers/workflowStatistics.controller.ts
  packages/cli/src/executions/execution.request.ts
  packages/cli/src/executions/executions.controller.ee.ts
  packages/cli/src/executions/executions.controller.ts
  packages/cli/src/executions/executions.service.ee.ts
  packages/cli/src/executions/executions.service.ts
  packages/cli/src/requests.ts
  packages/cli/test/integration/shared/utils/testServer.ts
Labels: core, n8n team

#8332 fix(core): Prevent issues with missing or mismatching encryption key
  packages/cli/src/commands/worker.ts
  packages/cli/src/config/index.ts
  packages/cli/test/setup-test-folder.ts
  packages/core/src/Credentials.ts
  packages/core/src/InstanceSettings.ts
  packages/core/test/InstanceSettings.test.ts
  packages/nodes-base/nodes/HttpRequest/V3/HttpRequestV3.node.ts
Labels: core, n8n team

#8340 fix(core): Ensure waiting executions account for workflow timezone
  packages/core/package.json
  packages/core/src/NodeExecuteFunctions.ts
  packages/core/src/utils.ts
  packages/core/test/utils.test.ts
  pnpm-lock.yaml
Labels: core, n8n team

#8269 feat(Redis Node): Update node-redis (no-changelog)
  packages/@n8n/nodes-langchain/package.json
  packages/nodes-base/nodes/Redis/Redis.node.ts
  packages/nodes-base/nodes/Redis/RedisTrigger.node.ts
  packages/nodes-base/nodes/Redis/test/Redis.node.test.ts
  packages/nodes-base/nodes/Redis/utils.ts
  packages/nodes-base/package.json
  pnpm-lock.yaml
Labels: node/improvement, n8n team

#8348 refactor(core): Move methods from WorkflowHelpers into various workflow services (no-changelog)
  packages/cli/src/Server.ts
  packages/cli/src/WorkflowExecuteAdditionalData.ts
  packages/cli/src/WorkflowHelpers.ts
  packages/cli/src/WorkflowRunner.ts
  packages/cli/src/executions/executions.service.ee.ts
  packages/cli/src/executions/executions.service.ts
  packages/cli/src/services/userOnboarding.service.ts
  packages/cli/src/workflows/workflow.service.ee.ts
  packages/cli/src/workflows/workflow.service.ts
  packages/cli/src/workflows/workflowExecution.service.ts
  packages/cli/src/workflows/workflowSharing.service.ts
  packages/cli/src/workflows/workflowStaticData.service.ts
  packages/cli/src/workflows/workflows.controller.ts
  packages/cli/test/integration/executions.controller.test.ts
  packages/cli/test/integration/shared/workflow.ts
  packages/cli/test/integration/workflows/workflow.service.ee.test.ts
  packages/cli/test/integration/workflows/workflow.service.test.ts
  packages/cli/test/integration/workflows/workflows.controller.ee.test.ts
  packages/cli/test/integration/workflows/workflows.controller.test.ts
  packages/cli/test/unit/WorkflowHelpers.test.ts
  packages/cli/test/unit/services/workflowHistory.service.ee.test.ts
Labels: core, n8n team

#8331 fix(editor): Capture indexed access expressions when building completions
  packages/editor-ui/src/plugins/codemirror/completions/__tests__/completions.test.ts
  packages/editor-ui/src/plugins/codemirror/completions/datatype.completions.ts
  packages/editor-ui/src/plugins/codemirror/completions/utils.ts
Labels: ui, n8n team

#8359 fix(core): Parse any readable stream response instead of only IncomingMessage
  packages/core/src/NodeExecuteFunctions.ts
Labels: core, n8n team

#8346 fix(Salesforce Node): Upgrade to API version 59
  packages/nodes-base/nodes/Salesforce/GenericFunctions.ts
  test-results.json
Labels: node/improvement, n8n team

#8350 docs(Discord Node): Better OAuth description (no-changelog)
  packages/nodes-base/nodes/Discord/v2/actions/versionDescription.ts
Labels: node/improvement, n8n team

#8356 fix(core): Report when waitTill is invalid and handle it
  packages/cli/src/WaitTracker.ts
Labels: core, n8n team

#8361 test(core): Fix cleanup in test teardown script (no-changelog)
  packages/cli/src/config/index.ts
  packages/cli/test/setup-test-folder.ts
Labels: core, n8n team

#8238 fix(Microsoft Outlook Node): Message -> Send with attachments
  packages/nodes-base/nodes/Microsoft/Outlook/v2/actions/message/reply.operation.ts
  packages/nodes-base/nodes/Microsoft/Outlook/v2/actions/message/send.operation.ts
Labels: n8n team, node/issue

#8358 refactor(core): Use DI in execution services (no-changelog)
  packages/cli/src/ActiveWorkflowRunner.ts
  packages/cli/src/executions/execution.service.ee.ts
  packages/cli/src/executions/execution.service.ts
  packages/cli/src/executions/executions.controller.ts
  packages/cli/test/integration/ActiveWorkflowRunner.test.ts
  packages/cli/test/integration/executions.controller.test.ts
  packages/cli/test/integration/publicApi/workflows.test.ts
  packages/cli/test/integration/shared/utils/index.ts
  packages/cli/test/integration/users.api.test.ts
Labels: core, n8n team

#8365 feat(core): Upgrade bull and ioredis to address CVE-2023-52079
  packages/cli/package.json
  pnpm-lock.yaml
Labels: core, n8n team

#8360 fix: Change the UI text for some filter operations
  packages/editor-ui/src/plugins/i18n/locales/en.json
  packages/nodes-base/nodes/Switch/V3/SwitchV3.node.ts
  packages/nodes-base/nodes/TheHiveProject/descriptions/filter.description.ts
Labels: node/improvement, ui, n8n team

#8378 fix: Fix issue preventing secrets with a - in the path from being imported
  packages/cli/src/ExternalSecrets/constants.ts
Labels: core, n8n team

#8374 fix: Force posthog recording to be disabled outside cloud
  packages/cli/src/config/schema.ts
  packages/cli/src/services/frontend.service.ts
Labels: core, n8n team

#8384 feat(core): Upgrade swagger (no-changelog)
  packages/cli/package.json
  packages/cli/scripts/build.mjs
  pnpm-lock.yaml
Labels: core, n8n team

#8370 fix(editor): Open native context menu when editing Sticky
  packages/editor-ui/src/components/Sticky.vue
Labels: ui, n8n team

#8380 fix(core): Errors are returned on the success branch if error item has other keys in addition to 'error'
  packages/core/src/WorkflowExecute.ts
Labels: core, n8n team, node/issue

#8386 fix(core): Adjust starter node priority for manual executions with pinned activators
  packages/cli/src/workflows/workflowExecution.service.ts
  packages/cli/test/unit/workflow-execution.service.test.ts
Labels: core, n8n team

#8395 fix(editor): Use cursor pointer on close icon (no-changelog)
  packages/editor-ui/src/components/BecomeTemplateCreatorCta/BecomeTemplateCreatorCta.vue
Labels: ui, n8n team

#8385 fix(editor): Use web native <a> element in nav menus
  packages/design-system/package.json
  packages/design-system/src/components/ConditionalRouterLink/CondtionalRouterLink.vue
  packages/design-system/src/components/ConditionalRouterLink/__tests__/ConditionalRouterLink.spec.ts
  packages/design-system/src/components/ConditionalRouterLink/__tests__/__snapshots__/ConditionalRouterLink.spec.ts.snap
  packages/design-system/src/components/ConditionalRouterLink/index.ts
  packages/design-system/src/components/N8nMenu/Menu.stories.ts
  packages/design-system/src/components/N8nMenu/Menu.vue
  packages/design-system/src/components/N8nMenuItem/MenuItem.stories.ts
  packages/design-system/src/components/N8nMenuItem/MenuItem.vue
  packages/design-system/src/components/N8nMenuItem/routerUtil.ts
  packages/design-system/src/types/menu.ts
  packages/editor-ui/src/Interface.ts
  packages/editor-ui/src/components/MainSidebar.vue
  packages/editor-ui/src/components/SettingsSidebar.vue
  packages/editor-ui/src/components/__tests__/ExecutionsList.test.ts
  packages/editor-ui/src/components/__tests__/RBAC.test.ts
  packages/editor-ui/src/composables/__tests__/useHistoryHelper.test.ts
  packages/editor-ui/src/router.ts
  packages/editor-ui/src/stores/ui.store.ts
  packages/editor-ui/src/views/__tests__/SamlOnboarding.test.ts
  packages/editor-ui/src/views/__tests__/WorkflowHistory.test.ts
  pnpm-lock.yaml
Labels: ui, n8n team

#8382 fix(AWS SQS Node): Fix issue preventing data from being sent correctly
  packages/nodes-base/nodes/Aws/SQS/AwsSqs.node.ts
Labels: node/improvement, n8n team

#8396 fix(AMQP Trigger Node): Properly close connection after manual test step
  packages/nodes-base/nodes/Amqp/AmqpTrigger.node.ts
Labels: n8n team, node/issue

#8394 fix(core): Missing pairedItem fixes
  packages/nodes-base/nodes/Airtable/v1/AirtableV1.node.ts
  packages/nodes-base/nodes/Airtable/v1/GenericFunctions.ts
  packages/nodes-base/nodes/Airtable/v2/actions/record/search.operation.ts
  packages/nodes-base/nodes/Airtable/v2/transport/index.ts
  packages/nodes-base/nodes/Merge/v1/MergeV1.node.ts
  packages/nodes-base/nodes/Merge/v2/MergeV2.node.ts
  packages/nodes-base/nodes/NocoDB/GenericFunctions.ts
  packages/nodes-base/nodes/NocoDB/NocoDB.node.ts
  packages/nodes-base/nodes/Notion/GenericFunctions.ts
  packages/nodes-base/nodes/Notion/v2/NotionV2.node.ts
  packages/nodes-base/nodes/Redis/Redis.node.ts
  packages/nodes-base/nodes/Set/v1/SetV1.node.ts
Labels: n8n team, node/issue

#8387 fix(editor): Enable ctrl/cmd click in workflow editor header
  packages/design-system/src/components/N8nRadioButtons/RadioButtons.vue
  packages/editor-ui/src/components/MainHeader/MainHeader.vue
Labels: ui, n8n team

#8161 feat(editor): Add additional email domains to our disallowed list for self-serve enterprise license (no-changelog)
  packages/editor-ui/package.json
  packages/editor-ui/src/components/PersonalizationModal.vue
  pnpm-lock.yaml
Labels: ui, n8n team

#8390 fix(Microsoft SQL Node): Prevent MSSQL max parameters error by chunking
  packages/nodes-base/nodes/Microsoft/Sql/GenericFunctions.ts
  packages/nodes-base/nodes/Microsoft/Sql/test/utils.test.ts
Labels: node/improvement, n8n team

#8389 feat(Execute Workflow Node): Add 'Wait For Sub-Workflow Completion' option
  packages/nodes-base/nodes/ExecuteWorkflow/ExecuteWorkflow.node.ts
Labels: node/improvement, n8n team

#8323 fix(editor): Add pinned data for freshly added nodes
  cypress/e2e/19-execution.cy.ts
  packages/editor-ui/src/composables/useNodeHelpers.ts
  packages/editor-ui/src/utils/nodeViewUtils.ts
  packages/editor-ui/src/views/NodeView.vue
Labels: ui, n8n team

#8392 fix(editor): Rename `Execute previous nodes` label to `Test previous nodes` (no-changelog)
  packages/editor-ui/src/plugins/i18n/locales/en.json
Labels: ui, n8n team

#8322 feat(editor): Migrate `moveNodeWorkflow` mixin to `useCanvasPanning` composable
  packages/editor-ui/src/composables/__tests__/useCanvasPanning.test.ts
  packages/editor-ui/src/composables/useCanvasPanning.ts
  packages/editor-ui/src/constants.ts
  packages/editor-ui/src/mixins/moveNodeWorkflow.ts
  packages/editor-ui/src/views/NodeView.vue
Labels: ui, n8n team

#8278 fix: Fix issue with pnpm run watch not working (no-changelog)
  package.json
Labels: n8n team

#8398 fix: Fix openapi generation (no-changelog)
  packages/cli/scripts/build.mjs
Labels: core, n8n team

#8399 docs(editor): All buttons to sentence case (no-changelog)
  cypress/constants.ts
  cypress/e2e/36-suggested-templates.cy.ts
  cypress/e2e/4-node-creator.cy.ts
  cypress/e2e/5-ndv.cy.ts
  cypress/fixtures/Floating_Nodes.json
  cypress/fixtures/Lots_of_nodes.json
  cypress/fixtures/Node_IO_filter.json
  cypress/fixtures/Suggested_Templates.json
  cypress/fixtures/Test_workflow_5.json
  cypress/fixtures/Test_workflow_filter.json
  cypress/fixtures/Test_workflow_ndv_version.json
  cypress/fixtures/Test_workflow_schema_test.json
  cypress/fixtures/Test_workflow_schema_test_pinned_data.json
  cypress/fixtures/Test_workflow_webhook_with_pin_data.json
  cypress/fixtures/Test_workflow_xml_output.json
  cypress/fixtures/expression_with_paired_item_in_multi_input_node.json
  cypress/fixtures/workflow-with-unknown-credentials.json
  cypress/fixtures/workflow-with-unknown-nodes.json
  packages/cli/templates/form-trigger-404.handlebars
  packages/editor-ui/src/plugins/i18n/locales/en.json
  packages/nodes-base/nodes/Form/common.descriptions.ts
  packages/nodes-base/nodes/ManualTrigger/ManualTrigger.node.ts
  packages/workflow/test/TelemetryHelpers.test.ts
Labels: node/improvement, core, ui, n8n team

#8401 fix(core): Fix trigger and poller activation on vacant leadership
  packages/cli/src/commands/start.ts
  packages/cli/src/services/orchestration/main/MultiMainSetup.ee.ts
Labels: core, n8n team

#8342 feat(core): Custom session timeout and refresh configuration
  packages/cli/src/Interfaces.ts
  packages/cli/src/auth/jwt.ts
  packages/cli/src/config/index.ts
  packages/cli/src/config/schema.ts
  packages/cli/src/constants.ts
  packages/cli/src/middlewares/auth.ts
  packages/cli/test/unit/auth/jwt.test.ts
  packages/cli/test/unit/config/index.test.ts
  packages/cli/test/unit/middleware/auth.test.ts
Labels: core, n8n team

#8377 fix(Discord Node): Remove requirement on message for webhooks
  packages/nodes-base/nodes/Discord/v2/actions/webhook/sendLegacy.operation.ts
Labels: node/improvement, community

#8406 fix(editor): Fix invisible community package update button
  packages/editor-ui/src/components/CommunityPackageCard.vue
Labels: ui, n8n team

#8364 refactor(core): Simplify `OrchestrationService` (no-changelog)
  packages/cli/src/ActiveWorkflowRunner.ts
  packages/cli/src/ExternalSecrets/ExternalSecretsManager.ee.ts
  packages/cli/src/License.ts
  packages/cli/src/Server.ts
  packages/cli/src/TestWebhooks.ts
  packages/cli/src/commands/start.ts
  packages/cli/src/controllers/debug.controller.ts
  packages/cli/src/controllers/orchestration.controller.ts
  packages/cli/src/eventbus/MessageEventBus/MessageEventBus.ts
  packages/cli/src/push/abstract.push.ts
  packages/cli/src/push/sse.push.ts
  packages/cli/src/push/websocket.push.ts
  packages/cli/src/services/orchestration.base.service.ts
  packages/cli/src/services/orchestration.service.ts
  packages/cli/src/services/orchestration/main/MultiMainSetup.ee.ts
  packages/cli/src/services/orchestration/main/SingleMainSetup.ts
  packages/cli/src/services/orchestration/main/handleCommandMessageMain.ts
  packages/cli/src/services/orchestration/webhook/orchestration.webhook.service.ts
  packages/cli/src/services/orchestration/worker/orchestration.worker.service.ts
  packages/cli/src/services/pruning.service.ts
  packages/cli/src/workflows/workflow.service.ts
  packages/cli/test/integration/ActiveWorkflowRunner.test.ts
  packages/cli/test/integration/commands/worker.cmd.test.ts
  packages/cli/test/integration/debug.controller.test.ts
  packages/cli/test/integration/shared/utils/index.ts
  packages/cli/test/integration/workflows/workflow.service.test.ts
  packages/cli/test/unit/License.test.ts
  packages/cli/test/unit/services/orchestration.service.test.ts
Labels: core, n8n team

#8407 fix(editor): Fix secondary icon for environments on sidebar menu item
  packages/design-system/src/components/N8nMenuItem/MenuItem.vue
  packages/design-system/src/components/N8nTooltip/Tooltip.vue
  packages/editor-ui/src/plugins/i18n/locales/en.json
Labels: ui, n8n team

#8405 fix(editor): Fix doclines for `plus` and `minus`
  packages/workflow/src/Extensions/DateExtensions.ts
Labels: core, n8n team

#8369 feat: Extend collection of usage metrics during license renewal (no-changelog)
  packages/cli/src/License.ts
  packages/cli/src/controllers/auth.controller.ts
  packages/cli/src/controllers/invitation.controller.ts
  packages/cli/src/controllers/users.controller.ts
  packages/cli/src/databases/repositories/usageMetrics.repository.ts
  packages/cli/src/databases/repositories/user.repository.ts
  packages/cli/src/services/usageMetrics.service.ts
  packages/cli/test/integration/shared/db/credentials.ts
  packages/cli/test/integration/usageMetrics.repository.test.ts
Labels: core, n8n team

#8397 fix(Notion Node): Fix is_empty query on formula fields
  packages/nodes-base/nodes/Notion/GenericFunctions.ts
Labels: node/improvement, n8n team

#8404 fix(Asana Node): Fix issue when connecting to the new Asana environment
  packages/nodes-base/nodes/Asana/Asana.node.ts
  packages/nodes-base/nodes/Asana/AsanaTrigger.node.ts
  packages/nodes-base/nodes/Asana/GenericFunctions.ts
Labels: node/improvement, n8n team
