Repository n8n-io/n8n, pull requests merged in 2024-10, with the labels that each got.

#11023 test(n8n Form Trigger Node): Add tests, extract testing util for webhook triggers (no-changelog)
  packages/nodes-base/nodes/Form/test/FormTriggerV2.node.test.ts
  packages/nodes-base/nodes/Form/test/utils.test.ts
  packages/nodes-base/nodes/Schedule/test/ScheduleTrigger.node.test.ts
  packages/nodes-base/test/nodes/TriggerHelpers.ts
Labels: node/improvement, n8n team

#11032 feat(editor): Support node-creator actions for vector store nodes
  cypress/composables/workflow.ts
  cypress/e2e/4-node-creator.cy.ts
  packages/@n8n/nodes-langchain/nodes/vector_store/shared/createVectorStoreNode.ts
  packages/editor-ui/src/components/Node/NodeCreator/ItemTypes/NodeItem.vue
  packages/editor-ui/src/components/Node/NodeCreator/Modes/NodesMode.vue
  packages/editor-ui/src/components/Node/NodeCreator/composables/useActionsGeneration.ts
  packages/editor-ui/src/components/Node/NodeCreator/composables/useViewStacks.ts
Labels: ui, n8n team

#11020 feat(editor): Remove execution annotation feature flag
  packages/editor-ui/src/components/executions/ExecutionsFilter.vue
  packages/editor-ui/src/components/executions/global/GlobalExecutionsList.vue
  packages/editor-ui/src/components/executions/workflow/WorkflowExecutionsCard.vue
  packages/editor-ui/src/components/executions/workflow/WorkflowExecutionsPreview.vue
  packages/editor-ui/src/constants.ts
Labels: ui, n8n team

#11039 fix(editor): Fix success state for disabled nodes in new canvas (no-changelog)
  packages/editor-ui/src/components/canvas/elements/nodes/render-types/CanvasNodeDefault.vue
  packages/editor-ui/src/components/canvas/elements/nodes/render-types/parts/CanvasNodeDisabledStrikeThrough.vue
Labels: ui, n8n team

#11024 fix(core): Fix new partial execution flow not working with workflows with multiple disabled nodes in a row (no-changelog)
  packages/core/src/PartialExecutionUtils/DirectedGraph.ts
  packages/core/src/PartialExecutionUtils/__tests__/DirectedGraph.test.ts
  packages/core/src/PartialExecutionUtils/__tests__/findSubgraph.test.ts
  packages/core/src/PartialExecutionUtils/findSubgraph.ts
  packages/core/src/PartialExecutionUtils/recreateNodeExecutionStack.ts
Labels: core, n8n team

#11014 feat: Add more context to support chat
  packages/editor-ui/src/components/CredentialEdit/CredentialConfig.vue
  packages/editor-ui/src/components/CredentialEdit/CredentialEdit.vue
  packages/editor-ui/src/components/Error/NodeErrorView.vue
  packages/editor-ui/src/composables/__tests__/useAIAssistantHelpers.test.ts
  packages/editor-ui/src/composables/useAIAssistantHelpers.ts
  packages/editor-ui/src/plugins/i18n/locales/en.json
  packages/editor-ui/src/stores/assistant.store.ts
  packages/editor-ui/src/stores/ui.store.ts
  packages/editor-ui/src/types/assistant.types.ts
  packages/editor-ui/src/utils/nodeTypesUtils.ts
Labels: ui, n8n team

#11050 refactor(core): Bring job options into scaling service
  packages/cli/src/scaling/__tests__/scaling.service.test.ts
  packages/cli/src/scaling/scaling.service.ts
  packages/cli/src/workflow-runner.ts
Labels: core, n8n team

#11051 fix(core): Fix ownerless project case in statistics service
  packages/cli/src/services/__tests__/workflow-statistics.service.test.ts
  packages/cli/src/services/workflow-statistics.service.ts
Labels: core, n8n team

#10698 feat: Initial Code Task Runners support (no-changelog)
  packages/@n8n/config/src/configs/runners.config.ts
  packages/@n8n/config/src/index.ts
  packages/@n8n/config/test/config.test.ts
  packages/@n8n/task-runner-node-js/.eslintrc.js
  packages/@n8n/task-runner-node-js/jest.config.js
  packages/@n8n/task-runner-node-js/package.json
  packages/@n8n/task-runner-node-js/src/authenticator.ts
  packages/@n8n/task-runner-node-js/src/code.ts
  packages/@n8n/task-runner-node-js/src/index.ts
  packages/@n8n/task-runner-node-js/src/runner-types.ts
  packages/@n8n/task-runner-node-js/src/start.ts
  packages/@n8n/task-runner-node-js/src/task-runner.ts
  packages/@n8n/task-runner-node-js/tsconfig.build.json
  packages/@n8n/task-runner-node-js/tsconfig.json
  packages/cli/package.json
  packages/cli/src/abstract-server.ts
  packages/cli/src/commands/start.ts
  packages/cli/src/runners/__tests__/task-broker.test.ts
  packages/cli/src/runners/auth/__tests__/task-runner-auth.controller.test.ts
  packages/cli/src/runners/auth/__tests__/task-runner-auth.service.test.ts
  packages/cli/src/runners/auth/task-runner-auth.controller.ts
  packages/cli/src/runners/auth/task-runner-auth.schema.ts
  packages/cli/src/runners/auth/task-runner-auth.service.ts
  packages/cli/src/runners/errors.ts
  packages/cli/src/runners/runner-types.ts
  packages/cli/src/runners/runner-ws-server.ts
  packages/cli/src/runners/task-broker.service.ts
  packages/cli/src/runners/task-managers/single-main-task-manager.ts
  packages/cli/src/runners/task-managers/task-manager.ts
  packages/cli/src/server.ts
  packages/cli/src/services/cache/cache.service.ts
  packages/cli/src/workflow-execute-additional-data.ts
  packages/cli/src/workflow-runner.ts
  packages/core/src/Agent/index.ts
  packages/core/src/NodeExecuteFunctions.ts
  packages/nodes-base/nodes/Code/Code.node.ts
  packages/nodes-base/package.json
  packages/workflow/src/Interfaces.ts
  pnpm-lock.yaml
Labels: node/improvement, core, n8n team

#9238 feat(Invoice Ninja Node): Add more query params to getAll requests
  packages/nodes-base/nodes/InvoiceNinja/ClientDescription.ts
  packages/nodes-base/nodes/InvoiceNinja/InvoiceDescription.ts
  packages/nodes-base/nodes/InvoiceNinja/InvoiceNinja.node.ts
  packages/nodes-base/nodes/InvoiceNinja/PaymentDescription.ts
  packages/nodes-base/nodes/InvoiceNinja/QuoteDescription.ts
Labels: node/improvement, community

#11049 fix(Github Document Loader Node): Pass through apiUrl from credentials & fix log output
  packages/@n8n/nodes-langchain/nodes/document_loaders/DocumentGithubLoader/DocumentGithubLoader.node.ts
Labels: n8n team

#7033 feat: Add Sysdig API credentials for SecOps
  packages/nodes-base/credentials/SysdigApi.credentials.ts
  packages/nodes-base/credentials/icons/Sysdig.Black.svg
  packages/nodes-base/credentials/icons/Sysdig.White.svg
  packages/nodes-base/package.json
Labels: community

#10862 feat(core): Implement Dynamic Parameters within regular nodes used as AI Tools
  packages/core/src/CreateNodeAsTool.ts
  packages/core/src/NodeExecuteFunctions.ts
  packages/core/test/CreateNodeAsTool.test.ts
  packages/editor-ui/src/composables/useToast.ts
  packages/editor-ui/src/constants.ts
  packages/editor-ui/src/plugins/codemirror/completions/__tests__/completions.test.ts
  packages/editor-ui/src/plugins/codemirror/completions/constants.ts
  packages/editor-ui/src/styles/plugins/_codemirror.scss
  packages/nodes-base/nodes/Airtable/v2/AirtableV2.node.ts
  packages/nodes-base/nodes/Airtable/v2/actions/record/Record.resource.ts
  packages/nodes-base/nodes/Baserow/Baserow.node.ts
  packages/nodes-base/nodes/EmailSend/v2/EmailSendV2.node.ts
  packages/nodes-base/nodes/Google/Calendar/GoogleCalendar.node.ts
  packages/nodes-base/nodes/Google/Docs/GoogleDocs.node.ts
  packages/nodes-base/nodes/Google/Drive/v2/actions/versionDescription.ts
  packages/nodes-base/nodes/Google/Gmail/v2/GmailV2.node.ts
  packages/nodes-base/nodes/Google/Sheet/v2/actions/versionDescription.ts
  packages/nodes-base/nodes/HackerNews/HackerNews.node.ts
  packages/nodes-base/nodes/Jira/Jira.node.ts
  packages/nodes-base/nodes/Microsoft/Outlook/v2/actions/node.description.ts
  packages/nodes-base/nodes/Microsoft/Sql/MicrosoftSql.node.ts
  packages/nodes-base/nodes/MongoDb/MongoDb.node.ts
  packages/nodes-base/nodes/MySql/v2/actions/versionDescription.ts
  packages/nodes-base/nodes/NocoDB/NocoDB.node.ts
  packages/nodes-base/nodes/Notion/v2/VersionDescription.ts
  packages/nodes-base/nodes/Postgres/v2/actions/versionDescription.ts
  packages/nodes-base/nodes/Redis/Redis.node.ts
  packages/nodes-base/nodes/Slack/V2/SlackV2.node.ts
  packages/nodes-base/nodes/Supabase/Supabase.node.ts
  packages/nodes-base/nodes/Telegram/Telegram.node.ts
  packages/nodes-base/nodes/WooCommerce/WooCommerce.node.ts
  packages/workflow/src/NodeHelpers.ts
  packages/workflow/src/WorkflowDataProxy.ts
  packages/workflow/test/NodeHelpers.test.ts
Labels: node/improvement, core, ui, n8n team

#11058 chore: Exclude `@n8n/task-runner` from global dev script (no-changelog)
  package.json
Labels: n8n team

#11015 feat: Make task runners work with n8n from npm (no-changelog)
  packages/@n8n/task-runner-node-js/package.json
  packages/@n8n/task-runner-node-js/src/start.ts
  packages/cli/src/commands/start.ts
  packages/cli/src/runners/runner-ws-server.ts
  packages/cli/src/runners/task-runner-process.ts
  packages/cli/test/integration/runners/task-runner-process.test.ts
  packages/cli/test/integration/shared/utils/task-runner-test-server.ts
Labels: core, n8n team

#11030 fix(editor): Format action names properly when action is not defined
  cypress/e2e/26-resource-locator.cy.ts
  packages/editor-ui/package.json
  packages/editor-ui/src/components/Node/NodeCreator/__tests__/utils.test.ts
  packages/editor-ui/src/components/Node/NodeCreator/composables/useActionsGeneration.ts
  packages/editor-ui/src/components/Node/NodeCreator/utils.ts
  pnpm-lock.yaml
Labels: ui, n8n team

#11053 chore: Add `verbose` removal to breaking changes
  packages/cli/BREAKING-CHANGES.md
Labels: core, n8n team

#11062 feat: Separate task runner server from main http server (no-changelog)
  packages/@n8n/config/src/configs/runners.config.ts
  packages/@n8n/config/test/config.test.ts
  packages/@n8n/task-runner-node-js/src/start.ts
  packages/cli/src/abstract-server.ts
  packages/cli/src/commands/start.ts
  packages/cli/src/constants.ts
  packages/cli/src/runners/task-runner-process.ts
  packages/cli/src/runners/task-runner-server.ts
  packages/cli/src/server.ts
  packages/cli/test/integration/runners/task-runner-process.test.ts
  packages/cli/test/integration/shared/utils/task-runner-test-server.ts
Labels: core, n8n team

#11067 ci: `@n8n/task-runner` package setup (no-changelog)
  packages/@n8n/task-runner-node-js/package.json
  packages/@n8n/task-runner/.eslintrc.js
  packages/@n8n/task-runner/jest.config.js
  packages/@n8n/task-runner/package.json
  packages/@n8n/task-runner/src/authenticator.ts
  packages/@n8n/task-runner/src/code.ts
  packages/@n8n/task-runner/src/index.ts
  packages/@n8n/task-runner/src/runner-types.ts
  packages/@n8n/task-runner/src/start.ts
  packages/@n8n/task-runner/src/task-runner.ts
  packages/@n8n/task-runner/tsconfig.build.json
  packages/@n8n/task-runner/tsconfig.json
  pnpm-lock.yaml
Labels: n8n team

#11059 fix(n8n Form Trigger Node): When clicking on a multiple choice label, the wrong one is selected
  packages/nodes-base/nodes/Form/test/utils.test.ts
  packages/nodes-base/nodes/Form/utils.ts
Labels: n8n team, node/issue

#11029 fix(editor): Respect tag querystring filter when listing workflows
  cypress/e2e/1-workflows.cy.ts
  packages/editor-ui/src/views/WorkflowsView.test.ts
  packages/editor-ui/src/views/WorkflowsView.vue
Labels: ui, n8n team

#11072 fix: Use 127.0.0.1 as n8n uri for task runner process (no-changelog)
  packages/cli/src/runners/task-runner-process.ts
Labels: core, n8n team

#11064 test(editor): Add test render helper to design system
  packages/design-system/src/__tests__/render.ts
  packages/design-system/src/__tests__/setup.ts
Labels: ui, n8n team

#11066 chore: Anonymise ip addresses in rudderstack events
  packages/cli/src/telemetry/__tests__/telemetry.test.ts
  packages/cli/src/telemetry/index.ts
  packages/editor-ui/src/plugins/__tests__/telemetry.test.ts
  packages/editor-ui/src/plugins/telemetry/index.ts
Labels: core, ui, n8n team

#11040 fix(editor): Fix design system form element sizing
  packages/design-system/src/components/N8nFormBox/__tests__/FormBox.test.ts
  packages/design-system/src/components/N8nFormBox/__tests__/__snapshots__/FormBox.test.ts.snap
  packages/design-system/src/components/N8nFormInput/FormInput.vue
  packages/design-system/src/components/N8nFormInputs/FormInputs.vue
  packages/design-system/src/components/N8nInput/Input.vue
  packages/design-system/src/types/form.ts
Labels: ui, n8n team

#11044 test(HTTP Request Node): Improve http request node testing (no-changelog)
  packages/nodes-base/nodes/HttpRequest/V3/Description.ts
  packages/nodes-base/nodes/HttpRequest/V3/HttpRequestV3.node.ts
  packages/nodes-base/nodes/HttpRequest/test/node/HttpRequestV3.test.ts
  packages/nodes-base/nodes/HttpRequest/test/utils/utils.test.ts
Labels: node/improvement, n8n team

#11075 fix(Postgres PGVector Store Node): Fix filtering in retriever mode
  packages/@n8n/nodes-langchain/nodes/vector_store/VectorStorePGVector/VectorStorePGVector.node.ts
Labels: n8n team

#11074 fix(editor): Update Usage page for Community+ edition
  packages/editor-ui/src/plugins/i18n/locales/en.json
  packages/editor-ui/src/views/SettingsUsageAndPlan.test.ts
  packages/editor-ui/src/views/SettingsUsageAndPlan.vue
Labels: ui, n8n team

#11076 test(Gmail Trigger Node): Add tests (no-changelog)
  packages/nodes-base/nodes/ExecuteWorkflowTrigger/test/ExecuteWorkflowTrigger.node.test.ts
  packages/nodes-base/nodes/Google/Gmail/test/GmailTrigger.test.ts
  packages/nodes-base/nodes/Google/Gmail/types.ts
  packages/nodes-base/test/nodes/TriggerHelpers.ts
Labels: node/improvement, n8n team

#10815 fix: Show result of waiting execution on canvas after execution complete
  packages/@n8n/api-types/src/frontend-settings.ts
  packages/cli/src/services/frontend.service.ts
  packages/cli/templates/form-trigger.handlebars
  packages/editor-ui/src/Interface.ts
  packages/editor-ui/src/__tests__/defaults.ts
  packages/editor-ui/src/components/InputPanel.vue
  packages/editor-ui/src/components/Node.vue
  packages/editor-ui/src/components/NodeExecuteButton.vue
  packages/editor-ui/src/components/OutputPanel.vue
  packages/editor-ui/src/components/RunData.vue
  packages/editor-ui/src/components/canvas/elements/nodes/render-types/parts/CanvasNodeStatusIcons.vue
  packages/editor-ui/src/composables/__tests__/useRunWorkflow.spec.ts
  packages/editor-ui/src/composables/useCanvasMapping.ts
  packages/editor-ui/src/composables/usePushConnection.ts
  packages/editor-ui/src/composables/useRunWorkflow.ts
  packages/editor-ui/src/plugins/i18n/locales/en.json
  packages/editor-ui/src/stores/root.store.ts
  packages/editor-ui/src/stores/settings.store.ts
  packages/editor-ui/src/stores/workflows.store.ts
  packages/editor-ui/src/utils/__tests__/executionUtils.spec.ts
  packages/editor-ui/src/utils/executionUtils.ts
  packages/editor-ui/src/views/NodeView.v2.vue
  packages/editor-ui/src/views/NodeView.vue
  packages/nodes-base/nodes/Wait/Wait.node.ts
Labels: ui, n8n team

#11041 fix(editor): Hide run workflow button if only chat trigger available on new canvas (no-changelog)
  packages/editor-ui/src/views/NodeView.v2.vue
Labels: ui, n8n team

#11079 feat(editor): Add executing state and disable node run button while executing on new canvas (no-changelog)
  packages/editor-ui/src/__tests__/data/canvas.ts
  packages/editor-ui/src/components/canvas/Canvas.vue
  packages/editor-ui/src/components/canvas/WorkflowCanvas.vue
  packages/editor-ui/src/components/canvas/elements/nodes/CanvasNodeToolbar.spec.ts
  packages/editor-ui/src/components/canvas/elements/nodes/CanvasNodeToolbar.vue
  packages/editor-ui/src/composables/useCanvas.ts
  packages/editor-ui/src/types/canvas.ts
  packages/editor-ui/src/views/NodeView.v2.vue
Labels: ui, n8n team

#11047 feat(editor): Add navigation dropdown component
  packages/design-system/src/components/N8nNavigationDropdown/NavigationDropdown.stories.ts
  packages/design-system/src/components/N8nNavigationDropdown/NavigationDropdown.vue
  packages/design-system/src/components/N8nNavigationDropdown/__tests__/NavigationDropdown.spec.ts
  packages/design-system/src/components/N8nNavigationDropdown/index.ts
  packages/design-system/src/components/index.ts
Labels: ui, n8n team

#11078 refactor(editor): WorkflowsView to script setup + tests
  packages/editor-ui/src/views/WorkflowsView.test.ts
  packages/editor-ui/src/views/WorkflowsView.vue
Labels: ui, n8n team

#11081 feat(editor): Add logic for renaming duplicate nodes in new canvas (no-changelog)
  packages/editor-ui/src/composables/useCanvasOperations.ts
  packages/editor-ui/src/utils/__tests__/canvasUtilsV2.spec.ts
  packages/editor-ui/src/utils/canvasUtilsV2.ts
Labels: ui, n8n team

#11048 refactor(core): Simplify webhook pubsub message handler
  packages/cli/src/commands/webhook.ts
  packages/cli/src/scaling/__tests__/pubsub-handler.test.ts
  packages/cli/src/scaling/__tests__/subscriber.service.test.ts
  packages/cli/src/scaling/pubsub/pubsub-handler.ts
  packages/cli/src/scaling/pubsub/subscriber.service.ts
  packages/cli/src/services/orchestration/webhook/handle-command-message-webhook.ts
  packages/cli/src/services/orchestration/webhook/orchestration.handler.webhook.service.ts
Labels: core, n8n team

#11085 test(editor): Update RunDataSchema snapshots in editor-ui (no-changelog)
  packages/editor-ui/src/components/__tests__/__snapshots__/RunDataSchema.test.ts.snap
Labels: ui, n8n team

#11082 fix(editor): Fix condition for allowing keyboard shortcuts and pasting on new canvas (no-changelog)
  packages/editor-ui/src/views/NodeView.v2.vue
Labels: ui, n8n team

#11090 fix(editor): Don't report certain error types to Sentry (no-changelog)
  packages/editor-ui/src/main.ts
Labels: ui, n8n team

#11088 feat(editor): Adjust selection rectangle to include node selection box on new canvas (no-changelog)
  packages/editor-ui/src/components/canvas/elements/edges/CanvasEdge.vue
  packages/editor-ui/src/styles/plugins/_vueflow.scss
Labels: ui, n8n team

#11093 fix: Incorrect error message on calling wrong webhook method
  packages/cli/src/errors/response-errors/webhook-not-found.error.ts
  packages/cli/src/webhooks/live-webhooks.ts
Labels: n8n team, node/issue, tests-needed

#11087 fix(core)!: Bind worker server to IPv4
  packages/@n8n/config/src/configs/scaling-mode.config.ts
  packages/@n8n/config/test/config.test.ts
  packages/cli/BREAKING-CHANGES.md
  packages/cli/src/errors/port-taken.error.ts
  packages/cli/src/scaling/__tests__/worker-server.test.ts
  packages/cli/src/scaling/worker-server.ts
Labels: core, n8n team

#11083 feat(editor): Add node execution waiting state to new canvas (no-changelog)
  packages/editor-ui/src/components/canvas/elements/nodes/render-types/CanvasNodeDefault.spec.ts
  packages/editor-ui/src/components/canvas/elements/nodes/render-types/CanvasNodeDefault.vue
  packages/editor-ui/src/components/canvas/elements/nodes/render-types/parts/CanvasNodeStatusIcons.vue
Labels: ui, n8n team

#11094 refactor(editor): CredentialsView.vue to script setup
  packages/editor-ui/src/views/CredentialsView.vue
Labels: ui, n8n team

#11100 fix(editor): Set document title when renaming and loading workflow (no-changelog)
  packages/editor-ui/src/components/MainHeader/WorkflowDetails.vue
  packages/editor-ui/src/views/NodeView.v2.vue
Labels: ui, n8n team

#11097 fix(editor): Fix node position when auto adding chat trigger node (no-changelog)
  packages/editor-ui/src/composables/useCanvasOperations.ts
Labels: ui, n8n team

#11095 test(core): Allow Jest to exit cleanly in `worker` command test
  packages/cli/test/integration/commands/worker.cmd.test.ts
Labels: core, n8n team

#11099 fix(core): Print errors that happen before the execution starts on the worker instead of just on the main instance
  packages/cli/src/scaling/scaling.service.ts
Labels: core, n8n team, release/backport

#11104 fix(editor): Add safety to prevent undefined errors
  packages/editor-ui/src/composables/useWorkflowHelpers.ts
  packages/editor-ui/src/utils/__tests__/expressions.test.ts
  packages/editor-ui/src/utils/expressions.ts
Labels: ui, n8n team

#11105 fix(editor): Fix render key for dynamic number of handles on new canvas (no-changelog)
  packages/editor-ui/src/components/canvas/elements/handles/CanvasHandleRenderer.vue
  packages/editor-ui/src/components/canvas/elements/nodes/CanvasNode.vue
Labels: ui, n8n team

#11091 fix(core): Separate error handlers for main and worker
  packages/cli/src/scaling/scaling.service.ts
Labels: core, n8n team

#11103 fix(editor): Fix getInitials when Intl.Segmenter is not supported
  packages/design-system/src/utils/labelUtil.spec.ts
  packages/design-system/src/utils/labelUtil.ts
Labels: ui, n8n team

#11080 feat(OpenAI Node): Allow to specify thread ID for Assistant -> Message operation
  packages/@n8n/nodes-langchain/nodes/vendors/OpenAi/actions/assistant/message.operation.ts
  packages/@n8n/nodes-langchain/nodes/vendors/OpenAi/actions/versionDescription.ts
Labels: n8n team

#11126 refactor: Use single request to execute `runOnceForEachItem` in task runner
  packages/@n8n/task-runner/package.json
  packages/@n8n/task-runner/src/__tests__/code.test.ts
  packages/@n8n/task-runner/src/__tests__/test-data.ts
  packages/@n8n/task-runner/src/code.ts
  packages/@n8n/task-runner/src/execution-error.ts
  packages/@n8n/task-runner/src/obj-utils.ts
  packages/@n8n/task-runner/src/result-validation.ts
  packages/@n8n/task-runner/src/task-runner.ts
  packages/@n8n/task-runner/src/validation-error.ts
  packages/nodes-base/nodes/Code/Code.node.ts
  packages/nodes-base/nodes/Code/JsTaskRunnerSandbox.ts
Labels: node/improvement, n8n team

#11009 feat: Graceful termination of task runner (no-changelog)
  packages/@n8n/task-runner/src/start.ts
  packages/@n8n/task-runner/src/task-runner.ts
Labels: n8n team

#11130 fix(core): Allow loading nodes from multiple custom directories
  packages/cli/src/load-nodes-and-credentials.ts
Labels: core, n8n team, release/backport, tests-needed

#11128 fix: Fix task runner default n8n uri and auth endpoint (no-changelog)
  packages/@n8n/task-runner/src/authenticator.ts
  packages/@n8n/task-runner/src/start.ts
Labels: n8n team

#10776 feat(editor): Community+ enrollment
  packages/@n8n/api-types/src/dto/index.ts
  packages/@n8n/api-types/src/dto/license/__tests__/community-registered-request.dto.test.ts
  packages/@n8n/api-types/src/dto/license/community-registered-request.dto.ts
  packages/cli/src/events/maps/relay.event-map.ts
  packages/cli/src/events/relays/telemetry.event-relay.ts
  packages/cli/src/license/__tests__/license.service.test.ts
  packages/cli/src/license/license.controller.ts
  packages/cli/src/license/license.service.ts
  packages/editor-ui/src/api/usage.ts
  packages/editor-ui/src/components/CommunityPlusEnrollmentModal.test.ts
  packages/editor-ui/src/components/CommunityPlusEnrollmentModal.vue
  packages/editor-ui/src/components/Modals.vue
  packages/editor-ui/src/components/PersonalizationModal.test.ts
  packages/editor-ui/src/components/PersonalizationModal.vue
  packages/editor-ui/src/constants.ts
  packages/editor-ui/src/plugins/i18n/locales/en.json
  packages/editor-ui/src/stores/ui.store.ts
  packages/editor-ui/src/stores/usage.store.ts
  packages/editor-ui/src/views/SettingsUsageAndPlan.test.ts
  packages/editor-ui/src/views/SettingsUsageAndPlan.vue
Labels: ui, n8n team

#11139 chore: Document file-upload properties for `@n8n/chat` (no-changelog)
  packages/@n8n/chat/README.md
Labels: n8n team

#11138 fix(editor): Reset last interacted with when resetting the workspace on new canvas (no-changelog)
  packages/editor-ui/src/composables/useCanvasOperations.ts
Labels: ui, n8n team

#10675 feat: Human in the loop
  packages/cli/src/webhooks/__tests__/waiting-webhooks.test.ts
  packages/cli/src/webhooks/waiting-webhooks.ts
  packages/cli/templates/send-and-wait-no-action-required.handlebars
  packages/editor-ui/src/components/Node.vue
  packages/editor-ui/src/composables/useCanvasMapping.ts
  packages/editor-ui/src/composables/useRunWorkflow.ts
  packages/editor-ui/src/plugins/i18n/locales/en.json
  packages/editor-ui/src/stores/workflows.store.ts
  packages/editor-ui/src/utils/executionUtils.ts
  packages/nodes-base/nodes/Google/Gmail/GenericFunctions.ts
  packages/nodes-base/nodes/Google/Gmail/v1/GmailV1.node.ts
  packages/nodes-base/nodes/Google/Gmail/v2/GmailV2.node.ts
  packages/nodes-base/nodes/Google/Gmail/v2/MessageDescription.ts
  packages/nodes-base/nodes/Slack/V2/GenericFunctions.ts
  packages/nodes-base/nodes/Slack/V2/MessageDescription.ts
  packages/nodes-base/nodes/Slack/V2/SlackV2.node.ts
  packages/nodes-base/nodes/Slack/test/v2/utils.test.ts
  packages/nodes-base/utils/sendAndWait/email-templates.ts
  packages/nodes-base/utils/sendAndWait/interfaces.ts
  packages/nodes-base/utils/sendAndWait/test/util.test.ts
  packages/nodes-base/utils/sendAndWait/utils.ts
  packages/nodes-base/utils/utilities.ts
  packages/workflow/src/Constants.ts
  packages/workflow/src/WorkflowDataProxy.ts
Labels: node/improvement, n8n team

#11140 fix(editor): Fix success status for plus stalk on new canvas (no-changelog)
  packages/editor-ui/src/components/canvas/elements/handles/render-types/CanvasHandleMainOutput.spec.ts
  packages/editor-ui/src/components/canvas/elements/handles/render-types/CanvasHandleMainOutput.vue
  packages/editor-ui/src/components/canvas/elements/handles/render-types/CanvasHandleNonMainInput.vue
  packages/editor-ui/src/components/canvas/elements/handles/render-types/parts/CanvasHandlePlus.vue
Labels: ui, n8n team

#11142 fix(editor): Make sure deactivated status shows even for nodes with long names on new canvas (no-changelog)
  packages/editor-ui/src/components/canvas/elements/nodes/render-types/CanvasNodeDefault.vue
  packages/editor-ui/src/components/canvas/elements/nodes/render-types/__snapshots__/CanvasNodeDefault.spec.ts.snap
Labels: ui, n8n team

#11086 refactor(core): Simplify worker pubsub message handler
  packages/cli/src/commands/webhook.ts
  packages/cli/src/commands/worker.ts
  packages/cli/src/scaling/__tests__/pubsub-handler.test.ts
  packages/cli/src/scaling/pubsub/pubsub-handler.ts
  packages/cli/src/scaling/worker-status.ts
  packages/cli/src/services/orchestration/worker/handle-command-message-worker.ts
  packages/cli/src/services/orchestration/worker/orchestration.handler.worker.service.ts
  packages/cli/test/integration/commands/worker.cmd.test.ts
Labels: core, n8n team

#11092 perf(core): Optimize worker healthchecks
  packages/@n8n/config/src/configs/scaling-mode.config.ts
  packages/cli/BREAKING-CHANGES.md
  packages/cli/src/scaling/__tests__/worker-server.test.ts
  packages/cli/src/scaling/worker-server.ts
  packages/cli/src/services/redis-client.service.ts
Labels: core, n8n team

#11096 chore(core): Better debug logs for local dev
  packages/cli/src/logging/logger.service.ts
  packages/workflow/src/ErrorReporterProxy.ts
Labels: core, n8n team

#11137 fix(editor): Disable all modifying keybindings when the canvas is in read-only mode (no-changelog)
  packages/editor-ui/src/components/canvas/Canvas.vue
  packages/editor-ui/src/composables/__tests__/useKeybindings.test.ts
  packages/editor-ui/src/composables/useKeybindings.spec.ts
  packages/editor-ui/src/composables/useKeybindings.ts
Labels: ui, n8n team

#11114 fix(Convert to File Node): Convert to ICS start date defaults to now
  packages/nodes-base/nodes/ICalendar/createEvent.operation.ts
Labels: node/improvement, n8n team, tests-needed

#11145 fix: Fix transaction handling for 'revert' command
  packages/cli/src/commands/db/__tests__/revert.test.ts
  packages/cli/src/commands/db/revert.ts
Labels: core, n8n team, release/backport

#11110 fix(editor): Shorten overflowing Node Label in InputLabels on hover and focus
  packages/design-system/src/components/N8nInputLabel/InputLabel.vue
  packages/design-system/src/components/N8nInputLabel/__tests__/InputLabel.spec.ts
  packages/design-system/src/components/N8nInputLabel/__tests__/__snapshots__/InputLabel.spec.ts.snap
Labels: ui, n8n team

#11133 test(core): Add community+ register tracking test
  packages/cli/src/events/__tests__/telemetry-event-relay.test.ts
Labels: core, n8n team

#11111 fix(editor): Show previous nodes autocomplete in AI tool nodes
  packages/editor-ui/src/plugins/codemirror/completions/__tests__/utils.test.ts
  packages/editor-ui/src/plugins/codemirror/completions/utils.ts
Labels: ui, n8n team

#11118 fix(core): Add `down` method to `AddApiKeysTable1724951148974` migration (no-changelog)
  packages/cli/src/databases/migrations/common/1724951148974-AddApiKeysTable.ts
  packages/cli/src/databases/migrations/sqlite/1724951148974-AddApiKeysTable.ts
Labels: core, n8n team, release/backport

#11149 refactor(core): Include self-sending and debouncing in pubsub commands
  packages/cli/src/scaling/__tests__/publisher.service.test.ts
  packages/cli/src/scaling/constants.ts
  packages/cli/src/scaling/pubsub/publisher.service.ts
  packages/cli/src/scaling/pubsub/pubsub.types.ts
  packages/cli/src/scaling/pubsub/subscriber.service.ts
  packages/cli/src/services/orchestration/main/handle-command-message-main.ts
Labels: core, n8n team

#11146 refactor: Move js task runner into own directory
  packages/@n8n/task-runner/src/js-task-runner/__tests__/js-task-runner.test.ts
  packages/@n8n/task-runner/src/js-task-runner/__tests__/test-data.ts
  packages/@n8n/task-runner/src/js-task-runner/errors/execution-error.ts
  packages/@n8n/task-runner/src/js-task-runner/errors/validation-error.ts
  packages/@n8n/task-runner/src/js-task-runner/js-task-runner.ts
  packages/@n8n/task-runner/src/js-task-runner/obj-utils.ts
  packages/@n8n/task-runner/src/js-task-runner/result-validation.ts
  packages/@n8n/task-runner/src/start.ts
Labels: n8n team

#11134 feat(editor): Add route for create / edit / share credentials
  packages/editor-ui/src/components/CredentialCard.vue
  packages/editor-ui/src/routes/projects.routes.ts
  packages/editor-ui/src/views/CredentialsView.test.ts
  packages/editor-ui/src/views/CredentialsView.vue
Labels: ui, n8n team

#11046 fix(NASA Node): Astronomy-Picture-Of-The-Day fails when it's YouTube video
  packages/nodes-base/nodes/Nasa/Nasa.node.ts
Labels: node/improvement, n8n team, tests-needed

#11163 refactor(core): Change triggers and pollers removal log to debug level
  packages/cli/src/active-workflow-manager.ts
Labels: core, n8n team

#11152 fix: Forbid access to files outside source control work directory
  packages/cli/src/environments/source-control/__tests__/source-control.service.test.ts
  packages/cli/src/environments/source-control/source-control-helper.ee.ts
  packages/cli/src/environments/source-control/source-control.controller.ee.ts
  packages/cli/src/environments/source-control/source-control.service.ee.ts
  packages/cli/src/utils/__tests__/path-util.test.ts
  packages/cli/src/utils/path-util.ts
Labels: core, n8n team

#11147 fix: Fix console log handling in JS task runner (no-changelog)
  packages/@n8n/task-runner/src/js-task-runner/__tests__/js-task-runner.test.ts
  packages/@n8n/task-runner/src/js-task-runner/js-task-runner.ts
Labels: n8n team

#11154 fix(editor): Align undo/redo functionality on new canvas (no-changelog)
  packages/editor-ui/src/components/canvas/Canvas.spec.ts
  packages/editor-ui/src/components/canvas/Canvas.vue
  packages/editor-ui/src/composables/useCanvasOperations.ts
  packages/editor-ui/src/composables/useNodeHelpers.ts
  packages/editor-ui/src/views/NodeView.vue
Labels: ui, n8n team

#11165 refactor: Simplify resolveIcon checks and add tests
  packages/cli/src/__tests__/load-nodes-and-credentials.test.ts
  packages/cli/src/load-nodes-and-credentials.ts
Labels: core, n8n team

#11164 feat(core): Deduplicate transitive-dependencies, and ensure all peer-dependencies are met (no-changelog)
  packages/@n8n/nodes-langchain/package.json
  packages/nodes-base/package.json
  pnpm-lock.yaml
Labels: n8n team

#11170 feat(editor): Upgrade vite, vitest, esbuild, and rollup to address CVE-2024-47068 (no-changelog)
  package.json
  pnpm-lock.yaml
  pnpm-workspace.yaml
Labels: n8n team

#11055 fix(core): Fix AI nodes not working with new partial execution flow
  packages/core/src/PartialExecutionUtils/DirectedGraph.ts
  packages/core/src/PartialExecutionUtils/__tests__/DirectedGraph.test.ts
  packages/core/src/PartialExecutionUtils/__tests__/findSubgraph.test.ts
  packages/core/src/PartialExecutionUtils/findStartNodes.ts
  packages/core/src/PartialExecutionUtils/findSubgraph.ts
  packages/core/src/PartialExecutionUtils/recreateNodeExecutionStack.ts
Labels: core, n8n team

#11077 fix(Gitlab Node): Author name and email not being set
  packages/nodes-base/nodes/Gitlab/Gitlab.node.ts
Labels: node/improvement, community, in linear, tests-needed

#11178 feat(core): Upgrade express and some related packages to address some vulnerabilities (no-changelog)
  packages/cli/package.json
  pnpm-lock.yaml
Labels: core, n8n team

#11179 refactor(core): Deregistering cronjobs should also release them (no-changelog)
  packages/core/src/ScheduledTaskManager.ts
  packages/core/test/ScheduledTaskManager.test.ts
Labels: core, n8n team

#11180 refactor(core): Remove dead pubsub code
  packages/cli/src/controllers/orchestration.controller.ts
  packages/cli/src/events/maps/pub-sub.event-map.ts
  packages/cli/src/scaling/__tests__/publisher.service.test.ts
  packages/cli/src/scaling/__tests__/pubsub-handler.test.ts
  packages/cli/src/scaling/pubsub/pubsub-handler.ts
  packages/cli/src/scaling/pubsub/pubsub.types.ts
  packages/cli/src/services/__tests__/orchestration.service.test.ts
  packages/cli/src/services/orchestration.service.ts
  packages/cli/src/services/orchestration/main/handle-worker-response-message-main.ts
Labels: core, n8n team

#11127 feat(core): Introduce scoped logging
  packages/@n8n/config/src/configs/logging.config.ts
  packages/@n8n/config/src/index.ts
  packages/@n8n/config/test/config.test.ts
  packages/cli/src/__tests__/license.test.ts
  packages/cli/src/__tests__/wait-tracker.test.ts
  packages/cli/src/commands/base-command.ts
  packages/cli/src/concurrency/__tests__/concurrency-control.service.test.ts
  packages/cli/src/concurrency/concurrency-control.service.ts
  packages/cli/src/databases/repositories/__tests__/execution.repository.test.ts
  packages/cli/src/environments/source-control/source-control-import.service.ee.ts
  packages/cli/src/eventbus/message-event-bus-writer/message-event-bus-log-writer.ts
  packages/cli/src/execution-lifecycle-hooks/shared/shared-hook-functions.ts
  packages/cli/src/license.ts
  packages/cli/src/logging/__tests__/logger.service.test.ts
  packages/cli/src/logging/logger.service.ts
  packages/cli/src/logging/types.ts
  packages/cli/src/scaling/__tests__/scaling.service.test.ts
  packages/cli/src/scaling/scaling.service.ts
  packages/cli/src/services/import.service.ts
  packages/cli/src/wait-tracker.ts
  packages/cli/src/workflows/workflow-history/__tests__/workflow-history.service.ee.test.ts
  packages/cli/src/workflows/workflow-history/workflow-history.service.ee.ts
  packages/cli/test/shared/mocking.ts
Labels: core, n8n team

#11166 feat: Opt in to additional features on community for existing users
  packages/cli/src/license/license.service.ts
  packages/editor-ui/src/components/CommunityPlusEnrollmentModal.test.ts
  packages/editor-ui/src/components/CommunityPlusEnrollmentModal.vue
  packages/editor-ui/src/plugins/i18n/locales/en.json
  packages/editor-ui/src/views/SettingsUsageAndPlan.test.ts
  packages/editor-ui/src/views/SettingsUsageAndPlan.vue
Labels: ui, n8n team

#11182 feat(core): Upgrade chokidar, braces, and micromatch to address CVE-2024-4067 & CVE-2024-4068 (no-changelog)
  package.json
  packages/cli/package.json
  packages/nodes-base/nodes/LocalFileTrigger/LocalFileTrigger.node.ts
  packages/nodes-base/package.json
  pnpm-lock.yaml
  pnpm-workspace.yaml
Labels: node/improvement, core, n8n team

#11177 feat: Add support for $env in the js task runner (no-changelog)
  packages/@n8n/task-runner/package.json
  packages/@n8n/task-runner/src/js-task-runner/__tests__/js-task-runner.test.ts
  packages/@n8n/task-runner/src/js-task-runner/__tests__/test-data.ts
  packages/@n8n/task-runner/src/js-task-runner/js-task-runner.ts
  packages/cli/src/runners/task-managers/task-manager.ts
  packages/cli/src/workflow-execute-additional-data.ts
  packages/core/src/Agent/index.ts
  packages/workflow/src/Interfaces.ts
  packages/workflow/src/WorkflowDataProxy.ts
  packages/workflow/src/WorkflowDataProxyEnvProvider.ts
  packages/workflow/src/index.ts
  packages/workflow/test/WorkflowDataProxyEnvProvider.test.ts
  pnpm-lock.yaml
Labels: core, n8n team

#11027 refactor: Use Ask AI feature through AI services instead of hooks
  cypress/e2e/45-ai-assistant.cy.ts
  cypress/e2e/6-code-node.cy.ts
  packages/@n8n/api-types/src/frontend-settings.ts
  packages/cli/package.json
  packages/cli/src/constants.ts
  packages/cli/src/controllers/ai.controller.ts
  packages/cli/src/controllers/e2e.controller.ts
  packages/cli/src/license.ts
  packages/cli/src/requests.ts
  packages/cli/src/server.ts
  packages/cli/src/services/ai.service.ts
  packages/cli/src/services/frontend.service.ts
  packages/editor-ui/src/__tests__/defaults.ts
  packages/editor-ui/src/api/ai.ts
  packages/editor-ui/src/api/assistant.ts
  packages/editor-ui/src/components/ButtonParameter/ButtonParameter.vue
  packages/editor-ui/src/components/CodeNodeEditor/AskAI/AskAI.vue
  packages/editor-ui/src/components/CodeNodeEditor/CodeNodeEditor.vue
  packages/editor-ui/src/components/Node/NodeCreator/composables/useViewStacks.ts
  packages/editor-ui/src/components/Node/NodeCreator/utils.ts
  packages/editor-ui/src/constants.ts
  packages/editor-ui/src/stores/__tests__/assistant.store.test.ts
  packages/editor-ui/src/stores/assistant.store.ts
  packages/editor-ui/src/stores/posthog.store.ts
  packages/editor-ui/src/stores/settings.store.ts
  packages/editor-ui/src/types/assistant.types.ts
  pnpm-lock.yaml
Labels: core, ui, n8n team

#11174 fix(n8n Trigger Node): Merge with Workflow Trigger node
  packages/nodes-base/nodes/N8nTrigger/N8nTrigger.node.ts
  packages/nodes-base/nodes/N8nTrigger/test/trigger.test.ts
  packages/nodes-base/nodes/WorkflowTrigger/WorkflowTrigger.node.ts
Labels: node/improvement, n8n team

#10786 ci: Upgrade frontend dev tooling (no-changelog)
  package.json
  packages/@n8n/chat/package.json
  packages/@n8n/storybook/package.json
  packages/design-system/src/components/AskAssistantChat/__tests__/AskAssistantChat.spec.ts
  packages/design-system/src/components/AskAssistantChat/__tests__/__snapshots__/AskAssistantChat.spec.ts.snap
  packages/design-system/src/components/CodeDiff/__tests__/CodeDiff.spec.ts
  packages/design-system/src/components/CodeDiff/__tests__/__snapshots__/CodeDiff.spec.ts.snap
  packages/design-system/src/components/N8nOption/Option.vue
  packages/design-system/src/components/N8nSelect/Select.vue
  packages/editor-ui/package.json
  packages/editor-ui/src/components/__tests__/__snapshots__/RunDataSchema.test.ts.snap
  pnpm-lock.yaml
  pnpm-workspace.yaml
Labels: ui, n8n team

#11195 fix(editor): Allow SSO login focus outlines to draw fully (no-changelog)
  packages/editor-ui/src/components/SSOLogin.vue
Labels: ui, n8n team

#11184 feat: Add configurable require support to js task runner (no-changelog)
  packages/@n8n/task-runner/src/js-task-runner/__tests__/js-task-runner.test.ts
  packages/@n8n/task-runner/src/js-task-runner/js-task-runner.ts
  packages/@n8n/task-runner/src/js-task-runner/require-resolver.ts
  packages/@n8n/task-runner/src/start.ts
  packages/cli/src/runners/__tests__/task-runner-process.test.ts
  packages/cli/src/runners/task-runner-process.ts
Labels: core, n8n team

#11197 fix(HTTP Request Node): Fix typos in JSON validation error message (no-changelog)
  packages/cli/src/eventbus/message-event-bus-destination/message-event-bus-destination-webhook.ee.ts
  packages/nodes-base/nodes/HttpRequest/V3/HttpRequestV3.node.ts
Labels: node/improvement, n8n team

#11199 refactor(core): Use options object for functions with lots of arguments to make the call site more readable and avoid errors
  packages/core/src/PartialExecutionUtils/__tests__/findStartNodes.test.ts
  packages/core/src/PartialExecutionUtils/__tests__/findSubgraph.test.ts
  packages/core/src/PartialExecutionUtils/__tests__/recreateNodeExecutionStack.test.ts
  packages/core/src/PartialExecutionUtils/findStartNodes.ts
  packages/core/src/PartialExecutionUtils/findSubgraph.ts
  packages/core/src/WorkflowExecute.ts
Labels: core, n8n team

#11135 feat(editor): Send workflow context to assistant store
  cypress/composables/ndv.ts
  cypress/e2e/45-ai-assistant.cy.ts
  cypress/fixtures/aiAssistant/responses/apply_code_diff_response.json
  cypress/fixtures/aiAssistant/responses/code_diff_suggestion_response.json
  cypress/fixtures/aiAssistant/responses/code_snippet_response.json
  cypress/fixtures/aiAssistant/responses/end_session_response.json
  cypress/fixtures/aiAssistant/responses/node_execution_error_response.json
  cypress/fixtures/aiAssistant/responses/quick_reply_message_response.json
  cypress/fixtures/aiAssistant/responses/simple_message_response.json
  cypress/fixtures/aiAssistant/workflows/simple_http_request_workflow.json
  cypress/fixtures/aiAssistant/workflows/test_workflow.json
  cypress/pages/ndv.ts
  n8n.code-workspace
  packages/editor-ui/src/composables/useAIAssistantHelpers.ts
  packages/editor-ui/src/stores/assistant.store.ts
  packages/editor-ui/src/types/assistant.types.ts
Labels: ui, n8n team

#11201 fix(OpenAI Node): Fix tool parameter parsing issue
  packages/@n8n/nodes-langchain/nodes/vendors/OpenAi/actions/text/message.operation.ts
Labels: n8n team

#11205 fix(editor): Fix `DataTable` markup (no-changelog)
  packages/editor-ui/src/components/RunDataTable.vue
Labels: ui, n8n team

#11185 fix(Google Calendar Node): Fix issue with conference data types not loading
  packages/nodes-base/nodes/Google/Calendar/EventDescription.ts
  packages/nodes-base/nodes/Google/Calendar/GoogleCalendar.node.ts
Labels: node/improvement, n8n team

#11206 feat(editor): Remove manual chunking from vite (no-changelog)
  packages/editor-ui/vite.config.mts
Labels: ui, n8n team

#11132 fix(Google Calendar Node): Mode to add or replace attendees in event update
  packages/nodes-base/nodes/Google/Calendar/EventDescription.ts
  packages/nodes-base/nodes/Google/Calendar/GoogleCalendar.node.ts
  packages/nodes-base/nodes/Google/Calendar/test/node/event.update.test.ts
Labels: node/improvement, n8n team, node/issue

#11208 feat(editor): Improve Sentry ignore definitions for class instance types (no-changelog)
  packages/cli/src/server.ts
  packages/editor-ui/src/main.ts
  packages/editor-ui/src/plugins/sentry.spec.ts
  packages/editor-ui/src/plugins/sentry.ts
  packages/editor-ui/src/shims.d.ts
Labels: ui, n8n team

#11216 fix(editor): Bring back the "Forgot password" link on SigninView
  packages/editor-ui/src/views/SigninView.vue
Labels: release/backport

#11214 fix: Make sure errors are transferred correctly from js task runner (no-changelog)
  packages/@n8n/task-runner/src/js-task-runner/__tests__/js-task-runner.test.ts
  packages/@n8n/task-runner/src/js-task-runner/errors/__tests__/execution-error.test.ts
  packages/@n8n/task-runner/src/js-task-runner/errors/error-like.ts
  packages/@n8n/task-runner/src/js-task-runner/errors/execution-error.ts
  packages/@n8n/task-runner/src/js-task-runner/errors/serializable-error.ts
  packages/@n8n/task-runner/src/js-task-runner/errors/validation-error.ts
  packages/@n8n/task-runner/src/js-task-runner/js-task-runner.ts
  packages/@n8n/task-runner/src/task-runner.ts
  packages/cli/src/runners/task-managers/task-manager.ts
  packages/core/src/Agent/index.ts
  packages/nodes-base/nodes/Code/JsTaskRunnerSandbox.ts
  packages/nodes-base/nodes/Code/errors/WrappedExecutionError.ts
  packages/workflow/src/Interfaces.ts
  packages/workflow/src/NodeParameters/FilterParameter.ts
  packages/workflow/src/index.ts
  packages/workflow/src/result.ts
Labels: node/improvement, core, n8n team

#11210 fix(editor): Fix chat crashing when rendering output-parsed content
  packages/editor-ui/src/components/WorkflowLMChat/WorkflowLMChat.vue
Labels: ui, n8n team

#11156 refactor(core): Simplify main pubsub message handler
  packages/@n8n/api-types/src/scaling.ts
  packages/cli/src/commands/start.ts
  packages/cli/src/commands/webhook.ts
  packages/cli/src/commands/worker.ts
  packages/cli/src/events/maps/pub-sub.event-map.ts
  packages/cli/src/scaling/__tests__/publisher.service.test.ts
  packages/cli/src/scaling/__tests__/pubsub-handler.test.ts
  packages/cli/src/scaling/__tests__/subscriber.service.test.ts
  packages/cli/src/scaling/pubsub/publisher.service.ts
  packages/cli/src/scaling/pubsub/pubsub-handler.ts
  packages/cli/src/scaling/pubsub/pubsub.types.ts
  packages/cli/src/scaling/pubsub/subscriber.service.ts
  packages/cli/src/scaling/worker-status.service.ts
  packages/cli/src/services/__tests__/orchestration.service.test.ts
  packages/cli/src/services/orchestration/helpers.ts
  packages/cli/src/services/orchestration/main/handle-command-message-main.ts
  packages/cli/src/services/orchestration/main/handle-worker-response-message-main.ts
  packages/cli/src/services/orchestration/main/orchestration.handler.main.service.ts
  packages/cli/test/integration/commands/worker.cmd.test.ts
  packages/editor-ui/src/components/Workers/WorkerCard.ee.vue
  packages/editor-ui/src/stores/orchestration.store.ts
Labels: core, n8n team

#11160 fix(editor): Fix canvas handle plus rectangle background on new canvas (no-changelog)
  packages/editor-ui/src/components/canvas/elements/handles/render-types/parts/CanvasHandleDiamond.spec.ts
  packages/editor-ui/src/components/canvas/elements/handles/render-types/parts/CanvasHandlePlus.vue
  packages/editor-ui/src/components/canvas/elements/handles/render-types/parts/__snapshots__/CanvasHandleDiamond.spec.ts.snap
  packages/editor-ui/src/components/canvas/elements/handles/render-types/parts/__snapshots__/CanvasHandlePlus.spec.ts.snap
Labels: ui, n8n team

#11194 fix(editor): Disable Ask AI button in deprecated nodes (no-changelog)
  packages/design-system/src/components/AskAssistantChat/__tests__/__snapshots__/AskAssistantChat.spec.ts.snap
  packages/design-system/src/components/InlineAskAssistantButton/InlineAskAssistantButton.vue
  packages/editor-ui/src/components/Error/NodeErrorView.vue
  packages/editor-ui/src/components/Error/__tests__/NodeErrorView.test.ts
Labels: ui, n8n team

#11213 feat(editor): Improve insertion algorithm for nodes with multiple main outputs (no-changelog)
  packages/editor-ui/src/composables/__tests__/useCanvasOperations.spec.ts
  packages/editor-ui/src/composables/useCanvasOperations.ts
  packages/editor-ui/src/utils/__tests__/nodeViewUtils.spec.ts
  packages/editor-ui/src/utils/nodeViewUtils.ts
  packages/editor-ui/src/views/NodeView.vue
Labels: ui, n8n team

#11219 fix(HTTP Request Tool Node): Respond with an error when receive binary response
  packages/@n8n/nodes-langchain/nodes/tools/ToolHttpRequest/ToolHttpRequest.node.ts
  packages/@n8n/nodes-langchain/nodes/tools/ToolHttpRequest/test/ToolHttpRequest.node.test.ts
  packages/@n8n/nodes-langchain/nodes/tools/ToolHttpRequest/utils.ts
  packages/@n8n/nodes-langchain/package.json
  pnpm-lock.yaml
Labels: n8n team

#11227 fix(editor): Make submit in ChangePasswordView work again
  packages/editor-ui/src/views/ChangePasswordView.vue
Labels: ui, n8n team, release/backport

#11226 fix(Strava Trigger Node): Fix issue with webhook not being deleted
  packages/nodes-base/nodes/Strava/GenericFunctions.ts
  packages/nodes-base/nodes/Strava/StravaTrigger.node.ts
Labels: node/improvement, n8n team

#11242 fix(MySQL Node): Fix "Maximum call stack size exceeded" error when handling a large number of rows
  packages/nodes-base/nodes/MySql/v2/helpers/utils.ts
Labels: node/improvement, n8n team

#11246 chore: Stop reporting to Sentry leader key renewals
  packages/cli/src/services/orchestration/main/multi-main-setup.ee.ts
Labels: core, n8n team

#11245 fix(core): Ensure error reporter does not promote `info` to `error` messages
  packages/workflow/src/ErrorReporterProxy.ts
Labels: core, n8n team

#11243 fix(Google Ads Node): Update to use v17 api
  packages/nodes-base/nodes/Google/Ads/CampaignDescription.ts
  packages/nodes-base/nodes/Google/Ads/GoogleAds.node.ts
Labels: node/improvement, n8n team

#11244 refactor(core): Revamp logs for scaling mode
  packages/cli/src/commands/start.ts
  packages/cli/src/commands/worker.ts
  packages/cli/src/errors/worker-missing-encryption-key.error.ts
  packages/cli/src/scaling/__tests__/publisher.service.test.ts
  packages/cli/src/scaling/__tests__/worker-server.test.ts
  packages/cli/src/scaling/job-processor.ts
  packages/cli/src/scaling/pubsub/publisher.service.ts
  packages/cli/src/scaling/pubsub/pubsub.types.ts
  packages/cli/src/scaling/pubsub/subscriber.service.ts
  packages/cli/src/scaling/scaling.service.ts
  packages/cli/src/scaling/scaling.types.ts
  packages/cli/src/scaling/worker-server.ts
  packages/cli/src/workflow-runner.ts
  packages/core/src/DirectoryLoader.ts
  packages/workflow/src/ErrorReporterProxy.ts
  packages/workflow/src/errors/application.error.ts
Labels: core, n8n team

#11071 feat: Start Task Runner via Launcher (no-changelog)
  docker/images/n8n-custom/Dockerfile
  docker/images/n8n/Dockerfile
  docker/images/n8n/n8n-task-runners.json
  packages/@n8n/config/src/configs/runners.config.ts
  packages/@n8n/config/test/config.test.ts
  packages/cli/src/runners/task-runner-process.ts
  packages/cli/test/integration/runners/task-runner-process.test.ts
Labels: core, n8n team

#11241 feat: Enable code capture in ai transform node (no-changelog)
  packages/editor-ui/src/components/JsEditor/JsEditor.vue
  packages/editor-ui/src/components/ParameterInput.vue
Labels: ui, n8n team

#11250 fix(core): Override executions mode if `regular` during worker startup
  packages/cli/src/commands/worker.ts
  packages/cli/test/integration/commands/worker.cmd.test.ts
Labels: release/backport

#11248 fix: Adjust arrow button colors in dark mode
  packages/design-system/src/components/N8nTabs/Tabs.vue
  packages/editor-ui/src/components/RunData.vue
Labels: ui, n8n team

#11251 refactor(core): Remove deprecated properties from orchestration service
  packages/cli/src/__tests__/wait-tracker.test.ts
  packages/cli/src/active-workflow-manager.ts
  packages/cli/src/controllers/debug.controller.ts
  packages/cli/src/license.ts
  packages/cli/src/services/orchestration.service.ts
  packages/cli/src/services/pruning.service.ts
  packages/cli/src/wait-tracker.ts
  packages/cli/test/integration/debug.controller.test.ts
Labels: core, n8n team

#11189 docs: Add end of service notice for Line (no-changelog)
  packages/nodes-base/nodes/Line/Line.node.ts
Labels: node/improvement, n8n team

#11235 perf(Google Sheets Node): Don't load whole spreadsheet dataset to determine columns when appending data
  packages/nodes-base/nodes/Google/Sheet/v2/actions/sheet/append.operation.ts
Labels: node/improvement, community, in linear

#11254 feat: Fail all tasks for a disconnected Task Runner (no-changelog)
  packages/cli/src/runners/__tests__/task-broker.test.ts
  packages/cli/src/runners/task-broker.service.ts
Labels: core, n8n team

#11253 feat: Enable Task Runners on Scaling mode Workers (no-changelog)
  packages/cli/src/commands/start.ts
  packages/cli/src/commands/worker.ts
  packages/cli/src/runners/task-managers/local-task-manager.ts
  packages/cli/test/integration/commands/worker.cmd.test.ts
Labels: core, n8n team

#11060 feat: Add tracking for node errors and update node graph
  packages/cli/src/events/relays/telemetry.event-relay.ts
  packages/editor-ui/src/components/SourceControlPushModal.ee.test.ts
  packages/editor-ui/src/components/executions/workflow/WorkflowExecutionsCard.test.ts
  packages/editor-ui/src/components/layouts/ResourcesListLayout.test.ts
  packages/editor-ui/src/stores/workflows.store.spec.ts
  packages/editor-ui/src/stores/workflows.store.ts
  packages/editor-ui/src/views/__tests__/SamlOnboarding.test.ts
  packages/workflow/src/Interfaces.ts
  packages/workflow/src/TelemetryHelpers.ts
  packages/workflow/test/TelemetryHelpers.test.ts
Labels: core, ui, n8n team

#11262 refactor(core): Move `queueModeId` as `hostId` to `InstanceSettings`
  packages/cli/src/abstract-server.ts
  packages/cli/src/commands/base-command.ts
  packages/cli/src/commands/start.ts
  packages/cli/src/commands/webhook.ts
  packages/cli/src/commands/worker.ts
  packages/cli/src/config/schema.ts
  packages/cli/src/errors/worker-missing-encryption-key.error.ts
  packages/cli/src/scaling/__tests__/publisher.service.test.ts
  packages/cli/src/scaling/__tests__/subscriber.service.test.ts
  packages/cli/src/scaling/job-processor.ts
  packages/cli/src/scaling/pubsub/publisher.service.ts
  packages/cli/src/scaling/pubsub/pubsub-handler.ts
  packages/cli/src/scaling/pubsub/subscriber.service.ts
  packages/cli/src/scaling/scaling.service.ts
  packages/cli/src/scaling/worker-status.service.ts
  packages/cli/src/server.ts
  packages/cli/src/services/__tests__/orchestration.service.test.ts
  packages/cli/src/services/orchestration.service.ts
  packages/cli/src/services/orchestration/main/multi-main-setup.ee.ts
  packages/cli/src/services/orchestration/main/types.ts
  packages/cli/src/services/orchestration/worker/types.ts
  packages/cli/src/webhooks/webhook-server.ts
  packages/cli/test/integration/commands/worker.cmd.test.ts
  packages/core/package.json
  packages/core/src/InstanceSettings.ts
  packages/core/test/InstanceSettings.test.ts
  pnpm-lock.yaml
Labels: core, n8n team

#11263 fix(Set Node): Fix issue with UI properties not being hidden
  packages/nodes-base/nodes/Set/v2/SetV2.node.ts
Labels: node/improvement, n8n team

#11249 fix: Don't show pinned data tooltip for pinned nodes
  cypress/e2e/13-pinning.cy.ts
  cypress/e2e/16-webhook-node.cy.ts
  cypress/fixtures/Pinned_webhook_node.json
  packages/editor-ui/src/components/Node.vue
Labels: ui, n8n team

#11266 refactor(core): Remove dead orchestration code
  packages/cli/src/commands/webhook.ts
  packages/cli/src/commands/worker.ts
  packages/cli/src/permissions/global-roles.ts
  packages/cli/src/services/orchestration.handler.base.service.ts
  packages/cli/src/services/orchestration/main/types.ts
  packages/cli/src/services/orchestration/webhook/orchestration.webhook.service.ts
  packages/cli/src/services/orchestration/worker/orchestration.worker.service.ts
  packages/cli/src/services/orchestration/worker/types.ts
  packages/cli/test/integration/commands/worker.cmd.test.ts
Labels: core, n8n team

#11261 refactor(core): Convey error stack from job failure to main
  packages/cli/src/scaling/scaling.service.ts
  packages/cli/src/scaling/scaling.types.ts
Labels: core, n8n team

#11272 refactor: Move secrets provider imports (no-changelog)
  packages/cli/src/external-secrets/providers/azure-key-vault/azure-key-vault.ts
  packages/cli/src/external-secrets/providers/gcp-secrets-manager/gcp-secrets-manager.ts
Labels: core, n8n team

#10777 feat(Gong Node): New node
  packages/nodes-base/credentials/GongApi.credentials.ts
  packages/nodes-base/credentials/GongOAuth2Api.credentials.ts
  packages/nodes-base/nodes/Gong/GenericFunctions.ts
  packages/nodes-base/nodes/Gong/Gong.node.json
  packages/nodes-base/nodes/Gong/Gong.node.ts
  packages/nodes-base/nodes/Gong/descriptions/CallDescription.ts
  packages/nodes-base/nodes/Gong/descriptions/UserDescription.ts
  packages/nodes-base/nodes/Gong/descriptions/index.ts
  packages/nodes-base/nodes/Gong/gong.svg
  packages/nodes-base/nodes/Gong/test/Gong.node.test.ts
  packages/nodes-base/nodes/Gong/test/mocks.ts
  packages/nodes-base/package.json
  packages/nodes-base/test/nodes/FakeCredentialsMap.ts
  packages/nodes-base/test/nodes/Helpers.ts
  packages/workflow/src/Interfaces.ts
  packages/workflow/src/RoutingNode.ts
Labels: node/new, community, in linear

#11277 chore: Add `server_type` tag to Sentry errors (no-changelog)
  packages/cli/src/error-reporting.ts
Labels: core, n8n team

#11257 fix: Expressions display actual result of evaluating expression inside string
  packages/editor-ui/src/composables/useExpressionEditor.ts
Labels: ui, n8n team

#10504 feat(n8n Google My Business Node): New node
  packages/nodes-base/credentials/GoogleMyBusinessOAuth2Api.credentials.ts
  packages/nodes-base/nodes/Google/MyBusiness/GenericFunctions.ts
  packages/nodes-base/nodes/Google/MyBusiness/GoogleMyBusiness.node.json
  packages/nodes-base/nodes/Google/MyBusiness/GoogleMyBusiness.node.ts
  packages/nodes-base/nodes/Google/MyBusiness/GoogleMyBusinessTrigger.node.json
  packages/nodes-base/nodes/Google/MyBusiness/GoogleMyBusinessTrigger.node.ts
  packages/nodes-base/nodes/Google/MyBusiness/Interfaces.ts
  packages/nodes-base/nodes/Google/MyBusiness/PostDescription.ts
  packages/nodes-base/nodes/Google/MyBusiness/ReviewDescription.ts
  packages/nodes-base/nodes/Google/MyBusiness/googleMyBusines.svg
  packages/nodes-base/nodes/Google/MyBusiness/test/AddUpdateMask.test.ts
  packages/nodes-base/nodes/Google/MyBusiness/test/GoogleApiRequest.test.ts
  packages/nodes-base/nodes/Google/MyBusiness/test/HandleDatesPresend.test.ts
  packages/nodes-base/nodes/Google/MyBusiness/test/HandlePagination.test.ts
  packages/nodes-base/nodes/Google/MyBusiness/test/SearchAccounts.test.ts
  packages/nodes-base/nodes/Google/MyBusiness/test/SearchLocations.test.ts
  packages/nodes-base/nodes/Google/MyBusiness/test/SearchPosts.test.ts
  packages/nodes-base/nodes/Google/MyBusiness/test/SearchReviews.test.ts
  packages/nodes-base/package.json
Labels: node/new, community, in linear

#11275 refactor(core): Make orchestration service smaller
  packages/cli/src/__tests__/wait-tracker.test.ts
  packages/cli/src/active-workflow-manager.ts
  packages/cli/src/controllers/orchestration.controller.ts
  packages/cli/src/eventbus/message-event-bus/message-event-bus.ts
  packages/cli/src/external-secrets/__tests__/external-secrets-manager.ee.test.ts
  packages/cli/src/external-secrets/external-secrets-manager.ee.ts
  packages/cli/src/push/__tests__/index.test.ts
  packages/cli/src/push/index.ts
  packages/cli/src/requests.ts
  packages/cli/src/services/__tests__/orchestration.service.test.ts
  packages/cli/src/services/community-packages.service.ts
  packages/cli/src/services/orchestration.service.ts
  packages/cli/src/webhooks/__tests__/test-webhooks.test.ts
  packages/cli/src/webhooks/test-webhooks.ts
  packages/cli/test/integration/active-workflow-manager.test.ts
  packages/cli/test/integration/collaboration/collaboration.service.test.ts
  packages/cli/test/integration/eventbus.ee.test.ts
  packages/cli/test/integration/external-secrets/external-secrets.api.test.ts
  packages/cli/test/integration/shared/utils/index.ts
Labels: core, n8n team

#11285 fix: JS Task Runner not having access to Buffer (no-changelog)
  packages/@n8n/task-runner/src/js-task-runner/__tests__/js-task-runner.test.ts
  packages/@n8n/task-runner/src/js-task-runner/js-task-runner.ts
Labels: n8n team

#11161 fix(editor): Add Personal project to main navigation
  packages/design-system/src/components/N8nMenuItem/MenuItem.vue
  packages/editor-ui/src/components/Projects/ProjectNavigation.test.ts
  packages/editor-ui/src/components/Projects/ProjectNavigation.vue
  packages/editor-ui/src/plugins/i18n/locales/en.json
  packages/editor-ui/src/plugins/icons/index.ts
  packages/editor-ui/src/stores/projects.store.ts
Labels: ui, n8n team

#11288 fix(Pinecone Vector Store Node): Prevent populating of vectors after manually stopping the execution
  packages/@n8n/nodes-langchain/nodes/vector_store/shared/createVectorStoreNode.ts
Labels: n8n team

#11289 chore(core): Bring multi-main setup in line with scaling services
  packages/@n8n/config/src/configs/multi-main-setup.config.ts
  packages/@n8n/config/src/index.ts
  packages/@n8n/config/test/config.test.ts
  packages/cli/src/__tests__/license.test.ts
  packages/cli/src/__tests__/wait-tracker.test.ts
  packages/cli/src/commands/start.ts
  packages/cli/src/commands/webhook.ts
  packages/cli/src/config/schema.ts
  packages/cli/src/events/relays/telemetry.event-relay.ts
  packages/cli/src/license.ts
  packages/cli/src/scaling/multi-main-setup.ee.ts
  packages/cli/src/services/orchestration.service.ts
  packages/cli/src/services/pruning.service.ts
  packages/cli/test/integration/debug.controller.test.ts
  packages/cli/test/integration/pruning.service.test.ts
Labels: core, n8n team

#11290 fix(benchmark): Benchmark improvements
  packages/@n8n/benchmark/scenarios/binary-data/binary-data.script.js
  packages/@n8n/benchmark/scenarios/http-node/http-node.script.js
  packages/@n8n/benchmark/scenarios/js-code-node/js-code-node.script.js
  packages/@n8n/benchmark/scenarios/set-node-expressions/set-node-expressions.script.js
  packages/@n8n/benchmark/scenarios/single-webhook/single-webhook.script.js
  packages/@n8n/benchmark/scripts/n8n-setups/scaling-multi-main/docker-compose.yml
  packages/@n8n/benchmark/scripts/n8n-setups/scaling-multi-main/nginx.conf
  packages/@n8n/benchmark/scripts/run-in-cloud.mjs
  packages/@n8n/benchmark/scripts/vm-benchmark.sh
Labels: n8n team

#11282 chore(core): Add check to help diagnose PAY-2100
  packages/cli/src/workflow-runner.ts
Labels: core, n8n team

#11291 fix: Fix task runner error propagation (no-changelog)
  packages/@n8n/task-runner/src/js-task-runner/__tests__/js-task-runner.test.ts
  packages/@n8n/task-runner/src/js-task-runner/errors/__tests__/execution-error.test.ts
  packages/@n8n/task-runner/src/js-task-runner/errors/serializable-error.ts
  packages/@n8n/task-runner/src/js-task-runner/js-task-runner.ts
  packages/nodes-base/nodes/Code/errors/WrappedExecutionError.ts
Labels: node/improvement, n8n team
