Repository n8n-io/n8n, pull requests merged in 2024-07, with the labels that each got.

#9894 fix(core): Add a WebCrypto Polyfill for older versions of Node.js 18
  packages/cli/bin/n8n
Labels: core, n8n team

#9896 fix(editor): Fix new node credential creation via Resource Locator Component
  cypress/e2e/26-resource-locator.cy.ts
  cypress/pages/ndv.ts
  packages/editor-ui/src/components/NodeCredentials.vue
  packages/editor-ui/src/components/ResourceLocator/ResourceLocator.vue
  packages/editor-ui/src/utils/nodeTypesUtils.ts
Labels: ui, n8n team

#9657 feat: Add Zep Cloud Memory component
  packages/@n8n/nodes-langchain/credentials/ZepApi.credentials.ts
  packages/@n8n/nodes-langchain/nodes/memory/MemoryZep/MemoryZep.node.ts
  packages/@n8n/nodes-langchain/nodes/memory/MemoryZep/zep.png
  packages/@n8n/nodes-langchain/package.json
  packages/cli/package.json
  packages/workflow/package.json
  pnpm-lock.yaml
Labels: community, in linear

#9890 fix(Execute Workflow Node): Continue on fail behaviour not correctly implemented
  packages/nodes-base/nodes/ExecuteWorkflow/ExecuteWorkflow.node.ts
Labels: node/improvement, n8n team

#9528 feat(Merge Node): Overhaul, v3
  packages/core/src/NodeExecuteFunctions.ts
  packages/core/src/WorkflowExecute.ts
  packages/editor-ui/src/components/InputPanel.vue
  packages/editor-ui/src/components/Node.vue
  packages/editor-ui/src/stores/nodeTypes.store.ts
  packages/nodes-base/nodes/Merge/Merge.node.ts
  packages/nodes-base/nodes/Merge/test/v3/operations.test.ts
  packages/nodes-base/nodes/Merge/v2/MergeV2.node.ts
  packages/nodes-base/nodes/Merge/v2/descriptions.ts
  packages/nodes-base/nodes/Merge/v2/interfaces.ts
  packages/nodes-base/nodes/Merge/v2/utils.ts
  packages/nodes-base/nodes/Merge/v3/MergeV3.node.ts
  packages/nodes-base/nodes/Merge/v3/actions/mode/append.ts
  packages/nodes-base/nodes/Merge/v3/actions/mode/chooseBranch.ts
  packages/nodes-base/nodes/Merge/v3/actions/mode/combineAll.ts
  packages/nodes-base/nodes/Merge/v3/actions/mode/combineByFields.ts
  packages/nodes-base/nodes/Merge/v3/actions/mode/combineByPosition.ts
  packages/nodes-base/nodes/Merge/v3/actions/mode/combineBySql.ts
  packages/nodes-base/nodes/Merge/v3/actions/mode/index.ts
  packages/nodes-base/nodes/Merge/v3/actions/node.type.ts
  packages/nodes-base/nodes/Merge/v3/actions/router.ts
  packages/nodes-base/nodes/Merge/v3/actions/versionDescription.ts
  packages/nodes-base/nodes/Merge/v3/helpers/descriptions.ts
  packages/nodes-base/nodes/Merge/v3/helpers/interfaces.ts
  packages/nodes-base/nodes/Merge/v3/helpers/utils.ts
  packages/nodes-base/nodes/Merge/v3/methods/index.ts
  packages/nodes-base/nodes/Merge/v3/methods/loadOptions.ts
  packages/nodes-base/package.json
  packages/workflow/src/Constants.ts
  packages/workflow/src/Interfaces.ts
  packages/workflow/src/TelemetryHelpers.ts
  pnpm-lock.yaml
Labels: node/improvement, n8n team

#9901 fix(editor): Fix frontend project roles
  packages/editor-ui/src/stores/roles.store.test.ts
  packages/editor-ui/src/stores/roles.store.ts
Labels: ui, n8n team

#9910 fix(core): Fix AddActivatedAtUserSetting migration on MariaDB
  packages/cli/src/databases/migrations/mysqldb/1717498465931-AddActivatedAtUserSetting.ts
Labels: core, n8n team, release/backport

#9848 feat(GitHub Node): Add support for state reasons when editing an issue
  packages/nodes-base/nodes/Github/Github.node.ts
Labels: node/improvement, n8n team

#9904 fix(core): Filter out certain executions from crash recovery
  packages/cli/src/ActiveExecutions.ts
  packages/cli/src/commands/start.ts
  packages/cli/src/concurrency/__tests__/concurrency-control.service.test.ts
  packages/cli/src/concurrency/concurrency-control.service.ts
  packages/cli/src/concurrency/concurrency-queue.ts
  packages/cli/src/eventbus/EventMessageClasses/EventMessageExecution.ts
  packages/cli/src/eventbus/EventMessageClasses/index.ts
  packages/cli/src/eventbus/MessageEventBus/MessageEventBus.ts
  packages/cli/src/eventbus/MessageEventBusWriter/MessageEventBusLogWriter.ts
  packages/cli/src/eventbus/audit-event-relay.service.ts
  packages/cli/src/eventbus/event.types.ts
  packages/workflow/src/MessageEventBus.ts
Labels: core, n8n team, release/backport

#9891 refactor(editor): Migrate `tags.store` to use composition API (no-changelog)
  packages/editor-ui/src/components/MainHeader/WorkflowDetails.spec.ts
  packages/editor-ui/src/components/MainHeader/WorkflowDetails.vue
  packages/editor-ui/src/components/TagsContainer.vue
  packages/editor-ui/src/components/TagsDropdown.vue
  packages/editor-ui/src/components/TagsManager/TagsManager.vue
  packages/editor-ui/src/stores/tags.store.ts
Labels: ui, n8n team

#9889 refactor(editor): Convert Draggable components to composition API (no-changelog)
  cypress/e2e/14-mapping.cy.ts
  packages/editor-ui/src/components/AssignmentCollection/__tests__/AssignmentCollection.test.ts
  packages/editor-ui/src/components/Draggable.vue
  packages/editor-ui/src/components/DraggableTarget.vue
  packages/editor-ui/src/components/NDVDraggablePanels.vue
  packages/editor-ui/src/components/PanelDragButton.vue
  packages/editor-ui/src/components/RunDataTable.vue
Labels: ui, n8n team

#9895 feat: Introduce debug info button
  packages/cli/src/License.ts
  packages/cli/src/services/frontend.service.ts
  packages/editor-ui/src/Interface.ts
  packages/editor-ui/src/__tests__/defaults.ts
  packages/editor-ui/src/__tests__/utils.ts
  packages/editor-ui/src/components/AboutModal.vue
  packages/editor-ui/src/composables/useDebugInfo.ts
  packages/editor-ui/src/plugins/i18n/locales/en.json
  packages/editor-ui/src/stores/settings.store.ts
  packages/workflow/src/Interfaces.ts
Labels: core, ui, n8n team

#9911 feat(Zammad Node): Add reply_to and sender fields to article on ticket creation
  packages/nodes-base/nodes/Zammad/descriptions/TicketDescription.ts
  packages/nodes-base/nodes/Zammad/types.ts
Labels: node/improvement, community, in linear

#9887 feat(Embeddings Cohere Node): Add v3 Cohere models
  packages/@n8n/nodes-langchain/nodes/embeddings/EmbeddingsCohere/EmbeddingsCohere.node.ts
Labels: community, in linear

#9837 feat(Copper Node): Update credential to support HTTP Request node
  packages/nodes-base/credentials/CopperApi.credentials.ts
  packages/nodes-base/nodes/Copper/GenericFunctions.ts
Labels: node/improvement, community, in linear

#9919 fix(core): Fix worker logs relay
  packages/cli/src/commands/worker.ts
  packages/cli/test/integration/commands/worker.cmd.test.ts
Labels: core, n8n team, release/backport

#9852 ci: Update codecov setup (no-changelog)
  .github/workflows/ci-master.yml
  .github/workflows/units-tests-reusable.yml
  packages/@n8n/nodes-langchain/jest.config.js
Labels: n8n team

#9916 fix(core): Don't allow using credentials that are not part of the same project
  packages/cli/src/workflows/workflow.service.ee.ts
  packages/cli/test/integration/workflows/workflows.controller.ee.test.ts
Labels: core, n8n team

#9914 feat(editor): Add docs sidebar to credential modal
  packages/editor-ui/src/components/CredentialEdit/CredentialConfig.vue
  packages/editor-ui/src/components/CredentialEdit/CredentialDocs.vue
  packages/editor-ui/src/components/CredentialEdit/CredentialEdit.vue
  packages/editor-ui/src/components/CredentialEdit/docs.ts
  packages/editor-ui/src/components/Feedback.vue
  packages/editor-ui/src/plugins/i18n/locales/en.json
Labels: ui, n8n team

#9926 fix(editor): Don't try to load credentials on the demo route
  cypress/e2e/31-demo.cy.ts
  cypress/pages/demo.ts
  packages/editor-ui/src/views/NodeView.vue
Labels: ui, n8n team, release/backport

#9930 refactor: Improve types (no-changelog)
  packages/editor-ui/src/components/FilterConditions/utils.ts
  packages/workflow/src/Interfaces.ts
  packages/workflow/test/FilterParameter.test.ts
Labels: core, ui, n8n team

#9925 ci: Start typechecking `n8n-workflow` and `n8n-core` (no-changelog)
  package.json
  packages/core/test/helpers/constants.ts
  packages/editor-ui/src/components/FilterConditions/utils.ts
  packages/workflow/src/Interfaces.ts
  packages/workflow/test/FilterParameter.test.ts
  packages/workflow/test/TelemetryHelpers.test.ts
  packages/workflow/test/TypeValidation.test.ts
Labels: core, n8n team

#9929 refactor(core): Delete all collaboration related code (no-changelog)
  packages/cli/src/Interfaces.ts
  packages/cli/src/collaboration/collaboration.message.ts
  packages/cli/src/collaboration/collaboration.service.ts
  packages/cli/src/collaboration/collaboration.state.ts
  packages/cli/src/push/abstract.push.ts
  packages/cli/src/push/index.ts
  packages/cli/src/push/sse.push.ts
  packages/cli/src/push/types.ts
  packages/cli/src/push/websocket.push.ts
  packages/cli/test/unit/collaboration/collaboration.service.test.ts
  packages/cli/test/unit/collaboration/collaboration.state.test.ts
  packages/cli/test/unit/push/index.test.ts
  packages/cli/test/unit/push/websocket.push.test.ts
  packages/editor-ui/src/Interface.ts
  packages/editor-ui/src/components/MainHeader/CollaborationPane.vue
  packages/editor-ui/src/components/MainHeader/WorkflowDetails.vue
  packages/editor-ui/src/components/__tests__/CollaborationPane.test.ts
  packages/editor-ui/src/composables/__tests__/usePushConnection.spec.ts
  packages/editor-ui/src/composables/usePushConnection.ts
  packages/editor-ui/src/constants.ts
  packages/editor-ui/src/stores/collaboration.store.ts
  packages/editor-ui/src/views/NodeView.v2.vue
  packages/editor-ui/src/views/NodeView.vue
Labels: core, n8n team

#9892 refactor(editor): Migrate `ui.store` to use composition API (no-changelog)
  packages/editor-ui/src/Interface.ts
  packages/editor-ui/src/components/CredentialEdit/CredentialEdit.vue
  packages/editor-ui/src/components/FeatureComingSoon.vue
  packages/editor-ui/src/components/GenerateCurlModal.vue
  packages/editor-ui/src/components/ImportCurlModal.vue
  packages/editor-ui/src/components/InputPanel.vue
  packages/editor-ui/src/components/MainHeader/WorkflowDetails.vue
  packages/editor-ui/src/components/Modal.vue
  packages/editor-ui/src/components/ModalDrawer.vue
  packages/editor-ui/src/components/ModalRoot.vue
  packages/editor-ui/src/components/Node.vue
  packages/editor-ui/src/components/NodeDetailsView.vue
  packages/editor-ui/src/components/NodeExecuteButton.vue
  packages/editor-ui/src/components/OutputPanel.vue
  packages/editor-ui/src/components/Projects/ProjectMoveResourceConfirmModal.test.ts
  packages/editor-ui/src/components/SettingsSidebar.vue
  packages/editor-ui/src/components/SourceControlPushModal.ee.vue
  packages/editor-ui/src/components/Sticky.vue
  packages/editor-ui/src/components/TriggerPanel.vue
  packages/editor-ui/src/components/WorkflowLMChat.vue
  packages/editor-ui/src/components/__tests__/ChatEmbedModal.test.ts
  packages/editor-ui/src/components/__tests__/CommunityPackageInstallModal.spec.ts
  packages/editor-ui/src/components/__tests__/PersonalizationModal.spec.ts
  packages/editor-ui/src/components/__tests__/WorkflowSettings.spec.ts
  packages/editor-ui/src/components/canvas/elements/buttons/CanvasExecuteWorkflowButton.vue
  packages/editor-ui/src/composables/__tests__/useCanvasPanning.test.ts
  packages/editor-ui/src/composables/__tests__/useNodeBase.spec.ts
  packages/editor-ui/src/composables/__tests__/useRunWorkflow.spec.ts
  packages/editor-ui/src/composables/useCanvasMouseSelect.ts
  packages/editor-ui/src/composables/useCanvasPanning.ts
  packages/editor-ui/src/composables/useNodeBase.ts
  packages/editor-ui/src/composables/usePushConnection.ts
  packages/editor-ui/src/composables/useRunWorkflow.ts
  packages/editor-ui/src/composables/useToast.ts
  packages/editor-ui/src/hooks/utils/hooksAddFakeDoorFeatures.ts
  packages/editor-ui/src/plugins/codemirror/completions/__tests__/completions.test.ts
  packages/editor-ui/src/plugins/codemirror/completions/utils.ts
  packages/editor-ui/src/stores/__tests__/ui.test.ts
  packages/editor-ui/src/stores/canvas.store.ts
  packages/editor-ui/src/stores/ui.store.ts
  packages/editor-ui/src/views/NodeView.vue
  packages/editor-ui/src/views/SettingsFakeDoorView.vue
Labels: ui, n8n team

#9590 fix(Invoice Ninja Node): Fix assigning an invoice to a payment
  packages/nodes-base/nodes/InvoiceNinja/InvoiceNinja.node.ts
  packages/nodes-base/nodes/InvoiceNinja/PaymentInterface.ts
Labels: node/improvement, community, in linear

#9931 refactor(core): Remove Ask AI HTTP request feature (no-changelog)
  packages/cli/package.json
  packages/cli/src/Server.ts
  packages/cli/src/config/schema.ts
  packages/cli/src/constants.ts
  packages/cli/src/controllers/ai.controller.ts
  packages/cli/src/errors/response-errors/failed-dependency.error.ts
  packages/cli/src/requests.ts
  packages/cli/src/services/ai.service.ts
  packages/cli/src/services/ai/prompts/generateCurl.ts
  packages/cli/src/services/ai/prompts/retrieveService.ts
  packages/cli/src/services/ai/providers/openai.ts
  packages/cli/src/services/ai/resources/README.md
  packages/cli/src/services/ai/resources/api-knowledgebase.json
  packages/cli/src/services/ai/schemas/generateCurl.ts
  packages/cli/src/services/ai/schemas/retrieveService.ts
  packages/cli/src/services/ai/utils/summarizeNodeTypeProperties.ts
  packages/cli/src/services/frontend.service.ts
  packages/cli/src/types/ai.types.ts
  packages/cli/test/unit/services/ai.service.test.ts
  packages/cli/test/unit/services/ai/utils/summarizeNodeTypeProperties.test.ts
  packages/editor-ui/src/App.vue
  packages/editor-ui/src/Interface.ts
  packages/editor-ui/src/__tests__/defaults.ts
  packages/editor-ui/src/api/ai.ts
  packages/editor-ui/src/components/AIAssistantChat/AIAssistantChat.vue
  packages/editor-ui/src/components/AIAssistantChat/NextStepPopup.vue
  packages/editor-ui/src/components/AIAssistantChat/QuickReplies.vue
  packages/editor-ui/src/components/GenerateCurlModal.vue
  packages/editor-ui/src/components/ImportCurlParameter.vue
  packages/editor-ui/src/components/Modals.vue
  packages/editor-ui/src/components/Node/NodeCreator/NodeCreator.vue
  packages/editor-ui/src/constants.ts
  packages/editor-ui/src/n8n-theme-variables.scss
  packages/editor-ui/src/n8n-theme.scss
  packages/editor-ui/src/plugins/i18n/locales/en.json
  packages/editor-ui/src/stores/ai.store.ts
  packages/editor-ui/src/stores/nodeCreator.store.ts
  packages/editor-ui/src/stores/ui.store.ts
  packages/editor-ui/src/views/NodeView.vue
  packages/workflow/src/Interfaces.ts
  pnpm-lock.yaml
Labels: core, ui, n8n team

#9906 refactor(core): Centralize SSH Tunnel management
  packages/core/package.json
  packages/core/src/NodeExecuteFunctions.ts
  packages/core/src/SSHClientsManager.ts
  packages/core/test/SSHClientsManager.test.ts
  packages/nodes-base/credentials/MySql.credentials.ts
  packages/nodes-base/credentials/Postgres.credentials.ts
  packages/nodes-base/nodes/MySql/v2/actions/router.ts
  packages/nodes-base/nodes/MySql/v2/helpers/interfaces.ts
  packages/nodes-base/nodes/MySql/v2/methods/credentialTest.ts
  packages/nodes-base/nodes/MySql/v2/methods/listSearch.ts
  packages/nodes-base/nodes/MySql/v2/methods/loadOptions.ts
  packages/nodes-base/nodes/MySql/v2/transport/index.ts
  packages/nodes-base/nodes/Postgres/PostgresTrigger.functions.ts
  packages/nodes-base/nodes/Postgres/v2/actions/router.ts
  packages/nodes-base/nodes/Postgres/v2/helpers/interfaces.ts
  packages/nodes-base/nodes/Postgres/v2/methods/credentialTest.ts
  packages/nodes-base/nodes/Postgres/v2/methods/listSearch.ts
  packages/nodes-base/nodes/Postgres/v2/methods/loadOptions.ts
  packages/nodes-base/nodes/Postgres/v2/methods/resourceMapping.ts
  packages/nodes-base/nodes/Postgres/v2/transport/index.ts
  packages/nodes-base/package.json
  packages/nodes-base/utils/constants.ts
  packages/nodes-base/utils/sshTunnel.properties.ts
  packages/workflow/src/Interfaces.ts
  pnpm-lock.yaml
Labels: node/improvement, core, n8n team

#9937 fix(editor): Improve the contrast in the Chat Window in dark mode (no-changelog)
  packages/design-system/src/css/_tokens.dark.scss
  packages/design-system/src/css/_tokens.scss
  packages/editor-ui/src/components/WorkflowLMChat.vue
Labels: ui, n8n team

#9933 refactor(core): Remove Onboarding call prompts (no-changelog)
  packages/cli/src/config/schema.ts
  packages/cli/src/services/frontend.service.ts
  packages/editor-ui/src/Interface.ts
  packages/editor-ui/src/__tests__/defaults.ts
  packages/editor-ui/src/__tests__/utils.ts
  packages/editor-ui/src/api/workflow-webhooks.ts
  packages/editor-ui/src/components/Modals.vue
  packages/editor-ui/src/components/OnboardingCallSignupModal.vue
  packages/editor-ui/src/components/PersonalizationModal.vue
  packages/editor-ui/src/constants.ts
  packages/editor-ui/src/plugins/i18n/locales/en.json
  packages/editor-ui/src/stores/settings.store.ts
  packages/editor-ui/src/stores/ui.store.ts
  packages/editor-ui/src/utils/userUtils.ts
  packages/editor-ui/src/views/NodeView.vue
  packages/workflow/src/Interfaces.ts
Labels: core, ui, n8n team

#9936 fix(HTML Node): Fix small typo (no-changelog)
  packages/nodes-base/nodes/Html/Html.node.ts
Labels: node/improvement, n8n team

#9900 feat: Qdrant Vector Store search filter
  packages/@n8n/nodes-langchain/nodes/vector_store/VectorStoreQdrant/VectorStoreQdrant.node.ts
  packages/@n8n/nodes-langchain/package.json
  packages/@n8n/nodes-langchain/utils/helpers.ts
  pnpm-lock.yaml
Labels: node/improvement, n8n team

#9813 feat(Splunk Node): Overhaul
  packages/nodes-base/credentials/SplunkApi.credentials.ts
  packages/nodes-base/nodes/Splunk/Splunk.node.ts
  packages/nodes-base/nodes/Splunk/splunk.svg
  packages/nodes-base/nodes/Splunk/test/v2/node/alert.test.ts
  packages/nodes-base/nodes/Splunk/test/v2/node/report.test.ts
  packages/nodes-base/nodes/Splunk/test/v2/node/search.test.ts
  packages/nodes-base/nodes/Splunk/test/v2/node/user.test.ts
  packages/nodes-base/nodes/Splunk/test/v2/utils.test.ts
  packages/nodes-base/nodes/Splunk/v1/GenericFunctions.ts
  packages/nodes-base/nodes/Splunk/v1/SplunkV1.node.ts
  packages/nodes-base/nodes/Splunk/v1/descriptions/FiredAlertDescription.ts
  packages/nodes-base/nodes/Splunk/v1/descriptions/SearchConfigurationDescription.ts
  packages/nodes-base/nodes/Splunk/v1/descriptions/SearchJobDescription.ts
  packages/nodes-base/nodes/Splunk/v1/descriptions/SearchResultDescription.ts
  packages/nodes-base/nodes/Splunk/v1/descriptions/UserDescription.ts
  packages/nodes-base/nodes/Splunk/v1/descriptions/index.ts
  packages/nodes-base/nodes/Splunk/v1/types.ts
  packages/nodes-base/nodes/Splunk/v2/SplunkV2.node.ts
  packages/nodes-base/nodes/Splunk/v2/actions/alert/getMetrics.operation.ts
  packages/nodes-base/nodes/Splunk/v2/actions/alert/getReport.operation.ts
  packages/nodes-base/nodes/Splunk/v2/actions/alert/index.ts
  packages/nodes-base/nodes/Splunk/v2/actions/node.type.ts
  packages/nodes-base/nodes/Splunk/v2/actions/report/create.operation.ts
  packages/nodes-base/nodes/Splunk/v2/actions/report/deleteReport.operation.ts
  packages/nodes-base/nodes/Splunk/v2/actions/report/get.operation.ts
  packages/nodes-base/nodes/Splunk/v2/actions/report/getAll.operation.ts
  packages/nodes-base/nodes/Splunk/v2/actions/report/index.ts
  packages/nodes-base/nodes/Splunk/v2/actions/router.ts
  packages/nodes-base/nodes/Splunk/v2/actions/search/create.operation.ts
  packages/nodes-base/nodes/Splunk/v2/actions/search/deleteJob.operation.ts
  packages/nodes-base/nodes/Splunk/v2/actions/search/get.operation.ts
  packages/nodes-base/nodes/Splunk/v2/actions/search/getAll.operation.ts
  packages/nodes-base/nodes/Splunk/v2/actions/search/getResult.operation.ts
  packages/nodes-base/nodes/Splunk/v2/actions/search/index.ts
  packages/nodes-base/nodes/Splunk/v2/actions/user/create.operation.ts
  packages/nodes-base/nodes/Splunk/v2/actions/user/deleteUser.operation.ts
  packages/nodes-base/nodes/Splunk/v2/actions/user/get.operation.ts
  packages/nodes-base/nodes/Splunk/v2/actions/user/getAll.operation.ts
  packages/nodes-base/nodes/Splunk/v2/actions/user/index.ts
  packages/nodes-base/nodes/Splunk/v2/actions/user/update.operation.ts
  packages/nodes-base/nodes/Splunk/v2/actions/versionDescription.ts
  packages/nodes-base/nodes/Splunk/v2/helpers/descriptions/index.ts
  packages/nodes-base/nodes/Splunk/v2/helpers/descriptions/rlc.description.ts
  packages/nodes-base/nodes/Splunk/v2/helpers/interfaces.ts
  packages/nodes-base/nodes/Splunk/v2/helpers/utils.ts
  packages/nodes-base/nodes/Splunk/v2/methods/index.ts
  packages/nodes-base/nodes/Splunk/v2/methods/listSearch.ts
  packages/nodes-base/nodes/Splunk/v2/methods/loadOptions.ts
  packages/nodes-base/nodes/Splunk/v2/transport/index.ts
Labels: node/improvement, n8n team

#9928 fix(core): Disconnect Redis after pausing queue during worker shutdown
  packages/cli/src/Queue.ts
  packages/cli/src/commands/worker.ts
  packages/cli/src/decorators/OnShutdown.ts
  packages/cli/src/services/redis/RedisServiceBaseClasses.ts
  packages/cli/src/services/redis/redis-client.service.ts
  packages/cli/test/integration/shared/utils/testCommand.ts
Labels: core, n8n team

#9944 refactor(core): Enforce range for shutdown priority (no-changelog)
  packages/cli/src/Queue.ts
  packages/cli/src/constants.ts
  packages/cli/src/decorators/OnShutdown.ts
  packages/cli/src/services/redis/redis-client.service.ts
  packages/cli/src/shutdown/Shutdown.service.ts
  packages/cli/test/unit/decorators/OnShutdown.test.ts
Labels: core, n8n team

#9589 fix(Invoice Ninja Node): Fix emailing and marking invoice as paid / sent
  packages/nodes-base/nodes/InvoiceNinja/InvoiceDescription.ts
  packages/nodes-base/nodes/InvoiceNinja/InvoiceNinja.node.ts
  packages/nodes-base/nodes/InvoiceNinja/QuoteDescription.ts
  packages/nodes-base/nodes/InvoiceNinja/invoiceInterface.ts
Labels: node/improvement, community, in linear

#9947 refactor: Extract ISOCountryCodes into a single place (no-changelog)
  packages/nodes-base/nodes/Copper/descriptions/CompanyDescription.ts
  packages/nodes-base/nodes/Copper/utils/isoCountryCodes.ts
  packages/nodes-base/nodes/Google/YouTube/CountryCodes.ts
  packages/nodes-base/nodes/Google/YouTube/YouTube.node.ts
  packages/nodes-base/nodes/HelpScout/CountriesCodes.ts
  packages/nodes-base/nodes/HelpScout/HelpScout.node.ts
  packages/nodes-base/nodes/InvoiceNinja/ISOCountryCodes.ts
  packages/nodes-base/nodes/InvoiceNinja/InvoiceNinja.node.ts
  packages/nodes-base/nodes/Spotify/Spotify.node.ts
  packages/nodes-base/utils/ISOCountryCodes.ts
Labels: node/improvement, n8n team

#9945 fix(Invoice Ninja Node): Fix some fields names (no-changelog)
  packages/nodes-base/nodes/InvoiceNinja/ClientDescription.ts
  packages/nodes-base/nodes/InvoiceNinja/InvoiceNinja.node.ts
Labels: node/improvement, n8n team

#9946 ci: Do not run notify-pr-status workflow on community PRs (no-changelog)
  .github/workflows/notify-pr-status.yml
Labels: n8n team

#9943 fix: Rename LDAP files to include .ee (no-changelog)
  packages/cli/src/Ldap/helpers.ee.ts
  packages/cli/src/Ldap/ldap.controller.ee.ts
  packages/cli/src/Ldap/ldap.service.ee.ts
  packages/cli/src/Server.ts
  packages/cli/src/auth/methods/email.ts
  packages/cli/src/auth/methods/ldap.ts
  packages/cli/src/services/frontend.service.ts
  packages/cli/test/integration/commands/ldap/reset.test.ts
  packages/cli/test/integration/ldap/ldap.api.test.ts
  packages/cli/test/integration/shared/utils/testServer.ts
  packages/cli/test/unit/Ldap/helpers.test.ts
Labels: core, n8n team

#9951 fix(core): Add DB host to n8n environment variables for dev-containers (no-changelog)
  .devcontainer/docker-compose.yml
Labels: n8n team

#9952 feat: Simplify n8n/chat build process (no-changelog)
  packages/@n8n/chat/README.md
  packages/@n8n/chat/build.config.js
  packages/@n8n/chat/package.json
  packages/@n8n/chat/scripts/pack.js
  packages/@n8n/chat/scripts/postbuild.js
  packages/@n8n/chat/src/env.d.ts
  packages/@n8n/chat/src/style.scss
  packages/@n8n/chat/tsconfig.json
  packages/@n8n/nodes-langchain/nodes/trigger/ChatTrigger/templates.ts
  packages/editor-ui/src/components/ChatEmbedModal.vue
  pnpm-lock.yaml
Labels: ui, n8n team

#9954 ci: Make pinning e2e test work locally (no-changelog)
  .github/workflows/e2e-reusable.yml
  cypress/cypress.config.js
  cypress/e2e/13-pinning.cy.ts
  cypress/scripts/run-e2e.js
  cypress/support/index.ts
  packages/editor-ui/src/composables/usePinnedData.ts
  packages/editor-ui/src/constants.ts
  packages/editor-ui/src/shims.d.ts
Labels: ui, n8n team

#9696 ci: Use turbo for build cache (no-changelog)
  .github/workflows/ci-master.yml
  .github/workflows/ci-postgres-mysql.yml
  .github/workflows/ci-pull-requests.yml
  .github/workflows/linting-reusable.yml
  .github/workflows/units-tests-reusable.yml
  package.json
  packages/@n8n/chat/package.json
  pnpm-lock.yaml
  turbo.json
Labels: core, n8n team

#9950 fix(Google Sheets Node): Append fails if cells have some default values added by data validation rules
  packages/nodes-base/nodes/Google/Sheet/test/v2/utils/utils.test.ts
  packages/nodes-base/nodes/Google/Sheet/v2/actions/sheet/append.operation.ts
  packages/nodes-base/nodes/Google/Sheet/v2/actions/sheet/appendOrUpdate.operation.ts
  packages/nodes-base/nodes/Google/Sheet/v2/actions/sheet/read.operation.ts
  packages/nodes-base/nodes/Google/Sheet/v2/actions/sheet/update.operation.ts
  packages/nodes-base/nodes/Google/Sheet/v2/actions/versionDescription.ts
  packages/nodes-base/nodes/Google/Sheet/v2/helpers/GoogleSheet.ts
Labels: n8n team, node/issue

#9959 refactor(editor): Rename `$emits` to `emits` where we use `defineEmits` (no-changelog)
  packages/@n8n_io/eslint-config/frontend.js
  packages/design-system/src/components/N8nActionDropdown/ActionDropdown.vue
  packages/design-system/src/components/N8nActionToggle/ActionToggle.vue
  packages/design-system/src/components/N8nButton/Button.vue
  packages/design-system/src/components/N8nDatatable/Datatable.vue
  packages/design-system/src/components/N8nFormBox/FormBox.vue
  packages/design-system/src/components/N8nFormInput/FormInput.vue
  packages/design-system/src/components/N8nInfoAccordion/InfoAccordion.vue
  packages/design-system/src/components/N8nMarkdown/Markdown.vue
  packages/design-system/src/components/N8nMenu/Menu.vue
  packages/design-system/src/components/N8nNotice/Notice.vue
  packages/design-system/src/components/N8nRadioButtons/RadioButtons.vue
  packages/design-system/src/components/N8nResizeWrapper/ResizeWrapper.vue
  packages/design-system/src/components/N8nTabs/Tabs.vue
  packages/design-system/src/components/N8nTags/Tags.vue
  packages/design-system/src/components/N8nUserSelect/UserSelect.vue
  packages/editor-ui/src/components/CredentialPicker/CredentialPicker.vue
  packages/editor-ui/src/components/CredentialPicker/CredentialsDropdown.vue
Labels: ui, n8n team

#9966 ci: Pass env variables down in e2e dev tasks (no-changelog)
  package.json
Labels: n8n team

#9902 feat(editor): Add execute workflow functionality and statuses to new canvas (no-changelog)
  packages/editor-ui/package.json
  packages/editor-ui/src/__tests__/data/canvas.ts
  packages/editor-ui/src/__tests__/mocks.ts
  packages/editor-ui/src/components/canvas/Canvas.vue
  packages/editor-ui/src/components/canvas/elements/edges/CanvasEdge.spec.ts
  packages/editor-ui/src/components/canvas/elements/edges/CanvasEdge.vue
  packages/editor-ui/src/components/canvas/elements/nodes/CanvasNodeRenderer.spec.ts
  packages/editor-ui/src/components/canvas/elements/nodes/render-types/CanvasNodeConfigurable.spec.ts
  packages/editor-ui/src/components/canvas/elements/nodes/render-types/CanvasNodeConfigurable.vue
  packages/editor-ui/src/components/canvas/elements/nodes/render-types/CanvasNodeConfiguration.spec.ts
  packages/editor-ui/src/components/canvas/elements/nodes/render-types/CanvasNodeConfiguration.vue
  packages/editor-ui/src/components/canvas/elements/nodes/render-types/CanvasNodeDefault.spec.ts
  packages/editor-ui/src/components/canvas/elements/nodes/render-types/CanvasNodeDefault.vue
  packages/editor-ui/src/components/canvas/elements/nodes/render-types/parts/CanvasNodeDisabledStrikeThrough.vue
  packages/editor-ui/src/components/canvas/elements/nodes/render-types/parts/CanvasNodeStatusIcons.vue
  packages/editor-ui/src/composables/__tests__/useCanvasOperations.spec.ts
  packages/editor-ui/src/composables/useCanvasMapping.spec.ts
  packages/editor-ui/src/composables/useCanvasMapping.ts
  packages/editor-ui/src/composables/useCanvasNode.spec.ts
  packages/editor-ui/src/composables/useCanvasNode.ts
  packages/editor-ui/src/composables/useCanvasOperations.ts
  packages/editor-ui/src/composables/useNodeHelpers.ts
  packages/editor-ui/src/composables/useWorkflowHelpers.ts
  packages/editor-ui/src/constants.ts
  packages/editor-ui/src/router.ts
  packages/editor-ui/src/stores/workflows.store.ts
  packages/editor-ui/src/styles/plugins/_codemirror.scss
  packages/editor-ui/src/types/canvas.ts
  packages/editor-ui/src/utils/__tests__/canvasUtilsV2.spec.ts
  packages/editor-ui/src/utils/canvasUtilsV2.ts
  packages/editor-ui/src/utils/typeGuards.ts
  packages/editor-ui/src/views/NodeView.v2.vue
  pnpm-lock.yaml
Labels: ui, n8n team

#9713 feat(Google Cloud Firestore Node): Add support for service account and document creation with id
  packages/nodes-base/nodes/Google/Firebase/CloudFirestore/DocumentDescription.ts
  packages/nodes-base/nodes/Google/Firebase/CloudFirestore/GenericFunctions.ts
  packages/nodes-base/nodes/Google/Firebase/CloudFirestore/GoogleFirebaseCloudFirestore.node.ts
  packages/nodes-base/nodes/Google/GenericFunctions.ts
Labels: node/improvement, community, in linear

#9967 feat(editor): Add prompt to save when leaving with unsaved changes in new canvas (no-changelog)
  packages/editor-ui/src/composables/useMessage.ts
  packages/editor-ui/src/router.ts
  packages/editor-ui/src/views/NodeView.v2.vue
Labels: ui, n8n team

#9964 refactor(editor): Remove getters with arguments from `communityNodes.store.ts`
  packages/editor-ui/src/components/CommunityPackageManageConfirmModal.vue
  packages/editor-ui/src/stores/communityNodes.store.ts
Labels: ui, n8n team

#9960 refactor(editor): Migrate `users.store` to composition API (no-changelog)
  packages/editor-ui/src/Interface.ts
  packages/editor-ui/src/components/DeleteUserModal.vue
  packages/editor-ui/src/components/MfaSetupModal.vue
  packages/editor-ui/src/components/Projects/ProjectSettings.vue
  packages/editor-ui/src/components/__tests__/BannersStack.test.ts
  packages/editor-ui/src/components/__tests__/PersonalizationModal.spec.ts
  packages/editor-ui/src/components/banners/__tests__/V1Banner.spec.ts
  packages/editor-ui/src/stores/__tests__/posthog.test.ts
  packages/editor-ui/src/stores/users.store.ts
  packages/editor-ui/src/views/SettingsUsersView.vue
  packages/editor-ui/src/views/__tests__/SettingsPersonalView.test.ts
Labels: ui, n8n team

#9958 refactor(editor): Migrate `OutputPanel.vue` to composition API (no-changelog)
  packages/editor-ui/src/components/OutputPanel.vue
Labels: ui, n8n team

#9802 feat(Chat Trigger Node): Add support for file uploads & harmonize public and development chat
  cypress/composables/modals/chat-modal.ts
  packages/@n8n/chat/package.json
  packages/@n8n/chat/src/__stories__/App.stories.ts
  packages/@n8n/chat/src/api/generic.ts
  packages/@n8n/chat/src/api/message.ts
  packages/@n8n/chat/src/components/ChatFile.vue
  packages/@n8n/chat/src/components/Input.vue
  packages/@n8n/chat/src/components/Message.vue
  packages/@n8n/chat/src/components/MessageTyping.vue
  packages/@n8n/chat/src/components/MessagesList.vue
  packages/@n8n/chat/src/css/index.scss
  packages/@n8n/chat/src/css/markdown.scss
  packages/@n8n/chat/src/plugins/chat.ts
  packages/@n8n/chat/src/types/chat.ts
  packages/@n8n/chat/src/types/messages.ts
  packages/@n8n/chat/src/types/options.ts
  packages/@n8n/nodes-langchain/nodes/agents/Agent/agents/ToolsAgent/description.ts
  packages/@n8n/nodes-langchain/nodes/agents/Agent/agents/ToolsAgent/execute.ts
  packages/@n8n/nodes-langchain/nodes/document_loaders/DocumentDefaultDataLoader/DocumentDefaultDataLoader.node.ts
  packages/@n8n/nodes-langchain/nodes/trigger/ChatTrigger/ChatTrigger.node.ts
  packages/@n8n/nodes-langchain/nodes/trigger/ChatTrigger/templates.ts
  packages/@n8n/nodes-langchain/utils/N8nBinaryLoader.ts
  packages/@n8n/nodes-langchain/utils/helpers.ts
  packages/editor-ui/package.json
  packages/editor-ui/src/components/Modals.vue
  packages/editor-ui/src/components/WorkflowLMChat.vue
  packages/editor-ui/src/components/WorkflowLMChat/MessageOptionAction.vue
  packages/editor-ui/src/components/WorkflowLMChat/MessageOptionTooltip.vue
  packages/editor-ui/src/components/WorkflowLMChat/WorkflowLMChat.vue
  packages/editor-ui/src/components/__tests__/WorkflowLMChatModal.test.ts
  packages/editor-ui/src/composables/__tests__/useClipboard.test.ts
  pnpm-lock.yaml
Labels: ui, n8n team

#9977 fix(editor): Use `workflowHelpers.getWebhookUrl` to determine webhook/form test URL (no-changelog)
  packages/editor-ui/src/composables/useRunWorkflow.ts
Labels: ui, n8n team

#9973 ci: Remove unused dependencies (no-changelog)
  packages/@n8n/nodes-langchain/package.json
  packages/cli/package.json
  packages/design-system/package.json
  packages/editor-ui/package.json
  packages/nodes-base/package.json
  pnpm-lock.yaml
Labels: core, ui, n8n team

#9905 fix(core): Don't execute 'workflowExecuteBefore' hook on execution continuations
  packages/cli/src/WorkflowRunner.ts
Labels: core, n8n team, release/backport

#9922 fix(core): Allow owner and admin to edit nodes with credentials that haven't been shared with them explicitly
  cypress/e2e/17-sharing.cy.ts
  packages/cli/src/credentials/credentials.service.ts
  packages/cli/src/workflows/workflow.service.ee.ts
  packages/cli/test/integration/workflows/workflows.controller.ee.test.ts
Labels: core, n8n team

#9981 fix(core): Use Custom cache-control headers force cache-revalidation on `/types/*.json` (no-changelog)
  packages/cli/src/Server.ts
Labels: core, n8n team

#9979 fix(core): Clear active execution on cancellation in scaling mode
  packages/cli/src/executions/__tests__/execution.service.test.ts
  packages/cli/src/executions/execution.service.ts
Labels: core, n8n team

#9983 fix(core): Ensure correct `Cache-Control` header on `/` as well (no-changelog)
  packages/cli/src/Server.ts
Labels: core, n8n team

#9988 fix(editor): Fix the regression in runWorkflow, introduced in #9977 (no-changelog)
  packages/editor-ui/src/composables/useRunWorkflow.ts
Labels: ui, n8n team

#9962 feat(Orbit Node): Deprecate Orbit nicely
  packages/nodes-base/credentials/OrbitApi.credentials.ts
  packages/nodes-base/nodes/Orbit/ActivityDescription.ts
  packages/nodes-base/nodes/Orbit/MemberDescription.ts
  packages/nodes-base/nodes/Orbit/NoteDescription.ts
  packages/nodes-base/nodes/Orbit/Orbit.node.ts
  packages/nodes-base/nodes/Orbit/PostDescription.ts
Labels: node/improvement, n8n team

#9986 feat(editor): Add ability to execute a specific node to canvas v2 (no-changelog)
  packages/editor-ui/src/components/canvas/Canvas.vue
  packages/editor-ui/src/components/canvas/elements/nodes/CanvasNode.vue
  packages/editor-ui/src/components/canvas/elements/nodes/CanvasNodeToolbar.vue
  packages/editor-ui/src/views/NodeView.v2.vue
Labels: ui, n8n team

#9984 feat(editor): Add execution indication to canvas v2 (no-changelog)
  packages/design-system/src/css/_tokens.scss
  packages/editor-ui/src/__tests__/data/canvas.ts
  packages/editor-ui/src/components/canvas/Canvas.spec.ts
  packages/editor-ui/src/components/canvas/Canvas.vue
  packages/editor-ui/src/components/canvas/WorkflowCanvas.vue
  packages/editor-ui/src/components/canvas/elements/edges/CanvasEdge.spec.ts
  packages/editor-ui/src/components/canvas/elements/edges/CanvasEdge.vue
  packages/editor-ui/src/components/canvas/elements/nodes/CanvasNode.spec.ts
  packages/editor-ui/src/components/canvas/elements/nodes/render-types/CanvasNodeConfigurable.spec.ts
  packages/editor-ui/src/components/canvas/elements/nodes/render-types/CanvasNodeDefault.spec.ts
  packages/editor-ui/src/components/canvas/elements/nodes/render-types/CanvasNodeDefault.vue
  packages/editor-ui/src/components/canvas/elements/nodes/render-types/parts/CanvasNodeStatusIcons.spec.ts
  packages/editor-ui/src/components/canvas/elements/nodes/render-types/parts/CanvasNodeStatusIcons.vue
  packages/editor-ui/src/composables/useCanvasMapping.spec.ts
  packages/editor-ui/src/composables/useCanvasMapping.ts
  packages/editor-ui/src/composables/useCanvasNode.spec.ts
  packages/editor-ui/src/composables/useCanvasNode.ts
  packages/editor-ui/src/types/canvas.ts
Labels: ui, n8n team

#9968 feat(editor): Add stop current execution button in new canvas (no-changelog)
  packages/editor-ui/src/components/canvas/elements/buttons/CanvasExecuteWorkflowButton.spec.ts
  packages/editor-ui/src/components/canvas/elements/buttons/CanvasExecuteWorkflowButton.vue
  packages/editor-ui/src/components/canvas/elements/buttons/CanvasStopCurrentExecutionButton.spec.ts
  packages/editor-ui/src/components/canvas/elements/buttons/CanvasStopCurrentExecutionButton.vue
  packages/editor-ui/src/components/canvas/elements/buttons/CanvasStopWaitingForWebhookButton.spec.ts
  packages/editor-ui/src/components/canvas/elements/buttons/CanvasStopWaitingForWebhookButton.vue
  packages/editor-ui/src/components/canvas/elements/buttons/__snapshots__/CanvasExecuteWorkflowButton.spec.ts.snap
  packages/editor-ui/src/components/canvas/elements/buttons/__snapshots__/CanvasStopCurrentExecutionButton.spec.ts.snap
  packages/editor-ui/src/components/canvas/elements/buttons/__snapshots__/CanvasStopWaitingForWebhookButton.spec.ts.snap
  packages/editor-ui/src/composables/__tests__/useCanvasOperations.spec.ts
  packages/editor-ui/src/composables/useCanvasOperations.ts
  packages/editor-ui/src/composables/useNodeHelpers.ts
  packages/editor-ui/src/composables/useRunWorkflow.ts
  packages/editor-ui/src/composables/useWorkflowHelpers.ts
  packages/editor-ui/src/views/NodeView.v2.vue
Labels: ui, n8n team

#9978 feat(editor): Open node creator when cancelling a connection in new canvas (no-changelog)
  packages/editor-ui/src/components/canvas/Canvas.vue
  packages/editor-ui/src/types/canvas.ts
  packages/editor-ui/src/views/NodeView.v2.vue
Labels: ui, n8n team

#9980 fix(core): Aborting manual trigger tests should call `closeFunction`
  packages/workflow/src/Workflow.ts
  packages/workflow/test/Workflow.test.ts
Labels: core, n8n team

#9511 feat(Telegram Node): Add support to Keyboard Button Mini Apps
  packages/nodes-base/nodes/Telegram/Telegram.node.ts
Labels: node/improvement, ui, community, in linear

#9953 fix(core): Prevent multiple values in the execution metadata for the same key and executionId
  packages/cli/src/databases/dsl/Column.ts
  packages/cli/src/databases/entities/ExecutionMetadata.ts
  packages/cli/src/databases/migrations/common/1720101653148-AddConstraintToExecutionMetadata.ts
  packages/cli/src/databases/migrations/mysqldb/index.ts
  packages/cli/src/databases/migrations/postgresdb/index.ts
  packages/cli/src/databases/migrations/sqlite/index.ts
  packages/cli/src/services/executionMetadata.service.ts
  packages/cli/test/integration/services/executionMetadata.service.test.ts
  packages/cli/test/unit/ExecutionMetadataService.test.ts
Labels: core, n8n team

#9994 ci: Ensure that all published packages have consistent provenance data in package.json
  .github/scripts/ensure-provenance-fields.mjs
  .github/workflows/release-publish.yml
  package.json
  packages/@n8n/chat/LICENSE.md
  packages/@n8n/chat/package.json
  packages/@n8n/client-oauth2/package.json
  packages/@n8n/imap/package.json
  packages/@n8n/nodes-langchain/LICENSE.md
  packages/@n8n/nodes-langchain/package.json
  packages/@n8n/permissions/package.json
  packages/cli/LICENSE.md
  packages/cli/LICENSE_EE.md
  packages/cli/package.json
  packages/core/LICENSE.md
  packages/core/LICENSE_EE.md
  packages/core/package.json
  packages/design-system/LICENSE.md
  packages/design-system/LICENSE_EE.md
  packages/design-system/package.json
  packages/editor-ui/.npmignore
  packages/editor-ui/LICENSE.md
  packages/editor-ui/LICENSE_EE.md
  packages/editor-ui/package.json
  packages/node-dev/LICENSE.md
  packages/node-dev/LICENSE_EE.md
  packages/node-dev/package.json
  packages/nodes-base/LICENSE.md
  packages/nodes-base/LICENSE_EE.md
  packages/nodes-base/package.json
  packages/workflow/LICENSE.md
  packages/workflow/LICENSE_EE.md
  packages/workflow/package.json
Labels: core, ui, n8n team

#9991 feat(editor): Add support for configurable configuration nodes in new canvas (no-changelog)
  packages/editor-ui/src/__tests__/data/canvas.ts
  packages/editor-ui/src/components/canvas/elements/nodes/CanvasNodeRenderer.spec.ts
  packages/editor-ui/src/components/canvas/elements/nodes/CanvasNodeRenderer.vue
  packages/editor-ui/src/components/canvas/elements/nodes/CanvasNodeToolbar.spec.ts
  packages/editor-ui/src/components/canvas/elements/nodes/CanvasNodeToolbar.vue
  packages/editor-ui/src/components/canvas/elements/nodes/render-types/CanvasNodeConfigurable.spec.ts
  packages/editor-ui/src/components/canvas/elements/nodes/render-types/CanvasNodeConfigurable.vue
  packages/editor-ui/src/components/canvas/elements/nodes/render-types/CanvasNodeConfiguration.spec.ts
  packages/editor-ui/src/components/canvas/elements/nodes/render-types/CanvasNodeConfiguration.vue
  packages/editor-ui/src/components/canvas/elements/nodes/render-types/CanvasNodeDefault.spec.ts
  packages/editor-ui/src/components/canvas/elements/nodes/render-types/CanvasNodeDefault.vue
  packages/editor-ui/src/components/canvas/elements/nodes/render-types/__snapshots__/CanvasNodeDefault.spec.ts.snap
  packages/editor-ui/src/composables/useCanvasMapping.spec.ts
  packages/editor-ui/src/composables/useCanvasMapping.ts
  packages/editor-ui/src/composables/useCanvasNode.spec.ts
  packages/editor-ui/src/composables/useCanvasNode.ts
  packages/editor-ui/src/types/canvas.ts
Labels: ui, n8n team

#10001 feat(editor): Render trigger node on canvas v2 (no-changelog)
  packages/editor-ui/src/components/canvas/elements/nodes/CanvasNode.vue
  packages/editor-ui/src/components/canvas/elements/nodes/render-types/CanvasNodeDefault.spec.ts
  packages/editor-ui/src/components/canvas/elements/nodes/render-types/CanvasNodeDefault.vue
  packages/editor-ui/src/components/canvas/elements/nodes/render-types/__snapshots__/CanvasNodeDefault.spec.ts.snap
  packages/editor-ui/src/types/canvas.ts
Labels: ui, n8n team

#10004 feat(editor): Add support for fallback nodes and new addNodes node render type in new canvas (no-changelog)
  packages/editor-ui/src/__tests__/data/canvas.ts
  packages/editor-ui/src/components/canvas/Canvas.spec.ts
  packages/editor-ui/src/components/canvas/Canvas.vue
  packages/editor-ui/src/components/canvas/WorkflowCanvas.vue
  packages/editor-ui/src/components/canvas/elements/buttons/CanvasRunWorkflowButton.spec.ts
  packages/editor-ui/src/components/canvas/elements/buttons/CanvasRunWorkflowButton.vue
  packages/editor-ui/src/components/canvas/elements/buttons/__snapshots__/CanvasRunWorkflowButton.spec.ts.snap
  packages/editor-ui/src/components/canvas/elements/nodes/CanvasNode.vue
  packages/editor-ui/src/components/canvas/elements/nodes/CanvasNodeRenderer.spec.ts
  packages/editor-ui/src/components/canvas/elements/nodes/CanvasNodeRenderer.vue
  packages/editor-ui/src/components/canvas/elements/nodes/CanvasNodeToolbar.spec.ts
  packages/editor-ui/src/components/canvas/elements/nodes/render-types/CanvasNodeAddNodes.vue
  packages/editor-ui/src/components/canvas/elements/nodes/render-types/CanvasNodeDefault.spec.ts
  packages/editor-ui/src/composables/__tests__/useCanvasOperations.spec.ts
  packages/editor-ui/src/composables/__tests__/useNodeConnections.spec.ts
  packages/editor-ui/src/composables/useCanvasMapping.spec.ts
  packages/editor-ui/src/composables/useCanvasMapping.ts
  packages/editor-ui/src/composables/useCanvasNode.spec.ts
  packages/editor-ui/src/composables/useCanvasNode.ts
  packages/editor-ui/src/composables/useCanvasOperations.ts
  packages/editor-ui/src/composables/useNodeConnections.ts
  packages/editor-ui/src/stores/nodeCreator.store.ts
  packages/editor-ui/src/types/canvas.ts
  packages/editor-ui/src/views/NodeView.v2.vue
Labels: ui, n8n team

#10008 refactor(core): Remove unused Sentry report from `WaitTracker` (no-changelog)
  packages/cli/src/WaitTracker.ts
Labels: core, n8n team

#10009 feat: Better error when calling expression function on input that is undefined or null
  packages/nodes-base/nodes/Filter/V2/FilterV2.node.ts
  packages/nodes-base/nodes/If/V2/IfV2.node.ts
  packages/nodes-base/nodes/Switch/V3/SwitchV3.node.ts
  packages/nodes-base/utils/constants.ts
  packages/workflow/src/Extensions/ExpressionExtension.ts
  packages/workflow/src/Extensions/utils.ts
  packages/workflow/test/ExpressionExtensions/ExpressionExtension.test.ts
Labels: n8n team, node/issue

#9970 feat(Google Vertex Chat Model Node): Add support for Google Vertex AI Chat models
  packages/@n8n/nodes-langchain/nodes/agents/Agent/Agent.node.ts
  packages/@n8n/nodes-langchain/nodes/agents/Agent/agents/ToolsAgent/execute.ts
  packages/@n8n/nodes-langchain/nodes/llms/LmChatGoogleGemini/LmChatGoogleGemini.node.ts
  packages/@n8n/nodes-langchain/nodes/llms/LmChatGoogleVertex/LmChatGoogleVertex.node.ts
  packages/@n8n/nodes-langchain/nodes/llms/LmChatGoogleVertex/error-handling.ts
  packages/@n8n/nodes-langchain/nodes/llms/LmChatGoogleVertex/google.svg
  packages/@n8n/nodes-langchain/nodes/llms/gemini-common/additional-options.ts
  packages/@n8n/nodes-langchain/nodes/llms/gemini-common/safety-options.ts
  packages/@n8n/nodes-langchain/package.json
  packages/@n8n/nodes-langchain/utils/helpers.ts
  packages/@n8n/nodes-langchain/utils/logWrapper.ts
  packages/nodes-base/nodes/Google/GenericFunctions.ts
  pnpm-lock.yaml
Labels: node/improvement, n8n team

#10010 feat(editor): Add clear execution button to new canvas (no-changelog)
  packages/editor-ui/src/components/canvas/elements/buttons/CanvasClearExecutionDataButton.spec.ts
  packages/editor-ui/src/components/canvas/elements/buttons/CanvasClearExecutionDataButton.vue
  packages/editor-ui/src/components/canvas/elements/buttons/__snapshots__/CanvasClearExecutionDataButton.spec.ts.snap
  packages/editor-ui/src/views/NodeView.v2.vue
Labels: ui, n8n team

#10014 fix(core): Ensure executions cannot resume if already running
  packages/cli/src/WaitingWebhooks.ts
  packages/cli/src/__tests__/waiting-webhooks.test.ts
Labels: core, n8n team

#10006 feat(editor): Add ability to add a node between two nodes in new canvas (no-changelog)
  packages/editor-ui/src/components/canvas/Canvas.vue
  packages/editor-ui/src/components/canvas/elements/edges/CanvasEdge.vue
  packages/editor-ui/src/components/canvas/elements/edges/CanvasEdgeToolbar.vue
  packages/editor-ui/src/composables/useCanvasMapping.spec.ts
  packages/editor-ui/src/composables/useCanvasOperations.ts
  packages/editor-ui/src/plugins/i18n/locales/en.json
  packages/editor-ui/src/stores/nodeCreator.store.ts
  packages/editor-ui/src/stores/ui.store.ts
  packages/editor-ui/src/utils/__tests__/canvasUtilsV2.spec.ts
  packages/editor-ui/src/utils/canvasUtilsV2.ts
  packages/editor-ui/src/utils/typeGuards.ts
  packages/editor-ui/src/views/NodeView.v2.vue
Labels: ui, n8n team

#10012 fix: Filter component - array contains comparison not correct when ignore case option set to true
  packages/workflow/src/NodeParameters/FilterParameter.ts
  packages/workflow/test/FilterParameter.test.ts
Labels: n8n team, node/issue

#9997 feat(Text Classifier Node): Add Text Classifier Node
  packages/@n8n/nodes-langchain/nodes/chains/TextClassifier/TextClassifier.node.ts
  packages/@n8n/nodes-langchain/package.json
  packages/editor-ui/src/plugins/icons/index.ts
Labels: ui, n8n team

#10007 fix(Telegram Trigger Node): Fix issue with videos not being downloaded
  packages/nodes-base/nodes/Telegram/IEvent.ts
  packages/nodes-base/nodes/Telegram/TelegramTrigger.node.ts
Labels: node/improvement, n8n team

#9869 fix(HTTP Request Node): Respect the original encoding of the incoming response
  packages/core/src/BinaryData/BinaryData.service.ts
  packages/core/src/BinaryData/ObjectStore.manager.ts
  packages/core/src/BinaryData/utils.ts
  packages/core/src/NodeExecuteFunctions.ts
  packages/core/test/BinaryData/utils.test.ts
  packages/nodes-base/nodes/HttpRequest/V3/HttpRequestV3.node.ts
  packages/nodes-base/nodes/HttpRequest/test/encoding/HttpRequest.test.ts
  packages/nodes-base/nodes/HttpRequest/test/encoding/encoding.test.json
  packages/workflow/src/Interfaces.ts
Labels: node/improvement, core, n8n team

#10011 feat(editor): Add capability to open workflow from template in new canvas (no-changelog)
  packages/editor-ui/src/components/canvas/Canvas.vue
  packages/editor-ui/src/components/canvas/WorkflowCanvas.vue
  packages/editor-ui/src/views/NodeView.v2.vue
Labels: ui, n8n team

#10017 feat(editor): Make expression autocomplete search case-insensitive
  packages/editor-ui/src/plugins/codemirror/completions/__tests__/completions.test.ts
  packages/editor-ui/src/plugins/codemirror/completions/datatype.completions.ts
  packages/editor-ui/src/plugins/codemirror/completions/utils.ts
Labels: ui, n8n team

#10016 fix(editor): Make schema view use the correct output
  cypress/e2e/5-ndv.cy.ts
  cypress/fixtures/Test_workflow_multiple_outputs.json
  packages/editor-ui/src/components/RunDataSchema.vue
Labels: ui, n8n team

#10018 fix: Update logos for Cohere nodes (no-changelog)
  packages/@n8n/nodes-langchain/nodes/embeddings/EmbeddingsCohere/EmbeddingsCohere.node.ts
  packages/@n8n/nodes-langchain/nodes/embeddings/EmbeddingsCohere/cohere.dark.svg
  packages/@n8n/nodes-langchain/nodes/embeddings/EmbeddingsCohere/cohere.svg
  packages/@n8n/nodes-langchain/nodes/llms/LMCohere/LmCohere.node.ts
  packages/@n8n/nodes-langchain/nodes/llms/LMCohere/cohere.dark.svg
  packages/@n8n/nodes-langchain/nodes/llms/LMCohere/cohere.svg
Labels: n8n team

#10013 fix(HubSpot Node): Migrate from v2 owners api
  packages/nodes-base/nodes/Hubspot/V1/HubspotV1.node.ts
  packages/nodes-base/nodes/Hubspot/V2/HubspotV2.node.ts
Labels: node/improvement, n8n team

#10023 fix: Prevent errors processed by n8n to be flagged as internal (no-changelog)
  packages/@n8n/nodes-langchain/nodes/trigger/ChatTrigger/error.ts
  packages/cli/src/services/project.service.ts
  packages/editor-ui/src/composables/useToast.ts
  packages/editor-ui/src/utils/apiUtils.ts
  packages/nodes-base/nodes/Code/ValidationError.ts
  packages/nodes-base/nodes/Code/test/workflow.do_not_obfuscate_validation_error.json
  packages/nodes-base/nodes/Webhook/error.ts
  packages/workflow/src/NodeParameters/FilterParameter.ts
Labels: n8n team

#10025 feat(editor): Tweak node creator search logic for AI sub-nodes
  packages/@n8n/nodes-langchain/nodes/vector_store/shared/createVectorStoreNode.ts
  packages/editor-ui/src/components/Node/NodeCreator/composables/useViewStacks.ts
  packages/editor-ui/src/views/NodeView.vue
Labels: ui, n8n team

#10021 fix: Number input defaults to 0 not allowing to have arbitrary precision
  packages/design-system/src/components/N8nInputNumber/InputNumber.vue
Labels: ui, n8n team

#10030 refactor(editor): Refactor VariableSelector and VariableSelectorItem to composition API (no-changelog)
  packages/editor-ui/src/components/VariableSelector.vue
  packages/editor-ui/src/components/VariableSelectorItem.vue
Labels: ui, n8n team

#10015 fix(AWS Comprehend Node): Add paired item support
  packages/nodes-base/nodes/Aws/Comprehend/AwsComprehend.node.ts
  packages/nodes-base/nodes/Aws/Comprehend/test/AwsComprehend.node.test.ts
  packages/nodes-base/nodes/Aws/Comprehend/test/AwsComprehendTestWorkflow.json
Labels: node/improvement, n8n team

#10027 feat(Asana Node): Add support for project privacy settings
  packages/nodes-base/nodes/Asana/Asana.node.ts
Labels: node/improvement, n8n team

#10028 docs: Update aliases for file nodes (no-changelog)
  packages/nodes-base/nodes/Files/ConvertToFile/ConvertToFile.node.json
  packages/nodes-base/nodes/Files/ExtractFromFile/ExtractFromFile.node.json
Labels: node/improvement, n8n team

#10032 fix(NocoDB Node): Add warning level to loadOptions errors (no-changelog)
  packages/nodes-base/nodes/NocoDB/NocoDB.node.ts
Labels: node/improvement, n8n team

#10029 refactor(editor): Move a few components to script setup (no-changelog)
  packages/editor-ui/src/components/NDVDraggablePanels.vue
  packages/editor-ui/src/components/SaveButton.vue
  packages/editor-ui/src/components/ScopesNotice.vue
  packages/editor-ui/src/components/Telemetry.vue
  packages/editor-ui/src/components/WorkflowActivator.vue
  packages/editor-ui/src/components/executions/ExecutionsTime.vue
  packages/editor-ui/src/views/SettingsPersonalView.vue
  packages/editor-ui/src/views/SettingsUsersView.vue
Labels: ui, n8n team

#10038 feat(editor): Refactor several smaller components to composition API (no-changelog)
  packages/editor-ui/src/components/Banner.vue
  packages/editor-ui/src/components/CollectionWorkflowCard.vue
  packages/editor-ui/src/components/GoBackButton.vue
  packages/editor-ui/src/components/PageContentWrapper.vue
  packages/editor-ui/src/components/ParameterInput.vue
  packages/editor-ui/src/components/ShortenName.vue
  packages/editor-ui/src/components/TagsManager/NoTagsView.vue
  packages/editor-ui/src/components/TagsManager/TagsView/TagsTableHeader.vue
  packages/editor-ui/src/components/TemplateDetailsBlock.vue
  packages/editor-ui/src/components/TextEdit.vue
  packages/editor-ui/src/components/TitledList.vue
  packages/editor-ui/src/components/transitions/SlideTransition.vue
Labels: ui, n8n team

#10035 fix(AMQP Trigger Node): Manual execution updated error reduced wait time
  packages/nodes-base/nodes/Amqp/AmqpTrigger.node.ts
Labels: n8n team, node/issue

#10026 fix(AMQP Sender Node): Node hangs forever on disconnect
  packages/nodes-base/credentials/Amqp.credentials.ts
  packages/nodes-base/nodes/Amqp/Amqp.node.ts
Labels: n8n team, node/issue

#10039 feat(Text Classifier Node): Change fallback option to a drop-down (no-changelog)
  packages/@n8n/nodes-langchain/nodes/chains/TextClassifier/TextClassifier.node.ts
Labels: n8n team

#10040 fix(GitHub Node): File Create operation prevent duplicated base64 encoding
  packages/nodes-base/nodes/Github/GenericFunctions.ts
  packages/nodes-base/nodes/Github/Github.node.ts
Labels: node/improvement, n8n team

#10034 docs: Add notice to S3 node to mention AWS S3 node (no-changelog)
  packages/nodes-base/nodes/S3/S3.node.ts
Labels: node/improvement, n8n team

#10037 fix: HTTP Request tool - allow hyphens in placeholders
  packages/@n8n/nodes-langchain/nodes/tools/ToolHttpRequest/utils.ts
Labels: n8n team, node/issue

#10043 fix(Webhook Node): Binary property option name and description update
  packages/nodes-base/nodes/Webhook/description.ts
Labels: node/improvement, n8n team

#10050 test(core): Add tests for Prometheus metrics service (no-changelog)
  packages/cli/src/Server.ts
  packages/cli/src/metrics/__tests__/prometheus-metrics.service.test.ts
  packages/cli/src/metrics/prometheus-metrics.service.ts
  packages/cli/test/integration/metrics.test.ts
  packages/cli/test/integration/shared/utils/testServer.ts
Labels: core, n8n team

#10044 fix: HTTP Request tool - do not error on missing headers
  packages/@n8n/nodes-langchain/nodes/tools/ToolHttpRequest/utils.ts
Labels: n8n team, node/issue

#10056 fix(LangChain Code Node): Add clarifying comments to the default code (no-changelog)
  packages/@n8n/nodes-langchain/nodes/code/Code.node.ts
Labels: n8n team

#10062 fix(editor): Ensure all static assets are accessible from the server
  packages/cli/src/Server.ts
  packages/editor-ui/public/static/google-auth/disabled.dark.png
  packages/editor-ui/public/static/google-auth/disabled.png
  packages/editor-ui/public/static/google-auth/focus.dark.png
  packages/editor-ui/public/static/google-auth/focus.png
  packages/editor-ui/public/static/google-auth/normal.dark.png
  packages/editor-ui/public/static/google-auth/normal.png
  packages/editor-ui/public/static/google-auth/pressed.dark.png
  packages/editor-ui/public/static/google-auth/pressed.png
  packages/editor-ui/src/components/CredentialEdit/GoogleAuthButton.vue
Labels: core, ui, n8n team, release/backport

#10063 fix(editor): Remove push event listeners when migrating away from the canvas
  packages/editor-ui/src/components/MainHeader/MainHeader.vue
Labels: release/backport

#10059 feat(editor): Add support for connection validation (no-changelog)
  packages/editor-ui/src/components/canvas/elements/handles/HandleRenderer.vue
  packages/editor-ui/src/components/canvas/elements/nodes/CanvasNode.vue
  packages/editor-ui/src/composables/__tests__/useNodeConnections.spec.ts
  packages/editor-ui/src/composables/useNodeConnections.ts
Labels: ui, n8n team

#10075 fix(core): Redact `csrfSecret` when returning oauth credentials to the frontend
  packages/cli/src/credentials/__tests__/credentials.service.test.ts
  packages/cli/src/credentials/credentials.service.ts
Labels: core, n8n team, security

#10077 refactor(core): Suppress `MaxListenersExceededWarning` in the logs
  packages/cli/src/Queue.ts
  packages/cli/src/commands/worker.ts
Labels: core, n8n team

#10073 refactor(core): Use use up-to-date timezone data
  packages/cli/package.json
  packages/cli/scripts/build.mjs
  packages/cli/src/Server.ts
  pnpm-lock.yaml
Labels: core, n8n team

#9992 fix(core): Stopping an execution should reject any response promises
  packages/cli/src/ActiveExecutions.ts
  packages/cli/src/WaitTracker.ts
  packages/cli/src/WorkflowRunner.ts
  packages/cli/src/databases/repositories/execution.repository.ts
  packages/cli/src/executions/execution.service.ts
  packages/cli/test/integration/execution.service.integration.test.ts
  packages/workflow/src/Interfaces.ts
  packages/workflow/src/errors/execution-cancelled.error.ts
  packages/workflow/src/errors/index.ts
Labels: core, n8n team

#10033 refactor(core): Centralize CronJob management
  packages/core/package.json
  packages/core/src/ActiveWorkflows.ts
  packages/core/src/Interfaces.ts
  packages/core/src/NodeExecuteFunctions.ts
  packages/core/src/ScheduledTaskManager.ts
  packages/core/test/ScheduledTaskManager.test.ts
  packages/nodes-base/nodes/Cron/Cron.node.ts
  packages/nodes-base/nodes/Schedule/GenericFunctions.ts
  packages/nodes-base/nodes/Schedule/ScheduleTrigger.node.ts
  packages/nodes-base/nodes/Schedule/SchedulerInterface.ts
  packages/nodes-base/nodes/Schedule/test/GenericFunctions.test.ts
  packages/nodes-base/nodes/Schedule/tests/ScheduleTrigger.node.test.ts
  packages/nodes-base/package.json
  packages/workflow/src/Cron.ts
  packages/workflow/src/Interfaces.ts
  packages/workflow/src/Workflow.ts
  packages/workflow/test/Cron.test.ts
  pnpm-lock.yaml
Labels: node/improvement, core, n8n team

#10078 feat: Add AI assistant SDK
  packages/cli/package.json
  packages/cli/src/AbstractServer.ts
  packages/cli/src/Server.ts
  packages/cli/src/config/schema.ts
  packages/cli/src/services/frontend.service.ts
  packages/editor-ui/src/stores/settings.store.ts
  packages/workflow/src/Interfaces.ts
  pnpm-lock.yaml
Labels: core, ui, n8n team

#10076 fix(OpenAI Chat Model Node): Respect baseURL override for /models
  packages/@n8n/nodes-langchain/nodes/llms/LMChatOpenAi/LmChatOpenAi.node.ts
  packages/@n8n/nodes-langchain/nodes/llms/LMOpenAi/LmOpenAi.node.ts
  packages/workflow/src/Interfaces.ts
  packages/workflow/src/NodeHelpers.ts
  packages/workflow/test/NodeHelpers.conditions.test.ts
Labels: core, n8n team

#10071 feat(Postgres Chat Memory Node): Implement Postgres Chat Memory node
  packages/@n8n/nodes-langchain/nodes/memory/MemoryPostgresChat/MemoryPostgresChat.node.ts
  packages/@n8n/nodes-langchain/nodes/memory/MemoryPostgresChat/postgres.svg
  packages/@n8n/nodes-langchain/package.json
  packages/@n8n/nodes-langchain/utils/helpers.ts
  packages/@n8n/nodes-langchain/utils/logWrapper.ts
  pnpm-lock.yaml
Labels: n8n team

#10052 fix(editor): Handle disabled nodes in schema view
  packages/editor-ui/src/components/RunData.vue
  packages/editor-ui/src/components/RunDataSchema.vue
  packages/editor-ui/src/components/__tests__/RunDataSchema.test.ts
  packages/editor-ui/src/components/__tests__/__snapshots__/RunDataSchema.test.ts.snap
  packages/editor-ui/src/plugins/i18n/locales/en.json
Labels: ui, n8n team

#10081 refactor(core): Decouple projects telemetry (no-changelog)
  packages/cli/src/InternalHooks.ts
  packages/cli/src/commands/BaseCommand.ts
  packages/cli/src/controllers/project.controller.ts
  packages/cli/src/eventbus/event.types.ts
  packages/cli/src/telemetry/telemetry-event-relay.service.ts
  packages/cli/test/integration/shared/utils/testCommand.ts
Labels: core, n8n team

#10082 refactor(core): Port Public API config (no-changelog)
  packages/@n8n/config/src/configs/public-api.ts
  packages/@n8n/config/src/index.ts
  packages/cli/src/PublicApi/index.ts
  packages/cli/src/Server.ts
  packages/cli/src/config/schema.ts
  packages/cli/src/services/frontend.service.ts
  packages/cli/test/integration/me.api.test.ts
  packages/cli/test/integration/shared/constants.ts
Labels: core, n8n team

#10048 fix(MQTT Node): Node hangs forever on failed connection
  packages/nodes-base/nodes/MQTT/GenericFunctions.ts
Labels: n8n team, node/issue

#10084 fix(HelpScout Node): Fix issue with thread types not working correctly
  packages/nodes-base/nodes/HelpScout/HelpScout.node.ts
Labels: node/improvement, n8n team

#10087 refactor(core): Port version notifications config (no-changelog)
  packages/@n8n/config/src/configs/version-notifications.ts
  packages/@n8n/config/src/index.ts
  packages/cli/src/InternalHooks.ts
  packages/cli/src/config/schema.ts
  packages/cli/src/security-audit/risk-reporters/InstanceRiskReporter.ts
  packages/cli/src/services/frontend.service.ts
  packages/cli/test/integration/security-audit/utils.ts
  packages/cli/test/unit/InternalHooks.test.ts
Labels: core, n8n team

#10068 refactor(core): Clean up Prometheus service (no-changelog)
  packages/cli/src/Server.ts
  packages/cli/src/eventbus/MessageEventBus/MessageEventBus.ts
  packages/cli/src/metrics/__tests__/prometheus-metrics.service.test.ts
  packages/cli/src/metrics/prometheus-metrics.service.ts
  packages/cli/test/integration/metrics.test.ts
  packages/cli/test/integration/prometheus-metrics.test.ts
  packages/cli/test/integration/shared/utils/testServer.ts
Labels: core, n8n team

#10086 fix(editor): Close node creator when clicking on new canvas (no-changelog)
  packages/editor-ui/src/views/NodeView.v2.vue
Labels: ui, n8n team

#10094 refactor(core): Port external secrets config (no-changelog)
  packages/@n8n/config/src/configs/external-secrets.ts
  packages/@n8n/config/src/index.ts
  packages/cli/src/ExternalSecrets/externalSecretsHelper.ee.ts
  packages/cli/src/config/schema.ts
Labels: core, n8n team

#10051 feat(editor): Add ability to import workflows in new canvas (no-changelog)
  packages/editor-ui/src/Interface.ts
  packages/editor-ui/src/components/canvas/Canvas.vue
  packages/editor-ui/src/composables/__tests__/useCanvasOperations.spec.ts
  packages/editor-ui/src/composables/useCanvasOperations.ts
  packages/editor-ui/src/composables/useNodeHelpers.ts
  packages/editor-ui/src/composables/useWorkflowHelpers.ts
  packages/editor-ui/src/stores/nodeCreator.store.ts
  packages/editor-ui/src/stores/ui.store.ts
  packages/editor-ui/src/stores/workflows.store.ts
  packages/editor-ui/src/types/canvas.ts
  packages/editor-ui/src/utils/canvasUtilsV2.ts
  packages/editor-ui/src/views/NodeView.v2.vue
Labels: ui, n8n team

#10088 feat(editor): Add context menu to canvas v2 (no-changelog)
  packages/editor-ui/src/components/ContextMenu/ContextMenu.vue
  packages/editor-ui/src/components/Node.vue
  packages/editor-ui/src/components/Sticky.vue
  packages/editor-ui/src/components/canvas/Canvas.spec.ts
  packages/editor-ui/src/components/canvas/Canvas.vue
  packages/editor-ui/src/components/canvas/elements/nodes/CanvasNode.vue
  packages/editor-ui/src/components/canvas/elements/nodes/CanvasNodeToolbar.spec.ts
  packages/editor-ui/src/components/canvas/elements/nodes/CanvasNodeToolbar.vue
  packages/editor-ui/src/components/canvas/elements/nodes/render-types/CanvasNodeDefault.vue
  packages/editor-ui/src/composables/__tests__/useContextMenu.test.ts
  packages/editor-ui/src/composables/__tests__/useKeybindings.test.ts
  packages/editor-ui/src/composables/useCanvasOperations.ts
  packages/editor-ui/src/composables/useContextMenu.ts
  packages/editor-ui/src/composables/useKeybindings.ts
  packages/editor-ui/src/views/NodeView.v2.vue
  packages/editor-ui/src/views/NodeView.vue
Labels: ui, n8n team

#9683 fix(editor): UX Improvements to RBAC feature set
  cypress/composables/projects.ts
  packages/design-system/src/components/N8nAvatar/Avatar.vue
  packages/design-system/src/components/N8nMenuItem/MenuItem.vue
  packages/design-system/src/utils/labelUtil.spec.ts
  packages/design-system/src/utils/labelUtil.ts
  packages/editor-ui/src/components/CredentialCard.vue
  packages/editor-ui/src/components/PersonalizationModal.vue
  packages/editor-ui/src/components/Projects/ProjectCardBadge.test.ts
  packages/editor-ui/src/components/Projects/ProjectCardBadge.vue
  packages/editor-ui/src/components/Projects/ProjectMoveResourceConfirmModal.test.ts
  packages/editor-ui/src/components/Projects/ProjectMoveResourceConfirmModal.vue
  packages/editor-ui/src/components/Projects/ProjectMoveResourceModal.test.ts
  packages/editor-ui/src/components/Projects/ProjectMoveResourceModal.vue
  packages/editor-ui/src/components/Projects/ProjectMoveSuccessToastMessage.vue
  packages/editor-ui/src/components/Projects/ProjectNavigation.vue
  packages/editor-ui/src/components/WorkflowCard.vue
  packages/editor-ui/src/components/__tests__/PersonalizationModal.spec.ts
  packages/editor-ui/src/components/forms/ResourceFiltersDropdown.vue
  packages/editor-ui/src/components/layouts/ResourcesListLayout.test.ts
  packages/editor-ui/src/components/layouts/ResourcesListLayout.vue
  packages/editor-ui/src/plugins/i18n/locales/en.json
  packages/editor-ui/src/routes/projects.routes.ts
  packages/editor-ui/src/utils/projects.utils.ts
  packages/editor-ui/src/views/CredentialsView.vue
  packages/editor-ui/src/views/ProjectSettings.test.ts
  packages/editor-ui/src/views/ProjectSettings.vue
  packages/editor-ui/src/views/SetupView.vue
  packages/editor-ui/src/views/SignupView.vue
  packages/editor-ui/src/views/VariablesView.spec.ts
  packages/editor-ui/src/views/VariablesView.vue
  packages/editor-ui/src/views/WorkflowsView.test.ts
  packages/editor-ui/src/views/WorkflowsView.vue
Labels: ui, n8n team

#10057 fix(editor): Remove "move" action from workflow and credential on community plan
  packages/cli/src/controllers/e2e.controller.ts
  packages/editor-ui/src/components/CredentialCard.test.ts
  packages/editor-ui/src/components/CredentialCard.vue
  packages/editor-ui/src/components/WorkflowCard.test.ts
  packages/editor-ui/src/components/WorkflowCard.vue
  packages/editor-ui/src/composables/useDebugInfo.ts
  packages/editor-ui/src/stores/settings.store.ts
Labels: ui, n8n team

#10054 feat: Introduce Azure Key Vault as external secrets provider
  packages/cli/package.json
  packages/cli/src/ExternalSecrets/ExternalSecretsProviders.ee.ts
  packages/cli/src/ExternalSecrets/constants.ts
  packages/cli/src/ExternalSecrets/providers/__tests__/azure-key-vault.test.ts
  packages/cli/src/ExternalSecrets/providers/aws-secrets/aws-secrets-manager.ts
  packages/cli/src/ExternalSecrets/providers/azure-key-vault/azure-key-vault.ts
  packages/cli/src/ExternalSecrets/providers/azure-key-vault/types.ts
  packages/cli/src/ExternalSecrets/providers/infisical.ts
  packages/cli/src/ExternalSecrets/providers/vault.ts
  packages/editor-ui/src/assets/images/azure-key-vault.svg
  packages/editor-ui/src/components/ExternalSecretsProviderImage.ee.vue
  pnpm-lock.yaml
Labels: core, n8n team

#10100 refactor(core): Delete dead code in ExternalHooks (no-changelog)
  packages/cli/src/ExternalHooks.ts
Labels: core, n8n team

#10099 refactor(core): More decouplings from internal hooks (no-changelog)
  packages/cli/src/ExternalSecrets/ExternalSecretsManager.ee.ts
  packages/cli/src/InternalHooks.ts
  packages/cli/src/commands/audit.ts
  packages/cli/src/environments/variables/variables.service.ee.ts
  packages/cli/src/eventbus/event-relay.service.ts
  packages/cli/src/eventbus/event.types.ts
  packages/cli/src/license/license.service.ts
  packages/cli/src/telemetry/telemetry-event-relay.service.ts
  packages/cli/test/integration/ExternalSecrets/externalSecrets.api.test.ts
  packages/cli/test/unit/ExternalSecrets/ExternalSecretsManager.test.ts
  packages/cli/test/unit/license/license.service.test.ts
Labels: core, n8n team

#10103 refactor(core): Port templates config (no-changelog)
  packages/@n8n/config/src/configs/templates.ts
  packages/@n8n/config/src/index.ts
  packages/cli/src/security-audit/risk-reporters/InstanceRiskReporter.ts
  packages/cli/src/services/frontend.service.ts
Labels: core, n8n team

#10105 refactor(core): Remove unused security audit telemetry event (no-changelog)
  packages/cli/src/commands/audit.ts
  packages/cli/src/eventbus/event-relay.service.ts
  packages/cli/src/eventbus/event.types.ts
  packages/cli/src/telemetry/telemetry-event-relay.service.ts
Labels: core, n8n team

#10093 fix(editor): Allow `$secrets` to resolve on credentials
  packages/editor-ui/src/components/ParameterInputHint.vue
  packages/editor-ui/src/components/ParameterInputWrapper.test.ts
  packages/editor-ui/src/components/ParameterInputWrapper.vue
  packages/editor-ui/src/composables/useExpressionEditor.ts
Labels: ui, n8n team

#9397 fix(RabbitMQ Node): Fix issue with arguments not being sent
  packages/nodes-base/nodes/RabbitMQ/RabbitMQ.node.ts
Labels: node/improvement, n8n team

#10107 refactor(core): Rename `EventsService` to `WorkflowStatisticsService` (no-changelog)
  packages/cli/src/InternalHooks.ts
  packages/cli/src/WebhookHelpers.ts
  packages/cli/src/WorkflowExecuteAdditionalData.ts
  packages/cli/src/services/workflow-statistics.service.ts
  packages/cli/test/unit/services/workflow-statistics.service.test.ts
Labels: core, n8n team

#10110 refactor(core): Rename `EventRelay` to `EventService` (no-changelog)
  packages/cli/src/ExternalSecrets/ExternalSecretsManager.ee.ts
  packages/cli/src/PublicApi/v1/handlers/credentials/credentials.service.ts
  packages/cli/src/PublicApi/v1/handlers/sourceControl/sourceControl.handler.ts
  packages/cli/src/PublicApi/v1/handlers/workflows/workflows.handler.ts
  packages/cli/src/UserManagement/email/UserManagementMailer.ts
  packages/cli/src/WorkflowExecuteAdditionalData.ts
  packages/cli/src/WorkflowRunner.ts
  packages/cli/src/auth/methods/ldap.ts
  packages/cli/src/commands/start.ts
  packages/cli/src/concurrency/__tests__/concurrency-control.service.test.ts
  packages/cli/src/concurrency/concurrency-control.service.ts
  packages/cli/src/controllers/auth.controller.ts
  packages/cli/src/controllers/communityPackages.controller.ts
  packages/cli/src/controllers/invitation.controller.ts
  packages/cli/src/controllers/me.controller.ts
  packages/cli/src/controllers/passwordReset.controller.ts
  packages/cli/src/controllers/project.controller.ts
  packages/cli/src/controllers/users.controller.ts
  packages/cli/src/credentials/credentials.controller.ts
  packages/cli/src/environments/sourceControl/sourceControl.controller.ee.ts
  packages/cli/src/environments/sourceControl/sourceControl.service.ee.ts
  packages/cli/src/environments/variables/variables.service.ee.ts
  packages/cli/src/eventbus/__tests__/audit-event-relay.service.test.ts
  packages/cli/src/eventbus/audit-event-relay.service.ts
  packages/cli/src/eventbus/event.service.ts
  packages/cli/src/eventbus/event.types.ts
  packages/cli/src/executions/__tests__/execution-recovery.service.test.ts
  packages/cli/src/executions/execution-recovery.service.ts
  packages/cli/src/license/license.service.ts
  packages/cli/src/services/user.service.ts
  packages/cli/src/sso/saml/routes/saml.controller.ee.ts
  packages/cli/src/telemetry/telemetry-event-relay.service.ts
  packages/cli/src/workflows/workflow.service.ts
  packages/cli/src/workflows/workflows.controller.ts
  packages/cli/test/integration/ExternalSecrets/externalSecrets.api.test.ts
  packages/cli/test/unit/license/license.service.test.ts
Labels: core, n8n team

#10111 refactor(core): Port event bus config (no-changelog)
  packages/@n8n/config/src/configs/event-bus.ts
  packages/@n8n/config/src/index.ts
  packages/cli/src/config/schema.ts
  packages/cli/src/eventbus/MessageEventBus/MessageEventBus.ts
  packages/cli/src/eventbus/MessageEventBusWriter/MessageEventBusLogWriter.ts
  packages/cli/test/integration/eventbus.ee.test.ts
Labels: core, n8n team

#10115 refactor: Silence `@n8n/nodes-langchain` lint warnings (no-changelog)
  packages/@n8n/nodes-langchain/package.json
Labels: n8n team

#10106 feat(editor): Cleanup unused keymap functions and add additional onSave events in new canvas (no-changelog)
  packages/editor-ui/src/components/MainHeader/WorkflowDetails.vue
  packages/editor-ui/src/components/canvas/elements/handles/render-types/parts/CanvasHandlePlus.vue
  packages/editor-ui/src/components/canvas/elements/nodes/render-types/CanvasNodeStickyNote.vue
  packages/editor-ui/src/views/NodeView.v2.vue
Labels: ui, n8n team

#10114 feat(editor): Open NDV when a node is added to canvas v2 (no-changelog)
  packages/editor-ui/src/composables/__tests__/useCanvasOperations.spec.ts
  packages/editor-ui/src/composables/useCanvasOperations.ts
Labels: ui, n8n team

#10022 refactor(editor): Migrate settings.store to composition API (no-changelog)
  packages/editor-ui/src/__tests__/defaults.ts
  packages/editor-ui/src/components/AssignmentCollection/__tests__/Assignment.test.ts
  packages/editor-ui/src/components/AssignmentCollection/__tests__/AssignmentCollection.test.ts
  packages/editor-ui/src/components/CredentialEdit/CredentialEdit.vue
  packages/editor-ui/src/components/CredentialEdit/CredentialSharing.ee.vue
  packages/editor-ui/src/components/EnterpriseEdition.ee.vue
  packages/editor-ui/src/components/InviteUsersModal.vue
  packages/editor-ui/src/components/MainHeader/WorkflowDetails.vue
  packages/editor-ui/src/components/NodeDetailsView.vue
  packages/editor-ui/src/components/VariablesRow.vue
  packages/editor-ui/src/components/WorkflowSettings.vue
  packages/editor-ui/src/components/WorkflowShareModal.ee.vue
  packages/editor-ui/src/components/executions/ExecutionsFilter.vue
  packages/editor-ui/src/composables/useDebugInfo.ts
  packages/editor-ui/src/composables/useExecutionDebugging.ts
  packages/editor-ui/src/stores/__tests__/posthog.test.ts
  packages/editor-ui/src/stores/__tests__/ui.test.ts
  packages/editor-ui/src/stores/auditLogs.store.ts
  packages/editor-ui/src/stores/credentials.store.ts
  packages/editor-ui/src/stores/externalSecrets.ee.store.ts
  packages/editor-ui/src/stores/settings.store.ts
  packages/editor-ui/src/stores/sourceControl.store.ts
  packages/editor-ui/src/stores/sso.store.ts
  packages/editor-ui/src/stores/templates.store.ts
  packages/editor-ui/src/stores/workflows.ee.store.ts
  packages/editor-ui/src/utils/rbac/checks/isEnterpriseFeatureEnabled.test.ts
  packages/editor-ui/src/utils/rbac/checks/isEnterpriseFeatureEnabled.ts
  packages/editor-ui/src/utils/rbac/middleware/enterprise.test.ts
  packages/editor-ui/src/views/CredentialsView.vue
  packages/editor-ui/src/views/NodeView.v2.vue
  packages/editor-ui/src/views/NodeView.vue
  packages/editor-ui/src/views/SettingsLogStreamingView.vue
  packages/editor-ui/src/views/SettingsUsersView.vue
  packages/editor-ui/src/views/VariablesView.spec.ts
  packages/editor-ui/src/views/VariablesView.vue
  packages/editor-ui/src/views/WorkflowsView.vue
  packages/editor-ui/src/views/__tests__/SettingsUsersView.test.ts
  packages/workflow/src/Interfaces.ts
Labels: core, ui, n8n team

#10117 refactor: Mark defaults.color as deprecated in node descriptions
  packages/workflow/src/Interfaces.ts
Labels: core, n8n team

#10112 feat(editor): Add duplicate and copy/paste to canvas v2 (no-changelog)
  packages/editor-ui/src/components/MainHeader/WorkflowDetails.vue
  packages/editor-ui/src/components/canvas/Canvas.vue
  packages/editor-ui/src/composables/__tests__/__snapshots__/useCanvasOperations.spec.ts.snap
  packages/editor-ui/src/composables/__tests__/useCanvasOperations.spec.ts
  packages/editor-ui/src/composables/useCanvasOperations.ts
  packages/editor-ui/src/constants.ts
  packages/editor-ui/src/stores/workflows.store.ts
  packages/editor-ui/src/views/NodeView.v2.vue
  packages/editor-ui/src/views/NodeView.vue
Labels: ui, n8n team

#10118 refactor(Text Classifier Node): Mark the text classifier node as black
  packages/@n8n/nodes-langchain/nodes/chains/TextClassifier/TextClassifier.node.ts
Labels: n8n team

#10116 ci: Pin node.js 22 to 22.4 (no-changelog)
  .github/workflows/ci-master.yml
Labels: n8n team
