Repository n8n-io/n8n, pull requests merged in 2024-02, with the labels that each got.

#8503 fix(core): Fix new graceful shutdown env being always overridden by deprecated env
  packages/cli/src/commands/BaseCommand.ts
  packages/cli/src/commands/worker.ts
Labels: core, n8n team

#8497 fix(HTTP Request Node): Support form data when using pagination
  packages/core/src/NodeExecuteFunctions.ts
  packages/nodes-base/nodes/HttpRequest/test/node/HttpRequest.test.ts
  packages/nodes-base/nodes/HttpRequest/test/node/workflow.pagination.json
Labels: node/improvement, core, n8n team

#8454 fix(HTTP Request Node): Require parameter with filled name and value to avoid infinite loop
  packages/nodes-base/nodes/HttpRequest/V3/HttpRequestV3.node.ts
Labels: node/improvement, n8n team, node/issue

#8461 fix(Microsoft Excel 365 Node): Upsert append new rows at the end of used range, option to append at the end of selected range
  packages/nodes-base/nodes/Microsoft/Excel/MicrosoftExcel.node.ts
  packages/nodes-base/nodes/Microsoft/Excel/v2/actions/versionDescription.ts
  packages/nodes-base/nodes/Microsoft/Excel/v2/actions/worksheet/upsert.operation.ts
Labels: node/improvement, n8n team, node/issue

#8471 fix(Slack Node): Attachments fix
  packages/nodes-base/nodes/Slack/V2/GenericFunctions.ts
Labels: n8n team, node/issue

#8522 feat: Azure Open AI chat model & embeddings
  cypress/composables/workflow.ts
  cypress/e2e/30-langchain.cy.ts
  packages/@n8n/nodes-langchain/credentials/AzureOpenAiApi.credentials.ts
  packages/@n8n/nodes-langchain/nodes/embeddings/EmbeddingsAzureOpenAi/EmbeddingsAzureOpenAi.node.ts
  packages/@n8n/nodes-langchain/nodes/embeddings/EmbeddingsAzureOpenAi/azure.svg
  packages/@n8n/nodes-langchain/nodes/llms/LmChatAzureOpenAi/LmChatAzureOpenAi.node.ts
  packages/@n8n/nodes-langchain/nodes/llms/LmChatAzureOpenAi/azure.svg
  packages/@n8n/nodes-langchain/package.json
Labels: n8n team

#8524 fix(core): Fix test runs of triggers that rely on static data
  packages/cli/src/TestWebhooks.ts
  packages/workflow/src/Workflow.ts
Labels: core, n8n team

#8504 ci: Replace `pnpm/action-setup` action with corepack (no-changelog)
  .github/workflows/check-documentation-urls.yml
  .github/workflows/check-pr-title.yml
  .github/workflows/ci-master.yml
  .github/workflows/ci-postgres-mysql.yml
  .github/workflows/ci-pull-requests.yml
  .github/workflows/release-create-pr.yml
  .github/workflows/release-publish.yml
  .github/workflows/test-workflows.yml
  .github/workflows/units-tests-reusable.yml
Labels: n8n team

#8530 fix(MongoDB Node): Fix "Maximum call stack size exceeded" error on too many rows
  packages/nodes-base/nodes/MongoDb/MongoDb.node.ts
Labels: node/improvement, n8n team

#8525 fix: Allow Date/Luxon objects and additional formats in DateTime validation
  packages/workflow/src/TypeValidation.ts
  packages/workflow/test/FilterParameter.test.ts
  packages/workflow/test/TypeValidation.test.ts
Labels: core, n8n team

#8478 fix(editor): Prune values that are not in the schema in the ResourceMapper component
  packages/editor-ui/src/components/ResourceMapper/ResourceMapper.vue
Labels: ui, n8n team

#8528 fix(core): Fix PermissionChecker.check, and add additional unit tests
  packages/cli/src/UserManagement/PermissionChecker.ts
  packages/cli/src/credentials/credentials.service.ts
  packages/cli/src/databases/repositories/sharedCredentials.repository.ts
  packages/cli/src/databases/repositories/sharedWorkflow.repository.ts
  packages/cli/test/integration/PermissionChecker.test.ts
  packages/cli/test/unit/PermissionChecker.test.ts
Labels: core, n8n team

#8521 fix(core): Fix DropRoleMapping migration
  packages/cli/src/databases/migrations/common/1705429061930-DropRoleMapping.ts
Labels: core, n8n team

#8509 fix(core): Ensure AxiosError status always gets copied over to NodeApiError
  packages/workflow/package.json
  packages/workflow/src/errors/node-api.error.ts
  pnpm-lock.yaml
Labels: core, n8n team

#8533 fix(Embeddings OpenAI Node): Fix dynamic models fetching
  packages/@n8n/nodes-langchain/nodes/embeddings/EmbeddingsOpenAI/EmbeddingsOpenAi.node.ts
Labels: n8n team

#8505 fix(core): Fix workflow tagging failure due to unique constraint check
  packages/cli/src/databases/repositories/workflowTagMapping.repository.ts
  packages/cli/src/workflows/workflow.service.ts
  packages/cli/test/integration/workflow-tag-mapping.repository.integration.test.ts
Labels: core, n8n team

#8535 fix(core): Upgrade nodemailer to address an exploit
  packages/cli/package.json
  packages/nodes-base/package.json
  pnpm-lock.yaml
Labels: core, n8n team

#8424 refactor(core): Centralize executions retrieval (no-changelog)
  packages/cli/src/ActiveExecutions.ts
  packages/cli/src/Interfaces.ts
  packages/cli/src/WaitTracker.ts
  packages/cli/src/databases/repositories/execution.repository.ts
  packages/cli/src/errors/postgres-live-rows-retrieval.error.ts
  packages/cli/src/executions/active-execution.service.ts
  packages/cli/src/executions/execution.service.ts
  packages/cli/src/executions/execution.types.ts
  packages/cli/src/executions/executionHelpers.ts
  packages/cli/src/executions/executions.controller.ts
  packages/cli/src/executions/parse-range-query.middleware.ts
  packages/cli/test/integration/execution.service.integration.test.ts
  packages/cli/test/unit/active-execution.service.test.ts
  packages/cli/test/unit/controllers/executions.controller.test.ts
  packages/cli/test/unit/middleware/executions/parse-range-query.middleware.test.ts
  packages/editor-ui/src/api/workflows.ts
  packages/editor-ui/src/composables/__tests__/useExecutionHelpers.test.ts
  packages/editor-ui/src/stores/executions.store.ts
  packages/editor-ui/src/stores/workflows.store.ts
Labels: core, n8n team

#8430 feat(RabbitMQ Trigger Node): Add options to configure assert of exchanges and queues
  packages/nodes-base/nodes/RabbitMQ/DefaultOptions.ts
  packages/nodes-base/nodes/RabbitMQ/GenericFunctions.ts
Labels: node/improvement, community

#8539 feat(Email Trigger (IMAP) Node): Upgrade mailparser
  packages/nodes-base/package.json
  pnpm-lock.yaml
Labels: n8n team

#8446 refactor(core): Streamline flows in multi-main mode (no-changelog)
  packages/cli/src/ActiveWorkflowRunner.ts
  packages/cli/src/commands/start.ts
  packages/cli/src/services/orchestration.service.ts
  packages/cli/src/services/orchestration/main/MultiMainSetup.ee.ts
  packages/cli/src/services/orchestration/main/handleCommandMessageMain.ts
  packages/cli/src/services/redis/RedisServiceCommands.ts
  packages/cli/src/workflows/workflow.service.ts
  packages/cli/test/integration/ActiveWorkflowRunner.test.ts
  packages/cli/test/integration/shared/utils/index.ts
  packages/cli/test/integration/workflows/workflow.service.test.ts
  packages/workflow/src/ErrorReporterProxy.ts
  packages/workflow/src/Interfaces.ts
Labels: core, n8n team

#8547 fix: Remove ts-node from overrides and typeorm script (no-changelog)
  package.json
  packages/cli/package.json
  pnpm-lock.yaml
Labels: core, n8n team

#8551 docs: Add encryption key check to breaking changes list
  packages/cli/BREAKING-CHANGES.md
Labels: core, n8n team

#8549 refactor(core): Lock `webhook` process out of multi-main setup (no-changelog)
  packages/cli/src/commands/webhook.ts
  packages/cli/src/services/orchestration/webhook/handleCommandMessageWebhook.ts
Labels: core, n8n team

#8545 refactor(core): Continue breaking dependency cycles (no-changelog)
  packages/cli/src/CredentialsHelper.ts
  packages/cli/src/InternalHooks.ts
  packages/cli/src/Server.ts
  packages/cli/src/WorkflowRunner.ts
  packages/cli/src/commands/start.ts
  packages/cli/src/commands/worker.ts
  packages/cli/src/controllers/e2e.controller.ts
  packages/cli/src/credentials/credentials.service.ts
  packages/cli/src/eventbus/index.ts
  packages/cli/src/services/credentials-tester.service.ts
  packages/cli/src/services/metrics.service.ts
  packages/cli/test/integration/eventbus.ee.test.ts
  packages/cli/test/integration/eventbus.test.ts
  packages/cli/test/integration/workflows/workflow.service.test.ts
  packages/cli/test/unit/services/orchestration.service.test.ts
Labels: core, n8n team

#8557 fix(core): Use trx manager instead of repository for tags overwrite
  packages/cli/src/databases/repositories/workflowTagMapping.repository.ts
Labels: core, n8n team

#8558 build: Fix outdated import to fix build (no-changelog)
  packages/cli/src/services/orchestration/webhook/handleCommandMessageWebhook.ts
  packages/cli/test/unit/InternalHooks.test.ts
Labels: core, n8n team

#8487 refactor(core): Couple of refactors on WorkflowRunner and ActiveExecutions (no-changelog)
  packages/cli/src/ActiveExecutions.ts
  packages/cli/src/WorkflowExecuteAdditionalData.ts
  packages/cli/src/WorkflowRunner.ts
  packages/cli/src/commands/executeBatch.ts
  packages/cli/src/commands/start.ts
  packages/cli/src/commands/webhook.ts
Labels: core, n8n team

#8553 ci: Update validate-n8n-pull-request-title action (no-changelog)
  .github/workflows/check-pr-title.yml
Labels: n8n team

#8562 fix(core): Use hostname from URL instead of Host header for SNI
  packages/core/src/NodeExecuteFunctions.ts
  packages/core/test/NodeExecuteFunctions.test.ts
Labels: core, n8n team

#8559 refactor(core): Additions to executions retrieval
  packages/cli/src/databases/repositories/execution.repository.ts
  packages/cli/src/executions/execution.service.ts
  packages/cli/src/executions/execution.types.ts
  packages/cli/src/executions/executions.controller.ts
  packages/cli/test/integration/execution.service.integration.test.ts
  packages/cli/test/unit/controllers/executions.controller.test.ts
Labels: core, n8n team

#8566 fix(Microsoft Outlook Node): Download executes more than once per incoming item
  packages/nodes-base/nodes/Microsoft/Outlook/v2/actions/messageAttachment/download.operation.ts
Labels: n8n team, node/issue

#8570 ci(core): Avoid slow bcrypt calls in tests (no-changelog)
  packages/cli/src/services/password.utility.ts
  packages/cli/test/integration/ldap/ldap.api.test.ts
  packages/cli/test/integration/shared/db/users.ts
Labels: core, n8n team

#8568 fix(core): Upgrade rudderstack sdk to address npm postInstall issues
  packages/cli/package.json
  pnpm-lock.yaml
Labels: core, n8n team

#8585 build: Add GitHub issue form for reporting bugs
  .github/ISSUE_TEMPLATE/01-bug.yml
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/config.yml
  .github/workflows/check-issue-template.yml
Labels: n8n team

#8580 fix(Google Sheets Trigger Node): First non-header row is ignored when using on row added event
  packages/nodes-base/nodes/Google/Sheet/GoogleSheetsTrigger.node.ts
Labels: n8n team, node/issue

#8572 fix(RSS Feed Trigger Node): Save last item's date instead of last execution date
  packages/nodes-base/nodes/RssFeedRead/RssFeedReadTrigger.node.ts
Labels: node/improvement, community

#8564 feat(core): Link all shared credentials to the personal project of the user it's shared with
  packages/cli/src/PublicApi/v1/handlers/credentials/credentials.service.ts
  packages/cli/src/commands/import/credentials.ts
  packages/cli/src/controllers/e2e.controller.ts
  packages/cli/src/credentials/credentials.service.ee.ts
  packages/cli/src/credentials/credentials.service.ts
  packages/cli/src/databases/repositories/project.repository.ts
  packages/cli/src/services/user.service.ts
  packages/cli/test/integration/shared/db/credentials.ts
  packages/cli/test/integration/shared/db/users.ts
  packages/cli/test/unit/services/user.service.test.ts
Labels: core, n8n team

#8587 refactor: Add lint rule for unsafe property access with lodash get/set (no-changelog)
  packages/@n8n/nodes-langchain/nodes/output_parser/OutputParserStructured/OutputParserStructured.node.ts
  packages/@n8n_io/eslint-config/base.js
  packages/@n8n_io/eslint-config/package.json
  packages/core/src/NodeExecuteFunctions.ts
  packages/core/src/WorkflowExecute.ts
  packages/editor-ui/src/components/CollectionParameter.vue
  packages/editor-ui/src/components/FixedCollectionParameter.vue
  packages/editor-ui/src/components/WorkflowLMChat.vue
  packages/nodes-base/nodes/Aws/ELB/GenericFunctions.ts
  packages/nodes-base/nodes/Aws/Rekognition/GenericFunctions.ts
  packages/nodes-base/nodes/Aws/S3/V1/GenericFunctions.ts
  packages/nodes-base/nodes/Aws/S3/V2/GenericFunctions.ts
  packages/nodes-base/nodes/Aws/SES/GenericFunctions.ts
  packages/nodes-base/nodes/Aws/Transcribe/GenericFunctions.ts
  packages/nodes-base/nodes/CompareDatasets/GenericFunctions.ts
  packages/nodes-base/nodes/Crypto/Crypto.node.ts
  packages/nodes-base/nodes/CustomerIo/GenericFunctions.ts
  packages/nodes-base/nodes/DateTime/V1/DateTimeV1.node.ts
  packages/nodes-base/nodes/Linear/GenericFunctions.ts
  packages/nodes-base/nodes/S3/GenericFunctions.ts
  packages/nodes-base/nodes/WhatsApp/MessageFunctions.ts
  pnpm-lock.yaml
Labels: node/improvement, core, ui, n8n team

#8583 fix(HTTP Request Node): Errorneous binary object without content-disposition response header
  packages/nodes-base/nodes/HttpRequest/V3/HttpRequestV3.node.ts
Labels: n8n team, node/issue

#8561 fix(core): Custom workflow tool tweaks
  packages/@n8n/nodes-langchain/nodes/tools/ToolCode/ToolCode.node.ts
  packages/@n8n/nodes-langchain/nodes/tools/ToolWorkflow/ToolWorkflow.node.ts
Labels: node/improvement, n8n team, node/issue

#8584 feat(core): Link all shared workflows to the personal project of the user it's shared with
  packages/cli/src/PublicApi/v1/handlers/workflows/workflows.handler.ts
  packages/cli/src/PublicApi/v1/handlers/workflows/workflows.service.ts
  packages/cli/src/databases/entities/SharedCredentials.ts
  packages/cli/src/databases/entities/SharedWorkflow.ts
  packages/cli/src/databases/migrations/common/1705928727784-CreateProject.ts
  packages/cli/src/databases/repositories/sharedWorkflow.repository.ts
  packages/cli/src/services/import.service.ts
  packages/cli/src/workflows/workflows.controller.ts
  packages/cli/test/integration/PermissionChecker.test.ts
  packages/cli/test/integration/shared/db/workflows.ts
Labels: core, n8n team

#8526 feat: Add support for AI log streaming
  packages/@n8n/nodes-langchain/nodes/vector_store/shared/createVectorStoreNode.ts
  packages/@n8n/nodes-langchain/utils/logWrapper.ts
  packages/cli/src/WorkflowExecuteAdditionalData.ts
  packages/cli/src/eventbus/EventMessageClasses/EventMessageAiNode.ts
  packages/cli/src/eventbus/EventMessageClasses/index.ts
  packages/cli/src/eventbus/MessageEventBus/MessageEventBus.ts
  packages/cli/test/unit/ExecutionMetadataService.test.ts
  packages/cli/test/unit/WorkflowExecuteAdditionalData.test.ts
  packages/core/src/NodeExecuteFunctions.ts
  packages/editor-ui/src/plugins/i18n/locales/en.json
  packages/workflow/src/Interfaces.ts
  packages/workflow/src/MessageEventBus.ts
Labels: core, ui, n8n team

#8596 fix(core): Adjust executions list filter behavior
  packages/cli/src/executions/executions.controller.ts
  packages/cli/test/unit/controllers/executions.controller.test.ts
Labels: core, n8n team

#8595 fix: Fix bug in #8588
  packages/cli/src/PublicApi/v1/handlers/tags/tags.handler.ts
  packages/cli/src/PublicApi/v1/handlers/tags/tags.service.ts
Labels: core, community

#8550 feat: Create personal project when inviting a user
  packages/cli/src/controllers/e2e.controller.ts
  packages/cli/src/databases/entities/Project.ts
  packages/cli/src/databases/entities/ProjectRelation.ts
  packages/cli/src/databases/migrations/common/1705928727784-CreateProject.ts
  packages/cli/src/databases/repositories/user.repository.ts
  packages/cli/src/services/user.service.ts
  packages/cli/test/integration/controllers/invitation/invitation.controller.integration.test.ts
  packages/cli/test/integration/shared/db/users.ts
  packages/cli/test/integration/user.repository.test.ts
Labels: core, n8n team

#8601 fix(API): Fire workflowExecuteBefore hook in runMainProcess (no-changelog)
  packages/cli/src/WorkflowRunner.ts
Labels: core, n8n team

#8598 feat: Include totalUsers in usage metrics during license renewal (no-changelog)
  packages/cli/src/databases/repositories/usageMetrics.repository.ts
  packages/cli/src/services/usageMetrics.service.ts
  packages/cli/test/integration/usageMetrics.repository.test.ts
Labels: core, n8n team

#8597 refactor: Remove any appcues events
  packages/editor-ui/src/Interface.ts
  packages/editor-ui/src/plugins/__tests__/telemetry.test.ts
  packages/editor-ui/src/plugins/telemetry/index.ts
  packages/editor-ui/src/views/NodeView.vue
Labels: ui, n8n team

#8588 feat(API): Add tag support to public API
  packages/cli/src/PublicApi/types.ts
  packages/cli/src/PublicApi/v1/handlers/tags/spec/paths/tags.id.yml
  packages/cli/src/PublicApi/v1/handlers/tags/spec/paths/tags.yml
  packages/cli/src/PublicApi/v1/handlers/tags/spec/schemas/parameters/tagId.yml
  packages/cli/src/PublicApi/v1/handlers/tags/spec/schemas/tag.yml
  packages/cli/src/PublicApi/v1/handlers/tags/spec/schemas/tagList.yml
  packages/cli/src/PublicApi/v1/handlers/tags/tags.handler.ts
  packages/cli/src/PublicApi/v1/handlers/workflows/spec/paths/workflows.id.tags.yml
  packages/cli/src/PublicApi/v1/handlers/workflows/spec/paths/workflows.yml
  packages/cli/src/PublicApi/v1/handlers/workflows/spec/schemas/tagIds.yml
  packages/cli/src/PublicApi/v1/handlers/workflows/spec/schemas/workflow.yml
  packages/cli/src/PublicApi/v1/handlers/workflows/spec/schemas/workflowTags.yml
  packages/cli/src/PublicApi/v1/handlers/workflows/workflows.handler.ts
  packages/cli/src/PublicApi/v1/handlers/workflows/workflows.service.ts
  packages/cli/src/PublicApi/v1/openapi.yml
  packages/cli/src/PublicApi/v1/shared/spec/parameters/_index.yml
  packages/cli/src/PublicApi/v1/shared/spec/responses/_index.yml
  packages/cli/src/PublicApi/v1/shared/spec/responses/forbidden.yml
  packages/cli/src/PublicApi/v1/shared/spec/schemas/_index.yml
  packages/cli/src/services/tag.service.ts
  packages/cli/test/integration/publicApi/tags.test.ts
  packages/cli/test/integration/publicApi/workflows.test.ts
Labels: core, n8n team

#8602 docs: Update cursor description in the public api documentation
  packages/cli/src/PublicApi/v1/shared/spec/parameters/cursor.yml
Labels: core, n8n team

#8571 fix(Jira Software Node): Fix issue with not all issue types being supported
  packages/nodes-base/nodes/Jira/IssueDescription.ts
Labels: node/improvement, n8n team

#8600 refactor(editor): Refactor workflowHelpers mixin to composable (no-changelog)
  packages/editor-ui/src/components/AssignmentCollection/Assignment.vue
  packages/editor-ui/src/components/AssignmentCollection/__tests__/AssignmentCollection.test.ts
  packages/editor-ui/src/components/AssignmentCollection/utils.ts
  packages/editor-ui/src/components/CodeNodeEditor/CodeNodeEditor.vue
  packages/editor-ui/src/components/ContactPromptModal.vue
  packages/editor-ui/src/components/DuplicateWorkflowDialog.vue
  packages/editor-ui/src/components/ExecutionsView/ExecutionsInfoAccordion.vue
  packages/editor-ui/src/components/ExecutionsView/ExecutionsList.vue
  packages/editor-ui/src/components/ExpressionEditorModal/ExpressionEditorModalInput.vue
  packages/editor-ui/src/components/FilterConditions/Condition.vue
  packages/editor-ui/src/components/FilterConditions/FilterConditions.vue
  packages/editor-ui/src/components/InlineExpressionEditor/InlineExpressionEditorInput.vue
  packages/editor-ui/src/components/InputPanel.vue
  packages/editor-ui/src/components/MainHeader/MainHeader.vue
  packages/editor-ui/src/components/MainHeader/WorkflowDetails.vue
  packages/editor-ui/src/components/Node.vue
  packages/editor-ui/src/components/NodeDetailsView.vue
  packages/editor-ui/src/components/NodeExecuteButton.vue
  packages/editor-ui/src/components/NodeWebhooks.vue
  packages/editor-ui/src/components/ParameterInput.vue
  packages/editor-ui/src/components/ParameterInputList.vue
  packages/editor-ui/src/components/ParameterInputWrapper.vue
  packages/editor-ui/src/components/PersonalizationModal.vue
  packages/editor-ui/src/components/ResourceLocator/ResourceLocator.vue
  packages/editor-ui/src/components/ResourceMapper/ResourceMapper.vue
  packages/editor-ui/src/components/Sticky.vue
  packages/editor-ui/src/components/TriggerPanel.vue
  packages/editor-ui/src/components/ValueSurvey.vue
  packages/editor-ui/src/components/VariableSelector.vue
  packages/editor-ui/src/components/WorkflowLMChat.vue
  packages/editor-ui/src/components/__tests__/ResourceMapper.test.ts
  packages/editor-ui/src/composables/useDebounce.ts
  packages/editor-ui/src/composables/useWorkflowHelpers.ts
  packages/editor-ui/src/mixins/__tests__/workflowHelpers.spec.ts
  packages/editor-ui/src/mixins/expressionManager.ts
  packages/editor-ui/src/mixins/pushConnection.ts
  packages/editor-ui/src/mixins/workflowActivate.ts
  packages/editor-ui/src/mixins/workflowHelpers.ts
  packages/editor-ui/src/mixins/workflowRun.ts
  packages/editor-ui/src/plugins/codemirror/completions/__tests__/completions.test.ts
  packages/editor-ui/src/plugins/codemirror/completions/bracketAccess.completions.ts
  packages/editor-ui/src/plugins/codemirror/completions/datatype.completions.ts
  packages/editor-ui/src/plugins/codemirror/completions/types.ts
  packages/editor-ui/src/plugins/codemirror/completions/utils.ts
  packages/editor-ui/src/views/NodeView.vue
  packages/editor-ui/src/views/TemplatesCollectionView.vue
  packages/editor-ui/src/views/TemplatesWorkflowView.vue
Labels: ui, n8n team

#8605 fix: Fix MFA end to end tests
  packages/cli/src/controllers/e2e.controller.ts
Labels: core, n8n team

#8613 fix(FTP Node): Fix issue with paireditems not always working
  packages/nodes-base/nodes/Ftp/Ftp.node.ts
Labels: node/improvement, n8n team

#8576 fix(HTTP Request Node): Handle special characters in pagination expressions + improve hint text
  packages/@n8n/nodes-langchain/nodes/trigger/ChatTrigger/ChatTrigger.node.ts
  packages/core/src/NodeExecuteFunctions.ts
  packages/editor-ui/src/components/InlineExpressionEditor/InlineExpressionEditorInput.vue
  packages/editor-ui/src/components/Node.vue
  packages/editor-ui/src/composables/useWorkflowHelpers.ts
  packages/nodes-base/nodes/HttpRequest/V3/HttpRequestV3.node.ts
  packages/nodes-base/nodes/HttpRequest/test/node/workflow.pagination.json
  packages/nodes-base/test/nodes/Helpers.ts
  packages/workflow/src/RoutingNode.ts
  packages/workflow/src/errors/node-api.error.ts
  packages/workflow/src/errors/node-operation.error.ts
Labels: node/improvement, core, ui, n8n team

#8615 docs: Update changelog to make removal of own node obvious (no-changelog)
  CHANGELOG.md
Labels: n8n team

#8614 fix(Execute Workflow Node): Passing the workflow that is supposed to be executed as a paramter
  packages/nodes-base/nodes/ExecuteWorkflow/GenericFunctions.ts
Labels: node/improvement, n8n team

#8618 fix(core): Give better error message if `executions.process` is still used in the configs
  packages/cli/src/config/index.ts
  packages/cli/src/config/schema.ts
Labels: core, n8n team

#8479 fix(Merge Node): Fixing how paired items are handled in the merge node, when choosing a branch and selecting to return an empty object
  packages/nodes-base/nodes/Merge/test/node/workflow.chooseBranch.empty.paired.items.json
  packages/nodes-base/nodes/Merge/v2/MergeV2.node.ts
Labels: node/improvement, n8n team

#8619 fix(FTP Node): Fix issue with connections not closing properly
  packages/nodes-base/nodes/Ftp/Ftp.node.ts
Labels: node/improvement, n8n team

#8612 fix: Fix resolving of expressions of deeply nested sub-nodes
  packages/editor-ui/src/components/VariableSelector.vue
  packages/editor-ui/src/composables/useWorkflowHelpers.ts
  packages/workflow/src/Workflow.ts
  packages/workflow/src/WorkflowDataProxy.ts
Labels: core, ui, n8n team

#8622 fix(Notion Node): Block with text results in a body validation error
  packages/nodes-base/nodes/Notion/GenericFunctions.ts
  packages/nodes-base/nodes/Notion/test/GenericFunctions.test.ts
Labels: n8n team, node/issue

#8625 feat: Add telemetry event when users click on templates link
  packages/editor-ui/src/components/MainSidebar.vue
Labels: ui, n8n team

#8627 fix(core): Upgrade `@n8n/typeorm` to address postgres timestamp issues
  packages/@n8n/nodes-langchain/package.json
  packages/cli/package.json
  pnpm-lock.yaml
Labels: core, n8n team

#8629 fix(editor): Debounce expression changes
  packages/editor-ui/src/components/ExpressionParameterInput.vue
Labels: ui, n8n team

#8630 fix(core): Improve the startup error when EXECUTIONS_PROCESS is set
  packages/cli/src/commands/BaseCommand.ts
  packages/cli/src/config/index.ts
  packages/cli/src/config/schema.ts
Labels: core, n8n team

#8632 docs: Document own mode removal in `BREAKING-CHANGES.md` (no-changelog)
  packages/cli/BREAKING-CHANGES.md
Labels: core, n8n team

#8631 fix(core): Improve handling of wrapped errors (no-changelog)
  packages/workflow/src/errors/abstract/node.error.ts
  packages/workflow/src/errors/application.error.ts
  packages/workflow/test/errors/node.error.test.ts
Labels: core, n8n team

#8335 feat(OpenAI Node): Overhaul
  packages/@n8n/nodes-langchain/jest.config.js
  packages/@n8n/nodes-langchain/nodes/agents/OpenAiAssistant/OpenAiAssistant.node.ts
  packages/@n8n/nodes-langchain/nodes/tools/ToolCode/ToolCode.node.ts
  packages/@n8n/nodes-langchain/nodes/tools/ToolWorkflow/ToolWorkflow.node.ts
  packages/@n8n/nodes-langchain/nodes/vendors/OpenAi/OpenAi.node.ts
  packages/@n8n/nodes-langchain/nodes/vendors/OpenAi/actions/assistant/create.operation.ts
  packages/@n8n/nodes-langchain/nodes/vendors/OpenAi/actions/assistant/deleteAssistant.operation.ts
  packages/@n8n/nodes-langchain/nodes/vendors/OpenAi/actions/assistant/index.ts
  packages/@n8n/nodes-langchain/nodes/vendors/OpenAi/actions/assistant/list.operation.ts
  packages/@n8n/nodes-langchain/nodes/vendors/OpenAi/actions/assistant/message.operation.ts
  packages/@n8n/nodes-langchain/nodes/vendors/OpenAi/actions/assistant/update.operation.ts
  packages/@n8n/nodes-langchain/nodes/vendors/OpenAi/actions/audio/generate.operation.ts
  packages/@n8n/nodes-langchain/nodes/vendors/OpenAi/actions/audio/index.ts
  packages/@n8n/nodes-langchain/nodes/vendors/OpenAi/actions/audio/transcribe.operation.ts
  packages/@n8n/nodes-langchain/nodes/vendors/OpenAi/actions/audio/translate.operation.ts
  packages/@n8n/nodes-langchain/nodes/vendors/OpenAi/actions/descriptions.ts
  packages/@n8n/nodes-langchain/nodes/vendors/OpenAi/actions/file/deleteFile.operation.ts
  packages/@n8n/nodes-langchain/nodes/vendors/OpenAi/actions/file/index.ts
  packages/@n8n/nodes-langchain/nodes/vendors/OpenAi/actions/file/list.operation.ts
  packages/@n8n/nodes-langchain/nodes/vendors/OpenAi/actions/file/upload.operation.ts
  packages/@n8n/nodes-langchain/nodes/vendors/OpenAi/actions/image/analyze.operation.ts
  packages/@n8n/nodes-langchain/nodes/vendors/OpenAi/actions/image/generate.operation.ts
  packages/@n8n/nodes-langchain/nodes/vendors/OpenAi/actions/image/index.ts
  packages/@n8n/nodes-langchain/nodes/vendors/OpenAi/actions/node.type.ts
  packages/@n8n/nodes-langchain/nodes/vendors/OpenAi/actions/router.ts
  packages/@n8n/nodes-langchain/nodes/vendors/OpenAi/actions/text/classify.operation.ts
  packages/@n8n/nodes-langchain/nodes/vendors/OpenAi/actions/text/index.ts
  packages/@n8n/nodes-langchain/nodes/vendors/OpenAi/actions/text/message.operation.ts
  packages/@n8n/nodes-langchain/nodes/vendors/OpenAi/actions/versionDescription.ts
  packages/@n8n/nodes-langchain/nodes/vendors/OpenAi/helpers/interfaces.ts
  packages/@n8n/nodes-langchain/nodes/vendors/OpenAi/helpers/utils.ts
  packages/@n8n/nodes-langchain/nodes/vendors/OpenAi/methods/index.ts
  packages/@n8n/nodes-langchain/nodes/vendors/OpenAi/methods/listSearch.ts
  packages/@n8n/nodes-langchain/nodes/vendors/OpenAi/methods/loadOptions.ts
  packages/@n8n/nodes-langchain/nodes/vendors/OpenAi/openAi.svg
  packages/@n8n/nodes-langchain/nodes/vendors/OpenAi/test/OpenAi.node.test.ts
  packages/@n8n/nodes-langchain/nodes/vendors/OpenAi/transport/index.ts
  packages/@n8n/nodes-langchain/package.json
  packages/@n8n/nodes-langchain/utils/sharedFields.ts
  packages/core/src/DirectoryLoader.ts
  packages/editor-ui/public/static/open-ai.svg
  packages/editor-ui/src/components/Node/NodeCreator/Modes/ActionsMode.vue
  packages/editor-ui/src/components/Node/NodeCreator/composables/useActions.ts
  packages/editor-ui/src/components/Node/NodeCreator/viewsData.ts
  packages/editor-ui/src/constants.ts
  packages/nodes-base/nodes/OpenAi/OpenAi.node.ts
  packages/workflow/src/index.ts
  packages/workflow/src/utils.ts
  pnpm-lock.yaml
Labels: node/improvement, n8n team, node/issue

#8636 refactor(editor): Do not use CodeNodeEditor anywhere except the Code node (no-changelog)
  packages/@n8n/nodes-langchain/nodes/code/Code.node.ts
  packages/@n8n/nodes-langchain/nodes/tools/ToolCode/ToolCode.node.ts
  packages/editor-ui/src/components/ChatEmbedModal.vue
Labels: ui, n8n team

#8641 test: Fix broken workflow tag tests
  packages/cli/src/PublicApi/v1/handlers/workflows/workflows.handler.ts
Labels: core, n8n team

#8645 fix: Broken migration for create project (no-changelog)
  packages/cli/src/databases/migrations/common/1705928727784-CreateProject.ts
Labels: core, n8n team

#8646 fix(GraphQL Node): Fix request format JSON error
  packages/nodes-base/nodes/GraphQL/GraphQL.node.ts
  packages/nodes-base/nodes/GraphQL/test/GraphQL.node.test.ts
  packages/nodes-base/nodes/GraphQL/test/workflow.json
  packages/workflow/src/Interfaces.ts
Labels: node/improvement, n8n team

#8651 fix(OpenAI Node): Always show jsonOutput toggle for OpenAI message operation (no-changelog)
  packages/@n8n/nodes-langchain/nodes/vendors/OpenAi/actions/text/message.operation.ts
Labels: n8n team

#8648 ci: Disable flaky 38-custom-template-repository.cy.ts (no-changelog)
  cypress/e2e/38-custom-template-repository.cy.ts
Labels: n8n team

#8647 fix(Extract From File Node): Make binary data work with any backend
  packages/nodes-base/utils/binary.ts
Labels: node/improvement, n8n team

#8483 refactor(editor): Re-organize n8n logo files (no-changelog)
  cypress/e2e/18-user-management.cy.ts
  packages/editor-ui/public/favicon-16x16.png
  packages/editor-ui/public/favicon-32x32.png
  packages/editor-ui/public/google-signin-light.png
  packages/editor-ui/public/n8n-icon-small.png
  packages/editor-ui/public/n8n-logo.svg
  packages/editor-ui/public/static/logo/channel/beta-dark.svg
  packages/editor-ui/public/static/logo/channel/beta.svg
  packages/editor-ui/public/static/logo/channel/dev-dark.svg
  packages/editor-ui/public/static/logo/channel/dev.svg
  packages/editor-ui/public/static/logo/channel/nightly-dark.svg
  packages/editor-ui/public/static/logo/channel/nightly.svg
  packages/editor-ui/public/static/logo/collapsed.svg
  packages/editor-ui/public/static/logo/expanded-dark.svg
  packages/editor-ui/public/static/logo/expanded.svg
  packages/editor-ui/src/components/MainSidebar.vue
  packages/editor-ui/src/stores/ui.store.ts
Labels: ui, n8n team

#8621 fix(editor): Fix SQL editors not always re-rendering when query changes
  cypress/e2e/29-sql-editor.cy.ts
  packages/editor-ui/src/components/HtmlEditor/HtmlEditor.vue
  packages/editor-ui/src/components/SqlEditor/SqlEditor.vue
  packages/editor-ui/src/mixins/expressionManager.ts
Labels: ui, n8n team

#8658 fix(OpenAI Node): Remove require from text in assistant message (no-changelog)
  packages/@n8n/nodes-langchain/nodes/vendors/OpenAi/actions/assistant/message.operation.ts
Labels: n8n team, node/issue

#8635 fix(editor): Filter component: do not clear expression when changing operator
  packages/editor-ui/src/components/FilterConditions/Condition.vue
  packages/editor-ui/src/components/FilterConditions/OperatorSelect.vue
  packages/editor-ui/src/components/FilterConditions/__tests__/FilterConditions.test.ts
  packages/editor-ui/src/components/FilterConditions/__tests__/utils.test.ts
  packages/editor-ui/src/components/FilterConditions/types.ts
  packages/editor-ui/src/components/FilterConditions/utils.ts
  packages/editor-ui/src/utils/expressions.ts
Labels: ui, n8n team

#8657 fix(FTP Node): Fix "Maximum call stack size exceeded" error when dealing with too many files
  packages/nodes-base/nodes/Ftp/Ftp.node.ts
Labels: node/improvement, n8n team

#8660 fix(editor): Use proper composable for localization
  packages/editor-ui/src/composables/useWorkflowHelpers.ts
Labels: ui, n8n team

#8669 fix(editor): Fix runData check for pinned data
  cypress/e2e/19-execution.cy.ts
  cypress/fixtures/Check_manual_node_run_for_pinned_and_rundata.json
  packages/editor-ui/src/mixins/workflowRun.ts
  packages/editor-ui/src/utils/typesUtils.ts
Labels: ui, n8n team

#8628 fix(Google Calendar Node): Errors with after/before options
  packages/nodes-base/nodes/Google/Calendar/GenericFunctions.ts
  packages/nodes-base/nodes/Google/Calendar/GoogleCalendar.node.ts
  packages/nodes-base/nodes/Google/Calendar/test/GeneircFunctions.test.ts
Labels: n8n team, node/issue

#8546 refactor(core): Introduce `@GlobalScope()` and `@ProjectScope()` decorators (no-changelog)
  packages/cli/.eslintrc.js
  packages/cli/src/ExternalSecrets/ExternalSecrets.controller.ee.ts
  packages/cli/src/Ldap/ldap.controller.ts
  packages/cli/src/PublicApi/types.ts
  packages/cli/src/PublicApi/v1/handlers/credentials/credentials.handler.ts
  packages/cli/src/auth/jwt.ts
  packages/cli/src/constants.ts
  packages/cli/src/controllers/auth.controller.ts
  packages/cli/src/controllers/communityPackages.controller.ts
  packages/cli/src/controllers/invitation.controller.ts
  packages/cli/src/controllers/orchestration.controller.ts
  packages/cli/src/controllers/passwordReset.controller.ts
  packages/cli/src/controllers/tags.controller.ts
  packages/cli/src/controllers/users.controller.ts
  packages/cli/src/credentials/credentials.controller.ts
  packages/cli/src/databases/entities/User.ts
  packages/cli/src/databases/repositories/projectRelation.repository.ts
  packages/cli/src/decorators/Scoped.ts
  packages/cli/src/decorators/Scopes.ts
  packages/cli/src/decorators/constants.ts
  packages/cli/src/decorators/index.ts
  packages/cli/src/decorators/registerController.ts
  packages/cli/src/decorators/types.ts
  packages/cli/src/environments/sourceControl/sourceControl.controller.ee.ts
  packages/cli/src/environments/variables/variables.controller.ee.ts
  packages/cli/src/errors/response-errors/forbidden.error.ts
  packages/cli/src/errors/response-errors/unauthenticated.error.ts
  packages/cli/src/errors/response-errors/unauthorized.error.ts
  packages/cli/src/eventbus/eventBus.controller.ee.ts
  packages/cli/src/eventbus/eventBus.controller.ts
  packages/cli/src/license/license.controller.ts
  packages/cli/src/permissions/global-roles.ts
  packages/cli/src/permissions/project-roles.ts
  packages/cli/src/permissions/resource-roles.ts
  packages/cli/src/requests.ts
  packages/cli/src/services/role.service.ts
  packages/cli/src/sso/saml/routes/saml.controller.ee.ts
  packages/cli/src/workflows/workflow.request.ts
  packages/cli/src/workflows/workflows.controller.ts
  packages/cli/test/integration/credentials.ee.test.ts
  packages/cli/test/integration/credentials.test.ts
  packages/cli/test/integration/license.api.test.ts
  packages/cli/test/integration/users.api.test.ts
  packages/cli/test/integration/workflows/workflows.controller.ee.test.ts
  packages/cli/test/unit/repositories/sharedCredentials.repository.test.ts
Labels: core, n8n team

#8659 fix(FTP Node): Continue of fail looping support with paired item
  packages/nodes-base/nodes/Ftp/Ftp.node.ts
Labels: n8n team, node/issue

#8674 fix(core): Apply correct hostname to redirected requests
  packages/core/src/NodeExecuteFunctions.ts
Labels: core, n8n team

#8676 fix: ProjectRepository.getPersonalProjectForUser[OrFail] not taking the type or the role of the user to the project into account
  packages/cli/src/databases/repositories/project.repository.ts
  packages/cli/test/integration/database/repositories/project.repository.test.ts
  packages/cli/test/integration/shared/db/projects.ts
  packages/cli/test/integration/shared/testDb.ts
Labels: core, n8n team

#8633 feat(editor): Add chevron to filter component operator select
  packages/editor-ui/src/components/FilterConditions/OperatorSelect.vue
Labels: ui, n8n team

#8680 fix(core): Report all sqlite transaction rollback errors to Sentry (no-changelog)
  packages/@n8n/nodes-langchain/package.json
  packages/cli/package.json
  pnpm-lock.yaml
Labels: core, n8n team

#8678 fix: Fix typeorm .save usage (no-changelog)
  packages/cli/src/Ldap/helpers.ts
  packages/cli/src/controllers/invitation.controller.ts
  packages/cli/src/controllers/me.controller.ts
  packages/cli/src/controllers/owner.controller.ts
  packages/cli/src/databases/repositories/settings.repository.ts
  packages/cli/src/environments/sourceControl/sourceControlImport.service.ee.ts
  packages/cli/src/environments/sourceControl/sourceControlPreferences.service.ee.ts
  packages/cli/src/environments/variables/variables.service.ee.ts
  packages/cli/src/services/tag.service.ts
  packages/cli/src/sso/saml/saml.service.ee.ts
  packages/cli/src/sso/saml/samlHelpers.ts
  packages/cli/src/sso/ssoHelpers.ts
  packages/cli/test/unit/controllers/me.controller.test.ts
  packages/cli/test/unit/controllers/owner.controller.test.ts
Labels: core, n8n team

#8673 fix(editor): Wrap expressions in resource locator component
  packages/editor-ui/src/components/InlineExpressionEditor/theme.ts
  packages/editor-ui/src/components/ResourceLocator/ResourceLocator.vue
Labels: ui, n8n team

#8683 feat(core): Add support for $("NodeName").isExecuted
  packages/workflow/src/WorkflowDataProxy.ts
  packages/workflow/test/WorkflowDataProxy.test.ts
Labels: core, n8n team

#8652 feat(Google Sheets Node): Option how to combine filters when reading rows
  packages/nodes-base/nodes/Google/Sheet/GoogleSheets.node.ts
  packages/nodes-base/nodes/Google/Sheet/test/v2/utils/utils.test.ts
  packages/nodes-base/nodes/Google/Sheet/v2/actions/sheet/append.operation.ts
  packages/nodes-base/nodes/Google/Sheet/v2/actions/sheet/appendOrUpdate.operation.ts
  packages/nodes-base/nodes/Google/Sheet/v2/actions/sheet/read.operation.ts
  packages/nodes-base/nodes/Google/Sheet/v2/actions/sheet/update.operation.ts
  packages/nodes-base/nodes/Google/Sheet/v2/actions/versionDescription.ts
  packages/nodes-base/nodes/Google/Sheet/v2/helpers/GoogleSheet.ts
  packages/workflow/src/Interfaces.ts
Labels: node/improvement, n8n team, node/issue

#8689 feat: Allow product updates as well as security updates (no-changelog)
  packages/editor-ui/src/api/workflow-webhooks.ts
  packages/editor-ui/src/plugins/i18n/locales/en.json
Labels: ui, n8n team

#8663 fix(editor): Escape node names with quotes in autocomplete and drag'n'drop
  packages/editor-ui/src/components/CodeNodeEditor/completions/base.completions.ts
  packages/editor-ui/src/components/VariableSelector.vue
  packages/editor-ui/src/plugins/codemirror/completions/dollar.completions.ts
  packages/editor-ui/src/utils/__tests__/mappingUtils.test.ts
  packages/editor-ui/src/utils/mappingUtils.ts
Labels: ui, n8n team

#8574 refactor(core): Enrich inaccessible credential error
  packages/cli/src/UserManagement/PermissionChecker.ts
  packages/workflow/src/errors/abstract/execution-base.error.ts
  packages/workflow/src/errors/credential-access-error.ts
  packages/workflow/src/errors/index.ts
Labels: core, n8n team

#8691 fix(editor): Send protocol and n8n version in templates destination parameter, stop redirecting template preview page to website
  cypress/e2e/29-templates.cy.ts
  packages/editor-ui/src/Interface.ts
  packages/editor-ui/src/router.ts
  packages/editor-ui/src/stores/templates.store.ts
Labels: ui, n8n team

#8677 feat(core): Move execution permission checks earlier in the lifecycle
  packages/cli/src/UserManagement/PermissionChecker.ts
  packages/cli/src/WorkflowExecuteAdditionalData.ts
  packages/cli/src/WorkflowRunner.ts
  packages/cli/src/commands/worker.ts
  packages/cli/test/integration/PermissionChecker.test.ts
  packages/cli/test/unit/PermissionChecker.test.ts
  packages/editor-ui/src/mixins/pushConnection.ts
  packages/editor-ui/src/stores/workflows.store.ts
  packages/workflow/src/Interfaces.ts
  packages/workflow/src/errors/credential-access-error.ts
Labels: core, ui, n8n team

#8693 docs(OpenAI Node): Use the correct docs url (no-changelog)
  packages/@n8n/nodes-langchain/nodes/vendors/OpenAi/actions/versionDescription.ts
Labels: n8n team

#8700 fix(editor): Correctly set condition operator when changed
  packages/editor-ui/src/components/FilterConditions/__tests__/utils.test.ts
  packages/editor-ui/src/components/FilterConditions/utils.ts
Labels: ui, n8n team

#8699 feat(AI Agent Node): Whitelist Azure Chat model for Agent
  cypress/e2e/30-langchain.cy.ts
  packages/@n8n/nodes-langchain/nodes/agents/Agent/Agent.node.ts
Labels: n8n team

#8499 feat(Google Workspace Admin Node): Add support for error output branch
  packages/nodes-base/nodes/Google/GSuiteAdmin/GSuiteAdmin.node.ts
Labels: node/improvement, n8n team

#8665 feat: Update resource list pages for RBAC
  packages/editor-ui/src/components/forms/ResourceFiltersDropdown.vue
  packages/editor-ui/src/components/forms/ResourceOwnershipSelect.ee.vue
  packages/editor-ui/src/components/layouts/PageViewLayout.vue
  packages/editor-ui/src/components/layouts/PageViewLayoutList.vue
  packages/editor-ui/src/components/layouts/ResourcesListLayout.vue
  packages/editor-ui/src/views/WorkflowsView.vue
Labels: ui, n8n team, feature/rbac

#8623 feat: Change routes for RBAC
  packages/editor-ui/src/__tests__/router.test.ts
  packages/editor-ui/src/components/MainHeader/WorkflowDetails.vue
  packages/editor-ui/src/components/WorkflowCard.vue
  packages/editor-ui/src/components/WorkflowShareModal.ee.vue
  packages/editor-ui/src/components/forms/ResourceFiltersDropdown.vue
  packages/editor-ui/src/components/forms/ResourceOwnershipSelect.ee.vue
  packages/editor-ui/src/components/layouts/PageViewLayout.vue
  packages/editor-ui/src/components/layouts/PageViewLayoutList.vue
  packages/editor-ui/src/components/layouts/ResourcesListLayout.vue
  packages/editor-ui/src/constants.ts
  packages/editor-ui/src/features/projects/projects.routes.ts
  packages/editor-ui/src/router.ts
  packages/editor-ui/src/views/NodeView.vue
  packages/editor-ui/src/views/WorkflowsView.vue
Labels: ui, n8n team, feature/rbac

#8688 feat(editor): Add projects menu
  packages/editor-ui/src/components/MainSidebar.vue
  packages/editor-ui/src/features/projects/ProjectNavigation.vue
Labels: ui, n8n team, feature/rbac

#8517 docs(editor): Nodes icons, Merge node descriptions
  cypress/e2e/4-node-creator.cy.ts
  packages/nodes-base/nodes/Code/Code.node.ts
  packages/nodes-base/nodes/Code/code.svg
  packages/nodes-base/nodes/Files/ConvertToFile/ConvertToFile.node.json
  packages/nodes-base/nodes/Files/ConvertToFile/ConvertToFile.node.ts
  packages/nodes-base/nodes/Files/ExtractFromFile/ExtractFromFile.node.json
  packages/nodes-base/nodes/Files/ExtractFromFile/ExtractFromFile.node.ts
  packages/nodes-base/nodes/Merge/Merge.node.ts
  packages/nodes-base/nodes/Merge/merge.svg
  packages/nodes-base/nodes/Merge/test/node/workflow.mixed.not.forceInputNodeExecution.json
  packages/nodes-base/nodes/Merge/v1/MergeV1.node.ts
  packages/nodes-base/nodes/Merge/v2/MergeV2.node.ts
  packages/nodes-base/nodes/Microsoft/Excel/v2/actions/versionDescription.ts
  packages/nodes-base/nodes/Transform/Sort/Sort.node.json
  packages/nodes-base/nodes/WhatsApp/WhatsApp.node.json
  packages/nodes-base/nodes/Xml/Xml.node.ts
Labels: node/improvement, n8n team

#8662 feat(core): Allow creating workflows in other projects than the personal one
  packages/cli/src/databases/repositories/project.repository.ts
  packages/cli/src/services/project.service.ts
  packages/cli/src/workflows/workflow.request.ts
  packages/cli/src/workflows/workflows.controller.ts
  packages/cli/test/integration/services/project.service.test.ts
  packages/cli/test/integration/workflows/workflows.controller.test.ts
Labels: n8n team, feature/rbac

#8698 fix(MongoDB Node): Driver update (no-changelog)
  packages/nodes-base/package.json
  pnpm-lock.yaml
Labels: node/improvement, n8n team, node/issue

#8708 fix: Wrong prompt input key for sql agent
  packages/@n8n/nodes-langchain/nodes/agents/Agent/agents/SqlAgent/execute.ts
Labels: n8n team, node/issue

#8696 feat(editor): Retrieve previous chat message on arrow-up
  packages/editor-ui/src/Interface.ts
  packages/editor-ui/src/components/WorkflowLMChat.vue
  packages/editor-ui/src/plugins/i18n/locales/en.json
  packages/editor-ui/src/stores/workflows.store.ts
  packages/editor-ui/src/views/NodeView.vue
Labels: ui, n8n team

#8714 fix(editor): Do not break NDV for version-less nodes
  cypress/e2e/5-ndv.cy.ts
  cypress/fixtures/Test_workflow_ndv_version.json
  packages/editor-ui/src/components/NodeSettings.vue
Labels: ui, n8n team

#8715 fix(Trello Node): Remove GET request body
  packages/nodes-base/nodes/Trello/GenericFunctions.ts
Labels: node/improvement, community

#8706 fix(core): Ensure `maxRedirects` is used for any http request defining it
  packages/core/src/NodeExecuteFunctions.ts
  packages/core/test/NodeExecuteFunctions.test.ts
  packages/nodes-base/nodes/HttpRequest/V1/HttpRequestV1.node.ts
  packages/nodes-base/nodes/HttpRequest/V2/HttpRequestV2.node.ts
  packages/workflow/src/Interfaces.ts
Labels: node/improvement, core, n8n team

#8704 ci: Upgrade `ip` to address CVE-2023-42282 (no-changelog)
  package.json
  pnpm-lock.yaml
Labels: n8n team

#8725 feat(AI Agent Node): Allow use of Azure Chat model for OpenAI Functions agent
  packages/@n8n/nodes-langchain/credentials/AzureOpenAiApi.credentials.ts
  packages/@n8n/nodes-langchain/nodes/agents/Agent/Agent.node.ts
Labels: n8n team

#8724 fix: Fix execution error when using AI chain nodes with non-chat model
  packages/@n8n/nodes-langchain/nodes/vector_store/shared/createVectorStoreNode.ts
  packages/@n8n/nodes-langchain/utils/helpers.ts
  packages/@n8n/nodes-langchain/utils/logWrapper.ts
Labels: n8n team

#8712 feat(editor): Add project page tab navigation
  packages/design-system/src/components/N8nTabs/Tabs.vue
  packages/editor-ui/src/components/layouts/ResourcesListLayout.vue
  packages/editor-ui/src/features/projects/components/ProjectTabs.vue
  packages/editor-ui/src/views/CredentialsView.vue
  packages/editor-ui/src/views/VariablesView.vue
  packages/editor-ui/src/views/WorkflowsView.vue
Labels: ui, n8n team

#8703 feat(editor): AI Floating Nodes
  cypress/e2e/5-ndv.cy.ts
  packages/editor-ui/src/components/NDVDraggablePanels.vue
  packages/editor-ui/src/components/NDVFloatingNodes.vue
  packages/editor-ui/src/components/NDVSubConnections.vue
  packages/editor-ui/src/components/NodeDetailsView.vue
  packages/editor-ui/src/components/NodeSettings.vue
  packages/editor-ui/src/views/NodeView.vue
Labels: ui, n8n team

#8686 refactor(core): Update auth related typings (no-changelog)
  packages/cli/src/PublicApi/index.ts
  packages/cli/src/PublicApi/types.ts
  packages/cli/src/PublicApi/v1/shared/middlewares/global.middleware.ts
  packages/cli/src/requests.ts
Labels: core, n8n team

#8727 feat: Allow editing team project
  packages/cli/src/controllers/project.controller.ts
  packages/cli/src/requests.ts
  packages/cli/src/services/project.service.ts
  packages/cli/test/integration/project.api.test.ts
Labels: core, n8n team

#8710 fix(editor): Hide previous execution data for sub-nodes in debug mode if it has execution error
  packages/editor-ui/src/components/InputPanel.vue
  packages/editor-ui/src/components/RunData.vue
Labels: ui, n8n team

#8709 feat: SQL agent improvements
  packages/@n8n/nodes-langchain/nodes/agents/Agent/Agent.node.ts
  packages/@n8n/nodes-langchain/nodes/agents/Agent/agents/SqlAgent/description.ts
  packages/@n8n/nodes-langchain/nodes/agents/Agent/agents/SqlAgent/execute.ts
  packages/@n8n/nodes-langchain/nodes/agents/Agent/agents/SqlAgent/other/handlers/sqlite.ts
  packages/@n8n/nodes-langchain/nodes/agents/Agent/agents/SqlAgent/other/prompts.ts
  packages/@n8n/nodes-langchain/nodes/vendors/OpenAi/actions/file/upload.operation.ts
  packages/@n8n/nodes-langchain/nodes/vendors/OpenAi/test/OpenAi.node.test.ts
  packages/@n8n/nodes-langchain/utils/descriptions.ts
  packages/@n8n/nodes-langchain/utils/helpers.ts
  packages/workflow/src/Interfaces.ts
  packages/workflow/src/TelemetryHelpers.ts
Labels: node/improvement, n8n team, node/issue

#8639 fix: Send user id when setting up an account
  packages/editor-ui/src/api/workflow-webhooks.ts
  packages/editor-ui/src/components/PersonalizationModal.vue
  packages/editor-ui/src/stores/ui.store.ts
  packages/editor-ui/src/views/NodeView.vue
Labels: ui, n8n team

#8716 feat: Allow instance owners and admins to edit all credentials
  packages/cli/src/credentials/credentials.controller.ts
  packages/cli/src/permissions/roles.ts
  packages/cli/test/integration/credentials.ee.test.ts
  packages/cli/test/integration/credentials.test.ts
  packages/editor-ui/src/components/CredentialEdit/CredentialConfig.vue
  packages/editor-ui/src/permissions.ts
Labels: core, ui, n8n team

#8448 feat: No expression error when node hasn’t executed
  cypress/e2e/11-inline-expression-editor.cy.ts
  cypress/e2e/14-mapping.cy.ts
  cypress/e2e/9-expression-editor-modal.cy.ts
  packages/design-system/src/css/_tokens.dark.scss
  packages/design-system/src/css/_tokens.scss
  packages/editor-ui/src/components/ExpressionParameterInput.vue
  packages/editor-ui/src/components/InlineExpressionEditor/InlineExpressionEditorOutput.vue
  packages/editor-ui/src/components/InputPanel.vue
  packages/editor-ui/src/components/NodeExecuteButton.vue
  packages/editor-ui/src/components/ParameterInputWrapper.vue
  packages/editor-ui/src/mixins/expressionManager.ts
  packages/editor-ui/src/mixins/pushConnection.ts
  packages/editor-ui/src/plugins/codemirror/resolvableHighlighter.ts
  packages/editor-ui/src/plugins/i18n/locales/en.json
  packages/editor-ui/src/stores/ndv.store.ts
  packages/editor-ui/src/types/expressions.ts
  packages/editor-ui/src/utils/expressions.ts
  packages/workflow/src/Interfaces.ts
  packages/workflow/src/WorkflowDataProxy.ts
  packages/workflow/src/errors/expression.error.ts
  packages/workflow/test/Expression.test.ts
  packages/workflow/test/ExpressionFixtures/base.ts
  packages/workflow/test/Helpers.ts
  packages/workflow/test/NodeTypes.ts
  packages/workflow/test/WorkflowDataProxy.test.ts
  packages/workflow/test/fixtures/WorkflowDataProxy/base_run.json
  packages/workflow/test/fixtures/WorkflowDataProxy/base_workflow.json
  packages/workflow/test/fixtures/WorkflowDataProxy/errors_run.json
  packages/workflow/test/fixtures/WorkflowDataProxy/errors_workflow.json
Labels: core, ui, n8n team

#8711 feat(editor): Migrate workflowRun mixin to useRunWorkflow composable (no-changelog)
  packages/editor-ui/src/components/DuplicateWorkflowDialog.vue
  packages/editor-ui/src/components/ExecutionsView/ExecutionsInfoAccordion.vue
  packages/editor-ui/src/components/ExecutionsView/ExecutionsList.vue
  packages/editor-ui/src/components/MainHeader/WorkflowDetails.vue
  packages/editor-ui/src/components/NodeDetailsView.vue
  packages/editor-ui/src/components/NodeExecuteButton.vue
  packages/editor-ui/src/components/NodeWebhooks.vue
  packages/editor-ui/src/components/ParameterInput.vue
  packages/editor-ui/src/components/ParameterInputList.vue
  packages/editor-ui/src/components/ParameterInputWrapper.vue
  packages/editor-ui/src/components/ResourceLocator/ResourceLocator.vue
  packages/editor-ui/src/components/TriggerPanel.vue
  packages/editor-ui/src/components/VariableSelector.vue
  packages/editor-ui/src/components/WorkflowLMChat.vue
  packages/editor-ui/src/composables/useRunWorkflow.test.ts
  packages/editor-ui/src/composables/useRunWorkflow.ts
  packages/editor-ui/src/composables/useToast.ts
  packages/editor-ui/src/composables/useWorkflowHelpers.ts
  packages/editor-ui/src/mixins/expressionManager.ts
  packages/editor-ui/src/mixins/pushConnection.ts
  packages/editor-ui/src/mixins/workflowActivate.ts
  packages/editor-ui/src/mixins/workflowRun.ts
  packages/editor-ui/src/views/NodeView.vue
Labels: ui, n8n team

#8749 fix(core): Do not report generic webhook execution errors (no-changelog)
  packages/cli/src/WebhookHelpers.ts
Labels: core, n8n team

#8748 feat: Add get project API and merge project patch APIs
  packages/@n8n/permissions/src/types.ts
  packages/cli/src/controllers/project.controller.ts
  packages/cli/src/permissions/global-roles.ts
  packages/cli/src/permissions/project-roles.ts
  packages/cli/src/requests.ts
  packages/cli/src/services/project.service.ts
  packages/cli/test/integration/project.api.test.ts
Labels: core, n8n team

#8736 feat: Session is selector for memory nodes
  packages/@n8n/nodes-langchain/nodes/memory/MemoryBufferWindow/MemoryBufferWindow.node.ts
  packages/@n8n/nodes-langchain/nodes/memory/MemoryMotorhead/MemoryMotorhead.node.ts
  packages/@n8n/nodes-langchain/nodes/memory/MemoryRedisChat/MemoryRedisChat.node.ts
  packages/@n8n/nodes-langchain/nodes/memory/MemoryXata/MemoryXata.node.ts
  packages/@n8n/nodes-langchain/nodes/memory/MemoryZep/MemoryZep.node.ts
  packages/@n8n/nodes-langchain/nodes/memory/descriptions.ts
  packages/@n8n/nodes-langchain/utils/helpers.ts
Labels: node/improvement, n8n team, node/issue

#8718 feat: Add role API (no-changelog)
  packages/cli/src/Server.ts
  packages/cli/src/controllers/role.controller.ts
  packages/cli/src/services/role.service.ts
  packages/cli/test/integration/role.api.test.ts
  packages/cli/test/integration/shared/types.ts
  packages/cli/test/integration/shared/utils/testServer.ts
Labels: core, n8n team

#8750 test: Update fix test that broke due to the global:owner having the credential:update scope now
  packages/cli/test/integration/credentials.test.ts
Labels: core, n8n team

#8752 docs: Update docker readme
  docker/images/n8n/README.md
Labels: n8n team

#8745 feat(editor): Filter and create workflows and credentials by projectId
  packages/editor-ui/src/api/credentials.ts
  packages/editor-ui/src/api/workflows.ts
  packages/editor-ui/src/components/CredentialEdit/CredentialEdit.vue
  packages/editor-ui/src/stores/credentials.store.ts
  packages/editor-ui/src/stores/workflows.store.ts
  packages/editor-ui/src/views/CredentialsView.vue
  packages/editor-ui/src/views/NodeView.vue
  packages/editor-ui/src/views/WorkflowsView.vue
Labels: ui, n8n team

#8753 fix: Project API GET (no-changelog)
  packages/cli/src/permissions/project-roles.ts
  packages/cli/src/services/project.service.ts
  packages/cli/test/integration/project.api.test.ts
Labels: core, n8n team

#8656 feat: Add Outlook Trigger Node
  packages/nodes-base/nodes/Microsoft/Outlook/MicrosoftOutlookTrigger.node.json
  packages/nodes-base/nodes/Microsoft/Outlook/MicrosoftOutlookTrigger.node.ts
  packages/nodes-base/nodes/Microsoft/Outlook/trigger/GenericFunctions.ts
  packages/nodes-base/nodes/Microsoft/Outlook/trigger/MessageDescription.ts
  packages/nodes-base/nodes/Microsoft/Outlook/v2/helpers/utils.ts
  packages/nodes-base/nodes/Microsoft/Outlook/v2/transport/index.ts
  packages/nodes-base/package.json
Labels: node/improvement, node/new, community

#8740 feat: Allow filtering credentials and workflows by project ID
  packages/cli/src/databases/repositories/credentials.repository.ts
  packages/cli/src/databases/repositories/workflow.repository.ts
  packages/cli/src/middlewares/listQuery/dtos/credentials.filter.dto.ts
  packages/cli/src/middlewares/listQuery/dtos/workflow.filter.dto.ts
  packages/cli/test/integration/credentials.controller.test.ts
  packages/cli/test/integration/workflows/workflows.controller.test.ts
Labels: core, n8n team

#8746 feat: Return project related information from `GET /workflows` and `GET /credentials`
  packages/cli/src/credentials/credentials.controller.ts
  packages/cli/src/databases/repositories/credentials.repository.ts
  packages/cli/src/databases/repositories/workflow.repository.ts
  packages/cli/src/requests.ts
  packages/cli/src/services/ownership.service.ts
  packages/cli/test/integration/credentials.ee.test.ts
  packages/cli/test/integration/workflows/workflows.controller.test.ts
  packages/cli/test/unit/services/ownership.service.test.ts
  packages/cli/test/unit/shared/mockObjects.ts
Labels: core, n8n team

#8757 feat: Chat Memory Manager group messages option, on insert delete return confirmation of success instead of messages
  packages/@n8n/nodes-langchain/nodes/memory/MemoryManager/MemoryManager.node.ts
Labels: node/improvement, n8n team, node/issue

#8760 refactor(core): Rename RequireGlobalScope to GlobalScope (no-changelog)
  packages/cli/src/ExternalSecrets/ExternalSecrets.controller.ee.ts
  packages/cli/src/Ldap/ldap.controller.ts
  packages/cli/src/controllers/communityPackages.controller.ts
  packages/cli/src/controllers/invitation.controller.ts
  packages/cli/src/controllers/orchestration.controller.ts
  packages/cli/src/controllers/tags.controller.ts
  packages/cli/src/controllers/users.controller.ts
  packages/cli/src/decorators/Scopes.ts
  packages/cli/src/decorators/index.ts
  packages/cli/src/environments/sourceControl/sourceControl.controller.ee.ts
  packages/cli/src/environments/variables/variables.controller.ee.ts
  packages/cli/src/eventbus/eventBus.controller.ee.ts
  packages/cli/src/eventbus/eventBus.controller.ts
  packages/cli/src/license/license.controller.ts
  packages/cli/src/sso/saml/routes/saml.controller.ee.ts
Labels: core, n8n team

#8762 refactor(core): Enforce authorization by default on all routes (no-changelog)
  packages/@n8n/permissions/src/types.ts
  packages/cli/src/ExternalSecrets/ExternalSecrets.controller.ee.ts
  packages/cli/src/Ldap/ldap.controller.ts
  packages/cli/src/auth/auth.service.ts
  packages/cli/src/controllers/activeWorkflows.controller.ts
  packages/cli/src/controllers/auth.controller.ts
  packages/cli/src/controllers/communityPackages.controller.ts
  packages/cli/src/controllers/cta.controller.ts
  packages/cli/src/controllers/debug.controller.ts
  packages/cli/src/controllers/dynamicNodeParameters.controller.ts
  packages/cli/src/controllers/e2e.controller.ts
  packages/cli/src/controllers/invitation.controller.ts
  packages/cli/src/controllers/me.controller.ts
  packages/cli/src/controllers/mfa.controller.ts
  packages/cli/src/controllers/nodeTypes.controller.ts
  packages/cli/src/controllers/oauth/oAuth1Credential.controller.ts
  packages/cli/src/controllers/oauth/oAuth2Credential.controller.ts
  packages/cli/src/controllers/orchestration.controller.ts
  packages/cli/src/controllers/owner.controller.ts
  packages/cli/src/controllers/passwordReset.controller.ts
  packages/cli/src/controllers/tags.controller.ts
  packages/cli/src/controllers/translation.controller.ts
  packages/cli/src/controllers/users.controller.ts
  packages/cli/src/credentials/credentials.controller.ts
  packages/cli/src/decorators/Authorized.ts
  packages/cli/src/decorators/Route.ts
  packages/cli/src/decorators/constants.ts
  packages/cli/src/decorators/index.ts
  packages/cli/src/decorators/registerController.ts
  packages/cli/src/decorators/types.ts
  packages/cli/src/environments/sourceControl/sourceControl.controller.ee.ts
  packages/cli/src/environments/variables/variables.controller.ee.ts
  packages/cli/src/eventbus/eventBus.controller.ee.ts
  packages/cli/src/eventbus/eventBus.controller.ts
  packages/cli/src/executions/executions.controller.ts
  packages/cli/src/license/license.controller.ts
  packages/cli/src/permissions/roles.ts
  packages/cli/src/push/index.ts
  packages/cli/src/requests.ts
  packages/cli/src/sso/saml/routes/saml.controller.ee.ts
  packages/cli/src/workflows/workflowHistory/workflowHistory.controller.ee.ts
  packages/cli/src/workflows/workflows.controller.ts
  packages/cli/test/integration/auth.mw.test.ts
  packages/cli/test/integration/owner.api.test.ts
  packages/cli/test/unit/auth/auth.service.test.ts
  packages/cli/test/unit/controllers/owner.controller.test.ts
Labels: core, n8n team

#8763 feat(core): Allow creating credentials in other projects than the personal one
  packages/cli/src/credentials/credentials.controller.ts
  packages/cli/src/credentials/credentials.service.ts
  packages/cli/src/decorators/registerController.ts
  packages/cli/src/requests.ts
  packages/cli/src/services/user.service.ts
  packages/cli/test/integration/credentials.test.ts
Labels: core, n8n team, feature/rbac

#8766 fix: AI agents, throw error on duplicate names in dynamic tools
  packages/@n8n/nodes-langchain/nodes/agents/Agent/Agent.node.ts
  packages/@n8n/nodes-langchain/nodes/agents/Agent/agents/ConversationalAgent/execute.ts
  packages/@n8n/nodes-langchain/nodes/agents/Agent/agents/OpenAiFunctionsAgent/execute.ts
  packages/@n8n/nodes-langchain/nodes/agents/Agent/agents/PlanAndExecuteAgent/execute.ts
  packages/@n8n/nodes-langchain/nodes/agents/Agent/agents/ReActAgent/execute.ts
  packages/@n8n/nodes-langchain/nodes/agents/Agent/agents/SqlAgent/execute.ts
  packages/@n8n/nodes-langchain/nodes/agents/OpenAiAssistant/OpenAiAssistant.node.ts
  packages/@n8n/nodes-langchain/nodes/vendors/OpenAi/actions/assistant/message.operation.ts
  packages/@n8n/nodes-langchain/nodes/vendors/OpenAi/actions/text/message.operation.ts
  packages/@n8n/nodes-langchain/nodes/vendors/OpenAi/actions/versionDescription.ts
  packages/@n8n/nodes-langchain/utils/helpers.ts
Labels: node/improvement, n8n team, node/issue

#8773 fix(core): Remove sensitive data from User entity during serialization (no-changelog)
  packages/cli/src/databases/entities/User.ts
  packages/cli/test/unit/databases/entities/user.entity.test.ts
Labels: core, n8n team

#8772 fix(HubSpot Node): Include properties for contact and deal in getAll operation
  packages/nodes-base/nodes/Hubspot/Hubspot.node.ts
  packages/nodes-base/nodes/Hubspot/V2/DealDescription.ts
  packages/nodes-base/nodes/Hubspot/V2/HubspotV2.node.ts
Labels: n8n team, node/issue
