Repository n8n-io/n8n, pull requests merged in 2024-11, with the labels that each got.

#11490 fix: Show Pinned data in demo mode
  cypress/composables/ndv.ts
  cypress/composables/workflow.ts
  cypress/e2e/31-demo.cy.ts
  packages/editor-ui/src/stores/workflows.store.spec.ts
  packages/editor-ui/src/stores/workflows.store.ts
Labels: ui, n8n team

#11371 fix(editor): Add optional chaining to `currentWorkflow` in NodeSettings (no-changelog)
  packages/editor-ui/src/components/NodeSettings.vue
Labels: ui, n8n team

#11499 fix(editor): Add optional chaining to execution socket event (no-changelog)
  packages/editor-ui/src/composables/usePushConnection.ts
Labels: ui, n8n team

#11495 fix(core): Account for double quotes in instance base URL
  packages/cli/src/services/__tests__/url.service.test.ts
  packages/cli/src/services/url.service.ts
Labels: core, n8n team

#11498 refactor: Clean up hooks and fake doors (no-changelog)
  packages/editor-ui/src/Interface.ts
  packages/editor-ui/src/__tests__/init.test.ts
  packages/editor-ui/src/components/CredentialEdit/CredentialEdit.vue
  packages/editor-ui/src/components/FeatureComingSoon.vue
  packages/editor-ui/src/components/SettingsSidebar.vue
  packages/editor-ui/src/constants.ts
  packages/editor-ui/src/hooks/cloud.ts
  packages/editor-ui/src/hooks/register.ts
  packages/editor-ui/src/hooks/types.ts
  packages/editor-ui/src/hooks/utils/hooksAddFakeDoorFeatures.ts
  packages/editor-ui/src/hooks/utils/index.ts
  packages/editor-ui/src/init.ts
  packages/editor-ui/src/plugins/i18n/locales/en.json
  packages/editor-ui/src/router.ts
  packages/editor-ui/src/stores/ui.store.ts
  packages/editor-ui/src/views/SettingsFakeDoorView.vue
Labels: ui, n8n team

#11370 fix(editor): Add optional chaining to `nodeExecutionRunData` in node execution status (no-changelog)
  packages/editor-ui/src/components/Node.vue
Labels: ui, n8n team

#11467 fix(editor): When cloud users click on "How to update your n8n version" auto-login them before redirecting to the dashboard (no-changelog)
  packages/editor-ui/src/components/CredentialEdit/CredentialSharing.ee.vue
  packages/editor-ui/src/components/InviteUsersModal.vue
  packages/editor-ui/src/components/MainHeader/WorkflowDetails.vue
  packages/editor-ui/src/components/MainSidebar.vue
  packages/editor-ui/src/components/Projects/ProjectNavigation.test.ts
  packages/editor-ui/src/components/Projects/ProjectNavigation.vue
  packages/editor-ui/src/components/Projects/ProjectRoleUpgradeDialog.vue
  packages/editor-ui/src/components/UpdatesPanel.vue
  packages/editor-ui/src/components/WorkflowShareModal.ee.vue
  packages/editor-ui/src/components/banners/TrialBanner.vue
  packages/editor-ui/src/components/banners/TrialOverBanner.vue
  packages/editor-ui/src/components/executions/ExecutionsFilter.vue
  packages/editor-ui/src/composables/__tests__/usePageRedirectionHelper.test.ts
  packages/editor-ui/src/composables/useExecutionDebugging.ts
  packages/editor-ui/src/composables/usePageRedirectionHelper.ts
  packages/editor-ui/src/stores/__tests__/ui.test.ts
  packages/editor-ui/src/stores/cloudPlan.store.ts
  packages/editor-ui/src/stores/settings.store.ts
  packages/editor-ui/src/stores/ui.store.ts
  packages/editor-ui/src/stores/users.store.ts
  packages/editor-ui/src/views/SettingsApiView.vue
  packages/editor-ui/src/views/SettingsExternalSecrets.vue
  packages/editor-ui/src/views/SettingsLdapView.vue
  packages/editor-ui/src/views/SettingsLogStreamingView.vue
  packages/editor-ui/src/views/SettingsSourceControl.vue
  packages/editor-ui/src/views/SettingsSso.test.ts
  packages/editor-ui/src/views/SettingsSso.vue
  packages/editor-ui/src/views/SettingsUsageAndPlan.vue
  packages/editor-ui/src/views/SettingsUsersView.test.ts
  packages/editor-ui/src/views/SettingsUsersView.vue
  packages/editor-ui/src/views/VariablesView.vue
  packages/editor-ui/src/views/WorkerView.vue
  packages/editor-ui/src/views/WorkflowHistory.vue
Labels: ui, n8n team

#11501 refactor(editor): Migrate `ParameterOptions` to composition API (no-changelog)
  packages/editor-ui/src/components/AssignmentCollection/AssignmentCollection.vue
  packages/editor-ui/src/components/ParameterOptions.test.ts
  packages/editor-ui/src/components/ParameterOptions.vue
  packages/editor-ui/src/components/ResourceMapper/MappingFields.vue
  packages/editor-ui/src/components/ResourceMapper/MatchingColumnsSelect.vue
Labels: ui, n8n team

#11125 fix(Edit Image Node): Fix Text operation by setting Arial as default font
  packages/nodes-base/nodes/EditImage/EditImage.node.ts
Labels: node/improvement, n8n team, tests-needed

#11507 refactor(core): Port `pruning` config
  packages/@n8n/config/src/configs/pruning.config.ts
  packages/@n8n/config/src/index.ts
  packages/@n8n/config/test/config.test.ts
  packages/cli/src/config/schema.ts
  packages/cli/src/databases/repositories/execution.repository.ts
  packages/cli/src/events/relays/telemetry.event-relay.ts
  packages/cli/src/services/frontend.service.ts
  packages/cli/src/services/pruning.service.ts
  packages/cli/test/integration/pruning.service.test.ts
Labels: core, n8n team

#11449 refactor(core): Extract poll context out of NodeExecutionFunctions (no-changelog)
  packages/cli/src/active-workflow-manager.ts
  packages/core/package.json
  packages/core/src/NodeExecuteFunctions.ts
  packages/core/src/index.ts
  packages/core/src/node-execution-context/__tests__/base-context.test.ts
  packages/core/src/node-execution-context/__tests__/poll-context.test.ts
  packages/core/src/node-execution-context/helpers/__tests__/binary-helpers.test.ts
  packages/core/src/node-execution-context/helpers/__tests__/scheduling-helpers.test.ts
  packages/core/src/node-execution-context/helpers/binary-helpers.ts
  packages/core/src/node-execution-context/helpers/request-helpers.ts
  packages/core/src/node-execution-context/helpers/scheduling-helpers.ts
  packages/core/src/node-execution-context/index.ts
  packages/core/src/node-execution-context/node-execution-context.ts
  packages/core/src/node-execution-context/poll-context.ts
  packages/nodes-base/test/nodes/TriggerHelpers.ts
  packages/workflow/src/Interfaces.ts
Labels: node/improvement, core, n8n team

#11487 feat: Only send needed data to task runner (no-changelog)
  packages/@n8n/task-runner/package.json
  packages/@n8n/task-runner/src/js-task-runner/__tests__/js-task-runner.test.ts
  packages/@n8n/task-runner/src/js-task-runner/__tests__/test-data.ts
  packages/@n8n/task-runner/src/js-task-runner/built-ins-parser/__tests__/built-ins-parser-state.test.ts
  packages/@n8n/task-runner/src/js-task-runner/built-ins-parser/__tests__/built-ins-parser.test.ts
  packages/@n8n/task-runner/src/js-task-runner/built-ins-parser/acorn-helpers.ts
  packages/@n8n/task-runner/src/js-task-runner/built-ins-parser/built-ins-parser-state.ts
  packages/@n8n/task-runner/src/js-task-runner/built-ins-parser/built-ins-parser.ts
  packages/@n8n/task-runner/src/js-task-runner/js-task-runner.ts
  packages/@n8n/task-runner/src/runner-types.ts
  packages/@n8n/task-runner/src/task-runner.ts
  packages/cli/src/runners/__tests__/task-broker.test.ts
  packages/cli/src/runners/__tests__/task-runner-process.test.ts
  packages/cli/src/runners/runner-types.ts
  packages/cli/src/runners/task-broker.service.ts
  packages/cli/src/runners/task-managers/__tests__/data-request-response-builder.test.ts
  packages/cli/src/runners/task-managers/data-request-response-builder.ts
  packages/cli/src/runners/task-managers/task-manager.ts
  packages/cli/src/runners/task-runner-process.ts
  packages/workflow/src/WorkflowDataProxy.ts
  packages/workflow/test/WorkflowDataProxy.test.ts
  packages/workflow/test/fixtures/WorkflowDataProxy/partial_data_run.json
  packages/workflow/test/fixtures/WorkflowDataProxy/partial_data_workflow.json
  pnpm-lock.yaml
Labels: core, n8n team

#11455 refactor(core): Extract webhook context out of NodeExecutionFunctions (no-changelog)
  packages/core/src/NodeExecuteFunctions.ts
  packages/core/src/node-execution-context/__tests__/webhook-context.test.ts
  packages/core/src/node-execution-context/index.ts
  packages/core/src/node-execution-context/webhook-context.ts
Labels: core, n8n team

#11529 fix(core): Use the correct docs URL for regular nodes when used as tools
  packages/workflow/src/NodeHelpers.ts
  packages/workflow/test/NodeHelpers.test.ts
Labels: core, n8n team

#11502 fix(core): Don't send a `executionFinished` event to the browser with no run data if the execution has already been cleaned up
  packages/cli/src/__tests__/workflow-runner.test.ts
  packages/cli/src/workflow-runner.ts
  packages/core/src/WorkflowExecute.ts
Labels: core, n8n team, release/backport

#11530 fix(editor): Respect user's dark-mode preference even before the application is loaded (no-changelog)
  packages/editor-ui/index.html
Labels: ui, n8n team

#11526 refactor(editor): ResourceListLayout to script setup
  packages/editor-ui/src/components/layouts/ResourcesListLayout.vue
  packages/editor-ui/src/views/CredentialsView.vue
  packages/editor-ui/src/views/WorkflowsView.vue
Labels: ui, n8n team

#11534 feat(editor): Update panning and selection keybindings on new canvas
  packages/editor-ui/package.json
  packages/editor-ui/src/components/canvas/Canvas.spec.ts
  packages/editor-ui/src/components/canvas/Canvas.vue
  pnpm-lock.yaml
Labels: ui, n8n team

#11509 refactor(editor): Migrate small components to composition API
  packages/editor-ui/src/components/ContactPromptModal.vue
  packages/editor-ui/src/components/IntersectionObserved.vue
  packages/editor-ui/src/components/IntersectionObserver.vue
  packages/editor-ui/src/components/Logo.vue
  packages/editor-ui/src/components/ModalDrawer.vue
  packages/editor-ui/src/components/ModalRoot.vue
  packages/editor-ui/src/components/Modals.vue
  packages/editor-ui/src/components/NodeList.vue
  packages/editor-ui/src/components/PanelDragButton.vue
  packages/editor-ui/src/components/ParameterIssues.vue
  packages/editor-ui/src/components/TemplateDetails.vue
  packages/editor-ui/src/components/WorkerList.ee.vue
Labels: ui, n8n team

#11458 fix(core): Do not delete waiting executions when saving of successful executions is disabled
  packages/cli/src/workflow-execute-additional-data.ts
Labels: core, n8n team, tests-needed

#11536 ci: Start collecting code-coverage on every PR (no-changelog)
  .github/workflows/ci-pull-requests.yml
Labels: n8n team

#11460 chore: Update @langchain/* packages to latest versions (no-changelog)
  package.json
  packages/@n8n/nodes-langchain/package.json
  patches/@langchain__core@0.3.3.patch
  pnpm-lock.yaml
  pnpm-workspace.yaml
Labels: n8n team

#11537 refactor(core): Extract hook context out of NodeExecutionFunctions (no-changelog)
  packages/core/src/NodeExecuteFunctions.ts
  packages/core/src/node-execution-context/__tests__/hook-context.test.ts
  packages/core/src/node-execution-context/hook-context.ts
  packages/core/src/node-execution-context/index.ts
  packages/core/src/node-execution-context/webhook-context.ts
  packages/workflow/src/Interfaces.ts
Labels: core, n8n team

#11535 fix(core): Save exeution progress for waiting executions, even when progress saving is disabled
  packages/cli/src/execution-lifecycle-hooks/__tests__/save-execution-progress.test.ts
  packages/cli/src/execution-lifecycle-hooks/save-execution-progress.ts
Labels: core, n8n team

#11542 chore(core): Change NodeOperationError default level to `warning` (no-changelog)
  packages/workflow/src/errors/node-operation.error.ts
Labels: core, n8n team

#11497 refactor(editor): Migrate components to composition API
  packages/editor-ui/src/components/CommunityPackageCard.vue
  packages/editor-ui/src/components/InputPanel.vue
  packages/editor-ui/src/components/InviteUsersModal.vue
  packages/editor-ui/src/components/NodeIcon.vue
  packages/editor-ui/src/components/OutputPanel.vue
  packages/editor-ui/src/components/RunData.vue
  packages/editor-ui/src/components/RunDataJson.vue
  packages/editor-ui/src/components/RunDataJsonActions.vue
  packages/editor-ui/src/components/SettingsLogStreaming/EventDestinationCard.ee.vue
  packages/editor-ui/src/components/TemplateCard.vue
  packages/editor-ui/src/components/TemplateFilters.vue
  packages/editor-ui/src/components/TemplatesInfoCard.vue
  packages/editor-ui/src/plugins/i18n/locales/en.json
  packages/editor-ui/src/views/SettingsApiView.vue
  packages/editor-ui/src/views/SettingsLogStreamingView.vue
Labels: ui, n8n team

#11546 refactor(editor): Convert some smaller components to composition api (no-changelog)
  packages/editor-ui/src/components/EnterpriseEdition.ee.vue
  packages/editor-ui/src/components/PushConnectionTracker.vue
  packages/editor-ui/src/components/forms/ResourceFiltersDropdown.vue
Labels: ui, n8n team

#11552 refactor: Move runner types to runner package
  packages/@n8n/task-runner/package.json
  packages/@n8n/task-runner/src/index.ts
  packages/@n8n/task-runner/src/js-task-runner/built-ins-parser/built-ins-parser-state.ts
  packages/@n8n/task-runner/src/message-types.ts
  packages/@n8n/task-runner/src/runner-types.ts
  packages/@n8n/task-runner/src/task-runner.ts
  packages/cli/src/runners/__tests__/task-broker.test.ts
  packages/cli/src/runners/runner-types.ts
  packages/cli/src/runners/runner-ws-server.ts
  packages/cli/src/runners/task-broker.service.ts
  packages/cli/src/runners/task-managers/__tests__/data-request-response-builder.test.ts
  packages/cli/src/runners/task-managers/data-request-response-builder.ts
  packages/cli/src/runners/task-managers/local-task-manager.ts
  packages/cli/src/runners/task-managers/task-manager.ts
  packages/cli/src/runners/task-runner-process.ts
  packages/cli/test/integration/runners/task-runner-module.internal.test.ts
Labels: core, n8n team

#11553 test: Skip flaky 39-projects e2e tests (no-changelog)
  cypress/e2e/39-projects.cy.ts
Labels: n8n team

#11551 feat(Anthropic Chat Model Node): Add support for Haiku 3.5
  packages/@n8n/nodes-langchain/nodes/llms/LMChatAnthropic/LmChatAnthropic.node.ts
Labels: n8n team

#11500 fix(editor): Add optional chaining to error handler (no-changelog)
  packages/editor-ui/src/utils/apiUtils.ts
Labels: ui, n8n team

#11554 chore(editor): Delete some of the unused code (no-changelog)
  packages/editor-ui/src/components/AnnotationTagsContainer.ee.vue
  packages/editor-ui/src/components/RBAC.test.ts
  packages/editor-ui/src/components/RBAC.vue
  packages/editor-ui/src/components/canvas/elements/nodes/render-types/CanvasNodeStickyNote.vue
  packages/editor-ui/src/plugins/components.ts
Labels: ui, n8n team

#11549 fix: Toast not aligned to the bottom when AI assistant disable
  packages/editor-ui/src/composables/useToast.ts
Labels: ui, n8n team

#11548 fix(editor): Do not show success message if there is an error saving credentials (no-changelog)
  packages/editor-ui/src/components/CredentialEdit/CredentialEdit.vue
Labels: ui, n8n team

#11556 feat(Convert to File Node): Add delimiter convert to csv
  packages/nodes-base/nodes/Files/ConvertToFile/actions/spreadsheet.operation.ts
  packages/nodes-base/nodes/Files/ConvertToFile/test/toText.workflow.json
  packages/nodes-base/utils/__tests__/binary.test.ts
  packages/nodes-base/utils/binary.ts
Labels: node/improvement, n8n team

#11557 feat: Upload sourcemaps to Sentry on release (no-changelog)
  .github/workflows/release-publish.yml
  package.json
  packages/editor-ui/package.json
  packages/editor-ui/vite.config.mts
  patches/@sentry__cli@2.36.2.patch
  pnpm-lock.yaml
Labels: n8n team

#11558 fix(editor): Fix emitting `n8nReady` notification via `postmessage` on new canvas
  packages/editor-ui/src/views/NodeView.v2.vue
Labels: ui, n8n team

#11562 fix(editor): Do not overwrite the webhookId in the new canvas
  packages/editor-ui/src/Interface.ts
  packages/editor-ui/src/composables/useCanvasOperations.test.ts
  packages/editor-ui/src/composables/useCanvasOperations.ts
Labels: ui, n8n team

#11538 fix(editor): Fix run index input for RunData view in sub-nodes
  cypress/e2e/30-langchain.cy.ts
  cypress/fixtures/In_memory_vector_store_fake_embeddings.json
  cypress/utils/executions.ts
  packages/editor-ui/src/components/InputPanel.vue
  packages/editor-ui/src/components/NodeDetailsView.vue
  packages/editor-ui/src/components/RunDataAi/RunDataAi.vue
Labels: ui, n8n team

#11563 fix(editor): Ensure Enter key on Cancel button correctly cancels node rename
  packages/editor-ui/src/components/NodeTitle.test.ts
  packages/editor-ui/src/components/NodeTitle.vue
Labels: ui, n8n team

#11462 feat: Add Rapid7 InsightVm credentials
  packages/nodes-base/credentials/Rapid7InsightVmApi.credentials.ts
  packages/nodes-base/credentials/icons/Rapid7InsightVm.svg
  packages/nodes-base/package.json
Labels: community, in linear

#11567 test(core): Expand test coverage for pruning
  packages/@n8n/config/src/configs/logging.config.ts
  packages/cli/src/commands/start.ts
  packages/cli/src/databases/repositories/execution.repository.ts
  packages/cli/src/services/pruning/__tests__/pruning.service.test.ts
  packages/cli/src/services/pruning/pruning.service.ts
  packages/cli/test/integration/pruning.service.test.ts
Labels: core, n8n team

#11566 refactor(editor): Convert TagsView to composition API (no-changelog)
  packages/editor-ui/src/components/TagsManager/TagsView/TagsView.vue
Labels: ui, n8n team

#11568 refactor(editor): Convert MultipleParameter to composition API (no-changelog)
  packages/editor-ui/src/components/MultipleParameter.test.ts
  packages/editor-ui/src/components/MultipleParameter.vue
  packages/editor-ui/src/components/__snapshots__/MultipleParameter.test.ts.snap
Labels: ui, n8n team

#11280 feat(AI Transform Node): UX improvements
  packages/design-system/src/components/N8nInput/Input.vue
  packages/editor-ui/src/components/ButtonParameter.test.ts
  packages/editor-ui/src/components/ButtonParameter/ButtonParameter.vue
  packages/editor-ui/src/components/ButtonParameter/utils.ts
  packages/editor-ui/src/components/NodeExecuteButton.vue
  packages/editor-ui/src/components/NodeSettings.vue
  packages/editor-ui/src/components/ParameterOptions.test.ts
  packages/editor-ui/src/components/ParameterOptions.vue
  packages/editor-ui/src/plugins/i18n/locales/en.json
  packages/nodes-base/nodes/AiTransform/AiTransform.node.ts
  packages/workflow/src/Constants.ts
Labels: node/improvement, n8n team

#11571 refactor(editor): Migrate `TemplatesSearchView.vue` to composition API
  packages/editor-ui/src/views/TemplatesSearchView.vue
Labels: ui, n8n team

#11543 refactor(core): Extract execute-single context out of NodeExecutionFunctions (no-changelog)
  packages/core/src/NodeExecuteFunctions.ts
  packages/core/src/node-execution-context/__tests__/execute-single-context.test.ts
  packages/core/src/node-execution-context/execute-single-context.ts
  packages/core/src/node-execution-context/index.ts
  packages/workflow/src/RoutingNode.ts
Labels: core, n8n team

#11496 fix(editor): Fix selected credential being overwritten in NDV
  cypress/e2e/2-credentials.cy.ts
  packages/editor-ui/src/components/NodeCredentials.vue
  packages/editor-ui/src/composables/useCanvasOperations.test.ts
  packages/editor-ui/src/composables/useCanvasOperations.ts
Labels: ui, n8n team

#11579 fix(editor): Keep workflow pristine after load on new canvas
  packages/editor-ui/src/composables/useCanvasOperations.test.ts
  packages/editor-ui/src/composables/useCanvasOperations.ts
Labels: ui, n8n team

#11585 fix: Rapid7 InsightVM copy tweaks and docs url (no-changelog)
  packages/nodes-base/credentials/Rapid7InsightVmApi.credentials.ts
Labels: node/improvement, n8n team

#11578 refactor(core): Minor improvements to pruning service
  packages/cli/src/constants.ts
  packages/cli/src/services/orchestration.service.ts
  packages/cli/src/services/pruning/__tests__/pruning.service.test.ts
  packages/cli/src/services/pruning/pruning.service.ts
  packages/cli/test/integration/pruning.service.test.ts
Labels: core, n8n team

#11559 perf(core): Load node types on demand on runners (no-changelog)
  packages/@n8n/task-runner/src/__tests__/node-types.test.ts
  packages/@n8n/task-runner/src/js-task-runner/js-task-runner.ts
  packages/@n8n/task-runner/src/message-types.ts
  packages/@n8n/task-runner/src/node-types.ts
  packages/@n8n/task-runner/src/runner-types.ts
  packages/@n8n/task-runner/src/task-runner.ts
  packages/cli/src/node-types.ts
  packages/cli/src/runners/__tests__/task-broker.test.ts
  packages/cli/src/runners/runner-ws-server.ts
  packages/cli/src/runners/task-broker.service.ts
  packages/cli/src/runners/task-managers/local-task-manager.ts
  packages/cli/src/runners/task-managers/task-manager.ts
  packages/cli/src/runners/task-runner-module.ts
Labels: core, n8n team

#11590 fix(core): Include `projectId` in range query middleware
  packages/cli/src/executions/__tests__/parse-range-query.middleware.test.ts
  packages/cli/src/executions/execution.service.ts
Labels: core, n8n team

#11441 feat(Gmail Trigger Node): Add filter option to include drafts
  packages/nodes-base/nodes/Google/Gmail/GmailTrigger.node.ts
Labels: node/improvement, n8n team, tests-needed

#11505 chore: Create table and typeorm entity for test definitions (no-changelog)
  packages/cli/src/databases/dsl/table.ts
  packages/cli/src/databases/entities/index.ts
  packages/cli/src/databases/entities/test-definition.ts
  packages/cli/src/databases/migrations/common/1730386903556-CreateTestDefinitionTable.ts
  packages/cli/src/databases/migrations/mysqldb/index.ts
  packages/cli/src/databases/migrations/postgresdb/index.ts
  packages/cli/src/databases/migrations/sqlite/index.ts
  packages/cli/src/generic-helpers.ts
Labels: core, n8n team

#11580 refactor(editor): Migrate WorkflowSettings to setup script and composition API (no-changelog)
  packages/editor-ui/src/components/WorkflowSettings.vue
Labels: ui, n8n team

#11595 feat: Enable turbosnap on chromatic workflow (no-changelog)
  .github/workflows/chromatic.yml
Labels: n8n team

#11592 fix: Fix loading workflows with `null` connection value (no-changelog)
  packages/editor-ui/src/utils/canvasUtilsV2.test.ts
  packages/editor-ui/src/utils/canvasUtilsV2.ts
  packages/workflow/src/Workflow.ts
  packages/workflow/test/Workflow.test.ts
Labels: core, ui, n8n team

#11555 refactor(editor): Migrate FixedCollectionParameter to composition API
  packages/editor-ui/src/components/ExpressionEditModal.vue
  packages/editor-ui/src/components/FixedCollectionParameter.test.ts
  packages/editor-ui/src/components/FixedCollectionParameter.vue
  packages/editor-ui/src/components/MultipleParameter.vue
  packages/editor-ui/src/components/ParameterInput.vue
  packages/editor-ui/src/components/ParameterInputFull.vue
  packages/editor-ui/src/components/ParameterInputList.vue
Labels: ui, n8n team

#11589 fix(editor): Cross-platform build for @n8n/chat (no-changelog)
  package.json
  packages/@n8n/chat/package.json
  packages/editor-ui/package.json
  pnpm-lock.yaml
Labels: ui, n8n team

#11569 fix(Auto-fixing Output Parser Node): Only run retry chain on parsing errors
  packages/@n8n/nodes-langchain/nodes/agents/Agent/agents/ToolsAgent/execute.ts
  packages/@n8n/nodes-langchain/nodes/output_parser/OutputParserAutofixing/OutputParserAutofixing.node.ts
  packages/@n8n/nodes-langchain/nodes/output_parser/OutputParserAutofixing/prompt.ts
  packages/@n8n/nodes-langchain/nodes/output_parser/OutputParserAutofixing/test/OutputParserAutofixing.node.test.ts
  packages/@n8n/nodes-langchain/utils/output_parsers/N8nOutputFixingParser.ts
Labels: n8n team

#11601 ci: Checkout the repo before triggering the Sentry release creation (no-changelog)
  .github/workflows/release-publish.yml
Labels: n8n team

#11584 refactor(editor): Migrate `EventDestinationSettingsModal.ee.vue` to composition API (no-changelog)
  packages/editor-ui/src/components/SettingsLogStreaming/EventDestinationSettingsModal.ee.vue
Labels: ui, n8n team

#11452 fix(editor): Enable pinning main output with error and always allow unpinning
  packages/editor-ui/src/components/RunData.vue
  packages/editor-ui/src/composables/usePinnedData.test.ts
  packages/editor-ui/src/composables/usePinnedData.ts
Labels: ui, n8n team

#11573 fix(editor): Show only error title and 'Open errored node' button; hide 'Ask Assistant' in root for sub-node errors
  packages/editor-ui/src/components/Error/NodeErrorView.test.ts
  packages/editor-ui/src/components/Error/NodeErrorView.vue
  packages/editor-ui/src/plugins/i18n/locales/en.json
Labels: ui, n8n team

#11615 docs: Fix typo in Update action description for Google Storage
  packages/nodes-base/nodes/Google/CloudStorage/BucketDescription.ts
Labels: node/improvement, n8n team

#11616 fix(core): Revert all the context helpers changes
  packages/core/src/NodeExecuteFunctions.ts
  packages/core/src/node-execution-context/execute-single-context.ts
  packages/core/src/node-execution-context/helpers/__tests__/binary-helpers.test.ts
  packages/core/src/node-execution-context/helpers/__tests__/scheduling-helpers.test.ts
  packages/core/src/node-execution-context/helpers/__tests__/ssh-tunnel-helpers.test.ts
  packages/core/src/node-execution-context/helpers/binary-helpers.ts
  packages/core/src/node-execution-context/helpers/request-helpers.ts
  packages/core/src/node-execution-context/helpers/scheduling-helpers.ts
  packages/core/src/node-execution-context/helpers/ssh-tunnel-helpers.ts
  packages/core/src/node-execution-context/hook-context.ts
  packages/core/src/node-execution-context/load-options-context.ts
  packages/core/src/node-execution-context/poll-context.ts
  packages/core/src/node-execution-context/trigger-context.ts
  packages/core/src/node-execution-context/webhook-context.ts
Labels: core, n8n team, release/backport

#11604 feat(Oura Node): Update node for v2 api
  packages/nodes-base/credentials/OuraApi.credentials.ts
  packages/nodes-base/nodes/Oura/GenericFunctions.ts
  packages/nodes-base/nodes/Oura/Oura.node.ts
  packages/nodes-base/nodes/Oura/test/apiResponses.ts
  packages/nodes-base/nodes/Oura/test/oura.node.test.ts
  packages/nodes-base/nodes/Oura/test/oura_test_workflow.json
Labels: node/improvement, n8n team

#11621 refactor: Rename disabled to enabled in runner config
  packages/@n8n/config/src/configs/runners.config.ts
  packages/@n8n/config/test/config.test.ts
  packages/cli/src/commands/start.ts
  packages/cli/src/commands/worker.ts
  packages/cli/src/runners/__tests__/task-runner-process.test.ts
  packages/cli/src/runners/task-runner-module.ts
  packages/cli/test/integration/commands/worker.cmd.test.ts
  packages/cli/test/integration/runners/task-runner-module.external.test.ts
  packages/cli/test/integration/runners/task-runner-module.internal.test.ts
  packages/cli/test/integration/runners/task-runner-process.test.ts
  packages/nodes-base/nodes/Code/Code.node.ts
Labels: node/improvement, core, n8n team

#11605 refactor(editor): Migrate `WorkflowShareModal.ee.vue` to composition API
  packages/editor-ui/src/components/WorkflowShareModal.ee.vue
Labels: ui, n8n team

#11608 refactor(editor): Migrate `TriggerPanel.vue` to composition API
  packages/editor-ui/src/components/TriggerPanel.vue
Labels: ui, n8n team

#11533 fix(core): Use cached value in retrieval of personal project owner
  packages/cli/src/services/__tests__/ownership.service.test.ts
  packages/cli/src/services/ownership.service.ts
  packages/cli/src/subworkflows/subworkflow-policy-checker.service.ts
Labels: core, n8n team

#11560 feat(AI Transform Node): Show warning for binary data
  packages/nodes-base/nodes/AiTransform/AiTransform.node.ts
Labels: node/improvement, n8n team

#11600 fix(core): Set the authentication methad to `email` during startup if the SAML configuration in the database has been corrupted
  packages/cli/src/sso/saml/__tests__/saml.service.ee.test.ts
  packages/cli/src/sso/saml/errors/invalid-saml-metadata.error.ts
  packages/cli/src/sso/saml/saml.service.ee.ts
  packages/cli/src/sso/sso-helpers.ts
Labels: core, n8n team

#11624 fix(editor): Add stickies to node insert position conflict check allowlist
  packages/editor-ui/src/constants.ts
  packages/editor-ui/src/utils/nodeViewUtils.test.ts
  packages/editor-ui/src/utils/nodeViewUtils.ts
Labels: ui, n8n team

#11545 refactor(editor): RunData components to composition API (no-changelog)
  packages/design-system/src/components/N8nRadioButtons/RadioButtons.vue
  packages/design-system/src/components/N8nTabs/Tabs.vue
  packages/design-system/src/components/N8nTree/Tree.stories.ts
  packages/design-system/src/components/N8nTree/Tree.vue
  packages/editor-ui/src/Interface.ts
  packages/editor-ui/src/components/InputPanel.vue
  packages/editor-ui/src/components/NodeDetailsView.test.ts
  packages/editor-ui/src/components/NodeDetailsView.vue
  packages/editor-ui/src/components/OutputPanel.vue
  packages/editor-ui/src/components/RunData.test.ts
  packages/editor-ui/src/components/RunData.vue
  packages/editor-ui/src/components/RunDataPinButton.vue
  packages/editor-ui/src/components/RunDataTable.vue
Labels: ui, n8n team

#11532 fix(editor): Prevent NodeCreator from swallowing AskAssistant enter event
  cypress/e2e/45-ai-assistant.cy.ts
  packages/design-system/src/components/AskAssistantChat/AskAssistantChat.vue
  packages/design-system/src/components/AskAssistantChat/__snapshots__/AskAssistantChat.test.ts.snap
  packages/editor-ui/src/components/Node/NodeCreator/composables/useKeyboardNavigation.ts
  packages/editor-ui/src/components/ParameterInput.vue
  packages/editor-ui/src/components/RunData.vue
  packages/editor-ui/src/components/TextEdit.vue
  packages/editor-ui/src/components/WorkflowLMChat/WorkflowLMChat.vue
  packages/editor-ui/src/components/WorkflowSettings.vue
  packages/editor-ui/src/composables/useClipboard.ts
  packages/editor-ui/src/composables/useKeybindings.ts
  packages/editor-ui/src/views/NodeView.vue
Labels: ui, n8n team

#11561 fix(editor): Adjust Scrollbar Width of RunData Header Row
  packages/editor-ui/src/components/RunData.vue
Labels: ui, n8n team

#11614 fix(editor): Cap NDV Output View Tab Index to prevent rare edge case
  packages/editor-ui/src/components/RunData.vue
Labels: ui, n8n team

#11627 perf(core): Remove unneeded execution data from runner data response (no-changelog)
  packages/cli/src/runners/task-managers/__tests__/data-request-response-builder.test.ts
  packages/cli/src/runners/task-managers/__tests__/data-request-response-stripper.test.ts
  packages/cli/src/runners/task-managers/data-request-response-builder.ts
  packages/cli/src/runners/task-managers/data-request-response-stripper.ts
Labels: core, n8n team

#11633 fix(core): Ensure task runner server closes websocket connection correctly
  packages/cli/src/runners/__tests__/task-runner-server.test.ts
  packages/cli/src/runners/task-runner-server.ts
Labels: core, n8n team

#11418 fix(core): Improve model sub-nodes error handling
  packages/@n8n/nodes-langchain/nodes/llms/LMChatAnthropic/LmChatAnthropic.node.ts
  packages/@n8n/nodes-langchain/nodes/llms/LMChatOllama/LmChatOllama.node.ts
  packages/@n8n/nodes-langchain/nodes/llms/LMChatOpenAi/LmChatOpenAi.node.ts
  packages/@n8n/nodes-langchain/nodes/llms/LMCohere/LmCohere.node.ts
  packages/@n8n/nodes-langchain/nodes/llms/LMOllama/LmOllama.node.ts
  packages/@n8n/nodes-langchain/nodes/llms/LMOpenAi/LmOpenAi.node.ts
  packages/@n8n/nodes-langchain/nodes/llms/LMOpenHuggingFaceInference/LmOpenHuggingFaceInference.node.ts
  packages/@n8n/nodes-langchain/nodes/llms/LmChatAwsBedrock/LmChatAwsBedrock.node.ts
  packages/@n8n/nodes-langchain/nodes/llms/LmChatAzureOpenAi/LmChatAzureOpenAi.node.ts
  packages/@n8n/nodes-langchain/nodes/llms/LmChatGoogleGemini/LmChatGoogleGemini.node.ts
  packages/@n8n/nodes-langchain/nodes/llms/LmChatGoogleVertex/LmChatGoogleVertex.node.ts
  packages/@n8n/nodes-langchain/nodes/llms/LmChatGroq/LmChatGroq.node.ts
  packages/@n8n/nodes-langchain/nodes/llms/LmChatMistralCloud/LmChatMistralCloud.node.ts
  packages/@n8n/nodes-langchain/nodes/llms/N8nLlmTracing.ts
  packages/@n8n/nodes-langchain/nodes/llms/n8nDefaultFailedAttemptHandler.test.ts
  packages/@n8n/nodes-langchain/nodes/llms/n8nDefaultFailedAttemptHandler.ts
  packages/@n8n/nodes-langchain/nodes/llms/n8nLlmFailedAttemptHandler.test.ts
  packages/@n8n/nodes-langchain/nodes/llms/n8nLlmFailedAttemptHandler.ts
  packages/@n8n/nodes-langchain/nodes/vendors/OpenAi/helpers/error-handling.ts
  packages/@n8n/nodes-langchain/utils/logWrapper.ts
  packages/editor-ui/src/composables/usePushConnection.ts
  packages/editor-ui/src/utils/expressions.ts
  packages/workflow/src/errors/expression.error.ts
  packages/workflow/src/errors/node-api.error.ts
Labels: core, ui, n8n team

#11650 chore: Update PR template with examples to automatically close Github Issues (no-changelog)
  .github/pull_request_template.md
Labels: n8n team

#11641 refactor(editor): Migrate `templates.store` to composition API
  packages/editor-ui/src/components/Node/NodeCreator/viewsData.ts
  packages/editor-ui/src/stores/templates.store.ts
  packages/editor-ui/src/views/TemplatesCollectionView.vue
Labels: ui, n8n team

#11574 refactor(editor): Migrate `ndv.store` to composition API
  packages/editor-ui/src/Interface.ts
  packages/editor-ui/src/components/InlineExpressionEditor/InlineExpressionTip.test.ts
  packages/editor-ui/src/components/InlineExpressionEditor/InlineExpressionTip.vue
  packages/editor-ui/src/components/NDVDraggablePanels.vue
  packages/editor-ui/src/components/NodeExecuteButton.vue
  packages/editor-ui/src/components/OutputPanel.vue
  packages/editor-ui/src/components/ParameterInput.test.ts
  packages/editor-ui/src/components/ParameterInput.vue
  packages/editor-ui/src/components/RunData.vue
  packages/editor-ui/src/stores/ndv.store.ts
Labels: ui, n8n team

#11630 fix(Supabase Node): Reset query parameters in get many operation
  packages/nodes-base/nodes/Supabase/Supabase.node.ts
Labels: n8n team, node/issue

#11632 fix(editor): Fix default workflow settings
  packages/editor-ui/src/Interface.ts
  packages/editor-ui/src/__tests__/defaults.ts
  packages/editor-ui/src/components/WorkflowSettings.test.ts
  packages/editor-ui/src/components/WorkflowSettings.vue
Labels: ui, n8n team, release/backport

#11582 fix(AI Agent Node): Throw better errors for non-tool agents when using structured tools
  packages/@n8n/nodes-langchain/nodes/agents/Agent/agents/ConversationalAgent/execute.ts
  packages/@n8n/nodes-langchain/nodes/agents/Agent/agents/PlanAndExecuteAgent/execute.ts
  packages/@n8n/nodes-langchain/nodes/agents/Agent/agents/ReActAgent/execute.ts
  packages/@n8n/nodes-langchain/nodes/agents/Agent/agents/utils.ts
  packages/@n8n/nodes-langchain/nodes/agents/Agent/test/utils.test.ts
  packages/workflow/src/NodeHelpers.ts
  packages/workflow/src/WorkflowDataProxy.ts
Labels: core, n8n team

#11658 fix(core): Fix hot-reload that broke after chokidar upgrade (no-changelog)
  packages/cli/src/load-nodes-and-credentials.ts
Labels: core, n8n team

#11646 fix(core): Make task runner oom error message more user friendly (no-changelog)
  packages/cli/src/runners/errors/task-runner-oom-error.ts
Labels: core, n8n team

#11492 fix: Credentials save button is hidden unless you make changes to the
  packages/editor-ui/src/components/CredentialEdit/CredentialEdit.vue
  packages/editor-ui/src/components/CredentialEdit/__tests__/CredentialEdit.test.ts
Labels: ui, n8n team

#11635 fix(core): Handle websocket connection error more gracefully in task runners
  packages/@n8n/task-runner/src/task-runner.ts
Labels: n8n team

#11629 feat(editor): Improve workflow loading performance on new canvas
  packages/editor-ui/src/composables/useCanvasOperations.test.ts
  packages/editor-ui/src/composables/useCanvasOperations.ts
  packages/editor-ui/src/stores/workflows.store.ts
  packages/editor-ui/src/views/NodeView.v2.vue
Labels: ui, n8n team

#11660 fix(core): Handle `item`, `items` and `$node` correctly in JS task runner (no-changelog)
  packages/@n8n/task-runner/src/js-task-runner/built-ins-parser/__tests__/built-ins-parser.test.ts
  packages/@n8n/task-runner/src/js-task-runner/built-ins-parser/built-ins-parser.ts
Labels: n8n team

#11576 fix(editor): Prevent deleting a sticky note while editing (no-changelog)
  packages/editor-ui/src/components/Sticky.vue
  packages/editor-ui/src/components/canvas/elements/nodes/render-types/CanvasNodeStickyNote.test.ts
Labels: ui, n8n team

#11675 fix(editor): Show node executing status shortly before switching to success on new canvas
  packages/editor-ui/src/components/canvas/elements/nodes/render-types/parts/CanvasNodeStatusIcons.vue
  packages/editor-ui/src/composables/useCanvasNode.ts
Labels: ui, n8n team

#11678 fix(core): Make push work for waiting webhooks
  packages/cli/src/webhooks/waiting-webhooks.ts
  packages/cli/src/workflow-execute-additional-data.ts
  packages/workflow/src/Interfaces.ts
Labels: core, n8n team

#11644 test(editor): Add unit test for inputpanel component
  packages/editor-ui/src/components/InputPanel.test.ts
  packages/editor-ui/src/components/InputPanel.vue
  packages/editor-ui/src/components/RunData.vue
  packages/editor-ui/src/components/__snapshots__/InputPanel.test.ts.snap
Labels: ui, n8n team

#11647 fix(editor): Fix scrolling in code edit modal
  packages/editor-ui/src/components/CodeNodeEditor/CodeNodeEditor.vue
Labels: ui, n8n team

#11645 fix(editor): Fix collapsing nested items in expression modal schema view
  packages/editor-ui/src/components/ExpressionEditModal.vue
  packages/editor-ui/src/components/RunDataSchema.vue
  packages/editor-ui/src/components/RunDataSchemaItem.vue
  packages/editor-ui/src/components/__snapshots__/RunDataSchema.test.ts.snap
Labels: ui, n8n team

#11682 refactor(core): Mark `finished` as deprecated
  packages/cli/src/databases/entities/execution-entity.ts
  packages/cli/src/interfaces.ts
  packages/workflow/src/Interfaces.ts
Labels: core, n8n team

#11649 fix(editor): Fix hiding SQL query output when trying to select
  packages/editor-ui/src/components/SQLEditor.test.ts
  packages/editor-ui/src/components/SqlEditor/SqlEditor.vue
Labels: ui, n8n team

#11653 fix(editor): Do not show hover tooltip when autocomplete is active
  packages/editor-ui/src/plugins/codemirror/tooltips/InfoBoxTooltip.ts
  packages/editor-ui/src/plugins/codemirror/tooltips/infoBoxTooltip.test.ts
Labels: ui, n8n team

#11677 fix(n8n Form Trigger Node): Checkboxes different sizes
  packages/cli/templates/form-trigger.handlebars
Labels: n8n team, node/issue

#11591 feat(core): Add internal API for test definitions (no-changelog)
  packages/cli/src/databases/entities/index.ts
  packages/cli/src/databases/entities/test-definition.ee.ts
  packages/cli/src/databases/repositories/test-definition.repository.ee.ts
  packages/cli/src/evaluation/test-definition.schema.ts
  packages/cli/src/evaluation/test-definition.service.ee.ts
  packages/cli/src/evaluation/test-definitions.controller.ee.ts
  packages/cli/src/evaluation/test-definitions.types.ee.ts
  packages/cli/src/generic-helpers.ts
  packages/cli/src/server.ts
  packages/cli/test/integration/evaluation/test-definitions.api.test.ts
  packages/cli/test/integration/shared/test-db.ts
  packages/cli/test/integration/shared/types.ts
  packages/cli/test/integration/shared/utils/test-server.ts
Labels: core, n8n team

#11491 feat(editor): Improve how we show default Agent prompt and Memory session parameters
  packages/@n8n/nodes-langchain/nodes/agents/Agent/Agent.node.ts
  packages/@n8n/nodes-langchain/nodes/agents/Agent/agents/SqlAgent/description.ts
  packages/@n8n/nodes-langchain/nodes/agents/Agent/agents/SqlAgent/execute.ts
  packages/@n8n/nodes-langchain/nodes/agents/OpenAiAssistant/OpenAiAssistant.node.ts
  packages/@n8n/nodes-langchain/nodes/chains/ChainLLM/ChainLlm.node.ts
  packages/@n8n/nodes-langchain/nodes/chains/ChainRetrievalQA/ChainRetrievalQa.node.ts
  packages/@n8n/nodes-langchain/nodes/memory/MemoryBufferWindow/MemoryBufferWindow.node.ts
  packages/@n8n/nodes-langchain/nodes/memory/MemoryMotorhead/MemoryMotorhead.node.ts
  packages/@n8n/nodes-langchain/nodes/memory/MemoryPostgresChat/MemoryPostgresChat.node.ts
  packages/@n8n/nodes-langchain/nodes/memory/MemoryRedisChat/MemoryRedisChat.node.ts
  packages/@n8n/nodes-langchain/nodes/memory/MemoryXata/MemoryXata.node.ts
  packages/@n8n/nodes-langchain/nodes/memory/MemoryZep/MemoryZep.node.ts
  packages/@n8n/nodes-langchain/nodes/memory/descriptions.ts
  packages/@n8n/nodes-langchain/nodes/vendors/OpenAi/actions/assistant/message.operation.ts
  packages/@n8n/nodes-langchain/nodes/vendors/OpenAi/actions/versionDescription.ts
  packages/@n8n/nodes-langchain/utils/descriptions.ts
  packages/editor-ui/src/components/ExpressionEditorModal/ExpressionEditorModalInput.vue
  packages/editor-ui/src/components/InlineExpressionEditor/InlineExpressionEditorInput.vue
  packages/editor-ui/src/components/InlineExpressionEditor/InlineExpressionEditorOutput.vue
  packages/editor-ui/src/components/ParameterInput.vue
  packages/editor-ui/src/components/ParameterInputFull.vue
  packages/editor-ui/src/components/ParameterInputList.vue
  packages/editor-ui/src/components/ParameterOptions.vue
  packages/editor-ui/src/composables/useNodeHelpers.ts
  packages/workflow/src/Interfaces.ts
  packages/workflow/src/NodeHelpers.ts
Labels: core, ui, n8n team

#11689 fix(Redis Chat Memory Node): Respect the SSL flag from the credential
  packages/@n8n/nodes-langchain/nodes/memory/MemoryRedisChat/MemoryRedisChat.node.ts
Labels: n8n team

#11668 fix(editor): Ignore all node run messages after a success message is sent (no-changelog)
  cypress/e2e/45-ai-assistant.cy.ts
  cypress/fixtures/aiAssistant/responses/node_execution_succeeded_response.json
  packages/editor-ui/src/stores/assistant.store.ts
Labels: ui, n8n team

#11693 fix(editor): Fix duplicate chat trigger
  packages/editor-ui/src/components/Node/NodeCreator/viewsData.ts
  packages/editor-ui/src/plugins/i18n/locales/en.json
Labels: ui, n8n team

#11700 fix(editor): Fix node type properties not updating regression (no-changelog)
  packages/editor-ui/src/__tests__/mocks.ts
  packages/editor-ui/src/composables/useCanvasOperations.test.ts
  packages/editor-ui/src/composables/useCanvasOperations.ts
Labels: ui, n8n team

#11541 refactor(editor): Move executions under projects
  cypress/composables/projects.ts
  cypress/e2e/39-projects.cy.ts
  packages/editor-ui/src/Interface.ts
  packages/editor-ui/src/__tests__/data/projects.ts
  packages/editor-ui/src/components/MainSidebar.vue
  packages/editor-ui/src/components/Projects/ProjectHeader.test.ts
  packages/editor-ui/src/components/Projects/ProjectHeader.vue
  packages/editor-ui/src/components/Projects/ProjectTabs.test.ts
  packages/editor-ui/src/components/Projects/ProjectTabs.vue
  packages/editor-ui/src/components/executions/global/GlobalExecutionsList.vue
  packages/editor-ui/src/components/executions/workflow/WorkflowExecutionsSidebar.vue
  packages/editor-ui/src/components/layouts/ResourceListHeader.test.ts
  packages/editor-ui/src/components/layouts/ResourceListHeader.vue
  packages/editor-ui/src/components/layouts/ResourcesListLayout.test.ts
  packages/editor-ui/src/components/layouts/ResourcesListLayout.vue
  packages/editor-ui/src/composables/useRunWorkflow.test.ts
  packages/editor-ui/src/constants.ts
  packages/editor-ui/src/plugins/i18n/locales/en.json
  packages/editor-ui/src/router.ts
  packages/editor-ui/src/routes/projects.routes.ts
  packages/editor-ui/src/stores/executions.store.ts
  packages/editor-ui/src/views/CredentialsView.vue
  packages/editor-ui/src/views/ExecutionsView.vue
  packages/editor-ui/src/views/ProjectSettings.vue
  packages/editor-ui/src/views/WorkflowsView.vue
Labels: ui, n8n team

#11698 fix(Google Drive Node): Fix file upload for streams
  packages/nodes-base/nodes/Google/Drive/test/v2/node/file/upload.test.ts
  packages/nodes-base/nodes/Google/Drive/test/v2/node/helpers.ts
  packages/nodes-base/nodes/Google/Drive/v2/actions/file/upload.operation.ts
  packages/nodes-base/nodes/Google/Drive/v2/helpers/utils.ts
Labels: node/improvement, n8n team

#11701 fix(In-Memory Vector Store Node): Fix displaying execution data of connected embedding nodes
  packages/@n8n/nodes-langchain/nodes/vector_store/VectorStoreInMemory/VectorStoreInMemory.node.ts
  packages/@n8n/nodes-langchain/nodes/vector_store/shared/MemoryVectorStoreManager.test.ts
  packages/@n8n/nodes-langchain/nodes/vector_store/shared/MemoryVectorStoreManager.ts
Labels: n8n team

#11671 fix(n8n Form Node): Trigger page stack in waiting if error in workflow
  packages/cli/src/response-helper.ts
  packages/cli/templates/form-trigger-409.handlebars
Labels: n8n team, node/issue, tests-needed

#11673 fix(n8n Form Node): Open form page if form trigger has pin data
  packages/editor-ui/src/composables/useRunWorkflow.ts
Labels: n8n team, node/issue

#11162 fix(Switch Node): Maintain output connections
  cypress/e2e/5-ndv.cy.ts
  packages/editor-ui/src/components/NodeSettings.vue
  packages/editor-ui/src/stores/workflows.store.ts
  packages/editor-ui/src/utils/nodeSettingsUtils.test.ts
  packages/editor-ui/src/utils/nodeSettingsUtils.ts
Labels: node/improvement, ui, n8n team, node/issue

#11674 fix(n8n Form Node): Find completion page
  packages/cli/src/webhooks/__tests__/waiting-forms.test.ts
  packages/cli/src/webhooks/waiting-forms.ts
Labels: n8n team, node/issue

#11712 fix(Notion Node): Safe access in simplifyProperty (no-changelog)
  packages/nodes-base/nodes/Notion/shared/GenericFunctions.ts
Labels: n8n team, node/issue

#11717 fix(editor): Fix canvasNodes reactivity in canvas chat (no-changelog)
  packages/editor-ui/src/components/CanvasChat/CanvasChat.vue
  packages/editor-ui/src/components/CanvasChat/composables/useChatTrigger.ts
Labels: ui, n8n team

#11692 fix(Facebook Lead Ads Trigger Node): Fix issue with optional fields
  packages/nodes-base/nodes/FacebookLeadAds/FacebookLeadAdsTrigger.node.ts
  packages/nodes-base/nodes/FacebookLeadAds/GenericFunctions.ts
Labels: node/improvement, n8n team, tests-needed

#11684 fix(core): Continue with error output reverse items in success branch
  packages/core/src/WorkflowExecute.ts
  packages/core/test/WorkflowExecute.test.ts
  packages/core/test/workflows/error_outputs.json
Labels: core, n8n team

#11702 fix(Google BigQuery Node): Add item index to insert error
  packages/nodes-base/nodes/Google/BigQuery/v2/actions/database/insert.operation.ts
Labels: node/improvement, n8n team

#11695 feat: Github star button in-app
  cypress/e2e/1-workflows.cy.ts
  cypress/e2e/17-workflow-tags.cy.ts
  cypress/e2e/19-execution.cy.ts
  cypress/e2e/20-workflow-executions.cy.ts
  cypress/e2e/34-template-credentials-setup.cy.ts
  cypress/e2e/45-ai-assistant.cy.ts
  cypress/e2e/5-ndv.cy.ts
  packages/editor-ui/package.json
  packages/editor-ui/src/components/MainHeader/MainHeader.vue
  pnpm-lock.yaml
Labels: ui, n8n team

#11726 docs: Update npm package README.md to put minimum version to v18 (no-changelog)
  packages/cli/README.md
Labels: core, n8n team

#11708 fix(editor): Improve formatting of expired trial error message
  .vscode/launch.json
  packages/editor-ui/src/composables/usePushConnection.test.ts
  packages/editor-ui/src/composables/usePushConnection.ts
  packages/editor-ui/src/composables/useToast.test.ts
Labels: ui, n8n team

#11736 fix(editor): Change Home label to Overview
  cypress/e2e/39-projects.cy.ts
  packages/editor-ui/src/components/Projects/ProjectHeader.test.ts
  packages/editor-ui/src/components/Projects/ProjectHeader.vue
  packages/editor-ui/src/components/Projects/ProjectNavigation.vue
  packages/editor-ui/src/plugins/i18n/locales/en.json
Labels: ui, n8n team

#11705 fix(editor): Fix callout component border issue (no-changelog)
  packages/design-system/src/components/N8nCallout/Callout.vue
  packages/editor-ui/src/components/banners/BaseBanner.vue
  packages/editor-ui/src/components/banners/__snapshots__/V1Banner.test.ts.snap
Labels: ui, n8n team

#11724 fix(core): Allow Azure's SAML metadata XML containing WS-Federation nodes to pass validation
  packages/cli/src/sso/saml/__tests__/saml-validator.test.ts
  packages/cli/src/sso/saml/__tests__/saml.service.ee.test.ts
  packages/cli/src/sso/saml/saml-validator.ts
  packages/cli/src/sso/saml/schema/metadata-exchange.xsd.ts
  packages/cli/src/sso/saml/schema/oasis-200401-wss-wssecurity-secext-1.0.xsd.ts
  packages/cli/src/sso/saml/schema/oasis-200401-wss-wssecurity-utility-1.0.xsd.ts
  packages/cli/src/sso/saml/schema/saml-schema-assertion-2.0.xsd.ts
  packages/cli/src/sso/saml/schema/saml-schema-metadata-2.0.xsd.ts
  packages/cli/src/sso/saml/schema/saml-schema-protocol-2.0.xsd.ts
  packages/cli/src/sso/saml/schema/ws-addr.xsd.ts
  packages/cli/src/sso/saml/schema/ws-authorization.xsd.ts
  packages/cli/src/sso/saml/schema/ws-federation.xsd.ts
  packages/cli/src/sso/saml/schema/ws-securitypolicy-1.2.xsd.ts
  packages/cli/src/sso/saml/schema/xenc-schema.xsd.ts
  packages/cli/src/sso/saml/schema/xml.xsd.ts
  packages/cli/src/sso/saml/schema/xmldsig-core-schema.xsd.ts
Labels: core, n8n team

#11691 chore: Add description field to test definition (no-changelog)
  packages/cli/src/databases/entities/test-definition.ee.ts
  packages/cli/src/databases/migrations/common/1731404028106-AddDescriptionToTestDefinition.ts
  packages/cli/src/databases/migrations/mysqldb/index.ts
  packages/cli/src/databases/migrations/postgresdb/index.ts
  packages/cli/src/databases/migrations/sqlite/1731404028106-AddDescriptionToTestDefinition.ts
  packages/cli/src/databases/migrations/sqlite/index.ts
  packages/cli/src/evaluation/test-definition.schema.ts
  packages/cli/src/evaluation/test-definition.service.ee.ts
  packages/cli/test/integration/evaluation/test-definitions.api.test.ts
Labels: core, n8n team

#11741 fix(YouTube Node): Issue in published before and after dates filters
  packages/nodes-base/nodes/Google/GenericFunctions.ts
  packages/nodes-base/nodes/Google/YouTube/YouTube.node.ts
  packages/nodes-base/nodes/Google/YouTube/test/GenericFunctions.test.ts
Labels: node/improvement, n8n team

#11710 fix(editor): Fix the issue with RMC Values to Send collection disappears
  packages/editor-ui/src/components/ResourceMapper/ResourceMapper.vue
Labels: ui, n8n team, tests-needed

#11703 refactor(editor): Stop cloning and serializing full execution data for `executionFinished` push message
  cypress/package.json
  cypress/support/index.ts
  cypress/utils/executions.ts
  packages/@n8n/api-types/src/push/execution.ts
  packages/cli/package.json
  packages/cli/src/workflow-execute-additional-data.ts
  packages/editor-ui/package.json
  packages/editor-ui/src/Interface.ts
  packages/editor-ui/src/composables/usePushConnection.test.ts
  packages/editor-ui/src/composables/usePushConnection.ts
  packages/editor-ui/src/composables/useRunWorkflow.ts
  packages/editor-ui/src/stores/workflows.store.test.ts
  packages/editor-ui/src/stores/workflows.store.ts
  packages/editor-ui/src/views/NodeView.vue
  pnpm-lock.yaml
  pnpm-workspace.yaml
Labels: core, ui, n8n team

#11742 chore: Migrate test definition PK to string nanoid (no-changelog)
  packages/cli/src/databases/entities/test-definition.ee.ts
  packages/cli/src/databases/migrations/mysqldb/1731582748663-MigrateTestDefinitionKeyToString.ts
  packages/cli/src/databases/migrations/mysqldb/index.ts
  packages/cli/src/databases/migrations/postgresdb/1731582748663-MigrateTestDefinitionKeyToString.ts
  packages/cli/src/databases/migrations/postgresdb/index.ts
  packages/cli/src/databases/migrations/sqlite/1731582748663-MigrateTestDefinitionKeyToString.ts
  packages/cli/src/databases/migrations/sqlite/index.ts
  packages/cli/src/databases/repositories/test-definition.repository.ee.ts
  packages/cli/src/evaluation/test-definition.service.ee.ts
  packages/cli/src/evaluation/test-definitions.controller.ee.ts
Labels: core, n8n team

#11746 test: Fix flaky tags tests (no-changelog)
  cypress/pages/workflow.ts
Labels: n8n team

#11747 ci: Hide the github button in e2e tests (no-changelog)
  cypress/e2e/1-workflows.cy.ts
  cypress/e2e/17-workflow-tags.cy.ts
  cypress/e2e/19-execution.cy.ts
  cypress/e2e/20-workflow-executions.cy.ts
  cypress/e2e/34-template-credentials-setup.cy.ts
  cypress/e2e/45-ai-assistant.cy.ts
  cypress/e2e/5-ndv.cy.ts
  packages/@n8n/api-types/src/frontend-settings.ts
  packages/cli/src/services/frontend.service.ts
  packages/editor-ui/src/__tests__/defaults.ts
  packages/editor-ui/src/components/MainHeader/MainHeader.vue
Labels: core, ui, n8n team

#11740 refactor(core): Remove deprecated `TIME` constant
  packages/cli/src/constants.ts
  packages/cli/src/scaling/multi-main-setup.ee.ts
  packages/cli/src/services/cache/cache.service.ts
  packages/cli/src/workflows/workflow-history/constants.ts
  packages/cli/src/workflows/workflow-history/workflow-history-manager.ee.ts
  packages/cli/test/integration/pruning.service.test.ts
Labels: core, n8n team

#11683 feat(core): Add sentry for task runner (no-changelog)
  docker/images/n8n/n8n-task-runners.json
  packages/@n8n/task-runner/package.json
  packages/@n8n/task-runner/src/__tests__/error-reporter.test.ts
  packages/@n8n/task-runner/src/config/main-config.ts
  packages/@n8n/task-runner/src/config/sentry-config.ts
  packages/@n8n/task-runner/src/error-reporter.ts
  packages/@n8n/task-runner/src/js-task-runner/__tests__/js-task-runner.test.ts
  packages/@n8n/task-runner/src/start.ts
  packages/cli/package.json
  packages/cli/src/runners/__tests__/task-runner-process.test.ts
  packages/cli/src/runners/task-runner-process.ts
  pnpm-lock.yaml
  pnpm-workspace.yaml
Labels: core, n8n team

#11744 chore(editor): Stop reporting `ResponseError: Unauthorized` error to Sentry (no-changelog)
  packages/editor-ui/src/plugins/sentry.ts
Labels: ui, n8n team

#11763 ci: Fix flaky 34-template-credentials-setup.cy.ts (no-changelog)
  cypress/e2e/34-template-credentials-setup.cy.ts
  cypress/fixtures/Ecommerce_starter_pack_template_collection.json
  cypress/fixtures/Test_Template_1.json
  cypress/fixtures/templates_search/sales_templates_search_response.json
Labels: n8n team

#11690 feat(core): Implement task timeouts and heartbeats for runners (no-changelog)
  packages/@n8n/config/src/configs/runners.config.ts
  packages/@n8n/config/test/config.test.ts
  packages/@n8n/task-runner/src/config/base-runner-config.ts
  packages/@n8n/task-runner/src/healthcheck-server.ts
  packages/@n8n/task-runner/src/start.ts
  packages/cli/src/runners/__tests__/task-broker.test.ts
  packages/cli/src/runners/__tests__/task-runner-process.test.ts
  packages/cli/src/runners/__tests__/task-runner-ws-server.test.ts
  packages/cli/src/runners/default-task-runner-disconnect-analyzer.ts
  packages/cli/src/runners/errors/task-runner-failed-heartbeat.error.ts
  packages/cli/src/runners/errors/task-runner-timeout.error.ts
  packages/cli/src/runners/internal-task-runner-disconnect-analyzer.ts
  packages/cli/src/runners/runner-lifecycle-events.ts
  packages/cli/src/runners/runner-types.ts
  packages/cli/src/runners/runner-ws-server.ts
  packages/cli/src/runners/task-broker.service.ts
  packages/cli/src/runners/task-runner-process.ts
  packages/cli/src/runners/task-runner-server.ts
Labels: core, n8n team

#11770 fix(Google Sheets Trigger Node): Fix issue with regex showing correct sheet as invalid
  packages/nodes-base/nodes/Google/Sheet/GoogleSheetsTrigger.node.ts
  packages/nodes-base/nodes/Google/Sheet/test/v2/utils/utils.test.ts
  packages/nodes-base/nodes/Google/Sheet/v2/actions/sheet/Sheet.resource.ts
  packages/nodes-base/nodes/Google/constants.ts
Labels: node/improvement, n8n team

#11750 feat(core): Improve handling of manual executions with wait nodes
  packages/@n8n/api-types/src/push/execution.ts
  packages/cli/src/execution-lifecycle-hooks/__tests__/save-execution-progress.test.ts
  packages/cli/src/execution-lifecycle-hooks/save-execution-progress.ts
  packages/cli/src/execution-lifecycle-hooks/to-save-settings.ts
  packages/cli/src/webhooks/webhook-helpers.ts
  packages/cli/src/workflow-execute-additional-data.ts
  packages/cli/templates/form-trigger.handlebars
  packages/core/src/WorkflowExecute.ts
  packages/editor-ui/src/components/InputPanel.vue
  packages/editor-ui/src/components/NodeExecuteButton.vue
  packages/editor-ui/src/components/OutputPanel.vue
  packages/editor-ui/src/components/RunData.vue
  packages/editor-ui/src/composables/usePushConnection.ts
  packages/editor-ui/src/composables/useRunWorkflow.test.ts
  packages/editor-ui/src/composables/useRunWorkflow.ts
  packages/editor-ui/src/stores/workflows.store.test.ts
  packages/editor-ui/src/stores/workflows.store.ts
  packages/editor-ui/src/utils/executionUtils.test.ts
  packages/editor-ui/src/utils/executionUtils.ts
  packages/editor-ui/src/views/NodeView.v2.vue
  packages/editor-ui/src/views/NodeView.vue
Labels: core, ui, n8n team

#11761 refactor(core): Port diagnostics config
  packages/@n8n/config/src/configs/diagnostics.config.ts
  packages/@n8n/config/src/index.ts
  packages/@n8n/config/test/config.test.ts
  packages/cli/src/config/schema.ts
  packages/cli/src/events/__tests__/telemetry-event-relay.test.ts
  packages/cli/src/events/relays/telemetry.event-relay.ts
  packages/cli/src/posthog/__tests__/posthog.test.ts
  packages/cli/src/posthog/index.ts
  packages/cli/src/security-audit/risk-reporters/instance-risk-reporter.ts
  packages/cli/src/services/__tests__/workflow-statistics.service.test.ts
  packages/cli/src/services/frontend.service.ts
  packages/cli/src/telemetry/__tests__/telemetry.test.ts
  packages/cli/src/telemetry/index.ts
  packages/cli/test/integration/security-audit/instance-risk-reporter.test.ts
Labels: core, n8n team

#11773 feat(Embeddings OpenAI Node, Embeddings Azure OpenAI Node): Add dimensions option
  packages/@n8n/nodes-langchain/nodes/embeddings/EmbeddingsAzureOpenAi/EmbeddingsAzureOpenAi.node.ts
  packages/@n8n/nodes-langchain/nodes/embeddings/EmbeddingsOpenAI/EmbeddingsOpenAi.node.ts
Labels: n8n team

#11679 feat(editor): Add selection navigation using the keyboard on new canvas
  packages/editor-ui/src/components/canvas/Canvas.test.ts
  packages/editor-ui/src/components/canvas/Canvas.vue
  packages/editor-ui/src/composables/useCanvasTraversal.test.ts
  packages/editor-ui/src/composables/useCanvasTraversal.ts
Labels: ui, n8n team

#11768 refactor(core): Make launcher auth easier to debug
  packages/cli/src/runners/errors/missing-auth-token.error.ts
  packages/cli/src/runners/task-runner-module.ts
  packages/cli/src/runners/task-runner-server.ts
  packages/cli/test/integration/runners/task-runner-module.external.test.ts
Labels: core, n8n team

#11756 fix(Anthropic Chat Model Node): Update credentials test endpoint
  packages/@n8n/nodes-langchain/credentials/AnthropicApi.credentials.ts
Labels: n8n team

#11784 feat(Embeddings Azure OpenAI Node, Azure OpenAI Chat Model Node): Add support for basePath url in Azure Open AI nodes
  packages/@n8n/nodes-langchain/credentials/AzureOpenAiApi.credentials.ts
  packages/@n8n/nodes-langchain/nodes/embeddings/EmbeddingsAzureOpenAi/EmbeddingsAzureOpenAi.node.ts
  packages/@n8n/nodes-langchain/nodes/llms/LmChatAzureOpenAi/LmChatAzureOpenAi.node.ts
Labels: n8n team

#11672 feat(editor): Add Info Note to NDV Output Panel if no existing Tools were used during Execution
  cypress/composables/ndv.ts
  cypress/e2e/30-langchain.cy.ts
  packages/editor-ui/src/components/OutputPanel.vue
  packages/editor-ui/src/components/RunData.vue
  packages/editor-ui/src/components/__snapshots__/InputPanel.test.ts.snap
  packages/editor-ui/src/plugins/i18n/locales/en.json
Labels: ui, n8n team

#11788 fix(editor): Fix reordered switch connections when copying nodes on new canvas
  packages/editor-ui/src/composables/useCanvasOperations.test.ts
  packages/editor-ui/src/composables/useCanvasOperations.ts
Labels: ui, n8n team
