Repository n8n-io/n8n, pull requests merged in 2024-05, with the labels that each got.

#9198 fix(Jira Trigger Node): Update credentials UI
  packages/editor-ui/src/components/NodeCredentials.vue
  packages/nodes-base/nodes/Jira/JiraTrigger.node.ts
  packages/workflow/src/Interfaces.ts
Labels: node/improvement, n8n team, node/issue

#9267 feat(Telegram Node): Disable page preview by default
  packages/nodes-base/nodes/Telegram/GenericFunctions.ts
  packages/nodes-base/nodes/Telegram/Telegram.node.ts
Labels: node/improvement, n8n team

#9272 fix: Sharing credentials and workflows with pending users
  packages/cli/src/credentials/credentials.service.ee.ts
  packages/cli/src/workflows/workflow.service.ee.ts
  packages/cli/test/integration/credentials.ee.test.ts
  packages/cli/test/integration/workflows/workflows.controller.ee.test.ts
Labels: core, n8n team

#9274 fix: Members not being able to test credentials with external secrets
  packages/cli/src/services/credentials-tester.service.ts
Labels: core, n8n team

#9268 fix: Source Control import creating project without specifying type
  packages/cli/src/environments/sourceControl/sourceControlImport.service.ee.ts
  packages/cli/test/integration/environments/source-control-import.service.test.ts
Labels: core, n8n team

#9269 feat(S3 Node): Add support for self signed SSL certificates
  packages/nodes-base/credentials/S3.credentials.ts
  packages/nodes-base/nodes/S3/GenericFunctions.ts
Labels: node/improvement, n8n team

#9241 feat(Postgres Node): Add option IS NOT NULL and hide value input fields
  packages/nodes-base/nodes/MySql/v2/actions/common.descriptions.ts
  packages/nodes-base/nodes/MySql/v2/helpers/utils.ts
  packages/nodes-base/nodes/Postgres/v2/actions/common.descriptions.ts
  packages/nodes-base/nodes/Postgres/v2/helpers/utils.ts
Labels: node/improvement, n8n team

#9255 fix(Google BigQuery Node): Better error messages, transform timestamps
  packages/nodes-base/nodes/Google/BigQuery/GoogleBigQuery.node.ts
  packages/nodes-base/nodes/Google/BigQuery/test/v2/utils/utils.test.ts
  packages/nodes-base/nodes/Google/BigQuery/v2/actions/database/executeQuery.operation.ts
  packages/nodes-base/nodes/Google/BigQuery/v2/actions/versionDescription.ts
  packages/nodes-base/nodes/Google/BigQuery/v2/helpers/utils.ts
Labels: node/improvement, n8n team

#8917 feat: Add Ask AI to HTTP Request Node
  packages/cli/package.json
  packages/cli/src/CurlConverterHelper.ts
  packages/cli/src/config/schema.ts
  packages/cli/src/constants.ts
  packages/cli/src/controllers/ai.controller.ts
  packages/cli/src/controllers/passwordReset.controller.ts
  packages/cli/src/requests.ts
  packages/cli/src/services/ai.service.ts
  packages/cli/src/services/ai/prompts/debugError.ts
  packages/cli/src/services/ai/prompts/generateCurl.ts
  packages/cli/src/services/ai/prompts/retrieveService.ts
  packages/cli/src/services/ai/providers/openai.ts
  packages/cli/src/services/ai/providers/unknown.ts
  packages/cli/src/services/ai/resources/README.md
  packages/cli/src/services/ai/resources/api-knowledgebase.json
  packages/cli/src/services/ai/schemas/generateCurl.ts
  packages/cli/src/services/ai/schemas/retrieveService.ts
  packages/cli/src/services/frontend.service.ts
  packages/cli/src/types/ai.types.ts
  packages/cli/test/unit/services/ai.service.test.ts
  packages/editor-ui/src/api/ai.ts
  packages/editor-ui/src/components/GenerateCurlModal.vue
  packages/editor-ui/src/components/ImportCurlModal.vue
  packages/editor-ui/src/components/ImportCurlParameter.vue
  packages/editor-ui/src/components/ImportParameter.vue
  packages/editor-ui/src/components/JsonEditor/JsonEditor.vue
  packages/editor-ui/src/components/Modals.vue
  packages/editor-ui/src/components/NodeSettings.vue
  packages/editor-ui/src/components/ParameterInputList.vue
  packages/editor-ui/src/composables/useImportCurlCommand.ts
  packages/editor-ui/src/constants.ts
  packages/editor-ui/src/event-bus/import-curl.ts
  packages/editor-ui/src/event-bus/index.ts
  packages/editor-ui/src/plugins/i18n/locales/en.json
  packages/editor-ui/src/stores/ai.store.spec.ts
  packages/editor-ui/src/stores/ai.store.ts
  packages/editor-ui/src/stores/ui.store.ts
  packages/workflow/src/Constants.ts
  packages/workflow/src/Interfaces.ts
  pnpm-lock.yaml
Labels: core, ui, n8n team

#9260 fix: Cast boolean values in filter parameter
  packages/workflow/src/NodeParameters/FilterParameter.ts
  packages/workflow/test/FilterParameter.test.ts
Labels: core, n8n team

#9266 feat(Redis Node): Add support for TLS
  packages/nodes-base/credentials/Redis.credentials.ts
  packages/nodes-base/nodes/Redis/test/Redis.node.test.ts
  packages/nodes-base/nodes/Redis/utils.ts
Labels: node/improvement, n8n team

#9278 fix(editor): RBAC FE fixes and UI/UX tweaks
  cypress/e2e/39-projects.cy.ts
  packages/editor-ui/src/components/layouts/ResourcesListLayout.vue
  packages/editor-ui/src/features/projects/components/ProjectDeleteDialog.vue
  packages/editor-ui/src/features/projects/components/ProjectNavigation.vue
  packages/editor-ui/src/features/projects/components/ProjectSettings.vue
  packages/editor-ui/src/features/projects/components/ProjectSharing.vue
  packages/editor-ui/src/plugins/i18n/locales/en.json
  packages/editor-ui/src/views/CredentialsView.vue
  packages/editor-ui/src/views/WorkflowsView.vue
Labels: ui, n8n team

#9249 refactor(editor): Migrate `pushConnection` mixin to composable and remove collaboration store side effects (no-changelog)
  packages/editor-ui/src/Interface.ts
  packages/editor-ui/src/components/MainHeader/CollaborationPane.vue
  packages/editor-ui/src/components/MainHeader/MainHeader.vue
  packages/editor-ui/src/components/WorkerList.ee.vue
  packages/editor-ui/src/composables/usePushConnection.spec.ts
  packages/editor-ui/src/composables/usePushConnection.ts
  packages/editor-ui/src/mixins/pushConnection.ts
  packages/editor-ui/src/stores/collaboration.store.ts
  packages/editor-ui/src/stores/pushConnection.store.ts
  packages/editor-ui/src/types/index.ts
  packages/editor-ui/src/types/pushConnection.ts
  packages/editor-ui/src/views/NodeView.vue
  packages/editor-ui/src/views/SettingsCommunityNodesView.vue
Labels: ui, n8n team

#9128 fix: Return scopes on more resource APIs
  packages/cli/src/credentials/credentials.controller.ts
  packages/cli/src/credentials/credentials.service.ts
  packages/cli/src/services/role.service.ts
  packages/cli/src/workflows/workflow.service.ts
  packages/cli/src/workflows/workflows.controller.ts
  packages/cli/test/integration/credentials.test.ts
  packages/cli/test/integration/workflows/workflows.controller.test.ts
Labels: core, n8n team

#9282 fix(n8n Form Trigger Node): Fix missing options when using respond to webhook
  packages/nodes-base/nodes/Form/v2/FormTriggerV2.node.ts
Labels: node/improvement, n8n team

#9301 fix(editor): Show MFA section to instance owner, even when external auth is enabled
  packages/editor-ui/src/views/SettingsPersonalView.vue
  packages/editor-ui/src/views/__tests__/SettingsPersonalView.test.ts
Labels: ui, n8n team

#9302 refactor(core): Use logger for `packages/cli` messages (no-changelog)
  packages/cli/src/AbstractServer.ts
  packages/cli/src/ResponseHelper.ts
  packages/cli/src/WorkflowExecuteAdditionalData.ts
  packages/cli/src/WorkflowRunner.ts
  packages/cli/src/commands/BaseCommand.ts
  packages/cli/src/commands/executeBatch.ts
  packages/cli/src/commands/start.ts
  packages/cli/src/commands/update/workflow.ts
  packages/cli/src/controllers/e2e.controller.ts
  packages/cli/src/eventbus/MessageEventBusDestination/MessageEventBusDestinationSyslog.ee.ts
  packages/cli/src/eventbus/MessageEventBusDestination/MessageEventBusDestinationWebhook.ee.ts
  packages/cli/src/help.ts
  packages/cli/src/security-audit/risk-reporters/InstanceRiskReporter.ts
  packages/cli/test/integration/credentials.test.ts
  packages/cli/test/unit/services/redis.service.test.ts
Labels: core, n8n team

#9299 fix(Gmail Node): Remove duplicate options when creating drafts
  packages/nodes-base/nodes/Google/Gmail/v2/DraftDescription.ts
Labels: node/improvement, n8n team

#9285 feat(core): Allow transfering/deleting workflows and credentials when resetting LDAP, instead of orphaning them
  packages/cli/src/commands/import/workflow.ts
  packages/cli/src/commands/ldap/reset.ts
  packages/cli/src/controllers/users.controller.ts
  packages/cli/src/credentials/credentials.service.ts
  packages/cli/src/databases/repositories/projectRelation.repository.ts
  packages/cli/src/workflows/workflow.service.ts
  packages/cli/test/integration/commands/ldap/reset.test.ts
  packages/cli/test/integration/ldap/ldap.api.test.ts
  packages/cli/test/integration/shared/ldap.ts
Labels: core, n8n team

#9284 fix(core): Prevent occassional 429s on license init in multi-main setup
  packages/cli/src/License.ts
  packages/cli/src/commands/BaseCommand.ts
  packages/cli/src/commands/start.ts
  packages/cli/src/services/orchestration/main/MultiMainSetup.ee.ts
  packages/cli/test/unit/License.test.ts
Labels: core, n8n team

#9308 fix(editor): Fix type errors in the `SettingsLdapView.vue` (no-changelog)
  packages/design-system/src/types/form.ts
  packages/editor-ui/src/v3-infinite-loading.d.ts
  packages/editor-ui/src/views/SettingsLdapView.vue
Labels: ui, n8n team

#9310 fix(core): Create a personal project if a user signs up via SAML
  packages/cli/src/sso/saml/saml.service.ee.ts
  packages/cli/src/sso/saml/samlHelpers.ts
  packages/cli/test/integration/saml/samlHelpers.test.ts
Labels: core, n8n team

#9283 ci: Remove gulp (no-changelog)
  .github/pull_request_title_conventions.md
  packages/@n8n/nodes-langchain/gulpfile.js
  packages/@n8n/nodes-langchain/package.json
  packages/core/bin/copy-icons
  packages/core/bin/generate-translations
  packages/core/package.json
  packages/design-system/.npmignore
  packages/editor-ui/src/plugins/i18n/docs/README.md
  packages/nodes-base/package.json
  pnpm-lock.yaml
Labels: n8n team

#9309 fix(editor): Fix shortcut issue on save buttons
  packages/editor-ui/src/components/MainHeader/WorkflowDetails.vue
  packages/editor-ui/src/components/SaveButton.vue
  packages/editor-ui/src/plugins/i18n/locales/en.json
Labels: ui, n8n team

#9314 ci: Upgrade Turborepo to 1.13.3 (no-changelog)
  .gitignore
  package.json
  pnpm-lock.yaml
Labels: n8n team

#9316 fix(core): Report missing SAML attributes early with an actionable error message
  packages/cli/src/sso/saml/saml.service.ee.ts
  packages/cli/test/unit/sso/saml/saml.service.ee.test.ts
Labels: core, n8n team

#9063 fix(core): Webhooks responding with binary data should not prematurely end the response stream
  packages/cli/src/WebhookHelpers.ts
  packages/workflow/src/Interfaces.ts
Labels: core, n8n team

#9300 feat(editor): Implement AI Assistant chat UI
  packages/@n8n/chat/README.md
  packages/@n8n/chat/package.json
  packages/@n8n/chat/src/components/Chat.vue
  packages/@n8n/chat/src/components/Input.vue
  packages/@n8n/chat/src/components/Layout.vue
  packages/@n8n/chat/src/components/Message.vue
  packages/@n8n/chat/src/composables/useI18n.ts
  packages/@n8n/chat/src/constants/defaults.ts
  packages/@n8n/chat/src/css/_tokens.scss
  packages/@n8n/chat/src/types/chat.ts
  packages/@n8n/chat/src/types/messages.ts
  packages/@n8n/chat/src/types/options.ts
  packages/editor-ui/src/App.vue
  packages/editor-ui/src/Interface.ts
  packages/editor-ui/src/components/AIAssistantChat/AIAssistantChat.vue
  packages/editor-ui/src/components/AIAssistantChat/NextStepPopup.vue
  packages/editor-ui/src/components/AIAssistantChat/QuickReplies.vue
  packages/editor-ui/src/components/CanvasControls.vue
  packages/editor-ui/src/components/Node/NodeCreator/NodeCreator.vue
  packages/editor-ui/src/constants.ts
  packages/editor-ui/src/n8n-theme-variables.scss
  packages/editor-ui/src/n8n-theme.scss
  packages/editor-ui/src/plugins/i18n/locales/en.json
  packages/editor-ui/src/stores/ai.store.ts
  packages/editor-ui/src/utils/typeGuards.ts
  packages/editor-ui/src/views/CanvasAddButton.vue
  packages/editor-ui/src/views/NodeView.vue
  pnpm-lock.yaml
Labels: ui, n8n team

#9322 feat(Send Email Node): Add an option to customize client host-name on SMTP connections
  packages/nodes-base/credentials/Smtp.credentials.ts
  packages/nodes-base/nodes/EmailSend/v2/send.operation.ts
Labels: node/improvement, n8n team

#9319 fix(Pipedrive Node): Improve type-safety in custom-property handling
  packages/nodes-base/nodes/Pipedrive/GenericFunctions.ts
Labels: node/improvement, n8n team

#9324 fix(editor): Fix multi-select parameters with load options getting cleared
  packages/editor-ui/src/components/ParameterInput.vue
  packages/editor-ui/src/components/__tests__/ParameterInput.test.ts
Labels: ui, n8n team

#9329 feat(editor): Temporarily disable AI error helper
  packages/editor-ui/src/components/Error/NodeErrorView.vue
Labels: ui, n8n team

#9307 feat(LinkedIn Node): Upgrade LinkedIn API version
  packages/nodes-base/nodes/LinkedIn/GenericFunctions.ts
  packages/nodes-base/nodes/LinkedIn/LinkedIn.node.ts
Labels: node/improvement, community

#9273 fix(Linear Node): Fix issue with data not always being returned
  packages/nodes-base/nodes/Linear/GenericFunctions.ts
  packages/nodes-base/nodes/Linear/IssueDescription.ts
  packages/nodes-base/nodes/Linear/Linear.node.ts
Labels: node/improvement, n8n team

#9323 feat(Slack Node): Update to use the new API method for file uploads
  packages/nodes-base/nodes/Slack/Slack.node.ts
  packages/nodes-base/nodes/Slack/V2/FileDescription.ts
  packages/nodes-base/nodes/Slack/V2/GenericFunctions.ts
  packages/nodes-base/nodes/Slack/V2/SlackV2.node.ts
Labels: node/improvement, core, n8n team

#9109 feat(Simulate Node): New node (no-changelog)
  packages/cli/src/CredentialsHelper.ts
  packages/cli/src/NodeTypes.ts
  packages/cli/src/services/credentials-tester.service.ts
  packages/core/src/NodeExecuteFunctions.ts
  packages/editor-ui/src/components/Node.vue
  packages/editor-ui/src/constants.ts
  packages/nodes-base/nodes/Simulate/Simulate.node.json
  packages/nodes-base/nodes/Simulate/Simulate.node.ts
  packages/nodes-base/nodes/Simulate/SimulateTrigger.node.json
  packages/nodes-base/nodes/Simulate/SimulateTrigger.node.ts
  packages/nodes-base/nodes/Simulate/descriptions.ts
  packages/nodes-base/nodes/Simulate/methods/index.ts
  packages/nodes-base/nodes/Simulate/methods/loadOptions.ts
  packages/nodes-base/package.json
  packages/workflow/src/Interfaces.ts
Labels: node/new, n8n team

#9270 refactor(editor): Migrate workflows store to setup function with composition API (no-changelog)
  packages/editor-ui/src/Interface.ts
  packages/editor-ui/src/api/workflows.ts
  packages/editor-ui/src/components/__tests__/RunData.test.ts
  packages/editor-ui/src/components/__tests__/SQLEditor.test.ts
  packages/editor-ui/src/composables/__tests__/useContextMenu.test.ts
  packages/editor-ui/src/stores/__tests__/workflows.spec.ts
  packages/editor-ui/src/stores/__tests__/workflows.test.ts
  packages/editor-ui/src/stores/workflows.store.spec.ts
  packages/editor-ui/src/stores/workflows.store.ts
Labels: ui, n8n team

#9337 feat(editor): Remove AI Error Debugging
  packages/cli/src/controllers/ai.controller.ts
  packages/cli/src/requests.ts
  packages/cli/src/services/ai.service.ts
  packages/cli/src/services/ai/prompts/debugError.ts
  packages/cli/src/services/frontend.service.ts
  packages/cli/test/unit/controllers/ai.controller.test.ts
  packages/cli/test/unit/services/ai.service.test.ts
  packages/editor-ui/src/__tests__/defaults.ts
  packages/editor-ui/src/api/ai.ts
  packages/editor-ui/src/components/Error/NodeErrorView.vue
  packages/editor-ui/src/plugins/i18n/locales/en.json
  packages/editor-ui/src/stores/ai.store.spec.ts
  packages/editor-ui/src/stores/ai.store.ts
  packages/workflow/src/Interfaces.ts
Labels: core, ui, n8n team

#9318 fix(core): Make `project.type` type match in migration and entity
  packages/cli/src/databases/migrations/common/1714133768519-CreateProject.ts
Labels: core, n8n team

#9315 fix(core): Fix `RangeError: Maximum call stack size exceeded` under certain circumstances
  packages/cli/src/databases/entities/Project.ts
  packages/cli/test/integration/database/repositories/project.repository.test.ts
Labels: core, n8n team

#9334 fix(core): Deadlock when sharing credentials and workflows when using sqlite pooled
  packages/cli/src/credentials/credentials.controller.ts
  packages/cli/src/workflows/workflows.controller.ts
Labels: core, n8n team

#9338 fix(core): All calls to `plainToInstance` should exclude extraneous values (no-changelog)
  packages/cli/src/controllers/me.controller.ts
  packages/cli/src/controllers/users.controller.ts
  packages/cli/src/databases/entities/User.ts
  packages/cli/src/requests.ts
  packages/cli/test/integration/me.api.test.ts
  packages/cli/test/unit/controllers/me.controller.test.ts
Labels: core, n8n team

#9331 fix(core): Fix MySQL tests timeout issues
  packages/cli/test/integration/CredentialsHelper.test.ts
  packages/cli/test/integration/commands/reset.cmd.test.ts
  packages/cli/test/integration/environments/SourceControl.test.ts
  packages/cli/test/integration/executions.controller.test.ts
  packages/cli/test/integration/saml/samlHelpers.test.ts
  packages/cli/test/integration/shared/db/credentials.ts
  packages/cli/test/integration/users.api.test.ts
  packages/cli/test/integration/workflowHistoryManager.test.ts
  packages/cli/test/integration/workflows/workflowSharing.service.test.ts
Labels: core, n8n team

#9349 fix: Source Control import failing due to creating multiple of a project
  packages/cli/src/environments/sourceControl/sourceControlImport.service.ee.ts
Labels: core, n8n team

#9343 fix(editor): Update FE telemetry for RBAC
  packages/editor-ui/src/components/DuplicateWorkflowDialog.vue
  packages/editor-ui/src/components/Telemetry.vue
  packages/editor-ui/src/components/WorkflowShareModal.ee.vue
  packages/editor-ui/src/composables/useWorkflowHelpers.ts
  packages/editor-ui/src/features/projects/components/ProjectSharing.vue
  packages/editor-ui/src/plugins/__tests__/telemetry.test.ts
  packages/editor-ui/src/plugins/telemetry/index.ts
Labels: ui, n8n team

#9350 feat(core): Node version available in expression
  packages/editor-ui/src/components/CodeNodeEditor/completions/base.completions.ts
  packages/editor-ui/src/constants.ts
  packages/editor-ui/src/plugins/codemirror/completions/constants.ts
  packages/editor-ui/src/plugins/i18n/index.ts
  packages/editor-ui/src/plugins/i18n/locales/en.json
  packages/workflow/src/WorkflowDataProxy.ts
Labels: node/improvement, n8n team

#9352 fix(editor): Render backticks as code segments in error view
  packages/editor-ui/src/components/Error/NodeErrorView.vue
Labels: ui, n8n team

#9351 feat: RBAC backend Telemetry
  packages/cli/src/InternalHooks.ts
  packages/cli/src/PublicApi/v1/handlers/workflows/workflows.handler.ts
  packages/cli/src/controllers/project.controller.ts
  packages/cli/src/databases/repositories/project.repository.ts
  packages/cli/src/databases/repositories/projectRelation.repository.ts
  packages/cli/src/databases/repositories/sharedCredentials.repository.ts
  packages/cli/src/databases/repositories/sharedWorkflow.repository.ts
  packages/cli/src/services/project.service.ts
  packages/cli/src/telemetry/index.ts
  packages/cli/src/workflows/workflows.controller.ts
  packages/cli/test/integration/workflows/workflow.service.test.ts
  packages/cli/test/unit/InternalHooks.test.ts
Labels: core, n8n team

#9354 fix: Refactor source control import to run workflow by workflow
  packages/cli/src/environments/sourceControl/sourceControlImport.service.ee.ts
Labels: core, n8n team

#9019 feat(editor): Autocomplete info box: improve structure and add examples
  cypress/e2e/14-mapping.cy.ts
  packages/design-system/src/css/_primitives.scss
  packages/design-system/src/css/_tokens.dark.scss
  packages/design-system/src/css/_tokens.scss
  packages/editor-ui/src/components/CodeNodeEditor/theme.ts
  packages/editor-ui/src/components/InlineExpressionEditor/InlineExpressionTip.vue
  packages/editor-ui/src/composables/useExpressionEditor.ts
  packages/editor-ui/src/plugins/codemirror/completions/__tests__/completions.test.ts
  packages/editor-ui/src/plugins/codemirror/completions/constants.ts
  packages/editor-ui/src/plugins/codemirror/completions/datatype.completions.ts
  packages/editor-ui/src/plugins/codemirror/completions/dollar.completions.ts
  packages/editor-ui/src/plugins/codemirror/completions/infoBoxRenderer.ts
  packages/editor-ui/src/plugins/codemirror/completions/nativesAutocompleteDocs/luxon.instance.docs.ts
  packages/editor-ui/src/plugins/codemirror/completions/typeGuards.ts
  packages/editor-ui/src/plugins/codemirror/completions/utils.ts
  packages/editor-ui/src/plugins/codemirror/n8nLang.ts
  packages/editor-ui/src/plugins/i18n/locales/en.json
  packages/editor-ui/src/styles/plugins/_codemirror.scss
  packages/workflow/src/Extensions/ArrayExtensions.ts
  packages/workflow/src/Extensions/DateExtensions.ts
  packages/workflow/src/Extensions/ExpressionExtension.ts
  packages/workflow/src/Extensions/Extensions.ts
  packages/workflow/src/Extensions/NumberExtensions.ts
  packages/workflow/src/Extensions/StringExtensions.ts
  packages/workflow/src/Extensions/index.ts
  packages/workflow/src/NativeMethods/Array.methods.ts
  packages/workflow/src/NativeMethods/Number.methods.ts
  packages/workflow/src/NativeMethods/String.methods.ts
  packages/workflow/src/index.ts
  packages/workflow/test/ExpressionExtensions/NumberExtensions.test.ts
Labels: core, ui, n8n team

#9359 fix(editor): Fix unwanted side effects from tailwind components (no-changelog)
  packages/editor-ui/src/components/MainHeader/WorkflowDetails.vue
  packages/editor-ui/src/components/TagsManager/NoTagsView.vue
Labels: ui, n8n team

#9335 fix(editor): Update paywall states for RBAC
  cypress/e2e/39-projects.cy.ts
  cypress/support/commands.ts
  cypress/support/index.ts
  packages/cli/src/controllers/e2e.controller.ts
  packages/design-system/src/components/N8nMenuItem/MenuItem.vue
  packages/editor-ui/src/Interface.ts
  packages/editor-ui/src/api/roles.api.ts
  packages/editor-ui/src/components/CredentialEdit/CredentialSharing.ee.vue
  packages/editor-ui/src/components/MainSidebar.vue
  packages/editor-ui/src/components/WorkflowShareModal.ee.vue
  packages/editor-ui/src/composables/useWorkflowHelpers.ts
  packages/editor-ui/src/features/projects/components/ProjectNavigation.vue
  packages/editor-ui/src/features/projects/components/ProjectRoleUpgradeDialog.vue
  packages/editor-ui/src/features/projects/components/ProjectSettings.vue
  packages/editor-ui/src/features/projects/components/ProjectSharing.vue
  packages/editor-ui/src/features/projects/components/__tests__/ProjectSettings.test.ts
  packages/editor-ui/src/features/projects/components/__tests__/ProjectSharing.test.ts
  packages/editor-ui/src/features/projects/projects.api.ts
  packages/editor-ui/src/features/projects/projects.store.ts
  packages/editor-ui/src/features/projects/projects.types.ts
  packages/editor-ui/src/init.ts
  packages/editor-ui/src/plugins/i18n/locales/en.json
  packages/editor-ui/src/stores/roles.store.ts
  packages/editor-ui/src/types/roles.types.ts
Labels: ui, n8n team

#9362 fix(editor): Fix e2e for `codemirror-lang` package migration
  packages/@n8n/codemirror-lang/package.json
  packages/@n8n/codemirror-lang/src/expressions/grammar.ts
  packages/editor-ui/package.json
  pnpm-lock.yaml
Labels: ui, n8n team

#9087 feat(editor): Migrate `codemirror-lang-n8n-expression` into this monorepo (no-changelog)
  .github/workflows/units-tests-reusable.yml
  package.json
  packages/@n8n/codemirror-lang/.eslintrc.cjs
  packages/@n8n/codemirror-lang/README.md
  packages/@n8n/codemirror-lang/jest.config.js
  packages/@n8n/codemirror-lang/package.json
  packages/@n8n/codemirror-lang/src/expressions/README.md
  packages/@n8n/codemirror-lang/src/expressions/expressions.grammar
  packages/@n8n/codemirror-lang/src/expressions/grammar.terms.ts
  packages/@n8n/codemirror-lang/src/expressions/grammar.ts
  packages/@n8n/codemirror-lang/src/expressions/index.ts
  packages/@n8n/codemirror-lang/src/index.ts
  packages/@n8n/codemirror-lang/test/expressions/cases.txt
  packages/@n8n/codemirror-lang/test/expressions/expressions.test.ts
  packages/@n8n/codemirror-lang/tsconfig.build.json
  packages/@n8n/codemirror-lang/tsconfig.json
  packages/editor-ui/package.json
  packages/editor-ui/src/plugins/codemirror/n8nLang.ts
  pnpm-lock.yaml
Labels: ui, n8n team

#9363 perf: Reduce variance in `nodes-base` benchmarks
  packages/nodes-base/test/benchmark.ts
  packages/nodes-base/test/nodes/ExecuteWorkflow.ts
Labels: node/improvement, n8n team

#9311 refactor: Implement LLM tracing callback to improve parsing of tokens usage stats
  packages/@n8n/nodes-langchain/nodes/llms/LMChatAnthropic/LmChatAnthropic.node.ts
  packages/@n8n/nodes-langchain/nodes/llms/LMChatOllama/LmChatOllama.node.ts
  packages/@n8n/nodes-langchain/nodes/llms/LMChatOpenAi/LmChatOpenAi.node.ts
  packages/@n8n/nodes-langchain/nodes/llms/LMCohere/LmCohere.node.ts
  packages/@n8n/nodes-langchain/nodes/llms/LMOllama/LmOllama.node.ts
  packages/@n8n/nodes-langchain/nodes/llms/LMOpenAi/LmOpenAi.node.ts
  packages/@n8n/nodes-langchain/nodes/llms/LMOpenHuggingFaceInference/LmOpenHuggingFaceInference.node.ts
  packages/@n8n/nodes-langchain/nodes/llms/LmChatAwsBedrock/LmChatAwsBedrock.node.ts
  packages/@n8n/nodes-langchain/nodes/llms/LmChatAzureOpenAi/LmChatAzureOpenAi.node.ts
  packages/@n8n/nodes-langchain/nodes/llms/LmChatGoogleGemini/LmChatGoogleGemini.node.ts
  packages/@n8n/nodes-langchain/nodes/llms/LmChatGooglePalm/LmChatGooglePalm.node.ts
  packages/@n8n/nodes-langchain/nodes/llms/LmChatGroq/LmChatGroq.node.ts
  packages/@n8n/nodes-langchain/nodes/llms/LmChatMistralCloud/LmChatMistralCloud.node.ts
  packages/@n8n/nodes-langchain/nodes/llms/LmGooglePalm/LmGooglePalm.node.ts
  packages/@n8n/nodes-langchain/nodes/llms/N8nLlmTracing.ts
  packages/@n8n/nodes-langchain/utils/logWrapper.ts
  packages/core/src/WorkflowExecute.ts
  packages/editor-ui/src/components/RunDataAi/RunDataAiContent.vue
  packages/workflow/src/Interfaces.ts
Labels: ui, n8n team

#9369 feat(core): Extract UserSubscriber into it's own module breaking dependency cycles
  packages/cli/src/databases/config.ts
  packages/cli/src/databases/entities/Project.ts
  packages/cli/src/databases/entities/index.ts
  packages/cli/src/databases/subscribers/UserSubscriber.ts
  packages/cli/src/databases/subscribers/index.ts
Labels: core, n8n team

#8954 feat(core): Node hints(warnings) system
  packages/core/src/WorkflowExecute.ts
  packages/core/test/WorkflowExecute.test.ts
  packages/editor-ui/src/components/RunData.vue
  packages/nodes-base/utils/constants.ts
  packages/workflow/src/Interfaces.ts
  packages/workflow/src/NodeHelpers.ts
  packages/workflow/test/NodeHelpers.test.ts
Labels: node/improvement, ui, n8n team

#9358 feat(editor): Add examples for number & boolean, add new methods
  packages/editor-ui/src/plugins/codemirror/completions/__tests__/completions.test.ts
  packages/editor-ui/src/plugins/codemirror/completions/datatype.completions.ts
  packages/workflow/src/Extensions/BooleanExtensions.ts
  packages/workflow/src/Extensions/NumberExtensions.ts
  packages/workflow/src/Extensions/StringExtensions.ts
  packages/workflow/src/NativeMethods/Boolean.methods.ts
  packages/workflow/src/NativeMethods/Number.methods.ts
Labels: core, n8n team

#9376 fix(core): Fix project quota not being applied correctly
  packages/cli/src/services/project.service.ts
  packages/cli/test/integration/credentials.test.ts
  packages/cli/test/integration/project.api.test.ts
Labels: core, n8n team

#9381 refactor: Require project admin role for project creation
  packages/cli/src/controllers/project.controller.ts
Labels: core, n8n team

#9364 fix(editor): RBAC Frontend fixes
  cypress/e2e/39-projects.cy.ts
  packages/editor-ui/src/__tests__/permissions.spec.ts
  packages/editor-ui/src/components/CredentialCard.vue
  packages/editor-ui/src/components/CredentialEdit/CredentialEdit.vue
  packages/editor-ui/src/components/CredentialEdit/CredentialSharing.ee.vue
  packages/editor-ui/src/components/CredentialsSelect.vue
  packages/editor-ui/src/components/MainHeader/WorkflowDetails.vue
  packages/editor-ui/src/components/WorkflowCard.vue
  packages/editor-ui/src/components/WorkflowSettings.vue
  packages/editor-ui/src/components/WorkflowShareModal.ee.vue
  packages/editor-ui/src/components/__tests__/CredentialCard.test.ts
  packages/editor-ui/src/components/__tests__/WorkflowSettings.spec.ts
  packages/editor-ui/src/composables/useWorkflowHelpers.ts
  packages/editor-ui/src/features/projects/components/ProjectSettings.vue
  packages/editor-ui/src/features/projects/components/ProjectSharing.vue
  packages/editor-ui/src/features/projects/components/ProjectSharingInfo.vue
  packages/editor-ui/src/features/projects/components/ProjectTabs.vue
  packages/editor-ui/src/permissions.ts
  packages/editor-ui/src/plugins/i18n/locales/en.json
  packages/editor-ui/src/stores/credentials.store.ts
  packages/editor-ui/src/stores/workflows.ee.store.ts
  packages/editor-ui/src/views/WorkflowsView.vue
Labels: ui, n8n team

#9380 fix(Code Node): Bind helper methods to the correct context
  packages/nodes-base/nodes/Code/Sandbox.ts
Labels: node/improvement, n8n team

#9389 fix(editor): Add project settings change telemetry events
  packages/design-system/src/components/N8nButton/Button.vue
  packages/design-system/src/types/button.ts
  packages/editor-ui/src/features/projects/components/ProjectDeleteDialog.vue
  packages/editor-ui/src/features/projects/components/ProjectRoleUpgradeDialog.vue
  packages/editor-ui/src/features/projects/components/ProjectSettings.vue
  packages/editor-ui/src/features/projects/components/ProjectSharing.vue
Labels: ui, n8n team

#9375 fix(Mattermost Node): Fix issue when fetching reactions
  packages/nodes-base/nodes/Mattermost/v1/actions/reaction/getAll/execute.ts
Labels: node/improvement, n8n team

#9360 feat(editor): Add examples for object and array expression methods
  packages/editor-ui/src/plugins/codemirror/completions/datatype.completions.ts
  packages/editor-ui/src/plugins/codemirror/completions/infoBoxRenderer.ts
  packages/editor-ui/src/styles/plugins/_codemirror.scss
  packages/workflow/src/Extensions/ArrayExtensions.ts
  packages/workflow/src/Extensions/Extensions.ts
  packages/workflow/src/Extensions/NumberExtensions.ts
  packages/workflow/src/Extensions/ObjectExtensions.ts
  packages/workflow/src/Extensions/StringExtensions.ts
  packages/workflow/src/NativeMethods/Array.methods.ts
  packages/workflow/test/ExpressionExtensions/ArrayExtensions.test.ts
  packages/workflow/test/ExpressionExtensions/StringExtensions.test.ts
Labels: core, ui, n8n team

#8705 feat(core): Allow using a custom certificates in docker containers
  docker/images/n8n/docker-entrypoint.sh
Labels: n8n team

#9394 fix(editor): Temporarily disable tailwind (no-changelog)
  packages/design-system/.storybook/preview.js
  packages/design-system/postcss.config.js
  packages/editor-ui/postcss.config.js
  packages/editor-ui/src/main.ts
Labels: ui, n8n team

#9393 fix(editor): RBAC frontend fixes next round
  packages/editor-ui/src/components/MainHeader/WorkflowDetails.vue
  packages/editor-ui/src/components/MainSidebar.vue
  packages/editor-ui/src/components/layouts/ResourcesListLayout.vue
  packages/editor-ui/src/features/projects/components/ProjectCardBadge.vue
  packages/editor-ui/src/plugins/i18n/locales/en.json
  packages/editor-ui/src/plugins/icons/index.ts
  packages/editor-ui/src/stores/roles.store.ts
Labels: ui, n8n team

#9374 fix(Cortex Node): Fix issue with analyzer response not working for file observables
  packages/nodes-base/nodes/Cortex/Cortex.node.ts
Labels: node/improvement, n8n team

#8876 fix: Small typo fix (no-changelog)
  packages/nodes-base/nodes/FunctionItem/FunctionItem.node.ts
Labels: node/improvement, community

#8925 feat(Slack Node): Add block support for message updates
  packages/nodes-base/nodes/Slack/V2/MessageDescription.ts
  packages/nodes-base/nodes/Slack/V2/SlackV2.node.ts
Labels: node/improvement, community

#9339 feat(AI Agent Node): Implement Tool calling agent
  packages/@n8n/nodes-langchain/nodes/agents/Agent/Agent.node.ts
  packages/@n8n/nodes-langchain/nodes/agents/Agent/agents/ToolsAgent/description.ts
  packages/@n8n/nodes-langchain/nodes/agents/Agent/agents/ToolsAgent/execute.ts
  packages/@n8n/nodes-langchain/nodes/agents/Agent/agents/ToolsAgent/prompt.ts
  packages/@n8n/nodes-langchain/utils/logWrapper.ts
Labels: n8n team

#9404 fix(editor): Update caller policy select
  packages/editor-ui/src/components/WorkflowSettings.vue
  packages/editor-ui/src/components/__tests__/WorkflowSettings.spec.ts
  packages/editor-ui/src/plugins/i18n/locales/en.json
  packages/editor-ui/src/stores/workflows.ee.store.ts
Labels: ui, n8n team

#9190 feat: Add Slack trigger node
  cypress/e2e/2-credentials.cy.ts
  packages/nodes-base/nodes/Slack/SlackTrigger.node.ts
  packages/nodes-base/nodes/Slack/SlackTriggerHelpers.ts
  packages/nodes-base/nodes/Slack/SlackTriggger.node.json
  packages/nodes-base/nodes/Slack/V2/GenericFunctions.ts
  packages/nodes-base/package.json
Labels: node/improvement, node/new, n8n team

#9407 fix(editor): Fetching credentials by correct project id
  packages/editor-ui/src/views/NodeView.vue
Labels: ui, n8n team

#9409 fix(editor): Fix blank Public API page
  packages/editor-ui/src/components/SettingsSidebar.vue
Labels: ui, n8n team

#9401 fix(editor): Secondary button in dark mode
  packages/design-system/src/components/N8nButton/Button.scss
  packages/design-system/src/css/_primitives.scss
  packages/design-system/src/css/_tokens.dark.scss
  packages/design-system/src/css/_tokens.scss
  packages/design-system/src/css/common/var.scss
  packages/editor-ui/src/components/Node/NodeCreation.vue
Labels: ui, n8n team

#9411 fix(editor): Fix outdated roles in variables labels
  packages/editor-ui/src/components/VariablesRow.vue
  packages/editor-ui/src/plugins/i18n/locales/en.json
Labels: ui, n8n team

#9408 fix(core): Return tags from `GET /workflows/:id`
  packages/cli/src/workflows/workflows.controller.ts
  packages/cli/test/integration/workflows/workflows.controller.ee.test.ts
  packages/cli/test/integration/workflows/workflows.controller.test.ts
Labels: core, n8n team

#9417 test(editor): Fix failing sharing e2e tests partially
  cypress/e2e/17-sharing.cy.ts
  cypress/pages/credentials.ts
  cypress/pages/modals/credentials-modal.ts
  cypress/pages/modals/workflow-sharing-modal.ts
  cypress/pages/workflows.ts
Labels: n8n team

#9416 fix(editor): RBAC frontend fixes
  packages/editor-ui/src/components/DeleteUserModal.vue
  packages/editor-ui/src/components/MainHeader/WorkflowDetails.vue
  packages/editor-ui/src/features/projects/components/ProjectSettings.vue
  packages/editor-ui/src/plugins/i18n/locales/en.json
Labels: ui, n8n team

#9415 fix(core): Add an option to disable STARTTLS for SMTP connections
  packages/cli/src/UserManagement/email/NodeMailer.ts
  packages/cli/src/config/schema.ts
Labels: core, n8n team

#9179 fix(core): Handle credential in body for oauth2 refresh token
  packages/@n8n/client-oauth2/src/ClientOAuth2Token.ts
  packages/@n8n/client-oauth2/test/CredentialsFlow.test.ts
Labels: community

#9357 fix: PairedItems various fixes (no-changelog)
  packages/nodes-base/nodes/FileMaker/FileMaker.node.ts
  packages/nodes-base/nodes/Google/Sheet/v2/actions/sheet/append.operation.ts
  packages/nodes-base/nodes/Google/Sheet/v2/actions/sheet/appendOrUpdate.operation.ts
  packages/nodes-base/nodes/Google/Sheet/v2/actions/sheet/update.operation.ts
  packages/nodes-base/nodes/Merge/v2/MergeV2.node.ts
Labels: node/improvement, n8n team, node/issue

#9396 refactor: Allow admins and instance owners to use any credentials in their workflows
  packages/cli/src/UserManagement/PermissionChecker.ts
  packages/cli/src/credentials/credentials.service.ts
  packages/cli/test/integration/PermissionChecker.test.ts
  packages/cli/test/integration/credentials.controller.test.ts
Labels: core, n8n team

#9413 fix(Mattermost Node): Change loadOptions to fetch all items
  packages/nodes-base/nodes/Mattermost/v1/methods/loadOptions.ts
Labels: node/improvement, n8n team

#9403 fix(HubSpot Trigger Node): Fix issue with ticketId not being set
  packages/nodes-base/nodes/Hubspot/HubspotTrigger.node.ts
Labels: node/improvement, n8n team

#9392 feat(Extract from File Node): Add option to set encoding for CSV files
  packages/nodes-base/nodes/Files/ExtractFromFile/actions/spreadsheet.operation.ts
  packages/nodes-base/nodes/SpreadsheetFile/description.ts
  packages/nodes-base/nodes/SpreadsheetFile/v2/fromFile.operation.ts
Labels: node/improvement, n8n team

#9420 feat(editor): Expand supported Unicode range for expressions
  packages/@n8n/codemirror-lang/src/expressions/README.md
  packages/@n8n/codemirror-lang/src/expressions/expressions.grammar
  packages/@n8n/codemirror-lang/src/expressions/grammar.ts
  packages/@n8n/codemirror-lang/test/expressions/cases.txt
Labels: n8n team

#9361 feat(editor): Add examples for Luxon DateTime expression methods
  packages/editor-ui/src/components/CodeNodeEditor/completions/luxon.completions.ts
  packages/editor-ui/src/plugins/codemirror/completions/constants.ts
  packages/editor-ui/src/plugins/codemirror/completions/datatype.completions.ts
  packages/editor-ui/src/plugins/codemirror/completions/nativesAutocompleteDocs/luxon.instance.docs.ts
  packages/editor-ui/src/plugins/codemirror/completions/nativesAutocompleteDocs/luxon.static.docs.ts
  packages/editor-ui/src/plugins/i18n/index.ts
  packages/editor-ui/src/plugins/i18n/locales/en.json
  packages/workflow/src/Expression.ts
  packages/workflow/src/Extensions/DateExtensions.ts
  packages/workflow/src/Extensions/StringExtensions.ts
  packages/workflow/test/ExpressionExtensions/DateExtensions.test.ts
Labels: core, ui, n8n team

#9406 feat(OpenAI Node): Use v2 assistants API and add support for memory
  packages/@n8n/nodes-langchain/nodes/vendors/OpenAi/actions/assistant/create.operation.ts
  packages/@n8n/nodes-langchain/nodes/vendors/OpenAi/actions/assistant/deleteAssistant.operation.ts
  packages/@n8n/nodes-langchain/nodes/vendors/OpenAi/actions/assistant/list.operation.ts
  packages/@n8n/nodes-langchain/nodes/vendors/OpenAi/actions/assistant/message.operation.ts
  packages/@n8n/nodes-langchain/nodes/vendors/OpenAi/actions/assistant/update.operation.ts
  packages/@n8n/nodes-langchain/nodes/vendors/OpenAi/actions/versionDescription.ts
  packages/@n8n/nodes-langchain/nodes/vendors/OpenAi/methods/listSearch.ts
  packages/@n8n/nodes-langchain/nodes/vendors/OpenAi/test/OpenAi.node.test.ts
Labels: n8n team

#9427 fix(core): Send email again when a workflow or credential is shared
  packages/cli/src/credentials/credentials.controller.ts
  packages/cli/src/workflows/workflows.controller.ts
  packages/cli/test/integration/credentials.ee.test.ts
  packages/cli/test/integration/workflows/workflows.controller.ee.test.ts
Labels: core, n8n team

#9379 fix(core): Do not report to Sentry trigger activation errors from `ETIMEDOUT` or `ECONNREFUSED` (no-changelog)
  packages/core/src/ActiveWorkflows.ts
Labels: core, n8n team

#9426 fix: Credential testing for sharees
  packages/cli/src/credentials/credentials.controller.ts
  packages/cli/src/credentials/credentials.service.ts
  packages/cli/test/integration/credentials/credentials.controller.test.ts
  packages/cli/test/integration/credentials/credentials.ee.test.ts
  packages/cli/test/integration/credentials/credentials.service.test.ts
Labels: core, n8n team

#9395 fix(core): Retry before continue on fail
  packages/core/src/WorkflowExecute.ts
Labels: core, n8n team

#9377 fix(core): Remove excess args from routing error
  packages/workflow/src/RoutingNode.ts
Labels: core, n8n team

#9436 fix: Fix color picker type errors
  packages/design-system/src/components/N8nColorPicker/ColorPicker.vue
  packages/design-system/src/components/N8nColorPicker/__tests__/__snapshots__/ColorPicker.spec.ts.snap
Labels: ui, n8n team

#9435 fix(editor): Fix RBAC type errors (no-changelog)
  packages/editor-ui/src/rbac/checks/__tests__/isAuthenticated.test.ts
  packages/editor-ui/src/rbac/middleware/authenticated.ts
  packages/editor-ui/src/rbac/middleware/defaultUser.ts
  packages/editor-ui/src/rbac/middleware/enterprise.ts
  packages/editor-ui/src/rbac/middleware/guest.ts
  packages/editor-ui/src/rbac/middleware/rbac.ts
  packages/editor-ui/src/rbac/middleware/role.ts
  packages/editor-ui/src/types/router.ts
Labels: ui, n8n team

#9425 feat(editor): Update Node Details View header tabs structure
  packages/design-system/src/components/N8nInputLabel/InputLabel.vue
  packages/design-system/src/components/N8nTabs/Tabs.vue
  packages/editor-ui/src/components/NodeSettings.vue
  packages/editor-ui/src/components/NodeSettingsTabs.vue
  packages/editor-ui/src/plugins/i18n/locales/en.json
Labels: ui, n8n team

#9440 fix(HTML Node): Fix typo preventing row attributes from being set in tables
  packages/nodes-base/nodes/Html/Html.node.ts
Labels: node/improvement, n8n team

#9434 fix(editor): Fix External secrets typecheck (no-changelog)
  packages/editor-ui/src/Interface.ts
  packages/editor-ui/src/api/externalSecrets.ee.ts
  packages/editor-ui/src/components/ExternalSecretsProviderCard.ee.vue
  packages/editor-ui/src/components/ExternalSecretsProviderImage.ee.vue
  packages/editor-ui/src/components/ExternalSecretsProviderModal.ee.vue
  packages/editor-ui/src/composables/useExternalSecretsProvider.ts
  packages/editor-ui/src/shims.d.ts
  packages/editor-ui/src/utils/typeGuards.ts
  packages/editor-ui/tsconfig.json
Labels: ui, n8n team

#9439 refactor: Fix type errors in completions code
  packages/editor-ui/src/composables/useWorkflowHelpers.ts
  packages/editor-ui/src/plugins/codemirror/completions/__tests__/completions.test.ts
  packages/editor-ui/src/plugins/codemirror/completions/bracketAccess.completions.ts
Labels: ui, n8n team

#9445 fix: Fix type errors in community nodes components
  packages/editor-ui/src/components/CommunityPackageCard.vue
  packages/editor-ui/src/views/SettingsCommunityNodesView.vue
Labels: ui, n8n team

#9446 fix(editor): Fix editor-ui tsconfig types for vue-tsc (no-changelog)
  packages/editor-ui/tsconfig.json
Labels: ui, n8n team

#9448 fix(editor): Fix type errors in `components/executions/workflow`
  packages/editor-ui/src/components/executions/workflow/WorkflowExecutionsCard.vue
  packages/editor-ui/src/components/executions/workflow/WorkflowExecutionsInfoAccordion.vue
  packages/editor-ui/src/components/executions/workflow/WorkflowExecutionsLandingPage.vue
  packages/editor-ui/src/components/executions/workflow/WorkflowExecutionsList.vue
  packages/editor-ui/src/components/executions/workflow/WorkflowExecutionsPreview.vue
  packages/editor-ui/src/components/executions/workflow/WorkflowExecutionsSidebar.vue
Labels: ui, n8n team

#9423 refactor(editor): Convert `workflowActivate` mixin into a composable (no-changelog)
  packages/editor-ui/src/components/NodeDetailsView.vue
  packages/editor-ui/src/components/WorkflowActivator.vue
  packages/editor-ui/src/composables/useWorkflowActivate.ts
  packages/editor-ui/src/mixins/workflowActivate.ts
Labels: ui, n8n team

#9431 refactor(editor): Fix type errors in `NodeDetailsView.vue` (no-changelog)
  packages/editor-ui/src/components/NDVDraggablePanels.vue
  packages/editor-ui/src/components/NodeDetailsView.vue
  packages/editor-ui/src/components/NodeSettings.vue
Labels: ui, n8n team

#9451 fix(editor): Fix i18n translation addition
  packages/editor-ui/src/components/CredentialEdit/CredentialConfig.vue
  packages/editor-ui/src/plugins/i18n/index.ts
Labels: ui, n8n team

#9456 ci: Delete unused code in some backend tests (no-changelog)
  packages/core/test/helpers/index.ts
  packages/nodes-base/test/nodes/ExecuteWorkflow.ts
  packages/nodes-base/test/nodes/Helpers.ts
  packages/workflow/src/Interfaces.ts
  packages/workflow/test/Helpers.ts
  packages/workflow/test/NodeTypes.ts
  packages/workflow/test/RoutingNode.test.ts
Labels: node/improvement, core, n8n team

#9467 fix: Init license properly with multi main (no-changelog)
  packages/cli/src/License.ts
Labels: core, n8n team

#8437 feat(Telegram Node): Add support for local bot api server
  packages/editor-ui/src/utils/testData/credentialTypeTestData.ts
  packages/nodes-base/credentials/TelegramApi.credentials.ts
  packages/nodes-base/nodes/Telegram/GenericFunctions.ts
  packages/nodes-base/nodes/Telegram/Telegram.node.ts
  packages/nodes-base/nodes/Telegram/TelegramTrigger.node.ts
Labels: node/improvement, ui, community

#9472 fix(Telegram Node): Revert typo introduced in #8437 (no-changelog)
  packages/nodes-base/nodes/Telegram/Telegram.node.ts
Labels: node/improvement, community

#9459 refactor(editor): Refactor code completions mixins to composables (no-changelog)
  cypress/fixtures/Multiple_trigger_node_rerun.json
  packages/editor-ui/src/components/CodeNodeEditor/completer.ts
  packages/editor-ui/src/components/CodeNodeEditor/completions/base.completions.ts
  packages/editor-ui/src/components/CodeNodeEditor/completions/execution.completions.ts
  packages/editor-ui/src/components/CodeNodeEditor/completions/itemField.completions.ts
  packages/editor-ui/src/components/CodeNodeEditor/completions/itemIndex.completions.ts
  packages/editor-ui/src/components/CodeNodeEditor/completions/jsonField.completions.ts
  packages/editor-ui/src/components/CodeNodeEditor/completions/luxon.completions.ts
  packages/editor-ui/src/components/CodeNodeEditor/completions/prevNode.completions.ts
  packages/editor-ui/src/components/CodeNodeEditor/completions/require.completions.ts
  packages/editor-ui/src/components/CodeNodeEditor/completions/secrets.completions.ts
  packages/editor-ui/src/components/CodeNodeEditor/completions/variables.completions.ts
  packages/editor-ui/src/components/CodeNodeEditor/completions/workflow.completions.ts
  packages/editor-ui/src/plugins/codemirror/completions/__tests__/base.completions.test.ts
  packages/editor-ui/src/plugins/codemirror/completions/__tests__/itemField.completions.test.ts
  packages/editor-ui/src/plugins/codemirror/completions/__tests__/itemIndex.completions.test.ts
  packages/editor-ui/src/plugins/codemirror/completions/__tests__/jsonField.completions.test.ts
  packages/editor-ui/src/plugins/codemirror/completions/__tests__/prevNode.completions.test.ts
  packages/editor-ui/src/plugins/codemirror/completions/__tests__/require.completions.test.ts
  packages/editor-ui/src/plugins/codemirror/completions/__tests__/variables.completions.test.ts
Labels: ui, n8n team

#9443 fix(editor): Fix rundata type errors (no-changelog)
  packages/editor-ui/src/components/Draggable.vue
  packages/editor-ui/src/components/InputPanel.vue
  packages/editor-ui/src/components/NodeExecuteButton.vue
  packages/editor-ui/src/components/OutputPanel.vue
  packages/editor-ui/src/components/RunData.vue
  packages/editor-ui/src/components/RunDataHtml.vue
  packages/editor-ui/src/components/RunDataJson.vue
  packages/editor-ui/src/components/RunDataJsonActions.vue
  packages/editor-ui/src/components/RunDataSchemaItem.vue
  packages/editor-ui/src/components/RunDataTable.vue
  packages/editor-ui/src/composables/usePinnedData.ts
  packages/editor-ui/src/plugins/i18n/locales/en.json
  packages/workflow/src/Interfaces.ts
Labels: ui, n8n team

#9449 refactor: Fix type issues for parameter input components
  packages/core/src/Interfaces.ts
  packages/core/src/NodeExecuteFunctions.ts
  packages/editor-ui/src/Interface.ts
  packages/editor-ui/src/components/CodeNodeEditor/linter.ts
  packages/editor-ui/src/components/CollectionParameter.vue
  packages/editor-ui/src/components/ExpandableInput/ExpandableInputEdit.vue
  packages/editor-ui/src/components/ExpressionEdit.vue
  packages/editor-ui/src/components/ExpressionParameterInput.vue
  packages/editor-ui/src/components/FilterConditions/Condition.vue
  packages/editor-ui/src/components/FilterConditions/utils.ts
  packages/editor-ui/src/components/FixedCollectionParameter.vue
  packages/editor-ui/src/components/MultipleParameter.vue
  packages/editor-ui/src/components/NodeIcon.vue
  packages/editor-ui/src/components/NodeTitle.vue
  packages/editor-ui/src/components/OnboardingCallSignupModal.vue
  packages/editor-ui/src/components/OutputPanel.vue
  packages/editor-ui/src/components/PageAlert.vue
  packages/editor-ui/src/components/ParameterInput.vue
  packages/editor-ui/src/components/ParameterInputExpanded.vue
  packages/editor-ui/src/components/ParameterInputFull.vue
  packages/editor-ui/src/components/ParameterInputList.vue
  packages/editor-ui/src/components/ParameterInputWrapper.vue
  packages/editor-ui/src/components/ParameterOptions.vue
  packages/editor-ui/src/components/RBAC.vue
  packages/editor-ui/src/components/ResourceLocator/ResourceLocator.vue
  packages/editor-ui/src/components/ResourceLocator/ResourceLocatorDropdown.vue
  packages/editor-ui/src/components/ResourceMapper/MappingFields.vue
  packages/editor-ui/src/components/ResourceMapper/ResourceMapper.vue
  packages/editor-ui/src/components/forms/ResourceFiltersDropdown.vue
  packages/editor-ui/src/hooks/segment/getters.ts
  packages/editor-ui/src/plugins/i18n/index.ts
  packages/editor-ui/src/plugins/i18n/utils.ts
  packages/nodes-base/nodes/Set/v2/helpers/utils.ts
  packages/workflow/src/Interfaces.ts
  packages/workflow/src/NodeParameters/FilterParameter.ts
  packages/workflow/src/TypeValidation.ts
Labels: core, ui, n8n team

#9475 fix(editor): Fix project settings layout
  packages/editor-ui/src/features/projects/components/ProjectSettings.vue
  packages/editor-ui/src/features/projects/components/ProjectSharing.vue
Labels: ui, n8n team

#9384 fix(core): Fix 431 for large dynamic node parameters
  cypress/e2e/5-ndv.cy.ts
  packages/cli/src/controllers/dynamicNodeParameters.controller.ts
  packages/cli/src/requests.ts
  packages/cli/test/integration/controllers/dynamic-node-parameters.controller.test.ts
  packages/cli/test/integration/shared/types.ts
  packages/cli/test/integration/shared/utils/testServer.ts
  packages/editor-ui/src/api/nodeTypes.ts
Labels: core, ui, n8n team

#9447 fix(editor): Fix design system typecheck errors (no-changelog)
  packages/design-system/src/components/N8nColorPicker/ColorPicker.vue
  packages/design-system/src/components/N8nColorPicker/__tests__/__snapshots__/ColorPicker.spec.ts.snap
  packages/design-system/src/components/N8nFormInput/FormInput.vue
  packages/design-system/src/components/N8nFormInput/validators.ts
  packages/design-system/src/components/N8nFormInputs/FormInputs.vue
  packages/design-system/src/components/N8nInput/Input.vue
  packages/design-system/src/components/N8nInput/__tests__/__snapshots__/Input.spec.ts.snap
  packages/design-system/src/components/N8nInputNumber/InputNumber.vue
  packages/design-system/src/components/N8nLink/Link.vue
  packages/design-system/src/components/N8nNodeIcon/NodeIcon.vue
  packages/design-system/src/components/N8nRoute/Route.vue
  packages/design-system/src/components/N8nSelect/Select.vue
  packages/design-system/src/components/N8nUsersList/UsersList.stories.ts
  packages/design-system/src/components/N8nUsersList/UsersList.vue
  packages/design-system/src/types/datatable.ts
  packages/design-system/src/types/form.ts
  packages/design-system/src/utils/index.ts
  packages/design-system/src/utils/typeguards.ts
  packages/design-system/tsconfig.json
  packages/editor-ui/src/views/SettingsUsersView.vue
Labels: ui, n8n team

#9480 fix(editor): Fix type errors for various utils files (no-changelog)
  packages/editor-ui/src/Interface.ts
  packages/editor-ui/src/__tests__/mocks.ts
  packages/editor-ui/src/types/expressions.ts
  packages/editor-ui/src/utils/__tests__/rbacUtils.test.ts
  packages/editor-ui/src/utils/__tests__/sourceControlUtils.test.ts
  packages/editor-ui/src/utils/canvasUtils.ts
  packages/editor-ui/src/utils/nodeTypesUtils.ts
  packages/editor-ui/src/utils/nodeViewUtils.ts
  packages/editor-ui/src/utils/rbacUtils.ts
  packages/editor-ui/src/utils/sourceControlUtils.ts
  packages/editor-ui/src/utils/telemetryUtils.ts
  packages/editor-ui/src/utils/testData/templateTestData.ts
  packages/editor-ui/src/utils/typeGuards.ts
  packages/editor-ui/src/utils/typesUtils.ts
  packages/editor-ui/src/utils/userUtils.ts
  packages/workflow/src/Interfaces.ts
Labels: core, ui, n8n team

#9479 fix(editor): Emit change events from filter component on update
  packages/editor-ui/src/components/FilterConditions/Condition.vue
  packages/editor-ui/src/components/FilterConditions/__tests__/FilterConditions.test.ts
Labels: ui, n8n team

#9462 feat(Strava Node): Update to use sport type
  packages/nodes-base/nodes/Strava/ActivityDescription.ts
  packages/nodes-base/nodes/Strava/Strava.node.ts
Labels: node/improvement, community, in linear

#9478 fix(core): Fix typos in common error messages (no-changelog)
  packages/workflow/src/errors/abstract/node.error.ts
  packages/workflow/test/NodeErrors.test.ts
Labels: community

#9373 feat(editor): Add examples for root expression methods
  packages/editor-ui/src/components/CodeNodeEditor/completions/base.completions.ts
  packages/editor-ui/src/components/CodeNodeEditor/completions/execution.completions.ts
  packages/editor-ui/src/components/CodeNodeEditor/utils.ts
  packages/editor-ui/src/plugins/codemirror/completions/__tests__/completions.test.ts
  packages/editor-ui/src/plugins/codemirror/completions/constants.ts
  packages/editor-ui/src/plugins/codemirror/completions/datatype.completions.ts
  packages/editor-ui/src/plugins/codemirror/completions/dollar.completions.ts
  packages/editor-ui/src/plugins/codemirror/completions/nativesAutocompleteDocs/luxon.instance.docs.ts
  packages/editor-ui/src/plugins/codemirror/completions/nonDollar.completions.ts
  packages/editor-ui/src/plugins/codemirror/completions/utils.ts
  packages/editor-ui/src/plugins/i18n/index.ts
  packages/editor-ui/src/plugins/i18n/locales/en.json
Labels: ui, n8n team

#9182 fix(RSS Feed Trigger Node): Use newest date instead of first item for new items
  packages/nodes-base/nodes/RssFeedRead/RssFeedReadTrigger.node.ts
Labels: node/improvement, community

#9469 feat(Linear Node): Add identifier to outputs
  packages/nodes-base/nodes/Linear/Queries.ts
Labels: node/improvement, n8n team

#9471 test: Add tests for license manager reinit method
  packages/cli/test/unit/License.test.ts
Labels: core, n8n team

#9424 fix(Gmail Trigger Node): Fetching duplicate emails
  packages/nodes-base/nodes/Google/Gmail/GmailTrigger.node.ts
Labels: n8n team, node/issue

#9387 feat(core): Node hints improvements (no-changelog)
  packages/design-system/src/css/_tokens.scss
  packages/editor-ui/src/components/RunData.vue
  packages/nodes-base/nodes/Postgres/v2/actions/router.ts
  packages/nodes-base/nodes/Transform/SplitOut/SplitOut.node.ts
  packages/workflow/src/NodeHelpers.ts
Labels: node/improvement, ui, n8n team

#8967 fix: Update operations to run per item
  packages/nodes-base/credentials/CodaApi.credentials.ts
  packages/nodes-base/nodes/Airtable/Airtable.node.ts
  packages/nodes-base/nodes/Airtable/v2/actions/record/search.operation.ts
  packages/nodes-base/nodes/Airtable/v2/actions/versionDescription.ts
  packages/nodes-base/nodes/Coda/Coda.node.ts
  packages/nodes-base/nodes/Coda/TableDescription.ts
  packages/nodes-base/nodes/Google/Firebase/CloudFirestore/GoogleFirebaseCloudFirestore.node.ts
  packages/nodes-base/nodes/Google/Sheet/v2/actions/spreadsheet/delete.operation.ts
  packages/nodes-base/nodes/Microsoft/Sql/MicrosoftSql.node.ts
  packages/nodes-base/nodes/MongoDb/GenericFunctions.ts
  packages/nodes-base/nodes/MongoDb/MongoDb.node.ts
  packages/nodes-base/nodes/RssFeedRead/RssFeedRead.node.ts
Labels: node/improvement, n8n team, node/issue

#9470 feat(Custom n8n Workflow Tool Node): Add support for tool input schema
  packages/@n8n/nodes-langchain/nodes/agents/Agent/agents/ConversationalAgent/execute.ts
  packages/@n8n/nodes-langchain/nodes/agents/Agent/agents/PlanAndExecuteAgent/execute.ts
  packages/@n8n/nodes-langchain/nodes/agents/Agent/agents/ReActAgent/execute.ts
  packages/@n8n/nodes-langchain/nodes/code/Code.node.ts
  packages/@n8n/nodes-langchain/nodes/output_parser/OutputParserStructured/OutputParserStructured.node.ts
  packages/@n8n/nodes-langchain/nodes/tools/ToolWorkflow/ToolWorkflow.node.ts
  packages/@n8n/nodes-langchain/package.json
  packages/@n8n/nodes-langchain/tsconfig.build.json
  packages/@n8n/nodes-langchain/tsconfig.json
  packages/@n8n/nodes-langchain/types/generate-schema.d.ts
  packages/@n8n/nodes-langchain/types/zod.types.ts
  packages/@n8n/nodes-langchain/utils/descriptions.ts
  packages/@n8n/nodes-langchain/utils/schemaParsing.ts
  pnpm-lock.yaml
Labels: node/improvement, n8n team

#9485 fix(core): Detect DB connection aquisition deadlocks (no-changelog)
  .github/workflows/ci-postgres-mysql.yml
  packages/cli/src/PublicApi/v1/handlers/credentials/credentials.service.ts
  packages/cli/src/PublicApi/v1/handlers/workflows/workflows.service.ts
  packages/cli/src/WaitTracker.ts
  packages/cli/src/commands/import/credentials.ts
  packages/cli/src/commands/import/workflow.ts
  packages/cli/src/credentials/credentials.service.ts
  packages/cli/src/databases/repositories/project.repository.ts
  packages/cli/src/databases/subscribers/UserSubscriber.ts
  packages/cli/src/services/import.service.ts
Labels: n8n team

#9474 fix(core): Account for retry of execution aborted by pre-execute hook
  packages/cli/src/errors/aborted-execution-retry.error.ts
  packages/cli/src/executions/execution.service.ts
  packages/cli/test/unit/services/execution.service.test.ts
  packages/editor-ui/src/plugins/i18n/locales/en.json
Labels: core, ui, n8n team

#9487 fix(editor): Fix node execution errors showing undefined
  cypress/e2e/5-ndv.cy.ts
  cypress/fixtures/Test_workflow_ndv_run_error.json
  cypress/pages/ndv.ts
  packages/editor-ui/src/components/Error/NodeErrorView.vue
  packages/editor-ui/src/components/Error/__tests__/NodeErrorView.test.ts
  packages/editor-ui/src/components/RunData.vue
Labels: ui, n8n team

#9482 fix(editor): Project related frontend fixes (no-changelog)
  cypress/e2e/39-projects.cy.ts
  packages/editor-ui/src/__tests__/data/projects.ts
  packages/editor-ui/src/components/CredentialEdit/CredentialSharing.ee.vue
  packages/editor-ui/src/components/WorkflowSettings.vue
  packages/editor-ui/src/components/WorkflowShareModal.ee.vue
  packages/editor-ui/src/components/forms/ResourceFiltersDropdown.vue
  packages/editor-ui/src/features/projects/components/ProjectCardBadge.vue
  packages/editor-ui/src/features/projects/components/ProjectDeleteDialog.vue
  packages/editor-ui/src/features/projects/components/ProjectNavigation.vue
  packages/editor-ui/src/features/projects/components/ProjectSharing.vue
  packages/editor-ui/src/features/projects/components/ProjectSharingInfo.vue
  packages/editor-ui/src/features/projects/projects.store.ts
  packages/editor-ui/src/features/projects/projects.types.ts
  packages/editor-ui/src/features/projects/projects.utils.ts
  packages/editor-ui/src/plugins/i18n/locales/en.json
  packages/editor-ui/src/views/NodeView.vue
Labels: ui, n8n team

#9488 fix(core): Do not allow admins to generate password-reset links for instance owner
  packages/cli/src/controllers/users.controller.ts
  packages/cli/test/integration/users.api.test.ts
Labels: core, n8n team, security

#9476 refactor(core): Track potentially unneeded inferral of execution status (no-changelog)
  packages/cli/src/executions/execution.service.ts
Labels: core, n8n team

#9483 refactor(core): Make execution status non-nullable (no-changelog)
  packages/cli/src/databases/entities/ExecutionEntity.ts
  packages/cli/src/databases/migrations/common/1714133768521-MakeExecutionStatusNonNullable.ts
  packages/cli/src/databases/migrations/mysqldb/index.ts
  packages/cli/src/databases/migrations/postgresdb/index.ts
  packages/cli/src/databases/migrations/sqlite/index.ts
  packages/cli/test/integration/security-audit/CredentialsRiskReporter.test.ts
  packages/cli/test/integration/shared/db/executions.ts
Labels: core, n8n team

#9481 ci: Skip the flaky test in SettingsSso.test.ts (no-changelog)
  packages/editor-ui/src/views/__tests__/SettingsSso.test.ts
Labels: ui, n8n team

#9477 perf(core): Optimize executions filtering by metadata
  packages/cli/src/databases/repositories/execution.repository.ts
  packages/cli/test/integration/execution.service.integration.test.ts
  packages/cli/test/integration/shared/db/executions.ts
Labels: core, n8n team

#9490 fix(editor): Prevent XSS in node-issues tooltip
  packages/editor-ui/src/components/Node.vue
Labels: ui, n8n team, security

#9495 fix(editor): Show input panel with not connected message
  cypress/e2e/5-ndv.cy.ts
  packages/editor-ui/src/components/InputPanel.vue
  packages/editor-ui/src/components/OutputPanel.vue
  packages/editor-ui/src/components/RunData.vue
Labels: ui, n8n team

#9135 feat(editor): Add initial code for NodeView and Canvas rewrite (no-changelog)
  packages/editor-ui/package.json
  packages/editor-ui/src/Interface.ts
  packages/editor-ui/src/__tests__/data/canvas.ts
  packages/editor-ui/src/__tests__/data/index.ts
  packages/editor-ui/src/__tests__/defaults.ts
  packages/editor-ui/src/__tests__/mocks.ts
  packages/editor-ui/src/__tests__/render.ts
  packages/editor-ui/src/__tests__/utils.ts
  packages/editor-ui/src/components/canvas/Canvas.spec.ts
  packages/editor-ui/src/components/canvas/Canvas.vue
  packages/editor-ui/src/components/canvas/WorkflowCanvas.vue
  packages/editor-ui/src/components/canvas/elements/buttons/CanvasExecuteWorkflowButton.vue
  packages/editor-ui/src/components/canvas/elements/edges/CanvasEdge.vue
  packages/editor-ui/src/components/canvas/elements/handles/HandleRenderer.spec.ts
  packages/editor-ui/src/components/canvas/elements/handles/HandleRenderer.vue
  packages/editor-ui/src/components/canvas/elements/handles/render-types/CanvasHandleMainInput.spec.ts
  packages/editor-ui/src/components/canvas/elements/handles/render-types/CanvasHandleMainInput.vue
  packages/editor-ui/src/components/canvas/elements/handles/render-types/CanvasHandleMainOutput.spec.ts
  packages/editor-ui/src/components/canvas/elements/handles/render-types/CanvasHandleMainOutput.vue
  packages/editor-ui/src/components/canvas/elements/handles/render-types/CanvasHandleNonMain.spec.ts
  packages/editor-ui/src/components/canvas/elements/handles/render-types/CanvasHandleNonMain.vue
  packages/editor-ui/src/components/canvas/elements/nodes/CanvasNode.spec.ts
  packages/editor-ui/src/components/canvas/elements/nodes/CanvasNode.vue
  packages/editor-ui/src/components/canvas/elements/nodes/CanvasNodeRenderer.spec.ts
  packages/editor-ui/src/components/canvas/elements/nodes/CanvasNodeRenderer.vue
  packages/editor-ui/src/components/canvas/elements/nodes/CanvasNodeToolbar.spec.ts
  packages/editor-ui/src/components/canvas/elements/nodes/CanvasNodeToolbar.vue
  packages/editor-ui/src/components/canvas/elements/nodes/render-types/CanvasNodeConfigurable.spec.ts
  packages/editor-ui/src/components/canvas/elements/nodes/render-types/CanvasNodeConfigurable.vue
  packages/editor-ui/src/components/canvas/elements/nodes/render-types/CanvasNodeConfiguration.spec.ts
  packages/editor-ui/src/components/canvas/elements/nodes/render-types/CanvasNodeConfiguration.vue
  packages/editor-ui/src/components/canvas/elements/nodes/render-types/CanvasNodeDefault.spec.ts
  packages/editor-ui/src/components/canvas/elements/nodes/render-types/CanvasNodeDefault.vue
  packages/editor-ui/src/composables/useCanvasMapping.spec.ts
  packages/editor-ui/src/composables/useCanvasMapping.ts
  packages/editor-ui/src/composables/useNodeConnections.spec.ts
  packages/editor-ui/src/composables/useNodeConnections.ts
  packages/editor-ui/src/constants.ts
  packages/editor-ui/src/main.ts
  packages/editor-ui/src/plugins/codemirror/completions/__tests__/mock.ts
  packages/editor-ui/src/router.ts
  packages/editor-ui/src/stores/ui.store.ts
  packages/editor-ui/src/stores/workflows.store.ts
  packages/editor-ui/src/types/canvas.ts
  packages/editor-ui/src/types/index.ts
  packages/editor-ui/src/utils/canvasUtilsV2.spec.ts
  packages/editor-ui/src/utils/canvasUtilsV2.ts
  packages/editor-ui/src/views/NodeView.v2.vue
  pnpm-lock.yaml
Labels: ui, n8n team

#9497 refactor: Remove skipped tests (no-changelog)
  cypress/e2e/2-credentials.cy.ts
  cypress/e2e/30-workflow-filters.cy.ts
  cypress/e2e/38-custom-template-repository.cy.ts
  packages/cli/test/integration/eventbus.ee.test.ts
  packages/cli/test/integration/publicApi/executions.test.ts
  packages/cli/test/unit/services/redis.service.test.ts
  packages/editor-ui/src/views/__tests__/SettingsSso.test.ts
Labels: core, ui, n8n team

#9498 fix(core): Upgrade sheetjs to address CVE-2024-22363
  packages/nodes-base/nodes/SpreadsheetFile/test/SpreadsheetFile.test.ts
  packages/nodes-base/nodes/SpreadsheetFile/test/spreadsheet.html
  packages/nodes-base/nodes/SpreadsheetFile/test/spreadsheet.rtf
  packages/nodes-base/nodes/SpreadsheetFile/test/spreadsheet.xls
  packages/nodes-base/package.json
  pnpm-lock.yaml
Labels: n8n team

#9496 refactor(core): Stop reporting `EAUTH` error codes to Sentry (no-changelog)
  packages/cli/src/ActiveWorkflowManager.ts
  packages/core/src/ActiveWorkflows.ts
  packages/workflow/src/errors/workflow-activation.error.ts
  packages/workflow/test/errors/workflow-activation.error.test.ts
Labels: core, n8n team

#9500 fix(editor): Hard load after logout to reset stores (no-changelog)
  cypress/e2e/18-user-management.cy.ts
  cypress/e2e/39-projects.cy.ts
  cypress/pages/sidebar/main-sidebar.ts
  packages/editor-ui/src/views/SignoutView.vue
Labels: ui, n8n team

#9473 feat(core): Print the name of the migration that cannot be reverted when using `n8n db:revert`
  packages/cli/src/commands/db/revert.ts
  packages/cli/src/databases/utils/migrationHelpers.ts
  packages/cli/test/unit/commands/db/revert.test.ts
  packages/cli/test/unit/databases/utils/migrationHelpers.test.ts
Labels: core, n8n team

#9502 fix(core): Fix `level` in `warn` method of error reporter (no-changelog)
  packages/workflow/src/ErrorReporterProxy.ts
Labels: core, n8n team

#9501 ci: Switch to Node.js 20 by default. Add initial support for Node.js 22
  .github/workflows/check-documentation-urls.yml
  .github/workflows/check-pr-title.yml
  .github/workflows/check-tests.yml
  .github/workflows/chromatic.yml
  .github/workflows/ci-master.yml
  .github/workflows/ci-postgres-mysql.yml
  .github/workflows/ci-pull-requests.yml
  .github/workflows/docker-base-image.yml
  .github/workflows/release-create-pr.yml
  .github/workflows/release-publish.yml
  .github/workflows/release-push-to-channel.yml
  .github/workflows/test-workflows.yml
  .github/workflows/units-tests-reusable.yml
  CONTRIBUTING.md
  docker/images/n8n-base/Dockerfile
  docker/images/n8n-custom/Dockerfile
  docker/images/n8n/Dockerfile
  packages/cli/bin/n8n
Labels: core, n8n team
