Repository n8n-io/n8n, pull requests merged in 2024-04, with the labels that each got.

#8969 feat: Use scopes on the public API
  packages/@n8n/permissions/src/types.ts
  packages/cli/src/PublicApi/v1/handlers/audit/audit.handler.ts
  packages/cli/src/PublicApi/v1/handlers/credentials/credentials.handler.ts
  packages/cli/src/PublicApi/v1/handlers/executions/executions.handler.ts
  packages/cli/src/PublicApi/v1/handlers/sourceControl/sourceControl.handler.ts
  packages/cli/src/PublicApi/v1/handlers/tags/tags.handler.ts
  packages/cli/src/PublicApi/v1/handlers/users/users.handler.ee.ts
  packages/cli/src/PublicApi/v1/handlers/workflows/workflows.handler.ts
  packages/cli/src/PublicApi/v1/handlers/workflows/workflows.service.ts
  packages/cli/src/PublicApi/v1/shared/middlewares/global.middleware.ts
  packages/cli/src/decorators/registerController.ts
  packages/cli/src/permissions/checkAccess.ts
  packages/cli/src/permissions/global-roles.ts
  packages/cli/src/workflows/workflowSharing.service.ts
  packages/cli/test/integration/publicApi/credentials.test.ts
  packages/cli/test/integration/publicApi/executions.test.ts
Labels: core, n8n team

#9009 fix: Prevent chat modal opening on 'Test workflow' click
  cypress/composables/workflow.ts
  cypress/e2e/30-langchain.cy.ts
  packages/editor-ui/src/composables/useRunWorkflow.ts
  packages/editor-ui/src/views/NodeView.vue
Labels: ui, n8n team

#8920 feat: Add Salesforce Trigger Node
  packages/nodes-base/nodes/Salesforce/GenericFunctions.ts
  packages/nodes-base/nodes/Salesforce/SalesforceTrigger.node.ts
  packages/nodes-base/package.json
Labels: node/improvement, node/new, community

#9036 fix: Fix canvas selection for touch devices that use mouse
  packages/design-system/src/composables/useDeviceSupport.test.ts
  packages/design-system/src/composables/useDeviceSupport.ts
Labels: ui, n8n team

#9018 fix(editor): Fix execution debug button
  packages/editor-ui/src/components/ExecutionsView/ExecutionPreview.vue
Labels: ui, n8n team

#9037 feat: Allow workflow execution even if it has errors
  cypress/e2e/19-execution.cy.ts
  cypress/fixtures/Test_workflow_partial_execution_with_missing_credentials.json
  packages/editor-ui/src/composables/useRunWorkflow.test.ts
  packages/editor-ui/src/composables/useRunWorkflow.ts
  packages/editor-ui/src/composables/useWorkflowHelpers.ts
Labels: ui, n8n team

#9041 docs: Remove Vue TS plugin from recommended (no-changelog)
  .vscode/extensions.json
Labels: n8n team

#9025 fix(editor): Make share modal content scrollable
  packages/editor-ui/src/components/WorkflowShareModal.ee.vue
Labels: ui, n8n team

#9044 refactor(core): Delete all auth exclusion config and checks (no-changelog)
  packages/cli/src/Server.ts
  packages/cli/src/config/schema.ts
  packages/cli/src/security-audit/risk-reporters/InstanceRiskReporter.ts
  packages/cli/test/integration/security-audit/InstanceRiskReporter.test.ts
Labels: core, n8n team

#9045 fix(editor): Add fallback for expression resolution in multi-output case
  packages/editor-ui/src/composables/useWorkflowHelpers.ts
Labels: ui, n8n team

#9021 fix(core): Upgrade express to address CVE-2024-29041 (no-changelog)
  packages/cli/package.json
  pnpm-lock.yaml
Labels: core, n8n team

#9047 fix(editor): Make Webhook node pinnable
  cypress/e2e/13-pinning.cy.ts
  packages/editor-ui/src/composables/useNodeType.ts
Labels: ui, n8n team

#9015 fix(core): Ensure `status` on Axios errors is available to the BE
  packages/core/src/NodeExecuteFunctions.ts
  packages/core/test/NodeExecuteFunctions.test.ts
Labels: core, n8n team

#9048 fix(editor): Prevent saving workflow while another save is in progress
  cypress/e2e/7-workflow-actions.cy.ts
  packages/editor-ui/src/components/MainHeader/WorkflowDetails.vue
Labels: ui, n8n team

#9043 fix: Fix missing input panel in node details view
  cypress/e2e/1338-ADO-ndv-missing-input-panel.cy.ts
  cypress/fixtures/Test_ado_1338.json
  packages/editor-ui/src/composables/useNodeHelpers.ts
Labels: ui, n8n team

#9010 fix: Workflows executed from other workflows not stopping
  packages/cli/src/WorkflowExecuteAdditionalData.ts
Labels: core, n8n team

#9001 fix(editor): Canvas showing error toast when clicking outside of "import workflow by url" modal
  cypress/e2e/39-import-workflow.cy.ts
  cypress/e2e/7-workflow-actions.cy.ts
  packages/editor-ui/src/components/MainHeader/WorkflowDetails.vue
Labels: ui, n8n team

#9050 fix(editor): Rerun failed nodes in manual executions
  packages/editor-ui/src/composables/useRunWorkflow.test.ts
  packages/editor-ui/src/composables/useRunWorkflow.ts
Labels: ui, n8n team

#8999 fix(editor): Issue showing Auth2 callback section when all properties are overriden
  cypress/e2e/2-credentials.cy.ts
  packages/editor-ui/src/components/CredentialEdit/CredentialConfig.vue
  packages/editor-ui/src/components/CredentialEdit/CredentialEdit.vue
Labels: ui, n8n team

#9051 fix(editor): Fix execution with wait node
  packages/editor-ui/src/mixins/pushConnection.ts
Labels: ui, n8n team

#9014 fix(core): Ensure only leader handles waiting executions
  packages/cli/src/WaitTracker.ts
  packages/cli/src/commands/start.ts
  packages/cli/src/services/orchestration.service.ts
  packages/cli/src/services/orchestration/main/MultiMainSetup.ee.ts
  packages/cli/test/unit/WaitTracker.test.ts
Labels: core, n8n team

#9046 refactor(editor): Do not make rest api calls for disabled features (no-changelog)
  packages/editor-ui/src/init.ts
  packages/editor-ui/src/views/NodeView.vue
  packages/editor-ui/src/views/SettingsExternalSecrets.vue
  packages/editor-ui/src/views/SettingsSourceControl.vue
  packages/editor-ui/src/views/VariablesView.vue
Labels: ui, n8n team

#9053 refactor(editor): Remove legacy audit logs view (no-changelog)
  packages/editor-ui/src/components/SettingsSidebar.vue
  packages/editor-ui/src/constants.ts
  packages/editor-ui/src/plugins/i18n/locales/en.json
  packages/editor-ui/src/router.ts
  packages/editor-ui/src/views/SettingsAuditLogs.vue
  packages/editor-ui/src/views/__tests__/SettingsAuditLogs.test.ts
Labels: ui, n8n team

#9016 refactor(core, editor): Remove legacy `nodesAccess` (no-changelog)
  packages/cli/src/CredentialsHelper.ts
  packages/cli/src/PublicApi/v1/handlers/credentials/credentials.service.ts
  packages/cli/src/commands/export/credentials.ts
  packages/cli/src/commands/import/credentials.ts
  packages/cli/src/controllers/oauth/abstractOAuth.controller.ts
  packages/cli/src/credentials/credentials.service.ts
  packages/cli/src/databases/entities/CredentialsEntity.ts
  packages/cli/src/databases/migrations/common/1712044305787-RemoveNodesAccess.ts
  packages/cli/src/databases/migrations/mysqldb/index.ts
  packages/cli/src/databases/migrations/postgresdb/index.ts
  packages/cli/src/databases/migrations/sqlite/index.ts
  packages/cli/src/databases/repositories/credentials.repository.ts
  packages/cli/src/environments/sourceControl/sourceControl.service.ee.ts
  packages/cli/src/environments/sourceControl/sourceControlExport.service.ee.ts
  packages/cli/src/environments/sourceControl/sourceControlImport.service.ee.ts
  packages/cli/src/environments/sourceControl/types/exportableCredential.ts
  packages/cli/src/requests.ts
  packages/cli/test/integration/commands/credentials.cmd.test.ts
  packages/cli/test/integration/commands/importCredentials/credentials.json
  packages/cli/test/integration/credentials.controller.test.ts
  packages/cli/test/integration/credentials.ee.test.ts
  packages/cli/test/integration/credentials.test.ts
  packages/cli/test/integration/environments/source-control-import.service.test.ts
  packages/cli/test/integration/publicApi/credentials.test.ts
  packages/cli/test/integration/security-audit/CredentialsRiskReporter.test.ts
  packages/cli/test/integration/shared/db/credentials.ts
  packages/cli/test/integration/shared/random.ts
  packages/cli/test/integration/shared/types.ts
  packages/cli/test/integration/users.api.test.ts
  packages/cli/test/unit/controllers/oAuth1Credential.controller.test.ts
  packages/cli/test/unit/controllers/oAuth2Credential.controller.test.ts
  packages/core/src/Credentials.ts
  packages/core/test/Credentials.test.ts
  packages/editor-ui/src/__tests__/server/factories/credential.ts
  packages/editor-ui/src/components/CredentialCard.vue
  packages/editor-ui/src/components/CredentialEdit/CredentialEdit.vue
  packages/editor-ui/src/views/SetupWorkflowFromTemplateView/__tests__/setupTemplate.store.testData.ts
  packages/workflow/src/Interfaces.ts
  packages/workflow/test/Helpers.ts
Labels: core, n8n team

#9049 ci: Delete some duplicate code in cli tests (no-changelog)
  packages/cli/test/integration/shared/db/users.ts
  packages/cli/test/shared/mocking.ts
  packages/cli/test/unit/repositories/execution.repository.test.ts
  packages/cli/test/unit/repositories/sharedCredentials.repository.test.ts
  packages/cli/test/unit/repositories/workflowStatistics.test.ts
Labels: core, n8n team

#9062 fix(core): Ensure TTL safeguard for test webhooks applies only to multi-main setup
  packages/cli/src/services/cache/cache.service.ts
  packages/cli/src/services/test-webhook-registrations.service.ts
  packages/cli/test/unit/services/test-webhook-registrations.service.test.ts
Labels: core, n8n team

#9071 fix(editor): Fix issue with case insensitive tags
  cypress/e2e/17-workflow-tags.cy.ts
  packages/editor-ui/src/components/TagsDropdown.vue
Labels: ui, n8n team

#9042 fix(editor): Connecting nodes to triggers when adding them together
  cypress/e2e/5-ndv.cy.ts
  packages/editor-ui/src/components/Node/NodeCreator/__tests__/useActions.test.ts
  packages/editor-ui/src/components/Node/NodeCreator/composables/useActions.ts
Labels: ui, n8n team

#9012 test(core): Fix multiple parallel private key checks (no-changelog)
  packages/cli/src/databases/migrations/common/1711390882123-MoveSshKeysToDatabase.ts
Labels: core, n8n team

#9072 fix(API): Accept `settings.executionOrder` in workflow creation
  packages/cli/src/PublicApi/v1/handlers/workflows/spec/schemas/workflowSettings.yml
  packages/cli/test/integration/publicApi/workflows.test.ts
Labels: core, n8n team

#9056 fix(core): Remove binary data when deleting executions by filter
  packages/cli/src/databases/repositories/execution.repository.ts
  packages/cli/test/unit/repositories/execution.repository.test.ts
Labels: core, n8n team

#9075 refactor(core): Better UX for `maxStalledCount` queue mode error
  packages/cli/src/commands/worker.ts
  packages/cli/src/errors/max-stalled-count.error.ts
Labels: core, n8n team

#9068 fix(editor): Fix issues in dark mode
  packages/design-system/src/css/_tokens.dark.scss
  packages/design-system/src/css/_tokens.scss
  packages/editor-ui/src/components/BinaryDataDisplay.vue
  packages/editor-ui/src/components/Node.vue
  packages/editor-ui/src/components/Node/NodeCreator/Panel/SearchBar.vue
  packages/editor-ui/src/mixins/nodeBase.ts
  packages/editor-ui/src/n8n-theme.scss
  packages/editor-ui/src/utils/nodeViewUtils.ts
Labels: ui, n8n team

#9026 feat: Add credential update and delete events to log streaming
  packages/cli/src/InternalHooks.ts
  packages/cli/src/PublicApi/v1/handlers/credentials/credentials.handler.ts
  packages/cli/src/PublicApi/v1/handlers/credentials/credentials.service.ts
  packages/cli/src/credentials/credentials.controller.ts
  packages/cli/src/eventbus/EventMessageClasses/index.ts
Labels: core, n8n team

#9069 fix: Fix some vue warnings (no-changelog)
  packages/editor-ui/src/components/InlineExpressionEditor/InlineExpressionEditorOutput.vue
  packages/editor-ui/src/components/NodeExecuteButton.vue
Labels: ui, n8n team

#9083 fix(editor): Expand range of allowed characters in expressions
  packages/editor-ui/package.json
  packages/editor-ui/src/plugins/codemirror/resolvableHighlighter.ts
  pnpm-lock.yaml
Labels: ui, n8n team

#8995 feat(core): Create names for personal projects in one place and resuse it
  packages/cli/src/databases/entities/Project.ts
  packages/cli/src/databases/entities/User.ts
  packages/cli/src/databases/repositories/user.repository.ts
  packages/cli/test/integration/controllers/invitation/invitation.controller.integration.test.ts
  packages/cli/test/integration/credentials.ee.test.ts
  packages/cli/test/integration/me.api.test.ts
  packages/cli/test/integration/project.api.test.ts
  packages/cli/test/integration/users.api.test.ts
  packages/cli/test/integration/workflows/workflows.controller.ee.test.ts
  packages/cli/test/integration/workflows/workflows.controller.test.ts
  packages/cli/test/unit/databases/entities/user.entity.test.ts
Labels: core, n8n team

#9081 feat(core): Improve Langsmith traces for AI executions
  packages/@n8n/nodes-langchain/nodes/agents/Agent/agents/ConversationalAgent/execute.ts
  packages/@n8n/nodes-langchain/nodes/agents/Agent/agents/OpenAiFunctionsAgent/execute.ts
  packages/@n8n/nodes-langchain/nodes/agents/Agent/agents/PlanAndExecuteAgent/execute.ts
  packages/@n8n/nodes-langchain/nodes/agents/Agent/agents/ReActAgent/execute.ts
  packages/@n8n/nodes-langchain/nodes/agents/Agent/agents/SqlAgent/execute.ts
  packages/@n8n/nodes-langchain/nodes/agents/OpenAiAssistant/OpenAiAssistant.node.ts
  packages/@n8n/nodes-langchain/nodes/chains/ChainLLM/ChainLlm.node.ts
  packages/@n8n/nodes-langchain/nodes/chains/ChainRetrievalQA/ChainRetrievalQa.node.ts
  packages/@n8n/nodes-langchain/nodes/chains/ChainSummarization/V2/ChainSummarizationV2.node.ts
  packages/@n8n/nodes-langchain/nodes/retrievers/RetrieverWorkflow/RetrieverWorkflow.node.ts
  packages/@n8n/nodes-langchain/nodes/tools/ToolWorkflow/ToolWorkflow.node.ts
  packages/@n8n/nodes-langchain/nodes/vendors/OpenAi/actions/assistant/message.operation.ts
  packages/@n8n/nodes-langchain/utils/tracing.ts
  packages/cli/src/WorkflowExecuteAdditionalData.ts
  packages/core/src/NodeExecuteFunctions.ts
  packages/workflow/package.json
  packages/workflow/src/Interfaces.ts
  pnpm-lock.yaml
Labels: core, n8n team

#9055 fix(editor): Drop outgoing connections on order changed event for nodes with dynamic outputs
  cypress/e2e/5-ndv.cy.ts
  cypress/fixtures/NDV-test-switch_reorder.json
  packages/editor-ui/src/Interface.ts
  packages/editor-ui/src/components/FixedCollectionParameter.vue
  packages/editor-ui/src/components/NodeSettings.vue
  packages/editor-ui/src/constants.ts
  packages/editor-ui/src/plugins/i18n/locales/en.json
  packages/editor-ui/src/stores/workflows.store.ts
Labels: ui, n8n team, node/issue

#9011 fix(MySQL Node): Query Parameters parse string to number
  packages/nodes-base/nodes/MySql/MySql.node.ts
  packages/nodes-base/nodes/MySql/test/v2/operations.test.ts
  packages/nodes-base/nodes/MySql/v2/actions/database/executeQuery.operation.ts
  packages/nodes-base/nodes/MySql/v2/actions/versionDescription.ts
Labels: n8n team, node/issue

#9090 fix(core): Don't fail when asking for an execution with sharing enabled
  packages/cli/src/executions/execution.service.ee.ts
  packages/cli/test/integration/executions.controller.test.ts
Labels: core, n8n team

#9061 fix(editor): Fix displaying logic of execution retry button
  packages/editor-ui/src/components/ExecutionsList.vue
  packages/editor-ui/src/components/ExecutionsView/ExecutionCard.vue
  packages/editor-ui/src/components/ExecutionsView/ExecutionPreview.vue
  packages/editor-ui/src/components/ExecutionsView/__tests__/ExecutionCard.test.ts
  packages/editor-ui/src/mixins/executionsHelpers.ts
Labels: ui, n8n team

#8994 fix(core): Create personal project when a user is created via LDAP
  packages/cli/src/Ldap/helpers.ts
  packages/cli/test/integration/ldap/ldap.api.test.ts
Labels: core, n8n team

#9070 feat: Append item index suffix to an error message, if provided, and node has many input items
  packages/editor-ui/src/components/Error/NodeErrorView.vue
Labels: ui, n8n team

#9057 feat(core): Prevent session hijacking
  cypress/support/commands.ts
  packages/cli/src/Server.ts
  packages/cli/src/auth/auth.service.ts
  packages/cli/src/controllers/auth.controller.ts
  packages/cli/src/controllers/invitation.controller.ts
  packages/cli/src/controllers/me.controller.ts
  packages/cli/src/controllers/owner.controller.ts
  packages/cli/src/controllers/passwordReset.controller.ts
  packages/cli/src/middlewares/cors.ts
  packages/cli/src/requests.ts
  packages/cli/src/sso/saml/routes/saml.controller.ee.ts
  packages/cli/test/unit/auth/auth.service.test.ts
  packages/cli/test/unit/controllers/me.controller.test.ts
  packages/cli/test/unit/controllers/owner.controller.test.ts
  packages/editor-ui/src/utils/apiUtils.ts
Labels: core, ui, n8n team

#8899 feat(Email Trigger (IMAP) Node): Migrate from `imap-simple` to `@n8n/imap`
  package.json
  packages/@n8n/imap/.eslintrc.js
  packages/@n8n/imap/jest.config.js
  packages/@n8n/imap/package.json
  packages/@n8n/imap/src/ImapSimple.ts
  packages/@n8n/imap/src/errors.ts
  packages/@n8n/imap/src/helpers/getMessage.ts
  packages/@n8n/imap/src/index.ts
  packages/@n8n/imap/src/types.ts
  packages/@n8n/imap/tsconfig.build.json
  packages/@n8n/imap/tsconfig.json
  packages/nodes-base/nodes/EmailReadImap/v1/EmailReadImapV1.node.ts
  packages/nodes-base/nodes/EmailReadImap/v2/EmailReadImapV2.node.ts
  packages/nodes-base/package.json
  packages/nodes-base/tsconfig.json
  pnpm-lock.yaml
Labels: node/improvement, n8n team

#9059 fix(editor): UX improvements to mfa setup modal
  packages/design-system/src/css/_tokens.dark.scss
  packages/design-system/src/css/_tokens.scss
  packages/editor-ui/src/components/MfaSetupModal.vue
Labels: ui, n8n team

#9095 feat(editor): Remove cloud deployment check from settings route middlewareOptions (no-changelog)
  packages/editor-ui/src/router.ts
Labels: ui, n8n team

#9096 feat: Add telemetry event 'User clicked AI error helper button' (no-changelog)
  packages/editor-ui/src/components/Error/NodeErrorView.vue
Labels: ui, n8n team

#9078 fix: Continue on fail / error output support for chains and agents
  packages/@n8n/nodes-langchain/nodes/agents/Agent/agents/ConversationalAgent/execute.ts
  packages/@n8n/nodes-langchain/nodes/agents/Agent/agents/OpenAiFunctionsAgent/execute.ts
  packages/@n8n/nodes-langchain/nodes/agents/Agent/agents/PlanAndExecuteAgent/execute.ts
  packages/@n8n/nodes-langchain/nodes/agents/Agent/agents/ReActAgent/execute.ts
  packages/@n8n/nodes-langchain/nodes/agents/Agent/agents/SqlAgent/execute.ts
  packages/@n8n/nodes-langchain/nodes/agents/OpenAiAssistant/OpenAiAssistant.node.ts
  packages/@n8n/nodes-langchain/nodes/chains/ChainLLM/ChainLlm.node.ts
  packages/@n8n/nodes-langchain/nodes/chains/ChainRetrievalQA/ChainRetrievalQa.node.ts
  packages/@n8n/nodes-langchain/nodes/chains/ChainSummarization/V2/ChainSummarizationV2.node.ts
Labels: node/improvement, n8n team, node/issue

#9085 fix(AWS Bedrock Chat Model Node): Improve filtering of Bedrock models & fix Claude 3
  packages/@n8n/nodes-langchain/nodes/embeddings/EmbeddingsAwsBedrock/EmbeddingsAwsBedrock.node.ts
  packages/@n8n/nodes-langchain/nodes/llms/LmChatAwsBedrock/LmChatAwsBedrock.node.ts
  packages/@n8n/nodes-langchain/package.json
  packages/cli/package.json
  pnpm-lock.yaml
Labels: n8n team

#9097 fix(editor): Set `browser-id` on all relative urls (no-changelog)
  packages/editor-ui/src/utils/apiUtils.ts
Labels: ui, n8n team

#9100 fix(core): Fix `isLeader` check in `WaitTracker` constructor
  packages/cli/src/WaitTracker.ts
  packages/cli/src/services/orchestration.service.ts
  packages/cli/test/unit/WaitTracker.test.ts
Labels: core, n8n team

#9067 feat(Postgres Node): Options keepAlive and keepAliveInitialDelayMillis
  packages/nodes-base/nodes/Postgres/PostgresTrigger.functions.ts
  packages/nodes-base/nodes/Postgres/PostgresTrigger.node.ts
  packages/nodes-base/nodes/Postgres/v2/actions/common.descriptions.ts
  packages/nodes-base/nodes/Postgres/v2/actions/database/deleteTable.operation.ts
  packages/nodes-base/nodes/Postgres/v2/actions/database/executeQuery.operation.ts
  packages/nodes-base/nodes/Postgres/v2/actions/database/insert.operation.ts
  packages/nodes-base/nodes/Postgres/v2/actions/database/select.operation.ts
  packages/nodes-base/nodes/Postgres/v2/actions/database/update.operation.ts
  packages/nodes-base/nodes/Postgres/v2/actions/database/upsert.operation.ts
  packages/nodes-base/nodes/Postgres/v2/actions/router.ts
  packages/nodes-base/nodes/Postgres/v2/helpers/interfaces.ts
  packages/nodes-base/nodes/Postgres/v2/methods/credentialTest.ts
  packages/nodes-base/nodes/Postgres/v2/methods/listSearch.ts
  packages/nodes-base/nodes/Postgres/v2/methods/loadOptions.ts
  packages/nodes-base/nodes/Postgres/v2/methods/resourceMapping.ts
  packages/nodes-base/nodes/Postgres/v2/transport/index.ts
Labels: node/improvement, n8n team, node/issue

#9040 fix(HTTP Request Node): Duplicate key names support for form data
  packages/nodes-base/nodes/HttpRequest/GenericFunctions.ts
  packages/nodes-base/nodes/HttpRequest/HttpRequest.node.ts
  packages/nodes-base/nodes/HttpRequest/V3/HttpRequestV3.node.ts
Labels: n8n team, node/issue

#9102 fix(core): Some more browser-id related fixes (no-changelog)
  packages/@n8n/nodes-langchain/nodes/trigger/ChatTrigger/templates.ts
  packages/cli/src/auth/auth.service.ts
  packages/cli/test/integration/shared/utils/testServer.ts
Labels: core, n8n team

#9103 refactor(core): Remove unnecessary indirection in SAML code (no-changelog)
  packages/cli/src/sso/saml/constants.ts
  packages/cli/src/sso/saml/middleware/samlEnabledMiddleware.ts
  packages/cli/src/sso/saml/routes/saml.controller.ee.ts
  packages/cli/src/sso/saml/serviceProvider.ee.ts
  packages/cli/test/integration/saml/saml.api.test.ts
Labels: core, n8n team

#9005 feat(JWT Node): New node
  packages/nodes-base/credentials/jwtAuth.credentials.ts
  packages/nodes-base/nodes/Jwt/Jwt.node.json
  packages/nodes-base/nodes/Jwt/Jwt.node.ts
  packages/nodes-base/nodes/Jwt/jwt.svg
  packages/nodes-base/nodes/Jwt/test/Jwt.node.test.ts
  packages/nodes-base/nodes/Jwt/test/jwt.workflow.json
  packages/nodes-base/nodes/Webhook/Webhook.node.ts
  packages/nodes-base/package.json
  packages/nodes-base/test/nodes/FakeCredentialsMap.ts
  packages/nodes-base/utils/utilities.ts
  packages/workflow/src/Interfaces.ts
  packages/workflow/src/TypeValidation.ts
Labels: node/new, n8n team

#9091 docs: Update wording for Advanced AI in nodes panel
  packages/editor-ui/src/plugins/i18n/locales/en.json
Labels: ui, n8n team

#9029 ci: Move docker-compose examples out of this repo (no-changelog)
  docker/compose/subfolderWithSSL/.env
  docker/compose/subfolderWithSSL/README.md
  docker/compose/subfolderWithSSL/docker-compose.yml
  docker/compose/withPostgres/.env
  docker/compose/withPostgres/README.md
  docker/compose/withPostgres/docker-compose.yml
  docker/compose/withPostgres/init-data.sh
  docker/compose/withPostgresAndWorker/.env
  docker/compose/withPostgresAndWorker/README.md
  docker/compose/withPostgresAndWorker/docker-compose.yml
  docker/compose/withPostgresAndWorker/init-data.sh
Labels: n8n team

#9107 ci: Keep n8n-workflow version in sync with the main version (no-changelog)
  .github/scripts/bump-versions.mjs
  .github/workflows/release-push-to-channel.yml
Labels: n8n team

#9106 fix: Remove scope filter on projects APIs
  packages/cli/src/controllers/project.controller.ts
  packages/cli/test/integration/project.api.test.ts
Labels: core, n8n team

#9088 feat(editor): Add object keys that need bracket access to autocomplete
  packages/editor-ui/src/plugins/codemirror/completions/__tests__/completions.test.ts
  packages/editor-ui/src/plugins/codemirror/completions/bracketAccess.completions.ts
  packages/editor-ui/src/plugins/codemirror/completions/datatype.completions.ts
  packages/editor-ui/src/plugins/codemirror/completions/utils.ts
Labels: ui, n8n team

#9117 fix(core): Upgrade `tar` to address CVE-2024-28863 (no-changelog)
  pnpm-lock.yaml
Labels: n8n team

#9099 feat: Enable External Secrets for team projects with an instance owner or admin as an admin
  packages/cli/src/CredentialsHelper.ts
  packages/cli/src/controllers/users.controller.ts
  packages/cli/src/services/project.service.ts
  packages/cli/test/integration/CredentialsHelper.test.ts
  packages/cli/test/integration/project.api.test.ts
  packages/cli/test/integration/users.api.test.ts
Labels: core, n8n team

#9105 fix(core): Don't revert irreversibble migrations
  packages/cli/src/commands/db/revert.ts
  packages/cli/src/databases/utils/migrationHelpers.ts
  packages/cli/test/unit/commands/db/revert.test.ts
Labels: core, n8n team

#9119 fix(editor): Do not show overlapping trash icon in the node's settings
  packages/editor-ui/src/components/ParameterInputList.vue
Labels: ui, n8n team

#9116 ci: Fix docs urls (no-changelog)
  .github/workflows/check-documentation-urls.yml
  packages/nodes-base/credentials/JwtAuth.credentials.ts
  packages/nodes-base/nodes/Twilio/TwilioTrigger.node.json
  packages/nodes-base/package.json
Labels: node/improvement, n8n team

#9121 fix(editor): Open links from embedded chat in new tab
  packages/@n8n/chat/package.json
  packages/@n8n/chat/src/components/Message.vue
  pnpm-lock.yaml
Labels: n8n team

#9120 fix(core): Support MySQL in `MoveSshKeysToDatabase` migration
  packages/cli/src/databases/migrations/common/1711390882123-MoveSshKeysToDatabase.ts
Labels: core, n8n team

#9118 feat(Summarize Node): Option to continue when field to summarize can't be found in any items
  packages/nodes-base/nodes/Transform/Summarize/Summarize.node.ts
  packages/nodes-base/nodes/Transform/Summarize/utils.ts
Labels: node/improvement, n8n team, node/issue

#9089 fix(editor): Render dates correctly in parameter hint
  packages/editor-ui/src/components/AssignmentCollection/Assignment.vue
  packages/editor-ui/src/components/ParameterInputWrapper.vue
  packages/editor-ui/src/utils/__tests__/expressions.test.ts
  packages/editor-ui/src/utils/expressions.ts
Labels: ui, n8n team

#9115 fix(Respond to Webhook Node): Continue on fail and error branch support
  packages/nodes-base/nodes/RespondToWebhook/RespondToWebhook.node.ts
Labels: n8n team, node/issue

#9122 fix(core): Add an option to add additional non-ui routes (no-changelog)
  packages/cli/src/Server.ts
  packages/cli/src/config/schema.ts
Labels: core, n8n team

#9136 refactor(core): Remove `waiting` status from active executions when fetching latest
  packages/cli/src/executions/execution.service.ts
  packages/cli/test/integration/execution.service.integration.test.ts
Labels: core, n8n team

#9112 fix(core): Don't create multiple owners when importing credentials or workflows
  packages/cli/src/commands/import/credentials.ts
  packages/cli/src/commands/import/workflow.ts
  packages/cli/src/services/import.service.ts
  packages/cli/test/integration/commands/credentials.cmd.test.ts
  packages/cli/test/integration/commands/import.cmd.test.ts
  packages/cli/test/integration/commands/importCredentials/credentials-updated.json
  packages/cli/test/integration/commands/importCredentials/separate/separate-credential.json
  packages/cli/test/integration/commands/importWorkflows/combined-with-update/original.json
  packages/cli/test/integration/commands/importWorkflows/combined-with-update/updated.json
  packages/cli/test/integration/import.service.test.ts
  packages/cli/test/integration/shared/db/credentials.ts
  packages/cli/test/integration/shared/db/workflows.ts
Labels: core, n8n team

#9077 fix(Gitlab Trigger Node): Fix typo (no-changelog)
  packages/nodes-base/nodes/Gitlab/GitlabTrigger.node.ts
Labels: node/improvement, community

#9094 feat(Github Node): Add option to get pull requests
  packages/nodes-base/nodes/Github/Github.node.ts
Labels: node/improvement, community

#9143 :rocket: Release 1.36.4
  CHANGELOG.md
  package.json
  packages/@n8n/nodes-langchain/package.json
  packages/cli/package.json
  packages/core/package.json
  packages/nodes-base/package.json
  packages/workflow/package.json
Labels: release

#9130 feat(Google Gemini Chat Model Node): Add support for new Google Gemini models
  packages/@n8n/nodes-langchain/credentials/GooglePalmApi.credentials.ts
  packages/@n8n/nodes-langchain/nodes/agents/Agent/Agent.node.ts
  packages/@n8n/nodes-langchain/nodes/chains/ChainLLM/ChainLlm.node.ts
  packages/@n8n/nodes-langchain/nodes/embeddings/EmbeddingsGoogleGemini/EmbeddingsGoogleGemini.node.ts
  packages/@n8n/nodes-langchain/nodes/embeddings/EmbeddingsGoogleGemini/google.svg
  packages/@n8n/nodes-langchain/nodes/llms/LmChatGoogleGemini/LmChatGoogleGemini.node.ts
  packages/@n8n/nodes-langchain/nodes/llms/LmChatGoogleGemini/google.svg
  packages/@n8n/nodes-langchain/nodes/llms/LmChatGoogleGemini/options.ts
  packages/@n8n/nodes-langchain/package.json
  packages/editor-ui/src/components/RunDataAi/useAiContentParsers.ts
  pnpm-lock.yaml
Labels: ui, n8n team

#9108 fix: Fix issue with Crowdstrike credential not working correctly
  packages/nodes-base/credentials/CrowdStrikeOAuth2Api.credentials.ts
Labels: node/improvement, n8n team

#9138 fix(HTTP Request Node): Tolerate header name being empty
  packages/nodes-base/nodes/HttpRequest/V3/HttpRequestV3.node.ts
  packages/nodes-base/nodes/HttpRequest/test/node/HttpRequest.test.ts
  packages/nodes-base/nodes/HttpRequest/test/node/workflow.get.json
Labels: node/improvement, n8n team

#9145 fix(Execute Workflow Node): Assign fallback pairedItem only if not present in output item and different length of input output
  packages/nodes-base/nodes/ExecuteWorkflow/ExecuteWorkflow.node.ts
Labels: n8n team, node/issue

#9149 fix(HTTP Request Node): Proxy IPv6 hostname fix (no-changelog)
  packages/core/src/NodeExecuteFunctions.ts
Labels: n8n team, node/issue

#9150 fix(Notion Node): Add itemIndex to API and operation errors
  packages/nodes-base/nodes/Notion/shared/GenericFunctions.ts
  packages/nodes-base/nodes/Notion/v2/NotionV2.node.ts
Labels: n8n team, node/issue

#9154 feat(core): Upgrade mysql2 to address CVE-2024-21507, CVE-2024-21508, and CVE-2024-21509
  packages/cli/package.json
  packages/nodes-base/package.json
  pnpm-lock.yaml
Labels: core, n8n team

#9158 fix(core): Exclude oAuth callback urls from browser-id checks
  packages/cli/src/auth/auth.service.ts
Labels: core, community

#9027 feat(core): Setup helmet.js for setting security headers
  packages/cli/package.json
  packages/cli/src/AbstractServer.ts
  packages/cli/src/Server.ts
  pnpm-lock.yaml
Labels: core, n8n team

#9006 refactor: Refactor ParameterInput to composition API + fix all TS errors (no-changelog)
  packages/design-system/src/components/N8nInput/Input.vue
  packages/design-system/src/types/index.ts
  packages/design-system/src/types/input.ts
  packages/editor-ui/src/components/ParameterInput.vue
  packages/editor-ui/src/components/__tests__/ParameterInput.test.ts
Labels: ui, n8n team

#9146 fix(Schedule Trigger Node): Default to 0 minute if falsy on hourly run
  packages/nodes-base/nodes/Schedule/GenericFunctions.ts
  packages/nodes-base/nodes/Schedule/ScheduleTrigger.node.ts
Labels: n8n team, node/issue

#9160 fix(Postgres Node): Convert js arrays to postgres type, if column type is ARRAY
  packages/nodes-base/nodes/Postgres/Postgres.node.ts
  packages/nodes-base/nodes/Postgres/test/v2/utils.test.ts
  packages/nodes-base/nodes/Postgres/v2/actions/database/insert.operation.ts
  packages/nodes-base/nodes/Postgres/v2/actions/database/update.operation.ts
  packages/nodes-base/nodes/Postgres/v2/actions/database/upsert.operation.ts
  packages/nodes-base/nodes/Postgres/v2/actions/versionDescription.ts
  packages/nodes-base/nodes/Postgres/v2/helpers/interfaces.ts
  packages/nodes-base/nodes/Postgres/v2/helpers/utils.ts
Labels: node/improvement, n8n team, node/issue

#9155 fix: Update sales templates card content (no-changelog)
  packages/editor-ui/src/views/WorkflowsView.vue
Labels: ui, community

#8840 feat: Add WhatsApp Business Trigger Node
  packages/nodes-base/credentials/WhatsAppTriggerApi.credentials.ts
  packages/nodes-base/nodes/Facebook/FacebookTrigger.node.ts
  packages/nodes-base/nodes/WhatsApp/GenericFunctions.ts
  packages/nodes-base/nodes/WhatsApp/WhatsAppTrigger.node.json
  packages/nodes-base/nodes/WhatsApp/WhatsAppTrigger.node.ts
  packages/nodes-base/nodes/WhatsApp/WhatsappDescription.ts
  packages/nodes-base/nodes/WhatsApp/types.ts
  packages/nodes-base/package.json
Labels: node/new, community

#9137 fix(editor): Fix parameter reset on credential change in Discord node
  cypress/e2e/5-ndv.cy.ts
  packages/editor-ui/src/components/NodeSettings.vue
Labels: ui, n8n team

#9161 fix(core): Improve browserId checks, and add logging
  package.json
  packages/@n8n/nodes-langchain/package.json
  packages/cli/src/auth/auth.service.ts
  packages/core/package.json
  packages/nodes-base/package.json
  packages/workflow/package.json
  patches/@types__express-serve-static-core@4.17.43.patch
  pnpm-lock.yaml
Labels: core, community

#9140 fix(editor): Fix expression preview when previous node is selected
  cypress/e2e/14-mapping.cy.ts
  packages/editor-ui/src/components/AssignmentCollection/Assignment.vue
Labels: ui, n8n team

#9157 fix(Respond to Webhook Node): Fix issue stopping form trigger response
  packages/nodes-base/nodes/RespondToWebhook/RespondToWebhook.node.ts
Labels: node/improvement, community

#9129 fix(editor): Prevent duplicate values in preview for SQL editor
  packages/editor-ui/src/components/ExpressionEdit.vue
  packages/editor-ui/src/components/ExpressionEditorModal/ExpressionEditorModalOutput.vue
  packages/editor-ui/src/components/InlineExpressionEditor/ExpressionOutput.vue
  packages/editor-ui/src/components/InlineExpressionEditor/InlineExpressionEditorOutput.vue
  packages/editor-ui/src/components/InlineExpressionEditor/__tests__/InlineExpressionEditorOutput.test.ts
  packages/editor-ui/src/components/SqlEditor/SqlEditor.vue
Labels: ui, n8n team

#9180 feat(Zammad Node): Add more options to the Organizations endpoint
  packages/nodes-base/nodes/Zammad/descriptions/OrganizationDescription.ts
Labels: node/improvement, n8n team

#9187 fix(editor): Fix sessionId for manual chat trigger execution
  packages/editor-ui/src/components/WorkflowLMChat.vue
Labels: ui, n8n team

#9175 fix(Google Sheets Node): Fix "Append or Update" on an empty sheet
  packages/editor-ui/src/components/ResourceMapper/ResourceMapper.vue
  packages/nodes-base/nodes/Google/Sheet/v2/actions/sheet/appendOrUpdate.operation.ts
  packages/nodes-base/nodes/Google/Sheet/v2/helpers/GoogleSheet.ts
Labels: node/improvement, ui, n8n team

#9181 feat(core): Allow assigning imported credentials and workflows to projects
  packages/cli/src/commands/import/credentials.ts
  packages/cli/src/commands/import/workflow.ts
  packages/cli/src/services/import.service.ts
  packages/cli/test/integration/commands/credentials.cmd.test.ts
  packages/cli/test/integration/commands/import.cmd.test.ts
  packages/cli/test/integration/import.service.test.ts
Labels: core, n8n team

#9197 fix(core): Truncate project and project relation table inbetween e2e tests
  packages/cli/src/controllers/e2e.controller.ts
Labels: core, n8n team

#9200 test: Re-enable node IO filter test for pinned data
  cypress/e2e/32-node-io-filter.cy.ts
Labels: n8n team

#9192 fix(editor): Make sticky node content parameter non require to support empty stickies
  cypress/e2e/25-stickies.cy.ts
  cypress/pages/workflow.ts
  packages/nodes-base/nodes/StickyNote/StickyNote.node.ts
Labels: node/improvement, n8n team

#9086 feat(Webhook Node): Setting to enable multiple outputs/methods
  packages/cli/src/TestWebhooks.ts
  packages/editor-ui/src/components/NodeWebhooks.vue
  packages/editor-ui/src/components/TriggerPanel.vue
  packages/editor-ui/src/composables/useWorkflowHelpers.ts
  packages/nodes-base/nodes/Webhook/Webhook.node.ts
  packages/nodes-base/nodes/Webhook/utils.ts
  packages/workflow/src/NodeHelpers.ts
Labels: node/improvement, n8n team

#9206 fix(core): Upgrade mysql2 to address CVE-2024-21511
  packages/cli/package.json
  packages/nodes-base/package.json
  pnpm-lock.yaml
Labels: core, n8n team

#9205 test(core): Re-enable and amend test for `n8n user-management:reset`
  packages/cli/test/integration/commands/reset.cmd.test.ts
Labels: core, n8n team

#9184 fix(Google Gemini Chat Model Node): Ping @google/generative-ai version (no-changelog)
  packages/@n8n/nodes-langchain/package.json
  pnpm-lock.yaml
Labels: n8n team

#9171 fix(Airtable Node): Do not allow to use deprecated api keys in v1
  packages/nodes-base/credentials/AirtableApi.credentials.ts
  packages/nodes-base/nodes/Airtable/v1/AirtableV1.node.ts
  packages/nodes-base/test/nodes/Airtable/Airtable.node.test.ts
  packages/workflow/src/Interfaces.ts
Labels: node/improvement, n8n team, node/issue

#9125 feat(HTTP Request Node): Option to provide SSL Certificates in Http Request Node
  packages/core/src/NodeExecuteFunctions.ts
  packages/core/test/NodeExecuteFunctions.test.ts
  packages/nodes-base/credentials/HttpSslAuth.credentials.ts
  packages/nodes-base/nodes/HttpRequest/GenericFunctions.ts
  packages/nodes-base/nodes/HttpRequest/V3/HttpRequestV3.node.ts
  packages/nodes-base/nodes/HttpRequest/interfaces.ts
  packages/nodes-base/nodes/HttpRequest/test/utils/utils.test.ts
  packages/nodes-base/package.json
  packages/workflow/src/Interfaces.ts
Labels: node/improvement, n8n team, node/issue

#9202 feat: Update source control to work with projects
  packages/cli/src/databases/entities/Project.ts
  packages/cli/src/databases/repositories/sharedCredentials.repository.ts
  packages/cli/src/environments/sourceControl/sourceControlExport.service.ee.ts
  packages/cli/src/environments/sourceControl/sourceControlImport.service.ee.ts
  packages/cli/src/environments/sourceControl/types/exportableCredential.ts
  packages/cli/src/environments/sourceControl/types/exportableWorkflow.ts
  packages/cli/src/environments/sourceControl/types/resourceOwner.ts
  packages/cli/src/utils.ts
  packages/cli/test/integration/environments/source-control-import.service.test.ts
Labels: core, n8n team

#9212 fix(core): Fix browser session refreshes not working
  packages/cli/src/auth/auth.service.ts
  packages/cli/test/unit/auth/auth.service.test.ts
Labels: core, n8n team

#9185 fix(Google Drive Node): Create from text operation
  packages/nodes-base/nodes/Google/Drive/test/v2/node/file/createFromText.test.ts
  packages/nodes-base/nodes/Google/Drive/v2/actions/file/createFromText.operation.ts
Labels: n8n team, node/issue

#9183 fix(Discord Node): When using OAuth2 authentication, check if user is a guild member when sending direct message
  packages/nodes-base/nodes/Discord/v2/actions/channel/deleteChannel.operation.ts
  packages/nodes-base/nodes/Discord/v2/actions/channel/get.operation.ts
  packages/nodes-base/nodes/Discord/v2/actions/channel/update.operation.ts
  packages/nodes-base/nodes/Discord/v2/actions/message/deleteMessage.operation.ts
  packages/nodes-base/nodes/Discord/v2/actions/message/get.operation.ts
  packages/nodes-base/nodes/Discord/v2/actions/message/getAll.operation.ts
  packages/nodes-base/nodes/Discord/v2/actions/message/react.operation.ts
  packages/nodes-base/nodes/Discord/v2/actions/message/send.operation.ts
  packages/nodes-base/nodes/Discord/v2/helpers/utils.ts
  packages/nodes-base/nodes/Discord/v2/methods/listSearch.ts
  packages/nodes-base/nodes/Discord/v2/transport/discord.api.ts
Labels: n8n team, node/issue

#9017 fix(editor): Take project permissions into account when checking resource permissions
  packages/editor-ui/src/__tests__/permissions.spec.ts
  packages/editor-ui/src/components/CredentialCard.vue
  packages/editor-ui/src/components/CredentialEdit/CredentialConfig.vue
  packages/editor-ui/src/components/CredentialEdit/CredentialEdit.vue
  packages/editor-ui/src/components/CredentialEdit/CredentialSharing.ee.vue
  packages/editor-ui/src/components/DuplicateWorkflowDialog.vue
  packages/editor-ui/src/components/MainHeader/WorkflowDetails.vue
  packages/editor-ui/src/components/VariablesRow.vue
  packages/editor-ui/src/components/WorkflowCard.vue
  packages/editor-ui/src/components/WorkflowSettings.vue
  packages/editor-ui/src/components/WorkflowShareModal.ee.vue
  packages/editor-ui/src/components/__tests__/ParameterInput.test.ts
  packages/editor-ui/src/composables/useWorkflowHelpers.ts
  packages/editor-ui/src/features/projects/components/ProjectTabs.vue
  packages/editor-ui/src/permissions.ts
  packages/editor-ui/src/plugins/i18n/locales/en.json
  packages/editor-ui/src/views/NodeView.vue
Labels: ui, n8n team

#8857 feat(Jira Software Node): Add Wiki Markup support for Jira Cloud comments
  packages/nodes-base/nodes/Jira/IssueCommentDescription.ts
  packages/nodes-base/nodes/Jira/Jira.node.ts
Labels: node/improvement, community

#8729 feat(Gmail Node): Add thread option for draft emails
  packages/nodes-base/nodes/Google/Gmail/v2/DraftDescription.ts
  packages/nodes-base/nodes/Google/Gmail/v2/GmailV2.node.ts
Labels: node/improvement, community

#8728 feat(Gmail Node): Add support for creating drafts using an alias
  packages/nodes-base/nodes/Google/Gmail/v2/DraftDescription.ts
  packages/nodes-base/nodes/Google/Gmail/v2/GmailV2.node.ts
Labels: node/improvement, community

#9214 feat(core): Make `project.name` required
  packages/cli/src/controllers/project.controller.ts
  packages/cli/src/databases/entities/Project.ts
  packages/cli/src/databases/migrations/common/1705928727784-CreateProject.ts
  packages/cli/src/environments/sourceControl/sourceControlExport.service.ee.ts
  packages/cli/src/services/ownership.service.ts
  packages/cli/src/services/project.service.ts
  packages/cli/test/integration/workflows/workflows.controller.test.ts
  packages/cli/test/unit/services/ownership.service.test.ts
  packages/cli/test/unit/shared/mockObjects.ts
Labels: core, n8n team

#9207 fix(MySQL Node): Query to statements splitting fix
  packages/nodes-base/nodes/MySql/MySql.node.ts
  packages/nodes-base/nodes/MySql/test/v2/utils.test.ts
  packages/nodes-base/nodes/MySql/v2/actions/versionDescription.ts
  packages/nodes-base/nodes/MySql/v2/helpers/utils.ts
Labels: n8n team, node/issue

#9189 feat(Wise Trigger Node): Add support for balance updates
  packages/nodes-base/nodes/Wise/GenericFunctions.ts
  packages/nodes-base/nodes/Wise/WiseTrigger.node.ts
Labels: node/improvement, community

#6918 feat(Microsoft To Do Node): Add an option to set a reminder when updating a task
  packages/nodes-base/nodes/Microsoft/ToDo/MicrosoftToDo.node.ts
  packages/nodes-base/nodes/Microsoft/ToDo/TaskDescription.ts
Labels: node/improvement, community

#9219 fix: Get workflow API sending shared data to the frontend
  packages/cli/src/workflows/workflows.controller.ts
  packages/cli/test/integration/workflows/workflows.controller.ee.test.ts
Labels: core, n8n team

#9208 feat(Pipedrive Node): Add busy and description options to activities
  packages/nodes-base/nodes/Pipedrive/Pipedrive.node.ts
Labels: node/improvement, community

#9216 fix(editor): RBAC FE fixes
  packages/design-system/src/components/N8nMenu/Menu.vue
  packages/editor-ui/src/components/CredentialEdit/CredentialEdit.vue
  packages/editor-ui/src/components/CredentialEdit/CredentialSharing.ee.vue
  packages/editor-ui/src/components/DuplicateWorkflowDialog.vue
  packages/editor-ui/src/components/WorkflowShareModal.ee.vue
  packages/editor-ui/src/features/projects/components/ProjectSharing.vue
  packages/editor-ui/src/features/projects/components/ProjectSharingInfo.vue
  packages/editor-ui/src/features/projects/components/ProjectTabs.vue
  packages/editor-ui/src/features/projects/components/__tests__/ProjectSharing.test.ts
  packages/editor-ui/src/features/projects/components/__tests__/ProjectTabs.test.ts
  packages/editor-ui/src/features/projects/components/__tests__/projects.utils.test.ts
  packages/editor-ui/src/features/projects/projects.utils.ts
  packages/editor-ui/src/plugins/i18n/locales/en.json
  packages/editor-ui/src/stores/workflowHistory.store.ts
  packages/editor-ui/src/stores/workflows.store.ts
  packages/editor-ui/src/utils/templates/templateActions.ts
Labels: ui, n8n team

#9218 fix: Return scopes on the personal the project endpoint
  packages/cli/src/controllers/project.controller.ts
  packages/cli/test/integration/project.api.test.ts
Labels: core, n8n team

#9196 feat(MISP Node): Rest search operations
  packages/nodes-base/nodes/Misp/GenericFunctions.ts
  packages/nodes-base/nodes/Misp/Misp.node.ts
  packages/nodes-base/nodes/Misp/descriptions/AttributeDescription.ts
  packages/nodes-base/nodes/Misp/descriptions/EventDescription.ts
  packages/nodes-base/nodes/Misp/descriptions/ObjectDescription.ts
  packages/nodes-base/nodes/Misp/descriptions/common.descriptions.ts
  packages/nodes-base/nodes/Misp/descriptions/index.ts
Labels: node/improvement, n8n team

#9229 fix(editor): Throw expression error on attempting to set variables at runtime
  packages/editor-ui/src/stores/environments.ee.store.ts
Labels: ui, n8n team

#9232 fix(editor): Fix read-only mode in inline expression editor
  packages/editor-ui/src/components/InlineExpressionEditor/InlineExpressionEditorInput.vue
  packages/editor-ui/src/components/ParameterOptions.vue
  packages/editor-ui/src/components/__tests__/ExpressionParameterInput.test.ts
Labels: ui, n8n team

#9227 fix(editor): Fix and report `settings` being `null` in workflow payloads (no-changelog)
  packages/editor-ui/src/stores/workflows.store.ts
Labels: ui, n8n team

#9233 fix: Elaborate scope of Sustainable Use License
  LICENSE.md
  packages/@n8n/chat/LICENSE.md
  packages/@n8n/nodes-langchain/LICENSE.md
  packages/cli/LICENSE.md
  packages/core/LICENSE.md
  packages/design-system/LICENSE.md
  packages/editor-ui/LICENSE.md
  packages/node-dev/LICENSE.md
  packages/nodes-base/LICENSE.md
  packages/workflow/LICENSE.md
Labels: n8n team

#9186 refactor(editor): Migrate header WorkflowDetails to composition api (no-changelog)
  packages/design-system/src/components/N8nActionDropdown/ActionDropdown.vue
  packages/design-system/src/css/tag.scss
  packages/design-system/src/types/action-dropdown.ts
  packages/design-system/src/types/index.ts
  packages/editor-ui/src/__tests__/setup.ts
  packages/editor-ui/src/components/MainHeader/MainHeader.vue
  packages/editor-ui/src/components/MainHeader/WorkflowDetails.spec.ts
  packages/editor-ui/src/components/MainHeader/WorkflowDetails.vue
  packages/editor-ui/src/components/TagsDropdown.vue
  packages/editor-ui/src/composables/useContextMenu.ts
  packages/editor-ui/src/n8n-theme.scss
Labels: ui, n8n team

#9193 feat(Wise Node): Add XML as supported format in getStatement operation
  packages/nodes-base/nodes/Wise/Wise.node.ts
  packages/nodes-base/nodes/Wise/descriptions/AccountDescription.ts
Labels: node/improvement, community

#8854 fix: Typo fixes in various descriptions (no-changelog)
  packages/cli/src/ActiveWorkflowRunner.ts
  packages/nodes-base/nodes/Chargebee/Chargebee.node.ts
  packages/nodes-base/nodes/Filter/V1/FilterV1.node.ts
  packages/nodes-base/nodes/Google/Sheet/v1/GoogleSheet.ts
  packages/nodes-base/nodes/Google/Sheet/v2/helpers/GoogleSheet.ts
  packages/nodes-base/nodes/Hunter/Hunter.node.ts
  packages/nodes-base/nodes/If/V1/IfV1.node.ts
  packages/nodes-base/nodes/Kafka/Kafka.node.ts
  packages/nodes-base/nodes/MQTT/Mqtt.node.ts
  packages/nodes-base/nodes/Mautic/GenericFunctions.ts
  packages/nodes-base/nodes/MondayCom/BoardItemDescription.ts
  packages/nodes-base/nodes/RabbitMQ/RabbitMQ.node.ts
  packages/nodes-base/nodes/Switch/V1/SwitchV1.node.ts
  packages/nodes-base/nodes/Switch/V2/SwitchV2.node.ts
Labels: node/improvement, core, community

#9224 fix(core): Add `view engine` to webhook server to support forms
  packages/cli/src/AbstractServer.ts
  packages/cli/src/Server.ts
Labels: community

#9244 docs: Update link to postgres example
  docker/images/n8n/README.md
Labels: n8n team

#9215 feat(Ollama Chat Model Node): Add aditional Ollama config parameters & fix vision
  packages/@n8n/nodes-langchain/nodes/chains/ChainLLM/ChainLlm.node.ts
  packages/@n8n/nodes-langchain/nodes/llms/LMChatOllama/LmChatOllama.node.ts
  packages/@n8n/nodes-langchain/nodes/llms/LMOllama/description.ts
Labels: n8n team

#9239 refactor(Structured Output Parser Node): Sandbox JSON schema parsing (no-changelog)
  packages/@n8n/nodes-langchain/nodes/output_parser/OutputParserStructured/OutputParserStructured.node.ts
  packages/@n8n/nodes-langchain/nodes/output_parser/OutputParserStructured/test/OutputParserStructured.node.test.ts
  packages/@n8n/nodes-langchain/package.json
  pnpm-lock.yaml
Labels: n8n team

#9240 fix(OpenAI Node): Allow to pass files ids as comma separated string in expressions (no-changelog)
  packages/@n8n/nodes-langchain/nodes/vendors/OpenAi/actions/assistant/create.operation.ts
  packages/@n8n/nodes-langchain/nodes/vendors/OpenAi/actions/assistant/update.operation.ts
Labels: n8n team, node/issue

#9252 refactor: Update Langchain dependencies (no-changelog)
  package.json
  packages/@n8n/nodes-langchain/nodes/agents/OpenAiAssistant/utils.ts
  packages/@n8n/nodes-langchain/nodes/tools/ToolCalculator/ToolCalculator.node.ts
  packages/@n8n/nodes-langchain/nodes/vendors/OpenAi/actions/assistant/message.operation.ts
  packages/@n8n/nodes-langchain/nodes/vendors/OpenAi/helpers/utils.ts
  packages/@n8n/nodes-langchain/package.json
  packages/cli/package.json
  packages/cli/src/services/ai/providers/openai.ts
  packages/workflow/package.json
  pnpm-lock.yaml
Labels: core, n8n team

#9254 ci: Update release-push-to-channel.yml (no-changelog)
  .github/workflows/release-push-to-channel.yml
Labels: n8n team

#9226 fix(editor): RBAC FE fixes 2
  packages/editor-ui/src/components/CredentialEdit/CredentialEdit.vue
  packages/editor-ui/src/components/CredentialEdit/CredentialSharing.ee.vue
  packages/editor-ui/src/components/MainHeader/WorkflowDetails.spec.ts
  packages/editor-ui/src/components/MainSidebar.vue
  packages/editor-ui/src/features/projects/components/ProjectSettings.vue
  packages/editor-ui/src/plugins/i18n/locales/en.json
  packages/editor-ui/src/views/WorkflowsView.vue
  packages/editor-ui/src/views/__tests__/WorkflowsView.test.ts
Labels: ui, n8n team

#9250 feat(Groq Chat Model Node): Add support for Groq chat models
  packages/@n8n/nodes-langchain/credentials/GroqApi.credentials.ts
  packages/@n8n/nodes-langchain/nodes/agents/Agent/Agent.node.ts
  packages/@n8n/nodes-langchain/nodes/llms/LmChatGroq/LmChatGroq.node.ts
  packages/@n8n/nodes-langchain/nodes/llms/LmChatGroq/groq.svg
  packages/@n8n/nodes-langchain/package.json
  packages/editor-ui/src/components/RunDataAi/RunDataAiContent.vue
  pnpm-lock.yaml
Labels: core, ui, n8n team

#9256 fix(core): Create personal projects for users created via LDAP
  packages/cli/src/Ldap/helpers.ts
  packages/cli/src/Ldap/ldap.service.ts
  packages/cli/test/integration/ldap/ldap.api.test.ts
Labels: core, n8n team

#9235 feat(core): Down migration for RBAC
  packages/cli/src/databases/dsl/Table.ts
  packages/cli/src/databases/migrations/common/1705928727784-CreateProject.ts
  packages/cli/src/databases/migrations/common/1714133768519-CreateProject.ts
  packages/cli/src/databases/migrations/mysqldb/index.ts
  packages/cli/src/databases/migrations/postgresdb/index.ts
  packages/cli/src/databases/migrations/sqlite/index.ts
Labels: core, n8n team

#9257 fix(core): Prevent node param resolution from failing telemetry graph generation
  packages/workflow/src/TelemetryHelpers.ts
  packages/workflow/test/TelemetryHelpers.test.ts
Labels: core, n8n team

#9258 fix(LangChain Code Node): Fix resolution of scoped langchain modules
  packages/@n8n/nodes-langchain/nodes/code/Code.node.ts
Labels: n8n team

#9262 fix(Customer.io Node): Update logo (no-changelog)
  packages/nodes-base/nodes/CustomerIo/customerio.svg
Labels: node/improvement, n8n team

#9261 fix(Baserow Node): Update logo (no-changelog)
  packages/nodes-base/nodes/Baserow/baserow.svg
Labels: node/improvement, n8n team
