Repository n8n-io/n8n, pull requests merged in 2025-05, with the labels that each got.

#14945 feat(editor): Support partial executions of tool nodes
  packages/cli/src/__tests__/load-nodes-and-credentials.test.ts
  packages/cli/src/load-nodes-and-credentials.ts
  packages/frontend/editor-ui/src/components/FromAiParametersModal.test.ts
  packages/frontend/editor-ui/src/components/FromAiParametersModal.vue
  packages/frontend/editor-ui/src/components/Modals.vue
  packages/frontend/editor-ui/src/components/NodeExecuteButton.vue
  packages/frontend/editor-ui/src/components/NodeSettings.vue
  packages/frontend/editor-ui/src/components/canvas/elements/nodes/CanvasNodeToolbar.test.ts
  packages/frontend/editor-ui/src/components/canvas/elements/nodes/CanvasNodeToolbar.vue
  packages/frontend/editor-ui/src/composables/useRunWorkflow.test.ts
  packages/frontend/editor-ui/src/composables/useRunWorkflow.ts
  packages/frontend/editor-ui/src/constants.ts
  packages/frontend/editor-ui/src/plugins/i18n/locales/en.json
  packages/frontend/editor-ui/src/stores/nodeTypes.store.ts
  packages/frontend/editor-ui/src/stores/parameterOverrides.store.ts
  packages/frontend/editor-ui/src/stores/parameterOverrides.test.ts
  packages/frontend/editor-ui/src/stores/ui.store.ts
  packages/frontend/editor-ui/src/utils/nodes/nodeTransforms.ts
  packages/frontend/editor-ui/src/views/NodeView.vue
  packages/workflow/src/FromAIParseUtils.ts
  packages/workflow/src/NodeHelpers.ts
Labels: core, ui, n8n team

#15038 fix(editor): Add missing uiStore import (no-changelog)
  packages/frontend/editor-ui/src/components/NodeExecuteButton.vue
Labels: n8n team

#15040 fix(editor): Fix workflow-builder feedback tracking (no-changelog)
  packages/frontend/editor-ui/src/components/AskAssistant/Agent/AskAssistantBuild.test.ts
  packages/frontend/editor-ui/src/components/AskAssistant/Agent/AskAssistantBuild.vue
Labels: n8n team

#15051 refactor(core): Set up `@n8n/backend-common` package
  codecov.yml
  packages/@n8n/backend-common/.eslintrc.js
  packages/@n8n/backend-common/jest.config.js
  packages/@n8n/backend-common/package.json
  packages/@n8n/backend-common/src/index.ts
  packages/@n8n/backend-common/tsconfig.build.json
  packages/@n8n/backend-common/tsconfig.json
  packages/cli/package.json
  packages/cli/tsconfig.json
  pnpm-lock.yaml
  turbo.json
Labels: core, n8n team

#15037 fix: Secure input handling in release workflow (no-changelog)
  .github/workflows/release-push-to-channel.yml
  .github/workflows/units-tests-dispatch.yml
Labels: n8n team

#15054 fix(editor): Nodes in disabled state appear in the logs (no-changelog)
  packages/frontend/editor-ui/src/components/CanvasChat/future/components/RunDataView.vue
  packages/frontend/editor-ui/src/components/RunDataAi/utils.test.ts
  packages/frontend/editor-ui/src/components/RunDataAi/utils.ts
  packages/frontend/editor-ui/src/composables/useRunWorkflow.test.ts
  packages/frontend/editor-ui/src/composables/useRunWorkflow.ts
Labels: n8n team

#15011 feat: Optimize langchain calls in a batching mode
  packages/@n8n/nodes-langchain/nodes/agents/Agent/agents/ToolsAgent/description.ts
  packages/@n8n/nodes-langchain/nodes/agents/Agent/agents/ToolsAgent/execute.ts
  packages/@n8n/nodes-langchain/nodes/chains/ChainLLM/ChainLlm.node.ts
  packages/@n8n/nodes-langchain/nodes/chains/ChainLLM/methods/config.ts
  packages/@n8n/nodes-langchain/nodes/chains/ChainLLM/test/ChainLlm.node.test.ts
  packages/@n8n/nodes-langchain/nodes/chains/ChainRetrievalQA/ChainRetrievalQa.node.ts
  packages/@n8n/nodes-langchain/nodes/chains/ChainRetrievalQA/test/ChainRetrievalQa.node.test.ts
  packages/@n8n/nodes-langchain/nodes/chains/ChainSummarization/V2/ChainSummarizationV2.node.ts
  packages/@n8n/nodes-langchain/nodes/chains/InformationExtractor/InformationExtractor.node.ts
  packages/@n8n/nodes-langchain/nodes/chains/InformationExtractor/test/InformationExtraction.node.test.ts
  packages/@n8n/nodes-langchain/nodes/chains/SentimentAnalysis/SentimentAnalysis.node.ts
  packages/@n8n/nodes-langchain/nodes/chains/TextClassifier/TextClassifier.node.ts
Labels: node/improvement, n8n team

#12271 feat(Google Workspace Admin Node): Google Admin Node Overhaul implementation
  packages/nodes-base/credentials/GSuiteAdminOAuth2Api.credentials.ts
  packages/nodes-base/nodes/Google/GSuiteAdmin/DeviceDescription.ts
  packages/nodes-base/nodes/Google/GSuiteAdmin/GSuiteAdmin.node.ts
  packages/nodes-base/nodes/Google/GSuiteAdmin/GenericFunctions.ts
  packages/nodes-base/nodes/Google/GSuiteAdmin/GroupDescripion.ts
  packages/nodes-base/nodes/Google/GSuiteAdmin/SearchFunctions.ts
  packages/nodes-base/nodes/Google/GSuiteAdmin/UserDescription.ts
  packages/nodes-base/nodes/Google/GSuiteAdmin/gSuiteAdmin.svg
  packages/nodes-base/nodes/Google/GSuiteAdmin/google-workspace-admin.png
  packages/nodes-base/nodes/Google/GSuiteAdmin/test/GSuiteAdmin.node.test.ts
  packages/nodes-base/nodes/Google/GSuiteAdmin/test/GenericFunctions.test.ts
  packages/nodes-base/nodes/Google/GSuiteAdmin/test/SearchFunctions.test.ts
  packages/nodes-base/nodes/Google/GSuiteAdmin/test/device/changeStatus.test.ts
  packages/nodes-base/nodes/Google/GSuiteAdmin/test/device/changeStatus.workflow.json
  packages/nodes-base/nodes/Google/GSuiteAdmin/test/device/get.test.ts
  packages/nodes-base/nodes/Google/GSuiteAdmin/test/device/get.workflow.json
  packages/nodes-base/nodes/Google/GSuiteAdmin/test/device/getAll.test.ts
  packages/nodes-base/nodes/Google/GSuiteAdmin/test/device/getAll.workflow.json
  packages/nodes-base/nodes/Google/GSuiteAdmin/test/device/update.test.ts
  packages/nodes-base/nodes/Google/GSuiteAdmin/test/device/update.workflow.json
  packages/nodes-base/nodes/Google/GSuiteAdmin/test/group/create.test.ts
  packages/nodes-base/nodes/Google/GSuiteAdmin/test/group/create.workflow.json
  packages/nodes-base/nodes/Google/GSuiteAdmin/test/group/delete.test.ts
  packages/nodes-base/nodes/Google/GSuiteAdmin/test/group/delete.workflow.json
  packages/nodes-base/nodes/Google/GSuiteAdmin/test/group/get.test.ts
  packages/nodes-base/nodes/Google/GSuiteAdmin/test/group/get.workflow.json
  packages/nodes-base/nodes/Google/GSuiteAdmin/test/group/getAll.test.ts
  packages/nodes-base/nodes/Google/GSuiteAdmin/test/group/getAll.workflow.json
  packages/nodes-base/nodes/Google/GSuiteAdmin/test/group/update.test.ts
  packages/nodes-base/nodes/Google/GSuiteAdmin/test/group/update.workflow.json
  packages/nodes-base/nodes/Google/GSuiteAdmin/test/user/addToGroup.test.ts
  packages/nodes-base/nodes/Google/GSuiteAdmin/test/user/addToGroup.workflow.json
  packages/nodes-base/nodes/Google/GSuiteAdmin/test/user/create.test.ts
  packages/nodes-base/nodes/Google/GSuiteAdmin/test/user/create.workflow.json
  packages/nodes-base/nodes/Google/GSuiteAdmin/test/user/delete.test.ts
  packages/nodes-base/nodes/Google/GSuiteAdmin/test/user/delete.workflow.json
  packages/nodes-base/nodes/Google/GSuiteAdmin/test/user/get.test.ts
  packages/nodes-base/nodes/Google/GSuiteAdmin/test/user/get.workflow.json
  packages/nodes-base/nodes/Google/GSuiteAdmin/test/user/getAll.test.ts
  packages/nodes-base/nodes/Google/GSuiteAdmin/test/user/getAll.workflow.json
  packages/nodes-base/nodes/Google/GSuiteAdmin/test/user/removeFromGroup.test.ts
  packages/nodes-base/nodes/Google/GSuiteAdmin/test/user/removeFromGroup.workflow.json
  packages/nodes-base/nodes/Google/GSuiteAdmin/test/user/update.test.ts
  packages/nodes-base/nodes/Google/GSuiteAdmin/test/user/update.workflow.json
Labels: node/improvement, community, in linear

#14885 feat(core): Add onlySharedWithMe filter to GET `/credentials` endpoint (no-changelog)
  packages/@n8n/api-types/src/dto/credentials/credentials-get-many-request.dto.ts
  packages/cli/src/credentials/credentials.controller.ts
  packages/cli/src/credentials/credentials.service.ts
  packages/cli/src/databases/repositories/credentials.repository.ts
  packages/cli/test/integration/credentials/credentials.api.test.ts
Labels: core, n8n team

#15048 feat(Calendly Trigger Node): Deprecation notice for apiKey authentication
  packages/nodes-base/nodes/Calendly/CalendlyTrigger.node.ts
Labels: node/improvement, n8n team, node/issue

#15052 fix(core): Manual execution defaults to Manual trigger
  packages/cli/src/__tests__/manual-execution.service.test.ts
  packages/cli/src/manual-execution.service.ts
Labels: core, n8n team

#14698 chore: Include Linear URL in PR Template (no-changelog)
  .github/pull_request_template.md
Labels: n8n team

#15063 feat(Anthropic Chat Model Node): Add configurable base URL for Anthropic API
  packages/@n8n/nodes-langchain/credentials/AnthropicApi.credentials.ts
  packages/@n8n/nodes-langchain/nodes/llms/LMChatAnthropic/LmChatAnthropic.node.ts
  packages/@n8n/nodes-langchain/nodes/llms/LMChatAnthropic/methods/__tests__/searchModels.test.ts
  packages/@n8n/nodes-langchain/nodes/llms/LMChatAnthropic/methods/searchModels.ts
Labels: n8n team

#15093 fix(core): Use manual tool description if neither resources or operations exist
  packages/core/src/execution-engine/node-execution-context/utils/__tests__/create-node-as-tool.test.ts
  packages/core/src/execution-engine/node-execution-context/utils/create-node-as-tool.ts
Labels: core, n8n team, release/backport

#15065 fix(editor): Only prompt for MFA code when email is updated
  cypress/e2e/27-two-factor-authentication.cy.ts
  packages/frontend/editor-ui/src/views/SettingsPersonalView.vue
Labels: n8n team

#15104 refactor(core): Overhaul community packages installation code
  packages/cli/src/services/__tests__/community-packages.service.test.ts
  packages/cli/src/services/community-packages.service.ts
Labels: core, n8n team

#15117 refactor(core): Change log-level for unregistered pushRef logging (no-changelog)
  packages/cli/src/push/abstract.push.ts
Labels: core, n8n team

#15126 feat(core): Improve nodeNameToToolName special characters normalization
  packages/@n8n/nodes-langchain/utils/helpers.ts
  packages/@n8n/nodes-langchain/utils/tests/helpers.test.ts
  packages/core/src/execution-engine/node-execution-context/utils/create-node-as-tool.ts
Labels: core, n8n team

#15111 fix(core): Fix task runner logging to browser console
  packages/@n8n/task-runner/src/js-task-runner/js-task-runner.ts
  packages/core/src/execution-engine/node-execution-context/__tests__/execute-context.test.ts
  packages/core/src/execution-engine/node-execution-context/execute-context.ts
Labels: core, n8n team

#15106 fix(core): Fix task runner validation error on array of arrays
  packages/@n8n/task-runner/src/js-task-runner/__tests__/result-validation.test.ts
  packages/@n8n/task-runner/src/js-task-runner/obj-utils.ts
  packages/@n8n/task-runner/src/js-task-runner/result-validation.ts
Labels: n8n team

#15078 fix: Center circular element in Milvus logo
  packages/@n8n/nodes-langchain/nodes/vector_store/VectorStoreMilvus/milvus-icon-white.svg
Labels: community, in linear

#15116 fix(editor): Fix context menu behaviour and rename shortcut indicator
  packages/frontend/editor-ui/src/components/canvas/Canvas.vue
  packages/frontend/editor-ui/src/composables/__snapshots__/useContextMenu.test.ts.snap
  packages/frontend/editor-ui/src/composables/useContextMenu.ts
Labels: n8n team

#15105 fix(editor): Fix sticky button disappearing on window resize
  packages/frontend/editor-ui/src/components/Node/NodeCreation.vue
Labels: n8n team

#15125 fix(editor): Increase hover delay and hit area for canvas toolbar edge
  packages/frontend/editor-ui/src/components/canvas/elements/edges/CanvasEdge.test.ts
  packages/frontend/editor-ui/src/components/canvas/elements/edges/CanvasEdge.vue
  packages/frontend/editor-ui/src/components/canvas/elements/edges/CanvasEdgeToolbar.vue
Labels: n8n team

#15098 refactor(core): Set up `@n8n/integration-test-utils` package
  codecov.yml
  packages/@n8n/integration-test-utils/.eslintrc.js
  packages/@n8n/integration-test-utils/package.json
  packages/@n8n/integration-test-utils/src/index.ts
  packages/@n8n/integration-test-utils/tsconfig.build.json
  packages/@n8n/integration-test-utils/tsconfig.json
  packages/cli/package.json
  packages/cli/tsconfig.json
  pnpm-lock.yaml
  turbo.json
Labels: core, n8n team

#15101 feat(editor): Preserve workflow list sort & page size preferences
  cypress/e2e/1-workflows.cy.ts
  packages/frontend/editor-ui/src/components/TagsDropdown.vue
  packages/frontend/editor-ui/src/components/layouts/ResourcesListLayout.test.ts
  packages/frontend/editor-ui/src/components/layouts/ResourcesListLayout.vue
  packages/frontend/editor-ui/src/composables/useN8nLocalStorage.test.ts
  packages/frontend/editor-ui/src/composables/useN8nLocalStorage.ts
  packages/frontend/editor-ui/src/constants.ts
  packages/frontend/editor-ui/src/views/WorkflowsView.vue
Labels: n8n team

#15142 fix: Folders typo in modal (no-changelog)
  packages/frontend/editor-ui/src/plugins/i18n/locales/en.json
Labels: n8n team

#15149 fix(editor): Fix workflow typings in a test with isArchived field (no-changelog)
  packages/frontend/editor-ui/src/components/layouts/ResourcesListLayout.test.ts
Labels: n8n team

#15147 fix(core): Support task runner in `execute` and `execute-batch` commands
  packages/cli/src/commands/__tests__/execute-batch.test.ts
  packages/cli/src/commands/__tests__/execute.test.ts
  packages/cli/src/commands/base-command.ts
  packages/cli/src/commands/execute-batch.ts
  packages/cli/src/commands/execute.ts
  packages/cli/src/commands/start.ts
  packages/cli/src/commands/worker.ts
Labels: core, n8n team

#15095 fix(Google Sheets Node): Return single row in read operation if combine conditions is OR and 'Return only First Matching Row'
  packages/nodes-base/nodes/Google/Sheet/GoogleSheets.node.ts
  packages/nodes-base/nodes/Google/Sheet/test/v2/helpers/GoogleSheet.test.ts
  packages/nodes-base/nodes/Google/Sheet/test/v2/utils/utils.test.ts
  packages/nodes-base/nodes/Google/Sheet/v2/actions/sheet/read.operation.ts
  packages/nodes-base/nodes/Google/Sheet/v2/actions/versionDescription.ts
  packages/nodes-base/nodes/Google/Sheet/v2/helpers/GoogleSheet.ts
Labels: n8n team, node/issue

#14452 fix(Microsoft Entra ID Node): Change Micosoft typo with Microsoft
  packages/nodes-base/nodes/Microsoft/Entra/MicrosoftEntra.node.ts
  packages/nodes-base/nodes/Microsoft/Entra/test/GroupDescription.test.ts
  packages/nodes-base/nodes/Microsoft/Entra/test/MicrosoftEntra.node.test.ts
  packages/nodes-base/nodes/Microsoft/Entra/test/UserDescription.test.ts
Labels: node/improvement, community, in linear

#15049 fix(editor): Fix AI Node Logs View to Filter Duplicate Executions
  cypress/e2e/233-AI-switch-to-logs-on-error.cy.ts
  cypress/e2e/30-langchain.cy.ts
  packages/core/src/execution-engine/node-execution-context/supply-data-context.ts
  packages/core/src/execution-engine/node-execution-context/utils/get-input-connection-data.ts
  packages/frontend/editor-ui/src/Interface.ts
  packages/frontend/editor-ui/src/components/RunDataAi/utils.test.ts
  packages/frontend/editor-ui/src/components/RunDataAi/utils.ts
Labels: core, n8n team

#15172 chore(core): Remove `role` table
  packages/cli/src/databases/migrations/common/1745934666077-DropRoleTable.ts
  packages/cli/src/databases/migrations/mysqldb/index.ts
  packages/cli/src/databases/migrations/postgresdb/index.ts
  packages/cli/src/databases/migrations/sqlite/index.ts
Labels: core, n8n team

#15174 fix: Remove external call and simplify test (no-changelog)
  cypress/e2e/19-execution.cy.ts
  cypress/fixtures/Multiple_trigger_node_rerun.json
Labels: n8n team

#15178 refactor(core): Expand error message for unknown webhook request
  packages/@n8n/db/src/entities/webhook-entity.ts
  packages/cli/src/webhooks/webhook-request-handler.ts
  packages/cli/src/webhooks/webhook.service.ts
Labels: core, n8n team

#15165 fix(core): Prioritize workflow execution with existing execution data on worker
  packages/cli/src/scaling/__tests__/job-processor.service.test.ts
  packages/cli/src/scaling/job-processor.ts
Labels: core, n8n team

#15170 fix(editor): Fix showing sub node logs when source is missing (no-changelog)
  packages/frontend/editor-ui/src/components/RunDataAi/utils.test.ts
  packages/frontend/editor-ui/src/components/RunDataAi/utils.ts
Labels: n8n team

#15191 chore: Clean up Schema Preview feature flag (no-changelog)
  packages/frontend/editor-ui/src/components/RunData.vue
  packages/frontend/editor-ui/src/components/VirtualSchema.vue
  packages/frontend/editor-ui/src/constants.ts
Labels: n8n team

#15064 feat(MCP Server Trigger Node): Handle multiple tool calls in mcp server trigger
  packages/@n8n/nodes-langchain/nodes/mcp/McpTrigger/McpServer.ts
  packages/@n8n/nodes-langchain/nodes/mcp/McpTrigger/__test__/McpServer.test.ts
  packages/@n8n/nodes-langchain/package.json
  pnpm-lock.yaml
Labels: n8n team

#15175 chore: Update license-sdk for extra renewal debugging (no-changelog)
  packages/cli/package.json
  pnpm-lock.yaml
Labels: core, n8n team

#15060 test(editor): Add e2e test cases for the logs view
  cypress/composables/executions.ts
  cypress/composables/logs.ts
  cypress/composables/workflow.ts
  cypress/e2e/50-logs.cy.ts
  cypress/fixtures/Workflow_ai_agent.json
  cypress/fixtures/Workflow_if.json
  cypress/fixtures/Workflow_loop.json
  packages/frontend/editor-ui/src/components/CanvasChat/future/components/LogsOverviewPanel.vue
  packages/frontend/editor-ui/src/components/CanvasChat/future/components/LogsOverviewRow.vue
  packages/frontend/editor-ui/src/composables/usePushConnection/handlers/executionFinished.ts
  packages/frontend/editor-ui/src/composables/usePushConnection/handlers/executionRecovered.ts
Labels: n8n team

#15140 feat(editor): Implement 'Shared with you' section in the main navigation
  packages/frontend/editor-ui/src/api/credentials.ts
  packages/frontend/editor-ui/src/api/workflows.ts
  packages/frontend/editor-ui/src/components/CredentialCard.vue
  packages/frontend/editor-ui/src/components/Folders/EmptySharedSectionActionBox.vue
  packages/frontend/editor-ui/src/components/Projects/ProjectHeader.test.ts
  packages/frontend/editor-ui/src/components/Projects/ProjectHeader.vue
  packages/frontend/editor-ui/src/components/Projects/ProjectNavigation.vue
  packages/frontend/editor-ui/src/components/Projects/ProjectTabs.vue
  packages/frontend/editor-ui/src/components/layouts/ResourcesListLayout.vue
  packages/frontend/editor-ui/src/composables/useN8nLocalStorage.test.ts
  packages/frontend/editor-ui/src/composables/useN8nLocalStorage.ts
  packages/frontend/editor-ui/src/composables/useProjectPages.ts
  packages/frontend/editor-ui/src/constants.ts
  packages/frontend/editor-ui/src/plugins/i18n/locales/en.json
  packages/frontend/editor-ui/src/plugins/icons/index.ts
  packages/frontend/editor-ui/src/routes/projects.routes.ts
  packages/frontend/editor-ui/src/stores/credentials.store.ts
  packages/frontend/editor-ui/src/stores/projects.store.ts
  packages/frontend/editor-ui/src/stores/workflows.store.ts
  packages/frontend/editor-ui/src/views/CredentialsView.vue
  packages/frontend/editor-ui/src/views/ExecutionsView.vue
  packages/frontend/editor-ui/src/views/WorkflowsView.test.ts
  packages/frontend/editor-ui/src/views/WorkflowsView.vue
Labels: n8n team

#15133 fix(editor): Ensure editor state updates during execution by using throttle instead of debounce (no-changelog)
  packages/frontend/editor-ui/src/components/canvas/WorkflowCanvas.test.ts
  packages/frontend/editor-ui/src/components/canvas/WorkflowCanvas.vue
Labels: n8n team

#15192 fix(Google Sheet Node): Refactor Google Sheets (no-changelog)
  packages/nodes-base/nodes/Google/Sheet/GoogleSheetsTrigger.node.ts
  packages/nodes-base/nodes/Google/Sheet/v2/actions/sheet/read.operation.ts
  packages/nodes-base/nodes/Google/Sheet/v2/actions/utils/readOperation.ts
  packages/nodes-base/nodes/Google/Sheet/v2/actions/versionDescription.ts
Labels: node/improvement, n8n team

#15207 fix(editor): Remove withDefaults import warning during dev and build (no-changelog)
  packages/frontend/editor-ui/src/components/InlineNameEdit.vue
Labels: n8n team

#15210 fix(editor): Fix chat package build warning related to types (no-changelog)
  packages/frontend/@n8n/chat/package.json
Labels: n8n team

#11767 feat(n8n AWS Cognito Node): New node
  packages/nodes-base/credentials/Aws.credentials.ts
  packages/nodes-base/nodes/Aws/Cognito/AwsCognito.node.json
  packages/nodes-base/nodes/Aws/Cognito/AwsCognito.node.ts
  packages/nodes-base/nodes/Aws/Cognito/cognito.svg
  packages/nodes-base/nodes/Aws/Cognito/descriptions/common.description.ts
  packages/nodes-base/nodes/Aws/Cognito/descriptions/group/Group.resource.ts
  packages/nodes-base/nodes/Aws/Cognito/descriptions/group/create.operation.ts
  packages/nodes-base/nodes/Aws/Cognito/descriptions/group/delete.operation.ts
  packages/nodes-base/nodes/Aws/Cognito/descriptions/group/get.operation.ts
  packages/nodes-base/nodes/Aws/Cognito/descriptions/group/getAll.operation.ts
  packages/nodes-base/nodes/Aws/Cognito/descriptions/group/update.operation.ts
  packages/nodes-base/nodes/Aws/Cognito/descriptions/index.ts
  packages/nodes-base/nodes/Aws/Cognito/descriptions/user/User.resource.ts
  packages/nodes-base/nodes/Aws/Cognito/descriptions/user/addToGroup.operation.ts
  packages/nodes-base/nodes/Aws/Cognito/descriptions/user/create.operation.ts
  packages/nodes-base/nodes/Aws/Cognito/descriptions/user/delete.operation.ts
  packages/nodes-base/nodes/Aws/Cognito/descriptions/user/get.operation.ts
  packages/nodes-base/nodes/Aws/Cognito/descriptions/user/getAll.operation.ts
  packages/nodes-base/nodes/Aws/Cognito/descriptions/user/removeFromGroup.operation.ts
  packages/nodes-base/nodes/Aws/Cognito/descriptions/user/update.operation.ts
  packages/nodes-base/nodes/Aws/Cognito/descriptions/userPool/UserPool.resource.ts
  packages/nodes-base/nodes/Aws/Cognito/descriptions/userPool/get.operation.ts
  packages/nodes-base/nodes/Aws/Cognito/helpers/constants.ts
  packages/nodes-base/nodes/Aws/Cognito/helpers/errorHandler.ts
  packages/nodes-base/nodes/Aws/Cognito/helpers/interfaces.ts
  packages/nodes-base/nodes/Aws/Cognito/helpers/utils.ts
  packages/nodes-base/nodes/Aws/Cognito/methods/index.ts
  packages/nodes-base/nodes/Aws/Cognito/methods/listSearch.ts
  packages/nodes-base/nodes/Aws/Cognito/test/group/create.test.ts
  packages/nodes-base/nodes/Aws/Cognito/test/group/create.workflow.json
  packages/nodes-base/nodes/Aws/Cognito/test/group/delete.test.ts
  packages/nodes-base/nodes/Aws/Cognito/test/group/delete.workflow.json
  packages/nodes-base/nodes/Aws/Cognito/test/group/get.test.ts
  packages/nodes-base/nodes/Aws/Cognito/test/group/get.workflow.json
  packages/nodes-base/nodes/Aws/Cognito/test/group/getAll.test.ts
  packages/nodes-base/nodes/Aws/Cognito/test/group/getAll.workflow.json
  packages/nodes-base/nodes/Aws/Cognito/test/group/update.test.ts
  packages/nodes-base/nodes/Aws/Cognito/test/group/update.workflow.json
  packages/nodes-base/nodes/Aws/Cognito/test/helpers/utils.test.ts
  packages/nodes-base/nodes/Aws/Cognito/test/listSearch/listSearch.test.ts
  packages/nodes-base/nodes/Aws/Cognito/test/user/addToGroup.test.ts
  packages/nodes-base/nodes/Aws/Cognito/test/user/addToGroup.workflow.json
  packages/nodes-base/nodes/Aws/Cognito/test/user/create.test.ts
  packages/nodes-base/nodes/Aws/Cognito/test/user/create.workflow.json
  packages/nodes-base/nodes/Aws/Cognito/test/user/delete.test.ts
  packages/nodes-base/nodes/Aws/Cognito/test/user/delete.workflow.json
  packages/nodes-base/nodes/Aws/Cognito/test/user/get.test.ts
  packages/nodes-base/nodes/Aws/Cognito/test/user/get.workflow.json
  packages/nodes-base/nodes/Aws/Cognito/test/user/getAll.test.ts
  packages/nodes-base/nodes/Aws/Cognito/test/user/getAll.workflow.json
  packages/nodes-base/nodes/Aws/Cognito/test/user/removeFromGroup.test.ts
  packages/nodes-base/nodes/Aws/Cognito/test/user/removeFromGroup.workflow.json
  packages/nodes-base/nodes/Aws/Cognito/test/user/update.test.ts
  packages/nodes-base/nodes/Aws/Cognito/test/user/update.workflow.json
  packages/nodes-base/nodes/Aws/Cognito/test/userPool/get.test.ts
  packages/nodes-base/nodes/Aws/Cognito/test/userPool/get.workflow.json
  packages/nodes-base/nodes/Aws/Cognito/transport/index.ts
  packages/nodes-base/package.json
Labels: node/improvement, node/new, community, in linear

#15198 feat(editor): Show different text when only archived filter is on (no-changelog)
  packages/frontend/editor-ui/src/components/layouts/ResourcesListLayout.test.ts
  packages/frontend/editor-ui/src/components/layouts/ResourcesListLayout.vue
  packages/frontend/editor-ui/src/plugins/i18n/locales/en.json
Labels: n8n team

#14988 fix(core): Add mechanism to prevent concurrent compaction on Insights
  packages/cli/src/modules/insights/__tests__/insights-compaction.service.test.ts
  packages/cli/src/modules/insights/database/repositories/__tests__/insights-by-period.repository.test.ts
  packages/cli/src/modules/insights/database/repositories/insights-by-period.repository.ts
Labels: core, n8n team

#15056 feat(editor): Show error on Execute Workflow Node if connected workflow is archived
  packages/frontend/editor-ui/src/Interface.ts
  packages/frontend/editor-ui/src/components/ParameterInput.test.ts
  packages/frontend/editor-ui/src/components/ParameterInput.vue
  packages/frontend/editor-ui/src/components/ResourceLocator/ResourceLocatorDropdown.vue
  packages/frontend/editor-ui/src/components/ResourceLocator/resourceLocator.scss
  packages/frontend/editor-ui/src/components/WorkflowSelectorParameterInput/WorkflowSelectorParameterInput.test.ts
  packages/frontend/editor-ui/src/components/WorkflowSelectorParameterInput/WorkflowSelectorParameterInput.vue
  packages/frontend/editor-ui/src/components/WorkflowSelectorParameterInput/useWorkflowResourcesLocator.ts
  packages/frontend/editor-ui/src/plugins/i18n/locales/en.json
Labels: n8n team

#15185 fix(editor): Issue with context menu disabling most options when importing template
  packages/frontend/editor-ui/src/composables/useCanvasOperations.test.ts
  packages/frontend/editor-ui/src/composables/useCanvasOperations.ts
  packages/frontend/editor-ui/src/stores/workflows.store.ts
  packages/frontend/editor-ui/src/views/NodeView.vue
Labels: n8n team

#15171 fix(editor): Fix Paired item error message
  cypress/e2e/39-projects.cy.ts
  cypress/e2e/5-ndv.cy.ts
  packages/workflow/src/WorkflowDataProxy.ts
  packages/workflow/test/WorkflowDataProxy.test.ts
Labels: core, n8n team

#15206 chore(editor): Validate SSO metadata url
  packages/frontend/editor-ui/src/plugins/i18n/locales/en.json
  packages/frontend/editor-ui/src/views/SettingsSso.test.ts
  packages/frontend/editor-ui/src/views/SettingsSso.vue
Labels: n8n team

#15214 feat(editor): Change WorkflowCard archived styles (no-changelog)
  packages/frontend/editor-ui/src/components/WorkflowCard.test.ts
  packages/frontend/editor-ui/src/components/WorkflowCard.vue
Labels: n8n team

#15199 fix(editor): Don't count archived WFs on tag usage counts (no-changelog)
  packages/cli/src/services/tag.service.ts
Labels: core, n8n team

#15220 feat(editor): Display archived tag on WorkflowHistory (no-changelog)
  packages/frontend/editor-ui/src/views/WorkflowHistory.test.ts
  packages/frontend/editor-ui/src/views/WorkflowHistory.vue
Labels: n8n team

#15100 refactor(core): Tear down `OrchestrationService`
  packages/@n8n/config/src/configs/logging.config.ts
  packages/cli/src/__tests__/active-workflow-manager.test.ts
  packages/cli/src/active-workflow-manager.ts
  packages/cli/src/commands/start.ts
  packages/cli/src/commands/webhook.ts
  packages/cli/src/commands/worker.ts
  packages/cli/src/controllers/debug.controller.ts
  packages/cli/src/scaling/multi-main-setup.ee.ts
  packages/cli/src/services/__tests__/orchestration.service.test.ts
  packages/cli/src/services/orchestration.service.ts
  packages/cli/src/workflows/workflow.service.ts
  packages/cli/test/integration/active-workflow-manager.test.ts
  packages/cli/test/integration/commands/worker.cmd.test.ts
  packages/cli/test/integration/public-api/workflows.test.ts
  packages/cli/test/integration/workflows/workflow.service.test.ts
Labels: core, n8n team

#15139 fix(editor): Fix importing workflow node renaming algorithm (no-changelog)
  packages/frontend/editor-ui/src/composables/useCanvasOperations.ts
Labels: n8n team

#15094 feat(Jina AI Node): Add Jina AI node
  packages/nodes-base/credentials/JinaAiApi.credentials.ts
  packages/nodes-base/nodes/JinaAI/JinaAi.node.json
  packages/nodes-base/nodes/JinaAI/JinaAi.node.ts
  packages/nodes-base/nodes/JinaAI/__test__/node/JinaAi.node.test.ts
  packages/nodes-base/nodes/JinaAI/__test__/node/deepResearch.workflow.json
  packages/nodes-base/nodes/JinaAI/__test__/node/fixtures/deepResearch.json
  packages/nodes-base/nodes/JinaAI/__test__/node/fixtures/read.json
  packages/nodes-base/nodes/JinaAI/__test__/node/fixtures/search.json
  packages/nodes-base/nodes/JinaAI/__test__/node/read.workflow.json
  packages/nodes-base/nodes/JinaAI/__test__/node/search.workflow.json
  packages/nodes-base/nodes/JinaAI/jinaAi.dark.svg
  packages/nodes-base/nodes/JinaAI/jinaAi.svg
  packages/nodes-base/package.json
Labels: node/new, n8n team

#15190 docs: Update doc links in azure cosmos db (no-changelog)
  packages/nodes-base/credentials/MicrosoftAzureCosmosDbSharedKeyApi.credentials.ts
  packages/nodes-base/nodes/Microsoft/AzureCosmosDb/AzureCosmosDb.node.json
Labels: node/improvement, n8n team

#13923 feat: Community Nodes in the Nodes Panel
  cypress/e2e/21-community-nodes.cy.ts
  packages/@n8n/api-types/src/community-node-types.ts
  packages/@n8n/api-types/src/frontend-settings.ts
  packages/@n8n/api-types/src/index.ts
  packages/@n8n/config/src/configs/nodes.config.ts
  packages/@n8n/config/test/config.test.ts
  packages/cli/src/controllers/__tests__/community-packages.controller.test.ts
  packages/cli/src/controllers/community-node-types.controller.ts
  packages/cli/src/controllers/community-packages.controller.ts
  packages/cli/src/load-nodes-and-credentials.ts
  packages/cli/src/requests.ts
  packages/cli/src/server.ts
  packages/cli/src/services/__tests__/community-packages.service.test.ts
  packages/cli/src/services/community-node-types.service.ts
  packages/cli/src/services/community-packages.service.ts
  packages/cli/src/services/frontend.service.ts
  packages/cli/src/utils/__tests__/community-nodes-request.test.ts
  packages/cli/src/utils/__tests__/npm-utils.test.ts
  packages/cli/src/utils/community-nodes-request-utils.ts
  packages/cli/src/utils/npm-utils.ts
  packages/frontend/@n8n/design-system/src/components/N8nNodeCreatorNode/NodeCreatorNode.vue
  packages/frontend/editor-ui/src/__tests__/defaults.ts
  packages/frontend/editor-ui/src/api/communityNodes.ts
  packages/frontend/editor-ui/src/api/nodeTypes.ts
  packages/frontend/editor-ui/src/components/ButtonParameter/ButtonParameter.vue
  packages/frontend/editor-ui/src/components/CommunityPackageCard.vue
  packages/frontend/editor-ui/src/components/CommunityPackageInstallModal.vue
  packages/frontend/editor-ui/src/components/CommunityPackageManageConfirmModal.vue
  packages/frontend/editor-ui/src/components/Node/NodeCreator/ItemTypes/CommunityNodeItem.vue
  packages/frontend/editor-ui/src/components/Node/NodeCreator/ItemTypes/NodeItem.vue
  packages/frontend/editor-ui/src/components/Node/NodeCreator/Modes/ActionsMode.vue
  packages/frontend/editor-ui/src/components/Node/NodeCreator/Modes/NodesMode.vue
  packages/frontend/editor-ui/src/components/Node/NodeCreator/Panel/CommunityNodeDetails.test.ts
  packages/frontend/editor-ui/src/components/Node/NodeCreator/Panel/CommunityNodeDetails.vue
  packages/frontend/editor-ui/src/components/Node/NodeCreator/Panel/CommunityNodeDocsLink.vue
  packages/frontend/editor-ui/src/components/Node/NodeCreator/Panel/CommunityNodeFooter.vue
  packages/frontend/editor-ui/src/components/Node/NodeCreator/Panel/CommunityNodeInfo.test.ts
  packages/frontend/editor-ui/src/components/Node/NodeCreator/Panel/CommunityNodeInfo.vue
  packages/frontend/editor-ui/src/components/Node/NodeCreator/Panel/CommunityNodeInstallHint.vue
  packages/frontend/editor-ui/src/components/Node/NodeCreator/Panel/NodesListPanel.vue
  packages/frontend/editor-ui/src/components/Node/NodeCreator/Renderers/CategorizedItemsRenderer.vue
  packages/frontend/editor-ui/src/components/Node/NodeCreator/Renderers/ItemsRenderer.vue
  packages/frontend/editor-ui/src/components/Node/NodeCreator/composables/useActionsGeneration.ts
  packages/frontend/editor-ui/src/components/Node/NodeCreator/composables/useViewStacks.ts
  packages/frontend/editor-ui/src/components/Node/NodeCreator/utils.test.ts
  packages/frontend/editor-ui/src/components/Node/NodeCreator/utils.ts
  packages/frontend/editor-ui/src/composables/usePushConnection/handlers/reloadNodeType.ts
  packages/frontend/editor-ui/src/plugins/i18n/locales/en.json
  packages/frontend/editor-ui/src/stores/communityNodes.store.ts
  packages/frontend/editor-ui/src/stores/nodeCreator.store.ts
  packages/frontend/editor-ui/src/stores/nodeTypes.store.ts
  packages/frontend/editor-ui/src/stores/settings.store.ts
  packages/frontend/editor-ui/src/utils/nodeIcon.test.ts
  packages/frontend/editor-ui/src/utils/nodeIcon.ts
  packages/frontend/editor-ui/src/views/SettingsCommunityNodesView.vue
Labels: ui, n8n team

#15177 fix(editor): Close Workflow URL Import Modal after import
  cypress/e2e/10-undo-redo.cy.ts
  cypress/e2e/39-import-workflow.cy.ts
  cypress/pages/workflow.ts
  packages/frontend/editor-ui/src/components/ImportWorkflowUrlModal.test.ts
  packages/frontend/editor-ui/src/components/ImportWorkflowUrlModal.vue
  packages/frontend/editor-ui/src/components/MainHeader/WorkflowDetails.vue
  packages/frontend/editor-ui/src/components/Modals.vue
  packages/frontend/editor-ui/src/constants.ts
  packages/frontend/editor-ui/src/stores/ui.store.ts
Labels: n8n team

#14468 feat(core): Implement Insights pruning system
  packages/cli/src/commands/start.ts
  packages/cli/src/modules/insights/__tests__/insights-collection.service.test.ts
  packages/cli/src/modules/insights/__tests__/insights-pruning.service.test.ts
  packages/cli/src/modules/insights/__tests__/insights.module.test.ts
  packages/cli/src/modules/insights/__tests__/insights.service.test.ts
  packages/cli/src/modules/insights/database/entities/__tests__/insights-by-period.test.ts
  packages/cli/src/modules/insights/database/repositories/insights-by-period.repository.ts
  packages/cli/src/modules/insights/insights-pruning.service.ts
  packages/cli/src/modules/insights/insights.config.ts
  packages/cli/src/modules/insights/insights.module.ts
  packages/cli/src/modules/insights/insights.service.ts
  packages/cli/src/services/pruning/__tests__/executions-pruning.service.test.ts
  packages/cli/src/services/pruning/executions-pruning.service.ts
  packages/cli/test/integration/pruning.service.test.ts
Labels: core, n8n team

#15180 refactor(core): Improve workflow activation logs
  packages/@n8n/config/src/configs/logging.config.ts
  packages/cli/src/__tests__/active-workflow-manager.test.ts
  packages/cli/src/active-workflow-manager.ts
  packages/cli/test/integration/active-workflow-manager.test.ts
Labels: core, n8n team

#15028 fix(core): Fix Insights concurrency issues for legacy sqlite
  packages/cli/src/modules/insights/__tests__/insights-collection.service.test.ts
  packages/cli/src/modules/insights/__tests__/insights-compaction.service.test.ts
  packages/cli/src/modules/insights/__tests__/insights.pre-init.test.ts
  packages/cli/src/modules/insights/__tests__/insights.service.test.ts
  packages/cli/src/modules/insights/insights-collection.service.ts
  packages/cli/src/modules/insights/insights.pre-init.ts
Labels: core, n8n team

#15262 fix(editor): Fix typo in empty state on the shared with you section (no-changelog)
  packages/frontend/editor-ui/src/plugins/i18n/locales/en.json
Labels: n8n team

#15057 feat(core): Archive workflows when removing folders without transfer
  packages/cli/src/controllers/folder.controller.ts
  packages/cli/src/databases/repositories/workflow.repository.ts
  packages/cli/src/services/folder.service.ts
  packages/cli/src/workflows/workflow.service.ts
  packages/cli/test/integration/folder/folder.controller.test.ts
  packages/frontend/editor-ui/src/plugins/i18n/locales/en.json
Labels: core, n8n team

#15195 fix(editor): Correct WF counts on folder with archived filter (no-changelog)
  packages/@n8n/db/src/repositories/folder.repository.ts
  packages/cli/src/controllers/folder.controller.ts
  packages/cli/src/databases/repositories/__tests__/folder.repository.test.ts
  packages/cli/src/databases/repositories/workflow.repository.ts
  packages/cli/src/services/folder.service.ts
  packages/cli/test/integration/folder/folder.controller.test.ts
Labels: core, n8n team

#15254 fix(editor): Sort start start nodes for manual execution by Y position
  packages/frontend/editor-ui/src/composables/useRunWorkflow.test.ts
  packages/frontend/editor-ui/src/composables/useRunWorkflow.ts
Labels: n8n team

#15168 feat(core): Implement partial execution for all tool nodes
  packages/@n8n/nodes-langchain/nodes/ToolExecutor/ToolExecutor.node.json
  packages/@n8n/nodes-langchain/nodes/ToolExecutor/ToolExecutor.node.ts
  packages/@n8n/nodes-langchain/nodes/ToolExecutor/test/ToolExecutor.node.test.ts
  packages/@n8n/nodes-langchain/nodes/ToolExecutor/test/convertToSchema.test.ts
  packages/@n8n/nodes-langchain/nodes/ToolExecutor/utils/convertToSchema.ts
  packages/@n8n/nodes-langchain/nodes/ToolExecutor/utils/executeTool.ts
  packages/@n8n/nodes-langchain/nodes/mcp/McpClientTool/McpClientTool.node.test.ts
  packages/@n8n/nodes-langchain/nodes/mcp/McpClientTool/loadOptions.ts
  packages/@n8n/nodes-langchain/package.json
  packages/cli/src/__tests__/load-nodes-and-credentials.test.ts
  packages/cli/src/load-nodes-and-credentials.ts
  packages/cli/src/manual-execution.service.ts
  packages/cli/src/workflows/__tests__/workflow-execution.service.test.ts
  packages/cli/src/workflows/workflow-execution.service.ts
  packages/cli/src/workflows/workflow.request.ts
  packages/core/src/execution-engine/__tests__/workflow-execute.test.ts
  packages/core/src/execution-engine/partial-execution-utils/__tests__/is-tool.test.ts
  packages/core/src/execution-engine/partial-execution-utils/__tests__/rewire-graph.test.ts
  packages/core/src/execution-engine/partial-execution-utils/is-tool.ts
  packages/core/src/execution-engine/partial-execution-utils/rewire-graph.ts
  packages/core/src/execution-engine/workflow-execute.ts
  packages/core/test/helpers/constants.ts
  packages/frontend/editor-ui/src/Interface.ts
  packages/frontend/editor-ui/src/components/FromAiParametersModal.test.ts
  packages/frontend/editor-ui/src/components/FromAiParametersModal.vue
  packages/frontend/editor-ui/src/components/NodeExecuteButton.vue
  packages/frontend/editor-ui/src/components/NodeSettings.vue
  packages/frontend/editor-ui/src/components/canvas/elements/nodes/CanvasNodeToolbar.vue
  packages/frontend/editor-ui/src/composables/useRunWorkflow.test.ts
  packages/frontend/editor-ui/src/composables/useRunWorkflow.ts
  packages/frontend/editor-ui/src/constants.ts
  packages/frontend/editor-ui/src/stores/agentRequest.store.test.ts
  packages/frontend/editor-ui/src/stores/agentRequest.store.ts
  packages/frontend/editor-ui/src/stores/nodeTypes.store.ts
  packages/frontend/editor-ui/src/utils/nodes/nodeTransforms.ts
  packages/frontend/editor-ui/src/views/NodeView.vue
  packages/workflow/src/Interfaces.ts
  packages/workflow/src/NodeHelpers.ts
  packages/workflow/test/NodeHelpers.test.ts
Labels: core, ui, n8n team

#15200 feat(editor): Allow jumping into sub-workflow with shortkey
  packages/frontend/editor-ui/src/components/ParameterInput.vue
  packages/frontend/editor-ui/src/components/ParameterInputFull.vue
  packages/frontend/editor-ui/src/components/ParameterOptions.vue
  packages/frontend/editor-ui/src/components/ResourceLocator/ResourceLocator.vue
  packages/frontend/editor-ui/src/components/canvas/Canvas.vue
  packages/frontend/editor-ui/src/components/canvas/elements/nodes/CanvasNode.vue
  packages/frontend/editor-ui/src/components/canvas/elements/nodes/render-types/CanvasNodeDefault.vue
  packages/frontend/editor-ui/src/composables/__snapshots__/useContextMenu.test.ts.snap
  packages/frontend/editor-ui/src/composables/useCanvasOperations.ts
  packages/frontend/editor-ui/src/composables/useContextMenu.test.ts
  packages/frontend/editor-ui/src/composables/useContextMenu.ts
  packages/frontend/editor-ui/src/plugins/i18n/locales/en.json
  packages/frontend/editor-ui/src/utils/mappingUtils.ts
  packages/frontend/editor-ui/src/utils/nodeTypesUtils.ts
  packages/frontend/editor-ui/src/utils/typeGuards.ts
  packages/frontend/editor-ui/src/views/NodeView.vue
  packages/workflow/src/NodeHelpers.ts
  packages/workflow/src/WorkflowDataProxy.ts
  packages/workflow/src/index.ts
  packages/workflow/src/type-guards.ts
Labels: n8n team

#15305 fix: Community nodes - setting page empty state
  packages/cli/src/services/__tests__/community-packages.service.test.ts
  packages/cli/src/services/community-packages.service.ts
  packages/frontend/editor-ui/src/components/Node/NodeCreator/Modes/ActionsMode.vue
  packages/frontend/editor-ui/src/components/Node/NodeCreator/Panel/CommunityNodeFooter.test.ts
  packages/frontend/editor-ui/src/components/Node/NodeCreator/Panel/CommunityNodeFooter.vue
  packages/frontend/editor-ui/src/components/Node/NodeCreator/Panel/CommunityNodeInfo.vue
  packages/frontend/editor-ui/src/components/Node/NodeCreator/Panel/NodesListPanel.vue
  packages/frontend/editor-ui/src/plugins/i18n/locales/en.json
  packages/frontend/editor-ui/src/views/SettingsCommunityNodesView.vue
Labels: core, ui, n8n team

#15251 refactor(core): Remove unused deprecated license methods
  packages/cli/src/license.ts
Labels: core, n8n team

#15249 docs: Lowercase xAI credentials documentation link (no-changelog)
  packages/@n8n/nodes-langchain/credentials/XAiApi.credentials.ts
Labels: n8n team

#15310 refactor(core): Move settings repository to @n8n/db
  packages/@n8n/db/src/repositories/index.ts
  packages/@n8n/db/src/repositories/settings.repository.ts
  packages/cli/src/__tests__/external-hooks.test.ts
  packages/cli/src/commands/ldap/reset.ts
  packages/cli/src/commands/start.ts
  packages/cli/src/commands/user-management/reset.ts
  packages/cli/src/controllers/__tests__/owner.controller.test.ts
  packages/cli/src/controllers/e2e.controller.ts
  packages/cli/src/controllers/owner.controller.ts
  packages/cli/src/databases/repositories/settings.repository.ts
  packages/cli/src/environments.ee/source-control/source-control-preferences.service.ee.ts
  packages/cli/src/external-hooks.ts
  packages/cli/src/external-secrets.ee/__tests__/external-secrets-manager.ee.test.ts
  packages/cli/src/external-secrets.ee/external-secrets-manager.ee.ts
  packages/cli/src/ldap.ee/__tests__/ldap.service.test.ts
  packages/cli/src/ldap.ee/ldap.service.ee.ts
  packages/cli/src/license.ts
  packages/cli/src/services/__tests__/banner.service.test.ts
  packages/cli/src/services/__tests__/hooks.service.test.ts
  packages/cli/src/services/banner.service.ts
  packages/cli/src/services/hooks.service.ts
  packages/cli/src/sso.ee/saml/__tests__/saml.service.ee.test.ts
  packages/cli/src/sso.ee/saml/saml.service.ee.ts
  packages/cli/src/sso.ee/sso-helpers.ts
  packages/cli/test/integration/commands/reset.cmd.test.ts
  packages/cli/test/integration/external-secrets/external-secrets.api.test.ts
  packages/cli/test/integration/shared/ldap.ts
  packages/cli/test/integration/shared/utils/index.ts
Labels: core, n8n team

#15315 feat(API): Add Public API endpoint for updating variables
  packages/@n8n/permissions/src/constants.ee.ts
  packages/cli/src/public-api/v1/handlers/variables/spec/paths/variables.id.yml
  packages/cli/src/public-api/v1/handlers/variables/variables.handler.ts
  packages/cli/test/integration/public-api/variables.test.ts
Labels: core, n8n team

#15304 perf(editor): Avoid deep watch on execution result data
  packages/frontend/editor-ui/src/components/CanvasChat/future/composables/useExecutionData.ts
  packages/frontend/editor-ui/src/stores/assistant.store.ts
  packages/frontend/editor-ui/src/stores/workflows.store.ts
Labels: n8n team

#15302 fix(editor): Make `AI Agent` appear before `Magento 2` when typing `agent`
  packages/@n8n/utils/src/search/sublimeSearch.test.ts
  packages/@n8n/utils/src/search/sublimeSearch.ts
Labels: n8n team

#15318 refactor(core): Move webhook repository to `@n8n/db`
  packages/@n8n/db/src/repositories/index.ts
  packages/@n8n/db/src/repositories/webhook.repository.ts
  packages/cli/src/webhooks/__tests__/webhook.service.test.ts
  packages/cli/src/webhooks/webhook.service.ts
Labels: core, n8n team

#15319 chore(core): Remove unused `database` field from `ModulePreInitContext`
  packages/cli/src/commands/base-command.ts
  packages/cli/src/modules/insights/__tests__/insights.pre-init.test.ts
  packages/cli/src/modules/modules.config.ts
Labels: core, n8n team

#13734 feat(Respond to Webhook Node): Additional output branch - Response
  packages/frontend/editor-ui/src/constants.ts
  packages/nodes-base/nodes/RespondToWebhook/RespondToWebhook.node.ts
  packages/nodes-base/nodes/RespondToWebhook/test/RespondToWebhook.test.ts
  packages/nodes-base/nodes/RespondToWebhook/test/utils.test.ts
  packages/nodes-base/nodes/RespondToWebhook/utils.ts
Labels: node/improvement, n8n team

#15336 fix(editor): Tag styling issues
  packages/frontend/@n8n/design-system/src/components/N8nTag/Tag.vue
  packages/frontend/@n8n/design-system/src/components/N8nTags/Tags.vue
  packages/frontend/@n8n/design-system/src/css/tag.scss
  packages/frontend/editor-ui/src/components/TagsContainer.vue
  packages/frontend/editor-ui/src/components/TagsDropdown.vue
Labels: n8n team

#15322 fix: Ensure diagnostics stay disabled in e2e even when enabled by environment variable
  packages/cli/src/config/index.ts
Labels: core, n8n team

#14833 feat(Snowflake Node): Add support for Key-Pair authentication
  packages/nodes-base/credentials/Snowflake.credentials.ts
  packages/nodes-base/nodes/Snowflake/GenericFunctions.ts
  packages/nodes-base/nodes/Snowflake/Snowflake.node.ts
  packages/nodes-base/nodes/Snowflake/__tests__/GenericFunctions.test.ts
Labels: node/improvement, n8n team

#15335 fix(Azure OpenAI Chat Model Node): Simplify Azure Entra ID Authentication and Auto-Refresh token
  packages/@n8n/client-oauth2/src/CredentialsFlow.ts
  packages/@n8n/nodes-langchain/credentials/AzureEntraCognitiveServicesOAuth2Api.credentials.ts
  packages/@n8n/nodes-langchain/nodes/llms/LmChatAzureOpenAi/__tests__/N8nOAuth2TokenCredential.test.ts
  packages/@n8n/nodes-langchain/nodes/llms/LmChatAzureOpenAi/credentials/N8nOAuth2TokenCredential.ts
Labels: n8n team

#15341 fix(core): Upgrade formidable to address CVE-2025-46653
  package.json
  packages/cli/package.json
  pnpm-lock.yaml
Labels: core, n8n team

#15347 fix: Corrects success response code to match handler (no-changelog)
  packages/cli/src/public-api/v1/handlers/variables/spec/paths/variables.id.yml
Labels: core, n8n team

#15324 refactor(core): Migrate DB setup to use DI
  packages/@n8n/config/src/configs/instance-settings-config.ts
  packages/@n8n/config/src/index.ts
  packages/cli/src/abstract-server.ts
  packages/cli/src/commands/__tests__/execute-batch.test.ts
  packages/cli/src/commands/__tests__/execute.test.ts
  packages/cli/src/commands/base-command.ts
  packages/cli/src/commands/db/revert.ts
  packages/cli/src/commands/import/credentials.ts
  packages/cli/src/credentials/credentials.controller.ts
  packages/cli/src/credentials/credentials.service.ts
  packages/cli/src/databases/__tests__/db-connection-options.test.ts
  packages/cli/src/databases/__tests__/db-connection.test.ts
  packages/cli/src/databases/config.ts
  packages/cli/src/databases/db-connection-options.ts
  packages/cli/src/databases/db-connection.ts
  packages/cli/src/db.ts
  packages/cli/src/evaluation.ee/test-runner/__tests__/test-runner.service.ee.test.ts
  packages/cli/src/evaluation.ee/test-runner/test-runner.service.ee.ts
  packages/cli/src/ldap.ee/helpers.ee.ts
  packages/cli/src/public-api/v1/handlers/credentials/credentials.service.ts
  packages/cli/src/public-api/v1/handlers/workflows/workflows.service.ts
  packages/cli/src/scaling/__tests__/worker-server.test.ts
  packages/cli/src/scaling/worker-server.ts
  packages/cli/src/services/__tests__/public-api-key.service.test.ts
  packages/cli/src/services/import.service.ts
  packages/cli/src/services/pruning/__tests__/executions-pruning.service.test.ts
  packages/cli/src/services/pruning/executions-pruning.service.ts
  packages/cli/src/workflows/workflows.controller.ts
  packages/cli/test/integration/executions-pruning.service.test.ts
  packages/cli/test/integration/import.service.test.ts
  packages/cli/test/integration/shared/test-db.ts
  packages/core/src/instance-settings/__tests__/instance-settings.test.ts
  packages/core/src/instance-settings/instance-settings.ts
  packages/core/src/logging/__tests__/logger.test.ts
  packages/core/src/logging/logger.ts
Labels: core, n8n team

#15243 feat: Optimise langchain calls in batching mode
  packages/@n8n/nodes-langchain/nodes/agents/Agent/Agent.node.ts
  packages/@n8n/nodes-langchain/nodes/agents/Agent/V1/AgentV1.node.ts
  packages/@n8n/nodes-langchain/nodes/agents/Agent/V2/AgentV2.node.ts
  packages/@n8n/nodes-langchain/nodes/agents/Agent/agents/ToolsAgent/V1/description.ts
  packages/@n8n/nodes-langchain/nodes/agents/Agent/agents/ToolsAgent/V1/execute.ts
  packages/@n8n/nodes-langchain/nodes/agents/Agent/agents/ToolsAgent/V2/description.ts
  packages/@n8n/nodes-langchain/nodes/agents/Agent/agents/ToolsAgent/V2/execute.ts
  packages/@n8n/nodes-langchain/nodes/agents/Agent/agents/ToolsAgent/common.ts
  packages/@n8n/nodes-langchain/nodes/agents/Agent/agents/ToolsAgent/description.ts
  packages/@n8n/nodes-langchain/nodes/agents/Agent/agents/ToolsAgent/options.ts
  packages/@n8n/nodes-langchain/nodes/agents/Agent/test/ToolsAgent/ToolsAgentV1.test.ts
  packages/@n8n/nodes-langchain/nodes/agents/Agent/test/ToolsAgent/ToolsAgentV2.test.ts
  packages/@n8n/nodes-langchain/nodes/agents/Agent/test/ToolsAgent/commons.test.ts
  packages/@n8n/nodes-langchain/nodes/chains/ChainLLM/ChainLlm.node.ts
  packages/@n8n/nodes-langchain/nodes/chains/ChainLLM/methods/config.ts
  packages/@n8n/nodes-langchain/nodes/chains/ChainLLM/methods/processItem.ts
  packages/@n8n/nodes-langchain/nodes/chains/ChainLLM/test/ChainLlm.node.test.ts
  packages/@n8n/nodes-langchain/nodes/chains/ChainRetrievalQA/ChainRetrievalQa.node.ts
  packages/@n8n/nodes-langchain/nodes/chains/ChainRetrievalQA/constants.ts
  packages/@n8n/nodes-langchain/nodes/chains/ChainRetrievalQA/processItem.ts
  packages/@n8n/nodes-langchain/nodes/chains/ChainRetrievalQA/test/ChainRetrievalQa.node.test.ts
  packages/@n8n/nodes-langchain/nodes/chains/ChainSummarization/ChainSummarization.node.ts
  packages/@n8n/nodes-langchain/nodes/chains/ChainSummarization/V2/ChainSummarizationV2.node.ts
  packages/@n8n/nodes-langchain/nodes/chains/ChainSummarization/V2/processItem.ts
  packages/@n8n/nodes-langchain/nodes/chains/InformationExtractor/InformationExtractor.node.ts
  packages/@n8n/nodes-langchain/nodes/chains/InformationExtractor/constants.ts
  packages/@n8n/nodes-langchain/nodes/chains/InformationExtractor/processItem.ts
  packages/@n8n/nodes-langchain/nodes/chains/InformationExtractor/test/InformationExtraction.node.test.ts
  packages/@n8n/nodes-langchain/nodes/chains/SentimentAnalysis/SentimentAnalysis.node.ts
  packages/@n8n/nodes-langchain/nodes/chains/TextClassifier/TextClassifier.node.ts
  packages/@n8n/nodes-langchain/nodes/chains/TextClassifier/constants.ts
  packages/@n8n/nodes-langchain/nodes/chains/TextClassifier/processItem.ts
  packages/@n8n/nodes-langchain/utils/sharedFields.ts
  packages/frontend/editor-ui/src/stores/workflows.store.test.ts
  packages/frontend/editor-ui/src/stores/workflows.store.ts
Labels: n8n team

#15163 feat(editor): Show sub workflow runs in the log view
  packages/frontend/editor-ui/src/__tests__/mocks.ts
  packages/frontend/editor-ui/src/components/CanvasChat/__test__/data.ts
  packages/frontend/editor-ui/src/components/CanvasChat/future/LogsPanel.test.ts
  packages/frontend/editor-ui/src/components/CanvasChat/future/LogsPanel.vue
  packages/frontend/editor-ui/src/components/CanvasChat/future/components/LogDetailsPanel.test.ts
  packages/frontend/editor-ui/src/components/CanvasChat/future/components/LogDetailsPanel.vue
  packages/frontend/editor-ui/src/components/CanvasChat/future/components/LogsOverviewPanel.test.ts
  packages/frontend/editor-ui/src/components/CanvasChat/future/components/LogsOverviewPanel.vue
  packages/frontend/editor-ui/src/components/CanvasChat/future/components/LogsOverviewRow.vue
  packages/frontend/editor-ui/src/components/CanvasChat/future/components/RunDataView.vue
  packages/frontend/editor-ui/src/components/CanvasChat/future/composables/useExecutionData.test.ts
  packages/frontend/editor-ui/src/components/CanvasChat/future/composables/useExecutionData.ts
  packages/frontend/editor-ui/src/components/CanvasChat/types/logs.ts
  packages/frontend/editor-ui/src/components/RunData.vue
  packages/frontend/editor-ui/src/components/RunDataAi/utils.test.ts
  packages/frontend/editor-ui/src/components/RunDataAi/utils.ts
  packages/frontend/editor-ui/src/composables/useNodeHelpers.ts
Labels: n8n team

#15349 ci: Upgrade frontend dev-tooling to address a couple of "vulnerable" dependencies (no-changelog)
  packages/frontend/@n8n/chat/package.json
  packages/frontend/@n8n/design-system/package.json
  pnpm-lock.yaml
  pnpm-workspace.yaml
Labels: n8n team

#15346 fix: Set `tournament` for nodes test harness
  packages/core/nodes-testing/node-test-harness.ts
  packages/nodes-base/nodes/Microsoft/Entra/test/UserDescription.test.ts
Labels: node/improvement, core, n8n team

#15250 fix(AI Agent Node): Fix tool calling when tools run in a loop
  packages/@n8n/nodes-langchain/nodes/tools/ToolWorkflow/v2/ToolWorkflowV2.node.ts
  packages/@n8n/nodes-langchain/nodes/tools/ToolWorkflow/v2/ToolWorkflowV2.test.ts
  packages/@n8n/nodes-langchain/nodes/tools/ToolWorkflow/v2/utils/WorkflowToolService.ts
  packages/core/src/execution-engine/node-execution-context/__tests__/supply-data-context.test.ts
  packages/core/src/execution-engine/node-execution-context/supply-data-context.ts
  packages/core/src/execution-engine/node-execution-context/utils/__tests__/get-input-connection-data.test.ts
  packages/core/src/execution-engine/node-execution-context/utils/get-input-connection-data.ts
  packages/workflow/src/Interfaces.ts
Labels: core, n8n team

#15348 refactor(core): Restructure decorators and add tests
  packages/@n8n/decorators/jest.config.js
  packages/@n8n/decorators/src/__tests__/redactable.test.ts
  packages/@n8n/decorators/src/controller/__tests__/args.test.ts
  packages/@n8n/decorators/src/controller/__tests__/controller-registry-metadata.test.ts
  packages/@n8n/decorators/src/controller/__tests__/license.test.ts
  packages/@n8n/decorators/src/controller/__tests__/rest-controller.test.ts
  packages/@n8n/decorators/src/controller/__tests__/route.test.ts
  packages/@n8n/decorators/src/controller/__tests__/scoped.test.ts
  packages/@n8n/decorators/src/controller/args.ts
  packages/@n8n/decorators/src/controller/controller-registry-metadata.ts
  packages/@n8n/decorators/src/controller/index.ts
  packages/@n8n/decorators/src/controller/licensed.ts
  packages/@n8n/decorators/src/controller/middleware.ts
  packages/@n8n/decorators/src/controller/rest-controller.ts
  packages/@n8n/decorators/src/controller/route.ts
  packages/@n8n/decorators/src/controller/scoped.ts
  packages/@n8n/decorators/src/controller/types.ts
  packages/@n8n/decorators/src/execution-lifecycle/__tests__/on-lifecycle-event.test.ts
  packages/@n8n/decorators/src/execution-lifecycle/index.ts
  packages/@n8n/decorators/src/execution-lifecycle/lifecycle-metadata.ts
  packages/@n8n/decorators/src/execution-lifecycle/on-lifecycle-event.ts
  packages/@n8n/decorators/src/index.ts
  packages/@n8n/decorators/src/module/__tests__/module.test.ts
  packages/@n8n/decorators/src/module/index.ts
  packages/@n8n/decorators/src/module/module-metadata.ts
  packages/@n8n/decorators/src/module/module.ts
  packages/@n8n/decorators/src/multi-main-metadata.ts
  packages/@n8n/decorators/src/multi-main/__tests__/on-multi-main-event.test.ts
  packages/@n8n/decorators/src/multi-main/index.ts
  packages/@n8n/decorators/src/multi-main/multi-main-metadata.ts
  packages/@n8n/decorators/src/multi-main/on-multi-main-event.ts
  packages/@n8n/decorators/src/shutdown/__tests__/on-shutdown.test.ts
  packages/@n8n/decorators/src/shutdown/index.ts
  packages/@n8n/decorators/src/shutdown/on-shutdown.ts
  packages/@n8n/decorators/src/shutdown/shutdown-registry-metadata.ts
  packages/@n8n/decorators/src/shutdown/types.ts
  packages/@n8n/decorators/src/types.ts
  packages/cli/src/commands/base-command.ts
  packages/cli/src/modules/module-registry.ts
  packages/cli/src/shutdown/__tests__/shutdown.service.test.ts
Labels: n8n team

#15352 refactor(core): Move `UserRepository` and subscribers to `@n8n/db`
  packages/@n8n/db/src/index.ts
  packages/@n8n/db/src/repositories/index.ts
  packages/@n8n/db/src/repositories/user.repository.ts
  packages/@n8n/db/src/subscribers/index.ts
  packages/@n8n/db/src/subscribers/user-subscriber.ts
  packages/cli/src/__tests__/external-hooks.test.ts
  packages/cli/src/auth/__tests__/auth.service.test.ts
  packages/cli/src/auth/auth.service.ts
  packages/cli/src/auth/methods/email.ts
  packages/cli/src/collaboration/collaboration.service.ts
  packages/cli/src/commands/community-node.ts
  packages/cli/src/commands/import/workflow.ts
  packages/cli/src/commands/ldap/reset.ts
  packages/cli/src/commands/user-management/reset.ts
  packages/cli/src/controllers/__tests__/auth.controller.test.ts
  packages/cli/src/controllers/__tests__/me.controller.test.ts
  packages/cli/src/controllers/__tests__/owner.controller.test.ts
  packages/cli/src/controllers/__tests__/users.controller.test.ts
  packages/cli/src/controllers/auth.controller.ts
  packages/cli/src/controllers/e2e.controller.ts
  packages/cli/src/controllers/invitation.controller.ts
  packages/cli/src/controllers/me.controller.ts
  packages/cli/src/controllers/owner.controller.ts
  packages/cli/src/controllers/password-reset.controller.ts
  packages/cli/src/controllers/users.controller.ts
  packages/cli/src/credentials/credentials.service.ts
  packages/cli/src/databases/db-connection-options.ts
  packages/cli/src/environments.ee/source-control/source-control-import.service.ee.ts
  packages/cli/src/external-hooks.ts
  packages/cli/src/ldap.ee/__tests__/helpers.test.ts
  packages/cli/src/ldap.ee/helpers.ee.ts
  packages/cli/src/mfa/helpers.ts
  packages/cli/src/public-api/v1/handlers/users/users.service.ee.ts
  packages/cli/src/services/__tests__/hooks.service.test.ts
  packages/cli/src/services/__tests__/ownership.service.test.ts
  packages/cli/src/services/__tests__/public-api-key.service.test.ts
  packages/cli/src/services/__tests__/user.service.test.ts
  packages/cli/src/services/access.service.ts
  packages/cli/src/services/hooks.service.ts
  packages/cli/src/services/ownership.service.ts
  packages/cli/src/services/public-api-key.service.ts
  packages/cli/src/services/user.service.ts
  packages/cli/src/sso.ee/saml/__tests__/saml-helpers.test.ts
  packages/cli/src/sso.ee/saml/saml-helpers.ts
  packages/cli/src/sso.ee/saml/saml.service.ee.ts
  packages/cli/src/telemetry/index.ts
  packages/cli/src/user-management/email/user-management-mailer.ts
  packages/cli/test/integration/ai/ai.api.test.ts
  packages/cli/test/integration/auth.api.test.ts
  packages/cli/test/integration/commands/reset.cmd.test.ts
  packages/cli/test/integration/controllers/invitation/invitation.controller.integration.test.ts
  packages/cli/test/integration/database/repositories/project.repository.test.ts
  packages/cli/test/integration/environments/source-control-import.service.test.ts
  packages/cli/test/integration/ldap/ldap.api.test.ts
  packages/cli/test/integration/me.api.test.ts
  packages/cli/test/integration/owner.api.test.ts
  packages/cli/test/integration/password-reset.api.test.ts
  packages/cli/test/integration/shared/db/users.ts
  packages/cli/test/integration/user.repository.test.ts
  packages/cli/test/integration/users.api.test.ts
Labels: core, n8n team

#15339 refactor(Google Sheets Node): Refactor Google Sheets (no-changelog)
  packages/nodes-base/nodes/Google/Sheet/GoogleSheetsTrigger.node.ts
  packages/nodes-base/nodes/Google/Sheet/v2/actions/sheet/read.operation.ts
  packages/nodes-base/nodes/Google/Sheet/v2/actions/utils/readOperation.ts
  packages/nodes-base/nodes/Google/Sheet/v2/actions/versionDescription.ts
Labels: node/improvement, n8n team

#15158 feat(core): Update endpoint to retrieve folder to allow returning the path to root (no-changelog)
  packages/@n8n/api-types/src/dto/folders/list-folder-query.dto.ts
  packages/@n8n/db/src/entities/types-db.ts
  packages/@n8n/db/src/repositories/folder.repository.ts
  packages/@n8n/db/src/repositories/workflow.repository.ts
  packages/cli/src/services/folder.service.ts
  packages/cli/test/integration/folder/folder.controller.test.ts
Labels: core, n8n team

#15343 fix(editor): Waiting executions broken - Chat, Form, Wait (no-changelog)
  cypress/composables/workflow.ts
  cypress/e2e/50-logs.cy.ts
  cypress/fixtures/Workflow_wait_for_webhook.json
  packages/frontend/editor-ui/src/components/CanvasChat/future/LogsPanel.test.ts
  packages/frontend/editor-ui/src/components/CanvasChat/future/composables/useExecutionData.ts
  packages/frontend/editor-ui/src/components/RunDataAi/utils.test.ts
  packages/frontend/editor-ui/src/components/RunDataAi/utils.ts
  packages/frontend/editor-ui/src/composables/usePushConnection/handlers/executionFinished.ts
  packages/frontend/editor-ui/src/composables/usePushConnection/handlers/nodeExecuteBefore.ts
  packages/frontend/editor-ui/src/stores/workflows.store.ts
Labels: n8n team

#14518 refactor(core): Remove legacy expression evaluator
  packages/@n8n/api-types/src/frontend-settings.ts
  packages/cli/src/commands/base-command.ts
  packages/cli/src/config/schema.ts
  packages/cli/src/deprecation/deprecation.service.ts
  packages/cli/src/expression-evaluator.ts
  packages/cli/src/services/frontend.service.ts
  packages/core/nodes-testing/node-test-harness.ts
  packages/frontend/editor-ui/src/__tests__/defaults.ts
  packages/frontend/editor-ui/src/composables/useNodeHelpers.ts
  packages/frontend/editor-ui/src/composables/useWorkflowHelpers.ts
  packages/frontend/editor-ui/src/stores/settings.store.ts
  packages/workflow/package.json
  packages/workflow/src/Expression.ts
  packages/workflow/src/ExpressionEvaluatorProxy.ts
  packages/workflow/src/Extensions/ExpressionExtension.ts
  packages/workflow/src/Extensions/ExpressionParser.ts
  packages/workflow/src/Interfaces.ts
  packages/workflow/src/index.ts
  packages/workflow/test/Expression.test.ts
  packages/workflow/test/ExpressionExtensions/ExpressionExtension.test.ts
  packages/workflow/test/ExpressionExtensions/ObjectExtensions.test.ts
  pnpm-lock.yaml
Labels: core, n8n team

#15297 fix(editor): Fix switching between connected SQL/HTML editors
  cypress/e2e/41-editors.cy.ts
  cypress/e2e/5-ndv.cy.ts
  packages/frontend/editor-ui/src/components/CssEditor/CssEditor.vue
  packages/frontend/editor-ui/src/components/HtmlEditor/HtmlEditor.vue
  packages/frontend/editor-ui/src/components/SqlEditor/SqlEditor.vue
  packages/frontend/editor-ui/src/composables/useExpressionEditor.ts
Labels: n8n team

#15363 chore: Delete credential docs experiment (no-changelog)
  packages/frontend/editor-ui/src/components/CredentialEdit/CredentialConfig.vue
  packages/frontend/editor-ui/src/components/CredentialEdit/CredentialDocs.vue
  packages/frontend/editor-ui/src/components/CredentialEdit/docs.ts
  packages/frontend/editor-ui/src/constants.ts
  packages/frontend/editor-ui/src/plugins/i18n/locales/en.json
Labels: n8n team

#14966 fix: Align release Docker image build with lockfile (no-changelog)
  .github/workflows/docker-images-custom.yml
  .github/workflows/docker-images-nightly.yml
  .github/workflows/release-publish.yml
  docker/images/n8n-custom/Dockerfile
  docker/images/n8n-custom/README.md
  docker/images/n8n/Dockerfile
  packages/core/src/errors/error-reporter.ts
Labels: n8n team

#15358 fix(PostBin Node): Update base URL for postbin node
  packages/nodes-base/nodes/PostBin/BinDescription.ts
  packages/nodes-base/nodes/PostBin/GenericFunctions.ts
  packages/nodes-base/nodes/PostBin/PostBin.node.ts
  packages/nodes-base/nodes/PostBin/RequestDescription.ts
Labels: n8n team

#15283 fix(editor): Don't render `now` when `startedAt` is `null`
  packages/@n8n/db/src/repositories/execution.repository.ts
  packages/cli/test/integration/execution.repository.test.ts
  packages/cli/test/integration/shared/db/executions.ts
  packages/frontend/editor-ui/src/components/executions/global/GlobalExecutionsListItem.test.ts
  packages/frontend/editor-ui/src/components/executions/global/GlobalExecutionsListItem.vue
  packages/frontend/editor-ui/src/components/executions/workflow/WorkflowExecutionsCard.test.ts
  packages/frontend/editor-ui/src/components/executions/workflow/WorkflowExecutionsCard.vue
  packages/frontend/editor-ui/src/composables/useExecutionHelpers.test.ts
  packages/frontend/editor-ui/src/composables/useExecutionHelpers.ts
  packages/frontend/editor-ui/src/stores/executions.store.test.ts
  packages/frontend/editor-ui/src/stores/executions.store.ts
  packages/workflow/src/Interfaces.ts
Labels: core, n8n team

#15382 feat(editor): Rollout improved log view (2nd attempt)
  cypress/composables/logs.ts
  cypress/composables/modals/chat-modal.ts
  cypress/e2e/233-AI-switch-to-logs-on-error.cy.ts
  cypress/e2e/30-langchain.cy.ts
  cypress/utils/executions.ts
  packages/cli/src/config/schema.ts
  packages/frontend/editor-ui/src/components/CanvasChat/future/components/LogsOverviewPanel.vue
Labels: core, n8n team

#15381 fix(Basic LLM Chain Node): Use JSON parsing for Claude 3.7 with thinking enabled
  packages/@n8n/nodes-langchain/nodes/chains/ChainLLM/methods/chainExecutor.ts
  packages/@n8n/nodes-langchain/nodes/chains/ChainLLM/test/chainExecutor.test.ts
Labels: n8n team

#15300 feat(editor): Expose connectionType for 'createNodeActiveChanged' hook and 'User opened nodes panel' event (no-changelog)
  packages/frontend/editor-ui/src/Interface.ts
  packages/frontend/editor-ui/src/stores/nodeCreator.store.ts
  packages/frontend/editor-ui/src/types/externalHooks.ts
Labels: n8n team

#15387 fix(editor): Not all sub node runs are shown in sub execution log (no-changelog)
  packages/frontend/editor-ui/src/components/RunDataAi/utils.test.ts
  packages/frontend/editor-ui/src/components/RunDataAi/utils.ts
Labels: n8n team

#15313 fix(editor): Fix resizing NDV output panel when closing assistant
  packages/frontend/editor-ui/src/components/transitions/SlideTransition.vue
  packages/frontend/editor-ui/src/constants.ts
  packages/frontend/editor-ui/src/stores/assistant.store.ts
  packages/frontend/editor-ui/src/stores/builder.store.ts
Labels: n8n team

#15258 chore(core): Reset SAML configuration in case SAML is enabled but invalid
  packages/cli/src/sso.ee/saml/__tests__/saml.service.ee.test.ts
  packages/cli/src/sso.ee/saml/errors/invalid-saml-metadata-url.error.ts
  packages/cli/src/sso.ee/saml/saml.service.ee.ts
  packages/frontend/editor-ui/src/plugins/i18n/locales/en.json
Labels: core, n8n team

#15390 fix(Text Classifier Node): Return error for empty inputText
  packages/@n8n/nodes-langchain/nodes/chains/TextClassifier/TextClassifier.node.ts
  packages/@n8n/nodes-langchain/nodes/chains/TextClassifier/processItem.ts
  packages/@n8n/nodes-langchain/nodes/chains/TextClassifier/test/TextClassifier.node.test.ts
  packages/@n8n/nodes-langchain/nodes/chains/TextClassifier/test/processItem.test.ts
Labels: n8n team

#15393 chore: Add missing project reference from `core` to `@n8n/decorators`
  packages/core/tsconfig.json
Labels: core, n8n team

#15389 feat(editor): Include pending users for project users search
  packages/frontend/@n8n/design-system/src/components/N8nUserSelect/UserSelect.test.ts
  packages/frontend/@n8n/design-system/src/components/N8nUserSelect/UserSelect.vue
Labels: n8n team

#15259 feat(Execute Workflow Trigger Node): Reintroduce binary data on Workflow Triggers
  packages/nodes-base/nodes/ExecuteWorkflow/ExecuteWorkflowTrigger/ExecuteWorkflowTrigger.node.ts
  packages/nodes-base/utils/workflowInputsResourceMapping/GenericFunctions.ts
Labels: node/improvement, n8n team

#15414 refactor(core): Move `isObjectLiteral` to `@n8n/backend-common`
  packages/@n8n/backend-common/src/index.ts
  packages/@n8n/backend-common/src/utils/__tests__/is-object-literal.test.ts
  packages/@n8n/backend-common/src/utils/is-object-literal.ts
  packages/@n8n/db/package.json
  packages/@n8n/db/src/migrations/common/1659888469333-AddJsonKeyPinData.ts
  packages/cli/src/middlewares/list-query/dtos/base.filter.dto.ts
  packages/cli/src/scaling/scaling.service.ts
  packages/cli/src/services/credentials-tester.service.ts
  packages/cli/src/utils/object-to-error.ts
  packages/core/src/credentials.ts
  packages/core/src/logging/logger.ts
  packages/core/src/utils/index.ts
  packages/core/src/utils/serialized-buffer.ts
  packages/core/tsconfig.json
  pnpm-lock.yaml
Labels: core, n8n team, extensions

#11963 feat(AWS IAM Node): Add new AWS IAM Node
  packages/nodes-base/nodes/Aws/IAM/AwsIam.node.json
  packages/nodes-base/nodes/Aws/IAM/AwsIam.node.ts
  packages/nodes-base/nodes/Aws/IAM/AwsIam.svg
  packages/nodes-base/nodes/Aws/IAM/descriptions/common.ts
  packages/nodes-base/nodes/Aws/IAM/descriptions/group/Group.resource.ts
  packages/nodes-base/nodes/Aws/IAM/descriptions/group/create.operation.ts
  packages/nodes-base/nodes/Aws/IAM/descriptions/group/delete.operation.ts
  packages/nodes-base/nodes/Aws/IAM/descriptions/group/get.operation.ts
  packages/nodes-base/nodes/Aws/IAM/descriptions/group/getAll.operation.ts
  packages/nodes-base/nodes/Aws/IAM/descriptions/group/update.operation.ts
  packages/nodes-base/nodes/Aws/IAM/descriptions/index.ts
  packages/nodes-base/nodes/Aws/IAM/descriptions/user/User.resource.ts
  packages/nodes-base/nodes/Aws/IAM/descriptions/user/addToGroup.operation.ts
  packages/nodes-base/nodes/Aws/IAM/descriptions/user/create.operation.ts
  packages/nodes-base/nodes/Aws/IAM/descriptions/user/delete.operation.ts
  packages/nodes-base/nodes/Aws/IAM/descriptions/user/get.operation.ts
  packages/nodes-base/nodes/Aws/IAM/descriptions/user/getAll.operation.ts
  packages/nodes-base/nodes/Aws/IAM/descriptions/user/removeFromGroup.operation.ts
  packages/nodes-base/nodes/Aws/IAM/descriptions/user/update.operation.ts
  packages/nodes-base/nodes/Aws/IAM/helpers/constants.ts
  packages/nodes-base/nodes/Aws/IAM/helpers/errorHandler.ts
  packages/nodes-base/nodes/Aws/IAM/helpers/types.ts
  packages/nodes-base/nodes/Aws/IAM/helpers/utils.ts
  packages/nodes-base/nodes/Aws/IAM/methods/index.ts
  packages/nodes-base/nodes/Aws/IAM/methods/listSearch.ts
  packages/nodes-base/nodes/Aws/IAM/test/group/create.test.ts
  packages/nodes-base/nodes/Aws/IAM/test/group/create.workflow.json
  packages/nodes-base/nodes/Aws/IAM/test/group/delete.test.ts
  packages/nodes-base/nodes/Aws/IAM/test/group/delete.workflow.json
  packages/nodes-base/nodes/Aws/IAM/test/group/get.test.ts
  packages/nodes-base/nodes/Aws/IAM/test/group/get.workflow.json
  packages/nodes-base/nodes/Aws/IAM/test/group/getAll.test.ts
  packages/nodes-base/nodes/Aws/IAM/test/group/getAll.workflow.json
  packages/nodes-base/nodes/Aws/IAM/test/group/update.test.ts
  packages/nodes-base/nodes/Aws/IAM/test/group/update.workflow.json
  packages/nodes-base/nodes/Aws/IAM/test/helpers/errorHandler.test.ts
  packages/nodes-base/nodes/Aws/IAM/test/helpers/utils.test.ts
  packages/nodes-base/nodes/Aws/IAM/test/listSearch/listSearch.test.ts
  packages/nodes-base/nodes/Aws/IAM/test/user/addToGroup.test.ts
  packages/nodes-base/nodes/Aws/IAM/test/user/addToGroup.workflow.json
  packages/nodes-base/nodes/Aws/IAM/test/user/create.test.ts
  packages/nodes-base/nodes/Aws/IAM/test/user/create.workflow.json
  packages/nodes-base/nodes/Aws/IAM/test/user/delete.test.ts
  packages/nodes-base/nodes/Aws/IAM/test/user/delete.workflow.json
  packages/nodes-base/nodes/Aws/IAM/test/user/get.test.ts
  packages/nodes-base/nodes/Aws/IAM/test/user/get.workflow.json
  packages/nodes-base/nodes/Aws/IAM/test/user/getAll.test.ts
  packages/nodes-base/nodes/Aws/IAM/test/user/getAll.workflow.json
  packages/nodes-base/nodes/Aws/IAM/test/user/removeFromGroup.test.ts
  packages/nodes-base/nodes/Aws/IAM/test/user/removeFromGroup.workflow.json
  packages/nodes-base/nodes/Aws/IAM/test/user/update.test.ts
  packages/nodes-base/nodes/Aws/IAM/test/user/update.workflow.json
  packages/nodes-base/nodes/Aws/IAM/transport/index.ts
  packages/nodes-base/package.json
Labels: node/new, community, in linear

#12875 feat(n8n Microsoft Teams Node): New trigger node
  packages/nodes-base/credentials/MicrosoftTeamsOAuth2Api.credentials.ts
  packages/nodes-base/nodes/Microsoft/Teams/MicrosoftTeamsTrigger.node.json
  packages/nodes-base/nodes/Microsoft/Teams/MicrosoftTeamsTrigger.node.ts
  packages/nodes-base/nodes/Microsoft/Teams/test/trigger/MicrosoftTeamTrigger.test.ts
  packages/nodes-base/nodes/Microsoft/Teams/test/trigger/utiles-trigger.test.ts
  packages/nodes-base/nodes/Microsoft/Teams/v2/helpers/types.ts
  packages/nodes-base/nodes/Microsoft/Teams/v2/helpers/utils-trigger.ts
  packages/nodes-base/nodes/Microsoft/Teams/v2/transport/index.ts
  packages/nodes-base/package.json
Labels: node/new, community, in linear

#15416 test(core): Skip test until fixed
  packages/cli/test/integration/execution.repository.test.ts
Labels: core, n8n team

#15396 feat(editor): Add "Go to Sub-workflow" menu context action to `Workflow Tool`
  packages/frontend/editor-ui/src/composables/__snapshots__/useContextMenu.test.ts.snap
  packages/frontend/editor-ui/src/composables/useContextMenu.test.ts
  packages/frontend/editor-ui/src/composables/useContextMenu.ts
  packages/frontend/editor-ui/src/plugins/i18n/locales/en.json
  packages/workflow/src/NodeHelpers.ts
Labels: core, n8n team

#15419 feat: Expand DB tests to relevant paths (no-changelog)
  .github/workflows/ci-postgres-mysql.yml
Labels: n8n team

#15373 feat(editor): Improve manual description in nodes as tools
  packages/cli/src/__tests__/load-nodes-and-credentials.test.ts
  packages/cli/src/load-nodes-and-credentials.ts
  packages/core/src/execution-engine/node-execution-context/utils/__tests__/create-node-as-tool.test.ts
  packages/core/src/execution-engine/node-execution-context/utils/create-node-as-tool.ts
  packages/frontend/editor-ui/src/components/NodeSettings.vue
  packages/workflow/src/NodeHelpers.ts
  packages/workflow/test/NodeHelpers.test.ts
Labels: core, n8n team

#15379 fix(editor): Fix partial chat executions
  cypress/composables/workflow.ts
  cypress/e2e/812-AI-partial-execs-broken-when-using-chat-trigger.cy.ts
  cypress/fixtures/Test_chat_partial_execution.json
  packages/cli/src/__tests__/manual-execution.service.test.ts
  packages/cli/src/manual-execution.service.ts
  packages/core/src/execution-engine/workflow-execute.ts
  packages/frontend/editor-ui/src/composables/useRunWorkflow.test.ts
  packages/frontend/editor-ui/src/composables/useRunWorkflow.ts
Labels: core, n8n team

#15406 fix(core): Load config early to fix `N8N_CONFIG_FILES`
  packages/cli/bin/n8n
Labels: core, n8n team

#15425 fix(core): Allow strings starting with numbers in alphanumeric string validator
  packages/workflow/src/TypeValidation.ts
  packages/workflow/test/TypeValidation.test.ts
Labels: core, n8n team

#13727 feat(Microsoft SharePoint Node): New node
  packages/nodes-base/credentials/MicrosoftSharePointOAuth2Api.credentials.ts
  packages/nodes-base/nodes/Microsoft/SharePoint/MicrosoftSharePoint.node.ts
  packages/nodes-base/nodes/Microsoft/SharePoint/MicrosoftSharepoint.node.json
  packages/nodes-base/nodes/Microsoft/SharePoint/descriptions/common.descriptions.ts
  packages/nodes-base/nodes/Microsoft/SharePoint/descriptions/file/File.resource.ts
  packages/nodes-base/nodes/Microsoft/SharePoint/descriptions/file/download.operation.ts
  packages/nodes-base/nodes/Microsoft/SharePoint/descriptions/file/update.operation.ts
  packages/nodes-base/nodes/Microsoft/SharePoint/descriptions/file/upload.operation.ts
  packages/nodes-base/nodes/Microsoft/SharePoint/descriptions/index.ts
  packages/nodes-base/nodes/Microsoft/SharePoint/descriptions/item/Item.resource.ts
  packages/nodes-base/nodes/Microsoft/SharePoint/descriptions/item/create.operation.ts
  packages/nodes-base/nodes/Microsoft/SharePoint/descriptions/item/delete.operation.ts
  packages/nodes-base/nodes/Microsoft/SharePoint/descriptions/item/get.operation.ts
  packages/nodes-base/nodes/Microsoft/SharePoint/descriptions/item/getAll.operation.ts
  packages/nodes-base/nodes/Microsoft/SharePoint/descriptions/item/update.operation.ts
  packages/nodes-base/nodes/Microsoft/SharePoint/descriptions/item/upsert.operation.ts
  packages/nodes-base/nodes/Microsoft/SharePoint/descriptions/list/List.resource.ts
  packages/nodes-base/nodes/Microsoft/SharePoint/descriptions/list/get.operation.ts
  packages/nodes-base/nodes/Microsoft/SharePoint/descriptions/list/getAll.operation.ts
  packages/nodes-base/nodes/Microsoft/SharePoint/helpers/interfaces.ts
  packages/nodes-base/nodes/Microsoft/SharePoint/helpers/utils.ts
  packages/nodes-base/nodes/Microsoft/SharePoint/methods/index.ts
  packages/nodes-base/nodes/Microsoft/SharePoint/methods/listSearch.ts
  packages/nodes-base/nodes/Microsoft/SharePoint/methods/resourceMapping.ts
  packages/nodes-base/nodes/Microsoft/SharePoint/microsoftSharePoint.svg
  packages/nodes-base/nodes/Microsoft/SharePoint/test/credentials.ts
  packages/nodes-base/nodes/Microsoft/SharePoint/test/credentials/oauth2.test.ts
  packages/nodes-base/nodes/Microsoft/SharePoint/test/credentials/oauth2.workflow.json
  packages/nodes-base/nodes/Microsoft/SharePoint/test/file/download.test.ts
  packages/nodes-base/nodes/Microsoft/SharePoint/test/file/download.workflow.json
  packages/nodes-base/nodes/Microsoft/SharePoint/test/file/update.test.ts
  packages/nodes-base/nodes/Microsoft/SharePoint/test/file/update.workflow.json
  packages/nodes-base/nodes/Microsoft/SharePoint/test/file/upload.test.ts
  packages/nodes-base/nodes/Microsoft/SharePoint/test/file/upload.workflow.json
  packages/nodes-base/nodes/Microsoft/SharePoint/test/helpers/utils.test.ts
  packages/nodes-base/nodes/Microsoft/SharePoint/test/item/create.test.ts
  packages/nodes-base/nodes/Microsoft/SharePoint/test/item/create.workflow.json
  packages/nodes-base/nodes/Microsoft/SharePoint/test/item/delete.test.ts
  packages/nodes-base/nodes/Microsoft/SharePoint/test/item/delete.workflow.json
  packages/nodes-base/nodes/Microsoft/SharePoint/test/item/get.test.ts
  packages/nodes-base/nodes/Microsoft/SharePoint/test/item/get.workflow.json
  packages/nodes-base/nodes/Microsoft/SharePoint/test/item/getAll.test.ts
  packages/nodes-base/nodes/Microsoft/SharePoint/test/item/getAll.workflow.json
  packages/nodes-base/nodes/Microsoft/SharePoint/test/item/getAllLimitSimplify.test.ts
  packages/nodes-base/nodes/Microsoft/SharePoint/test/item/getAllLimitSimplify.workflow.json
  packages/nodes-base/nodes/Microsoft/SharePoint/test/item/update.test.ts
  packages/nodes-base/nodes/Microsoft/SharePoint/test/item/update.workflow.json
  packages/nodes-base/nodes/Microsoft/SharePoint/test/item/upsert.test.ts
  packages/nodes-base/nodes/Microsoft/SharePoint/test/item/upsert.workflow.json
  packages/nodes-base/nodes/Microsoft/SharePoint/test/list/get.test.ts
  packages/nodes-base/nodes/Microsoft/SharePoint/test/list/get.workflow.json
  packages/nodes-base/nodes/Microsoft/SharePoint/test/list/getAll.test.ts
  packages/nodes-base/nodes/Microsoft/SharePoint/test/list/getAll.workflow.json
  packages/nodes-base/nodes/Microsoft/SharePoint/test/methods/listSearch.test.ts
  packages/nodes-base/nodes/Microsoft/SharePoint/test/methods/resourceMapping.test.ts
  packages/nodes-base/nodes/Microsoft/SharePoint/transport/index.ts
  packages/nodes-base/package.json
Labels: node/improvement, node/new, community, in linear

#15388 fix(editor): Show error toast for failed executions
  packages/frontend/editor-ui/src/composables/useCanvasOperations.test.ts
  packages/frontend/editor-ui/src/composables/useCanvasOperations.ts
  packages/frontend/editor-ui/src/composables/usePushConnection/handlers/executionFinished.ts
  packages/frontend/editor-ui/src/utils/executionUtils.test.ts
  packages/frontend/editor-ui/src/utils/executionUtils.ts
Labels: n8n team

#15434 fix(editor): Normalize credential data from source control
  packages/frontend/editor-ui/src/components/CredentialEdit/CredentialEdit.vue
  packages/frontend/editor-ui/src/components/CredentialEdit/__tests__/CredentialEdit.test.ts
Labels: n8n team

#15194 feat(n8n Evaluation Trigger Node): Add Evaluation Trigger and Evaluation Node
  cypress/e2e/20-workflow-executions.cy.ts
  packages/frontend/editor-ui/src/components/Node/NodeCreator/NodesListPanel.test.ts
  packages/frontend/editor-ui/src/components/Node/NodeCreator/__snapshots__/viewsData.spec.ts.snap
  packages/frontend/editor-ui/src/components/Node/NodeCreator/composables/useActionsGeneration.ts
  packages/frontend/editor-ui/src/components/Node/NodeCreator/useActionsGeneration.test.ts
  packages/frontend/editor-ui/src/components/Node/NodeCreator/viewsData.spec.ts
  packages/frontend/editor-ui/src/components/Node/NodeCreator/viewsData.ts
  packages/frontend/editor-ui/src/constants.ts
  packages/nodes-base/nodes/Evaluation/Evaluation/Description.node.ts
  packages/nodes-base/nodes/Evaluation/Evaluation/Evaluation.node.ee.json
  packages/nodes-base/nodes/Evaluation/Evaluation/Evaluation.node.ee.ts
  packages/nodes-base/nodes/Evaluation/EvaluationTrigger/EvaluationTrigger.node.ee.json
  packages/nodes-base/nodes/Evaluation/EvaluationTrigger/EvaluationTrigger.node.ee.ts
  packages/nodes-base/nodes/Evaluation/methods/index.ts
  packages/nodes-base/nodes/Evaluation/methods/loadOptions.ts
  packages/nodes-base/nodes/Evaluation/test/Evaluation.node.test.ts
  packages/nodes-base/nodes/Evaluation/test/EvaluationTrigger.node.test.ts
  packages/nodes-base/nodes/Evaluation/test/evaluationTriggerUtils.test.ts
  packages/nodes-base/nodes/Evaluation/test/loadOptions.test.ts
  packages/nodes-base/nodes/Evaluation/utils/evaluationTriggerUtils.ts
  packages/nodes-base/nodes/Evaluation/utils/evaluationUtils.ts
  packages/nodes-base/package.json
  packages/workflow/src/Constants.ts
  packages/workflow/src/errors/base/base.error.ts
Labels: node/improvement, node/new, n8n team

#15449 feat: Add HTTP proxy for supported LLM nodes
  packages/@n8n/nodes-langchain/nodes/llms/LMChatAnthropic/LmChatAnthropic.node.ts
  packages/@n8n/nodes-langchain/nodes/llms/LMChatOpenAi/LmChatOpenAi.node.ts
  packages/@n8n/nodes-langchain/nodes/llms/LMChatOpenAi/methods/loadModels.ts
  packages/@n8n/nodes-langchain/nodes/llms/LMOpenAi/LmOpenAi.node.ts
  packages/@n8n/nodes-langchain/nodes/llms/LmChatAwsBedrock/LmChatAwsBedrock.node.ts
  packages/@n8n/nodes-langchain/nodes/llms/LmChatAzureOpenAi/LmChatAzureOpenAi.node.ts
  packages/@n8n/nodes-langchain/nodes/llms/LmChatDeepSeek/LmChatDeepSeek.node.ts
  packages/@n8n/nodes-langchain/nodes/llms/LmChatGroq/LmChatGroq.node.ts
  packages/@n8n/nodes-langchain/nodes/llms/LmChatOpenRouter/LmChatOpenRouter.node.ts
  packages/@n8n/nodes-langchain/nodes/llms/LmChatXAiGrok/LmChatXAiGrok.node.ts
  packages/@n8n/nodes-langchain/package.json
  packages/@n8n/nodes-langchain/utils/httpProxyAgent.ts
  packages/@n8n/nodes-langchain/utils/tests/httpProxyAgent.test.ts
  pnpm-lock.yaml
Labels: n8n team

#15378 feat(editor): Keyboard shortcuts for the log view
  packages/frontend/editor-ui/src/components/AskAssistant/Chat/AskAssistantFloatingButton.vue
  packages/frontend/editor-ui/src/components/CanvasChat/CanvasChat.test.ts
  packages/frontend/editor-ui/src/components/CanvasChat/CanvasChat.vue
  packages/frontend/editor-ui/src/components/CanvasChat/components/ChatMessagesPanel.vue
  packages/frontend/editor-ui/src/components/CanvasChat/composables/useChatState.ts
  packages/frontend/editor-ui/src/components/CanvasChat/future/LogsPanel.test.ts
  packages/frontend/editor-ui/src/components/CanvasChat/future/LogsPanel.vue
  packages/frontend/editor-ui/src/components/CanvasChat/future/components/LogDetailsPanel.test.ts
  packages/frontend/editor-ui/src/components/CanvasChat/future/components/LogDetailsPanel.vue
  packages/frontend/editor-ui/src/components/CanvasChat/future/components/LogsOverviewPanel.test.ts
  packages/frontend/editor-ui/src/components/CanvasChat/future/components/LogsOverviewPanel.vue
  packages/frontend/editor-ui/src/components/CanvasChat/future/components/LogsOverviewRow.vue
  packages/frontend/editor-ui/src/components/CanvasChat/future/components/LogsPanelActions.vue
  packages/frontend/editor-ui/src/components/CanvasChat/future/components/LogsPanelHeader.vue
  packages/frontend/editor-ui/src/components/CanvasChat/future/components/LogsViewConsumedTokenCountText.vue
  packages/frontend/editor-ui/src/components/CanvasChat/future/components/LogsViewExecutionSummary.vue
  packages/frontend/editor-ui/src/components/CanvasChat/future/components/LogsViewNodeName.vue
  packages/frontend/editor-ui/src/components/CanvasChat/future/components/LogsViewRunData.vue
  packages/frontend/editor-ui/src/components/CanvasChat/future/composables/useLogsExecutionData.test.ts
  packages/frontend/editor-ui/src/components/CanvasChat/future/composables/useLogsExecutionData.ts
  packages/frontend/editor-ui/src/components/CanvasChat/future/composables/useLogsPanelLayout.ts
  packages/frontend/editor-ui/src/components/CanvasChat/future/composables/useLogsSelection.ts
  packages/frontend/editor-ui/src/components/CanvasChat/future/composables/useLogsTreeExpand.ts
  packages/frontend/editor-ui/src/components/CanvasChat/types/logs.ts
  packages/frontend/editor-ui/src/components/KeyboardShortcutTooltip.vue
  packages/frontend/editor-ui/src/components/RunDataAi/utils.ts
  packages/frontend/editor-ui/src/components/canvas/Canvas.vue
  packages/frontend/editor-ui/src/components/canvas/elements/nodes/render-types/parts/CanvasNodeTrigger.vue
  packages/frontend/editor-ui/src/composables/useCanvasOperations.test.ts
  packages/frontend/editor-ui/src/composables/useCanvasOperations.ts
  packages/frontend/editor-ui/src/composables/useResizablePanel.test.ts
  packages/frontend/editor-ui/src/composables/useResizablePanel.ts
  packages/frontend/editor-ui/src/composables/useRunWorkflow.ts
  packages/frontend/editor-ui/src/composables/useToast.ts
  packages/frontend/editor-ui/src/constants.ts
  packages/frontend/editor-ui/src/plugins/i18n/locales/en.json
  packages/frontend/editor-ui/src/stores/canvas.store.ts
  packages/frontend/editor-ui/src/stores/logs.store.ts
  packages/frontend/editor-ui/src/stores/workflows.store.ts
  packages/frontend/editor-ui/src/views/NodeView.vue
Labels: n8n team

#15440 fix(editor): Fix paired items after renaming a node
  packages/frontend/editor-ui/src/stores/workflows.store.test.ts
  packages/frontend/editor-ui/src/stores/workflows.store.ts
Labels: n8n team

#15455 feat(n8n Evaluation Trigger Node): Add link to dataset template in trigger
  packages/nodes-base/nodes/Evaluation/EvaluationTrigger/EvaluationTrigger.node.ee.ts
Labels: node/improvement, n8n team

#15337 refactor: Split paired item logic into more manageable methods (no-changelog)
  packages/workflow/src/WorkflowDataProxy.ts
  packages/workflow/test/WorkflowDataProxy.test.ts
Labels: core, n8n team

#15462 refactor(editor): Migrate `agentRequest` store to `@n8n/stores` package (no-changelog)
  packages/frontend/@n8n/stores/package.json
  packages/frontend/@n8n/stores/src/useAgentRequestStore.test.ts
  packages/frontend/@n8n/stores/src/useAgentRequestStore.ts
  packages/frontend/editor-ui/package.json
  packages/frontend/editor-ui/src/components/FromAiParametersModal.test.ts
  packages/frontend/editor-ui/src/components/FromAiParametersModal.vue
  packages/frontend/editor-ui/src/composables/useRunWorkflow.test.ts
  packages/frontend/editor-ui/src/composables/useRunWorkflow.ts
  packages/frontend/editor-ui/src/views/NodeView.vue
  pnpm-lock.yaml
  pnpm-workspace.yaml
Labels: n8n team

#15458 fix(Execute Workflow Trigger Node): Show helpful error message when passing array to JSON Example
  packages/nodes-base/utils/workflowInputsResourceMapping/GenericFunctions.ts
Labels: n8n team, team:adore

#15465 feat(n8n Evaluation Trigger Node): Add telemetry events
  packages/cli/src/events/relays/telemetry.event-relay.ts
  packages/workflow/src/Constants.ts
  packages/workflow/src/Interfaces.ts
  packages/workflow/src/TelemetryHelpers.ts
  packages/workflow/test/TelemetryHelpers.test.ts
Labels: core, n8n team

#15420 feat(editor): Add user info on relations to enhance design of project users list
  packages/frontend/@n8n/design-system/src/components/N8nUserInfo/UserInfo.test.ts
  packages/frontend/editor-ui/src/views/ProjectSettings.vue
Labels: n8n team

#15356 fix: Remove `variable:read` as a valid API key scope and make `variable:update` selectable in the UI (no-changelog)
  packages/@n8n/permissions/src/constants.ee.ts
  packages/@n8n/permissions/src/public-api-permissions.ee.ts
  packages/cli/test/integration/public-api/endpoints-with-scopes-enabled.test.ts
  packages/cli/test/integration/public-api/variables.test.ts
  packages/cli/test/integration/shared/db/variables.ts
  packages/cli/test/integration/variables.test.ts
Labels: n8n team

#15482 fix(editor): Fix node renaming in pinned data
  packages/frontend/editor-ui/src/stores/workflows.store.test.ts
  packages/frontend/editor-ui/src/stores/workflows.store.ts
Labels: n8n team

#15413 fix(core): Make the Insights by time datetime parsing more robust
  packages/cli/src/modules/insights/database/repositories/__tests__/insights-by-period.repository.test.ts
  packages/cli/src/modules/insights/database/repositories/insights-by-period.repository.ts
Labels: core, n8n team

#15433 fix(core): Load insights module on webhook instance to save insights on webhook workflows
  packages/cli/src/modules/insights/__tests__/insights.pre-init.test.ts
  packages/cli/src/modules/insights/insights.pre-init.ts
Labels: core, n8n team

#15410 fix(editor): Fix phantom items for waiting nodes (no-changelog)
  packages/frontend/editor-ui/src/stores/workflows.store.test.ts
  packages/frontend/editor-ui/src/stores/workflows.store.ts
Labels: n8n team

#15457 fix(editor): Correctly show Workflow Breadcrumbs in MainHeader on Registered Community
  packages/cli/src/workflows/workflows.controller.ts
  packages/frontend/editor-ui/src/components/Folders/FolderBreadcrumbs.test.ts
  packages/frontend/editor-ui/src/components/Folders/FolderBreadcrumbs.vue
  packages/frontend/editor-ui/src/components/MainHeader/WorkflowDetails.vue
Labels: core, n8n team

#15473 fix(n8n Evaluation Trigger Node): Fix tweaks
  packages/frontend/editor-ui/src/components/Node/NodeCreator/viewsData.ts
  packages/frontend/editor-ui/src/plugins/i18n/locales/en.json
  packages/nodes-base/nodes/Evaluation/Evaluation/Description.node.ts
  packages/nodes-base/nodes/Evaluation/Evaluation/Evaluation.node.ee.ts
  packages/nodes-base/nodes/Evaluation/EvaluationTrigger/EvaluationTrigger.node.ee.ts
  packages/nodes-base/nodes/Evaluation/test/Evaluation.node.test.ts
  packages/nodes-base/nodes/Evaluation/utils/evaluationUtils.ts
Labels: node/improvement, n8n team

#15508 fix(n8n Form Node): Limit the max width for text area
  packages/cli/templates/form-trigger.handlebars
Labels: core, n8n team

#15351 fix(editor): Handle Loop node execution data preview correctly when inserting a node
  packages/frontend/editor-ui/src/composables/useWorkflowHelpers.test.ts
  packages/frontend/editor-ui/src/composables/useWorkflowHelpers.ts
  packages/frontend/editor-ui/src/mixins/workflowHelpers.test.ts
Labels: n8n team

#15459 fix(editor): Make deleting Call n8n Workflow Tool fromAI workflow input descriptions work
  packages/frontend/@n8n/design-system/src/components/N8nSelectableList/SelectableList.test.ts
  packages/frontend/@n8n/design-system/src/components/N8nSelectableList/SelectableList.vue
  packages/frontend/editor-ui/src/components/ParameterInputOverrides/ParameterOverrideSelectableList.test.ts
  packages/frontend/editor-ui/src/components/ParameterInputOverrides/ParameterOverrideSelectableList.vue
Labels: n8n team

#15438 fix(Chat Trigger Node): Don't continue when action is load previous session and option is not set
  packages/@n8n/nodes-langchain/nodes/trigger/ChatTrigger/ChatTrigger.node.ts
  packages/@n8n/nodes-langchain/nodes/trigger/ChatTrigger/__test__/ChatTrigger.node.test.ts
Labels: n8n team

#15526 fix(editor): Fix how deviation percentage is calculated in Insights summary
  packages/frontend/editor-ui/src/features/insights/insights.utils.test.ts
  packages/frontend/editor-ui/src/features/insights/insights.utils.ts
Labels: n8n team

#15532 fix: Fix jobs for secrets inherit
  .github/workflows/test-workflows-nightly.yml
  .github/workflows/test-workflows-pr-approved.yml
  .github/workflows/test-workflows-pr-comment.yml
Labels: n8n team
