Repository n8n-io/n8n, pull requests merged in 2025-03, with the labels that each got.

#13580 fix(editor): Fix browser crash with large execution result
  packages/frontend/editor-ui/src/utils/pairedItemUtils.test.ts
  packages/frontend/editor-ui/src/utils/pairedItemUtils.ts
Labels: ui, n8n team

#13552 fix(editor): Hide fromAI button in old workflow tool
  packages/frontend/editor-ui/src/components/ParameterInputFull.vue
  packages/frontend/editor-ui/src/components/ResourceLocator/ResourceLocator.vue
  packages/frontend/editor-ui/src/utils/fromAIOverrideUtils.test.ts
  packages/frontend/editor-ui/src/utils/fromAIOverrideUtils.ts
Labels: ui, n8n team

#13621 fix(editor): Fix workflows list status filter
  cypress/e2e/1-workflows.cy.ts
  packages/frontend/editor-ui/src/views/WorkflowsView.test.ts
  packages/frontend/editor-ui/src/views/WorkflowsView.vue
Labels: n8n team

#13617 fix(core): Add documentation hints for API keys to `SettingApiView.vue` (no-changelog)
  packages/frontend/editor-ui/src/components/ApiKeyCreateOrEditModal.test.ts
  packages/frontend/editor-ui/src/components/ApiKeyCreateOrEditModal.vue
  packages/frontend/editor-ui/src/views/SettingsApiView.test.ts
  packages/frontend/editor-ui/src/views/SettingsApiView.vue
Labels: n8n team

#13635 test: Replace 1-workflow delete implementation (no-changelog)
  cypress/e2e/1-workflows.cy.ts
Labels: n8n team

#13632 fix(core): Gracefully handle missing tasks metadata
  packages/core/src/execution-engine/workflow-execute.ts
Labels: core, n8n team, release/backport

#13637 fix(OpenAI Node): Do not report openai RateLimitErrors to Sentry (no-changelog)
  packages/@n8n/nodes-langchain/nodes/vendors/OpenAi/helpers/error-handling.test.ts
  packages/@n8n/nodes-langchain/nodes/vendors/OpenAi/helpers/error-handling.ts
Labels: n8n team

#13602 fix(QuickBooks Online Node): Add qty to quickbooks invoice line details
  packages/nodes-base/nodes/QuickBooks/GenericFunctions.ts
  packages/nodes-base/nodes/QuickBooks/__tests__/GenericFunctions.test.ts
  packages/nodes-base/nodes/QuickBooks/descriptions/Invoice/InvoiceDescription.ts
Labels: node/improvement, n8n team

#13579 fix(editor): Fix RLC dropdown vanishing when focusing search input
  packages/frontend/editor-ui/src/components/ResourceLocator/ResourceLocatorDropdown.vue
  packages/frontend/editor-ui/src/components/TestDefinition/EditDefinition/EvaluationStep.vue
Labels: ui, n8n team

#13634 fix(editor): Add `rewriteFramesIntegration` to sentry (no-changelog)
  packages/frontend/editor-ui/src/plugins/sentry.ts
Labels: n8n team

#13595 fix(n8n Form Trigger Node): Sanitize HTML for formNode
  packages/nodes-base/nodes/Form/formNodeUtils.ts
  packages/nodes-base/nodes/Form/test/formNodeUtils.test.ts
Labels: node/improvement, n8n team

#13589 fix(Google Sheets Node): Accommodate special characters when updating row
  packages/nodes-base/nodes/Google/Sheet/test/v2/node/update.test.ts
  packages/nodes-base/nodes/Google/Sheet/v2/actions/sheet/update.operation.ts
Labels: node/improvement, n8n team

#13631 fix(core): Stop enforcing max numbers of API keys limit (no-changelog)
  packages/@n8n/api-types/src/frontend-settings.ts
  packages/cli/src/constants.ts
  packages/cli/src/controllers/__tests__/api-keys.controller.test.ts
  packages/cli/src/controllers/api-keys.controller.ts
  packages/cli/src/controllers/e2e.controller.ts
  packages/cli/src/license.ts
  packages/cli/src/services/frontend.service.ts
  packages/cli/test/integration/api-keys.api.test.ts
  packages/frontend/editor-ui/src/__tests__/defaults.ts
  packages/frontend/editor-ui/src/stores/apiKeys.store.ts
  packages/frontend/editor-ui/src/stores/settings.store.ts
  packages/frontend/editor-ui/src/views/SettingsApiView.vue
Labels: core, n8n team

#13203 fix(editor): Fix sidebar logo container layout
  packages/frontend/editor-ui/src/components/Logo/Logo.vue
  packages/frontend/editor-ui/src/components/Logo/__tests__/__snapshots__/Logo.test.ts.snap
  packages/frontend/editor-ui/src/components/MainSidebar.test.ts
  packages/frontend/editor-ui/src/components/MainSidebar.vue
  packages/frontend/editor-ui/src/components/NodeDetailsView.vue
  packages/frontend/editor-ui/src/plugins/i18n/locales/en.json
  packages/frontend/editor-ui/src/stores/projects.store.ts
Labels: ui, n8n team

#13599 fix(GitHub Node): Fix workflow resource locator
  packages/nodes-base/nodes/Github/Github.node.ts
  packages/nodes-base/nodes/Github/__tests__/Github.node.test.ts
  packages/nodes-base/nodes/Github/__tests__/GithubTestWorkflow.json
Labels: node/improvement, n8n team

#13393 fix(Call n8n Workflow Tool Node): Return all items from subexecution
  packages/@n8n/nodes-langchain/nodes/tools/ToolWorkflow/ToolWorkflow.node.ts
  packages/@n8n/nodes-langchain/nodes/tools/ToolWorkflow/v2/ToolWorkflowV2.node.ts
  packages/@n8n/nodes-langchain/nodes/tools/ToolWorkflow/v2/ToolWorkflowV2.test.ts
  packages/@n8n/nodes-langchain/nodes/tools/ToolWorkflow/v2/utils/WorkflowToolService.ts
  packages/@n8n/nodes-langchain/nodes/tools/ToolWorkflow/v2/versionDescription.ts
Labels: n8n team

#13605 fix(core): Do not validate email when LDAP is enabled
  cypress/e2e/18-user-management.cy.ts
  cypress/e2e/39-projects.cy.ts
  cypress/pages/signin.ts
  cypress/support/commands.ts
  packages/@n8n/api-types/src/dto/auth/__tests__/login-request.dto.test.ts
  packages/@n8n/api-types/src/dto/auth/login-request.dto.ts
  packages/cli/src/controllers/__tests__/auth.controller.test.ts
  packages/cli/src/controllers/auth.controller.ts
  packages/cli/test/integration/auth.api.test.ts
  packages/cli/test/integration/ldap/ldap.api.test.ts
  packages/cli/test/integration/mfa/mfa.api.test.ts
  packages/frontend/editor-ui/src/api/users.ts
  packages/frontend/editor-ui/src/stores/users.store.ts
  packages/frontend/editor-ui/src/views/AuthView.vue
  packages/frontend/editor-ui/src/views/SigninView.test.ts
  packages/frontend/editor-ui/src/views/SigninView.vue
Labels: core, n8n team, release/backport

#13638 fix(editor): Allow pinned data for Code node AI generation
  packages/frontend/editor-ui/src/components/CodeNodeEditor/AskAI/AskAI.vue
Labels: n8n team

#13640 fix(editor): Fix save keybind in expression editor and unfocused node details view
  cypress/e2e/9-expression-editor-modal.cy.ts
  packages/frontend/editor-ui/src/components/NodeDetailsView.test.ts
  packages/frontend/editor-ui/src/components/NodeDetailsView.vue
Labels: n8n team

#13628 fix(editor): Ignore required module type declaration error in code node
  packages/frontend/editor-ui/src/plugins/codemirror/typescript/worker/linter.test.ts
  packages/frontend/editor-ui/src/plugins/codemirror/typescript/worker/linter.ts
Labels: n8n team

#13658 feat(editor): Add scrolling to API keys list (no-changelog)
  packages/frontend/editor-ui/src/components/ApiKeyCreateOrEditModal.vue
  packages/frontend/editor-ui/src/views/SettingsApiView.vue
Labels: n8n team

#13672 fix(editor): Fix GCP icon size for external secrets modal
  packages/frontend/editor-ui/src/components/ExternalSecretsProviderModal.ee.vue
Labels: n8n team

#13664 fix(editor): Fix code node displays lint messages in wrong location
  packages/frontend/editor-ui/package.json
  packages/frontend/editor-ui/src/__tests__/setup.ts
  packages/frontend/editor-ui/src/plugins/codemirror/typescript/client/useTypescript.ts
  packages/frontend/editor-ui/src/plugins/codemirror/typescript/worker/typescript.worker.test.ts
  packages/frontend/editor-ui/src/plugins/codemirror/typescript/worker/typescript.worker.ts
  pnpm-lock.yaml
Labels: n8n team

#13677 fix(editor): Adjust MappingFields parameterInput width to account for delete button (no-changelog)
  packages/frontend/editor-ui/src/components/ResourceMapper/MappingFields.vue
Labels: n8n team

#13673 fix(editor): Copy JSON from selected run if node has been multiple times
  packages/frontend/editor-ui/src/components/RunData.vue
  packages/frontend/editor-ui/src/components/RunDataJson.vue
  packages/frontend/editor-ui/src/components/RunDataJsonActions.test.ts
  packages/frontend/editor-ui/src/components/RunDataJsonActions.vue
Labels: n8n team

#13688 fix(editor): Expand error view to full output panel width
  packages/frontend/editor-ui/src/components/Error/NodeErrorView.vue
Labels: n8n team

#13689 fix(editor): Render credential-only nodes when loading from the backend
  packages/frontend/editor-ui/src/stores/workflows.store.test.ts
  packages/frontend/editor-ui/src/stores/workflows.store.ts
Labels: n8n team

#13578 feat(editor): Schema preview UI updates
  packages/frontend/editor-ui/src/components/VirtualSchema.vue
  packages/frontend/editor-ui/src/components/VirtualSchemaHeader.vue
  packages/frontend/editor-ui/src/components/VirtualSchemaItem.vue
  packages/frontend/editor-ui/src/components/__snapshots__/VirtualSchema.test.ts.snap
  packages/frontend/editor-ui/src/composables/useDataSchema.ts
  packages/frontend/editor-ui/src/constants.ts
  packages/frontend/editor-ui/src/plugins/i18n/locales/en.json
Labels: ui, n8n team

#13676 fix(editor): Fix opening 'Schema' view by default after opening binary nodes
  packages/frontend/editor-ui/src/components/RunData.vue
Labels: n8n team

#13652 fix(core): Pass `NODE_PATH` to task runners
  docker/images/n8n/n8n-task-runners.json
  packages/cli/src/task-runners/__tests__/task-runner-process.test.ts
  packages/cli/src/task-runners/task-runner-process.ts
Labels: core, n8n team

#13699 fix(editor): Support pasting values that start with `=`
  packages/frontend/editor-ui/src/__tests__/setup.ts
  packages/frontend/editor-ui/src/components/ParameterInput.test.ts
  packages/frontend/editor-ui/src/components/ParameterInput.vue
Labels: n8n team

#13302 fix(Elasticsearch Node): Use POST instead of GET to allow request body in search API
  packages/nodes-base/nodes/Elastic/Elasticsearch/GenericFunctions.ts
Labels: node/improvement, community, in linear

#13735 fix(Airtable Node): Table RLC should depend on Base RLC
  packages/nodes-base/nodes/Airtable/v2/actions/common.descriptions.ts
Labels: n8n team, node/issue

#13779 fix(core): Correct NODE_OPTIONS export syntax for custom certificates
  docker/images/n8n/docker-entrypoint.sh
Labels: community, in linear

#13780 build: Set Jest workerIdleMemoryLimit on local env (no-changelog)
  jest.config.js
  package.json
  pnpm-lock.yaml
Labels: n8n team

#13566 fix(n8n Form Node): Completion page response mode, do not error on execution running (no-changelog)
  packages/cli/src/webhooks/__tests__/waiting-forms.test.ts
  packages/cli/src/webhooks/waiting-forms.ts
  packages/cli/src/webhooks/webhook-helpers.ts
  packages/cli/templates/form-trigger.handlebars
  packages/frontend/editor-ui/src/components/ParameterInputList.test.ts
  packages/frontend/editor-ui/src/components/ParameterInputList.vue
  packages/workflow/src/Constants.ts
  packages/workflow/src/Interfaces.ts
Labels: n8n team, node/issue, release/backport

#13703 fix(editor): Apply html sanitization in right lifecycle
  packages/frontend/@n8n/design-system/src/components/N8nInputLabel/InputLabel.vue
  packages/frontend/@n8n/design-system/src/directives/n8n-html.ts
Labels: n8n team

#13716 fix(editor): Match nodes for autocomplete
  packages/frontend/editor-ui/src/plugins/codemirror/typescript/client/completions.ts
  packages/frontend/editor-ui/src/plugins/codemirror/typescript/client/tests/completions.test.ts
Labels: n8n team

#13784 fix(core): Find correct start nodes when the first node after that has no run data has pinned data
  packages/core/src/execution-engine/partial-execution-utils/__tests__/find-start-nodes.test.ts
  packages/core/src/execution-engine/partial-execution-utils/find-start-nodes.ts
Labels: core, n8n team, release/backport

#13714 fix(core): Ensure worker stops picking up new jobs while shutting down
  packages/cli/src/scaling/__tests__/scaling.service.test.ts
  packages/cli/src/scaling/scaling.service.ts
Labels: core, n8n team

#13755 fix(n8n Form Node): Resolve expressions in HTML fields
  packages/nodes-base/nodes/Form/Form.node.ts
  packages/nodes-base/nodes/Form/formNodeUtils.ts
  packages/nodes-base/nodes/Form/test/formNodeUtils.test.ts
  packages/nodes-base/nodes/Form/test/utils.test.ts
  packages/nodes-base/nodes/Form/utils.ts
Labels: node/improvement, n8n team, node/issue

#13799 chore: Upgrade axios to address CVE-2025-27152
  cypress/package.json
  package.json
  packages/nodes-base/nodes/GraphQL/test/GraphQL.node.test.ts
  pnpm-lock.yaml
  pnpm-workspace.yaml
Labels: n8n team

#13751 feat(WhatsApp Trigger Node): New option to opt-out from message status updates
  packages/nodes-base/nodes/WhatsApp/WhatsAppTrigger.node.ts
  packages/nodes-base/nodes/WhatsApp/tests/utils.trigger.test.ts
  packages/nodes-base/nodes/WhatsApp/types.ts
Labels: node/improvement, n8n team, node/issue

#13687 chore: Upgrade Typescript and other frontend tooling (no-changelog)
  package.json
  packages/@n8n/storybook/package.json
  packages/@n8n/utils/package.json
  packages/frontend/@n8n/chat/package.json
  packages/frontend/@n8n/composables/package.json
  packages/frontend/editor-ui/package.json
  patches/vue-tsc@2.2.8.patch
  pnpm-lock.yaml
  pnpm-workspace.yaml
Labels: n8n team

#13822 refactor(core): Do not report Unrecognized node/credential type errors to Sentry (no-changelog)
  packages/core/src/errors/error-reporter.ts
  packages/core/src/errors/unrecognized-credential-type.error.ts
  packages/core/src/errors/unrecognized-node-type.error.ts
Labels: core, n8n team

#13708 fix(editor): Fix NDV panels size on narrow screens
  packages/frontend/editor-ui/src/App.vue
  packages/frontend/editor-ui/src/components/NDVDraggablePanels.vue
  packages/frontend/editor-ui/src/components/NodeDetailsView.vue
  packages/frontend/editor-ui/src/stores/assistant.store.ts
  packages/frontend/editor-ui/src/stores/ui.store.ts
Labels: n8n team

#13792 fix: Do not trigger sendAndWait response on bot visit if response type is approval
  packages/nodes-base/utils/sendAndWait/test/util.test.ts
  packages/nodes-base/utils/sendAndWait/utils.ts
Labels: node/improvement, n8n team, node/issue

#13827 fix(core): Log all command errors messages
  packages/cli/src/commands/base-command.ts
Labels: core, n8n team

#13816 fix(editor): Disable `test step` option in context menu for sub-nodes
  packages/frontend/editor-ui/src/composables/useContextMenu.test.ts
  packages/frontend/editor-ui/src/composables/useContextMenu.ts
  packages/workflow/src/NodeHelpers.ts
  packages/workflow/test/NodeHelpers.test.ts
Labels: core, n8n team

#13570 fix(AWS SES Node): Encode template parameters properly
  packages/nodes-base/nodes/Aws/SES/AwsSes.node.ts
  packages/nodes-base/nodes/Aws/SES/test/AwsSes.node.test.ts
Labels: node/improvement, n8n team

#13821 fix(core): Clean run data for dirty nodes properly, including their children
  packages/core/src/execution-engine/__tests__/workflow-execute.test.ts
  packages/core/src/execution-engine/partial-execution-utils/clean-run-data.ts
  packages/core/src/execution-engine/workflow-execute.ts
  packages/workflow/src/Workflow.ts
  packages/workflow/test/Workflow.test.ts
Labels: core, n8n team, release/backport

#13834 fix(Linear Node): Fix issue with undefined error (no-changelog)
  packages/nodes-base/nodes/Linear/GenericFunctions.ts
Labels: node/improvement, n8n team

#13795 refactor(core): Improve UX on permission errors (no-changelog)
  packages/cli/src/__tests__/workflow-execute-additional-data.test.ts
  packages/cli/src/__tests__/workflow-runner.test.ts
  packages/cli/src/executions/__tests__/execution-data.service.test.ts
  packages/cli/src/executions/execution-data.service.ts
  packages/cli/src/executions/pre-execution-checks/__tests__/credentials-permission-checker.test.ts
  packages/cli/src/executions/pre-execution-checks/__tests__/subworkflow-policy-checker.test.ts
  packages/cli/src/executions/pre-execution-checks/credentials-permission-checker.ts
  packages/cli/src/executions/pre-execution-checks/index.ts
  packages/cli/src/executions/pre-execution-checks/subworkflow-policy-checker.ts
  packages/cli/src/workflow-execute-additional-data.ts
  packages/cli/src/workflow-helpers.ts
  packages/cli/src/workflow-runner.ts
  packages/cli/src/workflows/__tests__/workflow-execution.service.test.ts
  packages/cli/src/workflows/workflow-execution.service.ts
  packages/cli/test/integration/executions/pre-execution-checks/credentials-permission-checker.test.ts
  packages/workflow/src/errors/credential-access-error.ts
  packages/workflow/src/errors/index.ts
Labels: core, n8n team

#13831 feat(editor): Add telemetry event for tidy up feature (no-changelog)
  packages/frontend/editor-ui/src/components/canvas/Canvas.vue
  packages/frontend/editor-ui/src/components/canvas/elements/buttons/CanvasControlButtons.test.ts
  packages/frontend/editor-ui/src/components/canvas/elements/buttons/CanvasControlButtons.vue
  packages/frontend/editor-ui/src/composables/useCanvasLayout.test.ts
  packages/frontend/editor-ui/src/composables/useCanvasLayout.ts
  packages/frontend/editor-ui/src/composables/useCanvasOperations.test.ts
  packages/frontend/editor-ui/src/composables/useCanvasOperations.ts
  packages/frontend/editor-ui/src/views/NodeView.vue
Labels: n8n team

#13828 feat(editor): Show personal project for community edition (no-changelog)
  packages/frontend/editor-ui/src/components/Projects/ProjectNavigation.test.ts
  packages/frontend/editor-ui/src/components/Projects/ProjectNavigation.vue
Labels: n8n team

#13643 fix(editor): Disable deactivated node execution
  packages/frontend/editor-ui/src/components/NodeExecuteButton.test.ts
  packages/frontend/editor-ui/src/components/NodeExecuteButton.vue
  packages/frontend/editor-ui/src/components/canvas/elements/nodes/CanvasNodeToolbar.test.ts
  packages/frontend/editor-ui/src/components/canvas/elements/nodes/CanvasNodeToolbar.vue
  packages/frontend/editor-ui/src/plugins/i18n/locales/en.json
Labels: n8n team

#13852 chore: Upgrade babel to address CVE-2025-27789 (no-changelog)
  pnpm-lock.yaml
Labels: n8n team

#13785 feat(editor): Add functionality to delete and rename folders (no-changelog)
  .github/workflows/e2e-reusable.yml
  cypress/composables/folders.ts
  cypress/e2e/49-folders.cy.ts
  cypress/scripts/run-e2e.js
  packages/frontend/@n8n/design-system/src/components/N8nBreadcrumbs/BreadCrumbs.test.ts
  packages/frontend/@n8n/design-system/src/components/N8nBreadcrumbs/Breadcrumbs.vue
  packages/frontend/@n8n/design-system/src/components/N8nBreadcrumbs/__snapshots__/BreadCrumbs.test.ts.snap
  packages/frontend/editor-ui/src/Interface.ts
  packages/frontend/editor-ui/src/api/workflows.ts
  packages/frontend/editor-ui/src/components/Folders/DeleteFolderModal.vue
  packages/frontend/editor-ui/src/components/Folders/FolderBreadcrumbs.vue
  packages/frontend/editor-ui/src/components/Folders/FolderCard.test.ts
  packages/frontend/editor-ui/src/components/Folders/FolderCard.vue
  packages/frontend/editor-ui/src/components/Modals.vue
  packages/frontend/editor-ui/src/components/Projects/ProjectHeader.vue
  packages/frontend/editor-ui/src/constants.ts
  packages/frontend/editor-ui/src/plugins/i18n/locales/en.json
  packages/frontend/editor-ui/src/stores/folders.store.ts
  packages/frontend/editor-ui/src/stores/ui.store.ts
  packages/frontend/editor-ui/src/views/WorkflowsView.test.ts
  packages/frontend/editor-ui/src/views/WorkflowsView.vue
Labels: n8n team

#13531 fix(editor): Ai 695 update executions view ux (no-changelog)
  packages/frontend/editor-ui/src/components/executions/workflow/WorkflowExecutionsPreview.test.ts
  packages/frontend/editor-ui/src/components/executions/workflow/WorkflowExecutionsPreview.vue
  packages/frontend/editor-ui/src/plugins/i18n/locales/en.json
  packages/frontend/editor-ui/src/views/TestDefinition/TestDefinitionNewView.vue
  packages/frontend/editor-ui/src/views/TestDefinition/tests/TestDefinitionNewView.test.ts
Labels: ui, n8n team

#13519 feat(core): Add endpoint GET `/projects/:projectId/folders` (no-changelog)
  packages/@n8n/api-types/package.json
  packages/@n8n/api-types/src/dto/folders/__tests__/list-folder-query.dto.test.ts
  packages/@n8n/api-types/src/dto/folders/list-folder-query.dto.ts
  packages/@n8n/api-types/src/dto/index.ts
  packages/@n8n/permissions/src/constants.ee.ts
  packages/cli/src/controllers/folder.controller.ts
  packages/cli/src/databases/repositories/__tests__/folder.repository.test.ts
  packages/cli/src/databases/repositories/folder.repository.ts
  packages/cli/src/permissions.ee/project-roles.ts
  packages/cli/src/services/folder.service.ts
  packages/cli/test/integration/folder/folder.controller.test.ts
  pnpm-lock.yaml
Labels: core, n8n team

#13832 fix(core): Avoid using structuredClone on node descriptions
  packages/cli/src/load-nodes-and-credentials.ts
Labels: core, n8n team

#13548 feat(core): Add `subFolderCount` to GET `/workflows` and `/folders` (no-changelog)
  packages/@n8n/api-types/src/dto/folders/list-folder-query.dto.ts
  packages/cli/src/databases/entities/folder.ts
  packages/cli/src/databases/repositories/__tests__/folder.repository.test.ts
  packages/cli/src/databases/repositories/folder.repository.ts
  packages/cli/src/databases/repositories/workflow.repository.ts
  packages/cli/test/integration/workflows/workflows.controller.test.ts
Labels: core, n8n team

#13574 feat(core): Update PATCH `/projects/:projectId/folders/:folderId` endpoint to allow moving folder (no-changelog)
  packages/@n8n/api-types/src/dto/folders/__tests__/update-folder.request.dto.test.ts
  packages/@n8n/api-types/src/dto/folders/create-folder.dto.ts
  packages/@n8n/api-types/src/dto/folders/delete-folder.dto.ts
  packages/@n8n/api-types/src/dto/folders/update-folder.dto.ts
  packages/@n8n/api-types/src/schemas/folder.schema.ts
  packages/cli/src/controllers/folder.controller.ts
  packages/cli/src/services/folder.service.ts
  packages/cli/test/integration/folder/folder.controller.test.ts
Labels: core, n8n team

#13865 feat(core): Transfer folder structure when deleting a project (no-changelog)
  packages/cli/src/services/folder.service.ts
  packages/cli/src/services/project.service.ee.ts
  packages/cli/test/integration/project.api.test.ts
Labels: core, n8n team

#11581 test(core): Add LDAP service unit tests (no-changelog)
  packages/cli/src/ldap.ee/__tests__/ldap.service.test.ts
Labels: core, n8n team

#13845 feat(core): Transfer folder structure when deleting user (no-changelog)
  packages/cli/src/controllers/__tests__/users.controller.test.ts
  packages/cli/src/controllers/users.controller.ts
  packages/cli/src/databases/repositories/folder.repository.ts
  packages/cli/src/services/folder.service.ts
  packages/cli/src/services/project.service.ee.ts
  packages/cli/test/integration/users.api.test.ts
Labels: core, n8n team

#13867 fix(editor): Add disabled state with tooltip on project creation buttons if user lacks permission
  packages/frontend/editor-ui/src/components/MainSidebar.vue
  packages/frontend/editor-ui/src/components/Projects/ProjectNavigation.test.ts
  packages/frontend/editor-ui/src/components/Projects/ProjectNavigation.vue
  packages/frontend/editor-ui/src/composables/useGlobalEntityCreation.test.ts
  packages/frontend/editor-ui/src/composables/useGlobalEntityCreation.ts
  packages/frontend/editor-ui/src/plugins/i18n/locales/en.json
Labels: ui, n8n team

#13819 fix(editor): Tweak schema view empty state copy and styling
  cypress/e2e/5-ndv.cy.ts
  packages/frontend/editor-ui/src/components/VirtualSchema.vue
  packages/frontend/editor-ui/src/plugins/i18n/locales/en.json
Labels: n8n team

#13791 docs: Fix image example links in "Chat" README.md
  packages/frontend/@n8n/chat/README.md
Labels: community, in linear

#13386 feat: Hints for tools and agent
  packages/frontend/editor-ui/src/utils/nodeViewUtils.test.ts
  packages/frontend/editor-ui/src/utils/nodeViewUtils.ts
Labels: ui, n8n team

#13752 fix(Postgres Node): RMC do not mark collumn as required if identity_generation is BY DEFAULT
  packages/nodes-base/nodes/Postgres/Postgres.node.ts
  packages/nodes-base/nodes/Postgres/test/v2/operations.test.ts
  packages/nodes-base/nodes/Postgres/test/v2/resourceMapping.test.ts
  packages/nodes-base/nodes/Postgres/test/v2/utils.test.ts
  packages/nodes-base/nodes/Postgres/v2/actions/database/insert.operation.ts
  packages/nodes-base/nodes/Postgres/v2/actions/versionDescription.ts
  packages/nodes-base/nodes/Postgres/v2/methods/resourceMapping.ts
Labels: node/improvement, n8n team, node/issue

#13818 fix(MySQL Node): Fix potential sql injection
  packages/nodes-base/nodes/MySql/test/v1/GenericFunctions.test.ts
  packages/nodes-base/nodes/MySql/v1/GenericFunctions.ts
Labels: node/improvement, n8n team

#13870 fix(editor): Fix logo alignment issues
  packages/frontend/editor-ui/src/components/Logo/Logo.vue
  packages/frontend/editor-ui/src/components/Logo/__tests__/Logo.test.ts
  packages/frontend/editor-ui/src/components/Logo/__tests__/__snapshots__/Logo.test.ts.snap
  packages/frontend/editor-ui/src/components/Logo/logo-icon.svg
Labels: n8n team

#13849 feat(Merge Node): Better pairedItem mapping in combineBySql operation if SELECT query
  packages/nodes-base/nodes/Merge/Merge.node.ts
  packages/nodes-base/nodes/Merge/test/v3/operations.test.ts
  packages/nodes-base/nodes/Merge/test/v3/utils.test.ts
  packages/nodes-base/nodes/Merge/v3/actions/mode/combineBySql.ts
  packages/nodes-base/nodes/Merge/v3/actions/versionDescription.ts
  packages/nodes-base/nodes/Merge/v3/helpers/utils.ts
Labels: node/improvement, n8n team, node/issue

#13900 fix: Update Sentry `rewriteFramesIntegration` prefix (no-changleog)
  packages/frontend/editor-ui/src/plugins/sentry.ts
Labels: n8n team

#13874 feat: Add endpoint to return folder content (no-changelog)
  packages/cli/src/controllers/folder.controller.ts
  packages/cli/src/services/folder.service.ts
  packages/cli/test/integration/folder/folder.controller.test.ts
Labels: core, n8n team

#13880 feat(core): Update list folders endpoint to support filter `excludeFolderIdAndDescendants` (no-changelog)
  packages/@n8n/api-types/src/dto/folders/list-folder-query.dto.ts
  packages/cli/src/databases/repositories/folder.repository.ts
  packages/cli/test/integration/folder/folder.controller.test.ts
Labels: core, n8n team

#13909 fix(OpenAI Chat Model Node): Sort models alphabetically
  packages/@n8n/nodes-langchain/nodes/llms/LMChatOpenAi/methods/__tests__/loadModels.test.ts
  packages/@n8n/nodes-langchain/nodes/llms/LMChatOpenAi/methods/loadModels.ts
Labels: n8n team

#13908 fix(Structured Output Parser Node, Auto-fixing Output Parser Node, Tools Agent Node): Structured output improvements
  cypress/e2e/233-AI-switch-to-logs-on-error.cy.ts
  packages/@n8n/nodes-langchain/nodes/agents/Agent/agents/ToolsAgent/execute.ts
  packages/@n8n/nodes-langchain/nodes/agents/Agent/test/ToolsAgent.test.ts
  packages/@n8n/nodes-langchain/utils/helpers.ts
  packages/@n8n/nodes-langchain/utils/output_parsers/N8nOutputFixingParser.ts
  packages/@n8n/nodes-langchain/utils/output_parsers/N8nStructuredOutputParser.ts
  packages/@n8n/nodes-langchain/utils/tests/helpers.test.ts
Labels: n8n team

#13674 refactor: `createVectorStoreNode` refactoring and embeddings batching support (no-changelog)
  packages/@n8n/nodes-langchain/nodes/vector_store/VectorStoreInMemory/VectorStoreInMemory.node.ts
  packages/@n8n/nodes-langchain/nodes/vector_store/VectorStorePGVector/VectorStorePGVector.node.ts
  packages/@n8n/nodes-langchain/nodes/vector_store/VectorStorePinecone/VectorStorePinecone.node.ts
  packages/@n8n/nodes-langchain/nodes/vector_store/VectorStorePineconeInsert/VectorStorePineconeInsert.node.ts
  packages/@n8n/nodes-langchain/nodes/vector_store/VectorStorePineconeLoad/VectorStorePineconeLoad.node.ts
  packages/@n8n/nodes-langchain/nodes/vector_store/VectorStoreQdrant/VectorStoreQdrant.node.ts
  packages/@n8n/nodes-langchain/nodes/vector_store/VectorStoreSupabase/VectorStoreSupabase.node.ts
  packages/@n8n/nodes-langchain/nodes/vector_store/VectorStoreSupabaseInsert/VectorStoreSupabaseInsert.node.ts
  packages/@n8n/nodes-langchain/nodes/vector_store/VectorStoreSupabaseLoad/VectorStoreSupabaseLoad.node.ts
  packages/@n8n/nodes-langchain/nodes/vector_store/VectorStoreZep/VectorStoreZep.node.ts
  packages/@n8n/nodes-langchain/nodes/vector_store/shared/createVectorStoreNode.ts
  packages/@n8n/nodes-langchain/nodes/vector_store/shared/createVectorStoreNode/README.md
  packages/@n8n/nodes-langchain/nodes/vector_store/shared/createVectorStoreNode/__snapshots__/createVectorStoreNode.test.ts.snap
  packages/@n8n/nodes-langchain/nodes/vector_store/shared/createVectorStoreNode/__tests__/utils.test.ts
  packages/@n8n/nodes-langchain/nodes/vector_store/shared/createVectorStoreNode/constants.ts
  packages/@n8n/nodes-langchain/nodes/vector_store/shared/createVectorStoreNode/createVectorStoreNode.test.ts
  packages/@n8n/nodes-langchain/nodes/vector_store/shared/createVectorStoreNode/createVectorStoreNode.ts
  packages/@n8n/nodes-langchain/nodes/vector_store/shared/createVectorStoreNode/methods/listSearch.ts
  packages/@n8n/nodes-langchain/nodes/vector_store/shared/createVectorStoreNode/operations/__tests__/insertOperation.test.ts
  packages/@n8n/nodes-langchain/nodes/vector_store/shared/createVectorStoreNode/operations/__tests__/loadOperation.test.ts
  packages/@n8n/nodes-langchain/nodes/vector_store/shared/createVectorStoreNode/operations/__tests__/operationHandlers.test.ts
  packages/@n8n/nodes-langchain/nodes/vector_store/shared/createVectorStoreNode/operations/__tests__/retrieveAsToolOperation.test.ts
  packages/@n8n/nodes-langchain/nodes/vector_store/shared/createVectorStoreNode/operations/__tests__/retrieveOperation.test.ts
  packages/@n8n/nodes-langchain/nodes/vector_store/shared/createVectorStoreNode/operations/__tests__/updateOperation.test.ts
  packages/@n8n/nodes-langchain/nodes/vector_store/shared/createVectorStoreNode/operations/index.ts
  packages/@n8n/nodes-langchain/nodes/vector_store/shared/createVectorStoreNode/operations/insertOperation.ts
  packages/@n8n/nodes-langchain/nodes/vector_store/shared/createVectorStoreNode/operations/loadOperation.ts
  packages/@n8n/nodes-langchain/nodes/vector_store/shared/createVectorStoreNode/operations/retrieveAsToolOperation.ts
  packages/@n8n/nodes-langchain/nodes/vector_store/shared/createVectorStoreNode/operations/retrieveOperation.ts
  packages/@n8n/nodes-langchain/nodes/vector_store/shared/createVectorStoreNode/operations/updateOperation.ts
  packages/@n8n/nodes-langchain/nodes/vector_store/shared/createVectorStoreNode/types.ts
  packages/@n8n/nodes-langchain/nodes/vector_store/shared/createVectorStoreNode/utils.ts
  packages/frontend/editor-ui/src/components/canvas/WorkflowCanvas.test.ts
  packages/frontend/editor-ui/src/components/canvas/WorkflowCanvas.vue
Labels: n8n team

#13912 fix(core): License should ignore empty input on onFeatureChange
  packages/cli/src/license.ts
Labels: core, n8n team, release/backport

#13901 feat(editor): Add telemetry for schema preview (no-changelog)
  packages/frontend/editor-ui/src/components/VirtualSchema.test.ts
  packages/frontend/editor-ui/src/components/VirtualSchema.vue
  packages/frontend/editor-ui/src/components/VirtualSchemaItem.vue
  packages/frontend/editor-ui/src/components/__snapshots__/VirtualSchema.test.ts.snap
  packages/frontend/editor-ui/src/composables/useDataSchema.ts
Labels: n8n team

#13898 fix(editor): Fix vitest config (no-changelog)
  vitest.workspace.ts
Labels: n8n team

#13910 fix: Execute method should be assigned to a Routing node even if it has webhook defined
  packages/cli/src/__tests__/utils.test.ts
  packages/cli/src/node-types.ts
  packages/cli/src/utils.ts
  packages/core/src/execution-engine/workflow-execute.ts
Labels: core, n8n team, release/backport

#13920 fix(editor): Increase contrast on hover for AI button
  packages/frontend/editor-ui/src/components/ParameterInputOverrides/FromAiOverrideButton.vue
  packages/frontend/editor-ui/src/components/ParameterInputOverrides/FromAiOverrideField.vue
Labels: n8n team

#13904 refactor: Add Insights schema
  packages/@n8n/api-types/src/index.ts
  packages/@n8n/api-types/src/schemas/__tests__/insights.schema.test.ts
  packages/@n8n/api-types/src/schemas/insights.schema.ts
Labels: n8n team

#13868 refactor(Question and Answer Chain Node): Use new LangChain's syntax
  packages/@n8n/nodes-langchain/nodes/chains/ChainRetrievalQA/ChainRetrievalQa.node.ts
  packages/@n8n/nodes-langchain/nodes/chains/ChainRetrievalQA/test/ChainRetrievalQa.node.test.ts
Labels: n8n team

#13850 refactor(Basic LLM Chain Node): Refactor Basic LLM Chain & add tests
  packages/@n8n/nodes-langchain/nodes/agents/Agent/Agent.node.ts
  packages/@n8n/nodes-langchain/nodes/agents/Agent/agents/ConversationalAgent/execute.ts
  packages/@n8n/nodes-langchain/nodes/agents/Agent/agents/OpenAiFunctionsAgent/execute.ts
  packages/@n8n/nodes-langchain/nodes/agents/Agent/agents/PlanAndExecuteAgent/execute.ts
  packages/@n8n/nodes-langchain/nodes/agents/Agent/agents/ReActAgent/execute.ts
  packages/@n8n/nodes-langchain/nodes/agents/Agent/agents/ToolsAgent/execute.ts
  packages/@n8n/nodes-langchain/nodes/chains/ChainLLM/ChainLlm.node.ts
  packages/@n8n/nodes-langchain/nodes/chains/ChainLLM/methods/chainExecutor.ts
  packages/@n8n/nodes-langchain/nodes/chains/ChainLLM/methods/config.ts
  packages/@n8n/nodes-langchain/nodes/chains/ChainLLM/methods/imageUtils.ts
  packages/@n8n/nodes-langchain/nodes/chains/ChainLLM/methods/index.ts
  packages/@n8n/nodes-langchain/nodes/chains/ChainLLM/methods/promptUtils.ts
  packages/@n8n/nodes-langchain/nodes/chains/ChainLLM/methods/responseFormatter.ts
  packages/@n8n/nodes-langchain/nodes/chains/ChainLLM/methods/types.ts
  packages/@n8n/nodes-langchain/nodes/chains/ChainLLM/test/ChainLlm.node.test.ts
  packages/@n8n/nodes-langchain/nodes/chains/ChainLLM/test/chainExecutor.test.ts
  packages/@n8n/nodes-langchain/nodes/chains/ChainLLM/test/config.test.ts
  packages/@n8n/nodes-langchain/nodes/chains/ChainLLM/test/imageUtils.test.ts
  packages/@n8n/nodes-langchain/nodes/chains/ChainLLM/test/promptUtils.test.ts
  packages/@n8n/nodes-langchain/nodes/chains/ChainLLM/test/responseFormatter.test.ts
  packages/@n8n/nodes-langchain/nodes/chains/ChainLLM/test/utils.test.ts
  packages/@n8n/nodes-langchain/nodes/chains/ChainLLM/utils.ts
  packages/@n8n/nodes-langchain/nodes/llms/LmChatAzureOpenAi/LmChatAzureOpenAi.node.ts
  packages/@n8n/nodes-langchain/utils/output_parsers/N8nOutputParser.ts
Labels: n8n team

#13907 fix(core): Ensure sentry releases follow semver (no-changelog)
  .github/workflows/release-publish.yml
  packages/@n8n/task-runner/src/__tests__/task-runner-sentry.test.ts
  packages/@n8n/task-runner/src/task-runner-sentry.ts
  packages/cli/src/commands/base-command.ts
Labels: core, n8n team

#12461 test(Gmail Node): Add tests for Gmail node v1 (no-changelog)
  packages/nodes-base/nodes/Google/Gmail/GenericFunctions.ts
  packages/nodes-base/nodes/Google/Gmail/test/fixtures/labels.json
  packages/nodes-base/nodes/Google/Gmail/test/fixtures/messages.json
  packages/nodes-base/nodes/Google/Gmail/test/v1/GmailV1.node.test.ts
  packages/nodes-base/nodes/Google/Gmail/test/v1/drafts.workflow.json
  packages/nodes-base/nodes/Google/Gmail/test/v1/labels.workflow.json
  packages/nodes-base/nodes/Google/Gmail/test/v1/message-labels.workflow.json
  packages/nodes-base/nodes/Google/Gmail/test/v1/messages.workflow.json
  packages/nodes-base/nodes/Google/Gmail/test/v2/GmailV2.node.test.ts
  packages/nodes-base/nodes/Google/Gmail/v1/GmailV1.node.ts
  packages/nodes-base/nodes/Google/Gmail/v1/loadOptions.ts
  packages/nodes-base/nodes/Google/Gmail/v2/loadOptions.ts
Labels: node/improvement, n8n team

#13951 fix(core): Update samlify and xml-crypto to address CVE-2025-29775 and CVE-2025-29774
  packages/cli/package.json
  pnpm-lock.yaml
Labels: core, n8n team, security

#13899 fix(editor): Ai 668 UI changes to mock nodes modal (no-changelog)
  packages/frontend/editor-ui/src/components/TestDefinition/EditDefinition/NodesPinning.vue
  packages/frontend/editor-ui/src/components/TestDefinition/EditDefinition/sections/ConfigSection.vue
  packages/frontend/editor-ui/src/components/TestDefinition/EditDefinition/tests/NodesPinning.test.ts
  packages/frontend/editor-ui/src/components/canvas/Canvas.vue
  packages/frontend/editor-ui/src/plugins/i18n/locales/en.json
Labels: n8n team

#13788 feat(editor): Popping logs out into a new window
  cypress/e2e/30-langchain.cy.ts
  packages/frontend/@n8n/design-system/src/components/N8nResizeWrapper/ResizeWrapper.vue
  packages/frontend/@n8n/design-system/src/components/N8nTooltip/Tooltip.vue
  packages/frontend/@n8n/design-system/src/composables/useTooltipAppendTo.ts
  packages/frontend/editor-ui/src/Interface.ts
  packages/frontend/editor-ui/src/components/CanvasChat/CanvasChat.test.ts
  packages/frontend/editor-ui/src/components/CanvasChat/CanvasChat.vue
  packages/frontend/editor-ui/src/components/CanvasChat/components/ChatLogsPanel.vue
  packages/frontend/editor-ui/src/components/CanvasChat/components/ChatMessagesPanel.vue
  packages/frontend/editor-ui/src/components/CanvasChat/composables/usePiPWindow.test.ts
  packages/frontend/editor-ui/src/components/CanvasChat/composables/usePiPWindow.ts
  packages/frontend/editor-ui/src/components/canvas/elements/nodes/render-types/parts/CanvasNodeTrigger.vue
  packages/frontend/editor-ui/src/composables/useCanvasOperations.test.ts
  packages/frontend/editor-ui/src/composables/useCanvasOperations.ts
  packages/frontend/editor-ui/src/composables/useClipboard.ts
  packages/frontend/editor-ui/src/composables/useRunWorkflow.ts
  packages/frontend/editor-ui/src/composables/useToast.ts
  packages/frontend/editor-ui/src/constants.ts
  packages/frontend/editor-ui/src/plugins/i18n/locales/en.json
  packages/frontend/editor-ui/src/plugins/icons/custom.ts
  packages/frontend/editor-ui/src/plugins/icons/index.ts
  packages/frontend/editor-ui/src/stores/workflows.store.ts
  packages/frontend/editor-ui/src/views/NodeView.vue
Labels: n8n team

#13981 Fix summary value displays according to expected api values
  packages/frontend/editor-ui/src/features/insights/insights.api.ts
  packages/frontend/editor-ui/src/features/insights/insights.utils.ts
Labels: n8n team

#13930 feat(editor): Add new telemetry event for schema preview (no-changelog)
  packages/frontend/editor-ui/src/api/schemaPreview.ts
  packages/frontend/editor-ui/src/composables/usePushConnection.ts
  packages/frontend/editor-ui/src/stores/schemaPreview.store.test.ts
  packages/frontend/editor-ui/src/stores/schemaPreview.store.ts
  packages/frontend/editor-ui/src/utils/expressions.test.ts
  packages/frontend/editor-ui/src/utils/expressions.ts
  packages/frontend/editor-ui/src/utils/json-schema.test.ts
  packages/frontend/editor-ui/src/utils/json-schema.ts
Labels: n8n team

#13922 feat(editor): Implement folder move functionality (no-changelog)
  packages/frontend/editor-ui/src/Interface.ts
  packages/frontend/editor-ui/src/api/workflows.ts
  packages/frontend/editor-ui/src/components/Folders/DeleteFolderModal.vue
  packages/frontend/editor-ui/src/components/Folders/MoveToFolderDropdown.vue
  packages/frontend/editor-ui/src/components/Folders/MoveToFolderModal.test.ts
  packages/frontend/editor-ui/src/components/Folders/MoveToFolderModal.vue
  packages/frontend/editor-ui/src/components/Modals.vue
  packages/frontend/editor-ui/src/components/Projects/ProjectHeader.vue
  packages/frontend/editor-ui/src/components/WorkflowCard.vue
  packages/frontend/editor-ui/src/components/layouts/ResourcesListLayout.vue
  packages/frontend/editor-ui/src/constants.ts
  packages/frontend/editor-ui/src/plugins/i18n/locales/en.json
  packages/frontend/editor-ui/src/stores/folders.store.ts
  packages/frontend/editor-ui/src/stores/ui.store.ts
  packages/frontend/editor-ui/src/views/WorkflowsView.test.ts
  packages/frontend/editor-ui/src/views/WorkflowsView.vue
Labels: n8n team

#13987 fix(n8n Form Trigger Node): Add back the query selector for multiselect
  packages/cli/templates/form-trigger.handlebars
Labels: core, n8n team, release/backport

#13860 feat(Merge Node): Add Telemetry for SQL query (no-changelog)
  packages/workflow/src/TelemetryHelpers.ts
  packages/workflow/test/TelemetryHelpers.test.ts
Labels: core, n8n team

#11431 feat(SeaTable Node): Update node with new options
  packages/nodes-base/credentials/SeaTableApi.credentials.ts
  packages/nodes-base/nodes/SeaTable/SeaTable.node.ts
  packages/nodes-base/nodes/SeaTable/SeaTableTrigger.node.ts
  packages/nodes-base/nodes/SeaTable/__tests__/v2/GenericFunctions.test.ts
  packages/nodes-base/nodes/SeaTable/seaTable.svg
  packages/nodes-base/nodes/SeaTable/v1/GenericFunctions.ts
  packages/nodes-base/nodes/SeaTable/v1/Interfaces.ts
  packages/nodes-base/nodes/SeaTable/v1/RowDescription.ts
  packages/nodes-base/nodes/SeaTable/v1/Schema.ts
  packages/nodes-base/nodes/SeaTable/v1/SeaTable.node.ts
  packages/nodes-base/nodes/SeaTable/v1/SeaTableTriggerV1.node.ts
  packages/nodes-base/nodes/SeaTable/v1/SeaTableV1.node.ts
  packages/nodes-base/nodes/SeaTable/v1/VersionDescription.ts
  packages/nodes-base/nodes/SeaTable/v1/types.ts
  packages/nodes-base/nodes/SeaTable/v2/GenericFunctions.ts
  packages/nodes-base/nodes/SeaTable/v2/Schema.ts
  packages/nodes-base/nodes/SeaTable/v2/SeaTableTriggerV2.node.ts
  packages/nodes-base/nodes/SeaTable/v2/SeaTableV2.node.ts
  packages/nodes-base/nodes/SeaTable/v2/actions/Interfaces.ts
  packages/nodes-base/nodes/SeaTable/v2/actions/SeaTable.node.ts
  packages/nodes-base/nodes/SeaTable/v2/actions/asset/getPublicURL.operation.ts
  packages/nodes-base/nodes/SeaTable/v2/actions/asset/index.ts
  packages/nodes-base/nodes/SeaTable/v2/actions/asset/upload.operation.ts
  packages/nodes-base/nodes/SeaTable/v2/actions/base/collaborator.operation.ts
  packages/nodes-base/nodes/SeaTable/v2/actions/base/index.ts
  packages/nodes-base/nodes/SeaTable/v2/actions/base/metadata.operation.ts
  packages/nodes-base/nodes/SeaTable/v2/actions/base/snapshot.operation.ts
  packages/nodes-base/nodes/SeaTable/v2/actions/link/add.operation.ts
  packages/nodes-base/nodes/SeaTable/v2/actions/link/index.ts
  packages/nodes-base/nodes/SeaTable/v2/actions/link/list.operation.ts
  packages/nodes-base/nodes/SeaTable/v2/actions/link/remove.operation.ts
  packages/nodes-base/nodes/SeaTable/v2/actions/router.ts
  packages/nodes-base/nodes/SeaTable/v2/actions/row/create.operation.ts
  packages/nodes-base/nodes/SeaTable/v2/actions/row/get.operation.ts
  packages/nodes-base/nodes/SeaTable/v2/actions/row/index.ts
  packages/nodes-base/nodes/SeaTable/v2/actions/row/list.operation.ts
  packages/nodes-base/nodes/SeaTable/v2/actions/row/lock.operation.ts
  packages/nodes-base/nodes/SeaTable/v2/actions/row/remove.operation.ts
  packages/nodes-base/nodes/SeaTable/v2/actions/row/search.operation.ts
  packages/nodes-base/nodes/SeaTable/v2/actions/row/sharedProperties.ts
  packages/nodes-base/nodes/SeaTable/v2/actions/row/unlock.operation.ts
  packages/nodes-base/nodes/SeaTable/v2/actions/row/update.operation.ts
  packages/nodes-base/nodes/SeaTable/v2/actions/versionDescription.ts
  packages/nodes-base/nodes/SeaTable/v2/methods/index.ts
  packages/nodes-base/nodes/SeaTable/v2/methods/loadOptions.ts
  packages/nodes-base/nodes/SeaTable/v2/types.ts
Labels: node/improvement, node/new, n8n team

#13999 fix(core): Bring back the missing GMT and UTC timezone for workflow settings
  packages/cli/scripts/build.mjs
Labels: core, n8n team

#13796 feat: Allow custom scopes for Entra credential
  packages/nodes-base/credentials/MicrosoftEntraOAuth2Api.credentials.ts
Labels: node/improvement, n8n team

#13697 feat: Add appendN8nAttribution option to sendAndWait operation
  packages/nodes-base/nodes/Discord/v2/helpers/utils.ts
  packages/nodes-base/nodes/EmailSend/test/v2/sendAndWait.operation.test.ts
  packages/nodes-base/nodes/EmailSend/v2/sendAndWait.operation.ts
  packages/nodes-base/nodes/Google/Chat/GenericFunctions.ts
  packages/nodes-base/nodes/Google/Chat/test/node/sendAndWait.operation.test.ts
  packages/nodes-base/nodes/Microsoft/Outlook/test/v2/node/message/sendAndWait.test.ts
  packages/nodes-base/nodes/Microsoft/Outlook/v2/actions/message/sendAndWait.operation.ts
  packages/nodes-base/nodes/Microsoft/Teams/v2/actions/chatMessage/sendAndWait.operation.ts
  packages/nodes-base/nodes/Slack/V2/GenericFunctions.ts
  packages/nodes-base/nodes/Telegram/GenericFunctions.ts
  packages/nodes-base/nodes/Telegram/tests/node/sendAndWait.operation.test.ts
  packages/nodes-base/nodes/WhatsApp/GenericFunctions.ts
  packages/nodes-base/nodes/WhatsApp/WhatsApp.node.ts
  packages/nodes-base/nodes/WhatsApp/tests/utils.test.ts
  packages/nodes-base/utils/sendAndWait/email-templates.ts
  packages/nodes-base/utils/sendAndWait/utils.ts
Labels: node/improvement, n8n team

#13925 fix(core): Don't fail partial execution when an unrelated node is dirty
  packages/core/src/execution-engine/__tests__/workflow-execute.test.ts
  packages/core/src/execution-engine/partial-execution-utils/__tests__/directed-graph.test.ts
  packages/core/src/execution-engine/partial-execution-utils/directed-graph.ts
  packages/core/src/execution-engine/workflow-execute.ts
Labels: core, n8n team, release/backport

#13984 ci: Pin all workflow actions
  .github/workflows/benchmark-destroy-nightly.yml
  .github/workflows/benchmark-nightly.yml
  .github/workflows/check-documentation-urls.yml
  .github/workflows/check-pr-title.yml
  .github/workflows/chromatic.yml
  .github/workflows/ci-master.yml
  .github/workflows/ci-postgres-mysql.yml
  .github/workflows/ci-pull-requests.yml
  .github/workflows/docker-base-image.yml
  .github/workflows/docker-images-benchmark.yml
  .github/workflows/docker-images-custom.yml
  .github/workflows/docker-images-nightly.yml
  .github/workflows/e2e-reusable.yml
  .github/workflows/e2e-tests-pr.yml
  .github/workflows/e2e-tests.yml
  .github/workflows/linting-reusable.yml
  .github/workflows/notify-pr-status.yml
  .github/workflows/release-create-pr.yml
  .github/workflows/release-publish.yml
  .github/workflows/release-push-to-channel.yml
  .github/workflows/test-workflows.yml
Labels: n8n team

#14019 fix(core): Ensure frontend sentry releases also follow semver
  packages/cli/src/server.ts
Labels: core, n8n team

#13989 fix(core): Allow running webhook servers in multi-main mode
  packages/cli/src/commands/webhook.ts
Labels: core, n8n team

#13942 feat(core): Enable folders feature via license server
  packages/cli/src/constants.ts
  packages/cli/src/controllers/e2e.controller.ts
  packages/cli/src/license.ts
  packages/cli/src/services/frontend.service.ts
Labels: core, n8n team

#13985 fix: Allow saved credenitals types of up to 64 characters instead of 32
  packages/@n8n/api-types/src/dto/credentials/__tests__/create-credential.dto.test.ts
  packages/@n8n/api-types/src/dto/credentials/create-credential.dto.ts
Labels: n8n team

#13715 feat(editor): Always show collapsed panel at the bottom of canvas
  packages/frontend/@n8n/chat/src/components/MessagesList.vue
  packages/frontend/@n8n/design-system/src/components/N8nButton/Button.vue
  packages/frontend/@n8n/design-system/src/types/button.ts
  packages/frontend/editor-ui/src/components/AskAssistant/AskAssistantFloatingButton.vue
  packages/frontend/editor-ui/src/components/CanvasChat/CanvasChat.vue
  packages/frontend/editor-ui/src/components/CanvasChat/CanvasChatSwitch.vue
  packages/frontend/editor-ui/src/components/CanvasChat/components/ChatMessagesPanel.vue
  packages/frontend/editor-ui/src/components/CanvasChat/components/PanelHeader.vue
  packages/frontend/editor-ui/src/components/CanvasChat/composables/useChatState.ts
  packages/frontend/editor-ui/src/components/CanvasChat/future/LogsPanel.test.ts
  packages/frontend/editor-ui/src/components/CanvasChat/future/LogsPanel.vue
  packages/frontend/editor-ui/src/components/CanvasChat/future/components/LogsOverviewPanel.vue
  packages/frontend/editor-ui/src/composables/useClearExecutionButtonVisible.ts
  packages/frontend/editor-ui/src/constants.ts
  packages/frontend/editor-ui/src/plugins/i18n/locales/en.json
  packages/frontend/editor-ui/src/router.ts
  packages/frontend/editor-ui/src/stores/settings.store.ts
  packages/frontend/editor-ui/src/stores/workflows.store.ts
  packages/frontend/editor-ui/src/views/NodeView.vue
Labels: n8n team

#13941 feat(core): Allow transferring user's data to team project when deleting them (no-changelog)
  packages/cli/src/controllers/users.controller.ts
  packages/cli/test/integration/users.api.test.ts
Labels: core, n8n team

#14029 fix: Skip project resource movement test until more reliable (no-changelog)
  cypress/e2e/39-projects.cy.ts
Labels: n8n team

#14031 fix(editor): Fix routing between workflow editing and new workflow pages
  cypress/composables/create.ts
  cypress/e2e/39-projects.cy.ts
  packages/frontend/editor-ui/src/views/NodeView.vue
Labels: n8n team

#14042 feat(core): Allow community nodes to be used as tools
  packages/@n8n/config/src/configs/nodes.config.ts
  packages/@n8n/config/test/config.test.ts
  packages/cli/src/__tests__/node-types.test.ts
  packages/cli/src/node-types.ts
Labels: core, n8n team

#13802 fix(core): Do not use `url.includes` to check for domain names
  packages/@n8n/nodes-langchain/nodes/llms/LMChatOpenAi/LmChatOpenAi.node.ts
  packages/@n8n/nodes-langchain/nodes/llms/LMChatOpenAi/methods/loadModels.ts
  packages/@n8n/nodes-langchain/nodes/vendors/OpenAi/methods/listSearch.ts
  packages/nodes-base/credentials/CustomerIoApi.credentials.ts
  packages/nodes-base/credentials/MindeeInvoiceApi.credentials.ts
  packages/nodes-base/credentials/MindeeReceiptApi.credentials.ts
Labels: node/improvement, n8n team

#13855 feat(core): Allow customizing auth cookie samesite attribute and CSP headers
  packages/@n8n/config/src/configs/auth.config.ts
  packages/@n8n/config/src/configs/security.config.ts
  packages/@n8n/config/src/index.ts
  packages/@n8n/config/test/config.test.ts
  packages/cli/src/auth/__tests__/auth.service.test.ts
  packages/cli/src/auth/auth.service.ts
  packages/cli/src/config/schema.ts
  packages/cli/src/server.ts
  packages/cli/src/services/frontend.service.ts
Labels: core, n8n team

#13507 feat(n8n Form Trigger Node): Respond with File
  packages/cli/templates/form-trigger-completion.handlebars
  packages/nodes-base/nodes/Form/Form.node.ts
  packages/nodes-base/nodes/Form/formCompletionUtils.ts
  packages/nodes-base/nodes/Form/test/Form.node.test.ts
  packages/nodes-base/nodes/Form/test/formCompletionUtils.test.ts
Labels: node/improvement, core, n8n team

#14047 refactor(core): Add strong typing for `INodeTypeBaseDescription['group']` (no-changelog)
  packages/cli/src/__tests__/load-nodes-and-credentials.test.ts
  packages/frontend/editor-ui/src/components/Node/NodeCreator/__tests__/utils.ts
  packages/frontend/editor-ui/src/components/Node/NodeCreator/composables/useActionsGeneration.ts
  packages/frontend/editor-ui/src/composables/useUniqueNodeName.test.ts
  packages/workflow/src/Interfaces.ts
Labels: core, n8n team

#14052 fix: Fix the example command for license clearing (no-changelog)
  packages/cli/src/commands/license/clear.ts
Labels: core, n8n team

#13875 feat(editor): Add variables and context section to schema view
  packages/frontend/editor-ui/src/__tests__/setup.ts
  packages/frontend/editor-ui/src/components/ExpressionEditModal.test.ts
  packages/frontend/editor-ui/src/components/RunData.test.ts
  packages/frontend/editor-ui/src/components/VirtualSchema.test.ts
  packages/frontend/editor-ui/src/components/VirtualSchema.vue
  packages/frontend/editor-ui/src/components/VirtualSchemaHeader.vue
  packages/frontend/editor-ui/src/components/VirtualSchemaItem.vue
  packages/frontend/editor-ui/src/components/__snapshots__/VirtualSchema.test.ts.snap
  packages/frontend/editor-ui/src/composables/useDataSchema.test.ts
  packages/frontend/editor-ui/src/composables/useDataSchema.ts
  packages/frontend/editor-ui/src/plugins/i18n/locales/en.json
  packages/frontend/editor-ui/src/utils/mappingUtils.ts
Labels: n8n team

#14048 feat: Add nodeAsTool description overrides for tool version (no-changelog)
  packages/cli/src/__tests__/load-nodes-and-credentials.test.ts
  packages/cli/src/load-nodes-and-credentials.ts
  packages/workflow/src/Interfaces.ts
Labels: core, n8n team

#14054 fix(editor): Add smart decimals directive
  packages/@n8n/utils/src/number/smartDecimal.test.ts
  packages/@n8n/utils/src/number/smartDecimal.ts
  packages/frontend/@n8n/design-system/src/directives/n8n-smart-decimal.test.ts
  packages/frontend/@n8n/design-system/src/directives/n8n-smart-decimal.ts
Labels: n8n team

#14074 feat(core): Allow transferring folder to project root with delete operation (no-changelog)
  packages/cli/src/databases/repositories/workflow.repository.ts
  packages/cli/src/services/folder.service.ts
  packages/cli/test/integration/folder/folder.controller.test.ts
Labels: core, n8n team

#13986 feat(Simple Vector Store Node): Implement store cleaning based on age/used memory
  packages/@n8n/nodes-langchain/nodes/vector_store/VectorStoreInMemory/VectorStoreInMemory.node.ts
  packages/@n8n/nodes-langchain/nodes/vector_store/VectorStoreInMemoryInsert/VectorStoreInMemoryInsert.node.ts
  packages/@n8n/nodes-langchain/nodes/vector_store/VectorStoreInMemoryLoad/VectorStoreInMemoryLoad.node.ts
  packages/@n8n/nodes-langchain/nodes/vector_store/shared/MemoryManager/MemoryCalculator.ts
  packages/@n8n/nodes-langchain/nodes/vector_store/shared/MemoryManager/MemoryVectorStoreManager.ts
  packages/@n8n/nodes-langchain/nodes/vector_store/shared/MemoryManager/StoreCleanupService.ts
  packages/@n8n/nodes-langchain/nodes/vector_store/shared/MemoryManager/config.ts
  packages/@n8n/nodes-langchain/nodes/vector_store/shared/MemoryManager/test/MemoryCalculator.test.ts
  packages/@n8n/nodes-langchain/nodes/vector_store/shared/MemoryManager/test/MemoryVectorStoreManager.test.ts
  packages/@n8n/nodes-langchain/nodes/vector_store/shared/MemoryManager/test/StoreCleanupService.test.ts
  packages/@n8n/nodes-langchain/nodes/vector_store/shared/MemoryManager/test/config.test.ts
  packages/@n8n/nodes-langchain/nodes/vector_store/shared/MemoryManager/types.ts
  packages/@n8n/nodes-langchain/nodes/vector_store/shared/MemoryVectorStoreManager.test.ts
  packages/@n8n/nodes-langchain/nodes/vector_store/shared/MemoryVectorStoreManager.ts
Labels: n8n team

#14075 feat(core): Allow moving workflow to project root (no-changelog)
  packages/cli/src/workflows/workflow.service.ts
  packages/cli/test/integration/workflows/workflows.controller.test.ts
Labels: core, n8n team

#13997 fix(editor): Addressing internal testing feedback for folders (no-changelog)
  cypress/composables/folders.ts
  cypress/composables/ndv.ts
  cypress/e2e/30-editor-after-route-changes.cy.ts
  cypress/e2e/39-projects.cy.ts
  cypress/e2e/49-folders.cy.ts
  cypress/pages/workflows.ts
  packages/frontend/@n8n/design-system/src/components/N8nActionBox/ActionBox.vue
  packages/frontend/@n8n/design-system/src/components/N8nBreadcrumbs/Breadcrumbs.vue
  packages/frontend/@n8n/design-system/src/css/_tokens.scss
  packages/frontend/@n8n/design-system/src/types/user.ts
  packages/frontend/editor-ui/src/Interface.ts
  packages/frontend/editor-ui/src/api/workflows.ts
  packages/frontend/editor-ui/src/components/CommunityPlusEnrollmentModal.vue
  packages/frontend/editor-ui/src/components/Folders/DeleteFolderModal.vue
  packages/frontend/editor-ui/src/components/Folders/FolderBreadcrumbs.vue
  packages/frontend/editor-ui/src/components/Folders/MoveToFolderDropdown.vue
  packages/frontend/editor-ui/src/components/Folders/MoveToFolderModal.vue
  packages/frontend/editor-ui/src/components/MainHeader/WorkflowDetails.vue
  packages/frontend/editor-ui/src/components/PersonalizationModal.vue
  packages/frontend/editor-ui/src/components/Projects/ProjectHeader.vue
  packages/frontend/editor-ui/src/components/WorkflowCard.vue
  packages/frontend/editor-ui/src/components/forms/ResourceFiltersDropdown.vue
  packages/frontend/editor-ui/src/components/layouts/ResourcesListLayout.vue
  packages/frontend/editor-ui/src/composables/useFolders.test.ts
  packages/frontend/editor-ui/src/composables/useFolders.ts
  packages/frontend/editor-ui/src/composables/useGlobalEntityCreation.ts
  packages/frontend/editor-ui/src/constants.ts
  packages/frontend/editor-ui/src/plugins/i18n/locales/en.json
  packages/frontend/editor-ui/src/stores/folders.store.ts
  packages/frontend/editor-ui/src/stores/ui.store.ts
  packages/frontend/editor-ui/src/views/SettingsUsageAndPlan.test.ts
  packages/frontend/editor-ui/src/views/SettingsUsageAndPlan.vue
  packages/frontend/editor-ui/src/views/VariablesView.vue
  packages/frontend/editor-ui/src/views/WorkflowsView.test.ts
  packages/frontend/editor-ui/src/views/WorkflowsView.vue
Labels: n8n team

#14076 refactor(core): Remove env variable to enable folders (no-changelog)
  .github/workflows/e2e-reusable.yml
  cypress/e2e/49-folders.cy.ts
  cypress/scripts/run-e2e.js
  packages/cli/src/config/schema.ts
  packages/cli/src/services/frontend.service.ts
Labels: core, n8n team

#14081 fix(editor): Fix filter button overflow in workflows list (no-changelog)
  packages/frontend/editor-ui/src/components/forms/ResourceFiltersDropdown.vue
Labels: n8n team

#13905 feat(core): Store insights data at the end of executions (no-changelog)
  packages/cli/src/databases/entities/index.ts
  packages/cli/src/databases/migrations/common/1739549398681-CreateAnalyticsTables.ts
  packages/cli/src/databases/migrations/common/1741167584277-RenameAnalyticsToInsights.ts
  packages/cli/src/databases/migrations/mysqldb/index.ts
  packages/cli/src/databases/migrations/postgresdb/index.ts
  packages/cli/src/databases/migrations/sqlite/index.ts
  packages/cli/src/modules/insights/__tests__/insights.service.test.ts
  packages/cli/src/modules/insights/entities/__tests__/db-utils.ts
  packages/cli/src/modules/insights/entities/__tests__/insights-by-period.test.ts
  packages/cli/src/modules/insights/entities/__tests__/insights-raw.test.ts
  packages/cli/src/modules/insights/entities/insights-by-period.ts
  packages/cli/src/modules/insights/entities/insights-metadata.ts
  packages/cli/src/modules/insights/entities/insights-raw.ts
  packages/cli/src/modules/insights/entities/insights-shared.ts
  packages/cli/src/modules/insights/insights.module.ts
  packages/cli/src/modules/insights/insights.service.ts
  packages/cli/src/modules/insights/repositories/insights-by-period.repository.ts
  packages/cli/src/modules/insights/repositories/insights-metadata.repository.ts
  packages/cli/src/modules/insights/repositories/insights-raw.repository.ts
  packages/cli/src/utils/sql.ts
  packages/cli/test/integration/shared/db/workflows.ts
  packages/cli/test/integration/shared/test-db.ts
  packages/workflow/src/Interfaces.ts
Labels: core, n8n team

#14093 perf(editor): Prevent excessive fetch requests from workflows list (no-changelog)
  packages/frontend/editor-ui/src/views/WorkflowsView.vue
Labels: n8n team

#14063 feat(API): Only allow instance owners and admins to see overview
  packages/@n8n/permissions/src/constants.ee.ts
  packages/cli/src/modules/insights/insights.controller.ts
  packages/cli/src/permissions.ee/global-roles.ts
  packages/frontend/editor-ui/src/permissions.test.ts
  packages/frontend/editor-ui/src/stores/rbac.store.ts
Labels: core, n8n team

#13607 feat(Extract from File Node): Add relax_quote option
  packages/nodes-base/nodes/Files/ExtractFromFile/actions/spreadsheet.operation.ts
  packages/nodes-base/nodes/SpreadsheetFile/description.ts
  packages/nodes-base/nodes/SpreadsheetFile/v2/fromFile.operation.ts
Labels: node/improvement, community, in linear

#13424 feat(editor): Insights summary banner
  packages/@n8n/permissions/src/constants.ee.ts
  packages/frontend/@n8n/design-system/src/components/N8nLoading/Loading.vue
  packages/frontend/editor-ui/src/components/Projects/ProjectHeader.test.ts
  packages/frontend/editor-ui/src/components/Projects/ProjectHeader.vue
  packages/frontend/editor-ui/src/components/executions/global/GlobalExecutionsList.vue
  packages/frontend/editor-ui/src/composables/useOverview.ts
  packages/frontend/editor-ui/src/features/insights/components/InsightsSummary.test.ts
  packages/frontend/editor-ui/src/features/insights/components/InsightsSummary.vue
  packages/frontend/editor-ui/src/features/insights/components/__snapshots__/InsightsSummary.test.ts.snap
  packages/frontend/editor-ui/src/features/insights/insights.api.ts
  packages/frontend/editor-ui/src/features/insights/insights.constants.ts
  packages/frontend/editor-ui/src/features/insights/insights.store.ts
  packages/frontend/editor-ui/src/features/insights/insights.types.ts
  packages/frontend/editor-ui/src/features/insights/insights.utils.ts
  packages/frontend/editor-ui/src/init.ts
  packages/frontend/editor-ui/src/permissions.test.ts
  packages/frontend/editor-ui/src/plugins/i18n/locales/en.json
  packages/frontend/editor-ui/src/plugins/icons/index.ts
  packages/frontend/editor-ui/src/stores/rbac.store.ts
  packages/frontend/editor-ui/src/views/CredentialsView.vue
  packages/frontend/editor-ui/src/views/ExecutionsView.vue
  packages/frontend/editor-ui/src/views/WorkflowsView.vue
Labels: ui, n8n team

#14026 feat(core): Add tool to uninstall a community node
  packages/cli/src/commands/__tests__/community-node.test.ts
  packages/cli/src/commands/community-node.ts
Labels: core, n8n team

#14062 feat(API): Implement compaction logic for insights
  packages/cli/src/modules/insights/__tests__/insights.service.test.ts
  packages/cli/src/modules/insights/entities/__tests__/db-utils.ts
  packages/cli/src/modules/insights/insights.config.ts
  packages/cli/src/modules/insights/insights.service.ts
  packages/cli/src/modules/insights/repositories/insights-by-period.repository.ts
  packages/cli/src/modules/insights/repositories/insights-raw.repository.ts
Labels: core, n8n team

#14118 fix(n8n Form Trigger Node): Fix docs link (no-changelog)
  packages/nodes-base/nodes/Form/Form.node.ts
Labels: node/improvement, community, in linear

#14125 fix(editor): Fix folder creation (no-changelog)
  packages/frontend/editor-ui/src/views/WorkflowsView.vue
Labels: n8n team

#14117 fix(editor): Update registered community CTA (no-changelog)
  packages/frontend/editor-ui/src/components/CommunityPlusEnrollmentModal.vue
  packages/frontend/editor-ui/src/constants.ts
  packages/frontend/editor-ui/src/plugins/i18n/locales/en.json
Labels: n8n team

#13670 feat: Add xAiGrok Chat Model node and credentials
  packages/@n8n/nodes-langchain/credentials/XAiApi.credentials.ts
  packages/@n8n/nodes-langchain/nodes/agents/Agent/Agent.node.ts
  packages/@n8n/nodes-langchain/nodes/llms/LmChatXAiGrok/LmChatXAiGrok.node.ts
  packages/@n8n/nodes-langchain/nodes/llms/LmChatXAiGrok/logo.dark.svg
  packages/@n8n/nodes-langchain/nodes/llms/LmChatXAiGrok/logo.svg
  packages/@n8n/nodes-langchain/package.json
Labels: n8n team, tests-needed

#14082 feat(Salesforce Node): Add support for PKCE
  packages/nodes-base/credentials/SalesforceOAuth2Api.credentials.ts
Labels: node/improvement, n8n team

#14131 refactor: Convert all enums to const object types in nodes-base (no-changelog)
  packages/nodes-base/nodes/Aws/DynamoDB/types.ts
  packages/nodes-base/nodes/Brevo/GenericFunctions.ts
  packages/nodes-base/nodes/Clockify/ClockifyTrigger.node.ts
  packages/nodes-base/nodes/Clockify/CommonDtos.ts
  packages/nodes-base/nodes/Clockify/EntryType.ts
  packages/nodes-base/nodes/Clockify/EntryTypeEnum.ts
  packages/nodes-base/nodes/Clockify/ProjectInterfaces.ts
  packages/nodes-base/nodes/Clockify/UserDtos.ts
  packages/nodes-base/nodes/Clockify/WorkpaceInterfaces.ts
  packages/nodes-base/nodes/Cortex/AnalyzerDescriptions.ts
  packages/nodes-base/nodes/Cortex/AnalyzerInterface.ts
  packages/nodes-base/nodes/Cortex/ResponderDescription.ts
  packages/nodes-base/nodes/Formstack/GenericFunctions.ts
  packages/nodes-base/nodes/Freshdesk/Freshdesk.node.ts
  packages/nodes-base/nodes/Google/Chat/MessageInterface.ts
  packages/nodes-base/nodes/Google/Drive/v2/helpers/interfaces.ts
  packages/nodes-base/nodes/Mailchimp/Mailchimp.node.ts
  packages/nodes-base/nodes/PayPal/PaymentInteface.ts
  packages/nodes-base/nodes/TheHive/descriptions/AlertDescription.ts
  packages/nodes-base/nodes/TheHive/descriptions/CaseDescription.ts
  packages/nodes-base/nodes/TheHive/descriptions/ObservableDescription.ts
  packages/nodes-base/nodes/TheHive/interfaces/AlertInterface.ts
  packages/nodes-base/nodes/TheHive/interfaces/CaseInterface.ts
  packages/nodes-base/nodes/TheHive/interfaces/LogInterface.ts
  packages/nodes-base/nodes/TheHive/interfaces/ObservableInterface.ts
  packages/nodes-base/nodes/TheHive/interfaces/TaskInterface.ts
  packages/nodes-base/nodes/TheHiveProject/descriptions/common.description.ts
  packages/nodes-base/nodes/TheHiveProject/helpers/constants.ts
  packages/nodes-base/nodes/TheHiveProject/helpers/interfaces.ts
  packages/nodes-base/nodes/Todoist/v1/OperationHandler.ts
  packages/nodes-base/nodes/Todoist/v2/OperationHandler.ts
Labels: node/improvement, n8n team

#14116 feat: Cat 720 improve pre merge ci
  .github/workflows/e2e-reusable.yml
  .github/workflows/linting-reusable.yml
Labels: n8n team

#13927 feat(core): Implement API to retrieve summary metrics
  packages/cli/src/modules/insights/__tests__/insights.controller.test.ts
  packages/cli/src/modules/insights/__tests__/insights.service.test.ts
  packages/cli/src/modules/insights/entities/__tests__/db-utils.ts
  packages/cli/src/modules/insights/entities/__tests__/insights-by-period.test.ts
  packages/cli/src/modules/insights/entities/__tests__/insights-raw.test.ts
  packages/cli/src/modules/insights/entities/insights-by-period.ts
  packages/cli/src/modules/insights/entities/insights-shared.ts
  packages/cli/src/modules/insights/insights.controller.ts
  packages/cli/src/modules/insights/insights.module.ts
  packages/cli/src/modules/insights/insights.service.ts
  packages/cli/src/modules/insights/repositories/insights-by-period.repository.ts
  packages/cli/src/permissions.ee/global-roles.ts
Labels: core, n8n team

#14044 feat(editor): Improve schema view empty state when node has binary data
  packages/frontend/editor-ui/src/components/VirtualSchema.test.ts
  packages/frontend/editor-ui/src/components/VirtualSchema.vue
  packages/frontend/editor-ui/src/composables/useDataSchema.ts
  packages/frontend/editor-ui/src/plugins/i18n/locales/en.json
Labels: n8n team

#14097 refactor: Support rendering NodeIcon without a full node type object (no-changelog)
  packages/frontend/editor-ui/src/__tests__/mocks.ts
  packages/frontend/editor-ui/src/components/Node/NodeCreator/Modes/NodesMode.vue
  packages/frontend/editor-ui/src/components/Node/NodeCreator/Panel/NodesListPanel.vue
  packages/frontend/editor-ui/src/components/Node/NodeCreator/composables/useViewStacks.ts
  packages/frontend/editor-ui/src/components/NodeIcon.vue
  packages/frontend/editor-ui/src/components/__snapshots__/VirtualSchema.test.ts.snap
  packages/frontend/editor-ui/src/components/canvas/elements/nodes/CanvasNode.vue
  packages/frontend/editor-ui/src/components/canvas/elements/nodes/CanvasNodeRenderer.vue
  packages/frontend/editor-ui/src/components/canvas/elements/nodes/render-types/CanvasNodeDefault.vue
  packages/frontend/editor-ui/src/components/canvas/elements/nodes/render-types/__snapshots__/CanvasNodeDefault.test.ts.snap
  packages/frontend/editor-ui/src/composables/useCanvasMapping.test.ts
  packages/frontend/editor-ui/src/composables/useCanvasMapping.ts
  packages/frontend/editor-ui/src/types/canvas.ts
  packages/frontend/editor-ui/src/utils/nodeIcon.test.ts
  packages/frontend/editor-ui/src/utils/nodeIcon.ts
  packages/frontend/editor-ui/src/utils/nodeTypesUtils.ts
Labels: n8n team

#13683 fix(editor): Adjust URL on lost change warning Cancel or failed save
  cypress/composables/modals/save-changes-modal.ts
  cypress/composables/workflowsPage.ts
  cypress/e2e/44-routing.cy.ts
  packages/frontend/editor-ui/src/composables/useWorkflowHelpers.ts
Labels: n8n team

#14057 feat(Matrix Node): Add audio and video media types
  packages/nodes-base/nodes/Matrix/MediaDescription.ts
Labels: node/improvement, community, in linear

#14142 fix(OpenAI Node): Show correct inputs for AI node
  packages/@n8n/nodes-langchain/nodes/vendors/OpenAi/actions/versionDescription.ts
Labels: n8n team, release/backport

#14155 fix: Correct connections in SentimentAnalysis and TextClassifier
  packages/@n8n/nodes-langchain/nodes/chains/SentimentAnalysis/SentimentAnalysis.node.ts
  packages/@n8n/nodes-langchain/nodes/chains/TextClassifier/TextClassifier.node.ts
Labels: release/backport

#13940 fix(Microsoft SQL Node): Fix maximum call stack on execute query
  packages/nodes-base/nodes/Microsoft/Sql/MicrosoftSql.node.ts
Labels: node/improvement, n8n team

#14126 fix(editor): Show left-hand NDV floating nodes in correct order
  cypress/e2e/5-ndv.cy.ts
  cypress/fixtures/Floating_Nodes.json
  packages/frontend/editor-ui/src/components/NDVFloatingNodes.vue
Labels: n8n team
