Repository n8n-io/n8n, pull requests merged in 2025-01, with the labels that each got.

#12383 test(Cron Node): Add workflow test to Cron node (no-changelog)
  packages/nodes-base/nodes/Cron/test/Cron.node.test.ts
Labels: n8n team

#12415 fix(core): Fix task runner sending too many offers
  packages/@n8n/task-runner/src/js-task-runner/__tests__/task-runner.test.ts
  packages/@n8n/task-runner/src/task-runner.ts
Labels: n8n team

#12432 ci: Fix e2e tests
  cypress/e2e/14-mapping.cy.ts
Labels: n8n team

#12411 refactor(core): Hide stack trace for warning-level errors
  packages/cli/src/errors/feature-not-licensed.error.ts
  packages/core/src/error-reporter.ts
  packages/core/test/error-reporter.test.ts
Labels: core, n8n team

#12439 fix(HTTP Request Node): Fix typo in hint
  packages/nodes-base/nodes/HttpRequest/V3/HttpRequestV3.node.ts
Labels: node/improvement, n8n team

#11284 feat(core): Offload manual executions to workers
  packages/@n8n/config/src/configs/logging.config.ts
  packages/cli/src/constants.ts
  packages/cli/src/executions/__tests__/execution.service.test.ts
  packages/cli/src/executions/execution.service.ts
  packages/cli/src/push/__tests__/index.test.ts
  packages/cli/src/push/index.ts
  packages/cli/src/scaling/__tests__/job-processor.service.test.ts
  packages/cli/src/scaling/__tests__/pubsub-handler.test.ts
  packages/cli/src/scaling/job-processor.ts
  packages/cli/src/scaling/pubsub/pubsub-handler.ts
  packages/cli/src/scaling/scaling.types.ts
  packages/cli/src/webhooks/test-webhooks.ts
  packages/cli/src/webhooks/webhook-helpers.ts
  packages/cli/src/workflow-execute-additional-data.ts
  packages/cli/src/workflow-runner.ts
  packages/cli/src/workflows/workflow-execution.service.ts
  packages/cli/test/integration/collaboration/collaboration.service.test.ts
  packages/core/src/InstanceSettings.ts
  packages/design-system/src/components/index.ts
  packages/editor-ui/src/components/RunData.vue
  packages/editor-ui/src/plugins/i18n/locales/en.json
  packages/workflow/src/Constants.ts
  packages/workflow/src/Interfaces.ts
Labels: core, n8n team

#12440 chore: Upgrade tournament to 1.0.6
  packages/workflow/package.json
  pnpm-lock.yaml
Labels: core, n8n team

#12435 refactor(core): Extract SAML requests payloads into DTOs
  packages/@n8n/api-types/src/dto/index.ts
  packages/@n8n/api-types/src/dto/saml/__tests__/saml-preferences.dto.test.ts
  packages/@n8n/api-types/src/dto/saml/saml-acs.dto.ts
  packages/@n8n/api-types/src/dto/saml/saml-preferences.dto.ts
  packages/@n8n/api-types/src/dto/saml/saml-toggle.dto.ts
  packages/cli/src/sso.ee/saml/__tests__/saml-helpers.test.ts
  packages/cli/src/sso.ee/saml/__tests__/saml-validator.test.ts
  packages/cli/src/sso.ee/saml/__tests__/saml.service.ee.test.ts
  packages/cli/src/sso.ee/saml/routes/__tests__/saml.controller.ee.test.ts
  packages/cli/src/sso.ee/saml/routes/saml.controller.ee.ts
  packages/cli/src/sso.ee/saml/saml-helpers.ts
  packages/cli/src/sso.ee/saml/saml-validator.ts
  packages/cli/src/sso.ee/saml/saml.service.ee.ts
  packages/cli/src/sso.ee/saml/service-provider.ee.ts
  packages/cli/src/sso.ee/saml/types.ts
  packages/cli/src/sso.ee/saml/types/index.ts
  packages/cli/src/sso.ee/saml/types/requests.ts
  packages/cli/src/sso.ee/saml/types/saml-attribute-mapping.ts
  packages/cli/src/sso.ee/saml/types/saml-preferences.ts
  packages/cli/src/sso.ee/saml/types/saml-user-attributes.ts
  packages/cli/test/integration/saml/saml-helpers.test.ts
  packages/cli/test/integration/saml/saml.api.test.ts
  packages/cli/test/integration/saml/sample-metadata.ts
  packages/cli/test/integration/shared/utils/test-server.ts
  packages/editor-ui/src/Interface.ts
  packages/editor-ui/src/__tests__/server/endpoints/sso.ts
  packages/editor-ui/src/api/sso.ts
  packages/editor-ui/src/stores/sso.store.ts
  packages/editor-ui/src/views/SettingsSso.test.ts
Labels: core, ui, n8n team

#12431 fix(core): Ensure tasks timeout even if they don't receive settings
  packages/@n8n/task-runner/src/js-task-runner/__tests__/js-task-runner.test.ts
  packages/@n8n/task-runner/src/js-task-runner/__tests__/task-runner.test.ts
  packages/@n8n/task-runner/src/js-task-runner/__tests__/test-data.ts
  packages/@n8n/task-runner/src/js-task-runner/js-task-runner.ts
  packages/@n8n/task-runner/src/task-runner.ts
  packages/@n8n/task-runner/src/task-state.ts
Labels: n8n team, release/backport

#12441 refactor(core): Extract Worfklow import request payload into a DTO
  packages/@n8n/api-types/src/dto/index.ts
  packages/@n8n/api-types/src/dto/workflows/__tests__/import-workflow-from-url.dto.test.ts
  packages/@n8n/api-types/src/dto/workflows/import-workflow-from-url.dto.ts
  packages/cli/src/workflows/__tests__/workflows.controller.test.ts
  packages/cli/src/workflows/workflow.request.ts
  packages/cli/src/workflows/workflows.controller.ts
Labels: core, n8n team

#12437 refactor(core): Add tests to `workflowPostExecute` in `TelemetryEventRelay`
  packages/cli/src/events/__tests__/telemetry-event-relay.test.ts
Labels: core, n8n team

#12426 fix(editor): Fix color scheme of danger disabled button (no-changelog)
  packages/design-system/src/components/N8nButton/Button.scss
  packages/design-system/src/css/_tokens.dark.scss
  packages/design-system/src/css/_tokens.scss
Labels: ui, n8n team

#12442 feat(AI Agent Node): Change Prompt Text Copy (no-changelog)
  packages/@n8n/nodes-langchain/utils/descriptions.ts
Labels: n8n team

#12449 test: Fix flaky mapping test (no-changelog)
  cypress/e2e/14-mapping.cy.ts
Labels: n8n team

#12429 fix(Supabase Node): Allow for filtering on the same field multiple times
  packages/nodes-base/nodes/Supabase/Supabase.node.ts
  packages/nodes-base/nodes/Supabase/tests/Supabase.node.test.ts
Labels: node/improvement, n8n team

#12311 feat: Allow using Vector Stores directly as Tools
  cypress/composables/ndv.ts
  cypress/composables/workflow.ts
  cypress/e2e/4-node-creator.cy.ts
  packages/@n8n/nodes-langchain/nodes/tools/ToolVectorStore/ToolVectorStore.node.ts
  packages/@n8n/nodes-langchain/nodes/vector_store/VectorStorePGVector/VectorStorePGVector.node.ts
  packages/@n8n/nodes-langchain/nodes/vector_store/VectorStorePinecone/VectorStorePinecone.node.ts
  packages/@n8n/nodes-langchain/nodes/vector_store/VectorStoreSupabase/VectorStoreSupabase.node.ts
  packages/@n8n/nodes-langchain/nodes/vector_store/shared/createVectorStoreNode.test.ts
  packages/@n8n/nodes-langchain/nodes/vector_store/shared/createVectorStoreNode.ts
  packages/editor-ui/src/Interface.ts
  packages/editor-ui/src/components/Node/NodeCreator/Modes/NodesMode.vue
  packages/editor-ui/src/components/Node/NodeCreator/composables/useActionsGeneration.ts
  packages/editor-ui/src/components/Node/NodeCreator/composables/useViewStacks.ts
  packages/editor-ui/src/components/Node/NodeCreator/utils.ts
  packages/editor-ui/src/constants.ts
  packages/workflow/src/Interfaces.ts
Labels: n8n team

#12430 fix(editor): Fix Multi option parameter expression when the value is an array
  packages/editor-ui/src/components/ParameterInput.vue
  packages/editor-ui/src/components/ParameterInputWrapper.vue
Labels: ui, n8n team, tests-needed

#12425 fix: Run workflow if active and single webhook service has pin data
  packages/editor-ui/src/composables/useRunWorkflow.test.ts
  packages/editor-ui/src/composables/useRunWorkflow.ts
Labels: ui, n8n team, node/issue

#12443 ci: Fix code coverage collection
  .github/workflows/ci-master.yml
  .github/workflows/units-tests-reusable.yml
  codecov.yml
  turbo.json
Labels: n8n team

#12413 fix(editor): Show all workflows in the error workflow dropdown in the workflow settings
  packages/editor-ui/src/components/WorkflowSettings.test.ts
  packages/editor-ui/src/components/WorkflowSettings.vue
Labels: ui, n8n team

#12464 docs: Add volumes to the Docker example from the README (no-changelog)
  README.md
Labels: n8n team

#12353 fix(Zep Vector Store Node): Cloud vector store integration
  packages/@n8n/nodes-langchain/nodes/vector_store/VectorStoreZep/VectorStoreZep.node.test.ts
  packages/@n8n/nodes-langchain/nodes/vector_store/VectorStoreZep/VectorStoreZep.node.ts
Labels: n8n team

#12462 feat: Add load options to new tool mode for vector stores
  packages/@n8n/nodes-langchain/nodes/vector_store/shared/__snapshots__/createVectorStoreNode.test.ts.snap
  packages/@n8n/nodes-langchain/nodes/vector_store/shared/createVectorStoreNode.test.ts
  packages/@n8n/nodes-langchain/nodes/vector_store/shared/createVectorStoreNode.ts
Labels: n8n team

#12469 fix(core): Allow `index` as top-level item key for Code node
  packages/@n8n/task-runner/src/js-task-runner/__tests__/result-validation.test.ts
  packages/@n8n/task-runner/src/js-task-runner/result-validation.ts
  packages/nodes-base/nodes/Code/Sandbox.ts
  packages/nodes-base/nodes/Code/test/Code.node.test.ts
Labels: node/improvement, n8n team

#12372 feat(editor): Make workflows, credentials, executions and new canvas usable on mobile and touch devices
  packages/design-system/src/components/N8nCard/Card.vue
  packages/design-system/src/composables/useDeviceSupport.test.ts
  packages/design-system/src/composables/useDeviceSupport.ts
  packages/design-system/src/css/index.scss
  packages/design-system/src/css/mixins/_breakpoints.scss
  packages/design-system/src/css/mixins/index.scss
  packages/editor-ui/src/App.vue
  packages/editor-ui/src/components/CredentialCard.vue
  packages/editor-ui/src/components/MainHeader/MainHeader.vue
  packages/editor-ui/src/components/MainHeader/WorkflowDetails.vue
  packages/editor-ui/src/components/Node/NodeCreator/NodeCreator.vue
  packages/editor-ui/src/components/Node/NodeCreator/Panel/NodesListPanel.vue
  packages/editor-ui/src/components/Projects/ProjectCardBadge.vue
  packages/editor-ui/src/components/Projects/ProjectHeader.vue
  packages/editor-ui/src/components/WorkflowCard.vue
  packages/editor-ui/src/components/canvas/Canvas.vue
  packages/editor-ui/src/components/executions/global/GlobalExecutionsList.vue
  packages/editor-ui/src/components/executions/workflow/WorkflowExecutionsList.vue
  packages/editor-ui/src/components/executions/workflow/WorkflowExecutionsSidebar.vue
  packages/editor-ui/src/components/forms/ResourceFiltersDropdown.vue
  packages/editor-ui/src/components/layouts/PageViewLayout.vue
  packages/editor-ui/src/components/layouts/ResourcesListLayout.vue
  packages/editor-ui/src/styles/plugins/_vueflow.scss
  packages/editor-ui/src/views/NodeView.v2.vue
  packages/editor-ui/vite.config.mts
Labels: ui, n8n team

#12471 fix(editor): Hide credential’s modal menu when the credential is managed (no-changelog)
  packages/editor-ui/src/components/CredentialEdit/CredentialEdit.vue
  packages/editor-ui/src/components/CredentialEdit/__tests__/CredentialEdit.test.ts
Labels: ui, n8n team

#12384 fix(Execute Workflow Node): Fallback to Passthrough explicitly to avoid exception (no-changelog)
  packages/nodes-base/utils/workflowInputsResourceMapping/GenericFunctions.ts
Labels: node/improvement, n8n team

#12446 fix(editor): Never show Pinned Data Callout for Input Panel
  packages/editor-ui/src/components/RunData.test.ts
  packages/editor-ui/src/components/RunData.vue
  packages/editor-ui/src/components/__snapshots__/InputPanel.test.ts.snap
Labels: ui, n8n team

#12348 feat(core): Use node IDs instead of names for data mocking during test runs (no-changelog)
  packages/cli/src/databases/entities/test-definition.ee.ts
  packages/cli/src/evaluation.ee/test-definition.schema.ts
  packages/cli/src/evaluation.ee/test-definition.service.ee.ts
  packages/cli/src/evaluation.ee/test-runner/__tests__/create-pin-data.ee.test.ts
  packages/cli/src/evaluation.ee/test-runner/__tests__/mock-data/workflow.under-test-renamed-nodes.json
  packages/cli/src/evaluation.ee/test-runner/__tests__/test-runner.service.ee.test.ts
  packages/cli/src/evaluation.ee/test-runner/test-runner.service.ee.ts
  packages/cli/src/evaluation.ee/test-runner/utils.ee.ts
  packages/cli/test/integration/evaluation/test-definitions.api.test.ts
Labels: core, n8n team

#12376 fix(editor): First project button tweaks border and copy
  packages/editor-ui/src/components/Projects/ProjectNavigation.vue
  packages/editor-ui/src/plugins/i18n/locales/en.json
Labels: ui, n8n team

#12445 fix(n8n Form Node): Remove dependence on static data from the form completion page (no-changelog)
  packages/nodes-base/nodes/Form/Form.node.ts
  packages/nodes-base/nodes/Form/interfaces.ts
  packages/nodes-base/nodes/Form/test/Form.node.test.ts
Labels: n8n team, node/issue

#12447 fix(core): Return unredacted credentials from `GET credentials/:id`
  packages/cli/src/credentials/credentials.service.ee.ts
  packages/cli/src/credentials/credentials.service.ts
  packages/cli/test/integration/credentials/credentials.api.ee.test.ts
  packages/cli/test/integration/credentials/credentials.api.test.ts
Labels: core, n8n team

#12258 feat(editor): Add workflow evaluation run views (no-changelog)
  packages/cli/src/evaluation.ee/test-runner/test-runner.service.ee.ts
  packages/design-system/src/components/N8nSelect/Select.vue
  packages/editor-ui/src/api/testDefinition.ee.ts
  packages/editor-ui/src/components/MainHeader/MainHeader.vue
  packages/editor-ui/src/components/TagsDropdown.vue
  packages/editor-ui/src/components/TestDefinition/EditDefinition/EvaluationHeader.vue
  packages/editor-ui/src/components/TestDefinition/EditDefinition/EvaluationStep.vue
  packages/editor-ui/src/components/TestDefinition/EditDefinition/MetricsInput.vue
  packages/editor-ui/src/components/TestDefinition/EditDefinition/NodesPinning.vue
  packages/editor-ui/src/components/TestDefinition/EditDefinition/TagsInput.vue
  packages/editor-ui/src/components/TestDefinition/ListDefinition/TestItem.vue
  packages/editor-ui/src/components/TestDefinition/ListDefinition/TestsList.vue
  packages/editor-ui/src/components/TestDefinition/ListRuns/MetricsChart.vue
  packages/editor-ui/src/components/TestDefinition/ListRuns/TestRunsTable.vue
  packages/editor-ui/src/components/TestDefinition/composables/useMetricsChart.ts
  packages/editor-ui/src/components/TestDefinition/composables/useTestDefinitionForm.ts
  packages/editor-ui/src/components/TestDefinition/shared/TableCell.vue
  packages/editor-ui/src/components/TestDefinition/shared/TestDefinitionTable.vue
  packages/editor-ui/src/components/TestDefinition/tests/MetricsInput.test.ts
  packages/editor-ui/src/components/TestDefinition/tests/useMetricsChart.test.ts
  packages/editor-ui/src/components/TestDefinition/tests/useTestDefinitionForm.test.ts
  packages/editor-ui/src/components/TestDefinition/types.ts
  packages/editor-ui/src/components/WorkflowTagsDropdown.vue
  packages/editor-ui/src/components/canvas/Canvas.vue
  packages/editor-ui/src/components/canvas/elements/nodes/CanvasNode.vue
  packages/editor-ui/src/constants.ts
  packages/editor-ui/src/plugins/i18n/locales/en.json
  packages/editor-ui/src/router.ts
  packages/editor-ui/src/stores/executions.store.ts
  packages/editor-ui/src/stores/testDefinition.store.ee.test.ts
  packages/editor-ui/src/stores/testDefinition.store.ee.ts
  packages/editor-ui/src/stores/ui.store.ts
  packages/editor-ui/src/stores/ui.utils.ts
  packages/editor-ui/src/types/canvas.ts
  packages/editor-ui/src/views/TestDefinition/TestDefinitionEditView.vue
  packages/editor-ui/src/views/TestDefinition/TestDefinitionListView.vue
  packages/editor-ui/src/views/TestDefinition/TestDefinitionRunDetailView.vue
  packages/editor-ui/src/views/TestDefinition/TestDefinitionRunsListView.vue
  packages/editor-ui/src/views/TestDefinition/tests/TestDefinitionEditView.test.ts
  packages/editor-ui/src/views/TestDefinition/tests/TestDefinitionListView.test.ts
  packages/editor-ui/src/views/TestDefinition/tests/TestDefinitionRunDetailView.test.ts
Labels: core, ui, n8n team

#12481 fix(editor): Free AI credits experiment evaluation (no-changelog)
  packages/editor-ui/src/components/FreeAiCreditsCallout.test.ts
  packages/editor-ui/src/components/FreeAiCreditsCallout.vue
Labels: ui, n8n team

#12459 feat: Add telemetry events for free AI credits feature (no-changelog)
  packages/cli/src/events/__tests__/telemetry-event-relay.test.ts
  packages/cli/src/events/relays/telemetry.event-relay.ts
  packages/editor-ui/src/components/FreeAiCreditsCallout.test.ts
  packages/editor-ui/src/components/FreeAiCreditsCallout.vue
  packages/workflow/src/TelemetryHelpers.ts
  packages/workflow/test/TelemetryHelpers.test.ts
Labels: core, ui, n8n team

#12300 feat(Google Vertex Chat Model Node): Add an option to specify GCP region
  cypress/pages/modals/credentials-modal.ts
  packages/@n8n/nodes-langchain/nodes/llms/LmChatGoogleVertex/LmChatGoogleVertex.node.ts
  packages/nodes-base/credentials/GoogleApi.credentials.ts
Labels: node/improvement, n8n team

#12488 test: Update demo e2e tests for new canvas (no-changelog)
  cypress/composables/workflow.ts
  packages/editor-ui/src/components/canvas/elements/nodes/CanvasNode.vue
Labels: ui, n8n team

#12490 fix(editor): Fix workflow name input size on desktop (no-changelog)
  packages/editor-ui/src/components/MainHeader/WorkflowDetails.vue
Labels: ui, n8n team

#12479 fix(editor): Update easy AI workflow setup instructions when user is in free AI credits experiment (no-changelog)
  cypress/e2e/27-cloud.cy.ts
  packages/editor-ui/src/composables/usePushConnection.ts
  packages/editor-ui/src/constants.workflows.ts
  packages/editor-ui/src/utils/easyAiWorkflowUtils.test.ts
  packages/editor-ui/src/utils/easyAiWorkflowUtils.ts
  packages/editor-ui/src/views/NodeView.v2.vue
  packages/editor-ui/src/views/NodeView.vue
  packages/editor-ui/src/views/WorkflowsView.vue
Labels: ui, n8n team

#12493 feat: Add more telemetry to free AI credits feature (no-changelog)
  packages/cli/src/constants.ts
  packages/cli/src/controllers/ai.controller.ts
  packages/cli/src/events/__tests__/telemetry-event-relay.test.ts
  packages/cli/src/events/relays/telemetry.event-relay.ts
  packages/cli/test/integration/ai/ai.api.test.ts
  packages/editor-ui/src/components/FreeAiCreditsCallout.vue
  packages/workflow/src/Constants.ts
  packages/workflow/src/TelemetryHelpers.ts
  packages/workflow/test/TelemetryHelpers.test.ts
Labels: core, ui, n8n team

#12486 fix(core): Use rate limiter for task runner endpoints
  packages/cli/src/task-runners/task-runner-server.ts
  packages/cli/test/integration/runners/task-runner-server.test.ts
Labels: core, n8n team

#12489 test(editor): Add deprecation warnings for e2e page classes (no-changelog)
  cypress/composables/workflow.ts
  cypress/e2e/27-cloud.cy.ts
  cypress/e2e/30-editor-after-route-changes.cy.ts
  cypress/e2e/35-admin-user-smoke-test.cy.ts
  cypress/pages/bannerStack.ts
  cypress/pages/base.ts
  cypress/pages/credentials.ts
  cypress/pages/features/ai-assistant.ts
  cypress/pages/features/node-creator.ts
  cypress/pages/index.ts
  cypress/pages/mfa-login.ts
  cypress/pages/modals/change-password-modal.ts
  cypress/pages/modals/credentials-modal.ts
  cypress/pages/modals/message-box.ts
  cypress/pages/modals/mfa-setup-modal.ts
  cypress/pages/modals/workflow-sharing-modal.ts
  cypress/pages/ndv.ts
  cypress/pages/settings-log-streaming.ts
  cypress/pages/settings-personal.ts
  cypress/pages/settings-usage.ts
  cypress/pages/settings-users.ts
  cypress/pages/settings.ts
  cypress/pages/sidebar/main-sidebar.ts
  cypress/pages/sidebar/settings-sidebar.ts
  cypress/pages/signin.ts
  cypress/pages/templates.ts
  cypress/pages/variables.ts
  cypress/pages/workerView.ts
  cypress/pages/workflow-executions-tab.ts
  cypress/pages/workflow-history.ts
  cypress/pages/workflow.ts
  cypress/pages/workflows.ts
Labels: n8n team

#12448 fix(editor): Render empty string instead of [empty]
  packages/editor-ui/src/composables/useExpressionEditor.test.ts
  packages/editor-ui/src/composables/useExpressionEditor.ts
Labels: ui, n8n team

#12452 fix(Postgres Node): Allow passing in arrays to JSON columns for insert
  packages/nodes-base/nodes/Postgres/test/v2/operations.test.ts
  packages/nodes-base/nodes/Postgres/test/v2/utils.test.ts
  packages/nodes-base/nodes/Postgres/v2/actions/database/insert.operation.ts
  packages/nodes-base/nodes/Postgres/v2/actions/router.ts
  packages/nodes-base/nodes/Postgres/v2/helpers/utils.ts
Labels: node/improvement, n8n team

#10820 feat(HighLevel Node): Add support for calendar items
  packages/nodes-base/credentials/HighLevelOAuth2Api.credentials.ts
  packages/nodes-base/nodes/HighLevel/v2/GenericFunctions.ts
  packages/nodes-base/nodes/HighLevel/v2/HighLevelV2.node.ts
  packages/nodes-base/nodes/HighLevel/v2/description/CalendarDescription.ts
  packages/nodes-base/nodes/HighLevel/v2/description/ContactDescription.ts
  packages/nodes-base/nodes/HighLevel/v2/test/AddCustomFieldsPreSendAction.test.ts
  packages/nodes-base/nodes/HighLevel/v2/test/AddLocationIdPreSendAction.test.ts
  packages/nodes-base/nodes/HighLevel/v2/test/AddNotePostReceiveAction.test.ts
  packages/nodes-base/nodes/HighLevel/v2/test/ContactIdentifierPreSendAction.test.ts
  packages/nodes-base/nodes/HighLevel/v2/test/DateTimeToEpochPreSendAction.test.ts
  packages/nodes-base/nodes/HighLevel/v2/test/DateToIsoSuperssMillis.test.ts
  packages/nodes-base/nodes/HighLevel/v2/test/DueDatePreSendAction.test.ts
  packages/nodes-base/nodes/HighLevel/v2/test/GetContacts.test.ts
  packages/nodes-base/nodes/HighLevel/v2/test/GetPipelineStages.test.ts
  packages/nodes-base/nodes/HighLevel/v2/test/GetPipelines.test.ts
  packages/nodes-base/nodes/HighLevel/v2/test/GetUsers.test.ts
  packages/nodes-base/nodes/HighLevel/v2/test/HighLevelApiPagination.test.ts
  packages/nodes-base/nodes/HighLevel/v2/test/HighLevelApiRequest.test.ts
  packages/nodes-base/nodes/HighLevel/v2/test/IsEmailValid.test.ts
  packages/nodes-base/nodes/HighLevel/v2/test/IsPhoneValid.test.ts
  packages/nodes-base/nodes/HighLevel/v2/test/SplitTagsPreSendAction.test.ts
  packages/nodes-base/nodes/HighLevel/v2/test/TaskPostReceiceAction.test.ts
  packages/nodes-base/nodes/HighLevel/v2/test/TaskUpdatePreSendAction.test.ts
  packages/nodes-base/nodes/HighLevel/v2/test/ValidEmailAndPhonePreSendAction.test.ts
Labels: node/improvement, community, in linear

#12474 feat: Update copy for Vector Store Tool modes (no-changelog)
  cypress/e2e/4-node-creator.cy.ts
  packages/@n8n/nodes-langchain/nodes/vector_store/shared/__snapshots__/createVectorStoreNode.test.ts.snap
  packages/@n8n/nodes-langchain/nodes/vector_store/shared/createVectorStoreNode.ts
Labels: n8n team

#12496 fix(core): Increase default concurrency and timeout in task runners
  packages/@n8n/config/src/configs/runners.config.ts
  packages/@n8n/config/test/config.test.ts
Labels: n8n team

#12494 chore(core): Mark `item.index` as deprecated
  packages/workflow/src/Interfaces.ts
Labels: core, n8n team

#12285 feat(editor): New Code editor based on the TypeScript language service
  cypress/e2e/6-code-node.cy.ts
  packages/design-system/src/css/_primitives.scss
  packages/design-system/src/css/_tokens.dark.scss
  packages/design-system/src/css/_tokens.scss
  packages/editor-ui/package.json
  packages/editor-ui/src/components/CodeNodeEditor/CodeNodeEditor.vue
  packages/editor-ui/src/components/CodeNodeEditor/baseExtensions.ts
  packages/editor-ui/src/components/CodeNodeEditor/constants.ts
  packages/editor-ui/src/components/CodeNodeEditor/linter.ts
  packages/editor-ui/src/components/CodeNodeEditor/theme.ts
  packages/editor-ui/src/components/ExpressionEditModal.vue
  packages/editor-ui/src/components/ExpressionEditorModal/ExpressionEditorModalInput.vue
  packages/editor-ui/src/components/HtmlEditor/HtmlEditor.vue
  packages/editor-ui/src/components/InlineExpressionEditor/ExpressionOutput.vue
  packages/editor-ui/src/components/InlineExpressionEditor/InlineExpressionEditorInput.vue
  packages/editor-ui/src/components/JsEditor/JsEditor.vue
  packages/editor-ui/src/components/JsonEditor/JsonEditor.vue
  packages/editor-ui/src/components/ParameterInput.vue
  packages/editor-ui/src/components/SqlEditor/SqlEditor.vue
  packages/editor-ui/src/composables/useCodeEditor.ts
  packages/editor-ui/src/composables/useExpressionEditor.test.ts
  packages/editor-ui/src/composables/useExpressionEditor.ts
  packages/editor-ui/src/composables/usePushConnection.ts
  packages/editor-ui/src/event-bus/code-node-editor.ts
  packages/editor-ui/src/plugins/codemirror/completions/utils.ts
  packages/editor-ui/src/plugins/codemirror/format.ts
  packages/editor-ui/src/plugins/codemirror/keymap.ts
  packages/editor-ui/src/plugins/codemirror/multiCursor.ts
  packages/editor-ui/src/plugins/codemirror/typescript/client/completions.ts
  packages/editor-ui/src/plugins/codemirror/typescript/client/facet.ts
  packages/editor-ui/src/plugins/codemirror/typescript/client/hoverTooltip.ts
  packages/editor-ui/src/plugins/codemirror/typescript/client/linter.ts
  packages/editor-ui/src/plugins/codemirror/typescript/client/snippets.ts
  packages/editor-ui/src/plugins/codemirror/typescript/client/useTypescript.ts
  packages/editor-ui/src/plugins/codemirror/typescript/types.ts
  packages/editor-ui/src/plugins/codemirror/typescript/worker/cache.ts
  packages/editor-ui/src/plugins/codemirror/typescript/worker/completions.ts
  packages/editor-ui/src/plugins/codemirror/typescript/worker/constants.ts
  packages/editor-ui/src/plugins/codemirror/typescript/worker/dynamicTypes.test.ts
  packages/editor-ui/src/plugins/codemirror/typescript/worker/dynamicTypes.ts
  packages/editor-ui/src/plugins/codemirror/typescript/worker/env.ts
  packages/editor-ui/src/plugins/codemirror/typescript/worker/hoverTooltip.ts
  packages/editor-ui/src/plugins/codemirror/typescript/worker/linter.ts
  packages/editor-ui/src/plugins/codemirror/typescript/worker/npmTypesLoader.ts
  packages/editor-ui/src/plugins/codemirror/typescript/worker/type-declarations/globals.d.ts
  packages/editor-ui/src/plugins/codemirror/typescript/worker/type-declarations/n8n-once-for-all-items.d.ts
  packages/editor-ui/src/plugins/codemirror/typescript/worker/type-declarations/n8n-once-for-each-item.d.ts
  packages/editor-ui/src/plugins/codemirror/typescript/worker/type-declarations/n8n.d.ts
  packages/editor-ui/src/plugins/codemirror/typescript/worker/typescript.worker.ts
  packages/editor-ui/src/plugins/codemirror/typescript/worker/typescriptAst.ts
  packages/editor-ui/src/plugins/codemirror/typescript/worker/utils.ts
  packages/editor-ui/src/shims-modules.d.ts
  packages/editor-ui/src/shims.d.ts
  packages/editor-ui/src/styles/plugins/_codemirror.scss
  packages/editor-ui/src/utils/forceParse.ts
  packages/editor-ui/tsconfig.json
  packages/editor-ui/vite.config.mts
  pnpm-lock.yaml
Labels: ui, n8n team, tests-needed

#11779 feat(Microsoft Entra ID Node): New node
  packages/nodes-base/credentials/MicrosoftEntraOAuth2Api.credentials.ts
  packages/nodes-base/nodes/Microsoft/Entra/GenericFunctions.ts
  packages/nodes-base/nodes/Microsoft/Entra/MicrosoftEntra.node.json
  packages/nodes-base/nodes/Microsoft/Entra/MicrosoftEntra.node.ts
  packages/nodes-base/nodes/Microsoft/Entra/descriptions/GroupDescription.ts
  packages/nodes-base/nodes/Microsoft/Entra/descriptions/UserDescription.ts
  packages/nodes-base/nodes/Microsoft/Entra/descriptions/index.ts
  packages/nodes-base/nodes/Microsoft/Entra/microsoftEntra.dark.svg
  packages/nodes-base/nodes/Microsoft/Entra/microsoftEntra.svg
  packages/nodes-base/nodes/Microsoft/Entra/test/GroupDescription.test.ts
  packages/nodes-base/nodes/Microsoft/Entra/test/MicrosoftEntra.node.test.ts
  packages/nodes-base/nodes/Microsoft/Entra/test/UserDescription.test.ts
  packages/nodes-base/nodes/Microsoft/Entra/test/mocks.ts
  packages/nodes-base/package.json
  packages/nodes-base/test/nodes/FakeCredentialsMap.ts
  packages/workflow/src/Interfaces.ts
Labels: node/improvement, node/new, core, community, in linear

#12245 test(editor): Update workflow actions tests for the new canvas (no-changelog)
  cypress/e2e/7-workflow-actions.cy.ts
  packages/editor-ui/src/views/NodeView.v2.vue
Labels: ui, n8n team

#12317 fix(editor): Improve configurable nodes design on new canvas
  packages/editor-ui/src/components/canvas/elements/nodes/CanvasNode.test.ts
  packages/editor-ui/src/components/canvas/elements/nodes/CanvasNode.vue
  packages/editor-ui/src/components/canvas/elements/nodes/render-types/CanvasNodeDefault.vue
  packages/editor-ui/src/utils/canvasUtilsV2.test.ts
  packages/editor-ui/src/utils/canvasUtilsV2.ts
Labels: ui, n8n team

#11065 chore: Fix dev setup on windows machines (no-changelog)
  scripts/prepare.mjs
Labels: n8n team

#12501 ci: Skip workflow tests on community PRs
  .github/workflows/test-workflows.yml
Labels: community

#12503 fix(core): Align concurrency and timeout defaults between instance and runner
  packages/@n8n/config/src/configs/runners.config.ts
  packages/@n8n/task-runner/src/config/base-runner-config.ts
Labels: n8n team

#12491 fix(core): Fix manually running a pinned trigger with offloading enabled
  packages/cli/src/workflows/workflow-execution.service.ts
Labels: core, n8n team

#12509 fix(editor): Fix NDV resize handle and scrollbar overlapping
  packages/design-system/src/components/N8nResizeWrapper/ResizeWrapper.vue
  packages/editor-ui/src/components/NDVDraggablePanels.vue
Labels: ui, n8n team

#12507 fix(editor): Fix workflow initilisation for test definition routes & add unit tests
  packages/editor-ui/src/api/testDefinition.ee.ts
  packages/editor-ui/src/components/TestDefinition/EditDefinition/EvaluationStep.vue
  packages/editor-ui/src/components/TestDefinition/EditDefinition/NodesPinning.vue
  packages/editor-ui/src/components/TestDefinition/EditDefinition/tests/NodesPinning.test.ts
  packages/editor-ui/src/components/TestDefinition/types.ts
  packages/editor-ui/src/plugins/i18n/locales/en.json
  packages/editor-ui/src/router.ts
  packages/editor-ui/src/views/TestDefinition/TestDefinitionEditView.vue
  packages/editor-ui/src/views/TestDefinition/TestDefinitionRootView.vue
  packages/editor-ui/src/views/TestDefinition/TestDefinitionRunDetailView.vue
  packages/editor-ui/src/views/TestDefinition/tests/TestDefinitionRootView.test.ts
Labels: ui, n8n team

#12505 feat(editor): Persist sidebar collapsed status preference
  packages/editor-ui/src/components/MainSidebar.vue
  packages/editor-ui/src/stores/ui.store.ts
Labels: ui, n8n team

#12510 feat(editor): Show warning when user activates workflow with free AI credits credential (no-changelog)
  packages/editor-ui/src/components/WorkflowActivator.test.ts
  packages/editor-ui/src/components/WorkflowActivator.vue
  packages/editor-ui/src/plugins/i18n/locales/en.json
Labels: ui, n8n team

#12495 fix(core): Fix Sentry error reporting on task runners
  packages/@n8n/config/src/configs/sentry.config.ts
  packages/@n8n/config/test/config.test.ts
  packages/@n8n/task-runner/src/config/sentry-config.ts
  packages/@n8n/task-runner/src/js-task-runner/__tests__/js-task-runner.test.ts
  packages/@n8n/task-runner/src/start.ts
  packages/cli/src/commands/base-command.ts
  packages/core/src/error-reporter.ts
Labels: core, n8n team

#12460 test: Finish Sub-Workflow Inputs Testing (no-changelog)
  cypress/composables/ndv.ts
  cypress/composables/workflowsPage.ts
  cypress/e2e/30-langchain.cy.ts
  cypress/e2e/45-workflow-selector-parameter.cy.ts
  cypress/e2e/48-subworkflow-inputs.cy.ts
Labels: n8n team

#12525 refactor(core): Report malformed execution data
  packages/core/src/WorkflowExecute.ts
Labels: core, n8n team

#12518 fix(editor): Condition to show the warning after workflow activation for free AI credits (no-changelog)
  packages/editor-ui/src/components/WorkflowActivator.test.ts
  packages/editor-ui/src/components/WorkflowActivator.vue
Labels: ui, n8n team

#12522 fix(core): Disallow code generation in task runner
  docker/images/n8n/n8n-task-runners.json
  packages/@n8n/task-runner/src/js-task-runner/__tests__/js-task-runner.test.ts
  packages/@n8n/task-runner/src/js-task-runner/js-task-runner.ts
  packages/cli/src/task-runners/__tests__/task-runner-process.test.ts
  packages/cli/src/task-runners/task-runner-process.ts
Labels: core, n8n team

#12526 fix(editor): Swap Activate/Deactivate texts in FloatingToolbar
  packages/editor-ui/src/components/canvas/elements/nodes/CanvasNodeToolbar.vue
Labels: ui, n8n team

#12528 refactor(core): Port over project request payloads to DTOs
  packages/@n8n/api-types/src/dto/index.ts
  packages/@n8n/api-types/src/dto/project/__tests__/create-project.dto.test.ts
  packages/@n8n/api-types/src/dto/project/__tests__/update-project.dto.test.ts
  packages/@n8n/api-types/src/dto/project/create-project.dto.ts
  packages/@n8n/api-types/src/dto/project/delete-project.dto.ts
  packages/@n8n/api-types/src/dto/project/update-project.dto.ts
  packages/@n8n/api-types/src/index.ts
  packages/@n8n/api-types/src/schemas/__tests__/project.schema.test.ts
  packages/@n8n/api-types/src/schemas/project.schema.ts
  packages/cli/src/__tests__/project.test-data.ts
  packages/cli/src/controllers/project.controller.ts
  packages/cli/src/databases/entities/project-relation.ts
  packages/cli/src/databases/entities/project.ts
  packages/cli/src/databases/migrations/common/1714133768519-CreateProject.ts
  packages/cli/src/databases/repositories/project-relation.repository.ts
  packages/cli/src/databases/repositories/shared-credentials.repository.ts
  packages/cli/src/events/maps/relay.event-map.ts
  packages/cli/src/public-api/v1/handlers/projects/projects.handler.ts
  packages/cli/src/requests.ts
  packages/cli/src/services/project.service.ee.ts
  packages/cli/src/services/role.service.ts
  packages/cli/src/workflows/workflow-sharing.service.ts
  packages/cli/test/integration/credentials/credentials.api.ee.test.ts
  packages/cli/test/integration/project.api.test.ts
  packages/cli/test/integration/public-api/workflows.test.ts
  packages/cli/test/integration/role.api.test.ts
  packages/cli/test/integration/services/project.service.test.ts
  packages/cli/test/integration/shared/db/projects.ts
  packages/cli/test/integration/workflows/workflow-sharing.service.test.ts
  packages/cli/test/integration/workflows/workflows.controller.ee.test.ts
  packages/editor-ui/src/api/projects.api.ts
  packages/editor-ui/src/stores/projects.store.ts
  packages/editor-ui/src/types/projects.types.ts
  packages/editor-ui/src/views/ProjectSettings.vue
Labels: core, n8n team

#12534 fix(core): AugmentObject should check for own propeties correctly
  packages/workflow/src/AugmentObject.ts
  packages/workflow/test/AugmentObject.test.ts
Labels: core, n8n team

#12532 fix(editor): Fix parameter input validation
  packages/editor-ui/src/components/ParameterInput.vue
  packages/editor-ui/src/components/ParameterInputWrapper.vue
Labels: release/backport, tests-needed

#12444 fix(core): Fix orchestration flow with expired license
  packages/cli/src/__tests__/license.test.ts
  packages/cli/src/commands/start.ts
  packages/cli/src/license.ts
Labels: core, n8n team

#12470 refactor(core): Use DTOs for source control push/pull requests
  packages/@n8n/api-types/src/dto/index.ts
  packages/@n8n/api-types/src/dto/source-control/__tests__/pull-work-folder-request.dto.test.ts
  packages/@n8n/api-types/src/dto/source-control/__tests__/push-work-folder-request.dto.test.ts
  packages/@n8n/api-types/src/dto/source-control/pull-work-folder-request.dto.ts
  packages/@n8n/api-types/src/dto/source-control/push-work-folder-request.dto.ts
  packages/@n8n/api-types/src/index.ts
  packages/@n8n/api-types/src/schemas/source-controlled-file.schema.ts
  packages/cli/src/environments.ee/source-control/__tests__/source-control-export.service.test.ts
  packages/cli/src/environments.ee/source-control/__tests__/source-control-helper.ee.test.ts
  packages/cli/src/environments.ee/source-control/source-control-export.service.ee.ts
  packages/cli/src/environments.ee/source-control/source-control-helper.ee.ts
  packages/cli/src/environments.ee/source-control/source-control-import.service.ee.ts
  packages/cli/src/environments.ee/source-control/source-control.controller.ee.ts
  packages/cli/src/environments.ee/source-control/source-control.service.ee.ts
  packages/cli/src/environments.ee/source-control/types/requests.ts
  packages/cli/src/environments.ee/source-control/types/source-control-pull-work-folder.ts
  packages/cli/src/environments.ee/source-control/types/source-control-push-work-folder.ts
  packages/cli/src/environments.ee/source-control/types/source-controlled-file.ts
  packages/cli/src/public-api/types.ts
  packages/cli/src/public-api/v1/handlers/source-control/source-control.handler.ts
  packages/cli/test/integration/environments/source-control-import.service.test.ts
  packages/cli/test/integration/environments/source-control.test.ts
  packages/editor-ui/src/api/sourceControl.ts
  packages/editor-ui/src/components/MainSidebarSourceControl.vue
  packages/editor-ui/src/components/SourceControlPullModal.ee.vue
  packages/editor-ui/src/components/SourceControlPushModal.ee.test.ts
  packages/editor-ui/src/components/SourceControlPushModal.ee.vue
  packages/editor-ui/src/stores/sourceControl.store.ts
  packages/editor-ui/src/types/sourceControl.types.ts
Labels: core, ui, n8n team

#12080 fix(Spotify Node): Fix issue with null values breaking the response
  packages/nodes-base/nodes/Spotify/GenericFunctions.ts
  packages/nodes-base/nodes/Spotify/Spotify.node.ts
  packages/nodes-base/nodes/Spotify/__tests__/GenericFunctions.test.ts
  packages/nodes-base/nodes/Spotify/__tests__/workflow/Spotify.workflow.json
  packages/nodes-base/nodes/Spotify/__tests__/workflow/apiResponses.ts
  packages/nodes-base/nodes/Spotify/__tests__/workflow/workflow.test.ts
  packages/nodes-base/test/nodes/FakeCredentialsMap.ts
Labels: node/improvement, n8n team

#12539 ci: Fix frontend dev setup
  packages/@n8n/api-types/src/index.ts
Labels: n8n team

#12530 test: Update node creator e2e tests to work with new canvas (no-changelog)
  cypress/composables/workflow.ts
  cypress/e2e/4-node-creator.cy.ts
  cypress/pages/workflow.ts
  packages/editor-ui/src/components/canvas/elements/edges/CanvasEdge.test.ts
  packages/editor-ui/src/components/canvas/elements/edges/CanvasEdge.vue
  packages/editor-ui/src/components/canvas/elements/handles/render-types/CanvasHandleMainOutput.test.ts
  packages/editor-ui/src/components/canvas/elements/handles/render-types/CanvasHandleMainOutput.vue
  packages/editor-ui/src/components/canvas/elements/handles/render-types/parts/CanvasHandlePlus.vue
  packages/editor-ui/src/components/canvas/elements/handles/render-types/parts/__snapshots__/CanvasHandlePlus.test.ts.snap
  packages/editor-ui/src/components/canvas/elements/nodes/CanvasNode.vue
Labels: ui, n8n team

#12433 fix(core): Only show personal credentials in the personal space
  packages/cli/src/credentials/credentials.service.ts
  packages/cli/test/integration/credentials/credentials.api.test.ts
Labels: core, n8n team

#12380 refactor(core): Update tag endpoints to use DTOs and injectable config
  packages/@n8n/api-types/src/dto/index.ts
  packages/@n8n/api-types/src/dto/tag/__tests__/create-or-update-tag-request.dto.test.ts
  packages/@n8n/api-types/src/dto/tag/__tests__/retrieve-tag-query.dto.test.ts
  packages/@n8n/api-types/src/dto/tag/create-or-update-tag-request.dto.ts
  packages/@n8n/api-types/src/dto/tag/retrieve-tag-query.dto.ts
  packages/@n8n/config/src/configs/tags.config.ts
  packages/@n8n/config/src/index.ts
  packages/@n8n/config/test/config.test.ts
  packages/cli/src/config/schema.ts
  packages/cli/src/controllers/tags.controller.ts
  packages/cli/src/databases/repositories/workflow.repository.ts
  packages/cli/src/public-api/v1/handlers/workflows/workflows.handler.ts
  packages/cli/src/public-api/v1/handlers/workflows/workflows.service.ts
  packages/cli/src/requests.ts
  packages/cli/src/server.ts
  packages/cli/src/services/frontend.service.ts
  packages/cli/src/workflow-execute-additional-data.ts
  packages/cli/src/workflows/workflow.service.ts
  packages/cli/src/workflows/workflows.controller.ts
  packages/cli/test/integration/public-api/workflows.test.ts
  packages/cli/test/integration/security-audit/instance-risk-reporter.test.ts
  packages/cli/test/integration/tags.api.test.ts
  packages/cli/test/integration/workflows/workflow.service.test.ts
  packages/cli/test/setup-test-folder.ts
  packages/editor-ui/src/api/tags.ts
  packages/editor-ui/src/stores/tags.store.ts
Labels: core, ui, n8n team

#12497 feat(editor): Make node credential select searchable
  cypress/e2e/16-webhook-node.cy.ts
  cypress/e2e/17-sharing.cy.ts
  cypress/e2e/2-credentials.cy.ts
  cypress/e2e/21-community-nodes.cy.ts
  cypress/e2e/39-projects.cy.ts
  cypress/e2e/45-ai-assistant.cy.ts
  packages/design-system/src/components/N8nSelect/Select.vue
  packages/design-system/src/css/_tokens.scss
  packages/editor-ui/src/components/NodeCredentials.test.ts
  packages/editor-ui/src/components/NodeCredentials.vue
  packages/editor-ui/src/components/ParameterIssues.vue
  packages/editor-ui/src/plugins/i18n/locales/en.json
Labels: ui, n8n team

#10715 fix(Google Calendar Node): Updates and fixes
  packages/nodes-base/nodes/Google/Calendar/CalendarDescription.ts
  packages/nodes-base/nodes/Google/Calendar/EventDescription.ts
  packages/nodes-base/nodes/Google/Calendar/EventInterface.ts
  packages/nodes-base/nodes/Google/Calendar/GenericFunctions.ts
  packages/nodes-base/nodes/Google/Calendar/GoogleCalendar.node.json
  packages/nodes-base/nodes/Google/Calendar/GoogleCalendar.node.ts
  packages/nodes-base/nodes/Google/Calendar/test/GeneircFunctions.test.ts
  packages/nodes-base/nodes/Google/Calendar/test/addNextOccurrence.test.ts
  packages/nodes-base/nodes/Google/Calendar/test/node/event.getAll.test.ts
  packages/nodes-base/nodes/Google/Calendar/test/node/event.update.test.ts
  packages/nodes-base/test/utils/utilities.test.ts
  packages/nodes-base/utils/utilities.ts
  packages/workflow/src/NodeHelpers.ts
  packages/workflow/test/NodeHelpers.test.ts
Labels: n8n team, node/issue

#12547 refactor(core): Patch Bull to include stack trace on job fail
  package.json
  patches/bull@4.12.1.patch
  pnpm-lock.yaml
Labels: n8n team

#12548 refactor(core): Validate job data on worker
  packages/cli/src/scaling/scaling.service.ts
Labels: core, n8n team

#12549 fix(editor): Override selected nodes on single click without Meta/Ctrl key
  packages/editor-ui/src/components/canvas/Canvas.vue
Labels: ui, n8n team

#12537 fix(core): Filter out task runner errors originating from user code from sentry (no-changelog)
  packages/@n8n/task-runner/src/__tests__/task-runner-sentry.test.ts
  packages/@n8n/task-runner/src/start.ts
  packages/@n8n/task-runner/src/task-runner-sentry.ts
  packages/core/src/error-reporter.ts
  packages/core/test/error-reporter.test.ts
Labels: core, n8n team

#12544 fix(core): Fix node exclusion on the frontend types
  packages/core/src/DirectoryLoader.ts
  packages/core/test/DirectoryLoader.test.ts
Labels: core, n8n team

#12382 fix(core): Validate values which are intentionally 0
  packages/core/src/node-execution-context/utils/__tests__/validateValueAgainstSchema.test.ts
  packages/core/src/node-execution-context/utils/validateValueAgainstSchema.ts
Labels: core, n8n team

#12512 docs: Fix the docs for starting n8n with `--tunnel` option (no-changelog)
  docker/images/n8n/README.md
Labels: n8n team

#12516 ci: Stop publishing custom images to docker hub by default
  .github/workflows/docker-base-image.yml
  .github/workflows/docker-images-benchmark.yml
  .github/workflows/docker-images-custom.yml
  .github/workflows/docker-images-nightly.yml
  .github/workflows/release-publish.yml
  .github/workflows/release-push-to-channel.yml
Labels: n8n team

#12529 fix(editor): Don't show toolsUnused notice if run had errors
  packages/editor-ui/src/components/OutputPanel.vue
Labels: ui, n8n team

#12504 fix(editor): Update filter and feedback for source control
  packages/editor-ui/src/api/credentials.ts
  packages/editor-ui/src/api/sourceControl.ts
  packages/editor-ui/src/components/CredentialCard.vue
  packages/editor-ui/src/components/MainSidebarSourceControl.test.ts
  packages/editor-ui/src/components/MainSidebarSourceControl.vue
  packages/editor-ui/src/components/forms/ResourceFiltersDropdown.vue
  packages/editor-ui/src/components/layouts/ResourcesListLayout.vue
  packages/editor-ui/src/plugins/i18n/locales/en.json
  packages/editor-ui/src/views/CredentialsView.test.ts
  packages/editor-ui/src/views/CredentialsView.vue
Labels: ui, n8n team

#12541 fix(core): Node mocking for evaluation executions (no-changelog)
  packages/cli/src/evaluation.ee/test-runner/__tests__/test-runner.service.ee.test.ts
  packages/cli/src/evaluation.ee/test-runner/test-runner.service.ee.ts
  packages/cli/src/manual-execution.service.ts
  packages/cli/src/webhooks/webhook-helpers.ts
  packages/cli/src/workflow-runner.ts
  packages/editor-ui/src/composables/useCanvasOperations.ts
  packages/editor-ui/src/views/NodeView.v2.vue
Labels: core, ui, n8n team

#12566 fix(editor): Ensure proper "AI Template" URL construction in node creator
  packages/editor-ui/src/components/Node/NodeCreator/viewsData.ts
  packages/editor-ui/src/stores/templates.store.ts
Labels: ui, n8n team

#12581 fix(editor): Update selected node when navigating via flowing nodes
  packages/editor-ui/src/views/NodeView.v2.vue
Labels: ui, n8n team

#12567 fix(editor): Show NDV errors when opening existing nodes with errors
  packages/editor-ui/src/composables/useCanvasOperations.test.ts
  packages/editor-ui/src/composables/useCanvasOperations.ts
Labels: ui, n8n team

#12578 feat(editor): Don't show Sub-Workflow id for RunDataAi 'View Execution' link (no-changelog)
  packages/editor-ui/src/components/RunDataAi/RunDataAiContent.vue
Labels: ui, n8n team

#12585 fix(editor): Make clicking item in RLC work the first time on small screens
  packages/editor-ui/src/components/ResourceLocator/ResourceLocator.vue
  packages/editor-ui/src/components/ResourceLocator/ResourceLocatorDropdown.vue
Labels: ui, n8n team, tests-needed

#12115 feat: Add API endpoint to cancel a test run (no-changelog)
  packages/cli/src/databases/entities/test-run.ee.ts
  packages/cli/src/databases/repositories/test-run.repository.ee.ts
  packages/cli/src/errors/response-errors/not-implemented.error.ts
  packages/cli/src/evaluation.ee/test-definitions.types.ee.ts
  packages/cli/src/evaluation.ee/test-runner/__tests__/test-runner.service.ee.test.ts
  packages/cli/src/evaluation.ee/test-runner/test-runner.service.ee.ts
  packages/cli/src/evaluation.ee/test-runs.controller.ee.ts
  packages/cli/test/integration/evaluation/test-runs.api.test.ts
  packages/editor-ui/src/api/testDefinition.ee.ts
  packages/editor-ui/src/components/TestDefinition/ListDefinition/TestItem.vue
  packages/editor-ui/src/components/TestDefinition/ListRuns/TestRunsTable.vue
  packages/editor-ui/src/components/TestDefinition/shared/TableCell.vue
  packages/editor-ui/src/components/TestDefinition/types.ts
  packages/editor-ui/src/plugins/i18n/locales/en.json
  packages/editor-ui/src/stores/testDefinition.store.ee.ts
  packages/editor-ui/src/views/TestDefinition/TestDefinitionListView.vue
Labels: core, n8n team

#12387 feat(core): Separate concurrency limits for production and evaluation executions (no-changelog)
  packages/cli/src/concurrency/__tests__/concurrency-control.service.test.ts
  packages/cli/src/concurrency/concurrency-control.service.ts
  packages/cli/src/concurrency/concurrency-queue.ts
  packages/cli/src/config/schema.ts
  packages/cli/src/events/__tests__/log-streaming-event-relay.test.ts
  packages/cli/src/events/maps/relay.event-map.ts
  packages/cli/src/events/relays/log-streaming.event-relay.ts
  packages/editor-ui/src/components/executions/ConcurrentExecutionsHeader.vue
  packages/editor-ui/src/components/executions/global/GlobalExecutionsList.vue
  packages/editor-ui/src/components/executions/workflow/WorkflowExecutionsSidebar.vue
  packages/editor-ui/src/plugins/i18n/locales/en.json
Labels: core, ui, n8n team

#12463 refactor(core): Make placeholders in manual executions in workers temporary
  packages/@n8n/api-types/src/push/execution.ts
  packages/cli/src/push/index.ts
  packages/editor-ui/src/components/RunData.vue
  packages/editor-ui/src/composables/usePushConnection.ts
  packages/editor-ui/src/plugins/i18n/locales/en.json
  packages/editor-ui/src/stores/ui.store.ts
  packages/editor-ui/src/utils/executionUtils.ts
Labels: ui, n8n team

#12599 chore(core): Log failed webhook requests with debug (no-changelog)
  packages/cli/src/webhooks/webhook-request-handler.ts
Labels: core, n8n team

#12598 test: Add more tests for expression extensions (no-changelog)
  packages/workflow/test/ExpressionExtensions/ArrayExtensions.test.ts
  packages/workflow/test/ExpressionExtensions/BooleanExtensions.test.ts
  packages/workflow/test/ExpressionExtensions/DateExtensions.test.ts
  packages/workflow/test/ExpressionExtensions/ExpressionExtension.test.ts
  packages/workflow/test/ExpressionExtensions/ObjectExtensions.test.ts
  packages/workflow/test/ExpressionExtensions/StringExtensions.test.ts
  packages/workflow/test/NodeErrors.test.ts
  packages/workflow/test/WorkflowDataProxyEnvProvider.test.ts
Labels: core, n8n team

#12597 fix(editor): Make sure code editors work correctly in fullscreen
  cypress/e2e/5-ndv.cy.ts
  packages/editor-ui/src/components/HtmlEditor/HtmlEditor.vue
  packages/editor-ui/src/components/JsonEditor/JsonEditor.vue
  packages/editor-ui/src/components/ParameterInput.vue
  packages/editor-ui/src/components/SqlEditor/SqlEditor.vue
  packages/editor-ui/src/composables/useExpressionEditor.ts
Labels: ui, n8n team, release/backport

#12588 fix(core): Prevent prototype pollution in task runner
  docker/images/n8n/n8n-task-runners.json
  packages/@n8n/task-runner/src/js-task-runner/__tests__/js-task-runner.test.ts
  packages/@n8n/task-runner/src/js-task-runner/js-task-runner.ts
  packages/cli/src/task-runners/__tests__/task-runner-process.test.ts
  packages/cli/src/task-runners/task-runner-process.ts
Labels: core, n8n team

#12586 feat(editor): Enhance workflow evaluations edit view (no-changelog)
  packages/editor-ui/src/components/TestDefinition/EditDefinition/DescriptionInput.vue
  packages/editor-ui/src/components/TestDefinition/EditDefinition/EvaluationHeader.vue
  packages/editor-ui/src/components/TestDefinition/EditDefinition/EvaluationStep.vue
  packages/editor-ui/src/components/TestDefinition/ListDefinition/EmptyState.vue
  packages/editor-ui/src/components/TestDefinition/ListRuns/MetricsChart.vue
  packages/editor-ui/src/components/TestDefinition/ListRuns/TestRunsTable.vue
  packages/editor-ui/src/components/TestDefinition/composables/useMetricsChart.ts
  packages/editor-ui/src/components/TestDefinition/composables/useTestDefinitionForm.ts
  packages/editor-ui/src/components/TestDefinition/shared/TableCell.vue
  packages/editor-ui/src/components/TestDefinition/shared/TestDefinitionTable.vue
  packages/editor-ui/src/components/TestDefinition/shared/TestTableBase.vue
  packages/editor-ui/src/components/TestDefinition/tests/useTestDefinitionForm.test.ts
  packages/editor-ui/src/components/TestDefinition/types.ts
  packages/editor-ui/src/plugins/i18n/locales/en.json
  packages/editor-ui/src/plugins/icons/index.ts
  packages/editor-ui/src/views/TestDefinition/TestDefinitionEditView.vue
  packages/editor-ui/src/views/TestDefinition/TestDefinitionListView.vue
  packages/editor-ui/src/views/TestDefinition/TestDefinitionRootView.vue
  packages/editor-ui/src/views/TestDefinition/TestDefinitionRunDetailView.vue
  packages/editor-ui/src/views/TestDefinition/TestDefinitionRunsListView.vue
  packages/editor-ui/src/views/TestDefinition/tests/TestDefinitionEditView.test.ts
Labels: ui, n8n team

#12612 fix(editor): Fix `hasTrimmedItem` for multi-output nodes and sub-nodes (no-changelog)
  packages/editor-ui/src/utils/executionUtils.ts
Labels: ui, n8n team

#12514 fix(core): Prefix package name in `supportedNodes` on generated types as well
  packages/cli/src/load-nodes-and-credentials.ts
Labels: core, n8n team

#12610 fix(core): Prevent prototype pollution of internal classes in task runner
  packages/@n8n/task-runner/package.json
  packages/@n8n/task-runner/src/js-task-runner/__tests__/js-task-runner.test.ts
  packages/@n8n/task-runner/src/js-task-runner/js-task-runner.ts
  pnpm-lock.yaml
Labels: n8n team

#12600 fix(core): Improve cyclic dependency check in the DI container
  packages/@n8n/di/jest.config.js
  packages/@n8n/di/src/__tests__/circular-depedency.test.ts
  packages/@n8n/di/src/__tests__/fixtures/ServiceA.ts
  packages/@n8n/di/src/__tests__/fixtures/ServiceB.ts
  packages/@n8n/di/src/di.ts
Labels: n8n team

#12616 fix(editor): Show run workflow button when chat trigger has pinned data
  packages/editor-ui/src/views/NodeView.v2.vue
Labels: ui, n8n team

#12628 fix(editor): Fix execution list hover & selection colour in dark mode
  packages/design-system/src/css/_tokens.dark.scss
  packages/design-system/src/css/_tokens.scss
  packages/editor-ui/src/components/executions/workflow/WorkflowExecutionsCard.vue
Labels: ui, n8n team

#12601 test: Use task runner in benchmarks
  packages/@n8n/benchmark/scripts/n8n-setups/postgres/docker-compose.yml
  packages/@n8n/benchmark/scripts/n8n-setups/scaling-multi-main/docker-compose.yml
  packages/@n8n/benchmark/scripts/n8n-setups/scaling-single-main/docker-compose.yml
  packages/@n8n/benchmark/scripts/n8n-setups/sqlite/docker-compose.yml
Labels: n8n team

#12622 fix(editor): Show connector label above the line when it's straight
  packages/editor-ui/src/components/canvas/elements/edges/CanvasEdge.test.ts
  packages/editor-ui/src/components/canvas/elements/edges/CanvasEdge.vue
  packages/editor-ui/src/components/canvas/elements/edges/utils/getEdgeRenderData.ts
  packages/editor-ui/src/components/canvas/elements/handles/render-types/CanvasHandleMainOutput.vue
Labels: ui, n8n team

#12484 refactor(Postgres Node): Backport connection pooling to postgres v1
  packages/@n8n/nodes-langchain/nodes/memory/MemoryPostgresChat/MemoryPostgresChat.node.ts
  packages/@n8n/nodes-langchain/nodes/vector_store/VectorStorePGVector/VectorStorePGVector.node.ts
  packages/nodes-base/credentials/Postgres.credentials.ts
  packages/nodes-base/nodes/Postgres/PostgresTrigger.functions.ts
  packages/nodes-base/nodes/Postgres/transport/index.ts
  packages/nodes-base/nodes/Postgres/v1/PostgresV1.node.ts
  packages/nodes-base/nodes/Postgres/v2/actions/router.ts
  packages/nodes-base/nodes/Postgres/v2/helpers/interfaces.ts
  packages/nodes-base/nodes/Postgres/v2/methods/credentialTest.ts
  packages/nodes-base/nodes/Postgres/v2/methods/listSearch.ts
  packages/nodes-base/nodes/Postgres/v2/methods/loadOptions.ts
  packages/nodes-base/nodes/Postgres/v2/methods/resourceMapping.ts
Labels: node/improvement, n8n team, release/backport

#12635 fix(Execute Workflow Node): Pass binary data to sub-workflow
  packages/nodes-base/utils/workflowInputsResourceMapping/GenericFunctions.ts
  packages/nodes-base/utils/workflowInputsResourceMapping/__tests__/GenericFunctions.test.ts
Labels: node/improvement, n8n team, release/backport

#12630 fix(editor): Defer crypto.randomUUID call in CodeNodeEditor
  packages/editor-ui/src/components/CodeNodeEditor/CodeNodeEditor.vue
Labels: ui, n8n team, release/backport

#12643 fix(Google Gemini Chat Model Node): Add base URL support for Google Gemini Chat API
  packages/@n8n/nodes-langchain/nodes/llms/LmChatGoogleGemini/LmChatGoogleGemini.node.ts
Labels: n8n team

#11346 fix(GraphQL Node): Change default request format to json instead of graphql
  packages/nodes-base/nodes/GraphQL/GraphQL.node.ts
Labels: node/improvement, n8n team

#12646 chore(editor): Exclude codemirror range errors from Sentry
  packages/editor-ui/src/plugins/sentry.ts
Labels: ui, n8n team

#12637 fix(editor): Fix Code node bug erasing and overwriting code when switching between nodes
  packages/editor-ui/src/__tests__/setup.ts
  packages/editor-ui/src/composables/useCodeEditor.test.ts
  packages/editor-ui/src/composables/useCodeEditor.ts
  packages/editor-ui/src/utils/forceParse.ts
Labels: ui, n8n team, release/backport

#12634 fix(OpenAI Chat Model Node): Fix loading of custom models when using custom credential URL
  packages/@n8n/nodes-langchain/nodes/embeddings/EmbeddingsOpenAI/EmbeddingsOpenAi.node.ts
  packages/@n8n/nodes-langchain/nodes/llms/LMChatOpenAi/LmChatOpenAi.node.ts
  packages/@n8n/nodes-langchain/nodes/llms/LMChatOpenAi/methods/__tests__/loadModels.test.ts
  packages/@n8n/nodes-langchain/nodes/llms/LMChatOpenAi/methods/loadModels.ts
  packages/@n8n/nodes-langchain/nodes/vendors/OpenAi/methods/listSearch.ts
Labels: n8n team

#12650 fix(editor): Update workflow re-initialization to use query parameter
  packages/editor-ui/src/composables/useWorkflowHelpers.ts
  packages/editor-ui/src/views/NodeView.v2.vue
  packages/editor-ui/src/views/NodeView.vue
Labels: ui, n8n team

#12639 fix(Postgres Node): Allow using composite key in upsert queries
  packages/nodes-base/nodes/Postgres/test/v2/operations.test.ts
  packages/nodes-base/nodes/Postgres/v2/actions/database/upsert.operation.ts
Labels: node/improvement, n8n team

#12649 refactor(editor): Adjust empty state for large data when manual executions in workers
  packages/editor-ui/src/components/RunData.vue
  packages/editor-ui/src/plugins/i18n/locales/en.json
Labels: ui, n8n team

#12603 fix(core): Update isDocker check to return true on kubernetes/containerd
  packages/core/src/InstanceSettings.ts
  packages/core/test/InstanceSettings.test.ts
Labels: core, n8n team

#12592 refactor(core): Add unit tests for execution lifecycle hooks - part 1
  packages/cli/src/__tests__/execution-lifecycle-hooks.test.ts
Labels: core, n8n team

#12674 fix(Postgres Chat Memory Node): Do not terminate the connection pool
  packages/@n8n/nodes-langchain/nodes/memory/MemoryPostgresChat/MemoryPostgresChat.node.ts
  packages/nodes-base/nodes/Postgres/transport/index.ts
Labels: release/backport

#12641 fix(core): Improve error message when resolving itemMatching with pinned data (no-changelog)
  cypress/e2e/5-ndv.cy.ts
  packages/workflow/src/WorkflowDataProxy.ts
  packages/workflow/test/WorkflowDataProxy.test.ts
  packages/workflow/test/fixtures/WorkflowDataProxy/pindata_paireditem_run.json
  packages/workflow/test/fixtures/WorkflowDataProxy/pindata_paireditem_workflow.json
Labels: core, n8n team

#12672 fix(core): Fix keyboard shortcuts for non-ansi layouts
  packages/editor-ui/src/components/canvas/Canvas.vue
  packages/editor-ui/src/composables/useKeybindings.test.ts
  packages/editor-ui/src/composables/useKeybindings.ts
Labels: ui, n8n team

#12644 chore: Update LangChain packages to their latest versions
  packages/@n8n/nodes-langchain/package.json
  pnpm-lock.yaml
Labels: n8n team

#12677 fix(editor): Correct missing whitespace in JSON output
  packages/editor-ui/src/components/RunDataJson.vue
Labels: ui, n8n team

#12621 feat: Add SelectableList component (no-changelog)
  packages/design-system/src/components/N8nSelectableList/SelectableList.stories.ts
  packages/design-system/src/components/N8nSelectableList/SelectableList.test.ts
  packages/design-system/src/components/N8nSelectableList/SelectableList.vue
  packages/design-system/src/components/N8nSelectableList/__snapshots__/SelectableList.test.ts.snap
  packages/design-system/src/components/N8nSelectableList/index.ts
  packages/design-system/src/components/index.ts
  packages/design-system/src/locale/lang/en.ts
Labels: ui, n8n team

#12666 fix(n8n Form Node): Remove the ability to change the formatting of dates
  packages/nodes-base/nodes/Form/common.descriptions.ts
Labels: node/improvement, n8n team

#12684 chore: Update @langchain/core (no-changelog)
  pnpm-lock.yaml
  pnpm-workspace.yaml
Labels: n8n team

#12645 feat: Add credential only node for Microsoft Azure Monitor
  packages/nodes-base/credentials/MicrosoftAzureMonitorOAuth2Api.credentials.ts
  packages/nodes-base/nodes/HttpRequest/GenericFunctions.ts
  packages/nodes-base/package.json
Labels: node/improvement, n8n team

#12680 chore: Update zod version to 3.24.1 (no-changelog)
  pnpm-lock.yaml
  pnpm-workspace.yaml
Labels: n8n team

#12236 fix(core): Reduce payload of license renewal calls (no-changelog)
  packages/cli/src/databases/repositories/workflow.repository.ts
  packages/cli/src/metrics/license-metrics.service.ts
  packages/cli/test/integration/database/repositories/workflow.repository.test.ts
Labels: core, n8n team

#12681 chore: Bump license-sdk to v2.14.0 (no-changelog)
  packages/cli/package.json
  pnpm-lock.yaml
Labels: core, n8n team

#12636 fix(Wait Node): Fix for hasNextPage in waiting forms
  packages/core/src/execution-engine/node-execution-context/node-execution-context.ts
  packages/nodes-base/nodes/Form/test/utils.test.ts
  packages/nodes-base/nodes/Form/utils.ts
  packages/workflow/src/Interfaces.ts
Labels: n8n team, node/issue

#12611 feat(editor): VariablesView Reskin - Add Filters for missing values
  cypress/e2e/23-variables.cy.ts
  cypress/pages/variables.ts
  packages/design-system/src/components/N8nActionBox/ActionBox.vue
  packages/design-system/src/components/N8nDatatable/Datatable.vue
  packages/design-system/src/components/N8nDatatable/__snapshots__/Datatable.test.ts.snap
  packages/design-system/src/components/N8nFormInput/FormInput.vue
  packages/editor-ui/src/components/VariablesForm.vue
  packages/editor-ui/src/components/VariablesRow.test.ts
  packages/editor-ui/src/components/VariablesRow.vue
  packages/editor-ui/src/components/VariablesUsageBadge.test.ts
  packages/editor-ui/src/components/VariablesUsageBadge.vue
  packages/editor-ui/src/components/layouts/PageViewLayoutList.vue
  packages/editor-ui/src/components/layouts/ResourcesListLayout.vue
  packages/editor-ui/src/plugins/i18n/locales/en.json
  packages/editor-ui/src/views/VariablesView.test.ts
  packages/editor-ui/src/views/VariablesView.vue
Labels: ui, n8n team

#12669 chore(core): Report to Sentry successful execution with empty data
  packages/cli/src/databases/repositories/execution.repository.ts
Labels: core, n8n team

#12662 fix(editor): Partial execution of a workflow with manual chat trigger
  cypress/e2e/30-langchain.cy.ts
  cypress/fixtures/Test_workflow_chat_partial_execution.json
  packages/editor-ui/src/components/CanvasChat/CanvasChat.vue
  packages/editor-ui/src/components/NodeExecuteButton.vue
  packages/editor-ui/src/composables/useRunWorkflow.ts
  packages/editor-ui/src/stores/workflows.store.ts
Labels: ui, n8n team

#12659 feat(editor): Evaluation UI tweaks
  packages/editor-ui/src/components/TestDefinition/EditDefinition/EvaluationHeader.vue
  packages/editor-ui/src/components/TestDefinition/EditDefinition/EvaluationStep.vue
  packages/editor-ui/src/components/TestDefinition/EditDefinition/NodesPinning.vue
  packages/editor-ui/src/components/TestDefinition/EditDefinition/TestNameInput.vue
  packages/editor-ui/src/components/TestDefinition/EditDefinition/sections/ConfigSection.vue
  packages/editor-ui/src/components/TestDefinition/EditDefinition/sections/HeaderSection.vue
  packages/editor-ui/src/components/TestDefinition/EditDefinition/sections/RunsSection.vue
  packages/editor-ui/src/components/TestDefinition/ListDefinition/TestItem.vue
  packages/editor-ui/src/components/TestDefinition/ListDefinition/TestsList.vue
  packages/editor-ui/src/components/TestDefinition/ListRuns/TestRunsTable.vue
  packages/editor-ui/src/components/TestDefinition/composables/useTestDefinitionForm.ts
  packages/editor-ui/src/components/TestDefinition/types.ts
  packages/editor-ui/src/components/WorkflowSelectorParameterInput/WorkflowSelectorParameterInput.vue
  packages/editor-ui/src/components/executions/global/GlobalExecutionsListItem.vue
  packages/editor-ui/src/components/executions/workflow/WorkflowExecutionsCard.vue
  packages/editor-ui/src/plugins/i18n/locales/en.json
  packages/editor-ui/src/stores/testDefinition.store.ee.test.ts
  packages/editor-ui/src/stores/testDefinition.store.ee.ts
  packages/editor-ui/src/views/TestDefinition/TestDefinitionEditView.vue
  packages/editor-ui/src/views/TestDefinition/TestDefinitionListView.vue
  packages/editor-ui/src/views/TestDefinition/TestDefinitionRunsListView.vue
  packages/editor-ui/src/views/TestDefinition/tests/TestDefinitionEditView.test.ts
  packages/editor-ui/src/views/TestDefinition/tests/TestDefinitionListView.test.ts
Labels: ui, n8n team

#12724 chore: Bump License-SDK to v2.14.1 (no-changelog)
  packages/cli/package.json
  pnpm-lock.yaml
Labels: core, n8n team

#12590 feat(n8n Form Trigger Node): Form Improvements
  packages/cli/templates/form-trigger.handlebars
  packages/nodes-base/nodes/Form/common.descriptions.ts
  packages/nodes-base/nodes/Form/interfaces.ts
  packages/nodes-base/nodes/Form/test/FormTriggerV2.node.test.ts
  packages/nodes-base/nodes/Form/test/utils.test.ts
  packages/nodes-base/nodes/Form/utils.ts
  packages/nodes-base/package.json
  packages/nodes-base/utils/sendAndWait/test/util.test.ts
  pnpm-lock.yaml
Labels: node/improvement, core, n8n team

#12170 feat: Synchronize deletions when pulling from source control
  packages/cli/src/commands/ldap/reset.ts
  packages/cli/src/controllers/users.controller.ts
  packages/cli/src/credentials/credentials.controller.ts
  packages/cli/src/credentials/credentials.service.ts
  packages/cli/src/environments.ee/source-control/__tests__/source-control-import.service.ee.test.ts
  packages/cli/src/environments.ee/source-control/__tests__/source-control.service.test.ts
  packages/cli/src/environments.ee/source-control/source-control-import.service.ee.ts
  packages/cli/src/environments.ee/source-control/source-control.controller.ee.ts
  packages/cli/src/environments.ee/source-control/source-control.service.ee.ts
  packages/cli/src/public-api/v1/handlers/source-control/source-control.handler.ts
  packages/cli/src/services/project.service.ee.ts
  packages/cli/src/workflows/workflow.service.ts
  packages/cli/test/integration/environments/source-control-import.service.test.ts
  packages/editor-ui/src/components/MainSidebarSourceControl.test.ts
  packages/editor-ui/src/components/MainSidebarSourceControl.vue
  packages/editor-ui/src/components/SourceControlPullModal.ee.test.ts
  packages/editor-ui/src/components/SourceControlPullModal.ee.vue
  packages/editor-ui/src/components/SourceControlPushModal.ee.vue
  packages/editor-ui/src/plugins/i18n/locales/en.json
  packages/editor-ui/src/utils/sourceControlUtils.test.ts
  packages/editor-ui/src/utils/sourceControlUtils.ts
Labels: core, ui, n8n team

#12725 test(core): Fix a typo and add an additional test
  packages/core/src/execution-engine/partial-execution-utils/__tests__/clean-run-data.test.ts
  packages/core/src/execution-engine/partial-execution-utils/clean-run-data.ts
Labels: core, n8n team

#12717 feat(editor): Force final canvas v2 migration and remove switcher from UI
  cypress/support/commands.ts
  packages/editor-ui/src/components/MainHeader/WorkflowDetails.vue
  packages/editor-ui/src/composables/useNodeViewVersionSwitcher.ts
  packages/editor-ui/src/plugins/i18n/locales/en.json
Labels: ui, n8n team

#12729 chore: Upgrade vitest and storybook (no-changelog)
  packages/@n8n/storybook/package.json
  packages/design-system/package.json
  packages/editor-ui/src/plugins/telemetry.test.ts
  pnpm-lock.yaml
  pnpm-workspace.yaml
Labels: ui, n8n team

#12730 refactor: Remove usless catch blocks, and add a linting rule to prevent them (no-changelog)
  packages/@n8n/nodes-langchain/nodes/vector_store/shared/createVectorStoreNode.ts
  packages/@n8n_io/eslint-config/base.js
  packages/@n8n_io/eslint-config/local-rules.js
  packages/@n8n_io/eslint-config/local-rules.test.js
  packages/editor-ui/src/components/ButtonParameter/utils.ts
  packages/editor-ui/src/components/CanvasChat/CanvasChat.vue
  packages/editor-ui/src/stores/communityNodes.store.ts
  packages/editor-ui/src/stores/executions.store.ts
  packages/nodes-base/nodes/Disqus/Disqus.node.ts
  packages/nodes-base/nodes/Disqus/GenericFunctions.ts
  packages/nodes-base/nodes/FileMaker/GenericFunctions.ts
  packages/nodes-base/nodes/Flow/FlowTrigger.node.ts
  packages/nodes-base/nodes/ItemLists/V3/actions/router.ts
  packages/nodes-base/nodes/Mailchimp/MailchimpTrigger.node.ts
  packages/nodes-base/nodes/PayPal/PayPalTrigger.node.ts
  packages/nodes-base/nodes/Stripe/StripeTrigger.node.ts
  packages/nodes-base/nodes/Webflow/V2/actions/router.ts
Labels: node/improvement, ui, n8n team

#12737 fix(core): Fix license initialization failure on startup
  packages/cli/package.json
  pnpm-lock.yaml
Labels: core, n8n team

#12614 test: Update e2e tests for canvas specific actions (no-changelog)
  cypress/composables/workflow.ts
  cypress/e2e/12-canvas-actions.cy.ts
  cypress/e2e/12-canvas.cy.ts
  cypress/e2e/30-editor-after-route-changes.cy.ts
  cypress/pages/workflow.ts
  cypress/support/commands.ts
  packages/editor-ui/src/components/ContextMenu/ContextMenu.vue
  packages/editor-ui/src/components/canvas/elements/nodes/CanvasNode.vue
  packages/editor-ui/src/components/canvas/elements/nodes/CanvasNodeRenderer.vue
Labels: ui, n8n team

#12738 fix(editor): Fix navbar height flickering during load
  packages/editor-ui/src/components/MainHeader/MainHeader.vue
  packages/editor-ui/src/styles/_global.scss
  packages/editor-ui/src/styles/index.scss
Labels: ui, n8n team
