Repository n8n-io/n8n, pull requests merged in 2025-02, with the labels that each got.

#12970 fix(editor): Make AI transform node read only in executions view
  packages/editor-ui/src/components/ButtonParameter/ButtonParameter.test.ts
  packages/editor-ui/src/components/ButtonParameter/ButtonParameter.vue
Labels: ui, n8n team

#12901 feat(editor): Display schema preview for unexecuted nodes
  packages/editor-ui/package.json
  packages/editor-ui/src/Interface.ts
  packages/editor-ui/src/api/schemaPreview.ts
  packages/editor-ui/src/components/RunData.vue
  packages/editor-ui/src/components/VirtualSchema.test.ts
  packages/editor-ui/src/components/VirtualSchema.vue
  packages/editor-ui/src/components/VirtualSchemaHeader.vue
  packages/editor-ui/src/components/VirtualSchemaItem.vue
  packages/editor-ui/src/components/__snapshots__/VirtualSchema.test.ts.snap
  packages/editor-ui/src/composables/useDataSchema.test.ts
  packages/editor-ui/src/composables/useDataSchema.ts
  packages/editor-ui/src/constants.ts
  packages/editor-ui/src/plugins/i18n/locales/en.json
  packages/editor-ui/src/stores/schemaPreview.store.ts
  packages/nodes-base/nodes/ActiveCampaign/__schema__/v1.0.0/account/get.json
  packages/nodes-base/nodes/Asana/__schema__/v1.0.0/user/get.json
  pnpm-lock.yaml
Labels: node/improvement, ui, n8n team

#13004 ci: Update corepack before enabling it (no-changelog)
  .github/workflows/benchmark-destroy-nightly.yml
  .github/workflows/benchmark-nightly.yml
  .github/workflows/check-documentation-urls.yml
  .github/workflows/check-pr-title.yml
  .github/workflows/chromatic.yml
  .github/workflows/ci-master.yml
  .github/workflows/ci-postgres-mysql.yml
  .github/workflows/ci-pull-requests.yml
  .github/workflows/linting-reusable.yml
  .github/workflows/release-create-pr.yml
  .github/workflows/release-publish.yml
  .github/workflows/release-push-to-channel.yml
  .github/workflows/test-workflows.yml
  .github/workflows/units-tests-reusable.yml
  CONTRIBUTING.md
  docker/images/n8n-base/Dockerfile
  package.json
  packages/@n8n/benchmark/Dockerfile
Labels: n8n team

#12806 fix(core): "Respond to Webhook" should work with workflows with waiting nodes
  packages/cli/src/__tests__/active-executions.test.ts
  packages/cli/src/active-executions.ts
Labels: core, n8n team

#10288 fix(Wise Node): Use ISO formatting for timestamps
  packages/nodes-base/nodes/Wise/Wise.node.ts
Labels: node/improvement, community, in linear, tests-needed

#12732 fix(editor): Prevent infinite loop in expressions crashing the browser
  packages/editor-ui/src/components/AssignmentCollection/Assignment.vue
  packages/editor-ui/src/components/ParameterInputList.vue
  packages/editor-ui/src/components/ParameterInputWrapper.test.ts
  packages/editor-ui/src/components/ParameterInputWrapper.vue
  packages/editor-ui/src/composables/useResolvedExpression.test.ts
  packages/editor-ui/src/composables/useResolvedExpression.ts
  packages/editor-ui/src/composables/useWorkflowHelpers.ts
Labels: ui, n8n team

#13005 feat(OpenAI Chat Model Node, OpenAI Node): Include o3 models in model selection
  packages/@n8n/nodes-langchain/nodes/llms/LMChatOpenAi/LmChatOpenAi.node.ts
  packages/@n8n/nodes-langchain/nodes/llms/LMChatOpenAi/methods/loadModels.ts
  packages/@n8n/nodes-langchain/nodes/vendors/OpenAi/methods/listSearch.ts
Labels: n8n team

#13007 feat(core): Handle Declarative nodes more like regular nodes
  packages/cli/src/__tests__/node-types.test.ts
  packages/cli/src/node-types.ts
  packages/cli/src/services/credentials-tester.service.ts
  packages/cli/src/services/dynamic-node-parameters.service.ts
  packages/core/src/execution-engine/__tests__/routing-node.test.ts
  packages/core/src/execution-engine/node-execution-context/__tests__/shared-tests.ts
  packages/core/src/execution-engine/node-execution-context/base-execute-context.ts
  packages/core/src/execution-engine/node-execution-context/credentials-test-context.ts
  packages/core/src/execution-engine/node-execution-context/index.ts
  packages/core/src/execution-engine/node-execution-context/node-execution-context.ts
  packages/core/src/execution-engine/routing-node.ts
  packages/core/src/execution-engine/workflow-execute.ts
  packages/core/src/node-execute-functions.ts
Labels: core, n8n team

#12840 fix: Sync partial execution version of FE and BE, also allow enforcing a specific version
  packages/@n8n/api-types/src/dto/index.ts
  packages/@n8n/api-types/src/dto/workflows/__tests__/manual-run-query.dto.test.ts
  packages/@n8n/api-types/src/dto/workflows/manual-run-query.dto.ts
  packages/@n8n/api-types/src/frontend-settings.ts
  packages/@n8n/config/src/configs/partial-executions.config.ts
  packages/@n8n/config/src/index.ts
  packages/@n8n/config/test/config.test.ts
  packages/cli/src/config/schema.ts
  packages/cli/src/evaluation.ee/test-runner/test-runner.service.ee.ts
  packages/cli/src/manual-execution.service.ts
  packages/cli/src/services/frontend.service.ts
  packages/cli/src/workflows/workflow-execution.service.ts
  packages/cli/src/workflows/workflow.request.ts
  packages/cli/src/workflows/workflows.controller.ts
  packages/editor-ui/src/__tests__/defaults.ts
  packages/editor-ui/src/composables/useRunWorkflow.test.ts
  packages/editor-ui/src/composables/useRunWorkflow.ts
  packages/editor-ui/src/stores/settings.store.test.ts
  packages/editor-ui/src/stores/settings.store.ts
  packages/editor-ui/src/stores/workflows.store.ts
  packages/workflow/src/Interfaces.ts
Labels: core, ui, n8n team

#13013 ci: Fix tests for declarative nodes (no-changelog)
  packages/core/src/execution-engine/workflow-execute.ts
Labels: core, n8n team

#12954 feat: Allow setting API keys expiration
  packages/@n8n/api-types/src/api-keys.ts
  packages/@n8n/api-types/src/dto/api-keys/__tests__/create-api-key-request.dto.test.ts
  packages/@n8n/api-types/src/dto/api-keys/__tests__/update-api-key-request.dto.test.ts
  packages/@n8n/api-types/src/dto/api-keys/create-api-key-request.dto.ts
  packages/@n8n/api-types/src/dto/api-keys/update-api-key-request.dto.ts
  packages/@n8n/api-types/src/dto/index.ts
  packages/cli/src/controllers/__tests__/api-keys.controller.test.ts
  packages/cli/src/controllers/api-keys.controller.ts
  packages/cli/src/services/public-api-key.service.ts
  packages/cli/test/integration/api-keys.api.test.ts
  packages/cli/test/integration/shared/db/users.ts
  packages/editor-ui/src/api/api-keys.ts
  packages/editor-ui/src/components/ApiKeyCard.vue
  packages/editor-ui/src/components/ApiKeyCreateOrEditModal.test.ts
  packages/editor-ui/src/components/ApiKeyCreateOrEditModal.vue
  packages/editor-ui/src/plugins/i18n/locales/en.json
  packages/editor-ui/src/stores/apiKeys.store.ts
  packages/editor-ui/src/views/SettingsApiView.test.ts
Labels: core, ui, n8n team

#12898 refactor(core): Consolidate execution lifecycle hooks even more + additional tests
  packages/@n8n/api-types/src/scaling.ts
  packages/cli/src/active-executions.ts
  packages/cli/src/execution-lifecycle/__tests__/execution-lifecycle-hooks.test.ts
  packages/cli/src/execution-lifecycle/__tests__/save-execution-progress.test.ts
  packages/cli/src/execution-lifecycle/execution-lifecycle-hooks.ts
  packages/cli/src/execution-lifecycle/save-execution-progress.ts
  packages/cli/src/execution-lifecycle/to-save-settings.ts
  packages/cli/src/executions/execution-recovery.service.ts
  packages/cli/src/scaling/job-processor.ts
  packages/cli/src/workflow-execute-additional-data.ts
  packages/cli/src/workflow-runner.ts
  packages/workflow/src/Interfaces.ts
  packages/workflow/src/WorkflowHooks.ts
Labels: core, n8n team

#13035 fix(Google Cloud Firestore Node): Fix potential prototype pollution vulnerability
  packages/nodes-base/nodes/Google/Firebase/CloudFirestore/GenericFunctions.ts
Labels: node/improvement, n8n team

#13036 ci: Allow building nightly from any branch
  .github/workflows/docker-images-nightly.yml
Labels: n8n team

#13025 fix(editor): Actually enforce the version and don't break for old values in local storage
  packages/editor-ui/src/stores/settings.store.test.ts
  packages/editor-ui/src/stores/settings.store.ts
  packages/editor-ui/src/stores/workflows.store.test.ts
  packages/editor-ui/src/stores/workflows.store.ts
Labels: ui, n8n team

#13034 fix(editor): Fix position of connector buttons when the line is straight
  packages/editor-ui/src/components/canvas/elements/edges/CanvasEdge.test.ts
  packages/editor-ui/src/components/canvas/elements/edges/CanvasEdge.vue
Labels: ui, n8n team

#13037 fix(core): Do not enable strict type validation by default for resource mapper
  packages/core/src/execution-engine/node-execution-context/utils/__tests__/validate-value-against-schema.test.ts
  packages/core/src/execution-engine/node-execution-context/utils/validate-value-against-schema.ts
  packages/workflow/src/Interfaces.ts
Labels: core, n8n team, release/backport

#13016 fix(editor): Add telemetry to source control feature
  packages/editor-ui/src/components/SourceControlPullModal.ee.vue
  packages/editor-ui/src/components/SourceControlPushModal.ee.test.ts
  packages/editor-ui/src/components/SourceControlPushModal.ee.vue
  packages/editor-ui/src/components/layouts/ResourcesListLayout.vue
  packages/editor-ui/src/utils/sourceControlUtils.ts
Labels: ui, n8n team

#13029 feat(core): Add sorting to GET `/workflows` endpoint
  packages/cli/src/databases/repositories/workflow.repository.ts
  packages/cli/src/middlewares/list-query/__tests__/list-query.test.ts
  packages/cli/src/middlewares/list-query/dtos/workflow.sort-by.dto.ts
  packages/cli/src/middlewares/list-query/index.ts
  packages/cli/src/middlewares/list-query/sort-by.ts
  packages/cli/src/requests.ts
  packages/cli/test/integration/workflows/workflows.controller.test.ts
Labels: core, n8n team

#12817 chore(n8n Form Node): Incorporate design feedback for Custom HTML
  packages/cli/templates/form-trigger.handlebars
  packages/editor-ui/public/static/og_image.png
  packages/nodes-base/nodes/Form/common.descriptions.ts
  packages/nodes-base/nodes/Form/test/utils.test.ts
  packages/nodes-base/nodes/Form/utils.ts
  packages/workflow/src/Interfaces.ts
Labels: node/improvement, core, n8n team

#12979 feat(n8n Form Node): Respond with Text
  packages/cli/templates/form-trigger-completion.handlebars
  packages/nodes-base/nodes/Form/Form.node.ts
  packages/nodes-base/nodes/Form/formCompletionUtils.ts
  packages/nodes-base/nodes/Form/formNodeUtils.ts
  packages/nodes-base/nodes/Form/test/Form.node.test.ts
  packages/nodes-base/nodes/Form/utils.ts
Labels: node/improvement, core, n8n team

#12587 feat(editor): Easy $fromAI Button for AI Tools
  cypress/composables/ndv.ts
  cypress/e2e/16-form-trigger-node.cy.ts
  cypress/e2e/48-subworkflow-inputs.cy.ts
  packages/cli/src/__tests__/load-nodes-and-credentials.test.ts
  packages/cli/src/events/relays/telemetry.event-relay.ts
  packages/cli/src/load-nodes-and-credentials.ts
  packages/design-system/src/components/N8nCheckbox/__snapshots__/Checkbox.test.ts.snap
  packages/design-system/src/components/N8nFormBox/__snapshots__/FormBox.test.ts.snap
  packages/design-system/src/components/N8nInputLabel/InputLabel.vue
  packages/design-system/src/components/N8nInputLabel/__snapshots__/InputLabel.test.ts.snap
  packages/design-system/src/components/N8nSelectableList/SelectableList.test.ts
  packages/design-system/src/components/N8nSelectableList/SelectableList.vue
  packages/design-system/src/components/N8nSelectableList/__snapshots__/SelectableList.test.ts.snap
  packages/editor-ui/src/__tests__/mocks.ts
  packages/editor-ui/src/components/AiStarsIcon.vue
  packages/editor-ui/src/components/ExpressionParameterInput.vue
  packages/editor-ui/src/components/InlineExpressionEditor/InlineExpressionEditorInput.vue
  packages/editor-ui/src/components/ParameterInput.vue
  packages/editor-ui/src/components/ParameterInputFull.test.ts
  packages/editor-ui/src/components/ParameterInputFull.vue
  packages/editor-ui/src/components/ParameterInputOverrides/FromAiOverrideButton.vue
  packages/editor-ui/src/components/ParameterInputOverrides/FromAiOverrideField.vue
  packages/editor-ui/src/components/ParameterInputOverrides/ParameterOverrideSelectableList.vue
  packages/editor-ui/src/components/ParameterInputWrapper.vue
  packages/editor-ui/src/components/ResourceLocator/ResourceLocator.vue
  packages/editor-ui/src/components/ResourceLocator/resourceLocator.scss
  packages/editor-ui/src/components/__snapshots__/MultipleParameter.test.ts.snap
  packages/editor-ui/src/plugins/i18n/locales/en.json
  packages/editor-ui/src/utils/fromAIOverrideUtils.test.ts
  packages/editor-ui/src/utils/fromAIOverrideUtils.ts
  packages/workflow/src/Constants.ts
  packages/workflow/src/TelemetryHelpers.ts
  packages/workflow/test/FromAIParseUtils.test.ts
  packages/workflow/test/TelemetryHelpers.test.ts
Labels: ui, n8n team

#13038 feat: Add support for client credentials with Azure Log monitor
  packages/nodes-base/credentials/MicrosoftAzureMonitorOAuth2Api.credentials.ts
Labels: node/improvement, n8n team

#13061 fix(editor): Move overrideButton and other options to the left to line up with container boundary (no-changelog)
  packages/editor-ui/src/components/ParameterInput.vue
  packages/editor-ui/src/components/ParameterInputFull.vue
  packages/editor-ui/src/components/ParameterInputWrapper.vue
Labels: ui, n8n team

#13048 feat(HTTP Request Tool Node): Relax binary data detection
  packages/@n8n/nodes-langchain/nodes/tools/ToolHttpRequest/test/ToolHttpRequest.node.test.ts
  packages/@n8n/nodes-langchain/nodes/tools/ToolHttpRequest/utils.ts
Labels: n8n team

#13052 fix(AI Agent Node): Ignore SSL errors option for SQLAgent
  packages/@n8n/nodes-langchain/nodes/agents/Agent/agents/SqlAgent/other/handlers/postgres.test.ts
  packages/@n8n/nodes-langchain/nodes/agents/Agent/agents/SqlAgent/other/handlers/postgres.ts
Labels: n8n team

#13069 feat(Summarize Node): Preserves original field data type
  packages/nodes-base/nodes/Transform/Summarize/Summarize.node.ts
  packages/nodes-base/nodes/Transform/Summarize/test/workflow.summarize_datatypes.json
  packages/nodes-base/nodes/Transform/Summarize/utils.ts
Labels: node/improvement, n8n team

#13024 feat(Facebook Graph API Node): Update node to support API v22.0
  packages/nodes-base/nodes/Facebook/FacebookGraphApi.node.ts
Labels: node/improvement, community, in linear

#13068 fix(editor): Fix overrideField text overflow (no-changelog)
  packages/editor-ui/src/components/ParameterInputOverrides/FromAiOverrideField.vue
  packages/editor-ui/src/components/ResourceLocator/resourceLocator.scss
  packages/editor-ui/src/plugins/i18n/locales/en.json
Labels: ui, n8n team

#13062 feat: Add new schema files (no-changelog)
  packages/nodes-base/nodes/ActiveCampaign/__schema__/v1.0.0/deal/get.json
  packages/nodes-base/nodes/ActiveCampaign/__schema__/v1.0.0/deal/getAll.json
  packages/nodes-base/nodes/ActiveCampaign/__schema__/v1.0.0/deal/update.json
  packages/nodes-base/nodes/Aws/S3/__schema__/v2.0.0/file/download.json
  packages/nodes-base/nodes/ClickUp/__schema__/v1.0.0/timeEntry/getAll.json
  packages/nodes-base/nodes/Coda/__schema__/v1.1.0/table/getAllColumns.json
  packages/nodes-base/nodes/Coda/__schema__/v1.1.0/table/pushButton.json
  packages/nodes-base/nodes/ERPNext/__schema__/v1.0.0/document/getAll.json
  packages/nodes-base/nodes/Freshservice/__schema__/v1.0.0/ticket/get.json
  packages/nodes-base/nodes/Github/__schema__/v1.0.0/file/get.json
  packages/nodes-base/nodes/Gong/__schema__/v1.0.0/call/getAll.json
  packages/nodes-base/nodes/Google/Calendar/__schema__/v1.3.0/event/update.json
  packages/nodes-base/nodes/Google/Drive/__schema__/v2.0.0/file/list.json
  packages/nodes-base/nodes/Google/Slides/__schema__/v2.0.0/page/get.json
  packages/nodes-base/nodes/Grafana/__schema__/v1.0.0/dashboard/get.json
  packages/nodes-base/nodes/Harvest/__schema__/v1.0.0/invoice/getAll.json
  packages/nodes-base/nodes/HomeAssistant/__schema__/v1.0.0/state/upsert.json
  packages/nodes-base/nodes/Hubspot/__schema__/v2.1.0/company/update.json
  packages/nodes-base/nodes/OpenAi/__schema__/v1.1.0/text/complete.json
  packages/nodes-base/nodes/QuickBooks/__schema__/v1.0.0/vendor/getAll.json
  packages/nodes-base/nodes/Spotify/__schema__/v1.0.0/album/search.json
  packages/nodes-base/nodes/Spotify/__schema__/v1.0.0/artist/getTopTracks.json
  packages/nodes-base/nodes/Spotify/__schema__/v1.0.0/player/recentlyPlayed.json
  packages/nodes-base/nodes/Telegram/__schema__/v1.2.0/message/sendLocation.json
  packages/nodes-base/nodes/Todoist/__schema__/v2.1.0/task/close.json
  packages/nodes-base/nodes/Trello/__schema__/v1.0.0/checklist/create.json
  packages/nodes-base/nodes/Trello/__schema__/v1.0.0/checklist/createCheckItem.json
  packages/nodes-base/nodes/Wise/__schema__/v1.0.0/account/getBalances.json
  packages/nodes-base/nodes/WooCommerce/__schema__/v1.0.0/customer/get.json
  packages/nodes-base/nodes/Zendesk/__schema__/v1.0.0/user/getAll.json
Labels: n8n team

#13041 fix(editor): Allow to re-open sub-connection node creator if already active
  packages/editor-ui/src/Interface.ts
  packages/editor-ui/src/components/Node/NodeCreator/Panel/NodesListPanel.vue
  packages/editor-ui/src/components/Node/NodeCreator/composables/useViewStacks.ts
  packages/editor-ui/src/stores/nodeCreator.store.test.ts
  packages/editor-ui/src/stores/nodeCreator.store.ts
Labels: ui, n8n team

#13078 fix(editor): Code node overwrites code when switching nodes after edits
  cypress/e2e/6-code-node.cy.ts
  cypress/pages/ndv.ts
  packages/editor-ui/src/components/ParameterInput.vue
  packages/editor-ui/src/composables/useCodeEditor.ts
  packages/editor-ui/src/composables/useDebounce.ts
Labels: ui, n8n team

#13090 test: Fix flaky code node switching test
  cypress/e2e/6-code-node.cy.ts
Labels: n8n team

#13077 feat: Add reusable frontend `composables` package
  codecov.yml
  packages/design-system/.eslintrc.js
  packages/design-system/package.json
  packages/design-system/src/components/N8nKeyboardShortcut/N8nKeyboardShortcut.vue
  packages/design-system/src/components/N8nUserStack/UserStack.test.ts
  packages/design-system/src/index.ts
  packages/design-system/tsconfig.json
  packages/design-system/vite.config.mts
  packages/editor-ui/.eslintrc.js
  packages/editor-ui/package.json
  packages/editor-ui/src/components/CanvasControls.vue
  packages/editor-ui/src/components/Node.vue
  packages/editor-ui/src/components/NodeDetailsView.vue
  packages/editor-ui/src/components/Sticky.vue
  packages/editor-ui/src/components/canvas/Canvas.test.ts
  packages/editor-ui/src/components/canvas/Canvas.vue
  packages/editor-ui/src/composables/useCanvasMouseSelect.ts
  packages/editor-ui/src/composables/useCanvasPanning.ts
  packages/editor-ui/src/composables/useDebugInfo.test.ts
  packages/editor-ui/src/composables/useDebugInfo.ts
  packages/editor-ui/src/composables/useHistoryHelper.ts
  packages/editor-ui/src/composables/useKeybindings.ts
  packages/editor-ui/src/composables/useNodeBase.ts
  packages/editor-ui/src/views/NodeView.vue
  packages/editor-ui/tsconfig.json
  packages/editor-ui/vite.config.mts
  packages/frontend/@n8n/composables/.eslintrc.cjs
  packages/frontend/@n8n/composables/.gitignore
  packages/frontend/@n8n/composables/README.md
  packages/frontend/@n8n/composables/biome.jsonc
  packages/frontend/@n8n/composables/package.json
  packages/frontend/@n8n/composables/src/__tests__/setup.ts
  packages/frontend/@n8n/composables/src/shims.d.ts
  packages/frontend/@n8n/composables/src/useDeviceSupport.test.ts
  packages/frontend/@n8n/composables/src/useDeviceSupport.ts
  packages/frontend/@n8n/composables/tsconfig.json
  packages/frontend/@n8n/composables/tsup.config.ts
  packages/frontend/@n8n/composables/vite.config.ts
  packages/frontend/tooling/eslint-config/index.cjs
  packages/frontend/tooling/eslint-config/index.d.ts
  packages/frontend/tooling/eslint-config/package.json
  packages/frontend/tooling/typescript-config/package.json
  packages/frontend/tooling/typescript-config/tsconfig.json
  packages/frontend/tooling/vitest-config/index.d.ts
  packages/frontend/tooling/vitest-config/index.mjs
  packages/frontend/tooling/vitest-config/package.json
  pnpm-lock.yaml
  pnpm-workspace.yaml
  turbo.json
Labels: ui, n8n team

#13065 fix(core): Do not emit `workflow-post-execute` event for waiting executions
  packages/cli/src/events/__tests__/telemetry-event-relay.test.ts
  packages/cli/src/events/relays/telemetry.event-relay.ts
  packages/cli/src/execution-lifecycle/__tests__/execution-lifecycle-hooks.test.ts
  packages/cli/src/execution-lifecycle/execution-lifecycle-hooks.ts
  packages/cli/src/executions/__tests__/execution-recovery.service.test.ts
  packages/cli/src/executions/execution-recovery.service.ts
Labels: core, n8n team

#13098 fix: Add version to new @n8n/composables package (no-changelog)
  packages/frontend/@n8n/composables/package.json
Labels: n8n team

#13097 feat(editor): Add docs link in $fromAI hover info tooltip
  packages/editor-ui/src/plugins/codemirror/completions/constants.ts
Labels: ui, n8n team

#13075 feat(core): Add an option to allow community nodes as tools
  packages/@n8n/config/src/configs/nodes.config.ts
  packages/@n8n/config/test/config.test.ts
  packages/cli/src/__tests__/node-types.test.ts
  packages/cli/src/node-types.ts
Labels: core, n8n team

#11716 feat: Do not assign all paired items (no-changelog)
  packages/nodes-base/nodes/Airtable/test/v2/node/base/getMany.test.ts
  packages/nodes-base/nodes/Airtable/test/v2/node/record/search.test.ts
  packages/nodes-base/nodes/Airtable/v1/AirtableV1.node.ts
  packages/nodes-base/nodes/Airtable/v2/actions/base/getMany.operation.ts
  packages/nodes-base/nodes/Airtable/v2/actions/record/search.operation.ts
  packages/nodes-base/nodes/ExecuteWorkflow/ExecuteWorkflow/ExecuteWorkflow.node.ts
  packages/nodes-base/nodes/Files/ConvertToFile/actions/spreadsheet.operation.ts
  packages/nodes-base/nodes/Files/ConvertToFile/actions/toJson.operation.ts
  packages/nodes-base/nodes/Ftp/Ftp.node.ts
  packages/nodes-base/nodes/Google/BigQuery/v1/GoogleBigQueryV1.node.ts
  packages/nodes-base/nodes/Google/BigQuery/v2/actions/database/insert.operation.ts
  packages/nodes-base/nodes/Google/Firebase/CloudFirestore/GoogleFirebaseCloudFirestore.node.ts
  packages/nodes-base/nodes/Google/Sheet/v1/GoogleSheetsV1.node.ts
  packages/nodes-base/nodes/Google/Sheet/v2/actions/sheet/delete.operation.ts
  packages/nodes-base/nodes/Hubspot/V2/HubspotV2.node.ts
  packages/nodes-base/nodes/Kafka/Kafka.node.ts
  packages/nodes-base/nodes/Microsoft/Excel/v1/MicrosoftExcelV1.node.ts
  packages/nodes-base/nodes/Microsoft/Excel/v2/actions/table/append.operation.ts
  packages/nodes-base/nodes/Microsoft/Excel/v2/actions/worksheet/update.operation.ts
  packages/nodes-base/nodes/Microsoft/Excel/v2/actions/worksheet/upsert.operation.ts
  packages/nodes-base/nodes/Microsoft/Excel/v2/helpers/utils.ts
  packages/nodes-base/nodes/Microsoft/Sql/MicrosoftSql.node.ts
  packages/nodes-base/nodes/MongoDb/MongoDb.node.ts
  packages/nodes-base/nodes/Postgres/test/v2/runQueries.test.ts
  packages/nodes-base/nodes/Postgres/v2/helpers/utils.ts
  packages/nodes-base/nodes/QuickBase/QuickBase.node.ts
  packages/nodes-base/nodes/ReadBinaryFiles/ReadBinaryFiles.node.ts
  packages/nodes-base/nodes/RespondToWebhook/RespondToWebhook.node.ts
  packages/nodes-base/nodes/RespondToWebhook/test/RespondToWebhook.test.ts
  packages/nodes-base/nodes/RssFeedRead/RssFeedRead.node.ts
  packages/nodes-base/nodes/SpreadsheetFile/v1/SpreadsheetFileV1.node.ts
  packages/nodes-base/nodes/SpreadsheetFile/v2/toFile.operation.ts
  packages/nodes-base/nodes/Stackby/Stackby.node.ts
Labels: n8n team, node/issue

#13053 fix(core): Fix high volume of node operation errors in Sentry
  packages/workflow/src/errors/node-operation.error.ts
Labels: core, n8n team

#13085 fix(editor): Fix issues with push connect reconnection
  packages/editor-ui/src/Interface.ts
  packages/editor-ui/src/components/CanvasChat/CanvasChat.test.ts
  packages/editor-ui/src/components/MainHeader/WorkflowDetails.test.ts
  packages/editor-ui/src/components/PushConnectionTracker.test.ts
  packages/editor-ui/src/components/PushConnectionTracker.vue
  packages/editor-ui/src/components/__snapshots__/PushConnectionTracker.test.ts.snap
  packages/editor-ui/src/composables/useRunWorkflow.test.ts
  packages/editor-ui/src/composables/useRunWorkflow.ts
  packages/editor-ui/src/push-connection/__tests__/mockEventSource.ts
  packages/editor-ui/src/push-connection/__tests__/mockWebSocketClient.ts
  packages/editor-ui/src/push-connection/__tests__/useEventSourceClient.test.ts
  packages/editor-ui/src/push-connection/__tests__/useHeartbeat.test.ts
  packages/editor-ui/src/push-connection/__tests__/useWebSocketClient.test.ts
  packages/editor-ui/src/push-connection/useEventSourceClient.ts
  packages/editor-ui/src/push-connection/useHeartbeat.ts
  packages/editor-ui/src/push-connection/useReconnectTimer.ts
  packages/editor-ui/src/push-connection/useWebSocketClient.ts
  packages/editor-ui/src/stores/pushConnection.store.ts
  packages/editor-ui/src/stores/root.store.ts
Labels: ui, n8n team

#13103 feat(OpenAI Chat Model Node): Add reasoning effort option to control the amount of reasoning tokens to use
  packages/@n8n/nodes-langchain/nodes/llms/LMChatOpenAi/LmChatOpenAi.node.ts
Labels: n8n team

#13076 refactor(Google Gemini Chat Model Node): Provide custom message mapper to N8nLlmTracing (no-changelog)
  packages/@n8n/nodes-langchain/nodes/llms/LmChatGoogleGemini/LmChatGoogleGemini.node.ts
  packages/@n8n/nodes-langchain/nodes/llms/N8nLlmTracing.ts
Labels: n8n team

#13102 fix(Call n8n Sub-Workflow Tool Node): Fix json type when using $fromAI
  packages/core/src/execution-engine/node-execution-context/utils/__tests__/create-node-as-tool.test.ts
  packages/workflow/src/FromAIParseUtils.ts
  packages/workflow/test/FromAIParseUtils.test.ts
Labels: core, n8n team

#12978 fix(Basic LLM Chain Node): Use correct mimetype for binary data
  packages/@n8n/nodes-langchain/nodes/chains/ChainLLM/ChainLlm.node.ts
  packages/@n8n/nodes-langchain/nodes/chains/ChainLLM/test/utils.test.ts
  packages/@n8n/nodes-langchain/nodes/chains/ChainLLM/utils.ts
Labels: n8n team

#13120 feat(editor): Add `node_id` to canvas events (no-changelog)
  packages/editor-ui/src/components/NodeDetailsView.vue
  packages/editor-ui/src/composables/useCanvasOperations.ts
  packages/editor-ui/src/stores/nodeCreator.store.test.ts
  packages/editor-ui/src/stores/nodeCreator.store.ts
  packages/editor-ui/src/views/NodeView.vue
Labels: ui, n8n team

#11432 refactor: Move cURL converter to frontend
  package.json
  packages/cli/package.json
  packages/cli/src/controllers/__tests__/curl.controller.test.ts
  packages/cli/src/controllers/curl.controller.ts
  packages/cli/src/curlconverter.d.ts
  packages/cli/src/server.ts
  packages/cli/src/services/__tests__/curl.service.test.ts
  packages/cli/src/services/curl.service.ts
  packages/editor-ui/package.json
  packages/editor-ui/src/api/curlHelper.ts
  packages/editor-ui/src/components/ImportCurlModal.vue
  packages/editor-ui/src/composables/useImportCurlCommand.test.ts
  packages/editor-ui/src/composables/useImportCurlCommand.ts
  packages/editor-ui/src/stores/ui.store.ts
  packages/editor-ui/vite.config.mts
  patches/curlconverter@4.11.0.patch
  pnpm-lock.yaml
Labels: core, ui, n8n team

#13118 fix(core): Add an option to enable dual-stack lookup to support IPv6 for redis
  packages/@n8n/config/src/configs/scaling-mode.config.ts
  packages/@n8n/config/test/config.test.ts
  packages/cli/src/services/redis-client.service.ts
Labels: core, n8n team

#13051 fix(core): Handle cancellation of waiting executions correctly
  packages/cli/src/__tests__/active-executions.test.ts
  packages/cli/src/active-executions.ts
  packages/cli/src/concurrency/__tests__/concurrency-control.service.test.ts
  packages/cli/src/concurrency/concurrency-control.service.ts
  packages/cli/src/webhooks/webhook-helpers.ts
Labels: core, n8n team

#13123 ci: Create task runner sentry release on publish
  .github/workflows/release-publish.yml
Labels: n8n team

#13124 chore(editor): Upgrade curlconverter, remove the custom patch (no-changelog)
  package.json
  packages/editor-ui/package.json
  patches/curlconverter@4.11.0.patch
  pnpm-lock.yaml
Labels: ui, n8n team

#13119 fix(Google Sheets Trigger Node): Do not return header row in rowAdded mode
  packages/nodes-base/nodes/Google/Sheet/GoogleSheetsTrigger.node.ts
  packages/nodes-base/nodes/Google/Sheet/test/GoogleSheetsTrigger.test.ts
Labels: node/improvement, n8n team

#13131 refactor(core): Move more code out of NodeExecutionFunctions, and add unit tests (no-changelog)
  packages/cli/src/active-workflow-manager.ts
  packages/core/src/__tests__/node-execute-functions.test.ts
  packages/core/src/execution-engine/__tests__/active-workflows.test.ts
  packages/core/src/execution-engine/active-workflows.ts
  packages/core/src/execution-engine/index.ts
  packages/core/src/execution-engine/interfaces.ts
  packages/core/src/execution-engine/node-execution-context/execute-context.ts
  packages/core/src/execution-engine/node-execution-context/execute-single-context.ts
  packages/core/src/execution-engine/node-execution-context/index.ts
  packages/core/src/execution-engine/node-execution-context/poll-context.ts
  packages/core/src/execution-engine/node-execution-context/supply-data-context.ts
  packages/core/src/execution-engine/node-execution-context/trigger-context.ts
  packages/core/src/execution-engine/node-execution-context/utils/__tests__/binary-helper-functions.test.ts
  packages/core/src/execution-engine/node-execution-context/utils/__tests__/deduplication-helper-functions.test.ts
  packages/core/src/execution-engine/node-execution-context/utils/__tests__/file-system-helper-functions.test.ts
  packages/core/src/execution-engine/node-execution-context/utils/__tests__/parse-incoming-message.test.ts
  packages/core/src/execution-engine/node-execution-context/utils/__tests__/parse-request-object.test.ts
  packages/core/src/execution-engine/node-execution-context/utils/binary-helper-functions.ts
  packages/core/src/execution-engine/node-execution-context/utils/deduplication-helper-functions.ts
  packages/core/src/execution-engine/node-execution-context/utils/file-system-helper-functions.ts
  packages/core/src/execution-engine/node-execution-context/utils/parse-incoming-message.ts
  packages/core/src/execution-engine/node-execution-context/utils/parse-request-object.ts
  packages/core/src/execution-engine/node-execution-context/webhook-context.ts
  packages/core/src/execution-engine/triggers-and-pollers.ts
  packages/core/src/node-execute-functions.ts
  packages/workflow/src/Interfaces.ts
Labels: core, n8n team

#13110 fix(core): Allow secrets manager secrets to be used in credentials
  packages/cli/src/controllers/oauth/__tests__/oauth1-credential.controller.test.ts
  packages/cli/src/controllers/oauth/__tests__/oauth2-credential.controller.test.ts
  packages/cli/src/controllers/oauth/abstract-oauth.controller.ts
  packages/cli/src/controllers/oauth/oauth1-credential.controller.ts
  packages/cli/src/controllers/oauth/oauth2-credential.controller.ts
Labels: core, n8n team

#13042 refactor(core): Move ExecutionLifecycleHooks to core
  packages/cli/src/__tests__/workflow-runner.test.ts
  packages/cli/src/execution-lifecycle/__tests__/execution-lifecycle-hooks.test.ts
  packages/cli/src/execution-lifecycle/execution-lifecycle-hooks.ts
  packages/cli/src/executions/execution-recovery.service.ts
  packages/cli/src/scaling/job-processor.ts
  packages/cli/src/workflow-execute-additional-data.ts
  packages/cli/src/workflow-runner.ts
  packages/core/src/__tests__/node-execute-functions.test.ts
  packages/core/src/execution-engine/__tests__/execution-lifecycle-hooks.test.ts
  packages/core/src/execution-engine/__tests__/triggers-and-pollers.test.ts
  packages/core/src/execution-engine/__tests__/workflow-execute.test.ts
  packages/core/src/execution-engine/execution-lifecycle-hooks.ts
  packages/core/src/execution-engine/index.ts
  packages/core/src/execution-engine/node-execution-context/execute-context.ts
  packages/core/src/execution-engine/node-execution-context/supply-data-context.ts
  packages/core/src/execution-engine/triggers-and-pollers.ts
  packages/core/src/execution-engine/workflow-execute.ts
  packages/core/src/node-execute-functions.ts
  packages/core/test/helpers/index.ts
  packages/nodes-base/test/nodes/Helpers.ts
  packages/nodes-base/test/nodes/TriggerHelpers.ts
  packages/workflow/src/Interfaces.ts
  packages/workflow/src/WorkflowHooks.ts
  packages/workflow/src/index.ts
Labels: node/improvement, core, n8n team

#12964 feat(Microsoft Teams Node): New operation sendAndWait
  packages/nodes-base/nodes/Discord/test/v2/node/message/sendAndWait.test.ts
  packages/nodes-base/nodes/Discord/v2/helpers/utils.ts
  packages/nodes-base/nodes/EmailSend/v2/send.operation.ts
  packages/nodes-base/nodes/Google/Chat/GenericFunctions.ts
  packages/nodes-base/nodes/Google/Chat/test/node/sendAndWait.operation.test.ts
  packages/nodes-base/nodes/Google/Gmail/GenericFunctions.ts
  packages/nodes-base/nodes/Microsoft/Teams/MicrosoftTeams.node.json
  packages/nodes-base/nodes/Microsoft/Teams/test/v2/node/chatMessage/sendAndWait.test.ts
  packages/nodes-base/nodes/Microsoft/Teams/v2/MicrosoftTeamsV2.node.ts
  packages/nodes-base/nodes/Microsoft/Teams/v2/actions/chatMessage/index.ts
  packages/nodes-base/nodes/Microsoft/Teams/v2/actions/chatMessage/sendAndWait.operation.ts
  packages/nodes-base/nodes/Microsoft/Teams/v2/actions/node.type.ts
  packages/nodes-base/nodes/Microsoft/Teams/v2/actions/router.ts
  packages/nodes-base/nodes/Microsoft/Teams/v2/actions/versionDescription.ts
  packages/nodes-base/nodes/Telegram/GenericFunctions.ts
  packages/nodes-base/utils/utilities.ts
Labels: node/improvement, n8n team

#12769 feat(editor): Add ‘execute workflow’ buttons below triggers on the canvas
  cypress/composables/ndv.ts
  cypress/composables/workflow.ts
  cypress/e2e/19-execution.cy.ts
  cypress/fixtures/Two_schedule_triggers.json
  packages/cli/src/__tests__/manual-execution.service.test.ts
  packages/cli/src/manual-execution.service.ts
  packages/cli/src/workflows/__tests__/workflow-execution.service.test.ts
  packages/cli/src/workflows/workflow-execution.service.ts
  packages/editor-ui/src/Interface.ts
  packages/editor-ui/src/components/canvas/Canvas.vue
  packages/editor-ui/src/components/canvas/elements/nodes/CanvasNode.vue
  packages/editor-ui/src/components/canvas/elements/nodes/render-types/CanvasNodeDefault.vue
  packages/editor-ui/src/components/canvas/elements/nodes/render-types/__snapshots__/CanvasNodeDefault.test.ts.snap
  packages/editor-ui/src/components/canvas/elements/nodes/render-types/parts/CanvasNodeTooltip.vue
  packages/editor-ui/src/components/canvas/elements/nodes/render-types/parts/CanvasNodeTrigger.vue
  packages/editor-ui/src/components/canvas/elements/nodes/render-types/parts/CanvasNodeTriggerIcon.test.ts
  packages/editor-ui/src/components/canvas/elements/nodes/render-types/parts/CanvasNodeTriggerIcon.vue
  packages/editor-ui/src/composables/useCanvasMapping.ts
  packages/editor-ui/src/composables/useCanvasNodeHover.test.ts
  packages/editor-ui/src/composables/useCanvasNodeHover.ts
  packages/editor-ui/src/composables/useCanvasOperations.test.ts
  packages/editor-ui/src/composables/useCanvasOperations.ts
  packages/editor-ui/src/composables/useRunWorkflow.test.ts
  packages/editor-ui/src/composables/useRunWorkflow.ts
  packages/editor-ui/src/constants.ts
  packages/editor-ui/src/plugins/i18n/locales/en.json
  packages/editor-ui/src/views/NodeView.v2.vue
  packages/editor-ui/src/views/NodeView.vue
Labels: ui, n8n team

#12826 fix(editor): Load only personal credentials when setting up a template
  packages/editor-ui/src/components/CredentialPicker/CredentialPicker.test.constants.ts
  packages/editor-ui/src/components/CredentialPicker/CredentialPicker.test.ts
  packages/editor-ui/src/components/CredentialPicker/CredentialPicker.vue
Labels: ui, n8n team

#13125 fix(editor): Disable fromAI button for vector stores
  packages/editor-ui/src/utils/fromAIOverrideUtils.test.ts
  packages/editor-ui/src/utils/fromAIOverrideUtils.ts
Labels: ui, n8n team, release/backport

#13133 fix(editor): Fix sending of push messages when connection is down (no-changelog)
  packages/editor-ui/src/push-connection/useReconnectTimer.ts
  packages/editor-ui/src/push-connection/useWebSocketClient.ts
  packages/editor-ui/src/stores/pushConnection.store.test.ts
  packages/editor-ui/src/stores/pushConnection.store.ts
Labels: ui, n8n team

#13116 fix(Google Sheets Node): RMC should correctly map columns if data location set in options
  packages/nodes-base/nodes/Google/Sheet/test/v2/methods/resourceMapping.test.ts
  packages/nodes-base/nodes/Google/Sheet/test/v2/utils/utils.test.ts
  packages/nodes-base/nodes/Google/Sheet/v2/helpers/GoogleSheets.utils.ts
  packages/nodes-base/nodes/Google/Sheet/v2/methods/resourceMapping.ts
Labels: n8n team, node/issue

#13166 fix(core): Handle credential decryption failures gracefully on the API
  packages/cli/src/credentials/__tests__/credentials.service.test.ts
  packages/cli/src/credentials/credentials.service.ts
Labels: core, n8n team

#13106 fix(core): Same version of merge node behaves differently after n8n update
  packages/core/src/execution-engine/workflow-execute.ts
Labels: core, n8n team

#13137 fix(OpenAI Node): Limit chat history to context window when using memory
  packages/@n8n/nodes-langchain/nodes/vendors/OpenAi/actions/assistant/message.operation.ts
  packages/@n8n/nodes-langchain/nodes/vendors/OpenAi/helpers/utils.ts
  packages/@n8n/nodes-langchain/nodes/vendors/OpenAi/test/utils.test.ts
Labels: n8n team

#13111 refactor(core): Remove NodeExecutionOutput. Add execution hints directly to the context
  packages/core/src/execution-engine/__tests__/workflow-execute.test.ts
  packages/core/src/execution-engine/node-execution-context/execute-context.ts
  packages/core/src/execution-engine/workflow-execute.ts
  packages/nodes-base/nodes/Code/Code.node.ts
  packages/nodes-base/nodes/Code/test/utils.test.ts
  packages/nodes-base/nodes/Code/utils.ts
  packages/nodes-base/nodes/Google/Calendar/GoogleCalendar.node.ts
  packages/nodes-base/nodes/Google/Calendar/test/node/event.getAll.test.ts
  packages/nodes-base/nodes/HttpRequest/V3/HttpRequestV3.node.ts
  packages/nodes-base/nodes/Merge/v3/actions/mode/combineByPosition.ts
  packages/nodes-base/nodes/Postgres/v2/actions/router.ts
  packages/nodes-base/nodes/Transform/Aggregate/Aggregate.node.ts
  packages/nodes-base/nodes/Transform/RemoveDuplicates/v2/RemoveDuplicatesV2.node.ts
  packages/nodes-base/nodes/Transform/SplitOut/SplitOut.node.ts
  packages/nodes-base/nodes/Transform/Summarize/Summarize.node.ts
  packages/nodes-base/nodes/Transform/Summarize/test/unitTests/execute.test.ts
  packages/workflow/src/Interfaces.ts
Labels: node/improvement, core, n8n team

#13127 chore(editor): Upgrade vitest to address CVE-2025-24964
  pnpm-lock.yaml
  pnpm-workspace.yaml
Labels: n8n team

#13170 fix(core): Do not save credential overwrites data into the database
  packages/cli/src/controllers/oauth/__tests__/oauth1-credential.controller.test.ts
  packages/cli/src/controllers/oauth/__tests__/oauth2-credential.controller.test.ts
  packages/cli/src/controllers/oauth/abstract-oauth.controller.ts
  packages/cli/src/controllers/oauth/oauth1-credential.controller.ts
  packages/cli/src/controllers/oauth/oauth2-credential.controller.ts
  packages/core/src/__tests__/credentials.test.ts
  packages/core/src/credentials.ts
Labels: core, n8n team

#13136 fix(core): Fix parsing of push messages (no-changelog)
  packages/@n8n/api-types/src/index.ts
  packages/@n8n/api-types/src/push/heartbeat.ts
  packages/cli/src/push/__tests__/websocket.push.test.ts
  packages/cli/src/push/websocket.push.ts
  packages/editor-ui/src/push-connection/useWebSocketClient.ts
Labels: core, ui, n8n team

#13158 fix(Google Sheets Node): Do not delete row_number key from input item
  packages/nodes-base/nodes/Google/Sheet/test/v2/node/append.test.ts
  packages/nodes-base/nodes/Google/Sheet/v2/helpers/GoogleSheets.utils.ts
Labels: n8n team, node/issue

#13171 fix(Gmail Trigger Node): Prevent error for empty emails, improve type safety
  packages/nodes-base/nodes/Google/Gmail/GmailTrigger.node.ts
  packages/nodes-base/nodes/Google/Gmail/test/GmailTrigger.test.ts
  packages/nodes-base/nodes/Google/Gmail/test/__snapshots__/GmailTrigger.test.ts.snap
  packages/nodes-base/nodes/Google/Gmail/types.ts
Labels: node/improvement, n8n team

#13167 fix(editor): Fix alignment in RMC component
  packages/editor-ui/src/components/ResourceMapper/MappingFields.vue
Labels: ui, n8n team

#13162 fix(n8n Form Trigger Node): Update error in validateResponseModeConfiguration (no-changelog)
  packages/nodes-base/nodes/Form/test/FormTriggerV2.node.test.ts
  packages/nodes-base/nodes/Form/test/utils.test.ts
  packages/nodes-base/nodes/Form/utils.ts
Labels: n8n team, node/issue

#13191 perf(core): Batch workflow activation to speed up startup
  packages/@n8n/config/src/configs/workflows.config.ts
  packages/@n8n/config/src/index.ts
  packages/@n8n/config/test/config.test.ts
  packages/cli/src/__tests__/active-workflow-manager.test.ts
  packages/cli/src/active-workflow-manager.ts
Labels: core, n8n team

#12838 feat(core): Add error reporting for workflow evaluation (no-changelog)
  cypress/e2e/233-AI-switch-to-logs-on-error.cy.ts
  packages/@n8n/nodes-langchain/nodes/chains/InformationExtractor/test/InformationExtraction.node.test.ts
  packages/cli/src/commands/base-command.ts
  packages/cli/src/commands/start.ts
  packages/cli/src/databases/entities/test-case-execution.ee.ts
  packages/cli/src/databases/entities/test-run.ee.ts
  packages/cli/src/databases/migrations/common/1737715421462-AddErrorColumnsToTestRuns.ts
  packages/cli/src/databases/migrations/mysqldb/index.ts
  packages/cli/src/databases/migrations/postgresdb/index.ts
  packages/cli/src/databases/migrations/sqlite/index.ts
  packages/cli/src/databases/repositories/test-case-execution.repository.ee.ts
  packages/cli/src/databases/repositories/test-run.repository.ee.ts
  packages/cli/src/evaluation.ee/test-definition.service.ee.ts
  packages/cli/src/evaluation.ee/test-runner/__tests__/evaluation-metrics.ee.test.ts
  packages/cli/src/evaluation.ee/test-runner/__tests__/get-test-run-final-result.ee.test.ts
  packages/cli/src/evaluation.ee/test-runner/__tests__/mock-data/execution-data-renamed-nodes.json
  packages/cli/src/evaluation.ee/test-runner/__tests__/test-runner.service.ee.test.ts
  packages/cli/src/evaluation.ee/test-runner/errors.ee.ts
  packages/cli/src/evaluation.ee/test-runner/evaluation-metrics.ee.ts
  packages/cli/src/evaluation.ee/test-runner/test-runner.service.ee.ts
  packages/cli/src/evaluation.ee/test-runner/utils.ee.ts
  packages/cli/src/evaluation.ee/test-runs.controller.ee.ts
  packages/editor-ui/src/api/testDefinition.ee.ts
  packages/editor-ui/src/components/TestDefinition/ListRuns/TestRunsTable.vue
  packages/editor-ui/src/components/TestDefinition/shared/TableCell.vue
  packages/editor-ui/src/components/TestDefinition/shared/TableStatusCell.vue
  packages/editor-ui/src/components/TestDefinition/shared/TestTableBase.vue
  packages/editor-ui/src/plugins/i18n/locales/en.json
  packages/editor-ui/src/views/TestDefinition/TestDefinitionRunDetailView.vue
Labels: core, ui, n8n team

#13195 refactor(core): Move more code out of NodeExecutionFunctions, and add additional tests (no-changelog)
  packages/core/src/__tests__/node-execute-functions.test.ts
  packages/core/src/execution-engine/node-execution-context/credentials-test-context.ts
  packages/core/src/execution-engine/node-execution-context/execute-context.ts
  packages/core/src/execution-engine/node-execution-context/execute-single-context.ts
  packages/core/src/execution-engine/node-execution-context/hook-context.ts
  packages/core/src/execution-engine/node-execution-context/index.ts
  packages/core/src/execution-engine/node-execution-context/load-options-context.ts
  packages/core/src/execution-engine/node-execution-context/poll-context.ts
  packages/core/src/execution-engine/node-execution-context/supply-data-context.ts
  packages/core/src/execution-engine/node-execution-context/trigger-context.ts
  packages/core/src/execution-engine/node-execution-context/utils/__tests__/construct-execution-metadata.test.ts
  packages/core/src/execution-engine/node-execution-context/utils/__tests__/copy-input-items.test.ts
  packages/core/src/execution-engine/node-execution-context/utils/__tests__/normalize-items.test.ts
  packages/core/src/execution-engine/node-execution-context/utils/__tests__/parse-request-object.test.ts
  packages/core/src/execution-engine/node-execution-context/utils/__tests__/request-helper-functions.test.ts
  packages/core/src/execution-engine/node-execution-context/utils/__tests__/return-json-array.test.ts
  packages/core/src/execution-engine/node-execution-context/utils/__tests__/scheduling-helper-functions.test.ts
  packages/core/src/execution-engine/node-execution-context/utils/__tests__/ssh-tunnel-helper-functions.test.ts
  packages/core/src/execution-engine/node-execution-context/utils/__tests__/webhook-helper-functions.test.ts
  packages/core/src/execution-engine/node-execution-context/utils/construct-execution-metadata.ts
  packages/core/src/execution-engine/node-execution-context/utils/copy-input-items.ts
  packages/core/src/execution-engine/node-execution-context/utils/get-input-connection-data.ts
  packages/core/src/execution-engine/node-execution-context/utils/normalize-items.ts
  packages/core/src/execution-engine/node-execution-context/utils/parse-request-object.ts
  packages/core/src/execution-engine/node-execution-context/utils/request-helper-functions.ts
  packages/core/src/execution-engine/node-execution-context/utils/return-json-array.ts
  packages/core/src/execution-engine/node-execution-context/utils/scheduling-helper-functions.ts
  packages/core/src/execution-engine/node-execution-context/utils/ssh-tunnel-helper-functions.ts
  packages/core/src/execution-engine/node-execution-context/utils/webhook-helper-functions.ts
  packages/core/src/execution-engine/node-execution-context/webhook-context.ts
  packages/core/src/node-execute-functions.ts
  packages/nodes-base/nodes/Google/Drive/test/v2/node/helpers.ts
Labels: core, n8n team

#13179 fix(editor): Correctly compare old parameter value for nested parameters
  packages/editor-ui/src/components/ParameterInput.vue
Labels: ui, n8n team

#12780 docs: Update description for Telegram label (no-changelog)
  packages/nodes-base/nodes/Telegram/Telegram.node.ts
Labels: node/improvement, n8n team

#13174 fix(Airtable Node): Use item at correct index in base/getSchema
  packages/nodes-base/nodes/Airtable/test/v2/node/base/getSchema.test.ts
  packages/nodes-base/nodes/Airtable/v2/actions/base/getSchema.operation.ts
  packages/nodes-base/nodes/Airtable/v2/actions/types.ts
Labels: node/improvement, n8n team

#13044 fix(Summarize Node): Not dealing with null values properly
  packages/nodes-base/nodes/Transform/Summarize/Summarize.node.ts
  packages/nodes-base/nodes/Transform/Summarize/test/workflow.summarize_countWithEmpty.json
  packages/nodes-base/nodes/Transform/Summarize/utils.ts
Labels: node/improvement, n8n team

#13180 fix(editor): Make connector buttons background opaque when dark mode is enabled system-wide
  packages/editor-ui/src/components/canvas/elements/edges/CanvasEdge.vue
  packages/editor-ui/src/components/canvas/elements/edges/CanvasEdgeToolbar.vue
Labels: ui, n8n team

#13199 fix(editor): Don't show 'Test workflow' button if the canvas is read-only
  packages/editor-ui/src/components/canvas/elements/nodes/CanvasNode.test.ts
  packages/editor-ui/src/components/canvas/elements/nodes/CanvasNode.vue
  packages/editor-ui/src/components/canvas/elements/nodes/render-types/parts/CanvasNodeTrigger.vue
Labels: ui, n8n team

#13200 fix(Microsoft OneDrive Node): Try to download file using downloadUrl
  packages/nodes-base/nodes/Microsoft/OneDrive/MicrosoftOneDrive.node.ts
  packages/nodes-base/nodes/Microsoft/OneDrive/test/node/file.download.test.ts
Labels: node/improvement, n8n team

#13219 fix(core): Handle missing `json` property on `nodeSuccessData`
  packages/core/src/execution-engine/workflow-execute.ts
Labels: core, n8n team

#13060 feat(core): Add migration to create model for folders feature
  packages/cli/src/databases/entities/folder.ts
  packages/cli/src/databases/entities/index.ts
  packages/cli/src/databases/entities/workflow-entity.ts
  packages/cli/src/databases/migrations/common/1738709609940-CreateFolderTable.ts
  packages/cli/src/databases/migrations/mysqldb/index.ts
  packages/cli/src/databases/migrations/postgresdb/index.ts
  packages/cli/src/databases/migrations/sqlite/1738709609940-CreateFolderTable.ts
  packages/cli/src/databases/migrations/sqlite/index.ts
  packages/cli/src/databases/repositories/folder.repository.ts
Labels: core, n8n team

#12663 feat: Add ConvertAPI cred only node
  packages/nodes-base/credentials/ConvertApi.credentials.ts
  packages/nodes-base/credentials/icons/ConvertApi.png
  packages/nodes-base/package.json
Labels: n8n team

#13185 feat(editor): Expose `View Execution` links for erroneous sub-executions
  packages/@n8n/nodes-langchain/nodes/chains/ChainRetrievalQA/ChainRetrievalQa.node.ts
  packages/@n8n/nodes-langchain/nodes/tools/ToolWorkflow/v2/utils/WorkflowToolService.ts
  packages/@n8n/nodes-langchain/utils/logWrapper.ts
  packages/cli/src/workflow-execute-additional-data.ts
  packages/editor-ui/src/components/RunData.test.ts
  packages/editor-ui/src/components/RunData.vue
  packages/nodes-base/nodes/ExecuteWorkflow/ExecuteWorkflow/ExecuteWorkflow.node.ts
  packages/workflow/src/MetadataUtils.ts
  packages/workflow/src/errors/node-api.error.ts
  packages/workflow/src/errors/node-operation.error.ts
  packages/workflow/src/index.ts
  packages/workflow/src/utils.ts
  packages/workflow/test/MetadataUtils.test.ts
  packages/workflow/test/utils.test.ts
Labels: node/improvement, core, ui, n8n team

#13225 refactor(core): Use IWorkflowBase over WorkflowEntity in most places
  packages/cli/src/__tests__/workflow-runner.test.ts
  packages/cli/src/active-workflow-manager.ts
  packages/cli/src/commands/execute-batch.ts
  packages/cli/src/commands/import/workflow.ts
  packages/cli/src/databases/entities/workflow-entity.ts
  packages/cli/src/databases/repositories/tag.repository.ts
  packages/cli/src/environments.ee/source-control/__tests__/source-control-export.service.test.ts
  packages/cli/src/environments.ee/source-control/source-control-export.service.ee.ts
  packages/cli/src/environments.ee/source-control/types/exportable-workflow.ts
  packages/cli/src/errors/workflow-missing-id.error.ts
  packages/cli/src/evaluation.ee/test-runner/test-runner.service.ee.ts
  packages/cli/src/evaluation.ee/test-runner/utils.ee.ts
  packages/cli/src/events/maps/pub-sub.event-map.ts
  packages/cli/src/executions/__tests__/constants.ts
  packages/cli/src/executions/execution.service.ts
  packages/cli/src/interfaces.ts
  packages/cli/src/public-api/v1/handlers/workflows/workflows.handler.ts
  packages/cli/src/public-api/v1/handlers/workflows/workflows.service.ts
  packages/cli/src/scaling/__tests__/pubsub-handler.test.ts
  packages/cli/src/security-audit/risk-reporters/credentials-risk-reporter.ts
  packages/cli/src/security-audit/risk-reporters/database-risk-reporter.ts
  packages/cli/src/security-audit/risk-reporters/filesystem-risk-reporter.ts
  packages/cli/src/security-audit/risk-reporters/instance-risk-reporter.ts
  packages/cli/src/security-audit/risk-reporters/nodes-risk-reporter.ts
  packages/cli/src/security-audit/types.ts
  packages/cli/src/security-audit/utils.ts
  packages/cli/src/services/import.service.ts
  packages/cli/src/user-management/email/user-management-mailer.ts
  packages/cli/src/webhooks/__tests__/test-webhooks.test.ts
  packages/cli/src/webhooks/test-webhook-registrations.service.ts
  packages/cli/src/webhooks/test-webhooks.ts
  packages/cli/src/webhooks/waiting-webhooks.ts
  packages/cli/src/webhooks/webhook-helpers.ts
  packages/cli/src/workflow-helpers.ts
  packages/cli/src/workflows/__tests__/workflow-execution.service.test.ts
  packages/cli/src/workflows/workflow-execution.service.ts
  packages/cli/src/workflows/workflow-history.ee/workflow-history.service.ee.ts
  packages/cli/src/workflows/workflow.formatter.ts
  packages/cli/src/workflows/workflow.request.ts
  packages/cli/src/workflows/workflow.service.ee.ts
  packages/cli/src/workflows/workflows.controller.ts
  packages/cli/test/integration/active-workflow-manager.test.ts
  packages/cli/test/integration/collaboration/collaboration.service.test.ts
  packages/cli/test/integration/evaluation/metrics.api.test.ts
  packages/cli/test/integration/evaluation/test-definitions.api.test.ts
  packages/cli/test/integration/evaluation/test-runs.api.test.ts
  packages/cli/test/integration/permission-checker.test.ts
  packages/cli/test/integration/pruning.service.test.ts
  packages/cli/test/integration/shared/db/executions.ts
  packages/cli/test/integration/shared/db/tags.ts
  packages/cli/test/integration/shared/db/workflows.ts
  packages/cli/test/integration/webhooks.api.test.ts
  packages/cli/test/integration/workflows/workflows.controller.test.ts
  packages/workflow/src/Interfaces.ts
Labels: core, n8n team

#13215 chore: Add new schemas (no-changelog)
  packages/nodes-base/nodes/Aws/Comprehend/__schema__/v1.0.0/text/detectSentiment.json
  packages/nodes-base/nodes/Aws/Rekognition/__schema__/v1.0.0/image/analyze.json
  packages/nodes-base/nodes/Aws/Transcribe/__schema__/v1.0.0/transcriptionJob/get.json
  packages/nodes-base/nodes/Bitwarden/__schema__/v1.0.0/member/getAll.json
  packages/nodes-base/nodes/Box/__schema__/v1.0.0/file/copy.json
  packages/nodes-base/nodes/Box/__schema__/v1.0.0/file/delete.json
  packages/nodes-base/nodes/Cisco/Webex/__schema__/v1.0.0/message/create.json
  packages/nodes-base/nodes/Clockify/__schema__/v1.0.0/project/get.json
  packages/nodes-base/nodes/ConvertKit/__schema__/v1.0.0/form/addSubscriber.json
  packages/nodes-base/nodes/Dropbox/__schema__/v1.0.0/file/copy.json
  packages/nodes-base/nodes/Google/Calendar/__schema__/v1.3.0/event/delete.json
  packages/nodes-base/nodes/Google/Chat/__schema__/v1.0.0/message/get.json
  packages/nodes-base/nodes/Google/CloudStorage/__schema__/v1.0.0/bucket/getAll.json
  packages/nodes-base/nodes/Google/Contacts/__schema__/v1.0.0/contact/get.json
  packages/nodes-base/nodes/Google/GSuiteAdmin/__schema__/v1.0.0/group/getAll.json
  packages/nodes-base/nodes/Google/YouTube/__schema__/v1.0.0/playlistItem/add.json
  packages/nodes-base/nodes/Google/YouTube/__schema__/v1.0.0/videoCategory/getAll.json
  packages/nodes-base/nodes/Keap/__schema__/v1.0.0/contact/getAll.json
  packages/nodes-base/nodes/Linear/__schema__/v1.0.0/issue/update.json
  packages/nodes-base/nodes/Microsoft/OneDrive/__schema__/v1.0.0/file/share.json
  packages/nodes-base/nodes/Microsoft/Outlook/__schema__/v2.0.0/contact/get.json
  packages/nodes-base/nodes/Microsoft/Outlook/__schema__/v2.0.0/message/sendAndWait.json
  packages/nodes-base/nodes/Microsoft/Teams/__schema__/v2.0.0/channel/get.json
  packages/nodes-base/nodes/Mindee/__schema__/v3.0.0/invoice/predict.json
  packages/nodes-base/nodes/N8nTrainingCustomerDatastore/__schema__/v1.0.0/credential/getSchema.json
  packages/nodes-base/nodes/Odoo/__schema__/v1.0.0/custom/delete.json
  packages/nodes-base/nodes/Oura/__schema__/v1.0.0/summary/getActivity.json
  packages/nodes-base/nodes/Oura/__schema__/v1.0.0/summary/getSleep.json
  packages/nodes-base/nodes/Pushbullet/__schema__/v1.0.0/push/create.json
  packages/nodes-base/nodes/Raindrop/__schema__/v1.0.0/collection/getAll.json
  packages/nodes-base/nodes/Slack/__schema__/v2.3.0/user/getPresence.json
  packages/nodes-base/nodes/Sms77/__schema__/v1.0.0/sms/send.json
  packages/nodes-base/nodes/Splunk/__schema__/v2.0.0/search/create.json
  packages/nodes-base/nodes/Twitter/__schema__/v2.0.0/tweet/like.json
  packages/nodes-base/nodes/Webflow/__schema__/v2.0.0/item/deleteItem.json
  packages/nodes-base/nodes/Wise/__schema__/v1.0.0/exchangeRate/get.json
  packages/nodes-base/nodes/Wordpress/__schema__/v1.0.0/post/update.json
  packages/nodes-base/nodes/Zendesk/__schema__/v1.0.0/organization/getAll.json
Labels: n8n team

#13189 refactor(core): Show deprecation warning if task runners are disabled
  packages/cli/src/deprecation/__tests__/deprecation.service.test.ts
  packages/cli/src/deprecation/deprecation.service.ts
Labels: core, n8n team

#13172 fix(editor): Add template id to metadata when saving workflows from json
  packages/editor-ui/src/composables/useCanvasOperations.test.ts
  packages/editor-ui/src/composables/useCanvasOperations.ts
  packages/editor-ui/src/views/NodeView.v2.vue
Labels: ui, n8n team

#13216 fix(editor): Propagate isReadOnly to ResourceMapper `Attempt to Convert Types` switch
  packages/editor-ui/src/components/ResourceMapper/ResourceMapper.vue
Labels: ui, n8n team

#13165 fix(AI Agent Node): Move model retrieval into try/catch to fix continueOnFail handling
  packages/@n8n/nodes-langchain/nodes/agents/Agent/agents/ToolsAgent/execute.ts
  packages/@n8n/nodes-langchain/nodes/agents/Agent/test/ToolsAgent.test.ts
  packages/@n8n/nodes-langchain/nodes/chains/ChainLLM/ChainLlm.node.ts
  packages/@n8n/nodes-langchain/nodes/chains/ChainRetrievalQA/ChainRetrievalQa.node.ts
  packages/@n8n/nodes-langchain/nodes/chains/ChainSummarization/V2/ChainSummarizationV2.node.ts
Labels: n8n team

#13186 fix(core): Reduce risk of race condition during workflow activation loop
  packages/cli/src/__tests__/active-workflow-manager.test.ts
  packages/cli/src/active-workflow-manager.ts
  packages/cli/src/databases/repositories/workflow.repository.ts
Labels: core, n8n team

#13251 fix: Display correct editor URL
  packages/cli/src/commands/start.ts
Labels: core, n8n team

#13194 fix(core): Run full manual execution when a trigger is executed even if run data exists
  packages/cli/src/workflows/__tests__/workflow-execution.service.test.ts
  packages/cli/src/workflows/workflow-execution.service.ts
  packages/cli/src/workflows/workflow.request.ts
Labels: core, n8n team

#13252 fix(editor): Render assignments without ID correctly
  packages/editor-ui/src/components/AssignmentCollection/AssignmentCollection.test.ts
  packages/editor-ui/src/components/AssignmentCollection/AssignmentCollection.vue
  packages/editor-ui/src/components/FilterConditions/FilterConditions.vue
Labels: ui, n8n team

#13263 fix(core): Redact credentials
  packages/cli/src/credentials/credentials.controller.ts
  packages/cli/src/credentials/credentials.service.ee.ts
  packages/cli/src/credentials/credentials.service.ts
  packages/cli/src/services/credentials-tester.service.ts
  packages/cli/test/integration/credentials/credentials.api.ee.test.ts
  packages/cli/test/integration/credentials/credentials.api.test.ts
  packages/cli/test/integration/shared/random.ts
Labels: core, n8n team

#13249 fix(editor): Open autocompletion when starting an expression
  packages/editor-ui/src/plugins/codemirror/expressionCloseBrackets.test.ts
  packages/editor-ui/src/plugins/codemirror/expressionCloseBrackets.ts
Labels: ui, n8n team

#13265 fix(editor): Fix page size resetting when filters are reset on workflows page
  packages/editor-ui/src/components/layouts/ResourcesListLayout.vue
Labels: ui, n8n team

#13245 fix(Code Tool Node): Fix Input Schema Parameter not hiding correctly
  packages/@n8n/nodes-langchain/nodes/tools/ToolCode/ToolCode.node.ts
  packages/@n8n/nodes-langchain/utils/descriptions.ts
Labels: n8n team

#13207 refactor(core): Update `workflowRepository.getMany` to use query builder (no-changelog)
  packages/cli/src/databases/repositories/workflow.repository.ts
  packages/cli/test/integration/shared/db/tags.ts
  packages/cli/test/integration/workflows/workflows.controller.test.ts
Labels: core, n8n team

#13318 fix(editor): Fix configurable node description margins and text alignment
  packages/editor-ui/src/components/canvas/elements/nodes/render-types/CanvasNodeDefault.vue
Labels: ui, n8n team

#13246 fix(editor): Do not show project settings for users without permission with direct link
  packages/editor-ui/src/routes/projects.routes.ts
Labels: ui, n8n team

#13264 fix(editor): Do not show credential details popup for users without necessary scopes with direct link
  packages/editor-ui/src/routes/projects.routes.ts
  packages/editor-ui/src/views/CredentialsView.test.ts
  packages/editor-ui/src/views/CredentialsView.vue
Labels: ui, n8n team

#11872 feat(editor): Change rename node keyboard shortcut to Space on new canvas
  packages/editor-ui/package.json
  packages/editor-ui/src/__tests__/data/canvas.ts
  packages/editor-ui/src/components/canvas/Canvas.test.ts
  packages/editor-ui/src/components/canvas/Canvas.vue
  packages/editor-ui/src/views/NodeView.v2.vue
  packages/frontend/@n8n/composables/package.json
  packages/frontend/@n8n/composables/src/useShortKeyPress.test.ts
  packages/frontend/@n8n/composables/src/useShortKeyPress.ts
  pnpm-lock.yaml
  pnpm-workspace.yaml
Labels: ui, n8n team

#13326 fix(core): Ensure that 'workflow-post-execute' event has userId whenever it's available
  packages/cli/src/execution-lifecycle/__tests__/execution-lifecycle-hooks.test.ts
  packages/cli/src/execution-lifecycle/execution-lifecycle-hooks.ts
  packages/cli/src/scaling/job-processor.ts
  packages/cli/src/workflow-runner.ts
Labels: core, n8n team

#13211 fix: Build on windows with cross-platform path compatibility (no-changelog)
  packages/editor-ui/vite.config.mts
Labels: ui, community, in linear

#13261 fix(core): Fix DB migrations for MySQL
  .github/docker-compose.yml
  .github/workflows/ci-postgres-mysql.yml
  packages/cli/package.json
  packages/cli/src/databases/migrations/mysqldb/1731582748663-MigrateTestDefinitionKeyToString.ts
  packages/cli/src/databases/migrations/mysqldb/1732271325258-CreateTestMetricTable.ts
  packages/cli/src/databases/migrations/mysqldb/1736172058779-AddStatsColumnsToTestRun.ts
  packages/cli/src/databases/migrations/mysqldb/1739873751194-FixTestDefinitionPrimaryKey.ts
  packages/cli/src/databases/migrations/mysqldb/index.ts
Labels: core, n8n team

#13303 refactor(core): Prepare `workflowService.geyMany` for union
  packages/cli/src/workflows/workflow.service.ts
Labels: core, n8n team

#13347 fix(core): Avoid renewing the license on init to prevent excessive duplicate renewal calls
  packages/cli/package.json
  pnpm-lock.yaml
Labels: core, n8n team

#13346 refactor(core): Remove unused betaFeatures and FrontendConfig (no-changelog)
  packages/@n8n/api-types/src/frontend-settings.ts
  packages/@n8n/config/src/configs/frontend.config.ts
  packages/@n8n/config/src/index.ts
  packages/cli/src/services/frontend.service.ts
  packages/editor-ui/src/__tests__/defaults.ts
Labels: core, ui, n8n team

#13255 test(Email Trigger (IMAP) Node): Improve email imap testing
  packages/nodes-base/nodes/EmailReadImap/test/v2/EmailReadImapV2.node.test.ts
  packages/nodes-base/nodes/EmailReadImap/test/v2/utils.test.ts
  packages/nodes-base/nodes/EmailReadImap/v2/EmailReadImapV2.node.ts
  packages/nodes-base/nodes/EmailReadImap/v2/utils.ts
Labels: node/improvement, n8n team

#13343 refactor(editor): Remove old canvas code (no-changelog)
  packages/@n8n/api-types/src/frontend-settings.ts
  packages/@n8n/config/src/configs/frontend.config.ts
  packages/@n8n/config/src/index.ts
  packages/cli/src/services/frontend.service.ts
  packages/editor-ui/package.json
  packages/editor-ui/src/App.vue
  packages/editor-ui/src/Interface.ts
  packages/editor-ui/src/__tests__/defaults.ts
  packages/editor-ui/src/__tests__/mocks.ts
  packages/editor-ui/src/components/CanvasControls.vue
  packages/editor-ui/src/components/Node.vue
  packages/editor-ui/src/components/Sticky.vue
  packages/editor-ui/src/components/executions/workflow/WorkflowExecutionsList.vue
  packages/editor-ui/src/composables/useCanvasMouseSelect.ts
  packages/editor-ui/src/composables/useCanvasPanning.test.ts
  packages/editor-ui/src/composables/useCanvasPanning.ts
  packages/editor-ui/src/composables/useHistoryHelper.ts
  packages/editor-ui/src/composables/useNodeBase.test.ts
  packages/editor-ui/src/composables/useNodeBase.ts
  packages/editor-ui/src/composables/useNodeHelpers.ts
  packages/editor-ui/src/composables/useNodeViewVersionSwitcher.test.ts
  packages/editor-ui/src/composables/useNodeViewVersionSwitcher.ts
  packages/editor-ui/src/main.ts
  packages/editor-ui/src/plugins/connectors/N8nCustomConnector.ts
  packages/editor-ui/src/plugins/jsplumb/N8nAddInputEndpointRenderer.ts
  packages/editor-ui/src/plugins/jsplumb/N8nAddInputEndpointType.ts
  packages/editor-ui/src/plugins/jsplumb/N8nPlusEndpointRenderer.ts
  packages/editor-ui/src/plugins/jsplumb/N8nPlusEndpointType.ts
  packages/editor-ui/src/plugins/jsplumb/index.ts
  packages/editor-ui/src/router.ts
  packages/editor-ui/src/shims-jsplumb.d.ts
  packages/editor-ui/src/stores/canvas.store.ts
  packages/editor-ui/src/stores/settings.store.ts
  packages/editor-ui/src/utils/canvasUtils.ts
  packages/editor-ui/src/utils/nodeViewUtils.ts
  packages/editor-ui/src/utils/typeGuards.ts
  packages/editor-ui/src/views/NodeView.v2.vue
  packages/editor-ui/src/views/NodeView.vue
  packages/editor-ui/src/views/NodeViewSwitcher.vue
  packages/editor-ui/src/views/WorkflowExecutionsView.vue
  pnpm-lock.yaml
Labels: ui, n8n team

#13314 fix(editor): Disable fromAI override button for credentialsSelect (no-changelog)
  packages/editor-ui/src/utils/fromAIOverrideUtils.test.ts
  packages/editor-ui/src/utils/fromAIOverrideUtils.ts
Labels: ui, n8n team

#13160 feat(n8n Form Node): Limit wait time parameters
  packages/nodes-base/nodes/Discord/v2/actions/router.ts
  packages/nodes-base/nodes/EmailSend/v2/sendAndWait.operation.ts
  packages/nodes-base/nodes/Form/Form.node.ts
  packages/nodes-base/nodes/Form/test/Form.node.test.ts
  packages/nodes-base/nodes/Google/Chat/GoogleChat.node.ts
  packages/nodes-base/nodes/Google/Gmail/v2/GmailV2.node.ts
  packages/nodes-base/nodes/Microsoft/Outlook/v2/actions/router.ts
  packages/nodes-base/nodes/Microsoft/Teams/v2/actions/router.ts
  packages/nodes-base/nodes/Slack/V2/SlackV2.node.ts
  packages/nodes-base/nodes/Telegram/Telegram.node.ts
  packages/nodes-base/nodes/Wait/Wait.node.ts
  packages/nodes-base/utils/sendAndWait/configureWaitTillDate.util.ts
  packages/nodes-base/utils/sendAndWait/descriptions.ts
  packages/nodes-base/utils/sendAndWait/test/util.test.ts
  packages/nodes-base/utils/sendAndWait/utils.ts
Labels: node/improvement, n8n team, node/issue

#13327 refactor(core): Extract more code out in `WorkflowExecute` and add unit tests
  packages/core/src/execution-engine/__tests__/workflow-execute.test.ts
  packages/core/src/execution-engine/workflow-execute.ts
Labels: core, n8n team

#13104 fix(n8n Form Node): Redirection update (no-changelog)
  .prettierignore
  packages/cli/src/active-executions.ts
  packages/cli/src/webhooks/__tests__/webhook-helpers.test.ts
  packages/cli/src/webhooks/waiting-forms.ts
  packages/cli/src/webhooks/webhook-helpers.ts
  packages/cli/src/workflow-runner.ts
  packages/cli/templates/form-trigger-completion.handlebars
  packages/cli/templates/form-trigger.handlebars
  packages/nodes-base/nodes/Form/Form.node.ts
  packages/nodes-base/nodes/Form/formCompletionUtils.ts
  packages/nodes-base/nodes/Form/formNodeUtils.ts
  packages/nodes-base/nodes/Form/test/Form.node.test.ts
  packages/nodes-base/nodes/Form/utils.ts
  packages/nodes-base/nodes/Wait/Wait.node.ts
  packages/workflow/src/Interfaces.ts
Labels: n8n team, node/issue, release/backport

#13363 fix: Always clear popupWindowState before showing popup from form trigger
  packages/editor-ui/src/utils/executionUtils.ts
Labels: ui, n8n team, release/backport, tests-needed

#13365 fix(core): Return original hooks errors to the frontend
  packages/cli/src/__tests__/external-hooks.test.ts
  packages/cli/src/external-hooks.ts
Labels: core, n8n team

#13317 feat(editor): Implement breadcrumbs component
  packages/design-system/src/components/N8nActionToggle/ActionToggle.vue
  packages/design-system/src/components/N8nBreadcrumbs/AsyncLoadingCacheDemo.vue
  packages/design-system/src/components/N8nBreadcrumbs/BreadCrumbs.test.ts
  packages/design-system/src/components/N8nBreadcrumbs/Breadcrumbs.stories.ts
  packages/design-system/src/components/N8nBreadcrumbs/Breadcrumbs.vue
  packages/design-system/src/components/N8nBreadcrumbs/__snapshots__/BreadCrumbs.test.ts.snap
  packages/design-system/src/components/N8nBreadcrumbs/index.ts
  packages/design-system/src/components/index.ts
Labels: ui, n8n team

#13338 fix(editor): Correctly close node creator when selecting/deselecting a node
  packages/editor-ui/src/components/canvas/Canvas.vue
  packages/editor-ui/src/components/canvas/elements/handles/render-types/parts/CanvasHandlePlus.vue
  packages/editor-ui/src/components/canvas/elements/nodes/render-types/CanvasNodeAddNodes.vue
  packages/editor-ui/src/views/NodeView.v2.vue
Labels: ui, n8n team

#13351 chore: Bump license-sdk to v2.16.1 (no-changelog)
  packages/cli/package.json
  packages/cli/src/license.ts
  pnpm-lock.yaml
Labels: core, n8n team

#13306 refactor: Add dto for `POST /credentials` endpoint
  packages/@n8n/api-types/src/dto/credentials/__tests__/create-credential.dto.test.ts
  packages/@n8n/api-types/src/dto/credentials/create-credential.dto.ts
  packages/@n8n/api-types/src/dto/index.ts
  packages/cli/src/controllers/ai.controller.ts
  packages/cli/src/credentials-helper.ts
  packages/cli/src/credentials/__tests__/credentials.controller.test.ts
  packages/cli/src/credentials/__tests__/credentials.service.test.ts
  packages/cli/src/credentials/__tests__/credentials.test-data.ts
  packages/cli/src/credentials/credentials.controller.ts
  packages/cli/src/credentials/credentials.service.ts
  packages/cli/src/requests.ts
  packages/cli/test/integration/credentials/credentials.api.test.ts
  packages/cli/test/integration/shared/db/credentials.ts
  packages/editor-ui/src/api/credentials.ts
  packages/editor-ui/src/stores/credentials.store.ts
Labels: core, ui, n8n team

#13362 fix(core): Handle connections for missing nodes in a workflow
  packages/workflow/src/Workflow.ts
  packages/workflow/test/Workflow.test.ts
Labels: core, n8n team, release/backport

#13374 feat: Add temporary env variable `N8N_FOLDERS_ENABLED` (no-changelog)
  packages/@n8n/api-types/src/frontend-settings.ts
  packages/cli/src/config/schema.ts
  packages/cli/src/services/frontend.service.ts
  packages/editor-ui/src/__tests__/defaults.ts
  packages/editor-ui/src/stores/settings.store.ts
Labels: core, ui, n8n team

#13323 chore(core): Stop reporting errors to Sentry for older releases (no-changelog)
  .github/workflows/release-publish.yml
  docker/images/n8n/Dockerfile
  packages/@n8n/config/src/configs/generic.config.ts
  packages/@n8n/config/src/decorators.ts
  packages/@n8n/config/test/config.test.ts
  packages/cli/src/commands/base-command.ts
  packages/core/src/errors/error-reporter.ts
Labels: core, n8n team

#13237 feat(core): Hackmation - Add last activity metric
  packages/cli/src/metrics/__tests__/prometheus-metrics.service.test.ts
  packages/cli/src/metrics/prometheus-metrics.service.ts
Labels: core, n8n team

#13367 feat(core): Add telemetry for workflow evaluation feature (no-changelog)
  packages/cli/src/evaluation.ee/metrics.controller.ts
  packages/cli/src/evaluation.ee/test-definition.service.ee.ts
  packages/cli/src/evaluation.ee/test-runner/test-runner.service.ee.ts
  packages/cli/src/evaluation.ee/test-runs.controller.ee.ts
  packages/editor-ui/src/components/TestDefinition/EditDefinition/NodesPinning.vue
  packages/editor-ui/src/components/TestDefinition/EditDefinition/WorkflowSelector.vue
  packages/editor-ui/src/components/TestDefinition/EditDefinition/sections/ConfigSection.vue
  packages/editor-ui/src/components/WorkflowSelectorParameterInput/WorkflowSelectorParameterInput.vue
  packages/editor-ui/src/components/executions/workflow/WorkflowExecutionAnnotationPanel.ee.vue
  packages/editor-ui/src/views/TestDefinition/TestDefinitionEditView.vue
Labels: core, ui, n8n team

#13390 fix(core): Make sure middleware works with legacy API Keys
  packages/cli/src/services/__tests__/public-api-key.service.test.ts
  packages/cli/src/services/public-api-key.service.ts
  packages/cli/test/integration/shared/db/users.ts
Labels: core, n8n team, release/backport

#13396 fix(editor): Fix workflow moving E2E tests
  cypress/e2e/39-projects.cy.ts
  cypress/pages/notifications.ts
Labels: n8n team

#13344 feat: Enable partial exections v2 by default
  cypress/e2e/19-execution.cy.ts
  cypress/e2e/40-manual-partial-execution.cy.ts
  packages/@n8n/api-types/src/frontend-settings.ts
  packages/@n8n/config/src/configs/partial-executions.config.ts
  packages/@n8n/config/test/config.test.ts
  packages/cli/src/deprecation/__tests__/deprecation.service.test.ts
  packages/cli/src/deprecation/deprecation.service.ts
  packages/editor-ui/src/__tests__/defaults.ts
  packages/editor-ui/src/stores/settings.store.test.ts
  packages/editor-ui/src/stores/settings.store.ts
  packages/editor-ui/src/stores/workflows.store.test.ts
Labels: n8n team

#12524 fix(editor): Optionally share credentials used by the workflow when moving the workflow between projects
  packages/@n8n/api-types/src/dto/index.ts
  packages/@n8n/api-types/src/dto/workflows/__tests__/transfer-workflow.dto.test.ts
  packages/@n8n/api-types/src/dto/workflows/transfer.dto.ts
  packages/cli/src/credentials/credentials.controller.ts
  packages/cli/src/credentials/credentials.service.ee.ts
  packages/cli/src/databases/repositories/shared-credentials.repository.ts
  packages/cli/src/workflows/workflow.request.ts
  packages/cli/src/workflows/workflow.service.ee.ts
  packages/cli/src/workflows/workflows.controller.ts
  packages/cli/test/integration/credentials/credentials.api.ee.test.ts
  packages/cli/test/integration/workflows/workflow.service.ee.test.ts
  packages/cli/test/integration/workflows/workflows.controller.ee.test.ts
  packages/cli/test/integration/workflows/workflows.controller.test.ts
  packages/design-system/src/css/notification.scss
  packages/editor-ui/src/api/workflows.ee.ts
  packages/editor-ui/src/components/Projects/ProjectMoveResourceModal.test.ts
  packages/editor-ui/src/components/Projects/ProjectMoveResourceModal.vue
  packages/editor-ui/src/components/Projects/ProjectMoveResourceModalCredentialsList.vue
  packages/editor-ui/src/components/Projects/ProjectMoveSuccessToastMessage.test.ts
  packages/editor-ui/src/components/Projects/ProjectMoveSuccessToastMessage.vue
  packages/editor-ui/src/plugins/i18n/locales/en.json
  packages/editor-ui/src/stores/projects.store.ts
Labels: ui, n8n team

#13383 feat(editor): Evaluation feature Phase one readiness (no-changelog)
  cypress/pages/ndv.ts
  packages/design-system/src/components/N8nActionToggle/ActionToggle.vue
  packages/design-system/src/components/N8nTag/Tag.vue
  packages/design-system/src/components/N8nText/Text.vue
  packages/design-system/src/types/text.ts
  packages/editor-ui/src/api/testDefinition.ee.ts
  packages/editor-ui/src/components/InlineNameEdit.vue
  packages/editor-ui/src/components/MainHeader/MainHeader.vue
  packages/editor-ui/src/components/Projects/ProjectCreateResource.vue
  packages/editor-ui/src/components/ResourceLocator/ResourceLocatorDropdown.vue
  packages/editor-ui/src/components/TestDefinition/EditDefinition/BlockArrow.vue
  packages/editor-ui/src/components/TestDefinition/EditDefinition/EvaluationStep.vue
  packages/editor-ui/src/components/TestDefinition/EditDefinition/MetricsInput.vue
  packages/editor-ui/src/components/TestDefinition/EditDefinition/NodesPinning.vue
  packages/editor-ui/src/components/TestDefinition/EditDefinition/WorkflowSelector.vue
  packages/editor-ui/src/components/TestDefinition/EditDefinition/sections/ConfigSection.vue
  packages/editor-ui/src/components/TestDefinition/EditDefinition/sections/HeaderSection.vue
  packages/editor-ui/src/components/TestDefinition/EditDefinition/sections/RunsSection.vue
  packages/editor-ui/src/components/TestDefinition/ListDefinition/EmptyState.vue
  packages/editor-ui/src/components/TestDefinition/ListDefinition/TestItem.vue
  packages/editor-ui/src/components/TestDefinition/ListDefinition/TestsList.vue
  packages/editor-ui/src/components/TestDefinition/ListRuns/MetricsChart.vue
  packages/editor-ui/src/components/TestDefinition/ListRuns/TestRunsTable.vue
  packages/editor-ui/src/components/TestDefinition/composables/useTestDefinitionForm.ts
  packages/editor-ui/src/components/TestDefinition/shared/TestTableBase.vue
  packages/editor-ui/src/components/TestDefinition/tests/MetricsInput.test.ts
  packages/editor-ui/src/components/TestDefinition/tests/useTestDefinitionForm.test.ts
  packages/editor-ui/src/components/TestDefinition/types.ts
  packages/editor-ui/src/components/WorkflowSelectorParameterInput/WorkflowSelectorParameterInput.vue
  packages/editor-ui/src/components/executions/workflow/WorkflowExecutionsCard.vue
  packages/editor-ui/src/components/executions/workflow/WorkflowExecutionsList.vue
  packages/editor-ui/src/components/executions/workflow/WorkflowExecutionsPreview.test.ts
  packages/editor-ui/src/components/executions/workflow/WorkflowExecutionsPreview.vue
  packages/editor-ui/src/constants.ts
  packages/editor-ui/src/constants.workflows.ts
  packages/editor-ui/src/plugins/i18n/locales/en.json
  packages/editor-ui/src/plugins/icons/index.ts
  packages/editor-ui/src/router.ts
  packages/editor-ui/src/stores/tags.store.ts
  packages/editor-ui/src/stores/testDefinition.store.ee.test.ts
  packages/editor-ui/src/stores/testDefinition.store.ee.ts
  packages/editor-ui/src/views/TestDefinition/TestDefinitionEditView.vue
  packages/editor-ui/src/views/TestDefinition/TestDefinitionListView.vue
  packages/editor-ui/src/views/TestDefinition/TestDefinitionNewView.vue
  packages/editor-ui/src/views/TestDefinition/TestDefinitionRootView.vue
  packages/editor-ui/src/views/TestDefinition/TestDefinitionRunDetailView.vue
  packages/editor-ui/src/views/TestDefinition/TestDefinitionRunsListView.vue
  packages/editor-ui/src/views/TestDefinition/tests/TestDefinitionEditView.test.ts
  packages/editor-ui/src/views/TestDefinition/tests/TestDefinitionListView.test.ts
  packages/editor-ui/src/views/TestDefinition/tests/TestDefinitionRootView.test.ts
  packages/editor-ui/src/views/TestDefinition/tests/TestDefinitionRunDetailView.test.ts
  packages/editor-ui/src/views/WorkflowExecutionsView.vue
Labels: ui, n8n team

#13341 fix(editor): Switch back to selection mode on window blur
  packages/editor-ui/src/components/canvas/Canvas.vue
Labels: ui, n8n team

#13421 refactor: Rename NodeView.v2 to NodeView (no-changelog)
  packages/editor-ui/src/router.ts
  packages/editor-ui/src/views/NodeView.vue
Labels: ui, n8n team

#13419 fix(editor): Register/unregister keybindings on window focus/blur
  packages/editor-ui/src/composables/useKeybindings.test.ts
  packages/editor-ui/src/composables/useKeybindings.ts
Labels: ui, n8n team

#13416 feat(editor): Rename 'Text' fields on AI nodes to 'Prompt'
  packages/@n8n/nodes-langchain/nodes/chains/ChainLLM/ChainLlm.node.ts
  packages/@n8n/nodes-langchain/nodes/chains/ChainRetrievalQA/ChainRetrievalQa.node.ts
  packages/@n8n/nodes-langchain/nodes/vendors/OpenAi/actions/assistant/message.operation.ts
  packages/@n8n/nodes-langchain/nodes/vendors/OpenAi/actions/text/message.operation.ts
  packages/@n8n/nodes-langchain/utils/descriptions.ts
Labels: n8n team

#13410 fix(core): Fix resuming executions on test webhooks from Wait forms
  packages/cli/src/webhooks/__tests__/waiting-forms.test.ts
  packages/cli/src/webhooks/waiting-forms.ts
Labels: core, n8n team, release/backport

#13427 fix(editor): Fix workflow moving e2e test (no-changelog)
  cypress/e2e/39-projects.cy.ts
Labels: n8n team

#13352 feat(core): Introduce new query string parameter `includeFolders` to GET `/workflows` endpoint (no-changelog)
  packages/cli/src/databases/entities/folder.ts
  packages/cli/src/databases/repositories/__tests__/folder.repository.test.ts
  packages/cli/src/databases/repositories/folder.repository.ts
  packages/cli/src/databases/repositories/workflow.repository.ts
  packages/cli/src/middlewares/list-query/dtos/workflow.filter.dto.ts
  packages/cli/src/middlewares/list-query/dtos/workflow.select.dto.ts
  packages/cli/src/requests.ts
  packages/cli/src/workflows/workflow.request.ts
  packages/cli/src/workflows/workflow.service.ts
  packages/cli/src/workflows/workflows.controller.ts
  packages/cli/test/integration/shared/db/folders.ts
  packages/cli/test/integration/workflows/workflows.controller.test.ts
Labels: core, n8n team

#13429 fix: Manually reverted PR 11716 Do not assign all paired items (no-changelog)
  packages/nodes-base/nodes/Airtable/test/v2/node/base/getMany.test.ts
  packages/nodes-base/nodes/Airtable/test/v2/node/record/search.test.ts
  packages/nodes-base/nodes/Airtable/v1/AirtableV1.node.ts
  packages/nodes-base/nodes/Airtable/v2/actions/base/getMany.operation.ts
  packages/nodes-base/nodes/Airtable/v2/actions/record/search.operation.ts
  packages/nodes-base/nodes/ExecuteWorkflow/ExecuteWorkflow/ExecuteWorkflow.node.ts
  packages/nodes-base/nodes/Files/ConvertToFile/actions/spreadsheet.operation.ts
  packages/nodes-base/nodes/Files/ConvertToFile/actions/toJson.operation.ts
  packages/nodes-base/nodes/Ftp/Ftp.node.ts
  packages/nodes-base/nodes/Google/BigQuery/v1/GoogleBigQueryV1.node.ts
  packages/nodes-base/nodes/Google/BigQuery/v2/actions/database/insert.operation.ts
  packages/nodes-base/nodes/Google/Firebase/CloudFirestore/GoogleFirebaseCloudFirestore.node.ts
  packages/nodes-base/nodes/Google/Sheet/test/v2/node/delete.test.ts
  packages/nodes-base/nodes/Google/Sheet/v1/GoogleSheetsV1.node.ts
  packages/nodes-base/nodes/Google/Sheet/v2/actions/sheet/delete.operation.ts
  packages/nodes-base/nodes/Hubspot/V2/HubspotV2.node.ts
  packages/nodes-base/nodes/Kafka/Kafka.node.ts
  packages/nodes-base/nodes/Microsoft/Excel/v1/MicrosoftExcelV1.node.ts
  packages/nodes-base/nodes/Microsoft/Excel/v2/actions/table/append.operation.ts
  packages/nodes-base/nodes/Microsoft/Excel/v2/actions/worksheet/update.operation.ts
  packages/nodes-base/nodes/Microsoft/Excel/v2/actions/worksheet/upsert.operation.ts
  packages/nodes-base/nodes/Microsoft/Excel/v2/helpers/utils.ts
  packages/nodes-base/nodes/Microsoft/Sql/MicrosoftSql.node.ts
  packages/nodes-base/nodes/MongoDb/MongoDb.node.ts
  packages/nodes-base/nodes/Postgres/test/v2/runQueries.test.ts
  packages/nodes-base/nodes/Postgres/v2/helpers/utils.ts
  packages/nodes-base/nodes/QuickBase/QuickBase.node.ts
  packages/nodes-base/nodes/ReadBinaryFiles/ReadBinaryFiles.node.ts
  packages/nodes-base/nodes/RespondToWebhook/RespondToWebhook.node.ts
  packages/nodes-base/nodes/RespondToWebhook/test/RespondToWebhook.test.ts
  packages/nodes-base/nodes/RssFeedRead/RssFeedRead.node.ts
  packages/nodes-base/nodes/SpreadsheetFile/v1/SpreadsheetFileV1.node.ts
  packages/nodes-base/nodes/SpreadsheetFile/v2/toFile.operation.ts
  packages/nodes-base/nodes/Stackby/Stackby.node.ts
Labels: node/improvement, n8n team, release/backport

#13423 refactor: Document and rename canvasUtils (no-changelog)
  packages/editor-ui/src/components/canvas/elements/edges/CanvasConnectionLine.vue
  packages/editor-ui/src/components/canvas/elements/nodes/CanvasNode.vue
  packages/editor-ui/src/composables/useCanvasMapping.test.ts
  packages/editor-ui/src/composables/useCanvasMapping.ts
  packages/editor-ui/src/composables/useCanvasOperations.test.ts
  packages/editor-ui/src/composables/useCanvasOperations.ts
  packages/editor-ui/src/composables/useNodeConnections.test.ts
  packages/editor-ui/src/composables/useNodeConnections.ts
  packages/editor-ui/src/stores/nodeCreator.store.test.ts
  packages/editor-ui/src/stores/nodeCreator.store.ts
  packages/editor-ui/src/stores/templates.store.ts
  packages/editor-ui/src/utils/canvasUtils.test.ts
  packages/editor-ui/src/utils/canvasUtils.ts
  packages/editor-ui/src/utils/nodeViewUtils.ts
  packages/editor-ui/src/utils/templates/templateActions.ts
  packages/editor-ui/src/views/NodeView.vue
Labels: ui, n8n team

#13411 chore(editor): Clean up feature flag for trigger button variant
  packages/editor-ui/src/components/canvas/elements/nodes/render-types/CanvasNodeDefault.vue
  packages/editor-ui/src/components/canvas/elements/nodes/render-types/__snapshots__/CanvasNodeDefault.test.ts.snap
  packages/editor-ui/src/components/canvas/elements/nodes/render-types/parts/CanvasNodeTrigger.vue
  packages/editor-ui/src/constants.ts
Labels: ui, n8n team

#13348 fix: Prevent flicker during paginated workflow navigation
  packages/editor-ui/src/components/layouts/ResourcesListLayout.vue
  packages/editor-ui/src/views/WorkflowsView.vue
Labels: ui, n8n team

#13370 feat(editor): Implement folder navigation in workflows list
  packages/@n8n/permissions/src/constants.ee.ts
  packages/design-system/src/components/N8nBreadcrumbs/Breadcrumbs.vue
  packages/editor-ui/src/Interface.ts
  packages/editor-ui/src/api/workflows.ts
  packages/editor-ui/src/components/CredentialCard.test.ts
  packages/editor-ui/src/components/CredentialCard.vue
  packages/editor-ui/src/components/Folders/FolderCard.test.ts
  packages/editor-ui/src/components/Folders/FolderCard.vue
  packages/editor-ui/src/components/Folders/constants.ts
  packages/editor-ui/src/components/Projects/ProjectCardBadge.vue
  packages/editor-ui/src/components/Projects/ProjectIcon.vue
  packages/editor-ui/src/components/Projects/ProjectTabs.vue
  packages/editor-ui/src/components/WorkflowCard.vue
  packages/editor-ui/src/components/forms/ResourceFiltersDropdown.vue
  packages/editor-ui/src/components/layouts/ResourcesListLayout.vue
  packages/editor-ui/src/constants.ts
  packages/editor-ui/src/permissions.test.ts
  packages/editor-ui/src/plugins/i18n/locales/en.json
  packages/editor-ui/src/plugins/icons/index.ts
  packages/editor-ui/src/routes/projects.routes.ts
  packages/editor-ui/src/stores/rbac.store.ts
  packages/editor-ui/src/stores/workflows.store.ts
  packages/editor-ui/src/utils/typeGuards.ts
  packages/editor-ui/src/views/CredentialsView.vue
  packages/editor-ui/src/views/VariablesView.vue
  packages/editor-ui/src/views/WorkflowsView.test.ts
  packages/editor-ui/src/views/WorkflowsView.vue
Labels: ui, n8n team

#13467 fix(editor): Ai 675 minor tweaks to tests list
  packages/editor-ui/src/components/TestDefinition/ListDefinition/TestItem.vue
  packages/editor-ui/src/views/TestDefinition/TestDefinitionListView.vue
Labels: ui, n8n team

#13461 fix(editor): Ai 672 minor UI fixes on evaluation creation
  packages/design-system/src/components/N8nInfoTip/InfoTip.vue
  packages/editor-ui/src/components/TestDefinition/EditDefinition/BlockArrow.vue
  packages/editor-ui/src/components/TestDefinition/EditDefinition/EvaluationStep.vue
  packages/editor-ui/src/components/TestDefinition/EditDefinition/MetricsInput.vue
  packages/editor-ui/src/components/TestDefinition/EditDefinition/sections/ConfigSection.vue
  packages/editor-ui/src/components/TestDefinition/ListDefinition/TestItem.vue
  packages/editor-ui/src/components/TestDefinition/tests/MetricsInput.test.ts
  packages/editor-ui/src/plugins/i18n/locales/en.json
  packages/editor-ui/src/views/TestDefinition/TestDefinitionEditView.vue
  packages/editor-ui/src/views/TestDefinition/TestDefinitionListView.vue
  packages/editor-ui/src/views/TestDefinition/tests/TestDefinitionListView.test.ts
Labels: ui, n8n team

#13448 feat(core): Add endpoint GET `/projects/:projectId/folders/:folderId/tree` (no-changelog)
  packages/cli/src/controllers/folder.controller.ts
  packages/cli/src/permissions.ee/project-roles.ts
  packages/cli/src/services/folder.service.ts
  packages/cli/test/integration/folder/folder.controller.test.ts
Labels: core, n8n team

#13336 feat(core): Add tables for reporting dashboard (no-changelog)
  packages/cli/src/databases/dsl/column.ts
  packages/cli/src/databases/migrations/common/1739549398681-CreateAnalyticsTables.ts
  packages/cli/src/databases/migrations/mysqldb/index.ts
  packages/cli/src/databases/migrations/postgresdb/index.ts
  packages/cli/src/databases/migrations/sqlite/index.ts
Labels: core, n8n team

#13213 feat: Hackmation - automatically switch to expression mode
  packages/editor-ui/src/components/AssignmentCollection/AssignmentCollection.vue
  packages/editor-ui/src/components/FilterConditions/Condition.vue
  packages/editor-ui/src/components/FilterConditions/FilterConditions.vue
  packages/editor-ui/src/components/ParameterInput.vue
  packages/editor-ui/src/utils/expressions.test.ts
  packages/editor-ui/src/utils/expressions.ts
Labels: ui, n8n team
